export const ab = [
  { nume: "Abrud-Sat", comuna: "Abrud" },
  { nume: "Abrud" },
  { nume: "Achimețești", simplu: "Achimetesti", comuna: "Avram Iancu" },
  { nume: "Acmariu", comuna: "Blandiana" },
  { nume: "Aiud" },
  { nume: "Aiudul de Sus", comuna: "Aiud" },
  { nume: "Alba Iulia" },
  { nume: "Albac" },
  { nume: "Alecuș", simplu: "Alecus", comuna: "Sona" },
  {
    nume: "Almașu de Mijloc",
    simplu: "Almasu de Mijloc",
    comuna: "Almasu Mare",
  },
  { nume: "Almașu Mare", simplu: "Almasu Mare" },
  { nume: "Ampoița", simplu: "Ampoita", comuna: "Metes" },
  { nume: "Anghelești", simplu: "Anghelesti", comuna: "Bucium" },
  { nume: "Arieșeni", simplu: "Arieseni" },
  { nume: "Aronești", simplu: "Aronesti", comuna: "Bistra" },
  { nume: "Arți", simplu: "Arti", comuna: "Sugag" },
  { nume: "Asinip", comuna: "Lopadea Noua" },
  { nume: "Avram Iancu" },
  { nume: "Avrămești", simplu: "Avramesti", comuna: "Arieseni" },
  { nume: "Avrămești", simplu: "Avramesti", comuna: "Avram Iancu" },
  { nume: "Baba", comuna: "Horea" },
  { nume: "Băcăinți", simplu: "Bacainti", comuna: "Sibot" },
  { nume: "Bădăi", simplu: "Badai", comuna: "Avram Iancu" },
  { nume: "Băgău", simplu: "Bagau", comuna: "Lopadea Noua" },
  { nume: "Băi", simplu: "Bai", comuna: "Vidra" },
  { nume: "Baia de Arieș", simplu: "Baia de Aries" },
  { nume: "Bălcaciu", simplu: "Balcaciu", comuna: "Jidvei" },
  { nume: "Bălești-Cătun", simplu: "Balesti-Catun", comuna: "Bistra" },
  { nume: "Bălești", simplu: "Balesti", comuna: "Bistra" },
  { nume: "Bălmoșești", simplu: "Balmosesti", comuna: "Rosia Montana" },
  { nume: "Balomiru de Câmp", simplu: "Balomiru de Camp", comuna: "Sibot" },
  { nume: "Bărăbanț", simplu: "Barabant", comuna: "Alba Iulia" },
  { nume: "Bărăști", simplu: "Barasti", comuna: "Albac" },
  { nume: "Bărbești", simplu: "Barbesti", comuna: "Mogos" },
  { nume: "Bârdești", simplu: "Bardesti", comuna: "Lupsa" },
  { nume: "Bârlești-Cătun", simplu: "Barlesti-Catun", comuna: "Mogos" },
  { nume: "Bârlești", simplu: "Barlesti", comuna: "Bistra" },
  { nume: "Bârlești", simplu: "Barlesti", comuna: "Mogos" },
  { nume: "Bârlești", simplu: "Barlesti", comuna: "Scarisoara" },
  { nume: "Bârsana", simplu: "Barsana", comuna: "Sugag" },
  { nume: "Bârzan", simplu: "Barzan", comuna: "Lupsa" },
  { nume: "Bârzogani", simplu: "Barzogani", comuna: "Mogos" },
  { nume: "Băzești", simplu: "Bazesti", comuna: "Sohodol" },
  { nume: "Beldiu", comuna: "Teius" },
  { nume: "Benic", comuna: "Galda De Jos" },
  { nume: "Berghin" },
  { nume: "Beța", simplu: "Beta", comuna: "Lopadea Noua" },
  { nume: "Bidigești", simplu: "Bidigesti", comuna: "Ciuruleasa" },
  { nume: "Biharia", comuna: "Garda De Sus" },
  { nume: "Biia", comuna: "Sona" },
  { nume: "Bilănești", simplu: "Bilanesti", comuna: "Sohodol" },
  { nume: "Bisericani", comuna: "Bucium" },
  { nume: "Bistra" },
  { nume: "Blaj" },
  { nume: "Blandiana" },
  { nume: "Blidești", simplu: "Blidesti", comuna: "Rosia Montana" },
  { nume: "Bobărești", simplu: "Bobaresti", comuna: "Sohodol" },
  { nume: "Bobărești", simplu: "Bobaresti", comuna: "Vidra" },
  { nume: "Bocești", simplu: "Bocesti", comuna: "Mogos" },
  { nume: "Bocșitura", simplu: "Bocsitura", comuna: "Cugir" },
  { nume: "Bodești", simplu: "Bodesti", comuna: "Vadu Motilor" },
  { nume: "Bodrești", simplu: "Bodresti", comuna: "Ciuruleasa" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Mogos" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Vidra" },
  { nume: "Boglești", simplu: "Boglesti", comuna: "Ciuruleasa" },
  { nume: "Boldești", simplu: "Boldesti", comuna: "Avram Iancu" },
  { nume: "Bolovănești", simplu: "Bolovanesti", comuna: "Ceru-Bacainti" },
  { nume: "Boncești", simplu: "Boncesti", comuna: "Campeni" },
  { nume: "Bordeștii Poieni", simplu: "Bordestii Poieni", comuna: "Vidra" },
  { nume: "Borlești", simplu: "Borlesti", comuna: "Campeni" },
  { nume: "Boțani", simplu: "Botani", comuna: "Ramet" },
  { nume: "Botești", simplu: "Botesti", comuna: "Campeni" },
  { nume: "Botești", simplu: "Botesti", comuna: "Scarisoara" },
  { nume: "Botești", simplu: "Botesti", comuna: "Zlatna" },
  { nume: "Boz", comuna: "Dostat" },
  { nume: "Brădeana", simplu: "Bradeana", comuna: "Sohodol" },
  { nume: "Brădești", simplu: "Bradesti", comuna: "Ramet" },
  { nume: "Brădet", simplu: "Bradet", comuna: "Almasu Mare" },
  { nume: "Brăzești", simplu: "Brazesti", comuna: "Baia De Aries" },
  { nume: "Bubești", simplu: "Bubesti", comuna: "Arieseni" },
  {
    nume: "Bucerdea Grânoasă",
    simplu: "Bucerdea Granoasa",
    comuna: "Craciunelu De Jos",
  },
  { nume: "Bucerdea Vânoasă", simplu: "Bucerdea Vanoasa", comuna: "Ighiu" },
  { nume: "Bucium-Sat", comuna: "Bucium" },
  { nume: "Bucium" },
  { nume: "Bucuru", comuna: "Cugir" },
  { nume: "Budăiești", simplu: "Budaiesti", comuna: "Albac" },
  { nume: "Budeni", comuna: "Zlatna" },
  { nume: "Bulbuc", comuna: "Ceru-Bacainti" },
  { nume: "Buninginea", comuna: "Ciuruleasa" },
  { nume: "Bunta", comuna: "Rosia Montana" },
  { nume: "Burzești", simplu: "Burzesti", comuna: "Vadu Motilor" },
  { nume: "Burzonești", simplu: "Burzonesti", comuna: "Sohodol" },
  { nume: "Butești", simplu: "Butesti", comuna: "Horea" },
  { nume: "Butești", simplu: "Butesti", comuna: "Mogos" },
  { nume: "Călene", simplu: "Calene", comuna: "Cugir" },
  { nume: "Câlnic", simplu: "Calnic" },
  { nume: "Călugărești", simplu: "Calugaresti", comuna: "Avram Iancu" },
  { nume: "Câmpeni", simplu: "Campeni" },
  { nume: "Câmpu Goblii", simplu: "Campu Goblii", comuna: "Vintu De Jos" },
  { nume: "Cândești", simplu: "Candesti", comuna: "Avram Iancu" },
  { nume: "Căpâlna de Jos", simplu: "Capalna de Jos", comuna: "Jidvei" },
  { nume: "Căpâlna", simplu: "Capalna", comuna: "Sasciori" },
  { nume: "Căptălan", simplu: "Captalan", comuna: "Noslac" },
  { nume: "Capu Dealului", comuna: "Cenade" },
  { nume: "Căpud", simplu: "Capud", comuna: "Teius" },
  { nume: "Cârăști", simplu: "Carasti", comuna: "Avram Iancu" },
  { nume: "Carpen", comuna: "Spring" },
  { nume: "Carpenii de Sus", comuna: "Spring" },
  { nume: "Cărpiniș", simplu: "Carpinis", comuna: "Garbova" },
  { nume: "Cărpiniș", simplu: "Carpinis", comuna: "Rosia Montana" },
  { nume: "Cârțulești", simplu: "Cartulesti", comuna: "Avram Iancu" },
  { nume: "Casa de Piatră", simplu: "Casa de Piatra", comuna: "Arieseni" },
  { nume: "Căsoaia", simplu: "Casoaia", comuna: "Avram Iancu" },
  { nume: "Cenade" },
  { nume: "Cerbu", comuna: "Bucium" },
  { nume: "Cergău Mare", simplu: "Cergau Mare", comuna: "Cergau" },
  { nume: "Cergău Mic", simplu: "Cergau Mic", comuna: "Cergau" },
  { nume: "Certege", comuna: "Campeni" },
  { nume: "Ceru-Băcăinți", simplu: "Ceru-Bacainti" },
  { nume: "Cetatea de Baltă", simplu: "Cetatea de Balta" },
  { nume: "Cetea", comuna: "Galda De Jos" },
  { nume: "Cheia", comuna: "Ramet" },
  { nume: "Cheile Cibului", comuna: "Almasu Mare" },
  { nume: "Cheleteni", comuna: "Bistra" },
  { nume: "Cib", comuna: "Almasu Mare" },
  { nume: "Cicârd", simplu: "Cicard", comuna: "Lopadea Noua" },
  { nume: "Cicău", simplu: "Cicau", comuna: "Miraslau" },
  { nume: "Cioara de Sus", comuna: "Baia De Aries" },
  { nume: "Ciocașu", simplu: "Ciocasu", comuna: "Vintu De Jos" },
  { nume: "Cionești", simplu: "Cionesti", comuna: "Albac" },
  { nume: "Cistei", comuna: "Mihalt" },
  {
    nume: "Cisteiu de Mureș",
    simplu: "Cisteiu de Mures",
    comuna: "Ocna Mures",
  },
  { nume: "Ciuculești", simplu: "Ciuculesti", comuna: "Bucium" },
  { nume: "Ciugud" },
  { nume: "Ciugudu de Jos", comuna: "Unirea" },
  { nume: "Ciugudu de Sus", comuna: "Unirea" },
  { nume: "Ciuguzel", comuna: "Lopadea Noua" },
  { nume: "Ciuldești", simplu: "Ciuldesti", comuna: "Bistra" },
  { nume: "Ciumbrud", comuna: "Aiud" },
  { nume: "Ciuruleasa" },
  { nume: "Coasta Henții", simplu: "Coasta Hentii", comuna: "Rosia Montana" },
  { nume: "Coasta Vâscului", simplu: "Coasta Vascului", comuna: "Campeni" },
  { nume: "Cobleș", simplu: "Cobles", comuna: "Arieseni" },
  { nume: "Cocești", simplu: "Cocesti", comuna: "Avram Iancu" },
  { nume: "Cocoșești", simplu: "Cocosesti", comuna: "Avram Iancu" },
  { nume: "Cojocani", comuna: "Mogos" },
  { nume: "Coleșeni", simplu: "Coleseni", comuna: "Bucium" },
  { nume: "Colibi", comuna: "Ohaba" },
  { nume: "Colțești", simplu: "Coltesti", comuna: "Rametea" },
  { nume: "Copand", comuna: "Noslac" },
  { nume: "Corna", comuna: "Rosia Montana" },
  { nume: "Cornu", comuna: "Craciunelu De Jos" },
  { nume: "Coroiești", simplu: "Coroiesti", comuna: "Avram Iancu" },
  { nume: "Corțești", simplu: "Cortesti", comuna: "Posaga" },
  { nume: "Coșlariu Nou", simplu: "Coslariu Nou", comuna: "Teius" },
  { nume: "Coșlariu", simplu: "Coslariu", comuna: "Santimbru" },
  { nume: "Costești", simplu: "Costesti", comuna: "Albac" },
  { nume: "Costești", simplu: "Costesti", comuna: "Poiana Vadului" },
  { nume: "Cotorăști", simplu: "Cotorasti", comuna: "Ramet" },
  { nume: "Crăciunelu de Jos", simplu: "Craciunelu de Jos" },
  { nume: "Craciunelu de Sus", comuna: "Cetatea De Balta" },
  { nume: "Craiva", comuna: "Cricau" },
  { nume: "Crețești", simplu: "Cretesti", comuna: "Bistra" },
  { nume: "Cricău", simplu: "Cricau" },
  { nume: "Crișeni", simplu: "Criseni", comuna: "Vintu De Jos" },
  { nume: "Cristești", simplu: "Cristesti", comuna: "Mogos" },
  { nume: "Cucuta", comuna: "Ceru-Bacainti" },
  { nume: "Cugir" },
  { nume: "Culdești", simplu: "Culdesti", comuna: "Vidra" },
  { nume: "Cunța", simplu: "Cunta", comuna: "Spring" },
  { nume: "Curături", simplu: "Curaturi", comuna: "Rosia Montana" },
  { nume: "Curmătură", simplu: "Curmatura", comuna: "Lupsa" },
  { nume: "Curpeni", comuna: "Ceru-Bacainti" },
  { nume: "Cut", comuna: "Calnic" },
  { nume: "Daia Română", simplu: "Daia Romana" },
  { nume: "Dâmbureni", simplu: "Dambureni", comuna: "Bistra" },
  { nume: "Dănduț", simplu: "Dandut", comuna: "Campeni" },
  { nume: "Dârlești", simplu: "Darlesti", comuna: "Horea" },
  { nume: "Dăroaia", simplu: "Daroaia", comuna: "Rosia Montana" },
  { nume: "Deal", comuna: "Calnic" },
  { nume: "Dealu Bajului", comuna: "Arieseni" },
  { nume: "Dealu Bistrii", comuna: "Campeni" },
  { nume: "Dealu Capsei", comuna: "Campeni" },
  { nume: "Dealu Caselor", comuna: "Salciua" },
  { nume: "Dealu Crișului", simplu: "Dealu Crisului", comuna: "Avram Iancu" },
  { nume: "Dealu Doștatului", simplu: "Dealu Dostatului", comuna: "Dostat" },
  { nume: "Dealu Ferului", comuna: "Vintu De Jos" },
  { nume: "Dealu Frumos", comuna: "Garda De Sus" },
  { nume: "Dealu Frumos", comuna: "Vadu Motilor" },
  { nume: "Dealu Geoagiului", comuna: "Intregalde" },
  { nume: "Dealu Goiești", simplu: "Dealu Goiesti", comuna: "Vidra" },
  { nume: "Dealu Lămășoi", simplu: "Dealu Lamasoi", comuna: "Albac" },
  { nume: "Dealu Muntelui", comuna: "Bistra" },
  {
    nume: "Dealu Ordâncușii",
    simplu: "Dealu Ordancusii",
    comuna: "Garda De Sus",
  },
  { nume: "Dealu Roatei", comuna: "Zlatna" },
  { nume: "Decea", comuna: "Miraslau" },
  { nume: "Deleni-Obârșie", simplu: "Deleni-Obarsie", comuna: "Blaj" },
  { nume: "Deoncești", simplu: "Deoncesti", comuna: "Sohodol" },
  { nume: "Deve", comuna: "Albac" },
  { nume: "Dilimani", comuna: "Sohodol" },
  { nume: "Dobra", comuna: "Sugag" },
  { nume: "Dobrești", simplu: "Dobresti", comuna: "Garda De Sus" },
  { nume: "Dobrot", comuna: "Zlatna" },
  { nume: "Dogărești", simplu: "Dogaresti", comuna: "Bucium" },
  { nume: "Dolești", simplu: "Dolesti", comuna: "Avram Iancu" },
  { nume: "Doptău", simplu: "Doptau", comuna: "Sona" },
  { nume: "Dos", comuna: "Vidra" },
  { nume: "Doștat", simplu: "Dostat" },
  { nume: "Dosu Luncii", comuna: "Vidra" },
  { nume: "Dosu Văsești", simplu: "Dosu Vasesti", comuna: "Vidra" },
  { nume: "Drăgoiești-Luncă", simplu: "Dragoiesti-Lunca", comuna: "Vidra" },
  { nume: "Drâmbar", simplu: "Drambar", comuna: "Ciugud" },
  { nume: "Drașov", simplu: "Drasov", comuna: "Spring" },
  { nume: "Dric", comuna: "Campeni" },
  { nume: "Duduieni", comuna: "Poiana Vadului" },
  { nume: "Dumăcești", simplu: "Dumacesti", comuna: "Avram Iancu" },
  { nume: "Dumbrava", comuna: "Sasciori" },
  { nume: "Dumbrava", comuna: "Unirea" },
  { nume: "Dumbrava", comuna: "Zlatna" },
  { nume: "Dumbrăvița", simplu: "Dumbravita", comuna: "Ceru-Bacainti" },
  { nume: "Dumești", simplu: "Dumesti", comuna: "Salciua" },
  { nume: "Dumitra", comuna: "Santimbru" },
  { nume: "Dupa Deal", comuna: "Ponor" },
  { nume: "După Deal", simplu: "Dupa Deal", comuna: "Lupsa" },
  { nume: "După Pleșe", simplu: "Dupa Plese", comuna: "Albac" },
  { nume: "Durăști", simplu: "Durasti", comuna: "Bistra" },
  { nume: "Făget", simplu: "Faget", comuna: "Valea Lunga" },
  { nume: "Făgetu de Jos", simplu: "Fagetu de Jos", comuna: "Poiana Vadului" },
  { nume: "Făgetu de Sus", simplu: "Fagetu de Sus", comuna: "Poiana Vadului" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Ceru-Bacainti" },
  { nume: "Fărău", simplu: "Farau" },
  { nume: "Fața Abrudului", simplu: "Fata Abrudului", comuna: "Campeni" },
  { nume: "Fața Cristesei", simplu: "Fata Cristesei", comuna: "Arieseni" },
  { nume: "Fața Lăpușului", simplu: "Fata Lapusului", comuna: "Arieseni" },
  { nume: "Fața Pietrii", simplu: "Fata Pietrii", comuna: "Stremt" },
  { nume: "Fața-Lăzești", simplu: "Fata-Lazesti", comuna: "Scarisoara" },
  { nume: "Fața", simplu: "Fata", comuna: "Albac" },
  { nume: "Feisa", comuna: "Jidvei" },
  { nume: "Feneș", simplu: "Fenes", comuna: "Zlatna" },
  { nume: "Ferești", simplu: "Feresti", comuna: "Bucium" },
  { nume: "Fericet", comuna: "Horea" },
  { nume: "Fețeni", simplu: "Feteni", comuna: "Cugir" },
  { nume: "Ficărești", simplu: "Ficaresti", comuna: "Vidra" },
  { nume: "Flitești", simplu: "Flitesti", comuna: "Blaj" },
  { nume: "Florești", simplu: "Floresti", comuna: "Bucium" },
  { nume: "Florești", simplu: "Floresti", comuna: "Campeni" },
  { nume: "Florești", simplu: "Floresti", comuna: "Ramet" },
  { nume: "Florești", simplu: "Floresti", comuna: "Scarisoara" },
  { nume: "Furduiești", simplu: "Furduiesti", comuna: "Campeni" },
  { nume: "Furduiești", simplu: "Furduiesti", comuna: "Sohodol" },
  { nume: "Găbud", simplu: "Gabud", comuna: "Noslac" },
  { nume: "Galați", simplu: "Galati", comuna: "Zlatna" },
  { nume: "Galbena", comuna: "Arieseni" },
  { nume: "Galda de Jos" },
  { nume: "Galda de Sus", comuna: "Galda De Jos" },
  { nume: "Galtiu", comuna: "Santimbru" },
  { nume: "Gâmbaș", simplu: "Gambas", comuna: "Aiud" },
  { nume: "Gănești", simplu: "Ganesti", comuna: "Bistra" },
  { nume: "Gârbova de Jos", simplu: "Garbova de Jos", comuna: "Aiud" },
  { nume: "Gârbova de Sus", simplu: "Garbova de Sus", comuna: "Aiud" },
  { nume: "Gârbova", simplu: "Garbova" },
  { nume: "Gârbovița", simplu: "Garbovita", comuna: "Aiud" },
  { nume: "Gârda de Sus", simplu: "Garda de Sus" },
  { nume: "Gârda Seacă", simplu: "Garda Seaca", comuna: "Garda De Sus" },
  {
    nume: "Gârda-Bărbulești",
    simplu: "Garda-Barbulesti",
    comuna: "Rosia Montana",
  },
  { nume: "Gârde", simplu: "Garde", comuna: "Bistra" },
  { nume: "Geamăna", simplu: "Geamana", comuna: "Lupsa" },
  { nume: "Geoagiu de Sus", comuna: "Stremt" },
  { nume: "Geogel", comuna: "Ponor" },
  { nume: "Geomal", comuna: "Stremt" },
  { nume: "Ghedulești", simplu: "Ghedulesti", comuna: "Ciuruleasa" },
  { nume: "Ghețari", simplu: "Ghetari", comuna: "Garda De Sus" },
  { nume: "Ghioncani", comuna: "Intregalde" },
  { nume: "Ghirbom", comuna: "Berghin" },
  { nume: "Giurgiuț", simplu: "Giurgiut", comuna: "Horea" },
  { nume: "Gligorești", simplu: "Gligoresti", comuna: "Vidra" },
  { nume: "Glod", comuna: "Almasu Mare" },
  { nume: "Glogoveț", simplu: "Glogovet", comuna: "Valea Lunga" },
  { nume: "Goașele", simplu: "Goasele", comuna: "Cugir" },
  { nume: "Goiești", simplu: "Goiesti", comuna: "Vidra" },
  { nume: "Gojeiești", simplu: "Gojeiesti", comuna: "Avram Iancu" },
  { nume: "Gorgan", comuna: "Cenade" },
  { nume: "Groși", simplu: "Grosi", comuna: "Ceru-Bacainti" },
  {
    nume: "Gura Arieșului",
    simplu: "Gura Ariesului",
    comuna: "Lunca Muresului",
  },
  { nume: "Gura Cornei", comuna: "Abrud" },
  { nume: "Gura Cuțului", simplu: "Gura Cutului", comuna: "Vintu De Jos" },
  { nume: "Gura Izbitei", comuna: "Bucium" },
  { nume: "Gura Roșiei", simplu: "Gura Rosiei", comuna: "Rosia Montana" },
  { nume: "Gura Sohodol", comuna: "Sohodol" },
  { nume: "Hădărău", simplu: "Hadarau", comuna: "Lupsa" },
  { nume: "Haiducești", simplu: "Haiducesti", comuna: "Vidra" },
  { nume: "Hanășești", simplu: "Hanasesti", comuna: "Garda De Sus" },
  { nume: "Hănășești", simplu: "Hanasesti", comuna: "Poiana Vadului" },
  { nume: "Hăpria", simplu: "Hapria", comuna: "Ciugud" },
  { nume: "Hărăști", simplu: "Harasti", comuna: "Vidra" },
  { nume: "Hațegana", simplu: "Hategana", comuna: "Vintu De Jos" },
  { nume: "Helerești", simplu: "Heleresti", comuna: "Avram Iancu" },
  { nume: "Helești", simplu: "Helesti", comuna: "Bucium" },
  { nume: "Henig", comuna: "Berghin" },
  { nume: "Heria", comuna: "Farau" },
  { nume: "Hoancă", simplu: "Hoanca", comuna: "Sohodol" },
  { nume: "Hoancă", simplu: "Hoanca", comuna: "Vidra" },
  { nume: "Hodișești", simplu: "Hodisesti", comuna: "Bistra" },
  { nume: "Hodobana", comuna: "Arieseni" },
  { nume: "Holobani", comuna: "Lupsa" },
  { nume: "Hopârta", simplu: "Hoparta" },
  { nume: "Horea" },
  { nume: "Hudricești", simplu: "Hudricesti", comuna: "Bistra" },
  { nume: "Huzărești", simplu: "Huzaresti", comuna: "Garda De Sus" },
  { nume: "Iacobești", simplu: "Iacobesti", comuna: "Rosia Montana" },
  { nume: "Ibru", comuna: "Blandiana" },
  { nume: "Iclod", comuna: "Sancel" },
  { nume: "Ighiel", comuna: "Ighiu" },
  { nume: "Ighiu" },
  { nume: "Ignățești", simplu: "Ignatesti", comuna: "Rosia Montana" },
  { nume: "Iliești", simplu: "Iliesti", comuna: "Intregalde" },
  { nume: "Incești", simplu: "Incesti", comuna: "Avram Iancu" },
  { nume: "Incești", simplu: "Incesti", comuna: "Posaga" },
  { nume: "Inoc", comuna: "Unirea" },
  { nume: "Întregalde", simplu: "Intregalde" },
  { nume: "Inuri", comuna: "Vintu De Jos" },
  { nume: "Isca", comuna: "Metes" },
  { nume: "Ivăniș", simplu: "Ivanis", comuna: "Intregalde" },
  { nume: "Izbicioara", comuna: "Bucium" },
  { nume: "Izbita", comuna: "Bucium" },
  { nume: "Izlaz", comuna: "Arieseni" },
  { nume: "Izvoarele", comuna: "Blaj" },
  { nume: "Izvoarele", comuna: "Garda De Sus" },
  { nume: "Izvoarele", comuna: "Livezile" },
  { nume: "Izvoru Ampoiului", comuna: "Zlatna" },
  { nume: "Jeflești", simplu: "Jeflesti", comuna: "Vidra" },
  { nume: "Jidoștina", simplu: "Jidostina", comuna: "Sugag" },
  { nume: "Jidvei" },
  { nume: "Jojei", comuna: "Avram Iancu" },
  { nume: "Joldișești", simplu: "Joldisesti", comuna: "Sohodol" },
  { nume: "Jurcuiești", simplu: "Jurcuiesti", comuna: "Bucium" },
  { nume: "Lancrăm", simplu: "Lancram", comuna: "Sebes" },
  { nume: "Laz", comuna: "Sasciori" },
  { nume: "Laz", comuna: "Vintu De Jos" },
  { nume: "Lăzești", simplu: "Lazesti", comuna: "Scarisoara" },
  { nume: "Lăzești", simplu: "Lazesti", comuna: "Vadu Motilor" },
  { nume: "Lazuri", comuna: "Lupsa" },
  { nume: "Lazuri", comuna: "Sohodol" },
  { nume: "Lehești", simplu: "Lehesti", comuna: "Sohodol" },
  { nume: "Leorinț", simplu: "Leorint", comuna: "Radesti" },
  { nume: "Lespezea", comuna: "Scarisoara" },
  { nume: "Limba", comuna: "Ciugud" },
  { nume: "Lipaia", comuna: "Bistra" },
  { nume: "Livezile" },
  { nume: "Lodroman", comuna: "Valea Lunga" },
  { nume: "Loman", comuna: "Sasciori" },
  { nume: "Lopadea Nouă", simplu: "Lopadea Noua" },
  { nume: "Lopadea Veche", comuna: "Miraslau" },
  { nume: "Luminești", simplu: "Luminesti", comuna: "Sohodol" },
  { nume: "Lunca Ampoiței", simplu: "Lunca Ampoitei", comuna: "Metes" },
  { nume: "Lunca Bisericii", comuna: "Vidra" },
  { nume: "Lunca de Jos", comuna: "Vidra" },
  { nume: "Lunca Goiești", simplu: "Lunca Goiesti", comuna: "Vidra" },
  { nume: "Lunca Largă", simplu: "Lunca Larga", comuna: "Bistra" },
  { nume: "Lunca Largă", simplu: "Lunca Larga", comuna: "Ocolis" },
  { nume: "Lunca Merilor", comuna: "Bistra" },
  { nume: "Lunca Meteșului", simplu: "Lunca Metesului", comuna: "Metes" },
  { nume: "Lunca Mureșului", simplu: "Lunca Muresului" },
  { nume: "Lunca Târnavei", simplu: "Lunca Tarnavei", comuna: "Sona" },
  { nume: "Lunca Vesești", simplu: "Lunca Vesesti", comuna: "Vidra" },
  { nume: "Lunca", comuna: "Lupsa" },
  { nume: "Lunca", comuna: "Posaga" },
  { nume: "Lunca", comuna: "Valea Lunga" },
  { nume: "Lunca", comuna: "Vidra" },
  { nume: "Lupăiești", simplu: "Lupaiesti", comuna: "Poiana Vadului" },
  { nume: "Lupșa", simplu: "Lupsa" },
  { nume: "Lupșeni", simplu: "Lupseni", comuna: "Galda De Jos" },
  { nume: "Lupu", comuna: "Cergau" },
  { nume: "Lupulești", simplu: "Lupulesti", comuna: "Bucium" },
  { nume: "Măcărești", simplu: "Macaresti", comuna: "Ponor" },
  { nume: "Măghierat", simplu: "Maghierat", comuna: "Ohaba" },
  { nume: "Măgina", simplu: "Magina", comuna: "Aiud" },
  { nume: "Măgura", simplu: "Magura", comuna: "Bucium" },
  { nume: "Măgura", simplu: "Magura", comuna: "Galda De Jos" },
  { nume: "Măhăceni", simplu: "Mahaceni", comuna: "Unirea" },
  { nume: "Mămăligani", simplu: "Mamaligani", comuna: "Mogos" },
  { nume: "Mănărade", simplu: "Manarade", comuna: "Blaj" },
  { nume: "Mănăstire", simplu: "Manastire", comuna: "Lupsa" },
  { nume: "Măncești", simplu: "Mancesti", comuna: "Horea" },
  { nume: "Mărgaia", simplu: "Margaia", comuna: "Lupsa" },
  { nume: "Mărgineni", simplu: "Margineni", comuna: "Salistea" },
  { nume: "Mărinești", simplu: "Marinesti", comuna: "Intregalde" },
  { nume: "Mărtești", simplu: "Martesti", comuna: "Avram Iancu" },
  { nume: "Mărtinie", simplu: "Martinie", comuna: "Sugag" },
  { nume: "Mătăcina", simplu: "Matacina", comuna: "Vintu De Jos" },
  { nume: "Maței", simplu: "Matei", comuna: "Scarisoara" },
  { nume: "Mătișești", simplu: "Matisesti", comuna: "Ciuruleasa" },
  { nume: "Mătișești", simplu: "Matisesti", comuna: "Horea" },
  { nume: "Medrești", simplu: "Medresti", comuna: "Sohodol" },
  { nume: "Medveș", simplu: "Medves", comuna: "Farau" },
  { nume: "Mereteu", comuna: "Vintu De Jos" },
  { nume: "Meșcreac", simplu: "Mescreac", comuna: "Radesti" },
  { nume: "Mesentea", comuna: "Galda De Jos" },
  { nume: "Meteș", simplu: "Metes" },
  { nume: "Micești", simplu: "Micesti", comuna: "Alba Iulia" },
  { nume: "Micoșlaca", simplu: "Micoslaca", comuna: "Ocna Mures" },
  { nume: "Mihăiești", simplu: "Mihaiesti", comuna: "Bistra" },
  { nume: "Mihalț", simplu: "Mihalt" },
  { nume: "Mihoești", simplu: "Mihoesti", comuna: "Campeni" },
  { nume: "Mirăslău", simplu: "Miraslau" },
  { nume: "Modolești", simplu: "Modolesti", comuna: "Intregalde" },
  { nume: "Modolești", simplu: "Modolesti", comuna: "Vidra" },
  { nume: "Mogoș", simplu: "Mogos" },
  { nume: "Morărești", simplu: "Moraresti", comuna: "Ciuruleasa" },
  { nume: "Morărești", simplu: "Moraresti", comuna: "Sohodol" },
  { nume: "Morcănești", simplu: "Morcanesti", comuna: "Poiana Vadului" },
  { nume: "Motorăști", simplu: "Motorasti", comuna: "Campeni" },
  { nume: "Mugești", simplu: "Mugesti", comuna: "Cugir" },
  { nume: "Muncelu", comuna: "Baia De Aries" },
  { nume: "Munești", simplu: "Munesti", comuna: "Sohodol" },
  { nume: "Muntari", comuna: "Bucium" },
  { nume: "Munună", simplu: "Mununa", comuna: "Garda De Sus" },
  { nume: "Mușca", simplu: "Musca", comuna: "Lupsa" },
  { nume: "Nădăștia", simplu: "Nadastia", comuna: "Almasu Mare" },
  { nume: "Nămaș", simplu: "Namas", comuna: "Bistra" },
  { nume: "Năpăiești", simplu: "Napaiesti", comuna: "Sohodol" },
  { nume: "Necrilești", simplu: "Necrilesti", comuna: "Intregalde" },
  { nume: "Necșești", simplu: "Necsesti", comuna: "Vadu Motilor" },
  { nume: "Negești", simplu: "Negesti", comuna: "Scarisoara" },
  { nume: "Negrești", simplu: "Negresti", comuna: "Mogos" },
  { nume: "Nelegești", simplu: "Nelegesti", comuna: "Sohodol" },
  { nume: "Nemeși", simplu: "Nemesi", comuna: "Vidra" },
  { nume: "Nicorești", simplu: "Nicoresti", comuna: "Sohodol" },
  { nume: "Niculești", simplu: "Niculesti", comuna: "Horea" },
  { nume: "Noșlac", simplu: "Noslac" },
  { nume: "Novăcești", simplu: "Novacesti", comuna: "Bistra" },
  { nume: "Oarda", comuna: "Alba Iulia" },
  { nume: "Obreja", comuna: "Mihalt" },
  { nume: "Ocna Mureș", simplu: "Ocna Mures" },
  { nume: "Ocnișoara", simplu: "Ocnisoara", comuna: "Lopadea Noua" },
  { nume: "Ocoale", comuna: "Garda De Sus" },
  { nume: "Ocoliș", simplu: "Ocolis" },
  { nume: "Odverem", comuna: "Lopadea Noua" },
  { nume: "Ohaba" },
  { nume: "Oidești", simplu: "Oidesti", comuna: "Vidra" },
  { nume: "Oiejdea", comuna: "Galda De Jos" },
  { nume: "Olteni", comuna: "Ramet" },
  { nume: "Oncești", simplu: "Oncesti", comuna: "Mogos" },
  { nume: "Orăști", simplu: "Orasti", comuna: "Posaga" },
  { nume: "Orgești", simplu: "Orgesti", comuna: "Avram Iancu" },
  { nume: "Ormeniș", simplu: "Ormenis", comuna: "Miraslau" },
  { nume: "Pâclișa", simplu: "Paclisa", comuna: "Alba Iulia" },
  { nume: "Pădure", simplu: "Padure", comuna: "Craciunelu De Jos" },
  { nume: "Pădurea", simplu: "Padurea", comuna: "Metes" },
  { nume: "Păgida", simplu: "Pagida", comuna: "Aiud" },
  { nume: "Pănade", simplu: "Panade", comuna: "Sancel" },
  { nume: "Pânca", simplu: "Panca", comuna: "Craciunelu De Jos" },
  { nume: "Păntești", simplu: "Pantesti", comuna: "Arieseni" },
  { nume: "Pârau Gruiului", simplu: "Parau Gruiului", comuna: "Zlatna" },
  {
    nume: "Pârău lui Mihai",
    simplu: "Parau lui Mihai",
    comuna: "Vintu De Jos",
  },
  { nume: "Pârâu-Cărbunări", simplu: "Parau-Carbunari", comuna: "Lupsa" },
  { nume: "Păștești", simplu: "Pastesti", comuna: "Poiana Vadului" },
  { nume: "Pătrăhăițești", simplu: "Patrahaitesti", comuna: "Arieseni" },
  { nume: "Pătrângeni", simplu: "Patrangeni", comuna: "Zlatna" },
  { nume: "Pătrușești", simplu: "Patrusesti", comuna: "Horea" },
  { nume: "Pătruțești", simplu: "Patrutesti", comuna: "Avram Iancu" },
  { nume: "Peleș", simplu: "Peles", comuna: "Sohodol" },
  { nume: "Perjești", simplu: "Perjesti", comuna: "Bistra" },
  { nume: "Peste Valea Bistrii", comuna: "Campeni" },
  { nume: "Pețelca", simplu: "Petelca", comuna: "Teius" },
  { nume: "Petelei", comuna: "Poiana Vadului" },
  { nume: "Petreasa", comuna: "Horea" },
  { nume: "Petreni", comuna: "Bucium" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Sebes" },
  { nume: "Petrisat", comuna: "Blaj" },
  { nume: "Pianu de Jos", comuna: "Pianu" },
  { nume: "Pianu de Sus", comuna: "Pianu" },
  { nume: "Pirita", comuna: "Zlatna" },
  { nume: "Pitărcești", simplu: "Pitarcesti", comuna: "Vidra" },
  { nume: "Pițiga", simplu: "Pitiga", comuna: "Lupsa" },
  { nume: "Plai", comuna: "Avram Iancu" },
  { nume: "Plai", comuna: "Garda De Sus" },
  { nume: "Plaiuri", comuna: "Pianu" },
  { nume: "Pleșcuța", simplu: "Plescuta", comuna: "Vidra" },
  { nume: "Pleșești", simplu: "Plesesti", comuna: "Albac" },
  { nume: "Pleși", simplu: "Plesi", comuna: "Sasciori" },
  { nume: "Pliști", simplu: "Plisti", comuna: "Garda De Sus" },
  { nume: "Podu lui Paul", comuna: "Zlatna" },
  {
    nume: "Poduri-Bricești",
    simplu: "Poduri-Bricesti",
    comuna: "Vadu Motilor",
  },
  { nume: "Poduri", comuna: "Campeni" },
  { nume: "Poiana Aiudului", comuna: "Livezile" },
  { nume: "Poiana Ampoiului", comuna: "Metes" },
  { nume: "Poiana Galdei", comuna: "Galda De Jos" },
  { nume: "Poiana Ursului", comuna: "Metes" },
  { nume: "Poiana Vadului" },
  { nume: "Poiana", comuna: "Bistra" },
  { nume: "Poiana", comuna: "Bucium" },
  { nume: "Poiana", comuna: "Sohodol" },
  { nume: "Poieni", comuna: "Blandiana" },
  { nume: "Poieni", comuna: "Bucium" },
  { nume: "Poieni", comuna: "Vidra" },
  { nume: "Poienile-Mogoș", simplu: "Poienile-Mogos", comuna: "Mogos" },
  { nume: "Poienița", simplu: "Poienita", comuna: "Arieseni" },
  { nume: "Poienița", simplu: "Poienita", comuna: "Vintu De Jos" },
  { nume: "Poiu", comuna: "Bistra" },
  { nume: "Ponor" },
  { nume: "Ponorel", comuna: "Vidra" },
  { nume: "Popești", simplu: "Popesti", comuna: "Intregalde" },
  {
    nume: "Popeștii de Jos",
    simplu: "Popestii de Jos",
    comuna: "Vadu Motilor",
  },
  {
    nume: "Popeștii de Sus",
    simplu: "Popestii de Sus",
    comuna: "Vadu Motilor",
  },
  { nume: "Poșaga de Jos", simplu: "Posaga de Jos", comuna: "Posaga" },
  { nume: "Poșaga de Sus", simplu: "Posaga de Sus", comuna: "Posaga" },
  { nume: "Poșogani", simplu: "Posogani", comuna: "Lupsa" },
  { nume: "Potionci", comuna: "Albac" },
  { nume: "Preluca", comuna: "Horea" },
  { nume: "Prelucă", simplu: "Preluca", comuna: "Scarisoara" },
  { nume: "Presaca Ampoiului", comuna: "Metes" },
  { nume: "Puiulețești", simplu: "Puiuletesti", comuna: "Vidra" },
  { nume: "Purcăreți", simplu: "Purcareti", comuna: "Pianu" },
  { nume: "Pușelești", simplu: "Puselesti", comuna: "Avram Iancu" },
  { nume: "Răcătău", simplu: "Racatau", comuna: "Blandiana" },
  { nume: "Rachiș", simplu: "Rachis", comuna: "Miraslau" },
  { nume: "Răchita", simplu: "Rachita", comuna: "Sasciori" },
  { nume: "Rădești", simplu: "Radesti" },
  { nume: "Răhău", simplu: "Rahau", comuna: "Sebes" },
  { nume: "Răicani", simplu: "Raicani", comuna: "Galda De Jos" },
  { nume: "Râmeț", simplu: "Ramet" },
  { nume: "Râmetea", simplu: "Rametea" },
  { nume: "Rătitiș", simplu: "Ratitis", comuna: "Bistra" },
  { nume: "Ravicești", simplu: "Ravicesti", comuna: "Arieseni" },
  {
    nume: "Războieni-Cetate",
    simplu: "Razboieni-Cetate",
    comuna: "Ocna Mures",
  },
  { nume: "Reciu", comuna: "Garbova" },
  { nume: "Remetea", comuna: "Metes" },
  { nume: "Robești", simplu: "Robesti", comuna: "Sohodol" },
  { nume: "Rogoz", comuna: "Albac" },
  { nume: "Roșești", simplu: "Rosesti", comuna: "Albac" },
  { nume: "Roșia de Secaș", simplu: "Rosia de Secas" },
  { nume: "Roșia Montană", simplu: "Rosia Montana" },
  { nume: "Runc", comuna: "Ocolis" },
  { nume: "Runc", comuna: "Scarisoara" },
  { nume: "Runc", comuna: "Vidra" },
  { nume: "Runc", comuna: "Zlatna" },
  { nume: "Runcuri", comuna: "Bistra" },
  { nume: "Rusești", simplu: "Rusesti", comuna: "Albac" },
  { nume: "Ruși", simplu: "Rusi", comuna: "Zlatna" },
  { nume: "Sagagea", comuna: "Posaga" },
  { nume: "Sălăgești", simplu: "Salagesti", comuna: "Bistra" },
  { nume: "Sălciua de Jos", simplu: "Salciua de Jos", comuna: "Salciua" },
  { nume: "Sălciua de Sus", simplu: "Salciua de Sus", comuna: "Salciua" },
  { nume: "Săliștea-Deal", simplu: "Salistea-Deal", comuna: "Salistea" },
  { nume: "Săliștea", simplu: "Salistea" },
  { nume: "Sânbenedic", simplu: "Sanbenedic", comuna: "Farau" },
  { nume: "Sâncel", simplu: "Sancel" },
  { nume: "Sâncrai", simplu: "Sancrai", comuna: "Aiud" },
  { nume: "Sânmiclăuș", simplu: "Sanmiclaus", comuna: "Sona" },
  { nume: "Sântămărie", simplu: "Santamarie", comuna: "Cetatea De Balta" },
  { nume: "Sântimbru", simplu: "Santimbru" },
  { nume: "Sărăcsău", simplu: "Saracsau", comuna: "Sibot" },
  { nume: "Șard", simplu: "Sard", comuna: "Ighiu" },
  { nume: "Sartăș", simplu: "Sartas", comuna: "Baia De Aries" },
  { nume: "Șasa", simplu: "Sasa", comuna: "Lupsa" },
  { nume: "Săsciori", simplu: "Sasciori" },
  { nume: "Scărișoara", simplu: "Scarisoara" },
  { nume: "Scoarța", simplu: "Scoarta", comuna: "Garda De Sus" },
  { nume: "Sebeș", simplu: "Sebes" },
  { nume: "Sebeșel", simplu: "Sebesel", comuna: "Sasciori" },
  { nume: "Sebișești", simplu: "Sebisesti", comuna: "Sohodol" },
  { nume: "Secășel", simplu: "Secasel", comuna: "Ohaba" },
  { nume: "Segaj", comuna: "Vidra" },
  { nume: "Șeușa", simplu: "Seusa", comuna: "Ciugud" },
  { nume: "Sfârcea", simplu: "Sfarcea", comuna: "Intregalde" },
  { nume: "Sfoartea", comuna: "Scarisoara" },
  { nume: "Șibot", simplu: "Sibot" },
  { nume: "Sicoiești", simplu: "Sicoiesti", comuna: "Sohodol" },
  { nume: "Șilea", simplu: "Silea", comuna: "Farau" },
  { nume: "Silivaș", simplu: "Silivas", comuna: "Hoparta" },
  { nume: "Șimocești", simplu: "Simocesti", comuna: "Sohodol" },
  { nume: "Simulești", simplu: "Simulesti", comuna: "Baia De Aries" },
  { nume: "Snide", comuna: "Garda De Sus" },
  { nume: "Șoal", simplu: "Soal", comuna: "Rosia Montana" },
  { nume: "Soharu", comuna: "Abrud" },
  { nume: "Sohodol" },
  { nume: "Sohodol", comuna: "Albac" },
  { nume: "Șoicești", simplu: "Soicesti", comuna: "Avram Iancu" },
  { nume: "Șoimuș", simplu: "Soimus", comuna: "Radesti" },
  { nume: "Șona", simplu: "Sona" },
  { nume: "Sorlița", simplu: "Sorlita", comuna: "Campeni" },
  { nume: "Șpălnaca", simplu: "Spalnaca", comuna: "Hoparta" },
  { nume: "Spătac", simplu: "Spatac", comuna: "Blaj" },
  { nume: "Șpring", simplu: "Spring" },
  { nume: "Stâlnișoara", simplu: "Stalnisoara", comuna: "Bucium" },
  { nume: "Stâna de Mureș", simplu: "Stana de Mures", comuna: "Noslac" },
  { nume: "Stănești", simplu: "Stanesti", comuna: "Poiana Vadului" },
  { nume: "Stăuini", simplu: "Stauini", comuna: "Vintu De Jos" },
  { nume: "Ștefanca", simplu: "Stefanca", comuna: "Bistra" },
  { nume: "Ștei-Arieșeni", simplu: "Stei-Arieseni", comuna: "Arieseni" },
  { nume: "Ștertești", simplu: "Stertesti", comuna: "Avram Iancu" },
  { nume: "Știuleți", simplu: "Stiuleti", comuna: "Scarisoara" },
  { nume: "Straja", comuna: "Berghin" },
  { nume: "Stremț", simplu: "Stremt" },
  { nume: "Strungari", comuna: "Pianu" },
  { nume: "Sturu", comuna: "Arieseni" },
  { nume: "Sub Piatră", simplu: "Sub Piatra", comuna: "Salciua" },
  { nume: "Sucești", simplu: "Sucesti", comuna: "Garda De Sus" },
  { nume: "Șugag", simplu: "Sugag" },
  { nume: "Surdești", simplu: "Surdesti", comuna: "Sohodol" },
  { nume: "Suseni", comuna: "Zlatna" },
  { nume: "Tamborești", simplu: "Tamboresti", comuna: "Albac" },
  { nume: "Țărănești", simplu: "Taranesti", comuna: "Bistra" },
  { nume: "Țarina", simplu: "Tarina", comuna: "Rosia Montana" },
  { nume: "Târsa-Plai", simplu: "Tarsa-Plai", comuna: "Avram Iancu" },
  { nume: "Târsa", simplu: "Tarsa", comuna: "Avram Iancu" },
  { nume: "Tărtăria", simplu: "Tartaria", comuna: "Salistea" },
  { nume: "Tătârlaua", simplu: "Tatarlaua", comuna: "Cetatea De Balta" },
  { nume: "Tău Bistra", simplu: "Tau Bistra", comuna: "Sugag" },
  { nume: "Tău", simplu: "Tau", comuna: "Rosia De Secas" },
  { nume: "Tăuni", simplu: "Tauni", comuna: "Valea Lunga" },
  { nume: "Tăuți", simplu: "Tauti", comuna: "Metes" },
  { nume: "Tecșești", simplu: "Tecsesti", comuna: "Intregalde" },
  { nume: "Teiu", comuna: "Horea" },
  { nume: "Teiuș", simplu: "Teius" },
  { nume: "Teleac", comuna: "Ciugud" },
  { nume: "Țelna", simplu: "Telna", comuna: "Ighiu" },
  { nume: "Tibru", comuna: "Cricau" },
  { nume: "Țifra", simplu: "Tifra", comuna: "Aiud" },
  { nume: "Tiur", comuna: "Blaj" },
  { nume: "Toci", comuna: "Sohodol" },
  { nume: "Tolăcești", simplu: "Tolacesti", comuna: "Bistra" },
  { nume: "Tomești", simplu: "Tomesti", comuna: "Mogos" },
  { nume: "Tomnatec", comuna: "Bistra" },
  { nume: "Tomușești", simplu: "Tomusesti", comuna: "Campeni" },
  { nume: "Tomuțești", simplu: "Tomutesti", comuna: "Vadu Motilor" },
  { nume: "Tonea", comuna: "Sasciori" },
  { nume: "Toțești", simplu: "Totesti", comuna: "Vadu Motilor" },
  { nume: "Totoi", comuna: "Santimbru" },
  { nume: "Trâmpoiele", simplu: "Trampoiele", comuna: "Zlatna" },
  { nume: "Trâncești", simplu: "Trancesti", comuna: "Scarisoara" },
  { nume: "Trifești", simplu: "Trifesti", comuna: "Horea" },
  { nume: "Trifești", simplu: "Trifesti", comuna: "Lupsa" },
  { nume: "Trișorești", simplu: "Trisoresti", comuna: "Bistra" },
  { nume: "Turdaș", simplu: "Turdas", comuna: "Hoparta" },
  { nume: "Uioara de Jos", comuna: "Ocna Mures" },
  { nume: "Uioara de Sus", comuna: "Ocna Mures" },
  { nume: "Ungurei", comuna: "Rosia De Secas" },
  { nume: "Unirea" },
  { nume: "Urdeș", simplu: "Urdes", comuna: "Vidra" },
  { nume: "Vadu Moților", simplu: "Vadu Motilor" },
  { nume: "Văi", simplu: "Vai", comuna: "Lupsa" },
  { nume: "Vâlcăneasa", simplu: "Valcaneasa", comuna: "Vidra" },
  { nume: "Vâlcea", simplu: "Valcea", comuna: "Bucium" },
  { nume: "Vâlcești", simplu: "Valcesti", comuna: "Vidra" },
  { nume: "Vale In Jos", comuna: "Ponor" },
  { nume: "Valea Abruzel", comuna: "Bucium" },
  { nume: "Valea Albă", simplu: "Valea Alba", comuna: "Bucium" },
  { nume: "Valea Bârluțești", simplu: "Valea Barlutesti", comuna: "Mogos" },
  { nume: "Valea Barnii", comuna: "Mogos" },
  { nume: "Valea Bistrii", comuna: "Campeni" },
  { nume: "Valea Bucurului", comuna: "Ponor" },
  { nume: "Valea Caselor", comuna: "Campeni" },
  { nume: "Valea Cerbului", comuna: "Bucium" },
  { nume: "Valea Ciuciului", comuna: "Noslac" },
  { nume: "Valea Cocești", simplu: "Valea Cocesti", comuna: "Mogos" },
  { nume: "Valea Făgetului", simplu: "Valea Fagetului", comuna: "Ramet" },
  { nume: "Valea Giogești", simplu: "Valea Giogesti", comuna: "Mogos" },
  { nume: "Valea Goblii", comuna: "Vintu De Jos" },
  { nume: "Valea Holhorii", comuna: "Lupsa" },
  { nume: "Valea Inzelului", comuna: "Ramet" },
  { nume: "Valea Largă", simplu: "Valea Larga", comuna: "Salciua" },
  { nume: "Valea lui Mihai", comuna: "Vintu De Jos" },
  { nume: "Valea Lungă", simplu: "Valea Lunga" },
  { nume: "Valea Lupșii", simplu: "Valea Lupsii", comuna: "Lupsa" },
  { nume: "Valea Maciului", comuna: "Avram Iancu" },
  { nume: "Valea Mănăstirii", simplu: "Valea Manastirii", comuna: "Ramet" },
  { nume: "Valea Mare", comuna: "Ceru-Bacainti" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Zlatna" },
  { nume: "Valea Mlacii", comuna: "Mogos" },
  { nume: "Valea Morii", comuna: "Vidra" },
  { nume: "Valea Negrilesii", comuna: "Bucium" },
  { nume: "Valea Poienii", comuna: "Bucium" },
  { nume: "Valea Poienii", comuna: "Ramet" },
  { nume: "Valea Sasului", comuna: "Sona" },
  { nume: "Valea șesii", simplu: "Valea Sesii", comuna: "Bucium" },
  { nume: "Valea șesii", simplu: "Valea Sesii", comuna: "Lupsa" },
  { nume: "Valea țupilor", simplu: "Valea Tupilor", comuna: "Mogos" },
  { nume: "Valea Uțului", simplu: "Valea Utului", comuna: "Avram Iancu" },
  { nume: "Valea Uzei", comuna: "Ramet" },
  { nume: "Valea Verde", comuna: "Sohodol" },
  { nume: "Valea Vințului", simplu: "Valea Vintului", comuna: "Vintu De Jos" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Bucium" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Metes" },
  { nume: "Vălișoara", simplu: "Valisoara", comuna: "Livezile" },
  { nume: "Vâltori", simplu: "Valtori", comuna: "Vadu Motilor" },
  { nume: "Vâltori", simplu: "Valtori", comuna: "Zlatna" },
  { nume: "Vama Seacă", simplu: "Vama Seaca", comuna: "Hoparta" },
  { nume: "Vanvucești", simplu: "Vanvucesti", comuna: "Arieseni" },
  { nume: "Vârși-Rontu", simplu: "Varsi-Rontu", comuna: "Bistra" },
  { nume: "Vârși", simplu: "Varsi", comuna: "Campeni" },
  { nume: "Vârșii Mari", simplu: "Varsii Mari", comuna: "Bistra" },
  { nume: "Vârșii Mici", simplu: "Varsii Mici", comuna: "Bistra" },
  { nume: "Vârtănești", simplu: "Vartanesti", comuna: "Vidra" },
  { nume: "Vârtop", simplu: "Vartop", comuna: "Rosia Montana" },
  { nume: "Văsești", simplu: "Vasesti", comuna: "Vidra" },
  { nume: "Verdești", simplu: "Verdesti", comuna: "Avram Iancu" },
  { nume: "Veseuș", simplu: "Veseus", comuna: "Jidvei" },
  { nume: "Veza", comuna: "Blaj" },
  { nume: "Vidolm", comuna: "Ocolis" },
  { nume: "Vidra" },
  { nume: "Vidrișoara", simplu: "Vidrisoara", comuna: "Avram Iancu" },
  { nume: "Viezuri", comuna: "Ceru-Bacainti" },
  { nume: "Vinerea", comuna: "Cugir" },
  { nume: "Vingard", comuna: "Spring" },
  { nume: "Vința", simplu: "Vinta", comuna: "Lupsa" },
  { nume: "Vințu de Jos", simplu: "Vintu de Jos" },
  { nume: "Vlădești", simplu: "Vladesti", comuna: "Ramet" },
  { nume: "Vlădoșești", simplu: "Vladosesti", comuna: "Sohodol" },
  { nume: "Vulcan", comuna: "Ciuruleasa" },
  { nume: "Vurpăr", simplu: "Vurpar", comuna: "Vintu De Jos" },
  { nume: "Zăgriș", simplu: "Zagris", comuna: "Galda De Jos" },
  { nume: "Zânzești", simplu: "Zanzesti", comuna: "Horea" },
  { nume: "Zărieș", simplu: "Zaries", comuna: "Mihalt" },
  { nume: "Zlatna" },
];
