export const ab = [
  { nume: "Abrud", coo: { lat: '', lon: ''} },
  { nume: "Aiud" },
  { nume: "Aiudul de Sus", comuna: "Aiud" },
  { nume: "Alba Iulia", coo: { lat: '', lon: ''} },
  { nume: "Albac" },
  { nume: "Almasu Mare" },
  { nume: "Arieseni" },
  { nume: "Avram Iancu" },
  { nume: "Baia de Aries" },
  { nume: "Berghin" },
  { nume: "Bistra" },
  { nume: "Blaj" },
  { nume: "Blandiana" },
  { nume: "Bucium" },
  { nume: "Cenade" },
  { nume: "Ceru-Bacainti" },
  { nume: "Cetatea de Balta" },
  { nume: "Ciugud" },
  { nume: "Ciuruleasa" },
  { nume: "Cricau" },
  { nume: "Craciunelu de Jos" },
  { nume: "Cugir" },
  { nume: "Calnic" },
  { nume: "Campeni" },
  { nume: "Daia Romana" },
  { nume: "Dostat" },
  { nume: "Farau" },
  { nume: "Galda de Jos" },
  { nume: "Garda de Sus" },
  { nume: "Garbova" },
  { nume: "Hoparta" },
  { nume: "Horea" },
  { nume: "Ighiu" },
  { nume: "Intregalde" },
  { nume: "Jidvei" },
  { nume: "Livezile" },
  { nume: "Lopadea Noua" },
  { nume: "Lunca Muresului" },
  { nume: "Lupsa" },
  { nume: "Metes" },
  { nume: "Mihalt" },
  { nume: "Miraslau" },
  { nume: "Mogos" },
  { nume: "Noslac" },
  { nume: "Ocna Mures" },
  { nume: "Ocolis" },
  { nume: "Ohaba" },
  { nume: "Poiana Vadului" },
  { nume: "Ponor" },
  { nume: "Rosia Montana" },
  { nume: "Rosia de Secas" },
  { nume: "Rametea" },
  { nume: "Ramet" },
  { nume: "Radesti" },
  { nume: "Salistea" },
  { nume: "Sancel" },
  { nume: "Santimbru" },
  { nume: "Sasciori" },
  { nume: "Scarisoara" },
  { nume: "Sebes" },
  { nume: "Sibot" },
  { nume: "Sohodol" },
  { nume: "Sona" },
  { nume: "Spring" },
  { nume: "Stremt" },
  { nume: "Sugag" },
  { nume: "Teius" },
  { nume: "Unirea" },
  { nume: "Vadu Motilor" },
  { nume: "Valea Lunga" },
  { nume: "Vidra" },
  { nume: "Vintu de Jos" },
  { nume: "Zlatna" },
  { nume: "Abrud-Sat", comuna: "Abrud" },
  { nume: "Gura Cornei", comuna: "Abrud" },
  { nume: "Soharu", comuna: "Abrud" },
  { nume: "Ciumbrud", comuna: "Aiud" },
  { nume: "Gambas", comuna: "Aiud" },
  { nume: "Garbova de Jos", comuna: "Aiud" },
  { nume: "Garbova de Sus", comuna: "Aiud" },
  { nume: "Garbovita", comuna: "Aiud" },
  { nume: "Magina", comuna: "Aiud" },
  { nume: "Pagida", comuna: "Aiud" },
  { nume: "Sancrai", comuna: "Aiud" },
  { nume: "Tifra", comuna: "Aiud" },
  { nume: "Barabant", comuna: "Alba Iulia" },
  { nume: "Micesti", comuna: "Alba Iulia" },
  { nume: "Oarda", comuna: "Alba Iulia" },
  { nume: "Paclisa", comuna: "Alba Iulia" },
  { nume: "Budaiesti", comuna: "Albac" },
  { nume: "Barasti", comuna: "Albac" },
  { nume: "Cionesti", comuna: "Albac" },
  { nume: "Costesti", comuna: "Albac" },
  { nume: "Dealu Lamasoi", comuna: "Albac" },
  { nume: "Deve", comuna: "Albac" },
  { nume: "Dupa Plese", comuna: "Albac" },
  { nume: "Fata", comuna: "Albac" },
  { nume: "Plesesti", comuna: "Albac" },
  { nume: "Potionci", comuna: "Albac" },
  { nume: "Rogoz", comuna: "Albac" },
  { nume: "Rosesti", comuna: "Albac" },
  { nume: "Rusesti", comuna: "Albac" },
  { nume: "Sohodol", comuna: "Albac" },
  { nume: "Tamboresti", comuna: "Albac" },
  { nume: "Almasu de Mijloc", comuna: "Almasu Mare" },
  { nume: "Bradet", comuna: "Almasu Mare" },
  { nume: "Cheile Cibului", comuna: "Almasu Mare" },
  { nume: "Cib", comuna: "Almasu Mare" },
  { nume: "Glod", comuna: "Almasu Mare" },
  { nume: "Nadastia", comuna: "Almasu Mare" },
  { nume: "Avramesti", comuna: "Arieseni" },
  { nume: "Bubesti", comuna: "Arieseni" },
  { nume: "Casa de Piatra", comuna: "Arieseni" },
  { nume: "Cobles", comuna: "Arieseni" },
  { nume: "Dealu Bajului", comuna: "Arieseni" },
  { nume: "Fata Cristesei", comuna: "Arieseni" },
  { nume: "Fata Lapusului", comuna: "Arieseni" },
  { nume: "Galbena", comuna: "Arieseni" },
  { nume: "Hodobana", comuna: "Arieseni" },
  { nume: "Izlaz", comuna: "Arieseni" },
  { nume: "Poienita", comuna: "Arieseni" },
  { nume: "Pantesti", comuna: "Arieseni" },
  { nume: "Patrahaitesti", comuna: "Arieseni" },
  { nume: "Ravicesti", comuna: "Arieseni" },
  { nume: "Sturu", comuna: "Arieseni" },
  { nume: "Vanvucesti", comuna: "Arieseni" },
  { nume: "Stei-Arieseni", comuna: "Arieseni" },
  { nume: "Achimetesti", comuna: "Avram Iancu" },
  { nume: "Avramesti", comuna: "Avram Iancu" },
  { nume: "Boldesti", comuna: "Avram Iancu" },
  { nume: "Badai", comuna: "Avram Iancu" },
  { nume: "Cocesti", comuna: "Avram Iancu" },
  { nume: "Cocosesti", comuna: "Avram Iancu" },
  { nume: "Coroiesti", comuna: "Avram Iancu" },
  { nume: "Candesti", comuna: "Avram Iancu" },
  { nume: "Carasti", comuna: "Avram Iancu" },
  { nume: "Cartulesti", comuna: "Avram Iancu" },
  { nume: "Calugaresti", comuna: "Avram Iancu" },
  { nume: "Casoaia", comuna: "Avram Iancu" },
  { nume: "Dealu Crisului", comuna: "Avram Iancu" },
  { nume: "Dolesti", comuna: "Avram Iancu" },
  { nume: "Dumacesti", comuna: "Avram Iancu" },
  { nume: "Gojeiesti", comuna: "Avram Iancu" },
  { nume: "Heleresti", comuna: "Avram Iancu" },
  { nume: "Incesti", comuna: "Avram Iancu" },
  { nume: "Jojei", comuna: "Avram Iancu" },
  { nume: "Martesti", comuna: "Avram Iancu" },
  { nume: "Orgesti", comuna: "Avram Iancu" },
  { nume: "Plai", comuna: "Avram Iancu" },
  { nume: "Puselesti", comuna: "Avram Iancu" },
  { nume: "Patrutesti", comuna: "Avram Iancu" },
  { nume: "Tarsa", comuna: "Avram Iancu" },
  { nume: "Tarsa-Plai", comuna: "Avram Iancu" },
  { nume: "Valea Maciului", comuna: "Avram Iancu" },
  { nume: "Valea Utului", comuna: "Avram Iancu" },
  { nume: "Verdesti", comuna: "Avram Iancu" },
  { nume: "Vidrisoara", comuna: "Avram Iancu" },
  { nume: "Soicesti", comuna: "Avram Iancu" },
  { nume: "Stertesti", comuna: "Avram Iancu" },
  { nume: "Brazesti", comuna: "Baia De Aries" },
  { nume: "Cioara de Sus", comuna: "Baia De Aries" },
  { nume: "Muncelu", comuna: "Baia De Aries" },
  { nume: "Sartas", comuna: "Baia De Aries" },
  { nume: "Simulesti", comuna: "Baia De Aries" },
  { nume: "Ghirbom", comuna: "Berghin" },
  { nume: "Henig", comuna: "Berghin" },
  { nume: "Straja", comuna: "Berghin" },
  { nume: "Aronesti", comuna: "Bistra" },
  { nume: "Barlesti", comuna: "Bistra" },
  { nume: "Balesti", comuna: "Bistra" },
  { nume: "Balesti-Catun", comuna: "Bistra" },
  { nume: "Cheleteni", comuna: "Bistra" },
  { nume: "Ciuldesti", comuna: "Bistra" },
  { nume: "Cretesti", comuna: "Bistra" },
  { nume: "Dealu Muntelui", comuna: "Bistra" },
  { nume: "Durasti", comuna: "Bistra" },
  { nume: "Dambureni", comuna: "Bistra" },
  { nume: "Garde", comuna: "Bistra" },
  { nume: "Ganesti", comuna: "Bistra" },
  { nume: "Hodisesti", comuna: "Bistra" },
  { nume: "Hudricesti", comuna: "Bistra" },
  { nume: "Lipaia", comuna: "Bistra" },
  { nume: "Lunca Larga", comuna: "Bistra" },
  { nume: "Lunca Merilor", comuna: "Bistra" },
  { nume: "Mihaiesti", comuna: "Bistra" },
  { nume: "Novacesti", comuna: "Bistra" },
  { nume: "Namas", comuna: "Bistra" },
  { nume: "Perjesti", comuna: "Bistra" },
  { nume: "Poiana", comuna: "Bistra" },
  { nume: "Poiu", comuna: "Bistra" },
  { nume: "Runcuri", comuna: "Bistra" },
  { nume: "Ratitis", comuna: "Bistra" },
  { nume: "Salagesti", comuna: "Bistra" },
  { nume: "Tolacesti", comuna: "Bistra" },
  { nume: "Tomnatec", comuna: "Bistra" },
  { nume: "Trisoresti", comuna: "Bistra" },
  { nume: "Varsi-Rontu", comuna: "Bistra" },
  { nume: "Varsii Mari", comuna: "Bistra" },
  { nume: "Varsii Mici", comuna: "Bistra" },
  { nume: "Stefanca", comuna: "Bistra" },
  { nume: "Taranesti", comuna: "Bistra" },
  { nume: "Deleni-Obarsie", comuna: "Blaj" },
  { nume: "Flitesti", comuna: "Blaj" },
  { nume: "Izvoarele", comuna: "Blaj" },
  { nume: "Manarade", comuna: "Blaj" },
  { nume: "Petrisat", comuna: "Blaj" },
  { nume: "Spatac", comuna: "Blaj" },
  { nume: "Tiur", comuna: "Blaj" },
  { nume: "Veza", comuna: "Blaj" },
  { nume: "Acmariu", comuna: "Blandiana" },
  { nume: "Ibru", comuna: "Blandiana" },
  { nume: "Poieni", comuna: "Blandiana" },
  { nume: "Racatau", comuna: "Blandiana" },
  { nume: "Anghelesti", comuna: "Bucium" },
  { nume: "Bisericani", comuna: "Bucium" },
  { nume: "Bucium-Sat", comuna: "Bucium" },
  { nume: "Cerbu", comuna: "Bucium" },
  { nume: "Ciuculesti", comuna: "Bucium" },
  { nume: "Coleseni", comuna: "Bucium" },
  { nume: "Dogaresti", comuna: "Bucium" },
  { nume: "Feresti", comuna: "Bucium" },
  { nume: "Floresti", comuna: "Bucium" },
  { nume: "Gura Izbitei", comuna: "Bucium" },
  { nume: "Helesti", comuna: "Bucium" },
  { nume: "Izbicioara", comuna: "Bucium" },
  { nume: "Izbita", comuna: "Bucium" },
  { nume: "Jurcuiesti", comuna: "Bucium" },
  { nume: "Lupulesti", comuna: "Bucium" },
  { nume: "Muntari", comuna: "Bucium" },
  { nume: "Magura", comuna: "Bucium" },
  { nume: "Petreni", comuna: "Bucium" },
  { nume: "Poiana", comuna: "Bucium" },
  { nume: "Poieni", comuna: "Bucium" },
  { nume: "Stalnisoara", comuna: "Bucium" },
  { nume: "Valea Abruzel", comuna: "Bucium" },
  { nume: "Valea Alba", comuna: "Bucium" },
  { nume: "Valea Cerbului", comuna: "Bucium" },
  { nume: "Valea Negrilesii", comuna: "Bucium" },
  { nume: "Valea Poienii", comuna: "Bucium" },
  { nume: "Valea sesii", comuna: "Bucium" },
  { nume: "Valcea", comuna: "Bucium" },
  { nume: "Valeni", comuna: "Bucium" },
  { nume: "Cut", comuna: "Calnic" },
  { nume: "Deal", comuna: "Calnic" },
  { nume: "Boncesti", comuna: "Campeni" },
  { nume: "Borlesti", comuna: "Campeni" },
  { nume: "Vurpar", comuna: "Vintu De Jos" },
  { nume: "Botesti", comuna: "Campeni" },
  { nume: "Certege", comuna: "Campeni" },
  { nume: "Coasta Vascului", comuna: "Campeni" },
  { nume: "Dealu Bistrii", comuna: "Campeni" },
  { nume: "Dealu Capsei", comuna: "Campeni" },
  { nume: "Dric", comuna: "Campeni" },
  { nume: "Dandut", comuna: "Campeni" },
  { nume: "Fata Abrudului", comuna: "Campeni" },
  { nume: "Floresti", comuna: "Campeni" },
  { nume: "Furduiesti", comuna: "Campeni" },
  { nume: "Mihoesti", comuna: "Campeni" },
  { nume: "Motorasti", comuna: "Campeni" },
  { nume: "Peste Valea Bistrii", comuna: "Campeni" },
  { nume: "Poduri", comuna: "Campeni" },
  { nume: "Sorlita", comuna: "Campeni" },
  { nume: "Tomusesti", comuna: "Campeni" },
  { nume: "Valea Bistrii", comuna: "Campeni" },
  { nume: "Valea Caselor", comuna: "Campeni" },
  { nume: "Varsi", comuna: "Campeni" },
  { nume: "Capu Dealului", comuna: "Cenade" },
  { nume: "Gorgan", comuna: "Cenade" },
  { nume: "Cergau Mare", comuna: "Cergau" },
  { nume: "Cergau Mic", comuna: "Cergau" },
  { nume: "Lupu", comuna: "Cergau" },
  { nume: "Bolovanesti", comuna: "Ceru-Bacainti" },
  { nume: "Bulbuc", comuna: "Ceru-Bacainti" },
  { nume: "Cucuta", comuna: "Ceru-Bacainti" },
  { nume: "Curpeni", comuna: "Ceru-Bacainti" },
  { nume: "Dumbravita", comuna: "Ceru-Bacainti" },
  { nume: "Fantanele", comuna: "Ceru-Bacainti" },
  { nume: "Grosi", comuna: "Ceru-Bacainti" },
  { nume: "Valea Mare", comuna: "Ceru-Bacainti" },
  { nume: "Viezuri", comuna: "Ceru-Bacainti" },
  { nume: "Craciunelu de Sus", comuna: "Cetatea De Balta" },
  { nume: "Santamarie", comuna: "Cetatea De Balta" },
  { nume: "Tatarlaua", comuna: "Cetatea De Balta" },
  { nume: "Drambar", comuna: "Ciugud" },
  { nume: "Hapria", comuna: "Ciugud" },
  { nume: "Limba", comuna: "Ciugud" },
  { nume: "Teleac", comuna: "Ciugud" },
  { nume: "Seusa", comuna: "Ciugud" },
  { nume: "Bidigesti", comuna: "Ciuruleasa" },
  { nume: "Cornu", comuna: "Craciunelu De Jos" },
  { nume: "Bodresti", comuna: "Ciuruleasa" },
  { nume: "Buninginea", comuna: "Ciuruleasa" },
  { nume: "Boglesti", comuna: "Ciuruleasa" },
  { nume: "Ghedulesti", comuna: "Ciuruleasa" },
  { nume: "Moraresti", comuna: "Ciuruleasa" },
  { nume: "Matisesti", comuna: "Ciuruleasa" },
  { nume: "Vulcan", comuna: "Ciuruleasa" },
  { nume: "Bucerdea Granoasa", comuna: "Craciunelu De Jos" },
  { nume: "Panca", comuna: "Craciunelu De Jos" },
  { nume: "Padure", comuna: "Craciunelu De Jos" },
  { nume: "Craiva", comuna: "Cricau" },
  { nume: "Calene", comuna: "Cugir" },
  { nume: "Bocsitura", comuna: "Cugir" },
  { nume: "Bucuru", comuna: "Cugir" },
  { nume: "Feteni", comuna: "Cugir" },
  { nume: "Goasele", comuna: "Cugir" },
  { nume: "Mugesti", comuna: "Cugir" },
  { nume: "Boz", comuna: "Dostat" },
  { nume: "Tibru", comuna: "Cricau" },
  { nume: "Dealu Dostatului", comuna: "Dostat" },
  { nume: "Heria", comuna: "Farau" },
  { nume: "Medves", comuna: "Farau" },
  { nume: "Sanbenedic", comuna: "Farau" },
  { nume: "Silea", comuna: "Farau" },
  { nume: "Benic", comuna: "Galda De Jos" },
  { nume: "Vinerea", comuna: "Cugir" },
  { nume: "Cetea", comuna: "Galda De Jos" },
  { nume: "Galda de Sus", comuna: "Galda De Jos" },
  { nume: "Lupseni", comuna: "Galda De Jos" },
  { nume: "Mesentea", comuna: "Galda De Jos" },
  { nume: "Magura", comuna: "Galda De Jos" },
  { nume: "Oiejdea", comuna: "Galda De Jos" },
  { nume: "Poiana Galdei", comuna: "Galda De Jos" },
  { nume: "Raicani", comuna: "Galda De Jos" },
  { nume: "Zagris", comuna: "Galda De Jos" },
  { nume: "Carpinis", comuna: "Garbova" },
  { nume: "Reciu", comuna: "Garbova" },
  { nume: "Biharia", comuna: "Garda De Sus" },
  { nume: "Dealu Frumos", comuna: "Garda De Sus" },
  { nume: "Dealu Ordancusii", comuna: "Garda De Sus" },
  { nume: "Dobresti", comuna: "Garda De Sus" },
  { nume: "Ghetari", comuna: "Garda De Sus" },
  { nume: "Garda Seaca", comuna: "Garda De Sus" },
  { nume: "Hanasesti", comuna: "Garda De Sus" },
  { nume: "Huzaresti", comuna: "Garda De Sus" },
  { nume: "Izvoarele", comuna: "Garda De Sus" },
  { nume: "Mununa", comuna: "Garda De Sus" },
  { nume: "Ocoale", comuna: "Garda De Sus" },
  { nume: "Plai", comuna: "Garda De Sus" },
  { nume: "Plisti", comuna: "Garda De Sus" },
  { nume: "Scoarta", comuna: "Garda De Sus" },
  { nume: "Snide", comuna: "Garda De Sus" },
  { nume: "Sucesti", comuna: "Garda De Sus" },
  { nume: "Silivas", comuna: "Hoparta" },
  { nume: "Turdas", comuna: "Hoparta" },
  { nume: "Vama Seaca", comuna: "Hoparta" },
  { nume: "Spalnaca", comuna: "Hoparta" },
  { nume: "Baba", comuna: "Horea" },
  { nume: "Butesti", comuna: "Horea" },
  { nume: "Darlesti", comuna: "Horea" },
  { nume: "Fericet", comuna: "Horea" },
  { nume: "Giurgiut", comuna: "Horea" },
  { nume: "Mancesti", comuna: "Horea" },
  { nume: "Matisesti", comuna: "Horea" },
  { nume: "Niculesti", comuna: "Horea" },
  { nume: "Petreasa", comuna: "Horea" },
  { nume: "Preluca", comuna: "Horea" },
  { nume: "Patrusesti", comuna: "Horea" },
  { nume: "Teiu", comuna: "Horea" },
  { nume: "Trifesti", comuna: "Horea" },
  { nume: "Zanzesti", comuna: "Horea" },
  { nume: "Bucerdea Vanoasa", comuna: "Ighiu" },
  { nume: "Ighiel", comuna: "Ighiu" },
  { nume: "Sard", comuna: "Ighiu" },
  { nume: "Telna", comuna: "Ighiu" },
  { nume: "Dealu Geoagiului", comuna: "Intregalde" },
  { nume: "Ghioncani", comuna: "Intregalde" },
  { nume: "Iliesti", comuna: "Intregalde" },
  { nume: "Ivanis", comuna: "Intregalde" },
  { nume: "Modolesti", comuna: "Intregalde" },
  { nume: "Marinesti", comuna: "Intregalde" },
  { nume: "Necrilesti", comuna: "Intregalde" },
  { nume: "Popesti", comuna: "Intregalde" },
  { nume: "Sfarcea", comuna: "Intregalde" },
  { nume: "Tecsesti", comuna: "Intregalde" },
  { nume: "Balcaciu", comuna: "Jidvei" },
  { nume: "Capalna de Jos", comuna: "Jidvei" },
  { nume: "Feisa", comuna: "Jidvei" },
  { nume: "Veseus", comuna: "Jidvei" },
  { nume: "Izvoarele", comuna: "Livezile" },
  { nume: "Poiana Aiudului", comuna: "Livezile" },
  { nume: "Valisoara", comuna: "Livezile" },
  { nume: "Asinip", comuna: "Lopadea Noua" },
  { nume: "Beta", comuna: "Lopadea Noua" },
  { nume: "Bagau", comuna: "Lopadea Noua" },
  { nume: "Cicard", comuna: "Lopadea Noua" },
  { nume: "Ciuguzel", comuna: "Lopadea Noua" },
  { nume: "Ocnisoara", comuna: "Lopadea Noua" },
  { nume: "Odverem", comuna: "Lopadea Noua" },
  { nume: "Gura Ariesului", comuna: "Lunca Muresului" },
  { nume: "Bardesti", comuna: "Lupsa" },
  { nume: "Barzan", comuna: "Lupsa" },
  { nume: "Curmatura", comuna: "Lupsa" },
  { nume: "Dupa Deal", comuna: "Lupsa" },
  { nume: "Geamana", comuna: "Lupsa" },
  { nume: "Holobani", comuna: "Lupsa" },
  { nume: "Hadarau", comuna: "Lupsa" },
  { nume: "Lazuri", comuna: "Lupsa" },
  { nume: "Lunca", comuna: "Lupsa" },
  { nume: "Musca", comuna: "Lupsa" },
  { nume: "Manastire", comuna: "Lupsa" },
  { nume: "Margaia", comuna: "Lupsa" },
  { nume: "Pitiga", comuna: "Lupsa" },
  { nume: "Posogani", comuna: "Lupsa" },
  { nume: "Parau-Carbunari", comuna: "Lupsa" },
  { nume: "Trifesti", comuna: "Lupsa" },
  { nume: "Valea Holhorii", comuna: "Lupsa" },
  { nume: "Valea Lupsii", comuna: "Lupsa" },
  { nume: "Valea sesii", comuna: "Lupsa" },
  { nume: "Vinta", comuna: "Lupsa" },
  { nume: "Vai", comuna: "Lupsa" },
  { nume: "Sasa", comuna: "Lupsa" },
  { nume: "Ampoita", comuna: "Metes" },
  { nume: "Isca", comuna: "Metes" },
  { nume: "Lunca Ampoitei", comuna: "Metes" },
  { nume: "Lunca Metesului", comuna: "Metes" },
  { nume: "Poiana Ampoiului", comuna: "Metes" },
  { nume: "Poiana Ursului", comuna: "Metes" },
  { nume: "Presaca Ampoiului", comuna: "Metes" },
  { nume: "Padurea", comuna: "Metes" },
  { nume: "Remetea", comuna: "Metes" },
  { nume: "Tauti", comuna: "Metes" },
  { nume: "Valeni", comuna: "Metes" },
  { nume: "Cistei", comuna: "Mihalt" },
  { nume: "Obreja", comuna: "Mihalt" },
  { nume: "Zaries", comuna: "Mihalt" },
  { nume: "Cicau", comuna: "Miraslau" },
  { nume: "Decea", comuna: "Miraslau" },
  { nume: "Lopadea Veche", comuna: "Miraslau" },
  { nume: "Ormenis", comuna: "Miraslau" },
  { nume: "Rachis", comuna: "Miraslau" },
  { nume: "Bocesti", comuna: "Mogos" },
  { nume: "Bogdanesti", comuna: "Mogos" },
  { nume: "Butesti", comuna: "Mogos" },
  { nume: "Barlesti", comuna: "Mogos" },
  { nume: "Barlesti-Catun", comuna: "Mogos" },
  { nume: "Barzogani", comuna: "Mogos" },
  { nume: "Barbesti", comuna: "Mogos" },
  { nume: "Cojocani", comuna: "Mogos" },
  { nume: "Cristesti", comuna: "Mogos" },
  { nume: "Mamaligani", comuna: "Mogos" },
  { nume: "Negresti", comuna: "Mogos" },
  { nume: "Oncesti", comuna: "Mogos" },
  { nume: "Poienile-Mogos", comuna: "Mogos" },
  { nume: "Tomesti", comuna: "Mogos" },
  { nume: "Valea Barnii", comuna: "Mogos" },
  { nume: "Valea Barlutesti", comuna: "Mogos" },
  { nume: "Valea Cocesti", comuna: "Mogos" },
  { nume: "Valea Giogesti", comuna: "Mogos" },
  { nume: "Valea Mlacii", comuna: "Mogos" },
  { nume: "Valea tupilor", comuna: "Mogos" },
  { nume: "Copand", comuna: "Noslac" },
  { nume: "Captalan", comuna: "Noslac" },
  { nume: "Gabud", comuna: "Noslac" },
  { nume: "Stana de Mures", comuna: "Noslac" },
  { nume: "Valea Ciuciului", comuna: "Noslac" },
  { nume: "Cisteiu de Mures", comuna: "Ocna Mures" },
  { nume: "Micoslaca", comuna: "Ocna Mures" },
  { nume: "Razboieni-Cetate", comuna: "Ocna Mures" },
  { nume: "Uioara de Jos", comuna: "Ocna Mures" },
  { nume: "Uioara de Sus", comuna: "Ocna Mures" },
  { nume: "Lunca Larga", comuna: "Ocolis" },
  { nume: "Runc", comuna: "Ocolis" },
  { nume: "Vidolm", comuna: "Ocolis" },
  { nume: "Colibi", comuna: "Ohaba" },
  { nume: "Maghierat", comuna: "Ohaba" },
  { nume: "Secasel", comuna: "Ohaba" },
  { nume: "Pianu de Jos", comuna: "Pianu" },
  { nume: "Pianu de Sus", comuna: "Pianu" },
  { nume: "Plaiuri", comuna: "Pianu" },
  { nume: "Purcareti", comuna: "Pianu" },
  { nume: "Strungari", comuna: "Pianu" },
  { nume: "Costesti", comuna: "Poiana Vadului" },
  { nume: "Duduieni", comuna: "Poiana Vadului" },
  { nume: "Fagetu de Jos", comuna: "Poiana Vadului" },
  { nume: "Fagetu de Sus", comuna: "Poiana Vadului" },
  { nume: "Hanasesti", comuna: "Poiana Vadului" },
  { nume: "Lupaiesti", comuna: "Poiana Vadului" },
  { nume: "Morcanesti", comuna: "Poiana Vadului" },
  { nume: "Petelei", comuna: "Poiana Vadului" },
  { nume: "Pastesti", comuna: "Poiana Vadului" },
  { nume: "Stanesti", comuna: "Poiana Vadului" },
  { nume: "Dupa Deal", comuna: "Ponor" },
  { nume: "Geogel", comuna: "Ponor" },
  { nume: "Macaresti", comuna: "Ponor" },
  { nume: "Vale In Jos", comuna: "Ponor" },
  { nume: "Valea Bucurului", comuna: "Ponor" },
  { nume: "Cortesti", comuna: "Posaga" },
  { nume: "Incesti", comuna: "Posaga" },
  { nume: "Lunca", comuna: "Posaga" },
  { nume: "Orasti", comuna: "Posaga" },
  { nume: "Posaga de Jos", comuna: "Posaga" },
  { nume: "Posaga de Sus", comuna: "Posaga" },
  { nume: "Sagagea", comuna: "Posaga" },
  { nume: "Leorint", comuna: "Radesti" },
  { nume: "Mescreac", comuna: "Radesti" },
  { nume: "Soimus", comuna: "Radesti" },
  { nume: "Botani", comuna: "Ramet" },
  { nume: "Bradesti", comuna: "Ramet" },
  { nume: "Cheia", comuna: "Ramet" },
  { nume: "Cotorasti", comuna: "Ramet" },
  { nume: "Floresti", comuna: "Ramet" },
  { nume: "Olteni", comuna: "Ramet" },
  { nume: "Valea Fagetului", comuna: "Ramet" },
  { nume: "Valea Inzelului", comuna: "Ramet" },
  { nume: "Valea Manastirii", comuna: "Ramet" },
  { nume: "Valea Poienii", comuna: "Ramet" },
  { nume: "Valea Uzei", comuna: "Ramet" },
  { nume: "Vladesti", comuna: "Ramet" },
  { nume: "Coltesti", comuna: "Rametea" },
  { nume: "Tau", comuna: "Rosia De Secas" },
  { nume: "Ungurei", comuna: "Rosia De Secas" },
  { nume: "Blidesti", comuna: "Rosia Montana" },
  { nume: "Bunta", comuna: "Rosia Montana" },
  { nume: "Balmosesti", comuna: "Rosia Montana" },
  { nume: "Coasta Hentii", comuna: "Rosia Montana" },
  { nume: "Corna", comuna: "Rosia Montana" },
  { nume: "Curaturi", comuna: "Rosia Montana" },
  { nume: "Carpinis", comuna: "Rosia Montana" },
  { nume: "Daroaia", comuna: "Rosia Montana" },
  { nume: "Gura Rosiei", comuna: "Rosia Montana" },
  { nume: "Garda-Barbulesti", comuna: "Rosia Montana" },
  { nume: "Iacobesti", comuna: "Rosia Montana" },
  { nume: "Ignatesti", comuna: "Rosia Montana" },
  { nume: "Vartop", comuna: "Rosia Montana" },
  { nume: "Soal", comuna: "Rosia Montana" },
  { nume: "Tarina", comuna: "Rosia Montana" },
  { nume: "Dealu Caselor", comuna: "Salciua" },
  { nume: "Dumesti", comuna: "Salciua" },
  { nume: "Sub Piatra", comuna: "Salciua" },
  { nume: "Salciua de Jos", comuna: "Salciua" },
  { nume: "Salciua de Sus", comuna: "Salciua" },
  { nume: "Valea Larga", comuna: "Salciua" },
  { nume: "Margineni", comuna: "Salistea" },
  { nume: "Salistea-Deal", comuna: "Salistea" },
  { nume: "Tartaria", comuna: "Salistea" },
  { nume: "Iclod", comuna: "Sancel" },
  { nume: "Panade", comuna: "Sancel" },
  { nume: "Coslariu", comuna: "Santimbru" },
  { nume: "Dumitra", comuna: "Santimbru" },
  { nume: "Galtiu", comuna: "Santimbru" },
  { nume: "Totoi", comuna: "Santimbru" },
  { nume: "Capalna", comuna: "Sasciori" },
  { nume: "Dumbrava", comuna: "Sasciori" },
  { nume: "Laz", comuna: "Sasciori" },
  { nume: "Loman", comuna: "Sasciori" },
  { nume: "Plesi", comuna: "Sasciori" },
  { nume: "Rachita", comuna: "Sasciori" },
  { nume: "Sebesel", comuna: "Sasciori" },
  { nume: "Tonea", comuna: "Sasciori" },
  { nume: "Botesti", comuna: "Scarisoara" },
  { nume: "Barlesti", comuna: "Scarisoara" },
  { nume: "Fata-Lazesti", comuna: "Scarisoara" },
  { nume: "Floresti", comuna: "Scarisoara" },
  { nume: "Lespezea", comuna: "Scarisoara" },
  { nume: "Lazesti", comuna: "Scarisoara" },
  { nume: "Matei", comuna: "Scarisoara" },
  { nume: "Negesti", comuna: "Scarisoara" },
  { nume: "Preluca", comuna: "Scarisoara" },
  { nume: "Runc", comuna: "Scarisoara" },
  { nume: "Sfoartea", comuna: "Scarisoara" },
  { nume: "Trancesti", comuna: "Scarisoara" },
  { nume: "Stiuleti", comuna: "Scarisoara" },
  { nume: "Lancram", comuna: "Sebes" },
  { nume: "Petresti", comuna: "Sebes" },
  { nume: "Rahau", comuna: "Sebes" },
  { nume: "Balomiru de Camp", comuna: "Sibot" },
  { nume: "Bacainti", comuna: "Sibot" },
  { nume: "Saracsau", comuna: "Sibot" },
  { nume: "Bilanesti", comuna: "Sohodol" },
  { nume: "Bobaresti", comuna: "Sohodol" },
  { nume: "Bradeana", comuna: "Sohodol" },
  { nume: "Burzonesti", comuna: "Sohodol" },
  { nume: "Bazesti", comuna: "Sohodol" },
  { nume: "Deoncesti", comuna: "Sohodol" },
  { nume: "Dilimani", comuna: "Sohodol" },
  { nume: "Furduiesti", comuna: "Sohodol" },
  { nume: "Gura Sohodol", comuna: "Sohodol" },
  { nume: "Hoanca", comuna: "Sohodol" },
  { nume: "Joldisesti", comuna: "Sohodol" },
  { nume: "Lazuri", comuna: "Sohodol" },
  { nume: "Lehesti", comuna: "Sohodol" },
  { nume: "Luminesti", comuna: "Sohodol" },
  { nume: "Medresti", comuna: "Sohodol" },
  { nume: "Moraresti", comuna: "Sohodol" },
  { nume: "Munesti", comuna: "Sohodol" },
  { nume: "Nelegesti", comuna: "Sohodol" },
  { nume: "Nicoresti", comuna: "Sohodol" },
  { nume: "Napaiesti", comuna: "Sohodol" },
  { nume: "Peles", comuna: "Sohodol" },
  { nume: "Poiana", comuna: "Sohodol" },
  { nume: "Robesti", comuna: "Sohodol" },
  { nume: "Sebisesti", comuna: "Sohodol" },
  { nume: "Sicoiesti", comuna: "Sohodol" },
  { nume: "Surdesti", comuna: "Sohodol" },
  { nume: "Toci", comuna: "Sohodol" },
  { nume: "Valea Verde", comuna: "Sohodol" },
  { nume: "Vladosesti", comuna: "Sohodol" },
  { nume: "Simocesti", comuna: "Sohodol" },
  { nume: "Alecus", comuna: "Sona" },
  { nume: "Biia", comuna: "Sona" },
  { nume: "Doptau", comuna: "Sona" },
  { nume: "Lunca Tarnavei", comuna: "Sona" },
  { nume: "Sanmiclaus", comuna: "Sona" },
  { nume: "Valea Sasului", comuna: "Sona" },
  { nume: "Carpen", comuna: "Spring" },
  { nume: "Carpenii de Sus", comuna: "Spring" },
  { nume: "Cunta", comuna: "Spring" },
  { nume: "Drasov", comuna: "Spring" },
  { nume: "Vingard", comuna: "Spring" },
  { nume: "Fata Pietrii", comuna: "Stremt" },
  { nume: "Geoagiu de Sus", comuna: "Stremt" },
  { nume: "Geomal", comuna: "Stremt" },
  { nume: "Arti", comuna: "Sugag" },
  { nume: "Barsana", comuna: "Sugag" },
  { nume: "Dobra", comuna: "Sugag" },
  { nume: "Jidostina", comuna: "Sugag" },
  { nume: "Martinie", comuna: "Sugag" },
  { nume: "Tau Bistra", comuna: "Sugag" },
  { nume: "Beldiu", comuna: "Teius" },
  { nume: "Coslariu Nou", comuna: "Teius" },
  { nume: "Capud", comuna: "Teius" },
  { nume: "Petelca", comuna: "Teius" },
  { nume: "Ciugudu de Jos", comuna: "Unirea" },
  { nume: "Ciugudu de Sus", comuna: "Unirea" },
  { nume: "Dumbrava", comuna: "Unirea" },
  { nume: "Inoc", comuna: "Unirea" },
  { nume: "Mahaceni", comuna: "Unirea" },
  { nume: "Bodesti", comuna: "Vadu Motilor" },
  { nume: "Burzesti", comuna: "Vadu Motilor" },
  { nume: "Dealu Frumos", comuna: "Vadu Motilor" },
  { nume: "Lazesti", comuna: "Vadu Motilor" },
  { nume: "Necsesti", comuna: "Vadu Motilor" },
  { nume: "Poduri-Bricesti", comuna: "Vadu Motilor" },
  { nume: "Popestii de Jos", comuna: "Vadu Motilor" },
  { nume: "Popestii de Sus", comuna: "Vadu Motilor" },
  { nume: "Tomutesti", comuna: "Vadu Motilor" },
  { nume: "Totesti", comuna: "Vadu Motilor" },
  { nume: "Valtori", comuna: "Vadu Motilor" },
  { nume: "Faget", comuna: "Valea Lunga" },
  { nume: "Glogovet", comuna: "Valea Lunga" },
  { nume: "Lodroman", comuna: "Valea Lunga" },
  { nume: "Lunca", comuna: "Valea Lunga" },
  { nume: "Tauni", comuna: "Valea Lunga" },
  { nume: "Bobaresti", comuna: "Vidra" },
  { nume: "Bogdanesti", comuna: "Vidra" },
  { nume: "Bordestii Poieni", comuna: "Vidra" },
  { nume: "Bai", comuna: "Vidra" },
  { nume: "Culdesti", comuna: "Vidra" },
  { nume: "Dealu Goiesti", comuna: "Vidra" },
  { nume: "Dos", comuna: "Vidra" },
  { nume: "Dosu Luncii", comuna: "Vidra" },
  { nume: "Dosu Vasesti", comuna: "Vidra" },
  { nume: "Dragoiesti-Lunca", comuna: "Vidra" },
  { nume: "Ficaresti", comuna: "Vidra" },
  { nume: "Gligoresti", comuna: "Vidra" },
  { nume: "Goiesti", comuna: "Vidra" },
  { nume: "Haiducesti", comuna: "Vidra" },
  { nume: "Hoanca", comuna: "Vidra" },
  { nume: "Harasti", comuna: "Vidra" },
  { nume: "Jeflesti", comuna: "Vidra" },
  { nume: "Lunca", comuna: "Vidra" },
  { nume: "Lunca Bisericii", comuna: "Vidra" },
  { nume: "Lunca Goiesti", comuna: "Vidra" },
  { nume: "Lunca Vesesti", comuna: "Vidra" },
  { nume: "Lunca de Jos", comuna: "Vidra" },
  { nume: "Modolesti", comuna: "Vidra" },
  { nume: "Nemesi", comuna: "Vidra" },
  { nume: "Oidesti", comuna: "Vidra" },
  { nume: "Pitarcesti", comuna: "Vidra" },
  { nume: "Plescuta", comuna: "Vidra" },
  { nume: "Poieni", comuna: "Vidra" },
  { nume: "Ponorel", comuna: "Vidra" },
  { nume: "Puiuletesti", comuna: "Vidra" },
  { nume: "Runc", comuna: "Vidra" },
  { nume: "Segaj", comuna: "Vidra" },
  { nume: "Urdes", comuna: "Vidra" },
  { nume: "Valea Morii", comuna: "Vidra" },
  { nume: "Valcesti", comuna: "Vidra" },
  { nume: "Valcaneasa", comuna: "Vidra" },
  { nume: "Valtori", comuna: "Zlatna" },
  { nume: "Vartanesti", comuna: "Vidra" },
  { nume: "Vasesti", comuna: "Vidra" },
  { nume: "Ciocasu", comuna: "Vintu De Jos" },
  { nume: "Criseni", comuna: "Vintu De Jos" },
  { nume: "Campu Goblii", comuna: "Vintu De Jos" },
  { nume: "Dealu Ferului", comuna: "Vintu De Jos" },
  { nume: "Gura Cutului", comuna: "Vintu De Jos" },
  { nume: "Hategana", comuna: "Vintu De Jos" },
  { nume: "Inuri", comuna: "Vintu De Jos" },
  { nume: "Laz", comuna: "Vintu De Jos" },
  { nume: "Mereteu", comuna: "Vintu De Jos" },
  { nume: "Matacina", comuna: "Vintu De Jos" },
  { nume: "Poienita", comuna: "Vintu De Jos" },
  { nume: "Parau lui Mihai", comuna: "Vintu De Jos" },
  { nume: "Stauini", comuna: "Vintu De Jos" },
  { nume: "Valea Goblii", comuna: "Vintu De Jos" },
  { nume: "Valea Vintului", comuna: "Vintu De Jos" },
  { nume: "Valea lui Mihai", comuna: "Vintu De Jos" },
  { nume: "Galati", comuna: "Zlatna" },
  { nume: "Valea Mica", comuna: "Zlatna" },
  { nume: "Botesti", comuna: "Zlatna" },
  { nume: "Budeni", comuna: "Zlatna" },
  { nume: "Izvoru Ampoiului", comuna: "Zlatna" },
  { nume: "Dealu Roatei", comuna: "Zlatna" },
  { nume: "Dobrot", comuna: "Zlatna" },
  { nume: "Dumbrava", comuna: "Zlatna" },
  { nume: "Fenes", comuna: "Zlatna" },
  { nume: "Pirita", comuna: "Zlatna" },
  { nume: "Podu lui Paul", comuna: "Zlatna" },
  { nume: "Parau Gruiului", comuna: "Zlatna" },
  { nume: "Patrangeni", comuna: "Zlatna" },
  { nume: "Runc", comuna: "Zlatna" },
  { nume: "Rusi", comuna: "Zlatna" },
  { nume: "Suseni", comuna: "Zlatna" },
  { nume: "Trampoiele", comuna: "Zlatna" },
];
