export const ar = [
  { nume: "Aciuța", simplu: "Aciuta", comuna: "Plescuta" },
  { nume: "Adea", comuna: "Sintea Mare" },
  { nume: "Agrișu Mare", simplu: "Agrisu Mare", comuna: "Tarnova" },
  { nume: "Agrișu Mic", simplu: "Agrisu Mic", comuna: "Hasmas" },
  { nume: "Aldești", simplu: "Aldesti", comuna: "Barsa" },
  { nume: "Almaș", simplu: "Almas" },
  { nume: "Aluniș", simplu: "Alunis", comuna: "Fantinele" },
  { nume: "Andrei Șaguna", simplu: "Andrei Saguna", comuna: "Zimandu Nou" },
  { nume: "Apateu" },
  { nume: "Arad" },
  { nume: "Arăneag", simplu: "Araneag", comuna: "Tarnova" },
  { nume: "Archiș", simplu: "Archis" },
  { nume: "Avram Iancu", comuna: "Cermei" },
  { nume: "Avram Iancu", comuna: "Varfurile" },
  { nume: "Bacău de Mijloc", simplu: "Bacau de Mijloc", comuna: "Bata" },
  { nume: "Baia", comuna: "Varadia De Mures" },
  { nume: "Bănești", simplu: "Banesti", comuna: "Halmagiu" },
  { nume: "Barațca", simplu: "Baratca", comuna: "Paulis" },
  { nume: "Bârsa", simplu: "Barsa" },
  { nume: "Bârzava", simplu: "Barzava" },
  { nume: "Bârzești", simplu: "Barzesti", comuna: "Archis" },
  { nume: "Bata" },
  { nume: "Bătuța", simplu: "Batuta", comuna: "Barzava" },
  { nume: "Beliu" },
  { nume: "Belotinț", simplu: "Belotint", comuna: "Conop" },
  { nume: "Benești", simplu: "Benesti", comuna: "Beliu" },
  { nume: "Berechiu", comuna: "Apateu" },
  { nume: "Berindia", comuna: "Buteni" },
  { nume: "Birchiș", simplu: "Birchis" },
  { nume: "Bochia", comuna: "Beliu" },
  { nume: "Bocsig" },
  { nume: "Bodești", simplu: "Bodesti", comuna: "Halmagiu" },
  { nume: "Bodrogu Nou", comuna: "Felnac" },
  { nume: "Bodrogu Vechi", comuna: "Pecica" },
  { nume: "Bonțești", simplu: "Bontesti", comuna: "Gurahont" },
  { nume: "Botfei", comuna: "Hasmas" },
  { nume: "Brazii" },
  { nume: "Brusturi", comuna: "Halmagiu" },
  { nume: "Bruznic", comuna: "Dorgos" },
  { nume: "Buceava-Șoimuș", simplu: "Buceava-Soimus", comuna: "Brazii" },
  { nume: "Budești", simplu: "Budesti", comuna: "Plescuta" },
  { nume: "Buhani", comuna: "Dezna" },
  { nume: "Bulci", comuna: "Bata" },
  { nume: "Buteni" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Felnac" },
  { nume: "Camna", comuna: "Silindia" },
  { nume: "Căpălnaș", simplu: "Capalnas", comuna: "Birchis" },
  { nume: "Caporal Alexa", comuna: "Santana" },
  { nume: "Căprioara", simplu: "Caprioara", comuna: "Savarsin" },
  { nume: "Căpruța", simplu: "Capruta", comuna: "Barzava" },
  { nume: "Cărand", simplu: "Carand" },
  { nume: "Cermei" },
  { nume: "Chelmac", comuna: "Conop" },
  { nume: "Chereluș", simplu: "Cherelus", comuna: "Sicula" },
  { nume: "Chesinț", simplu: "Chesint", comuna: "Zabrani" },
  { nume: "Chier", comuna: "Tarnova" },
  { nume: "Chisindia" },
  { nume: "Chișineu-Criș", simplu: "Chisineu-Cris" },
  { nume: "Chișlaca", simplu: "Chislaca", comuna: "Craiva" },
  { nume: "Cicir", comuna: "Vladimirescu" },
  { nume: "Cil", comuna: "Almas" },
  { nume: "Cintei", comuna: "Zarand" },
  { nume: "Ciuntești", simplu: "Ciuntesti", comuna: "Craiva" },
  { nume: "Cladova", comuna: "Paulis" },
  { nume: "Clit", comuna: "Hasmas" },
  { nume: "Cociuba", comuna: "Dieci" },
  { nume: "Comănești", simplu: "Comanesti", comuna: "Hasmas" },
  { nume: "Conop" },
  { nume: "Corbești", simplu: "Corbesti", comuna: "Petris" },
  { nume: "Coroi", comuna: "Craiva" },
  { nume: "Covăsinț", simplu: "Covasint" },
  { nume: "Craiva" },
  { nume: "Cristești", simplu: "Cristesti", comuna: "Halmagiu" },
  { nume: "Crocna", comuna: "Dieci" },
  { nume: "Cruceni", comuna: "Sagu" },
  { nume: "Cuiaș", simplu: "Cuias", comuna: "Savarsin" },
  { nume: "Cuied", comuna: "Buteni" },
  { nume: "Curtici" },
  { nume: "Cuveșdia", simplu: "Cuvesdia", comuna: "Sistarovat" },
  { nume: "Cuvin", comuna: "Ghioroc" },
  { nume: "Dezna" },
  { nume: "Dieci" },
  { nume: "Donceni", comuna: "Sebis" },
  { nume: "Dorgoș", simplu: "Dorgos" },
  { nume: "Dorobanți", simplu: "Dorobanti", comuna: "Curtici" },
  { nume: "Drauț", simplu: "Draut", comuna: "Tarnova" },
  { nume: "Dud", comuna: "Tarnova" },
  { nume: "Dulcele", comuna: "Gurahont" },
  { nume: "Dumbrava", comuna: "Plescuta" },
  { nume: "Dumbrăvița", simplu: "Dumbravita", comuna: "Barzava" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Fantinele" },
  { nume: "Felnac" },
  { nume: "Feniș", simplu: "Fenis", comuna: "Gurahont" },
  { nume: "Firiteaz", comuna: "Sagu" },
  { nume: "Fiscut", comuna: "Sagu" },
  { nume: "Frumușeni", simplu: "Frumuseni", comuna: "Fantinele" },
  { nume: "Galșa", simplu: "Galsa", comuna: "Siria" },
  { nume: "Ghioroc" },
  { nume: "Grăniceri", simplu: "Graniceri" },
  { nume: "Groșeni", simplu: "Groseni", comuna: "Archis" },
  { nume: "Groși", simplu: "Grosi", comuna: "Varfurile" },
  { nume: "Groșii Noi", simplu: "Grosii Noi", comuna: "Barzava" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Plescuta" },
  { nume: "Gurahonț", simplu: "Gurahont" },
  { nume: "Gurba", comuna: "Sicula" },
  { nume: "Hălăliș", simplu: "Halalis", comuna: "Savarsin" },
  { nume: "Hălmăgel", simplu: "Halmagel" },
  { nume: "Hălmagiu", simplu: "Halmagiu" },
  { nume: "Hășmaș", simplu: "Hasmas" },
  { nume: "Hodiș", simplu: "Hodis", comuna: "Barsa" },
  { nume: "Honțișor", simplu: "Hontisor", comuna: "Gurahont" },
  { nume: "Horia", comuna: "Vladimirescu" },
  { nume: "Hunedoara Timișană", simplu: "Hunedoara Timisana", comuna: "Sagu" },
  { nume: "Iacobini", comuna: "Brazii" },
  { nume: "Iercoșeni", simplu: "Iercoseni", comuna: "Silindia" },
  { nume: "Iermata Neagră", simplu: "Iermata Neagra", comuna: "Zerind" },
  { nume: "Iermata", comuna: "Seleus" },
  { nume: "Ignești", simplu: "Ignesti" },
  { nume: "Ilteu", comuna: "Petris" },
  { nume: "Ineu" },
  { nume: "Ionești", simplu: "Ionesti", comuna: "Halmagiu" },
  { nume: "Iosaș", simplu: "Iosas", comuna: "Gurahont" },
  { nume: "Iratoșu", simplu: "Iratosu" },
  { nume: "Joia Mare", comuna: "Almas" },
  { nume: "Julița", simplu: "Julita", comuna: "Varadia De Mures" },
  { nume: "Labașinț", simplu: "Labasint", comuna: "Sistarovat" },
  { nume: "Lalașinț", simplu: "Lalasint", comuna: "Barzava" },
  { nume: "Laz", comuna: "Dezna" },
  { nume: "Lazuri", comuna: "Varfurile" },
  { nume: "Leasa", comuna: "Halmagiu" },
  { nume: "Leștioara", simplu: "Lestioara", comuna: "Halmagiu" },
  { nume: "Lipova" },
  { nume: "Livada" },
  { nume: "Luguzău", simplu: "Luguzau", comuna: "Silindia" },
  { nume: "Luncșoara", simplu: "Luncsoara", comuna: "Halmagel" },
  { nume: "Lupești", simplu: "Lupesti", comuna: "Varadia De Mures" },
  { nume: "Macea" },
  { nume: "Măderat", simplu: "Maderat", comuna: "Pancota" },
  { nume: "Mădrigești", simplu: "Madrigesti", comuna: "Brazii" },
  { nume: "Măgulicea", simplu: "Magulicea", comuna: "Varfurile" },
  { nume: "Mailat", comuna: "Vinga" },
  { nume: "Mănăștur", simplu: "Manastur", comuna: "Vinga" },
  { nume: "Mândruloc", simplu: "Mandruloc", comuna: "Vladimirescu" },
  { nume: "Mânerău", simplu: "Manerau", comuna: "Bocsig" },
  { nume: "Mărăuș", simplu: "Maraus", comuna: "Craiva" },
  { nume: "Mâsca", simplu: "Masca", comuna: "Siria" },
  { nume: "Mermești", simplu: "Mermesti", comuna: "Varfurile" },
  { nume: "Milova", comuna: "Conop" },
  { nume: "Minead", comuna: "Ignesti" },
  { nume: "Miniș", simplu: "Minis", comuna: "Ghioroc" },
  { nume: "Minișel", simplu: "Minisel", comuna: "Taut" },
  { nume: "Minișu de Sus", simplu: "Minisu de Sus", comuna: "Taut" },
  { nume: "Mișca", simplu: "Misca" },
  { nume: "Mocrea", comuna: "Ineu" },
  { nume: "Moneasa" },
  { nume: "Monoroștia", simplu: "Monorostia", comuna: "Barzava" },
  { nume: "Moroda", comuna: "Seleus" },
  { nume: "Moțiori", simplu: "Motiori", comuna: "Apateu" },
  { nume: "Munar", comuna: "Secusigiu" },
  { nume: "Mustești", simplu: "Mustesti", comuna: "Gurahont" },
  { nume: "Nadab", comuna: "Chisineu-Cris" },
  { nume: "Nădălbești", simplu: "Nadalbesti", comuna: "Ignesti" },
  { nume: "Nadăș", simplu: "Nadas", comuna: "Taut" },
  { nume: "Nădlac", simplu: "Nadlac" },
  { nume: "Neagra", comuna: "Dezna" },
  { nume: "Nermiș", simplu: "Nermis", comuna: "Archis" },
  { nume: "Neudorf", comuna: "Zabrani" },
  {
    nume: "Nicolae Bălcescu",
    simplu: "Nicolae Balcescu",
    comuna: "Varadia De Mures",
  },
  { nume: "Obârșia", simplu: "Obarsia", comuna: "Petris" },
  { nume: "Odvoș", simplu: "Odvos", comuna: "Conop" },
  { nume: "Olari" },
  { nume: "Ostrov", comuna: "Birchis" },
  { nume: "Păiușeni", simplu: "Paiuseni", comuna: "Chisindia" },
  { nume: "Pâncota", simplu: "Pancota" },
  { nume: "Pârnești", simplu: "Parnesti", comuna: "Savarsin" },
  { nume: "Pătârș", simplu: "Patars", comuna: "Dorgos" },
  { nume: "Păulian", simplu: "Paulian", comuna: "Buteni" },
  { nume: "Păuliș", simplu: "Paulis" },
  { nume: "Pecica" },
  { nume: "Peregu Mare" },
  { nume: "Peregu Mic", comuna: "Peregu Mare" },
  { nume: "Pescari", comuna: "Gurahont" },
  { nume: "Petriș", simplu: "Petris" },
  { nume: "Pilu" },
  { nume: "Pleșcuța", simplu: "Plescuta" },
  { nume: "Poiana", comuna: "Varfurile" },
  { nume: "Poienari", comuna: "Halmagiu" },
  { nume: "Prunișor", simplu: "Prunisor", comuna: "Sebis" },
  { nume: "Rădești", simplu: "Radesti", comuna: "Almas" },
  { nume: "Radna", comuna: "Lipova" },
  { nume: "Rănușa", simplu: "Ranusa", comuna: "Moneasa" },
  { nume: "Răpsig", simplu: "Rapsig", comuna: "Bocsig" },
  { nume: "Revetiș", simplu: "Revetis", comuna: "Dieci" },
  { nume: "Rogoz de Beliu", comuna: "Craiva" },
  { nume: "Roșia Nouă", simplu: "Rosia Noua", comuna: "Petris" },
  { nume: "Roșia", simplu: "Rosia", comuna: "Dieci" },
  { nume: "Rostoci", comuna: "Plescuta" },
  { nume: "Șagu", simplu: "Sagu" },
  { nume: "Sălăjeni", simplu: "Salajeni", comuna: "Sebis" },
  { nume: "Sâmbăteni", simplu: "Sambateni", comuna: "Paulis" },
  { nume: "Sânleani", simplu: "Sanleani", comuna: "Livada" },
  { nume: "Sânmartin", simplu: "Sanmartin", comuna: "Macea" },
  { nume: "Sânpaul", simplu: "Sanpaul", comuna: "Sofronea" },
  { nume: "Sânpetru German", simplu: "Sanpetru German", comuna: "Secusigiu" },
  { nume: "Sântana", simplu: "Santana" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Halmagel" },
  { nume: "Satu Mare", comuna: "Secusigiu" },
  { nume: "Satu Mic", comuna: "Silindia" },
  { nume: "Satu Nou", comuna: "Misca" },
  { nume: "Săvârșin", simplu: "Savarsin" },
  { nume: "Sebiș", simplu: "Sebis" },
  { nume: "Secaci", comuna: "Beliu" },
  { nume: "Secaș", simplu: "Secas", comuna: "Brazii" },
  { nume: "Secusigiu" },
  { nume: "Sederhat", comuna: "Pecica" },
  { nume: "Șeitin", simplu: "Seitin" },
  { nume: "Seleuș", simplu: "Seleus" },
  { nume: "Seliște", simplu: "Seliste", comuna: "Petris" },
  { nume: "Seliștea", simplu: "Selistea", comuna: "Carand" },
  { nume: "Semlac" },
  { nume: "Șepreuș", simplu: "Sepreus" },
  { nume: "Șiad", simplu: "Siad", comuna: "Craiva" },
  { nume: "Șiclău", simplu: "Siclau", comuna: "Graniceri" },
  { nume: "Șicula", simplu: "Sicula" },
  { nume: "Șilindia", simplu: "Silindia" },
  { nume: "Șimand", simplu: "Simand" },
  { nume: "Sintea Mare" },
  { nume: "Sintea Mică", simplu: "Sintea Mica", comuna: "Olari" },
  { nume: "Șiria", simplu: "Siria" },
  { nume: "Șiștarovăț", simplu: "Sistarovat" },
  { nume: "Slatina de Criș", simplu: "Slatina de Cris", comuna: "Dezna" },
  { nume: "Slatina de Mureș", simplu: "Slatina de Mures", comuna: "Barzava" },
  { nume: "Socodor" },
  { nume: "Șofronea", simplu: "Sofronea" },
  { nume: "Șoimoș", simplu: "Soimos", comuna: "Lipova" },
  { nume: "Șomoșcheș", simplu: "Somosches", comuna: "Cermei" },
  { nume: "Stejar", comuna: "Varadia De Mures" },
  { nume: "Stoinești", simplu: "Stoinesti", comuna: "Craiva" },
  { nume: "Susag", comuna: "Craiva" },
  { nume: "Susani", comuna: "Ignesti" },
  { nume: "Tăgădău", simplu: "Tagadau", comuna: "Beliu" },
  { nume: "Tălagiu", simplu: "Talagiu", comuna: "Plescuta" },
  { nume: "Tălmaci", simplu: "Talmaci", comuna: "Craiva" },
  { nume: "Țărmure", simplu: "Tarmure", comuna: "Halmagiu" },
  { nume: "Târnăvița", simplu: "Tarnavita", comuna: "Halmagel" },
  { nume: "Târnova", simplu: "Tarnova" },
  { nume: "Tauț", simplu: "Taut" },
  { nume: "Țela", simplu: "Tela", comuna: "Bata" },
  { nume: "Temeșești", simplu: "Temesesti", comuna: "Savarsin" },
  { nume: "Țipar", simplu: "Tipar", comuna: "Sintea Mare" },
  { nume: "Tisa Nouă", simplu: "Tisa Noua", comuna: "Fantinele" },
  { nume: "Tisa", comuna: "Halmagiu" },
  { nume: "Toc", comuna: "Savarsin" },
  { nume: "Țohești", simplu: "Tohesti", comuna: "Halmagel" },
  { nume: "Troaș", simplu: "Troas", comuna: "Savarsin" },
  { nume: "Turnu", comuna: "Pecica" },
  { nume: "Urvișu de Beliu", simplu: "Urvisu de Beliu", comuna: "Hasmas" },
  { nume: "Ususău", simplu: "Ususau", comuna: "Dorgos" },
  { nume: "Valea Mare", comuna: "Gurahont" },
  { nume: "Valea Mare", comuna: "Savarsin" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Misca" },
  { nume: "Vărădia de Mureș", simplu: "Varadia de Mures" },
  { nume: "Vârfurile", simplu: "Varfurile" },
  { nume: "Variașu Mare", simplu: "Variasu Mare", comuna: "Iratosu" },
  { nume: "Variașu Mic", simplu: "Variasu Mic", comuna: "Iratosu" },
  { nume: "Varnița", simplu: "Varnita", comuna: "Sistarovat" },
  { nume: "Vărșand", simplu: "Varsand", comuna: "Pilu" },
  { nume: "Vasile Goldiș", simplu: "Vasile Goldis", comuna: "Beliu" },
  { nume: "Văsoaia", simplu: "Vasoaia", comuna: "Chisindia" },
  { nume: "Vidra", comuna: "Varfurile" },
  { nume: "Vinga" },
  { nume: "Virismort", comuna: "Birchis" },
  { nume: "Vladimirescu" },
  { nume: "Voivodeni", comuna: "Barsa" },
  { nume: "Zăbalț", simplu: "Zabalt", comuna: "Dorgos" },
  { nume: "Zăbrani", simplu: "Zabrani" },
  { nume: "Zădăreni", simplu: "Zadareni", comuna: "Felnac" },
  { nume: "Zărand", simplu: "Zarand" },
  { nume: "Zerind" },
  { nume: "Zerindu Mic", comuna: "Misca" },
  { nume: "Zimandcuz", comuna: "Zimandu Nou" },
  { nume: "Zimandu Nou" },
  { nume: "Zimbru", comuna: "Gurahont" },
];
