export const  ar = [
  { nume: "Almas" },
  { nume: "Apateu" },
  { nume: "Arad" },
  { nume: "Archis" },
  { nume: "Bata" },
  { nume: "Beliu" },
  { nume: "Birchis" },
  { nume: "Bocsig" },
  { nume: "Brazii" },
  { nume: "Buteni" },
  { nume: "Barsa" },
  { nume: "Barzava" },
  { nume: "Cermei" },
  { nume: "Chisindia" },
  { nume: "Chisineu-Cris" },
  { nume: "Conop" },
  { nume: "Covasint" },
  { nume: "Craiva" },
  { nume: "Curtici" },
  { nume: "Carand" },
  { nume: "Dezna" },
  { nume: "Dieci" },
  { nume: "Dorgos" },
  { nume: "Felnac" },
  { nume: "Ghioroc" },
  { nume: "Graniceri" },
  { nume: "Gurahont" },
  { nume: "Halmagiu" },
  { nume: "Halmagel" },
  { nume: "Hasmas" },
  { nume: "Ignesti" },
  { nume: "Ineu" },
  { nume: "Iratosu" },
  { nume: "Lipova" },
  { nume: "Livada" },
  { nume: "Macea" },
  { nume: "Misca" },
  { nume: "Moneasa" },
  { nume: "Nadlac" },
  { nume: "Olari" },
  { nume: "Pecica" },
  { nume: "Peregu Mare" },
  { nume: "Petris" },
  { nume: "Pilu" },
  { nume: "Plescuta" },
  { nume: "Pancota" },
  { nume: "Paulis" },
  { nume: "Sebis" },
  { nume: "Secusigiu" },
  { nume: "Seleus" },
  { nume: "Semlac" },
  { nume: "Sintea Mare" },
  { nume: "Socodor" },
  { nume: "Santana" },
  { nume: "Savarsin" },
  { nume: "Taut" },
  { nume: "Tarnova" },
  { nume: "Vinga" },
  { nume: "Vladimirescu" },
  { nume: "Varfurile" },
  { nume: "Varadia de Mures" },
  { nume: "Zerind" },
  { nume: "Zimandu Nou" },
  { nume: "Zabrani" },
  { nume: "Zarand" },
  { nume: "Sagu" },
  { nume: "Seitin" },
  { nume: "Sepreus" },
  { nume: "Sicula" },
  { nume: "Silindia" },
  { nume: "Simand" },
  { nume: "Siria" },
  { nume: "Sistarovat" },
  { nume: "Sofronea" },
  { nume: "Cil", comuna: "Almas" },
  { nume: "Joia Mare", comuna: "Almas" },
  { nume: "Radesti", comuna: "Almas" },
  { nume: "Berechiu", comuna: "Apateu" },
  { nume: "Motiori", comuna: "Apateu" },
  { nume: "Barzesti", comuna: "Archis" },
  { nume: "Groseni", comuna: "Archis" },
  { nume: "Nermis", comuna: "Archis" },
  { nume: "Aldesti", comuna: "Barsa" },
  { nume: "Hodis", comuna: "Barsa" },
  { nume: "Voivodeni", comuna: "Barsa" },
  { nume: "Batuta", comuna: "Barzava" },
  { nume: "Capruta", comuna: "Barzava" },
  { nume: "Dumbravita", comuna: "Barzava" },
  { nume: "Grosii Noi", comuna: "Barzava" },
  { nume: "Lalasint", comuna: "Barzava" },
  { nume: "Monorostia", comuna: "Barzava" },
  { nume: "Slatina de Mures", comuna: "Barzava" },
  { nume: "Bacau de Mijloc", comuna: "Bata" },
  { nume: "Bulci", comuna: "Bata" },
  { nume: "Tela", comuna: "Bata" },
  { nume: "Benesti", comuna: "Beliu" },
  { nume: "Bochia", comuna: "Beliu" },
  { nume: "Secaci", comuna: "Beliu" },
  { nume: "Tagadau", comuna: "Beliu" },
  { nume: "Vasile Goldis", comuna: "Beliu" },
  { nume: "Capalnas", comuna: "Birchis" },
  { nume: "Ostrov", comuna: "Birchis" },
  { nume: "Virismort", comuna: "Birchis" },
  { nume: "Manerau", comuna: "Bocsig" },
  { nume: "Rapsig", comuna: "Bocsig" },
  { nume: "Buceava-Soimus", comuna: "Brazii" },
  { nume: "Iacobini", comuna: "Brazii" },
  { nume: "Madrigesti", comuna: "Brazii" },
  { nume: "Secas", comuna: "Brazii" },
  { nume: "Berindia", comuna: "Buteni" },
  { nume: "Cuied", comuna: "Buteni" },
  { nume: "Paulian", comuna: "Buteni" },
  { nume: "Selistea", comuna: "Carand" },
  { nume: "Avram Iancu", comuna: "Cermei" },
  { nume: "Somosches", comuna: "Cermei" },
  { nume: "Paiuseni", comuna: "Chisindia" },
  { nume: "Vasoaia", comuna: "Chisindia" },
  { nume: "Nadab", comuna: "Chisineu-Cris" },
  { nume: "Belotint", comuna: "Conop" },
  { nume: "Chelmac", comuna: "Conop" },
  { nume: "Milova", comuna: "Conop" },
  { nume: "Odvos", comuna: "Conop" },
  { nume: "Chislaca", comuna: "Craiva" },
  { nume: "Ciuntesti", comuna: "Craiva" },
  { nume: "Coroi", comuna: "Craiva" },
  { nume: "Maraus", comuna: "Craiva" },
  { nume: "Rogoz de Beliu", comuna: "Craiva" },
  { nume: "Stoinesti", comuna: "Craiva" },
  { nume: "Susag", comuna: "Craiva" },
  { nume: "Talmaci", comuna: "Craiva" },
  { nume: "Siad", comuna: "Craiva" },
  { nume: "Dorobanti", comuna: "Curtici" },
  { nume: "Buhani", comuna: "Dezna" },
  { nume: "Laz", comuna: "Dezna" },
  { nume: "Neagra", comuna: "Dezna" },
  { nume: "Slatina de Cris", comuna: "Dezna" },
  { nume: "Cociuba", comuna: "Dieci" },
  { nume: "Crocna", comuna: "Dieci" },
  { nume: "Revetis", comuna: "Dieci" },
  { nume: "Rosia", comuna: "Dieci" },
  { nume: "Bruznic", comuna: "Dorgos" },
  { nume: "Patars", comuna: "Dorgos" },
  { nume: "Ususau", comuna: "Dorgos" },
  { nume: "Zabalt", comuna: "Dorgos" },
  { nume: "Alunis", comuna: "Fantinele" },
  { nume: "Frumuseni", comuna: "Fantinele" },
  { nume: "Fantanele", comuna: "Fantinele" },
  { nume: "Tisa Noua", comuna: "Fantinele" },
  { nume: "Bodrogu Nou", comuna: "Felnac" },
  { nume: "Calugareni", comuna: "Felnac" },
  { nume: "Zadareni", comuna: "Felnac" },
  { nume: "Cuvin", comuna: "Ghioroc" },
  { nume: "Minis", comuna: "Ghioroc" },
  { nume: "Siclau", comuna: "Graniceri" },
  { nume: "Bontesti", comuna: "Gurahont" },
  { nume: "Dulcele", comuna: "Gurahont" },
  { nume: "Fenis", comuna: "Gurahont" },
  { nume: "Hontisor", comuna: "Gurahont" },
  { nume: "Iosas", comuna: "Gurahont" },
  { nume: "Mustesti", comuna: "Gurahont" },
  { nume: "Pescari", comuna: "Gurahont" },
  { nume: "Valea Mare", comuna: "Gurahont" },
  { nume: "Zimbru", comuna: "Gurahont" },
  { nume: "Luncsoara", comuna: "Halmagel" },
  { nume: "Sarbi", comuna: "Halmagel" },
  { nume: "Tarnavita", comuna: "Halmagel" },
  { nume: "Tohesti", comuna: "Halmagel" },
  { nume: "Bodesti", comuna: "Halmagiu" },
  { nume: "Brusturi", comuna: "Halmagiu" },
  { nume: "Banesti", comuna: "Halmagiu" },
  { nume: "Cristesti", comuna: "Halmagiu" },
  { nume: "Ionesti", comuna: "Halmagiu" },
  { nume: "Leasa", comuna: "Halmagiu" },
  { nume: "Lestioara", comuna: "Halmagiu" },
  { nume: "Poienari", comuna: "Halmagiu" },
  { nume: "Tisa", comuna: "Halmagiu" },
  { nume: "Tarmure", comuna: "Halmagiu" },
  { nume: "Agrisu Mic", comuna: "Hasmas" },
  { nume: "Botfei", comuna: "Hasmas" },
  { nume: "Clit", comuna: "Hasmas" },
  { nume: "Comanesti", comuna: "Hasmas" },
  { nume: "Urvisu de Beliu", comuna: "Hasmas" },
  { nume: "Minead", comuna: "Ignesti" },
  { nume: "Nadalbesti", comuna: "Ignesti" },
  { nume: "Susani", comuna: "Ignesti" },
  { nume: "Mocrea", comuna: "Ineu" },
  { nume: "Variasu Mare", comuna: "Iratosu" },
  { nume: "Variasu Mic", comuna: "Iratosu" },
  { nume: "Radna", comuna: "Lipova" },
  { nume: "Soimos", comuna: "Lipova" },
  { nume: "Sanleani", comuna: "Livada" },
  { nume: "Sanmartin", comuna: "Macea" },
  { nume: "Satu Nou", comuna: "Misca" },
  { nume: "Vanatori", comuna: "Misca" },
  { nume: "Zerindu Mic", comuna: "Misca" },
  { nume: "Ranusa", comuna: "Moneasa" },
  { nume: "Sintea Mica", comuna: "Olari" },
  { nume: "Maderat", comuna: "Pancota" },
  { nume: "Baratca", comuna: "Paulis" },
  { nume: "Cladova", comuna: "Paulis" },
  { nume: "Sambateni", comuna: "Paulis" },
  { nume: "Bodrogu Vechi", comuna: "Pecica" },
  { nume: "Sederhat", comuna: "Pecica" },
  { nume: "Turnu", comuna: "Pecica" },
  { nume: "Peregu Mic", comuna: "Peregu Mare" },
  { nume: "Corbesti", comuna: "Petris" },
  { nume: "Ilteu", comuna: "Petris" },
  { nume: "Obarsia", comuna: "Petris" },
  { nume: "Rosia Noua", comuna: "Petris" },
  { nume: "Seliste", comuna: "Petris" },
  { nume: "Varsand", comuna: "Pilu" },
  { nume: "Aciuta", comuna: "Plescuta" },
  { nume: "Budesti", comuna: "Plescuta" },
  { nume: "Dumbrava", comuna: "Plescuta" },
  { nume: "Gura Vaii", comuna: "Plescuta" },
  { nume: "Rostoci", comuna: "Plescuta" },
  { nume: "Talagiu", comuna: "Plescuta" },
  { nume: "Cruceni", comuna: "Sagu" },
  { nume: "Firiteaz", comuna: "Sagu" },
  { nume: "Fiscut", comuna: "Sagu" },
  { nume: "Hunedoara Timisana", comuna: "Sagu" },
  { nume: "Caporal Alexa", comuna: "Santana" },
  { nume: "Cuias", comuna: "Savarsin" },
  { nume: "Caprioara", comuna: "Savarsin" },
  { nume: "Halalis", comuna: "Savarsin" },
  { nume: "Parnesti", comuna: "Savarsin" },
  { nume: "Temesesti", comuna: "Savarsin" },
  { nume: "Toc", comuna: "Savarsin" },
  { nume: "Troas", comuna: "Savarsin" },
  { nume: "Valea Mare", comuna: "Savarsin" },
  { nume: "Donceni", comuna: "Sebis" },
  { nume: "Prunisor", comuna: "Sebis" },
  { nume: "Salajeni", comuna: "Sebis" },
  { nume: "Munar", comuna: "Secusigiu" },
  { nume: "Satu Mare", comuna: "Secusigiu" },
  { nume: "Sanpetru German", comuna: "Secusigiu" },
  { nume: "Iermata", comuna: "Seleus" },
  { nume: "Moroda", comuna: "Seleus" },
  { nume: "Cherelus", comuna: "Sicula" },
  { nume: "Gurba", comuna: "Sicula" },
  { nume: "Camna", comuna: "Silindia" },
  { nume: "Iercoseni", comuna: "Silindia" },
  { nume: "Luguzau", comuna: "Silindia" },
  { nume: "Satu Mic", comuna: "Silindia" },
  { nume: "Adea", comuna: "Sintea Mare" },
  { nume: "Tipar", comuna: "Sintea Mare" },
  { nume: "Galsa", comuna: "Siria" },
  { nume: "Masca", comuna: "Siria" },
  { nume: "Cuvesdia", comuna: "Sistarovat" },
  { nume: "Labasint", comuna: "Sistarovat" },
  { nume: "Varnita", comuna: "Sistarovat" },
  { nume: "Sanpaul", comuna: "Sofronea" },
  { nume: "Agrisu Mare", comuna: "Tarnova" },
  { nume: "Araneag", comuna: "Tarnova" },
  { nume: "Chier", comuna: "Tarnova" },
  { nume: "Draut", comuna: "Tarnova" },
  { nume: "Dud", comuna: "Tarnova" },
  { nume: "Minisel", comuna: "Taut" },
  { nume: "Minisu de Sus", comuna: "Taut" },
  { nume: "Nadas", comuna: "Taut" },
  { nume: "Baia", comuna: "Varadia De Mures" },
  { nume: "Julita", comuna: "Varadia De Mures" },
  { nume: "Lupesti", comuna: "Varadia De Mures" },
  { nume: "Nicolae Balcescu", comuna: "Varadia De Mures" },
  { nume: "Stejar", comuna: "Varadia De Mures" },
  { nume: "Avram Iancu", comuna: "Varfurile" },
  { nume: "Grosi", comuna: "Varfurile" },
  { nume: "Lazuri", comuna: "Varfurile" },
  { nume: "Mermesti", comuna: "Varfurile" },
  { nume: "Magulicea", comuna: "Varfurile" },
  { nume: "Poiana", comuna: "Varfurile" },
  { nume: "Vidra", comuna: "Varfurile" },
  { nume: "Mailat", comuna: "Vinga" },
  { nume: "Manastur", comuna: "Vinga" },
  { nume: "Cicir", comuna: "Vladimirescu" },
  { nume: "Horia", comuna: "Vladimirescu" },
  { nume: "Mandruloc", comuna: "Vladimirescu" },
  { nume: "Chesint", comuna: "Zabrani" },
  { nume: "Neudorf", comuna: "Zabrani" },
  { nume: "Cintei", comuna: "Zarand" },
  { nume: "Iermata Neagra", comuna: "Zerind" },
  { nume: "Andrei Saguna", comuna: "Zimandu Nou" },
  { nume: "Zimandcuz", comuna: "Zimandu Nou" },
];
