export const ar = [
  { nume: "Aciuţa", simplu: "Aciuta", comuna: "Plescuta" },
  { nume: "Adea", comuna: "Sintea Mare" },
  { nume: "Agrişu Mare", simplu: "Agrisu Mare", comuna: "Tarnova" },
  { nume: "Agrişu Mic", simplu: "Agrisu Mic", comuna: "Hasmas" },
  { nume: "Aldeşti", simplu: "Aldesti", comuna: "Barsa" },
  { nume: "Almaş", simplu: "Almas" },
  { nume: "Aluniş", simplu: "Alunis", comuna: "Fantinele" },
  { nume: "Andrei Şaguna", simplu: "Andrei Saguna", comuna: "Zimandu Nou" },
  { nume: "Apateu" },
  { nume: "Arad" },
  { nume: "Arăneag", simplu: "Araneag", comuna: "Tarnova" },
  { nume: "Archiş", simplu: "Archis" },
  { nume: "Avram Iancu", comuna: "Cermei" },
  { nume: "Avram Iancu", comuna: "Varfurile" },
  { nume: "Bacău de Mijloc", simplu: "Bacau de Mijloc", comuna: "Bata" },
  { nume: "Baia", comuna: "Varadia De Mures" },
  { nume: "Băneşti", simplu: "Banesti", comuna: "Halmagiu" },
  { nume: "Baraţca", simplu: "Baratca", comuna: "Paulis" },
  { nume: "Bârsa", simplu: "Barsa" },
  { nume: "Bârzava", simplu: "Barzava" },
  { nume: "Bârzeşti", simplu: "Barzesti", comuna: "Archis" },
  { nume: "Bata" },
  { nume: "Bătuţa", simplu: "Batuta", comuna: "Barzava" },
  { nume: "Beliu" },
  { nume: "Belotinţ", simplu: "Belotint", comuna: "Conop" },
  { nume: "Beneşti", simplu: "Benesti", comuna: "Beliu" },
  { nume: "Berechiu", comuna: "Apateu" },
  { nume: "Berindia", comuna: "Buteni" },
  { nume: "Birchiş", simplu: "Birchis" },
  { nume: "Bochia", comuna: "Beliu" },
  { nume: "Bocsig" },
  { nume: "Bodeşti", simplu: "Bodesti", comuna: "Halmagiu" },
  { nume: "Bodrogu Nou", comuna: "Felnac" },
  { nume: "Bodrogu Vechi", comuna: "Pecica" },
  { nume: "Bonţeşti", simplu: "Bontesti", comuna: "Gurahont" },
  { nume: "Botfei", comuna: "Hasmas" },
  { nume: "Brazii" },
  { nume: "Brusturi", comuna: "Halmagiu" },
  { nume: "Bruznic", comuna: "Dorgos" },
  { nume: "Buceava-Şoimuş", simplu: "Buceava-Soimus", comuna: "Brazii" },
  { nume: "Budeşti", simplu: "Budesti", comuna: "Plescuta" },
  { nume: "Buhani", comuna: "Dezna" },
  { nume: "Bulci", comuna: "Bata" },
  { nume: "Buteni" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Felnac" },
  { nume: "Camna", comuna: "Silindia" },
  { nume: "Căpălnaş", simplu: "Capalnas", comuna: "Birchis" },
  { nume: "Caporal Alexa", comuna: "Santana" },
  { nume: "Căprioara", simplu: "Caprioara", comuna: "Savarsin" },
  { nume: "Căpruţa", simplu: "Capruta", comuna: "Barzava" },
  { nume: "Cărand", simplu: "Carand" },
  { nume: "Cermei" },
  { nume: "Chelmac", comuna: "Conop" },
  { nume: "Chereluş", simplu: "Cherelus", comuna: "Sicula" },
  { nume: "Chesinţ", simplu: "Chesint", comuna: "Zabrani" },
  { nume: "Chier", comuna: "Tarnova" },
  { nume: "Chisindia" },
  { nume: "Chişineu-Criş", simplu: "Chisineu-Cris" },
  { nume: "Chişlaca", simplu: "Chislaca", comuna: "Craiva" },
  { nume: "Cicir", comuna: "Vladimirescu" },
  { nume: "Cil", comuna: "Almas" },
  { nume: "Cintei", comuna: "Zarand" },
  { nume: "Ciunteşti", simplu: "Ciuntesti", comuna: "Craiva" },
  { nume: "Cladova", comuna: "Paulis" },
  { nume: "Clit", comuna: "Hasmas" },
  { nume: "Cociuba", comuna: "Dieci" },
  { nume: "Comăneşti", simplu: "Comanesti", comuna: "Hasmas" },
  { nume: "Conop" },
  { nume: "Corbeşti", simplu: "Corbesti", comuna: "Petris" },
  { nume: "Coroi", comuna: "Craiva" },
  { nume: "Covăsinţ", simplu: "Covasint" },
  { nume: "Craiva" },
  { nume: "Cristeşti", simplu: "Cristesti", comuna: "Halmagiu" },
  { nume: "Crocna", comuna: "Dieci" },
  { nume: "Cruceni", comuna: "Sagu" },
  { nume: "Cuiaş", simplu: "Cuias", comuna: "Savarsin" },
  { nume: "Cuied", comuna: "Buteni" },
  { nume: "Curtici" },
  { nume: "Cuveşdia", simplu: "Cuvesdia", comuna: "Sistarovat" },
  { nume: "Cuvin", comuna: "Ghioroc" },
  { nume: "Dezna" },
  { nume: "Dieci" },
  { nume: "Donceni", comuna: "Sebis" },
  { nume: "Dorgoş", simplu: "Dorgos" },
  { nume: "Dorobanţi", simplu: "Dorobanti", comuna: "Curtici" },
  { nume: "Drauţ", simplu: "Draut", comuna: "Tarnova" },
  { nume: "Dud", comuna: "Tarnova" },
  { nume: "Dulcele", comuna: "Gurahont" },
  { nume: "Dumbrava", comuna: "Plescuta" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita", comuna: "Barzava" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Fantinele" },
  { nume: "Felnac" },
  { nume: "Feniş", simplu: "Fenis", comuna: "Gurahont" },
  { nume: "Firiteaz", comuna: "Sagu" },
  { nume: "Fiscut", comuna: "Sagu" },
  { nume: "Frumuşeni", simplu: "Frumuseni", comuna: "Fantinele" },
  { nume: "Galşa", simplu: "Galsa", comuna: "Siria" },
  { nume: "Ghioroc" },
  { nume: "Grăniceri", simplu: "Graniceri" },
  { nume: "Groşeni", simplu: "Groseni", comuna: "Archis" },
  { nume: "Groşi", simplu: "Grosi", comuna: "Varfurile" },
  { nume: "Groşii Noi", simplu: "Grosii Noi", comuna: "Barzava" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Plescuta" },
  { nume: "Gurahonţ", simplu: "Gurahont" },
  { nume: "Gurba", comuna: "Sicula" },
  { nume: "Hălăliş", simplu: "Halalis", comuna: "Savarsin" },
  { nume: "Hălmăgel", simplu: "Halmagel" },
  { nume: "Hălmagiu", simplu: "Halmagiu" },
  { nume: "Hăşmaş", simplu: "Hasmas" },
  { nume: "Hodiş", simplu: "Hodis", comuna: "Barsa" },
  { nume: "Honţişor", simplu: "Hontisor", comuna: "Gurahont" },
  { nume: "Horia", comuna: "Vladimirescu" },
  { nume: "Hunedoara Timişană", simplu: "Hunedoara Timisana", comuna: "Sagu" },
  { nume: "Iacobini", comuna: "Brazii" },
  { nume: "Iercoşeni", simplu: "Iercoseni", comuna: "Silindia" },
  { nume: "Iermata Neagră", simplu: "Iermata Neagra", comuna: "Zerind" },
  { nume: "Iermata", comuna: "Seleus" },
  { nume: "Igneşti", simplu: "Ignesti" },
  { nume: "Ilteu", comuna: "Petris" },
  { nume: "Ineu" },
  { nume: "Ioneşti", simplu: "Ionesti", comuna: "Halmagiu" },
  { nume: "Iosaş", simplu: "Iosas", comuna: "Gurahont" },
  { nume: "Iratoşu", simplu: "Iratosu" },
  { nume: "Joia Mare", comuna: "Almas" },
  { nume: "Juliţa", simplu: "Julita", comuna: "Varadia De Mures" },
  { nume: "Labaşinţ", simplu: "Labasint", comuna: "Sistarovat" },
  { nume: "Lalaşinţ", simplu: "Lalasint", comuna: "Barzava" },
  { nume: "Laz", comuna: "Dezna" },
  { nume: "Lazuri", comuna: "Varfurile" },
  { nume: "Leasa", comuna: "Halmagiu" },
  { nume: "Leştioara", simplu: "Lestioara", comuna: "Halmagiu" },
  { nume: "Lipova" },
  { nume: "Livada" },
  { nume: "Luguzău", simplu: "Luguzau", comuna: "Silindia" },
  { nume: "Luncşoara", simplu: "Luncsoara", comuna: "Halmagel" },
  { nume: "Lupeşti", simplu: "Lupesti", comuna: "Varadia De Mures" },
  { nume: "Macea" },
  { nume: "Măderat", simplu: "Maderat", comuna: "Pancota" },
  { nume: "Mădrigeşti", simplu: "Madrigesti", comuna: "Brazii" },
  { nume: "Măgulicea", simplu: "Magulicea", comuna: "Varfurile" },
  { nume: "Mailat", comuna: "Vinga" },
  { nume: "Mănăştur", simplu: "Manastur", comuna: "Vinga" },
  { nume: "Mândruloc", simplu: "Mandruloc", comuna: "Vladimirescu" },
  { nume: "Mânerău", simplu: "Manerau", comuna: "Bocsig" },
  { nume: "Mărăuş", simplu: "Maraus", comuna: "Craiva" },
  { nume: "Mâsca", simplu: "Masca", comuna: "Siria" },
  { nume: "Mermeşti", simplu: "Mermesti", comuna: "Varfurile" },
  { nume: "Milova", comuna: "Conop" },
  { nume: "Minead", comuna: "Ignesti" },
  { nume: "Miniş", simplu: "Minis", comuna: "Ghioroc" },
  { nume: "Minişel", simplu: "Minisel", comuna: "Taut" },
  { nume: "Minişu de Sus", simplu: "Minisu de Sus", comuna: "Taut" },
  { nume: "Mişca", simplu: "Misca" },
  { nume: "Mocrea", comuna: "Ineu" },
  { nume: "Moneasa" },
  { nume: "Monoroştia", simplu: "Monorostia", comuna: "Barzava" },
  { nume: "Moroda", comuna: "Seleus" },
  { nume: "Moţiori", simplu: "Motiori", comuna: "Apateu" },
  { nume: "Munar", comuna: "Secusigiu" },
  { nume: "Musteşti", simplu: "Mustesti", comuna: "Gurahont" },
  { nume: "Nadab", comuna: "Chisineu-Cris" },
  { nume: "Nădălbeşti", simplu: "Nadalbesti", comuna: "Ignesti" },
  { nume: "Nadăş", simplu: "Nadas", comuna: "Taut" },
  { nume: "Nădlac", simplu: "Nadlac" },
  { nume: "Neagra", comuna: "Dezna" },
  { nume: "Nermiş", simplu: "Nermis", comuna: "Archis" },
  { nume: "Neudorf", comuna: "Zabrani" },
  {
    nume: "Nicolae Bălcescu",
    simplu: "Nicolae Balcescu",
    comuna: "Varadia De Mures",
  },
  { nume: "Obârşia", simplu: "Obarsia", comuna: "Petris" },
  { nume: "Odvoş", simplu: "Odvos", comuna: "Conop" },
  { nume: "Olari" },
  { nume: "Ostrov", comuna: "Birchis" },
  { nume: "Păiuşeni", simplu: "Paiuseni", comuna: "Chisindia" },
  { nume: "Pâncota", simplu: "Pancota" },
  { nume: "Pârneşti", simplu: "Parnesti", comuna: "Savarsin" },
  { nume: "Pătârş", simplu: "Patars", comuna: "Dorgos" },
  { nume: "Păulian", simplu: "Paulian", comuna: "Buteni" },
  { nume: "Păuliş", simplu: "Paulis" },
  { nume: "Pecica" },
  { nume: "Peregu Mare" },
  { nume: "Peregu Mic", comuna: "Peregu Mare" },
  { nume: "Pescari", comuna: "Gurahont" },
  { nume: "Petriş", simplu: "Petris" },
  { nume: "Pilu" },
  { nume: "Pleşcuţa", simplu: "Plescuta" },
  { nume: "Poiana", comuna: "Varfurile" },
  { nume: "Poienari", comuna: "Halmagiu" },
  { nume: "Prunişor", simplu: "Prunisor", comuna: "Sebis" },
  { nume: "Rădeşti", simplu: "Radesti", comuna: "Almas" },
  { nume: "Radna", comuna: "Lipova" },
  { nume: "Rănuşa", simplu: "Ranusa", comuna: "Moneasa" },
  { nume: "Răpsig", simplu: "Rapsig", comuna: "Bocsig" },
  { nume: "Revetiş", simplu: "Revetis", comuna: "Dieci" },
  { nume: "Rogoz de Beliu", comuna: "Craiva" },
  { nume: "Roşia Nouă", simplu: "Rosia Noua", comuna: "Petris" },
  { nume: "Roşia", simplu: "Rosia", comuna: "Dieci" },
  { nume: "Rostoci", comuna: "Plescuta" },
  { nume: "Şagu", simplu: "Sagu" },
  { nume: "Sălăjeni", simplu: "Salajeni", comuna: "Sebis" },
  { nume: "Sâmbăteni", simplu: "Sambateni", comuna: "Paulis" },
  { nume: "Sânleani", simplu: "Sanleani", comuna: "Livada" },
  { nume: "Sânmartin", simplu: "Sanmartin", comuna: "Macea" },
  { nume: "Sânpaul", simplu: "Sanpaul", comuna: "Sofronea" },
  { nume: "Sânpetru German", simplu: "Sanpetru German", comuna: "Secusigiu" },
  { nume: "Sântana", simplu: "Santana" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Halmagel" },
  { nume: "Satu Mare", comuna: "Secusigiu" },
  { nume: "Satu Mic", comuna: "Silindia" },
  { nume: "Satu Nou", comuna: "Misca" },
  { nume: "Săvârşin", simplu: "Savarsin" },
  { nume: "Sebiş", simplu: "Sebis" },
  { nume: "Secaci", comuna: "Beliu" },
  { nume: "Secaş", simplu: "Secas", comuna: "Brazii" },
  { nume: "Secusigiu" },
  { nume: "Sederhat", comuna: "Pecica" },
  { nume: "Şeitin", simplu: "Seitin" },
  { nume: "Seleuş", simplu: "Seleus" },
  { nume: "Selişte", simplu: "Seliste", comuna: "Petris" },
  { nume: "Seliştea", simplu: "Selistea", comuna: "Carand" },
  { nume: "Semlac" },
  { nume: "Şepreuş", simplu: "Sepreus" },
  { nume: "Şiad", simplu: "Siad", comuna: "Craiva" },
  { nume: "Şiclău", simplu: "Siclau", comuna: "Graniceri" },
  { nume: "Şicula", simplu: "Sicula" },
  { nume: "Şilindia", simplu: "Silindia" },
  { nume: "Şimand", simplu: "Simand" },
  { nume: "Sintea Mare" },
  { nume: "Sintea Mică", simplu: "Sintea Mica", comuna: "Olari" },
  { nume: "Şiria", simplu: "Siria" },
  { nume: "Şiştarovăţ", simplu: "Sistarovat" },
  { nume: "Slatina de Criş", simplu: "Slatina de Cris", comuna: "Dezna" },
  { nume: "Slatina de Mureş", simplu: "Slatina de Mures", comuna: "Barzava" },
  { nume: "Socodor" },
  { nume: "Şofronea", simplu: "Sofronea" },
  { nume: "Şoimoş", simplu: "Soimos", comuna: "Lipova" },
  { nume: "Şomoşcheş", simplu: "Somosches", comuna: "Cermei" },
  { nume: "Stejar", comuna: "Varadia De Mures" },
  { nume: "Stoineşti", simplu: "Stoinesti", comuna: "Craiva" },
  { nume: "Susag", comuna: "Craiva" },
  { nume: "Susani", comuna: "Ignesti" },
  { nume: "Tăgădău", simplu: "Tagadau", comuna: "Beliu" },
  { nume: "Tălagiu", simplu: "Talagiu", comuna: "Plescuta" },
  { nume: "Tălmaci", simplu: "Talmaci", comuna: "Craiva" },
  { nume: "Ţărmure", simplu: "Tarmure", comuna: "Halmagiu" },
  { nume: "Târnăviţa", simplu: "Tarnavita", comuna: "Halmagel" },
  { nume: "Târnova", simplu: "Tarnova" },
  { nume: "Tauţ", simplu: "Taut" },
  { nume: "Ţela", simplu: "Tela", comuna: "Bata" },
  { nume: "Temeşeşti", simplu: "Temesesti", comuna: "Savarsin" },
  { nume: "Ţipar", simplu: "Tipar", comuna: "Sintea Mare" },
  { nume: "Tisa Nouă", simplu: "Tisa Noua", comuna: "Fantinele" },
  { nume: "Tisa", comuna: "Halmagiu" },
  { nume: "Toc", comuna: "Savarsin" },
  { nume: "Ţoheşti", simplu: "Tohesti", comuna: "Halmagel" },
  { nume: "Troaş", simplu: "Troas", comuna: "Savarsin" },
  { nume: "Turnu", comuna: "Pecica" },
  { nume: "Urvişu de Beliu", simplu: "Urvisu de Beliu", comuna: "Hasmas" },
  { nume: "Ususău", simplu: "Ususau", comuna: "Dorgos" },
  { nume: "Valea Mare", comuna: "Gurahont" },
  { nume: "Valea Mare", comuna: "Savarsin" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Misca" },
  { nume: "Vărădia de Mureş", simplu: "Varadia de Mures" },
  { nume: "Vârfurile", simplu: "Varfurile" },
  { nume: "Variaşu Mare", simplu: "Variasu Mare", comuna: "Iratosu" },
  { nume: "Variaşu Mic", simplu: "Variasu Mic", comuna: "Iratosu" },
  { nume: "Varniţa", simplu: "Varnita", comuna: "Sistarovat" },
  { nume: "Vărşand", simplu: "Varsand", comuna: "Pilu" },
  { nume: "Vasile Goldiş", simplu: "Vasile Goldis", comuna: "Beliu" },
  { nume: "Văsoaia", simplu: "Vasoaia", comuna: "Chisindia" },
  { nume: "Vidra", comuna: "Varfurile" },
  { nume: "Vinga" },
  { nume: "Virismort", comuna: "Birchis" },
  { nume: "Vladimirescu" },
  { nume: "Voivodeni", comuna: "Barsa" },
  { nume: "Zăbalţ", simplu: "Zabalt", comuna: "Dorgos" },
  { nume: "Zăbrani", simplu: "Zabrani" },
  { nume: "Zădăreni", simplu: "Zadareni", comuna: "Felnac" },
  { nume: "Zărand", simplu: "Zarand" },
  { nume: "Zerind" },
  { nume: "Zerindu Mic", comuna: "Misca" },
  { nume: "Zimandcuz", comuna: "Zimandu Nou" },
  { nume: "Zimandu Nou" },
  { nume: "Zimbru", comuna: "Gurahont" },
];
