export const ag = [
  { nume: "Albota" },
  { nume: "Aninoasa" },
  { nume: "Arefu" },
  { nume: "Bascov" },
  { nume: "Berevoesti" },
  { nume: "Bogati" },
  { nume: "Boteni" },
  { nume: "Botesti" },
  { nume: "Bradu" },
  { nume: "Bradulet" },
  { nume: "Bughea de Jos" },
  { nume: "Buzoesti" },
  { nume: "Barla" },
  { nume: "Babana" },
  { nume: "Baiculesti" },
  { nume: "Balilesti" },
  { nume: "Cetateni" },
  { nume: "Cicanesti" },
  { nume: "Ciofrangeni" },
  { nume: "Ciomagesti" },
  { nume: "Cocu" },
  { nume: "Corbeni" },
  { nume: "Corbi" },
  { nume: "Costesti" },
  { nume: "Cotmeana" },
  { nume: "Cosesti" },
  { nume: "Cuca" },
  { nume: "Curtea de Arges" },
  { nume: "Campulung" },
  { nume: "Caldararu" },
  { nume: "Calinesti" },
  { nume: "Cateasca" },
  { nume: "Davidesti" },
  { nume: "Dobresti" },
  { nume: "Domnesti" },
  { nume: "Dragoslavele" },
  { nume: "Dambovicioara" },
  { nume: "Darmanesti" },
  { nume: "Godeni" },
  { nume: "Harsesti" },
  { nume: "Hartiesti" },
  { nume: "Izvoru" },
  { nume: "Leordeni" },
  { nume: "Leresti" },
  { nume: "Lunca Corbului" },
  { nume: "Merisani" },
  { nume: "Micesti" },
  { nume: "Mihaesti" },
  { nume: "Mioveni" },
  { nume: "Mirosi" },
  { nume: "Moraresti" },
  { nume: "Mozaceni" },
  { nume: "Mosoaia" },
  { nume: "Musatesti" },
  { nume: "Malureni" },
  { nume: "Maracineni" },
  { nume: "Negrasi" },
  { nume: "Nucsoara" },
  { nume: "Oarja" },
  { nume: "Pietrosani" },
  { nume: "Pitesti" },
  { nume: "Poiana Lacului" },
  { nume: "Popesti" },
  { nume: "Priboieni" },
  { nume: "Recea" },
  { nume: "Rociu" },
  { nume: "Rucar" },
  { nume: "Raca" },
  { nume: "Ratesti" },
  { nume: "Schitu Golesti" },
  { nume: "Slobozia" },
  { nume: "Stoenesti" },
  { nume: "Stolnici" },
  { nume: "Stalpeni" },
  { nume: "Suseni" },
  { nume: "Salatrucu" },
  { nume: "Teiu" },
  { nume: "Tigveni" },
  { nume: "Topoloveni" },
  { nume: "Uda" },
  { nume: "Ungheni" },
  { nume: "Valea Danului" },
  { nume: "Valea Iasului" },
  { nume: "Valea Mare Pravat" },
  { nume: "Vedea" },
  { nume: "Vladesti" },
  { nume: "Vulturesti" },
  { nume: "Stefan cel Mare" },
  { nume: "Stefanesti" },
  { nume: "Suici" },
  { nume: "Titesti" },
  { nume: "Albestii Pamanteni", comuna: "Albestii De Arges" },
  { nume: "Albestii Ungureni", comuna: "Albestii De Arges" },
  { nume: "Bratesti", comuna: "Albestii De Arges" },
  { nume: "Doblea", comuna: "Albestii De Arges" },
  { nume: "Dobrotu", comuna: "Albestii De Arges" },
  { nume: "Dumiresti", comuna: "Albestii De Arges" },
  { nume: "Florieni", comuna: "Albestii De Arges" },
  { nume: "Albesti", comuna: "Albestii De Muscel" },
  { nume: "Bughea de Sus", comuna: "Albestii De Muscel" },
  { nume: "Candesti", comuna: "Albestii De Muscel" },
  { nume: "Cerbu", comuna: "Albota" },
  { nume: "Fratesti", comuna: "Albota" },
  { nume: "Gura Vaii", comuna: "Albota" },
  { nume: "Mares", comuna: "Albota" },
  { nume: "Brosteni", comuna: "Aninoasa" },
  { nume: "Slanic", comuna: "Aninoasa" },
  { nume: "Valea Silistii", comuna: "Aninoasa" },
  { nume: "Căpăţânenii Pământeni", comuna: "Arefu" },
  { nume: "Căpăţânenii Ungureni", comuna: "Arefu" },
  { nume: "Bajanesti", comuna: "Babana" },
  { nume: "Ciobanesti", comuna: "Babana" },
  { nume: "Cotmenita", comuna: "Babana" },
  { nume: "Grosi", comuna: "Babana" },
  { nume: "Lupueni", comuna: "Babana" },
  { nume: "Slaatioarele", comuna: "Babana" },
  { nume: "Alunisu", comuna: "Baiculesti" },
  { nume: "Anghinesti", comuna: "Baiculesti" },
  { nume: "Argesani", comuna: "Baiculesti" },
  { nume: "Manicesti", comuna: "Baiculesti" },
  { nume: "Stejari", comuna: "Baiculesti" },
  { nume: "Tutana", comuna: "Baiculesti" },
  { nume: "Valea Brazilor", comuna: "Baiculesti" },
  { nume: "Valea lui Enache", comuna: "Baiculesti" },
  { nume: "Zigoneni", comuna: "Baiculesti" },
  { nume: "Bajesti", comuna: "Balilesti" },
  { nume: "Golesti", comuna: "Balilesti" },
  { nume: "Poienita", comuna: "Balilesti" },
  { nume: "Priboaia", comuna: "Balilesti" },
  { nume: "Ulita", comuna: "Balilesti" },
  { nume: "Valea Mare-Bratia", comuna: "Balilesti" },
  { nume: "Afrimesti", comuna: "Barla" },
  { nume: "Brabeti", comuna: "Barla" },
  { nume: "Badesti", comuna: "Barla" },
  { nume: "Ciocesti", comuna: "Barla" },
  { nume: "Malu", comuna: "Barla" },
  { nume: "Mozacenii-Vale", comuna: "Barla" },
  { nume: "Mandra", comuna: "Barla" },
  { nume: "Podisoru", comuna: "Barla" },
  { nume: "Urlueni", comuna: "Barla" },
  { nume: "Zuvelcati", comuna: "Barla" },
  { nume: "Selareasca", comuna: "Barla" },
  { nume: "Braileni", comuna: "Bascov" },
  { nume: "Glambocu", comuna: "Bascov" },
  { nume: "Mica", comuna: "Bascov" },
  { nume: "Prislopu Mic", comuna: "Bascov" },
  { nume: "Scheau", comuna: "Bascov" },
  { nume: "Uiasca", comuna: "Bascov" },
  { nume: "Valea Ursului", comuna: "Bascov" },
  { nume: "Beleti", comuna: "Beleti-Negresti" },
  { nume: "Lentea", comuna: "Beleti-Negresti" },
  { nume: "Negresti", comuna: "Beleti-Negresti" },
  { nume: "Zgripcesti", comuna: "Beleti-Negresti" },
  { nume: "Bratia", comuna: "Berevoesti" },
  { nume: "Gamacesti", comuna: "Berevoesti" },
  { nume: "Otelu", comuna: "Berevoesti" },
  { nume: "Bujoi", comuna: "Bogati" },
  { nume: "Barloi", comuna: "Bogati" },
  { nume: "Chitesti", comuna: "Bogati" },
  { nume: "Dumbrava", comuna: "Bogati" },
  { nume: "Glambocel", comuna: "Bogati" },
  { nume: "Glambocelu", comuna: "Bogati" },
  { nume: "Suseni", comuna: "Bogati" },
  { nume: "Balabani", comuna: "Boteni" },
  { nume: "Lunca", comuna: "Boteni" },
  { nume: "Muscel", comuna: "Boteni" },
  { nume: "Mosteni-Greci", comuna: "Botesti" },
  { nume: "Geamana", comuna: "Bradu" },
  { nume: "Alunisu", comuna: "Bradulet" },
  { nume: "Bradetu", comuna: "Bradulet" },
  { nume: "Cosaci", comuna: "Bradulet" },
  { nume: "Galesu", comuna: "Bradulet" },
  { nume: "Piatra", comuna: "Bradulet" },
  { nume: "Slamnesti", comuna: "Bradulet" },
  { nume: "Uleni", comuna: "Bradulet" },
  { nume: "Ungureni", comuna: "Bradulet" },
  { nume: "Budeasa Mare", comuna: "Budeasa" },
  { nume: "Budeasa Mica", comuna: "Budeasa" },
  { nume: "Calotesti", comuna: "Budeasa" },
  { nume: "Galasesti", comuna: "Budeasa" },
  { nume: "Rogojina", comuna: "Budeasa" },
  { nume: "Valea Marului", comuna: "Budeasa" },
  { nume: "Bujoreni", comuna: "Buzoesti" },
  { nume: "Cornatel", comuna: "Buzoesti" },
  { nume: "Curteanca", comuna: "Buzoesti" },
  { nume: "Ionesti", comuna: "Buzoesti" },
  { nume: "Podeni", comuna: "Buzoesti" },
  { nume: "Redea", comuna: "Buzoesti" },
  { nume: "Tomsanca", comuna: "Buzoesti" },
  { nume: "Vladuta", comuna: "Buzoesti" },
  { nume: "Vulpesti", comuna: "Buzoesti" },
  { nume: "Serboeni", comuna: "Buzoesti" },
  { nume: "Burdea", comuna: "Caldararu" },
  { nume: "Strambeni", comuna: "Caldararu" },
  { nume: "Ciocanesti", comuna: "Calinesti" },
  { nume: "Carstieni", comuna: "Calinesti" },
  { nume: "Glodu", comuna: "Calinesti" },
  { nume: "Gorganu", comuna: "Calinesti" },
  { nume: "Radu Negru", comuna: "Calinesti" },
  { nume: "Rancaciov", comuna: "Calinesti" },
  { nume: "Udeni-Zavoi", comuna: "Calinesti" },
  { nume: "Urlucea", comuna: "Calinesti" },
  { nume: "Valea Corbului", comuna: "Calinesti" },
  { nume: "Vranesti", comuna: "Calinesti" },
  { nume: "Valeni-Podgoria", comuna: "Calinesti" },
  { nume: "Valea Rumanestilor", comuna: "Campulung" },
  { nume: "Catanele", comuna: "Cateasca" },
  { nume: "Ciresu", comuna: "Cateasca" },
  { nume: "Coseri", comuna: "Cateasca" },
  { nume: "Gruiu", comuna: "Cateasca" },
  { nume: "Recea", comuna: "Cateasca" },
  { nume: "Silistea", comuna: "Cateasca" },
  { nume: "Ceparii Pamanteni", comuna: "Cepari" },
  { nume: "Ceparii Ungureni", comuna: "Cepari" },
  { nume: "Carpenis", comuna: "Cepari" },
  { nume: "Morasti", comuna: "Cepari" },
  { nume: "Urluiesti", comuna: "Cepari" },
  { nume: "Valea Magurei", comuna: "Cepari" },
  { nume: "Zamfiresti", comuna: "Cepari" },
  { nume: "Sendrulesti", comuna: "Cepari" },
  { nume: "Laicai", comuna: "Cetateni" },
  { nume: "Valea Cetatuia", comuna: "Cetateni" },
  { nume: "Barasti", comuna: "Cicanesti" },
  { nume: "Mioarele", comuna: "Cicanesti" },
  { nume: "Urechesti", comuna: "Cicanesti" },
  { nume: "Burlusi", comuna: "Ciofrangeni" },
  { nume: "Lacurile", comuna: "Ciofrangeni" },
  { nume: "Piatra", comuna: "Ciofrangeni" },
  { nume: "Schitu-Matei", comuna: "Ciofrangeni" },
  { nume: "Beculesti", comuna: "Ciomagesti" },
  { nume: "Bratia", comuna: "Ciomagesti" },
  { nume: "Cungrea", comuna: "Ciomagesti" },
  { nume: "Dogari", comuna: "Ciomagesti" },
  { nume: "Fedelesoiu", comuna: "Ciomagesti" },
  { nume: "Giuclani", comuna: "Ciomagesti" },
  { nume: "Paunesti", comuna: "Ciomagesti" },
  { nume: "Radutesti", comuna: "Ciomagesti" },
  { nume: "Barbatesti", comuna: "Cocu" },
  { nume: "Crucisoara", comuna: "Cocu" },
  { nume: "Facaletesti", comuna: "Cocu" },
  { nume: "Greabanu", comuna: "Cocu" },
  { nume: "Popesti", comuna: "Cocu" },
  { nume: "Rachitele de Jos", comuna: "Cocu" },
  { nume: "Rachitele de Sus", comuna: "Cocu" },
  { nume: "Berindesti", comuna: "Corbeni" },
  { nume: "Bucsenesti", comuna: "Corbeni" },
  { nume: "Oestii Pamanteni", comuna: "Corbeni" },
  { nume: "Oestii Ungureni", comuna: "Corbeni" },
  { nume: "Poienari", comuna: "Corbeni" },
  { nume: "Rotunda", comuna: "Corbeni" },
  { nume: "Turburea", comuna: "Corbeni" },
  { nume: "Corbsori", comuna: "Corbi" },
  { nume: "Jgheaburi", comuna: "Corbi" },
  { nume: "Poduri", comuna: "Corbi" },
  { nume: "Poienarei", comuna: "Corbi" },
  { nume: "Stanesti", comuna: "Corbi" },
  { nume: "Jupanesti", comuna: "Cosesti" },
  { nume: "Leicesti", comuna: "Cosesti" },
  { nume: "Lapusani", comuna: "Cosesti" },
  { nume: "Petresti", comuna: "Cosesti" },
  { nume: "Priseaca", comuna: "Cosesti" },
  { nume: "Pacioiu", comuna: "Cosesti" },
  { nume: "Brosteni", comuna: "Costesti" },
  { nume: "Laceni", comuna: "Costesti" },
  { nume: "Podu Brosteni", comuna: "Costesti" },
  { nume: "Parvu Rosu", comuna: "Costesti" },
  { nume: "Smei", comuna: "Costesti" },
  { nume: "Starci", comuna: "Costesti" },
  { nume: "Bascovele", comuna: "Cotmeana" },
  { nume: "Bunesti", comuna: "Cotmeana" },
  { nume: "Costesti", comuna: "Cotmeana" },
  { nume: "Dealu Padurii", comuna: "Cotmeana" },
  { nume: "Dragolesti", comuna: "Cotmeana" },
  { nume: "Lintesti", comuna: "Cotmeana" },
  { nume: "Negesti", comuna: "Cotmeana" },
  { nume: "Pielesti", comuna: "Cotmeana" },
  { nume: "Spiridoni", comuna: "Cotmeana" },
  { nume: "Sandulesti", comuna: "Cotmeana" },
  { nume: "Ursoaia", comuna: "Cotmeana" },
  { nume: "Varloveni", comuna: "Cotmeana" },
  { nume: "Zamfiresti", comuna: "Cotmeana" },
  { nume: "Baltata", comuna: "Cuca" },
  { nume: "Barbalani", comuna: "Cuca" },
  { nume: "Cotu", comuna: "Cuca" },
  { nume: "Crivatu", comuna: "Cuca" },
  { nume: "Carcesti", comuna: "Cuca" },
  { nume: "Launele de Sus", comuna: "Cuca" },
  { nume: "Macai", comuna: "Cuca" },
  { nume: "Manesti", comuna: "Cuca" },
  { nume: "Sinesti", comuna: "Cuca" },
  { nume: "Stanicei", comuna: "Cuca" },
  { nume: "Teodoresti", comuna: "Cuca" },
  { nume: "Valea Cucii", comuna: "Cuca" },
  { nume: "Vonigeasa", comuna: "Cuca" },
  { nume: "Noaptes", comuna: "Curtea De Arges" },
  { nume: "Ciocanu", comuna: "Dambovicioara" },
  { nume: "Podu Dambovitei", comuna: "Dambovicioara" },
  { nume: "Negreni", comuna: "Darmanesti" },
  { nume: "Piscani", comuna: "Darmanesti" },
  { nume: "Valea Nandrii", comuna: "Darmanesti" },
  { nume: "Valea Rizii", comuna: "Darmanesti" },
  { nume: "Contesti", comuna: "Davidesti" },
  { nume: "Voroveni", comuna: "Davidesti" },
  { nume: "Furesti", comuna: "Dobresti" },
  { nume: "Bacesti", comuna: "Draganu" },
  { nume: "Draganu-Olteni", comuna: "Draganu" },
  { nume: "Dumbravesti", comuna: "Draganu" },
  { nume: "Prislopu Mare", comuna: "Draganu" },
  { nume: "Valea Hotarului", comuna: "Dragoslavele" },
  { nume: "Bordeieni", comuna: "Godeni" },
  { nume: "Capu Piscului", comuna: "Godeni" },
  { nume: "Cotesti", comuna: "Godeni" },
  { nume: "Malu", comuna: "Godeni" },
  { nume: "Ciobani", comuna: "Harsesti" },
  { nume: "Martalogi", comuna: "Harsesti" },
  { nume: "Dealu", comuna: "Hartiesti" },
  { nume: "Lespezi", comuna: "Hartiesti" },
  { nume: "Lucieni", comuna: "Hartiesti" },
  { nume: "Baloteasca", comuna: "Leordeni" },
  { nume: "Budisteni", comuna: "Leordeni" },
  { nume: "Bantau", comuna: "Leordeni" },
  { nume: "Baila", comuna: "Leordeni" },
  { nume: "Ciolcesti", comuna: "Leordeni" },
  { nume: "Ciulnita", comuna: "Leordeni" },
  { nume: "Cotu Malului", comuna: "Leordeni" },
  { nume: "Carciumaresti", comuna: "Leordeni" },
  { nume: "Glodu", comuna: "Leordeni" },
  { nume: "Glambocata", comuna: "Leordeni" },
  { nume: "Glambocata-Deal", comuna: "Leordeni" },
  { nume: "Moara Mocanului", comuna: "Leordeni" },
  { nume: "Schitu Scoicesti", comuna: "Leordeni" },
  { nume: "Pojorata", comuna: "Leresti" },
  { nume: "Voinesti", comuna: "Leresti" },
  { nume: "Bumbueni", comuna: "Lunca Corbului" },
  { nume: "Catane", comuna: "Lunca Corbului" },
  { nume: "Ciesti", comuna: "Lunca Corbului" },
  { nume: "Langesti", comuna: "Lunca Corbului" },
  { nume: "Marghia de Jos", comuna: "Lunca Corbului" },
  { nume: "Marghia de Sus", comuna: "Lunca Corbului" },
  { nume: "Padureti", comuna: "Lunca Corbului" },
  { nume: "Silisteni", comuna: "Lunca Corbului" },
  { nume: "Bunesti", comuna: "Malureni" },
  { nume: "Pauleasca", comuna: "Malureni" },
  { nume: "Toplita", comuna: "Malureni" },
  { nume: "Zarnesti", comuna: "Malureni" },
  { nume: "Argeselu", comuna: "Maracineni" },
  { nume: "Borlesti", comuna: "Merisani" },
  { nume: "Brateasca", comuna: "Merisani" },
  { nume: "Capu Piscului", comuna: "Merisani" },
  { nume: "Crampotani", comuna: "Merisani" },
  { nume: "Dobrogostea", comuna: "Merisani" },
  { nume: "Malu Vanat", comuna: "Merisani" },
  { nume: "Valcelele", comuna: "Merisani" },
  { nume: "Varzaru", comuna: "Merisani" },
  { nume: "Branzari", comuna: "Micesti" },
  { nume: "Purcareni", comuna: "Micesti" },
  { nume: "Pauleasca", comuna: "Micesti" },
  { nume: "Draghici", comuna: "Mihaesti" },
  { nume: "Furnicosi", comuna: "Mihaesti" },
  { nume: "Rudeni", comuna: "Mihaesti" },
  { nume: "Valea Bradului", comuna: "Mihaesti" },
  { nume: "Valea Popii", comuna: "Mihaesti" },
  { nume: "Vacarea", comuna: "Mihaesti" },
  { nume: "Alunis", comuna: "Mioarele" },
  { nume: "Chilii", comuna: "Mioarele" },
  { nume: "Cocenesti", comuna: "Mioarele" },
  { nume: "Matau", comuna: "Mioarele" },
  { nume: "Suslanesti", comuna: "Mioarele" },
  { nume: "Clucereasa", comuna: "Mioveni" },
  { nume: "Colibasi", comuna: "Mioveni" },
  { nume: "Fagetu", comuna: "Mioveni" },
  { nume: "Racovita", comuna: "Mioveni" },
  { nume: "Surdulesti", comuna: "Mirosi" },
  { nume: "Dealu Obejdeanului", comuna: "Moraresti" },
  { nume: "Dedulesti", comuna: "Moraresti" },
  { nume: "Luminile", comuna: "Moraresti" },
  { nume: "Mancioiu", comuna: "Moraresti" },
  { nume: "Sapunari", comuna: "Moraresti" },
  { nume: "Batrani", comuna: "Mosoaia" },
  { nume: "Ciocanai", comuna: "Mosoaia" },
  { nume: "Dealu Viilor", comuna: "Mosoaia" },
  { nume: "Hintesti", comuna: "Mosoaia" },
  { nume: "Lazaresti", comuna: "Mosoaia" },
  { nume: "Smeura", comuna: "Mosoaia" },
  { nume: "Babaroaga", comuna: "Mozaceni" },
  { nume: "Zidurile", comuna: "Mozaceni" },
  { nume: "Bolovanesti", comuna: "Musatesti" },
  { nume: "Costesti-Vaslan", comuna: "Musatesti" },
  { nume: "Prosia", comuna: "Musatesti" },
  { nume: "Robaia", comuna: "Musatesti" },
  { nume: "Stroesti", comuna: "Musatesti" },
  { nume: "Valea Faurului", comuna: "Musatesti" },
  { nume: "Valea Muscelului", comuna: "Musatesti" },
  { nume: "Valea lui Mas", comuna: "Musatesti" },
  { nume: "Valsanesti", comuna: "Musatesti" },
  { nume: "Buta", comuna: "Negrasi" },
  { nume: "Barlogu", comuna: "Negrasi" },
  { nume: "Mozacu", comuna: "Negrasi" },
  { nume: "Gruiu", comuna: "Nucsoara" },
  { nume: "Sboghitesti", comuna: "Nucsoara" },
  { nume: "Slatina", comuna: "Nucsoara" },
  { nume: "Ceausesti", comuna: "Oarja" },
  { nume: "Badesti", comuna: "Pietrosani" },
  { nume: "Ganesti", comuna: "Pietrosani" },
  { nume: "Retevoiesti", comuna: "Pietrosani" },
  { nume: "Varzaroaia", comuna: "Pietrosani" },
  { nume: "Cepari", comuna: "Poiana Lacului" },
  { nume: "Catunasi", comuna: "Poiana Lacului" },
  { nume: "Dealu Orasului", comuna: "Poiana Lacului" },
  { nume: "Dealu Viilor", comuna: "Poiana Lacului" },
  { nume: "Dinculesti", comuna: "Poiana Lacului" },
  { nume: "Galcesti", comuna: "Poiana Lacului" },
  { nume: "Galeteanu", comuna: "Poiana Lacului" },
  { nume: "Gardinesti", comuna: "Poiana Lacului" },
  { nume: "Metofu", comuna: "Poiana Lacului" },
  { nume: "Paduroiu din Deal", comuna: "Poiana Lacului" },
  { nume: "Paduroiu din Vale", comuna: "Poiana Lacului" },
  { nume: "Samara", comuna: "Poiana Lacului" },
  { nume: "Ceauresti", comuna: "Poienarii De Arges" },
  { nume: "Ioanicesti", comuna: "Poienarii De Arges" },
  { nume: "Poienari", comuna: "Poienarii De Arges" },
  { nume: "Tomulesti", comuna: "Poienarii De Arges" },
  { nume: "Grosani", comuna: "Poienarii De Muscel" },
  { nume: "Jugur", comuna: "Poienarii De Muscel" },
  { nume: "Poienari", comuna: "Poienarii De Muscel" },
  { nume: "Valea Indarat", comuna: "Poienarii De Muscel" },
  { nume: "Serbanesti", comuna: "Poienarii De Muscel" },
  { nume: "Palanga", comuna: "Popesti" },
  { nume: "Purcareni", comuna: "Popesti" },
  { nume: "Slobozia", comuna: "Popesti" },
  { nume: "Albotele", comuna: "Priboieni" },
  { nume: "Paraschivesti", comuna: "Priboieni" },
  { nume: "Pitoi", comuna: "Priboieni" },
  { nume: "Samaila", comuna: "Priboieni" },
  { nume: "Valea Mare", comuna: "Priboieni" },
  { nume: "Valea Nenii", comuna: "Priboieni" },
  { nume: "Valea Popii", comuna: "Priboieni" },
  { nume: "Adunati", comuna: "Raca" },
  { nume: "Bucov", comuna: "Raca" },
  { nume: "Ciupa-Manciulescu", comuna: "Ratesti" },
  { nume: "Furduesti", comuna: "Ratesti" },
  { nume: "Mavrodolu", comuna: "Ratesti" },
  { nume: "Nejlovelu", comuna: "Ratesti" },
  { nume: "Patuleni", comuna: "Ratesti" },
  { nume: "Tigveni", comuna: "Ratesti" },
  { nume: "Deagu de Jos", comuna: "Recea" },
  { nume: "Deagu de Sus", comuna: "Recea" },
  { nume: "Goleasca", comuna: "Recea" },
  { nume: "Orodel", comuna: "Recea" },
  { nume: "Gliganu de Jos", comuna: "Rociu" },
  { nume: "Gliganu de Sus", comuna: "Rociu" },
  { nume: "Serbanesti", comuna: "Rociu" },
  { nume: "Satic", comuna: "Rucar" },
  { nume: "Valeni", comuna: "Salatrucu" },
  { nume: "Banaresti", comuna: "Sapata" },
  { nume: "Dealu Bradului", comuna: "Sapata" },
  { nume: "Draghicesti", comuna: "Sapata" },
  { nume: "Gainusa", comuna: "Sapata" },
  { nume: "Lipia", comuna: "Sapata" },
  { nume: "Martesti", comuna: "Sapata" },
  { nume: "Popesti", comuna: "Sapata" },
  { nume: "Turcesti", comuna: "Sapata" },
  { nume: "Burnesti", comuna: "Schitu Golesti" },
  { nume: "Costita", comuna: "Schitu Golesti" },
  { nume: "Loturi", comuna: "Schitu Golesti" },
  { nume: "Lazaresti", comuna: "Schitu Golesti" },
  { nume: "Valea Pechii", comuna: "Schitu Golesti" },
  { nume: "Nigrisoara", comuna: "Slobozia" },
  { nume: "Dealu Frumos", comuna: "Stalpeni" },
  { nume: "Livezeni", comuna: "Stalpeni" },
  { nume: "Ogrezea", comuna: "Stalpeni" },
  { nume: "Opresti", comuna: "Stalpeni" },
  { nume: "Pitigaia", comuna: "Stalpeni" },
  { nume: "Radesti", comuna: "Stalpeni" },
  { nume: "Glavacioc", comuna: "Stefan Cel Mare" },
  { nume: "Enculesti", comuna: "Stefanesti" },
  { nume: "Golesti", comuna: "Stefanesti" },
  { nume: "Izvorani", comuna: "Stefanesti" },
  { nume: "Valea Mare-Podgoria", comuna: "Stefanesti" },
  { nume: "Viisoara", comuna: "Stefanesti" },
  { nume: "Zavoi", comuna: "Stefanesti" },
  { nume: "Stefanestii Noi", comuna: "Stefanesti" },
  { nume: "Badeni", comuna: "Stoenesti" },
  { nume: "Cotenesti", comuna: "Stoenesti" },
  { nume: "Lunca Gartii", comuna: "Stoenesti" },
  { nume: "Piatra", comuna: "Stoenesti" },
  { nume: "Slobozia", comuna: "Stoenesti" },
  { nume: "Valea Badenilor", comuna: "Stoenesti" },
  { nume: "Cochinesti", comuna: "Stolnici" },
  { nume: "Cotmeana", comuna: "Stolnici" },
  { nume: "Falfani", comuna: "Stolnici" },
  { nume: "Izbasesti", comuna: "Stolnici" },
  { nume: "Vlascuta", comuna: "Stolnici" },
  { nume: "Ianculesti", comuna: "Suici" },
  { nume: "Paltenu", comuna: "Suici" },
  { nume: "Pauleni", comuna: "Suici" },
  { nume: "Rudeni", comuna: "Suici" },
  { nume: "Valea Calului", comuna: "Suici" },
  { nume: "Burdesti", comuna: "Suseni" },
  { nume: "Cersani", comuna: "Suseni" },
  { nume: "Chiritesti", comuna: "Suseni" },
  { nume: "Galesesti", comuna: "Suseni" },
  { nume: "Odaeni", comuna: "Suseni" },
  { nume: "Padureni", comuna: "Suseni" },
  { nume: "Stefanesti", comuna: "Suseni" },
  { nume: "Strambeni", comuna: "Suseni" },
  { nume: "Tutulesti", comuna: "Suseni" },
  { nume: "Lesile", comuna: "Teiu" },
  { nume: "Blaju", comuna: "Tigveni" },
  { nume: "Barsestii de Jos", comuna: "Tigveni" },
  { nume: "Barsestii de Sus", comuna: "Tigveni" },
  { nume: "Badislava", comuna: "Tigveni" },
  { nume: "Balilesti", comuna: "Tigveni" },
  { nume: "Balteni", comuna: "Tigveni" },
  { nume: "Vladesti", comuna: "Tigveni" },
  { nume: "Bucsenesti-Lotasi", comuna: "Titesti" },
  { nume: "Cismea", comuna: "Titesti" },
  { nume: "Valea Manastirii", comuna: "Titesti" },
  { nume: "Valea Stanii", comuna: "Titesti" },
  { nume: "Botarcani", comuna: "Topoloveni" },
  { nume: "Crintesti", comuna: "Topoloveni" },
  { nume: "Goranesti", comuna: "Topoloveni" },
  { nume: "Tiganesti", comuna: "Topoloveni" },
  { nume: "Branistea", comuna: "Uda" },
  { nume: "Badulesti", comuna: "Uda" },
  { nume: "Baranesti", comuna: "Uda" },
  { nume: "Chiritesti", comuna: "Uda" },
  { nume: "Cotu", comuna: "Uda" },
  { nume: "Dealu Bisericii", comuna: "Uda" },
  { nume: "Dealu Tolcesii", comuna: "Uda" },
  { nume: "Diconesti", comuna: "Uda" },
  { nume: "Gorani", comuna: "Uda" },
  { nume: "Greaban", comuna: "Uda" },
  { nume: "Lungulesti", comuna: "Uda" },
  { nume: "Miercani", comuna: "Uda" },
  { nume: "Romana", comuna: "Uda" },
  { nume: "Rajletu-Govora", comuna: "Uda" },
  { nume: "Salistea", comuna: "Uda" },
  { nume: "Coltu", comuna: "Ungheni" },
  { nume: "Goia", comuna: "Ungheni" },
  { nume: "Gaujani", comuna: "Ungheni" },
  { nume: "Humele", comuna: "Ungheni" },
  { nume: "Satu Nou", comuna: "Ungheni" },
  { nume: "Bolculesti", comuna: "Valea Danului" },
  { nume: "Borobanesti", comuna: "Valea Danului" },
  { nume: "Banicesti", comuna: "Valea Danului" },
  { nume: "Vernesti", comuna: "Valea Danului" },
  { nume: "Borovinesti", comuna: "Valea Iasului" },
  { nume: "Badila", comuna: "Valea Iasului" },
  { nume: "Barbalatesti", comuna: "Valea Iasului" },
  { nume: "Cerbureni", comuna: "Valea Iasului" },
  { nume: "Mustatesti", comuna: "Valea Iasului" },
  { nume: "Ruginoasa", comuna: "Valea Iasului" },
  { nume: "Ungureni", comuna: "Valea Iasului" },
  { nume: "Valea Uleiului", comuna: "Valea Iasului" },
  { nume: "Bilcesti", comuna: "Valea Mare Pravat" },
  { nume: "Colnic", comuna: "Valea Mare Pravat" },
  { nume: "Fantanea", comuna: "Valea Mare Pravat" },
  { nume: "Gura Pravat", comuna: "Valea Mare Pravat" },
  { nume: "Namaesti", comuna: "Valea Mare Pravat" },
  { nume: "Pietroasa", comuna: "Valea Mare Pravat" },
  { nume: "Selari", comuna: "Valea Mare Pravat" },
  { nume: "Blejani", comuna: "Vedea" },
  { nume: "Buretesti", comuna: "Vedea" },
  { nume: "Badicea", comuna: "Vedea" },
  { nume: "Chiritesti", comuna: "Vedea" },
  { nume: "Chitani", comuna: "Vedea" },
  { nume: "Ciuresti", comuna: "Vedea" },
  { nume: "Dincani", comuna: "Vedea" },
  { nume: "Fata", comuna: "Vedea" },
  { nume: "Fratici", comuna: "Vedea" },
  { nume: "Izvoru de Jos", comuna: "Vedea" },
  { nume: "Izvoru de Sus", comuna: "Vedea" },
  { nume: "Lungani", comuna: "Vedea" },
  { nume: "Mogosesti", comuna: "Vedea" },
  { nume: "Prodani", comuna: "Vedea" },
  { nume: "Ratoi", comuna: "Vedea" },
  { nume: "Vata", comuna: "Vedea" },
  { nume: "Vetisoara", comuna: "Vedea" },
  { nume: "Varsesti", comuna: "Vedea" },
  { nume: "Coteasca", comuna: "Vladesti" },
  { nume: "Draghescu", comuna: "Vladesti" },
  { nume: "Putina", comuna: "Vladesti" },
  { nume: "Barzesti", comuna: "Vulturesti" },
  { nume: "Huluba", comuna: "Vulturesti" },
];
