export const ag = [
  { nume: "Adunaţi", simplu: "Adunati", comuna: "Raca" },
  { nume: "Afrimeşti", simplu: "Afrimesti", comuna: "Barla" },
  { nume: "Albeşti", simplu: "Albesti", comuna: "Albestii De Muscel" },
  {
    nume: "Albeştii Pamânteni",
    simplu: "Albestii Pamanteni",
    comuna: "Albestii De Arges",
  },
  {
    nume: "Albeştii Ungureni",
    simplu: "Albestii Ungureni",
    comuna: "Albestii De Arges",
  },
  { nume: "Albota" },
  { nume: "Albotele", comuna: "Priboieni" },
  { nume: "Aluniş", simplu: "Alunis", comuna: "Mioarele" },
  { nume: "Alunişu", simplu: "Alunisu", comuna: "Baiculesti" },
  { nume: "Alunişu", simplu: "Alunisu", comuna: "Bradulet" },
  { nume: "Anghineşti", simplu: "Anghinesti", comuna: "Baiculesti" },
  { nume: "Aninoasa" },
  { nume: "Arefu" },
  { nume: "Argeşani", simplu: "Argesani", comuna: "Baiculesti" },
  { nume: "Argeşelu", simplu: "Argeselu", comuna: "Maracineni" },
  { nume: "Băbana", simplu: "Babana" },
  { nume: "Babaroaga", comuna: "Mozaceni" },
  { nume: "Băceşti", simplu: "Bacesti", comuna: "Draganu" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Stoenesti" },
  { nume: "Bădeşti", simplu: "Badesti", comuna: "Barla" },
  { nume: "Bădeşti", simplu: "Badesti", comuna: "Pietrosani" },
  { nume: "Bădicea", simplu: "Badicea", comuna: "Vedea" },
  { nume: "Bădila", simplu: "Badila", comuna: "Valea Iasului" },
  { nume: "Bădislava", simplu: "Badislava", comuna: "Tigveni" },
  { nume: "Băduleşti", simplu: "Badulesti", comuna: "Uda" },
  { nume: "Băiculeşti", simplu: "Baiculesti" },
  { nume: "Băila", simplu: "Baila", comuna: "Leordeni" },
  { nume: "Băjăneşti", simplu: "Bajanesti", comuna: "Babana" },
  { nume: "Băjeşti", simplu: "Bajesti", comuna: "Balilesti" },
  { nume: "Balabani", comuna: "Boteni" },
  { nume: "Bălileşti", simplu: "Balilesti" },
  { nume: "Bălileşti", simplu: "Balilesti", comuna: "Tigveni" },
  { nume: "Baloteasca", comuna: "Leordeni" },
  { nume: "Bălţata", simplu: "Baltata", comuna: "Cuca" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Tigveni" },
  { nume: "Bănăreşti", simplu: "Banaresti", comuna: "Sapata" },
  { nume: "Băniceşti", simplu: "Banicesti", comuna: "Valea Danului" },
  { nume: "Bântău", simplu: "Bantau", comuna: "Leordeni" },
  { nume: "Bărăneşti", simplu: "Baranesti", comuna: "Uda" },
  { nume: "Bărăşti", simplu: "Barasti", comuna: "Cicanesti" },
  { nume: "Bărbălani", simplu: "Barbalani", comuna: "Cuca" },
  { nume: "Bărbălăteşti", simplu: "Barbalatesti", comuna: "Valea Iasului" },
  { nume: "Bărbăteşti", simplu: "Barbatesti", comuna: "Cocu" },
  { nume: "Bârla", simplu: "Barla" },
  { nume: "Bârlogu", simplu: "Barlogu", comuna: "Negrasi" },
  { nume: "Bârloi", simplu: "Barloi", comuna: "Bogati" },
  { nume: "Bârseştii de Jos", simplu: "Barsestii de Jos", comuna: "Tigveni" },
  { nume: "Bârseştii de Sus", simplu: "Barsestii de Sus", comuna: "Tigveni" },
  { nume: "Bârzeşti", simplu: "Barzesti", comuna: "Vulturesti" },
  { nume: "Bascov" },
  { nume: "Bascovele", comuna: "Cotmeana" },
  { nume: "Bătrâni", simplu: "Batrani", comuna: "Mosoaia" },
  { nume: "Beculeşti", simplu: "Beculesti", comuna: "Ciomagesti" },
  { nume: "Beleţi", simplu: "Beleti", comuna: "Beleti-Negresti" },
  { nume: "Berevoeşti", simplu: "Berevoesti" },
  { nume: "Berindeşti", simplu: "Berindesti", comuna: "Corbeni" },
  { nume: "Bilceşti", simplu: "Bilcesti", comuna: "Valea Mare Pravat" },
  { nume: "Blaju", comuna: "Tigveni" },
  { nume: "Blejani", comuna: "Vedea" },
  { nume: "Bogaţi", simplu: "Bogati" },
  { nume: "Bolculeşti", simplu: "Bolculesti", comuna: "Valea Danului" },
  { nume: "Bolovăneşti", simplu: "Bolovanesti", comuna: "Musatesti" },
  { nume: "Bordeieni", comuna: "Godeni" },
  { nume: "Borleşti", simplu: "Borlesti", comuna: "Merisani" },
  { nume: "Borobăneşti", simplu: "Borobanesti", comuna: "Valea Danului" },
  { nume: "Borovineşti", simplu: "Borovinesti", comuna: "Valea Iasului" },
  { nume: "Boţârcani", simplu: "Botarcani", comuna: "Topoloveni" },
  { nume: "Boteni" },
  { nume: "Boţeşti", simplu: "Botesti" },
  { nume: "Brabeţi", simplu: "Brabeti", comuna: "Barla" },
  { nume: "Brădetu", simplu: "Bradetu", comuna: "Bradulet" },
  { nume: "Bradu" },
  { nume: "Brăduleţ", simplu: "Bradulet" },
  { nume: "Brăileni", simplu: "Braileni", comuna: "Bascov" },
  { nume: "Braniştea", simplu: "Branistea", comuna: "Uda" },
  { nume: "Brânzari", simplu: "Branzari", comuna: "Micesti" },
  { nume: "Brăteasca", simplu: "Brateasca", comuna: "Merisani" },
  { nume: "Brăteşti", simplu: "Bratesti", comuna: "Albestii De Arges" },
  { nume: "Bratia", comuna: "Berevoesti" },
  { nume: "Bratia", comuna: "Ciomagesti" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Aninoasa" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Costesti" },
  { nume: "Bucov", comuna: "Raca" },
  { nume: "Bucşeneşti-Lotaşi", simplu: "Bucsenesti-Lotasi", comuna: "Titesti" },
  { nume: "Bucşeneşti", simplu: "Bucsenesti", comuna: "Corbeni" },
  { nume: "Budeasa Mare", comuna: "Budeasa" },
  { nume: "Budeasa Mică", simplu: "Budeasa Mica", comuna: "Budeasa" },
  { nume: "Budişteni", simplu: "Budisteni", comuna: "Leordeni" },
  { nume: "Bughea de Jos" },
  { nume: "Bughea de Sus", comuna: "Albestii De Muscel" },
  { nume: "Bujoi", comuna: "Bogati" },
  { nume: "Bujoreni", comuna: "Buzoesti" },
  { nume: "Bumbueni", comuna: "Lunca Corbului" },
  { nume: "Buneşti", simplu: "Bunesti", comuna: "Cotmeana" },
  { nume: "Buneşti", simplu: "Bunesti", comuna: "Malureni" },
  { nume: "Burdea", comuna: "Caldararu" },
  { nume: "Burdeşti", simplu: "Burdesti", comuna: "Suseni" },
  { nume: "Bureţeşti", simplu: "Buretesti", comuna: "Vedea" },
  { nume: "Burluşi", simplu: "Burlusi", comuna: "Ciofrangeni" },
  { nume: "Burneşti", simplu: "Burnesti", comuna: "Schitu Golesti" },
  { nume: "Buta", comuna: "Negrasi" },
  { nume: "Buzoeşti", simplu: "Buzoesti" },
  { nume: "Căldăraru", simplu: "Caldararu" },
  { nume: "Călineşti", simplu: "Calinesti" },
  { nume: "Caloteşti", simplu: "Calotesti", comuna: "Budeasa" },
  { nume: "Câmpulung", simplu: "Campulung" },
  { nume: "Cândeşti", simplu: "Candesti", comuna: "Albestii De Muscel" },
  {
    nume: "Căpăţânenii Pământeni",
    simplu: "Capatanenii Pamanteni",
    comuna: "Arefu",
  },
  {
    nume: "Căpăţânenii Ungureni",
    simplu: "Capatanenii Ungureni",
    comuna: "Arefu",
  },
  { nume: "Capu Piscului", comuna: "Godeni" },
  { nume: "Capu Piscului", comuna: "Merisani" },
  { nume: "Cârceşti", simplu: "Carcesti", comuna: "Cuca" },
  { nume: "Cârciumăreşti", simplu: "Carciumaresti", comuna: "Leordeni" },
  { nume: "Cărpeniş", simplu: "Carpenis", comuna: "Cepari" },
  { nume: "Cârstieni", simplu: "Carstieni", comuna: "Calinesti" },
  { nume: "Catane", comuna: "Lunca Corbului" },
  { nume: "Catanele", comuna: "Cateasca" },
  { nume: "Căteasca", simplu: "Cateasca" },
  { nume: "Cătunaşi", simplu: "Catunasi", comuna: "Poiana Lacului" },
  { nume: "Ceaureşti", simplu: "Ceauresti", comuna: "Poienarii De Arges" },
  { nume: "Ceauşeşti", simplu: "Ceausesti", comuna: "Oarja" },
  { nume: "Cepari", comuna: "Poiana Lacului" },
  { nume: "Ceparii Pământeni", simplu: "Ceparii Pamanteni", comuna: "Cepari" },
  { nume: "Ceparii Ungureni", comuna: "Cepari" },
  { nume: "Cerbu", comuna: "Albota" },
  { nume: "Cerbureni", comuna: "Valea Iasului" },
  { nume: "Cerşani", simplu: "Cersani", comuna: "Suseni" },
  { nume: "Cetăţeni", simplu: "Cetateni" },
  { nume: "Chilii", comuna: "Mioarele" },
  { nume: "Chiriţeşti", simplu: "Chiritesti", comuna: "Suseni" },
  { nume: "Chiriţeşti", simplu: "Chiritesti", comuna: "Uda" },
  { nume: "Chiriţeşti", simplu: "Chiritesti", comuna: "Vedea" },
  { nume: "Chiţani", simplu: "Chitani", comuna: "Vedea" },
  { nume: "Chiţeşti", simplu: "Chitesti", comuna: "Bogati" },
  { nume: "Cicăneşti", simplu: "Cicanesti" },
  { nume: "Cieşti", simplu: "Ciesti", comuna: "Lunca Corbului" },
  { nume: "Ciobăneşti", simplu: "Ciobanesti", comuna: "Babana" },
  { nume: "Ciobani", comuna: "Harsesti" },
  { nume: "Ciocănăi", simplu: "Ciocanai", comuna: "Mosoaia" },
  { nume: "Ciocăneşti", simplu: "Ciocanesti", comuna: "Calinesti" },
  { nume: "Ciocanu", comuna: "Dambovicioara" },
  { nume: "Cioceşti", simplu: "Ciocesti", comuna: "Barla" },
  { nume: "Ciofrângeni", simplu: "Ciofrangeni" },
  { nume: "Ciolceşti", simplu: "Ciolcesti", comuna: "Leordeni" },
  { nume: "Ciomăgeşti", simplu: "Ciomagesti" },
  { nume: "Cireşu", simplu: "Ciresu", comuna: "Cateasca" },
  { nume: "Cişmea", simplu: "Cismea", comuna: "Titesti" },
  { nume: "Ciulniţa", simplu: "Ciulnita", comuna: "Leordeni" },
  { nume: "Ciupa-Mănciulescu", simplu: "Ciupa-Manciulescu", comuna: "Ratesti" },
  { nume: "Ciureşti", simplu: "Ciuresti", comuna: "Vedea" },
  { nume: "Clucereasa", comuna: "Mioveni" },
  { nume: "Coceneşti", simplu: "Cocenesti", comuna: "Mioarele" },
  { nume: "Cochineşti", simplu: "Cochinesti", comuna: "Stolnici" },
  { nume: "Cocu" },
  { nume: "Colibaşi", simplu: "Colibasi", comuna: "Mioveni" },
  { nume: "Colnic", comuna: "Valea Mare Pravat" },
  { nume: "Colţu", simplu: "Coltu", comuna: "Ungheni" },
  { nume: "Conţeşti", simplu: "Contesti", comuna: "Davidesti" },
  { nume: "Corbeni" },
  { nume: "Corbi" },
  { nume: "Corbşori", simplu: "Corbsori", comuna: "Corbi" },
  { nume: "Cornăţel", simplu: "Cornatel", comuna: "Buzoesti" },
  { nume: "Cosaci", comuna: "Bradulet" },
  { nume: "Coşeri", simplu: "Coseri", comuna: "Cateasca" },
  { nume: "Coşeşti", simplu: "Cosesti" },
  { nume: "Costeşti-Vâslan", simplu: "Costesti-Vaslan", comuna: "Musatesti" },
  { nume: "Costeşti", simplu: "Costesti" },
  { nume: "Costeşti", simplu: "Costesti", comuna: "Cotmeana" },
  { nume: "Costiţă", simplu: "Costita", comuna: "Schitu Golesti" },
  { nume: "Coteasca", comuna: "Vladesti" },
  { nume: "Coteneşti", simplu: "Cotenesti", comuna: "Stoenesti" },
  { nume: "Coteşti", simplu: "Cotesti", comuna: "Godeni" },
  { nume: "Cotmeana" },
  { nume: "Cotmeana", comuna: "Stolnici" },
  { nume: "Cotmeniţa", simplu: "Cotmenita", comuna: "Babana" },
  { nume: "Cotu Malului", comuna: "Leordeni" },
  { nume: "Cotu", comuna: "Cuca" },
  { nume: "Cotu", comuna: "Uda" },
  { nume: "Crâmpotani", simplu: "Crampotani", comuna: "Merisani" },
  { nume: "Crinteşti", simplu: "Crintesti", comuna: "Topoloveni" },
  { nume: "Crivăţu", simplu: "Crivatu", comuna: "Cuca" },
  { nume: "Crucişoara", simplu: "Crucisoara", comuna: "Cocu" },
  { nume: "Cuca" },
  { nume: "Cungrea", comuna: "Ciomagesti" },
  { nume: "Curtea de Argeş", simplu: "Curtea de Arges" },
  { nume: "Curteanca", comuna: "Buzoesti" },
  { nume: "Dâmbovicioara", simplu: "Dambovicioara" },
  { nume: "Dârmăneşti", simplu: "Darmanesti" },
  { nume: "Davideşti", simplu: "Davidesti" },
  { nume: "Deagu de Jos", comuna: "Recea" },
  { nume: "Deagu de Sus", comuna: "Recea" },
  { nume: "Dealu Bisericii", comuna: "Uda" },
  { nume: "Dealu Bradului", comuna: "Sapata" },
  { nume: "Dealu Frumos", comuna: "Stalpeni" },
  { nume: "Dealu Obejdeanului", comuna: "Moraresti" },
  {
    nume: "Dealu Oraşului",
    simplu: "Dealu Orasului",
    comuna: "Poiana Lacului",
  },
  { nume: "Dealu Pădurii", simplu: "Dealu Padurii", comuna: "Cotmeana" },
  { nume: "Dealu Tolcesii", comuna: "Uda" },
  { nume: "Dealu Viilor", comuna: "Mosoaia" },
  { nume: "Dealu Viilor", comuna: "Poiana Lacului" },
  { nume: "Dealu", comuna: "Hartiesti" },
  { nume: "Deduleşti", simplu: "Dedulesti", comuna: "Moraresti" },
  { nume: "Diconeşti", simplu: "Diconesti", comuna: "Uda" },
  { nume: "Dincani", comuna: "Vedea" },
  { nume: "Dinculeşti", simplu: "Dinculesti", comuna: "Poiana Lacului" },
  { nume: "Doblea", comuna: "Albestii De Arges" },
  { nume: "Dobreşti", simplu: "Dobresti" },
  { nume: "Dobrogostea", comuna: "Merisani" },
  { nume: "Dobrotu", comuna: "Albestii De Arges" },
  { nume: "Dogari", comuna: "Ciomagesti" },
  { nume: "Domneşti", simplu: "Domnesti" },
  { nume: "Drăganu-Olteni", simplu: "Draganu-Olteni", comuna: "Draganu" },
  { nume: "Drăghescu", simplu: "Draghescu", comuna: "Vladesti" },
  { nume: "Drăghiceşti", simplu: "Draghicesti", comuna: "Sapata" },
  { nume: "Drăghici", simplu: "Draghici", comuna: "Mihaesti" },
  { nume: "Drăgoleşti", simplu: "Dragolesti", comuna: "Cotmeana" },
  { nume: "Dragoslavele" },
  { nume: "Dumbrava", comuna: "Bogati" },
  { nume: "Dumbrăveşti", simplu: "Dumbravesti", comuna: "Draganu" },
  { nume: "Dumireşti", simplu: "Dumiresti", comuna: "Albestii De Arges" },
  { nume: "Enculeşti", simplu: "Enculesti", comuna: "Stefanesti" },
  { nume: "Făcăleţeşti", simplu: "Facaletesti", comuna: "Cocu" },
  { nume: "Făgetu", simplu: "Fagetu", comuna: "Mioveni" },
  { nume: "Fâlfani", simplu: "Falfani", comuna: "Stolnici" },
  { nume: "Fântânea", simplu: "Fantanea", comuna: "Valea Mare Pravat" },
  { nume: "Fata", comuna: "Vedea" },
  { nume: "Fedeleşoiu", simplu: "Fedelesoiu", comuna: "Ciomagesti" },
  { nume: "Florieni", comuna: "Albestii De Arges" },
  { nume: "Frăteşti", simplu: "Fratesti", comuna: "Albota" },
  { nume: "Frătici", simplu: "Fratici", comuna: "Vedea" },
  { nume: "Furdueşti", simplu: "Furduesti", comuna: "Ratesti" },
  { nume: "Fureşti", simplu: "Furesti", comuna: "Dobresti" },
  { nume: "Furnicoşi", simplu: "Furnicosi", comuna: "Mihaesti" },
  { nume: "Găinuşa", simplu: "Gainusa", comuna: "Sapata" },
  { nume: "Gălăşeşti", simplu: "Galasesti", comuna: "Budeasa" },
  { nume: "Gâlceşti", simplu: "Galcesti", comuna: "Poiana Lacului" },
  { nume: "Găleşeşti", simplu: "Galesesti", comuna: "Suseni" },
  { nume: "Galeşu", simplu: "Galesu", comuna: "Bradulet" },
  { nume: "Găleţeanu", simplu: "Galeteanu", comuna: "Poiana Lacului" },
  { nume: "Gămăceşti", simplu: "Gamacesti", comuna: "Berevoesti" },
  { nume: "Găneşti", simplu: "Ganesti", comuna: "Pietrosani" },
  { nume: "Gărdineşti", simplu: "Gardinesti", comuna: "Poiana Lacului" },
  { nume: "Găujani", simplu: "Gaujani", comuna: "Ungheni" },
  { nume: "Geamăna", simplu: "Geamana", comuna: "Bradu" },
  { nume: "Giuclani", comuna: "Ciomagesti" },
  { nume: "Glâmbocata-Deal", simplu: "Glambocata-Deal", comuna: "Leordeni" },
  { nume: "Glâmbocata", simplu: "Glambocata", comuna: "Leordeni" },
  { nume: "Glâmbocel", simplu: "Glambocel", comuna: "Bogati" },
  { nume: "Glâmbocelu", simplu: "Glambocelu", comuna: "Bogati" },
  { nume: "Glâmbocu", simplu: "Glambocu", comuna: "Bascov" },
  { nume: "Glavacioc", comuna: "Stefan Cel Mare" },
  { nume: "Gliganu de Jos", comuna: "Rociu" },
  { nume: "Gliganu de Sus", comuna: "Rociu" },
  { nume: "Glodu", comuna: "Calinesti" },
  { nume: "Glodu", comuna: "Leordeni" },
  { nume: "Godeni" },
  { nume: "Goia", comuna: "Ungheni" },
  { nume: "Goleasca", comuna: "Recea" },
  { nume: "Goleşti", simplu: "Golesti", comuna: "Balilesti" },
  { nume: "Goleşti", simplu: "Golesti", comuna: "Stefanesti" },
  { nume: "Gorăneşti", simplu: "Goranesti", comuna: "Topoloveni" },
  { nume: "Gorani", comuna: "Uda" },
  { nume: "Gorganu", comuna: "Calinesti" },
  { nume: "Greabăn", simplu: "Greaban", comuna: "Uda" },
  { nume: "Greabănu", simplu: "Greabanu", comuna: "Cocu" },
  { nume: "Groşani", simplu: "Grosani", comuna: "Poienarii De Muscel" },
  { nume: "Groşi", simplu: "Grosi", comuna: "Babana" },
  { nume: "Gruiu", comuna: "Cateasca" },
  { nume: "Gruiu", comuna: "Nucsoara" },
  { nume: "Gura Pravăţ", simplu: "Gura Pravat", comuna: "Valea Mare Pravat" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Albota" },
  { nume: "Hârseşti", simplu: "Harsesti" },
  { nume: "Hârtieşti", simplu: "Hartiesti" },
  { nume: "Hinţeşti", simplu: "Hintesti", comuna: "Mosoaia" },
  { nume: "Huluba", comuna: "Vulturesti" },
  { nume: "Humele", comuna: "Ungheni" },
  { nume: "Ianculeşti", simplu: "Ianculesti", comuna: "Suici" },
  { nume: "Ioaniceşti", simplu: "Ioanicesti", comuna: "Poienarii De Arges" },
  { nume: "Ioneşti", simplu: "Ionesti", comuna: "Buzoesti" },
  { nume: "Izbăşeşti", simplu: "Izbasesti", comuna: "Stolnici" },
  { nume: "Izvorani", comuna: "Stefanesti" },
  { nume: "Izvoru de Jos", comuna: "Vedea" },
  { nume: "Izvoru de Sus", comuna: "Vedea" },
  { nume: "Izvoru" },
  { nume: "Jgheaburi", comuna: "Corbi" },
  { nume: "Jugur", comuna: "Poienarii De Muscel" },
  { nume: "Jupâneşti", simplu: "Jupanesti", comuna: "Cosesti" },
  { nume: "Lăceni", simplu: "Laceni", comuna: "Costesti" },
  { nume: "Lacurile", comuna: "Ciofrangeni" },
  { nume: "Lăicăi", simplu: "Laicai", comuna: "Cetateni" },
  { nume: "Lăngeşti", simplu: "Langesti", comuna: "Lunca Corbului" },
  { nume: "Lăpuşani", simplu: "Lapusani", comuna: "Cosesti" },
  { nume: "Lăunele de Sus", simplu: "Launele de Sus", comuna: "Cuca" },
  { nume: "Lăzăreşti", simplu: "Lazaresti", comuna: "Mosoaia" },
  { nume: "Lăzăreşti", simplu: "Lazaresti", comuna: "Schitu Golesti" },
  { nume: "Leiceşti", simplu: "Leicesti", comuna: "Cosesti" },
  { nume: "Lenţea", simplu: "Lentea", comuna: "Beleti-Negresti" },
  { nume: "Leordeni" },
  { nume: "Lereşti", simplu: "Leresti" },
  { nume: "Leşile", simplu: "Lesile", comuna: "Teiu" },
  { nume: "Lespezi", comuna: "Hartiesti" },
  { nume: "Linteşti", simplu: "Lintesti", comuna: "Cotmeana" },
  { nume: "Lipia", comuna: "Sapata" },
  { nume: "Livezeni", comuna: "Stalpeni" },
  { nume: "Loturi", comuna: "Schitu Golesti" },
  { nume: "Lucieni", comuna: "Hartiesti" },
  { nume: "Luminile", comuna: "Moraresti" },
  { nume: "Lunca Corbului" },
  { nume: "Lunca Gârtii", simplu: "Lunca Gartii", comuna: "Stoenesti" },
  { nume: "Lunca", comuna: "Boteni" },
  { nume: "Lungani", comuna: "Vedea" },
  { nume: "Lunguleşti", simplu: "Lungulesti", comuna: "Uda" },
  { nume: "Lupueni", comuna: "Babana" },
  { nume: "Măcăi", simplu: "Macai", comuna: "Cuca" },
  { nume: "Malu Vânăt", simplu: "Malu Vanat", comuna: "Merisani" },
  { nume: "Malu", comuna: "Barla" },
  { nume: "Malu", comuna: "Godeni" },
  { nume: "Mălureni", simplu: "Malureni" },
  { nume: "Măncioiu", simplu: "Mancioiu", comuna: "Moraresti" },
  { nume: "Mândra", simplu: "Mandra", comuna: "Barla" },
  { nume: "Măneşti", simplu: "Manesti", comuna: "Cuca" },
  { nume: "Măniceşti", simplu: "Manicesti", comuna: "Baiculesti" },
  { nume: "Mărăcineni", simplu: "Maracineni" },
  { nume: "Mareş", simplu: "Mares", comuna: "Albota" },
  {
    nume: "Mârghia de Jos",
    simplu: "Marghia de Jos",
    comuna: "Lunca Corbului",
  },
  {
    nume: "Mârghia de Sus",
    simplu: "Marghia de Sus",
    comuna: "Lunca Corbului",
  },
  { nume: "Martalogi", comuna: "Harsesti" },
  { nume: "Mârţeşti", simplu: "Martesti", comuna: "Sapata" },
  { nume: "Măţău", simplu: "Matau", comuna: "Mioarele" },
  { nume: "Mavrodolu", comuna: "Ratesti" },
  { nume: "Merişani", simplu: "Merisani" },
  { nume: "Metofu", comuna: "Poiana Lacului" },
  { nume: "Mica", comuna: "Bascov" },
  { nume: "Miceşti", simplu: "Micesti" },
  { nume: "Miercani", comuna: "Uda" },
  { nume: "Mihăeşti", simplu: "Mihaesti" },
  { nume: "Mioarele", comuna: "Cicanesti" },
  { nume: "Mioveni" },
  { nume: "Miroşi", simplu: "Mirosi" },
  { nume: "Moara Mocanului", comuna: "Leordeni" },
  { nume: "Mogoşeşti", simplu: "Mogosesti", comuna: "Vedea" },
  { nume: "Morăreşti", simplu: "Moraresti" },
  { nume: "Morăşti", simplu: "Morasti", comuna: "Cepari" },
  { nume: "Moşoaia", simplu: "Mosoaia" },
  { nume: "Moşteni-Greci", simplu: "Mosteni-Greci", comuna: "Botesti" },
  { nume: "Mozăceni", simplu: "Mozaceni" },
  { nume: "Mozăcenii-Vale", simplu: "Mozacenii-Vale", comuna: "Barla" },
  { nume: "Mozacu", comuna: "Negrasi" },
  { nume: "Musăţeşti", simplu: "Musatesti" },
  { nume: "Muşcel", simplu: "Muscel", comuna: "Boteni" },
  { nume: "Mustăţeşti", simplu: "Mustatesti", comuna: "Valea Iasului" },
  { nume: "Nămăeşti", simplu: "Namaesti", comuna: "Valea Mare Pravat" },
  { nume: "Negeşti", simplu: "Negesti", comuna: "Cotmeana" },
  { nume: "Negraşi", simplu: "Negrasi" },
  { nume: "Negreni", comuna: "Darmanesti" },
  { nume: "Negreşti", simplu: "Negresti", comuna: "Beleti-Negresti" },
  { nume: "Nejlovelu", comuna: "Ratesti" },
  { nume: "Nigrişoara", simplu: "Nigrisoara", comuna: "Slobozia" },
  { nume: "Noapteş", simplu: "Noaptes", comuna: "Curtea De Arges" },
  { nume: "Nucşoara", simplu: "Nucsoara" },
  { nume: "Oarja" },
  { nume: "Odăeni", simplu: "Odaeni", comuna: "Suseni" },
  { nume: "Oeştii Pamânteni", simplu: "Oestii Pamanteni", comuna: "Corbeni" },
  { nume: "Oeştii Ungureni", simplu: "Oestii Ungureni", comuna: "Corbeni" },
  { nume: "Ogrezea", comuna: "Stalpeni" },
  { nume: "Opreşti", simplu: "Opresti", comuna: "Stalpeni" },
  { nume: "Orodel", comuna: "Recea" },
  { nume: "Oţelu", simplu: "Otelu", comuna: "Berevoesti" },
  { nume: "Păcioiu", simplu: "Pacioiu", comuna: "Cosesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Suseni" },
  { nume: "Pădureţi", simplu: "Padureti", comuna: "Lunca Corbului" },
  {
    nume: "Păduroiu din Deal",
    simplu: "Paduroiu din Deal",
    comuna: "Poiana Lacului",
  },
  {
    nume: "Păduroiu din Vale",
    simplu: "Paduroiu din Vale",
    comuna: "Poiana Lacului",
  },
  { nume: "Palanga", comuna: "Popesti" },
  { nume: "Paltenu", comuna: "Suici" },
  { nume: "Paraschiveşti", simplu: "Paraschivesti", comuna: "Priboieni" },
  { nume: "Pârvu Roşu", simplu: "Parvu Rosu", comuna: "Costesti" },
  { nume: "Pătuleni", simplu: "Patuleni", comuna: "Ratesti" },
  { nume: "Păuleasca", simplu: "Pauleasca", comuna: "Malureni" },
  { nume: "Păuleasca", simplu: "Pauleasca", comuna: "Micesti" },
  { nume: "Păuleni", simplu: "Pauleni", comuna: "Suici" },
  { nume: "Păuneşti", simplu: "Paunesti", comuna: "Ciomagesti" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Cosesti" },
  { nume: "Piatra", comuna: "Bradulet" },
  { nume: "Piatra", comuna: "Ciofrangeni" },
  { nume: "Piatra", comuna: "Stoenesti" },
  { nume: "Pieleşti", simplu: "Pielesti", comuna: "Cotmeana" },
  { nume: "Pietroasa", comuna: "Valea Mare Pravat" },
  { nume: "Pietroşani", simplu: "Pietrosani" },
  { nume: "Piscani", comuna: "Darmanesti" },
  { nume: "Piteşti", simplu: "Pitesti" },
  { nume: "Piţigaia", simplu: "Pitigaia", comuna: "Stalpeni" },
  { nume: "Pitoi", comuna: "Priboieni" },
  { nume: "Podeni", comuna: "Buzoesti" },
  { nume: "Podişoru", simplu: "Podisoru", comuna: "Barla" },
  { nume: "Podu Broşteni", simplu: "Podu Brosteni", comuna: "Costesti" },
  {
    nume: "Podu Dâmboviţei",
    simplu: "Podu Dambovitei",
    comuna: "Dambovicioara",
  },
  { nume: "Poduri", comuna: "Corbi" },
  { nume: "Poiana Lacului" },
  { nume: "Poienărei", simplu: "Poienarei", comuna: "Corbi" },
  { nume: "Poienari", comuna: "Corbeni" },
  { nume: "Poienari", comuna: "Poienarii De Arges" },
  { nume: "Poienari", comuna: "Poienarii De Muscel" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Balilesti" },
  { nume: "Pojorâta", simplu: "Pojorata", comuna: "Leresti" },
  { nume: "Popeşti", simplu: "Popesti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Cocu" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Sapata" },
  { nume: "Priboaia", comuna: "Balilesti" },
  { nume: "Priboieni" },
  { nume: "Priseaca", comuna: "Cosesti" },
  { nume: "Prislopu Mare", comuna: "Draganu" },
  { nume: "Prislopu Mic", comuna: "Bascov" },
  { nume: "Prodani", comuna: "Vedea" },
  { nume: "Prosia", comuna: "Musatesti" },
  { nume: "Purcăreni", simplu: "Purcareni", comuna: "Micesti" },
  { nume: "Purcăreni", simplu: "Purcareni", comuna: "Popesti" },
  { nume: "Putina", comuna: "Vladesti" },
  { nume: "Râca", simplu: "Raca" },
  { nume: "Răchiţele de Jos", simplu: "Rachitele de Jos", comuna: "Cocu" },
  { nume: "Răchiţele de Sus", simplu: "Rachitele de Sus", comuna: "Cocu" },
  { nume: "Racoviţa", simplu: "Racovita", comuna: "Mioveni" },
  { nume: "Rădeşti", simplu: "Radesti", comuna: "Stalpeni" },
  { nume: "Radu Negru", comuna: "Calinesti" },
  { nume: "Răduţeşti", simplu: "Radutesti", comuna: "Ciomagesti" },
  { nume: "Râjleţu-Govora", simplu: "Rajletu-Govora", comuna: "Uda" },
  { nume: "Râncăciov", simplu: "Rancaciov", comuna: "Calinesti" },
  { nume: "Răteşti", simplu: "Ratesti" },
  { nume: "Răţoi", simplu: "Ratoi", comuna: "Vedea" },
  { nume: "Recea" },
  { nume: "Recea", comuna: "Cateasca" },
  { nume: "Redea", comuna: "Buzoesti" },
  { nume: "Retevoieşti", simplu: "Retevoiesti", comuna: "Pietrosani" },
  { nume: "Robaia", comuna: "Musatesti" },
  { nume: "Rociu" },
  { nume: "Rogojina", comuna: "Budeasa" },
  { nume: "Romana", comuna: "Uda" },
  { nume: "Rotunda", comuna: "Corbeni" },
  { nume: "Rucăr", simplu: "Rucar" },
  { nume: "Rudeni", comuna: "Mihaesti" },
  { nume: "Rudeni", comuna: "Suici" },
  { nume: "Ruginoasa", comuna: "Valea Iasului" },
  { nume: "Sălătrucu", simplu: "Salatrucu" },
  { nume: "Săliştea", simplu: "Salistea", comuna: "Uda" },
  { nume: "Sămăila", simplu: "Samaila", comuna: "Priboieni" },
  { nume: "Sămara", simplu: "Samara", comuna: "Poiana Lacului" },
  { nume: "Sănduleşti", simplu: "Sandulesti", comuna: "Cotmeana" },
  { nume: "Săpunari", simplu: "Sapunari", comuna: "Moraresti" },
  { nume: "Sătic", simplu: "Satic", comuna: "Rucar" },
  { nume: "Satu Nou", comuna: "Ungheni" },
  { nume: "Sboghiţeşti", simplu: "Sboghitesti", comuna: "Nucsoara" },
  { nume: "Scheau", comuna: "Bascov" },
  { nume: "Schitu Goleşti", simplu: "Schitu Golesti" },
  { nume: "Schitu Scoiceşti", simplu: "Schitu Scoicesti", comuna: "Leordeni" },
  { nume: "Schitu-Matei", comuna: "Ciofrangeni" },
  { nume: "Şelăreasca", simplu: "Selareasca", comuna: "Barla" },
  { nume: "Şelari", simplu: "Selari", comuna: "Valea Mare Pravat" },
  { nume: "Şendruleşti", simplu: "Sendrulesti", comuna: "Cepari" },
  { nume: "Şerbăneşti", simplu: "Serbanesti", comuna: "Poienarii De Muscel" },
  { nume: "Şerbăneşti", simplu: "Serbanesti", comuna: "Rociu" },
  { nume: "Şerboeni", simplu: "Serboeni", comuna: "Buzoesti" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Cateasca" },
  { nume: "Silişteni", simplu: "Silisteni", comuna: "Lunca Corbului" },
  { nume: "Sineşti", simplu: "Sinesti", comuna: "Cuca" },
  { nume: "Slăatioarele", simplu: "Slaatioarele", comuna: "Babana" },
  { nume: "Slămneşti", simplu: "Slamnesti", comuna: "Bradulet" },
  { nume: "Slănic", simplu: "Slanic", comuna: "Aninoasa" },
  { nume: "Slatina", comuna: "Nucsoara" },
  { nume: "Slobozia" },
  { nume: "Slobozia", comuna: "Popesti" },
  { nume: "Slobozia", comuna: "Stoenesti" },
  { nume: "Smei", comuna: "Costesti" },
  { nume: "Smeura", comuna: "Mosoaia" },
  { nume: "Spiridoni", comuna: "Cotmeana" },
  { nume: "Stâlpeni", simplu: "Stalpeni" },
  { nume: "Stăneşti", simplu: "Stanesti", comuna: "Corbi" },
  { nume: "Stănicei", simplu: "Stanicei", comuna: "Cuca" },
  { nume: "Stârci", simplu: "Starci", comuna: "Costesti" },
  { nume: "Ştefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Ştefăneşti", simplu: "Stefanesti" },
  { nume: "Stefăneşti", simplu: "Stefanesti", comuna: "Suseni" },
  { nume: "Ştefăneştii Noi", simplu: "Stefanestii Noi", comuna: "Stefanesti" },
  { nume: "Stejari", comuna: "Baiculesti" },
  { nume: "Stoeneşti", simplu: "Stoenesti" },
  { nume: "Stolnici" },
  { nume: "Strâmbeni", simplu: "Strambeni", comuna: "Caldararu" },
  { nume: "Strâmbeni", simplu: "Strambeni", comuna: "Suseni" },
  { nume: "Stroeşti", simplu: "Stroesti", comuna: "Musatesti" },
  { nume: "Şuici", simplu: "Suici" },
  { nume: "Surduleşti", simplu: "Surdulesti", comuna: "Mirosi" },
  { nume: "Suseni" },
  { nume: "Suseni", comuna: "Bogati" },
  { nume: "Suslăneşti", simplu: "Suslanesti", comuna: "Mioarele" },
  { nume: "Teiu" },
  { nume: "Teodoreşti", simplu: "Teodoresti", comuna: "Cuca" },
  { nume: "Ţigăneşti", simplu: "Tiganesti", comuna: "Topoloveni" },
  { nume: "Tigveni" },
  { nume: "Tigveni", comuna: "Ratesti" },
  { nume: "Ţiţeşti", simplu: "Titesti" },
  { nume: "Tomşanca", simplu: "Tomsanca", comuna: "Buzoesti" },
  { nume: "Tomuleşti", simplu: "Tomulesti", comuna: "Poienarii De Arges" },
  { nume: "Topliţa", simplu: "Toplita", comuna: "Malureni" },
  { nume: "Topoloveni" },
  { nume: "Turburea", comuna: "Corbeni" },
  { nume: "Turceşti", simplu: "Turcesti", comuna: "Sapata" },
  { nume: "Tutana", comuna: "Baiculesti" },
  { nume: "Ţuţuleşti", simplu: "Tutulesti", comuna: "Suseni" },
  { nume: "Uda" },
  { nume: "Udeni-Zăvoi", simplu: "Udeni-Zavoi", comuna: "Calinesti" },
  { nume: "Uiasca", comuna: "Bascov" },
  { nume: "Uleni", comuna: "Bradulet" },
  { nume: "Uliţa", simplu: "Ulita", comuna: "Balilesti" },
  { nume: "Ungheni" },
  { nume: "Ungureni", comuna: "Bradulet" },
  { nume: "Ungureni", comuna: "Valea Iasului" },
  { nume: "Urecheşti", simplu: "Urechesti", comuna: "Cicanesti" },
  { nume: "Urlucea", comuna: "Calinesti" },
  { nume: "Urlueni", comuna: "Barla" },
  { nume: "Urluieşti", simplu: "Urluiesti", comuna: "Cepari" },
  { nume: "Ursoaia", comuna: "Cotmeana" },
  { nume: "Văcarea", simplu: "Vacarea", comuna: "Mihaesti" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Merisani" },
  { nume: "Valea Bădenilor", simplu: "Valea Badenilor", comuna: "Stoenesti" },
  { nume: "Valea Bradului", comuna: "Mihaesti" },
  { nume: "Valea Brazilor", comuna: "Baiculesti" },
  { nume: "Valea Calului", comuna: "Suici" },
  { nume: "Valea Cetăţuia", simplu: "Valea Cetatuia", comuna: "Cetateni" },
  { nume: "Valea Corbului", comuna: "Calinesti" },
  { nume: "Valea Cucii", comuna: "Cuca" },
  { nume: "Valea Danului" },
  { nume: "Valea Faurului", comuna: "Musatesti" },
  { nume: "Valea Hotarului", comuna: "Dragoslavele" },
  { nume: "Valea Iaşului", simplu: "Valea Iasului" },
  {
    nume: "Valea Îndărăt",
    simplu: "Valea Indarat",
    comuna: "Poienarii De Muscel",
  },
  { nume: "Valea lui Enache", comuna: "Baiculesti" },
  { nume: "Valea lui Maş", simplu: "Valea lui Mas", comuna: "Musatesti" },
  { nume: "Valea Măgurei", simplu: "Valea Magurei", comuna: "Cepari" },
  { nume: "Valea Mănăstirii", simplu: "Valea Manastirii", comuna: "Titesti" },
  { nume: "Valea Mare Pravăţ", simplu: "Valea Mare Pravat" },
  { nume: "Valea Mare-Bratia", comuna: "Balilesti" },
  { nume: "Valea Mare-Podgoria", comuna: "Stefanesti" },
  { nume: "Valea Mare", comuna: "Priboieni" },
  { nume: "Valea Mărului", simplu: "Valea Marului", comuna: "Budeasa" },
  { nume: "Valea Muscelului", comuna: "Musatesti" },
  { nume: "Valea Nandrii", comuna: "Darmanesti" },
  { nume: "Valea Nenii", comuna: "Priboieni" },
  { nume: "Valea Pechii", comuna: "Schitu Golesti" },
  { nume: "Valea Popii", comuna: "Mihaesti" },
  { nume: "Valea Popii", comuna: "Priboieni" },
  { nume: "Valea Rizii", comuna: "Darmanesti" },
  {
    nume: "Valea Rumâneştilor",
    simplu: "Valea Rumanestilor",
    comuna: "Campulung",
  },
  { nume: "Valea Siliştii", simplu: "Valea Silistii", comuna: "Aninoasa" },
  { nume: "Valea Stânii", simplu: "Valea Stanii", comuna: "Titesti" },
  { nume: "Valea Uleiului", comuna: "Valea Iasului" },
  { nume: "Valea Ursului", comuna: "Bascov" },
  { nume: "Văleni-Podgoria", simplu: "Valeni-Podgoria", comuna: "Calinesti" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Salatrucu" },
  { nume: "Vâlsăneşti", simplu: "Valsanesti", comuna: "Musatesti" },
  { nume: "Vârloveni", simplu: "Varloveni", comuna: "Cotmeana" },
  { nume: "Vârşeşti", simplu: "Varsesti", comuna: "Vedea" },
  { nume: "Vărzăroaia", simplu: "Varzaroaia", comuna: "Pietrosani" },
  { nume: "Vărzaru", simplu: "Varzaru", comuna: "Merisani" },
  { nume: "Vaţa", simplu: "Vata", comuna: "Vedea" },
  { nume: "Vedea" },
  { nume: "Verneşti", simplu: "Vernesti", comuna: "Valea Danului" },
  { nume: "Veţişoara", simplu: "Vetisoara", comuna: "Vedea" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Stefanesti" },
  { nume: "Vlădeşti", simplu: "Vladesti" },
  { nume: "Vlădeşti", simplu: "Vladesti", comuna: "Tigveni" },
  { nume: "Vlăduţa", simplu: "Vladuta", comuna: "Buzoesti" },
  { nume: "Vlăşcuţa", simplu: "Vlascuta", comuna: "Stolnici" },
  { nume: "Voineşti", simplu: "Voinesti", comuna: "Leresti" },
  { nume: "Vonigeasa", comuna: "Cuca" },
  { nume: "Voroveni", comuna: "Davidesti" },
  { nume: "Vrăneşti", simplu: "Vranesti", comuna: "Calinesti" },
  { nume: "Vulpeşti", simplu: "Vulpesti", comuna: "Buzoesti" },
  { nume: "Vultureşti", simplu: "Vulturesti" },
  { nume: "Zamfireşti", simplu: "Zamfiresti", comuna: "Cepari" },
  { nume: "Zamfireşti", simplu: "Zamfiresti", comuna: "Cotmeana" },
  { nume: "Zărneşti", simplu: "Zarnesti", comuna: "Malureni" },
  { nume: "Zăvoi", simplu: "Zavoi", comuna: "Stefanesti" },
  { nume: "Zgripceşti", simplu: "Zgripcesti", comuna: "Beleti-Negresti" },
  { nume: "Zidurile", comuna: "Mozaceni" },
  { nume: "Zigoneni", comuna: "Baiculesti" },
  { nume: "Zuvelcaţi", simplu: "Zuvelcati", comuna: "Barla" },
];
