export const ag = [
  { nume: "Adunați", simplu: "Adunati", comuna: "Raca" },
  { nume: "Afrimești", simplu: "Afrimesti", comuna: "Barla" },
  { nume: "Albești", simplu: "Albesti", comuna: "Albestii De Muscel" },
  {
    nume: "Albeștii Pamânteni",
    simplu: "Albestii Pamanteni",
    comuna: "Albestii De Arges",
  },
  {
    nume: "Albeștii Ungureni",
    simplu: "Albestii Ungureni",
    comuna: "Albestii De Arges",
  },
  { nume: "Albota" },
  { nume: "Albotele", comuna: "Priboieni" },
  { nume: "Aluniș", simplu: "Alunis", comuna: "Mioarele" },
  { nume: "Alunișu", simplu: "Alunisu", comuna: "Baiculesti" },
  { nume: "Alunișu", simplu: "Alunisu", comuna: "Bradulet" },
  { nume: "Anghinești", simplu: "Anghinesti", comuna: "Baiculesti" },
  { nume: "Aninoasa" },
  { nume: "Arefu" },
  { nume: "Argeșani", simplu: "Argesani", comuna: "Baiculesti" },
  { nume: "Argeșelu", simplu: "Argeselu", comuna: "Maracineni" },
  { nume: "Băbana", simplu: "Babana" },
  { nume: "Babaroaga", comuna: "Mozaceni" },
  { nume: "Băcești", simplu: "Bacesti", comuna: "Draganu" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Stoenesti" },
  { nume: "Bădești", simplu: "Badesti", comuna: "Barla" },
  { nume: "Bădești", simplu: "Badesti", comuna: "Pietrosani" },
  { nume: "Bădicea", simplu: "Badicea", comuna: "Vedea" },
  { nume: "Bădila", simplu: "Badila", comuna: "Valea Iasului" },
  { nume: "Bădislava", simplu: "Badislava", comuna: "Tigveni" },
  { nume: "Bădulești", simplu: "Badulesti", comuna: "Uda" },
  { nume: "Băiculești", simplu: "Baiculesti" },
  { nume: "Băila", simplu: "Baila", comuna: "Leordeni" },
  { nume: "Băjănești", simplu: "Bajanesti", comuna: "Babana" },
  { nume: "Băjești", simplu: "Bajesti", comuna: "Balilesti" },
  { nume: "Balabani", comuna: "Boteni" },
  { nume: "Bălilești", simplu: "Balilesti" },
  { nume: "Bălilești", simplu: "Balilesti", comuna: "Tigveni" },
  { nume: "Baloteasca", comuna: "Leordeni" },
  { nume: "Bălțata", simplu: "Baltata", comuna: "Cuca" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Tigveni" },
  { nume: "Bănărești", simplu: "Banaresti", comuna: "Sapata" },
  { nume: "Bănicești", simplu: "Banicesti", comuna: "Valea Danului" },
  { nume: "Bântău", simplu: "Bantau", comuna: "Leordeni" },
  { nume: "Bărănești", simplu: "Baranesti", comuna: "Uda" },
  { nume: "Bărăști", simplu: "Barasti", comuna: "Cicanesti" },
  { nume: "Bărbălani", simplu: "Barbalani", comuna: "Cuca" },
  { nume: "Bărbălătești", simplu: "Barbalatesti", comuna: "Valea Iasului" },
  { nume: "Bărbătești", simplu: "Barbatesti", comuna: "Cocu" },
  { nume: "Bârla", simplu: "Barla" },
  { nume: "Bârlogu", simplu: "Barlogu", comuna: "Negrasi" },
  { nume: "Bârloi", simplu: "Barloi", comuna: "Bogati" },
  { nume: "Bârseștii de Jos", simplu: "Barsestii de Jos", comuna: "Tigveni" },
  { nume: "Bârseștii de Sus", simplu: "Barsestii de Sus", comuna: "Tigveni" },
  { nume: "Bârzești", simplu: "Barzesti", comuna: "Vulturesti" },
  { nume: "Bascov" },
  { nume: "Bascovele", comuna: "Cotmeana" },
  { nume: "Bătrâni", simplu: "Batrani", comuna: "Mosoaia" },
  { nume: "Beculești", simplu: "Beculesti", comuna: "Ciomagesti" },
  { nume: "Beleți", simplu: "Beleti", comuna: "Beleti-Negresti" },
  { nume: "Berevoești", simplu: "Berevoesti" },
  { nume: "Berindești", simplu: "Berindesti", comuna: "Corbeni" },
  { nume: "Bilcești", simplu: "Bilcesti", comuna: "Valea Mare Pravat" },
  { nume: "Blaju", comuna: "Tigveni" },
  { nume: "Blejani", comuna: "Vedea" },
  { nume: "Bogați", simplu: "Bogati" },
  { nume: "Bolculești", simplu: "Bolculesti", comuna: "Valea Danului" },
  { nume: "Bolovănești", simplu: "Bolovanesti", comuna: "Musatesti" },
  { nume: "Bordeieni", comuna: "Godeni" },
  { nume: "Borlești", simplu: "Borlesti", comuna: "Merisani" },
  { nume: "Borobănești", simplu: "Borobanesti", comuna: "Valea Danului" },
  { nume: "Borovinești", simplu: "Borovinesti", comuna: "Valea Iasului" },
  { nume: "Boțârcani", simplu: "Botarcani", comuna: "Topoloveni" },
  { nume: "Boteni" },
  { nume: "Boțești", simplu: "Botesti" },
  { nume: "Brabeți", simplu: "Brabeti", comuna: "Barla" },
  { nume: "Brădetu", simplu: "Bradetu", comuna: "Bradulet" },
  { nume: "Bradu" },
  { nume: "Brăduleț", simplu: "Bradulet" },
  { nume: "Brăileni", simplu: "Braileni", comuna: "Bascov" },
  { nume: "Braniștea", simplu: "Branistea", comuna: "Uda" },
  { nume: "Brânzari", simplu: "Branzari", comuna: "Micesti" },
  { nume: "Brăteasca", simplu: "Brateasca", comuna: "Merisani" },
  { nume: "Brătești", simplu: "Bratesti", comuna: "Albestii De Arges" },
  { nume: "Bratia", comuna: "Berevoesti" },
  { nume: "Bratia", comuna: "Ciomagesti" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Aninoasa" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Costesti" },
  { nume: "Bucov", comuna: "Raca" },
  { nume: "Bucșenești-Lotași", simplu: "Bucsenesti-Lotasi", comuna: "Titesti" },
  { nume: "Bucșenești", simplu: "Bucsenesti", comuna: "Corbeni" },
  { nume: "Budeasa Mare", comuna: "Budeasa" },
  { nume: "Budeasa Mică", simplu: "Budeasa Mica", comuna: "Budeasa" },
  { nume: "Budișteni", simplu: "Budisteni", comuna: "Leordeni" },
  { nume: "Bughea de Jos" },
  { nume: "Bughea de Sus", comuna: "Albestii De Muscel" },
  { nume: "Bujoi", comuna: "Bogati" },
  { nume: "Bujoreni", comuna: "Buzoesti" },
  { nume: "Bumbueni", comuna: "Lunca Corbului" },
  { nume: "Bunești", simplu: "Bunesti", comuna: "Cotmeana" },
  { nume: "Bunești", simplu: "Bunesti", comuna: "Malureni" },
  { nume: "Burdea", comuna: "Caldararu" },
  { nume: "Burdești", simplu: "Burdesti", comuna: "Suseni" },
  { nume: "Burețești", simplu: "Buretesti", comuna: "Vedea" },
  { nume: "Burluși", simplu: "Burlusi", comuna: "Ciofrangeni" },
  { nume: "Burnești", simplu: "Burnesti", comuna: "Schitu Golesti" },
  { nume: "Buta", comuna: "Negrasi" },
  { nume: "Buzoești", simplu: "Buzoesti" },
  { nume: "Căldăraru", simplu: "Caldararu" },
  { nume: "Călinești", simplu: "Calinesti" },
  { nume: "Calotești", simplu: "Calotesti", comuna: "Budeasa" },
  { nume: "Câmpulung", simplu: "Campulung" },
  { nume: "Cândești", simplu: "Candesti", comuna: "Albestii De Muscel" },
  {
    nume: "Căpățânenii Pământeni",
    simplu: "Capatanenii Pamanteni",
    comuna: "Arefu",
  },
  {
    nume: "Căpățânenii Ungureni",
    simplu: "Capatanenii Ungureni",
    comuna: "Arefu",
  },
  { nume: "Capu Piscului", comuna: "Godeni" },
  { nume: "Capu Piscului", comuna: "Merisani" },
  { nume: "Cârcești", simplu: "Carcesti", comuna: "Cuca" },
  { nume: "Cârciumărești", simplu: "Carciumaresti", comuna: "Leordeni" },
  { nume: "Cărpeniș", simplu: "Carpenis", comuna: "Cepari" },
  { nume: "Cârstieni", simplu: "Carstieni", comuna: "Calinesti" },
  { nume: "Catane", comuna: "Lunca Corbului" },
  { nume: "Catanele", comuna: "Cateasca" },
  { nume: "Căteasca", simplu: "Cateasca" },
  { nume: "Cătunași", simplu: "Catunasi", comuna: "Poiana Lacului" },
  { nume: "Ceaurești", simplu: "Ceauresti", comuna: "Poienarii De Arges" },
  { nume: "Ceaușești", simplu: "Ceausesti", comuna: "Oarja" },
  { nume: "Cepari", comuna: "Poiana Lacului" },
  { nume: "Ceparii Pământeni", simplu: "Ceparii Pamanteni", comuna: "Cepari" },
  { nume: "Ceparii Ungureni", comuna: "Cepari" },
  { nume: "Cerbu", comuna: "Albota" },
  { nume: "Cerbureni", comuna: "Valea Iasului" },
  { nume: "Cerșani", simplu: "Cersani", comuna: "Suseni" },
  { nume: "Cetățeni", simplu: "Cetateni" },
  { nume: "Chilii", comuna: "Mioarele" },
  { nume: "Chirițești", simplu: "Chiritesti", comuna: "Suseni" },
  { nume: "Chirițești", simplu: "Chiritesti", comuna: "Uda" },
  { nume: "Chirițești", simplu: "Chiritesti", comuna: "Vedea" },
  { nume: "Chițani", simplu: "Chitani", comuna: "Vedea" },
  { nume: "Chițești", simplu: "Chitesti", comuna: "Bogati" },
  { nume: "Cicănești", simplu: "Cicanesti" },
  { nume: "Ciești", simplu: "Ciesti", comuna: "Lunca Corbului" },
  { nume: "Ciobănești", simplu: "Ciobanesti", comuna: "Babana" },
  { nume: "Ciobani", comuna: "Harsesti" },
  { nume: "Ciocănăi", simplu: "Ciocanai", comuna: "Mosoaia" },
  { nume: "Ciocănești", simplu: "Ciocanesti", comuna: "Calinesti" },
  { nume: "Ciocanu", comuna: "Dambovicioara" },
  { nume: "Ciocești", simplu: "Ciocesti", comuna: "Barla" },
  { nume: "Ciofrângeni", simplu: "Ciofrangeni" },
  { nume: "Ciolcești", simplu: "Ciolcesti", comuna: "Leordeni" },
  { nume: "Ciomăgești", simplu: "Ciomagesti" },
  { nume: "Cireșu", simplu: "Ciresu", comuna: "Cateasca" },
  { nume: "Cișmea", simplu: "Cismea", comuna: "Titesti" },
  { nume: "Ciulnița", simplu: "Ciulnita", comuna: "Leordeni" },
  { nume: "Ciupa-Mănciulescu", simplu: "Ciupa-Manciulescu", comuna: "Ratesti" },
  { nume: "Ciurești", simplu: "Ciuresti", comuna: "Vedea" },
  { nume: "Clucereasa", comuna: "Mioveni" },
  { nume: "Cocenești", simplu: "Cocenesti", comuna: "Mioarele" },
  { nume: "Cochinești", simplu: "Cochinesti", comuna: "Stolnici" },
  { nume: "Cocu" },
  { nume: "Colibași", simplu: "Colibasi", comuna: "Mioveni" },
  { nume: "Colnic", comuna: "Valea Mare Pravat" },
  { nume: "Colțu", simplu: "Coltu", comuna: "Ungheni" },
  { nume: "Conțești", simplu: "Contesti", comuna: "Davidesti" },
  { nume: "Corbeni" },
  { nume: "Corbi" },
  { nume: "Corbșori", simplu: "Corbsori", comuna: "Corbi" },
  { nume: "Cornățel", simplu: "Cornatel", comuna: "Buzoesti" },
  { nume: "Cosaci", comuna: "Bradulet" },
  { nume: "Coșeri", simplu: "Coseri", comuna: "Cateasca" },
  { nume: "Coșești", simplu: "Cosesti" },
  { nume: "Costești-Vâslan", simplu: "Costesti-Vaslan", comuna: "Musatesti" },
  { nume: "Costești", simplu: "Costesti" },
  { nume: "Costești", simplu: "Costesti", comuna: "Cotmeana" },
  { nume: "Costiță", simplu: "Costita", comuna: "Schitu Golesti" },
  { nume: "Coteasca", comuna: "Vladesti" },
  { nume: "Cotenești", simplu: "Cotenesti", comuna: "Stoenesti" },
  { nume: "Cotești", simplu: "Cotesti", comuna: "Godeni" },
  { nume: "Cotmeana" },
  { nume: "Cotmeana", comuna: "Stolnici" },
  { nume: "Cotmenița", simplu: "Cotmenita", comuna: "Babana" },
  { nume: "Cotu Malului", comuna: "Leordeni" },
  { nume: "Cotu", comuna: "Cuca" },
  { nume: "Cotu", comuna: "Uda" },
  { nume: "Crâmpotani", simplu: "Crampotani", comuna: "Merisani" },
  { nume: "Crintești", simplu: "Crintesti", comuna: "Topoloveni" },
  { nume: "Crivățu", simplu: "Crivatu", comuna: "Cuca" },
  { nume: "Crucișoara", simplu: "Crucisoara", comuna: "Cocu" },
  { nume: "Cuca" },
  { nume: "Cungrea", comuna: "Ciomagesti" },
  { nume: "Curtea de Argeș", simplu: "Curtea de Arges" },
  { nume: "Curteanca", comuna: "Buzoesti" },
  { nume: "Dâmbovicioara", simplu: "Dambovicioara" },
  { nume: "Dârmănești", simplu: "Darmanesti" },
  { nume: "Davidești", simplu: "Davidesti" },
  { nume: "Deagu de Jos", comuna: "Recea" },
  { nume: "Deagu de Sus", comuna: "Recea" },
  { nume: "Dealu Bisericii", comuna: "Uda" },
  { nume: "Dealu Bradului", comuna: "Sapata" },
  { nume: "Dealu Frumos", comuna: "Stalpeni" },
  { nume: "Dealu Obejdeanului", comuna: "Moraresti" },
  {
    nume: "Dealu Orașului",
    simplu: "Dealu Orasului",
    comuna: "Poiana Lacului",
  },
  { nume: "Dealu Pădurii", simplu: "Dealu Padurii", comuna: "Cotmeana" },
  { nume: "Dealu Tolcesii", comuna: "Uda" },
  { nume: "Dealu Viilor", comuna: "Mosoaia" },
  { nume: "Dealu Viilor", comuna: "Poiana Lacului" },
  { nume: "Dealu", comuna: "Hartiesti" },
  { nume: "Dedulești", simplu: "Dedulesti", comuna: "Moraresti" },
  { nume: "Diconești", simplu: "Diconesti", comuna: "Uda" },
  { nume: "Dincani", comuna: "Vedea" },
  { nume: "Dinculești", simplu: "Dinculesti", comuna: "Poiana Lacului" },
  { nume: "Doblea", comuna: "Albestii De Arges" },
  { nume: "Dobrești", simplu: "Dobresti" },
  { nume: "Dobrogostea", comuna: "Merisani" },
  { nume: "Dobrotu", comuna: "Albestii De Arges" },
  { nume: "Dogari", comuna: "Ciomagesti" },
  { nume: "Domnești", simplu: "Domnesti" },
  { nume: "Drăganu-Olteni", simplu: "Draganu-Olteni", comuna: "Draganu" },
  { nume: "Drăghescu", simplu: "Draghescu", comuna: "Vladesti" },
  { nume: "Drăghicești", simplu: "Draghicesti", comuna: "Sapata" },
  { nume: "Drăghici", simplu: "Draghici", comuna: "Mihaesti" },
  { nume: "Drăgolești", simplu: "Dragolesti", comuna: "Cotmeana" },
  { nume: "Dragoslavele" },
  { nume: "Dumbrava", comuna: "Bogati" },
  { nume: "Dumbrăvești", simplu: "Dumbravesti", comuna: "Draganu" },
  { nume: "Dumirești", simplu: "Dumiresti", comuna: "Albestii De Arges" },
  { nume: "Enculești", simplu: "Enculesti", comuna: "Stefanesti" },
  { nume: "Făcălețești", simplu: "Facaletesti", comuna: "Cocu" },
  { nume: "Făgetu", simplu: "Fagetu", comuna: "Mioveni" },
  { nume: "Fâlfani", simplu: "Falfani", comuna: "Stolnici" },
  { nume: "Fântânea", simplu: "Fantanea", comuna: "Valea Mare Pravat" },
  { nume: "Fata", comuna: "Vedea" },
  { nume: "Fedeleșoiu", simplu: "Fedelesoiu", comuna: "Ciomagesti" },
  { nume: "Florieni", comuna: "Albestii De Arges" },
  { nume: "Frătești", simplu: "Fratesti", comuna: "Albota" },
  { nume: "Frătici", simplu: "Fratici", comuna: "Vedea" },
  { nume: "Furduești", simplu: "Furduesti", comuna: "Ratesti" },
  { nume: "Furești", simplu: "Furesti", comuna: "Dobresti" },
  { nume: "Furnicoși", simplu: "Furnicosi", comuna: "Mihaesti" },
  { nume: "Găinușa", simplu: "Gainusa", comuna: "Sapata" },
  { nume: "Gălășești", simplu: "Galasesti", comuna: "Budeasa" },
  { nume: "Gâlcești", simplu: "Galcesti", comuna: "Poiana Lacului" },
  { nume: "Găleșești", simplu: "Galesesti", comuna: "Suseni" },
  { nume: "Galeșu", simplu: "Galesu", comuna: "Bradulet" },
  { nume: "Gălețeanu", simplu: "Galeteanu", comuna: "Poiana Lacului" },
  { nume: "Gămăcești", simplu: "Gamacesti", comuna: "Berevoesti" },
  { nume: "Gănești", simplu: "Ganesti", comuna: "Pietrosani" },
  { nume: "Gărdinești", simplu: "Gardinesti", comuna: "Poiana Lacului" },
  { nume: "Găujani", simplu: "Gaujani", comuna: "Ungheni" },
  { nume: "Geamăna", simplu: "Geamana", comuna: "Bradu" },
  { nume: "Giuclani", comuna: "Ciomagesti" },
  { nume: "Glâmbocata-Deal", simplu: "Glambocata-Deal", comuna: "Leordeni" },
  { nume: "Glâmbocata", simplu: "Glambocata", comuna: "Leordeni" },
  { nume: "Glâmbocel", simplu: "Glambocel", comuna: "Bogati" },
  { nume: "Glâmbocelu", simplu: "Glambocelu", comuna: "Bogati" },
  { nume: "Glâmbocu", simplu: "Glambocu", comuna: "Bascov" },
  { nume: "Glavacioc", comuna: "Stefan Cel Mare" },
  { nume: "Gliganu de Jos", comuna: "Rociu" },
  { nume: "Gliganu de Sus", comuna: "Rociu" },
  { nume: "Glodu", comuna: "Calinesti" },
  { nume: "Glodu", comuna: "Leordeni" },
  { nume: "Godeni" },
  { nume: "Goia", comuna: "Ungheni" },
  { nume: "Goleasca", comuna: "Recea" },
  { nume: "Golești", simplu: "Golesti", comuna: "Balilesti" },
  { nume: "Golești", simplu: "Golesti", comuna: "Stefanesti" },
  { nume: "Gorănești", simplu: "Goranesti", comuna: "Topoloveni" },
  { nume: "Gorani", comuna: "Uda" },
  { nume: "Gorganu", comuna: "Calinesti" },
  { nume: "Greabăn", simplu: "Greaban", comuna: "Uda" },
  { nume: "Greabănu", simplu: "Greabanu", comuna: "Cocu" },
  { nume: "Groșani", simplu: "Grosani", comuna: "Poienarii De Muscel" },
  { nume: "Groși", simplu: "Grosi", comuna: "Babana" },
  { nume: "Gruiu", comuna: "Cateasca" },
  { nume: "Gruiu", comuna: "Nucsoara" },
  { nume: "Gura Pravăț", simplu: "Gura Pravat", comuna: "Valea Mare Pravat" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Albota" },
  { nume: "Hârsești", simplu: "Harsesti" },
  { nume: "Hârtiești", simplu: "Hartiesti" },
  { nume: "Hințești", simplu: "Hintesti", comuna: "Mosoaia" },
  { nume: "Huluba", comuna: "Vulturesti" },
  { nume: "Humele", comuna: "Ungheni" },
  { nume: "Ianculești", simplu: "Ianculesti", comuna: "Suici" },
  { nume: "Ioanicești", simplu: "Ioanicesti", comuna: "Poienarii De Arges" },
  { nume: "Ionești", simplu: "Ionesti", comuna: "Buzoesti" },
  { nume: "Izbășești", simplu: "Izbasesti", comuna: "Stolnici" },
  { nume: "Izvorani", comuna: "Stefanesti" },
  { nume: "Izvoru de Jos", comuna: "Vedea" },
  { nume: "Izvoru de Sus", comuna: "Vedea" },
  { nume: "Izvoru" },
  { nume: "Jgheaburi", comuna: "Corbi" },
  { nume: "Jugur", comuna: "Poienarii De Muscel" },
  { nume: "Jupânești", simplu: "Jupanesti", comuna: "Cosesti" },
  { nume: "Lăceni", simplu: "Laceni", comuna: "Costesti" },
  { nume: "Lacurile", comuna: "Ciofrangeni" },
  { nume: "Lăicăi", simplu: "Laicai", comuna: "Cetateni" },
  { nume: "Lăngești", simplu: "Langesti", comuna: "Lunca Corbului" },
  { nume: "Lăpușani", simplu: "Lapusani", comuna: "Cosesti" },
  { nume: "Lăunele de Sus", simplu: "Launele de Sus", comuna: "Cuca" },
  { nume: "Lăzărești", simplu: "Lazaresti", comuna: "Mosoaia" },
  { nume: "Lăzărești", simplu: "Lazaresti", comuna: "Schitu Golesti" },
  { nume: "Leicești", simplu: "Leicesti", comuna: "Cosesti" },
  { nume: "Lențea", simplu: "Lentea", comuna: "Beleti-Negresti" },
  { nume: "Leordeni" },
  { nume: "Lerești", simplu: "Leresti" },
  { nume: "Leșile", simplu: "Lesile", comuna: "Teiu" },
  { nume: "Lespezi", comuna: "Hartiesti" },
  { nume: "Lintești", simplu: "Lintesti", comuna: "Cotmeana" },
  { nume: "Lipia", comuna: "Sapata" },
  { nume: "Livezeni", comuna: "Stalpeni" },
  { nume: "Loturi", comuna: "Schitu Golesti" },
  { nume: "Lucieni", comuna: "Hartiesti" },
  { nume: "Luminile", comuna: "Moraresti" },
  { nume: "Lunca Corbului" },
  { nume: "Lunca Gârtii", simplu: "Lunca Gartii", comuna: "Stoenesti" },
  { nume: "Lunca", comuna: "Boteni" },
  { nume: "Lungani", comuna: "Vedea" },
  { nume: "Lungulești", simplu: "Lungulesti", comuna: "Uda" },
  { nume: "Lupueni", comuna: "Babana" },
  { nume: "Măcăi", simplu: "Macai", comuna: "Cuca" },
  { nume: "Malu Vânăt", simplu: "Malu Vanat", comuna: "Merisani" },
  { nume: "Malu", comuna: "Barla" },
  { nume: "Malu", comuna: "Godeni" },
  { nume: "Mălureni", simplu: "Malureni" },
  { nume: "Măncioiu", simplu: "Mancioiu", comuna: "Moraresti" },
  { nume: "Mândra", simplu: "Mandra", comuna: "Barla" },
  { nume: "Mănești", simplu: "Manesti", comuna: "Cuca" },
  { nume: "Mănicești", simplu: "Manicesti", comuna: "Baiculesti" },
  { nume: "Mărăcineni", simplu: "Maracineni" },
  { nume: "Mareș", simplu: "Mares", comuna: "Albota" },
  {
    nume: "Mârghia de Jos",
    simplu: "Marghia de Jos",
    comuna: "Lunca Corbului",
  },
  {
    nume: "Mârghia de Sus",
    simplu: "Marghia de Sus",
    comuna: "Lunca Corbului",
  },
  { nume: "Martalogi", comuna: "Harsesti" },
  { nume: "Mârțești", simplu: "Martesti", comuna: "Sapata" },
  { nume: "Mățău", simplu: "Matau", comuna: "Mioarele" },
  { nume: "Mavrodolu", comuna: "Ratesti" },
  { nume: "Merișani", simplu: "Merisani" },
  { nume: "Metofu", comuna: "Poiana Lacului" },
  { nume: "Mica", comuna: "Bascov" },
  { nume: "Micești", simplu: "Micesti" },
  { nume: "Miercani", comuna: "Uda" },
  { nume: "Mihăești", simplu: "Mihaesti" },
  { nume: "Mioarele", comuna: "Cicanesti" },
  { nume: "Mioveni" },
  { nume: "Miroși", simplu: "Mirosi" },
  { nume: "Moara Mocanului", comuna: "Leordeni" },
  { nume: "Mogoșești", simplu: "Mogosesti", comuna: "Vedea" },
  { nume: "Morărești", simplu: "Moraresti" },
  { nume: "Morăști", simplu: "Morasti", comuna: "Cepari" },
  { nume: "Moșoaia", simplu: "Mosoaia" },
  { nume: "Moșteni-Greci", simplu: "Mosteni-Greci", comuna: "Botesti" },
  { nume: "Mozăceni", simplu: "Mozaceni" },
  { nume: "Mozăcenii-Vale", simplu: "Mozacenii-Vale", comuna: "Barla" },
  { nume: "Mozacu", comuna: "Negrasi" },
  { nume: "Musățești", simplu: "Musatesti" },
  { nume: "Mușcel", simplu: "Muscel", comuna: "Boteni" },
  { nume: "Mustățești", simplu: "Mustatesti", comuna: "Valea Iasului" },
  { nume: "Nămăești", simplu: "Namaesti", comuna: "Valea Mare Pravat" },
  { nume: "Negești", simplu: "Negesti", comuna: "Cotmeana" },
  { nume: "Negrași", simplu: "Negrasi" },
  { nume: "Negreni", comuna: "Darmanesti" },
  { nume: "Negrești", simplu: "Negresti", comuna: "Beleti-Negresti" },
  { nume: "Nejlovelu", comuna: "Ratesti" },
  { nume: "Nigrișoara", simplu: "Nigrisoara", comuna: "Slobozia" },
  { nume: "Noapteș", simplu: "Noaptes", comuna: "Curtea De Arges" },
  { nume: "Nucșoara", simplu: "Nucsoara" },
  { nume: "Oarja" },
  { nume: "Odăeni", simplu: "Odaeni", comuna: "Suseni" },
  { nume: "Oeștii Pamânteni", simplu: "Oestii Pamanteni", comuna: "Corbeni" },
  { nume: "Oeștii Ungureni", simplu: "Oestii Ungureni", comuna: "Corbeni" },
  { nume: "Ogrezea", comuna: "Stalpeni" },
  { nume: "Oprești", simplu: "Opresti", comuna: "Stalpeni" },
  { nume: "Orodel", comuna: "Recea" },
  { nume: "Oțelu", simplu: "Otelu", comuna: "Berevoesti" },
  { nume: "Păcioiu", simplu: "Pacioiu", comuna: "Cosesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Suseni" },
  { nume: "Pădureți", simplu: "Padureti", comuna: "Lunca Corbului" },
  {
    nume: "Păduroiu din Deal",
    simplu: "Paduroiu din Deal",
    comuna: "Poiana Lacului",
  },
  {
    nume: "Păduroiu din Vale",
    simplu: "Paduroiu din Vale",
    comuna: "Poiana Lacului",
  },
  { nume: "Palanga", comuna: "Popesti" },
  { nume: "Paltenu", comuna: "Suici" },
  { nume: "Paraschivești", simplu: "Paraschivesti", comuna: "Priboieni" },
  { nume: "Pârvu Roșu", simplu: "Parvu Rosu", comuna: "Costesti" },
  { nume: "Pătuleni", simplu: "Patuleni", comuna: "Ratesti" },
  { nume: "Păuleasca", simplu: "Pauleasca", comuna: "Malureni" },
  { nume: "Păuleasca", simplu: "Pauleasca", comuna: "Micesti" },
  { nume: "Păuleni", simplu: "Pauleni", comuna: "Suici" },
  { nume: "Păunești", simplu: "Paunesti", comuna: "Ciomagesti" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Cosesti" },
  { nume: "Piatra", comuna: "Bradulet" },
  { nume: "Piatra", comuna: "Ciofrangeni" },
  { nume: "Piatra", comuna: "Stoenesti" },
  { nume: "Pielești", simplu: "Pielesti", comuna: "Cotmeana" },
  { nume: "Pietroasa", comuna: "Valea Mare Pravat" },
  { nume: "Pietroșani", simplu: "Pietrosani" },
  { nume: "Piscani", comuna: "Darmanesti" },
  { nume: "Pitești", simplu: "Pitesti" },
  { nume: "Pițigaia", simplu: "Pitigaia", comuna: "Stalpeni" },
  { nume: "Pitoi", comuna: "Priboieni" },
  { nume: "Podeni", comuna: "Buzoesti" },
  { nume: "Podișoru", simplu: "Podisoru", comuna: "Barla" },
  { nume: "Podu Broșteni", simplu: "Podu Brosteni", comuna: "Costesti" },
  {
    nume: "Podu Dâmboviței",
    simplu: "Podu Dambovitei",
    comuna: "Dambovicioara",
  },
  { nume: "Poduri", comuna: "Corbi" },
  { nume: "Poiana Lacului" },
  { nume: "Poienărei", simplu: "Poienarei", comuna: "Corbi" },
  { nume: "Poienari", comuna: "Corbeni" },
  { nume: "Poienari", comuna: "Poienarii De Arges" },
  { nume: "Poienari", comuna: "Poienarii De Muscel" },
  { nume: "Poienița", simplu: "Poienita", comuna: "Balilesti" },
  { nume: "Pojorâta", simplu: "Pojorata", comuna: "Leresti" },
  { nume: "Popești", simplu: "Popesti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Cocu" },
  { nume: "Popești", simplu: "Popesti", comuna: "Sapata" },
  { nume: "Priboaia", comuna: "Balilesti" },
  { nume: "Priboieni" },
  { nume: "Priseaca", comuna: "Cosesti" },
  { nume: "Prislopu Mare", comuna: "Draganu" },
  { nume: "Prislopu Mic", comuna: "Bascov" },
  { nume: "Prodani", comuna: "Vedea" },
  { nume: "Prosia", comuna: "Musatesti" },
  { nume: "Purcăreni", simplu: "Purcareni", comuna: "Micesti" },
  { nume: "Purcăreni", simplu: "Purcareni", comuna: "Popesti" },
  { nume: "Putina", comuna: "Vladesti" },
  { nume: "Râca", simplu: "Raca" },
  { nume: "Răchițele de Jos", simplu: "Rachitele de Jos", comuna: "Cocu" },
  { nume: "Răchițele de Sus", simplu: "Rachitele de Sus", comuna: "Cocu" },
  { nume: "Racovița", simplu: "Racovita", comuna: "Mioveni" },
  { nume: "Rădești", simplu: "Radesti", comuna: "Stalpeni" },
  { nume: "Radu Negru", comuna: "Calinesti" },
  { nume: "Răduțești", simplu: "Radutesti", comuna: "Ciomagesti" },
  { nume: "Râjlețu-Govora", simplu: "Rajletu-Govora", comuna: "Uda" },
  { nume: "Râncăciov", simplu: "Rancaciov", comuna: "Calinesti" },
  { nume: "Rătești", simplu: "Ratesti" },
  { nume: "Rățoi", simplu: "Ratoi", comuna: "Vedea" },
  { nume: "Recea" },
  { nume: "Recea", comuna: "Cateasca" },
  { nume: "Redea", comuna: "Buzoesti" },
  { nume: "Retevoiești", simplu: "Retevoiesti", comuna: "Pietrosani" },
  { nume: "Robaia", comuna: "Musatesti" },
  { nume: "Rociu" },
  { nume: "Rogojina", comuna: "Budeasa" },
  { nume: "Romana", comuna: "Uda" },
  { nume: "Rotunda", comuna: "Corbeni" },
  { nume: "Rucăr", simplu: "Rucar" },
  { nume: "Rudeni", comuna: "Mihaesti" },
  { nume: "Rudeni", comuna: "Suici" },
  { nume: "Ruginoasa", comuna: "Valea Iasului" },
  { nume: "Sălătrucu", simplu: "Salatrucu" },
  { nume: "Săliștea", simplu: "Salistea", comuna: "Uda" },
  { nume: "Sămăila", simplu: "Samaila", comuna: "Priboieni" },
  { nume: "Sămara", simplu: "Samara", comuna: "Poiana Lacului" },
  { nume: "Săndulești", simplu: "Sandulesti", comuna: "Cotmeana" },
  { nume: "Săpunari", simplu: "Sapunari", comuna: "Moraresti" },
  { nume: "Sătic", simplu: "Satic", comuna: "Rucar" },
  { nume: "Satu Nou", comuna: "Ungheni" },
  { nume: "Sboghițești", simplu: "Sboghitesti", comuna: "Nucsoara" },
  { nume: "Scheau", comuna: "Bascov" },
  { nume: "Schitu Golești", simplu: "Schitu Golesti" },
  { nume: "Schitu Scoicești", simplu: "Schitu Scoicesti", comuna: "Leordeni" },
  { nume: "Schitu-Matei", comuna: "Ciofrangeni" },
  { nume: "Șelăreasca", simplu: "Selareasca", comuna: "Barla" },
  { nume: "Șelari", simplu: "Selari", comuna: "Valea Mare Pravat" },
  { nume: "Șendrulești", simplu: "Sendrulesti", comuna: "Cepari" },
  { nume: "Șerbănești", simplu: "Serbanesti", comuna: "Poienarii De Muscel" },
  { nume: "Șerbănești", simplu: "Serbanesti", comuna: "Rociu" },
  { nume: "Șerboeni", simplu: "Serboeni", comuna: "Buzoesti" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Cateasca" },
  { nume: "Silișteni", simplu: "Silisteni", comuna: "Lunca Corbului" },
  { nume: "Sinești", simplu: "Sinesti", comuna: "Cuca" },
  { nume: "Slăatioarele", simplu: "Slaatioarele", comuna: "Babana" },
  { nume: "Slămnești", simplu: "Slamnesti", comuna: "Bradulet" },
  { nume: "Slănic", simplu: "Slanic", comuna: "Aninoasa" },
  { nume: "Slatina", comuna: "Nucsoara" },
  { nume: "Slobozia" },
  { nume: "Slobozia", comuna: "Popesti" },
  { nume: "Slobozia", comuna: "Stoenesti" },
  { nume: "Smei", comuna: "Costesti" },
  { nume: "Smeura", comuna: "Mosoaia" },
  { nume: "Spiridoni", comuna: "Cotmeana" },
  { nume: "Stâlpeni", simplu: "Stalpeni" },
  { nume: "Stănești", simplu: "Stanesti", comuna: "Corbi" },
  { nume: "Stănicei", simplu: "Stanicei", comuna: "Cuca" },
  { nume: "Stârci", simplu: "Starci", comuna: "Costesti" },
  { nume: "Ștefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Ștefănești", simplu: "Stefanesti" },
  { nume: "Stefănești", simplu: "Stefanesti", comuna: "Suseni" },
  { nume: "Ștefăneștii Noi", simplu: "Stefanestii Noi", comuna: "Stefanesti" },
  { nume: "Stejari", comuna: "Baiculesti" },
  { nume: "Stoenești", simplu: "Stoenesti" },
  { nume: "Stolnici" },
  { nume: "Strâmbeni", simplu: "Strambeni", comuna: "Caldararu" },
  { nume: "Strâmbeni", simplu: "Strambeni", comuna: "Suseni" },
  { nume: "Stroești", simplu: "Stroesti", comuna: "Musatesti" },
  { nume: "Șuici", simplu: "Suici" },
  { nume: "Surdulești", simplu: "Surdulesti", comuna: "Mirosi" },
  { nume: "Suseni" },
  { nume: "Suseni", comuna: "Bogati" },
  { nume: "Suslănești", simplu: "Suslanesti", comuna: "Mioarele" },
  { nume: "Teiu" },
  { nume: "Teodorești", simplu: "Teodoresti", comuna: "Cuca" },
  { nume: "Țigănești", simplu: "Tiganesti", comuna: "Topoloveni" },
  { nume: "Tigveni" },
  { nume: "Tigveni", comuna: "Ratesti" },
  { nume: "Țițești", simplu: "Titesti" },
  { nume: "Tomșanca", simplu: "Tomsanca", comuna: "Buzoesti" },
  { nume: "Tomulești", simplu: "Tomulesti", comuna: "Poienarii De Arges" },
  { nume: "Toplița", simplu: "Toplita", comuna: "Malureni" },
  { nume: "Topoloveni" },
  { nume: "Turburea", comuna: "Corbeni" },
  { nume: "Turcești", simplu: "Turcesti", comuna: "Sapata" },
  { nume: "Tutana", comuna: "Baiculesti" },
  { nume: "Țuțulești", simplu: "Tutulesti", comuna: "Suseni" },
  { nume: "Uda" },
  { nume: "Udeni-Zăvoi", simplu: "Udeni-Zavoi", comuna: "Calinesti" },
  { nume: "Uiasca", comuna: "Bascov" },
  { nume: "Uleni", comuna: "Bradulet" },
  { nume: "Ulița", simplu: "Ulita", comuna: "Balilesti" },
  { nume: "Ungheni" },
  { nume: "Ungureni", comuna: "Bradulet" },
  { nume: "Ungureni", comuna: "Valea Iasului" },
  { nume: "Urechești", simplu: "Urechesti", comuna: "Cicanesti" },
  { nume: "Urlucea", comuna: "Calinesti" },
  { nume: "Urlueni", comuna: "Barla" },
  { nume: "Urluiești", simplu: "Urluiesti", comuna: "Cepari" },
  { nume: "Ursoaia", comuna: "Cotmeana" },
  { nume: "Văcarea", simplu: "Vacarea", comuna: "Mihaesti" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Merisani" },
  { nume: "Valea Bădenilor", simplu: "Valea Badenilor", comuna: "Stoenesti" },
  { nume: "Valea Bradului", comuna: "Mihaesti" },
  { nume: "Valea Brazilor", comuna: "Baiculesti" },
  { nume: "Valea Calului", comuna: "Suici" },
  { nume: "Valea Cetățuia", simplu: "Valea Cetatuia", comuna: "Cetateni" },
  { nume: "Valea Corbului", comuna: "Calinesti" },
  { nume: "Valea Cucii", comuna: "Cuca" },
  { nume: "Valea Danului" },
  { nume: "Valea Faurului", comuna: "Musatesti" },
  { nume: "Valea Hotarului", comuna: "Dragoslavele" },
  { nume: "Valea Iașului", simplu: "Valea Iasului" },
  {
    nume: "Valea Îndărăt",
    simplu: "Valea Indarat",
    comuna: "Poienarii De Muscel",
  },
  { nume: "Valea lui Enache", comuna: "Baiculesti" },
  { nume: "Valea lui Maș", simplu: "Valea lui Mas", comuna: "Musatesti" },
  { nume: "Valea Măgurei", simplu: "Valea Magurei", comuna: "Cepari" },
  { nume: "Valea Mănăstirii", simplu: "Valea Manastirii", comuna: "Titesti" },
  { nume: "Valea Mare Pravăț", simplu: "Valea Mare Pravat" },
  { nume: "Valea Mare-Bratia", comuna: "Balilesti" },
  { nume: "Valea Mare-Podgoria", comuna: "Stefanesti" },
  { nume: "Valea Mare", comuna: "Priboieni" },
  { nume: "Valea Mărului", simplu: "Valea Marului", comuna: "Budeasa" },
  { nume: "Valea Muscelului", comuna: "Musatesti" },
  { nume: "Valea Nandrii", comuna: "Darmanesti" },
  { nume: "Valea Nenii", comuna: "Priboieni" },
  { nume: "Valea Pechii", comuna: "Schitu Golesti" },
  { nume: "Valea Popii", comuna: "Mihaesti" },
  { nume: "Valea Popii", comuna: "Priboieni" },
  { nume: "Valea Rizii", comuna: "Darmanesti" },
  {
    nume: "Valea Rumâneștilor",
    simplu: "Valea Rumanestilor",
    comuna: "Campulung",
  },
  { nume: "Valea Siliștii", simplu: "Valea Silistii", comuna: "Aninoasa" },
  { nume: "Valea Stânii", simplu: "Valea Stanii", comuna: "Titesti" },
  { nume: "Valea Uleiului", comuna: "Valea Iasului" },
  { nume: "Valea Ursului", comuna: "Bascov" },
  { nume: "Văleni-Podgoria", simplu: "Valeni-Podgoria", comuna: "Calinesti" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Salatrucu" },
  { nume: "Vâlsănești", simplu: "Valsanesti", comuna: "Musatesti" },
  { nume: "Vârloveni", simplu: "Varloveni", comuna: "Cotmeana" },
  { nume: "Vârșești", simplu: "Varsesti", comuna: "Vedea" },
  { nume: "Vărzăroaia", simplu: "Varzaroaia", comuna: "Pietrosani" },
  { nume: "Vărzaru", simplu: "Varzaru", comuna: "Merisani" },
  { nume: "Vața", simplu: "Vata", comuna: "Vedea" },
  { nume: "Vedea" },
  { nume: "Vernești", simplu: "Vernesti", comuna: "Valea Danului" },
  { nume: "Vețișoara", simplu: "Vetisoara", comuna: "Vedea" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Stefanesti" },
  { nume: "Vlădești", simplu: "Vladesti" },
  { nume: "Vlădești", simplu: "Vladesti", comuna: "Tigveni" },
  { nume: "Vlăduța", simplu: "Vladuta", comuna: "Buzoesti" },
  { nume: "Vlășcuța", simplu: "Vlascuta", comuna: "Stolnici" },
  { nume: "Voinești", simplu: "Voinesti", comuna: "Leresti" },
  { nume: "Vonigeasa", comuna: "Cuca" },
  { nume: "Voroveni", comuna: "Davidesti" },
  { nume: "Vrănești", simplu: "Vranesti", comuna: "Calinesti" },
  { nume: "Vulpești", simplu: "Vulpesti", comuna: "Buzoesti" },
  { nume: "Vulturești", simplu: "Vulturesti" },
  { nume: "Zamfirești", simplu: "Zamfiresti", comuna: "Cepari" },
  { nume: "Zamfirești", simplu: "Zamfiresti", comuna: "Cotmeana" },
  { nume: "Zărnești", simplu: "Zarnesti", comuna: "Malureni" },
  { nume: "Zăvoi", simplu: "Zavoi", comuna: "Stefanesti" },
  { nume: "Zgripcești", simplu: "Zgripcesti", comuna: "Beleti-Negresti" },
  { nume: "Zidurile", comuna: "Mozaceni" },
  { nume: "Zigoneni", comuna: "Baiculesti" },
  { nume: "Zuvelcați", simplu: "Zuvelcati", comuna: "Barla" },
];
