export const ab = [
  { nume: "Abrud-Sat", comuna: "Abrud" },
  { nume: "Abrud" },
  { nume: "Achimeţeşti", simplu: "Achimetesti", comuna: "Avram Iancu" },
  { nume: "Acmariu", comuna: "Blandiana" },
  { nume: "Aiud" },
  { nume: "Aiudul de Sus", comuna: "Aiud" },
  { nume: "Alba Iulia" },
  { nume: "Albac" },
  { nume: "Alecuş", simplu: "Alecus", comuna: "Sona" },
  {
    nume: "Almaşu de Mijloc",
    simplu: "Almasu de Mijloc",
    comuna: "Almasu Mare",
  },
  { nume: "Almaşu Mare", simplu: "Almasu Mare" },
  { nume: "Ampoiţa", simplu: "Ampoita", comuna: "Metes" },
  { nume: "Angheleşti", simplu: "Anghelesti", comuna: "Bucium" },
  { nume: "Arieşeni", simplu: "Arieseni" },
  { nume: "Aroneşti", simplu: "Aronesti", comuna: "Bistra" },
  { nume: "Arţi", simplu: "Arti", comuna: "Sugag" },
  { nume: "Asinip", comuna: "Lopadea Noua" },
  { nume: "Avram Iancu" },
  { nume: "Avrămeşti", simplu: "Avramesti", comuna: "Arieseni" },
  { nume: "Avrămeşti", simplu: "Avramesti", comuna: "Avram Iancu" },
  { nume: "Baba", comuna: "Horea" },
  { nume: "Băcăinţi", simplu: "Bacainti", comuna: "Sibot" },
  { nume: "Bădăi", simplu: "Badai", comuna: "Avram Iancu" },
  { nume: "Băgău", simplu: "Bagau", comuna: "Lopadea Noua" },
  { nume: "Băi", simplu: "Bai", comuna: "Vidra" },
  { nume: "Baia de Arieş", simplu: "Baia de Aries" },
  { nume: "Bălcaciu", simplu: "Balcaciu", comuna: "Jidvei" },
  { nume: "Băleşti-Cătun", simplu: "Balesti-Catun", comuna: "Bistra" },
  { nume: "Băleşti", simplu: "Balesti", comuna: "Bistra" },
  { nume: "Bălmoşeşti", simplu: "Balmosesti", comuna: "Rosia Montana" },
  { nume: "Balomiru de Câmp", simplu: "Balomiru de Camp", comuna: "Sibot" },
  { nume: "Bărăbanţ", simplu: "Barabant", comuna: "Alba Iulia" },
  { nume: "Bărăşti", simplu: "Barasti", comuna: "Albac" },
  { nume: "Bărbeşti", simplu: "Barbesti", comuna: "Mogos" },
  { nume: "Bârdeşti", simplu: "Bardesti", comuna: "Lupsa" },
  { nume: "Bârleşti-Cătun", simplu: "Barlesti-Catun", comuna: "Mogos" },
  { nume: "Bârleşti", simplu: "Barlesti", comuna: "Bistra" },
  { nume: "Bârleşti", simplu: "Barlesti", comuna: "Mogos" },
  { nume: "Bârleşti", simplu: "Barlesti", comuna: "Scarisoara" },
  { nume: "Bârsana", simplu: "Barsana", comuna: "Sugag" },
  { nume: "Bârzan", simplu: "Barzan", comuna: "Lupsa" },
  { nume: "Bârzogani", simplu: "Barzogani", comuna: "Mogos" },
  { nume: "Băzeşti", simplu: "Bazesti", comuna: "Sohodol" },
  { nume: "Beldiu", comuna: "Teius" },
  { nume: "Benic", comuna: "Galda De Jos" },
  { nume: "Berghin" },
  { nume: "Beţa", simplu: "Beta", comuna: "Lopadea Noua" },
  { nume: "Bidigeşti", simplu: "Bidigesti", comuna: "Ciuruleasa" },
  { nume: "Biharia", comuna: "Garda De Sus" },
  { nume: "Biia", comuna: "Sona" },
  { nume: "Bilăneşti", simplu: "Bilanesti", comuna: "Sohodol" },
  { nume: "Bisericani", comuna: "Bucium" },
  { nume: "Bistra" },
  { nume: "Blaj" },
  { nume: "Blandiana" },
  { nume: "Blideşti", simplu: "Blidesti", comuna: "Rosia Montana" },
  { nume: "Bobăreşti", simplu: "Bobaresti", comuna: "Sohodol" },
  { nume: "Bobăreşti", simplu: "Bobaresti", comuna: "Vidra" },
  { nume: "Boceşti", simplu: "Bocesti", comuna: "Mogos" },
  { nume: "Bocşitura", simplu: "Bocsitura", comuna: "Cugir" },
  { nume: "Bodeşti", simplu: "Bodesti", comuna: "Vadu Motilor" },
  { nume: "Bodreşti", simplu: "Bodresti", comuna: "Ciuruleasa" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Mogos" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Vidra" },
  { nume: "Bogleşti", simplu: "Boglesti", comuna: "Ciuruleasa" },
  { nume: "Boldeşti", simplu: "Boldesti", comuna: "Avram Iancu" },
  { nume: "Bolovăneşti", simplu: "Bolovanesti", comuna: "Ceru-Bacainti" },
  { nume: "Bonceşti", simplu: "Boncesti", comuna: "Campeni" },
  { nume: "Bordeştii Poieni", simplu: "Bordestii Poieni", comuna: "Vidra" },
  { nume: "Borleşti", simplu: "Borlesti", comuna: "Campeni" },
  { nume: "Boţani", simplu: "Botani", comuna: "Ramet" },
  { nume: "Boteşti", simplu: "Botesti", comuna: "Campeni" },
  { nume: "Boteşti", simplu: "Botesti", comuna: "Scarisoara" },
  { nume: "Boteşti", simplu: "Botesti", comuna: "Zlatna" },
  { nume: "Boz", comuna: "Dostat" },
  { nume: "Brădeana", simplu: "Bradeana", comuna: "Sohodol" },
  { nume: "Brădeşti", simplu: "Bradesti", comuna: "Ramet" },
  { nume: "Brădet", simplu: "Bradet", comuna: "Almasu Mare" },
  { nume: "Brăzeşti", simplu: "Brazesti", comuna: "Baia De Aries" },
  { nume: "Bubeşti", simplu: "Bubesti", comuna: "Arieseni" },
  {
    nume: "Bucerdea Grânoasă",
    simplu: "Bucerdea Granoasa",
    comuna: "Craciunelu De Jos",
  },
  { nume: "Bucerdea Vânoasă", simplu: "Bucerdea Vanoasa", comuna: "Ighiu" },
  { nume: "Bucium-Sat", comuna: "Bucium" },
  { nume: "Bucium" },
  { nume: "Bucuru", comuna: "Cugir" },
  { nume: "Budăieşti", simplu: "Budaiesti", comuna: "Albac" },
  { nume: "Budeni", comuna: "Zlatna" },
  { nume: "Bulbuc", comuna: "Ceru-Bacainti" },
  { nume: "Buninginea", comuna: "Ciuruleasa" },
  { nume: "Bunta", comuna: "Rosia Montana" },
  { nume: "Burzeşti", simplu: "Burzesti", comuna: "Vadu Motilor" },
  { nume: "Burzoneşti", simplu: "Burzonesti", comuna: "Sohodol" },
  { nume: "Buteşti", simplu: "Butesti", comuna: "Horea" },
  { nume: "Buteşti", simplu: "Butesti", comuna: "Mogos" },
  { nume: "Călene", simplu: "Calene", comuna: "Cugir" },
  { nume: "Câlnic", simplu: "Calnic" },
  { nume: "Călugăreşti", simplu: "Calugaresti", comuna: "Avram Iancu" },
  { nume: "Câmpeni", simplu: "Campeni" },
  { nume: "Câmpu Goblii", simplu: "Campu Goblii", comuna: "Vintu De Jos" },
  { nume: "Cândeşti", simplu: "Candesti", comuna: "Avram Iancu" },
  { nume: "Căpâlna de Jos", simplu: "Capalna de Jos", comuna: "Jidvei" },
  { nume: "Căpâlna", simplu: "Capalna", comuna: "Sasciori" },
  { nume: "Căptălan", simplu: "Captalan", comuna: "Noslac" },
  { nume: "Capu Dealului", comuna: "Cenade" },
  { nume: "Căpud", simplu: "Capud", comuna: "Teius" },
  { nume: "Cârăşti", simplu: "Carasti", comuna: "Avram Iancu" },
  { nume: "Carpen", comuna: "Spring" },
  { nume: "Carpenii de Sus", comuna: "Spring" },
  { nume: "Cărpiniş", simplu: "Carpinis", comuna: "Garbova" },
  { nume: "Cărpiniş", simplu: "Carpinis", comuna: "Rosia Montana" },
  { nume: "Cârţuleşti", simplu: "Cartulesti", comuna: "Avram Iancu" },
  { nume: "Casa de Piatră", simplu: "Casa de Piatra", comuna: "Arieseni" },
  { nume: "Căsoaia", simplu: "Casoaia", comuna: "Avram Iancu" },
  { nume: "Cenade" },
  { nume: "Cerbu", comuna: "Bucium" },
  { nume: "Cergău Mare", simplu: "Cergau Mare", comuna: "Cergau" },
  { nume: "Cergău Mic", simplu: "Cergau Mic", comuna: "Cergau" },
  { nume: "Certege", comuna: "Campeni" },
  { nume: "Ceru-Băcăinţi", simplu: "Ceru-Bacainti" },
  { nume: "Cetatea de Baltă", simplu: "Cetatea de Balta" },
  { nume: "Cetea", comuna: "Galda De Jos" },
  { nume: "Cheia", comuna: "Ramet" },
  { nume: "Cheile Cibului", comuna: "Almasu Mare" },
  { nume: "Cheleteni", comuna: "Bistra" },
  { nume: "Cib", comuna: "Almasu Mare" },
  { nume: "Cicârd", simplu: "Cicard", comuna: "Lopadea Noua" },
  { nume: "Cicău", simplu: "Cicau", comuna: "Miraslau" },
  { nume: "Cioara de Sus", comuna: "Baia De Aries" },
  { nume: "Ciocaşu", simplu: "Ciocasu", comuna: "Vintu De Jos" },
  { nume: "Cioneşti", simplu: "Cionesti", comuna: "Albac" },
  { nume: "Cistei", comuna: "Mihalt" },
  {
    nume: "Cisteiu de Mureş",
    simplu: "Cisteiu de Mures",
    comuna: "Ocna Mures",
  },
  { nume: "Ciuculeşti", simplu: "Ciuculesti", comuna: "Bucium" },
  { nume: "Ciugud" },
  { nume: "Ciugudu de Jos", comuna: "Unirea" },
  { nume: "Ciugudu de Sus", comuna: "Unirea" },
  { nume: "Ciuguzel", comuna: "Lopadea Noua" },
  { nume: "Ciuldeşti", simplu: "Ciuldesti", comuna: "Bistra" },
  { nume: "Ciumbrud", comuna: "Aiud" },
  { nume: "Ciuruleasa" },
  { nume: "Coasta Henţii", simplu: "Coasta Hentii", comuna: "Rosia Montana" },
  { nume: "Coasta Vâscului", simplu: "Coasta Vascului", comuna: "Campeni" },
  { nume: "Cobleş", simplu: "Cobles", comuna: "Arieseni" },
  { nume: "Coceşti", simplu: "Cocesti", comuna: "Avram Iancu" },
  { nume: "Cocoşeşti", simplu: "Cocosesti", comuna: "Avram Iancu" },
  { nume: "Cojocani", comuna: "Mogos" },
  { nume: "Coleşeni", simplu: "Coleseni", comuna: "Bucium" },
  { nume: "Colibi", comuna: "Ohaba" },
  { nume: "Colţeşti", simplu: "Coltesti", comuna: "Rametea" },
  { nume: "Copand", comuna: "Noslac" },
  { nume: "Corna", comuna: "Rosia Montana" },
  { nume: "Cornu", comuna: "Craciunelu De Jos" },
  { nume: "Coroieşti", simplu: "Coroiesti", comuna: "Avram Iancu" },
  { nume: "Corţeşti", simplu: "Cortesti", comuna: "Posaga" },
  { nume: "Coşlariu Nou", simplu: "Coslariu Nou", comuna: "Teius" },
  { nume: "Coşlariu", simplu: "Coslariu", comuna: "Santimbru" },
  { nume: "Costeşti", simplu: "Costesti", comuna: "Albac" },
  { nume: "Costeşti", simplu: "Costesti", comuna: "Poiana Vadului" },
  { nume: "Cotorăşti", simplu: "Cotorasti", comuna: "Ramet" },
  { nume: "Crăciunelu de Jos", simplu: "Craciunelu de Jos" },
  { nume: "Craciunelu de Sus", comuna: "Cetatea De Balta" },
  { nume: "Craiva", comuna: "Cricau" },
  { nume: "Creţeşti", simplu: "Cretesti", comuna: "Bistra" },
  { nume: "Cricău", simplu: "Cricau" },
  { nume: "Crişeni", simplu: "Criseni", comuna: "Vintu De Jos" },
  { nume: "Cristeşti", simplu: "Cristesti", comuna: "Mogos" },
  { nume: "Cucuta", comuna: "Ceru-Bacainti" },
  { nume: "Cugir" },
  { nume: "Culdeşti", simplu: "Culdesti", comuna: "Vidra" },
  { nume: "Cunţa", simplu: "Cunta", comuna: "Spring" },
  { nume: "Curături", simplu: "Curaturi", comuna: "Rosia Montana" },
  { nume: "Curmătură", simplu: "Curmatura", comuna: "Lupsa" },
  { nume: "Curpeni", comuna: "Ceru-Bacainti" },
  { nume: "Cut", comuna: "Calnic" },
  { nume: "Daia Română", simplu: "Daia Romana" },
  { nume: "Dâmbureni", simplu: "Dambureni", comuna: "Bistra" },
  { nume: "Dănduţ", simplu: "Dandut", comuna: "Campeni" },
  { nume: "Dârleşti", simplu: "Darlesti", comuna: "Horea" },
  { nume: "Dăroaia", simplu: "Daroaia", comuna: "Rosia Montana" },
  { nume: "Deal", comuna: "Calnic" },
  { nume: "Dealu Bajului", comuna: "Arieseni" },
  { nume: "Dealu Bistrii", comuna: "Campeni" },
  { nume: "Dealu Capsei", comuna: "Campeni" },
  { nume: "Dealu Caselor", comuna: "Salciua" },
  { nume: "Dealu Crişului", simplu: "Dealu Crisului", comuna: "Avram Iancu" },
  { nume: "Dealu Doştatului", simplu: "Dealu Dostatului", comuna: "Dostat" },
  { nume: "Dealu Ferului", comuna: "Vintu De Jos" },
  { nume: "Dealu Frumos", comuna: "Garda De Sus" },
  { nume: "Dealu Frumos", comuna: "Vadu Motilor" },
  { nume: "Dealu Geoagiului", comuna: "Intregalde" },
  { nume: "Dealu Goieşti", simplu: "Dealu Goiesti", comuna: "Vidra" },
  { nume: "Dealu Lămăşoi", simplu: "Dealu Lamasoi", comuna: "Albac" },
  { nume: "Dealu Muntelui", comuna: "Bistra" },
  {
    nume: "Dealu Ordâncuşii",
    simplu: "Dealu Ordancusii",
    comuna: "Garda De Sus",
  },
  { nume: "Dealu Roatei", comuna: "Zlatna" },
  { nume: "Decea", comuna: "Miraslau" },
  { nume: "Deleni-Obârşie", simplu: "Deleni-Obarsie", comuna: "Blaj" },
  { nume: "Deonceşti", simplu: "Deoncesti", comuna: "Sohodol" },
  { nume: "Deve", comuna: "Albac" },
  { nume: "Dilimani", comuna: "Sohodol" },
  { nume: "Dobra", comuna: "Sugag" },
  { nume: "Dobreşti", simplu: "Dobresti", comuna: "Garda De Sus" },
  { nume: "Dobrot", comuna: "Zlatna" },
  { nume: "Dogăreşti", simplu: "Dogaresti", comuna: "Bucium" },
  { nume: "Doleşti", simplu: "Dolesti", comuna: "Avram Iancu" },
  { nume: "Doptău", simplu: "Doptau", comuna: "Sona" },
  { nume: "Dos", comuna: "Vidra" },
  { nume: "Doştat", simplu: "Dostat" },
  { nume: "Dosu Luncii", comuna: "Vidra" },
  { nume: "Dosu Văseşti", simplu: "Dosu Vasesti", comuna: "Vidra" },
  { nume: "Drăgoieşti-Luncă", simplu: "Dragoiesti-Lunca", comuna: "Vidra" },
  { nume: "Drâmbar", simplu: "Drambar", comuna: "Ciugud" },
  { nume: "Draşov", simplu: "Drasov", comuna: "Spring" },
  { nume: "Dric", comuna: "Campeni" },
  { nume: "Duduieni", comuna: "Poiana Vadului" },
  { nume: "Dumăceşti", simplu: "Dumacesti", comuna: "Avram Iancu" },
  { nume: "Dumbrava", comuna: "Sasciori" },
  { nume: "Dumbrava", comuna: "Unirea" },
  { nume: "Dumbrava", comuna: "Zlatna" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita", comuna: "Ceru-Bacainti" },
  { nume: "Dumeşti", simplu: "Dumesti", comuna: "Salciua" },
  { nume: "Dumitra", comuna: "Santimbru" },
  { nume: "Dupa Deal", comuna: "Ponor" },
  { nume: "După Deal", simplu: "Dupa Deal", comuna: "Lupsa" },
  { nume: "După Pleşe", simplu: "Dupa Plese", comuna: "Albac" },
  { nume: "Durăşti", simplu: "Durasti", comuna: "Bistra" },
  { nume: "Făget", simplu: "Faget", comuna: "Valea Lunga" },
  { nume: "Făgetu de Jos", simplu: "Fagetu de Jos", comuna: "Poiana Vadului" },
  { nume: "Făgetu de Sus", simplu: "Fagetu de Sus", comuna: "Poiana Vadului" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Ceru-Bacainti" },
  { nume: "Fărău", simplu: "Farau" },
  { nume: "Faţa Abrudului", simplu: "Fata Abrudului", comuna: "Campeni" },
  { nume: "Faţa Cristesei", simplu: "Fata Cristesei", comuna: "Arieseni" },
  { nume: "Faţa Lăpuşului", simplu: "Fata Lapusului", comuna: "Arieseni" },
  { nume: "Faţa Pietrii", simplu: "Fata Pietrii", comuna: "Stremt" },
  { nume: "Faţa-Lăzeşti", simplu: "Fata-Lazesti", comuna: "Scarisoara" },
  { nume: "Faţa", simplu: "Fata", comuna: "Albac" },
  { nume: "Feisa", comuna: "Jidvei" },
  { nume: "Feneş", simplu: "Fenes", comuna: "Zlatna" },
  { nume: "Fereşti", simplu: "Feresti", comuna: "Bucium" },
  { nume: "Fericet", comuna: "Horea" },
  { nume: "Feţeni", simplu: "Feteni", comuna: "Cugir" },
  { nume: "Ficăreşti", simplu: "Ficaresti", comuna: "Vidra" },
  { nume: "Fliteşti", simplu: "Flitesti", comuna: "Blaj" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Bucium" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Campeni" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Ramet" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Scarisoara" },
  { nume: "Furduieşti", simplu: "Furduiesti", comuna: "Campeni" },
  { nume: "Furduieşti", simplu: "Furduiesti", comuna: "Sohodol" },
  { nume: "Găbud", simplu: "Gabud", comuna: "Noslac" },
  { nume: "Galaţi", simplu: "Galati", comuna: "Zlatna" },
  { nume: "Galbena", comuna: "Arieseni" },
  { nume: "Galda de Jos" },
  { nume: "Galda de Sus", comuna: "Galda De Jos" },
  { nume: "Galtiu", comuna: "Santimbru" },
  { nume: "Gâmbaş", simplu: "Gambas", comuna: "Aiud" },
  { nume: "Găneşti", simplu: "Ganesti", comuna: "Bistra" },
  { nume: "Gârbova de Jos", simplu: "Garbova de Jos", comuna: "Aiud" },
  { nume: "Gârbova de Sus", simplu: "Garbova de Sus", comuna: "Aiud" },
  { nume: "Gârbova", simplu: "Garbova" },
  { nume: "Gârboviţa", simplu: "Garbovita", comuna: "Aiud" },
  { nume: "Gârda de Sus", simplu: "Garda de Sus" },
  { nume: "Gârda Seacă", simplu: "Garda Seaca", comuna: "Garda De Sus" },
  {
    nume: "Gârda-Bărbuleşti",
    simplu: "Garda-Barbulesti",
    comuna: "Rosia Montana",
  },
  { nume: "Gârde", simplu: "Garde", comuna: "Bistra" },
  { nume: "Geamăna", simplu: "Geamana", comuna: "Lupsa" },
  { nume: "Geoagiu de Sus", comuna: "Stremt" },
  { nume: "Geogel", comuna: "Ponor" },
  { nume: "Geomal", comuna: "Stremt" },
  { nume: "Gheduleşti", simplu: "Ghedulesti", comuna: "Ciuruleasa" },
  { nume: "Gheţari", simplu: "Ghetari", comuna: "Garda De Sus" },
  { nume: "Ghioncani", comuna: "Intregalde" },
  { nume: "Ghirbom", comuna: "Berghin" },
  { nume: "Giurgiuţ", simplu: "Giurgiut", comuna: "Horea" },
  { nume: "Gligoreşti", simplu: "Gligoresti", comuna: "Vidra" },
  { nume: "Glod", comuna: "Almasu Mare" },
  { nume: "Glogoveţ", simplu: "Glogovet", comuna: "Valea Lunga" },
  { nume: "Goaşele", simplu: "Goasele", comuna: "Cugir" },
  { nume: "Goieşti", simplu: "Goiesti", comuna: "Vidra" },
  { nume: "Gojeieşti", simplu: "Gojeiesti", comuna: "Avram Iancu" },
  { nume: "Gorgan", comuna: "Cenade" },
  { nume: "Groşi", simplu: "Grosi", comuna: "Ceru-Bacainti" },
  {
    nume: "Gura Arieşului",
    simplu: "Gura Ariesului",
    comuna: "Lunca Muresului",
  },
  { nume: "Gura Cornei", comuna: "Abrud" },
  { nume: "Gura Cuţului", simplu: "Gura Cutului", comuna: "Vintu De Jos" },
  { nume: "Gura Izbitei", comuna: "Bucium" },
  { nume: "Gura Roşiei", simplu: "Gura Rosiei", comuna: "Rosia Montana" },
  { nume: "Gura Sohodol", comuna: "Sohodol" },
  { nume: "Hădărău", simplu: "Hadarau", comuna: "Lupsa" },
  { nume: "Haiduceşti", simplu: "Haiducesti", comuna: "Vidra" },
  { nume: "Hanăşeşti", simplu: "Hanasesti", comuna: "Garda De Sus" },
  { nume: "Hănăşeşti", simplu: "Hanasesti", comuna: "Poiana Vadului" },
  { nume: "Hăpria", simplu: "Hapria", comuna: "Ciugud" },
  { nume: "Hărăşti", simplu: "Harasti", comuna: "Vidra" },
  { nume: "Haţegana", simplu: "Hategana", comuna: "Vintu De Jos" },
  { nume: "Helereşti", simplu: "Heleresti", comuna: "Avram Iancu" },
  { nume: "Heleşti", simplu: "Helesti", comuna: "Bucium" },
  { nume: "Henig", comuna: "Berghin" },
  { nume: "Heria", comuna: "Farau" },
  { nume: "Hoancă", simplu: "Hoanca", comuna: "Sohodol" },
  { nume: "Hoancă", simplu: "Hoanca", comuna: "Vidra" },
  { nume: "Hodişeşti", simplu: "Hodisesti", comuna: "Bistra" },
  { nume: "Hodobana", comuna: "Arieseni" },
  { nume: "Holobani", comuna: "Lupsa" },
  { nume: "Hopârta", simplu: "Hoparta" },
  { nume: "Horea" },
  { nume: "Hudriceşti", simplu: "Hudricesti", comuna: "Bistra" },
  { nume: "Huzăreşti", simplu: "Huzaresti", comuna: "Garda De Sus" },
  { nume: "Iacobeşti", simplu: "Iacobesti", comuna: "Rosia Montana" },
  { nume: "Ibru", comuna: "Blandiana" },
  { nume: "Iclod", comuna: "Sancel" },
  { nume: "Ighiel", comuna: "Ighiu" },
  { nume: "Ighiu" },
  { nume: "Ignăţeşti", simplu: "Ignatesti", comuna: "Rosia Montana" },
  { nume: "Ilieşti", simplu: "Iliesti", comuna: "Intregalde" },
  { nume: "Inceşti", simplu: "Incesti", comuna: "Avram Iancu" },
  { nume: "Inceşti", simplu: "Incesti", comuna: "Posaga" },
  { nume: "Inoc", comuna: "Unirea" },
  { nume: "Întregalde", simplu: "Intregalde" },
  { nume: "Inuri", comuna: "Vintu De Jos" },
  { nume: "Isca", comuna: "Metes" },
  { nume: "Ivăniş", simplu: "Ivanis", comuna: "Intregalde" },
  { nume: "Izbicioara", comuna: "Bucium" },
  { nume: "Izbita", comuna: "Bucium" },
  { nume: "Izlaz", comuna: "Arieseni" },
  { nume: "Izvoarele", comuna: "Blaj" },
  { nume: "Izvoarele", comuna: "Garda De Sus" },
  { nume: "Izvoarele", comuna: "Livezile" },
  { nume: "Izvoru Ampoiului", comuna: "Zlatna" },
  { nume: "Jefleşti", simplu: "Jeflesti", comuna: "Vidra" },
  { nume: "Jidoştina", simplu: "Jidostina", comuna: "Sugag" },
  { nume: "Jidvei" },
  { nume: "Jojei", comuna: "Avram Iancu" },
  { nume: "Joldişeşti", simplu: "Joldisesti", comuna: "Sohodol" },
  { nume: "Jurcuieşti", simplu: "Jurcuiesti", comuna: "Bucium" },
  { nume: "Lancrăm", simplu: "Lancram", comuna: "Sebes" },
  { nume: "Laz", comuna: "Sasciori" },
  { nume: "Laz", comuna: "Vintu De Jos" },
  { nume: "Lăzeşti", simplu: "Lazesti", comuna: "Scarisoara" },
  { nume: "Lăzeşti", simplu: "Lazesti", comuna: "Vadu Motilor" },
  { nume: "Lazuri", comuna: "Lupsa" },
  { nume: "Lazuri", comuna: "Sohodol" },
  { nume: "Leheşti", simplu: "Lehesti", comuna: "Sohodol" },
  { nume: "Leorinţ", simplu: "Leorint", comuna: "Radesti" },
  { nume: "Lespezea", comuna: "Scarisoara" },
  { nume: "Limba", comuna: "Ciugud" },
  { nume: "Lipaia", comuna: "Bistra" },
  { nume: "Livezile" },
  { nume: "Lodroman", comuna: "Valea Lunga" },
  { nume: "Loman", comuna: "Sasciori" },
  { nume: "Lopadea Nouă", simplu: "Lopadea Noua" },
  { nume: "Lopadea Veche", comuna: "Miraslau" },
  { nume: "Lumineşti", simplu: "Luminesti", comuna: "Sohodol" },
  { nume: "Lunca Ampoiţei", simplu: "Lunca Ampoitei", comuna: "Metes" },
  { nume: "Lunca Bisericii", comuna: "Vidra" },
  { nume: "Lunca de Jos", comuna: "Vidra" },
  { nume: "Lunca Goieşti", simplu: "Lunca Goiesti", comuna: "Vidra" },
  { nume: "Lunca Largă", simplu: "Lunca Larga", comuna: "Bistra" },
  { nume: "Lunca Largă", simplu: "Lunca Larga", comuna: "Ocolis" },
  { nume: "Lunca Merilor", comuna: "Bistra" },
  { nume: "Lunca Meteşului", simplu: "Lunca Metesului", comuna: "Metes" },
  { nume: "Lunca Mureşului", simplu: "Lunca Muresului" },
  { nume: "Lunca Târnavei", simplu: "Lunca Tarnavei", comuna: "Sona" },
  { nume: "Lunca Veseşti", simplu: "Lunca Vesesti", comuna: "Vidra" },
  { nume: "Lunca", comuna: "Lupsa" },
  { nume: "Lunca", comuna: "Posaga" },
  { nume: "Lunca", comuna: "Valea Lunga" },
  { nume: "Lunca", comuna: "Vidra" },
  { nume: "Lupăieşti", simplu: "Lupaiesti", comuna: "Poiana Vadului" },
  { nume: "Lupşa", simplu: "Lupsa" },
  { nume: "Lupşeni", simplu: "Lupseni", comuna: "Galda De Jos" },
  { nume: "Lupu", comuna: "Cergau" },
  { nume: "Lupuleşti", simplu: "Lupulesti", comuna: "Bucium" },
  { nume: "Măcăreşti", simplu: "Macaresti", comuna: "Ponor" },
  { nume: "Măghierat", simplu: "Maghierat", comuna: "Ohaba" },
  { nume: "Măgina", simplu: "Magina", comuna: "Aiud" },
  { nume: "Măgura", simplu: "Magura", comuna: "Bucium" },
  { nume: "Măgura", simplu: "Magura", comuna: "Galda De Jos" },
  { nume: "Măhăceni", simplu: "Mahaceni", comuna: "Unirea" },
  { nume: "Mămăligani", simplu: "Mamaligani", comuna: "Mogos" },
  { nume: "Mănărade", simplu: "Manarade", comuna: "Blaj" },
  { nume: "Mănăstire", simplu: "Manastire", comuna: "Lupsa" },
  { nume: "Mănceşti", simplu: "Mancesti", comuna: "Horea" },
  { nume: "Mărgaia", simplu: "Margaia", comuna: "Lupsa" },
  { nume: "Mărgineni", simplu: "Margineni", comuna: "Salistea" },
  { nume: "Mărineşti", simplu: "Marinesti", comuna: "Intregalde" },
  { nume: "Mărteşti", simplu: "Martesti", comuna: "Avram Iancu" },
  { nume: "Mărtinie", simplu: "Martinie", comuna: "Sugag" },
  { nume: "Mătăcina", simplu: "Matacina", comuna: "Vintu De Jos" },
  { nume: "Maţei", simplu: "Matei", comuna: "Scarisoara" },
  { nume: "Mătişeşti", simplu: "Matisesti", comuna: "Ciuruleasa" },
  { nume: "Mătişeşti", simplu: "Matisesti", comuna: "Horea" },
  { nume: "Medreşti", simplu: "Medresti", comuna: "Sohodol" },
  { nume: "Medveş", simplu: "Medves", comuna: "Farau" },
  { nume: "Mereteu", comuna: "Vintu De Jos" },
  { nume: "Meşcreac", simplu: "Mescreac", comuna: "Radesti" },
  { nume: "Mesentea", comuna: "Galda De Jos" },
  { nume: "Meteş", simplu: "Metes" },
  { nume: "Miceşti", simplu: "Micesti", comuna: "Alba Iulia" },
  { nume: "Micoşlaca", simplu: "Micoslaca", comuna: "Ocna Mures" },
  { nume: "Mihăieşti", simplu: "Mihaiesti", comuna: "Bistra" },
  { nume: "Mihalţ", simplu: "Mihalt" },
  { nume: "Mihoeşti", simplu: "Mihoesti", comuna: "Campeni" },
  { nume: "Mirăslău", simplu: "Miraslau" },
  { nume: "Modoleşti", simplu: "Modolesti", comuna: "Intregalde" },
  { nume: "Modoleşti", simplu: "Modolesti", comuna: "Vidra" },
  { nume: "Mogoş", simplu: "Mogos" },
  { nume: "Morăreşti", simplu: "Moraresti", comuna: "Ciuruleasa" },
  { nume: "Morăreşti", simplu: "Moraresti", comuna: "Sohodol" },
  { nume: "Morcăneşti", simplu: "Morcanesti", comuna: "Poiana Vadului" },
  { nume: "Motorăşti", simplu: "Motorasti", comuna: "Campeni" },
  { nume: "Mugeşti", simplu: "Mugesti", comuna: "Cugir" },
  { nume: "Muncelu", comuna: "Baia De Aries" },
  { nume: "Muneşti", simplu: "Munesti", comuna: "Sohodol" },
  { nume: "Muntari", comuna: "Bucium" },
  { nume: "Munună", simplu: "Mununa", comuna: "Garda De Sus" },
  { nume: "Muşca", simplu: "Musca", comuna: "Lupsa" },
  { nume: "Nădăştia", simplu: "Nadastia", comuna: "Almasu Mare" },
  { nume: "Nămaş", simplu: "Namas", comuna: "Bistra" },
  { nume: "Năpăieşti", simplu: "Napaiesti", comuna: "Sohodol" },
  { nume: "Necrileşti", simplu: "Necrilesti", comuna: "Intregalde" },
  { nume: "Necşeşti", simplu: "Necsesti", comuna: "Vadu Motilor" },
  { nume: "Negeşti", simplu: "Negesti", comuna: "Scarisoara" },
  { nume: "Negreşti", simplu: "Negresti", comuna: "Mogos" },
  { nume: "Nelegeşti", simplu: "Nelegesti", comuna: "Sohodol" },
  { nume: "Nemeşi", simplu: "Nemesi", comuna: "Vidra" },
  { nume: "Nicoreşti", simplu: "Nicoresti", comuna: "Sohodol" },
  { nume: "Niculeşti", simplu: "Niculesti", comuna: "Horea" },
  { nume: "Noşlac", simplu: "Noslac" },
  { nume: "Novăceşti", simplu: "Novacesti", comuna: "Bistra" },
  { nume: "Oarda", comuna: "Alba Iulia" },
  { nume: "Obreja", comuna: "Mihalt" },
  { nume: "Ocna Mureş", simplu: "Ocna Mures" },
  { nume: "Ocnişoara", simplu: "Ocnisoara", comuna: "Lopadea Noua" },
  { nume: "Ocoale", comuna: "Garda De Sus" },
  { nume: "Ocoliş", simplu: "Ocolis" },
  { nume: "Odverem", comuna: "Lopadea Noua" },
  { nume: "Ohaba" },
  { nume: "Oideşti", simplu: "Oidesti", comuna: "Vidra" },
  { nume: "Oiejdea", comuna: "Galda De Jos" },
  { nume: "Olteni", comuna: "Ramet" },
  { nume: "Onceşti", simplu: "Oncesti", comuna: "Mogos" },
  { nume: "Orăşti", simplu: "Orasti", comuna: "Posaga" },
  { nume: "Orgeşti", simplu: "Orgesti", comuna: "Avram Iancu" },
  { nume: "Ormeniş", simplu: "Ormenis", comuna: "Miraslau" },
  { nume: "Pâclişa", simplu: "Paclisa", comuna: "Alba Iulia" },
  { nume: "Pădure", simplu: "Padure", comuna: "Craciunelu De Jos" },
  { nume: "Pădurea", simplu: "Padurea", comuna: "Metes" },
  { nume: "Păgida", simplu: "Pagida", comuna: "Aiud" },
  { nume: "Pănade", simplu: "Panade", comuna: "Sancel" },
  { nume: "Pânca", simplu: "Panca", comuna: "Craciunelu De Jos" },
  { nume: "Pănteşti", simplu: "Pantesti", comuna: "Arieseni" },
  { nume: "Pârau Gruiului", simplu: "Parau Gruiului", comuna: "Zlatna" },
  {
    nume: "Pârău lui Mihai",
    simplu: "Parau lui Mihai",
    comuna: "Vintu De Jos",
  },
  { nume: "Pârâu-Cărbunări", simplu: "Parau-Carbunari", comuna: "Lupsa" },
  { nume: "Păşteşti", simplu: "Pastesti", comuna: "Poiana Vadului" },
  { nume: "Pătrăhăiţeşti", simplu: "Patrahaitesti", comuna: "Arieseni" },
  { nume: "Pătrângeni", simplu: "Patrangeni", comuna: "Zlatna" },
  { nume: "Pătruşeşti", simplu: "Patrusesti", comuna: "Horea" },
  { nume: "Pătruţeşti", simplu: "Patrutesti", comuna: "Avram Iancu" },
  { nume: "Peleş", simplu: "Peles", comuna: "Sohodol" },
  { nume: "Perjeşti", simplu: "Perjesti", comuna: "Bistra" },
  { nume: "Peste Valea Bistrii", comuna: "Campeni" },
  { nume: "Peţelca", simplu: "Petelca", comuna: "Teius" },
  { nume: "Petelei", comuna: "Poiana Vadului" },
  { nume: "Petreasa", comuna: "Horea" },
  { nume: "Petreni", comuna: "Bucium" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Sebes" },
  { nume: "Petrisat", comuna: "Blaj" },
  { nume: "Pianu de Jos", comuna: "Pianu" },
  { nume: "Pianu de Sus", comuna: "Pianu" },
  { nume: "Pirita", comuna: "Zlatna" },
  { nume: "Pitărceşti", simplu: "Pitarcesti", comuna: "Vidra" },
  { nume: "Piţiga", simplu: "Pitiga", comuna: "Lupsa" },
  { nume: "Plai", comuna: "Avram Iancu" },
  { nume: "Plai", comuna: "Garda De Sus" },
  { nume: "Plaiuri", comuna: "Pianu" },
  { nume: "Pleşcuţa", simplu: "Plescuta", comuna: "Vidra" },
  { nume: "Pleşeşti", simplu: "Plesesti", comuna: "Albac" },
  { nume: "Pleşi", simplu: "Plesi", comuna: "Sasciori" },
  { nume: "Plişti", simplu: "Plisti", comuna: "Garda De Sus" },
  { nume: "Podu lui Paul", comuna: "Zlatna" },
  {
    nume: "Poduri-Briceşti",
    simplu: "Poduri-Bricesti",
    comuna: "Vadu Motilor",
  },
  { nume: "Poduri", comuna: "Campeni" },
  { nume: "Poiana Aiudului", comuna: "Livezile" },
  { nume: "Poiana Ampoiului", comuna: "Metes" },
  { nume: "Poiana Galdei", comuna: "Galda De Jos" },
  { nume: "Poiana Ursului", comuna: "Metes" },
  { nume: "Poiana Vadului" },
  { nume: "Poiana", comuna: "Bistra" },
  { nume: "Poiana", comuna: "Bucium" },
  { nume: "Poiana", comuna: "Sohodol" },
  { nume: "Poieni", comuna: "Blandiana" },
  { nume: "Poieni", comuna: "Bucium" },
  { nume: "Poieni", comuna: "Vidra" },
  { nume: "Poienile-Mogoş", simplu: "Poienile-Mogos", comuna: "Mogos" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Arieseni" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Vintu De Jos" },
  { nume: "Poiu", comuna: "Bistra" },
  { nume: "Ponor" },
  { nume: "Ponorel", comuna: "Vidra" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Intregalde" },
  {
    nume: "Popeştii de Jos",
    simplu: "Popestii de Jos",
    comuna: "Vadu Motilor",
  },
  {
    nume: "Popeştii de Sus",
    simplu: "Popestii de Sus",
    comuna: "Vadu Motilor",
  },
  { nume: "Poşaga de Jos", simplu: "Posaga de Jos", comuna: "Posaga" },
  { nume: "Poşaga de Sus", simplu: "Posaga de Sus", comuna: "Posaga" },
  { nume: "Poşogani", simplu: "Posogani", comuna: "Lupsa" },
  { nume: "Potionci", comuna: "Albac" },
  { nume: "Preluca", comuna: "Horea" },
  { nume: "Prelucă", simplu: "Preluca", comuna: "Scarisoara" },
  { nume: "Presaca Ampoiului", comuna: "Metes" },
  { nume: "Puiuleţeşti", simplu: "Puiuletesti", comuna: "Vidra" },
  { nume: "Purcăreţi", simplu: "Purcareti", comuna: "Pianu" },
  { nume: "Puşeleşti", simplu: "Puselesti", comuna: "Avram Iancu" },
  { nume: "Răcătău", simplu: "Racatau", comuna: "Blandiana" },
  { nume: "Rachiş", simplu: "Rachis", comuna: "Miraslau" },
  { nume: "Răchita", simplu: "Rachita", comuna: "Sasciori" },
  { nume: "Rădeşti", simplu: "Radesti" },
  { nume: "Răhău", simplu: "Rahau", comuna: "Sebes" },
  { nume: "Răicani", simplu: "Raicani", comuna: "Galda De Jos" },
  { nume: "Râmeţ", simplu: "Ramet" },
  { nume: "Râmetea", simplu: "Rametea" },
  { nume: "Rătitiş", simplu: "Ratitis", comuna: "Bistra" },
  { nume: "Raviceşti", simplu: "Ravicesti", comuna: "Arieseni" },
  {
    nume: "Războieni-Cetate",
    simplu: "Razboieni-Cetate",
    comuna: "Ocna Mures",
  },
  { nume: "Reciu", comuna: "Garbova" },
  { nume: "Remetea", comuna: "Metes" },
  { nume: "Robeşti", simplu: "Robesti", comuna: "Sohodol" },
  { nume: "Rogoz", comuna: "Albac" },
  { nume: "Roşeşti", simplu: "Rosesti", comuna: "Albac" },
  { nume: "Roşia de Secaş", simplu: "Rosia de Secas" },
  { nume: "Roşia Montană", simplu: "Rosia Montana" },
  { nume: "Runc", comuna: "Ocolis" },
  { nume: "Runc", comuna: "Scarisoara" },
  { nume: "Runc", comuna: "Vidra" },
  { nume: "Runc", comuna: "Zlatna" },
  { nume: "Runcuri", comuna: "Bistra" },
  { nume: "Ruseşti", simplu: "Rusesti", comuna: "Albac" },
  { nume: "Ruşi", simplu: "Rusi", comuna: "Zlatna" },
  { nume: "Sagagea", comuna: "Posaga" },
  { nume: "Sălăgeşti", simplu: "Salagesti", comuna: "Bistra" },
  { nume: "Sălciua de Jos", simplu: "Salciua de Jos", comuna: "Salciua" },
  { nume: "Sălciua de Sus", simplu: "Salciua de Sus", comuna: "Salciua" },
  { nume: "Săliştea-Deal", simplu: "Salistea-Deal", comuna: "Salistea" },
  { nume: "Săliştea", simplu: "Salistea" },
  { nume: "Sânbenedic", simplu: "Sanbenedic", comuna: "Farau" },
  { nume: "Sâncel", simplu: "Sancel" },
  { nume: "Sâncrai", simplu: "Sancrai", comuna: "Aiud" },
  { nume: "Sânmiclăuş", simplu: "Sanmiclaus", comuna: "Sona" },
  { nume: "Sântămărie", simplu: "Santamarie", comuna: "Cetatea De Balta" },
  { nume: "Sântimbru", simplu: "Santimbru" },
  { nume: "Sărăcsău", simplu: "Saracsau", comuna: "Sibot" },
  { nume: "Şard", simplu: "Sard", comuna: "Ighiu" },
  { nume: "Sartăş", simplu: "Sartas", comuna: "Baia De Aries" },
  { nume: "Şasa", simplu: "Sasa", comuna: "Lupsa" },
  { nume: "Săsciori", simplu: "Sasciori" },
  { nume: "Scărişoara", simplu: "Scarisoara" },
  { nume: "Scoarţa", simplu: "Scoarta", comuna: "Garda De Sus" },
  { nume: "Sebeş", simplu: "Sebes" },
  { nume: "Sebeşel", simplu: "Sebesel", comuna: "Sasciori" },
  { nume: "Sebişeşti", simplu: "Sebisesti", comuna: "Sohodol" },
  { nume: "Secăşel", simplu: "Secasel", comuna: "Ohaba" },
  { nume: "Segaj", comuna: "Vidra" },
  { nume: "Şeuşa", simplu: "Seusa", comuna: "Ciugud" },
  { nume: "Sfârcea", simplu: "Sfarcea", comuna: "Intregalde" },
  { nume: "Sfoartea", comuna: "Scarisoara" },
  { nume: "Şibot", simplu: "Sibot" },
  { nume: "Sicoieşti", simplu: "Sicoiesti", comuna: "Sohodol" },
  { nume: "Şilea", simplu: "Silea", comuna: "Farau" },
  { nume: "Silivaş", simplu: "Silivas", comuna: "Hoparta" },
  { nume: "Şimoceşti", simplu: "Simocesti", comuna: "Sohodol" },
  { nume: "Simuleşti", simplu: "Simulesti", comuna: "Baia De Aries" },
  { nume: "Snide", comuna: "Garda De Sus" },
  { nume: "Şoal", simplu: "Soal", comuna: "Rosia Montana" },
  { nume: "Soharu", comuna: "Abrud" },
  { nume: "Sohodol" },
  { nume: "Sohodol", comuna: "Albac" },
  { nume: "Şoiceşti", simplu: "Soicesti", comuna: "Avram Iancu" },
  { nume: "Şoimuş", simplu: "Soimus", comuna: "Radesti" },
  { nume: "Şona", simplu: "Sona" },
  { nume: "Sorliţa", simplu: "Sorlita", comuna: "Campeni" },
  { nume: "Şpălnaca", simplu: "Spalnaca", comuna: "Hoparta" },
  { nume: "Spătac", simplu: "Spatac", comuna: "Blaj" },
  { nume: "Şpring", simplu: "Spring" },
  { nume: "Stâlnişoara", simplu: "Stalnisoara", comuna: "Bucium" },
  { nume: "Stâna de Mureş", simplu: "Stana de Mures", comuna: "Noslac" },
  { nume: "Stăneşti", simplu: "Stanesti", comuna: "Poiana Vadului" },
  { nume: "Stăuini", simplu: "Stauini", comuna: "Vintu De Jos" },
  { nume: "Ştefanca", simplu: "Stefanca", comuna: "Bistra" },
  { nume: "Ştei-Arieşeni", simplu: "Stei-Arieseni", comuna: "Arieseni" },
  { nume: "Şterteşti", simplu: "Stertesti", comuna: "Avram Iancu" },
  { nume: "Ştiuleţi", simplu: "Stiuleti", comuna: "Scarisoara" },
  { nume: "Straja", comuna: "Berghin" },
  { nume: "Stremţ", simplu: "Stremt" },
  { nume: "Strungari", comuna: "Pianu" },
  { nume: "Sturu", comuna: "Arieseni" },
  { nume: "Sub Piatră", simplu: "Sub Piatra", comuna: "Salciua" },
  { nume: "Suceşti", simplu: "Sucesti", comuna: "Garda De Sus" },
  { nume: "Şugag", simplu: "Sugag" },
  { nume: "Surdeşti", simplu: "Surdesti", comuna: "Sohodol" },
  { nume: "Suseni", comuna: "Zlatna" },
  { nume: "Tamboreşti", simplu: "Tamboresti", comuna: "Albac" },
  { nume: "Ţărăneşti", simplu: "Taranesti", comuna: "Bistra" },
  { nume: "Ţarina", simplu: "Tarina", comuna: "Rosia Montana" },
  { nume: "Târsa-Plai", simplu: "Tarsa-Plai", comuna: "Avram Iancu" },
  { nume: "Târsa", simplu: "Tarsa", comuna: "Avram Iancu" },
  { nume: "Tărtăria", simplu: "Tartaria", comuna: "Salistea" },
  { nume: "Tătârlaua", simplu: "Tatarlaua", comuna: "Cetatea De Balta" },
  { nume: "Tău Bistra", simplu: "Tau Bistra", comuna: "Sugag" },
  { nume: "Tău", simplu: "Tau", comuna: "Rosia De Secas" },
  { nume: "Tăuni", simplu: "Tauni", comuna: "Valea Lunga" },
  { nume: "Tăuţi", simplu: "Tauti", comuna: "Metes" },
  { nume: "Tecşeşti", simplu: "Tecsesti", comuna: "Intregalde" },
  { nume: "Teiu", comuna: "Horea" },
  { nume: "Teiuş", simplu: "Teius" },
  { nume: "Teleac", comuna: "Ciugud" },
  { nume: "Ţelna", simplu: "Telna", comuna: "Ighiu" },
  { nume: "Tibru", comuna: "Cricau" },
  { nume: "Ţifra", simplu: "Tifra", comuna: "Aiud" },
  { nume: "Tiur", comuna: "Blaj" },
  { nume: "Toci", comuna: "Sohodol" },
  { nume: "Tolăceşti", simplu: "Tolacesti", comuna: "Bistra" },
  { nume: "Tomeşti", simplu: "Tomesti", comuna: "Mogos" },
  { nume: "Tomnatec", comuna: "Bistra" },
  { nume: "Tomuşeşti", simplu: "Tomusesti", comuna: "Campeni" },
  { nume: "Tomuţeşti", simplu: "Tomutesti", comuna: "Vadu Motilor" },
  { nume: "Tonea", comuna: "Sasciori" },
  { nume: "Toţeşti", simplu: "Totesti", comuna: "Vadu Motilor" },
  { nume: "Totoi", comuna: "Santimbru" },
  { nume: "Trâmpoiele", simplu: "Trampoiele", comuna: "Zlatna" },
  { nume: "Trânceşti", simplu: "Trancesti", comuna: "Scarisoara" },
  { nume: "Trifeşti", simplu: "Trifesti", comuna: "Horea" },
  { nume: "Trifeşti", simplu: "Trifesti", comuna: "Lupsa" },
  { nume: "Trişoreşti", simplu: "Trisoresti", comuna: "Bistra" },
  { nume: "Turdaş", simplu: "Turdas", comuna: "Hoparta" },
  { nume: "Uioara de Jos", comuna: "Ocna Mures" },
  { nume: "Uioara de Sus", comuna: "Ocna Mures" },
  { nume: "Ungurei", comuna: "Rosia De Secas" },
  { nume: "Unirea" },
  { nume: "Urdeş", simplu: "Urdes", comuna: "Vidra" },
  { nume: "Vadu Moţilor", simplu: "Vadu Motilor" },
  { nume: "Văi", simplu: "Vai", comuna: "Lupsa" },
  { nume: "Vâlcăneasa", simplu: "Valcaneasa", comuna: "Vidra" },
  { nume: "Vâlcea", simplu: "Valcea", comuna: "Bucium" },
  { nume: "Vâlceşti", simplu: "Valcesti", comuna: "Vidra" },
  { nume: "Vale In Jos", comuna: "Ponor" },
  { nume: "Valea Abruzel", comuna: "Bucium" },
  { nume: "Valea Albă", simplu: "Valea Alba", comuna: "Bucium" },
  { nume: "Valea Bârluţeşti", simplu: "Valea Barlutesti", comuna: "Mogos" },
  { nume: "Valea Barnii", comuna: "Mogos" },
  { nume: "Valea Bistrii", comuna: "Campeni" },
  { nume: "Valea Bucurului", comuna: "Ponor" },
  { nume: "Valea Caselor", comuna: "Campeni" },
  { nume: "Valea Cerbului", comuna: "Bucium" },
  { nume: "Valea Ciuciului", comuna: "Noslac" },
  { nume: "Valea Coceşti", simplu: "Valea Cocesti", comuna: "Mogos" },
  { nume: "Valea Făgetului", simplu: "Valea Fagetului", comuna: "Ramet" },
  { nume: "Valea Giogeşti", simplu: "Valea Giogesti", comuna: "Mogos" },
  { nume: "Valea Goblii", comuna: "Vintu De Jos" },
  { nume: "Valea Holhorii", comuna: "Lupsa" },
  { nume: "Valea Inzelului", comuna: "Ramet" },
  { nume: "Valea Largă", simplu: "Valea Larga", comuna: "Salciua" },
  { nume: "Valea lui Mihai", comuna: "Vintu De Jos" },
  { nume: "Valea Lungă", simplu: "Valea Lunga" },
  { nume: "Valea Lupşii", simplu: "Valea Lupsii", comuna: "Lupsa" },
  { nume: "Valea Maciului", comuna: "Avram Iancu" },
  { nume: "Valea Mănăstirii", simplu: "Valea Manastirii", comuna: "Ramet" },
  { nume: "Valea Mare", comuna: "Ceru-Bacainti" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Zlatna" },
  { nume: "Valea Mlacii", comuna: "Mogos" },
  { nume: "Valea Morii", comuna: "Vidra" },
  { nume: "Valea Negrilesii", comuna: "Bucium" },
  { nume: "Valea Poienii", comuna: "Bucium" },
  { nume: "Valea Poienii", comuna: "Ramet" },
  { nume: "Valea Sasului", comuna: "Sona" },
  { nume: "Valea Şesii", simplu: "Valea Sesii", comuna: "Bucium" },
  { nume: "Valea Şesii", simplu: "Valea Sesii", comuna: "Lupsa" },
  { nume: "Valea Ţupilor", simplu: "Valea Tupilor", comuna: "Mogos" },
  { nume: "Valea Uţului", simplu: "Valea Utului", comuna: "Avram Iancu" },
  { nume: "Valea Uzei", comuna: "Ramet" },
  { nume: "Valea Verde", comuna: "Sohodol" },
  { nume: "Valea Vinţului", simplu: "Valea Vintului", comuna: "Vintu De Jos" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Bucium" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Metes" },
  { nume: "Vălişoara", simplu: "Valisoara", comuna: "Livezile" },
  { nume: "Vâltori", simplu: "Valtori", comuna: "Vadu Motilor" },
  { nume: "Vâltori", simplu: "Valtori", comuna: "Zlatna" },
  { nume: "Vama Seacă", simplu: "Vama Seaca", comuna: "Hoparta" },
  { nume: "Vanvuceşti", simplu: "Vanvucesti", comuna: "Arieseni" },
  { nume: "Vârşi-Rontu", simplu: "Varsi-Rontu", comuna: "Bistra" },
  { nume: "Vârşi", simplu: "Varsi", comuna: "Campeni" },
  { nume: "Vârşii Mari", simplu: "Varsii Mari", comuna: "Bistra" },
  { nume: "Vârşii Mici", simplu: "Varsii Mici", comuna: "Bistra" },
  { nume: "Vârtăneşti", simplu: "Vartanesti", comuna: "Vidra" },
  { nume: "Vârtop", simplu: "Vartop", comuna: "Rosia Montana" },
  { nume: "Văseşti", simplu: "Vasesti", comuna: "Vidra" },
  { nume: "Verdeşti", simplu: "Verdesti", comuna: "Avram Iancu" },
  { nume: "Veseuş", simplu: "Veseus", comuna: "Jidvei" },
  { nume: "Veza", comuna: "Blaj" },
  { nume: "Vidolm", comuna: "Ocolis" },
  { nume: "Vidra" },
  { nume: "Vidrişoara", simplu: "Vidrisoara", comuna: "Avram Iancu" },
  { nume: "Viezuri", comuna: "Ceru-Bacainti" },
  { nume: "Vinerea", comuna: "Cugir" },
  { nume: "Vingard", comuna: "Spring" },
  { nume: "Vinţa", simplu: "Vinta", comuna: "Lupsa" },
  { nume: "Vinţu de Jos", simplu: "Vintu de Jos" },
  { nume: "Vlădeşti", simplu: "Vladesti", comuna: "Ramet" },
  { nume: "Vlădoşeşti", simplu: "Vladosesti", comuna: "Sohodol" },
  { nume: "Vulcan", comuna: "Ciuruleasa" },
  { nume: "Vurpăr", simplu: "Vurpar", comuna: "Vintu De Jos" },
  { nume: "Zăgriş", simplu: "Zagris", comuna: "Galda De Jos" },
  { nume: "Zânzeşti", simplu: "Zanzesti", comuna: "Horea" },
  { nume: "Zărieş", simplu: "Zaries", comuna: "Mihalt" },
  { nume: "Zlatna" },
];
