export const br = [
  { nume: "Bertestii de Jos" },
  { nume: "Bordei Verde" },
  { nume: "Braila" },
  { nume: "Baraganul" },
  { nume: "Cazasu" },
  { nume: "Chiscani" },
  { nume: "Ciocile" },
  { nume: "Ciresu" },
  { nume: "Dudesti" },
  { nume: "Frecatei" },
  { nume: "Faurei" },
  { nume: "Galbenu" },
  { nume: "Gemenele" },
  { nume: "Gradistea" },
  { nume: "Gropeni" },
  { nume: "Ianca" },
  { nume: "Jirlau" },
  { nume: "Mircea Voda" },
  { nume: "Movila Miresii" },
  { nume: "Marasu" },
  { nume: "Maxineni" },
  { nume: "Racovita" },
  { nume: "Romanu" },
  { nume: "Rosiori" },
  { nume: "Ramnicelu" },
  { nume: "Salcia Tudor" },
  { nume: "Scortaru Nou" },
  { nume: "Silistea" },
  { nume: "Stancuta" },
  { nume: "Surdila-Greci" },
  { nume: "Surdila-Gaiseanca" },
  { nume: "Tichilesti" },
  { nume: "Traian" },
  { nume: "Tudor Vladimirescu" },
  { nume: "Tufesti" },
  { nume: "Ulmu" },
  { nume: "Unirea" },
  { nume: "Victoria" },
  { nume: "Viziru" },
  { nume: "Visani" },
  { nume: "Vadeni" },
  { nume: "Zavoaia" },
  { nume: "Insuratei" },
  { nume: "Sutesti" },
  { nume: "Bertestii de Sus", comuna: "Bertestii De Jos" },
  { nume: "Gura Calmatui", comuna: "Bertestii De Jos" },
  { nume: "Gura Garlutei", comuna: "Bertestii De Jos" },
  { nume: "Nicolesti", comuna: "Bertestii De Jos" },
  { nume: "Spiru Haret", comuna: "Bertestii De Jos" },
  { nume: "Constantin Gabrielescu", comuna: "Bordei Verde" },
  { nume: "Filiu", comuna: "Bordei Verde" },
  { nume: "Liscoteanca", comuna: "Bordei Verde" },
  { nume: "Lacu Sarat", comuna: "Chiscani" },
  { nume: "Varsatura", comuna: "Chiscani" },
  { nume: "Chichinetu", comuna: "Ciocile" },
  { nume: "Chioibasesti", comuna: "Ciocile" },
  { nume: "Odaieni", comuna: "Ciocile" },
  { nume: "Batogu", comuna: "Ciresu" },
  { nume: "Ionesti", comuna: "Ciresu" },
  { nume: "Scarlatesti", comuna: "Ciresu" },
  { nume: "Vultureni", comuna: "Ciresu" },
  { nume: "Bumbacari", comuna: "Dudesti" },
  { nume: "Tataru", comuna: "Dudesti" },
  { nume: "Agaua", comuna: "Frecatei" },
  { nume: "Cistia", comuna: "Frecatei" },
  { nume: "Salcia", comuna: "Frecatei" },
  { nume: "Stoienesti", comuna: "Frecatei" },
  { nume: "Titcov", comuna: "Frecatei" },
  { nume: "Drogu", comuna: "Galbenu" },
  { nume: "Pantecani", comuna: "Galbenu" },
  { nume: "Satuc", comuna: "Galbenu" },
  { nume: "Zamfiresti", comuna: "Galbenu" },
  { nume: "Gavani", comuna: "Gemenele" },
  { nume: "Ibrianu", comuna: "Gradistea" },
  { nume: "Maraloiu", comuna: "Gradistea" },
  { nume: "Berlesti", comuna: "Ianca" },
  { nume: "Gara Ianca", comuna: "Ianca" },
  { nume: "Oprisenesti", comuna: "Ianca" },
  { nume: "Perisoru", comuna: "Ianca" },
  { nume: "Plopu", comuna: "Ianca" },
  { nume: "Tarlele Filiu", comuna: "Ianca" },
  { nume: "Lacu Rezii", comuna: "Insuratei" },
  { nume: "Maru Rosu", comuna: "Insuratei" },
  { nume: "Valea Calmatuiului", comuna: "Insuratei" },
  { nume: "Bradeanca", comuna: "Jirlau" },
  { nume: "Bandoiu", comuna: "Marasu" },
  { nume: "Magureni", comuna: "Marasu" },
  { nume: "Nedeicu", comuna: "Marasu" },
  { nume: "Plopi", comuna: "Marasu" },
  { nume: "Tacau", comuna: "Marasu" },
  { nume: "Corbu Nou", comuna: "Maxineni" },
  { nume: "Corbu Vechi", comuna: "Maxineni" },
  { nume: "Latinu", comuna: "Maxineni" },
  { nume: "Voinesti", comuna: "Maxineni" },
  { nume: "Dedulesti", comuna: "Mircea Voda" },
  { nume: "Esna", comuna: "Movila Miresii" },
  { nume: "Tepes Voda", comuna: "Movila Miresii" },
  { nume: "Corbeni", comuna: "Racovita" },
  { nume: "Custura", comuna: "Racovita" },
  { nume: "Boarca", comuna: "Ramnicelu" },
  { nume: "Constantinesti", comuna: "Ramnicelu" },
  { nume: "Mihail Kogalniceanu", comuna: "Ramnicelu" },
  { nume: "Oancea", comuna: "Romanu" },
  { nume: "Coltea", comuna: "Rosiori" },
  { nume: "Florica", comuna: "Rosiori" },
  { nume: "Pribeagu", comuna: "Rosiori" },
  { nume: "Ariciu", comuna: "Salcia Tudor" },
  { nume: "Cuza Voda", comuna: "Salcia Tudor" },
  { nume: "Gulianca", comuna: "Salcia Tudor" },
  { nume: "Olaneasca", comuna: "Salcia Tudor" },
  { nume: "Desirati", comuna: "Scortaru Nou" },
  { nume: "Gurguieti", comuna: "Scortaru Nou" },
  { nume: "Nicolae Balcescu", comuna: "Scortaru Nou" },
  { nume: "Pitulati", comuna: "Scortaru Nou" },
  { nume: "Sihleanu", comuna: "Scortaru Nou" },
  { nume: "Cotu Lung", comuna: "Silistea" },
  { nume: "Cotu Mihalea", comuna: "Silistea" },
  { nume: "Muchea", comuna: "Silistea" },
  { nume: "Martacesti", comuna: "Silistea" },
  { nume: "Vamesu", comuna: "Silistea" },
  { nume: "Cuza Voda", comuna: "Stancuta" },
  { nume: "Polizesti", comuna: "Stancuta" },
  { nume: "Stanca", comuna: "Stancuta" },
  { nume: "Filipesti", comuna: "Surdila-Gaiseanca" },
  { nume: "Bratesu Vechi", comuna: "Surdila-Greci" },
  { nume: "Faurei Sat", comuna: "Surdila-Greci" },
  { nume: "Horia", comuna: "Surdila-Greci" },
  { nume: "Mihail Kogalniceanu", comuna: "Sutesti" },
  { nume: "Albina", comuna: "Tichilesti" },
  { nume: "Caldarusa", comuna: "Traian" },
  { nume: "Silistraru", comuna: "Traian" },
  { nume: "Urleasca", comuna: "Traian" },
  { nume: "Comaneasca", comuna: "Tudor Vladimirescu" },
  { nume: "Scortaru Vechi", comuna: "Tudor Vladimirescu" },
  { nume: "Jugureanu", comuna: "Ulmu" },
  { nume: "Morotesti", comuna: "Unirea" },
  { nume: "Valea Canepii", comuna: "Unirea" },
  { nume: "Baldovinesti", comuna: "Vadeni" },
  { nume: "Pietroiu", comuna: "Vadeni" },
  { nume: "Mihai Bravu", comuna: "Victoria" },
  { nume: "Caineni-Bai", comuna: "Visani" },
  { nume: "Plasoiu", comuna: "Visani" },
  { nume: "Lanurile", comuna: "Viziru" },
  { nume: "Dudescu", comuna: "Zavoaia" },
];
