export const bt = [
  { nume: "Adăşeni", simplu: "Adaseni", comuna: "Avrameni" },
  { nume: "Agafton", comuna: "Curtesti" },
  { nume: "Alba", comuna: "Hudesti" },
  { nume: "Albeşti", simplu: "Albesti" },
  { nume: "Arborea", comuna: "George Enescu" },
  { nume: "Aurel Vlaicu", comuna: "Avrameni" },
  { nume: "Avram Iancu", comuna: "Cotusca" },
  { nume: "Avrămeni", simplu: "Avrameni" },
  { nume: "Băbiceni", simplu: "Babiceni", comuna: "Durnesti" },
  { nume: "Bădărăi", simplu: "Badarai", comuna: "Santa Mare" },
  { nume: "Bădiuţi", simplu: "Badiuti", comuna: "Stefanesti" },
  { nume: "Băiceni", simplu: "Baiceni", comuna: "Curtesti" },
  { nume: "Baisa", comuna: "Mihai Eminescu" },
  { nume: "Bajura", comuna: "Darabani" },
  { nume: "Balinţi", simplu: "Balinti", comuna: "Havarna" },
  { nume: "Balta Arsă", simplu: "Balta Arsa", comuna: "Corni" },
  { nume: "Băluşeni", simplu: "Baluseni" },
  { nume: "Băluşenii Noi", simplu: "Balusenii Noi", comuna: "Baluseni" },
  { nume: "Baranca", comuna: "Cristinesti" },
  { nume: "Baranca", comuna: "Hudesti" },
  { nume: "Bârsăneşti", simplu: "Barsanesti", comuna: "Durnesti" },
  { nume: "Başeu", simplu: "Baseu", comuna: "Hudești" },
  { nume: "Bătrâneşti", simplu: "Batranesti", comuna: "Gorbanesti" },
  { nume: "Belcea", comuna: "Leorda" },
  { nume: "Berza", comuna: "Santa Mare" },
  { nume: "Bivolari", comuna: "Dobarceni" },
  { nume: "Blândeşti", simplu: "Blandesti", comuna: "Blindesti" },
  { nume: "Bobuleşti", simplu: "Bobulesti", comuna: "Stefanesti" },
  { nume: "Bodeasa", comuna: "Saveni" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Santa Mare" },
  { nume: "Bohoghina", comuna: "Bucecea" },
  { nume: "Bold", comuna: "Manoleasa" },
  { nume: "Borolea", comuna: "Hanesti" },
  { nume: "Borzeşti", simplu: "Borzesti", comuna: "Ungureni" },
  { nume: "Boscoteni", comuna: "Frumusica" },
  { nume: "Botoşani", simplu: "Botosani" },
  { nume: "Bozieni", comuna: "Saveni" },
  { nume: "Brăeşti", simplu: "Braesti" },
  { nume: "Brăteni", simplu: "Brateni", comuna: "Dobarceni" },
  { nume: "Brehuieşti", simplu: "Brehuiesti", comuna: "Vladeni" },
  { nume: "Broscăuţi", simplu: "Broscauti" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Durnesti" },
  { nume: "Bucecea" },
  { nume: "Buda", comuna: "Cosula" },
  { nume: "Buhăceni", simplu: "Buhaceni", comuna: "Trusesti" },
  { nume: "Buimăceni", simplu: "Buimaceni", comuna: "Albesti" },
  { nume: "Burla", comuna: "Unteni" },
  { nume: "Burleşti", simplu: "Burlesti", comuna: "Unteni" },
  { nume: "Buzeni", comuna: "Baluseni" },
  { nume: "Călăraşi", simplu: "Calarasi" },
  { nume: "Călineşti", simplu: "Calinesti", comuna: "Bucecea" },
  { nume: "Călineşti", simplu: "Calinesti", comuna: "Candesti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Ungureni" },
  { nume: "Călugărenii Noi", simplu: "Calugarenii Noi", comuna: "Ungureni" },
  { nume: "Câmpeni", simplu: "Campeni", comuna: "Prajeni" },
  { nume: "Cândeşti", simplu: "Candesti" },
  { nume: "Caraiman", comuna: "Mihalaseni" },
  { nume: "Carasa", comuna: "Corlateni" },
  {
    nume: "Cătămăreşti-Deal",
    simplu: "Catamaresti-Deal",
    comuna: "Mihai Eminescu",
  },
  { nume: "Cătămăreşti", simplu: "Catamaresti", comuna: "Mihai Eminescu" },
  { nume: "Cerbu", comuna: "Copalau" },
  { nume: "Cerchejeni", comuna: "Blindesti" },
  { nume: "Cerneşti", simplu: "Cernesti", comuna: "Todireni" },
  {
    nume: "Cerviceşti-Deal",
    simplu: "Cervicesti-Deal",
    comuna: "Mihai Eminescu",
  },
  { nume: "Cerviceşti", simplu: "Cervicesti", comuna: "Mihai Eminescu" },
  { nume: "Cheliş", simplu: "Chelis", comuna: "Sulita" },
  { nume: "Chişcăreni", simplu: "Chiscareni", comuna: "Saveni" },
  { nume: "Chiţoveni", simplu: "Chitoveni", comuna: "Flamanzi" },
  { nume: "Cinghiniia", comuna: "Ripiceni" },
  { nume: "Ciritei", comuna: "Trusesti" },
  { nume: "Cişmăneşti", simplu: "Cismanesti", comuna: "Dobarceni" },
  { nume: "Cişmea", simplu: "Cismea", comuna: "Rachiti" },
  { nume: "Codreni", comuna: "Mileanca" },
  { nume: "Conceşti", simplu: "Concesti" },
  { nume: "Copălău", simplu: "Copalau" },
  { nume: "Cordăreni", simplu: "Cordareni" },
  { nume: "Corjăuţi", simplu: "Corjauti", comuna: "Hiliseu-Horia" },
  { nume: "Corlăteni", simplu: "Corlateni" },
  { nume: "Corni" },
  { nume: "Costeşti", simplu: "Costesti", comuna: "Rachiti" },
  { nume: "Costineşti", simplu: "Costinesti", comuna: "Leorda" },
  { nume: "Coştiugeni", simplu: "Costiugeni", comuna: "Albesti" },
  { nume: "Coşula", simplu: "Cosula" },
  { nume: "Coşuleni", simplu: "Cosuleni", comuna: "Baluseni" },
  { nume: "Cotârgaci", simplu: "Cotargaci", comuna: "Roma" },
  { nume: "Cotu Miculinţi", simplu: "Cotu Miculinti", comuna: "Cotusca" },
  { nume: "Cotu", comuna: "Copalau" },
  { nume: "Coţuşca", simplu: "Cotusca" },
  { nume: "Crasnaleuca", comuna: "Cotusca" },
  { nume: "Cristeşti", simplu: "Cristesti" },
  { nume: "Cristineşti", simplu: "Cristinesti" },
  { nume: "Cucorăni", simplu: "Cucorani", comuna: "Mihai Eminescu" },
  { nume: "Cucuteni", comuna: "Durnesti" },
  { nume: "Curteşti", simplu: "Curtesti" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Viisoara" },
  { nume: "Cuzlău", simplu: "Cuzlau", comuna: "Paltinis" },
  { nume: "Dacia", comuna: "Nicseni" },
  { nume: "Dămideni", simplu: "Damideni", comuna: "Romanesti" },
  { nume: "Dămileni", simplu: "Damileni", comuna: "Cristinești" },
  { nume: "Dângeni", simplu: "Dangeni" },
  { nume: "Darabani" },
  { nume: "Davidoaia", comuna: "Vorniceni" },
  { nume: "Dealu Crucii", comuna: "Vorniceni" },
  { nume: "Dealu Mare", comuna: "Dorohoi" },
  { nume: "Dersca" },
  { nume: "Dimăcheni", simplu: "Dimacheni" },
  { nume: "Dimitrie Cantemir", comuna: "Avrameni" },
  { nume: "Dobârceni", simplu: "Dobarceni" },
  {
    nume: "Dobrinăuţi-Hapăi",
    simplu: "Dobrinauti-Hapai",
    comuna: "Vârfu Câmpului",
  },
  { nume: "Doina", comuna: "Rauseni" },
  { nume: "Dolina", comuna: "Leorda" },
  { nume: "Dorobanţi", simplu: "Dorobanti", comuna: "Nicseni" },
  { nume: "Dorohoi" },
  { nume: "Dracşani", simplu: "Dracsani", comuna: "Sulita" },
  { nume: "Dragalina", comuna: "Cristinesti" },
  { nume: "Dragalina", comuna: "Hlipiceni" },
  { nume: "Drăguşeni", simplu: "Draguseni" },
  { nume: "Draxini", comuna: "Baluseni" },
  { nume: "Drislea", comuna: "Trusesti" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita", comuna: "Ibanesti" },
  { nume: "Dumeni", comuna: "George Enescu" },
  { nume: "Durneşti", simplu: "Durnesti" },
  { nume: "Durneşti", simplu: "Durnesti", comuna: "Santa Mare" },
  { nume: "Durneşti", simplu: "Durnesti", comuna: "Ungureni" },
  { nume: "Eşanca", simplu: "Esanca", comuna: "Darabani" },
  { nume: "Flamânzi", simplu: "Flamanzi" },
  { nume: "Flondora", comuna: "Manoleasa" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Todireni" },
  { nume: "Frumuşica", simplu: "Frumusica" },
  { nume: "Fundu Herţii", simplu: "Fundu Hertii", comuna: "Cristinesti" },
  { nume: "Galbeni", comuna: "Havarna" },
  { nume: "Gârbeni", simplu: "Garbeni", comuna: "Havarna" },
  { nume: "Gârbeşti", simplu: "Garbesti", comuna: "Todireni" },
  { nume: "George Coşbuc", simplu: "George Cosbuc", comuna: "Gorbanesti" },
  { nume: "George Enescu" },
  { nume: "Ghireni", comuna: "Cotusca" },
  { nume: "Gorbăneşti", simplu: "Gorbanesti" },
  { nume: "Gorovei", comuna: "Vaculesti" },
  { nume: "Griviţa", simplu: "Grivita", comuna: "Cordareni" },
  { nume: "Guranda", comuna: "Durnesti" },
  { nume: "Hăneşti", simplu: "Hanesti" },
  { nume: "Havârna", simplu: "Havarna" },
  { nume: "Hilişeu-Cloşca", simplu: "Hiliseu-Closca", comuna: "Hiliseu-Horia" },
  { nume: "Hilişeu-Crişan", simplu: "Hiliseu-Crisan", comuna: "Hiliseu-Horia" },
  { nume: "Hilişeu-Horia", simplu: "Hiliseu-Horia" },
  { nume: "Hlipiceni" },
  { nume: "Horia", comuna: "Mitoc" },
  { nume: "Horlăceni", simplu: "Horlaceni", comuna: "Sendriceni" },
  { nume: "Horodiştea", simplu: "Horodistea", comuna: "Paltinis" },
  { nume: "Hrişcani", simplu: "Hriscani", comuna: "Vladeni" },
  { nume: "Hudeşti", simplu: "Hudesti" },
  { nume: "Hudum", comuna: "Curtesti" },
  { nume: "Hulub", comuna: "Dangeni" },
  { nume: "Hulubeşti", simplu: "Hulubesti", comuna: "Pomarla" },
  { nume: "Huţani", simplu: "Hutani", comuna: "Vladeni" },
  { nume: "Iacobeni", comuna: "Dangeni" },
  { nume: "Ibăneasa", simplu: "Ibaneasa", comuna: "Stiubieni" },
  { nume: "Ibăneşti", simplu: "Ibanesti" },
  { nume: "Ichimeni", comuna: "Avrameni" },
  { nume: "Icuşeni", simplu: "Icuseni", comuna: "Vorona" },
  { nume: "Iezer", comuna: "Hiliseu-Horia" },
  { nume: "Ilişeni", simplu: "Iliseni", comuna: "Santa Mare" },
  { nume: "Ionăşeni", simplu: "Ionaseni", comuna: "Trusesti" },
  { nume: "Ionăşeni", simplu: "Ionaseni", comuna: "Varfu Campului" },
  { nume: "Iorga", comuna: "Manoleasa" },
  { nume: "Ipoteşti", simplu: "Ipotesti", comuna: "Mihai Eminescu" },
  { nume: "Iureşti", simplu: "Iuresti", comuna: "Todireni" },
  { nume: "Izvoare", comuna: "Suharau" },
  { nume: "Jijia", comuna: "Albesti" },
  { nume: "Joldeşti", simplu: "Joldesti", comuna: "Vorona" },
  { nume: "Lehneşti", simplu: "Lehnesti", comuna: "Ripiceni" },
  { nume: "Leorda" },
  { nume: "Libertatea", comuna: "Calarasi" },
  { nume: "Lismăniţa", simplu: "Lismanita", comuna: "Darabani" },
  { nume: "Lişna", simplu: "Lisna", comuna: "Suharau" },
  { nume: "Livada", comuna: "Dobarceni" },
  { nume: "Liveni", comuna: "Manoleasa" },
  { nume: "Loturi Enescu", comuna: "Dorohoi" },
  { nume: "Loturi", comuna: "Manoleasa" },
  { nume: "Lozna" },
  { nume: "Lunca" },
  { nume: "Lunca", comuna: "Varfu Campului" },
  { nume: "Lupăria", simplu: "Luparia", comuna: "Prajeni" },
  { nume: "Maghera", comuna: "Vârfu Câmpului" },
  {
    nume: "Mănăstirea Doamnei",
    simplu: "Manastirea Doamnei",
    comuna: "Curtesti",
  },
  { nume: "Mânăstireni", simplu: "Manastireni", comuna: "Unteni" },
  { nume: "Mândreşti", simplu: "Mandresti", comuna: "Ungureni" },
  { nume: "Mândreşti", simplu: "Mandresti", comuna: "Vladeni" },
  { nume: "Manoleasa-Prut", comuna: "Manoleasa" },
  { nume: "Manoleasa" },
  { nume: "Manoleşti", simplu: "Manolesti", comuna: "Mihai Eminescu" },
  { nume: "Măşcăteni", simplu: "Mascateni", comuna: "Albesti" },
  { nume: "Mateieni", comuna: "Dimacheni" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Corni" },
  { nume: "Mihai Eminescu", comuna: "Gorbanesti" },
  { nume: "Mihai Viteazu", comuna: "Ungureni" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Cotusca",
  },
  { nume: "Mihăileni", simplu: "Mihaileni" },
  { nume: "Mihălăşeni", simplu: "Mihalaseni" },
  { nume: "Mileanca" },
  { nume: "Miletin", comuna: "Prajeni" },
  { nume: "Miorcani", comuna: "Radauti-Prut" },
  { nume: "Miron Costin", comuna: "Vlasinesti" },
  { nume: "Mitoc" },
  { nume: "Mitoc", comuna: "Leorda" },
  { nume: "Mlenăuţi", simplu: "Mlenauti", comuna: "Hudesti" },
  { nume: "Moara Jorii", comuna: "Hanesti" },
  { nume: "Movila Ruptă", simplu: "Movila Rupta", comuna: "Ripiceni" },
  { nume: "Movileni", comuna: "Concesti" },
  { nume: "Murguţa", simplu: "Murguta", comuna: "Dobarceni" },
  { nume: "Năstase", simplu: "Nastase", comuna: "Mihalaseni" },
  { nume: "Negreni", comuna: "Stiubieni" },
  { nume: "Negreşti", simplu: "Negresti", comuna: "Mihalaseni" },
  { nume: "Nichiteni", comuna: "Cotusca" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu", comuna: "Cotusca" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu", comuna: "Flamanzi" },
  { nume: "Nicşeni", simplu: "Nicseni" },
  { nume: "Niculcea", comuna: "Havarna" },
  { nume: "Oneaga", comuna: "Cristesti" },
  { nume: "Orăşeni-Deal", simplu: "Oraseni-Deal", comuna: "Curtesti" },
  { nume: "Orăşeni-Vale", simplu: "Oraseni-Vale", comuna: "Curtesti" },
  { nume: "Oroftiana", comuna: "Suharau" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Cosula" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Sendriceni" },
  { nume: "Păltiniş", simplu: "Paltinis" },
  { nume: "Panaitoaia", comuna: "Avrameni" },
  { nume: "Pârâu Negru", simplu: "Parau Negru", comuna: "Mihaileni" },
  { nume: "Păsăteni", simplu: "Pasateni", comuna: "Trusesti" },
  { nume: "Păun", simplu: "Paun", comuna: "Mihalaseni" },
  { nume: "Petricani", comuna: "Saveni" },
  { nume: "Pleşani", simplu: "Plesani", comuna: "Calarasi" },
  { nume: "Plevna", comuna: "Suharau" },
  { nume: "Plopenii Mari", comuna: "Ungureni" },
  { nume: "Plopenii Mici", comuna: "Ungureni" },
  { nume: "Podeni", comuna: "Corlateni" },
  { nume: "Podriga", comuna: "Draguseni" },
  { nume: "Pogorăşti", simplu: "Pogorasti", comuna: "Rauseni" },
  { nume: "Poiana", comuna: "Braesti" },
  { nume: "Poiana", comuna: "Cristinesti" },
  { nume: "Poiana", comuna: "Flamanzi" },
  { nume: "Poiana", comuna: "Vorona" },
  { nume: "Pomârla", simplu: "Pomarla" },
  { nume: "Popeni", comuna: "Braesti" },
  { nume: "Popeni", comuna: "George Enescu" },
  { nume: "Popoaia", comuna: "Ripiceni" },
  { nume: "Prăjeni", simplu: "Prajeni" },
  { nume: "Prisăcani", simplu: "Prisacani", comuna: "Flamanzi" },
  { nume: "Progresul", comuna: "Dorohoi" },
  { nume: "Pustoaia", comuna: "Vârfu Câmpului" },
  { nume: "Puţureni", simplu: "Putureni", comuna: "Cotusca" },
  { nume: "Răchiţi", simplu: "Rachiti" },
  { nume: "Racovăţ", simplu: "Racovat", comuna: "Pomarla" },
  { nume: "Rădăuţi-Prut", simplu: "Radauti-Prut" },
  { nume: "Rădeni", simplu: "Radeni", comuna: "Frumusica" },
  {
    nume: "Rânghileşti-Deal",
    simplu: "Ranghilesti-Deal",
    comuna: "Santa Mare",
  },
  { nume: "Rânghileşti", simplu: "Ranghilesti", comuna: "Santa Mare" },
  { nume: "Râşca", simplu: "Rasca", comuna: "Ripiceni" },
  { nume: "Răuşeni", simplu: "Rauseni" },
  { nume: "Recia-Verbia", comuna: "Dimacheni" },
  { nume: "Rediu", comuna: "Radauti-Prut" },
  { nume: "Rediu", comuna: "Rauseni" },
  { nume: "Ripiceni" },
  { nume: "Ripicenii Vechi", comuna: "Ripiceni" },
  { nume: "Rogojeşti", simplu: "Rogojesti", comuna: "Mihaileni" },
  { nume: "Roma" },
  { nume: "Româneşti-Vale", simplu: "Romanesti-Vale", comuna: "Romanesti" },
  { nume: "Româneşti", simplu: "Romanesti" },
  { nume: "Roşiori", simplu: "Rosiori", comuna: "Rachiti" },
  { nume: "Sadoveni", comuna: "Manoleasa" },
  { nume: "Santa Mare" },
  { nume: "Sarafineşti", simplu: "Sarafinesti", comuna: "Corni" },
  { nume: "Sarata-Basarab", comuna: "Hanesti" },
  { nume: "Sarata-Drăguşeni", simplu: "Sarata-Draguseni", comuna: "Draguseni" },
  { nume: "Sarata", comuna: "Mihalaseni" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Romanesti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Vlasinesti" },
  { nume: "Sat Nou", comuna: "Saveni" },
  { nume: "Sauceniţa", simplu: "Saucenita", comuna: "Vaculesti" },
  { nume: "Săveni", simplu: "Saveni" },
  { nume: "Schit-Orăşeni", simplu: "Schit-Oraseni", comuna: "Cristesti" },
  { nume: "Scutari", comuna: "Mileanca" },
  { nume: "Seliştea", simplu: "Selistea", comuna: "Mileanca" },
  { nume: "Şendreni", simplu: "Sendreni", comuna: "Frumusica" },
  { nume: "Şendriceni", simplu: "Sendriceni" },
  { nume: "Şerpeniţa", simplu: "Serpenita", comuna: "Manoleasa" },
  { nume: "Silişcani", simplu: "Siliscani", comuna: "Gorbanesti" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Stauceni" },
  { nume: "Slobozia Hăneşti", simplu: "Slobozia Hanesti", comuna: "Hanesti" },
  {
    nume: "Slobozia Silişcani",
    simplu: "Slobozia Siliscani",
    comuna: "Mihalaseni",
  },
  { nume: "Slobozia", comuna: "Broscauti" },
  { nume: "Slobozia", comuna: "Cordăreni" },
  { nume: "Slobozia", comuna: "Paltinis" },
  { nume: "Smârdan", simplu: "Smardan", comuna: "Suharau" },
  { nume: "Socrujeni", comuna: "Gorbanesti" },
  { nume: "Şoldăneşti", simplu: "Soldanesti", comuna: "Blindesti" },
  { nume: "Soroceni", comuna: "Unteni" },
  { nume: "Stânca", simplu: "Stanca", comuna: "George Enescu" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Stefanesti" },
  { nume: "Stânceşti", simplu: "Stancesti", comuna: "Mihai Eminescu" },
  { nume: "Stăuceni", simplu: "Stauceni" },
  { nume: "Ştefăneşti-Sat", simplu: "Stefanesti-Sat", comuna: "Stefanesti" },
  { nume: "Ştefăneşti", simplu: "Stefanesti" },
  { nume: "Ştiubieni", simplu: "Stiubieni" },
  { nume: "Stolniceni", comuna: "Rauseni" },
  { nume: "Storeşti", simplu: "Storesti", comuna: "Frumusica" },
  { nume: "Strahotin", comuna: "Dangeni" },
  { nume: "Străteni", simplu: "Strateni", comuna: "Lozna" },
  { nume: "Stroieşti", simplu: "Stroiesti", comuna: "Lunca" },
  { nume: "Suharău", simplu: "Suharau" },
  { nume: "Suliţa", simplu: "Sulita" },
  { nume: "Şupitca", simplu: "Supitca", comuna: "Cosula" },
  { nume: "Talpa", comuna: "Candesti" },
  { nume: "Tătărăşeni", simplu: "Tataraseni", comuna: "Havarna" },
  { nume: "Tăuteşti", simplu: "Tautesti", comuna: "Ungureni" },
  { nume: "Timuş", simplu: "Timus", comuna: "Avrameni" },
  { nume: "Tocileni", comuna: "Stauceni" },
  { nume: "Todireni" },
  { nume: "Truşeşti", simplu: "Trusesti" },
  { nume: "Tudor Vladimirescu", comuna: "Albesti" },
  { nume: "Tudor Vladimirescu", comuna: "Avrameni" },
  { nume: "Tudora" },
  { nume: "Ungureni" },
  { nume: "Unguroaia", comuna: "Cristesti" },
  { nume: "Unţeni", simplu: "Unteni" },
  { nume: "Văculeşti", simplu: "Vaculesti" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Braesti" },
  { nume: "Valea Grajdului", comuna: "Unteni" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Gorbanesti" },
  { nume: "Vârfu Câmpului", simplu: "Varfu Campului" },
  { nume: "Vatra", comuna: "Hudești" },
  { nume: "Vicoleni", comuna: "Ungureni" },
  { nume: "Victoria", comuna: "Hlipiceni" },
  { nume: "Victoria", comuna: "Stauceni" },
  { nume: "Viforeni", comuna: "Gorbanesti" },
  { nume: "Viişoara Mică", simplu: "Viisoara Mica", comuna: "Viisoara" },
  { nume: "Viişoara", simplu: "Viisoara" },
  { nume: "Viţcani", simplu: "Vitcani", comuna: "Candesti" },
  { nume: "Vlădeni-Deal", simplu: "Vladeni-Deal", comuna: "Frumusica" },
  { nume: "Vlădeni", simplu: "Vladeni" },
  { nume: "Vlădeni", simplu: "Vladeni", comuna: "Corlateni" },
  { nume: "Vlăsineşti", simplu: "Vlasinesti" },
  { nume: "Vorniceni" },
  { nume: "Vorona Mare", comuna: "Vorona" },
  { nume: "Vorona-Teodoru", comuna: "Vorona" },
  { nume: "Vorona" },
  { nume: "Vultureni", comuna: "Unteni" },
  { nume: "Zahoreni", comuna: "Manoleasa" },
  { nume: "Zăiceşti", simplu: "Zaicesti", comuna: "Baluseni" },
  { nume: "Zlătunoaia", simplu: "Zlatunoaia", comuna: "Lunca" },
  { nume: "Zoiţani", simplu: "Zoitani", comuna: "Avrameni" },
];
