export const bc = [
  { nume: "Agăş", simplu: "Agas" },
  { nume: "Albele", comuna: "Barsanesti" },
  { nume: "Antoheşti", simplu: "Antohesti", comuna: "Izvoru Berheciului" },
  { nume: "Apa Asău", simplu: "Apa Asau", comuna: "Asau" },
  { nume: "Ardeoani" },
  { nume: "Arini", comuna: "Gaiceana" },
  { nume: "Asău", simplu: "Asau" },
  { nume: "Bacău", simplu: "Bacau" },
  { nume: "Băcioiu", simplu: "Bacioiu", comuna: "Corbasca" },
  { nume: "Bâcleşti", simplu: "Baclesti", comuna: "Motoseni" },
  { nume: "Bahna", comuna: "Pargaresti" },
  { nume: "Băhnăşeni", simplu: "Bahnaseni", comuna: "Parjol" },
  { nume: "Băimac", simplu: "Baimac", comuna: "Izvoru Berheciului" },
  { nume: "Bălaia", simplu: "Balaia", comuna: "Filipeni" },
  { nume: "Bălăneasa", simplu: "Balaneasa", comuna: "Livezi" },
  { nume: "Bălăneşti", simplu: "Balanesti", comuna: "Dealu Morii" },
  { nume: "Bălăneşti", simplu: "Balanesti", comuna: "Podu Turcului" },
  { nume: "Bâlca", simplu: "Balca", comuna: "Cotofanesti" },
  { nume: "Balcani" },
  { nume: "Baloteşti", simplu: "Balotesti", comuna: "Stanisesti" },
  { nume: "Bălţata", simplu: "Baltata", comuna: "Nicolae Balcescu" },
  { nume: "Băluşa", simplu: "Balusa", comuna: "Secuieni" },
  { nume: "Banca", comuna: "Dealu Morii" },
  { nume: "Baraţi", simplu: "Barati", comuna: "Margineni" },
  { nume: "Bărboasa", simplu: "Barboasa", comuna: "Oncesti" },
  { nume: "Barcana", comuna: "Rachitoasa" },
  { nume: "Barna", comuna: "Parincea" },
  { nume: "Bărneşti", simplu: "Barnesti", comuna: "Parjol" },
  { nume: "Bârsăneşti", simplu: "Barsanesti" },
  { nume: "Bărtăşeşti", simplu: "Bartasesti", comuna: "Ungureni" },
  { nume: "Bârzuleşti", simplu: "Barzulesti", comuna: "Sanduleni" },
  { nume: "Băsăşti", simplu: "Basasti", comuna: "Parjol" },
  { nume: "Bazga", comuna: "Horgesti" },
  { nume: "Belciuneasa", comuna: "Stanisesti" },
  { nume: "Beleghet", comuna: "Agas" },
  { nume: "Beneşti", simplu: "Benesti", comuna: "Stanisesti" },
  { nume: "Berbinceni", comuna: "Secuieni" },
  { nume: "Bereşti-Bistriţa", simplu: "Beresti-Bistrita" },
  { nume: "Bereşti-Tazlău", simplu: "Beresti-Tazlau" },
  { nume: "Bereşti", simplu: "Beresti", comuna: "Sascut" },
  { nume: "Berzunţi", simplu: "Berzunti" },
  { nume: "Bibireşti", simplu: "Bibiresti", comuna: "Ungureni" },
  { nume: "Bijghir", comuna: "Buhoci" },
  { nume: "Blaga", comuna: "Dealu Morii" },
  { nume: "Blăgeşti", simplu: "Blagesti" },
  { nume: "Blidari", comuna: "Caiuti" },
  { nume: "Boanţa", simplu: "Boanta", comuna: "Filipesti" },
  { nume: "Boboş", simplu: "Bobos", comuna: "Dealu Morii" },
  { nume: "Bodeasa", comuna: "Dealu Morii" },
  { nume: "Bogata", comuna: "Dofteana" },
  { nume: "Bogdan Vodă", simplu: "Bogdan Voda", comuna: "Saucesti" },
  { nume: "Bogdana", comuna: "Stefan Cel Mare" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Scorteni" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Traian" },
  { nume: "Boiştea de Jos", simplu: "Boistea de Jos", comuna: "Cotofanesti" },
  { nume: "Boiştea", simplu: "Boistea", comuna: "Caiuti" },
  { nume: "Bolătău", simplu: "Bolatau", comuna: "Zemes" },
  { nume: "Bolovăniş", simplu: "Bolovanis", comuna: "Ghimes-Faget" },
  { nume: "Borşani", simplu: "Borsani", comuna: "Cotofanesti" },
  { nume: "Borzeşti", simplu: "Borzesti", comuna: "Onesti" },
  { nume: "Bosia", comuna: "Vultureni" },
  { nume: "Boşoteni", simplu: "Bosoteni", comuna: "Beresti-Tazlau" },
  { nume: "Bostăneşti", simplu: "Bostanesti", comuna: "Dealu Morii" },
  { nume: "Bota", comuna: "Ungureni" },
  { nume: "Boteşti", simplu: "Botesti", comuna: "Ungureni" },
  { nume: "Brad", comuna: "Beresti-Bistrita" },
  { nume: "Brad", comuna: "Filipeni" },
  { nume: "Brad", comuna: "Negri" },
  { nume: "Brăteşti", simplu: "Bratesti", comuna: "Barsanesti" },
  { nume: "Brătila", simplu: "Bratila", comuna: "Helegiu" },
  { nume: "Brusturoasa" },
  { nume: "Buchila", comuna: "Nicolae Balcescu" },
  { nume: "Buciumi", comuna: "Stefan Cel Mare" },
  { nume: "Bucşa", simplu: "Bucsa", comuna: "Rachitoasa" },
  { nume: "Bucşeşti", simplu: "Bucsesti", comuna: "Poduri" },
  { nume: "Buda", comuna: "Berzunti" },
  { nume: "Buda", comuna: "Blagesti" },
  { nume: "Buda", comuna: "Rachitoasa" },
  { nume: "Budeşti", simplu: "Budesti", comuna: "Plopana" },
  { nume: "Buhocel", comuna: "Buhoci" },
  { nume: "Buhoci" },
  { nume: "Buhuşi", simplu: "Buhusi" },
  { nume: "Burdusaci", comuna: "Rachitoasa" },
  { nume: "Buruieniş", simplu: "Buruienis", comuna: "Brusturoasa" },
  {
    nume: "Buruienişu de Sus",
    simplu: "Buruienisu de Sus",
    comuna: "Brusturoasa",
  },
  { nume: "Căbeşti", simplu: "Cabesti", comuna: "Podu Turcului" },
  { nume: "Cădăreşti", simplu: "Cadaresti", comuna: "Palanca" },
  { nume: "Căiuţi", simplu: "Caiuti" },
  { nume: "Calapodeşti", simplu: "Calapodesti", comuna: "Dealu Morii" },
  { nume: "Călcâi", simplu: "Calcai", comuna: "Oituz" },
  { nume: "Călineşti", simplu: "Calinesti", comuna: "Negri" },
  { nume: "Călini", simplu: "Calini", comuna: "Colonesti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Damienesti" },
  { nume: "Camenca", comuna: "Brusturoasa" },
  { nume: "Câmpeni", simplu: "Campeni", comuna: "Parjol" },
  { nume: "Capăta", simplu: "Capata", comuna: "Gura Vaii" },
  { nume: "Căpoteşti", simplu: "Capotesti", comuna: "Huruiesti" },
  { nume: "Caraclău", simplu: "Caraclau", comuna: "Barsanesti" },
  { nume: "Cârligi", simplu: "Carligi", comuna: "Filipesti" },
  { nume: "Caşin", simplu: "Casin" },
  { nume: "Căuia", simplu: "Cauia", comuna: "Dealu Morii" },
  { nume: "Cerdac", comuna: "Slanic Moldova" },
  { nume: "Cernu", comuna: "Poduri" },
  { nume: "Cetăţuia", simplu: "Cetatuia", comuna: "Strugari" },
  { nume: "Chetreni", comuna: "Motoseni" },
  { nume: "Chetriş", simplu: "Chetris", comuna: "Tamasi" },
  { nume: "Chicerea", comuna: "Motoseni" },
  { nume: "Chilia Benei", comuna: "Pancesti" },
  { nume: "Chiticeni", comuna: "Secuieni" },
  { nume: "Ciobănuş", simplu: "Ciobanus", comuna: "Asau" },
  { nume: "Cireşoaia", simplu: "Ciresoaia", comuna: "Slanic Moldova" },
  { nume: "Ciucani", comuna: "Racaciuni" },
  { nume: "Ciugheş", simplu: "Ciughes", comuna: "Palanca" },
  { nume: "Ciumaşi", simplu: "Ciumasi", comuna: "Beresti-Bistrita" },
  { nume: "Ciutureşti", simplu: "Ciuturesti", comuna: "Secuieni" },
  { nume: "Cleja" },
  { nume: "Climeşti", simplu: "Climesti", comuna: "Beresti-Bistrita" },
  { nume: "Cociu", comuna: "Motoseni" },
  { nume: "Coloneşti", simplu: "Colonesti" },
  { nume: "Coman", comuna: "Sanduleni" },
  { nume: "Comăneşti", simplu: "Comanesti" },
  { nume: "Conţeşti", simplu: "Contesti", comuna: "Sascut" },
  { nume: "Corbasca" },
  { nume: "Cornăţel", simplu: "Cornatel", comuna: "Urechesti" },
  { nume: "Cornăţelu", simplu: "Cornatelu", comuna: "Motoseni" },
  { nume: "Corneşti", simplu: "Cornesti", comuna: "Filipesti" },
  { nume: "Cornet", comuna: "Poduri" },
  { nume: "Cornii de Jos", comuna: "Tatarasti" },
  { nume: "Cornii de Sus", comuna: "Tatarasti" },
  { nume: "Coşnea", simplu: "Cosnea", comuna: "Agas" },
  { nume: "Costei", comuna: "Saucesti" },
  { nume: "Coteni", comuna: "Buhoci" },
  { nume: "Coţofăneşti", simplu: "Cotofanesti" },
  { nume: "Cotu Grosului", comuna: "Filipesti" },
  { nume: "Cotumba", comuna: "Agas" },
  { nume: "Crăieşti", simplu: "Craiesti", comuna: "Stanisesti" },
  { nume: "Crihan", comuna: "Magura" },
  { nume: "Cuchiniş", simplu: "Cuchinis", comuna: "Brusturoasa" },
  { nume: "Cucova", comuna: "Valea Seaca" },
  { nume: "Cucuieţi", simplu: "Cucuieti", comuna: "Dofteana" },
  { nume: "Cucuieţi", simplu: "Cucuieti", comuna: "Solont" },
  { nume: "Curiţa", simplu: "Curita", comuna: "Casin" },
  { nume: "Dădeşti", simplu: "Dadesti", comuna: "Vultureni" },
  { nume: "Dămieneşti", simplu: "Damienesti" },
  { nume: "Dănăila", simplu: "Danaila", comuna: "Rachitoasa" },
  { nume: "Dărmăneasca", simplu: "Darmaneasca", comuna: "Darmanesti" },
  { nume: "Dărmăneşti", simplu: "Darmanesti" },
  { nume: "Dealu Morii" },
  { nume: "Dealu Perjului", comuna: "Oncesti" },
  { nume: "Dealu-Mare", comuna: "Magura" },
  { nume: "Deleni", comuna: "Helegiu" },
  { nume: "Diaconeşti", simplu: "Diaconesti", comuna: "Agas" },
  { nume: "Dieneţ", simplu: "Dienet", comuna: "Pancesti" },
  { nume: "Dofteana" },
  { nume: "Dorneni", comuna: "Plopana" },
  { nume: "Dorneni", comuna: "Vultureni" },
  { nume: "Dorofei", comuna: "Dealu Morii" },
  { nume: "Dospineşti", simplu: "Dospinesti", comuna: "Buhoci" },
  { nume: "Drăgeşti", simplu: "Dragesti", comuna: "Damienesti" },
  { nume: "Drăgeşti", simplu: "Dragesti", comuna: "Tatarasti" },
  { nume: "Dragomir", comuna: "Berzunti" },
  { nume: "Drăgugeşti", simplu: "Dragugesti", comuna: "Helegiu" },
  { nume: "Drăguşani", simplu: "Dragusani", comuna: "Parava" },
  { nume: "Dumbrava", comuna: "Beresti-Bistrita" },
  { nume: "Dumbrava", comuna: "Gura Vaii" },
  { nume: "Dumbrava", comuna: "Rachitoasa" },
  { nume: "Enăcheşti", simplu: "Enachesti", comuna: "Beresti-Tazlau" },
  { nume: "Făget", simplu: "Faget", comuna: "Ghimes-Faget" },
  { nume: "Făgeţel", simplu: "Fagetel", comuna: "Beresti-Bistrita" },
  { nume: "Făgetu de Sus", simplu: "Fagetu de Sus", comuna: "Ghimes-Faget" },
  { nume: "Făghieni", simplu: "Faghieni", comuna: "Izvoru Berheciului" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Hemeius" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Motoseni" },
  { nume: "Faraoani" },
  { nume: "Farcaşa", simplu: "Farcasa", comuna: "Rachitoasa" },
  { nume: "Ferestrău-Oituz", simplu: "Ferestrau-Oituz", comuna: "Oituz" },
  { nume: "Fichiteşti", simplu: "Fichitesti", comuna: "Podu Turcului" },
  { nume: "Filipeni" },
  { nume: "Filipeşti", simplu: "Filipesti" },
  { nume: "Filipeşti", simplu: "Filipesti", comuna: "Bogdanesti" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Caiuti" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Huruiesti" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Scorteni" },
  { nume: "Frumoasa", comuna: "Balcani" },
  { nume: "Frumuşelu", simplu: "Frumuselu", comuna: "Glavanesti" },
  { nume: "Frunteşti", simplu: "Fruntesti", comuna: "Filipeni" },
  { nume: "Fulgeriş", simplu: "Fulgeris", comuna: "Pancesti" },
  {
    nume: "Fundătura Răchitoasa",
    simplu: "Fundatura Rachitoasa",
    comuna: "Rachitoasa",
  },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Motoseni" },
  { nume: "Fundeni", comuna: "Secuieni" },
  { nume: "Fundoaia", comuna: "Huruiesti" },
  { nume: "Fundu Răcăciuni", simplu: "Fundu Racaciuni", comuna: "Racaciuni" },
  { nume: "Fundu Tutovei", comuna: "Plopana" },
  { nume: "Fundu Văii", simplu: "Fundu Vaii", comuna: "Pancesti" },
  { nume: "Furnicari", comuna: "Tamasi" },
  { nume: "Găiceana", simplu: "Gaiceana" },
  { nume: "Galbeni", comuna: "Filipesti" },
  { nume: "Galbeni", comuna: "Nicolae Balcescu" },
  { nume: "Galeri", comuna: "Horgesti" },
  { nume: "Gârla Anei", simplu: "Garla Anei", comuna: "Ungureni" },
  { nume: "Gârleni", simplu: "Garleni" },
  { nume: "Gârlenii de Sus", simplu: "Garlenii de Sus", comuna: "Garleni" },
  { nume: "Gâşteni", simplu: "Gasteni", comuna: "Racaciuni" },
  { nume: "Găzărie", simplu: "Gazarie", comuna: "Moinesti" },
  { nume: "Gheorghe Doja", comuna: "Racaciuni" },
  { nume: "Gherdana", comuna: "Tatarasti" },
  { nume: "Ghilăveşti", simplu: "Ghilavesti", comuna: "Vultureni" },
  { nume: "Ghimeş", simplu: "Ghimes", comuna: "Ghimes-Faget" },
  { nume: "Ghionoaia", comuna: "Dealu Morii" },
  { nume: "Gioseni", comuna: "Tamasi" },
  { nume: "Giurgeni", comuna: "Tatarasti" },
  { nume: "Giurgioana", comuna: "Podu Turcului" },
  { nume: "Glăvăneşti", simplu: "Glavanesti" },
  { nume: "Glodişoarele", simplu: "Glodisoarele", comuna: "Secuieni" },
  {
    nume: "Godineştii de Jos",
    simplu: "Godinestii de Jos",
    comuna: "Vultureni",
  },
  {
    nume: "Godineştii de Sus",
    simplu: "Godinestii de Sus",
    comuna: "Vultureni",
  },
  { nume: "Goioasa", comuna: "Agas" },
  { nume: "Gorgheşti", simplu: "Gorghesti", comuna: "Stanisesti" },
  { nume: "Grădeşti", simplu: "Gradesti", comuna: "Dealu Morii" },
  { nume: "Grigoreni", comuna: "Scorteni" },
  { nume: "Gura Crăieşti", simplu: "Gura Craiesti", comuna: "Motoseni" },
  { nume: "Gura Văii", simplu: "Gura Vaii" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Racova" },
  { nume: "Gutinaş", simplu: "Gutinas", comuna: "Stefan Cel Mare" },
  { nume: "Hăghiac", simplu: "Haghiac", comuna: "Dofteana" },
  { nume: "Hăghiac", simplu: "Haghiac", comuna: "Rachitoasa" },
  { nume: "Hâineala", simplu: "Haineala", comuna: "Parjol" },
  { nume: "Hălmăcioaia", simplu: "Halmacioaia", comuna: "Racova" },
  { nume: "Hângăneşti", simplu: "Hanganesti", comuna: "Brusturoasa" },
  { nume: "Hanţa", simplu: "Hanta", comuna: "Podu Turcului" },
  { nume: "Hârja", simplu: "Harja", comuna: "Oituz" },
  { nume: "Hârleşti", simplu: "Harlesti", comuna: "Filipesti" },
  { nume: "Helegiu" },
  { nume: "Heltiu", comuna: "Caiuti" },
  { nume: "Hemeiuş", simplu: "Hemeius" },
  { nume: "Hemieni", comuna: "Parjol" },
  { nume: "Hertioana de Jos", comuna: "Traian" },
  { nume: "Hertioana-Răzeşi", simplu: "Hertioana-Razesi", comuna: "Traian" },
  { nume: "Holt", comuna: "Letea Veche" },
  { nume: "Horgeşti", simplu: "Horgesti" },
  { nume: "Huruieşti", simplu: "Huruiesti" },
  { nume: "Huţu", simplu: "Hutu", comuna: "Gaiceana" },
  { nume: "Iaz", comuna: "Strugari" },
  { nume: "Ilieşi", simplu: "Iliesi", comuna: "Racova" },
  { nume: "Iţcani", simplu: "Itcani", comuna: "Plopana" },
  { nume: "Iteşti", simplu: "Itesti", comuna: "Beresti-Bistrita" },
  { nume: "Izvoru Berheciului" },
  { nume: "Lăpoş", simplu: "Lapos", comuna: "Darmanesti" },
  { nume: "Larga", comuna: "Dofteana" },
  { nume: "Lărguţa", simplu: "Larguta", comuna: "Nicolae Balcescu" },
  { nume: "Lehancea", comuna: "Podu Turcului" },
  { nume: "Leontineşti", simplu: "Leontinesti", comuna: "Ardeoani" },
  { nume: "Lespezi", comuna: "Garleni" },
  { nume: "Letea Veche" },
  { nume: "Lichitişeni", simplu: "Lichitiseni", comuna: "Vultureni" },
  { nume: "Lilieci", comuna: "Hemeius" },
  { nume: "Lipova" },
  { nume: "Livezi" },
  { nume: "Ludaşi", simplu: "Ludasi", comuna: "Balcani" },
  { nume: "Luizi-Călugăra", simplu: "Luizi-Calugara" },
  { nume: "Lunca Asău", simplu: "Lunca Asau", comuna: "Asau" },
  { nume: "Lunca Dochiei", comuna: "Urechesti" },
  { nume: "Luncani", comuna: "Margineni" },
  { nume: "Lupeşti", simplu: "Lupesti", comuna: "Manastirea Casin" },
  { nume: "Magazia", comuna: "Rachitoasa" },
  { nume: "Măgireşti", simplu: "Magiresti" },
  { nume: "Mâgla", simplu: "Magla", comuna: "Negri" },
  { nume: "Măgura", simplu: "Magura" },
  { nume: "Mâlosu", simplu: "Malosu", comuna: "Lipova" },
  { nume: "Mănăstirea Caşin", simplu: "Manastirea Casin" },
  { nume: "Mărăscu", simplu: "Marascu", comuna: "Horgesti" },
  { nume: "Mărăşti", simplu: "Marasti", comuna: "Filipeni" },
  { nume: "Mărceşti", simplu: "Marcesti", comuna: "Caiuti" },
  { nume: "Marginea", comuna: "Buhusi" },
  { nume: "Marginea", comuna: "Oituz" },
  { nume: "Mărgineni", simplu: "Margineni" },
  { nume: "Marvila", comuna: "Corbasca" },
  { nume: "Mateieşti", simplu: "Mateiesti", comuna: "Sanduleni" },
  { nume: "Medeleni", comuna: "Vultureni" },
  { nume: "Mileştii de Jos", simplu: "Milestii de Jos", comuna: "Parincea" },
  { nume: "Mileştii de Sus", simplu: "Milestii de Sus", comuna: "Parincea" },
  { nume: "Misihăneşti", simplu: "Misihanesti", comuna: "Rosiori" },
  { nume: "Moineşti", simplu: "Moinesti" },
  { nume: "Motoc", comuna: "Pancesti" },
  { nume: "Motoceşti", simplu: "Motocesti", comuna: "Gura Vaii" },
  { nume: "Motoşeni", simplu: "Motoseni" },
  { nume: "Moviliţa", simplu: "Movilita", comuna: "Rachitoasa" },
  { nume: "Muncelu", comuna: "Glavanesti" },
  { nume: "Nadişa", simplu: "Nadisa", comuna: "Strugari" },
  { nume: "Năneşti", simplu: "Nanesti", comuna: "Parincea" },
  { nume: "Năstăseni", simplu: "Nastaseni", comuna: "Parincea" },
  { nume: "Năzărioaia", simplu: "Nazarioaia", comuna: "Vultureni" },
  { nume: "Negoieşti", simplu: "Negoiesti", comuna: "Stefan Cel Mare" },
  { nume: "Negreni", comuna: "Poduri" },
  { nume: "Negri" },
  { nume: "Neguleşti", simplu: "Negulesti", comuna: "Dealu Morii" },
  { nume: "Neguşeni", simplu: "Neguseni", comuna: "Rosiori" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu" },
  { nume: "Nicoreşti", simplu: "Nicoresti", comuna: "Pargaresti" },
  { nume: "Obârşia", simplu: "Obarsia", comuna: "Izvoru Berheciului" },
  { nume: "Ocheni", comuna: "Huruiesti" },
  { nume: "Odobeşti", simplu: "Odobesti", comuna: "Secuieni" },
  { nume: "Oituz" },
  { nume: "Onceşti", simplu: "Oncesti" },
  { nume: "Onceştii Vechi", simplu: "Oncestii Vechi", comuna: "Oncesti" },
  { nume: "Oneşti", simplu: "Onesti" },
  { nume: "Onişcani", simplu: "Oniscani", comuna: "Filipesti" },
  { nume: "Oprişeşti", simplu: "Oprisesti", comuna: "Rachitoasa" },
  { nume: "Orăşa", simplu: "Orasa", comuna: "Livezi" },
  { nume: "Orbeni" },
  { nume: "Osebiţi", simplu: "Osebiti", comuna: "Luizi-Calugara" },
  { nume: "Oţeleşti", simplu: "Otelesti", comuna: "Izvoru Berheciului" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Beresti-Bistrita" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Damienesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Filipeni" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Izvoru Berheciului" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Margineni" },
  { nume: "Păgubeni", simplu: "Pagubeni", comuna: "Darmanesti" },
  { nume: "Pajiştea", simplu: "Pajistea", comuna: "Palanca" },
  { nume: "Palanca" },
  { nume: "Păltinata", simplu: "Paltinata", comuna: "Gura Vaii" },
  { nume: "Păltiniş", simplu: "Paltinis", comuna: "Asau" },
  { nume: "Pânceşti", simplu: "Pancesti" },
  { nume: "Pănceşti", simplu: "Pancesti", comuna: "Sascut" },
  { nume: "Pârâu Boghii", simplu: "Parau Boghii", comuna: "Pargaresti" },
  { nume: "Parava" },
  { nume: "Pârgăreşti", simplu: "Pargaresti" },
  { nume: "Parincea" },
  { nume: "Pârjol", simplu: "Parjol" },
  { nume: "Pârvuleşti", simplu: "Parvulesti", comuna: "Manastirea Casin" },
  { nume: "Perchiu", comuna: "Huruiesti" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Pancesti" },
  { nume: "Petricica", comuna: "Strugari" },
  { nume: "Plopana" },
  { nume: "Plopu", comuna: "Darmanesti" },
  { nume: "Plopu", comuna: "Podu Turcului" },
  { nume: "Podei", comuna: "Comanesti" },
  { nume: "Podiş", simplu: "Podis", comuna: "Margineni" },
  { nume: "Podu Turcului" },
  { nume: "Poduri" },
  { nume: "Pogleţ", simplu: "Poglet", comuna: "Corbasca" },
  { nume: "Poiana Negustorului", comuna: "Blagesti" },
  { nume: "Poiana Sărată", simplu: "Poiana Sarata", comuna: "Oituz" },
  { nume: "Poiana", comuna: "Colonesti" },
  { nume: "Poiana", comuna: "Livezi" },
  { nume: "Poiana", comuna: "Margineni" },
  { nume: "Poiana", comuna: "Motoseni" },
  { nume: "Poiana", comuna: "Negri" },
  { nume: "Poieni", comuna: "Parincea" },
  { nume: "Poieni", comuna: "Rosiori" },
  { nume: "Poieni", comuna: "Targu Ocna" },
  { nume: "Popeni", comuna: "Caiuti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Gaiceana" },
  { nume: "Popoiu", comuna: "Palanca" },
  { nume: "Prădaiş", simplu: "Pradais", comuna: "Huruiesti" },
  { nume: "Praja", comuna: "Motoseni" },
  { nume: "Prăjeşti", simplu: "Prajesti", comuna: "Magiresti" },
  { nume: "Prăjeşti", simplu: "Prajesti", comuna: "Traian" },
  { nume: "Prajoaia", comuna: "Livezi" },
  { nume: "Pralea", comuna: "Caiuti" },
  { nume: "Preluci", comuna: "Agas" },
  { nume: "Prisaca", comuna: "Beresti-Tazlau" },
  { nume: "Prohozeşti", simplu: "Prohozesti", comuna: "Poduri" },
  { nume: "Pustiana", comuna: "Parjol" },
  { nume: "Putini", comuna: "Rachitoasa" },
  { nume: "Putredeni", comuna: "Glavanesti" },
  { nume: "Răcăciuni", simplu: "Racaciuni" },
  { nume: "Răcătău de Jos", simplu: "Racatau de Jos", comuna: "Horgesti" },
  { nume: "Răcătău-Răzeşi", simplu: "Racatau-Razesi", comuna: "Horgesti" },
  { nume: "Răcăuţi", simplu: "Racauti", comuna: "Stefan Cel Mare" },
  { nume: "Răchitiş", simplu: "Rachitis", comuna: "Ghimes-Faget" },
  { nume: "Răchitişu", simplu: "Rachitisu", comuna: "Strugari" },
  { nume: "Răchitoasa", simplu: "Rachitoasa" },
  { nume: "Racova" },
  { nume: "Răcuşana", simplu: "Racusana", comuna: "Podu Turcului" },
  { nume: "Rădeana", simplu: "Radeana", comuna: "Stefan Cel Mare" },
  { nume: "Rădoaia", simplu: "Radoaia", comuna: "Parava" },
  { nume: "Radomireşti", simplu: "Radomiresti", comuna: "Letea Veche" },
  { nume: "Răstoaca", simplu: "Rastoaca", comuna: "Racaciuni" },
  { nume: "Răzeşu", simplu: "Razesu", comuna: "Glavanesti" },
  { nume: "Recea", comuna: "Horgesti" },
  { nume: "Reprivăţ", simplu: "Reprivat", comuna: "Vultureni" },
  { nume: "Rogoaza", comuna: "Corbasca" },
  { nume: "Româneşti", simplu: "Romanesti", comuna: "Beresti-Tazlau" },
  { nume: "Roşiori", simplu: "Rosiori" },
  { nume: "Rotăria", simplu: "Rotaria", comuna: "Motoseni" },
  { nume: "Runcu", comuna: "Buhusi" },
  { nume: "Rusenii de Sus", comuna: "Plopana" },
  { nume: "Rusenii Răzeşi", simplu: "Rusenii Razesi", comuna: "Plopana" },
  { nume: "Ruşi-Ciutea", simplu: "Rusi-Ciutea", comuna: "Letea Veche" },
  { nume: "Sălătruc", simplu: "Salatruc", comuna: "Darmanesti" },
  { nume: "Sănduleni", simplu: "Sanduleni" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Nicolae Balcescu" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Solont" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Podu Turcului" },
  { nume: "Sascut-Sat", comuna: "Sascut" },
  { nume: "Sascut" },
  { nume: "Satu Nou", comuna: "Colonesti" },
  { nume: "Satu Nou", comuna: "Lipova" },
  { nume: "Satu Nou", comuna: "Oncesti" },
  { nume: "Satu Nou", comuna: "Pargaresti" },
  { nume: "Satu Nou", comuna: "Parincea" },
  { nume: "Satu Nou", comuna: "Urechesti" },
  { nume: "Săuceşti", simplu: "Saucesti" },
  { nume: "Scăriga", simplu: "Scariga", comuna: "Livezi" },
  { nume: "Scărişoara", simplu: "Scarisoara", comuna: "Corbasca" },
  { nume: "Schineni", comuna: "Sascut" },
  { nume: "Schineni", comuna: "Saucesti" },
  { nume: "Schitu Frumoasa", comuna: "Balcani" },
  { nume: "Scorţeni", simplu: "Scorteni" },
  { nume: "Scurta", comuna: "Orbeni" },
  { nume: "Scutaru", comuna: "Manastirea Casin" },
  { nume: "Seaca", comuna: "Dofteana" },
  { nume: "Secuieni" },
  { nume: "Şendreşti", simplu: "Sendresti", comuna: "Motoseni" },
  { nume: "Şerbeşti", simplu: "Serbesti", comuna: "Saucesti" },
  { nume: "Şerpeni", simplu: "Serpeni", comuna: "Scorteni" },
  { nume: "Şesuri", simplu: "Sesuri", comuna: "Magiresti" },
  { nume: "Siretu", comuna: "Letea Veche" },
  { nume: "Siretu", comuna: "Saucesti" },
  {
    nume: "Slănic-Moldova",
    simplu: "Slanic-Moldova",
    comuna: "Slanic Moldova",
  },
  { nume: "Slobozia Nouă", simplu: "Slobozia Noua", comuna: "Stanisesti" },
  { nume: "Slobozia", comuna: "Filipeni" },
  { nume: "Slobozia", comuna: "Onesti" },
  { nume: "Slobozia", comuna: "Stanisesti" },
  { nume: "Slobozia", comuna: "Urechesti" },
  { nume: "Soci", comuna: "Pancesti" },
  { nume: "Sohodol", comuna: "Magura" },
  { nume: "Sohodor", comuna: "Horgesti" },
  { nume: "Solonţ", simplu: "Solont" },
  { nume: "Somuşca", simplu: "Somusca", comuna: "Cleja" },
  { nume: "Spria", comuna: "Colonesti" },
  { nume: "Stăneşti", simplu: "Stanesti", comuna: "Magiresti" },
  { nume: "Stănişeşti", simplu: "Stanisesti" },
  { nume: "Ştefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Ştefan Vodă", simplu: "Stefan Voda", comuna: "Dofteana" },
  { nume: "Stejaru", comuna: "Scorteni" },
  { nume: "Straja", comuna: "Asau" },
  { nume: "Străminoasa", simplu: "Straminoasa", comuna: "Plopana" },
  { nume: "Strugari" },
  { nume: "Stufu", comuna: "Sanduleni" },
  { nume: "Sulţa", simplu: "Sulta", comuna: "Agas" },
  { nume: "Şurina", simplu: "Surina", comuna: "Garleni" },
  { nume: "Ţâgâra", simplu: "Tagara", comuna: "Plopana" },
  { nume: "Tamaşi", simplu: "Tamasi" },
  { nume: "Tămăşoaia", simplu: "Tamasoaia", comuna: "Cotofanesti" },
  { nume: "Tărâţa", simplu: "Tarata", comuna: "Parjol" },
  { nume: "Ţârdenii Mari", simplu: "Tardenii Mari", comuna: "Blagesti" },
  { nume: "Târgu Ocna", simplu: "Targu Ocna" },
  { nume: "Târgu Trotuş", simplu: "Targu Trotus" },
  { nume: "Tărhăuşi", simplu: "Tarhausi", comuna: "Ghimes-Faget" },
  { nume: "Tarniţa", simplu: "Tarnita", comuna: "Oncesti" },
  { nume: "Tătărăşti", simplu: "Tatarasti" },
  { nume: "Taula", comuna: "Oncesti" },
  { nume: "Tăvădăreşti", simplu: "Tavadaresti", comuna: "Dealu Morii" },
  { nume: "Teiuş", simplu: "Teius", comuna: "Parava" },
  { nume: "Temelia", comuna: "Gura Vaii" },
  { nume: "Ţepoaia", simplu: "Tepoaia", comuna: "Motoseni" },
  { nume: "Tescani", comuna: "Beresti-Tazlau" },
  { nume: "Ţigăneşti", simplu: "Tiganesti", comuna: "Vultureni" },
  { nume: "Tisa-Silvestri", comuna: "Secuieni" },
  { nume: "Tisa", comuna: "Sanduleni" },
  { nume: "Tochilea", comuna: "Rachitoasa" },
  { nume: "Tomozia", comuna: "Vultureni" },
  { nume: "Traian" },
  { nume: "Trebeş", simplu: "Trebes", comuna: "Margineni" },
  { nume: "Turluianu", comuna: "Beresti-Tazlau" },
  { nume: "Tuta", comuna: "Targu Trotus" },
  { nume: "Ungureni" },
  { nume: "Ungureni", comuna: "Tatarasti" },
  { nume: "Urecheşti", simplu: "Urechesti" },
  { nume: "Ursoaia", comuna: "Negri" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Corbasca" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Targu Ocna" },
  { nume: "Valea Arinilor", comuna: "Magiresti" },
  { nume: "Valea Boţului", simplu: "Valea Botului", comuna: "Filipeni" },
  { nume: "Valea Budului", comuna: "Margineni" },
  { nume: "Valea Caselor", comuna: "Lipova" },
  { nume: "Valea Fânaţului", simplu: "Valea Fanatului", comuna: "Secuieni" },
  { nume: "Valea Hogei", comuna: "Lipova" },
  { nume: "Valea lui Ion", comuna: "Blagesti" },
  { nume: "Valea Lupului", comuna: "Vultureni" },
  { nume: "Valea Mare", comuna: "Colonesti" },
  { nume: "Valea Mare", comuna: "Rosiori" },
  { nume: "Valea Mărului", simplu: "Valea Marului", comuna: "Lipova" },
  { nume: "Valea Merilor", comuna: "Vultureni" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Cleja" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Rosiori" },
  { nume: "Valea Moşneagului", simplu: "Valea Mosneagului", comuna: "Lipova" },
  { nume: "Valea Nacului", comuna: "Sascut" },
  { nume: "Valea Salciei", comuna: "Vultureni" },
  { nume: "Valea Seacă", simplu: "Valea Seaca" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Nicolae Balcescu" },
  { nume: "Valea Şoşii", simplu: "Valea Sosii", comuna: "Poduri" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Parincea" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Secuieni" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Stanisesti" },
  { nume: "Vermeşti", simplu: "Vermesti", comuna: "Comanesti" },
  { nume: "Verşeşti", simplu: "Versesti", comuna: "Sanduleni" },
  { nume: "Viforeni", comuna: "Ungureni" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Stefan Cel Mare" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Targu Trotus" },
  { nume: "Vladnic", comuna: "Parincea" },
  { nume: "Vrânceni", simplu: "Vranceni", comuna: "Caiuti" },
  { nume: "Vultureni" },
  { nume: "Zăpodia", simplu: "Zapodia", comuna: "Colonesti" },
  { nume: "Zăpodia", simplu: "Zapodia", comuna: "Traian" },
  { nume: "Zemeş", simplu: "Zemes" },
  { nume: "Zlătari", simplu: "Zlatari", comuna: "Ungureni" },
];
