export const bh = [
  { nume: "Abram" },
  { nume: "Abramut" },
  { nume: "Alesd" },
  { nume: "Auseu" },
  { nume: "Avram Iancu" },
  { nume: "Astileu" },
  { nume: "Balc" },
  { nume: "Batar" },
  { nume: "Beius" },
  { nume: "Biharia" },
  { nume: "Boianu Mare" },
  { nume: "Borod" },
  { nume: "Bors" },
  { nume: "Bratca" },
  { nume: "Brusturi" },
  { nume: "Budureasa" },
  { nume: "Buduslau" },
  { nume: "Bulz" },
  { nume: "Buntesti" },
  { nume: "Cefa" },
  { nume: "Ceica" },
  { nume: "Cetariu" },
  { nume: "Cherechiu" },
  { nume: "Chislaz" },
  { nume: "Ciuhoi" },
  { nume: "Ciumeghiu" },
  { nume: "Cociuba Mare" },
  { nume: "Copacel" },
  { nume: "Cristioru de Jos" },
  { nume: "Curtuiseni" },
  { nume: "Curatele" },
  { nume: "Campani" },
  { nume: "Cabesti" },
  { nume: "Capalna" },
  { nume: "Carpinet" },
  { nume: "Derna" },
  { nume: "Diosig" },
  { nume: "Dobresti" },
  { nume: "Dragesti" },
  { nume: "Draganesti" },
  { nume: "Finis" },
  { nume: "Gepiu" },
  { nume: "Girisu de Cris" },
  { nume: "Hidiselu de Sus" },
  { nume: "Holod" },
  { nume: "Husasau de Tinca" },
  { nume: "Ineu" },
  { nume: "Lazuri de Beius" },
  { nume: "Lugasu de Jos" },
  { nume: "Lunca" },
  { nume: "Lazareni" },
  { nume: "Marghita" },
  { nume: "Madaras" },
  { nume: "Magesti" },
  { nume: "Nojorid" },
  { nume: "Nucet" },
  { nume: "Olcea" },
  { nume: "Oradea" },
  { nume: "Osorhei" },
  { nume: "Paleu" },
  { nume: "Pietroasa" },
  { nume: "Pocola" },
  { nume: "Pomezeu" },
  { nume: "Popesti" },
  { nume: "Remetea" },
  { nume: "Rieni" },
  { nume: "Rosia" },
  { nume: "Rosiori" },
  { nume: "Rabagani" },
  { nume: "Salonta" },
  { nume: "Spinus" },
  { nume: "Suplacu de Barcau" },
  { nume: "Sambata" },
  { nume: "Sanmartin" },
  { nume: "Sannicolau Roman" },
  { nume: "Santandrei" },
  { nume: "Sarbi" },
  { nume: "Sacueni" },
  { nume: "Sacadat" },
  { nume: "Salacea" },
  { nume: "Salard" },
  { nume: "Tarcea" },
  { nume: "Tileagd" },
  { nume: "Tinca" },
  { nume: "Tulca" },
  { nume: "Tamaseu" },
  { nume: "Tarcaia" },
  { nume: "Tauteu" },
  { nume: "Uileacu de Beius" },
  { nume: "Vadu Crisului" },
  { nume: "Valea lui Mihai" },
  { nume: "Vascau" },
  { nume: "Viisoara" },
  { nume: "Varciorog" },
  { nume: "Simian" },
  { nume: "Sinteu" },
  { nume: "Soimi" },
  { nume: "Stei" },
  { nume: "Suncuius" },
  { nume: "Tetchea" },
  { nume: "Cohani", comuna: "Abram" },
  { nume: "Dijir", comuna: "Abram" },
  { nume: "Iteu", comuna: "Abram" },
  { nume: "Iteu Nou", comuna: "Abram" },
  { nume: "Margine", comuna: "Abram" },
  { nume: "Satu Barba", comuna: "Abram" },
  { nume: "Suiug", comuna: "Abram" },
  { nume: "Crestur", comuna: "Abramut" },
  { nume: "Fancica", comuna: "Abramut" },
  { nume: "Petreu", comuna: "Abramut" },
  { nume: "Pestis", comuna: "Alesd" },
  { nume: "Padurea Neagra", comuna: "Alesd" },
  { nume: "Tinaud", comuna: "Alesd" },
  { nume: "Chistag", comuna: "Astileu" },
  { nume: "Calatea", comuna: "Astileu" },
  { nume: "Pestere", comuna: "Astileu" },
  { nume: "Cacuciu Vechi", comuna: "Auseu" },
  { nume: "Codrisoru", comuna: "Auseu" },
  { nume: "Gheghie", comuna: "Auseu" },
  { nume: "Grosi", comuna: "Auseu" },
  { nume: "Luncsoara", comuna: "Auseu" },
  { nume: "Ant", comuna: "Avram Iancu" },
  { nume: "Tamasda", comuna: "Avram Iancu" },
  { nume: "Almasu Mare", comuna: "Balc" },
  { nume: "Almasu Mic", comuna: "Balc" },
  { nume: "Ghida", comuna: "Balc" },
  { nume: "Saldabagiu de Barcau", comuna: "Balc" },
  { nume: "Arpasel", comuna: "Batar" },
  { nume: "Talpos", comuna: "Batar" },
  { nume: "Taut", comuna: "Batar" },
  { nume: "Delani", comuna: "Beius" },
  { nume: "Cauaceu", comuna: "Biharia" },
  { nume: "Corboaia", comuna: "Boianu Mare" },
  { nume: "Huta", comuna: "Boianu Mare" },
  { nume: "Pagaia", comuna: "Boianu Mare" },
  { nume: "Rugea", comuna: "Boianu Mare" },
  { nume: "Borozel", comuna: "Borod" },
  { nume: "Cetea", comuna: "Borod" },
  { nume: "Cornitel", comuna: "Borod" },
  { nume: "Valea Mare de Cris", comuna: "Borod" },
  { nume: "Serani", comuna: "Borod" },
  { nume: "Santaul Mare", comuna: "Bors" },
  { nume: "Santaul Mic", comuna: "Bors" },
  { nume: "Santion", comuna: "Bors" },
  { nume: "Beznea", comuna: "Bratca" },
  { nume: "Damis", comuna: "Bratca" },
  { nume: "Lorau", comuna: "Bratca" },
  { nume: "Ponoara", comuna: "Bratca" },
  { nume: "Valea Crisului", comuna: "Bratca" },
  { nume: "Cuiesd", comuna: "Brusturi" },
  { nume: "Loranta", comuna: "Brusturi" },
  { nume: "Orvisele", comuna: "Brusturi" },
  { nume: "Picleu", comuna: "Brusturi" },
  { nume: "Paulesti", comuna: "Brusturi" },
  { nume: "Varasau", comuna: "Brusturi" },
  { nume: "Tiganestii de Cris", comuna: "Brusturi" },
  { nume: "Burda", comuna: "Budureasa" },
  { nume: "Saca", comuna: "Budureasa" },
  { nume: "Saliste de Beius", comuna: "Budureasa" },
  { nume: "Teleac", comuna: "Budureasa" },
  { nume: "Albis", comuna: "Buduslau" },
  { nume: "Munteni", comuna: "Bulz" },
  { nume: "Remeti", comuna: "Bulz" },
  { nume: "Bradet", comuna: "Buntesti" },
  { nume: "Dumbravani", comuna: "Buntesti" },
  { nume: "Ferice", comuna: "Buntesti" },
  { nume: "Lelesti", comuna: "Buntesti" },
  { nume: "Poienii de Jos", comuna: "Buntesti" },
  { nume: "Poienii de Sus", comuna: "Buntesti" },
  { nume: "Stancesti", comuna: "Buntesti" },
  { nume: "Saud", comuna: "Buntesti" },
  { nume: "Goila", comuna: "Cabesti" },
  { nume: "Gurbesti", comuna: "Cabesti" },
  { nume: "Josani", comuna: "Cabesti" },
  { nume: "Sohodol", comuna: "Cabesti" },
  { nume: "Fanate", comuna: "Campani" },
  { nume: "Harsesti", comuna: "Campani" },
  { nume: "Sighistel", comuna: "Campani" },
  { nume: "Valea de Sus", comuna: "Campani" },
  { nume: "Ginta", comuna: "Capalna" },
  { nume: "Rohani", comuna: "Capalna" },
  { nume: "Suplacu de Tinca", comuna: "Capalna" },
  { nume: "Saldabagiu Mic", comuna: "Capalna" },
  { nume: "Calugari", comuna: "Carpinet" },
  { nume: "Izbuc", comuna: "Carpinet" },
  { nume: "Leheceni", comuna: "Carpinet" },
  { nume: "Ateas", comuna: "Cefa" },
  { nume: "Inand", comuna: "Cefa" },
  { nume: "Bucium", comuna: "Ceica" },
  { nume: "Ceisoara", comuna: "Ceica" },
  { nume: "Corbesti", comuna: "Ceica" },
  { nume: "Cotiglet", comuna: "Ceica" },
  { nume: "Dusesti", comuna: "Ceica" },
  { nume: "Incesti", comuna: "Ceica" },
  { nume: "Tautelec", comuna: "Cetariu" },
  { nume: "Sisterea", comuna: "Cetariu" },
  { nume: "Susturogi", comuna: "Cetariu" },
  { nume: "Chesereu", comuna: "Cherechiu" },
  { nume: "Targusor", comuna: "Cherechiu" },
  { nume: "Chiraleu", comuna: "Chislaz" },
  { nume: "Haucesti", comuna: "Chislaz" },
  { nume: "Misca", comuna: "Chislaz" },
  { nume: "Poclusa de Barcau", comuna: "Chislaz" },
  { nume: "Sanlazar", comuna: "Chislaz" },
  { nume: "Sarsig", comuna: "Chislaz" },
  { nume: "Cenalos", comuna: "Ciuhoi" },
  { nume: "Sfarnas", comuna: "Ciuhoi" },
  { nume: "Saniob", comuna: "Ciuhoi" },
  { nume: "Boiu", comuna: "Ciumeghiu" },
  { nume: "Ghiorac", comuna: "Ciumeghiu" },
  { nume: "Chesa", comuna: "Cociuba Mare" },
  { nume: "Carasau", comuna: "Cociuba Mare" },
  { nume: "Petid", comuna: "Cociuba Mare" },
  { nume: "Bucuroaia", comuna: "Copacel" },
  { nume: "Chijic", comuna: "Copacel" },
  { nume: "Poiana Tasad", comuna: "Copacel" },
  { nume: "Surduc", comuna: "Copacel" },
  { nume: "Sarand", comuna: "Copacel" },
  { nume: "Balc", comuna: "Cristioru De Jos" },
  { nume: "Cristioru de Sus", comuna: "Cristioru De Jos" },
  { nume: "Poiana", comuna: "Cristioru De Jos" },
  { nume: "Saliste de Vascau", comuna: "Cristioru De Jos" },
  { nume: "Beiusele", comuna: "Curatele" },
  { nume: "Cresuia", comuna: "Curatele" },
  { nume: "Nimaiesti", comuna: "Curatele" },
  { nume: "Pocioveliste", comuna: "Curatele" },
  { nume: "Vasad", comuna: "Curtuiseni" },
  { nume: "Dernisoara", comuna: "Derna" },
  { nume: "Sacalasau", comuna: "Derna" },
  { nume: "Sacalasau Nou", comuna: "Derna" },
  { nume: "Tria", comuna: "Derna" },
  { nume: "Ianca", comuna: "Diosig" },
  { nume: "Cornisesti", comuna: "Dobresti" },
  { nume: "Crancesti", comuna: "Dobresti" },
  { nume: "Hidisel", comuna: "Dobresti" },
  { nume: "Luncasprie", comuna: "Dobresti" },
  { nume: "Racas", comuna: "Dobresti" },
  { nume: "Topa de Jos", comuna: "Dobresti" },
  { nume: "Topa de Sus", comuna: "Dobresti" },
  { nume: "Belejeni", comuna: "Draganesti" },
  { nume: "Gradinari", comuna: "Draganesti" },
  { nume: "Livada Beiusului", comuna: "Draganesti" },
  { nume: "Mizies", comuna: "Draganesti" },
  { nume: "Pantasesti", comuna: "Draganesti" },
  { nume: "Talpe", comuna: "Draganesti" },
  { nume: "Sebis", comuna: "Draganesti" },
  { nume: "Tiganestii de Beius", comuna: "Draganesti" },
  { nume: "Dicanesti", comuna: "Dragesti" },
  { nume: "Stracos", comuna: "Dragesti" },
  { nume: "Topesti", comuna: "Dragesti" },
  { nume: "Tasad", comuna: "Dragesti" },
  { nume: "Pacalesti", comuna: "Drăgănești" },
  { nume: "Brusturi", comuna: "Finis" },
  { nume: "Fizis", comuna: "Finis" },
  { nume: "Ioanis", comuna: "Finis" },
  { nume: "Suncuis", comuna: "Finis" },
  { nume: "Bicaci", comuna: "Gepiu" },
  { nume: "Cheresig", comuna: "Girisu De Cris" },
  { nume: "Toboliu", comuna: "Girisu De Cris" },
  { nume: "Tarian", comuna: "Girisu De Cris" },
  { nume: "Hidiselu de Jos", comuna: "Hidiselu De Sus" },
  { nume: "Mierlau", comuna: "Hidiselu De Sus" },
  { nume: "Santelec", comuna: "Hidiselu De Sus" },
  { nume: "Sumugiu", comuna: "Hidiselu De Sus" },
  { nume: "Dumbrava", comuna: "Holod" },
  { nume: "Dumbravita", comuna: "Holod" },
  { nume: "Forosig", comuna: "Holod" },
  { nume: "Hodis", comuna: "Holod" },
  { nume: "Lupoaia", comuna: "Holod" },
  { nume: "Valea Mare de Codru", comuna: "Holod" },
  { nume: "Vintere", comuna: "Holod" },
  { nume: "Fonau", comuna: "Husasau De Tinca" },
  { nume: "Miersig", comuna: "Husasau De Tinca" },
  { nume: "Osand", comuna: "Husasau De Tinca" },
  { nume: "Sititelec", comuna: "Husasau De Tinca" },
  { nume: "Botean", comuna: "Ineu" },
  { nume: "Husasau de Cris", comuna: "Ineu" },
  { nume: "Bicacel", comuna: "Lazareni" },
  { nume: "Calea Mare", comuna: "Lazareni" },
  { nume: "Carandeni", comuna: "Lazareni" },
  { nume: "Caranzel", comuna: "Lazareni" },
  { nume: "Gepis", comuna: "Lazareni" },
  { nume: "Gruilung", comuna: "Lazareni" },
  { nume: "Miheleu", comuna: "Lazareni" },
  { nume: "Baleni", comuna: "Lazuri De Beius" },
  { nume: "Cusuius", comuna: "Lazuri De Beius" },
  { nume: "Hinchiris", comuna: "Lazuri De Beius" },
  { nume: "Lugasu de Sus", comuna: "Lugasu De Jos" },
  { nume: "Urvind", comuna: "Lugasu De Jos" },
  { nume: "Briheni", comuna: "Lunca" },
  { nume: "Hotarel", comuna: "Lunca" },
  { nume: "Seghiste", comuna: "Lunca" },
  { nume: "Sarbesti", comuna: "Lunca" },
  { nume: "Sustiu", comuna: "Lunca" },
  { nume: "Homorog", comuna: "Madaras" },
  { nume: "Ianosda", comuna: "Madaras" },
  { nume: "Martihaz", comuna: "Madaras" },
  { nume: "Butani", comuna: "Magesti" },
  { nume: "Cacuciu Nou", comuna: "Magesti" },
  { nume: "Dobricionesti", comuna: "Magesti" },
  { nume: "Galaseni", comuna: "Magesti" },
  { nume: "Josani", comuna: "Magesti" },
  { nume: "Ortiteag", comuna: "Magesti" },
  { nume: "Chet", comuna: "Marghita" },
  { nume: "Ghenetea", comuna: "Marghita" },
  { nume: "Apateu", comuna: "Nojorid" },
  { nume: "Chisirid", comuna: "Nojorid" },
  { nume: "Les", comuna: "Nojorid" },
  { nume: "Livada de Bihor", comuna: "Nojorid" },
  { nume: "Pausa", comuna: "Nojorid" },
  { nume: "Sauaieu", comuna: "Nojorid" },
  { nume: "Baita", comuna: "Nucet" },
  { nume: "Baita-Plai", comuna: "Nucet" },
  { nume: "Calacea", comuna: "Olcea" },
  { nume: "Hodisel", comuna: "Olcea" },
  { nume: "Ucuris", comuna: "Olcea" },
  { nume: "Alparea", comuna: "Osorhei" },
  { nume: "Cheriu", comuna: "Osorhei" },
  { nume: "Felcheriu", comuna: "Osorhei" },
  { nume: "Fughiu", comuna: "Osorhei" },
  { nume: "Saldabagiu de Munte", comuna: "Paleu" },
  { nume: "Uileacu de Munte", comuna: "Paleu" },
  { nume: "Chiscau", comuna: "Pietroasa" },
  { nume: "Cociuba Mica", comuna: "Pietroasa" },
  { nume: "Giulesti", comuna: "Pietroasa" },
  { nume: "Gurani", comuna: "Pietroasa" },
  { nume: "Motesti", comuna: "Pietroasa" },
  { nume: "Magura", comuna: "Pietroasa" },
  { nume: "Feneris", comuna: "Pocola" },
  { nume: "Petrani", comuna: "Pocola" },
  { nume: "Poietari", comuna: "Pocola" },
  { nume: "Sanmartin de Beius", comuna: "Pocola" },
  { nume: "Cosdeni", comuna: "Pomezeu" },
  { nume: "Campani de Pomezeu", comuna: "Pomezeu" },
  { nume: "Hidis", comuna: "Pomezeu" },
  { nume: "Lacu Sarat", comuna: "Pomezeu" },
  { nume: "Sitani", comuna: "Pomezeu" },
  { nume: "Spinus de Pomezeu", comuna: "Pomezeu" },
  { nume: "Valani de Pomezeu", comuna: "Pomezeu" },
  { nume: "Bistra", comuna: "Popesti" },
  { nume: "Budoi", comuna: "Popesti" },
  { nume: "Cuzap", comuna: "Popesti" },
  { nume: "Varviz", comuna: "Popesti" },
  { nume: "Voivozi", comuna: "Popesti" },
  { nume: "Varzari", comuna: "Popesti" },
  { nume: "Albesti", comuna: "Rabagani" },
  { nume: "Bratesti", comuna: "Rabagani" },
  { nume: "Saliste de Pomezeu", comuna: "Rabagani" },
  { nume: "Saucani", comuna: "Rabagani" },
  { nume: "Varaseni", comuna: "Rabagani" },
  { nume: "Dragoteni", comuna: "Remetea" },
  { nume: "Meziad", comuna: "Remetea" },
  { nume: "Petreasa", comuna: "Remetea" },
  { nume: "Soimus", comuna: "Remetea" },
  { nume: "Cucuceni", comuna: "Rieni" },
  { nume: "Ghighiseni", comuna: "Rieni" },
  { nume: "Petrileni", comuna: "Rieni" },
  { nume: "Sudrigiu", comuna: "Rieni" },
  { nume: "Valea de Jos", comuna: "Rieni" },
  { nume: "Lazuri", comuna: "Rosia" },
  { nume: "Mihai Bravu", comuna: "Rosiori" },
  { nume: "Vaida", comuna: "Rosiori" },
  { nume: "Borsa", comuna: "Sacadat" },
  { nume: "Sabolciu", comuna: "Sacadat" },
  { nume: "Cadea", comuna: "Sacueni" },
  { nume: "Ciocaia", comuna: "Sacueni" },
  { nume: "Cubulcut", comuna: "Sacueni" },
  { nume: "Olosig", comuna: "Sacueni" },
  { nume: "Sannicolau de Munte", comuna: "Sacueni" },
  { nume: "Otomani", comuna: "Salacea" },
  { nume: "Hodos", comuna: "Salard" },
  { nume: "Santimreu", comuna: "Salard" },
  { nume: "Copaceni", comuna: "Sambata" },
  { nume: "Ogesti", comuna: "Sambata" },
  { nume: "Rogoz", comuna: "Sambata" },
  { nume: "Rotaresti", comuna: "Sambata" },
  { nume: "Zavoiu", comuna: "Sambata" },
  { nume: "Betfia", comuna: "Sanmartin" },
  { nume: "Baile Felix", comuna: "Sanmartin" },
  { nume: "Cihei", comuna: "Sanmartin" },
  { nume: "Cordau", comuna: "Sanmartin" },
  { nume: "Haieu", comuna: "Sanmartin" },
  { nume: "Rontau", comuna: "Sanmartin" },
  { nume: "Berechiu", comuna: "Sannicolau Roman" },
  { nume: "Roit", comuna: "Sannicolau Roman" },
  { nume: "Palota", comuna: "Santandrei" },
  { nume: "Almasu Mic", comuna: "Sarbi" },
  { nume: "Burzuc", comuna: "Sarbi" },
  { nume: "Chioag", comuna: "Sarbi" },
  { nume: "Fegernic", comuna: "Sarbi" },
  { nume: "Fegernicu Nou", comuna: "Sarbi" },
  { nume: "Sarcau", comuna: "Sarbi" },
  { nume: "Voivozi", comuna: "Simian" },
  { nume: "Silindru", comuna: "Simian" },
  { nume: "Huta Voivozi", comuna: "Sinteu" },
  { nume: "Socet", comuna: "Sinteu" },
  { nume: "Valea Tarnei", comuna: "Sinteu" },
  { nume: "Borz", comuna: "Soimi" },
  { nume: "Codru", comuna: "Soimi" },
  { nume: "Dumbravita de Codru", comuna: "Soimi" },
  { nume: "Poclusa de Beius", comuna: "Soimi" },
  { nume: "Sannicolau de Beius", comuna: "Soimi" },
  { nume: "Ursad", comuna: "Soimi" },
  { nume: "Urvis de Beius", comuna: "Soimi" },
  { nume: "Ciulesti", comuna: "Spinus" },
  { nume: "Gurbesti", comuna: "Spinus" },
  { nume: "Nadar", comuna: "Spinus" },
  { nume: "Saliste", comuna: "Spinus" },
  { nume: "Balnaca", comuna: "Suncuius" },
  { nume: "Balnaca-Grosi", comuna: "Suncuius" },
  { nume: "Zece Hotare", comuna: "Suncuius" },
  { nume: "Borumlaca", comuna: "Suplacu De Barcau" },
  { nume: "Dolea", comuna: "Suplacu De Barcau" },
  { nume: "Foglas", comuna: "Suplacu De Barcau" },
  { nume: "Valea Cerului", comuna: "Suplacu De Barcau" },
  { nume: "Valcelele", comuna: "Suplacu De Barcau" },
  { nume: "Niuved", comuna: "Tamaseu" },
  { nume: "Parhida", comuna: "Tamaseu" },
  { nume: "Satu Nou", comuna: "Tamaseu" },
  { nume: "Mierag", comuna: "Tarcaia" },
  { nume: "Totoreni", comuna: "Tarcaia" },
  { nume: "Tarcaita", comuna: "Tarcaia" },
  { nume: "Adoni", comuna: "Tarcea" },
  { nume: "Galospetreu", comuna: "Tarcea" },
  { nume: "Bogei", comuna: "Tauteu" },
  { nume: "Chiribis", comuna: "Tauteu" },
  { nume: "Ciutelec", comuna: "Tauteu" },
  { nume: "Poiana", comuna: "Tauteu" },
  { nume: "Hotar", comuna: "Tetchea" },
  { nume: "Subpiatra", comuna: "Tetchea" },
  { nume: "Telechiu", comuna: "Tetchea" },
  { nume: "Balaia", comuna: "Tileagd" },
  { nume: "Calatani", comuna: "Tileagd" },
  { nume: "Posoloaca", comuna: "Tileagd" },
  { nume: "Tilecus", comuna: "Tileagd" },
  { nume: "Uileacu de Cris", comuna: "Tileagd" },
  { nume: "Belfir", comuna: "Tinca" },
  { nume: "Girisu Negru", comuna: "Tinca" },
  { nume: "Gurbediu", comuna: "Tinca" },
  { nume: "Rapa", comuna: "Tinca" },
  { nume: "Cauasd", comuna: "Tulca" },
  { nume: "Forau", comuna: "Uileacu De Beius" },
  { nume: "Prisaca", comuna: "Uileacu De Beius" },
  { nume: "Valanii de Beius", comuna: "Uileacu De Beius" },
  { nume: "Birtin", comuna: "Vadu Crisului" },
  { nume: "Tomnatic", comuna: "Vadu Crisului" },
  { nume: "Topa de Cris", comuna: "Vadu Crisului" },
  { nume: "Fasca", comuna: "Varciorog" },
  { nume: "Surducel", comuna: "Varciorog" },
  { nume: "Serghis", comuna: "Varciorog" },
  { nume: "Colesti", comuna: "Vascau" },
  { nume: "Camp", comuna: "Vascau" },
  { nume: "Camp-Moti", comuna: "Vascau" },
  { nume: "Varzarii de Jos", comuna: "Vascau" },
  { nume: "Varzarii de Sus", comuna: "Vascau" },
  { nume: "Izvoarele", comuna: "Viisoara" },
  { nume: "Padureni", comuna: "Viisoara" },
  { nume: "Reghea", comuna: "Viisoara" },
];
