export const bn = [
  { nume: "Beclean" },
  { nume: "Bistrita" },
  { nume: "Bistrita Bargaului" },
  { nume: "Branistea" },
  { nume: "Budacu de Jos" },
  { nume: "Budesti" },
  { nume: "Chiochis" },
  { nume: "Chiuza" },
  { nume: "Ciceu-Giurgesti" },
  { nume: "Cosbuc" },
  { nume: "Caianu Mic" },
  { nume: "Dumitra" },
  { nume: "Dumitrita" },
  { nume: "Feldru" },
  { nume: "Galatii Bistritei" },
  { nume: "Ilva Mare" },
  { nume: "Ilva Mica" },
  { nume: "Josenii Bargaului" },
  { nume: "Lechinta" },
  { nume: "Lesu" },
  { nume: "Livezile" },
  { nume: "Lunca Ilvei" },
  { nume: "Maieru" },
  { nume: "Matei" },
  { nume: "Micestii de Campie" },
  { nume: "Milas" },
  { nume: "Monor" },
  { nume: "Magura Ilvei" },
  { nume: "Mariselu" },
  { nume: "Negrilesti" },
  { nume: "Nuseni" },
  { nume: "Nasaud" },
  { nume: "Parva" },
  { nume: "Poiana Ilvei" },
  { nume: "Prundu Bargaului" },
  { nume: "Rebra" },
  { nume: "Rebrisoara" },
  { nume: "Rodna" },
  { nume: "Romuli" },
  { nume: "Salva" },
  { nume: "Spermezeu" },
  { nume: "Sangeorz-Bai" },
  { nume: "Teaca" },
  { nume: "Telciu" },
  { nume: "Tiha Bargaului" },
  { nume: "Tarlisua" },
  { nume: "Uriu" },
  { nume: "Urmenis" },
  { nume: "Zagra" },
  { nume: "Sant" },
  { nume: "Sieu" },
  { nume: "Sieu-Magherus" },
  { nume: "Sieu-Odorhei" },
  { nume: "Sieut" },
  { nume: "Sintereag" },
  { nume: "Coldau", comuna: "Beclean" },
  { nume: "Figa", comuna: "Beclean" },
  { nume: "Rusu de Jos", comuna: "Beclean" },
  { nume: "Ghinda", comuna: "Bistrita" },
  { nume: "Sigmir", comuna: "Bistrita" },
  { nume: "Slatinita", comuna: "Bistrita" },
  { nume: "Sarata", comuna: "Bistrita" },
  { nume: "Unirea", comuna: "Bistrita" },
  { nume: "Viisoara", comuna: "Bistrita" },
  { nume: "Colibita", comuna: "Bistrita Bargaului" },
  { nume: "Ciresoaia", comuna: "Branistea" },
  { nume: "Malut", comuna: "Branistea" },
  { nume: "Budus", comuna: "Budacu De Jos" },
  { nume: "Jelna", comuna: "Budacu De Jos" },
  { nume: "Monariu", comuna: "Budacu De Jos" },
  { nume: "Simionesti", comuna: "Budacu De Jos" },
  { nume: "Budesti-Fanate", comuna: "Budesti" },
  { nume: "Tagu", comuna: "Budesti" },
  { nume: "Tagsoru", comuna: "Budesti" },
  { nume: "Ciceu-Poieni", comuna: "Caianu Mic" },
  { nume: "Caianu Mare", comuna: "Caianu Mic" },
  { nume: "Dobric", comuna: "Caianu Mic" },
  { nume: "Dobricel", comuna: "Caianu Mic" },
  { nume: "Dumbravita", comuna: "Caianu Mic" },
  { nume: "Orheiu Bistritei", comuna: "Cetate" },
  { nume: "Petris", comuna: "Cetate" },
  { nume: "Satu Nou", comuna: "Cetate" },
  { nume: "Apatiu", comuna: "Chiochis" },
  { nume: "Bozies", comuna: "Chiochis" },
  { nume: "Buza Catun", comuna: "Chiochis" },
  { nume: "Chetiu", comuna: "Chiochis" },
  { nume: "Jimbor", comuna: "Chiochis" },
  { nume: "Manic", comuna: "Chiochis" },
  { nume: "Strugureni", comuna: "Chiochis" },
  { nume: "Sannicoara", comuna: "Chiochis" },
  { nume: "Tentea", comuna: "Chiochis" },
  { nume: "Mires", comuna: "Chiuza" },
  { nume: "Piatra", comuna: "Chiuza" },
  { nume: "Sasarm", comuna: "Chiuza" },
  { nume: "Dumbraveni", comuna: "Ciceu-Giurgesti" },
  { nume: "Bichigiu", comuna: "Cosbuc" },
  { nume: "Cepari", comuna: "Dumitra" },
  { nume: "Tarpiu", comuna: "Dumitra" },
  { nume: "Budacu de Sus", comuna: "Dumitrita" },
  { nume: "Ragla", comuna: "Dumitrita" },
  { nume: "Nepos", comuna: "Feldru" },
  { nume: "Albestii Bistritei", comuna: "Galatii Bistritei" },
  { nume: "Dipsa", comuna: "Galatii Bistritei" },
  { nume: "Herina", comuna: "Galatii Bistritei" },
  { nume: "Tonciu", comuna: "Galatii Bistritei" },
  { nume: "Ivaneasa", comuna: "Ilva Mare" },
  { nume: "Mijlocenii Bargaului", comuna: "Josenii Bargaului" },
  { nume: "Rusu Bargaului", comuna: "Josenii Bargaului" },
  { nume: "Stramba", comuna: "Josenii Bargaului" },
  { nume: "Bungard", comuna: "Lechinta" },
  { nume: "Chirales", comuna: "Lechinta" },
  { nume: "Sangeorzu Nou", comuna: "Lechinta" },
  { nume: "Saniacob", comuna: "Lechinta" },
  { nume: "Vermes", comuna: "Lechinta" },
  { nume: "Tigau", comuna: "Lechinta" },
  { nume: "Lunca Lesului", comuna: "Lesu" },
  { nume: "Cusma", comuna: "Livezile" },
  { nume: "Dorolea", comuna: "Livezile" },
  { nume: "Dumbrava", comuna: "Livezile" },
  { nume: "Valea Poenii", comuna: "Livezile" },
  { nume: "Arsita", comuna: "Magura Ilvei" },
  { nume: "Anies", comuna: "Maieru" },
  { nume: "Barla", comuna: "Mariselu" },
  { nume: "Domnesti", comuna: "Mariselu" },
  { nume: "Jeica", comuna: "Mariselu" },
  { nume: "Magurele", comuna: "Mariselu" },
  { nume: "Neteni", comuna: "Mariselu" },
  { nume: "Santioana", comuna: "Mariselu" },
  { nume: "Bidiu", comuna: "Matei" },
  { nume: "Corvinesti", comuna: "Matei" },
  { nume: "Enciu", comuna: "Matei" },
  { nume: "Fantanele", comuna: "Matei" },
  { nume: "Morut", comuna: "Matei" },
  { nume: "Fantanita", comuna: "Micestii De Campie" },
  { nume: "Visuia", comuna: "Micestii De Campie" },
  { nume: "Comlod", comuna: "Milas" },
  { nume: "Dupa Deal", comuna: "Milas" },
  { nume: "Ghemes", comuna: "Milas" },
  { nume: "Hirean", comuna: "Milas" },
  { nume: "Orosfaia", comuna: "Milas" },
  { nume: "Gledin", comuna: "Monor" },
  { nume: "Liviu Rebreanu", comuna: "Nasaud" },
  { nume: "Lusca", comuna: "Nasaud" },
  { nume: "Breaza", comuna: "Negrilesti" },
  { nume: "Purcarete", comuna: "Negrilesti" },
  { nume: "Floresti", comuna: "Nimigea" },
  { nume: "Mintiu", comuna: "Nimigea" },
  { nume: "Mititei", comuna: "Nimigea" },
  { nume: "Mocod", comuna: "Nimigea" },
  { nume: "Mogoseni", comuna: "Nimigea" },
  { nume: "Nimigea de Jos", comuna: "Nimigea" },
  { nume: "Nimigea de Sus", comuna: "Nimigea" },
  { nume: "Taure", comuna: "Nimigea" },
  { nume: "Beudiu", comuna: "Nuseni" },
  { nume: "Dumbrava", comuna: "Nuseni" },
  { nume: "Feleac", comuna: "Nuseni" },
  { nume: "Malin", comuna: "Nuseni" },
  { nume: "Rusu de Sus", comuna: "Nuseni" },
  { nume: "Vita", comuna: "Nuseni" },
  { nume: "Bata", comuna: "Petru Rares" },
  { nume: "Ciceu-Corabia", comuna: "Petru Rares" },
  { nume: "Ciceu-Mihaiesti", comuna: "Petru Rares" },
  { nume: "Lelesti", comuna: "Petru Rares" },
  { nume: "Reteag", comuna: "Petru Rares" },
  { nume: "Susenii Bargaului", comuna: "Prundu Bargaului" },
  { nume: "Gersa I", comuna: "Rebrisoara" },
  { nume: "Gersa Ii", comuna: "Rebrisoara" },
  { nume: "Poderei", comuna: "Rebrisoara" },
  { nume: "Valea Vinului", comuna: "Rodna" },
  { nume: "Dealu Stefanitei", comuna: "Romuli" },
  { nume: "Runcu Salvei", comuna: "Salva" },
  { nume: "Cormaia", comuna: "Sangeorz-Bai" },
  { nume: "Valea Borcutului", comuna: "Sangeorz-Bai" },
  { nume: "Brateni", comuna: "Sanmihaiu De Cimpie" },
  { nume: "La Curte", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Stupini", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Sanmihaiu de Campie", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Salcuta", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Zoreni", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Valea Mare", comuna: "Sant" },
  { nume: "Ardan", comuna: "Sieu" },
  { nume: "Posmus", comuna: "Sieu" },
  { nume: "Soimus", comuna: "Sieu" },
  { nume: "Arcalia", comuna: "Sieu-Magherus" },
  { nume: "Chintelnic", comuna: "Sieu-Magherus" },
  { nume: "Crainimat", comuna: "Sieu-Magherus" },
  { nume: "Podirei", comuna: "Sieu-Magherus" },
  { nume: "Saratel", comuna: "Sieu-Magherus" },
  { nume: "Valea Magherusului", comuna: "Sieu-Magherus" },
  { nume: "Agrisu de Jos", comuna: "Sieu-Odorhei" },
  { nume: "Agrisu de Sus", comuna: "Sieu-Odorhei" },
  { nume: "Bretea", comuna: "Sieu-Odorhei" },
  { nume: "Coasta", comuna: "Sieu-Odorhei" },
  { nume: "Cristur-Sieu", comuna: "Sieu-Odorhei" },
  { nume: "Sirioara", comuna: "Sieu-Odorhei" },
  { nume: "Lunca", comuna: "Sieut" },
  { nume: "Rustior", comuna: "Sieut" },
  { nume: "Sebis", comuna: "Sieut" },
  { nume: "Draga", comuna: "Silivasu De Cimpie" },
  { nume: "Fanatele Silivasului", comuna: "Silivasu De Cimpie" },
  { nume: "Porumbenii", comuna: "Silivasu De Cimpie" },
  { nume: "Silivasu de Campie", comuna: "Silivasu De Cimpie" },
  { nume: "Blajenii de Jos", comuna: "Sintereag" },
  { nume: "Blajenii de Sus", comuna: "Sintereag" },
  { nume: "Caila", comuna: "Sintereag" },
  { nume: "Cociu", comuna: "Sintereag" },
  { nume: "Sieu-Sfantu", comuna: "Sintereag" },
  { nume: "Sintereag-Gara", comuna: "Sintereag" },
  { nume: "Halmasau", comuna: "Spermezeu" },
  { nume: "Lunca Borlesei", comuna: "Spermezeu" },
  { nume: "Paltineasa", comuna: "Spermezeu" },
  { nume: "Sita", comuna: "Spermezeu" },
  { nume: "Sesuri Spermezeu-Vale", comuna: "Spermezeu" },
  { nume: "Agries", comuna: "Tarlisua" },
  { nume: "Agriesel", comuna: "Tarlisua" },
  { nume: "Borleasa", comuna: "Tarlisua" },
  { nume: "Cireasi", comuna: "Tarlisua" },
  { nume: "Lunca Sateasca", comuna: "Tarlisua" },
  { nume: "Moliset", comuna: "Tarlisua" },
  { nume: "Oarzina", comuna: "Tarlisua" },
  { nume: "Racatesu", comuna: "Tarlisua" },
  { nume: "Sendroaia", comuna: "Tarlisua" },
  { nume: "Archiud", comuna: "Teaca" },
  { nume: "Budurleni", comuna: "Teaca" },
  { nume: "Ocnita", comuna: "Teaca" },
  { nume: "Pinticu", comuna: "Teaca" },
  { nume: "Viile Tecii", comuna: "Teaca" },
  { nume: "Fiad", comuna: "Telciu" },
  { nume: "Telcisor", comuna: "Telciu" },
  { nume: "Ciosa", comuna: "Tiha Bargaului" },
  { nume: "Muresenii Bargaului", comuna: "Tiha Bargaului" },
  { nume: "Piatra Fantanele", comuna: "Tiha Bargaului" },
  { nume: "Tureac", comuna: "Tiha Bargaului" },
  { nume: "Cristestii Ciceului", comuna: "Uriu" },
  { nume: "Hasmasu Ciceului", comuna: "Uriu" },
  { nume: "Ilisua", comuna: "Uriu" },
  { nume: "Coseriu", comuna: "Urmenis" },
  { nume: "Camp", comuna: "Urmenis" },
  { nume: "Delureni", comuna: "Urmenis" },
  { nume: "Fanate", comuna: "Urmenis" },
  { nume: "Podenii", comuna: "Urmenis" },
  { nume: "Scoabe", comuna: "Urmenis" },
  { nume: "Valea", comuna: "Urmenis" },
  { nume: "Valea Mare", comuna: "Urmenis" },
  { nume: "Sopteriu", comuna: "Urmenis" },
  { nume: "Alunisul", comuna: "Zagra" },
  { nume: "Perisor", comuna: "Zagra" },
  { nume: "Poienile Zagrei", comuna: "Zagra" },
  { nume: "Suplai", comuna: "Zagra" },
];
