export const bh = [
  { nume: "Abram" },
  { nume: "Abrămuţ", simplu: "Abramut" },
  { nume: "Adoni", comuna: "Tarcea" },
  { nume: "Albeşti", simplu: "Albesti", comuna: "Rabagani" },
  { nume: "Albiş", simplu: "Albis", comuna: "Buduslau" },
  { nume: "Aleşd", simplu: "Alesd" },
  { nume: "Almaşu Mare", simplu: "Almasu Mare", comuna: "Balc" },
  { nume: "Almaşu Mic", simplu: "Almasu Mic", comuna: "Balc" },
  { nume: "Almaşu Mic", simplu: "Almasu Mic", comuna: "Sarbi" },
  { nume: "Alparea", comuna: "Osorhei" },
  { nume: "Ant", comuna: "Avram Iancu" },
  { nume: "Apateu", comuna: "Nojorid" },
  { nume: "Arpăşel", simplu: "Arpasel", comuna: "Batar" },
  { nume: "Aştileu", simplu: "Astileu" },
  { nume: "Ateaş", simplu: "Ateas", comuna: "Cefa" },
  { nume: "Auşeu", simplu: "Auseu" },
  { nume: "Avram Iancu" },
  { nume: "Băile Felix", simplu: "Baile Felix", comuna: "Sanmartin" },
  { nume: "Băiţa-Plai", simplu: "Baita-Plai", comuna: "Nucet" },
  { nume: "Băiţa", simplu: "Baita", comuna: "Nucet" },
  { nume: "Bălaia", simplu: "Balaia", comuna: "Tileagd" },
  { nume: "Balc" },
  { nume: "Bâlc", simplu: "Balc", comuna: "Cristioru De Jos" },
  { nume: "Băleni", simplu: "Baleni", comuna: "Lazuri De Beius" },
  { nume: "Bălnaca-Groşi", simplu: "Balnaca-Grosi", comuna: "Suncuius" },
  { nume: "Bălnaca", simplu: "Balnaca", comuna: "Suncuius" },
  { nume: "Batăr", simplu: "Batar" },
  { nume: "Beiuş", simplu: "Beius" },
  { nume: "Beiuşele", simplu: "Beiusele", comuna: "Curatele" },
  { nume: "Belejeni", comuna: "Draganesti" },
  { nume: "Belfir", comuna: "Tinca" },
  { nume: "Berechiu", comuna: "Sannicolau Roman" },
  { nume: "Betfia", comuna: "Sanmartin" },
  { nume: "Beznea", comuna: "Bratca" },
  { nume: "Bicăcel", simplu: "Bicacel", comuna: "Lazareni" },
  { nume: "Bicaci", comuna: "Gepiu" },
  { nume: "Biharia" },
  { nume: "Birtin", comuna: "Vadu Crisului" },
  { nume: "Bistra", comuna: "Popesti" },
  { nume: "Bogei", comuna: "Tauteu" },
  { nume: "Boianu Mare" },
  { nume: "Boiu", comuna: "Ciumeghiu" },
  { nume: "Borod" },
  { nume: "Borozel", comuna: "Borod" },
  { nume: "Borş", simplu: "Bors" },
  { nume: "Borşa", simplu: "Borsa", comuna: "Sacadat" },
  { nume: "Borumlaca", comuna: "Suplacu De Barcau" },
  { nume: "Borz", comuna: "Soimi" },
  { nume: "Botean", comuna: "Ineu" },
  { nume: "Brădet", simplu: "Bradet", comuna: "Buntesti" },
  { nume: "Bratca" },
  { nume: "Brăteşti", simplu: "Bratesti", comuna: "Rabagani" },
  { nume: "Briheni", comuna: "Lunca" },
  { nume: "Brusturi" },
  { nume: "Brusturi", comuna: "Finis" },
  { nume: "Bucium", comuna: "Ceica" },
  { nume: "Bucuroaia", comuna: "Copacel" },
  { nume: "Budoi", comuna: "Popesti" },
  { nume: "Budureasa" },
  { nume: "Buduslău", simplu: "Buduslau" },
  { nume: "Bulz" },
  { nume: "Bunteşti", simplu: "Buntesti" },
  { nume: "Burda", comuna: "Budureasa" },
  { nume: "Burzuc", comuna: "Sarbi" },
  { nume: "Butani", comuna: "Magesti" },
  { nume: "Căbeşti", simplu: "Cabesti" },
  { nume: "Cacuciu Nou", comuna: "Magesti" },
  { nume: "Cacuciu Vechi", comuna: "Auseu" },
  { nume: "Cadea", comuna: "Sacueni" },
  { nume: "Călacea", simplu: "Calacea", comuna: "Olcea" },
  { nume: "Călătani", simplu: "Calatani", comuna: "Tileagd" },
  { nume: "Călăţea", simplu: "Calatea", comuna: "Astileu" },
  { nume: "Calea Mare", comuna: "Lazareni" },
  { nume: "Călugări", simplu: "Calugari", comuna: "Carpinet" },
  { nume: "Câmp-Moţi", simplu: "Camp-Moti", comuna: "Vascau" },
  { nume: "Câmp", simplu: "Camp", comuna: "Vascau" },
  {
    nume: "Câmpani de Pomezeu",
    simplu: "Campani de Pomezeu",
    comuna: "Pomezeu",
  },
  { nume: "Câmpani", simplu: "Campani" },
  { nume: "Căpâlna", simplu: "Capalna" },
  { nume: "Cărăndeni", simplu: "Carandeni", comuna: "Lazareni" },
  { nume: "Cărănzel", simplu: "Caranzel", comuna: "Lazareni" },
  { nume: "Cărăsău", simplu: "Carasau", comuna: "Cociuba Mare" },
  { nume: "Cărpinet", simplu: "Carpinet" },
  { nume: "Cauaceu", comuna: "Biharia" },
  { nume: "Căuaşd", simplu: "Cauasd", comuna: "Tulca" },
  { nume: "Cefa" },
  { nume: "Ceica" },
  { nume: "Ceişoara", simplu: "Ceisoara", comuna: "Ceica" },
  { nume: "Cenaloş", simplu: "Cenalos", comuna: "Ciuhoi" },
  { nume: "Cetariu" },
  { nume: "Cetea", comuna: "Borod" },
  { nume: "Cherechiu" },
  { nume: "Cheresig", comuna: "Girisu De Cris" },
  { nume: "Cheriu", comuna: "Osorhei" },
  { nume: "Cheşa", simplu: "Chesa", comuna: "Cociuba Mare" },
  { nume: "Cheşereu", simplu: "Chesereu", comuna: "Cherechiu" },
  { nume: "Cheţ", simplu: "Chet", comuna: "Marghita" },
  { nume: "Chijic", comuna: "Copacel" },
  { nume: "Chioag", comuna: "Sarbi" },
  { nume: "Chiraleu", comuna: "Chislaz" },
  { nume: "Chiribiş", simplu: "Chiribis", comuna: "Tauteu" },
  { nume: "Chişcău", simplu: "Chiscau", comuna: "Pietroasa" },
  { nume: "Chişirid", simplu: "Chisirid", comuna: "Nojorid" },
  { nume: "Chişlaz", simplu: "Chislaz" },
  { nume: "Chistag", comuna: "Astileu" },
  { nume: "Cihei", comuna: "Sanmartin" },
  { nume: "Ciocaia", comuna: "Sacueni" },
  { nume: "Ciuhoi" },
  { nume: "Ciuleşti", simplu: "Ciulesti", comuna: "Spinus" },
  { nume: "Ciumeghiu" },
  { nume: "Ciutelec", comuna: "Tauteu" },
  { nume: "Cociuba Mare" },
  { nume: "Cociuba Mică", simplu: "Cociuba Mica", comuna: "Pietroasa" },
  { nume: "Codrişoru", simplu: "Codrisoru", comuna: "Auseu" },
  { nume: "Codru", comuna: "Soimi" },
  { nume: "Cohani", comuna: "Abram" },
  { nume: "Coleşti", simplu: "Colesti", comuna: "Vascau" },
  { nume: "Copăcel", simplu: "Copacel" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "Sambata" },
  { nume: "Corbeşti", simplu: "Corbesti", comuna: "Ceica" },
  { nume: "Corboaia", comuna: "Boianu Mare" },
  { nume: "Cordău", simplu: "Cordau", comuna: "Sanmartin" },
  { nume: "Cornişeşti", simplu: "Cornisesti", comuna: "Dobresti" },
  { nume: "Corniţel", simplu: "Cornitel", comuna: "Borod" },
  { nume: "Coşdeni", simplu: "Cosdeni", comuna: "Pomezeu" },
  { nume: "Cotiglet", comuna: "Ceica" },
  { nume: "Crânceşti", simplu: "Crancesti", comuna: "Dobresti" },
  { nume: "Crestur", comuna: "Abramut" },
  { nume: "Cresuia", comuna: "Curatele" },
  { nume: "Criştioru de Jos", simplu: "Cristioru de Jos" },
  {
    nume: "Criştioru de Sus",
    simplu: "Cristioru de Sus",
    comuna: "Cristioru De Jos",
  },
  { nume: "Cubulcut", comuna: "Sacueni" },
  { nume: "Cucuceni", comuna: "Rieni" },
  { nume: "Cuieşd", simplu: "Cuiesd", comuna: "Brusturi" },
  { nume: "Curăţele", simplu: "Curatele" },
  { nume: "Curtuişeni", simplu: "Curtuiseni" },
  { nume: "Cusuiuş", simplu: "Cusuius", comuna: "Lazuri De Beius" },
  { nume: "Cuzap", comuna: "Popesti" },
  { nume: "Damiş", simplu: "Damis", comuna: "Bratca" },
  { nume: "Delani", comuna: "Beius" },
  { nume: "Derna" },
  { nume: "Dernişoara", simplu: "Dernisoara", comuna: "Derna" },
  { nume: "Dicăneşti", simplu: "Dicanesti", comuna: "Dragesti" },
  { nume: "Dijir", comuna: "Abram" },
  { nume: "Diosig" },
  { nume: "Dobreşti", simplu: "Dobresti" },
  { nume: "Dobricioneşti", simplu: "Dobricionesti", comuna: "Magesti" },
  { nume: "Dolea", comuna: "Suplacu De Barcau" },
  { nume: "Drăgăneşti", simplu: "Draganesti" },
  { nume: "Drăgeşti", simplu: "Dragesti" },
  { nume: "Drăgoteni", simplu: "Dragoteni", comuna: "Remetea" },
  { nume: "Dumbrava", comuna: "Holod" },
  { nume: "Dumbrăvani", simplu: "Dumbravani", comuna: "Buntesti" },
  {
    nume: "Dumbrăviţa de Codru",
    simplu: "Dumbravita de Codru",
    comuna: "Soimi",
  },
  { nume: "Dumbrăviţa", simplu: "Dumbravita", comuna: "Holod" },
  { nume: "Duşeşti", simplu: "Dusesti", comuna: "Ceica" },
  { nume: "Fânaţe", simplu: "Fanate", comuna: "Campani" },
  { nume: "Făncica", simplu: "Fancica", comuna: "Abramut" },
  { nume: "Fâşca", simplu: "Fasca", comuna: "Varciorog" },
  { nume: "Fegernic", comuna: "Sarbi" },
  { nume: "Fegernicu Nou", comuna: "Sarbi" },
  { nume: "Felcheriu", comuna: "Osorhei" },
  { nume: "Feneriş", simplu: "Feneris", comuna: "Pocola" },
  { nume: "Ferice", comuna: "Buntesti" },
  { nume: "Finiş", simplu: "Finis" },
  { nume: "Fiziş", simplu: "Fizis", comuna: "Finis" },
  { nume: "Foglaş", simplu: "Foglas", comuna: "Suplacu De Barcau" },
  { nume: "Fonău", simplu: "Fonau", comuna: "Husasau De Tinca" },
  { nume: "Forău", simplu: "Forau", comuna: "Uileacu De Beius" },
  { nume: "Forosig", comuna: "Holod" },
  { nume: "Fughiu", comuna: "Osorhei" },
  { nume: "Gălăşeni", simplu: "Galaseni", comuna: "Magesti" },
  { nume: "Galoşpetreu", simplu: "Galospetreu", comuna: "Tarcea" },
  { nume: "Gepiş", simplu: "Gepis", comuna: "Lazareni" },
  { nume: "Gepiu" },
  { nume: "Gheghie", comuna: "Auseu" },
  { nume: "Ghenetea", comuna: "Marghita" },
  { nume: "Ghida", comuna: "Balc" },
  { nume: "Ghighişeni", simplu: "Ghighiseni", comuna: "Rieni" },
  { nume: "Ghiorac", comuna: "Ciumeghiu" },
  { nume: "Ginta", comuna: "Capalna" },
  { nume: "Girişu de Criş", simplu: "Girisu de Cris" },
  { nume: "Girişu Negru", simplu: "Girisu Negru", comuna: "Tinca" },
  { nume: "Giuleşti", simplu: "Giulesti", comuna: "Pietroasa" },
  { nume: "Goila", comuna: "Cabesti" },
  { nume: "Grădinari", simplu: "Gradinari", comuna: "Draganesti" },
  { nume: "Groşi", simplu: "Grosi", comuna: "Auseu" },
  { nume: "Gruilung", comuna: "Lazareni" },
  { nume: "Gurani", comuna: "Pietroasa" },
  { nume: "Gurbediu", comuna: "Tinca" },
  { nume: "Gurbeşti", simplu: "Gurbesti", comuna: "Cabesti" },
  { nume: "Gurbeşti", simplu: "Gurbesti", comuna: "Spinus" },
  { nume: "Haieu", comuna: "Sanmartin" },
  { nume: "Hârseşti", simplu: "Harsesti", comuna: "Campani" },
  { nume: "Hăuceşti", simplu: "Haucesti", comuna: "Chislaz" },
  { nume: "Hidiş", simplu: "Hidis", comuna: "Pomezeu" },
  { nume: "Hidişel", simplu: "Hidisel", comuna: "Dobresti" },
  {
    nume: "Hidişelu de Jos",
    simplu: "Hidiselu de Jos",
    comuna: "Hidiselu De Sus",
  },
  { nume: "Hidişelu de Sus", simplu: "Hidiselu de Sus" },
  { nume: "Hinchiriş", simplu: "Hinchiris", comuna: "Lazuri De Beius" },
  { nume: "Hodiş", simplu: "Hodis", comuna: "Holod" },
  { nume: "Hodişel", simplu: "Hodisel", comuna: "Olcea" },
  { nume: "Hodoş", simplu: "Hodos", comuna: "Salard" },
  { nume: "Holod" },
  { nume: "Homorog", comuna: "Madaras" },
  { nume: "Hotar", comuna: "Tetchea" },
  { nume: "Hotărel", simplu: "Hotarel", comuna: "Lunca" },
  { nume: "Husasău de Criş", simplu: "Husasau de Cris", comuna: "Ineu" },
  { nume: "Husasău de Tinca", simplu: "Husasau de Tinca" },
  { nume: "Huta Voivozi", comuna: "Sinteu" },
  { nume: "Huta", comuna: "Boianu Mare" },
  { nume: "Ianca", comuna: "Diosig" },
  { nume: "Ianoşda", simplu: "Ianosda", comuna: "Madaras" },
  { nume: "Inand", comuna: "Cefa" },
  { nume: "Inceşti", simplu: "Incesti", comuna: "Ceica" },
  { nume: "Ineu" },
  { nume: "Ioaniş", simplu: "Ioanis", comuna: "Finis" },
  { nume: "Iteu Nou", comuna: "Abram" },
  { nume: "Iteu", comuna: "Abram" },
  { nume: "Izbuc", comuna: "Carpinet" },
  { nume: "Izvoarele", comuna: "Viisoara" },
  { nume: "Josani", comuna: "Cabesti" },
  { nume: "Josani", comuna: "Magesti" },
  { nume: "Lacu Sărat", simplu: "Lacu Sarat", comuna: "Pomezeu" },
  { nume: "Lăzăreni", simplu: "Lazareni" },
  { nume: "Lazuri de Beiuş", simplu: "Lazuri de Beius" },
  { nume: "Lazuri", comuna: "Rosia" },
  { nume: "Leheceni", comuna: "Carpinet" },
  { nume: "Leleşti", simplu: "Lelesti", comuna: "Buntesti" },
  { nume: "Leş", simplu: "Les", comuna: "Nojorid" },
  {
    nume: "Livada Beiuşului",
    simplu: "Livada Beiusului",
    comuna: "Draganesti",
  },
  { nume: "Livada de Bihor", comuna: "Nojorid" },
  { nume: "Loranta", comuna: "Brusturi" },
  { nume: "Lorău", simplu: "Lorau", comuna: "Bratca" },
  { nume: "Lugaşu de Jos", simplu: "Lugasu de Jos" },
  { nume: "Lugaşu de Sus", simplu: "Lugasu de Sus", comuna: "Lugasu De Jos" },
  { nume: "Lunca" },
  { nume: "Luncasprie", comuna: "Dobresti" },
  { nume: "Luncşoara", simplu: "Luncsoara", comuna: "Auseu" },
  { nume: "Lupoaia", comuna: "Holod" },
  { nume: "Mădăraş", simplu: "Madaras" },
  { nume: "Măgeşti", simplu: "Magesti" },
  { nume: "Măgura", simplu: "Magura", comuna: "Pietroasa" },
  { nume: "Marghita" },
  { nume: "Margine", comuna: "Abram" },
  { nume: "Marţihaz", simplu: "Martihaz", comuna: "Madaras" },
  { nume: "Meziad", comuna: "Remetea" },
  { nume: "Mierag", comuna: "Tarcaia" },
  { nume: "Mierlău", simplu: "Mierlau", comuna: "Hidiselu De Sus" },
  { nume: "Miersig", comuna: "Husasau De Tinca" },
  { nume: "Mihai Bravu", comuna: "Rosiori" },
  { nume: "Miheleu", comuna: "Lazareni" },
  { nume: "Mişca", simplu: "Misca", comuna: "Chislaz" },
  { nume: "Mizieş", simplu: "Mizies", comuna: "Draganesti" },
  { nume: "Moţeşti", simplu: "Motesti", comuna: "Pietroasa" },
  { nume: "Munteni", comuna: "Bulz" },
  { nume: "Nădar", simplu: "Nadar", comuna: "Spinus" },
  { nume: "Nimăieşti", simplu: "Nimaiesti", comuna: "Curatele" },
  { nume: "Niuved", comuna: "Tamaseu" },
  { nume: "Nojorid" },
  { nume: "Nucet" },
  { nume: "Ogeşti", simplu: "Ogesti", comuna: "Sambata" },
  { nume: "Olcea" },
  { nume: "Olosig", comuna: "Sacueni" },
  { nume: "Oradea" },
  { nume: "Ortiteag", comuna: "Magesti" },
  { nume: "Orvişele", simplu: "Orvisele", comuna: "Brusturi" },
  { nume: "Oşand", simplu: "Osand", comuna: "Husasau De Tinca" },
  { nume: "Oşorhei", simplu: "Osorhei" },
  { nume: "Otomani", comuna: "Salacea" },
  { nume: "Păcăleşti", simplu: "Pacalesti", comuna: "Drăgănești" },
  { nume: "Pădurea Neagră", simplu: "Padurea Neagra", comuna: "Alesd" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Viisoara" },
  { nume: "Păgaia", simplu: "Pagaia", comuna: "Boianu Mare" },
  { nume: "Paleu" },
  { nume: "Palota", comuna: "Santandrei" },
  { nume: "Păntăşeşti", simplu: "Pantasesti", comuna: "Draganesti" },
  { nume: "Parhida", comuna: "Tamaseu" },
  { nume: "Păuleşti", simplu: "Paulesti", comuna: "Brusturi" },
  { nume: "Păuşa", simplu: "Pausa", comuna: "Nojorid" },
  { nume: "Peştere", simplu: "Pestere", comuna: "Astileu" },
  { nume: "Peştiş", simplu: "Pestis", comuna: "Alesd" },
  { nume: "Petid", comuna: "Cociuba Mare" },
  { nume: "Petrani", comuna: "Pocola" },
  { nume: "Petreasa", comuna: "Remetea" },
  { nume: "Petreu", comuna: "Abramut" },
  { nume: "Petrileni", comuna: "Rieni" },
  { nume: "Picleu", comuna: "Brusturi" },
  { nume: "Pietroasa" },
  { nume: "Pociovelişte", simplu: "Pocioveliste", comuna: "Curatele" },
  { nume: "Pocluşa de Barcău", simplu: "Poclusa de Barcau", comuna: "Chislaz" },
  { nume: "Pocluşa de Beiuş", simplu: "Poclusa de Beius", comuna: "Soimi" },
  { nume: "Pocola" },
  { nume: "Poiana Tăşad", simplu: "Poiana Tasad", comuna: "Copacel" },
  { nume: "Poiana", comuna: "Cristioru De Jos" },
  { nume: "Poiana", comuna: "Tauteu" },
  { nume: "Poienii de Jos", comuna: "Buntesti" },
  { nume: "Poienii de Sus", comuna: "Buntesti" },
  { nume: "Poietari", comuna: "Pocola" },
  { nume: "Pomezeu" },
  { nume: "Ponoară", simplu: "Ponoara", comuna: "Bratca" },
  { nume: "Popeşti", simplu: "Popesti" },
  { nume: "Poşoloaca", simplu: "Posoloaca", comuna: "Tileagd" },
  { nume: "Prisaca", comuna: "Uileacu De Beius" },
  { nume: "Răbăgani", simplu: "Rabagani" },
  { nume: "Răcaş", simplu: "Racas", comuna: "Dobresti" },
  { nume: "Râpa", simplu: "Rapa", comuna: "Tinca" },
  { nume: "Reghea", comuna: "Viisoara" },
  { nume: "Remetea" },
  { nume: "Remeţi", simplu: "Remeti", comuna: "Bulz" },
  { nume: "Rieni" },
  { nume: "Rogoz", comuna: "Sambata" },
  { nume: "Rohani", comuna: "Capalna" },
  { nume: "Roit", comuna: "Sannicolau Roman" },
  { nume: "Rontău", simplu: "Rontau", comuna: "Sanmartin" },
  { nume: "Roşia", simplu: "Rosia" },
  { nume: "Roşiori", simplu: "Rosiori" },
  { nume: "Rotăreşti", simplu: "Rotaresti", comuna: "Sambata" },
  { nume: "Rugea", comuna: "Boianu Mare" },
  { nume: "Săbolciu", simplu: "Sabolciu", comuna: "Sacadat" },
  { nume: "Saca", comuna: "Budureasa" },
  { nume: "Săcădat", simplu: "Sacadat" },
  { nume: "Sacalasău Nou", simplu: "Sacalasau Nou", comuna: "Derna" },
  { nume: "Sacalasău", simplu: "Sacalasau", comuna: "Derna" },
  { nume: "Săcueni", simplu: "Sacueni" },
  { nume: "Sălacea", simplu: "Salacea" },
  { nume: "Sălard", simplu: "Salard" },
  {
    nume: "Săldăbagiu de Barcău",
    simplu: "Saldabagiu de Barcau",
    comuna: "Balc",
  },
  {
    nume: "Săldăbagiu de Munte",
    simplu: "Saldabagiu de Munte",
    comuna: "Paleu",
  },
  { nume: "Săldăbagiu Mic", simplu: "Saldabagiu Mic", comuna: "Capalna" },
  { nume: "Sălişte de Beiuş", simplu: "Saliste de Beius", comuna: "Budureasa" },
  {
    nume: "Salişte de Pomezeu",
    simplu: "Saliste de Pomezeu",
    comuna: "Rabagani",
  },
  {
    nume: "Sălişte de Vaşcău",
    simplu: "Saliste de Vascau",
    comuna: "Cristioru De Jos",
  },
  { nume: "Sălişte", simplu: "Saliste", comuna: "Spinus" },
  { nume: "Salonta" },
  { nume: "Sâmbăta", simplu: "Sambata" },
  { nume: "Sâniob", simplu: "Saniob", comuna: "Ciuhoi" },
  { nume: "Sânlazăr", simplu: "Sanlazar", comuna: "Chislaz" },
  {
    nume: "Sânmartin de Beiuş",
    simplu: "Sanmartin de Beius",
    comuna: "Pocola",
  },
  { nume: "Sânmartin", simplu: "Sanmartin" },
  {
    nume: "Sânnicolau de Beiuş",
    simplu: "Sannicolau de Beius",
    comuna: "Soimi",
  },
  {
    nume: "Sânnicolau de Munte",
    simplu: "Sannicolau de Munte",
    comuna: "Sacueni",
  },
  { nume: "Sânnicolau Român", simplu: "Sannicolau Roman" },
  { nume: "Sântandrei", simplu: "Santandrei" },
  { nume: "Santăul Mare", simplu: "Santaul Mare", comuna: "Bors" },
  { nume: "Santăul Mic", simplu: "Santaul Mic", comuna: "Bors" },
  { nume: "Sântelec", simplu: "Santelec", comuna: "Hidiselu De Sus" },
  { nume: "Sântimreu", simplu: "Santimreu", comuna: "Salard" },
  { nume: "Sântion", simplu: "Santion", comuna: "Bors" },
  { nume: "Sărand", simplu: "Sarand", comuna: "Copacel" },
  { nume: "Sârbeşti", simplu: "Sarbesti", comuna: "Lunca" },
  { nume: "Sârbi", simplu: "Sarbi" },
  { nume: "Sarcău", simplu: "Sarcau", comuna: "Sarbi" },
  { nume: "Sărsig", simplu: "Sarsig", comuna: "Chislaz" },
  { nume: "Satu Barbă", simplu: "Satu Barba", comuna: "Abram" },
  { nume: "Satu Nou", comuna: "Tamaseu" },
  { nume: "Şauaieu", simplu: "Sauaieu", comuna: "Nojorid" },
  { nume: "Săucani", simplu: "Saucani", comuna: "Rabagani" },
  { nume: "Săud", simplu: "Saud", comuna: "Buntesti" },
  { nume: "Şebiş", simplu: "Sebis", comuna: "Draganesti" },
  { nume: "Seghişte", simplu: "Seghiste", comuna: "Lunca" },
  { nume: "Şerani", simplu: "Serani", comuna: "Borod" },
  { nume: "Şerghiş", simplu: "Serghis", comuna: "Varciorog" },
  { nume: "Sfârnaş", simplu: "Sfarnas", comuna: "Ciuhoi" },
  { nume: "Sighiştel", simplu: "Sighistel", comuna: "Campani" },
  { nume: "Şilindru", simplu: "Silindru", comuna: "Simian" },
  { nume: "Şimian", simplu: "Simian" },
  { nume: "Şinteu", simplu: "Sinteu" },
  { nume: "Şişterea", simplu: "Sisterea", comuna: "Cetariu" },
  { nume: "Sitani", comuna: "Pomezeu" },
  { nume: "Sititelec", comuna: "Husasau De Tinca" },
  { nume: "Socet", comuna: "Sinteu" },
  { nume: "Sohodol", comuna: "Cabesti" },
  { nume: "Şoimi", simplu: "Soimi" },
  { nume: "Soimuş", simplu: "Soimus", comuna: "Remetea" },
  { nume: "Spinuş de Pomezeu", simplu: "Spinus de Pomezeu", comuna: "Pomezeu" },
  { nume: "Spinuş", simplu: "Spinus" },
  { nume: "Stânceşti", simplu: "Stancesti", comuna: "Buntesti" },
  { nume: "Ştei", simplu: "Stei" },
  { nume: "Stracoş", simplu: "Stracos", comuna: "Dragesti" },
  { nume: "Subpiatră", simplu: "Subpiatra", comuna: "Tetchea" },
  { nume: "Sudrigiu", comuna: "Rieni" },
  { nume: "Suiug", comuna: "Abram" },
  { nume: "Şumugiu", simplu: "Sumugiu", comuna: "Hidiselu De Sus" },
  { nume: "Şuncuiş", simplu: "Suncuis", comuna: "Finis" },
  { nume: "Şuncuiuş", simplu: "Suncuius" },
  { nume: "Suplacu de Barcău", simplu: "Suplacu de Barcau" },
  { nume: "Suplacu de Tinca", comuna: "Capalna" },
  { nume: "Surduc", comuna: "Copacel" },
  { nume: "Surducel", comuna: "Varciorog" },
  { nume: "Şuştiu", simplu: "Sustiu", comuna: "Lunca" },
  { nume: "Şuşturogi", simplu: "Susturogi", comuna: "Cetariu" },
  { nume: "Talpe", comuna: "Draganesti" },
  { nume: "Talpoş", simplu: "Talpos", comuna: "Batar" },
  { nume: "Tămaşda", simplu: "Tamasda", comuna: "Avram Iancu" },
  { nume: "Tămăşeu", simplu: "Tamaseu" },
  { nume: "Tărcaia", simplu: "Tarcaia" },
  { nume: "Tărcăiţa", simplu: "Tarcaita", comuna: "Tarcaia" },
  { nume: "Tarcea" },
  { nume: "Târguşor", simplu: "Targusor", comuna: "Cherechiu" },
  { nume: "Tărian", simplu: "Tarian", comuna: "Girisu De Cris" },
  { nume: "Tăşad", simplu: "Tasad", comuna: "Dragesti" },
  { nume: "Tăut", simplu: "Taut", comuna: "Batar" },
  { nume: "Tăutelec", simplu: "Tautelec", comuna: "Cetariu" },
  { nume: "Tăuteu", simplu: "Tauteu" },
  { nume: "Teleac", comuna: "Budureasa" },
  { nume: "Telechiu", comuna: "Tetchea" },
  { nume: "Ţeţchea", simplu: "Tetchea" },
  {
    nume: "Ţigăneştii de Beiuş",
    simplu: "Tiganestii de Beius",
    comuna: "Draganesti",
  },
  {
    nume: "Ţigăneştii de Criş",
    simplu: "Tiganestii de Cris",
    comuna: "Brusturi",
  },
  { nume: "Tileagd" },
  { nume: "Tilecuş", simplu: "Tilecus", comuna: "Tileagd" },
  { nume: "Tinăud", simplu: "Tinaud", comuna: "Alesd" },
  { nume: "Tinca" },
  { nume: "Toboliu", comuna: "Girisu De Cris" },
  { nume: "Tomnatic", comuna: "Vadu Crisului" },
  { nume: "Topa de Criş", simplu: "Topa de Cris", comuna: "Vadu Crisului" },
  { nume: "Topa de Jos", comuna: "Dobresti" },
  { nume: "Topa de Sus", comuna: "Dobresti" },
  { nume: "Topeşti", simplu: "Topesti", comuna: "Dragesti" },
  { nume: "Totoreni", comuna: "Tarcaia" },
  { nume: "Tria", comuna: "Derna" },
  { nume: "Tulca" },
  { nume: "Ucuriş", simplu: "Ucuris", comuna: "Olcea" },
  { nume: "Uileacu de Beiuş", simplu: "Uileacu de Beius" },
  { nume: "Uileacu de Criş", simplu: "Uileacu de Cris", comuna: "Tileagd" },
  { nume: "Uileacu de Munte", comuna: "Paleu" },
  { nume: "Ursad", comuna: "Soimi" },
  { nume: "Urvind", comuna: "Lugasu De Jos" },
  { nume: "Urviş de Beiuş", simplu: "Urvis de Beius", comuna: "Soimi" },
  { nume: "Vadu Crişului", simplu: "Vadu Crisului" },
  { nume: "Vaida", comuna: "Rosiori" },
  { nume: "Vălani de Pomezeu", simplu: "Valani de Pomezeu", comuna: "Pomezeu" },
  {
    nume: "Vălanii de Beiuş",
    simplu: "Valanii de Beius",
    comuna: "Uileacu De Beius",
  },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Suplacu De Barcau" },
  { nume: "Valea Cerului", comuna: "Suplacu De Barcau" },
  { nume: "Valea Crişului", simplu: "Valea Crisului", comuna: "Bratca" },
  { nume: "Valea de Jos", comuna: "Rieni" },
  { nume: "Valea de Sus", comuna: "Campani" },
  { nume: "Valea lui Mihai" },
  { nume: "Valea Mare de Codru", comuna: "Holod" },
  { nume: "Valea Mare de Criş", simplu: "Valea Mare de Cris", comuna: "Borod" },
  { nume: "Valea Târnei", simplu: "Valea Tarnei", comuna: "Sinteu" },
  { nume: "Varasău", simplu: "Varasau", comuna: "Brusturi" },
  { nume: "Vărăşeni", simplu: "Varaseni", comuna: "Rabagani" },
  { nume: "Vârciorog", simplu: "Varciorog" },
  { nume: "Varviz", comuna: "Popesti" },
  { nume: "Vărzari", simplu: "Varzari", comuna: "Popesti" },
  { nume: "Vărzarii de Jos", simplu: "Varzarii de Jos", comuna: "Vascau" },
  { nume: "Vărzarii de Sus", simplu: "Varzarii de Sus", comuna: "Vascau" },
  { nume: "Văşad", simplu: "Vasad", comuna: "Curtuiseni" },
  { nume: "Vaşcău", simplu: "Vascau" },
  { nume: "Viişoara", simplu: "Viisoara" },
  { nume: "Vintere", comuna: "Holod" },
  { nume: "Voivozi", comuna: "Popesti" },
  { nume: "Voivozi", comuna: "Simian" },
  { nume: "Zăvoiu", simplu: "Zavoiu", comuna: "Sambata" },
  { nume: "Zece Hotare", comuna: "Suncuius" },
];
