export const bt = [
  { nume: "Adășeni", simplu: "Adaseni", comuna: "Avrameni" },
  { nume: "Agafton", comuna: "Curtesti" },
  { nume: "Alba", comuna: "Hudesti" },
  { nume: "Albești", simplu: "Albesti" },
  { nume: "Arborea", comuna: "George Enescu" },
  { nume: "Aurel Vlaicu", comuna: "Avrameni" },
  { nume: "Avram Iancu", comuna: "Cotusca" },
  { nume: "Avrămeni", simplu: "Avrameni" },
  { nume: "Băbiceni", simplu: "Babiceni", comuna: "Durnesti" },
  { nume: "Bădărăi", simplu: "Badarai", comuna: "Santa Mare" },
  { nume: "Bădiuți", simplu: "Badiuti", comuna: "Stefanesti" },
  { nume: "Băiceni", simplu: "Baiceni", comuna: "Curtesti" },
  { nume: "Baisa", comuna: "Mihai Eminescu" },
  { nume: "Bajura", comuna: "Darabani" },
  { nume: "Balinți", simplu: "Balinti", comuna: "Havarna" },
  { nume: "Balta Arsă", simplu: "Balta Arsa", comuna: "Corni" },
  { nume: "Bălușeni", simplu: "Baluseni" },
  { nume: "Bălușenii Noi", simplu: "Balusenii Noi", comuna: "Baluseni" },
  { nume: "Baranca", comuna: "Cristinesti" },
  { nume: "Baranca", comuna: "Hudesti" },
  { nume: "Bârsănești", simplu: "Barsanesti", comuna: "Durnesti" },
  { nume: "Bașeu", simplu: "Baseu", comuna: "Hudești" },
  { nume: "Bătrânești", simplu: "Batranesti", comuna: "Gorbanesti" },
  { nume: "Belcea", comuna: "Leorda" },
  { nume: "Berza", comuna: "Santa Mare" },
  { nume: "Bivolari", comuna: "Dobarceni" },
  { nume: "Blândești", simplu: "Blandesti", comuna: "Blindesti" },
  { nume: "Bobulești", simplu: "Bobulesti", comuna: "Stefanesti" },
  { nume: "Bodeasa", comuna: "Saveni" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Santa Mare" },
  { nume: "Bohoghina", comuna: "Bucecea" },
  { nume: "Bold", comuna: "Manoleasa" },
  { nume: "Borolea", comuna: "Hanesti" },
  { nume: "Borzești", simplu: "Borzesti", comuna: "Ungureni" },
  { nume: "Boscoteni", comuna: "Frumusica" },
  { nume: "Botoșani", simplu: "Botosani" },
  { nume: "Bozieni", comuna: "Saveni" },
  { nume: "Brăești", simplu: "Braesti" },
  { nume: "Brăteni", simplu: "Brateni", comuna: "Dobarceni" },
  { nume: "Brehuiești", simplu: "Brehuiesti", comuna: "Vladeni" },
  { nume: "Broscăuți", simplu: "Broscauti" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Durnesti" },
  { nume: "Bucecea" },
  { nume: "Buda", comuna: "Cosula" },
  { nume: "Buhăceni", simplu: "Buhaceni", comuna: "Trusesti" },
  { nume: "Buimăceni", simplu: "Buimaceni", comuna: "Albesti" },
  { nume: "Burla", comuna: "Unteni" },
  { nume: "Burlești", simplu: "Burlesti", comuna: "Unteni" },
  { nume: "Buzeni", comuna: "Baluseni" },
  { nume: "Călărași", simplu: "Calarasi" },
  { nume: "Călinești", simplu: "Calinesti", comuna: "Bucecea" },
  { nume: "Călinești", simplu: "Calinesti", comuna: "Candesti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Ungureni" },
  { nume: "Călugărenii Noi", simplu: "Calugarenii Noi", comuna: "Ungureni" },
  { nume: "Câmpeni", simplu: "Campeni", comuna: "Prajeni" },
  { nume: "Cândești", simplu: "Candesti" },
  { nume: "Caraiman", comuna: "Mihalaseni" },
  { nume: "Carasa", comuna: "Corlateni" },
  {
    nume: "Cătămărești-Deal",
    simplu: "Catamaresti-Deal",
    comuna: "Mihai Eminescu",
  },
  { nume: "Cătămărești", simplu: "Catamaresti", comuna: "Mihai Eminescu" },
  { nume: "Cerbu", comuna: "Copalau" },
  { nume: "Cerchejeni", comuna: "Blindesti" },
  { nume: "Cernești", simplu: "Cernesti", comuna: "Todireni" },
  {
    nume: "Cervicești-Deal",
    simplu: "Cervicesti-Deal",
    comuna: "Mihai Eminescu",
  },
  { nume: "Cervicești", simplu: "Cervicesti", comuna: "Mihai Eminescu" },
  { nume: "Cheliș", simplu: "Chelis", comuna: "Sulita" },
  { nume: "Chișcăreni", simplu: "Chiscareni", comuna: "Saveni" },
  { nume: "Chițoveni", simplu: "Chitoveni", comuna: "Flamanzi" },
  { nume: "Cinghiniia", comuna: "Ripiceni" },
  { nume: "Ciritei", comuna: "Trusesti" },
  { nume: "Cișmănești", simplu: "Cismanesti", comuna: "Dobarceni" },
  { nume: "Cișmea", simplu: "Cismea", comuna: "Rachiti" },
  { nume: "Codreni", comuna: "Mileanca" },
  { nume: "Concești", simplu: "Concesti" },
  { nume: "Copălău", simplu: "Copalau" },
  { nume: "Cordăreni", simplu: "Cordareni" },
  { nume: "Corjăuți", simplu: "Corjauti", comuna: "Hiliseu-Horia" },
  { nume: "Corlăteni", simplu: "Corlateni" },
  { nume: "Corni" },
  { nume: "Costești", simplu: "Costesti", comuna: "Rachiti" },
  { nume: "Costinești", simplu: "Costinesti", comuna: "Leorda" },
  { nume: "Coștiugeni", simplu: "Costiugeni", comuna: "Albesti" },
  { nume: "Coșula", simplu: "Cosula" },
  { nume: "Coșuleni", simplu: "Cosuleni", comuna: "Baluseni" },
  { nume: "Cotârgaci", simplu: "Cotargaci", comuna: "Roma" },
  { nume: "Cotu Miculinți", simplu: "Cotu Miculinti", comuna: "Cotusca" },
  { nume: "Cotu", comuna: "Copalau" },
  { nume: "Coțușca", simplu: "Cotusca" },
  { nume: "Crasnaleuca", comuna: "Cotusca" },
  { nume: "Cristești", simplu: "Cristesti" },
  { nume: "Cristinești", simplu: "Cristinesti" },
  { nume: "Cucorăni", simplu: "Cucorani", comuna: "Mihai Eminescu" },
  { nume: "Cucuteni", comuna: "Durnesti" },
  { nume: "Curtești", simplu: "Curtesti" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Viisoara" },
  { nume: "Cuzlău", simplu: "Cuzlau", comuna: "Paltinis" },
  { nume: "Dacia", comuna: "Nicseni" },
  { nume: "Dămideni", simplu: "Damideni", comuna: "Romanesti" },
  { nume: "Dămileni", simplu: "Damileni", comuna: "Cristinești" },
  { nume: "Dângeni", simplu: "Dangeni" },
  { nume: "Darabani" },
  { nume: "Davidoaia", comuna: "Vorniceni" },
  { nume: "Dealu Crucii", comuna: "Vorniceni" },
  { nume: "Dealu Mare", comuna: "Dorohoi" },
  { nume: "Dersca" },
  { nume: "Dimăcheni", simplu: "Dimacheni" },
  { nume: "Dimitrie Cantemir", comuna: "Avrameni" },
  { nume: "Dobârceni", simplu: "Dobarceni" },
  {
    nume: "Dobrinăuți-Hapăi",
    simplu: "Dobrinauti-Hapai",
    comuna: "Vârfu Câmpului",
  },
  { nume: "Doina", comuna: "Rauseni" },
  { nume: "Dolina", comuna: "Leorda" },
  { nume: "Dorobanți", simplu: "Dorobanti", comuna: "Nicseni" },
  { nume: "Dorohoi" },
  { nume: "Dracșani", simplu: "Dracsani", comuna: "Sulita" },
  { nume: "Dragalina", comuna: "Cristinesti" },
  { nume: "Dragalina", comuna: "Hlipiceni" },
  { nume: "Drăgușeni", simplu: "Draguseni" },
  { nume: "Draxini", comuna: "Baluseni" },
  { nume: "Drislea", comuna: "Trusesti" },
  { nume: "Dumbrăvița", simplu: "Dumbravita", comuna: "Ibanesti" },
  { nume: "Dumeni", comuna: "George Enescu" },
  { nume: "Durnești", simplu: "Durnesti" },
  { nume: "Durnești", simplu: "Durnesti", comuna: "Santa Mare" },
  { nume: "Durnești", simplu: "Durnesti", comuna: "Ungureni" },
  { nume: "Eșanca", simplu: "Esanca", comuna: "Darabani" },
  { nume: "Flamânzi", simplu: "Flamanzi" },
  { nume: "Flondora", comuna: "Manoleasa" },
  { nume: "Florești", simplu: "Floresti", comuna: "Todireni" },
  { nume: "Frumușica", simplu: "Frumusica" },
  { nume: "Fundu Herții", simplu: "Fundu Hertii", comuna: "Cristinesti" },
  { nume: "Galbeni", comuna: "Havarna" },
  { nume: "Gârbeni", simplu: "Garbeni", comuna: "Havarna" },
  { nume: "Gârbești", simplu: "Garbesti", comuna: "Todireni" },
  { nume: "George Coșbuc", simplu: "George Cosbuc", comuna: "Gorbanesti" },
  { nume: "George Enescu" },
  { nume: "Ghireni", comuna: "Cotusca" },
  { nume: "Gorbănești", simplu: "Gorbanesti" },
  { nume: "Gorovei", comuna: "Vaculesti" },
  { nume: "Grivița", simplu: "Grivita", comuna: "Cordareni" },
  { nume: "Guranda", comuna: "Durnesti" },
  { nume: "Hănești", simplu: "Hanesti" },
  { nume: "Havârna", simplu: "Havarna" },
  { nume: "Hilișeu-Cloșca", simplu: "Hiliseu-Closca", comuna: "Hiliseu-Horia" },
  { nume: "Hilișeu-Crișan", simplu: "Hiliseu-Crisan", comuna: "Hiliseu-Horia" },
  { nume: "Hilișeu-Horia", simplu: "Hiliseu-Horia" },
  { nume: "Hlipiceni" },
  { nume: "Horia", comuna: "Mitoc" },
  { nume: "Horlăceni", simplu: "Horlaceni", comuna: "Sendriceni" },
  { nume: "Horodiștea", simplu: "Horodistea", comuna: "Paltinis" },
  { nume: "Hrișcani", simplu: "Hriscani", comuna: "Vladeni" },
  { nume: "Hudești", simplu: "Hudesti" },
  { nume: "Hudum", comuna: "Curtesti" },
  { nume: "Hulub", comuna: "Dangeni" },
  { nume: "Hulubești", simplu: "Hulubesti", comuna: "Pomarla" },
  { nume: "Huțani", simplu: "Hutani", comuna: "Vladeni" },
  { nume: "Iacobeni", comuna: "Dangeni" },
  { nume: "Ibăneasa", simplu: "Ibaneasa", comuna: "Stiubieni" },
  { nume: "Ibănești", simplu: "Ibanesti" },
  { nume: "Ichimeni", comuna: "Avrameni" },
  { nume: "Icușeni", simplu: "Icuseni", comuna: "Vorona" },
  { nume: "Iezer", comuna: "Hiliseu-Horia" },
  { nume: "Ilișeni", simplu: "Iliseni", comuna: "Santa Mare" },
  { nume: "Ionășeni", simplu: "Ionaseni", comuna: "Trusesti" },
  { nume: "Ionășeni", simplu: "Ionaseni", comuna: "Varfu Campului" },
  { nume: "Iorga", comuna: "Manoleasa" },
  { nume: "Ipotești", simplu: "Ipotesti", comuna: "Mihai Eminescu" },
  { nume: "Iurești", simplu: "Iuresti", comuna: "Todireni" },
  { nume: "Izvoare", comuna: "Suharau" },
  { nume: "Jijia", comuna: "Albesti" },
  { nume: "Joldești", simplu: "Joldesti", comuna: "Vorona" },
  { nume: "Lehnești", simplu: "Lehnesti", comuna: "Ripiceni" },
  { nume: "Leorda" },
  { nume: "Libertatea", comuna: "Calarasi" },
  { nume: "Lismănița", simplu: "Lismanita", comuna: "Darabani" },
  { nume: "Lișna", simplu: "Lisna", comuna: "Suharau" },
  { nume: "Livada", comuna: "Dobarceni" },
  { nume: "Liveni", comuna: "Manoleasa" },
  { nume: "Loturi Enescu", comuna: "Dorohoi" },
  { nume: "Loturi", comuna: "Manoleasa" },
  { nume: "Lozna" },
  { nume: "Lunca" },
  { nume: "Lunca", comuna: "Varfu Campului" },
  { nume: "Lupăria", simplu: "Luparia", comuna: "Prajeni" },
  { nume: "Maghera", comuna: "Vârfu Câmpului" },
  {
    nume: "Mănăstirea Doamnei",
    simplu: "Manastirea Doamnei",
    comuna: "Curtesti",
  },
  { nume: "Mânăstireni", simplu: "Manastireni", comuna: "Unteni" },
  { nume: "Mândrești", simplu: "Mandresti", comuna: "Ungureni" },
  { nume: "Mândrești", simplu: "Mandresti", comuna: "Vladeni" },
  { nume: "Manoleasa-Prut", comuna: "Manoleasa" },
  { nume: "Manoleasa" },
  { nume: "Manolești", simplu: "Manolesti", comuna: "Mihai Eminescu" },
  { nume: "Mășcăteni", simplu: "Mascateni", comuna: "Albesti" },
  { nume: "Mateieni", comuna: "Dimacheni" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Corni" },
  { nume: "Mihai Eminescu", comuna: "Gorbanesti" },
  { nume: "Mihai Viteazu", comuna: "Ungureni" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Cotusca",
  },
  { nume: "Mihăileni", simplu: "Mihaileni" },
  { nume: "Mihălășeni", simplu: "Mihalaseni" },
  { nume: "Mileanca" },
  { nume: "Miletin", comuna: "Prajeni" },
  { nume: "Miorcani", comuna: "Radauti-Prut" },
  { nume: "Miron Costin", comuna: "Vlasinesti" },
  { nume: "Mitoc" },
  { nume: "Mitoc", comuna: "Leorda" },
  { nume: "Mlenăuți", simplu: "Mlenauti", comuna: "Hudesti" },
  { nume: "Moara Jorii", comuna: "Hanesti" },
  { nume: "Movila Ruptă", simplu: "Movila Rupta", comuna: "Ripiceni" },
  { nume: "Movileni", comuna: "Concesti" },
  { nume: "Murguța", simplu: "Murguta", comuna: "Dobarceni" },
  { nume: "Năstase", simplu: "Nastase", comuna: "Mihalaseni" },
  { nume: "Negreni", comuna: "Stiubieni" },
  { nume: "Negrești", simplu: "Negresti", comuna: "Mihalaseni" },
  { nume: "Nichiteni", comuna: "Cotusca" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu", comuna: "Cotusca" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu", comuna: "Flamanzi" },
  { nume: "Nicșeni", simplu: "Nicseni" },
  { nume: "Niculcea", comuna: "Havarna" },
  { nume: "Oneaga", comuna: "Cristesti" },
  { nume: "Orășeni-Deal", simplu: "Oraseni-Deal", comuna: "Curtesti" },
  { nume: "Orășeni-Vale", simplu: "Oraseni-Vale", comuna: "Curtesti" },
  { nume: "Oroftiana", comuna: "Suharau" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Cosula" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Sendriceni" },
  { nume: "Păltiniș", simplu: "Paltinis" },
  { nume: "Panaitoaia", comuna: "Avrameni" },
  { nume: "Pârâu Negru", simplu: "Parau Negru", comuna: "Mihaileni" },
  { nume: "Păsăteni", simplu: "Pasateni", comuna: "Trusesti" },
  { nume: "Păun", simplu: "Paun", comuna: "Mihalaseni" },
  { nume: "Petricani", comuna: "Saveni" },
  { nume: "Pleșani", simplu: "Plesani", comuna: "Calarasi" },
  { nume: "Plevna", comuna: "Suharau" },
  { nume: "Plopenii Mari", comuna: "Ungureni" },
  { nume: "Plopenii Mici", comuna: "Ungureni" },
  { nume: "Podeni", comuna: "Corlateni" },
  { nume: "Podriga", comuna: "Draguseni" },
  { nume: "Pogorăști", simplu: "Pogorasti", comuna: "Rauseni" },
  { nume: "Poiana", comuna: "Braesti" },
  { nume: "Poiana", comuna: "Cristinesti" },
  { nume: "Poiana", comuna: "Flamanzi" },
  { nume: "Poiana", comuna: "Vorona" },
  { nume: "Pomârla", simplu: "Pomarla" },
  { nume: "Popeni", comuna: "Braesti" },
  { nume: "Popeni", comuna: "George Enescu" },
  { nume: "Popoaia", comuna: "Ripiceni" },
  { nume: "Prăjeni", simplu: "Prajeni" },
  { nume: "Prisăcani", simplu: "Prisacani", comuna: "Flamanzi" },
  { nume: "Progresul", comuna: "Dorohoi" },
  { nume: "Pustoaia", comuna: "Vârfu Câmpului" },
  { nume: "Puțureni", simplu: "Putureni", comuna: "Cotusca" },
  { nume: "Răchiți", simplu: "Rachiti" },
  { nume: "Racovăț", simplu: "Racovat", comuna: "Pomarla" },
  { nume: "Rădăuți-Prut", simplu: "Radauti-Prut" },
  { nume: "Rădeni", simplu: "Radeni", comuna: "Frumusica" },
  {
    nume: "Rânghilești-Deal",
    simplu: "Ranghilesti-Deal",
    comuna: "Santa Mare",
  },
  { nume: "Rânghilești", simplu: "Ranghilesti", comuna: "Santa Mare" },
  { nume: "Râșca", simplu: "Rasca", comuna: "Ripiceni" },
  { nume: "Răușeni", simplu: "Rauseni" },
  { nume: "Recia-Verbia", comuna: "Dimacheni" },
  { nume: "Rediu", comuna: "Radauti-Prut" },
  { nume: "Rediu", comuna: "Rauseni" },
  { nume: "Ripiceni" },
  { nume: "Ripicenii Vechi", comuna: "Ripiceni" },
  { nume: "Rogojești", simplu: "Rogojesti", comuna: "Mihaileni" },
  { nume: "Roma" },
  { nume: "Românești-Vale", simplu: "Romanesti-Vale", comuna: "Romanesti" },
  { nume: "Românești", simplu: "Romanesti" },
  { nume: "Roșiori", simplu: "Rosiori", comuna: "Rachiti" },
  { nume: "Sadoveni", comuna: "Manoleasa" },
  { nume: "Santa Mare" },
  { nume: "Sarafinești", simplu: "Sarafinesti", comuna: "Corni" },
  { nume: "Sarata-Basarab", comuna: "Hanesti" },
  { nume: "Sarata-Drăgușeni", simplu: "Sarata-Draguseni", comuna: "Draguseni" },
  { nume: "Sarata", comuna: "Mihalaseni" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Romanesti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Vlasinesti" },
  { nume: "Sat Nou", comuna: "Saveni" },
  { nume: "Saucenița", simplu: "Saucenita", comuna: "Vaculesti" },
  { nume: "Săveni", simplu: "Saveni" },
  { nume: "Schit-Orășeni", simplu: "Schit-Oraseni", comuna: "Cristesti" },
  { nume: "Scutari", comuna: "Mileanca" },
  { nume: "Seliștea", simplu: "Selistea", comuna: "Mileanca" },
  { nume: "Șendreni", simplu: "Sendreni", comuna: "Frumusica" },
  { nume: "Șendriceni", simplu: "Sendriceni" },
  { nume: "Șerpenița", simplu: "Serpenita", comuna: "Manoleasa" },
  { nume: "Silișcani", simplu: "Siliscani", comuna: "Gorbanesti" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Stauceni" },
  { nume: "Slobozia Hănești", simplu: "Slobozia Hanesti", comuna: "Hanesti" },
  {
    nume: "Slobozia Silișcani",
    simplu: "Slobozia Siliscani",
    comuna: "Mihalaseni",
  },
  { nume: "Slobozia", comuna: "Broscauti" },
  { nume: "Slobozia", comuna: "Cordăreni" },
  { nume: "Slobozia", comuna: "Paltinis" },
  { nume: "Smârdan", simplu: "Smardan", comuna: "Suharau" },
  { nume: "Socrujeni", comuna: "Gorbanesti" },
  { nume: "Șoldănești", simplu: "Soldanesti", comuna: "Blindesti" },
  { nume: "Soroceni", comuna: "Unteni" },
  { nume: "Stânca", simplu: "Stanca", comuna: "George Enescu" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Stefanesti" },
  { nume: "Stâncești", simplu: "Stancesti", comuna: "Mihai Eminescu" },
  { nume: "Stăuceni", simplu: "Stauceni" },
  { nume: "Ștefănești-Sat", simplu: "Stefanesti-Sat", comuna: "Stefanesti" },
  { nume: "Ștefănești", simplu: "Stefanesti" },
  { nume: "Știubieni", simplu: "Stiubieni" },
  { nume: "Stolniceni", comuna: "Rauseni" },
  { nume: "Storești", simplu: "Storesti", comuna: "Frumusica" },
  { nume: "Strahotin", comuna: "Dangeni" },
  { nume: "Străteni", simplu: "Strateni", comuna: "Lozna" },
  { nume: "Stroiești", simplu: "Stroiesti", comuna: "Lunca" },
  { nume: "Suharău", simplu: "Suharau" },
  { nume: "Sulița", simplu: "Sulita" },
  { nume: "Șupitca", simplu: "Supitca", comuna: "Cosula" },
  { nume: "Talpa", comuna: "Candesti" },
  { nume: "Tătărășeni", simplu: "Tataraseni", comuna: "Havarna" },
  { nume: "Tăutești", simplu: "Tautesti", comuna: "Ungureni" },
  { nume: "Timuș", simplu: "Timus", comuna: "Avrameni" },
  { nume: "Tocileni", comuna: "Stauceni" },
  { nume: "Todireni" },
  { nume: "Trușești", simplu: "Trusesti" },
  { nume: "Tudor Vladimirescu", comuna: "Albesti" },
  { nume: "Tudor Vladimirescu", comuna: "Avrameni" },
  { nume: "Tudora" },
  { nume: "Ungureni" },
  { nume: "Unguroaia", comuna: "Cristesti" },
  { nume: "Unțeni", simplu: "Unteni" },
  { nume: "Văculești", simplu: "Vaculesti" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Braesti" },
  { nume: "Valea Grajdului", comuna: "Unteni" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Gorbanesti" },
  { nume: "Vârfu Câmpului", simplu: "Varfu Campului" },
  { nume: "Vatra", comuna: "Hudești" },
  { nume: "Vicoleni", comuna: "Ungureni" },
  { nume: "Victoria", comuna: "Hlipiceni" },
  { nume: "Victoria", comuna: "Stauceni" },
  { nume: "Viforeni", comuna: "Gorbanesti" },
  { nume: "Viișoara Mică", simplu: "Viisoara Mica", comuna: "Viisoara" },
  { nume: "Viișoara", simplu: "Viisoara" },
  { nume: "Vițcani", simplu: "Vitcani", comuna: "Candesti" },
  { nume: "Vlădeni-Deal", simplu: "Vladeni-Deal", comuna: "Frumusica" },
  { nume: "Vlădeni", simplu: "Vladeni" },
  { nume: "Vlădeni", simplu: "Vladeni", comuna: "Corlateni" },
  { nume: "Vlăsinești", simplu: "Vlasinesti" },
  { nume: "Vorniceni" },
  { nume: "Vorona Mare", comuna: "Vorona" },
  { nume: "Vorona-Teodoru", comuna: "Vorona" },
  { nume: "Vorona" },
  { nume: "Vultureni", comuna: "Unteni" },
  { nume: "Zahoreni", comuna: "Manoleasa" },
  { nume: "Zăicești", simplu: "Zaicesti", comuna: "Baluseni" },
  { nume: "Zlătunoaia", simplu: "Zlatunoaia", comuna: "Lunca" },
  { nume: "Zoițani", simplu: "Zoitani", comuna: "Avrameni" },
];
