export const bv = [
  { nume: "Acriş", simplu: "Acris", comuna: "Vama Buzaului" },
  { nume: "Apaţa", simplu: "Apata" },
  { nume: "Arini", comuna: "Maierus" },
  { nume: "Augustin", comuna: "Ormenis" },
  { nume: "Bărcut", simplu: "Barcut", comuna: "Soars" },
  { nume: "Beclean" },
  { nume: "Beia", comuna: "Cata" },
  { nume: "Berivoi", comuna: "Recea" },
  { nume: "Bod" },
  { nume: "Bogata Olteană", simplu: "Bogata Olteana", comuna: "Hoghiz" },
  { nume: "Boholţ", simplu: "Boholt", comuna: "Beclean" },
  { nume: "Bran" },
  { nume: "Braşov", simplu: "Brasov" },
  { nume: "Breaza", comuna: "Lisa" },
  { nume: "Bucium", comuna: "Sinca" },
  { nume: "Budila" },
  { nume: "Buneşti", simplu: "Bunesti" },
  { nume: "Buzăiel", simplu: "Buzaiel", comuna: "Vama Buzaului" },
  { nume: "Calbor", comuna: "Beclean" },
  { nume: "Cărpiniş", simplu: "Carpinis", comuna: "Tarlungeni" },
  { nume: "Caţa", simplu: "Cata" },
  { nume: "Cheia", comuna: "Moieciu" },
  { nume: "Cincşor", simplu: "Cincsor", comuna: "Voila" },
  { nume: "Cincu" },
  { nume: "Cobor", comuna: "Ticusu" },
  { nume: "Codlea" },
  { nume: "Colonia 1 Mai", comuna: "Vulcan" },
  { nume: "Colonia Bod", comuna: "Bod" },
  {
    nume: "Colonia Reconstrucţia",
    simplu: "Colonia Reconstructia",
    comuna: "Feldioara",
  },
  { nume: "Comana de Jos", comuna: "Comana" },
  { nume: "Comana de Sus", comuna: "Comana" },
  { nume: "Copăcel", simplu: "Copacel", comuna: "Harseni" },
  { nume: "Corbi", comuna: "Ucea" },
  { nume: "Crihalma", comuna: "Comana" },
  { nume: "Cristian" },
  { nume: "Criţ", simplu: "Crit", comuna: "Bunesti" },
  { nume: "Crizbav" },
  { nume: "Cuciulata", comuna: "Hoghiz" },
  { nume: "Cutuş", simplu: "Cutus", comuna: "Crizbav" },
  { nume: "Dacia", comuna: "Jibert" },
  { nume: "Dăişoara", simplu: "Daisoara", comuna: "Ungra" },
  { nume: "Dălghiu", simplu: "Dalghiu", comuna: "Vama Buzaului" },
  { nume: "Dejani", comuna: "Recea" },
  { nume: "Dopca", comuna: "Hoghiz" },
  { nume: "Drăguş", simplu: "Dragus", comuna: "Vistea" },
  { nume: "Drăuşeni", simplu: "Drauseni", comuna: "Cata" },
  { nume: "Dridif", comuna: "Voila" },
  { nume: "Drumul Carului", comuna: "Moieciu" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita" },
  { nume: "Făgăraş", simplu: "Fagaras" },
  { nume: "Fântâna", simplu: "Fantana", comuna: "Hoghiz" },
  { nume: "Feldioara" },
  { nume: "Feldioara", comuna: "Ucea" },
  { nume: "Felmer", comuna: "Soars" },
  { nume: "Fişer", simplu: "Fiser", comuna: "Rupea" },
  { nume: "Fundata" },
  { nume: "Fundăţica", simplu: "Fundatica", comuna: "Fundata" },
  { nume: "Ghimbav" },
  { nume: "Grânari", simplu: "Granari", comuna: "Jibert" },
  { nume: "Grid", comuna: "Parau" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Recea" },
  { nume: "Hălchiu", simplu: "Halchiu" },
  { nume: "Hălmeag", simplu: "Halmeag", comuna: "Sercaia" },
  { nume: "Hărman", simplu: "Harman" },
  { nume: "Hârseni", simplu: "Harseni" },
  { nume: "Hoghiz" },
  { nume: "Holbav", comuna: "Vulcan" },
  { nume: "Homorod" },
  { nume: "Hurez", comuna: "Beclean" },
  { nume: "Iaşi", simplu: "Iasi", comuna: "Recea" },
  { nume: "Ileni", comuna: "Mandra" },
  { nume: "Ioneşti", simplu: "Ionesti", comuna: "Cata" },
  { nume: "Jibert" },
  { nume: "Jimbor", comuna: "Homorod" },
  { nume: "Lisa" },
  { nume: "Lovnic", comuna: "Jibert" },
  { nume: "Ludişor", simplu: "Ludisor", comuna: "Voila" },
  { nume: "Lunca Calnicului", comuna: "Prejmer" },
  { nume: "Lupşa", simplu: "Lupsa", comuna: "Hoghiz" },
  { nume: "Luţa", simplu: "Luta", comuna: "Beclean" },
  { nume: "Măgura", simplu: "Magura", comuna: "Moieciu" },
  { nume: "Măieruş", simplu: "Maierus" },
  { nume: "Măliniş", simplu: "Malinis", comuna: "Harseni" },
  { nume: "Mândra", simplu: "Mandra" },
  { nume: "Mărgineni", simplu: "Margineni", comuna: "Harseni" },
  { nume: "Mateiaş", simplu: "Mateias", comuna: "Racos" },
  { nume: "Mercheaşa", simplu: "Mercheasa", comuna: "Homorod" },
  { nume: "Meşendorf", simplu: "Mesendorf", comuna: "Bunesti" },
  { nume: "Moieciu de Jos", comuna: "Moieciu" },
  { nume: "Moieciu de Sus", comuna: "Moieciu" },
  { nume: "Ohaba", comuna: "Sinca" },
  { nume: "Olteţ", simplu: "Oltet", comuna: "Vistea" },
  { nume: "Ormeniş", simplu: "Ormenis" },
  { nume: "Paloş", simplu: "Palos", comuna: "Cata" },
  { nume: "Paltin", comuna: "Sinca Noua" },
  { nume: "Părău", simplu: "Parau" },
  { nume: "Pârâul Rece", simplu: "Paraul Rece", comuna: "Predeal" },
  { nume: "Perşani", simplu: "Persani", comuna: "Sinca" },
  { nume: "Peştera", simplu: "Pestera", comuna: "Moieciu" },
  { nume: "Podu Oltului", comuna: "Harman" },
  { nume: "Poiana Braşov", simplu: "Poiana Brasov", comuna: "Brasov" },
  { nume: "Poiana Mărului", simplu: "Poiana Marului" },
  { nume: "Pojorta", comuna: "Lisa" },
  { nume: "Predeal" },
  { nume: "Predeluţ", simplu: "Predelut", comuna: "Bran" },
  { nume: "Prejmer" },
  { nume: "Purcăreni", simplu: "Purcareni", comuna: "Tarlungeni" },
  { nume: "Racoş", simplu: "Racos" },
  { nume: "Râşnov", simplu: "Rasnov" },
  { nume: "Râuşor", simplu: "Rausor", comuna: "Mandra" },
  { nume: "Recea" },
  { nume: "Roadeş", simplu: "Roades", comuna: "Bunesti" },
  { nume: "Rodbav", comuna: "Soars" },
  { nume: "Rotbav", comuna: "Feldioara" },
  { nume: "Rucăr", simplu: "Rucar", comuna: "Vistea" },
  { nume: "Rupea" },
  { nume: "Săcele", simplu: "Sacele" },
  { nume: "Sâmbăta de Jos", simplu: "Sambata de Jos", comuna: "Voila" },
  { nume: "Sâmbăta de Sus", simplu: "Sambata de Sus" },
  { nume: "Sânpetru", simplu: "Sanpetru" },
  { nume: "Săsciori", simplu: "Sasciori", comuna: "Recea" },
  { nume: "Satu Nou", comuna: "Halchiu" },
  { nume: "Săvăstreni", simplu: "Savastreni", comuna: "Recea" },
  { nume: "Sebeş", simplu: "Sebes", comuna: "Harseni" },
  { nume: "Seliştat", simplu: "Selistat", comuna: "Soars" },
  { nume: "Şercaia", simplu: "Sercaia" },
  { nume: "Şercăiţa", simplu: "Sercaita", comuna: "Sinca" },
  { nume: "Şimon", simplu: "Simon", comuna: "Bran" },
  { nume: "Şinca Nouă", simplu: "Sinca Noua" },
  { nume: "Şinca Veche", simplu: "Sinca Veche", comuna: "Sinca" },
  { nume: "Şirnea", simplu: "Sirnea", comuna: "Fundata" },
  { nume: "Şoarş", simplu: "Soars" },
  { nume: "Sohodol", comuna: "Bran" },
  { nume: "Şona", simplu: "Sona", comuna: "Mandra" },
  {
    nume: "Staţiunea Climaterică Sâmbăta",
    simplu: "Statiunea Climaterica Sambata",
    comuna: "Sambata De Sus",
  },
  { nume: "Stupinii Prejmerului", comuna: "Prejmer" },
  { nume: "Tărlungeni", simplu: "Tarlungeni" },
  { nume: "Teliu" },
  { nume: "Ticuşu Nou", simplu: "Ticusu Nou", comuna: "Comana" },
  { nume: "Ticuşu Vechi", simplu: "Ticusu Vechi", comuna: "Ticusu" },
  { nume: "Timişu de Jos", simplu: "Timisu de Jos", comuna: "Predeal" },
  { nume: "Timişu de Sus", simplu: "Timisu de Sus", comuna: "Predeal" },
  { nume: "Toarcla", comuna: "Cincu" },
  { nume: "Toderiţa", simplu: "Toderita", comuna: "Mandra" },
  { nume: "Tohanu Nou", comuna: "Zarnesti" },
  { nume: "Ucea de Jos", comuna: "Ucea" },
  { nume: "Ucea de Sus", comuna: "Ucea" },
  { nume: "Ungra" },
  { nume: "Vad", comuna: "Sercaia" },
  { nume: "Vâlcea", simplu: "Valcea", comuna: "Sinca" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Jibert" },
  { nume: "Vama Buzăului", simplu: "Vama Buzaului" },
  { nume: "Veneţia de Jos", simplu: "Venetia de Jos", comuna: "Parau" },
  { nume: "Veneţia de Sus", simplu: "Venetia de Sus", comuna: "Parau" },
  { nume: "Victoria" },
  { nume: "Viscri", comuna: "Bunesti" },
  { nume: "Viştea de Jos", simplu: "Vistea de Jos", comuna: "Vistea" },
  { nume: "Viştea de Sus", simplu: "Vistea de Sus", comuna: "Vistea" },
  { nume: "Viştişoara", simplu: "Vistisoara", comuna: "Vistea" },
  { nume: "Vlădeni", simplu: "Vladeni", comuna: "Dumbravita" },
  { nume: "Voila" },
  { nume: "Voivodeni", comuna: "Voila" },
  { nume: "Vulcan" },
  { nume: "Zărneşti", simplu: "Zarnesti" },
  { nume: "Zizin", comuna: "Tarlungeni" },
];
