export const bh = [
  { nume: "Abram" },
  { nume: "Abrămuț", simplu: "Abramut" },
  { nume: "Adoni", comuna: "Tarcea" },
  { nume: "Albești", simplu: "Albesti", comuna: "Rabagani" },
  { nume: "Albiș", simplu: "Albis", comuna: "Buduslau" },
  { nume: "Aleșd", simplu: "Alesd" },
  { nume: "Almașu Mare", simplu: "Almasu Mare", comuna: "Balc" },
  { nume: "Almașu Mic", simplu: "Almasu Mic", comuna: "Balc" },
  { nume: "Almașu Mic", simplu: "Almasu Mic", comuna: "Sarbi" },
  { nume: "Alparea", comuna: "Osorhei" },
  { nume: "Ant", comuna: "Avram Iancu" },
  { nume: "Apateu", comuna: "Nojorid" },
  { nume: "Arpășel", simplu: "Arpasel", comuna: "Batar" },
  { nume: "Aștileu", simplu: "Astileu" },
  { nume: "Ateaș", simplu: "Ateas", comuna: "Cefa" },
  { nume: "Aușeu", simplu: "Auseu" },
  { nume: "Avram Iancu" },
  { nume: "Băile Felix", simplu: "Baile Felix", comuna: "Sanmartin" },
  { nume: "Băița-Plai", simplu: "Baita-Plai", comuna: "Nucet" },
  { nume: "Băița", simplu: "Baita", comuna: "Nucet" },
  { nume: "Bălaia", simplu: "Balaia", comuna: "Tileagd" },
  { nume: "Balc" },
  { nume: "Bâlc", simplu: "Balc", comuna: "Cristioru De Jos" },
  { nume: "Băleni", simplu: "Baleni", comuna: "Lazuri De Beius" },
  { nume: "Bălnaca-Groși", simplu: "Balnaca-Grosi", comuna: "Suncuius" },
  { nume: "Bălnaca", simplu: "Balnaca", comuna: "Suncuius" },
  { nume: "Batăr", simplu: "Batar" },
  { nume: "Beiuș", simplu: "Beius" },
  { nume: "Beiușele", simplu: "Beiusele", comuna: "Curatele" },
  { nume: "Belejeni", comuna: "Draganesti" },
  { nume: "Belfir", comuna: "Tinca" },
  { nume: "Berechiu", comuna: "Sannicolau Roman" },
  { nume: "Betfia", comuna: "Sanmartin" },
  { nume: "Beznea", comuna: "Bratca" },
  { nume: "Bicăcel", simplu: "Bicacel", comuna: "Lazareni" },
  { nume: "Bicaci", comuna: "Gepiu" },
  { nume: "Biharia" },
  { nume: "Birtin", comuna: "Vadu Crisului" },
  { nume: "Bistra", comuna: "Popesti" },
  { nume: "Bogei", comuna: "Tauteu" },
  { nume: "Boianu Mare" },
  { nume: "Boiu", comuna: "Ciumeghiu" },
  { nume: "Borod" },
  { nume: "Borozel", comuna: "Borod" },
  { nume: "Borș", simplu: "Bors" },
  { nume: "Borșa", simplu: "Borsa", comuna: "Sacadat" },
  { nume: "Borumlaca", comuna: "Suplacu De Barcau" },
  { nume: "Borz", comuna: "Soimi" },
  { nume: "Botean", comuna: "Ineu" },
  { nume: "Brădet", simplu: "Bradet", comuna: "Buntesti" },
  { nume: "Bratca" },
  { nume: "Brătești", simplu: "Bratesti", comuna: "Rabagani" },
  { nume: "Briheni", comuna: "Lunca" },
  { nume: "Brusturi" },
  { nume: "Brusturi", comuna: "Finis" },
  { nume: "Bucium", comuna: "Ceica" },
  { nume: "Bucuroaia", comuna: "Copacel" },
  { nume: "Budoi", comuna: "Popesti" },
  { nume: "Budureasa" },
  { nume: "Buduslău", simplu: "Buduslau" },
  { nume: "Bulz" },
  { nume: "Buntești", simplu: "Buntesti" },
  { nume: "Burda", comuna: "Budureasa" },
  { nume: "Burzuc", comuna: "Sarbi" },
  { nume: "Butani", comuna: "Magesti" },
  { nume: "Căbești", simplu: "Cabesti" },
  { nume: "Cacuciu Nou", comuna: "Magesti" },
  { nume: "Cacuciu Vechi", comuna: "Auseu" },
  { nume: "Cadea", comuna: "Sacueni" },
  { nume: "Călacea", simplu: "Calacea", comuna: "Olcea" },
  { nume: "Călătani", simplu: "Calatani", comuna: "Tileagd" },
  { nume: "Călățea", simplu: "Calatea", comuna: "Astileu" },
  { nume: "Calea Mare", comuna: "Lazareni" },
  { nume: "Călugări", simplu: "Calugari", comuna: "Carpinet" },
  { nume: "Câmp-Moți", simplu: "Camp-Moti", comuna: "Vascau" },
  { nume: "Câmp", simplu: "Camp", comuna: "Vascau" },
  {
    nume: "Câmpani de Pomezeu",
    simplu: "Campani de Pomezeu",
    comuna: "Pomezeu",
  },
  { nume: "Câmpani", simplu: "Campani" },
  { nume: "Căpâlna", simplu: "Capalna" },
  { nume: "Cărăndeni", simplu: "Carandeni", comuna: "Lazareni" },
  { nume: "Cărănzel", simplu: "Caranzel", comuna: "Lazareni" },
  { nume: "Cărăsău", simplu: "Carasau", comuna: "Cociuba Mare" },
  { nume: "Cărpinet", simplu: "Carpinet" },
  { nume: "Cauaceu", comuna: "Biharia" },
  { nume: "Căuașd", simplu: "Cauasd", comuna: "Tulca" },
  { nume: "Cefa" },
  { nume: "Ceica" },
  { nume: "Ceișoara", simplu: "Ceisoara", comuna: "Ceica" },
  { nume: "Cenaloș", simplu: "Cenalos", comuna: "Ciuhoi" },
  { nume: "Cetariu" },
  { nume: "Cetea", comuna: "Borod" },
  { nume: "Cherechiu" },
  { nume: "Cheresig", comuna: "Girisu De Cris" },
  { nume: "Cheriu", comuna: "Osorhei" },
  { nume: "Cheșa", simplu: "Chesa", comuna: "Cociuba Mare" },
  { nume: "Cheșereu", simplu: "Chesereu", comuna: "Cherechiu" },
  { nume: "Cheț", simplu: "Chet", comuna: "Marghita" },
  { nume: "Chijic", comuna: "Copacel" },
  { nume: "Chioag", comuna: "Sarbi" },
  { nume: "Chiraleu", comuna: "Chislaz" },
  { nume: "Chiribiș", simplu: "Chiribis", comuna: "Tauteu" },
  { nume: "Chișcău", simplu: "Chiscau", comuna: "Pietroasa" },
  { nume: "Chișirid", simplu: "Chisirid", comuna: "Nojorid" },
  { nume: "Chișlaz", simplu: "Chislaz" },
  { nume: "Chistag", comuna: "Astileu" },
  { nume: "Cihei", comuna: "Sanmartin" },
  { nume: "Ciocaia", comuna: "Sacueni" },
  { nume: "Ciuhoi" },
  { nume: "Ciulești", simplu: "Ciulesti", comuna: "Spinus" },
  { nume: "Ciumeghiu" },
  { nume: "Ciutelec", comuna: "Tauteu" },
  { nume: "Cociuba Mare" },
  { nume: "Cociuba Mică", simplu: "Cociuba Mica", comuna: "Pietroasa" },
  { nume: "Codrișoru", simplu: "Codrisoru", comuna: "Auseu" },
  { nume: "Codru", comuna: "Soimi" },
  { nume: "Cohani", comuna: "Abram" },
  { nume: "Colești", simplu: "Colesti", comuna: "Vascau" },
  { nume: "Copăcel", simplu: "Copacel" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "Sambata" },
  { nume: "Corbești", simplu: "Corbesti", comuna: "Ceica" },
  { nume: "Corboaia", comuna: "Boianu Mare" },
  { nume: "Cordău", simplu: "Cordau", comuna: "Sanmartin" },
  { nume: "Cornișești", simplu: "Cornisesti", comuna: "Dobresti" },
  { nume: "Cornițel", simplu: "Cornitel", comuna: "Borod" },
  { nume: "Coșdeni", simplu: "Cosdeni", comuna: "Pomezeu" },
  { nume: "Cotiglet", comuna: "Ceica" },
  { nume: "Crâncești", simplu: "Crancesti", comuna: "Dobresti" },
  { nume: "Crestur", comuna: "Abramut" },
  { nume: "Cresuia", comuna: "Curatele" },
  { nume: "Criștioru de Jos", simplu: "Cristioru de Jos" },
  {
    nume: "Criștioru de Sus",
    simplu: "Cristioru de Sus",
    comuna: "Cristioru De Jos",
  },
  { nume: "Cubulcut", comuna: "Sacueni" },
  { nume: "Cucuceni", comuna: "Rieni" },
  { nume: "Cuieșd", simplu: "Cuiesd", comuna: "Brusturi" },
  { nume: "Curățele", simplu: "Curatele" },
  { nume: "Curtuișeni", simplu: "Curtuiseni" },
  { nume: "Cusuiuș", simplu: "Cusuius", comuna: "Lazuri De Beius" },
  { nume: "Cuzap", comuna: "Popesti" },
  { nume: "Damiș", simplu: "Damis", comuna: "Bratca" },
  { nume: "Delani", comuna: "Beius" },
  { nume: "Derna" },
  { nume: "Dernișoara", simplu: "Dernisoara", comuna: "Derna" },
  { nume: "Dicănești", simplu: "Dicanesti", comuna: "Dragesti" },
  { nume: "Dijir", comuna: "Abram" },
  { nume: "Diosig" },
  { nume: "Dobrești", simplu: "Dobresti" },
  { nume: "Dobricionești", simplu: "Dobricionesti", comuna: "Magesti" },
  { nume: "Dolea", comuna: "Suplacu De Barcau" },
  { nume: "Drăgănești", simplu: "Draganesti" },
  { nume: "Drăgești", simplu: "Dragesti" },
  { nume: "Drăgoteni", simplu: "Dragoteni", comuna: "Remetea" },
  { nume: "Dumbrava", comuna: "Holod" },
  { nume: "Dumbrăvani", simplu: "Dumbravani", comuna: "Buntesti" },
  {
    nume: "Dumbrăvița de Codru",
    simplu: "Dumbravita de Codru",
    comuna: "Soimi",
  },
  { nume: "Dumbrăvița", simplu: "Dumbravita", comuna: "Holod" },
  { nume: "Dușești", simplu: "Dusesti", comuna: "Ceica" },
  { nume: "Fânațe", simplu: "Fanate", comuna: "Campani" },
  { nume: "Făncica", simplu: "Fancica", comuna: "Abramut" },
  { nume: "Fâșca", simplu: "Fasca", comuna: "Varciorog" },
  { nume: "Fegernic", comuna: "Sarbi" },
  { nume: "Fegernicu Nou", comuna: "Sarbi" },
  { nume: "Felcheriu", comuna: "Osorhei" },
  { nume: "Feneriș", simplu: "Feneris", comuna: "Pocola" },
  { nume: "Ferice", comuna: "Buntesti" },
  { nume: "Finiș", simplu: "Finis" },
  { nume: "Fiziș", simplu: "Fizis", comuna: "Finis" },
  { nume: "Foglaș", simplu: "Foglas", comuna: "Suplacu De Barcau" },
  { nume: "Fonău", simplu: "Fonau", comuna: "Husasau De Tinca" },
  { nume: "Forău", simplu: "Forau", comuna: "Uileacu De Beius" },
  { nume: "Forosig", comuna: "Holod" },
  { nume: "Fughiu", comuna: "Osorhei" },
  { nume: "Gălășeni", simplu: "Galaseni", comuna: "Magesti" },
  { nume: "Galoșpetreu", simplu: "Galospetreu", comuna: "Tarcea" },
  { nume: "Gepiș", simplu: "Gepis", comuna: "Lazareni" },
  { nume: "Gepiu" },
  { nume: "Gheghie", comuna: "Auseu" },
  { nume: "Ghenetea", comuna: "Marghita" },
  { nume: "Ghida", comuna: "Balc" },
  { nume: "Ghighișeni", simplu: "Ghighiseni", comuna: "Rieni" },
  { nume: "Ghiorac", comuna: "Ciumeghiu" },
  { nume: "Ginta", comuna: "Capalna" },
  { nume: "Girișu de Criș", simplu: "Girisu de Cris" },
  { nume: "Girișu Negru", simplu: "Girisu Negru", comuna: "Tinca" },
  { nume: "Giulești", simplu: "Giulesti", comuna: "Pietroasa" },
  { nume: "Goila", comuna: "Cabesti" },
  { nume: "Grădinari", simplu: "Gradinari", comuna: "Draganesti" },
  { nume: "Groși", simplu: "Grosi", comuna: "Auseu" },
  { nume: "Gruilung", comuna: "Lazareni" },
  { nume: "Gurani", comuna: "Pietroasa" },
  { nume: "Gurbediu", comuna: "Tinca" },
  { nume: "Gurbești", simplu: "Gurbesti", comuna: "Cabesti" },
  { nume: "Gurbești", simplu: "Gurbesti", comuna: "Spinus" },
  { nume: "Haieu", comuna: "Sanmartin" },
  { nume: "Hârsești", simplu: "Harsesti", comuna: "Campani" },
  { nume: "Hăucești", simplu: "Haucesti", comuna: "Chislaz" },
  { nume: "Hidiș", simplu: "Hidis", comuna: "Pomezeu" },
  { nume: "Hidișel", simplu: "Hidisel", comuna: "Dobresti" },
  {
    nume: "Hidișelu de Jos",
    simplu: "Hidiselu de Jos",
    comuna: "Hidiselu De Sus",
  },
  { nume: "Hidișelu de Sus", simplu: "Hidiselu de Sus" },
  { nume: "Hinchiriș", simplu: "Hinchiris", comuna: "Lazuri De Beius" },
  { nume: "Hodiș", simplu: "Hodis", comuna: "Holod" },
  { nume: "Hodișel", simplu: "Hodisel", comuna: "Olcea" },
  { nume: "Hodoș", simplu: "Hodos", comuna: "Salard" },
  { nume: "Holod" },
  { nume: "Homorog", comuna: "Madaras" },
  { nume: "Hotar", comuna: "Tetchea" },
  { nume: "Hotărel", simplu: "Hotarel", comuna: "Lunca" },
  { nume: "Husasău de Criș", simplu: "Husasau de Cris", comuna: "Ineu" },
  { nume: "Husasău de Tinca", simplu: "Husasau de Tinca" },
  { nume: "Huta Voivozi", comuna: "Sinteu" },
  { nume: "Huta", comuna: "Boianu Mare" },
  { nume: "Ianca", comuna: "Diosig" },
  { nume: "Ianoșda", simplu: "Ianosda", comuna: "Madaras" },
  { nume: "Inand", comuna: "Cefa" },
  { nume: "Incești", simplu: "Incesti", comuna: "Ceica" },
  { nume: "Ineu" },
  { nume: "Ioaniș", simplu: "Ioanis", comuna: "Finis" },
  { nume: "Iteu Nou", comuna: "Abram" },
  { nume: "Iteu", comuna: "Abram" },
  { nume: "Izbuc", comuna: "Carpinet" },
  { nume: "Izvoarele", comuna: "Viisoara" },
  { nume: "Josani", comuna: "Cabesti" },
  { nume: "Josani", comuna: "Magesti" },
  { nume: "Lacu Sărat", simplu: "Lacu Sarat", comuna: "Pomezeu" },
  { nume: "Lăzăreni", simplu: "Lazareni" },
  { nume: "Lazuri de Beiuș", simplu: "Lazuri de Beius" },
  { nume: "Lazuri", comuna: "Rosia" },
  { nume: "Leheceni", comuna: "Carpinet" },
  { nume: "Lelești", simplu: "Lelesti", comuna: "Buntesti" },
  { nume: "Leș", simplu: "Les", comuna: "Nojorid" },
  {
    nume: "Livada Beiușului",
    simplu: "Livada Beiusului",
    comuna: "Draganesti",
  },
  { nume: "Livada de Bihor", comuna: "Nojorid" },
  { nume: "Loranta", comuna: "Brusturi" },
  { nume: "Lorău", simplu: "Lorau", comuna: "Bratca" },
  { nume: "Lugașu de Jos", simplu: "Lugasu de Jos" },
  { nume: "Lugașu de Sus", simplu: "Lugasu de Sus", comuna: "Lugasu De Jos" },
  { nume: "Lunca" },
  { nume: "Luncasprie", comuna: "Dobresti" },
  { nume: "Luncșoara", simplu: "Luncsoara", comuna: "Auseu" },
  { nume: "Lupoaia", comuna: "Holod" },
  { nume: "Mădăraș", simplu: "Madaras" },
  { nume: "Măgești", simplu: "Magesti" },
  { nume: "Măgura", simplu: "Magura", comuna: "Pietroasa" },
  { nume: "Marghita" },
  { nume: "Margine", comuna: "Abram" },
  { nume: "Marțihaz", simplu: "Martihaz", comuna: "Madaras" },
  { nume: "Meziad", comuna: "Remetea" },
  { nume: "Mierag", comuna: "Tarcaia" },
  { nume: "Mierlău", simplu: "Mierlau", comuna: "Hidiselu De Sus" },
  { nume: "Miersig", comuna: "Husasau De Tinca" },
  { nume: "Mihai Bravu", comuna: "Rosiori" },
  { nume: "Miheleu", comuna: "Lazareni" },
  { nume: "Mișca", simplu: "Misca", comuna: "Chislaz" },
  { nume: "Mizieș", simplu: "Mizies", comuna: "Draganesti" },
  { nume: "Moțești", simplu: "Motesti", comuna: "Pietroasa" },
  { nume: "Munteni", comuna: "Bulz" },
  { nume: "Nădar", simplu: "Nadar", comuna: "Spinus" },
  { nume: "Nimăiești", simplu: "Nimaiesti", comuna: "Curatele" },
  { nume: "Niuved", comuna: "Tamaseu" },
  { nume: "Nojorid" },
  { nume: "Nucet" },
  { nume: "Ogești", simplu: "Ogesti", comuna: "Sambata" },
  { nume: "Olcea" },
  { nume: "Olosig", comuna: "Sacueni" },
  { nume: "Oradea" },
  { nume: "Ortiteag", comuna: "Magesti" },
  { nume: "Orvișele", simplu: "Orvisele", comuna: "Brusturi" },
  { nume: "Oșand", simplu: "Osand", comuna: "Husasau De Tinca" },
  { nume: "Oșorhei", simplu: "Osorhei" },
  { nume: "Otomani", comuna: "Salacea" },
  { nume: "Păcălești", simplu: "Pacalesti", comuna: "Drăgănești" },
  { nume: "Pădurea Neagră", simplu: "Padurea Neagra", comuna: "Alesd" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Viisoara" },
  { nume: "Păgaia", simplu: "Pagaia", comuna: "Boianu Mare" },
  { nume: "Paleu" },
  { nume: "Palota", comuna: "Santandrei" },
  { nume: "Păntășești", simplu: "Pantasesti", comuna: "Draganesti" },
  { nume: "Parhida", comuna: "Tamaseu" },
  { nume: "Păulești", simplu: "Paulesti", comuna: "Brusturi" },
  { nume: "Păușa", simplu: "Pausa", comuna: "Nojorid" },
  { nume: "Peștere", simplu: "Pestere", comuna: "Astileu" },
  { nume: "Peștiș", simplu: "Pestis", comuna: "Alesd" },
  { nume: "Petid", comuna: "Cociuba Mare" },
  { nume: "Petrani", comuna: "Pocola" },
  { nume: "Petreasa", comuna: "Remetea" },
  { nume: "Petreu", comuna: "Abramut" },
  { nume: "Petrileni", comuna: "Rieni" },
  { nume: "Picleu", comuna: "Brusturi" },
  { nume: "Pietroasa" },
  { nume: "Pocioveliște", simplu: "Pocioveliste", comuna: "Curatele" },
  { nume: "Poclușa de Barcău", simplu: "Poclusa de Barcau", comuna: "Chislaz" },
  { nume: "Poclușa de Beiuș", simplu: "Poclusa de Beius", comuna: "Soimi" },
  { nume: "Pocola" },
  { nume: "Poiana Tășad", simplu: "Poiana Tasad", comuna: "Copacel" },
  { nume: "Poiana", comuna: "Cristioru De Jos" },
  { nume: "Poiana", comuna: "Tauteu" },
  { nume: "Poienii de Jos", comuna: "Buntesti" },
  { nume: "Poienii de Sus", comuna: "Buntesti" },
  { nume: "Poietari", comuna: "Pocola" },
  { nume: "Pomezeu" },
  { nume: "Ponoară", simplu: "Ponoara", comuna: "Bratca" },
  { nume: "Popești", simplu: "Popesti" },
  { nume: "Poșoloaca", simplu: "Posoloaca", comuna: "Tileagd" },
  { nume: "Prisaca", comuna: "Uileacu De Beius" },
  { nume: "Răbăgani", simplu: "Rabagani" },
  { nume: "Răcaș", simplu: "Racas", comuna: "Dobresti" },
  { nume: "Râpa", simplu: "Rapa", comuna: "Tinca" },
  { nume: "Reghea", comuna: "Viisoara" },
  { nume: "Remetea" },
  { nume: "Remeți", simplu: "Remeti", comuna: "Bulz" },
  { nume: "Rieni" },
  { nume: "Rogoz", comuna: "Sambata" },
  { nume: "Rohani", comuna: "Capalna" },
  { nume: "Roit", comuna: "Sannicolau Roman" },
  { nume: "Rontău", simplu: "Rontau", comuna: "Sanmartin" },
  { nume: "Roșia", simplu: "Rosia" },
  { nume: "Roșiori", simplu: "Rosiori" },
  { nume: "Rotărești", simplu: "Rotaresti", comuna: "Sambata" },
  { nume: "Rugea", comuna: "Boianu Mare" },
  { nume: "Săbolciu", simplu: "Sabolciu", comuna: "Sacadat" },
  { nume: "Saca", comuna: "Budureasa" },
  { nume: "Săcădat", simplu: "Sacadat" },
  { nume: "Sacalasău Nou", simplu: "Sacalasau Nou", comuna: "Derna" },
  { nume: "Sacalasău", simplu: "Sacalasau", comuna: "Derna" },
  { nume: "Săcueni", simplu: "Sacueni" },
  { nume: "Sălacea", simplu: "Salacea" },
  { nume: "Sălard", simplu: "Salard" },
  {
    nume: "Săldăbagiu de Barcău",
    simplu: "Saldabagiu de Barcau",
    comuna: "Balc",
  },
  {
    nume: "Săldăbagiu de Munte",
    simplu: "Saldabagiu de Munte",
    comuna: "Paleu",
  },
  { nume: "Săldăbagiu Mic", simplu: "Saldabagiu Mic", comuna: "Capalna" },
  { nume: "Săliște de Beiuș", simplu: "Saliste de Beius", comuna: "Budureasa" },
  {
    nume: "Saliște de Pomezeu",
    simplu: "Saliste de Pomezeu",
    comuna: "Rabagani",
  },
  {
    nume: "Săliște de Vașcău",
    simplu: "Saliste de Vascau",
    comuna: "Cristioru De Jos",
  },
  { nume: "Săliște", simplu: "Saliste", comuna: "Spinus" },
  { nume: "Salonta" },
  { nume: "Sâmbăta", simplu: "Sambata" },
  { nume: "Sâniob", simplu: "Saniob", comuna: "Ciuhoi" },
  { nume: "Sânlazăr", simplu: "Sanlazar", comuna: "Chislaz" },
  {
    nume: "Sânmartin de Beiuș",
    simplu: "Sanmartin de Beius",
    comuna: "Pocola",
  },
  { nume: "Sânmartin", simplu: "Sanmartin" },
  {
    nume: "Sânnicolau de Beiuș",
    simplu: "Sannicolau de Beius",
    comuna: "Soimi",
  },
  {
    nume: "Sânnicolau de Munte",
    simplu: "Sannicolau de Munte",
    comuna: "Sacueni",
  },
  { nume: "Sânnicolau Român", simplu: "Sannicolau Roman" },
  { nume: "Sântandrei", simplu: "Santandrei" },
  { nume: "Santăul Mare", simplu: "Santaul Mare", comuna: "Bors" },
  { nume: "Santăul Mic", simplu: "Santaul Mic", comuna: "Bors" },
  { nume: "Sântelec", simplu: "Santelec", comuna: "Hidiselu De Sus" },
  { nume: "Sântimreu", simplu: "Santimreu", comuna: "Salard" },
  { nume: "Sântion", simplu: "Santion", comuna: "Bors" },
  { nume: "Sărand", simplu: "Sarand", comuna: "Copacel" },
  { nume: "Sârbești", simplu: "Sarbesti", comuna: "Lunca" },
  { nume: "Sârbi", simplu: "Sarbi" },
  { nume: "Sarcău", simplu: "Sarcau", comuna: "Sarbi" },
  { nume: "Sărsig", simplu: "Sarsig", comuna: "Chislaz" },
  { nume: "Satu Barbă", simplu: "Satu Barba", comuna: "Abram" },
  { nume: "Satu Nou", comuna: "Tamaseu" },
  { nume: "Șauaieu", simplu: "Sauaieu", comuna: "Nojorid" },
  { nume: "Săucani", simplu: "Saucani", comuna: "Rabagani" },
  { nume: "Săud", simplu: "Saud", comuna: "Buntesti" },
  { nume: "Șebiș", simplu: "Sebis", comuna: "Draganesti" },
  { nume: "Seghiște", simplu: "Seghiste", comuna: "Lunca" },
  { nume: "Șerani", simplu: "Serani", comuna: "Borod" },
  { nume: "Șerghiș", simplu: "Serghis", comuna: "Varciorog" },
  { nume: "Sfârnaș", simplu: "Sfarnas", comuna: "Ciuhoi" },
  { nume: "Sighiștel", simplu: "Sighistel", comuna: "Campani" },
  { nume: "Șilindru", simplu: "Silindru", comuna: "Simian" },
  { nume: "Șimian", simplu: "Simian" },
  { nume: "Șinteu", simplu: "Sinteu" },
  { nume: "Șișterea", simplu: "Sisterea", comuna: "Cetariu" },
  { nume: "Sitani", comuna: "Pomezeu" },
  { nume: "Sititelec", comuna: "Husasau De Tinca" },
  { nume: "Socet", comuna: "Sinteu" },
  { nume: "Sohodol", comuna: "Cabesti" },
  { nume: "Șoimi", simplu: "Soimi" },
  { nume: "Soimuș", simplu: "Soimus", comuna: "Remetea" },
  { nume: "Spinuș de Pomezeu", simplu: "Spinus de Pomezeu", comuna: "Pomezeu" },
  { nume: "Spinuș", simplu: "Spinus" },
  { nume: "Stâncești", simplu: "Stancesti", comuna: "Buntesti" },
  { nume: "Ștei", simplu: "Stei" },
  { nume: "Stracoș", simplu: "Stracos", comuna: "Dragesti" },
  { nume: "Subpiatră", simplu: "Subpiatra", comuna: "Tetchea" },
  { nume: "Sudrigiu", comuna: "Rieni" },
  { nume: "Suiug", comuna: "Abram" },
  { nume: "Șumugiu", simplu: "Sumugiu", comuna: "Hidiselu De Sus" },
  { nume: "Șuncuiș", simplu: "Suncuis", comuna: "Finis" },
  { nume: "Șuncuiuș", simplu: "Suncuius" },
  { nume: "Suplacu de Barcău", simplu: "Suplacu de Barcau" },
  { nume: "Suplacu de Tinca", comuna: "Capalna" },
  { nume: "Surduc", comuna: "Copacel" },
  { nume: "Surducel", comuna: "Varciorog" },
  { nume: "Șuștiu", simplu: "Sustiu", comuna: "Lunca" },
  { nume: "Șușturogi", simplu: "Susturogi", comuna: "Cetariu" },
  { nume: "Talpe", comuna: "Draganesti" },
  { nume: "Talpoș", simplu: "Talpos", comuna: "Batar" },
  { nume: "Tămașda", simplu: "Tamasda", comuna: "Avram Iancu" },
  { nume: "Tămășeu", simplu: "Tamaseu" },
  { nume: "Tărcaia", simplu: "Tarcaia" },
  { nume: "Tărcăița", simplu: "Tarcaita", comuna: "Tarcaia" },
  { nume: "Tarcea" },
  { nume: "Târgușor", simplu: "Targusor", comuna: "Cherechiu" },
  { nume: "Tărian", simplu: "Tarian", comuna: "Girisu De Cris" },
  { nume: "Tășad", simplu: "Tasad", comuna: "Dragesti" },
  { nume: "Tăut", simplu: "Taut", comuna: "Batar" },
  { nume: "Tăutelec", simplu: "Tautelec", comuna: "Cetariu" },
  { nume: "Tăuteu", simplu: "Tauteu" },
  { nume: "Teleac", comuna: "Budureasa" },
  { nume: "Telechiu", comuna: "Tetchea" },
  { nume: "Țețchea", simplu: "Tetchea" },
  {
    nume: "Țigăneștii de Beiuș",
    simplu: "Tiganestii de Beius",
    comuna: "Draganesti",
  },
  {
    nume: "Țigăneștii de Criș",
    simplu: "Tiganestii de Cris",
    comuna: "Brusturi",
  },
  { nume: "Tileagd" },
  { nume: "Tilecuș", simplu: "Tilecus", comuna: "Tileagd" },
  { nume: "Tinăud", simplu: "Tinaud", comuna: "Alesd" },
  { nume: "Tinca" },
  { nume: "Toboliu", comuna: "Girisu De Cris" },
  { nume: "Tomnatic", comuna: "Vadu Crisului" },
  { nume: "Topa de Criș", simplu: "Topa de Cris", comuna: "Vadu Crisului" },
  { nume: "Topa de Jos", comuna: "Dobresti" },
  { nume: "Topa de Sus", comuna: "Dobresti" },
  { nume: "Topești", simplu: "Topesti", comuna: "Dragesti" },
  { nume: "Totoreni", comuna: "Tarcaia" },
  { nume: "Tria", comuna: "Derna" },
  { nume: "Tulca" },
  { nume: "Ucuriș", simplu: "Ucuris", comuna: "Olcea" },
  { nume: "Uileacu de Beiuș", simplu: "Uileacu de Beius" },
  { nume: "Uileacu de Criș", simplu: "Uileacu de Cris", comuna: "Tileagd" },
  { nume: "Uileacu de Munte", comuna: "Paleu" },
  { nume: "Ursad", comuna: "Soimi" },
  { nume: "Urvind", comuna: "Lugasu De Jos" },
  { nume: "Urviș de Beiuș", simplu: "Urvis de Beius", comuna: "Soimi" },
  { nume: "Vadu Crișului", simplu: "Vadu Crisului" },
  { nume: "Vaida", comuna: "Rosiori" },
  { nume: "Vălani de Pomezeu", simplu: "Valani de Pomezeu", comuna: "Pomezeu" },
  {
    nume: "Vălanii de Beiuș",
    simplu: "Valanii de Beius",
    comuna: "Uileacu De Beius",
  },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Suplacu De Barcau" },
  { nume: "Valea Cerului", comuna: "Suplacu De Barcau" },
  { nume: "Valea Crișului", simplu: "Valea Crisului", comuna: "Bratca" },
  { nume: "Valea de Jos", comuna: "Rieni" },
  { nume: "Valea de Sus", comuna: "Campani" },
  { nume: "Valea lui Mihai" },
  { nume: "Valea Mare de Codru", comuna: "Holod" },
  { nume: "Valea Mare de Criș", simplu: "Valea Mare de Cris", comuna: "Borod" },
  { nume: "Valea Târnei", simplu: "Valea Tarnei", comuna: "Sinteu" },
  { nume: "Varasău", simplu: "Varasau", comuna: "Brusturi" },
  { nume: "Vărășeni", simplu: "Varaseni", comuna: "Rabagani" },
  { nume: "Vârciorog", simplu: "Varciorog" },
  { nume: "Varviz", comuna: "Popesti" },
  { nume: "Vărzari", simplu: "Varzari", comuna: "Popesti" },
  { nume: "Vărzarii de Jos", simplu: "Varzarii de Jos", comuna: "Vascau" },
  { nume: "Vărzarii de Sus", simplu: "Varzarii de Sus", comuna: "Vascau" },
  { nume: "Vășad", simplu: "Vasad", comuna: "Curtuiseni" },
  { nume: "Vașcău", simplu: "Vascau" },
  { nume: "Viișoara", simplu: "Viisoara" },
  { nume: "Vintere", comuna: "Holod" },
  { nume: "Voivozi", comuna: "Popesti" },
  { nume: "Voivozi", comuna: "Simian" },
  { nume: "Zăvoiu", simplu: "Zavoiu", comuna: "Sambata" },
  { nume: "Zece Hotare", comuna: "Suncuius" },
];
