export const bn = [
  { nume: "Agrieș", simplu: "Agries", comuna: "Tarlisua" },
  { nume: "Agrieșel", simplu: "Agriesel", comuna: "Tarlisua" },
  { nume: "Agrișu de Jos", simplu: "Agrisu de Jos", comuna: "Sieu-Odorhei" },
  { nume: "Agrișu de Sus", simplu: "Agrisu de Sus", comuna: "Sieu-Odorhei" },
  {
    nume: "Albeștii Bistriței",
    simplu: "Albestii Bistritei",
    comuna: "Galatii Bistritei",
  },
  { nume: "Alunișul", simplu: "Alunisul", comuna: "Zagra" },
  { nume: "Anieș", simplu: "Anies", comuna: "Maieru" },
  { nume: "Apatiu", comuna: "Chiochis" },
  { nume: "Arcalia", comuna: "Sieu-Magherus" },
  { nume: "Archiud", comuna: "Teaca" },
  { nume: "Ardan", comuna: "Sieu" },
  { nume: "Arșița", simplu: "Arsita", comuna: "Magura Ilvei" },
  { nume: "Bârla", simplu: "Barla", comuna: "Mariselu" },
  { nume: "Bața", simplu: "Bata", comuna: "Petru Rares" },
  { nume: "Beclean" },
  { nume: "Beudiu", comuna: "Nuseni" },
  { nume: "Bichigiu", comuna: "Cosbuc" },
  { nume: "Bidiu", comuna: "Matei" },
  { nume: "Bistrița Bârgăului", simplu: "Bistrita Bargaului" },
  { nume: "Bistrița", simplu: "Bistrita" },
  { nume: "Blăjenii de Jos", simplu: "Blajenii de Jos", comuna: "Sintereag" },
  { nume: "Blăjenii de Sus", simplu: "Blajenii de Sus", comuna: "Sintereag" },
  { nume: "Borleasa", comuna: "Tarlisua" },
  { nume: "Bozieș", simplu: "Bozies", comuna: "Chiochis" },
  { nume: "Braniștea", simplu: "Branistea" },
  { nume: "Brăteni", simplu: "Brateni", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Breaza", comuna: "Negrilesti" },
  { nume: "Bretea", comuna: "Sieu-Odorhei" },
  { nume: "Budacu de Jos" },
  { nume: "Budacu de Sus", comuna: "Dumitrita" },
  { nume: "Budești-Fânațe", simplu: "Budesti-Fanate", comuna: "Budesti" },
  { nume: "Budești", simplu: "Budesti" },
  { nume: "Budurleni", comuna: "Teaca" },
  { nume: "Buduș", simplu: "Budus", comuna: "Budacu De Jos" },
  { nume: "Bungard", comuna: "Lechinta" },
  { nume: "Buza Cătun", simplu: "Buza Catun", comuna: "Chiochis" },
  { nume: "Căianu Mare", simplu: "Caianu Mare", comuna: "Caianu Mic" },
  { nume: "Căianu Mic", simplu: "Caianu Mic" },
  { nume: "Caila", comuna: "Sintereag" },
  { nume: "Câmp", simplu: "Camp", comuna: "Urmenis" },
  { nume: "Cepari", comuna: "Dumitra" },
  { nume: "Chețiu", simplu: "Chetiu", comuna: "Chiochis" },
  { nume: "Chintelnic", comuna: "Sieu-Magherus" },
  { nume: "Chiochiș", simplu: "Chiochis" },
  { nume: "Chiraleș", simplu: "Chirales", comuna: "Lechinta" },
  { nume: "Chiuza" },
  { nume: "Ciceu-Corabia", comuna: "Petru Rares" },
  { nume: "Ciceu-Giurgești", simplu: "Ciceu-Giurgesti" },
  { nume: "Ciceu-Mihăiești", simplu: "Ciceu-Mihaiesti", comuna: "Petru Rares" },
  { nume: "Ciceu-Poieni", comuna: "Caianu Mic" },
  { nume: "Ciosa", comuna: "Tiha Bargaului" },
  { nume: "Cireași", simplu: "Cireasi", comuna: "Tarlisua" },
  { nume: "Cireșoaia", simplu: "Ciresoaia", comuna: "Branistea" },
  { nume: "Coasta", comuna: "Sieu-Odorhei" },
  { nume: "Cociu", comuna: "Sintereag" },
  { nume: "Coldău", simplu: "Coldau", comuna: "Beclean" },
  { nume: "Colibița", simplu: "Colibita", comuna: "Bistrita Bargaului" },
  { nume: "Comlod", comuna: "Milas" },
  { nume: "Cormaia", comuna: "Sangeorz-Bai" },
  { nume: "Corvinești", simplu: "Corvinesti", comuna: "Matei" },
  { nume: "Coșbuc", simplu: "Cosbuc" },
  { nume: "Coșeriu", simplu: "Coseriu", comuna: "Urmenis" },
  { nume: "Crainimăt", simplu: "Crainimat", comuna: "Sieu-Magherus" },
  {
    nume: "Cristeștii Ciceului",
    simplu: "Cristestii Ciceului",
    comuna: "Uriu",
  },
  { nume: "Cristur-Șieu", simplu: "Cristur-Sieu", comuna: "Sieu-Odorhei" },
  { nume: "Cușma", simplu: "Cusma", comuna: "Livezile" },
  { nume: "Dealu Ștefăniței", simplu: "Dealu Stefanitei", comuna: "Romuli" },
  { nume: "Delureni", comuna: "Urmenis" },
  { nume: "Dipșa", simplu: "Dipsa", comuna: "Galatii Bistritei" },
  { nume: "Dobric", comuna: "Caianu Mic" },
  { nume: "Dobricel", comuna: "Caianu Mic" },
  { nume: "Domnești", simplu: "Domnesti", comuna: "Mariselu" },
  { nume: "Dorolea", comuna: "Livezile" },
  { nume: "Draga", comuna: "Silivasu De Cimpie" },
  { nume: "Dumbrava", comuna: "Livezile" },
  { nume: "Dumbrava", comuna: "Nuseni" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Ciceu-Giurgesti" },
  { nume: "Dumbrăvița", simplu: "Dumbravita", comuna: "Caianu Mic" },
  { nume: "Dumitra" },
  { nume: "Dumitrița", simplu: "Dumitrita" },
  { nume: "Dupa Deal", comuna: "Milas" },
  { nume: "Enciu", comuna: "Matei" },
  { nume: "Fânațe", simplu: "Fanate", comuna: "Urmenis" },
  {
    nume: "Fânațele Silivașului",
    simplu: "Fanatele Silivasului",
    comuna: "Silivasu De Cimpie",
  },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Matei" },
  { nume: "Fântânița", simplu: "Fantanita", comuna: "Micestii De Campie" },
  { nume: "Feldru" },
  { nume: "Feleac", comuna: "Nuseni" },
  { nume: "Fiad", comuna: "Telciu" },
  { nume: "Figa", comuna: "Beclean" },
  { nume: "Florești", simplu: "Floresti", comuna: "Nimigea" },
  { nume: "Galații Bistriței", simplu: "Galatii Bistritei" },
  { nume: "Gersa I", comuna: "Rebrisoara" },
  { nume: "Gersa Ii", comuna: "Rebrisoara" },
  { nume: "Ghemeș", simplu: "Ghemes", comuna: "Milas" },
  { nume: "Ghinda", comuna: "Bistrita" },
  { nume: "Gledin", comuna: "Monor" },
  { nume: "Hălmăsău", simplu: "Halmasau", comuna: "Spermezeu" },
  { nume: "Hășmașu Ciceului", simplu: "Hasmasu Ciceului", comuna: "Uriu" },
  { nume: "Herina", comuna: "Galatii Bistritei" },
  { nume: "Hirean", comuna: "Milas" },
  { nume: "Ilișua", simplu: "Ilisua", comuna: "Uriu" },
  { nume: "Ilva Mare" },
  { nume: "Ilva Mica" },
  { nume: "Ivăneasa", simplu: "Ivaneasa", comuna: "Ilva Mare" },
  { nume: "Jeica", comuna: "Mariselu" },
  { nume: "Jelna", comuna: "Budacu De Jos" },
  { nume: "Jimbor", comuna: "Chiochis" },
  { nume: "Josenii Bârgăului", simplu: "Josenii Bargaului" },
  { nume: "La Curte", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Lechința", simplu: "Lechinta" },
  { nume: "Lelești", simplu: "Lelesti", comuna: "Petru Rares" },
  { nume: "Leșu", simplu: "Lesu" },
  { nume: "Livezile" },
  { nume: "Liviu Rebreanu", comuna: "Nasaud" },
  { nume: "Lunca Borlesei", comuna: "Spermezeu" },
  { nume: "Lunca Ilvei" },
  { nume: "Lunca Leșului", simplu: "Lunca Lesului", comuna: "Lesu" },
  { nume: "Lunca Săteasca", simplu: "Lunca Sateasca", comuna: "Tarlisua" },
  { nume: "Lunca", comuna: "Sieut" },
  { nume: "Lușca", simplu: "Lusca", comuna: "Nasaud" },
  { nume: "Măgura Ilvei", simplu: "Magura Ilvei" },
  { nume: "Măgurele", simplu: "Magurele", comuna: "Mariselu" },
  { nume: "Maieru" },
  { nume: "Malin", comuna: "Nuseni" },
  { nume: "Măluț", simplu: "Malut", comuna: "Branistea" },
  { nume: "Manic", comuna: "Chiochis" },
  { nume: "Mărișelu", simplu: "Mariselu" },
  { nume: "Matei" },
  { nume: "Miceștii de Câmpie", simplu: "Micestii de Campie" },
  {
    nume: "Mijlocenii Bârgăului",
    simplu: "Mijlocenii Bargaului",
    comuna: "Josenii Bargaului",
  },
  { nume: "Milaș", simplu: "Milas" },
  { nume: "Mintiu", comuna: "Nimigea" },
  { nume: "Mireș", simplu: "Mires", comuna: "Chiuza" },
  { nume: "Mititei", comuna: "Nimigea" },
  { nume: "Mocod", comuna: "Nimigea" },
  { nume: "Mogoșeni", simplu: "Mogoseni", comuna: "Nimigea" },
  { nume: "Molișet", simplu: "Moliset", comuna: "Tarlisua" },
  { nume: "Monariu", comuna: "Budacu De Jos" },
  { nume: "Monor" },
  { nume: "Moruț", simplu: "Morut", comuna: "Matei" },
  {
    nume: "Mureșenii Bârgăului",
    simplu: "Muresenii Bargaului",
    comuna: "Tiha Bargaului",
  },
  { nume: "Năsăud", simplu: "Nasaud" },
  { nume: "Negrilești", simplu: "Negrilesti" },
  { nume: "Nepos", comuna: "Feldru" },
  { nume: "Nețeni", simplu: "Neteni", comuna: "Mariselu" },
  { nume: "Nimigea de Jos", comuna: "Nimigea" },
  { nume: "Nimigea de Sus", comuna: "Nimigea" },
  { nume: "Nușeni", simplu: "Nuseni" },
  { nume: "Oarzina", comuna: "Tarlisua" },
  { nume: "Ocnița", simplu: "Ocnita", comuna: "Teaca" },
  { nume: "Orheiu Bistriței", simplu: "Orheiu Bistritei", comuna: "Cetate" },
  { nume: "Orosfaia", comuna: "Milas" },
  { nume: "Păltineasa", simplu: "Paltineasa", comuna: "Spermezeu" },
  { nume: "Parva" },
  { nume: "Perișor", simplu: "Perisor", comuna: "Zagra" },
  { nume: "Petriș", simplu: "Petris", comuna: "Cetate" },
  {
    nume: "Piatra Fântânele",
    simplu: "Piatra Fantanele",
    comuna: "Tiha Bargaului",
  },
  { nume: "Piatra", comuna: "Chiuza" },
  { nume: "Pinticu", comuna: "Teaca" },
  { nume: "Podenii", comuna: "Urmenis" },
  { nume: "Poderei", comuna: "Rebrisoara" },
  { nume: "Podirei", comuna: "Sieu-Magherus" },
  { nume: "Poiana Ilvei" },
  { nume: "Poienile Zagrei", comuna: "Zagra" },
  { nume: "Porumbenii", comuna: "Silivasu De Cimpie" },
  { nume: "Posmuș", simplu: "Posmus", comuna: "Sieu" },
  { nume: "Prundu Bârgăului", simplu: "Prundu Bargaului" },
  { nume: "Purcărete", simplu: "Purcarete", comuna: "Negrilesti" },
  { nume: "Răcăteșu", simplu: "Racatesu", comuna: "Tarlisua" },
  { nume: "Ragla", comuna: "Dumitrita" },
  { nume: "Rebra" },
  { nume: "Rebrișoara", simplu: "Rebrisoara" },
  { nume: "Reteag", comuna: "Petru Rares" },
  { nume: "Rodna" },
  { nume: "Romuli" },
  { nume: "Runcu Salvei", comuna: "Salva" },
  { nume: "Ruștior", simplu: "Rustior", comuna: "Sieut" },
  {
    nume: "Rusu Bârgăului",
    simplu: "Rusu Bargaului",
    comuna: "Josenii Bargaului",
  },
  { nume: "Rusu de Jos", comuna: "Beclean" },
  { nume: "Rusu de Sus", comuna: "Nuseni" },
  { nume: "Sălcuța", simplu: "Salcuta", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Salva" },
  { nume: "Sângeorz-Băi", simplu: "Sangeorz-Bai" },
  { nume: "Sângeorzu Nou", simplu: "Sangeorzu Nou", comuna: "Lechinta" },
  { nume: "Sâniacob", simplu: "Saniacob", comuna: "Lechinta" },
  {
    nume: "Sânmihaiu de Câmpie",
    simplu: "Sanmihaiu de Campie",
    comuna: "Sanmihaiu De Cimpie",
  },
  { nume: "Sânnicoară", simplu: "Sannicoara", comuna: "Chiochis" },
  { nume: "Șanț", simplu: "Sant" },
  { nume: "Sântioana", simplu: "Santioana", comuna: "Mariselu" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Bistrita" },
  { nume: "Sărățel", simplu: "Saratel", comuna: "Sieu-Magherus" },
  { nume: "Săsarm", simplu: "Sasarm", comuna: "Chiuza" },
  { nume: "Satu Nou", comuna: "Cetate" },
  { nume: "Scoabe", comuna: "Urmenis" },
  { nume: "Sebiș", simplu: "Sebis", comuna: "Sieut" },
  { nume: "Șendroaia", simplu: "Sendroaia", comuna: "Tarlisua" },
  {
    nume: "Șeșuri Spermezeu-Vale",
    simplu: "Sesuri Spermezeu-Vale",
    comuna: "Spermezeu",
  },
  { nume: "Șieu-Măgheruș", simplu: "Sieu-Magherus" },
  { nume: "Șieu-Odorhei", simplu: "Sieu-Odorhei" },
  { nume: "Șieu-Sfântu", simplu: "Sieu-Sfantu", comuna: "Sintereag" },
  { nume: "Șieu", simplu: "Sieu" },
  { nume: "Șieuț", simplu: "Sieut" },
  { nume: "Sigmir", comuna: "Bistrita" },
  {
    nume: "Silivașu de Câmpie",
    simplu: "Silivasu de Campie",
    comuna: "Silivasu De Cimpie",
  },
  { nume: "Simionești", simplu: "Simionesti", comuna: "Budacu De Jos" },
  { nume: "Șintereag-Gară", simplu: "Sintereag-Gara", comuna: "Sintereag" },
  { nume: "Șintereag", simplu: "Sintereag" },
  { nume: "Șirioara", simplu: "Sirioara", comuna: "Sieu-Odorhei" },
  { nume: "Sita", comuna: "Spermezeu" },
  { nume: "Slătinița", simplu: "Slatinita", comuna: "Bistrita" },
  { nume: "Șoimuș", simplu: "Soimus", comuna: "Sieu" },
  { nume: "Șopteriu", simplu: "Sopteriu", comuna: "Urmenis" },
  { nume: "Spermezeu" },
  { nume: "Strâmba", simplu: "Stramba", comuna: "Josenii Bargaului" },
  { nume: "Strugureni", comuna: "Chiochis" },
  { nume: "Stupini", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Suplai", comuna: "Zagra" },
  {
    nume: "Susenii Bârgăului",
    simplu: "Susenii Bargaului",
    comuna: "Prundu Bargaului",
  },
  { nume: "Țăgșoru", simplu: "Tagsoru", comuna: "Budesti" },
  { nume: "Țagu", simplu: "Tagu", comuna: "Budesti" },
  { nume: "Târlișua", simplu: "Tarlisua" },
  { nume: "Tărpiu", simplu: "Tarpiu", comuna: "Dumitra" },
  { nume: "Tăure", simplu: "Taure", comuna: "Nimigea" },
  { nume: "Teaca" },
  { nume: "Telcișor", simplu: "Telcisor", comuna: "Telciu" },
  { nume: "Telciu" },
  { nume: "Țentea", simplu: "Tentea", comuna: "Chiochis" },
  { nume: "Țigău", simplu: "Tigau", comuna: "Lechinta" },
  { nume: "Tiha Bârgăului", simplu: "Tiha Bargaului" },
  { nume: "Tonciu", comuna: "Galatii Bistritei" },
  { nume: "Tureac", comuna: "Tiha Bargaului" },
  { nume: "Unirea", comuna: "Bistrita" },
  { nume: "Uriu" },
  { nume: "Urmeniș", simplu: "Urmenis" },
  { nume: "Valea Borcutului", comuna: "Sangeorz-Bai" },
  {
    nume: "Valea Măgherușului",
    simplu: "Valea Magherusului",
    comuna: "Sieu-Magherus",
  },
  { nume: "Valea Mare", comuna: "Sant" },
  { nume: "Valea Mare", comuna: "Urmenis" },
  { nume: "Valea Poenii", comuna: "Livezile" },
  { nume: "Valea Vinului", comuna: "Rodna" },
  { nume: "Valea", comuna: "Urmenis" },
  { nume: "Vermeș", simplu: "Vermes", comuna: "Lechinta" },
  { nume: "Viile Tecii", comuna: "Teaca" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Bistrita" },
  { nume: "Visuia", comuna: "Micestii De Campie" },
  { nume: "Vița", simplu: "Vita", comuna: "Nuseni" },
  { nume: "Zagra" },
  { nume: "Zoreni", comuna: "Sanmihaiu De Cimpie" },
];
