export const bz = [
  { nume: "Albești", simplu: "Albesti", comuna: "Smeeni" },
  { nume: "Aldeni", comuna: "Cernatesti" },
  { nume: "Alexandru Odobescu", comuna: "Buda" },
  { nume: "Aliceni", comuna: "Posta Calnau" },
  { nume: "Aluniș", simplu: "Alunis", comuna: "Colti" },
  { nume: "Amara", comuna: "Balta Alba" },
  { nume: "Amaru" },
  { nume: "Anini", comuna: "Cozieni" },
  { nume: "Arbănași", simplu: "Arbanasi", comuna: "Beceni" },
  { nume: "Arcanu", comuna: "Scutelnici" },
  { nume: "Băbeni", simplu: "Babeni", comuna: "Topliceni" },
  { nume: "Băceni", simplu: "Baceni", comuna: "Berca" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Breaza" },
  { nume: "Badila", comuna: "Parscov" },
  { nume: "Băești", simplu: "Baesti", comuna: "Cernatesti" },
  { nume: "Băile", simplu: "Baile", comuna: "Balta Alba" },
  { nume: "Băjani", simplu: "Bajani", comuna: "Vadu Pasii" },
  { nume: "Bălăceanu", simplu: "Balaceanu" },
  { nume: "Bălaia", simplu: "Balaia", comuna: "Smeeni" },
  { nume: "Bălănești", simplu: "Balanesti", comuna: "Cozieni" },
  { nume: "Bâlhacu", simplu: "Balhacu", comuna: "C.A. Rosetti" },
  { nume: "Balta Albă", simplu: "Balta Alba" },
  { nume: "Balta Tocila", comuna: "Scortoasa" },
  { nume: "Băltăgari", simplu: "Baltagari", comuna: "Bisoca" },
  { nume: "Băltăreți", simplu: "Baltareti", comuna: "Ulmeni" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "C.A. Rosetti" },
  { nume: "Banița", simplu: "Banita", comuna: "Sageata" },
  { nume: "Bărăști", simplu: "Barasti", comuna: "Cislau" },
  { nume: "Bărbuncești", simplu: "Barbuncesti", comuna: "Tisau" },
  { nume: "Bâsca Chiojdului", simplu: "Basca Chiojdului", comuna: "Chiojdu" },
  { nume: "Bâsca Rozilei", simplu: "Basca Rozilei", comuna: "Nehoiu" },
  { nume: "Bâscenii de Jos", simplu: "Bascenii de Jos", comuna: "Calvini" },
  { nume: "Bâscenii de Sus", simplu: "Bascenii de Sus", comuna: "Calvini" },
  { nume: "Batogu", comuna: "Murgesti" },
  { nume: "Beceni" },
  { nume: "Beciu", comuna: "Scortoasa" },
  { nume: "Begu", comuna: "Panatau" },
  { nume: "Beilic", comuna: "Sageata" },
  { nume: "Bentu", comuna: "Galbinasi" },
  { nume: "Berca" },
  { nume: "Bercești", simplu: "Bercesti", comuna: "Cozieni" },
  { nume: "Beșlii", simplu: "Beslii", comuna: "Manzalesti" },
  { nume: "Bisoca" },
  { nume: "Blăjani", simplu: "Blajani" },
  { nume: "Boboc", comuna: "Cochirleanca" },
  { nume: "Bodinești", simplu: "Bodinesti", comuna: "Vintila Voda" },
  { nume: "Boldu" },
  { nume: "Bordușani", simplu: "Bordusani", comuna: "Sageata" },
  { nume: "Bozioru" },
  { nume: "Brădeanca", simplu: "Bradeanca", comuna: "Vernesti" },
  { nume: "Brădeanu", simplu: "Bradeanu" },
  { nume: "Brăești", simplu: "Braesti" },
  { nume: "Brăgăreasa", simplu: "Bragareasa", comuna: "Scutelnici" },
  { nume: "Brătilești", simplu: "Bratilesti", comuna: "Braesti" },
  { nume: "Breaza" },
  { nume: "Brebu", comuna: "Lopatari" },
  { nume: "Buda Crăciunești", simplu: "Buda Craciunesti", comuna: "Cislau" },
  { nume: "Buda" },
  { nume: "Budești", simplu: "Budesti", comuna: "Chiliile" },
  { nume: "Budișteni", simplu: "Budisteni", comuna: "Costesti" },
  { nume: "Budrea", comuna: "Racoviteni" },
  { nume: "Buduile", comuna: "Bozioru" },
  { nume: "Buștea", simplu: "Bustea", comuna: "Manzalesti" },
  { nume: "Buzău", simplu: "Buzau" },
  { nume: "C.a. Rosetti" },
  { nume: "Căldărăști", simplu: "Caldarasti", comuna: "Pogoanele" },
  { nume: "Căldărușa", simplu: "Caldarusa", comuna: "Cernatesti" },
  { nume: "Căldărușeanca", simplu: "Caldaruseanca", comuna: "Glodeanu Sarat" },
  { nume: "Calea Chiojdului", comuna: "Patarlagele" },
  { nume: "Câlțești", simplu: "Caltesti", comuna: "Pietroasele" },
  { nume: "Călțuna", simplu: "Caltuna", comuna: "Smeeni" },
  { nume: "Calvini" },
  { nume: "Câmpeni", simplu: "Campeni", comuna: "Amaru" },
  { nume: "Câmpulungeanca", simplu: "Campulungeanca", comuna: "Margaritesti" },
  { nume: "Cândești", simplu: "Candesti", comuna: "Vernesti" },
  { nume: "Cănești", simplu: "Canesti" },
  { nume: "Căpățânești", simplu: "Capatanesti", comuna: "Maracineni" },
  { nume: "Capu Satului", comuna: "Odaile" },
  { nume: "Caragele", comuna: "Luciu" },
  { nume: "Cărătnău de Jos", simplu: "Caratnau de Jos", comuna: "Sarulesti" },
  { nume: "Cărătnău de Sus", simplu: "Caratnau de Sus", comuna: "Sarulesti" },
  { nume: "Cârligu Mare", simplu: "Carligu Mare", comuna: "Glodeanu-Silistea" },
  { nume: "Cârligu Mic", simplu: "Carligu Mic", comuna: "Glodeanu-Silistea" },
  { nume: "Cârlomănești", simplu: "Carlomanesti", comuna: "Vernesti" },
  { nume: "Cărpiniștea", simplu: "Carpinistea", comuna: "Beceni" },
  { nume: "Cașoca", simplu: "Casoca", comuna: "Siriu" },
  { nume: "Casota", comuna: "Glodeanu-Silistea" },
  { nume: "Cătiașu", simplu: "Catiasu", comuna: "Chiojdu" },
  { nume: "Cătina", simplu: "Catina" },
  { nume: "Ceairu", comuna: "Topliceni" },
  { nume: "Cernătești", simplu: "Cernatesti" },
  { nume: "Chiliile" },
  { nume: "Chiojdu" },
  { nume: "Chiperu", comuna: "Pardosi" },
  { nume: "Chirlești", simplu: "Chirlesti", comuna: "Nehoiu" },
  { nume: "Cilibia" },
  { nume: "Ciobănoaia", simplu: "Ciobanoaia", comuna: "Merei" },
  { nume: "Ciocănești", simplu: "Ciocanesti", comuna: "Cozieni" },
  { nume: "Cioranca", comuna: "Movila Banului" },
  { nume: "Cireșu", simplu: "Ciresu", comuna: "Manzalesti" },
  { nume: "Cislău", simplu: "Cislau" },
  { nume: "Ciuta", comuna: "Magura" },
  { nume: "Clondiru de Sus", comuna: "Pietroasele" },
  { nume: "Clondiru", comuna: "Ulmeni" },
  {
    nume: "Coca-Antimirești",
    simplu: "Coca-Antimiresti",
    comuna: "Vintila Voda",
  },
  { nume: "Coca-Niculești", simplu: "Coca-Niculesti", comuna: "Vintila Voda" },
  { nume: "Cocârceni", simplu: "Cocarceni", comuna: "Cozieni" },
  { nume: "Cochirleanca" },
  { nume: "Coconari", comuna: "Posta Calnau" },
  { nume: "Cojanu", comuna: "Berca" },
  { nume: "Colibași", simplu: "Colibasi", comuna: "Ramnicelu" },
  { nume: "Colțăneni", simplu: "Coltaneni", comuna: "Mihailesti" },
  { nume: "Colțeni", simplu: "Colteni", comuna: "Cozieni" },
  { nume: "Colți", simplu: "Colti" },
  { nume: "Colții de Jos", simplu: "Coltii de Jos", comuna: "Colti" },
  { nume: "Colțu Pietrii", simplu: "Coltu Pietrii", comuna: "Siriu" },
  { nume: "Comisoaia", comuna: "Zarnesti" },
  { nume: "Corbu", comuna: "Catina" },
  { nume: "Corbu", comuna: "Glodeanu-Silistea" },
  { nume: "Corneanu", comuna: "Odaile" },
  { nume: "Costești", simplu: "Costesti" },
  { nume: "Costieni", comuna: "Ziduri" },
  { nume: "Costomiru", comuna: "Pardosi" },
  { nume: "Coțatcu", simplu: "Cotatcu", comuna: "Podgoria" },
  { nume: "Cotorca", comuna: "Glodeanu-Silistea" },
  { nume: "Cotu Ciorii", comuna: "C.A. Rosetti" },
  { nume: "Cozieni" },
  { nume: "Crâng", simplu: "Crang", comuna: "Patarlagele" },
  { nume: "Crevelești", simplu: "Crevelesti", comuna: "Chiliile" },
  { nume: "Cuculeasa", comuna: "Ziduri" },
  { nume: "Curcănești", simplu: "Curcanesti", comuna: "Parscov" },
  { nume: "Curmătura", simplu: "Curmatura", comuna: "Nehoiu" },
  { nume: "Dâlma", simplu: "Dalma", comuna: "Scortoasa" },
  { nume: "Dâmbroca", simplu: "Dambroca", comuna: "Sageata" },
  { nume: "Dănulești", simplu: "Danulesti", comuna: "Buda" },
  { nume: "Dara", comuna: "Pietroasele" },
  { nume: "Dăscălești", simplu: "Dascalesti", comuna: "Puiesti" },
  { nume: "Dealul Viei", comuna: "Merei" },
  { nume: "Dedulești", simplu: "Dedulesti", comuna: "Topliceni" },
  { nume: "Deleni", comuna: "Scortoasa" },
  { nume: "Dobrilești", simplu: "Dobrilesti", comuna: "Merei" },
  { nume: "Dogari", comuna: "Beceni" },
  { nume: "Dulbanu", comuna: "Amaru" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Margaritesti" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Naeni" },
  { nume: "Fața lui Nan", simplu: "Fata lui Nan", comuna: "Cozieni" },
  { nume: "Fințești", simplu: "Fintesti", comuna: "Naeni" },
  { nume: "Fișici", simplu: "Fisici", comuna: "Bozioru" },
  { nume: "Florești", simplu: "Floresti", comuna: "Beceni" },
  { nume: "Florica", comuna: "Mihailesti" },
  { nume: "Focșănei", simplu: "Focsanei", comuna: "Vadu Pasii" },
  { nume: "Fotin", comuna: "Ramnicelu" },
  { nume: "Frăsinet", simplu: "Frasinet", comuna: "Calvini" },
  { nume: "Fulga", comuna: "Cernatesti" },
  { nume: "Fundata", comuna: "Lopatari" },
  { nume: "Fundăturile", simplu: "Fundaturile", comuna: "Patarlagele" },
  { nume: "Fundeni", comuna: "Zarnesti" },
  { nume: "Furtunești", simplu: "Furtunesti", comuna: "Gura Teghii" },
  { nume: "Găgeni", simplu: "Gageni", comuna: "Sahateni" },
  { nume: "Gălbinași", simplu: "Galbinasi" },
  { nume: "Gara Bobocu", comuna: "Cochirleanca" },
  { nume: "Gara Cilibia", comuna: "Cilibia" },
  { nume: "Găvanele", simplu: "Gavanele", comuna: "Bozioru" },
  { nume: "Găvănești", simplu: "Gavanesti", comuna: "Sageata" },
  { nume: "Gherăseni", simplu: "Gheraseni" },
  { nume: "Ghergheasa" },
  { nume: "Ghiocari", comuna: "Chiliile" },
  { nume: "Ghizdita", comuna: "Manzalesti" },
  { nume: "Glodeanu Sărat", simplu: "Glodeanu Sarat" },
  { nume: "Glodeanu-Siliștea", simplu: "Glodeanu-Silistea" },
  { nume: "Glodu-Petcari", comuna: "Chiliile" },
  { nume: "Glodurile", comuna: "Cozieni" },
  { nume: "Goicelu", comuna: "Sarulesti" },
  { nume: "Goidești", simplu: "Goidesti", comuna: "Braesti" },
  { nume: "Golu Grabicina", comuna: "Scortoasa" },
  { nume: "Gomoești", simplu: "Gomoesti", comuna: "Costesti" },
  { nume: "Gonțești", simplu: "Gontesti", comuna: "Canesti" },
  { nume: "Gorâni", simplu: "Gorani", comuna: "Odaile" },
  { nume: "Gornet", comuna: "Patarlagele" },
  { nume: "Grabicina de Jos", comuna: "Scortoasa" },
  { nume: "Grabicina de Sus", comuna: "Scortoasa" },
  { nume: "Grăjdana", simplu: "Grajdana", comuna: "Tisau" },
  { nume: "Grebănu", simplu: "Grebanu" },
  { nume: "Greceanca", comuna: "Breaza" },
  { nume: "Gresia", comuna: "Bozioru" },
  { nume: "Groșani", simplu: "Grosani", comuna: "Costesti" },
  { nume: "Gura Bădicului", simplu: "Gura Badicului", comuna: "Manzalesti" },
  { nume: "Gura Bâscei", simplu: "Gura Bascei", comuna: "Cislau" },
  { nume: "Gura Câlnăului", simplu: "Gura Calnaului", comuna: "Vadu Pasii" },
  { nume: "Gura Dimienii", comuna: "Beceni" },
  { nume: "Gura Făgetului", simplu: "Gura Fagetului", comuna: "Topliceni" },
  { nume: "Gura Sărății", simplu: "Gura Saratii", comuna: "Merei" },
  { nume: "Gura Siriului", comuna: "Siriu" },
  { nume: "Gura Teghii" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Scortoasa" },
  { nume: "Haleș", simplu: "Hales", comuna: "Tisau" },
  { nume: "Heliade Rădulescu", simplu: "Heliade Radulescu", comuna: "Ziduri" },
  { nume: "Homești", simplu: "Homesti", comuna: "Grebanu" },
  { nume: "Ileana", comuna: "Glodeanu Sarat" },
  { nume: "Istrița de Jos", simplu: "Istrita de Jos", comuna: "Sahateni" },
  { nume: "Ivănețu", simplu: "Ivanetu", comuna: "Braesti" },
  { nume: "Izvoarele", comuna: "Bozioru" },
  { nume: "Izvoranu", comuna: "Tisau" },
  { nume: "Izvoru Dulce", comuna: "Beceni" },
  { nume: "Izvoru Dulce", comuna: "Merei" },
  { nume: "Izvoru", comuna: "Cozieni" },
  { nume: "Izvoru", comuna: "Tisau" },
  { nume: "Jghiab", comuna: "Manzalesti" },
  { nume: "Joseni", comuna: "Berca" },
  { nume: "Lacu cu Anini", comuna: "Panatau" },
  { nume: "Lacu Sinaia", comuna: "Amaru" },
  { nume: "Lacu", comuna: "Odaile" },
  { nume: "Lacurile", comuna: "Bisoca" },
  { nume: "Lanurile", comuna: "Ziduri" },
  { nume: "Largu" },
  { nume: "Leiculești", simplu: "Leiculesti", comuna: "Tisau" },
  { nume: "Lera", comuna: "Chiojdu" },
  { nume: "Limpeziș", simplu: "Limpezis", comuna: "Movila Banului" },
  { nume: "Lipănescu", simplu: "Lipanescu", comuna: "Scutelnici" },
  { nume: "Lipia", comuna: "Merei" },
  { nume: "Livada Mică", simplu: "Livada Mica", comuna: "Grebanu" },
  { nume: "Livada", comuna: "Grebanu" },
  { nume: "Lopătăreasa", simplu: "Lopatareasa", comuna: "Bisoca" },
  { nume: "Lopătari", simplu: "Lopatari" },
  { nume: "Luciu" },
  { nume: "Lunca Frumoasă", simplu: "Lunca Frumoasa", comuna: "Parscov" },
  { nume: "Lunca Jariștei", simplu: "Lunca Jaristei", comuna: "Siriu" },
  { nume: "Lunca Priporului", comuna: "Nehoiu" },
  { nume: "Lunca", comuna: "Amaru" },
  { nume: "Lunca", comuna: "C.A. Rosetti" },
  { nume: "Lunca", comuna: "Patarlagele" },
  { nume: "Lunca", comuna: "Puiesti" },
  { nume: "Luncile", comuna: "Lopatari" },
  { nume: "Lungești", simplu: "Lungesti", comuna: "Cozieni" },
  { nume: "Măcrina", simplu: "Macrina", comuna: "Puiesti" },
  { nume: "Măgura", simplu: "Magura" },
  { nume: "Măguricea", simplu: "Maguricea", comuna: "Panatau" },
  { nume: "Manasia", comuna: "Cernatesti" },
  { nume: "Mânăstirea Rătești", simplu: "Manastirea Ratesti", comuna: "Berca" },
  { nume: "Mănăstirea", simplu: "Manastirea", comuna: "Patarlagele" },
  { nume: "Mânzălești", simplu: "Manzalesti" },
  { nume: "Mânzu", simplu: "Manzu", comuna: "Cilibia" },
  { nume: "Mărăcineni", simplu: "Maracineni" },
  { nume: "Mărgăritești", simplu: "Margaritesti" },
  { nume: "Mărgăriți", simplu: "Margariti", comuna: "Beceni" },
  { nume: "Mărgineanu", simplu: "Margineanu", comuna: "Mihailesti" },
  { nume: "Mărunțișu", simplu: "Maruntisu", comuna: "Patarlagele" },
  { nume: "Mătești", simplu: "Matesti", comuna: "Sapoca" },
  { nume: "Maxenu", comuna: "Tintesti" },
  { nume: "Merei" },
  { nume: "Mierea", comuna: "Vernesti" },
  { nume: "Mihăilești", simplu: "Mihailesti" },
  { nume: "Mitropolia", comuna: "Bradeanu" },
  { nume: "Mlăjet", simplu: "Mlajet", comuna: "Nehoiu" },
  { nume: "Modreni", comuna: "Valea Salciei" },
  { nume: "Moisica", comuna: "Smeeni" },
  { nume: "Moșești", simplu: "Mosesti", comuna: "Robeasca" },
  { nume: "Movila Banului" },
  { nume: "Movila Oii", comuna: "Cilibia" },
  { nume: "Movilița", simplu: "Movilita", comuna: "Sageata" },
  { nume: "Mucești-Dănulești", simplu: "Mucesti-Danulesti", comuna: "Buda" },
  { nume: "Murgești", simplu: "Murgesti" },
  { nume: "Muscel", comuna: "Viperesti" },
  { nume: "Mușcel", simplu: "Muscel", comuna: "Patarlagele" },
  {
    nume: "Muscelu Cărămănești",
    simplu: "Muscelu Caramanesti",
    comuna: "Colti",
  },
  { nume: "Mușcelușa", simplu: "Muscelusa", comuna: "Siriu" },
  { nume: "Năeni", simplu: "Naeni" },
  { nume: "Negoșina", simplu: "Negosina", comuna: "Canesti" },
  { nume: "Nehoiașu", simplu: "Nehoiasu", comuna: "Nehoiu" },
  { nume: "Nehoiu" },
  { nume: "Nemertea", comuna: "Gura Teghii" },
  { nume: "Nenciu", comuna: "Vernesti" },
  { nume: "Nenciulești", simplu: "Nenciulesti", comuna: "Merei" },
  { nume: "Nicolești", simplu: "Nicolesti", comuna: "Puiesti" },
  { nume: "Niculești", simplu: "Niculesti", comuna: "Vintila Voda" },
  { nume: "Nișcov", simplu: "Niscov", comuna: "Vernesti" },
  { nume: "Nistorești", simplu: "Nistoresti", comuna: "Cozieni" },
  { nume: "Nucu", comuna: "Bozioru" },
  { nume: "Odaia Banului", comuna: "Tintesti" },
  { nume: "Odăile", simplu: "Odaile" },
  { nume: "Ogrăzile", simplu: "Ograzile", comuna: "Merei" },
  { nume: "Ojasca", comuna: "Unguriu" },
  { nume: "Olari", comuna: "Calvini" },
  { nume: "Oleșești", simplu: "Olesesti", comuna: "Parscov" },
  { nume: "Oratia", comuna: "Podgoria" },
  { nume: "Oreavul", comuna: "Valea Ramnicului" },
  { nume: "Pâclele", simplu: "Paclele", comuna: "Berca" },
  { nume: "Păcurile", simplu: "Pacurile", comuna: "Canesti" },
  { nume: "Padina" },
  { nume: "Pădurenii", simplu: "Padurenii", comuna: "Tisau" },
  { nume: "Pălici", simplu: "Palici", comuna: "Viperesti" },
  { nume: "Păltineni", simplu: "Paltineni", comuna: "Nehoiu" },
  { nume: "Păltiniș", simplu: "Paltinis", comuna: "Gura Teghii" },
  { nume: "Pănătău", simplu: "Panatau" },
  { nume: "Pardoși", simplu: "Pardosi" },
  { nume: "Pârjolești", simplu: "Parjolesti", comuna: "Parscov" },
  { nume: "Pârscov", simplu: "Parscov" },
  { nume: "Pârscovelu", simplu: "Parscovelu", comuna: "Braesti" },
  { nume: "Pătârlagele", simplu: "Patarlagele" },
  { nume: "Pestrițu", simplu: "Pestritu", comuna: "Lopatari" },
  { nume: "Petrăchești", simplu: "Petrachesti", comuna: "Vintila Voda" },
  { nume: "Petrișoru", simplu: "Petrisoru", comuna: "Racoviteni" },
  { nume: "Piatra Albă", simplu: "Piatra Alba", comuna: "Odaile" },
  { nume: "Pietraru", comuna: "Cozieni" },
  { nume: "Pietroasa Mică", simplu: "Pietroasa Mica", comuna: "Pietroasele" },
  { nume: "Pietroasele" },
  { nume: "Pietrosu", comuna: "Costesti" },
  { nume: "Pinu", comuna: "Braesti" },
  { nume: "Pitulicea", comuna: "Glodeanu Sarat" },
  { nume: "Plăișor", simplu: "Plaisor", comuna: "Panatau" },
  { nume: "Plaiu Nucului", comuna: "Lopatari" },
  { nume: "Plavățu", simplu: "Plavatu", comuna: "Manzalesti" },
  { nume: "Plescioara", comuna: "Chiojdu" },
  { nume: "Pleșcoi", simplu: "Plescoi", comuna: "Berca" },
  { nume: "Pleșești", simplu: "Plesesti", comuna: "Berca" },
  { nume: "Pleșești", simplu: "Plesesti", comuna: "Podgoria" },
  { nume: "Pleși", simplu: "Plesi", comuna: "Bisoca" },
  { nume: "Plevna", comuna: "Grebanu" },
  { nume: "Plopeasa", comuna: "Scortoasa" },
  { nume: "Plopi", comuna: "Puiesti" },
  { nume: "Ploștina", simplu: "Plostina", comuna: "Lopatari" },
  { nume: "Podgoria" },
  { nume: "Podu Muncii", comuna: "Vintila Voda" },
  { nume: "Poenițele", simplu: "Poenitele", comuna: "Chiojdu" },
  { nume: "Pogoanele" },
  { nume: "Pogonele", comuna: "Tintesti" },
  { nume: "Poiana Pletari", comuna: "Chiliile" },
  { nume: "Poiana Vâlcului", simplu: "Poiana Valcului", comuna: "Manzalesti" },
  { nume: "Poienile", comuna: "Patarlagele" },
  { nume: "Policiori", comuna: "Scortoasa" },
  { nume: "Posobești", simplu: "Posobesti", comuna: "Odaile" },
  { nume: "Poșta Câlnău", simplu: "Posta Calnau" },
  { nume: "Poșta", simplu: "Posta", comuna: "Cilibia" },
  { nume: "Poșta", simplu: "Posta", comuna: "Topliceni" },
  { nume: "Potârnichești", simplu: "Potarnichesti", comuna: "Posta Calnau" },
  { nume: "Potecu", comuna: "Lopatari" },
  { nume: "Potoceni", comuna: "Maracineni" },
  { nume: "Proșca", simplu: "Prosca", comuna: "Naeni" },
  { nume: "Pruneni", comuna: "Zarnesti" },
  { nume: "Puieștii de Jos", simplu: "Puiestii de Jos", comuna: "Puiesti" },
  { nume: "Puieștii de Sus", simplu: "Puiestii de Sus", comuna: "Puiesti" },
  { nume: "Punga", comuna: "Cozieni" },
  { nume: "Racovițeni", simplu: "Racoviteni" },
  { nume: "Răducești", simplu: "Raducesti", comuna: "Topliceni" },
  { nume: "Râmnicelu", simplu: "Ramnicelu" },
  { nume: "Râmnicu Sărat", simplu: "Ramnicu Sarat" },
  { nume: "Râpile", simplu: "Rapile", comuna: "Panatau" },
  { nume: "Rătești", simplu: "Ratesti", comuna: "Berca" },
  { nume: "Recea", comuna: "Bisoca" },
  { nume: "Robeasca" },
  { nume: "Robești", simplu: "Robesti", comuna: "Parscov" },
  { nume: "Roșioru", simplu: "Rosioru", comuna: "Cochirleanca" },
  { nume: "Rubla", comuna: "Valea Ramnicului" },
  { nume: "Ruginoasa", comuna: "Braesti" },
  { nume: "Runcu", comuna: "Parscov" },
  { nume: "Rușavăț", simplu: "Rusavat", comuna: "Viperesti" },
  { nume: "Rușețu", simplu: "Rusetu" },
  { nume: "Săgeata", simplu: "Sageata" },
  { nume: "Săhăteni", simplu: "Sahateni" },
  { nume: "Salcia", comuna: "Tisau" },
  { nume: "Sălcioara", simplu: "Salcioara", comuna: "Ghergheasa" },
  { nume: "Săpoca", simplu: "Sapoca" },
  { nume: "Șarânga", simplu: "Saranga", comuna: "Pietroasele" },
  { nume: "Sărata-Monteoru", simplu: "Sarata-Monteoru", comuna: "Merei" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Ulmeni" },
  { nume: "Sârbești", simplu: "Sarbesti", comuna: "Vintila Voda" },
  { nume: "Săreni", simplu: "Sareni", comuna: "Lopatari" },
  { nume: "Sările-Cătun", simplu: "Sarile-Catun", comuna: "Sarulesti" },
  { nume: "Sările", simplu: "Sarile", comuna: "Bisoca" },
  { nume: "Sărulești", simplu: "Sarulesti" },
  { nume: "Săsenii Noi", simplu: "Sasenii Noi", comuna: "Vernesti" },
  { nume: "Săsenii pe Vale", simplu: "Sasenii pe Vale", comuna: "Vernesti" },
  { nume: "Săsenii Vechi", simplu: "Sasenii Vechi", comuna: "Vernesti" },
  { nume: "Satu Nou", comuna: "Glodeanu-Silistea" },
  { nume: "Satu Nou", comuna: "Mihailesti" },
  { nume: "Satu Vechi", comuna: "Manzalesti" },
  { nume: "Sătuc", simplu: "Satuc", comuna: "Berca" },
  { nume: "Scăeni", simplu: "Scaeni", comuna: "Bozioru" },
  { nume: "Scărișoara", simplu: "Scarisoara", comuna: "Cislau" },
  { nume: "Scărlătești", simplu: "Scarlatesti", comuna: "Largu" },
  { nume: "Scoroșești", simplu: "Scorosesti", comuna: "Odaile" },
  { nume: "Scorțeanca", simplu: "Scorteanca", comuna: "Amaru" },
  { nume: "Scorțoasa", simplu: "Scortoasa" },
  { nume: "Scurtești", simplu: "Scurtesti", comuna: "Vadu Pasii" },
  { nume: "Scutelnici" },
  { nume: "Secuiu", comuna: "Gura Teghii" },
  {
    nume: "Sergent Ionel Ștefan",
    simplu: "Sergent Ionel Stefan",
    comuna: "Rusetu",
  },
  { nume: "Sibiciu de Jos", comuna: "Panatau" },
  { nume: "Sibiciu de Sus", comuna: "Patarlagele" },
  { nume: "Șindrila", simplu: "Sindrila", comuna: "Bisoca" },
  { nume: "Slobozia", comuna: "Catina" },
  { nume: "Smârdan", simplu: "Smardan", comuna: "Bradeanu" },
  { nume: "Smeeni" },
  { nume: "Smeești", simplu: "Smeesti", comuna: "Vintila Voda" },
  { nume: "Sorești", simplu: "Soresti", comuna: "Blajani" },
  { nume: "Spătaru", simplu: "Spataru", comuna: "Costesti" },
  { nume: "Spidele", comuna: "Buda" },
  { nume: "Stâlpu", simplu: "Stalpu" },
  { nume: "Stăncești", simplu: "Stancesti", comuna: "Vadu Pasii" },
  { nume: "Stănila", simplu: "Stanila", comuna: "Nehoiu" },
  { nume: "Stăvărăști", simplu: "Stavarasti", comuna: "Balta Alba" },
  { nume: "Știubei", simplu: "Stiubei", comuna: "Ramnicelu" },
  { nume: "Strezeni", comuna: "Tisau" },
  { nume: "Stroești", simplu: "Stroesti", comuna: "Patarlagele" },
  { nume: "Șuchea", simplu: "Suchea", comuna: "Canesti" },
  { nume: "Sudiți", simplu: "Suditi", comuna: "Gheraseni" },
  { nume: "Sudiți", simplu: "Suditi", comuna: "Posta Calnau" },
  { nume: "Tăbăcari", simplu: "Tabacari", comuna: "Podgoria" },
  { nume: "Tăbărăști", simplu: "Tabarasti", comuna: "Galbinasi" },
  { nume: "Târcov", simplu: "Tarcov", comuna: "Parscov" },
  { nume: "Târlele", simplu: "Tarlele", comuna: "Cochirleanca" },
  { nume: "Tâțârligu", simplu: "Tatarligu", comuna: "Berca" },
  { nume: "Tătulești", simplu: "Tatulesti", comuna: "Padina" },
  { nume: "Tega", comuna: "Panatau" },
  { nume: "Teișu", simplu: "Teisu", comuna: "Cozieni" },
  { nume: "Terca", comuna: "Lopatari" },
  { nume: "Țintești", simplu: "Tintesti" },
  { nume: "Tisău", simplu: "Tisau" },
  { nume: "Tocileni", comuna: "Parscov" },
  { nume: "Topliceni" },
  { nume: "Toropălești", simplu: "Toropalesti", comuna: "Buda" },
  { nume: "Trestia", comuna: "Cozieni" },
  { nume: "Trestieni", comuna: "Parscov" },
  { nume: "Trestioara", comuna: "Chiliile" },
  { nume: "Trestioara", comuna: "Manzalesti" },
  { nume: "Tronari", comuna: "Viperesti" },
  { nume: "Tulburea", comuna: "Cozieni" },
  { nume: "Udați-Lucieni", simplu: "Udati-Lucieni", comuna: "Smeeni" },
  { nume: "Udați-Mânzu", simplu: "Udati-Manzu", comuna: "Smeeni" },
  { nume: "Ulmeni" },
  { nume: "Ulmet", comuna: "Bozioru" },
  { nume: "Unguriu", comuna: "Magura" },
  { nume: "Ursoaia", comuna: "Viperesti" },
  { nume: "Văcăreasca", simplu: "Vacareasca", comuna: "Glodeanu-Silistea" },
  { nume: "Vadu Oii", comuna: "Gura Teghii" },
  { nume: "Vadu Pașii", simplu: "Vadu Pasii" },
  { nume: "Vadu Sorești", simplu: "Vadu Soresti", comuna: "Zarnesti" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Ulmeni" },
  { nume: "Vâlcelele", simplu: "Valcelele" },
  { nume: "Valea Banului", comuna: "Cozieni" },
  { nume: "Valea Cătinei", simplu: "Valea Catinei", comuna: "Catina" },
  { nume: "Valea Cotoarei", comuna: "Manzalesti" },
  { nume: "Valea Fântânei", simplu: "Valea Fantanei", comuna: "Odaile" },
  {
    nume: "Valea Largă-Sărulești",
    simplu: "Valea Larga-Sarulesti",
    comuna: "Sarulesti",
  },
  { nume: "Valea Largă", simplu: "Valea Larga", comuna: "Buda" },
  { nume: "Valea lui Lalu", comuna: "Pardosi" },
  { nume: "Valea Lupului", comuna: "Patarlagele" },
  { nume: "Valea Nucului", comuna: "Berca" },
  { nume: "Valea Părului", simplu: "Valea Parului", comuna: "Beceni" },
  { nume: "Valea Purcarului", comuna: "Parscov" },
  {
    nume: "Valea Puțului Merei",
    simplu: "Valea Putului Merei",
    comuna: "Merei",
  },
  { nume: "Valea Râmnicului", simplu: "Valea Ramnicului" },
  { nume: "Valea Ratei", comuna: "Murgesti" },
  { nume: "Valea Roatei", comuna: "Cozieni" },
  {
    nume: "Valea Salciei-Cătun",
    simplu: "Valea Salciei-Catun",
    comuna: "Valea Salciei",
  },
  { nume: "Valea Salciei" },
  { nume: "Valea Sălciilor", simplu: "Valea Salciilor", comuna: "Tisau" },
  { nume: "Valea Șchiopului", simplu: "Valea Schiopului", comuna: "Pardosi" },
  { nume: "Valea Sibiciului", comuna: "Patarlagele" },
  { nume: "Valea Stânei", simplu: "Valea Stanei", comuna: "Sarulesti" },
  { nume: "Valea Ștefanului", simplu: "Valea Stefanului", comuna: "Odaile" },
  { nume: "Valea Ursului", comuna: "Manzalesti" },
  { nume: "Valea Verzei", comuna: "Canesti" },
  { nume: "Valea Viei", comuna: "Patarlagele" },
  {
    nume: "Văleanca-Vilănești",
    simplu: "Valeanca-Vilanesti",
    comuna: "Breaza",
  },
  { nume: "Vârf", simplu: "Varf", comuna: "Naeni" },
  { nume: "Varlaam", comuna: "Gura Teghii" },
  { nume: "Vârteju", simplu: "Varteju", comuna: "Lopatari" },
  { nume: "Văvălucile", simplu: "Vavalucile", comuna: "Bozioru" },
  { nume: "Vernești", simplu: "Vernesti" },
  { nume: "Viforâta", simplu: "Viforata", comuna: "Berca" },
  { nume: "Vinețișu", simplu: "Vinetisu", comuna: "Nehoiu" },
  { nume: "Vintilă Vodă", simplu: "Vintila Voda" },
  { nume: "Vintileanca", comuna: "Sahateni" },
  { nume: "Viperești", simplu: "Viperesti" },
  { nume: "Vispești", simplu: "Vispesti", comuna: "Breaza" },
  { nume: "Vizireni", comuna: "C.A. Rosetti" },
  { nume: "Vlădeni", simplu: "Vladeni", comuna: "Cernatesti" },
  { nume: "Zaharești", simplu: "Zaharesti", comuna: "Panatau" },
  { nume: "Zăplazi", simplu: "Zaplazi", comuna: "Grebanu" },
  { nume: "Zăpodia", simplu: "Zapodia", comuna: "Cozieni" },
  { nume: "Zărnești", simplu: "Zarnesti" },
  {
    nume: "Zărneștii de Slănic",
    simplu: "Zarnestii de Slanic",
    comuna: "Cernatesti",
  },
  { nume: "Zeletin", comuna: "Catina" },
  { nume: "Ziduri" },
  { nume: "Zilișteanca", simplu: "Zilisteanca", comuna: "Posta Calnau" },
  { nume: "Zoița", simplu: "Zoita", comuna: "Ziduri" },
  { nume: "Zorești", simplu: "Zoresti", comuna: "Vernesti" },
];
