export const br = [
  { nume: "Agaua", comuna: "Frecatei" },
  { nume: "Albina", comuna: "Tichilesti" },
  { nume: "Ariciu", comuna: "Salcia Tudor" },
  { nume: "Baldovinești", simplu: "Baldovinesti", comuna: "Vadeni" },
  { nume: "Băndoiu", simplu: "Bandoiu", comuna: "Marasu" },
  { nume: "Bărăganul", simplu: "Baraganul" },
  { nume: "Batogu", comuna: "Ciresu" },
  { nume: "Berlești", simplu: "Berlesti", comuna: "Ianca" },
  { nume: "Berteștii de Jos", simplu: "Bertestii de Jos" },
  {
    nume: "Berteștii de Sus",
    simplu: "Bertestii de Sus",
    comuna: "Bertestii De Jos",
  },
  { nume: "Boarca", comuna: "Ramnicelu" },
  { nume: "Bordei Verde" },
  { nume: "Brădeanca", simplu: "Bradeanca", comuna: "Jirlau" },
  { nume: "Brăila", simplu: "Braila" },
  { nume: "Brateșu Vechi", simplu: "Bratesu Vechi", comuna: "Surdila-Greci" },
  { nume: "Bumbăcari", simplu: "Bumbacari", comuna: "Dudesti" },
  { nume: "Câineni-Băi", simplu: "Caineni-Bai", comuna: "Visani" },
  { nume: "Căldărușa", simplu: "Caldarusa", comuna: "Traian" },
  { nume: "Cazasu" },
  { nume: "Chichinețu", simplu: "Chichinetu", comuna: "Ciocile" },
  { nume: "Chioibașești", simplu: "Chioibasesti", comuna: "Ciocile" },
  { nume: "Chișcani", simplu: "Chiscani" },
  { nume: "Ciocile" },
  { nume: "Cireșu", simplu: "Ciresu" },
  { nume: "Cistia", comuna: "Frecatei" },
  { nume: "Colțea", simplu: "Coltea", comuna: "Rosiori" },
  { nume: "Comăneasca", simplu: "Comaneasca", comuna: "Tudor Vladimirescu" },
  { nume: "Constantin Gabrielescu", comuna: "Bordei Verde" },
  { nume: "Constantinești", simplu: "Constantinesti", comuna: "Ramnicelu" },
  { nume: "Corbeni", comuna: "Racovita" },
  { nume: "Corbu Nou", comuna: "Maxineni" },
  { nume: "Corbu Vechi", comuna: "Maxineni" },
  { nume: "Cotu Lung", comuna: "Silistea" },
  { nume: "Cotu Mihalea", comuna: "Silistea" },
  { nume: "Custura", comuna: "Racovita" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Salcia Tudor" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Stancuta" },
  { nume: "Dedulești", simplu: "Dedulesti", comuna: "Mircea Voda" },
  { nume: "Deșirați", simplu: "Desirati", comuna: "Scortaru Nou" },
  { nume: "Drogu", comuna: "Galbenu" },
  { nume: "Dudescu", comuna: "Zavoaia" },
  { nume: "Dudești", simplu: "Dudesti" },
  { nume: "Esna", comuna: "Movila Miresii" },
  { nume: "Făurei Sat", simplu: "Faurei Sat", comuna: "Surdila-Greci" },
  { nume: "Făurei", simplu: "Faurei" },
  { nume: "Filipești", simplu: "Filipesti", comuna: "Surdila-Gaiseanca" },
  { nume: "Filiu", comuna: "Bordei Verde" },
  { nume: "Florica", comuna: "Rosiori" },
  { nume: "Frecăței", simplu: "Frecatei" },
  { nume: "Galbenu" },
  { nume: "Gara Ianca", comuna: "Ianca" },
  { nume: "Găvani", simplu: "Gavani", comuna: "Gemenele" },
  { nume: "Gemenele" },
  { nume: "Gradiștea", simplu: "Gradistea" },
  { nume: "Gropeni" },
  { nume: "Gulianca", comuna: "Salcia Tudor" },
  {
    nume: "Gura Călmățui",
    simplu: "Gura Calmatui",
    comuna: "Bertestii De Jos",
  },
  {
    nume: "Gura Gârluței",
    simplu: "Gura Garlutei",
    comuna: "Bertestii De Jos",
  },
  { nume: "Gurguieți", simplu: "Gurguieti", comuna: "Scortaru Nou" },
  { nume: "Horia", comuna: "Surdila-Greci" },
  { nume: "Ianca" },
  { nume: "Ibrianu", comuna: "Gradistea" },
  { nume: "Însurăței", simplu: "Insuratei" },
  { nume: "Ionești", simplu: "Ionesti", comuna: "Ciresu" },
  { nume: "Jirlău", simplu: "Jirlau" },
  { nume: "Jugureanu", comuna: "Ulmu" },
  { nume: "Lacu Rezii", comuna: "Insuratei" },
  { nume: "Lacu Sărat", simplu: "Lacu Sarat", comuna: "Chiscani" },
  { nume: "Lanurile", comuna: "Viziru" },
  { nume: "Latinu", comuna: "Maxineni" },
  { nume: "Lișcoteanca", simplu: "Liscoteanca", comuna: "Bordei Verde" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Marasu" },
  { nume: "Maraloiu", comuna: "Gradistea" },
  { nume: "Mărașu", simplu: "Marasu" },
  { nume: "Mărtăcești", simplu: "Martacesti", comuna: "Silistea" },
  { nume: "Măru Roșu", simplu: "Maru Rosu", comuna: "Insuratei" },
  { nume: "Măxineni", simplu: "Maxineni" },
  { nume: "Mihai Bravu", comuna: "Victoria" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Ramnicelu",
  },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Sutesti",
  },
  { nume: "Mircea Vodă", simplu: "Mircea Voda" },
  { nume: "Morotești", simplu: "Morotesti", comuna: "Unirea" },
  { nume: "Movila Miresii" },
  { nume: "Muchea", comuna: "Silistea" },
  { nume: "Nedeicu", comuna: "Marasu" },
  {
    nume: "Nicolae Bălcescu",
    simplu: "Nicolae Balcescu",
    comuna: "Scortaru Nou",
  },
  { nume: "Nicolești", simplu: "Nicolesti", comuna: "Bertestii De Jos" },
  { nume: "Oancea", comuna: "Romanu" },
  { nume: "Odăieni", simplu: "Odaieni", comuna: "Ciocile" },
  { nume: "Olăneasca", simplu: "Olaneasca", comuna: "Salcia Tudor" },
  { nume: "Oprișenești", simplu: "Oprisenesti", comuna: "Ianca" },
  { nume: "Pântecani", simplu: "Pantecani", comuna: "Galbenu" },
  { nume: "Perișoru", simplu: "Perisoru", comuna: "Ianca" },
  { nume: "Pietroiu", comuna: "Vadeni" },
  { nume: "Pitulați", simplu: "Pitulati", comuna: "Scortaru Nou" },
  { nume: "Plăsoiu", simplu: "Plasoiu", comuna: "Visani" },
  { nume: "Plopi", comuna: "Marasu" },
  { nume: "Plopu", comuna: "Ianca" },
  { nume: "Polizești", simplu: "Polizesti", comuna: "Stancuta" },
  { nume: "Pribeagu", comuna: "Rosiori" },
  { nume: "Racoviță", simplu: "Racovita" },
  { nume: "Râmnicelu", simplu: "Ramnicelu" },
  { nume: "Romanu" },
  { nume: "Roșiori", simplu: "Rosiori" },
  { nume: "Salcia Tudor" },
  { nume: "Salcia", comuna: "Frecatei" },
  { nume: "Sătuc", simplu: "Satuc", comuna: "Galbenu" },
  { nume: "Scărlătești", simplu: "Scarlatesti", comuna: "Ciresu" },
  { nume: "Scorțaru Nou", simplu: "Scortaru Nou" },
  {
    nume: "Scorțaru Vechi",
    simplu: "Scortaru Vechi",
    comuna: "Tudor Vladimirescu",
  },
  { nume: "Sihleanu", comuna: "Scortaru Nou" },
  { nume: "Siliștea", simplu: "Silistea" },
  { nume: "Silistraru", comuna: "Traian" },
  { nume: "Spiru Haret", comuna: "Bertestii De Jos" },
  { nume: "Stanca", comuna: "Stancuta" },
  { nume: "Stăncuța", simplu: "Stancuta" },
  { nume: "Stoienești", simplu: "Stoienesti", comuna: "Frecatei" },
  { nume: "Surdila-Găiseanca", simplu: "Surdila-Gaiseanca" },
  { nume: "Surdila-Greci" },
  { nume: "Șuțești", simplu: "Sutesti" },
  { nume: "Țăcău", simplu: "Tacau", comuna: "Marasu" },
  { nume: "Târlele Filiu", simplu: "Tarlele Filiu", comuna: "Ianca" },
  { nume: "Tătaru", simplu: "Tataru", comuna: "Dudesti" },
  { nume: "Țepeș Vodă", simplu: "Tepes Voda", comuna: "Movila Miresii" },
  { nume: "Tichilești", simplu: "Tichilesti" },
  { nume: "Titcov", comuna: "Frecatei" },
  { nume: "Traian" },
  { nume: "Tudor Vladimirescu" },
  { nume: "Tufești", simplu: "Tufesti" },
  { nume: "Ulmu" },
  { nume: "Unirea" },
  { nume: "Urleasca", comuna: "Traian" },
  { nume: "Vădeni", simplu: "Vadeni" },
  {
    nume: "Valea Călmățuiului",
    simplu: "Valea Calmatuiului",
    comuna: "Insuratei",
  },
  { nume: "Valea Cânepii", simplu: "Valea Canepii", comuna: "Unirea" },
  { nume: "Vameșu", simplu: "Vamesu", comuna: "Silistea" },
  { nume: "Vărsătura", simplu: "Varsatura", comuna: "Chiscani" },
  { nume: "Victoria" },
  { nume: "Vișani", simplu: "Visani" },
  { nume: "Viziru" },
  { nume: "Voinești", simplu: "Voinesti", comuna: "Maxineni" },
  { nume: "Vultureni", comuna: "Ciresu" },
  { nume: "Zamfirești", simplu: "Zamfiresti", comuna: "Galbenu" },
  { nume: "Zăvoaia", simplu: "Zavoaia" },
];
