export const bt = [
  { nume: "Albesti" },
  { nume: "Avrameni" },
  { nume: "Botosani" },
  { nume: "Broscauti" },
  { nume: "Braesti" },
  { nume: "Bucecea" },
  { nume: "Baluseni" },
  { nume: "Concesti" },
  { nume: "Copalau" },
  { nume: "Cordareni" },
  { nume: "Corlateni" },
  { nume: "Corni" },
  { nume: "Cosula" },
  { nume: "Cotusca" },
  { nume: "Cristesti" },
  { nume: "Cristinesti" },
  { nume: "Curtesti" },
  { nume: "Candesti" },
  { nume: "Calarasi" },
  { nume: "Darabani" },
  { nume: "Dersca" },
  { nume: "Dimacheni" },
  { nume: "Dobarceni" },
  { nume: "Dorohoi" },
  { nume: "Draguseni" },
  { nume: "Durnesti" },
  { nume: "Dangeni" },
  { nume: "Flamanzi" },
  { nume: "Frumusica" },
  { nume: "George Enescu" },
  { nume: "Gorbanesti" },
  { nume: "Havarna" },
  { nume: "Hiliseu-Horia" },
  { nume: "Hlipiceni" },
  { nume: "Hudesti" },
  { nume: "Hanesti" },
  { nume: "Ibanesti" },
  { nume: "Leorda" },
  { nume: "Lozna" },
  { nume: "Lunca" },
  { nume: "Manoleasa" },
  { nume: "Mihaileni" },
  { nume: "Mihalaseni" },
  { nume: "Mileanca" },
  { nume: "Mitoc" },
  { nume: "Nicseni" },
  { nume: "Pomarla" },
  { nume: "Prajeni" },
  { nume: "Paltinis" },
  { nume: "Ripiceni" },
  { nume: "Roma" },
  { nume: "Romanesti" },
  { nume: "Rachiti" },
  { nume: "Radauti-Prut" },
  { nume: "Rauseni" },
  { nume: "Santa Mare" },
  { nume: "Stauceni" },
  { nume: "Suharau" },
  { nume: "Sulita" },
  { nume: "Saveni" },
  { nume: "Todireni" },
  { nume: "Trusesti" },
  { nume: "Tudora" },
  { nume: "Ungureni" },
  { nume: "Unteni" },
  { nume: "Viisoara" },
  { nume: "Vladeni" },
  { nume: "Vlasinesti" },
  { nume: "Vorniceni" },
  { nume: "Vorona" },
  { nume: "Varfu Campului" },
  { nume: "Vaculesti" },
  { nume: "Sendriceni" },
  { nume: "Stefanesti" },
  { nume: "Stiubieni" },
  { nume: "Buimaceni", comuna: "Albesti" },
  { nume: "Costiugeni", comuna: "Albesti" },
  { nume: "Jijia", comuna: "Albesti" },
  { nume: "Mascateni", comuna: "Albesti" },
  { nume: "Tudor Vladimirescu", comuna: "Albesti" },
  { nume: "Adaseni", comuna: "Avrameni" },
  { nume: "Aurel Vlaicu", comuna: "Avrameni" },
  { nume: "Dimitrie Cantemir", comuna: "Avrameni" },
  { nume: "Ichimeni", comuna: "Avrameni" },
  { nume: "Panaitoaia", comuna: "Avrameni" },
  { nume: "Timus", comuna: "Avrameni" },
  { nume: "Tudor Vladimirescu", comuna: "Avrameni" },
  { nume: "Zoitani", comuna: "Avrameni" },
  { nume: "Buzeni", comuna: "Baluseni" },
  { nume: "Balusenii Noi", comuna: "Baluseni" },
  { nume: "Cosuleni", comuna: "Baluseni" },
  { nume: "Draxini", comuna: "Baluseni" },
  { nume: "Zaicesti", comuna: "Baluseni" },
  { nume: "Blandesti", comuna: "Blindesti" },
  { nume: "Cerchejeni", comuna: "Blindesti" },
  { nume: "Soldanesti", comuna: "Blindesti" },
  { nume: "Poiana", comuna: "Braesti" },
  { nume: "Popeni", comuna: "Braesti" },
  { nume: "Valcelele", comuna: "Braesti" },
  { nume: "Slobozia", comuna: "Broscauti" },
  { nume: "Bohoghina", comuna: "Bucecea" },
  { nume: "Calinesti", comuna: "Bucecea" },
  { nume: "Libertatea", comuna: "Calarasi" },
  { nume: "Plesani", comuna: "Calarasi" },
  { nume: "Calinesti", comuna: "Candesti" },
  { nume: "Talpa", comuna: "Candesti" },
  { nume: "Vitcani", comuna: "Candesti" },
  { nume: "Movileni", comuna: "Concesti" },
  { nume: "Cerbu", comuna: "Copalau" },
  { nume: "Cotu", comuna: "Copalau" },
  { nume: "Grivita", comuna: "Cordareni" },
  { nume: "Slobozia", comuna: "Cordăreni" },
  { nume: "Carasa", comuna: "Corlateni" },
  { nume: "Podeni", comuna: "Corlateni" },
  { nume: "Vladeni", comuna: "Corlateni" },
  { nume: "Balta Arsa", comuna: "Corni" },
  { nume: "Mesteacan", comuna: "Corni" },
  { nume: "Sarafinesti", comuna: "Corni" },
  { nume: "Buda", comuna: "Cosula" },
  { nume: "Padureni", comuna: "Cosula" },
  { nume: "Supitca", comuna: "Cosula" },
  { nume: "Avram Iancu", comuna: "Cotusca" },
  { nume: "Cotu Miculinti", comuna: "Cotusca" },
  { nume: "Crasnaleuca", comuna: "Cotusca" },
  { nume: "Ghireni", comuna: "Cotusca" },
  { nume: "Mihail Kogalniceanu", comuna: "Cotusca" },
  { nume: "Nichiteni", comuna: "Cotusca" },
  { nume: "Nicolae Balcescu", comuna: "Cotusca" },
  { nume: "Putureni", comuna: "Cotusca" },
  { nume: "Oneaga", comuna: "Cristesti" },
  { nume: "Schit-Oraseni", comuna: "Cristesti" },
  { nume: "Unguroaia", comuna: "Cristesti" },
  { nume: "Baranca", comuna: "Cristinesti" },
  { nume: "Dragalina", comuna: "Cristinesti" },
  { nume: "Fundu Hertii", comuna: "Cristinesti" },
  { nume: "Poiana", comuna: "Cristinesti" },
  { nume: "Damileni", comuna: "Cristinești" },
  { nume: "Agafton", comuna: "Curtesti" },
  { nume: "Baiceni", comuna: "Curtesti" },
  { nume: "Hudum", comuna: "Curtesti" },
  { nume: "Manastirea Doamnei", comuna: "Curtesti" },
  { nume: "Oraseni-Deal", comuna: "Curtesti" },
  { nume: "Oraseni-Vale", comuna: "Curtesti" },
  { nume: "Hulub", comuna: "Dangeni" },
  { nume: "Iacobeni", comuna: "Dangeni" },
  { nume: "Strahotin", comuna: "Dangeni" },
  { nume: "Bajura", comuna: "Darabani" },
  { nume: "Esanca", comuna: "Darabani" },
  { nume: "Lismanita", comuna: "Darabani" },
  { nume: "Mateieni", comuna: "Dimacheni" },
  { nume: "Recia-Verbia", comuna: "Dimacheni" },
  { nume: "Bivolari", comuna: "Dobarceni" },
  { nume: "Brateni", comuna: "Dobarceni" },
  { nume: "Cismanesti", comuna: "Dobarceni" },
  { nume: "Livada", comuna: "Dobarceni" },
  { nume: "Murguta", comuna: "Dobarceni" },
  { nume: "Dealu Mare", comuna: "Dorohoi" },
  { nume: "Loturi Enescu", comuna: "Dorohoi" },
  { nume: "Progresul", comuna: "Dorohoi" },
  { nume: "Podriga", comuna: "Draguseni" },
  { nume: "Sarata-Draguseni", comuna: "Draguseni" },
  { nume: "Brosteni", comuna: "Durnesti" },
  { nume: "Barsanesti", comuna: "Durnesti" },
  { nume: "Babiceni", comuna: "Durnesti" },
  { nume: "Cucuteni", comuna: "Durnesti" },
  { nume: "Guranda", comuna: "Durnesti" },
  { nume: "Chitoveni", comuna: "Flamanzi" },
  { nume: "Nicolae Balcescu", comuna: "Flamanzi" },
  { nume: "Poiana", comuna: "Flamanzi" },
  { nume: "Prisacani", comuna: "Flamanzi" },
  { nume: "Boscoteni", comuna: "Frumusica" },
  { nume: "Radeni", comuna: "Frumusica" },
  { nume: "Storesti", comuna: "Frumusica" },
  { nume: "Vladeni-Deal", comuna: "Frumusica" },
  { nume: "Sendreni", comuna: "Frumusica" },
  { nume: "Arborea", comuna: "George Enescu" },
  { nume: "Dumeni", comuna: "George Enescu" },
  { nume: "Popeni", comuna: "George Enescu" },
  { nume: "Stanca", comuna: "George Enescu" },
  { nume: "Batranesti", comuna: "Gorbanesti" },
  { nume: "George Cosbuc", comuna: "Gorbanesti" },
  { nume: "Mihai Eminescu", comuna: "Gorbanesti" },
  { nume: "Siliscani", comuna: "Gorbanesti" },
  { nume: "Socrujeni", comuna: "Gorbanesti" },
  { nume: "Viforeni", comuna: "Gorbanesti" },
  { nume: "Vanatori", comuna: "Gorbanesti" },
  { nume: "Borolea", comuna: "Hanesti" },
  { nume: "Moara Jorii", comuna: "Hanesti" },
  { nume: "Sarata-Basarab", comuna: "Hanesti" },
  { nume: "Slobozia Hanesti", comuna: "Hanesti" },
  { nume: "Balinti", comuna: "Havarna" },
  { nume: "Galbeni", comuna: "Havarna" },
  { nume: "Garbeni", comuna: "Havarna" },
  { nume: "Niculcea", comuna: "Havarna" },
  { nume: "Tataraseni", comuna: "Havarna" },
  { nume: "Corjauti", comuna: "Hiliseu-Horia" },
  { nume: "Hiliseu-Closca", comuna: "Hiliseu-Horia" },
  { nume: "Hiliseu-Crisan", comuna: "Hiliseu-Horia" },
  { nume: "Iezer", comuna: "Hiliseu-Horia" },
  { nume: "Dragalina", comuna: "Hlipiceni" },
  { nume: "Victoria", comuna: "Hlipiceni" },
  { nume: "Alba", comuna: "Hudesti" },
  { nume: "Baranca", comuna: "Hudesti" },
  { nume: "Mlenauti", comuna: "Hudesti" },
  { nume: "Baseu", comuna: "Hudești" },
  { nume: "Vatra", comuna: "Hudești" },
  { nume: "Dumbravita", comuna: "Ibanesti" },
  { nume: "Belcea", comuna: "Leorda" },
  { nume: "Costinesti", comuna: "Leorda" },
  { nume: "Dolina", comuna: "Leorda" },
  { nume: "Mitoc", comuna: "Leorda" },
  { nume: "Strateni", comuna: "Lozna" },
  { nume: "Stroiesti", comuna: "Lunca" },
  { nume: "Zlatunoaia", comuna: "Lunca" },
  { nume: "Bold", comuna: "Manoleasa" },
  { nume: "Flondora", comuna: "Manoleasa" },
  { nume: "Iorga", comuna: "Manoleasa" },
  { nume: "Liveni", comuna: "Manoleasa" },
  { nume: "Loturi", comuna: "Manoleasa" },
  { nume: "Manoleasa-Prut", comuna: "Manoleasa" },
  { nume: "Sadoveni", comuna: "Manoleasa" },
  { nume: "Zahoreni", comuna: "Manoleasa" },
  { nume: "Serpenita", comuna: "Manoleasa" },
  { nume: "Baisa", comuna: "Mihai Eminescu" },
  { nume: "Cervicesti", comuna: "Mihai Eminescu" },
  { nume: "Cervicesti-Deal", comuna: "Mihai Eminescu" },
  { nume: "Cucorani", comuna: "Mihai Eminescu" },
  { nume: "Catamaresti", comuna: "Mihai Eminescu" },
  { nume: "Catamaresti-Deal", comuna: "Mihai Eminescu" },
  { nume: "Ipotesti", comuna: "Mihai Eminescu" },
  { nume: "Manolesti", comuna: "Mihai Eminescu" },
  { nume: "Stancesti", comuna: "Mihai Eminescu" },
  { nume: "Parau Negru", comuna: "Mihaileni" },
  { nume: "Rogojesti", comuna: "Mihaileni" },
  { nume: "Caraiman", comuna: "Mihalaseni" },
  { nume: "Negresti", comuna: "Mihalaseni" },
  { nume: "Nastase", comuna: "Mihalaseni" },
  { nume: "Paun", comuna: "Mihalaseni" },
  { nume: "Sarata", comuna: "Mihalaseni" },
  { nume: "Slobozia Siliscani", comuna: "Mihalaseni" },
  { nume: "Codreni", comuna: "Mileanca" },
  { nume: "Scutari", comuna: "Mileanca" },
  { nume: "Selistea", comuna: "Mileanca" },
  { nume: "Horia", comuna: "Mitoc" },
  { nume: "Dacia", comuna: "Nicseni" },
  { nume: "Dorobanti", comuna: "Nicseni" },
  { nume: "Cuzlau", comuna: "Paltinis" },
  { nume: "Horodistea", comuna: "Paltinis" },
  { nume: "Slobozia", comuna: "Paltinis" },
  { nume: "Hulubesti", comuna: "Pomarla" },
  { nume: "Racovat", comuna: "Pomarla" },
  { nume: "Campeni", comuna: "Prajeni" },
  { nume: "Luparia", comuna: "Prajeni" },
  { nume: "Miletin", comuna: "Prajeni" },
  { nume: "Cismea", comuna: "Rachiti" },
  { nume: "Costesti", comuna: "Rachiti" },
  { nume: "Rosiori", comuna: "Rachiti" },
  { nume: "Miorcani", comuna: "Radauti-Prut" },
  { nume: "Rediu", comuna: "Radauti-Prut" },
  { nume: "Doina", comuna: "Rauseni" },
  { nume: "Pogorasti", comuna: "Rauseni" },
  { nume: "Rediu", comuna: "Rauseni" },
  { nume: "Stolniceni", comuna: "Rauseni" },
  { nume: "Cinghiniia", comuna: "Ripiceni" },
  { nume: "Lehnesti", comuna: "Ripiceni" },
  { nume: "Movila Rupta", comuna: "Ripiceni" },
  { nume: "Popoaia", comuna: "Ripiceni" },
  { nume: "Ripicenii Vechi", comuna: "Ripiceni" },
  { nume: "Rasca", comuna: "Ripiceni" },
  { nume: "Cotargaci", comuna: "Roma" },
  { nume: "Damideni", comuna: "Romanesti" },
  { nume: "Romanesti-Vale", comuna: "Romanesti" },
  { nume: "Sarata", comuna: "Romanesti" },
  { nume: "Berza", comuna: "Santa Mare" },
  { nume: "Bogdanesti", comuna: "Santa Mare" },
  { nume: "Badarai", comuna: "Santa Mare" },
  { nume: "Durnesti", comuna: "Santa Mare" },
  { nume: "Iliseni", comuna: "Santa Mare" },
  { nume: "Ranghilesti", comuna: "Santa Mare" },
  { nume: "Ranghilesti-Deal", comuna: "Santa Mare" },
  { nume: "Bodeasa", comuna: "Saveni" },
  { nume: "Bozieni", comuna: "Saveni" },
  { nume: "Chiscareni", comuna: "Saveni" },
  { nume: "Petricani", comuna: "Saveni" },
  { nume: "Sat Nou", comuna: "Saveni" },
  { nume: "Horlaceni", comuna: "Sendriceni" },
  { nume: "Padureni", comuna: "Sendriceni" },
  { nume: "Silistea", comuna: "Stauceni" },
  { nume: "Tocileni", comuna: "Stauceni" },
  { nume: "Victoria", comuna: "Stauceni" },
  { nume: "Bobulesti", comuna: "Stefanesti" },
  { nume: "Badiuti", comuna: "Stefanesti" },
  { nume: "Stanca", comuna: "Stefanesti" },
  { nume: "Stefanesti-Sat", comuna: "Stefanesti" },
  { nume: "Ibaneasa", comuna: "Stiubieni" },
  { nume: "Negreni", comuna: "Stiubieni" },
  { nume: "Izvoare", comuna: "Suharau" },
  { nume: "Lisna", comuna: "Suharau" },
  { nume: "Oroftiana", comuna: "Suharau" },
  { nume: "Plevna", comuna: "Suharau" },
  { nume: "Smardan", comuna: "Suharau" },
  { nume: "Chelis", comuna: "Sulita" },
  { nume: "Dracsani", comuna: "Sulita" },
  { nume: "Cernesti", comuna: "Todireni" },
  { nume: "Floresti", comuna: "Todireni" },
  { nume: "Garbesti", comuna: "Todireni" },
  { nume: "Iuresti", comuna: "Todireni" },
  { nume: "Buhaceni", comuna: "Trusesti" },
  { nume: "Ciritei", comuna: "Trusesti" },
  { nume: "Drislea", comuna: "Trusesti" },
  { nume: "Ionaseni", comuna: "Trusesti" },
  { nume: "Pasateni", comuna: "Trusesti" },
  { nume: "Borzesti", comuna: "Ungureni" },
  { nume: "Calugareni", comuna: "Ungureni" },
  { nume: "Calugarenii Noi", comuna: "Ungureni" },
  { nume: "Durnesti", comuna: "Ungureni" },
  { nume: "Mihai Viteazu", comuna: "Ungureni" },
  { nume: "Mandresti", comuna: "Ungureni" },
  { nume: "Plopenii Mari", comuna: "Ungureni" },
  { nume: "Plopenii Mici", comuna: "Ungureni" },
  { nume: "Tautesti", comuna: "Ungureni" },
  { nume: "Vicoleni", comuna: "Ungureni" },
  { nume: "Burla", comuna: "Unteni" },
  { nume: "Burlesti", comuna: "Unteni" },
  { nume: "Manastireni", comuna: "Unteni" },
  { nume: "Soroceni", comuna: "Unteni" },
  { nume: "Valea Grajdului", comuna: "Unteni" },
  { nume: "Vultureni", comuna: "Unteni" },
  { nume: "Gorovei", comuna: "Vaculesti" },
  { nume: "Saucenita", comuna: "Vaculesti" },
  { nume: "Ionaseni", comuna: "Varfu Campului" },
  { nume: "Lunca", comuna: "Varfu Campului" },
  { nume: "Cuza Voda", comuna: "Viisoara" },
  { nume: "Viisoara Mica", comuna: "Viisoara" },
  { nume: "Brehuiesti", comuna: "Vladeni" },
  { nume: "Hriscani", comuna: "Vladeni" },
  { nume: "Hutani", comuna: "Vladeni" },
  { nume: "Mandresti", comuna: "Vladeni" },
  { nume: "Miron Costin", comuna: "Vlasinesti" },
  { nume: "Sarbi", comuna: "Vlasinesti" },
  { nume: "Davidoaia", comuna: "Vorniceni" },
  { nume: "Dealu Crucii", comuna: "Vorniceni" },
  { nume: "Icuseni", comuna: "Vorona" },
  { nume: "Joldesti", comuna: "Vorona" },
  { nume: "Poiana", comuna: "Vorona" },
  { nume: "Vorona Mare", comuna: "Vorona" },
  { nume: "Vorona-Teodoru", comuna: "Vorona" },
  { nume: "Dobrinauti-Hapai", comuna: "Vârfu Câmpului" },
  { nume: "Maghera", comuna: "Vârfu Câmpului" },
  { nume: "Pustoaia", comuna: "Vârfu Câmpului" },
];
