export const bc = [
  { nume: "Agăș", simplu: "Agas" },
  { nume: "Albele", comuna: "Barsanesti" },
  { nume: "Antohești", simplu: "Antohesti", comuna: "Izvoru Berheciului" },
  { nume: "Apa Asău", simplu: "Apa Asau", comuna: "Asau" },
  { nume: "Ardeoani" },
  { nume: "Arini", comuna: "Gaiceana" },
  { nume: "Asău", simplu: "Asau" },
  { nume: "Bacău", simplu: "Bacau" },
  { nume: "Băcioiu", simplu: "Bacioiu", comuna: "Corbasca" },
  { nume: "Bâclești", simplu: "Baclesti", comuna: "Motoseni" },
  { nume: "Bahna", comuna: "Pargaresti" },
  { nume: "Băhnășeni", simplu: "Bahnaseni", comuna: "Parjol" },
  { nume: "Băimac", simplu: "Baimac", comuna: "Izvoru Berheciului" },
  { nume: "Bălaia", simplu: "Balaia", comuna: "Filipeni" },
  { nume: "Bălăneasa", simplu: "Balaneasa", comuna: "Livezi" },
  { nume: "Bălănești", simplu: "Balanesti", comuna: "Dealu Morii" },
  { nume: "Bălănești", simplu: "Balanesti", comuna: "Podu Turcului" },
  { nume: "Bâlca", simplu: "Balca", comuna: "Cotofanesti" },
  { nume: "Balcani" },
  { nume: "Balotești", simplu: "Balotesti", comuna: "Stanisesti" },
  { nume: "Bălțata", simplu: "Baltata", comuna: "Nicolae Balcescu" },
  { nume: "Bălușa", simplu: "Balusa", comuna: "Secuieni" },
  { nume: "Banca", comuna: "Dealu Morii" },
  { nume: "Barați", simplu: "Barati", comuna: "Margineni" },
  { nume: "Bărboasa", simplu: "Barboasa", comuna: "Oncesti" },
  { nume: "Barcana", comuna: "Rachitoasa" },
  { nume: "Barna", comuna: "Parincea" },
  { nume: "Bărnești", simplu: "Barnesti", comuna: "Parjol" },
  { nume: "Bârsănești", simplu: "Barsanesti" },
  { nume: "Bărtășești", simplu: "Bartasesti", comuna: "Ungureni" },
  { nume: "Bârzulești", simplu: "Barzulesti", comuna: "Sanduleni" },
  { nume: "Băsăști", simplu: "Basasti", comuna: "Parjol" },
  { nume: "Bazga", comuna: "Horgesti" },
  { nume: "Belciuneasa", comuna: "Stanisesti" },
  { nume: "Beleghet", comuna: "Agas" },
  { nume: "Benești", simplu: "Benesti", comuna: "Stanisesti" },
  { nume: "Berbinceni", comuna: "Secuieni" },
  { nume: "Berești-Bistrița", simplu: "Beresti-Bistrita" },
  { nume: "Berești-Tazlău", simplu: "Beresti-Tazlau" },
  { nume: "Berești", simplu: "Beresti", comuna: "Sascut" },
  { nume: "Berzunți", simplu: "Berzunti" },
  { nume: "Bibirești", simplu: "Bibiresti", comuna: "Ungureni" },
  { nume: "Bijghir", comuna: "Buhoci" },
  { nume: "Blaga", comuna: "Dealu Morii" },
  { nume: "Blăgești", simplu: "Blagesti" },
  { nume: "Blidari", comuna: "Caiuti" },
  { nume: "Boanța", simplu: "Boanta", comuna: "Filipesti" },
  { nume: "Boboș", simplu: "Bobos", comuna: "Dealu Morii" },
  { nume: "Bodeasa", comuna: "Dealu Morii" },
  { nume: "Bogata", comuna: "Dofteana" },
  { nume: "Bogdan Vodă", simplu: "Bogdan Voda", comuna: "Saucesti" },
  { nume: "Bogdana", comuna: "Stefan Cel Mare" },
  { nume: "Bogdănești", simplu: "Bogdanesti" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Scorteni" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Traian" },
  { nume: "Boiștea de Jos", simplu: "Boistea de Jos", comuna: "Cotofanesti" },
  { nume: "Boiștea", simplu: "Boistea", comuna: "Caiuti" },
  { nume: "Bolătău", simplu: "Bolatau", comuna: "Zemes" },
  { nume: "Bolovăniș", simplu: "Bolovanis", comuna: "Ghimes-Faget" },
  { nume: "Borșani", simplu: "Borsani", comuna: "Cotofanesti" },
  { nume: "Borzești", simplu: "Borzesti", comuna: "Onesti" },
  { nume: "Bosia", comuna: "Vultureni" },
  { nume: "Boșoteni", simplu: "Bosoteni", comuna: "Beresti-Tazlau" },
  { nume: "Bostănești", simplu: "Bostanesti", comuna: "Dealu Morii" },
  { nume: "Bota", comuna: "Ungureni" },
  { nume: "Botești", simplu: "Botesti", comuna: "Ungureni" },
  { nume: "Brad", comuna: "Beresti-Bistrita" },
  { nume: "Brad", comuna: "Filipeni" },
  { nume: "Brad", comuna: "Negri" },
  { nume: "Brătești", simplu: "Bratesti", comuna: "Barsanesti" },
  { nume: "Brătila", simplu: "Bratila", comuna: "Helegiu" },
  { nume: "Brusturoasa" },
  { nume: "Buchila", comuna: "Nicolae Balcescu" },
  { nume: "Buciumi", comuna: "Stefan Cel Mare" },
  { nume: "Bucșa", simplu: "Bucsa", comuna: "Rachitoasa" },
  { nume: "Bucșești", simplu: "Bucsesti", comuna: "Poduri" },
  { nume: "Buda", comuna: "Berzunti" },
  { nume: "Buda", comuna: "Blagesti" },
  { nume: "Buda", comuna: "Rachitoasa" },
  { nume: "Budești", simplu: "Budesti", comuna: "Plopana" },
  { nume: "Buhocel", comuna: "Buhoci" },
  { nume: "Buhoci" },
  { nume: "Buhuși", simplu: "Buhusi" },
  { nume: "Burdusaci", comuna: "Rachitoasa" },
  { nume: "Buruieniș", simplu: "Buruienis", comuna: "Brusturoasa" },
  {
    nume: "Buruienișu de Sus",
    simplu: "Buruienisu de Sus",
    comuna: "Brusturoasa",
  },
  { nume: "Căbești", simplu: "Cabesti", comuna: "Podu Turcului" },
  { nume: "Cădărești", simplu: "Cadaresti", comuna: "Palanca" },
  { nume: "Căiuți", simplu: "Caiuti" },
  { nume: "Calapodești", simplu: "Calapodesti", comuna: "Dealu Morii" },
  { nume: "Călcâi", simplu: "Calcai", comuna: "Oituz" },
  { nume: "Călinești", simplu: "Calinesti", comuna: "Negri" },
  { nume: "Călini", simplu: "Calini", comuna: "Colonesti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Damienesti" },
  { nume: "Camenca", comuna: "Brusturoasa" },
  { nume: "Câmpeni", simplu: "Campeni", comuna: "Parjol" },
  { nume: "Capăta", simplu: "Capata", comuna: "Gura Vaii" },
  { nume: "Căpotești", simplu: "Capotesti", comuna: "Huruiesti" },
  { nume: "Caraclău", simplu: "Caraclau", comuna: "Barsanesti" },
  { nume: "Cârligi", simplu: "Carligi", comuna: "Filipesti" },
  { nume: "Cașin", simplu: "Casin" },
  { nume: "Căuia", simplu: "Cauia", comuna: "Dealu Morii" },
  { nume: "Cerdac", comuna: "Slanic Moldova" },
  { nume: "Cernu", comuna: "Poduri" },
  { nume: "Cetățuia", simplu: "Cetatuia", comuna: "Strugari" },
  { nume: "Chetreni", comuna: "Motoseni" },
  { nume: "Chetriș", simplu: "Chetris", comuna: "Tamasi" },
  { nume: "Chicerea", comuna: "Motoseni" },
  { nume: "Chilia Benei", comuna: "Pancesti" },
  { nume: "Chiticeni", comuna: "Secuieni" },
  { nume: "Ciobănuș", simplu: "Ciobanus", comuna: "Asau" },
  { nume: "Cireșoaia", simplu: "Ciresoaia", comuna: "Slanic Moldova" },
  { nume: "Ciucani", comuna: "Racaciuni" },
  { nume: "Ciugheș", simplu: "Ciughes", comuna: "Palanca" },
  { nume: "Ciumași", simplu: "Ciumasi", comuna: "Beresti-Bistrita" },
  { nume: "Ciuturești", simplu: "Ciuturesti", comuna: "Secuieni" },
  { nume: "Cleja" },
  { nume: "Climești", simplu: "Climesti", comuna: "Beresti-Bistrita" },
  { nume: "Cociu", comuna: "Motoseni" },
  { nume: "Colonești", simplu: "Colonesti" },
  { nume: "Coman", comuna: "Sanduleni" },
  { nume: "Comănești", simplu: "Comanesti" },
  { nume: "Conțești", simplu: "Contesti", comuna: "Sascut" },
  { nume: "Corbasca" },
  { nume: "Cornățel", simplu: "Cornatel", comuna: "Urechesti" },
  { nume: "Cornățelu", simplu: "Cornatelu", comuna: "Motoseni" },
  { nume: "Cornești", simplu: "Cornesti", comuna: "Filipesti" },
  { nume: "Cornet", comuna: "Poduri" },
  { nume: "Cornii de Jos", comuna: "Tatarasti" },
  { nume: "Cornii de Sus", comuna: "Tatarasti" },
  { nume: "Coșnea", simplu: "Cosnea", comuna: "Agas" },
  { nume: "Costei", comuna: "Saucesti" },
  { nume: "Coteni", comuna: "Buhoci" },
  { nume: "Coțofănești", simplu: "Cotofanesti" },
  { nume: "Cotu Grosului", comuna: "Filipesti" },
  { nume: "Cotumba", comuna: "Agas" },
  { nume: "Crăiești", simplu: "Craiesti", comuna: "Stanisesti" },
  { nume: "Crihan", comuna: "Magura" },
  { nume: "Cuchiniș", simplu: "Cuchinis", comuna: "Brusturoasa" },
  { nume: "Cucova", comuna: "Valea Seaca" },
  { nume: "Cucuieți", simplu: "Cucuieti", comuna: "Dofteana" },
  { nume: "Cucuieți", simplu: "Cucuieti", comuna: "Solont" },
  { nume: "Curița", simplu: "Curita", comuna: "Casin" },
  { nume: "Dădești", simplu: "Dadesti", comuna: "Vultureni" },
  { nume: "Dămienești", simplu: "Damienesti" },
  { nume: "Dănăila", simplu: "Danaila", comuna: "Rachitoasa" },
  { nume: "Dărmăneasca", simplu: "Darmaneasca", comuna: "Darmanesti" },
  { nume: "Dărmănești", simplu: "Darmanesti" },
  { nume: "Dealu Morii" },
  { nume: "Dealu Perjului", comuna: "Oncesti" },
  { nume: "Dealu-Mare", comuna: "Magura" },
  { nume: "Deleni", comuna: "Helegiu" },
  { nume: "Diaconești", simplu: "Diaconesti", comuna: "Agas" },
  { nume: "Dieneț", simplu: "Dienet", comuna: "Pancesti" },
  { nume: "Dofteana" },
  { nume: "Dorneni", comuna: "Plopana" },
  { nume: "Dorneni", comuna: "Vultureni" },
  { nume: "Dorofei", comuna: "Dealu Morii" },
  { nume: "Dospinești", simplu: "Dospinesti", comuna: "Buhoci" },
  { nume: "Drăgești", simplu: "Dragesti", comuna: "Damienesti" },
  { nume: "Drăgești", simplu: "Dragesti", comuna: "Tatarasti" },
  { nume: "Dragomir", comuna: "Berzunti" },
  { nume: "Drăgugești", simplu: "Dragugesti", comuna: "Helegiu" },
  { nume: "Drăgușani", simplu: "Dragusani", comuna: "Parava" },
  { nume: "Dumbrava", comuna: "Beresti-Bistrita" },
  { nume: "Dumbrava", comuna: "Gura Vaii" },
  { nume: "Dumbrava", comuna: "Rachitoasa" },
  { nume: "Enăchești", simplu: "Enachesti", comuna: "Beresti-Tazlau" },
  { nume: "Făget", simplu: "Faget", comuna: "Ghimes-Faget" },
  { nume: "Făgețel", simplu: "Fagetel", comuna: "Beresti-Bistrita" },
  { nume: "Făgetu de Sus", simplu: "Fagetu de Sus", comuna: "Ghimes-Faget" },
  { nume: "Făghieni", simplu: "Faghieni", comuna: "Izvoru Berheciului" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Hemeius" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Motoseni" },
  { nume: "Faraoani" },
  { nume: "Farcașa", simplu: "Farcasa", comuna: "Rachitoasa" },
  { nume: "Ferestrău-Oituz", simplu: "Ferestrau-Oituz", comuna: "Oituz" },
  { nume: "Fichitești", simplu: "Fichitesti", comuna: "Podu Turcului" },
  { nume: "Filipeni" },
  { nume: "Filipești", simplu: "Filipesti" },
  { nume: "Filipești", simplu: "Filipesti", comuna: "Bogdanesti" },
  { nume: "Florești", simplu: "Floresti", comuna: "Caiuti" },
  { nume: "Florești", simplu: "Floresti", comuna: "Huruiesti" },
  { nume: "Florești", simplu: "Floresti", comuna: "Scorteni" },
  { nume: "Frumoasa", comuna: "Balcani" },
  { nume: "Frumușelu", simplu: "Frumuselu", comuna: "Glavanesti" },
  { nume: "Fruntești", simplu: "Fruntesti", comuna: "Filipeni" },
  { nume: "Fulgeriș", simplu: "Fulgeris", comuna: "Pancesti" },
  {
    nume: "Fundătura Răchitoasa",
    simplu: "Fundatura Rachitoasa",
    comuna: "Rachitoasa",
  },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Motoseni" },
  { nume: "Fundeni", comuna: "Secuieni" },
  { nume: "Fundoaia", comuna: "Huruiesti" },
  { nume: "Fundu Răcăciuni", simplu: "Fundu Racaciuni", comuna: "Racaciuni" },
  { nume: "Fundu Tutovei", comuna: "Plopana" },
  { nume: "Fundu Văii", simplu: "Fundu Vaii", comuna: "Pancesti" },
  { nume: "Furnicari", comuna: "Tamasi" },
  { nume: "Găiceana", simplu: "Gaiceana" },
  { nume: "Galbeni", comuna: "Filipesti" },
  { nume: "Galbeni", comuna: "Nicolae Balcescu" },
  { nume: "Galeri", comuna: "Horgesti" },
  { nume: "Gârla Anei", simplu: "Garla Anei", comuna: "Ungureni" },
  { nume: "Gârleni", simplu: "Garleni" },
  { nume: "Gârlenii de Sus", simplu: "Garlenii de Sus", comuna: "Garleni" },
  { nume: "Gâșteni", simplu: "Gasteni", comuna: "Racaciuni" },
  { nume: "Găzărie", simplu: "Gazarie", comuna: "Moinesti" },
  { nume: "Gheorghe Doja", comuna: "Racaciuni" },
  { nume: "Gherdana", comuna: "Tatarasti" },
  { nume: "Ghilăvești", simplu: "Ghilavesti", comuna: "Vultureni" },
  { nume: "Ghimeș", simplu: "Ghimes", comuna: "Ghimes-Faget" },
  { nume: "Ghionoaia", comuna: "Dealu Morii" },
  { nume: "Gioseni", comuna: "Tamasi" },
  { nume: "Giurgeni", comuna: "Tatarasti" },
  { nume: "Giurgioana", comuna: "Podu Turcului" },
  { nume: "Glăvănești", simplu: "Glavanesti" },
  { nume: "Glodișoarele", simplu: "Glodisoarele", comuna: "Secuieni" },
  {
    nume: "Godineștii de Jos",
    simplu: "Godinestii de Jos",
    comuna: "Vultureni",
  },
  {
    nume: "Godineștii de Sus",
    simplu: "Godinestii de Sus",
    comuna: "Vultureni",
  },
  { nume: "Goioasa", comuna: "Agas" },
  { nume: "Gorghești", simplu: "Gorghesti", comuna: "Stanisesti" },
  { nume: "Grădești", simplu: "Gradesti", comuna: "Dealu Morii" },
  { nume: "Grigoreni", comuna: "Scorteni" },
  { nume: "Gura Crăiești", simplu: "Gura Craiesti", comuna: "Motoseni" },
  { nume: "Gura Văii", simplu: "Gura Vaii" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Racova" },
  { nume: "Gutinaș", simplu: "Gutinas", comuna: "Stefan Cel Mare" },
  { nume: "Hăghiac", simplu: "Haghiac", comuna: "Dofteana" },
  { nume: "Hăghiac", simplu: "Haghiac", comuna: "Rachitoasa" },
  { nume: "Hâineala", simplu: "Haineala", comuna: "Parjol" },
  { nume: "Hălmăcioaia", simplu: "Halmacioaia", comuna: "Racova" },
  { nume: "Hângănești", simplu: "Hanganesti", comuna: "Brusturoasa" },
  { nume: "Hanța", simplu: "Hanta", comuna: "Podu Turcului" },
  { nume: "Hârja", simplu: "Harja", comuna: "Oituz" },
  { nume: "Hârlești", simplu: "Harlesti", comuna: "Filipesti" },
  { nume: "Helegiu" },
  { nume: "Heltiu", comuna: "Caiuti" },
  { nume: "Hemeiuș", simplu: "Hemeius" },
  { nume: "Hemieni", comuna: "Parjol" },
  { nume: "Hertioana de Jos", comuna: "Traian" },
  { nume: "Hertioana-Răzeși", simplu: "Hertioana-Razesi", comuna: "Traian" },
  { nume: "Holt", comuna: "Letea Veche" },
  { nume: "Horgești", simplu: "Horgesti" },
  { nume: "Huruiești", simplu: "Huruiesti" },
  { nume: "Huțu", simplu: "Hutu", comuna: "Gaiceana" },
  { nume: "Iaz", comuna: "Strugari" },
  { nume: "Ilieși", simplu: "Iliesi", comuna: "Racova" },
  { nume: "Ițcani", simplu: "Itcani", comuna: "Plopana" },
  { nume: "Itești", simplu: "Itesti", comuna: "Beresti-Bistrita" },
  { nume: "Izvoru Berheciului" },
  { nume: "Lăpoș", simplu: "Lapos", comuna: "Darmanesti" },
  { nume: "Larga", comuna: "Dofteana" },
  { nume: "Lărguța", simplu: "Larguta", comuna: "Nicolae Balcescu" },
  { nume: "Lehancea", comuna: "Podu Turcului" },
  { nume: "Leontinești", simplu: "Leontinesti", comuna: "Ardeoani" },
  { nume: "Lespezi", comuna: "Garleni" },
  { nume: "Letea Veche" },
  { nume: "Lichitișeni", simplu: "Lichitiseni", comuna: "Vultureni" },
  { nume: "Lilieci", comuna: "Hemeius" },
  { nume: "Lipova" },
  { nume: "Livezi" },
  { nume: "Ludași", simplu: "Ludasi", comuna: "Balcani" },
  { nume: "Luizi-Călugăra", simplu: "Luizi-Calugara" },
  { nume: "Lunca Asău", simplu: "Lunca Asau", comuna: "Asau" },
  { nume: "Lunca Dochiei", comuna: "Urechesti" },
  { nume: "Luncani", comuna: "Margineni" },
  { nume: "Lupești", simplu: "Lupesti", comuna: "Manastirea Casin" },
  { nume: "Magazia", comuna: "Rachitoasa" },
  { nume: "Măgirești", simplu: "Magiresti" },
  { nume: "Mâgla", simplu: "Magla", comuna: "Negri" },
  { nume: "Măgura", simplu: "Magura" },
  { nume: "Mâlosu", simplu: "Malosu", comuna: "Lipova" },
  { nume: "Mănăstirea Cașin", simplu: "Manastirea Casin" },
  { nume: "Mărăscu", simplu: "Marascu", comuna: "Horgesti" },
  { nume: "Mărăști", simplu: "Marasti", comuna: "Filipeni" },
  { nume: "Mărcești", simplu: "Marcesti", comuna: "Caiuti" },
  { nume: "Marginea", comuna: "Buhusi" },
  { nume: "Marginea", comuna: "Oituz" },
  { nume: "Mărgineni", simplu: "Margineni" },
  { nume: "Marvila", comuna: "Corbasca" },
  { nume: "Mateiești", simplu: "Mateiesti", comuna: "Sanduleni" },
  { nume: "Medeleni", comuna: "Vultureni" },
  { nume: "Mileștii de Jos", simplu: "Milestii de Jos", comuna: "Parincea" },
  { nume: "Mileștii de Sus", simplu: "Milestii de Sus", comuna: "Parincea" },
  { nume: "Misihănești", simplu: "Misihanesti", comuna: "Rosiori" },
  { nume: "Moinești", simplu: "Moinesti" },
  { nume: "Motoc", comuna: "Pancesti" },
  { nume: "Motocești", simplu: "Motocesti", comuna: "Gura Vaii" },
  { nume: "Motoșeni", simplu: "Motoseni" },
  { nume: "Movilița", simplu: "Movilita", comuna: "Rachitoasa" },
  { nume: "Muncelu", comuna: "Glavanesti" },
  { nume: "Nadișa", simplu: "Nadisa", comuna: "Strugari" },
  { nume: "Nănești", simplu: "Nanesti", comuna: "Parincea" },
  { nume: "Năstăseni", simplu: "Nastaseni", comuna: "Parincea" },
  { nume: "Năzărioaia", simplu: "Nazarioaia", comuna: "Vultureni" },
  { nume: "Negoiești", simplu: "Negoiesti", comuna: "Stefan Cel Mare" },
  { nume: "Negreni", comuna: "Poduri" },
  { nume: "Negri" },
  { nume: "Negulești", simplu: "Negulesti", comuna: "Dealu Morii" },
  { nume: "Negușeni", simplu: "Neguseni", comuna: "Rosiori" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu" },
  { nume: "Nicorești", simplu: "Nicoresti", comuna: "Pargaresti" },
  { nume: "Obârșia", simplu: "Obarsia", comuna: "Izvoru Berheciului" },
  { nume: "Ocheni", comuna: "Huruiesti" },
  { nume: "Odobești", simplu: "Odobesti", comuna: "Secuieni" },
  { nume: "Oituz" },
  { nume: "Oncești", simplu: "Oncesti" },
  { nume: "Onceștii Vechi", simplu: "Oncestii Vechi", comuna: "Oncesti" },
  { nume: "Onești", simplu: "Onesti" },
  { nume: "Onișcani", simplu: "Oniscani", comuna: "Filipesti" },
  { nume: "Oprișești", simplu: "Oprisesti", comuna: "Rachitoasa" },
  { nume: "Orășa", simplu: "Orasa", comuna: "Livezi" },
  { nume: "Orbeni" },
  { nume: "Osebiți", simplu: "Osebiti", comuna: "Luizi-Calugara" },
  { nume: "Oțelești", simplu: "Otelesti", comuna: "Izvoru Berheciului" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Beresti-Bistrita" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Damienesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Filipeni" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Izvoru Berheciului" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Margineni" },
  { nume: "Păgubeni", simplu: "Pagubeni", comuna: "Darmanesti" },
  { nume: "Pajiștea", simplu: "Pajistea", comuna: "Palanca" },
  { nume: "Palanca" },
  { nume: "Păltinata", simplu: "Paltinata", comuna: "Gura Vaii" },
  { nume: "Păltiniș", simplu: "Paltinis", comuna: "Asau" },
  { nume: "Pâncești", simplu: "Pancesti" },
  { nume: "Păncești", simplu: "Pancesti", comuna: "Sascut" },
  { nume: "Pârâu Boghii", simplu: "Parau Boghii", comuna: "Pargaresti" },
  { nume: "Parava" },
  { nume: "Pârgărești", simplu: "Pargaresti" },
  { nume: "Parincea" },
  { nume: "Pârjol", simplu: "Parjol" },
  { nume: "Pârvulești", simplu: "Parvulesti", comuna: "Manastirea Casin" },
  { nume: "Perchiu", comuna: "Huruiesti" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Pancesti" },
  { nume: "Petricica", comuna: "Strugari" },
  { nume: "Plopana" },
  { nume: "Plopu", comuna: "Darmanesti" },
  { nume: "Plopu", comuna: "Podu Turcului" },
  { nume: "Podei", comuna: "Comanesti" },
  { nume: "Podiș", simplu: "Podis", comuna: "Margineni" },
  { nume: "Podu Turcului" },
  { nume: "Poduri" },
  { nume: "Pogleț", simplu: "Poglet", comuna: "Corbasca" },
  { nume: "Poiana Negustorului", comuna: "Blagesti" },
  { nume: "Poiana Sărată", simplu: "Poiana Sarata", comuna: "Oituz" },
  { nume: "Poiana", comuna: "Colonesti" },
  { nume: "Poiana", comuna: "Livezi" },
  { nume: "Poiana", comuna: "Margineni" },
  { nume: "Poiana", comuna: "Motoseni" },
  { nume: "Poiana", comuna: "Negri" },
  { nume: "Poieni", comuna: "Parincea" },
  { nume: "Poieni", comuna: "Rosiori" },
  { nume: "Poieni", comuna: "Targu Ocna" },
  { nume: "Popeni", comuna: "Caiuti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Gaiceana" },
  { nume: "Popoiu", comuna: "Palanca" },
  { nume: "Prădaiș", simplu: "Pradais", comuna: "Huruiesti" },
  { nume: "Praja", comuna: "Motoseni" },
  { nume: "Prăjești", simplu: "Prajesti", comuna: "Magiresti" },
  { nume: "Prăjești", simplu: "Prajesti", comuna: "Traian" },
  { nume: "Prajoaia", comuna: "Livezi" },
  { nume: "Pralea", comuna: "Caiuti" },
  { nume: "Preluci", comuna: "Agas" },
  { nume: "Prisaca", comuna: "Beresti-Tazlau" },
  { nume: "Prohozești", simplu: "Prohozesti", comuna: "Poduri" },
  { nume: "Pustiana", comuna: "Parjol" },
  { nume: "Putini", comuna: "Rachitoasa" },
  { nume: "Putredeni", comuna: "Glavanesti" },
  { nume: "Răcăciuni", simplu: "Racaciuni" },
  { nume: "Răcătău de Jos", simplu: "Racatau de Jos", comuna: "Horgesti" },
  { nume: "Răcătău-Răzeși", simplu: "Racatau-Razesi", comuna: "Horgesti" },
  { nume: "Răcăuți", simplu: "Racauti", comuna: "Stefan Cel Mare" },
  { nume: "Răchitiș", simplu: "Rachitis", comuna: "Ghimes-Faget" },
  { nume: "Răchitișu", simplu: "Rachitisu", comuna: "Strugari" },
  { nume: "Răchitoasa", simplu: "Rachitoasa" },
  { nume: "Racova" },
  { nume: "Răcușana", simplu: "Racusana", comuna: "Podu Turcului" },
  { nume: "Rădeana", simplu: "Radeana", comuna: "Stefan Cel Mare" },
  { nume: "Rădoaia", simplu: "Radoaia", comuna: "Parava" },
  { nume: "Radomirești", simplu: "Radomiresti", comuna: "Letea Veche" },
  { nume: "Răstoaca", simplu: "Rastoaca", comuna: "Racaciuni" },
  { nume: "Răzeșu", simplu: "Razesu", comuna: "Glavanesti" },
  { nume: "Recea", comuna: "Horgesti" },
  { nume: "Reprivăț", simplu: "Reprivat", comuna: "Vultureni" },
  { nume: "Rogoaza", comuna: "Corbasca" },
  { nume: "Românești", simplu: "Romanesti", comuna: "Beresti-Tazlau" },
  { nume: "Roșiori", simplu: "Rosiori" },
  { nume: "Rotăria", simplu: "Rotaria", comuna: "Motoseni" },
  { nume: "Runcu", comuna: "Buhusi" },
  { nume: "Rusenii de Sus", comuna: "Plopana" },
  { nume: "Rusenii Răzeși", simplu: "Rusenii Razesi", comuna: "Plopana" },
  { nume: "Ruși-Ciutea", simplu: "Rusi-Ciutea", comuna: "Letea Veche" },
  { nume: "Sălătruc", simplu: "Salatruc", comuna: "Darmanesti" },
  { nume: "Sănduleni", simplu: "Sanduleni" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Nicolae Balcescu" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Solont" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Podu Turcului" },
  { nume: "Sascut-Sat", comuna: "Sascut" },
  { nume: "Sascut" },
  { nume: "Satu Nou", comuna: "Colonesti" },
  { nume: "Satu Nou", comuna: "Lipova" },
  { nume: "Satu Nou", comuna: "Oncesti" },
  { nume: "Satu Nou", comuna: "Pargaresti" },
  { nume: "Satu Nou", comuna: "Parincea" },
  { nume: "Satu Nou", comuna: "Urechesti" },
  { nume: "Săucești", simplu: "Saucesti" },
  { nume: "Scăriga", simplu: "Scariga", comuna: "Livezi" },
  { nume: "Scărișoara", simplu: "Scarisoara", comuna: "Corbasca" },
  { nume: "Schineni", comuna: "Sascut" },
  { nume: "Schineni", comuna: "Saucesti" },
  { nume: "Schitu Frumoasa", comuna: "Balcani" },
  { nume: "Scorțeni", simplu: "Scorteni" },
  { nume: "Scurta", comuna: "Orbeni" },
  { nume: "Scutaru", comuna: "Manastirea Casin" },
  { nume: "Seaca", comuna: "Dofteana" },
  { nume: "Secuieni" },
  { nume: "Șendrești", simplu: "Sendresti", comuna: "Motoseni" },
  { nume: "Șerbești", simplu: "Serbesti", comuna: "Saucesti" },
  { nume: "Șerpeni", simplu: "Serpeni", comuna: "Scorteni" },
  { nume: "Șesuri", simplu: "Sesuri", comuna: "Magiresti" },
  { nume: "Siretu", comuna: "Letea Veche" },
  { nume: "Siretu", comuna: "Saucesti" },
  {
    nume: "Slănic-Moldova",
    simplu: "Slanic-Moldova",
    comuna: "Slanic Moldova",
  },
  { nume: "Slobozia Nouă", simplu: "Slobozia Noua", comuna: "Stanisesti" },
  { nume: "Slobozia", comuna: "Filipeni" },
  { nume: "Slobozia", comuna: "Onesti" },
  { nume: "Slobozia", comuna: "Stanisesti" },
  { nume: "Slobozia", comuna: "Urechesti" },
  { nume: "Soci", comuna: "Pancesti" },
  { nume: "Sohodol", comuna: "Magura" },
  { nume: "Sohodor", comuna: "Horgesti" },
  { nume: "Solonț", simplu: "Solont" },
  { nume: "Somușca", simplu: "Somusca", comuna: "Cleja" },
  { nume: "Spria", comuna: "Colonesti" },
  { nume: "Stănești", simplu: "Stanesti", comuna: "Magiresti" },
  { nume: "Stănișești", simplu: "Stanisesti" },
  { nume: "Ștefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Ștefan Vodă", simplu: "Stefan Voda", comuna: "Dofteana" },
  { nume: "Stejaru", comuna: "Scorteni" },
  { nume: "Straja", comuna: "Asau" },
  { nume: "Străminoasa", simplu: "Straminoasa", comuna: "Plopana" },
  { nume: "Strugari" },
  { nume: "Stufu", comuna: "Sanduleni" },
  { nume: "Sulța", simplu: "Sulta", comuna: "Agas" },
  { nume: "Șurina", simplu: "Surina", comuna: "Garleni" },
  { nume: "Țâgâra", simplu: "Tagara", comuna: "Plopana" },
  { nume: "Tamași", simplu: "Tamasi" },
  { nume: "Tămășoaia", simplu: "Tamasoaia", comuna: "Cotofanesti" },
  { nume: "Tărâța", simplu: "Tarata", comuna: "Parjol" },
  { nume: "Țârdenii Mari", simplu: "Tardenii Mari", comuna: "Blagesti" },
  { nume: "Târgu Ocna", simplu: "Targu Ocna" },
  { nume: "Târgu Trotuș", simplu: "Targu Trotus" },
  { nume: "Tărhăuși", simplu: "Tarhausi", comuna: "Ghimes-Faget" },
  { nume: "Tarnița", simplu: "Tarnita", comuna: "Oncesti" },
  { nume: "Tătărăști", simplu: "Tatarasti" },
  { nume: "Taula", comuna: "Oncesti" },
  { nume: "Tăvădărești", simplu: "Tavadaresti", comuna: "Dealu Morii" },
  { nume: "Teiuș", simplu: "Teius", comuna: "Parava" },
  { nume: "Temelia", comuna: "Gura Vaii" },
  { nume: "Țepoaia", simplu: "Tepoaia", comuna: "Motoseni" },
  { nume: "Tescani", comuna: "Beresti-Tazlau" },
  { nume: "Țigănești", simplu: "Tiganesti", comuna: "Vultureni" },
  { nume: "Tisa-Silvestri", comuna: "Secuieni" },
  { nume: "Tisa", comuna: "Sanduleni" },
  { nume: "Tochilea", comuna: "Rachitoasa" },
  { nume: "Tomozia", comuna: "Vultureni" },
  { nume: "Traian" },
  { nume: "Trebeș", simplu: "Trebes", comuna: "Margineni" },
  { nume: "Turluianu", comuna: "Beresti-Tazlau" },
  { nume: "Tuta", comuna: "Targu Trotus" },
  { nume: "Ungureni" },
  { nume: "Ungureni", comuna: "Tatarasti" },
  { nume: "Urechești", simplu: "Urechesti" },
  { nume: "Ursoaia", comuna: "Negri" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Corbasca" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Targu Ocna" },
  { nume: "Valea Arinilor", comuna: "Magiresti" },
  { nume: "Valea Boțului", simplu: "Valea Botului", comuna: "Filipeni" },
  { nume: "Valea Budului", comuna: "Margineni" },
  { nume: "Valea Caselor", comuna: "Lipova" },
  { nume: "Valea Fânațului", simplu: "Valea Fanatului", comuna: "Secuieni" },
  { nume: "Valea Hogei", comuna: "Lipova" },
  { nume: "Valea lui Ion", comuna: "Blagesti" },
  { nume: "Valea Lupului", comuna: "Vultureni" },
  { nume: "Valea Mare", comuna: "Colonesti" },
  { nume: "Valea Mare", comuna: "Rosiori" },
  { nume: "Valea Mărului", simplu: "Valea Marului", comuna: "Lipova" },
  { nume: "Valea Merilor", comuna: "Vultureni" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Cleja" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Rosiori" },
  { nume: "Valea Moșneagului", simplu: "Valea Mosneagului", comuna: "Lipova" },
  { nume: "Valea Nacului", comuna: "Sascut" },
  { nume: "Valea Salciei", comuna: "Vultureni" },
  { nume: "Valea Seacă", simplu: "Valea Seaca" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Nicolae Balcescu" },
  { nume: "Valea Șoșii", simplu: "Valea Sosii", comuna: "Poduri" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Parincea" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Secuieni" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Stanisesti" },
  { nume: "Vermești", simplu: "Vermesti", comuna: "Comanesti" },
  { nume: "Verșești", simplu: "Versesti", comuna: "Sanduleni" },
  { nume: "Viforeni", comuna: "Ungureni" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Stefan Cel Mare" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Targu Trotus" },
  { nume: "Vladnic", comuna: "Parincea" },
  { nume: "Vrânceni", simplu: "Vranceni", comuna: "Caiuti" },
  { nume: "Vultureni" },
  { nume: "Zăpodia", simplu: "Zapodia", comuna: "Colonesti" },
  { nume: "Zăpodia", simplu: "Zapodia", comuna: "Traian" },
  { nume: "Zemeș", simplu: "Zemes" },
  { nume: "Zlătari", simplu: "Zlatari", comuna: "Ungureni" },
];
