export const bv = [
  { nume: "Apata" },
  { nume: "Beclean" },
  { nume: "Bod" },
  { nume: "Bran" },
  { nume: "Brasov" },
  { nume: "Budila" },
  { nume: "Bunesti" },
  { nume: "Cata" },
  { nume: "Cincu" },
  { nume: "Codlea" },
  { nume: "Cristian" },
  { nume: "Crizbav" },
  { nume: "Dumbravita" },
  { nume: "Feldioara" },
  { nume: "Fundata" },
  { nume: "Fagaras" },
  { nume: "Ghimbav" },
  { nume: "Hoghiz" },
  { nume: "Homorod" },
  { nume: "Harseni" },
  { nume: "Halchiu" },
  { nume: "Harman" },
  { nume: "Jibert" },
  { nume: "Lisa" },
  { nume: "Mandra" },
  { nume: "Maierus" },
  { nume: "Ormenis" },
  { nume: "Poiana Marului" },
  { nume: "Predeal" },
  { nume: "Prejmer" },
  { nume: "Parau" },
  { nume: "Racos" },
  { nume: "Recea" },
  { nume: "Rupea" },
  { nume: "Rasnov" },
  { nume: "Sambata de Sus" },
  { nume: "Sanpetru" },
  { nume: "Sacele" },
  { nume: "Teliu" },
  { nume: "Tarlungeni" },
  { nume: "Ungra" },
  { nume: "Vama Buzaului" },
  { nume: "Victoria" },
  { nume: "Voila" },
  { nume: "Vulcan" },
  { nume: "Zarnesti" },
  { nume: "Sercaia" },
  { nume: "Sinca Noua" },
  { nume: "Soars" },
  { nume: "Boholt", comuna: "Beclean" },
  { nume: "Calbor", comuna: "Beclean" },
  { nume: "Hurez", comuna: "Beclean" },
  { nume: "Luta", comuna: "Beclean" },
  { nume: "Colonia Bod", comuna: "Bod" },
  { nume: "Predelut", comuna: "Bran" },
  { nume: "Sohodol", comuna: "Bran" },
  { nume: "Simon", comuna: "Bran" },
  { nume: "Poiana Brasov", comuna: "Brasov" },
  { nume: "Crit", comuna: "Bunesti" },
  { nume: "Mesendorf", comuna: "Bunesti" },
  { nume: "Roades", comuna: "Bunesti" },
  { nume: "Viscri", comuna: "Bunesti" },
  { nume: "Beia", comuna: "Cata" },
  { nume: "Drauseni", comuna: "Cata" },
  { nume: "Ionesti", comuna: "Cata" },
  { nume: "Palos", comuna: "Cata" },
  { nume: "Toarcla", comuna: "Cincu" },
  { nume: "Comana de Jos", comuna: "Comana" },
  { nume: "Comana de Sus", comuna: "Comana" },
  { nume: "Crihalma", comuna: "Comana" },
  { nume: "Ticusu Nou", comuna: "Comana" },
  { nume: "Cutus", comuna: "Crizbav" },
  { nume: "Vladeni", comuna: "Dumbravita" },
  { nume: "Colonia Reconstructia", comuna: "Feldioara" },
  { nume: "Rotbav", comuna: "Feldioara" },
  { nume: "Fundatica", comuna: "Fundata" },
  { nume: "Sirnea", comuna: "Fundata" },
  { nume: "Satu Nou", comuna: "Halchiu" },
  { nume: "Podu Oltului", comuna: "Harman" },
  { nume: "Copacel", comuna: "Harseni" },
  { nume: "Malinis", comuna: "Harseni" },
  { nume: "Margineni", comuna: "Harseni" },
  { nume: "Sebes", comuna: "Harseni" },
  { nume: "Bogata Olteana", comuna: "Hoghiz" },
  { nume: "Cuciulata", comuna: "Hoghiz" },
  { nume: "Dopca", comuna: "Hoghiz" },
  { nume: "Fantana", comuna: "Hoghiz" },
  { nume: "Lupsa", comuna: "Hoghiz" },
  { nume: "Jimbor", comuna: "Homorod" },
  { nume: "Mercheasa", comuna: "Homorod" },
  { nume: "Dacia", comuna: "Jibert" },
  { nume: "Granari", comuna: "Jibert" },
  { nume: "Lovnic", comuna: "Jibert" },
  { nume: "Valeni", comuna: "Jibert" },
  { nume: "Breaza", comuna: "Lisa" },
  { nume: "Pojorta", comuna: "Lisa" },
  { nume: "Arini", comuna: "Maierus" },
  { nume: "Ileni", comuna: "Mandra" },
  { nume: "Rausor", comuna: "Mandra" },
  { nume: "Toderita", comuna: "Mandra" },
  { nume: "Sona", comuna: "Mandra" },
  { nume: "Cheia", comuna: "Moieciu" },
  { nume: "Drumul Carului", comuna: "Moieciu" },
  { nume: "Moieciu de Jos", comuna: "Moieciu" },
  { nume: "Moieciu de Sus", comuna: "Moieciu" },
  { nume: "Magura", comuna: "Moieciu" },
  { nume: "Pestera", comuna: "Moieciu" },
  { nume: "Augustin", comuna: "Ormenis" },
  { nume: "Grid", comuna: "Parau" },
  { nume: "Venetia de Jos", comuna: "Parau" },
  { nume: "Venetia de Sus", comuna: "Parau" },
  { nume: "Paraul Rece", comuna: "Predeal" },
  { nume: "Timisu de Jos", comuna: "Predeal" },
  { nume: "Timisu de Sus", comuna: "Predeal" },
  { nume: "Lunca Calnicului", comuna: "Prejmer" },
  { nume: "Stupinii Prejmerului", comuna: "Prejmer" },
  { nume: "Mateias", comuna: "Racos" },
  { nume: "Berivoi", comuna: "Recea" },
  { nume: "Dejani", comuna: "Recea" },
  { nume: "Gura Vaii", comuna: "Recea" },
  { nume: "Iasi", comuna: "Recea" },
  { nume: "Sasciori", comuna: "Recea" },
  { nume: "Savastreni", comuna: "Recea" },
  { nume: "Fiser", comuna: "Rupea" },
  { nume: "Statiunea Climaterica Sambata", comuna: "Sambata De Sus" },
  { nume: "Halmeag", comuna: "Sercaia" },
  { nume: "Vad", comuna: "Sercaia" },
  { nume: "Bucium", comuna: "Sinca" },
  { nume: "Ohaba", comuna: "Sinca" },
  { nume: "Persani", comuna: "Sinca" },
  { nume: "Valcea", comuna: "Sinca" },
  { nume: "Sercaita", comuna: "Sinca" },
  { nume: "Sinca Veche", comuna: "Sinca" },
  { nume: "Paltin", comuna: "Sinca Noua" },
  { nume: "Barcut", comuna: "Soars" },
  { nume: "Felmer", comuna: "Soars" },
  { nume: "Rodbav", comuna: "Soars" },
  { nume: "Selistat", comuna: "Soars" },
  { nume: "Carpinis", comuna: "Tarlungeni" },
  { nume: "Purcareni", comuna: "Tarlungeni" },
  { nume: "Zizin", comuna: "Tarlungeni" },
  { nume: "Cobor", comuna: "Ticusu" },
  { nume: "Ticusu Vechi", comuna: "Ticusu" },
  { nume: "Corbi", comuna: "Ucea" },
  { nume: "Feldioara", comuna: "Ucea" },
  { nume: "Ucea de Jos", comuna: "Ucea" },
  { nume: "Ucea de Sus", comuna: "Ucea" },
  { nume: "Daisoara", comuna: "Ungra" },
  { nume: "Acris", comuna: "Vama Buzaului" },
  { nume: "Buzaiel", comuna: "Vama Buzaului" },
  { nume: "Dalghiu", comuna: "Vama Buzaului" },
  { nume: "Dragus", comuna: "Vistea" },
  { nume: "Oltet", comuna: "Vistea" },
  { nume: "Rucar", comuna: "Vistea" },
  { nume: "Vistea de Jos", comuna: "Vistea" },
  { nume: "Vistea de Sus", comuna: "Vistea" },
  { nume: "Vistisoara", comuna: "Vistea" },
  { nume: "Cincsor", comuna: "Voila" },
  { nume: "Dridif", comuna: "Voila" },
  { nume: "Ludisor", comuna: "Voila" },
  { nume: "Sambata de Jos", comuna: "Voila" },
  { nume: "Voivodeni", comuna: "Voila" },
  { nume: "Colonia 1 Mai", comuna: "Vulcan" },
  { nume: "Holbav", comuna: "Vulcan" },
  { nume: "Tohanu Nou", comuna: "Zarnesti" },
];
