export const bv = [
  { nume: "Acriș", simplu: "Acris", comuna: "Vama Buzaului" },
  { nume: "Apața", simplu: "Apata" },
  { nume: "Arini", comuna: "Maierus" },
  { nume: "Augustin", comuna: "Ormenis" },
  { nume: "Bărcut", simplu: "Barcut", comuna: "Soars" },
  { nume: "Beclean" },
  { nume: "Beia", comuna: "Cata" },
  { nume: "Berivoi", comuna: "Recea" },
  { nume: "Bod" },
  { nume: "Bogata Olteană", simplu: "Bogata Olteana", comuna: "Hoghiz" },
  { nume: "Boholț", simplu: "Boholt", comuna: "Beclean" },
  { nume: "Bran" },
  { nume: "Brașov", simplu: "Brasov" },
  { nume: "Breaza", comuna: "Lisa" },
  { nume: "Bucium", comuna: "Sinca" },
  { nume: "Budila" },
  { nume: "Bunești", simplu: "Bunesti" },
  { nume: "Buzăiel", simplu: "Buzaiel", comuna: "Vama Buzaului" },
  { nume: "Calbor", comuna: "Beclean" },
  { nume: "Cărpiniș", simplu: "Carpinis", comuna: "Tarlungeni" },
  { nume: "Cața", simplu: "Cata" },
  { nume: "Cheia", comuna: "Moieciu" },
  { nume: "Cincșor", simplu: "Cincsor", comuna: "Voila" },
  { nume: "Cincu" },
  { nume: "Cobor", comuna: "Ticusu" },
  { nume: "Codlea" },
  { nume: "Colonia 1 Mai", comuna: "Vulcan" },
  { nume: "Colonia Bod", comuna: "Bod" },
  {
    nume: "Colonia Reconstrucția",
    simplu: "Colonia Reconstructia",
    comuna: "Feldioara",
  },
  { nume: "Comana de Jos", comuna: "Comana" },
  { nume: "Comana de Sus", comuna: "Comana" },
  { nume: "Copăcel", simplu: "Copacel", comuna: "Harseni" },
  { nume: "Corbi", comuna: "Ucea" },
  { nume: "Crihalma", comuna: "Comana" },
  { nume: "Cristian" },
  { nume: "Criț", simplu: "Crit", comuna: "Bunesti" },
  { nume: "Crizbav" },
  { nume: "Cuciulata", comuna: "Hoghiz" },
  { nume: "Cutuș", simplu: "Cutus", comuna: "Crizbav" },
  { nume: "Dacia", comuna: "Jibert" },
  { nume: "Dăișoara", simplu: "Daisoara", comuna: "Ungra" },
  { nume: "Dălghiu", simplu: "Dalghiu", comuna: "Vama Buzaului" },
  { nume: "Dejani", comuna: "Recea" },
  { nume: "Dopca", comuna: "Hoghiz" },
  { nume: "Drăguș", simplu: "Dragus", comuna: "Vistea" },
  { nume: "Drăușeni", simplu: "Drauseni", comuna: "Cata" },
  { nume: "Dridif", comuna: "Voila" },
  { nume: "Drumul Carului", comuna: "Moieciu" },
  { nume: "Dumbrăvița", simplu: "Dumbravita" },
  { nume: "Făgăraș", simplu: "Fagaras" },
  { nume: "Fântâna", simplu: "Fantana", comuna: "Hoghiz" },
  { nume: "Feldioara" },
  { nume: "Feldioara", comuna: "Ucea" },
  { nume: "Felmer", comuna: "Soars" },
  { nume: "Fișer", simplu: "Fiser", comuna: "Rupea" },
  { nume: "Fundata" },
  { nume: "Fundățica", simplu: "Fundatica", comuna: "Fundata" },
  { nume: "Ghimbav" },
  { nume: "Grânari", simplu: "Granari", comuna: "Jibert" },
  { nume: "Grid", comuna: "Parau" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Recea" },
  { nume: "Hălchiu", simplu: "Halchiu" },
  { nume: "Hălmeag", simplu: "Halmeag", comuna: "Sercaia" },
  { nume: "Hărman", simplu: "Harman" },
  { nume: "Hârseni", simplu: "Harseni" },
  { nume: "Hoghiz" },
  { nume: "Holbav", comuna: "Vulcan" },
  { nume: "Homorod" },
  { nume: "Hurez", comuna: "Beclean" },
  { nume: "Iași", simplu: "Iasi", comuna: "Recea" },
  { nume: "Ileni", comuna: "Mandra" },
  { nume: "Ionești", simplu: "Ionesti", comuna: "Cata" },
  { nume: "Jibert" },
  { nume: "Jimbor", comuna: "Homorod" },
  { nume: "Lisa" },
  { nume: "Lovnic", comuna: "Jibert" },
  { nume: "Ludișor", simplu: "Ludisor", comuna: "Voila" },
  { nume: "Lunca Calnicului", comuna: "Prejmer" },
  { nume: "Lupșa", simplu: "Lupsa", comuna: "Hoghiz" },
  { nume: "Luța", simplu: "Luta", comuna: "Beclean" },
  { nume: "Măgura", simplu: "Magura", comuna: "Moieciu" },
  { nume: "Măieruș", simplu: "Maierus" },
  { nume: "Măliniș", simplu: "Malinis", comuna: "Harseni" },
  { nume: "Mândra", simplu: "Mandra" },
  { nume: "Mărgineni", simplu: "Margineni", comuna: "Harseni" },
  { nume: "Mateiaș", simplu: "Mateias", comuna: "Racos" },
  { nume: "Mercheașa", simplu: "Mercheasa", comuna: "Homorod" },
  { nume: "Meșendorf", simplu: "Mesendorf", comuna: "Bunesti" },
  { nume: "Moieciu de Jos", comuna: "Moieciu" },
  { nume: "Moieciu de Sus", comuna: "Moieciu" },
  { nume: "Ohaba", comuna: "Sinca" },
  { nume: "Olteț", simplu: "Oltet", comuna: "Vistea" },
  { nume: "Ormeniș", simplu: "Ormenis" },
  { nume: "Paloș", simplu: "Palos", comuna: "Cata" },
  { nume: "Paltin", comuna: "Sinca Noua" },
  { nume: "Părău", simplu: "Parau" },
  { nume: "Pârâul Rece", simplu: "Paraul Rece", comuna: "Predeal" },
  { nume: "Perșani", simplu: "Persani", comuna: "Sinca" },
  { nume: "Peștera", simplu: "Pestera", comuna: "Moieciu" },
  { nume: "Podu Oltului", comuna: "Harman" },
  { nume: "Poiana Brașov", simplu: "Poiana Brasov", comuna: "Brasov" },
  { nume: "Poiana Mărului", simplu: "Poiana Marului" },
  { nume: "Pojorta", comuna: "Lisa" },
  { nume: "Predeal" },
  { nume: "Predeluț", simplu: "Predelut", comuna: "Bran" },
  { nume: "Prejmer" },
  { nume: "Purcăreni", simplu: "Purcareni", comuna: "Tarlungeni" },
  { nume: "Racoș", simplu: "Racos" },
  { nume: "Râșnov", simplu: "Rasnov" },
  { nume: "Râușor", simplu: "Rausor", comuna: "Mandra" },
  { nume: "Recea" },
  { nume: "Roadeș", simplu: "Roades", comuna: "Bunesti" },
  { nume: "Rodbav", comuna: "Soars" },
  { nume: "Rotbav", comuna: "Feldioara" },
  { nume: "Rucăr", simplu: "Rucar", comuna: "Vistea" },
  { nume: "Rupea" },
  { nume: "Săcele", simplu: "Sacele" },
  { nume: "Sâmbăta de Jos", simplu: "Sambata de Jos", comuna: "Voila" },
  { nume: "Sâmbăta de Sus", simplu: "Sambata de Sus" },
  { nume: "Sânpetru", simplu: "Sanpetru" },
  { nume: "Săsciori", simplu: "Sasciori", comuna: "Recea" },
  { nume: "Satu Nou", comuna: "Halchiu" },
  { nume: "Săvăstreni", simplu: "Savastreni", comuna: "Recea" },
  { nume: "Sebeș", simplu: "Sebes", comuna: "Harseni" },
  { nume: "Seliștat", simplu: "Selistat", comuna: "Soars" },
  { nume: "Șercaia", simplu: "Sercaia" },
  { nume: "Șercăița", simplu: "Sercaita", comuna: "Sinca" },
  { nume: "Șimon", simplu: "Simon", comuna: "Bran" },
  { nume: "Șinca Nouă", simplu: "Sinca Noua" },
  { nume: "Șinca Veche", simplu: "Sinca Veche", comuna: "Sinca" },
  { nume: "Șirnea", simplu: "Sirnea", comuna: "Fundata" },
  { nume: "Șoarș", simplu: "Soars" },
  { nume: "Sohodol", comuna: "Bran" },
  { nume: "Șona", simplu: "Sona", comuna: "Mandra" },
  {
    nume: "Stațiunea Climaterică Sâmbăta",
    simplu: "Statiunea Climaterica Sambata",
    comuna: "Sambata De Sus",
  },
  { nume: "Stupinii Prejmerului", comuna: "Prejmer" },
  { nume: "Tărlungeni", simplu: "Tarlungeni" },
  { nume: "Teliu" },
  { nume: "Ticușu Nou", simplu: "Ticusu Nou", comuna: "Comana" },
  { nume: "Ticușu Vechi", simplu: "Ticusu Vechi", comuna: "Ticusu" },
  { nume: "Timișu de Jos", simplu: "Timisu de Jos", comuna: "Predeal" },
  { nume: "Timișu de Sus", simplu: "Timisu de Sus", comuna: "Predeal" },
  { nume: "Toarcla", comuna: "Cincu" },
  { nume: "Toderița", simplu: "Toderita", comuna: "Mandra" },
  { nume: "Tohanu Nou", comuna: "Zarnesti" },
  { nume: "Ucea de Jos", comuna: "Ucea" },
  { nume: "Ucea de Sus", comuna: "Ucea" },
  { nume: "Ungra" },
  { nume: "Vad", comuna: "Sercaia" },
  { nume: "Vâlcea", simplu: "Valcea", comuna: "Sinca" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Jibert" },
  { nume: "Vama Buzăului", simplu: "Vama Buzaului" },
  { nume: "Veneția de Jos", simplu: "Venetia de Jos", comuna: "Parau" },
  { nume: "Veneția de Sus", simplu: "Venetia de Sus", comuna: "Parau" },
  { nume: "Victoria" },
  { nume: "Viscri", comuna: "Bunesti" },
  { nume: "Viștea de Jos", simplu: "Vistea de Jos", comuna: "Vistea" },
  { nume: "Viștea de Sus", simplu: "Vistea de Sus", comuna: "Vistea" },
  { nume: "Viștișoara", simplu: "Vistisoara", comuna: "Vistea" },
  { nume: "Vlădeni", simplu: "Vladeni", comuna: "Dumbravita" },
  { nume: "Voila" },
  { nume: "Voivodeni", comuna: "Voila" },
  { nume: "Vulcan" },
  { nume: "Zărnești", simplu: "Zarnesti" },
  { nume: "Zizin", comuna: "Tarlungeni" },
];
