export const br = [
  { nume: "Agaua", comuna: "Frecatei" },
  { nume: "Albina", comuna: "Tichilesti" },
  { nume: "Ariciu", comuna: "Salcia Tudor" },
  { nume: "Baldovineşti", simplu: "Baldovinesti", comuna: "Vadeni" },
  { nume: "Băndoiu", simplu: "Bandoiu", comuna: "Marasu" },
  { nume: "Bărăganul", simplu: "Baraganul" },
  { nume: "Batogu", comuna: "Ciresu" },
  { nume: "Berleşti", simplu: "Berlesti", comuna: "Ianca" },
  { nume: "Berteştii de Jos", simplu: "Bertestii de Jos" },
  {
    nume: "Berteştii de Sus",
    simplu: "Bertestii de Sus",
    comuna: "Bertestii De Jos",
  },
  { nume: "Boarca", comuna: "Ramnicelu" },
  { nume: "Bordei Verde" },
  { nume: "Brădeanca", simplu: "Bradeanca", comuna: "Jirlau" },
  { nume: "Brăila", simplu: "Braila" },
  { nume: "Brateşu Vechi", simplu: "Bratesu Vechi", comuna: "Surdila-Greci" },
  { nume: "Bumbăcari", simplu: "Bumbacari", comuna: "Dudesti" },
  { nume: "Câineni-Băi", simplu: "Caineni-Bai", comuna: "Visani" },
  { nume: "Căldăruşa", simplu: "Caldarusa", comuna: "Traian" },
  { nume: "Cazasu" },
  { nume: "Chichineţu", simplu: "Chichinetu", comuna: "Ciocile" },
  { nume: "Chioibaşeşti", simplu: "Chioibasesti", comuna: "Ciocile" },
  { nume: "Chişcani", simplu: "Chiscani" },
  { nume: "Ciocile" },
  { nume: "Cireşu", simplu: "Ciresu" },
  { nume: "Cistia", comuna: "Frecatei" },
  { nume: "Colţea", simplu: "Coltea", comuna: "Rosiori" },
  { nume: "Comăneasca", simplu: "Comaneasca", comuna: "Tudor Vladimirescu" },
  { nume: "Constantin Gabrielescu", comuna: "Bordei Verde" },
  { nume: "Constantineşti", simplu: "Constantinesti", comuna: "Ramnicelu" },
  { nume: "Corbeni", comuna: "Racovita" },
  { nume: "Corbu Nou", comuna: "Maxineni" },
  { nume: "Corbu Vechi", comuna: "Maxineni" },
  { nume: "Cotu Lung", comuna: "Silistea" },
  { nume: "Cotu Mihalea", comuna: "Silistea" },
  { nume: "Custura", comuna: "Racovita" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Salcia Tudor" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Stancuta" },
  { nume: "Deduleşti", simplu: "Dedulesti", comuna: "Mircea Voda" },
  { nume: "Deşiraţi", simplu: "Desirati", comuna: "Scortaru Nou" },
  { nume: "Drogu", comuna: "Galbenu" },
  { nume: "Dudescu", comuna: "Zavoaia" },
  { nume: "Dudeşti", simplu: "Dudesti" },
  { nume: "Esna", comuna: "Movila Miresii" },
  { nume: "Făurei Sat", simplu: "Faurei Sat", comuna: "Surdila-Greci" },
  { nume: "Făurei", simplu: "Faurei" },
  { nume: "Filipeşti", simplu: "Filipesti", comuna: "Surdila-Gaiseanca" },
  { nume: "Filiu", comuna: "Bordei Verde" },
  { nume: "Florica", comuna: "Rosiori" },
  { nume: "Frecăţei", simplu: "Frecatei" },
  { nume: "Galbenu" },
  { nume: "Gara Ianca", comuna: "Ianca" },
  { nume: "Găvani", simplu: "Gavani", comuna: "Gemenele" },
  { nume: "Gemenele" },
  { nume: "Gradiştea", simplu: "Gradistea" },
  { nume: "Gropeni" },
  { nume: "Gulianca", comuna: "Salcia Tudor" },
  {
    nume: "Gura Călmăţui",
    simplu: "Gura Calmatui",
    comuna: "Bertestii De Jos",
  },
  {
    nume: "Gura Gârluţei",
    simplu: "Gura Garlutei",
    comuna: "Bertestii De Jos",
  },
  { nume: "Gurguieţi", simplu: "Gurguieti", comuna: "Scortaru Nou" },
  { nume: "Horia", comuna: "Surdila-Greci" },
  { nume: "Ianca" },
  { nume: "Ibrianu", comuna: "Gradistea" },
  { nume: "Însurăţei", simplu: "Insuratei" },
  { nume: "Ioneşti", simplu: "Ionesti", comuna: "Ciresu" },
  { nume: "Jirlău", simplu: "Jirlau" },
  { nume: "Jugureanu", comuna: "Ulmu" },
  { nume: "Lacu Rezii", comuna: "Insuratei" },
  { nume: "Lacu Sărat", simplu: "Lacu Sarat", comuna: "Chiscani" },
  { nume: "Lanurile", comuna: "Viziru" },
  { nume: "Latinu", comuna: "Maxineni" },
  { nume: "Lişcoteanca", simplu: "Liscoteanca", comuna: "Bordei Verde" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Marasu" },
  { nume: "Maraloiu", comuna: "Gradistea" },
  { nume: "Măraşu", simplu: "Marasu" },
  { nume: "Mărtăceşti", simplu: "Martacesti", comuna: "Silistea" },
  { nume: "Măru Roşu", simplu: "Maru Rosu", comuna: "Insuratei" },
  { nume: "Măxineni", simplu: "Maxineni" },
  { nume: "Mihai Bravu", comuna: "Victoria" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Ramnicelu",
  },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Sutesti",
  },
  { nume: "Mircea Vodă", simplu: "Mircea Voda" },
  { nume: "Moroteşti", simplu: "Morotesti", comuna: "Unirea" },
  { nume: "Movila Miresii" },
  { nume: "Muchea", comuna: "Silistea" },
  { nume: "Nedeicu", comuna: "Marasu" },
  {
    nume: "Nicolae Bălcescu",
    simplu: "Nicolae Balcescu",
    comuna: "Scortaru Nou",
  },
  { nume: "Nicoleşti", simplu: "Nicolesti", comuna: "Bertestii De Jos" },
  { nume: "Oancea", comuna: "Romanu" },
  { nume: "Odăieni", simplu: "Odaieni", comuna: "Ciocile" },
  { nume: "Olăneasca", simplu: "Olaneasca", comuna: "Salcia Tudor" },
  { nume: "Oprişeneşti", simplu: "Oprisenesti", comuna: "Ianca" },
  { nume: "Pântecani", simplu: "Pantecani", comuna: "Galbenu" },
  { nume: "Perişoru", simplu: "Perisoru", comuna: "Ianca" },
  { nume: "Pietroiu", comuna: "Vadeni" },
  { nume: "Pitulaţi", simplu: "Pitulati", comuna: "Scortaru Nou" },
  { nume: "Plăsoiu", simplu: "Plasoiu", comuna: "Visani" },
  { nume: "Plopi", comuna: "Marasu" },
  { nume: "Plopu", comuna: "Ianca" },
  { nume: "Polizeşti", simplu: "Polizesti", comuna: "Stancuta" },
  { nume: "Pribeagu", comuna: "Rosiori" },
  { nume: "Racoviţă", simplu: "Racovita" },
  { nume: "Râmnicelu", simplu: "Ramnicelu" },
  { nume: "Romanu" },
  { nume: "Roşiori", simplu: "Rosiori" },
  { nume: "Salcia Tudor" },
  { nume: "Salcia", comuna: "Frecatei" },
  { nume: "Sătuc", simplu: "Satuc", comuna: "Galbenu" },
  { nume: "Scărlăteşti", simplu: "Scarlatesti", comuna: "Ciresu" },
  { nume: "Scorţaru Nou", simplu: "Scortaru Nou" },
  {
    nume: "Scorţaru Vechi",
    simplu: "Scortaru Vechi",
    comuna: "Tudor Vladimirescu",
  },
  { nume: "Sihleanu", comuna: "Scortaru Nou" },
  { nume: "Siliştea", simplu: "Silistea" },
  { nume: "Silistraru", comuna: "Traian" },
  { nume: "Spiru Haret", comuna: "Bertestii De Jos" },
  { nume: "Stanca", comuna: "Stancuta" },
  { nume: "Stăncuţa", simplu: "Stancuta" },
  { nume: "Stoieneşti", simplu: "Stoienesti", comuna: "Frecatei" },
  { nume: "Surdila-Găiseanca", simplu: "Surdila-Gaiseanca" },
  { nume: "Surdila-Greci" },
  { nume: "Şuţeşti", simplu: "Sutesti" },
  { nume: "Ţăcău", simplu: "Tacau", comuna: "Marasu" },
  { nume: "Târlele Filiu", simplu: "Tarlele Filiu", comuna: "Ianca" },
  { nume: "Tătaru", simplu: "Tataru", comuna: "Dudesti" },
  { nume: "Ţepeş Vodă", simplu: "Tepes Voda", comuna: "Movila Miresii" },
  { nume: "Tichileşti", simplu: "Tichilesti" },
  { nume: "Titcov", comuna: "Frecatei" },
  { nume: "Traian" },
  { nume: "Tudor Vladimirescu" },
  { nume: "Tufeşti", simplu: "Tufesti" },
  { nume: "Ulmu" },
  { nume: "Unirea" },
  { nume: "Urleasca", comuna: "Traian" },
  { nume: "Vădeni", simplu: "Vadeni" },
  {
    nume: "Valea Călmăţuiului",
    simplu: "Valea Calmatuiului",
    comuna: "Insuratei",
  },
  { nume: "Valea Cânepii", simplu: "Valea Canepii", comuna: "Unirea" },
  { nume: "Vameşu", simplu: "Vamesu", comuna: "Silistea" },
  { nume: "Vărsătura", simplu: "Varsatura", comuna: "Chiscani" },
  { nume: "Victoria" },
  { nume: "Vişani", simplu: "Visani" },
  { nume: "Viziru" },
  { nume: "Voineşti", simplu: "Voinesti", comuna: "Maxineni" },
  { nume: "Vultureni", comuna: "Ciresu" },
  { nume: "Zamfireşti", simplu: "Zamfiresti", comuna: "Galbenu" },
  { nume: "Zăvoaia", simplu: "Zavoaia" },
];
