export const bn = [
  { nume: "Agrieş", simplu: "Agries", comuna: "Tarlisua" },
  { nume: "Agrieşel", simplu: "Agriesel", comuna: "Tarlisua" },
  { nume: "Agrişu de Jos", simplu: "Agrisu de Jos", comuna: "Sieu-Odorhei" },
  { nume: "Agrişu de Sus", simplu: "Agrisu de Sus", comuna: "Sieu-Odorhei" },
  {
    nume: "Albeştii Bistriţei",
    simplu: "Albestii Bistritei",
    comuna: "Galatii Bistritei",
  },
  { nume: "Alunişul", simplu: "Alunisul", comuna: "Zagra" },
  { nume: "Anieş", simplu: "Anies", comuna: "Maieru" },
  { nume: "Apatiu", comuna: "Chiochis" },
  { nume: "Arcalia", comuna: "Sieu-Magherus" },
  { nume: "Archiud", comuna: "Teaca" },
  { nume: "Ardan", comuna: "Sieu" },
  { nume: "Arşiţa", simplu: "Arsita", comuna: "Magura Ilvei" },
  { nume: "Bârla", simplu: "Barla", comuna: "Mariselu" },
  { nume: "Baţa", simplu: "Bata", comuna: "Petru Rares" },
  { nume: "Beclean" },
  { nume: "Beudiu", comuna: "Nuseni" },
  { nume: "Bichigiu", comuna: "Cosbuc" },
  { nume: "Bidiu", comuna: "Matei" },
  { nume: "Bistriţa Bârgăului", simplu: "Bistrita Bargaului" },
  { nume: "Bistriţa", simplu: "Bistrita" },
  { nume: "Blăjenii de Jos", simplu: "Blajenii de Jos", comuna: "Sintereag" },
  { nume: "Blăjenii de Sus", simplu: "Blajenii de Sus", comuna: "Sintereag" },
  { nume: "Borleasa", comuna: "Tarlisua" },
  { nume: "Bozieş", simplu: "Bozies", comuna: "Chiochis" },
  { nume: "Braniştea", simplu: "Branistea" },
  { nume: "Brăteni", simplu: "Brateni", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Breaza", comuna: "Negrilesti" },
  { nume: "Bretea", comuna: "Sieu-Odorhei" },
  { nume: "Budacu de Jos" },
  { nume: "Budacu de Sus", comuna: "Dumitrita" },
  { nume: "Budeşti-Fânaţe", simplu: "Budesti-Fanate", comuna: "Budesti" },
  { nume: "Budeşti", simplu: "Budesti" },
  { nume: "Budurleni", comuna: "Teaca" },
  { nume: "Buduş", simplu: "Budus", comuna: "Budacu De Jos" },
  { nume: "Bungard", comuna: "Lechinta" },
  { nume: "Buza Cătun", simplu: "Buza Catun", comuna: "Chiochis" },
  { nume: "Căianu Mare", simplu: "Caianu Mare", comuna: "Caianu Mic" },
  { nume: "Căianu Mic", simplu: "Caianu Mic" },
  { nume: "Caila", comuna: "Sintereag" },
  { nume: "Câmp", simplu: "Camp", comuna: "Urmenis" },
  { nume: "Cepari", comuna: "Dumitra" },
  { nume: "Cheţiu", simplu: "Chetiu", comuna: "Chiochis" },
  { nume: "Chintelnic", comuna: "Sieu-Magherus" },
  { nume: "Chiochiş", simplu: "Chiochis" },
  { nume: "Chiraleş", simplu: "Chirales", comuna: "Lechinta" },
  { nume: "Chiuza" },
  { nume: "Ciceu-Corabia", comuna: "Petru Rares" },
  { nume: "Ciceu-Giurgeşti", simplu: "Ciceu-Giurgesti" },
  { nume: "Ciceu-Mihăieşti", simplu: "Ciceu-Mihaiesti", comuna: "Petru Rares" },
  { nume: "Ciceu-Poieni", comuna: "Caianu Mic" },
  { nume: "Ciosa", comuna: "Tiha Bargaului" },
  { nume: "Cireaşi", simplu: "Cireasi", comuna: "Tarlisua" },
  { nume: "Cireşoaia", simplu: "Ciresoaia", comuna: "Branistea" },
  { nume: "Coasta", comuna: "Sieu-Odorhei" },
  { nume: "Cociu", comuna: "Sintereag" },
  { nume: "Coldău", simplu: "Coldau", comuna: "Beclean" },
  { nume: "Colibiţa", simplu: "Colibita", comuna: "Bistrita Bargaului" },
  { nume: "Comlod", comuna: "Milas" },
  { nume: "Cormaia", comuna: "Sangeorz-Bai" },
  { nume: "Corvineşti", simplu: "Corvinesti", comuna: "Matei" },
  { nume: "Coşbuc", simplu: "Cosbuc" },
  { nume: "Coşeriu", simplu: "Coseriu", comuna: "Urmenis" },
  { nume: "Crainimăt", simplu: "Crainimat", comuna: "Sieu-Magherus" },
  {
    nume: "Cristeştii Ciceului",
    simplu: "Cristestii Ciceului",
    comuna: "Uriu",
  },
  { nume: "Cristur-Şieu", simplu: "Cristur-Sieu", comuna: "Sieu-Odorhei" },
  { nume: "Cuşma", simplu: "Cusma", comuna: "Livezile" },
  { nume: "Dealu Ştefăniţei", simplu: "Dealu Stefanitei", comuna: "Romuli" },
  { nume: "Delureni", comuna: "Urmenis" },
  { nume: "Dipşa", simplu: "Dipsa", comuna: "Galatii Bistritei" },
  { nume: "Dobric", comuna: "Caianu Mic" },
  { nume: "Dobricel", comuna: "Caianu Mic" },
  { nume: "Domneşti", simplu: "Domnesti", comuna: "Mariselu" },
  { nume: "Dorolea", comuna: "Livezile" },
  { nume: "Draga", comuna: "Silivasu De Cimpie" },
  { nume: "Dumbrava", comuna: "Livezile" },
  { nume: "Dumbrava", comuna: "Nuseni" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Ciceu-Giurgesti" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita", comuna: "Caianu Mic" },
  { nume: "Dumitra" },
  { nume: "Dumitriţa", simplu: "Dumitrita" },
  { nume: "Dupa Deal", comuna: "Milas" },
  { nume: "Enciu", comuna: "Matei" },
  { nume: "Fânaţe", simplu: "Fanate", comuna: "Urmenis" },
  {
    nume: "Fânaţele Silivaşului",
    simplu: "Fanatele Silivasului",
    comuna: "Silivasu De Cimpie",
  },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Matei" },
  { nume: "Fântâniţa", simplu: "Fantanita", comuna: "Micestii De Campie" },
  { nume: "Feldru" },
  { nume: "Feleac", comuna: "Nuseni" },
  { nume: "Fiad", comuna: "Telciu" },
  { nume: "Figa", comuna: "Beclean" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Nimigea" },
  { nume: "Galaţii Bistriţei", simplu: "Galatii Bistritei" },
  { nume: "Gersa I", comuna: "Rebrisoara" },
  { nume: "Gersa Ii", comuna: "Rebrisoara" },
  { nume: "Ghemeş", simplu: "Ghemes", comuna: "Milas" },
  { nume: "Ghinda", comuna: "Bistrita" },
  { nume: "Gledin", comuna: "Monor" },
  { nume: "Hălmăsău", simplu: "Halmasau", comuna: "Spermezeu" },
  { nume: "Hăşmaşu Ciceului", simplu: "Hasmasu Ciceului", comuna: "Uriu" },
  { nume: "Herina", comuna: "Galatii Bistritei" },
  { nume: "Hirean", comuna: "Milas" },
  { nume: "Ilişua", simplu: "Ilisua", comuna: "Uriu" },
  { nume: "Ilva Mare" },
  { nume: "Ilva Mica" },
  { nume: "Ivăneasa", simplu: "Ivaneasa", comuna: "Ilva Mare" },
  { nume: "Jeica", comuna: "Mariselu" },
  { nume: "Jelna", comuna: "Budacu De Jos" },
  { nume: "Jimbor", comuna: "Chiochis" },
  { nume: "Josenii Bârgăului", simplu: "Josenii Bargaului" },
  { nume: "La Curte", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Lechinţa", simplu: "Lechinta" },
  { nume: "Leleşti", simplu: "Lelesti", comuna: "Petru Rares" },
  { nume: "Leşu", simplu: "Lesu" },
  { nume: "Livezile" },
  { nume: "Liviu Rebreanu", comuna: "Nasaud" },
  { nume: "Lunca Borlesei", comuna: "Spermezeu" },
  { nume: "Lunca Ilvei" },
  { nume: "Lunca Leşului", simplu: "Lunca Lesului", comuna: "Lesu" },
  { nume: "Lunca Săteasca", simplu: "Lunca Sateasca", comuna: "Tarlisua" },
  { nume: "Lunca", comuna: "Sieut" },
  { nume: "Luşca", simplu: "Lusca", comuna: "Nasaud" },
  { nume: "Măgura Ilvei", simplu: "Magura Ilvei" },
  { nume: "Măgurele", simplu: "Magurele", comuna: "Mariselu" },
  { nume: "Maieru" },
  { nume: "Malin", comuna: "Nuseni" },
  { nume: "Măluţ", simplu: "Malut", comuna: "Branistea" },
  { nume: "Manic", comuna: "Chiochis" },
  { nume: "Mărişelu", simplu: "Mariselu" },
  { nume: "Matei" },
  { nume: "Miceştii de Câmpie", simplu: "Micestii de Campie" },
  {
    nume: "Mijlocenii Bârgăului",
    simplu: "Mijlocenii Bargaului",
    comuna: "Josenii Bargaului",
  },
  { nume: "Milaş", simplu: "Milas" },
  { nume: "Mintiu", comuna: "Nimigea" },
  { nume: "Mireş", simplu: "Mires", comuna: "Chiuza" },
  { nume: "Mititei", comuna: "Nimigea" },
  { nume: "Mocod", comuna: "Nimigea" },
  { nume: "Mogoşeni", simplu: "Mogoseni", comuna: "Nimigea" },
  { nume: "Molişet", simplu: "Moliset", comuna: "Tarlisua" },
  { nume: "Monariu", comuna: "Budacu De Jos" },
  { nume: "Monor" },
  { nume: "Moruţ", simplu: "Morut", comuna: "Matei" },
  {
    nume: "Mureşenii Bârgăului",
    simplu: "Muresenii Bargaului",
    comuna: "Tiha Bargaului",
  },
  { nume: "Năsăud", simplu: "Nasaud" },
  { nume: "Negrileşti", simplu: "Negrilesti" },
  { nume: "Nepos", comuna: "Feldru" },
  { nume: "Neţeni", simplu: "Neteni", comuna: "Mariselu" },
  { nume: "Nimigea de Jos", comuna: "Nimigea" },
  { nume: "Nimigea de Sus", comuna: "Nimigea" },
  { nume: "Nuşeni", simplu: "Nuseni" },
  { nume: "Oarzina", comuna: "Tarlisua" },
  { nume: "Ocniţa", simplu: "Ocnita", comuna: "Teaca" },
  { nume: "Orheiu Bistriţei", simplu: "Orheiu Bistritei", comuna: "Cetate" },
  { nume: "Orosfaia", comuna: "Milas" },
  { nume: "Păltineasa", simplu: "Paltineasa", comuna: "Spermezeu" },
  { nume: "Parva" },
  { nume: "Perişor", simplu: "Perisor", comuna: "Zagra" },
  { nume: "Petriş", simplu: "Petris", comuna: "Cetate" },
  {
    nume: "Piatra Fântânele",
    simplu: "Piatra Fantanele",
    comuna: "Tiha Bargaului",
  },
  { nume: "Piatra", comuna: "Chiuza" },
  { nume: "Pinticu", comuna: "Teaca" },
  { nume: "Podenii", comuna: "Urmenis" },
  { nume: "Poderei", comuna: "Rebrisoara" },
  { nume: "Podirei", comuna: "Sieu-Magherus" },
  { nume: "Poiana Ilvei" },
  { nume: "Poienile Zagrei", comuna: "Zagra" },
  { nume: "Porumbenii", comuna: "Silivasu De Cimpie" },
  { nume: "Posmuş", simplu: "Posmus", comuna: "Sieu" },
  { nume: "Prundu Bârgăului", simplu: "Prundu Bargaului" },
  { nume: "Purcărete", simplu: "Purcarete", comuna: "Negrilesti" },
  { nume: "Răcăteşu", simplu: "Racatesu", comuna: "Tarlisua" },
  { nume: "Ragla", comuna: "Dumitrita" },
  { nume: "Rebra" },
  { nume: "Rebrişoara", simplu: "Rebrisoara" },
  { nume: "Reteag", comuna: "Petru Rares" },
  { nume: "Rodna" },
  { nume: "Romuli" },
  { nume: "Runcu Salvei", comuna: "Salva" },
  { nume: "Ruştior", simplu: "Rustior", comuna: "Sieut" },
  {
    nume: "Rusu Bârgăului",
    simplu: "Rusu Bargaului",
    comuna: "Josenii Bargaului",
  },
  { nume: "Rusu de Jos", comuna: "Beclean" },
  { nume: "Rusu de Sus", comuna: "Nuseni" },
  { nume: "Sălcuţa", simplu: "Salcuta", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Salva" },
  { nume: "Sângeorz-Băi", simplu: "Sangeorz-Bai" },
  { nume: "Sângeorzu Nou", simplu: "Sangeorzu Nou", comuna: "Lechinta" },
  { nume: "Sâniacob", simplu: "Saniacob", comuna: "Lechinta" },
  {
    nume: "Sânmihaiu de Câmpie",
    simplu: "Sanmihaiu de Campie",
    comuna: "Sanmihaiu De Cimpie",
  },
  { nume: "Sânnicoară", simplu: "Sannicoara", comuna: "Chiochis" },
  { nume: "Şanţ", simplu: "Sant" },
  { nume: "Sântioana", simplu: "Santioana", comuna: "Mariselu" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Bistrita" },
  { nume: "Sărăţel", simplu: "Saratel", comuna: "Sieu-Magherus" },
  { nume: "Săsarm", simplu: "Sasarm", comuna: "Chiuza" },
  { nume: "Satu Nou", comuna: "Cetate" },
  { nume: "Scoabe", comuna: "Urmenis" },
  { nume: "Sebiş", simplu: "Sebis", comuna: "Sieut" },
  { nume: "Şendroaia", simplu: "Sendroaia", comuna: "Tarlisua" },
  {
    nume: "Şeşuri Spermezeu-Vale",
    simplu: "Sesuri Spermezeu-Vale",
    comuna: "Spermezeu",
  },
  { nume: "Şieu-Măgheruş", simplu: "Sieu-Magherus" },
  { nume: "Şieu-Odorhei", simplu: "Sieu-Odorhei" },
  { nume: "Şieu-Sfântu", simplu: "Sieu-Sfantu", comuna: "Sintereag" },
  { nume: "Şieu", simplu: "Sieu" },
  { nume: "Şieuţ", simplu: "Sieut" },
  { nume: "Sigmir", comuna: "Bistrita" },
  {
    nume: "Silivaşu de Câmpie",
    simplu: "Silivasu de Campie",
    comuna: "Silivasu De Cimpie",
  },
  { nume: "Simioneşti", simplu: "Simionesti", comuna: "Budacu De Jos" },
  { nume: "Şintereag-Gară", simplu: "Sintereag-Gara", comuna: "Sintereag" },
  { nume: "Şintereag", simplu: "Sintereag" },
  { nume: "Şirioara", simplu: "Sirioara", comuna: "Sieu-Odorhei" },
  { nume: "Sita", comuna: "Spermezeu" },
  { nume: "Slătiniţa", simplu: "Slatinita", comuna: "Bistrita" },
  { nume: "Şoimuş", simplu: "Soimus", comuna: "Sieu" },
  { nume: "Şopteriu", simplu: "Sopteriu", comuna: "Urmenis" },
  { nume: "Spermezeu" },
  { nume: "Strâmba", simplu: "Stramba", comuna: "Josenii Bargaului" },
  { nume: "Strugureni", comuna: "Chiochis" },
  { nume: "Stupini", comuna: "Sanmihaiu De Cimpie" },
  { nume: "Suplai", comuna: "Zagra" },
  {
    nume: "Susenii Bârgăului",
    simplu: "Susenii Bargaului",
    comuna: "Prundu Bargaului",
  },
  { nume: "Ţăgşoru", simplu: "Tagsoru", comuna: "Budesti" },
  { nume: "Ţagu", simplu: "Tagu", comuna: "Budesti" },
  { nume: "Târlişua", simplu: "Tarlisua" },
  { nume: "Tărpiu", simplu: "Tarpiu", comuna: "Dumitra" },
  { nume: "Tăure", simplu: "Taure", comuna: "Nimigea" },
  { nume: "Teaca" },
  { nume: "Telcişor", simplu: "Telcisor", comuna: "Telciu" },
  { nume: "Telciu" },
  { nume: "Ţentea", simplu: "Tentea", comuna: "Chiochis" },
  { nume: "Ţigău", simplu: "Tigau", comuna: "Lechinta" },
  { nume: "Tiha Bârgăului", simplu: "Tiha Bargaului" },
  { nume: "Tonciu", comuna: "Galatii Bistritei" },
  { nume: "Tureac", comuna: "Tiha Bargaului" },
  { nume: "Unirea", comuna: "Bistrita" },
  { nume: "Uriu" },
  { nume: "Urmeniş", simplu: "Urmenis" },
  { nume: "Valea Borcutului", comuna: "Sangeorz-Bai" },
  {
    nume: "Valea Măgheruşului",
    simplu: "Valea Magherusului",
    comuna: "Sieu-Magherus",
  },
  { nume: "Valea Mare", comuna: "Sant" },
  { nume: "Valea Mare", comuna: "Urmenis" },
  { nume: "Valea Poenii", comuna: "Livezile" },
  { nume: "Valea Vinului", comuna: "Rodna" },
  { nume: "Valea", comuna: "Urmenis" },
  { nume: "Vermeş", simplu: "Vermes", comuna: "Lechinta" },
  { nume: "Viile Tecii", comuna: "Teaca" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Bistrita" },
  { nume: "Visuia", comuna: "Micestii De Campie" },
  { nume: "Viţa", simplu: "Vita", comuna: "Nuseni" },
  { nume: "Zagra" },
  { nume: "Zoreni", comuna: "Sanmihaiu De Cimpie" },
];
