export const bz = [
  { nume: "Amaru" },
  { nume: "Balta Alba" },
  { nume: "Beceni" },
  { nume: "Berca" },
  { nume: "Bisoca" },
  { nume: "Blajani" },
  { nume: "Boldu" },
  { nume: "Bozioru" },
  { nume: "Breaza" },
  { nume: "Bradeanu" },
  { nume: "Braesti" },
  { nume: "Buda" },
  { nume: "Buzau" },
  { nume: "Balaceanu" },
  { nume: "C.a. Rosetti" },
  { nume: "Calvini" },
  { nume: "Cernatesti" },
  { nume: "Chiliile" },
  { nume: "Chiojdu" },
  { nume: "Cilibia" },
  { nume: "Cislau" },
  { nume: "Cochirleanca" },
  { nume: "Colti" },
  { nume: "Costesti" },
  { nume: "Cozieni" },
  { nume: "Canesti" },
  { nume: "Catina" },
  { nume: "Ghergheasa" },
  { nume: "Gheraseni" },
  { nume: "Glodeanu Sarat" },
  { nume: "Glodeanu-Silistea" },
  { nume: "Grebanu" },
  { nume: "Gura Teghii" },
  { nume: "Galbinasi" },
  { nume: "Largu" },
  { nume: "Lopatari" },
  { nume: "Luciu" },
  { nume: "Merei" },
  { nume: "Mihailesti" },
  { nume: "Movila Banului" },
  { nume: "Murgesti" },
  { nume: "Manzalesti" },
  { nume: "Magura" },
  { nume: "Margaritesti" },
  { nume: "Maracineni" },
  { nume: "Nehoiu" },
  { nume: "Naeni" },
  { nume: "Odaile" },
  { nume: "Padina" },
  { nume: "Pardosi" },
  { nume: "Pietroasele" },
  { nume: "Podgoria" },
  { nume: "Pogoanele" },
  { nume: "Posta Calnau" },
  { nume: "Parscov" },
  { nume: "Panatau" },
  { nume: "Patarlagele" },
  { nume: "Racoviteni" },
  { nume: "Robeasca" },
  { nume: "Rusetu" },
  { nume: "Ramnicelu" },
  { nume: "Ramnicu Sarat" },
  { nume: "Scortoasa" },
  { nume: "Scutelnici" },
  { nume: "Smeeni" },
  { nume: "Stalpu" },
  { nume: "Sageata" },
  { nume: "Sahateni" },
  { nume: "Sapoca" },
  { nume: "Sarulesti" },
  { nume: "Tisau" },
  { nume: "Topliceni" },
  { nume: "Ulmeni" },
  { nume: "Vadu Pasii" },
  { nume: "Valea Ramnicului" },
  { nume: "Valea Salciei" },
  { nume: "Vernesti" },
  { nume: "Vintila Voda" },
  { nume: "Viperesti" },
  { nume: "Valcelele" },
  { nume: "Ziduri" },
  { nume: "Zarnesti" },
  { nume: "Tintesti" },
  { nume: "Campeni", comuna: "Amaru" },
  { nume: "Dulbanu", comuna: "Amaru" },
  { nume: "Lacu Sinaia", comuna: "Amaru" },
  { nume: "Lunca", comuna: "Amaru" },
  { nume: "Scorteanca", comuna: "Amaru" },
  { nume: "Amara", comuna: "Balta Alba" },
  { nume: "Baile", comuna: "Balta Alba" },
  { nume: "Stavarasti", comuna: "Balta Alba" },
  { nume: "Arbanasi", comuna: "Beceni" },
  { nume: "Carpinistea", comuna: "Beceni" },
  { nume: "Dogari", comuna: "Beceni" },
  { nume: "Floresti", comuna: "Beceni" },
  { nume: "Gura Dimienii", comuna: "Beceni" },
  { nume: "Izvoru Dulce", comuna: "Beceni" },
  { nume: "Margariti", comuna: "Beceni" },
  { nume: "Valea Parului", comuna: "Beceni" },
  { nume: "Baceni", comuna: "Berca" },
  { nume: "Cojanu", comuna: "Berca" },
  { nume: "Joseni", comuna: "Berca" },
  { nume: "Manastirea Ratesti", comuna: "Berca" },
  { nume: "Plescoi", comuna: "Berca" },
  { nume: "Plesesti", comuna: "Berca" },
  { nume: "Paclele", comuna: "Berca" },
  { nume: "Ratesti", comuna: "Berca" },
  { nume: "Satuc", comuna: "Berca" },
  { nume: "Tatarligu", comuna: "Berca" },
  { nume: "Valea Nucului", comuna: "Berca" },
  { nume: "Viforata", comuna: "Berca" },
  { nume: "Baltagari", comuna: "Bisoca" },
  { nume: "Lacurile", comuna: "Bisoca" },
  { nume: "Lopatareasa", comuna: "Bisoca" },
  { nume: "Plesi", comuna: "Bisoca" },
  { nume: "Recea", comuna: "Bisoca" },
  { nume: "Sarile", comuna: "Bisoca" },
  { nume: "Sindrila", comuna: "Bisoca" },
  { nume: "Soresti", comuna: "Blajani" },
  { nume: "Buduile", comuna: "Bozioru" },
  { nume: "Fisici", comuna: "Bozioru" },
  { nume: "Gresia", comuna: "Bozioru" },
  { nume: "Gavanele", comuna: "Bozioru" },
  { nume: "Izvoarele", comuna: "Bozioru" },
  { nume: "Nucu", comuna: "Bozioru" },
  { nume: "Scaeni", comuna: "Bozioru" },
  { nume: "Ulmet", comuna: "Bozioru" },
  { nume: "Vavalucile", comuna: "Bozioru" },
  { nume: "Mitropolia", comuna: "Bradeanu" },
  { nume: "Smardan", comuna: "Bradeanu" },
  { nume: "Bratilesti", comuna: "Braesti" },
  { nume: "Goidesti", comuna: "Braesti" },
  { nume: "Ivanetu", comuna: "Braesti" },
  { nume: "Pinu", comuna: "Braesti" },
  { nume: "Parscovelu", comuna: "Braesti" },
  { nume: "Ruginoasa", comuna: "Braesti" },
  { nume: "Badeni", comuna: "Breaza" },
  { nume: "Greceanca", comuna: "Breaza" },
  { nume: "Vispesti", comuna: "Breaza" },
  { nume: "Valeanca-Vilanesti", comuna: "Breaza" },
  { nume: "Alexandru Odobescu", comuna: "Buda" },
  { nume: "Danulesti", comuna: "Buda" },
  { nume: "Mucesti-Danulesti", comuna: "Buda" },
  { nume: "Spidele", comuna: "Buda" },
  { nume: "Toropalesti", comuna: "Buda" },
  { nume: "Valea Larga", comuna: "Buda" },
  { nume: "Balhacu", comuna: "C.A. Rosetti" },
  { nume: "Balteni", comuna: "C.A. Rosetti" },
  { nume: "Cotu Ciorii", comuna: "C.A. Rosetti" },
  { nume: "Lunca", comuna: "C.A. Rosetti" },
  { nume: "Vizireni", comuna: "C.A. Rosetti" },
  { nume: "Bascenii de Jos", comuna: "Calvini" },
  { nume: "Bascenii de Sus", comuna: "Calvini" },
  { nume: "Frasinet", comuna: "Calvini" },
  { nume: "Olari", comuna: "Calvini" },
  { nume: "Gontesti", comuna: "Canesti" },
  { nume: "Negosina", comuna: "Canesti" },
  { nume: "Pacurile", comuna: "Canesti" },
  { nume: "Valea Verzei", comuna: "Canesti" },
  { nume: "Suchea", comuna: "Canesti" },
  { nume: "Corbu", comuna: "Catina" },
  { nume: "Slobozia", comuna: "Catina" },
  { nume: "Valea Catinei", comuna: "Catina" },
  { nume: "Zeletin", comuna: "Catina" },
  { nume: "Aldeni", comuna: "Cernatesti" },
  { nume: "Baesti", comuna: "Cernatesti" },
  { nume: "Caldarusa", comuna: "Cernatesti" },
  { nume: "Fulga", comuna: "Cernatesti" },
  { nume: "Manasia", comuna: "Cernatesti" },
  { nume: "Vladeni", comuna: "Cernatesti" },
  { nume: "Zarnestii de Slanic", comuna: "Cernatesti" },
  { nume: "Budesti", comuna: "Chiliile" },
  { nume: "Crevelesti", comuna: "Chiliile" },
  { nume: "Ghiocari", comuna: "Chiliile" },
  { nume: "Glodu-Petcari", comuna: "Chiliile" },
  { nume: "Poiana Pletari", comuna: "Chiliile" },
  { nume: "Trestioara", comuna: "Chiliile" },
  { nume: "Basca Chiojdului", comuna: "Chiojdu" },
  { nume: "Catiasu", comuna: "Chiojdu" },
  { nume: "Lera", comuna: "Chiojdu" },
  { nume: "Plescioara", comuna: "Chiojdu" },
  { nume: "Poenitele", comuna: "Chiojdu" },
  { nume: "Gara Cilibia", comuna: "Cilibia" },
  { nume: "Movila Oii", comuna: "Cilibia" },
  { nume: "Manzu", comuna: "Cilibia" },
  { nume: "Posta", comuna: "Cilibia" },
  { nume: "Buda Craciunesti", comuna: "Cislau" },
  { nume: "Barasti", comuna: "Cislau" },
  { nume: "Gura Bascei", comuna: "Cislau" },
  { nume: "Scarisoara", comuna: "Cislau" },
  { nume: "Boboc", comuna: "Cochirleanca" },
  { nume: "Gara Bobocu", comuna: "Cochirleanca" },
  { nume: "Rosioru", comuna: "Cochirleanca" },
  { nume: "Tarlele", comuna: "Cochirleanca" },
  { nume: "Alunis", comuna: "Colti" },
  { nume: "Coltii de Jos", comuna: "Colti" },
  { nume: "Muscelu Caramanesti", comuna: "Colti" },
  { nume: "Budisteni", comuna: "Costesti" },
  { nume: "Gomoesti", comuna: "Costesti" },
  { nume: "Grosani", comuna: "Costesti" },
  { nume: "Pietrosu", comuna: "Costesti" },
  { nume: "Spataru", comuna: "Costesti" },
  { nume: "Anini", comuna: "Cozieni" },
  { nume: "Bercesti", comuna: "Cozieni" },
  { nume: "Balanesti", comuna: "Cozieni" },
  { nume: "Ciocanesti", comuna: "Cozieni" },
  { nume: "Cocarceni", comuna: "Cozieni" },
  { nume: "Colteni", comuna: "Cozieni" },
  { nume: "Fata lui Nan", comuna: "Cozieni" },
  { nume: "Glodurile", comuna: "Cozieni" },
  { nume: "Izvoru", comuna: "Cozieni" },
  { nume: "Lungesti", comuna: "Cozieni" },
  { nume: "Nistoresti", comuna: "Cozieni" },
  { nume: "Pietraru", comuna: "Cozieni" },
  { nume: "Punga", comuna: "Cozieni" },
  { nume: "Teisu", comuna: "Cozieni" },
  { nume: "Trestia", comuna: "Cozieni" },
  { nume: "Tulburea", comuna: "Cozieni" },
  { nume: "Valea Banului", comuna: "Cozieni" },
  { nume: "Valea Roatei", comuna: "Cozieni" },
  { nume: "Zapodia", comuna: "Cozieni" },
  { nume: "Bentu", comuna: "Galbinasi" },
  { nume: "Tabarasti", comuna: "Galbinasi" },
  { nume: "Suditi", comuna: "Gheraseni" },
  { nume: "Salcioara", comuna: "Ghergheasa" },
  { nume: "Caldaruseanca", comuna: "Glodeanu Sarat" },
  { nume: "Ileana", comuna: "Glodeanu Sarat" },
  { nume: "Pitulicea", comuna: "Glodeanu Sarat" },
  { nume: "Casota", comuna: "Glodeanu-Silistea" },
  { nume: "Corbu", comuna: "Glodeanu-Silistea" },
  { nume: "Cotorca", comuna: "Glodeanu-Silistea" },
  { nume: "Carligu Mare", comuna: "Glodeanu-Silistea" },
  { nume: "Carligu Mic", comuna: "Glodeanu-Silistea" },
  { nume: "Satu Nou", comuna: "Glodeanu-Silistea" },
  { nume: "Vacareasca", comuna: "Glodeanu-Silistea" },
  { nume: "Homesti", comuna: "Grebanu" },
  { nume: "Livada", comuna: "Grebanu" },
  { nume: "Livada Mica", comuna: "Grebanu" },
  { nume: "Plevna", comuna: "Grebanu" },
  { nume: "Zaplazi", comuna: "Grebanu" },
  { nume: "Furtunesti", comuna: "Gura Teghii" },
  { nume: "Nemertea", comuna: "Gura Teghii" },
  { nume: "Paltinis", comuna: "Gura Teghii" },
  { nume: "Secuiu", comuna: "Gura Teghii" },
  { nume: "Vadu Oii", comuna: "Gura Teghii" },
  { nume: "Varlaam", comuna: "Gura Teghii" },
  { nume: "Scarlatesti", comuna: "Largu" },
  { nume: "Brebu", comuna: "Lopatari" },
  { nume: "Fundata", comuna: "Lopatari" },
  { nume: "Luncile", comuna: "Lopatari" },
  { nume: "Pestritu", comuna: "Lopatari" },
  { nume: "Plaiu Nucului", comuna: "Lopatari" },
  { nume: "Plostina", comuna: "Lopatari" },
  { nume: "Potecu", comuna: "Lopatari" },
  { nume: "Sareni", comuna: "Lopatari" },
  { nume: "Terca", comuna: "Lopatari" },
  { nume: "Varteju", comuna: "Lopatari" },
  { nume: "Caragele", comuna: "Luciu" },
  { nume: "Ciuta", comuna: "Magura" },
  { nume: "Unguriu", comuna: "Magura" },
  { nume: "Beslii", comuna: "Manzalesti" },
  { nume: "Bustea", comuna: "Manzalesti" },
  { nume: "Ciresu", comuna: "Manzalesti" },
  { nume: "Ghizdita", comuna: "Manzalesti" },
  { nume: "Gura Badicului", comuna: "Manzalesti" },
  { nume: "Jghiab", comuna: "Manzalesti" },
  { nume: "Plavatu", comuna: "Manzalesti" },
  { nume: "Poiana Valcului", comuna: "Manzalesti" },
  { nume: "Satu Vechi", comuna: "Manzalesti" },
  { nume: "Trestioara", comuna: "Manzalesti" },
  { nume: "Valea Cotoarei", comuna: "Manzalesti" },
  { nume: "Valea Ursului", comuna: "Manzalesti" },
  { nume: "Capatanesti", comuna: "Maracineni" },
  { nume: "Potoceni", comuna: "Maracineni" },
  { nume: "Campulungeanca", comuna: "Margaritesti" },
  { nume: "Fantanele", comuna: "Margaritesti" },
  { nume: "Ciobanoaia", comuna: "Merei" },
  { nume: "Dealul Viei", comuna: "Merei" },
  { nume: "Dobrilesti", comuna: "Merei" },
  { nume: "Gura Saratii", comuna: "Merei" },
  { nume: "Izvoru Dulce", comuna: "Merei" },
  { nume: "Lipia", comuna: "Merei" },
  { nume: "Nenciulesti", comuna: "Merei" },
  { nume: "Ograzile", comuna: "Merei" },
  { nume: "Sarata-Monteoru", comuna: "Merei" },
  { nume: "Valea Putului Merei", comuna: "Merei" },
  { nume: "Coltaneni", comuna: "Mihailesti" },
  { nume: "Florica", comuna: "Mihailesti" },
  { nume: "Margineanu", comuna: "Mihailesti" },
  { nume: "Satu Nou", comuna: "Mihailesti" },
  { nume: "Cioranca", comuna: "Movila Banului" },
  { nume: "Limpezis", comuna: "Movila Banului" },
  { nume: "Batogu", comuna: "Murgesti" },
  { nume: "Valea Ratei", comuna: "Murgesti" },
  { nume: "Fintesti", comuna: "Naeni" },
  { nume: "Fantanele", comuna: "Naeni" },
  { nume: "Prosca", comuna: "Naeni" },
  { nume: "Varf", comuna: "Naeni" },
  { nume: "Basca Rozilei", comuna: "Nehoiu" },
  { nume: "Chirlesti", comuna: "Nehoiu" },
  { nume: "Curmatura", comuna: "Nehoiu" },
  { nume: "Lunca Priporului", comuna: "Nehoiu" },
  { nume: "Mlajet", comuna: "Nehoiu" },
  { nume: "Nehoiasu", comuna: "Nehoiu" },
  { nume: "Paltineni", comuna: "Nehoiu" },
  { nume: "Stanila", comuna: "Nehoiu" },
  { nume: "Vinetisu", comuna: "Nehoiu" },
  { nume: "Capu Satului", comuna: "Odaile" },
  { nume: "Corneanu", comuna: "Odaile" },
  { nume: "Gorani", comuna: "Odaile" },
  { nume: "Lacu", comuna: "Odaile" },
  { nume: "Piatra Alba", comuna: "Odaile" },
  { nume: "Posobesti", comuna: "Odaile" },
  { nume: "Scorosesti", comuna: "Odaile" },
  { nume: "Valea Fantanei", comuna: "Odaile" },
  { nume: "Valea Stefanului", comuna: "Odaile" },
  { nume: "Tatulesti", comuna: "Padina" },
  { nume: "Begu", comuna: "Panatau" },
  { nume: "Lacu cu Anini", comuna: "Panatau" },
  { nume: "Maguricea", comuna: "Panatau" },
  { nume: "Plaisor", comuna: "Panatau" },
  { nume: "Rapile", comuna: "Panatau" },
  { nume: "Sibiciu de Jos", comuna: "Panatau" },
  { nume: "Tega", comuna: "Panatau" },
  { nume: "Zaharesti", comuna: "Panatau" },
  { nume: "Chiperu", comuna: "Pardosi" },
  { nume: "Costomiru", comuna: "Pardosi" },
  { nume: "Valea lui Lalu", comuna: "Pardosi" },
  { nume: "Valea Schiopului", comuna: "Pardosi" },
  { nume: "Badila", comuna: "Parscov" },
  { nume: "Curcanesti", comuna: "Parscov" },
  { nume: "Lunca Frumoasa", comuna: "Parscov" },
  { nume: "Olesesti", comuna: "Parscov" },
  { nume: "Parjolesti", comuna: "Parscov" },
  { nume: "Robesti", comuna: "Parscov" },
  { nume: "Runcu", comuna: "Parscov" },
  { nume: "Tocileni", comuna: "Parscov" },
  { nume: "Trestieni", comuna: "Parscov" },
  { nume: "Tarcov", comuna: "Parscov" },
  { nume: "Valea Purcarului", comuna: "Parscov" },
  { nume: "Calea Chiojdului", comuna: "Patarlagele" },
  { nume: "Crang", comuna: "Patarlagele" },
  { nume: "Fundaturile", comuna: "Patarlagele" },
  { nume: "Gornet", comuna: "Patarlagele" },
  { nume: "Lunca", comuna: "Patarlagele" },
  { nume: "Muscel", comuna: "Patarlagele" },
  { nume: "Manastirea", comuna: "Patarlagele" },
  { nume: "Maruntisu", comuna: "Patarlagele" },
  { nume: "Poienile", comuna: "Patarlagele" },
  { nume: "Sibiciu de Sus", comuna: "Patarlagele" },
  { nume: "Stroesti", comuna: "Patarlagele" },
  { nume: "Valea Lupului", comuna: "Patarlagele" },
  { nume: "Valea Sibiciului", comuna: "Patarlagele" },
  { nume: "Valea Viei", comuna: "Patarlagele" },
  { nume: "Clondiru de Sus", comuna: "Pietroasele" },
  { nume: "Caltesti", comuna: "Pietroasele" },
  { nume: "Dara", comuna: "Pietroasele" },
  { nume: "Pietroasa Mica", comuna: "Pietroasele" },
  { nume: "Saranga", comuna: "Pietroasele" },
  { nume: "Cotatcu", comuna: "Podgoria" },
  { nume: "Oratia", comuna: "Podgoria" },
  { nume: "Plesesti", comuna: "Podgoria" },
  { nume: "Tabacari", comuna: "Podgoria" },
  { nume: "Caldarasti", comuna: "Pogoanele" },
  { nume: "Aliceni", comuna: "Posta Calnau" },
  { nume: "Coconari", comuna: "Posta Calnau" },
  { nume: "Potarnichesti", comuna: "Posta Calnau" },
  { nume: "Suditi", comuna: "Posta Calnau" },
  { nume: "Zilisteanca", comuna: "Posta Calnau" },
  { nume: "Dascalesti", comuna: "Puiesti" },
  { nume: "Lunca", comuna: "Puiesti" },
  { nume: "Macrina", comuna: "Puiesti" },
  { nume: "Nicolesti", comuna: "Puiesti" },
  { nume: "Plopi", comuna: "Puiesti" },
  { nume: "Puiestii de Jos", comuna: "Puiesti" },
  { nume: "Puiestii de Sus", comuna: "Puiesti" },
  { nume: "Budrea", comuna: "Racoviteni" },
  { nume: "Petrisoru", comuna: "Racoviteni" },
  { nume: "Colibasi", comuna: "Ramnicelu" },
  { nume: "Fotin", comuna: "Ramnicelu" },
  { nume: "Stiubei", comuna: "Ramnicelu" },
  { nume: "Mosesti", comuna: "Robeasca" },
  { nume: "Sergent Ionel Stefan", comuna: "Rusetu" },
  { nume: "Banita", comuna: "Sageata" },
  { nume: "Beilic", comuna: "Sageata" },
  { nume: "Bordusani", comuna: "Sageata" },
  { nume: "Dambroca", comuna: "Sageata" },
  { nume: "Gavanesti", comuna: "Sageata" },
  { nume: "Movilita", comuna: "Sageata" },
  { nume: "Gageni", comuna: "Sahateni" },
  { nume: "Istrita de Jos", comuna: "Sahateni" },
  { nume: "Vintileanca", comuna: "Sahateni" },
  { nume: "Matesti", comuna: "Sapoca" },
  { nume: "Caratnau de Jos", comuna: "Sarulesti" },
  { nume: "Caratnau de Sus", comuna: "Sarulesti" },
  { nume: "Goicelu", comuna: "Sarulesti" },
  { nume: "Sarile-Catun", comuna: "Sarulesti" },
  { nume: "Valea Larga-Sarulesti", comuna: "Sarulesti" },
  { nume: "Valea Stanei", comuna: "Sarulesti" },
  { nume: "Balta Tocila", comuna: "Scortoasa" },
  { nume: "Beciu", comuna: "Scortoasa" },
  { nume: "Deleni", comuna: "Scortoasa" },
  { nume: "Dalma", comuna: "Scortoasa" },
  { nume: "Golu Grabicina", comuna: "Scortoasa" },
  { nume: "Grabicina de Jos", comuna: "Scortoasa" },
  { nume: "Grabicina de Sus", comuna: "Scortoasa" },
  { nume: "Gura Vaii", comuna: "Scortoasa" },
  { nume: "Plopeasa", comuna: "Scortoasa" },
  { nume: "Policiori", comuna: "Scortoasa" },
  { nume: "Arcanu", comuna: "Scutelnici" },
  { nume: "Bragareasa", comuna: "Scutelnici" },
  { nume: "Lipanescu", comuna: "Scutelnici" },
  { nume: "Casoca", comuna: "Siriu" },
  { nume: "Coltu Pietrii", comuna: "Siriu" },
  { nume: "Gura Siriului", comuna: "Siriu" },
  { nume: "Lunca Jaristei", comuna: "Siriu" },
  { nume: "Muscelusa", comuna: "Siriu" },
  { nume: "Albesti", comuna: "Smeeni" },
  { nume: "Balaia", comuna: "Smeeni" },
  { nume: "Caltuna", comuna: "Smeeni" },
  { nume: "Moisica", comuna: "Smeeni" },
  { nume: "Udati-Lucieni", comuna: "Smeeni" },
  { nume: "Udati-Manzu", comuna: "Smeeni" },
  { nume: "Maxenu", comuna: "Tintesti" },
  { nume: "Odaia Banului", comuna: "Tintesti" },
  { nume: "Pogonele", comuna: "Tintesti" },
  { nume: "Barbuncesti", comuna: "Tisau" },
  { nume: "Grajdana", comuna: "Tisau" },
  { nume: "Hales", comuna: "Tisau" },
  { nume: "Izvoranu", comuna: "Tisau" },
  { nume: "Izvoru", comuna: "Tisau" },
  { nume: "Leiculesti", comuna: "Tisau" },
  { nume: "Padurenii", comuna: "Tisau" },
  { nume: "Salcia", comuna: "Tisau" },
  { nume: "Strezeni", comuna: "Tisau" },
  { nume: "Valea Salciilor", comuna: "Tisau" },
  { nume: "Babeni", comuna: "Topliceni" },
  { nume: "Ceairu", comuna: "Topliceni" },
  { nume: "Dedulesti", comuna: "Topliceni" },
  { nume: "Gura Fagetului", comuna: "Topliceni" },
  { nume: "Posta", comuna: "Topliceni" },
  { nume: "Raducesti", comuna: "Topliceni" },
  { nume: "Baltareti", comuna: "Ulmeni" },
  { nume: "Clondiru", comuna: "Ulmeni" },
  { nume: "Sarata", comuna: "Ulmeni" },
  { nume: "Valcele", comuna: "Ulmeni" },
  { nume: "Ojasca", comuna: "Unguriu" },
  { nume: "Bajani", comuna: "Vadu Pasii" },
  { nume: "Focsanei", comuna: "Vadu Pasii" },
  { nume: "Gura Calnaului", comuna: "Vadu Pasii" },
  { nume: "Scurtesti", comuna: "Vadu Pasii" },
  { nume: "Stancesti", comuna: "Vadu Pasii" },
  { nume: "Oreavul", comuna: "Valea Ramnicului" },
  { nume: "Rubla", comuna: "Valea Ramnicului" },
  { nume: "Modreni", comuna: "Valea Salciei" },
  { nume: "Valea Salciei-Catun", comuna: "Valea Salciei" },
  { nume: "Bradeanca", comuna: "Vernesti" },
  { nume: "Candesti", comuna: "Vernesti" },
  { nume: "Carlomanesti", comuna: "Vernesti" },
  { nume: "Mierea", comuna: "Vernesti" },
  { nume: "Nenciu", comuna: "Vernesti" },
  { nume: "Niscov", comuna: "Vernesti" },
  { nume: "Sasenii Noi", comuna: "Vernesti" },
  { nume: "Sasenii Vechi", comuna: "Vernesti" },
  { nume: "Sasenii pe Vale", comuna: "Vernesti" },
  { nume: "Zoresti", comuna: "Vernesti" },
  { nume: "Bodinesti", comuna: "Vintila Voda" },
  { nume: "Coca-Antimiresti", comuna: "Vintila Voda" },
  { nume: "Coca-Niculesti", comuna: "Vintila Voda" },
  { nume: "Niculesti", comuna: "Vintila Voda" },
  { nume: "Petrachesti", comuna: "Vintila Voda" },
  { nume: "Podu Muncii", comuna: "Vintila Voda" },
  { nume: "Smeesti", comuna: "Vintila Voda" },
  { nume: "Sarbesti", comuna: "Vintila Voda" },
  { nume: "Muscel", comuna: "Viperesti" },
  { nume: "Palici", comuna: "Viperesti" },
  { nume: "Rusavat", comuna: "Viperesti" },
  { nume: "Tronari", comuna: "Viperesti" },
  { nume: "Ursoaia", comuna: "Viperesti" },
  { nume: "Comisoaia", comuna: "Zarnesti" },
  { nume: "Fundeni", comuna: "Zarnesti" },
  { nume: "Pruneni", comuna: "Zarnesti" },
  { nume: "Vadu Soresti", comuna: "Zarnesti" },
  { nume: "Costieni", comuna: "Ziduri" },
  { nume: "Cuculeasa", comuna: "Ziduri" },
  { nume: "Heliade Radulescu", comuna: "Ziduri" },
  { nume: "Lanurile", comuna: "Ziduri" },
  { nume: "Zoita", comuna: "Ziduri" },
];
