export const bc = [
  { nume: "Agas" },
  { nume: "Ardeoani" },
  { nume: "Asau" },
  { nume: "Bacau" },
  { nume: "Balcani" },
  { nume: "Beresti-Bistrita" },
  { nume: "Beresti-Tazlau" },
  { nume: "Berzunti" },
  { nume: "Blagesti" },
  { nume: "Bogdanesti" },
  { nume: "Brusturoasa" },
  { nume: "Buhoci" },
  { nume: "Buhusi" },
  { nume: "Barsanesti" },
  { nume: "Casin" },
  { nume: "Cleja" },
  { nume: "Colonesti" },
  { nume: "Comanesti" },
  { nume: "Corbasca" },
  { nume: "Cotofanesti" },
  { nume: "Caiuti" },
  { nume: "Dealu Morii" },
  { nume: "Dofteana" },
  { nume: "Damienesti" },
  { nume: "Darmanesti" },
  { nume: "Faraoani" },
  { nume: "Filipeni" },
  { nume: "Filipesti" },
  { nume: "Glavanesti" },
  { nume: "Gura Vaii" },
  { nume: "Garleni" },
  { nume: "Gaiceana" },
  { nume: "Helegiu" },
  { nume: "Hemeius" },
  { nume: "Horgesti" },
  { nume: "Huruiesti" },
  { nume: "Izvoru Berheciului" },
  { nume: "Letea Veche" },
  { nume: "Lipova" },
  { nume: "Livezi" },
  { nume: "Luizi-Calugara" },
  { nume: "Moinesti" },
  { nume: "Motoseni" },
  { nume: "Magiresti" },
  { nume: "Magura" },
  { nume: "Manastirea Casin" },
  { nume: "Margineni" },
  { nume: "Negri" },
  { nume: "Nicolae Balcescu" },
  { nume: "Oituz" },
  { nume: "Oncesti" },
  { nume: "Onesti" },
  { nume: "Orbeni" },
  { nume: "Palanca" },
  { nume: "Parava" },
  { nume: "Parincea" },
  { nume: "Plopana" },
  { nume: "Podu Turcului" },
  { nume: "Poduri" },
  { nume: "Pancesti" },
  { nume: "Pargaresti" },
  { nume: "Parjol" },
  { nume: "Racova" },
  { nume: "Rosiori" },
  { nume: "Rachitoasa" },
  { nume: "Racaciuni" },
  { nume: "Sascut" },
  { nume: "Scorteni" },
  { nume: "Secuieni" },
  { nume: "Solont" },
  { nume: "Strugari" },
  { nume: "Stanisesti" },
  { nume: "Sanduleni" },
  { nume: "Saucesti" },
  { nume: "Tamasi" },
  { nume: "Traian" },
  { nume: "Targu Ocna" },
  { nume: "Targu Trotus" },
  { nume: "Tatarasti" },
  { nume: "Ungureni" },
  { nume: "Urechesti" },
  { nume: "Valea Seaca" },
  { nume: "Vultureni" },
  { nume: "Zemes" },
  { nume: "Stefan cel Mare" },
  { nume: "Beleghet", comuna: "Agas" },
  { nume: "Cotumba", comuna: "Agas" },
  { nume: "Cosnea", comuna: "Agas" },
  { nume: "Diaconesti", comuna: "Agas" },
  { nume: "Goioasa", comuna: "Agas" },
  { nume: "Preluci", comuna: "Agas" },
  { nume: "Sulta", comuna: "Agas" },
  { nume: "Leontinesti", comuna: "Ardeoani" },
  { nume: "Apa Asau", comuna: "Asau" },
  { nume: "Ciobanus", comuna: "Asau" },
  { nume: "Lunca Asau", comuna: "Asau" },
  { nume: "Paltinis", comuna: "Asau" },
  { nume: "Straja", comuna: "Asau" },
  { nume: "Frumoasa", comuna: "Balcani" },
  { nume: "Ludasi", comuna: "Balcani" },
  { nume: "Schitu Frumoasa", comuna: "Balcani" },
  { nume: "Albele", comuna: "Barsanesti" },
  { nume: "Bratesti", comuna: "Barsanesti" },
  { nume: "Caraclau", comuna: "Barsanesti" },
  { nume: "Brad", comuna: "Beresti-Bistrita" },
  { nume: "Ciumasi", comuna: "Beresti-Bistrita" },
  { nume: "Climesti", comuna: "Beresti-Bistrita" },
  { nume: "Dumbrava", comuna: "Beresti-Bistrita" },
  { nume: "Fagetel", comuna: "Beresti-Bistrita" },
  { nume: "Itesti", comuna: "Beresti-Bistrita" },
  { nume: "Padureni", comuna: "Beresti-Bistrita" },
  { nume: "Bosoteni", comuna: "Beresti-Tazlau" },
  { nume: "Enachesti", comuna: "Beresti-Tazlau" },
  { nume: "Prisaca", comuna: "Beresti-Tazlau" },
  { nume: "Romanesti", comuna: "Beresti-Tazlau" },
  { nume: "Tescani", comuna: "Beresti-Tazlau" },
  { nume: "Turluianu", comuna: "Beresti-Tazlau" },
  { nume: "Buda", comuna: "Berzunti" },
  { nume: "Dragomir", comuna: "Berzunti" },
  { nume: "Buda", comuna: "Blagesti" },
  { nume: "Poiana Negustorului", comuna: "Blagesti" },
  { nume: "Valea lui Ion", comuna: "Blagesti" },
  { nume: "Tardenii Mari", comuna: "Blagesti" },
  { nume: "Filipesti", comuna: "Bogdanesti" },
  { nume: "Buruienis", comuna: "Brusturoasa" },
  { nume: "Buruienisu de Sus", comuna: "Brusturoasa" },
  { nume: "Camenca", comuna: "Brusturoasa" },
  { nume: "Cuchinis", comuna: "Brusturoasa" },
  { nume: "Hanganesti", comuna: "Brusturoasa" },
  { nume: "Bijghir", comuna: "Buhoci" },
  { nume: "Buhocel", comuna: "Buhoci" },
  { nume: "Coteni", comuna: "Buhoci" },
  { nume: "Dospinesti", comuna: "Buhoci" },
  { nume: "Marginea", comuna: "Buhusi" },
  { nume: "Runcu", comuna: "Buhusi" },
  { nume: "Blidari", comuna: "Caiuti" },
  { nume: "Boistea", comuna: "Caiuti" },
  { nume: "Floresti", comuna: "Caiuti" },
  { nume: "Heltiu", comuna: "Caiuti" },
  { nume: "Marcesti", comuna: "Caiuti" },
  { nume: "Popeni", comuna: "Caiuti" },
  { nume: "Pralea", comuna: "Caiuti" },
  { nume: "Vranceni", comuna: "Caiuti" },
  { nume: "Curita", comuna: "Casin" },
  { nume: "Somusca", comuna: "Cleja" },
  { nume: "Valea Mica", comuna: "Cleja" },
  { nume: "Calini", comuna: "Colonesti" },
  { nume: "Poiana", comuna: "Colonesti" },
  { nume: "Satu Nou", comuna: "Colonesti" },
  { nume: "Spria", comuna: "Colonesti" },
  { nume: "Valea Mare", comuna: "Colonesti" },
  { nume: "Zapodia", comuna: "Colonesti" },
  { nume: "Podei", comuna: "Comanesti" },
  { nume: "Vermesti", comuna: "Comanesti" },
  { nume: "Bacioiu", comuna: "Corbasca" },
  { nume: "Marvila", comuna: "Corbasca" },
  { nume: "Poglet", comuna: "Corbasca" },
  { nume: "Rogoaza", comuna: "Corbasca" },
  { nume: "Scarisoara", comuna: "Corbasca" },
  { nume: "Valcele", comuna: "Corbasca" },
  { nume: "Boistea de Jos", comuna: "Cotofanesti" },
  { nume: "Borsani", comuna: "Cotofanesti" },
  { nume: "Balca", comuna: "Cotofanesti" },
  { nume: "Tamasoaia", comuna: "Cotofanesti" },
  { nume: "Calugareni", comuna: "Damienesti" },
  { nume: "Dragesti", comuna: "Damienesti" },
  { nume: "Padureni", comuna: "Damienesti" },
  { nume: "Darmaneasca", comuna: "Darmanesti" },
  { nume: "Lapos", comuna: "Darmanesti" },
  { nume: "Plopu", comuna: "Darmanesti" },
  { nume: "Pagubeni", comuna: "Darmanesti" },
  { nume: "Salatruc", comuna: "Darmanesti" },
  { nume: "Banca", comuna: "Dealu Morii" },
  { nume: "Blaga", comuna: "Dealu Morii" },
  { nume: "Bobos", comuna: "Dealu Morii" },
  { nume: "Bodeasa", comuna: "Dealu Morii" },
  { nume: "Bostanesti", comuna: "Dealu Morii" },
  { nume: "Balanesti", comuna: "Dealu Morii" },
  { nume: "Calapodesti", comuna: "Dealu Morii" },
  { nume: "Cauia", comuna: "Dealu Morii" },
  { nume: "Dorofei", comuna: "Dealu Morii" },
  { nume: "Ghionoaia", comuna: "Dealu Morii" },
  { nume: "Gradesti", comuna: "Dealu Morii" },
  { nume: "Negulesti", comuna: "Dealu Morii" },
  { nume: "Tavadaresti", comuna: "Dealu Morii" },
  { nume: "Bogata", comuna: "Dofteana" },
  { nume: "Cucuieti", comuna: "Dofteana" },
  { nume: "Haghiac", comuna: "Dofteana" },
  { nume: "Larga", comuna: "Dofteana" },
  { nume: "Seaca", comuna: "Dofteana" },
  { nume: "Stefan Voda", comuna: "Dofteana" },
  { nume: "Brad", comuna: "Filipeni" },
  { nume: "Balaia", comuna: "Filipeni" },
  { nume: "Fruntesti", comuna: "Filipeni" },
  { nume: "Marasti", comuna: "Filipeni" },
  { nume: "Padureni", comuna: "Filipeni" },
  { nume: "Slobozia", comuna: "Filipeni" },
  { nume: "Valea Botului", comuna: "Filipeni" },
  { nume: "Boanta", comuna: "Filipesti" },
  { nume: "Cornesti", comuna: "Filipesti" },
  { nume: "Cotu Grosului", comuna: "Filipesti" },
  { nume: "Carligi", comuna: "Filipesti" },
  { nume: "Galbeni", comuna: "Filipesti" },
  { nume: "Harlesti", comuna: "Filipesti" },
  { nume: "Oniscani", comuna: "Filipesti" },
  { nume: "Arini", comuna: "Gaiceana" },
  { nume: "Hutu", comuna: "Gaiceana" },
  { nume: "Popesti", comuna: "Gaiceana" },
  { nume: "Garlenii de Sus", comuna: "Garleni" },
  { nume: "Lespezi", comuna: "Garleni" },
  { nume: "Surina", comuna: "Garleni" },
  { nume: "Bolovanis", comuna: "Ghimes-Faget" },
  { nume: "Faget", comuna: "Ghimes-Faget" },
  { nume: "Fagetu de Sus", comuna: "Ghimes-Faget" },
  { nume: "Ghimes", comuna: "Ghimes-Faget" },
  { nume: "Rachitis", comuna: "Ghimes-Faget" },
  { nume: "Tarhausi", comuna: "Ghimes-Faget" },
  { nume: "Frumuselu", comuna: "Glavanesti" },
  { nume: "Muncelu", comuna: "Glavanesti" },
  { nume: "Putredeni", comuna: "Glavanesti" },
  { nume: "Razesu", comuna: "Glavanesti" },
  { nume: "Capata", comuna: "Gura Vaii" },
  { nume: "Dumbrava", comuna: "Gura Vaii" },
  { nume: "Motocesti", comuna: "Gura Vaii" },
  { nume: "Paltinata", comuna: "Gura Vaii" },
  { nume: "Temelia", comuna: "Gura Vaii" },
  { nume: "Bratila", comuna: "Helegiu" },
  { nume: "Deleni", comuna: "Helegiu" },
  { nume: "Dragugesti", comuna: "Helegiu" },
  { nume: "Fantanele", comuna: "Hemeius" },
  { nume: "Lilieci", comuna: "Hemeius" },
  { nume: "Bazga", comuna: "Horgesti" },
  { nume: "Galeri", comuna: "Horgesti" },
  { nume: "Marascu", comuna: "Horgesti" },
  { nume: "Recea", comuna: "Horgesti" },
  { nume: "Racatau de Jos", comuna: "Horgesti" },
  { nume: "Racatau-Razesi", comuna: "Horgesti" },
  { nume: "Sohodor", comuna: "Horgesti" },
  { nume: "Capotesti", comuna: "Huruiesti" },
  { nume: "Floresti", comuna: "Huruiesti" },
  { nume: "Fundoaia", comuna: "Huruiesti" },
  { nume: "Ocheni", comuna: "Huruiesti" },
  { nume: "Perchiu", comuna: "Huruiesti" },
  { nume: "Pradais", comuna: "Huruiesti" },
  { nume: "Antohesti", comuna: "Izvoru Berheciului" },
  { nume: "Baimac", comuna: "Izvoru Berheciului" },
  { nume: "Faghieni", comuna: "Izvoru Berheciului" },
  { nume: "Obarsia", comuna: "Izvoru Berheciului" },
  { nume: "Otelesti", comuna: "Izvoru Berheciului" },
  { nume: "Padureni", comuna: "Izvoru Berheciului" },
  { nume: "Holt", comuna: "Letea Veche" },
  { nume: "Radomiresti", comuna: "Letea Veche" },
  { nume: "Rusi-Ciutea", comuna: "Letea Veche" },
  { nume: "Siretu", comuna: "Letea Veche" },
  { nume: "Malosu", comuna: "Lipova" },
  { nume: "Satu Nou", comuna: "Lipova" },
  { nume: "Valea Caselor", comuna: "Lipova" },
  { nume: "Valea Hogei", comuna: "Lipova" },
  { nume: "Valea Mosneagului", comuna: "Lipova" },
  { nume: "Valea Marului", comuna: "Lipova" },
  { nume: "Balaneasa", comuna: "Livezi" },
  { nume: "Orasa", comuna: "Livezi" },
  { nume: "Poiana", comuna: "Livezi" },
  { nume: "Prajoaia", comuna: "Livezi" },
  { nume: "Scariga", comuna: "Livezi" },
  { nume: "Osebiti", comuna: "Luizi-Calugara" },
  { nume: "Prajesti", comuna: "Magiresti" },
  { nume: "Stanesti", comuna: "Magiresti" },
  { nume: "Valea Arinilor", comuna: "Magiresti" },
  { nume: "Sesuri", comuna: "Magiresti" },
  { nume: "Crihan", comuna: "Magura" },
  { nume: "Dealu-Mare", comuna: "Magura" },
  { nume: "Sohodol", comuna: "Magura" },
  { nume: "Lupesti", comuna: "Manastirea Casin" },
  { nume: "Parvulesti", comuna: "Manastirea Casin" },
  { nume: "Scutaru", comuna: "Manastirea Casin" },
  { nume: "Barati", comuna: "Margineni" },
  { nume: "Luncani", comuna: "Margineni" },
  { nume: "Podis", comuna: "Margineni" },
  { nume: "Poiana", comuna: "Margineni" },
  { nume: "Padureni", comuna: "Margineni" },
  { nume: "Trebes", comuna: "Margineni" },
  { nume: "Valea Budului", comuna: "Margineni" },
  { nume: "Gazarie", comuna: "Moinesti" },
  { nume: "Baclesti", comuna: "Motoseni" },
  { nume: "Chetreni", comuna: "Motoseni" },
  { nume: "Chicerea", comuna: "Motoseni" },
  { nume: "Cociu", comuna: "Motoseni" },
  { nume: "Cornatelu", comuna: "Motoseni" },
  { nume: "Fundatura", comuna: "Motoseni" },
  { nume: "Fantanele", comuna: "Motoseni" },
  { nume: "Gura Craiesti", comuna: "Motoseni" },
  { nume: "Poiana", comuna: "Motoseni" },
  { nume: "Praja", comuna: "Motoseni" },
  { nume: "Rotaria", comuna: "Motoseni" },
  { nume: "Sendresti", comuna: "Motoseni" },
  { nume: "Tepoaia", comuna: "Motoseni" },
  { nume: "Brad", comuna: "Negri" },
  { nume: "Calinesti", comuna: "Negri" },
  { nume: "Magla", comuna: "Negri" },
  { nume: "Poiana", comuna: "Negri" },
  { nume: "Ursoaia", comuna: "Negri" },
  { nume: "Buchila", comuna: "Nicolae Balcescu" },
  { nume: "Baltata", comuna: "Nicolae Balcescu" },
  { nume: "Galbeni", comuna: "Nicolae Balcescu" },
  { nume: "Larguta", comuna: "Nicolae Balcescu" },
  { nume: "Sarata", comuna: "Nicolae Balcescu" },
  { nume: "Valea Seaca", comuna: "Nicolae Balcescu" },
  { nume: "Calcai", comuna: "Oituz" },
  { nume: "Ferestrau-Oituz", comuna: "Oituz" },
  { nume: "Harja", comuna: "Oituz" },
  { nume: "Marginea", comuna: "Oituz" },
  { nume: "Poiana Sarata", comuna: "Oituz" },
  { nume: "Barboasa", comuna: "Oncesti" },
  { nume: "Dealu Perjului", comuna: "Oncesti" },
  { nume: "Oncestii Vechi", comuna: "Oncesti" },
  { nume: "Satu Nou", comuna: "Oncesti" },
  { nume: "Tarnita", comuna: "Oncesti" },
  { nume: "Taula", comuna: "Oncesti" },
  { nume: "Borzesti", comuna: "Onesti" },
  { nume: "Slobozia", comuna: "Onesti" },
  { nume: "Scurta", comuna: "Orbeni" },
  { nume: "Ciughes", comuna: "Palanca" },
  { nume: "Cadaresti", comuna: "Palanca" },
  { nume: "Pajistea", comuna: "Palanca" },
  { nume: "Popoiu", comuna: "Palanca" },
  { nume: "Chilia Benei", comuna: "Pancesti" },
  { nume: "Dienet", comuna: "Pancesti" },
  { nume: "Fulgeris", comuna: "Pancesti" },
  { nume: "Fundu Vaii", comuna: "Pancesti" },
  { nume: "Motoc", comuna: "Pancesti" },
  { nume: "Petresti", comuna: "Pancesti" },
  { nume: "Soci", comuna: "Pancesti" },
  { nume: "Dragusani", comuna: "Parava" },
  { nume: "Radoaia", comuna: "Parava" },
  { nume: "Teius", comuna: "Parava" },
  { nume: "Bahna", comuna: "Pargaresti" },
  { nume: "Nicoresti", comuna: "Pargaresti" },
  { nume: "Parau Boghii", comuna: "Pargaresti" },
  { nume: "Satu Nou", comuna: "Pargaresti" },
  { nume: "Barna", comuna: "Parincea" },
  { nume: "Milestii de Jos", comuna: "Parincea" },
  { nume: "Milestii de Sus", comuna: "Parincea" },
  { nume: "Nanesti", comuna: "Parincea" },
  { nume: "Nastaseni", comuna: "Parincea" },
  { nume: "Poieni", comuna: "Parincea" },
  { nume: "Satu Nou", comuna: "Parincea" },
  { nume: "Vladnic", comuna: "Parincea" },
  { nume: "Valeni", comuna: "Parincea" },
  { nume: "Bahnaseni", comuna: "Parjol" },
  { nume: "Barnesti", comuna: "Parjol" },
  { nume: "Basasti", comuna: "Parjol" },
  { nume: "Campeni", comuna: "Parjol" },
  { nume: "Hemieni", comuna: "Parjol" },
  { nume: "Haineala", comuna: "Parjol" },
  { nume: "Pustiana", comuna: "Parjol" },
  { nume: "Tarata", comuna: "Parjol" },
  { nume: "Budesti", comuna: "Plopana" },
  { nume: "Dorneni", comuna: "Plopana" },
  { nume: "Fundu Tutovei", comuna: "Plopana" },
  { nume: "Itcani", comuna: "Plopana" },
  { nume: "Rusenii Razesi", comuna: "Plopana" },
  { nume: "Rusenii de Sus", comuna: "Plopana" },
  { nume: "Straminoasa", comuna: "Plopana" },
  { nume: "Tagara", comuna: "Plopana" },
  { nume: "Balanesti", comuna: "Podu Turcului" },
  { nume: "Cabesti", comuna: "Podu Turcului" },
  { nume: "Fichitesti", comuna: "Podu Turcului" },
  { nume: "Giurgioana", comuna: "Podu Turcului" },
  { nume: "Hanta", comuna: "Podu Turcului" },
  { nume: "Lehancea", comuna: "Podu Turcului" },
  { nume: "Plopu", comuna: "Podu Turcului" },
  { nume: "Racusana", comuna: "Podu Turcului" },
  { nume: "Sarbi", comuna: "Podu Turcului" },
  { nume: "Bucsesti", comuna: "Poduri" },
  { nume: "Cernu", comuna: "Poduri" },
  { nume: "Cornet", comuna: "Poduri" },
  { nume: "Negreni", comuna: "Poduri" },
  { nume: "Prohozesti", comuna: "Poduri" },
  { nume: "Valea Sosii", comuna: "Poduri" },
  { nume: "Ciucani", comuna: "Racaciuni" },
  { nume: "Fundu Racaciuni", comuna: "Racaciuni" },
  { nume: "Gheorghe Doja", comuna: "Racaciuni" },
  { nume: "Gasteni", comuna: "Racaciuni" },
  { nume: "Rastoaca", comuna: "Racaciuni" },
  { nume: "Barcana", comuna: "Rachitoasa" },
  { nume: "Bucsa", comuna: "Rachitoasa" },
  { nume: "Buda", comuna: "Rachitoasa" },
  { nume: "Burdusaci", comuna: "Rachitoasa" },
  { nume: "Dumbrava", comuna: "Rachitoasa" },
  { nume: "Danaila", comuna: "Rachitoasa" },
  { nume: "Farcasa", comuna: "Rachitoasa" },
  { nume: "Fundatura Rachitoasa", comuna: "Rachitoasa" },
  { nume: "Haghiac", comuna: "Rachitoasa" },
  { nume: "Magazia", comuna: "Rachitoasa" },
  { nume: "Movilita", comuna: "Rachitoasa" },
  { nume: "Oprisesti", comuna: "Rachitoasa" },
  { nume: "Putini", comuna: "Rachitoasa" },
  { nume: "Tochilea", comuna: "Rachitoasa" },
  { nume: "Gura Vaii", comuna: "Racova" },
  { nume: "Halmacioaia", comuna: "Racova" },
  { nume: "Iliesi", comuna: "Racova" },
  { nume: "Misihanesti", comuna: "Rosiori" },
  { nume: "Neguseni", comuna: "Rosiori" },
  { nume: "Poieni", comuna: "Rosiori" },
  { nume: "Valea Mare", comuna: "Rosiori" },
  { nume: "Valea Mica", comuna: "Rosiori" },
  { nume: "Barzulesti", comuna: "Sanduleni" },
  { nume: "Coman", comuna: "Sanduleni" },
  { nume: "Mateiesti", comuna: "Sanduleni" },
  { nume: "Stufu", comuna: "Sanduleni" },
  { nume: "Tisa", comuna: "Sanduleni" },
  { nume: "Versesti", comuna: "Sanduleni" },
  { nume: "Beresti", comuna: "Sascut" },
  { nume: "Contesti", comuna: "Sascut" },
  { nume: "Pancesti", comuna: "Sascut" },
  { nume: "Sascut-Sat", comuna: "Sascut" },
  { nume: "Schineni", comuna: "Sascut" },
  { nume: "Valea Nacului", comuna: "Sascut" },
  { nume: "Bogdan Voda", comuna: "Saucesti" },
  { nume: "Costei", comuna: "Saucesti" },
  { nume: "Schineni", comuna: "Saucesti" },
  { nume: "Siretu", comuna: "Saucesti" },
  { nume: "Serbesti", comuna: "Saucesti" },
  { nume: "Bogdanesti", comuna: "Scorteni" },
  { nume: "Floresti", comuna: "Scorteni" },
  { nume: "Grigoreni", comuna: "Scorteni" },
  { nume: "Stejaru", comuna: "Scorteni" },
  { nume: "Serpeni", comuna: "Scorteni" },
  { nume: "Berbinceni", comuna: "Secuieni" },
  { nume: "Balusa", comuna: "Secuieni" },
  { nume: "Chiticeni", comuna: "Secuieni" },
  { nume: "Ciuturesti", comuna: "Secuieni" },
  { nume: "Fundeni", comuna: "Secuieni" },
  { nume: "Glodisoarele", comuna: "Secuieni" },
  { nume: "Odobesti", comuna: "Secuieni" },
  { nume: "Tisa-Silvestri", comuna: "Secuieni" },
  { nume: "Valea Fanatului", comuna: "Secuieni" },
  { nume: "Valeni", comuna: "Secuieni" },
  { nume: "Cerdac", comuna: "Slanic Moldova" },
  { nume: "Ciresoaia", comuna: "Slanic Moldova" },
  { nume: "Slanic-Moldova", comuna: "Slanic Moldova" },
  { nume: "Cucuieti", comuna: "Solont" },
  { nume: "Sarata", comuna: "Solont" },
  { nume: "Balotesti", comuna: "Stanisesti" },
  { nume: "Belciuneasa", comuna: "Stanisesti" },
  { nume: "Benesti", comuna: "Stanisesti" },
  { nume: "Craiesti", comuna: "Stanisesti" },
  { nume: "Gorghesti", comuna: "Stanisesti" },
  { nume: "Slobozia", comuna: "Stanisesti" },
  { nume: "Slobozia Noua", comuna: "Stanisesti" },
  { nume: "Valeni", comuna: "Stanisesti" },
  { nume: "Bogdana", comuna: "Stefan Cel Mare" },
  { nume: "Buciumi", comuna: "Stefan Cel Mare" },
  { nume: "Gutinas", comuna: "Stefan Cel Mare" },
  { nume: "Negoiesti", comuna: "Stefan Cel Mare" },
  { nume: "Racauti", comuna: "Stefan Cel Mare" },
  { nume: "Radeana", comuna: "Stefan Cel Mare" },
  { nume: "Viisoara", comuna: "Stefan Cel Mare" },
  { nume: "Cetatuia", comuna: "Strugari" },
  { nume: "Iaz", comuna: "Strugari" },
  { nume: "Nadisa", comuna: "Strugari" },
  { nume: "Petricica", comuna: "Strugari" },
  { nume: "Rachitisu", comuna: "Strugari" },
  { nume: "Chetris", comuna: "Tamasi" },
  { nume: "Furnicari", comuna: "Tamasi" },
  { nume: "Gioseni", comuna: "Tamasi" },
  { nume: "Poieni", comuna: "Targu Ocna" },
  { nume: "Valcele", comuna: "Targu Ocna" },
  { nume: "Tuta", comuna: "Targu Trotus" },
  { nume: "Viisoara", comuna: "Targu Trotus" },
  { nume: "Cornii de Jos", comuna: "Tatarasti" },
  { nume: "Cornii de Sus", comuna: "Tatarasti" },
  { nume: "Dragesti", comuna: "Tatarasti" },
  { nume: "Gherdana", comuna: "Tatarasti" },
  { nume: "Giurgeni", comuna: "Tatarasti" },
  { nume: "Ungureni", comuna: "Tatarasti" },
  { nume: "Bogdanesti", comuna: "Traian" },
  { nume: "Hertioana de Jos", comuna: "Traian" },
  { nume: "Hertioana-Razesi", comuna: "Traian" },
  { nume: "Prajesti", comuna: "Traian" },
  { nume: "Zapodia", comuna: "Traian" },
  { nume: "Bibiresti", comuna: "Ungureni" },
  { nume: "Bota", comuna: "Ungureni" },
  { nume: "Botesti", comuna: "Ungureni" },
  { nume: "Bartasesti", comuna: "Ungureni" },
  { nume: "Garla Anei", comuna: "Ungureni" },
  { nume: "Viforeni", comuna: "Ungureni" },
  { nume: "Zlatari", comuna: "Ungureni" },
  { nume: "Cornatel", comuna: "Urechesti" },
  { nume: "Lunca Dochiei", comuna: "Urechesti" },
  { nume: "Satu Nou", comuna: "Urechesti" },
  { nume: "Slobozia", comuna: "Urechesti" },
  { nume: "Cucova", comuna: "Valea Seaca" },
  { nume: "Bosia", comuna: "Vultureni" },
  { nume: "Dorneni", comuna: "Vultureni" },
  { nume: "Dadesti", comuna: "Vultureni" },
  { nume: "Ghilavesti", comuna: "Vultureni" },
  { nume: "Godinestii de Jos", comuna: "Vultureni" },
  { nume: "Godinestii de Sus",comuna: "Vultureni" },
  { nume: "Lichitiseni", comuna: "Vultureni" },
  { nume: "Medeleni", comuna: "Vultureni" },
  { nume: "Nazarioaia", comuna: "Vultureni" },
  { nume: "Reprivat", comuna: "Vultureni" },
  { nume: "Tomozia", comuna: "Vultureni" },
  { nume: "Valea Lupului", comuna: "Vultureni" },
  { nume: "Valea Merilor", comuna: "Vultureni" },
  { nume: "Valea Salciei", comuna: "Vultureni" },
  { nume: "Tiganesti", comuna: "Vultureni" },
  { nume: "Bolatau", comuna: "Zemes" },
];
