export const cl = [
  { nume: "Alexandru Odobescu" },
  { nume: "Belciugatele" },
  { nume: "Borcea" },
  { nume: "Budesti" },
  { nume: "Chirnogi" },
  { nume: "Chiselet" },
  { nume: "Ciocanesti" },
  { nume: "Curcani" },
  { nume: "Cuza Voda" },
  { nume: "Calarasi" },
  { nume: "Cascioarele" },
  { nume: "Dichiseni" },
  { nume: "Dor Marunt" },
  { nume: "Dorobantu" },
  { nume: "Dragalina" },
  { nume: "Dragos Voda" },
  { nume: "Frumusani" },
  { nume: "Frasinet" },
  { nume: "Fundeni" },
  { nume: "Fundulea" },
  { nume: "Gradistea" },
  { nume: "Gurbanesti" },
  { nume: "Ileana" },
  { nume: "Independenta" },
  { nume: "Jegalia" },
  { nume: "Lehliu" },
  { nume: "Luica" },
  { nume: "Lupsanu" },
  { nume: "Mitreni" },
  { nume: "Modelu" },
  { nume: "Manastirea" },
  { nume: "Nana" },
  { nume: "Nicolae Balcescu" },
  { nume: "Oltenita" },
  { nume: "Perisoru" },
  { nume: "Plataresti" },
  { nume: "Radovanu" },
  { nume: "Roseti" },
  { nume: "Sohatu" },
  { nume: "Spantov" },
  { nume: "Sarulesti" },
  { nume: "Tamadau Mare" },
  { nume: "Ulmeni" },
  { nume: "Ulmu" },
  { nume: "Unirea" },
  { nume: "Valea Argovei" },
  { nume: "Vasilati" },
  { nume: "Vlad Tepes" },
  { nume: "Valcelele" },
  { nume: "Soldanu" },
  { nume: "Stefan Voda" },
  { nume: "Stefan cel Mare" },
  { nume: "Galatui", comuna: "Alexandru Odobescu" },
  { nume: "Nicolae Balcescu", comuna: "Alexandru Odobescu" },
  { nume: "Cojesti", comuna: "Belciugatele" },
  { nume: "Candeasca", comuna: "Belciugatele" },
  { nume: "Mataraua", comuna: "Belciugatele" },
  { nume: "Mariuta", comuna: "Belciugatele" },
  { nume: "Aprozi", comuna: "Budesti" },
  { nume: "Buciumeni", comuna: "Budesti" },
  { nume: "Crivat", comuna: "Budesti" },
  { nume: "Gruiu", comuna: "Budesti" },
  { nume: "Salcioara", comuna: "Curcani" },
  { nume: "Ceacu", comuna: "Cuza Voda" },
  { nume: "Calarasii Vechi", comuna: "Cuza Voda" },
  { nume: "Coslogeni", comuna: "Dichiseni" },
  { nume: "Libertatea", comuna: "Dichiseni" },
  { nume: "Satnoeni", comuna: "Dichiseni" },
  { nume: "Dalga", comuna: "Dor Marunt" },
  { nume: "Dalga-Gara", comuna: "Dor Marunt" },
  { nume: "Ogoru", comuna: "Dor Marunt" },
  { nume: "Pelinu", comuna: "Dor Marunt" },
  { nume: "Infratirea", comuna: "Dor Marunt" },
  { nume: "Bosneagu", comuna: "Dorobantu" },
  { nume: "Varasti", comuna: "Dorobantu" },
  { nume: "Constantin Brancoveanu", comuna: "Dragalina" },
  { nume: "Drajna Noua", comuna: "Dragalina" },
  { nume: "Bogdana", comuna: "Dragos Voda" },
  { nume: "Socoalele", comuna: "Dragos Voda" },
  { nume: "Curatesti", comuna: "Frasinet" },
  { nume: "Danesti", comuna: "Frasinet" },
  { nume: "Frasinetu de Jos", comuna: "Frasinet" },
  { nume: "Luptatori", comuna: "Frasinet" },
  { nume: "Tariceni", comuna: "Frasinet" },
  { nume: "Orasti", comuna: "Frumusani" },
  { nume: "Pasarea", comuna: "Frumusani" },
  { nume: "Pitigaia", comuna: "Frumusani" },
  { nume: "Postavari", comuna: "Frumusani" },
  { nume: "Padurisu", comuna: "Frumusani" },
  { nume: "Alexandru I. Cuza", comuna: "Fundulea" },
  { nume: "Gostilele", comuna: "Fundulea" },
  { nume: "Bogata", comuna: "Gradistea" },
  { nume: "Cunesti", comuna: "Gradistea" },
  { nume: "Rasa", comuna: "Gradistea" },
  { nume: "Codreni", comuna: "Gurbanesti" },
  { nume: "Cotofanca", comuna: "Gurbanesti" },
  { nume: "Preasna", comuna: "Gurbanesti" },
  { nume: "Preasna Veche", comuna: "Gurbanesti" },
  { nume: "Valea Presnei", comuna: "Gurbanesti" },
  { nume: "Artari", comuna: "Ileana" },
  { nume: "Florica", comuna: "Ileana" },
  { nume: "Podari", comuna: "Ileana" },
  { nume: "Rasurile", comuna: "Ileana" },
  { nume: "Razoarele", comuna: "Ileana" },
  { nume: "Satu Nou", comuna: "Ileana" },
  { nume: "Vlaiculesti", comuna: "Ileana" },
  { nume: "Stefanesti", comuna: "Ileana" },
  { nume: "Potcoava", comuna: "Independenta" },
  { nume: "Visinii", comuna: "Independenta" },
  { nume: "Galdau", comuna: "Jegalia" },
  { nume: "Iezeru", comuna: "Jegalia" },
  { nume: "Sapunari", comuna: "Lehliu" },
  { nume: "Buzoeni", comuna: "Lehliu Gara" },
  { nume: "Lehliu-Gara", comuna: "Lehliu Gara" },
  { nume: "Razvani", comuna: "Lehliu Gara" },
  { nume: "Valea Seaca", comuna: "Lehliu Gara" },
  { nume: "Valea Stanii", comuna: "Luica" },
  { nume: "Nucetu", comuna: "Lupsanu" },
  { nume: "Plevna", comuna: "Lupsanu" },
  { nume: "Radu Voda", comuna: "Lupsanu" },
  { nume: "Valea Rusului", comuna: "Lupsanu" },
  { nume: "Coconi", comuna: "Manastirea" },
  { nume: "Sultana", comuna: "Manastirea" },
  { nume: "Clatesti", comuna: "Mitreni" },
  { nume: "Valea Rosie", comuna: "Mitreni" },
  { nume: "Radu Negru", comuna: "Modelu" },
  { nume: "Stoenesti", comuna: "Modelu" },
  { nume: "Tonea", comuna: "Modelu" },
  { nume: "Fantana Doamnei", comuna: "Nicolae Balcescu" },
  { nume: "Paicu", comuna: "Nicolae Balcescu" },
  { nume: "Marculesti-Gara", comuna: "Perisoru" },
  { nume: "Tudor Vladimirescu", comuna: "Perisoru" },
  { nume: "Cucuieti", comuna: "Plataresti" },
  { nume: "Dorobantu", comuna: "Plataresti" },
  { nume: "Podu Pitarului", comuna: "Plataresti" },
  { nume: "Valea Popii", comuna: "Radovanu" },
  { nume: "Magureni", comuna: "Sarulesti" },
  { nume: "Polcesti", comuna: "Sarulesti" },
  { nume: "Solacolu", comuna: "Sarulesti" },
  { nume: "Sandulita", comuna: "Sarulesti" },
  { nume: "Sarulesti-Gara", comuna: "Sarulesti" },
  { nume: "Satucu", comuna: "Sarulesti" },
  { nume: "Progresu", comuna: "Sohatu" },
  { nume: "Negoesti", comuna: "Soldanu" },
  { nume: "Cetatea Veche", comuna: "Spantov" },
  { nume: "Stancea", comuna: "Spantov" },
  { nume: "Calareti", comuna: "Tamadau Mare" },
  { nume: "Darvari", comuna: "Tamadau Mare" },
  { nume: "Plumbuita", comuna: "Tamadau Mare" },
  { nume: "Sacele", comuna: "Tamadau Mare" },
  { nume: "Tamadau Mic", comuna: "Tamadau Mare" },
  { nume: "Seinoiu", comuna: "Tamadau Mare" },
  { nume: "Chirnogi", comuna: "Ulmu" },
  { nume: "Faurei", comuna: "Ulmu" },
  { nume: "Zimbru", comuna: "Ulmu" },
  { nume: "Oltina", comuna: "Unirea" },
  { nume: "Floroaica", comuna: "Valcelele" },
  { nume: "Lunca", comuna: "Valea Argovei" },
  { nume: "Ostrovu", comuna: "Valea Argovei" },
  { nume: "Silistea", comuna: "Valea Argovei" },
  { nume: "Vladiceasca", comuna: "Valea Argovei" },
  { nume: "Galbinasi", comuna: "Vasilati" },
  { nume: "Nuci", comuna: "Vasilati" },
  { nume: "Popesti", comuna: "Vasilati" },
  { nume: "Mihai Viteazu", comuna: "Vlad Tepes" },
];
