export const cs = [
  { nume: "Anina" },
  { nume: "Armenis" },
  { nume: "Berliste" },
  { nume: "Berzasca" },
  { nume: "Berzovia" },
  { nume: "Bocsa" },
  { nume: "Bolvasnita" },
  { nume: "Bozovici" },
  { nume: "Brebu" },
  { nume: "Brebu Nou" },
  { nume: "Buchin" },
  { nume: "Bucosnita" },
  { nume: "Baile Herculane" },
  { nume: "Bania" },
  { nume: "Bautar" },
  { nume: "Caransebes" },
  { nume: "Carasova" },
  { nume: "Ciclova Romana" },
  { nume: "Ciuchici" },
  { nume: "Ciudanovita" },
  { nume: "Copacele" },
  { nume: "Cornea" },
  { nume: "Cornereva" },
  { nume: "Coronini" },
  { nume: "Carbunari" },
  { nume: "Dalboset" },
  { nume: "Doclin" },
  { nume: "Dognecea" },
  { nume: "Domasnea" },
  { nume: "Eftimie Murgu" },
  { nume: "Ezeris" },
  { nume: "Forotic" },
  { nume: "Farliug" },
  { nume: "Glimboca" },
  { nume: "Goruia" },
  { nume: "Gradinari" },
  { nume: "Garnic" },
  { nume: "Iablanita" },
  { nume: "Luncavita" },
  { nume: "Lupac" },
  { nume: "Lapusnicel" },
  { nume: "Lapusnicu Mare" },
  { nume: "Marga" },
  { nume: "Mehadia" },
  { nume: "Mehadica" },
  { nume: "Moldova Noua" },
  { nume: "Maureni" },
  { nume: "Naidas" },
  { nume: "Obreja" },
  { nume: "Ocna de Fier" },
  { nume: "Oravita" },
  { nume: "Otelu Rosu" },
  { nume: "Pojejena" },
  { nume: "Prigor" },
  { nume: "Paltinis" },
  { nume: "Ramna" },
  { nume: "Resita" },
  { nume: "Rusca Montana" },
  { nume: "Racasdia" },
  { nume: "Sacu" },
  { nume: "Sasca Montana" },
  { nume: "Sichevita" },
  { nume: "Slatina-Timis" },
  { nume: "Socol" },
  { nume: "Teregova" },
  { nume: "Ticvaniu Mare" },
  { nume: "Toplet" },
  { nume: "Turnu Ruieni" },
  { nume: "Tarnova" },
  { nume: "Vermes" },
  { nume: "Vrani" },
  { nume: "Valiug" },
  { nume: "Varadia" },
  { nume: "Zorlentu Mare" },
  { nume: "Zavoi" },
  { nume: "Sopotu Nou" },
  { nume: "Steierdorf", comuna: "Anina" },
  { nume: "Fenes", comuna: "Armenis" },
  { nume: "Plopu", comuna: "Armenis" },
  { nume: "Sat Batran", comuna: "Armenis" },
  { nume: "Sub Margine", comuna: "Armenis" },
  { nume: "Pecinisca", comuna: "Baile Herculane" },
  { nume: "Garbovat", comuna: "Bania" },
  { nume: "Bucova", comuna: "Bautar" },
  { nume: "Cornisoru", comuna: "Bautar" },
  { nume: "Preveciori", comuna: "Bautar" },
  { nume: "Iam", comuna: "Berliste" },
  { nume: "Milcoveni", comuna: "Berliste" },
  { nume: "Rusova Noua", comuna: "Berliste" },
  { nume: "Rusova Veche", comuna: "Berliste" },
  { nume: "Bigar", comuna: "Berzasca" },
  { nume: "Cozla", comuna: "Berzasca" },
  { nume: "Drencova", comuna: "Berzasca" },
  { nume: "Liubcova", comuna: "Berzasca" },
  { nume: "Fizes", comuna: "Berzovia" },
  { nume: "Ghertenis", comuna: "Berzovia" },
  { nume: "Varciorova", comuna: "Bolvasnita" },
  { nume: "Poneasca", comuna: "Bozovici" },
  { nume: "Prilipet", comuna: "Bozovici" },
  { nume: "Valea Minisului", comuna: "Bozovici" },
  { nume: "Apadia", comuna: "Brebu" },
  { nume: "Valeadeni", comuna: "Brebu" },
  { nume: "Garana", comuna: "Brebu Nou" },
  { nume: "Lindenfeld", comuna: "Buchin" },
  { nume: "Poiana", comuna: "Buchin" },
  { nume: "Prisian", comuna: "Buchin" },
  { nume: "Valea Timisului", comuna: "Buchin" },
  { nume: "Golet", comuna: "Bucosnita" },
  { nume: "Petrosnita", comuna: "Bucosnita" },
  { nume: "Valisoara", comuna: "Bucosnita" },
  { nume: "Jupa", comuna: "Caransebes" },
  { nume: "Iabalcea", comuna: "Carasova" },
  { nume: "Nermed", comuna: "Carasova" },
  { nume: "Stinapari", comuna: "Carbunari" },
  { nume: "Ilidia", comuna: "Ciclova Romana" },
  { nume: "Socolari", comuna: "Ciclova Romana" },
  { nume: "Macoviste", comuna: "Ciuchici" },
  { nume: "Nicolint", comuna: "Ciuchici" },
  { nume: "Petrilova", comuna: "Ciuchici" },
  { nume: "Jitin", comuna: "Ciudanovita" },
  { nume: "Cavaran", comuna: "Constantin Daicoviciu" },
  { nume: "Maciova", comuna: "Constantin Daicoviciu" },
  { nume: "Matnicu Mare", comuna: "Constantin Daicoviciu" },
  { nume: "Pestere", comuna: "Constantin Daicoviciu" },
  { nume: "Prisaca", comuna: "Constantin Daicoviciu" },
  { nume: "Zagujeni", comuna: "Constantin Daicoviciu" },
  { nume: "Ohaba-Matnic", comuna: "Copacele" },
  { nume: "Ruginosu", comuna: "Copacele" },
  { nume: "Zorile", comuna: "Copacele" },
  { nume: "Crusovat", comuna: "Cornea" },
  { nume: "Cuptoare", comuna: "Cornea" },
  { nume: "Macoviste", comuna: "Cornea" },
  { nume: "Arsuri", comuna: "Cornereva" },
  { nume: "Bogaltin", comuna: "Cornereva" },
  { nume: "Bojia", comuna: "Cornereva" },
  { nume: "Borugi", comuna: "Cornereva" },
  { nume: "Camena", comuna: "Cornereva" },
  { nume: "Ciresel", comuna: "Cornereva" },
  { nume: "Costis", comuna: "Cornereva" },
  { nume: "Cozia", comuna: "Cornereva" },
  { nume: "Cracu Mare", comuna: "Cornereva" },
  { nume: "Cracu Teiului", comuna: "Cornereva" },
  { nume: "Dobraia", comuna: "Cornereva" },
  { nume: "Dolina", comuna: "Cornereva" },
  { nume: "Gruni", comuna: "Cornereva" },
  { nume: "Hora Mare", comuna: "Cornereva" },
  { nume: "Hora Mica", comuna: "Cornereva" },
  { nume: "Inelet", comuna: "Cornereva" },
  { nume: "Izvor", comuna: "Cornereva" },
  { nume: "Lunca Florii", comuna: "Cornereva" },
  { nume: "Lunca Zaicii", comuna: "Cornereva" },
  { nume: "Mesteacan", comuna: "Cornereva" },
  { nume: "Negiudin", comuna: "Cornereva" },
  { nume: "Obita", comuna: "Cornereva" },
  { nume: "Pogara", comuna: "Cornereva" },
  { nume: "Pogara de Sus", comuna: "Cornereva" },
  { nume: "Poiana Lunga", comuna: "Cornereva" },
  { nume: "Prisacina", comuna: "Cornereva" },
  { nume: "Prislop", comuna: "Cornereva" },
  { nume: "Rustin", comuna: "Cornereva" },
  { nume: "Scarisoara", comuna: "Cornereva" },
  { nume: "Strugasca", comuna: "Cornereva" },
  { nume: "Studena", comuna: "Cornereva" },
  { nume: "Sub Crang", comuna: "Cornereva" },
  { nume: "Sub Plai", comuna: "Cornereva" },
  { nume: "Topla", comuna: "Cornereva" },
  { nume: "Zbegu", comuna: "Cornereva" },
  { nume: "Zmogotin", comuna: "Cornereva" },
  { nume: "Zoina", comuna: "Cornereva" },
  { nume: "Zanogi", comuna: "Cornereva" },
  { nume: "Tatu", comuna: "Cornereva" },
  { nume: "Sfanta Elena", comuna: "Coronini" },
  { nume: "Boina", comuna: "Dalboset" },
  { nume: "Boinita", comuna: "Dalboset" },
  { nume: "Barz", comuna: "Dalboset" },
  { nume: "Prislop", comuna: "Dalboset" },
  { nume: "Resita Mica", comuna: "Dalboset" },
  { nume: "Sopotu Vechi", comuna: "Dalboset" },
  { nume: "Binis", comuna: "Doclin" },
  { nume: "Tirol", comuna: "Doclin" },
  { nume: "Calina", comuna: "Dognecea" },
  { nume: "Canicea", comuna: "Domasnea" },
  { nume: "Soceni", comuna: "Ezeris" },
  { nume: "Dezesti", comuna: "Farliug" },
  { nume: "Duleu", comuna: "Farliug" },
  { nume: "Remetea-Poganici", comuna: "Farliug" },
  { nume: "Scaius", comuna: "Farliug" },
  { nume: "Valea Mare", comuna: "Farliug" },
  { nume: "Brezon", comuna: "Forotic" },
  { nume: "Comoraste", comuna: "Forotic" },
  { nume: "Surducu Mare", comuna: "Forotic" },
  { nume: "Padina Matei", comuna: "Garnic" },
  { nume: "Giurgiova", comuna: "Goruia" },
  { nume: "Garliste", comuna: "Goruia" },
  { nume: "Greoni", comuna: "Gradinari" },
  { nume: "Globu Craiovei", comuna: "Iablanita" },
  { nume: "Petnic", comuna: "Iablanita" },
  { nume: "Parvova", comuna: "Lapusnicel" },
  { nume: "Sumita", comuna: "Lapusnicel" },
  { nume: "Moceris", comuna: "Lapusnicu Mare" },
  { nume: "Verendin", comuna: "Luncavita" },
  { nume: "Clocotici", comuna: "Lupac" },
  { nume: "Rafnic", comuna: "Lupac" },
  { nume: "Vodnic", comuna: "Lupac" },
  { nume: "Vama Marga", comuna: "Marga" },
  { nume: "Sosdea", comuna: "Maureni" },
  { nume: "Globurau", comuna: "Mehadia" },
  { nume: "Plugova", comuna: "Mehadia" },
  { nume: "Valea Bolvasnita", comuna: "Mehadia" },
  { nume: "Moldova Veche", comuna: "Moldova Noua" },
  { nume: "Moldovita", comuna: "Moldova Noua" },
  { nume: "Macesti", comuna: "Moldova Noua" },
  { nume: "Lescovita", comuna: "Naidas" },
  { nume: "Ciuta", comuna: "Obreja" },
  { nume: "Iaz", comuna: "Obreja" },
  { nume: "Var", comuna: "Obreja" },
  { nume: "Agadici", comuna: "Oravita" },
  { nume: "Brosteni", comuna: "Oravita" },
  { nume: "Bradisoru de Jos", comuna: "Oravita" },
  { nume: "Ciclova Montana", comuna: "Oravita" },
  { nume: "Marila", comuna: "Oravita" },
  { nume: "Rachitova", comuna: "Oravita" },
  { nume: "Ciresa", comuna: "Otelu Rosu" },
  { nume: "Mal", comuna: "Otelu Rosu" },
  { nume: "Cornutel", comuna: "Paltinis" },
  { nume: "Delinesti", comuna: "Paltinis" },
  { nume: "Ohabita", comuna: "Paltinis" },
  { nume: "Rugi", comuna: "Paltinis" },
  { nume: "Belobresca", comuna: "Pojejena" },
  { nume: "Divici", comuna: "Pojejena" },
  { nume: "Radimna", comuna: "Pojejena" },
  { nume: "Susca", comuna: "Pojejena" },
  { nume: "Borlovenii Noi", comuna: "Prigor" },
  { nume: "Borlovenii Vechi", comuna: "Prigor" },
  { nume: "Putna", comuna: "Prigor" },
  { nume: "Patas", comuna: "Prigor" },
  { nume: "Vraniut", comuna: "Racasdia" },
  { nume: "Barbosu", comuna: "Ramna" },
  { nume: "Valeapai", comuna: "Ramna" },
  { nume: "Cuptoare", comuna: "Resita" },
  { nume: "Calnic", comuna: "Resita" },
  { nume: "Doman", comuna: "Resita" },
  { nume: "Moniom", comuna: "Resita" },
  { nume: "Secu", comuna: "Resita" },
  { nume: "Terova", comuna: "Resita" },
  { nume: "Ruschita", comuna: "Rusca Montana" },
  { nume: "Salbagelu Nou", comuna: "Sacu" },
  { nume: "Tincova", comuna: "Sacu" },
  { nume: "Bogodint", comuna: "Sasca Montana" },
  { nume: "Potoc", comuna: "Sasca Montana" },
  { nume: "Sasca Romana", comuna: "Sasca Montana" },
  { nume: "Slatina-Nera", comuna: "Sasca Montana" },
  { nume: "Brestelnic", comuna: "Sichevita" },
  { nume: "Camenita", comuna: "Sichevita" },
  { nume: "Cracu Almaj", comuna: "Sichevita" },
  { nume: "Crusovita", comuna: "Sichevita" },
  { nume: "Curmatura", comuna: "Sichevita" },
  { nume: "Carsie", comuna: "Sichevita" },
  { nume: "Frasinis", comuna: "Sichevita" },
  { nume: "Gornea", comuna: "Sichevita" },
  { nume: "Liborajdea", comuna: "Sichevita" },
  { nume: "Lucacevat", comuna: "Sichevita" },
  { nume: "Martinovat", comuna: "Sichevita" },
  { nume: "Ogasu Podului", comuna: "Sichevita" },
  { nume: "Streneac", comuna: "Sichevita" },
  { nume: "Valea Orevita", comuna: "Sichevita" },
  { nume: "Valea Ravensca", comuna: "Sichevita" },
  { nume: "Valea Sichevitei", comuna: "Sichevita" },
  { nume: "Zanou", comuna: "Sichevita" },
  { nume: "Zasloane", comuna: "Sichevita" },
  { nume: "Ilova", comuna: "Slatina-Timis" },
  { nume: "Sadova Noua", comuna: "Slatina-Timis" },
  { nume: "Sadova Veche", comuna: "Slatina-Timis" },
  { nume: "Bazias", comuna: "Socol" },
  { nume: "Campia", comuna: "Socol" },
  { nume: "Parneaura", comuna: "Socol" },
  { nume: "Zlatita", comuna: "Socol" },
  { nume: "Carsa Rosie", comuna: "Sopotu Nou" },
  { nume: "Dristie", comuna: "Sopotu Nou" },
  { nume: "Poienile Boinei", comuna: "Sopotu Nou" },
  { nume: "Ravensca", comuna: "Sopotu Nou" },
  { nume: "Rachita", comuna: "Sopotu Nou" },
  { nume: "Stancilova", comuna: "Sopotu Nou" },
  { nume: "Urcu", comuna: "Sopotu Nou" },
  { nume: "Valea Rosie", comuna: "Sopotu Nou" },
  { nume: "Valea Rachitei", comuna: "Sopotu Nou" },
  { nume: "Bratova", comuna: "Tarnova" },
  { nume: "Rusca", comuna: "Teregova" },
  { nume: "Carnecea", comuna: "Ticvaniu Mare" },
  { nume: "Secaseni", comuna: "Ticvaniu Mare" },
  { nume: "Ticvaniu Mic", comuna: "Ticvaniu Mare" },
  { nume: "Barza", comuna: "Toplet" },
  { nume: "Borlova", comuna: "Turnu Ruieni" },
  { nume: "Cicleni", comuna: "Turnu Ruieni" },
  { nume: "Dalci", comuna: "Turnu Ruieni" },
  { nume: "Zervesti", comuna: "Turnu Ruieni" },
  { nume: "Zlagna", comuna: "Turnu Ruieni" },
  { nume: "Mercina", comuna: "Varadia" },
  { nume: "Ersig", comuna: "Vermes" },
  { nume: "Izgar", comuna: "Vermes" },
  { nume: "Ciortea", comuna: "Vrani" },
  { nume: "Iertof", comuna: "Vrani" },
  { nume: "23 August", comuna: "Zavoi" },
  { nume: "Magura", comuna: "Zavoi" },
  { nume: "Maru", comuna: "Zavoi" },
  { nume: "Poiana Marului", comuna: "Zavoi" },
  { nume: "Valea Bistrei", comuna: "Zavoi" },
  { nume: "Voislova", comuna: "Zavoi" },
  { nume: "Zorlencior", comuna: "Zorlentu Mare" },
];
