export const cl = [
  { nume: "Alexandru I. Cuza", comuna: "Fundulea" },
  { nume: "Alexandru Odobescu" },
  { nume: "Aprozi", comuna: "Budesti" },
  { nume: "Arțari", simplu: "Artari", comuna: "Ileana" },
  { nume: "Belciugatele" },
  { nume: "Bogata", comuna: "Gradistea" },
  { nume: "Bogdana", comuna: "Dragos Voda" },
  { nume: "Borcea" },
  { nume: "Boșneagu", simplu: "Bosneagu", comuna: "Dorobantu" },
  { nume: "Buciumeni", comuna: "Budesti" },
  { nume: "Budești", simplu: "Budesti" },
  { nume: "Buzoeni", comuna: "Lehliu Gara" },
  { nume: "Călărași", simplu: "Calarasi" },
  { nume: "Călărașii Vechi", simplu: "Calarasii Vechi", comuna: "Cuza Voda" },
  { nume: "Călăreți", simplu: "Calareti", comuna: "Tamadau Mare" },
  { nume: "Cândeasca", simplu: "Candeasca", comuna: "Belciugatele" },
  { nume: "Căscioarele", simplu: "Cascioarele" },
  { nume: "Ceacu", comuna: "Cuza Voda" },
  { nume: "Cetatea Veche", comuna: "Spantov" },
  { nume: "Chirnogi" },
  { nume: "Chirnogi", comuna: "Ulmu" },
  { nume: "Chiselet" },
  { nume: "Ciocănești", simplu: "Ciocanesti" },
  { nume: "Clătești", simplu: "Clatesti", comuna: "Mitreni" },
  { nume: "Coconi", comuna: "Manastirea" },
  { nume: "Codreni", comuna: "Gurbanesti" },
  { nume: "Cojești", simplu: "Cojesti", comuna: "Belciugatele" },
  {
    nume: "Constantin Brâncoveanu",
    simplu: "Constantin Brancoveanu",
    comuna: "Dragalina",
  },
  { nume: "Coslogeni", comuna: "Dichiseni" },
  { nume: "Coțofanca", simplu: "Cotofanca", comuna: "Gurbanesti" },
  { nume: "Crivăț", simplu: "Crivat", comuna: "Budesti" },
  { nume: "Cucuieți", simplu: "Cucuieti", comuna: "Plataresti" },
  { nume: "Cunești", simplu: "Cunesti", comuna: "Gradistea" },
  { nume: "Curătești", simplu: "Curatesti", comuna: "Frasinet" },
  { nume: "Curcani" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda" },
  { nume: "Dâlga-Gară", simplu: "Dalga-Gara", comuna: "Dor Marunt" },
  { nume: "Dâlga", simplu: "Dalga", comuna: "Dor Marunt" },
  { nume: "Dănești", simplu: "Danesti", comuna: "Frasinet" },
  { nume: "Dârvari", simplu: "Darvari", comuna: "Tamadau Mare" },
  { nume: "Dichiseni" },
  { nume: "Dor Mărunt", simplu: "Dor Marunt" },
  { nume: "Dorobanțu", simplu: "Dorobantu" },
  { nume: "Dorobanțu", simplu: "Dorobantu", comuna: "Plataresti" },
  { nume: "Dragalina" },
  { nume: "Dragoș Vodă", simplu: "Dragos Voda" },
  { nume: "Drajna Nouă", simplu: "Drajna Noua", comuna: "Dragalina" },
  {
    nume: "Fântâna Doamnei",
    simplu: "Fantana Doamnei",
    comuna: "Nicolae Balcescu",
  },
  { nume: "Făurei", simplu: "Faurei", comuna: "Ulmu" },
  { nume: "Florica", comuna: "Ileana" },
  { nume: "Floroaica", comuna: "Valcelele" },
  { nume: "Frăsinet", simplu: "Frasinet" },
  { nume: "Frăsinetu de Jos", simplu: "Frasinetu de Jos", comuna: "Frasinet" },
  { nume: "Frumușani", simplu: "Frumusani" },
  { nume: "Fundeni" },
  { nume: "Fundulea" },
  { nume: "Gălățui", simplu: "Galatui", comuna: "Alexandru Odobescu" },
  { nume: "Gălbinași", simplu: "Galbinasi", comuna: "Vasilati" },
  { nume: "Gâldău", simplu: "Galdau", comuna: "Jegalia" },
  { nume: "Gostilele", comuna: "Fundulea" },
  { nume: "Grădiștea", simplu: "Gradistea" },
  { nume: "Gruiu", comuna: "Budesti" },
  { nume: "Gurbănești", simplu: "Gurbanesti" },
  { nume: "Iezeru", comuna: "Jegalia" },
  { nume: "Ileana" },
  { nume: "Independența", simplu: "Independenta" },
  { nume: "Înfrățirea", simplu: "Infratirea", comuna: "Dor Marunt" },
  { nume: "Jegălia", simplu: "Jegalia" },
  { nume: "Lehliu-Gară", simplu: "Lehliu-Gara", comuna: "Lehliu Gara" },
  { nume: "Lehliu" },
  { nume: "Libertatea", comuna: "Dichiseni" },
  { nume: "Luica" },
  { nume: "Lunca", comuna: "Valea Argovei" },
  { nume: "Lupșanu", simplu: "Lupsanu" },
  { nume: "Luptători", simplu: "Luptatori", comuna: "Frasinet" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Sarulesti" },
  { nume: "Mânăstirea", simplu: "Manastirea" },
  { nume: "Mărculești-Gară", simplu: "Marculesti-Gara", comuna: "Perisoru" },
  { nume: "Măriuța", simplu: "Mariuta", comuna: "Belciugatele" },
  { nume: "Mataraua", comuna: "Belciugatele" },
  { nume: "Mihai Viteazu", comuna: "Vlad Tepes" },
  { nume: "Mitreni" },
  { nume: "Modelu" },
  { nume: "Nana" },
  { nume: "Negoești", simplu: "Negoesti", comuna: "Soldanu" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu" },
  {
    nume: "Nicolae Bălcescu",
    simplu: "Nicolae Balcescu",
    comuna: "Alexandru Odobescu",
  },
  { nume: "Nucetu", comuna: "Lupsanu" },
  { nume: "Nuci", comuna: "Vasilati" },
  { nume: "Ogoru", comuna: "Dor Marunt" },
  { nume: "Oltenița", simplu: "Oltenita" },
  { nume: "Oltina", comuna: "Unirea" },
  { nume: "Orăști", simplu: "Orasti", comuna: "Frumusani" },
  { nume: "Ostrovu", comuna: "Valea Argovei" },
  { nume: "Pădurișu", simplu: "Padurisu", comuna: "Frumusani" },
  { nume: "Paicu", comuna: "Nicolae Balcescu" },
  { nume: "Pasărea", simplu: "Pasarea", comuna: "Frumusani" },
  { nume: "Pelinu", comuna: "Dor Marunt" },
  { nume: "Perișoru", simplu: "Perisoru" },
  { nume: "Pițigaia", simplu: "Pitigaia", comuna: "Frumusani" },
  { nume: "Plătărești", simplu: "Plataresti" },
  { nume: "Plevna", comuna: "Lupsanu" },
  { nume: "Plumbuita", comuna: "Tamadau Mare" },
  { nume: "Podari", comuna: "Ileana" },
  { nume: "Podu Pitarului", comuna: "Plataresti" },
  { nume: "Polcești", simplu: "Polcesti", comuna: "Sarulesti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Vasilati" },
  { nume: "Postăvari", simplu: "Postavari", comuna: "Frumusani" },
  { nume: "Potcoava", comuna: "Independenta" },
  { nume: "Preasna Veche", comuna: "Gurbanesti" },
  { nume: "Preasna", comuna: "Gurbanesti" },
  { nume: "Progresu", comuna: "Sohatu" },
  { nume: "Radovanu" },
  { nume: "Radu Negru", comuna: "Modelu" },
  { nume: "Radu Vodă", simplu: "Radu Voda", comuna: "Lupsanu" },
  { nume: "Rasa", comuna: "Gradistea" },
  { nume: "Răsurile", simplu: "Rasurile", comuna: "Ileana" },
  { nume: "Răzoarele", simplu: "Razoarele", comuna: "Ileana" },
  { nume: "Răzvani", simplu: "Razvani", comuna: "Lehliu Gara" },
  { nume: "Roseți", simplu: "Roseti" },
  { nume: "Săcele", simplu: "Sacele", comuna: "Tamadau Mare" },
  { nume: "Sălcioara", simplu: "Salcioara", comuna: "Curcani" },
  { nume: "Săndulița", simplu: "Sandulita", comuna: "Sarulesti" },
  { nume: "Săpunari", simplu: "Sapunari", comuna: "Lehliu" },
  { nume: "Sărulești-Gară", simplu: "Sarulesti-Gara", comuna: "Sarulesti" },
  { nume: "Sărulești", simplu: "Sarulesti" },
  { nume: "Satnoeni", comuna: "Dichiseni" },
  { nume: "Satu Nou", comuna: "Ileana" },
  { nume: "Sătucu", simplu: "Satucu", comuna: "Sarulesti" },
  { nume: "Șeinoiu", simplu: "Seinoiu", comuna: "Tamadau Mare" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Valea Argovei" },
  { nume: "Socoalele", comuna: "Dragos Voda" },
  { nume: "Sohatu" },
  { nume: "Solacolu", comuna: "Sarulesti" },
  { nume: "Șoldanu", simplu: "Soldanu" },
  { nume: "Spanțov", simplu: "Spantov" },
  { nume: "Stancea", comuna: "Spantov" },
  { nume: "Ștefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Ștefan Vodă", simplu: "Stefan Voda" },
  { nume: "Ștefănești", simplu: "Stefanesti", comuna: "Ileana" },
  { nume: "Stoenești", simplu: "Stoenesti", comuna: "Modelu" },
  { nume: "Sultana", comuna: "Manastirea" },
  { nume: "Tămădău Mare", simplu: "Tamadau Mare" },
  { nume: "Tămădău Mic", simplu: "Tamadau Mic", comuna: "Tamadau Mare" },
  { nume: "Tăriceni", simplu: "Tariceni", comuna: "Frasinet" },
  { nume: "Tonea", comuna: "Modelu" },
  { nume: "Tudor Vladimirescu", comuna: "Perisoru" },
  { nume: "Ulmeni" },
  { nume: "Ulmu" },
  { nume: "Unirea" },
  { nume: "Vâlcelele", simplu: "Valcelele" },
  { nume: "Valea Argovei" },
  { nume: "Valea Popii", comuna: "Radovanu" },
  { nume: "Valea Presnei", comuna: "Gurbanesti" },
  { nume: "Valea Roșie", simplu: "Valea Rosie", comuna: "Mitreni" },
  { nume: "Valea Rusului", comuna: "Lupsanu" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Lehliu Gara" },
  { nume: "Valea Stânii", simplu: "Valea Stanii", comuna: "Luica" },
  { nume: "Vărăști", simplu: "Varasti", comuna: "Dorobantu" },
  { nume: "Vasilați", simplu: "Vasilati" },
  { nume: "Vișinii", simplu: "Visinii", comuna: "Independenta" },
  { nume: "Vlad Țepeș", simplu: "Vlad Tepes" },
  { nume: "Vlădiceasca", simplu: "Vladiceasca", comuna: "Valea Argovei" },
  { nume: "Vlăiculești", simplu: "Vlaiculesti", comuna: "Ileana" },
  { nume: "Zimbru", comuna: "Ulmu" },
];
