export const cv = [
  { nume: "Aita Mare" },
  { nume: "Baraolt" },
  { nume: "Barcani" },
  { nume: "Belin" },
  { nume: "Bodoc" },
  { nume: "Borosneu Mare" },
  { nume: "Brates" },
  { nume: "Bretcu" },
  { nume: "Bradut" },
  { nume: "Catalina" },
  { nume: "Cernat" },
  { nume: "Chichis" },
  { nume: "Comandau" },
  { nume: "Covasna" },
  { nume: "Dobarlau" },
  { nume: "Ghelinta" },
  { nume: "Ghidfalau" },
  { nume: "Haghig" },
  { nume: "Ilieni" },
  { nume: "Lemnia" },
  { nume: "Malnas" },
  { nume: "Moacsa" },
  { nume: "Ojdula" },
  { nume: "Ozun" },
  { nume: "Poian" },
  { nume: "Reci" },
  { nume: "Sita Buzaului" },
  { nume: "Sanzieni" },
  { nume: "Turia" },
  { nume: "Valea Crisului" },
  { nume: "Valea Mare" },
  { nume: "Valcele" },
  { nume: "Varghis" },
  { nume: "Zagon" },
  { nume: "Zabala" },
  { nume: "Intorsura Buzaului" },
  { nume: "Aita Medie", comuna: "Aita Mare" },
  { nume: "Biborteni", comuna: "Baraolt" },
  { nume: "Bodos", comuna: "Baraolt" },
  { nume: "Capeni", comuna: "Baraolt" },
  { nume: "Miclosoara", comuna: "Baraolt" },
  { nume: "Racosul de Sus", comuna: "Baraolt" },
  { nume: "Ladauti", comuna: "Barcani" },
  { nume: "Saramas", comuna: "Barcani" },
  { nume: "Aita Seaca", comuna: "Batani" },
  { nume: "Batanii Mari", comuna: "Batani" },
  { nume: "Batanii Mici", comuna: "Batani" },
  { nume: "Herculian", comuna: "Batani" },
  { nume: "Ozunca-Bai", comuna: "Batani" },
  { nume: "Belin-Vale", comuna: "Belin" },
  { nume: "Olteni", comuna: "Bodoc" },
  { nume: "Zalan", comuna: "Bodoc" },
  { nume: "Borosneu Mic", comuna: "Borosneu Mare" },
  { nume: "Dobolii de Sus", comuna: "Borosneu Mare" },
  { nume: "Let", comuna: "Borosneu Mare" },
  { nume: "Valea Mica", comuna: "Borosneu Mare" },
  { nume: "Tufalau", comuna: "Borosneu Mare" },
  { nume: "Doboseni", comuna: "Bradut" },
  { nume: "Filia", comuna: "Bradut" },
  { nume: "Talisoara", comuna: "Bradut" },
  { nume: "Pachia", comuna: "Brates" },
  { nume: "Telechia", comuna: "Brates" },
  { nume: "Martanus", comuna: "Bretcu" },
  { nume: "Oituz", comuna: "Bretcu" },
  { nume: "Hatuica", comuna: "Catalina" },
  { nume: "Imeni", comuna: "Catalina" },
  { nume: "Marcusa", comuna: "Catalina" },
  { nume: "Martineni", comuna: "Catalina" },
  { nume: "Albis", comuna: "Cernat" },
  { nume: "Icafalau", comuna: "Cernat" },
  { nume: "Bacel", comuna: "Chichis" },
  { nume: "Chiurus", comuna: "Covasna" },
  { nume: "Lunca Marcusului", comuna: "Dobarlau" },
  { nume: "Marcus", comuna: "Dobarlau" },
  { nume: "Valea Dobarlaului", comuna: "Dobarlau" },
  { nume: "Harale", comuna: "Ghelinta" },
  { nume: "Anghelus", comuna: "Ghidfalau" },
  { nume: "Fotos", comuna: "Ghidfalau" },
  { nume: "Zoltan", comuna: "Ghidfalau" },
  { nume: "Iaras", comuna: "Haghig" },
  { nume: "Dobolii de Jos", comuna: "Ilieni" },
  { nume: "Sancraiu", comuna: "Ilieni" },
  { nume: "Bradet", comuna: "Intorsura Buzaului" },
  { nume: "Floroaia", comuna: "Intorsura Buzaului" },
  { nume: "Scradoasa", comuna: "Intorsura Buzaului" },
  { nume: "Lutoasa", comuna: "Lemnia" },
  { nume: "Mereni", comuna: "Lemnia" },
  { nume: "Bixad", comuna: "Malnas" },
  { nume: "Malnas-Bai", comuna: "Malnas" },
  { nume: "Micfalau", comuna: "Malnas" },
  { nume: "Valea Zalanului", comuna: "Malnas" },
  { nume: "Dalnic", comuna: "Moacsa" },
  { nume: "Padureni", comuna: "Moacsa" },
  { nume: "Hilib", comuna: "Ojdula" },
  { nume: "Bicfalau", comuna: "Ozun" },
  { nume: "Lisnau", comuna: "Ozun" },
  { nume: "Lisnau-Vale", comuna: "Ozun" },
  { nume: "Lunca Ozunului", comuna: "Ozun" },
  { nume: "Magherus", comuna: "Ozun" },
  { nume: "Santionlunca", comuna: "Ozun" },
  { nume: "Belani", comuna: "Poian" },
  { nume: "Carpinenii", comuna: "Poian" },
  { nume: "Estelnic", comuna: "Poian" },
  { nume: "Valea Scurta", comuna: "Poian" },
  { nume: "Aninoasa", comuna: "Reci" },
  { nume: "Bita", comuna: "Reci" },
  { nume: "Saciova", comuna: "Reci" },
  { nume: "Casinu Mic", comuna: "Sanzieni" },
  { nume: "Petriceni", comuna: "Sanzieni" },
  { nume: "Valea Seaca", comuna: "Sanzieni" },
  { nume: "Chilieni", comuna: "Sfantul Gheorghe" },
  { nume: "Coseni", comuna: "Sfantul Gheorghe" },
  { nume: "Sfantu  Gheorghe", comuna: "Sfantul Gheorghe" },
  { nume: "Crasna", comuna: "Sita Buzaului" },
  { nume: "Merisor", comuna: "Sita Buzaului" },
  { nume: "Zabratau", comuna: "Sita Buzaului" },
  { nume: "Lunga", comuna: "Tirgu Secuiesc" },
  { nume: "Targu Secuiesc", comuna: "Tirgu Secuiesc" },
  { nume: "Alungeni", comuna: "Turia" },
  { nume: "Araci", comuna: "Valcele" },
  { nume: "Ariusd", comuna: "Valcele" },
  { nume: "Hetea", comuna: "Valcele" },
  { nume: "Arcus", comuna: "Valea Crisului" },
  { nume: "Calnic", comuna: "Valea Crisului" },
  { nume: "Peteni", comuna: "Zabala" },
  { nume: "Surcea", comuna: "Zabala" },
  { nume: "Tamasfalau", comuna: "Zabala" },
  { nume: "Papauti", comuna: "Zagon" },
];
