export const cv = [
  { nume: "Aita Mare" },
  { nume: "Aita Medie", comuna: "Aita Mare" },
  { nume: "Aita Seacă", simplu: "Aita Seaca", comuna: "Batani" },
  { nume: "Albiș", simplu: "Albis", comuna: "Cernat" },
  { nume: "Alungeni", comuna: "Turia" },
  { nume: "Angheluș", simplu: "Anghelus", comuna: "Ghidfalau" },
  { nume: "Aninoasa", comuna: "Reci" },
  { nume: "Araci", comuna: "Valcele" },
  { nume: "Arcuș", simplu: "Arcus", comuna: "Valea Crisului" },
  { nume: "Ariușd", simplu: "Ariusd", comuna: "Valcele" },
  { nume: "Băcel", simplu: "Bacel", comuna: "Chichis" },
  { nume: "Baraolt" },
  { nume: "Barcani" },
  { nume: "Bățanii Mari", simplu: "Batanii Mari", comuna: "Batani" },
  { nume: "Bățanii Mici", simplu: "Batanii Mici", comuna: "Batani" },
  { nume: "Belani", comuna: "Poian" },
  { nume: "Belin-Vale", comuna: "Belin" },
  { nume: "Belin" },
  { nume: "Biborțeni", simplu: "Biborteni", comuna: "Baraolt" },
  { nume: "Bicfalău", simplu: "Bicfalau", comuna: "Ozun" },
  { nume: "Bita", comuna: "Reci" },
  { nume: "Bixad", comuna: "Malnas" },
  { nume: "Bodoc" },
  { nume: "Bodoș", simplu: "Bodos", comuna: "Baraolt" },
  { nume: "Boroșneu Mare", simplu: "Borosneu Mare" },
  { nume: "Boroșneu Mic", simplu: "Borosneu Mic", comuna: "Borosneu Mare" },
  { nume: "Brădet", simplu: "Bradet", comuna: "Intorsura Buzaului" },
  { nume: "Brăduț", simplu: "Bradut" },
  { nume: "Brateș", simplu: "Brates" },
  { nume: "Brețcu", simplu: "Bretcu" },
  { nume: "Calnic", comuna: "Valea Crisului" },
  { nume: "Căpeni", simplu: "Capeni", comuna: "Baraolt" },
  { nume: "Cărpinenii", simplu: "Carpinenii", comuna: "Poian" },
  { nume: "Cașinu Mic", simplu: "Casinu Mic", comuna: "Sanzieni" },
  { nume: "Catalina" },
  { nume: "Cernat" },
  { nume: "Chichiș", simplu: "Chichis" },
  { nume: "Chilieni", comuna: "Sfantul Gheorghe" },
  { nume: "Chiuruș", simplu: "Chiurus", comuna: "Covasna" },
  { nume: "Comandău", simplu: "Comandau" },
  { nume: "Coșeni", simplu: "Coseni", comuna: "Sfantul Gheorghe" },
  { nume: "Covasna" },
  { nume: "Crasna", comuna: "Sita Buzaului" },
  { nume: "Dalnic", comuna: "Moacsa" },
  { nume: "Dobârlău", simplu: "Dobarlau" },
  { nume: "Dobolii de Jos", comuna: "Ilieni" },
  { nume: "Dobolii de Sus", comuna: "Borosneu Mare" },
  { nume: "Doboșeni", simplu: "Doboseni", comuna: "Bradut" },
  { nume: "Estelnic", comuna: "Poian" },
  { nume: "Filia", comuna: "Bradut" },
  { nume: "Floroaia", comuna: "Intorsura Buzaului" },
  { nume: "Fotoș", simplu: "Fotos", comuna: "Ghidfalau" },
  { nume: "Ghelința", simplu: "Ghelinta" },
  { nume: "Ghidfalău", simplu: "Ghidfalau" },
  { nume: "Hăghig", simplu: "Haghig" },
  { nume: "Harale", comuna: "Ghelinta" },
  { nume: "Hătuica", simplu: "Hatuica", comuna: "Catalina" },
  { nume: "Herculian", comuna: "Batani" },
  { nume: "Hetea", comuna: "Valcele" },
  { nume: "Hilib", comuna: "Ojdula" },
  { nume: "Iarăș", simplu: "Iaras", comuna: "Haghig" },
  { nume: "Icafalău", simplu: "Icafalau", comuna: "Cernat" },
  { nume: "Ilieni" },
  { nume: "Imeni", comuna: "Catalina" },
  { nume: "Întorsura Buzăului", simplu: "Intorsura Buzaului" },
  { nume: "Lădăuți", simplu: "Ladauti", comuna: "Barcani" },
  { nume: "Lemnia" },
  { nume: "Leț", simplu: "Let", comuna: "Borosneu Mare" },
  { nume: "Lisnău-Vale", simplu: "Lisnau-Vale", comuna: "Ozun" },
  { nume: "Lisnău", simplu: "Lisnau", comuna: "Ozun" },
  { nume: "Lunca Mărcușului", simplu: "Lunca Marcusului", comuna: "Dobarlau" },
  { nume: "Lunca Ozunului", comuna: "Ozun" },
  { nume: "Lunga", comuna: "Tirgu Secuiesc" },
  { nume: "Lutoasa", comuna: "Lemnia" },
  { nume: "Măgheruș", simplu: "Magherus", comuna: "Ozun" },
  { nume: "Malnaș-Băi", simplu: "Malnas-Bai", comuna: "Malnas" },
  { nume: "Malnaș", simplu: "Malnas" },
  { nume: "Mărcuș", simplu: "Marcus", comuna: "Dobarlau" },
  { nume: "Mărcușa", simplu: "Marcusa", comuna: "Catalina" },
  { nume: "Mărtănuș", simplu: "Martanus", comuna: "Bretcu" },
  { nume: "Mărtineni", simplu: "Martineni", comuna: "Catalina" },
  { nume: "Mereni", comuna: "Lemnia" },
  { nume: "Merișor", simplu: "Merisor", comuna: "Sita Buzaului" },
  { nume: "Micfalău", simplu: "Micfalau", comuna: "Malnas" },
  { nume: "Micloșoara", simplu: "Miclosoara", comuna: "Baraolt" },
  { nume: "Moacșa", simplu: "Moacsa" },
  { nume: "Oituz", comuna: "Bretcu" },
  { nume: "Ojdula" },
  { nume: "Olteni", comuna: "Bodoc" },
  { nume: "Ozun" },
  { nume: "Ozunca-Băi", simplu: "Ozunca-Bai", comuna: "Batani" },
  { nume: "Pachia", comuna: "Brates" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Moacsa" },
  { nume: "Păpăuți", simplu: "Papauti", comuna: "Zagon" },
  { nume: "Peteni", comuna: "Zabala" },
  { nume: "Petriceni", comuna: "Sanzieni" },
  { nume: "Poian" },
  { nume: "Racoșul de Sus", simplu: "Racosul de Sus", comuna: "Baraolt" },
  { nume: "Reci" },
  { nume: "Saciova", comuna: "Reci" },
  { nume: "Sâncraiu", simplu: "Sancraiu", comuna: "Ilieni" },
  { nume: "Sântionlunca", simplu: "Santionlunca", comuna: "Ozun" },
  { nume: "Sânzieni", simplu: "Sanzieni" },
  { nume: "Sărămăș", simplu: "Saramas", comuna: "Barcani" },
  { nume: "Scrădoasa", simplu: "Scradoasa", comuna: "Intorsura Buzaului" },
  {
    nume: "Sfântu  Gheorghe",
    simplu: "Sfantu  Gheorghe",
    comuna: "Sfantul Gheorghe",
  },
  { nume: "Sita Buzăului", simplu: "Sita Buzaului" },
  { nume: "Surcea", comuna: "Zabala" },
  { nume: "Tălișoara", simplu: "Talisoara", comuna: "Bradut" },
  { nume: "Tamașfalău", simplu: "Tamasfalau", comuna: "Zabala" },
  {
    nume: "Târgu Secuiesc",
    simplu: "Targu Secuiesc",
    comuna: "Tirgu Secuiesc",
  },
  { nume: "Telechia", comuna: "Brates" },
  { nume: "Țufalău", simplu: "Tufalau", comuna: "Borosneu Mare" },
  { nume: "Turia" },
  { nume: "Vâlcele", simplu: "Valcele" },
  { nume: "Valea Crișului", simplu: "Valea Crisului" },
  {
    nume: "Valea Dobârlăului",
    simplu: "Valea Dobarlaului",
    comuna: "Dobarlau",
  },
  { nume: "Valea Mare" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Borosneu Mare" },
  { nume: "Valea Scurtă", simplu: "Valea Scurta", comuna: "Poian" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Sanzieni" },
  { nume: "Valea Zălanului", simplu: "Valea Zalanului", comuna: "Malnas" },
  { nume: "Vârghiș", simplu: "Varghis" },
  { nume: "Zăbala", simplu: "Zabala" },
  { nume: "Zăbrătău", simplu: "Zabratau", comuna: "Sita Buzaului" },
  { nume: "Zagon" },
  { nume: "Zălan", simplu: "Zalan", comuna: "Bodoc" },
  { nume: "Zoltan", comuna: "Ghidfalau" },
];
