export const cs = [
  { nume: "23 August", comuna: "Zavoi" },
  { nume: "Agadici", comuna: "Oravita" },
  { nume: "Anina" },
  { nume: "Apadia", comuna: "Brebu" },
  { nume: "Armeniş", simplu: "Armenis" },
  { nume: "Arsuri", comuna: "Cornereva" },
  { nume: "Băile Herculane", simplu: "Baile Herculane" },
  { nume: "Bănia", simplu: "Bania" },
  { nume: "Bărbosu", simplu: "Barbosu", comuna: "Ramna" },
  { nume: "Bârz", simplu: "Barz", comuna: "Dalboset" },
  { nume: "Bârza", simplu: "Barza", comuna: "Toplet" },
  { nume: "Băuţar", simplu: "Bautar" },
  { nume: "Baziaş", simplu: "Bazias", comuna: "Socol" },
  { nume: "Belobreşca", simplu: "Belobresca", comuna: "Pojejena" },
  { nume: "Berlişte", simplu: "Berliste" },
  { nume: "Berzasca" },
  { nume: "Berzovia" },
  { nume: "Bigăr", simplu: "Bigar", comuna: "Berzasca" },
  { nume: "Biniş", simplu: "Binis", comuna: "Doclin" },
  { nume: "Bocşa", simplu: "Bocsa" },
  { nume: "Bogâltin", simplu: "Bogaltin", comuna: "Cornereva" },
  { nume: "Bogodinţ", simplu: "Bogodint", comuna: "Sasca Montana" },
  { nume: "Boina", comuna: "Dalboset" },
  { nume: "Boiniţa", simplu: "Boinita", comuna: "Dalboset" },
  { nume: "Bojia", comuna: "Cornereva" },
  { nume: "Bolvaşniţa", simplu: "Bolvasnita" },
  { nume: "Borlova", comuna: "Turnu Ruieni" },
  { nume: "Borlovenii Noi", comuna: "Prigor" },
  { nume: "Borlovenii Vechi", comuna: "Prigor" },
  { nume: "Borugi", comuna: "Cornereva" },
  { nume: "Bozovici" },
  { nume: "Brădişoru de Jos", simplu: "Bradisoru de Jos", comuna: "Oravita" },
  { nume: "Bratova", comuna: "Tarnova" },
  { nume: "Brebu Nou" },
  { nume: "Brebu" },
  { nume: "Brestelnic", comuna: "Sichevita" },
  { nume: "Brezon", comuna: "Forotic" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Oravita" },
  { nume: "Buchin" },
  { nume: "Bucoşniţa", simplu: "Bucosnita" },
  { nume: "Bucova", comuna: "Bautar" },
  { nume: "Calina", comuna: "Dognecea" },
  { nume: "Câlnic", simplu: "Calnic", comuna: "Resita" },
  { nume: "Camena", comuna: "Cornereva" },
  { nume: "Cameniţa", simplu: "Camenita", comuna: "Sichevita" },
  { nume: "Câmpia", simplu: "Campia", comuna: "Socol" },
  { nume: "Cănicea", simplu: "Canicea", comuna: "Domasnea" },
  { nume: "Caransebeş", simplu: "Caransebes" },
  { nume: "Caraşova", simplu: "Carasova" },
  { nume: "Cărbunari", simplu: "Carbunari" },
  { nume: "Cârnecea", simplu: "Carnecea", comuna: "Ticvaniu Mare" },
  { nume: "Cârşa Roşie", simplu: "Carsa Rosie", comuna: "Sopotu Nou" },
  { nume: "Cârşie", simplu: "Carsie", comuna: "Sichevita" },
  { nume: "Căvăran", simplu: "Cavaran", comuna: "Constantin Daicoviciu" },
  { nume: "Cicleni", comuna: "Turnu Ruieni" },
  { nume: "Ciclova Montană", simplu: "Ciclova Montana", comuna: "Oravita" },
  { nume: "Ciclova Română", simplu: "Ciclova Romana" },
  { nume: "Ciortea", comuna: "Vrani" },
  { nume: "Cireşa", simplu: "Ciresa", comuna: "Otelu Rosu" },
  { nume: "Cireşel", simplu: "Ciresel", comuna: "Cornereva" },
  { nume: "Ciuchici" },
  { nume: "Ciudanoviţa", simplu: "Ciudanovita" },
  { nume: "Ciuta", comuna: "Obreja" },
  { nume: "Clocotici", comuna: "Lupac" },
  { nume: "Comorâşte", simplu: "Comoraste", comuna: "Forotic" },
  { nume: "Copăcele", simplu: "Copacele" },
  { nume: "Cornea" },
  { nume: "Cornereva" },
  { nume: "Cornişoru", simplu: "Cornisoru", comuna: "Bautar" },
  { nume: "Cornuţel", simplu: "Cornutel", comuna: "Paltinis" },
  { nume: "Coronini" },
  { nume: "Costiş", simplu: "Costis", comuna: "Cornereva" },
  { nume: "Cozia", comuna: "Cornereva" },
  { nume: "Cozla", comuna: "Berzasca" },
  { nume: "Cracu Almăj", simplu: "Cracu Almaj", comuna: "Sichevita" },
  { nume: "Cracu Mare", comuna: "Cornereva" },
  { nume: "Cracu Teiului", comuna: "Cornereva" },
  { nume: "Cruşovăţ", simplu: "Crusovat", comuna: "Cornea" },
  { nume: "Cruşoviţa", simplu: "Crusovita", comuna: "Sichevita" },
  { nume: "Cuptoare", comuna: "Cornea" },
  { nume: "Cuptoare", comuna: "Resita" },
  { nume: "Curmătura", simplu: "Curmatura", comuna: "Sichevita" },
  { nume: "Dalboşeţ", simplu: "Dalboset" },
  { nume: "Dalci", comuna: "Turnu Ruieni" },
  { nume: "Delineşti", simplu: "Delinesti", comuna: "Paltinis" },
  { nume: "Dezeşti", simplu: "Dezesti", comuna: "Farliug" },
  { nume: "Divici", comuna: "Pojejena" },
  { nume: "Dobraia", comuna: "Cornereva" },
  { nume: "Doclin" },
  { nume: "Dognecea" },
  { nume: "Dolina", comuna: "Cornereva" },
  { nume: "Doman", comuna: "Resita" },
  { nume: "Domaşnea", simplu: "Domasnea" },
  { nume: "Drencova", comuna: "Berzasca" },
  { nume: "Driştie", simplu: "Dristie", comuna: "Sopotu Nou" },
  { nume: "Duleu", comuna: "Farliug" },
  { nume: "Eftimie Murgu" },
  { nume: "Ersig", comuna: "Vermes" },
  { nume: "Ezeriş", simplu: "Ezeris" },
  { nume: "Fârliug", simplu: "Farliug" },
  { nume: "Feneş", simplu: "Fenes", comuna: "Armenis" },
  { nume: "Fizeş", simplu: "Fizes", comuna: "Berzovia" },
  { nume: "Forotic" },
  { nume: "Frăsiniş", simplu: "Frasinis", comuna: "Sichevita" },
  { nume: "Gărâna", simplu: "Garana", comuna: "Brebu Nou" },
  { nume: "Gârbovăţ", simplu: "Garbovat", comuna: "Bania" },
  { nume: "Gârlişte", simplu: "Garliste", comuna: "Goruia" },
  { nume: "Gârnic", simplu: "Garnic" },
  { nume: "Gherteniş", simplu: "Ghertenis", comuna: "Berzovia" },
  { nume: "Giurgiova", comuna: "Goruia" },
  { nume: "Glimboca" },
  { nume: "Globu Craiovei", comuna: "Iablanita" },
  { nume: "Globurău", simplu: "Globurau", comuna: "Mehadia" },
  { nume: "Goleţ", simplu: "Golet", comuna: "Bucosnita" },
  { nume: "Gornea", comuna: "Sichevita" },
  { nume: "Goruia" },
  { nume: "Grădinari", simplu: "Gradinari" },
  { nume: "Greoni", comuna: "Gradinari" },
  { nume: "Gruni", comuna: "Cornereva" },
  { nume: "Hora Mare", comuna: "Cornereva" },
  { nume: "Hora Mică", simplu: "Hora Mica", comuna: "Cornereva" },
  { nume: "Iabalcea", comuna: "Carasova" },
  { nume: "Iablaniţa", simplu: "Iablanita" },
  { nume: "Iam", comuna: "Berliste" },
  { nume: "Iaz", comuna: "Obreja" },
  { nume: "Iertof", comuna: "Vrani" },
  { nume: "Ilidia", comuna: "Ciclova Romana" },
  { nume: "Ilova", comuna: "Slatina-Timis" },
  { nume: "Ineleţ", simplu: "Inelet", comuna: "Cornereva" },
  { nume: "Izgar", comuna: "Vermes" },
  { nume: "Izvor", comuna: "Cornereva" },
  { nume: "Jitin", comuna: "Ciudanovita" },
  { nume: "Jupa", comuna: "Caransebes" },
  { nume: "Lăpuşnicel", simplu: "Lapusnicel" },
  { nume: "Lăpuşnicu Mare", simplu: "Lapusnicu Mare" },
  { nume: "Lescoviţa", simplu: "Lescovita", comuna: "Naidas" },
  { nume: "Liborajdea", comuna: "Sichevita" },
  { nume: "Lindenfeld", comuna: "Buchin" },
  { nume: "Liubcova", comuna: "Berzasca" },
  { nume: "Lucacevăţ", simplu: "Lucacevat", comuna: "Sichevita" },
  { nume: "Lunca Florii", comuna: "Cornereva" },
  { nume: "Lunca Zaicii", comuna: "Cornereva" },
  { nume: "Luncaviţa", simplu: "Luncavita" },
  { nume: "Lupac" },
  { nume: "Măceşti", simplu: "Macesti", comuna: "Moldova Noua" },
  { nume: "Maciova", comuna: "Constantin Daicoviciu" },
  { nume: "Macovişte", simplu: "Macoviste", comuna: "Ciuchici" },
  { nume: "Macovişte", simplu: "Macoviste", comuna: "Cornea" },
  { nume: "Măgura", simplu: "Magura", comuna: "Zavoi" },
  { nume: "Mal", comuna: "Otelu Rosu" },
  { nume: "Marga" },
  { nume: "Marila", comuna: "Oravita" },
  { nume: "Martinovăţ", simplu: "Martinovat", comuna: "Sichevita" },
  { nume: "Măru", simplu: "Maru", comuna: "Zavoi" },
  {
    nume: "Mâtnicu Mare",
    simplu: "Matnicu Mare",
    comuna: "Constantin Daicoviciu",
  },
  { nume: "Măureni", simplu: "Maureni" },
  { nume: "Mehadia" },
  { nume: "Mehadica" },
  { nume: "Mercina", comuna: "Varadia" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Cornereva" },
  { nume: "Milcoveni", comuna: "Berliste" },
  { nume: "Moceriş", simplu: "Moceris", comuna: "Lapusnicu Mare" },
  { nume: "Moldova Nouă", simplu: "Moldova Noua" },
  { nume: "Moldova Veche", comuna: "Moldova Noua" },
  { nume: "Moldoviţa", simplu: "Moldovita", comuna: "Moldova Noua" },
  { nume: "Moniom", comuna: "Resita" },
  { nume: "Naidăş", simplu: "Naidas" },
  { nume: "Negiudin", comuna: "Cornereva" },
  { nume: "Nermed", comuna: "Carasova" },
  { nume: "Nicolinţ", simplu: "Nicolint", comuna: "Ciuchici" },
  { nume: "Obiţa", simplu: "Obita", comuna: "Cornereva" },
  { nume: "Obreja" },
  { nume: "Ocna de Fier" },
  { nume: "Ogaşu Podului", simplu: "Ogasu Podului", comuna: "Sichevita" },
  { nume: "Ohaba-Mâtnic", simplu: "Ohaba-Matnic", comuna: "Copacele" },
  { nume: "Ohabiţa", simplu: "Ohabita", comuna: "Paltinis" },
  { nume: "Oraviţa", simplu: "Oravita" },
  { nume: "Oţelu Roşu", simplu: "Otelu Rosu" },
  { nume: "Padina Matei", comuna: "Garnic" },
  { nume: "Păltiniş", simplu: "Paltinis" },
  { nume: "Pârneaura", simplu: "Parneaura", comuna: "Socol" },
  { nume: "Pârvova", simplu: "Parvova", comuna: "Lapusnicel" },
  { nume: "Pătaş", simplu: "Patas", comuna: "Prigor" },
  { nume: "Pecinişca", simplu: "Pecinisca", comuna: "Baile Herculane" },
  { nume: "Peştere", simplu: "Pestere", comuna: "Constantin Daicoviciu" },
  { nume: "Petnic", comuna: "Iablanita" },
  { nume: "Petrilova", comuna: "Ciuchici" },
  { nume: "Petroşniţa", simplu: "Petrosnita", comuna: "Bucosnita" },
  { nume: "Plopu", comuna: "Armenis" },
  { nume: "Plugova", comuna: "Mehadia" },
  { nume: "Pogara de Sus", comuna: "Cornereva" },
  { nume: "Pogara", comuna: "Cornereva" },
  { nume: "Poiana Lungă", simplu: "Poiana Lunga", comuna: "Cornereva" },
  { nume: "Poiana Mărului", simplu: "Poiana Marului", comuna: "Zavoi" },
  { nume: "Poiana", comuna: "Buchin" },
  { nume: "Poienile Boinei", comuna: "Sopotu Nou" },
  { nume: "Pojejena" },
  { nume: "Poneasca", comuna: "Bozovici" },
  { nume: "Potoc", comuna: "Sasca Montana" },
  { nume: "Preveciori", comuna: "Bautar" },
  { nume: "Prigor" },
  { nume: "Prilipeţ", simplu: "Prilipet", comuna: "Bozovici" },
  { nume: "Prisaca", comuna: "Constantin Daicoviciu" },
  { nume: "Prisacina", comuna: "Cornereva" },
  { nume: "Prisian", comuna: "Buchin" },
  { nume: "Prislop", comuna: "Cornereva" },
  { nume: "Prislop", comuna: "Dalboset" },
  { nume: "Putna", comuna: "Prigor" },
  { nume: "Răcăşdia", simplu: "Racasdia" },
  { nume: "Răchita", simplu: "Rachita", comuna: "Sopotu Nou" },
  { nume: "Răchitova", simplu: "Rachitova", comuna: "Oravita" },
  { nume: "Radimna", comuna: "Pojejena" },
  { nume: "Rafnic", comuna: "Lupac" },
  { nume: "Ramna" },
  { nume: "Ravensca", comuna: "Sopotu Nou" },
  { nume: "Remetea-Pogănici", simplu: "Remetea-Poganici", comuna: "Farliug" },
  { nume: "Reşiţa Mică", simplu: "Resita Mica", comuna: "Dalboset" },
  { nume: "Reşiţa", simplu: "Resita" },
  { nume: "Rugi", comuna: "Paltinis" },
  { nume: "Ruginosu", comuna: "Copacele" },
  { nume: "Rusca Montană", simplu: "Rusca Montana" },
  { nume: "Rusca", comuna: "Teregova" },
  { nume: "Ruşchiţa", simplu: "Ruschita", comuna: "Rusca Montana" },
  { nume: "Rusova Nouă", simplu: "Rusova Noua", comuna: "Berliste" },
  { nume: "Rusova Veche", comuna: "Berliste" },
  { nume: "Ruştin", simplu: "Rustin", comuna: "Cornereva" },
  { nume: "Sacu" },
  { nume: "Sadova Nouă", simplu: "Sadova Noua", comuna: "Slatina-Timis" },
  { nume: "Sadova Veche", comuna: "Slatina-Timis" },
  { nume: "Sălbăgelu Nou", simplu: "Salbagelu Nou", comuna: "Sacu" },
  { nume: "Sasca Montană", simplu: "Sasca Montana" },
  { nume: "Sasca Română", simplu: "Sasca Romana", comuna: "Sasca Montana" },
  { nume: "Sat Bătrân", simplu: "Sat Batran", comuna: "Armenis" },
  { nume: "Scăiuş", simplu: "Scaius", comuna: "Farliug" },
  { nume: "Scărişoara", simplu: "Scarisoara", comuna: "Cornereva" },
  { nume: "Secăşeni", simplu: "Secaseni", comuna: "Ticvaniu Mare" },
  { nume: "Secu", comuna: "Resita" },
  { nume: "Sfânta Elena", simplu: "Sfanta Elena", comuna: "Coronini" },
  { nume: "Sicheviţa", simplu: "Sichevita" },
  { nume: "Slatina-Nera", comuna: "Sasca Montana" },
  { nume: "Slatina-Timiş", simplu: "Slatina-Timis" },
  { nume: "Soceni", comuna: "Ezeris" },
  { nume: "Socol" },
  { nume: "Socolari", comuna: "Ciclova Romana" },
  { nume: "Şopotu Nou", simplu: "Sopotu Nou" },
  { nume: "Şopotu Vechi", simplu: "Sopotu Vechi", comuna: "Dalboset" },
  { nume: "Şoşdea", simplu: "Sosdea", comuna: "Maureni" },
  { nume: "Stăncilova", simplu: "Stancilova", comuna: "Sopotu Nou" },
  { nume: "Steierdorf", comuna: "Anina" },
  { nume: "Ştinăpari", simplu: "Stinapari", comuna: "Carbunari" },
  { nume: "Streneac", comuna: "Sichevita" },
  { nume: "Strugasca", comuna: "Cornereva" },
  { nume: "Studena", comuna: "Cornereva" },
  { nume: "Sub Crâng", simplu: "Sub Crang", comuna: "Cornereva" },
  { nume: "Sub Margine", comuna: "Armenis" },
  { nume: "Sub Plai", comuna: "Cornereva" },
  { nume: "Şumiţa", simplu: "Sumita", comuna: "Lapusnicel" },
  { nume: "Surducu Mare", comuna: "Forotic" },
  { nume: "Şuşca", simplu: "Susca", comuna: "Pojejena" },
  { nume: "Târnova", simplu: "Tarnova" },
  { nume: "Ţaţu", simplu: "Tatu", comuna: "Cornereva" },
  { nume: "Teregova" },
  { nume: "Ţerova", simplu: "Terova", comuna: "Resita" },
  { nume: "Ticvaniu Mare" },
  { nume: "Ticvaniu Mic", comuna: "Ticvaniu Mare" },
  { nume: "Tincova", comuna: "Sacu" },
  { nume: "Tirol", comuna: "Doclin" },
  { nume: "Topla", comuna: "Cornereva" },
  { nume: "Topleţ", simplu: "Toplet" },
  { nume: "Turnu Ruieni" },
  { nume: "Urcu", comuna: "Sopotu Nou" },
  { nume: "Valea Bistrei", comuna: "Zavoi" },
  { nume: "Valea Bolvaşniţa", simplu: "Valea Bolvasnita", comuna: "Mehadia" },
  { nume: "Valea Mare", comuna: "Farliug" },
  { nume: "Valea Minişului", simplu: "Valea Minisului", comuna: "Bozovici" },
  { nume: "Valea Oreviţa", simplu: "Valea Orevita", comuna: "Sichevita" },
  { nume: "Valea Răchitei", simplu: "Valea Rachitei", comuna: "Sopotu Nou" },
  { nume: "Valea Ravensca", comuna: "Sichevita" },
  { nume: "Valea Roşie", simplu: "Valea Rosie", comuna: "Sopotu Nou" },
  { nume: "Valea Sicheviţei", simplu: "Valea Sichevitei", comuna: "Sichevita" },
  { nume: "Valea Timişului", simplu: "Valea Timisului", comuna: "Buchin" },
  { nume: "Valeadeni", comuna: "Brebu" },
  { nume: "Valeapai", comuna: "Ramna" },
  { nume: "Vălişoara", simplu: "Valisoara", comuna: "Bucosnita" },
  { nume: "Văliug", simplu: "Valiug" },
  { nume: "Vama Marga", comuna: "Marga" },
  { nume: "Var", comuna: "Obreja" },
  { nume: "Vărădia", simplu: "Varadia" },
  { nume: "Vârciorova", simplu: "Varciorova", comuna: "Bolvasnita" },
  { nume: "Verendin", comuna: "Luncavita" },
  { nume: "Vermeş", simplu: "Vermes" },
  { nume: "Vodnic", comuna: "Lupac" },
  { nume: "Voislova", comuna: "Zavoi" },
  { nume: "Vrani" },
  { nume: "Vrăniuţ", simplu: "Vraniut", comuna: "Racasdia" },
  { nume: "Zăgujeni", simplu: "Zagujeni", comuna: "Constantin Daicoviciu" },
  { nume: "Zănogi", simplu: "Zanogi", comuna: "Cornereva" },
  { nume: "Zănou", simplu: "Zanou", comuna: "Sichevita" },
  { nume: "Zăsloane", simplu: "Zasloane", comuna: "Sichevita" },
  { nume: "Zăvoi", simplu: "Zavoi" },
  { nume: "Zbegu", comuna: "Cornereva" },
  { nume: "Zerveşti", simplu: "Zervesti", comuna: "Turnu Ruieni" },
  { nume: "Zlagna", comuna: "Turnu Ruieni" },
  { nume: "Zlatiţa", simplu: "Zlatita", comuna: "Socol" },
  { nume: "Zmogotin", comuna: "Cornereva" },
  { nume: "Zoina", comuna: "Cornereva" },
  { nume: "Zorile", comuna: "Copacele" },
  { nume: "Zorlencior", comuna: "Zorlentu Mare" },
  { nume: "Zorlenţu Mare", simplu: "Zorlentu Mare" },
];
