export const ct = [
  { nume: "23 August" },
  { nume: "Adamclisi" },
  { nume: "Agigea" },
  { nume: "Albesti" },
  { nume: "Aliman" },
  { nume: "Amzacea" },
  { nume: "Baneasa" },
  { nume: "Baraganu" },
  { nume: "Castelu" },
  { nume: "Cerchezu" },
  { nume: "Cernavoda" },
  { nume: "Chirnogeni" },
  { nume: "Ciobanu" },
  { nume: "Ciocarlia" },
  { nume: "Cobadin" },
  { nume: "Cogealac" },
  { nume: "Comana" },
  { nume: "Constanta" },
  { nume: "Corbu" },
  { nume: "Costinesti" },
  { nume: "Crucea" },
  { nume: "Cumpana" },
  { nume: "Deleni" },
  { nume: "Dobromir" },
  { nume: "Dumbraveni" },
  { nume: "Ghindaresti" },
  { nume: "Garliciu" },
  { nume: "Horia" },
  { nume: "Harsova" },
  { nume: "Independenta" },
  { nume: "Ion Corvin" },
  { nume: "Istria" },
  { nume: "Limanu" },
  { nume: "Lipnita" },
  { nume: "Lumina" },
  { nume: "Mangalia" },
  { nume: "Medgidia" },
  { nume: "Mereni" },
  { nume: "Mihai Viteazu" },
  { nume: "Mihail Kogalniceanu" },
  { nume: "Mircea Voda" },
  { nume: "Negru Voda" },
  { nume: "Nicolae Balcescu" },
  { nume: "Navodari" },
  { nume: "Oltina" },
  { nume: "Ostrov" },
  { nume: "Ovidiu" },
  { nume: "Pantelimon" },
  { nume: "Pecineaga" },
  { nume: "Pestera" },
  { nume: "Poarta Alba" },
  { nume: "Rasova" },
  { nume: "Saraiu" },
  { nume: "Seimeni" },
  { nume: "Silistea" },
  { nume: "Sacele" },
  { nume: "Techirghiol" },
  { nume: "Topalu" },
  { nume: "Topraisar" },
  { nume: "Tortoman" },
  { nume: "Tuzla" },
  { nume: "Targusor" },
  { nume: "Valu lui Traian" },
  { nume: "Vulturu" },
  { nume: "Dulcesti", comuna: "23 August" },
  { nume: "Mosneni", comuna: "23 August" },
  { nume: "Abrud", comuna: "Adamclisi" },
  { nume: "Hateg", comuna: "Adamclisi" },
  { nume: "Urluia", comuna: "Adamclisi" },
  { nume: "Zorile", comuna: "Adamclisi" },
  { nume: "Lazu", comuna: "Agigea" },
  { nume: "Sanatoriul Agigea", comuna: "Agigea" },
  { nume: "Statiunea Zoologica Marina Agigea", comuna: "Agigea" },
  { nume: "Arsa", comuna: "Albesti" },
  { nume: "Coroana", comuna: "Albesti" },
  { nume: "Cotu Vaii", comuna: "Albesti" },
  { nume: "Vartop", comuna: "Albesti" },
  { nume: "Dunareni", comuna: "Aliman" },
  { nume: "Floriile", comuna: "Aliman" },
  { nume: "Vlahii", comuna: "Aliman" },
  { nume: "Casicea", comuna: "Amzacea" },
  { nume: "General Scarisoreanu", comuna: "Amzacea" },
  { nume: "Faurei", comuna: "Baneasa" },
  { nume: "Negureni", comuna: "Baneasa" },
  { nume: "Tudor Vladimirescu", comuna: "Baneasa" },
  { nume: "Lanurile", comuna: "Baraganu" },
  { nume: "Murfatlar", comuna: "Basarabi" },
  { nume: "Siminoc", comuna: "Basarabi" },
  { nume: "Cuza Voda", comuna: "Castelu" },
  { nume: "Nisipari", comuna: "Castelu" },
  { nume: "Cascioarele", comuna: "Cerchezu" },
  { nume: "Magura", comuna: "Cerchezu" },
  { nume: "Viroaga", comuna: "Cerchezu" },
  { nume: "Credinta", comuna: "Chirnogeni" },
  { nume: "Plopeni", comuna: "Chirnogeni" },
  { nume: "Miorita", comuna: "Ciobanu" },
  { nume: "Ciocarlia de Sus", comuna: "Ciocarlia" },
  { nume: "Conacu", comuna: "Cobadin" },
  { nume: "Curcani", comuna: "Cobadin" },
  { nume: "Negresti", comuna: "Cobadin" },
  { nume: "Viisoara", comuna: "Cobadin" },
  { nume: "Fantanele", comuna: "Cogealac" },
  { nume: "Gura Dobrogei", comuna: "Cogealac" },
  { nume: "Ramnicu de Jos", comuna: "Cogealac" },
  { nume: "Ramnicu de Sus", comuna: "Cogealac" },
  { nume: "Tariverde", comuna: "Cogealac" },
  { nume: "Pelinu", comuna: "Comana" },
  { nume: "Tataru", comuna: "Comana" },
  { nume: "Mamaia", comuna: "Constanta" },
  { nume: "Palazu Mare", comuna: "Constanta" },
  { nume: "Luminita", comuna: "Corbu" },
  { nume: "Vadu", comuna: "Corbu" },
  { nume: "Schitu", comuna: "Costinesti" },
  { nume: "Baltagesti", comuna: "Crucea" },
  { nume: "Crisan", comuna: "Crucea" },
  { nume: "Galbiori", comuna: "Crucea" },
  { nume: "Stupina", comuna: "Crucea" },
  { nume: "Siriu", comuna: "Crucea" },
  { nume: "Straja", comuna: "Cumpana" },
  { nume: "Petrosani", comuna: "Deleni" },
  { nume: "Pietreni", comuna: "Deleni" },
  { nume: "Sipotele", comuna: "Deleni" },
  { nume: "Cetatea", comuna: "Dobromir" },
  { nume: "Dobromiru din Deal", comuna: "Dobromir" },
  { nume: "Lespezi", comuna: "Dobromir" },
  { nume: "Padureni", comuna: "Dobromir" },
  { nume: "Valeni", comuna: "Dobromir" },
  { nume: "Furnica", comuna: "Dumbraveni" },
  { nume: "Eforie Nord", comuna: "Eforie" },
  { nume: "Eforie Sud", comuna: "Eforie" },
  { nume: "Vadu Oii", comuna: "Harsova" },
  { nume: "Closca", comuna: "Horia" },
  { nume: "Tichilesti", comuna: "Horia" },
  { nume: "Fantana Mare", comuna: "Independenta" },
  { nume: "Movila Verde", comuna: "Independenta" },
  { nume: "Olteni", comuna: "Independenta" },
  { nume: "Tufani", comuna: "Independenta" },
  { nume: "Brebeni", comuna: "Ion Corvin" },
  { nume: "Crangu", comuna: "Ion Corvin" },
  { nume: "Raristea", comuna: "Ion Corvin" },
  { nume: "Viile", comuna: "Ion Corvin" },
  { nume: "Nuntasi", comuna: "Istria" },
  { nume: "2 Mai", comuna: "Limanu" },
  { nume: "Hagieni", comuna: "Limanu" },
  { nume: "Vama Veche", comuna: "Limanu" },
  { nume: "Canlia", comuna: "Lipnita" },
  { nume: "Carvan", comuna: "Lipnita" },
  { nume: "Coslugea", comuna: "Lipnita" },
  { nume: "Cuiugiuc", comuna: "Lipnita" },
  { nume: "Goruni", comuna: "Lipnita" },
  { nume: "Izvoarele", comuna: "Lipnita" },
  { nume: "Oituz", comuna: "Lumina" },
  { nume: "Sibioara", comuna: "Lumina" },
  { nume: "Cap Aurora", comuna: "Mangalia" },
  { nume: "Jupiter", comuna: "Mangalia" },
  { nume: "Neptun", comuna: "Mangalia" },
  { nume: "Olimp", comuna: "Mangalia" },
  { nume: "Saturn", comuna: "Mangalia" },
  { nume: "Venus", comuna: "Mangalia" },
  { nume: "Remus Opreanu", comuna: "Medgidia" },
  { nume: "Valea Dacilor", comuna: "Medgidia" },
  { nume: "Ciobanita", comuna: "Mereni" },
  { nume: "Miristea", comuna: "Mereni" },
  { nume: "Osmancea", comuna: "Mereni" },
  { nume: "Sinoie", comuna: "Mihai Viteazu" },
  { nume: "Palazu Mic", comuna: "Mihail Kogalniceanu" },
  { nume: "Piatra", comuna: "Mihail Kogalniceanu" },
  { nume: "Faclia", comuna: "Mircea Voda" },
  { nume: "Gherghina", comuna: "Mircea Voda" },
  { nume: "Saligny", comuna: "Mircea Voda" },
  { nume: "Satu Nou", comuna: "Mircea Voda" },
  { nume: "Stefan cel Mare", comuna: "Mircea Voda" },
  { nume: "Tibrinu", comuna: "Mircea Voda" },
  { nume: "Mamaia-Sat", comuna: "Navodari" },
  { nume: "Darabani", comuna: "Negru Voda" },
  { nume: "Graniceru", comuna: "Negru Voda" },
  { nume: "Valcelele", comuna: "Negru Voda" },
  { nume: "Dorobantu", comuna: "Nicolae Balcescu" },
  { nume: "Razoarele", comuna: "Oltina" },
  { nume: "Satu Nou", comuna: "Oltina" },
  { nume: "Strunga", comuna: "Oltina" },
  { nume: "Almalau", comuna: "Ostrov" },
  { nume: "Bugeac", comuna: "Ostrov" },
  { nume: "Esechioi", comuna: "Ostrov" },
  { nume: "Galita", comuna: "Ostrov" },
  { nume: "Garlita", comuna: "Ostrov" },
  { nume: "Poiana", comuna: "Ovidiu" },
  { nume: "Calugareni", comuna: "Pantelimon" },
  { nume: "Nistoresti", comuna: "Pantelimon" },
  { nume: "Pantelimon de Jos", comuna: "Pantelimon" },
  { nume: "Runcu", comuna: "Pantelimon" },
  { nume: "Vanatori", comuna: "Pecineaga" },
  { nume: "Ivrinezu Mare", comuna: "Pestera" },
  { nume: "Ivrinezu Mic", comuna: "Pestera" },
  { nume: "Izvoru Mare", comuna: "Pestera" },
  { nume: "Veteranu", comuna: "Pestera" },
  { nume: "Nazarcea", comuna: "Poarta Alba" },
  { nume: "Cochirleni", comuna: "Rasova" },
  { nume: "Traian", comuna: "Sacele" },
  { nume: "Dulgheru", comuna: "Saraiu" },
  { nume: "Stejaru", comuna: "Saraiu" },
  { nume: "Dunarea", comuna: "Seimeni" },
  { nume: "Seimenii Mici", comuna: "Seimeni" },
  { nume: "Tepes Voda", comuna: "Silistea" },
  { nume: "Casian", comuna: "Targusor" },
  { nume: "Cheia", comuna: "Targusor" },
  { nume: "Gradina", comuna: "Targusor" },
  { nume: "Mireasa", comuna: "Targusor" },
  { nume: "Capidava", comuna: "Topalu" },
  { nume: "Biruinta", comuna: "Topraisar" },
  { nume: "Movilita", comuna: "Topraisar" },
  { nume: "Potarnichea", comuna: "Topraisar" },
  { nume: "Dropia", comuna: "Tortoman" },
];
