export const cj = [
  { nume: "Aghiresu" },
  { nume: "Aiton" },
  { nume: "Alunis" },
  { nume: "Apahida" },
  { nume: "Baciu" },
  { nume: "Belis" },
  { nume: "Bobalna" },
  { nume: "Bontida" },
  { nume: "Borsa" },
  { nume: "Buza" },
  { nume: "Baisoara" },
  { nume: "Ceanu Mare" },
  { nume: "Chinteni" },
  { nume: "Chiuiesti" },
  { nume: "Ciucea" },
  { nume: "Ciurila" },
  { nume: "Cluj-Napoca" },
  { nume: "Cojocna" },
  { nume: "Cornesti" },
  { nume: "Cuzdrioara" },
  { nume: "Campia Turzii" },
  { nume: "Catcau" },
  { nume: "Caianu" },
  { nume: "Calarasi" },
  { nume: "Calatele" },
  { nume: "Camarasu" },
  { nume: "Capusu Mare" },
  { nume: "Catina" },
  { nume: "Caseiu" },
  { nume: "Dej" },
  { nume: "Dabaca" },
  { nume: "Feleacu" },
  { nume: "Fizesu Gherlii" },
  { nume: "Floresti" },
  { nume: "Frata" },
  { nume: "Geaca" },
  { nume: "Gherla" },
  { nume: "Gilau" },
  { nume: "Garbau" },
  { nume: "Huedin" },
  { nume: "Iara" },
  { nume: "Iclod" },
  { nume: "Izvoru Crisului" },
  { nume: "Jichisu de Jos" },
  { nume: "Luna" },
  { nume: "Mica" },
  { nume: "Mihai Viteazu" },
  { nume: "Mintiu Gherlii" },
  { nume: "Mociu" },
  { nume: "Moldovenesti" },
  { nume: "Maguri-Racatau" },
  { nume: "Manastireni" },
  { nume: "Margau" },
  { nume: "Marisel" },
  { nume: "Negreni" },
  { nume: "Panticeu" },
  { nume: "Petrestii de Jos" },
  { nume: "Ploscos" },
  { nume: "Poieni" },
  { nume: "Palatca" },
  { nume: "Recea-Cristur" },
  { nume: "Risca" },
  { nume: "Sic" },
  { nume: "Suatu" },
  { nume: "Sancraiu" },
  { nume: "Sanmartin" },
  { nume: "Sanpaul" },
  { nume: "Sacuieu" },
  { nume: "Sandulesti" },
  { nume: "Savadisla" },
  { nume: "Tritenii de Jos" },
  { nume: "Turda" },
  { nume: "Tureni" },
  { nume: "Unguras" },
  { nume: "Vad" },
  { nume: "Valea Ierii" },
  { nume: "Viisoara" },
  { nume: "Vultureni" },
  { nume: "Taga" },
  { nume: "Aghiresu-Fabrici", comuna: "Aghiresu" },
  { nume: "Arghisu", comuna: "Aghiresu" },
  { nume: "Bagara", comuna: "Aghiresu" },
  { nume: "Doroltu", comuna: "Aghiresu" },
  { nume: "Dancu", comuna: "Aghiresu" },
  { nume: "Inucu", comuna: "Aghiresu" },
  { nume: "Leghia", comuna: "Aghiresu" },
  { nume: "Macau", comuna: "Aghiresu" },
  { nume: "Ticu", comuna: "Aghiresu" },
  { nume: "Ticu-Colonie", comuna: "Aghiresu" },
  { nume: "Rediu", comuna: "Aiton" },
  { nume: "Corneni", comuna: "Alunis" },
  { nume: "Ghirolt", comuna: "Alunis" },
  { nume: "Pruneni", comuna: "Alunis" },
  { nume: "Vale", comuna: "Alunis" },
  { nume: "Bodrog", comuna: "Apahida" },
  { nume: "Corpadea", comuna: "Apahida" },
  { nume: "Campenesti", comuna: "Apahida" },
  { nume: "Dezmir", comuna: "Apahida" },
  { nume: "Pata", comuna: "Apahida" },
  { nume: "Sub Coasta", comuna: "Apahida" },
  { nume: "Sannicoara", comuna: "Apahida" },
  { nume: "Cristorel", comuna: "Aschileu" },
  { nume: "Dorna", comuna: "Aschileu" },
  { nume: "Fodora", comuna: "Aschileu" },
  { nume: "Aschileu Mare", comuna: "Aschileu" },
  { nume: "Aschileu Mic", comuna: "Aschileu" },
  { nume: "Corusu", comuna: "Baciu" },
  { nume: "Mera", comuna: "Baciu" },
  { nume: "Popesti", comuna: "Baciu" },
  { nume: "Radaia", comuna: "Baciu" },
  { nume: "Suceagu", comuna: "Baciu" },
  { nume: "Salistea Noua", comuna: "Baciu" },
  { nume: "Frasinet", comuna: "Baisoara" },
  { nume: "Moara de Padure", comuna: "Baisoara" },
  { nume: "Muntele Bocului", comuna: "Baisoara" },
  { nume: "Muntele Baisorii", comuna: "Baisoara" },
  { nume: "Muntele Cacovei", comuna: "Baisoara" },
  { nume: "Muntele Filii", comuna: "Baisoara" },
  { nume: "Muntele Sacelului", comuna: "Baisoara" },
  { nume: "Sacel", comuna: "Baisoara" },
  { nume: "Balcesti", comuna: "Belis" },
  { nume: "Dealu Botii", comuna: "Belis" },
  { nume: "Giurcuta de Jos", comuna: "Belis" },
  { nume: "Giurcuta de Sus", comuna: "Belis" },
  { nume: "Poiana Horea", comuna: "Belis" },
  { nume: "Smida", comuna: "Belis" },
  { nume: "Antas", comuna: "Bobalna" },
  { nume: "Blidaresti", comuna: "Bobalna" },
  { nume: "Babdiu", comuna: "Bobalna" },
  { nume: "Cremenea", comuna: "Bobalna" },
  { nume: "Maia", comuna: "Bobalna" },
  { nume: "Osorhel", comuna: "Bobalna" },
  { nume: "Pruni", comuna: "Bobalna" },
  { nume: "Razbuneni", comuna: "Bobalna" },
  { nume: "Suaras", comuna: "Bobalna" },
  { nume: "Valcelele", comuna: "Bobalna" },
  { nume: "Coasta", comuna: "Bontida" },
  { nume: "Rascruci", comuna: "Bontida" },
  { nume: "Tauseni", comuna: "Bontida" },
  { nume: "Borsa-Crestaia", comuna: "Borsa" },
  { nume: "Borsa-Catun", comuna: "Borsa" },
  { nume: "Ciumafaia", comuna: "Borsa" },
  { nume: "Giula", comuna: "Borsa" },
  { nume: "Rotunda", comuna: "Buza" },
  { nume: "Barai", comuna: "Caianu" },
  { nume: "Caianu Mic", comuna: "Caianu" },
  { nume: "Caianu-Vama", comuna: "Caianu" },
  { nume: "Vaida-Camaras", comuna: "Caianu" },
  { nume: "Valeni", comuna: "Caianu" },
  { nume: "Bogata", comuna: "Calarasi" },
  { nume: "Calarasi-Gara", comuna: "Calarasi" },
  { nume: "Calata", comuna: "Calatele" },
  { nume: "Dealu Negru", comuna: "Calatele" },
  { nume: "Finciu", comuna: "Calatele" },
  { nume: "Valeni", comuna: "Calatele" },
  { nume: "Naoiu", comuna: "Camarasu" },
  { nume: "Samboleni", comuna: "Camarasu" },
  { nume: "Agarbiciu", comuna: "Capusu Mare" },
  { nume: "Balcesti", comuna: "Capusu Mare" },
  { nume: "Capusu Mic", comuna: "Capusu Mare" },
  { nume: "Dumbrava", comuna: "Capusu Mare" },
  { nume: "Dangau Mare", comuna: "Capusu Mare" },
  { nume: "Dangau Mic", comuna: "Capusu Mare" },
  { nume: "Paniceni", comuna: "Capusu Mare" },
  { nume: "Straja", comuna: "Capusu Mare" },
  { nume: "Comorata", comuna: "Caseiu" },
  { nume: "Coplean", comuna: "Caseiu" },
  { nume: "Custura", comuna: "Caseiu" },
  { nume: "Guga", comuna: "Caseiu" },
  { nume: "Garbau Dejului", comuna: "Caseiu" },
  { nume: "Leurda", comuna: "Caseiu" },
  { nume: "Rugasesti", comuna: "Caseiu" },
  { nume: "Salatruc", comuna: "Caseiu" },
  { nume: "Urisor", comuna: "Caseiu" },
  { nume: "Muncel", comuna: "Catcau" },
  { nume: "Salisca", comuna: "Catcau" },
  { nume: "Copru", comuna: "Catina" },
  { nume: "Feldioara", comuna: "Catina" },
  { nume: "Hagau", comuna: "Catina" },
  { nume: "Hodaie", comuna: "Catina" },
  { nume: "Valea Calda", comuna: "Catina" },
  { nume: "Andici", comuna: "Ceanu Mare" },
  { nume: "Boian", comuna: "Ceanu Mare" },
  { nume: "Boldut", comuna: "Ceanu Mare" },
  { nume: "Ciurgau", comuna: "Ceanu Mare" },
  { nume: "Dosu Napului", comuna: "Ceanu Mare" },
  { nume: "Fanate", comuna: "Ceanu Mare" },
  { nume: "Hodai Boian", comuna: "Ceanu Mare" },
  { nume: "Iacobeni", comuna: "Ceanu Mare" },
  { nume: "Mortesti", comuna: "Ceanu Mare" },
  { nume: "Strucut", comuna: "Ceanu Mare" },
  { nume: "Starcu", comuna: "Ceanu Mare" },
  { nume: "Valea lui Cati", comuna: "Ceanu Mare" },
  { nume: "Deusu", comuna: "Chinteni" },
  { nume: "Feiurdeni", comuna: "Chinteni" },
  { nume: "Macicasu", comuna: "Chinteni" },
  { nume: "Padureni", comuna: "Chinteni" },
  { nume: "Satu Lung", comuna: "Chinteni" },
  { nume: "Sanmartin", comuna: "Chinteni" },
  { nume: "Salistea Veche", comuna: "Chinteni" },
  { nume: "Vechea", comuna: "Chinteni" },
  { nume: "Dosu Bricii", comuna: "Chiuiesti" },
  { nume: "Huta", comuna: "Chiuiesti" },
  { nume: "Magoaja", comuna: "Chiuiesti" },
  { nume: "Strambu", comuna: "Chiuiesti" },
  { nume: "Valea Caseielului", comuna: "Chiuiesti" },
  { nume: "Valea lui Opris", comuna: "Chiuiesti" },
  { nume: "Vanatori", comuna: "Ciucea" },
  { nume: "Filea de Jos", comuna: "Ciurila" },
  { nume: "Filea de Sus", comuna: "Ciurila" },
  { nume: "Prunis", comuna: "Ciurila" },
  { nume: "Padureni", comuna: "Ciurila" },
  { nume: "Salicea", comuna: "Ciurila" },
  { nume: "Saliste", comuna: "Ciurila" },
  { nume: "Sutu", comuna: "Ciurila" },
  { nume: "Boj-Catun", comuna: "Cojocna" },
  { nume: "Boju", comuna: "Cojocna" },
  { nume: "Cara", comuna: "Cojocna" },
  { nume: "Huci", comuna: "Cojocna" },
  { nume: "Iuriu de Campie", comuna: "Cojocna" },
  { nume: "Moristi", comuna: "Cojocna" },
  { nume: "Straja", comuna: "Cojocna" },
  { nume: "Barlea", comuna: "Cornesti" },
  { nume: "Igritia", comuna: "Cornesti" },
  { nume: "Lujerdiu", comuna: "Cornesti" },
  { nume: "Morau", comuna: "Cornesti" },
  { nume: "Stoiana", comuna: "Cornesti" },
  { nume: "Tiocu de Jos", comuna: "Cornesti" },
  { nume: "Tiocu de Sus", comuna: "Cornesti" },
  { nume: "Tioltiur", comuna: "Cornesti" },
  { nume: "Manasturel", comuna: "Cuzdrioara" },
  { nume: "Valea Garboului", comuna: "Cuzdrioara" },
  { nume: "Luna de Jos", comuna: "Dabaca" },
  { nume: "Paglisa", comuna: "Dabaca" },
  { nume: "Ocna Dejului", comuna: "Dej" },
  { nume: "Pestera", comuna: "Dej" },
  { nume: "Pintic", comuna: "Dej" },
  { nume: "Somcutu Mic", comuna: "Dej" },
  { nume: "Casele Micesti", comuna: "Feleacu" },
  { nume: "Gheorghieni", comuna: "Feleacu" },
  { nume: "Saradis", comuna: "Feleacu" },
  { nume: "Valcele", comuna: "Feleacu" },
  { nume: "Bont", comuna: "Fizesu Gherlii" },
  { nume: "Lunca Bontului", comuna: "Fizesu Gherlii" },
  { nume: "Nicula", comuna: "Fizesu Gherlii" },
  { nume: "Sacalaia", comuna: "Fizesu Gherlii" },
  { nume: "Luna de Sus", comuna: "Floresti" },
  { nume: "Tauti", comuna: "Floresti" },
  { nume: "Berchiesu", comuna: "Frata" },
  { nume: "Oas", comuna: "Frata" },
  { nume: "Olariu", comuna: "Frata" },
  { nume: "Poiana Fratii", comuna: "Frata" },
  { nume: "Padurea Iacobeni", comuna: "Frata" },
  { nume: "Razoare", comuna: "Frata" },
  { nume: "Soporu de Campie", comuna: "Frata" },
  { nume: "Cornesti", comuna: "Garbau" },
  { nume: "Nadaselu", comuna: "Garbau" },
  { nume: "Turea", comuna: "Garbau" },
  { nume: "Vistea", comuna: "Garbau" },
  { nume: "Chiris", comuna: "Geaca" },
  { nume: "Lacu", comuna: "Geaca" },
  { nume: "Legii", comuna: "Geaca" },
  { nume: "Puini", comuna: "Geaca" },
  { nume: "Sucutard", comuna: "Geaca" },
  { nume: "Baita", comuna: "Gherla" },
  { nume: "Hasdate", comuna: "Gherla" },
  { nume: "Silivas", comuna: "Gherla" },
  { nume: "Somesu Cald", comuna: "Gilau" },
  { nume: "Somesu Rece", comuna: "Gilau" },
  { nume: "Bicalatu", comuna: "Huedin" },
  { nume: "Agris", comuna: "Iara" },
  { nume: "Borzesti", comuna: "Iara" },
  { nume: "Buru", comuna: "Iara" },
  { nume: "Cacova Ierii", comuna: "Iara" },
  { nume: "Fagetu Ierii", comuna: "Iara" },
  { nume: "Lungesti", comuna: "Iara" },
  { nume: "Masca", comuna: "Iara" },
  { nume: "Magura Ierii", comuna: "Iara" },
  { nume: "Ocolisel", comuna: "Iara" },
  { nume: "Surduc", comuna: "Iara" },
  { nume: "Valea Agrisului", comuna: "Iara" },
  { nume: "Valea Vadului", comuna: "Iara" },
  { nume: "Fundatura", comuna: "Iclod" },
  { nume: "Iclozel", comuna: "Iclod" },
  { nume: "Livada", comuna: "Iclod" },
  { nume: "Orman", comuna: "Iclod" },
  { nume: "Nadasu", comuna: "Izvoru Crisului" },
  { nume: "Nearsova", comuna: "Izvoru Crisului" },
  { nume: "Saula", comuna: "Izvoru Crisului" },
  { nume: "Codor", comuna: "Jichisu De Jos" },
  { nume: "Jichisu de Sus", comuna: "Jichisu De Jos" },
  { nume: "Tarpiu", comuna: "Jichisu De Jos" },
  { nume: "Sigau", comuna: "Jichisu De Jos" },
  { nume: "Gadalin", comuna: "Jucu" },
  { nume: "Juc-Herghelie", comuna: "Jucu" },
  { nume: "Jucu de Mijloc", comuna: "Jucu" },
  { nume: "Jucu de Sus", comuna: "Jucu" },
  { nume: "Visea", comuna: "Jucu" },
  { nume: "Gligoresti", comuna: "Luna" },
  { nume: "Luncani", comuna: "Luna" },
  { nume: "Muntele Rece", comuna: "Maguri-Racatau" },
  { nume: "Maguri", comuna: "Maguri-Racatau" },
  { nume: "Ardeova", comuna: "Manastireni" },
  { nume: "Bedeciu", comuna: "Manastireni" },
  { nume: "Bica", comuna: "Manastireni" },
  { nume: "Dretea", comuna: "Manastireni" },
  { nume: "Manasturu Romanesc", comuna: "Manastireni" },
  { nume: "Bociu", comuna: "Margau" },
  { nume: "Buteni", comuna: "Margau" },
  { nume: "Ciuleni", comuna: "Margau" },
  { nume: "Rachitele", comuna: "Margau" },
  { nume: "Scrind-Frasinet", comuna: "Margau" },
  { nume: "Dambu Mare", comuna: "Mica" },
  { nume: "Manastirea", comuna: "Mica" },
  { nume: "Nires", comuna: "Mica" },
  { nume: "Sanmarghita", comuna: "Mica" },
  { nume: "Valea Ciresoii", comuna: "Mica" },
  { nume: "Valea Luncii", comuna: "Mica" },
  { nume: "Cheia", comuna: "Mihai Viteazu" },
  { nume: "Cornesti", comuna: "Mihai Viteazu" },
  { nume: "Bunesti", comuna: "Mintiu Gherlii" },
  { nume: "Nima", comuna: "Mintiu Gherlii" },
  { nume: "Petresti", comuna: "Mintiu Gherlii" },
  { nume: "Padurenii", comuna: "Mintiu Gherlii" },
  { nume: "Salatiu", comuna: "Mintiu Gherlii" },
  { nume: "Boteni", comuna: "Mociu" },
  { nume: "Chesau", comuna: "Mociu" },
  { nume: "Criseni", comuna: "Mociu" },
  { nume: "Falca", comuna: "Mociu" },
  { nume: "Ghirisu Roman", comuna: "Mociu" },
  { nume: "Rosieni", comuna: "Mociu" },
  { nume: "Turmasi", comuna: "Mociu" },
  { nume: "Zorenii de Vale", comuna: "Mociu" },
  { nume: "Badeni", comuna: "Moldovenesti" },
  { nume: "Pietroasa", comuna: "Moldovenesti" },
  { nume: "Plaiesti", comuna: "Moldovenesti" },
  { nume: "Podeni", comuna: "Moldovenesti" },
  { nume: "Stejeris", comuna: "Moldovenesti" },
  { nume: "Bucea", comuna: "Negreni" },
  { nume: "Prelucele", comuna: "Negreni" },
  { nume: "Bagaciu", comuna: "Palatca" },
  { nume: "Muresenii de Campie", comuna: "Palatca" },
  { nume: "Petea", comuna: "Palatca" },
  { nume: "Sava", comuna: "Palatca" },
  { nume: "Cublesu Somesan", comuna: "Panticeu" },
  { nume: "Catalina", comuna: "Panticeu" },
  { nume: "Darja", comuna: "Panticeu" },
  { nume: "Sarata", comuna: "Panticeu" },
  { nume: "Craesti", comuna: "Petrestii De Jos" },
  { nume: "Deleni", comuna: "Petrestii De Jos" },
  { nume: "Livada", comuna: "Petrestii De Jos" },
  { nume: "Petrestii de Mijloc", comuna: "Petrestii De Jos" },
  { nume: "Petrestii de Sus", comuna: "Petrestii De Jos" },
  { nume: "Plaiuri", comuna: "Petrestii De Jos" },
  { nume: "Crairat", comuna: "Ploscos" },
  { nume: "Lobodas", comuna: "Ploscos" },
  { nume: "Valea Florilor", comuna: "Ploscos" },
  { nume: "Bologa", comuna: "Poieni" },
  { nume: "Cerbesti", comuna: "Poieni" },
  { nume: "Hodisu", comuna: "Poieni" },
  { nume: "Lunca Visagului", comuna: "Poieni" },
  { nume: "Morlaca", comuna: "Poieni" },
  { nume: "Tranisu", comuna: "Poieni" },
  { nume: "Valea Draganului", comuna: "Poieni" },
  { nume: "Ciubanca", comuna: "Recea-Cristur" },
  { nume: "Ciubancuta", comuna: "Recea-Cristur" },
  { nume: "Caprioara", comuna: "Recea-Cristur" },
  { nume: "Elciu", comuna: "Recea-Cristur" },
  { nume: "Escu", comuna: "Recea-Cristur" },
  { nume: "Jurca", comuna: "Recea-Cristur" },
  { nume: "Osoi", comuna: "Recea-Cristur" },
  { nume: "Pustuta", comuna: "Recea-Cristur" },
  { nume: "Dealu Mare", comuna: "Risca" },
  { nume: "Lapustesti", comuna: "Risca" },
  { nume: "Marcesti", comuna: "Risca" },
  { nume: "Rogojel", comuna: "Sacuieu" },
  { nume: "Visagu", comuna: "Sacuieu" },
  { nume: "Alunisu", comuna: "Sancraiu" },
  { nume: "Braisoru", comuna: "Sancraiu" },
  { nume: "Domosu", comuna: "Sancraiu" },
  { nume: "Horlacea", comuna: "Sancraiu" },
  { nume: "Copaceni", comuna: "Sandulesti" },
  { nume: "Ceaba", comuna: "Sanmartin" },
  { nume: "Cutca", comuna: "Sanmartin" },
  { nume: "Diviciorii Mari", comuna: "Sanmartin" },
  { nume: "Diviciorii Mici", comuna: "Sanmartin" },
  { nume: "Mahal", comuna: "Sanmartin" },
  { nume: "Samboieni", comuna: "Sanmartin" },
  { nume: "Targusor", comuna: "Sanmartin" },
  { nume: "Berindu", comuna: "Sanpaul" },
  { nume: "Mihaiesti", comuna: "Sanpaul" },
  { nume: "Sumurducu", comuna: "Sanpaul" },
  { nume: "Topa Mica", comuna: "Sanpaul" },
  { nume: "Sardu", comuna: "Sanpaul" },
  { nume: "Finisel", comuna: "Savadisla" },
  { nume: "Hasdate", comuna: "Savadisla" },
  { nume: "Lita", comuna: "Savadisla" },
  { nume: "Liteni", comuna: "Savadisla" },
  { nume: "Stolna", comuna: "Savadisla" },
  { nume: "Vlaha", comuna: "Savadisla" },
  { nume: "Valisoara", comuna: "Savadisla" },
  { nume: "Aruncuta", comuna: "Suatu" },
  { nume: "Damburile", comuna: "Suatu" },
  { nume: "Nasal", comuna: "Taga" },
  { nume: "Santejude", comuna: "Taga" },
  { nume: "Santejude Vale", comuna: "Taga" },
  { nume: "Santioana", comuna: "Taga" },
  { nume: "Clapa", comuna: "Tritenii De Jos" },
  { nume: "Colonia", comuna: "Tritenii De Jos" },
  { nume: "Padureni", comuna: "Tritenii De Jos" },
  { nume: "Tritenii de Sus", comuna: "Tritenii De Jos" },
  { nume: "Tritenii-Hotar", comuna: "Tritenii De Jos" },
  { nume: "Ceanu Mic", comuna: "Tureni" },
  { nume: "Comsesti", comuna: "Tureni" },
  { nume: "Micesti", comuna: "Tureni" },
  { nume: "Martinesti", comuna: "Tureni" },
  { nume: "Batin", comuna: "Unguras" },
  { nume: "Darot", comuna: "Unguras" },
  { nume: "Sicfa", comuna: "Unguras" },
  { nume: "Valea Ungurasului", comuna: "Unguras" },
  { nume: "Bogata de Jos", comuna: "Vad" },
  { nume: "Bogata de Sus", comuna: "Vad" },
  { nume: "Calna", comuna: "Vad" },
  { nume: "Cetan", comuna: "Vad" },
  { nume: "Curtuiusu Dejului", comuna: "Vad" },
  { nume: "Valea Grosilor", comuna: "Vad" },
  { nume: "Cerc", comuna: "Valea Ierii" },
  { nume: "Plopi", comuna: "Valea Ierii" },
  { nume: "Urca", comuna: "Viisoara" },
  { nume: "Babutiu", comuna: "Vultureni" },
  { nume: "Badesti", comuna: "Vultureni" },
  { nume: "Chidea", comuna: "Vultureni" },
  { nume: "Faureni", comuna: "Vultureni" },
  { nume: "Soimeni", comuna: "Vultureni" },
];
