export const cl = [
  { nume: "Alexandru I. Cuza", comuna: "Fundulea" },
  { nume: "Alexandru Odobescu" },
  { nume: "Aprozi", comuna: "Budesti" },
  { nume: "Arţari", simplu: "Artari", comuna: "Ileana" },
  { nume: "Belciugatele" },
  { nume: "Bogata", comuna: "Gradistea" },
  { nume: "Bogdana", comuna: "Dragos Voda" },
  { nume: "Borcea" },
  { nume: "Boşneagu", simplu: "Bosneagu", comuna: "Dorobantu" },
  { nume: "Buciumeni", comuna: "Budesti" },
  { nume: "Budeşti", simplu: "Budesti" },
  { nume: "Buzoeni", comuna: "Lehliu Gara" },
  { nume: "Călăraşi", simplu: "Calarasi" },
  { nume: "Călăraşii Vechi", simplu: "Calarasii Vechi", comuna: "Cuza Voda" },
  { nume: "Călăreţi", simplu: "Calareti", comuna: "Tamadau Mare" },
  { nume: "Cândeasca", simplu: "Candeasca", comuna: "Belciugatele" },
  { nume: "Căscioarele", simplu: "Cascioarele" },
  { nume: "Ceacu", comuna: "Cuza Voda" },
  { nume: "Cetatea Veche", comuna: "Spantov" },
  { nume: "Chirnogi" },
  { nume: "Chirnogi", comuna: "Ulmu" },
  { nume: "Chiselet" },
  { nume: "Ciocăneşti", simplu: "Ciocanesti" },
  { nume: "Clăteşti", simplu: "Clatesti", comuna: "Mitreni" },
  { nume: "Coconi", comuna: "Manastirea" },
  { nume: "Codreni", comuna: "Gurbanesti" },
  { nume: "Cojeşti", simplu: "Cojesti", comuna: "Belciugatele" },
  {
    nume: "Constantin Brâncoveanu",
    simplu: "Constantin Brancoveanu",
    comuna: "Dragalina",
  },
  { nume: "Coslogeni", comuna: "Dichiseni" },
  { nume: "Coţofanca", simplu: "Cotofanca", comuna: "Gurbanesti" },
  { nume: "Crivăţ", simplu: "Crivat", comuna: "Budesti" },
  { nume: "Cucuieţi", simplu: "Cucuieti", comuna: "Plataresti" },
  { nume: "Cuneşti", simplu: "Cunesti", comuna: "Gradistea" },
  { nume: "Curăteşti", simplu: "Curatesti", comuna: "Frasinet" },
  { nume: "Curcani" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda" },
  { nume: "Dâlga-Gară", simplu: "Dalga-Gara", comuna: "Dor Marunt" },
  { nume: "Dâlga", simplu: "Dalga", comuna: "Dor Marunt" },
  { nume: "Dăneşti", simplu: "Danesti", comuna: "Frasinet" },
  { nume: "Dârvari", simplu: "Darvari", comuna: "Tamadau Mare" },
  { nume: "Dichiseni" },
  { nume: "Dor Mărunt", simplu: "Dor Marunt" },
  { nume: "Dorobanţu", simplu: "Dorobantu" },
  { nume: "Dorobanţu", simplu: "Dorobantu", comuna: "Plataresti" },
  { nume: "Dragalina" },
  { nume: "Dragoş Vodă", simplu: "Dragos Voda" },
  { nume: "Drajna Nouă", simplu: "Drajna Noua", comuna: "Dragalina" },
  {
    nume: "Fântâna Doamnei",
    simplu: "Fantana Doamnei",
    comuna: "Nicolae Balcescu",
  },
  { nume: "Făurei", simplu: "Faurei", comuna: "Ulmu" },
  { nume: "Florica", comuna: "Ileana" },
  { nume: "Floroaica", comuna: "Valcelele" },
  { nume: "Frăsinet", simplu: "Frasinet" },
  { nume: "Frăsinetu de Jos", simplu: "Frasinetu de Jos", comuna: "Frasinet" },
  { nume: "Frumuşani", simplu: "Frumusani" },
  { nume: "Fundeni" },
  { nume: "Fundulea" },
  { nume: "Gălăţui", simplu: "Galatui", comuna: "Alexandru Odobescu" },
  { nume: "Gălbinaşi", simplu: "Galbinasi", comuna: "Vasilati" },
  { nume: "Gâldău", simplu: "Galdau", comuna: "Jegalia" },
  { nume: "Gostilele", comuna: "Fundulea" },
  { nume: "Grădiştea", simplu: "Gradistea" },
  { nume: "Gruiu", comuna: "Budesti" },
  { nume: "Gurbăneşti", simplu: "Gurbanesti" },
  { nume: "Iezeru", comuna: "Jegalia" },
  { nume: "Ileana" },
  { nume: "Independenţa", simplu: "Independenta" },
  { nume: "Înfrăţirea", simplu: "Infratirea", comuna: "Dor Marunt" },
  { nume: "Jegălia", simplu: "Jegalia" },
  { nume: "Lehliu-Gară", simplu: "Lehliu-Gara", comuna: "Lehliu Gara" },
  { nume: "Lehliu" },
  { nume: "Libertatea", comuna: "Dichiseni" },
  { nume: "Luica" },
  { nume: "Lunca", comuna: "Valea Argovei" },
  { nume: "Lupşanu", simplu: "Lupsanu" },
  { nume: "Luptători", simplu: "Luptatori", comuna: "Frasinet" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Sarulesti" },
  { nume: "Mânăstirea", simplu: "Manastirea" },
  { nume: "Mărculeşti-Gară", simplu: "Marculesti-Gara", comuna: "Perisoru" },
  { nume: "Măriuţa", simplu: "Mariuta", comuna: "Belciugatele" },
  { nume: "Mataraua", comuna: "Belciugatele" },
  { nume: "Mihai Viteazu", comuna: "Vlad Tepes" },
  { nume: "Mitreni" },
  { nume: "Modelu" },
  { nume: "Nana" },
  { nume: "Negoeşti", simplu: "Negoesti", comuna: "Soldanu" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu" },
  {
    nume: "Nicolae Bălcescu",
    simplu: "Nicolae Balcescu",
    comuna: "Alexandru Odobescu",
  },
  { nume: "Nucetu", comuna: "Lupsanu" },
  { nume: "Nuci", comuna: "Vasilati" },
  { nume: "Ogoru", comuna: "Dor Marunt" },
  { nume: "Olteniţa", simplu: "Oltenita" },
  { nume: "Oltina", comuna: "Unirea" },
  { nume: "Orăşti", simplu: "Orasti", comuna: "Frumusani" },
  { nume: "Ostrovu", comuna: "Valea Argovei" },
  { nume: "Pădurişu", simplu: "Padurisu", comuna: "Frumusani" },
  { nume: "Paicu", comuna: "Nicolae Balcescu" },
  { nume: "Pasărea", simplu: "Pasarea", comuna: "Frumusani" },
  { nume: "Pelinu", comuna: "Dor Marunt" },
  { nume: "Perişoru", simplu: "Perisoru" },
  { nume: "Piţigaia", simplu: "Pitigaia", comuna: "Frumusani" },
  { nume: "Plătăreşti", simplu: "Plataresti" },
  { nume: "Plevna", comuna: "Lupsanu" },
  { nume: "Plumbuita", comuna: "Tamadau Mare" },
  { nume: "Podari", comuna: "Ileana" },
  { nume: "Podu Pitarului", comuna: "Plataresti" },
  { nume: "Polceşti", simplu: "Polcesti", comuna: "Sarulesti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Vasilati" },
  { nume: "Postăvari", simplu: "Postavari", comuna: "Frumusani" },
  { nume: "Potcoava", comuna: "Independenta" },
  { nume: "Preasna Veche", comuna: "Gurbanesti" },
  { nume: "Preasna", comuna: "Gurbanesti" },
  { nume: "Progresu", comuna: "Sohatu" },
  { nume: "Radovanu" },
  { nume: "Radu Negru", comuna: "Modelu" },
  { nume: "Radu Vodă", simplu: "Radu Voda", comuna: "Lupsanu" },
  { nume: "Rasa", comuna: "Gradistea" },
  { nume: "Răsurile", simplu: "Rasurile", comuna: "Ileana" },
  { nume: "Răzoarele", simplu: "Razoarele", comuna: "Ileana" },
  { nume: "Răzvani", simplu: "Razvani", comuna: "Lehliu Gara" },
  { nume: "Roseţi", simplu: "Roseti" },
  { nume: "Săcele", simplu: "Sacele", comuna: "Tamadau Mare" },
  { nume: "Sălcioara", simplu: "Salcioara", comuna: "Curcani" },
  { nume: "Sănduliţa", simplu: "Sandulita", comuna: "Sarulesti" },
  { nume: "Săpunari", simplu: "Sapunari", comuna: "Lehliu" },
  { nume: "Săruleşti-Gară", simplu: "Sarulesti-Gara", comuna: "Sarulesti" },
  { nume: "Săruleşti", simplu: "Sarulesti" },
  { nume: "Satnoeni", comuna: "Dichiseni" },
  { nume: "Satu Nou", comuna: "Ileana" },
  { nume: "Sătucu", simplu: "Satucu", comuna: "Sarulesti" },
  { nume: "Şeinoiu", simplu: "Seinoiu", comuna: "Tamadau Mare" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Valea Argovei" },
  { nume: "Socoalele", comuna: "Dragos Voda" },
  { nume: "Sohatu" },
  { nume: "Solacolu", comuna: "Sarulesti" },
  { nume: "Şoldanu", simplu: "Soldanu" },
  { nume: "Spanţov", simplu: "Spantov" },
  { nume: "Stancea", comuna: "Spantov" },
  { nume: "Ştefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Ştefan Vodă", simplu: "Stefan Voda" },
  { nume: "Ştefăneşti", simplu: "Stefanesti", comuna: "Ileana" },
  { nume: "Stoeneşti", simplu: "Stoenesti", comuna: "Modelu" },
  { nume: "Sultana", comuna: "Manastirea" },
  { nume: "Tămădău Mare", simplu: "Tamadau Mare" },
  { nume: "Tămădău Mic", simplu: "Tamadau Mic", comuna: "Tamadau Mare" },
  { nume: "Tăriceni", simplu: "Tariceni", comuna: "Frasinet" },
  { nume: "Tonea", comuna: "Modelu" },
  { nume: "Tudor Vladimirescu", comuna: "Perisoru" },
  { nume: "Ulmeni" },
  { nume: "Ulmu" },
  { nume: "Unirea" },
  { nume: "Vâlcelele", simplu: "Valcelele" },
  { nume: "Valea Argovei" },
  { nume: "Valea Popii", comuna: "Radovanu" },
  { nume: "Valea Presnei", comuna: "Gurbanesti" },
  { nume: "Valea Roşie", simplu: "Valea Rosie", comuna: "Mitreni" },
  { nume: "Valea Rusului", comuna: "Lupsanu" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Lehliu Gara" },
  { nume: "Valea Stânii", simplu: "Valea Stanii", comuna: "Luica" },
  { nume: "Vărăşti", simplu: "Varasti", comuna: "Dorobantu" },
  { nume: "Vasilaţi", simplu: "Vasilati" },
  { nume: "Vişinii", simplu: "Visinii", comuna: "Independenta" },
  { nume: "Vlad Ţepeş", simplu: "Vlad Tepes" },
  { nume: "Vlădiceasca", simplu: "Vladiceasca", comuna: "Valea Argovei" },
  { nume: "Vlăiculeşti", simplu: "Vlaiculesti", comuna: "Ileana" },
  { nume: "Zimbru", comuna: "Ulmu" },
];
