export const cj = [
  { nume: "Agârbiciu", simplu: "Agarbiciu", comuna: "Capusu Mare" },
  { nume: "Aghireșu-Fabrici", simplu: "Aghiresu-Fabrici", comuna: "Aghiresu" },
  { nume: "Aghireșu", simplu: "Aghiresu" },
  { nume: "Agriș", simplu: "Agris", comuna: "Iara" },
  { nume: "Aiton" },
  { nume: "Aluniș", simplu: "Alunis" },
  { nume: "Alunișu", simplu: "Alunisu", comuna: "Sancraiu" },
  { nume: "Andici", comuna: "Ceanu Mare" },
  { nume: "Antăș", simplu: "Antas", comuna: "Bobalna" },
  { nume: "Apahida" },
  { nume: "Ardeova", comuna: "Manastireni" },
  { nume: "Arghișu", simplu: "Arghisu", comuna: "Aghiresu" },
  { nume: "Aruncuta", comuna: "Suatu" },
  { nume: "Ășchileu Mare", simplu: "Aschileu Mare", comuna: "Aschileu" },
  { nume: "Ășchileu Mic", simplu: "Aschileu Mic", comuna: "Aschileu" },
  { nume: "Băbdiu", simplu: "Babdiu", comuna: "Bobalna" },
  { nume: "Băbuțiu", simplu: "Babutiu", comuna: "Vultureni" },
  { nume: "Baciu" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Moldovenesti" },
  { nume: "Bădești", simplu: "Badesti", comuna: "Vultureni" },
  { nume: "Băgaciu", simplu: "Bagaciu", comuna: "Palatca" },
  { nume: "Băgara", simplu: "Bagara", comuna: "Aghiresu" },
  { nume: "Băișoara", simplu: "Baisoara" },
  { nume: "Băița", simplu: "Baita", comuna: "Gherla" },
  { nume: "Bălcești", simplu: "Balcesti", comuna: "Belis" },
  { nume: "Bălcești", simplu: "Balcesti", comuna: "Capusu Mare" },
  { nume: "Bărăi", simplu: "Barai", comuna: "Caianu" },
  { nume: "Bârlea", simplu: "Barlea", comuna: "Cornesti" },
  { nume: "Batin", comuna: "Unguras" },
  { nume: "Bedeciu", comuna: "Manastireni" },
  { nume: "Beliș", simplu: "Belis" },
  { nume: "Berchieșu", simplu: "Berchiesu", comuna: "Frata" },
  { nume: "Berindu", comuna: "Sanpaul" },
  { nume: "Bica", comuna: "Manastireni" },
  { nume: "Bicălatu", simplu: "Bicalatu", comuna: "Huedin" },
  { nume: "Blidărești", simplu: "Blidaresti", comuna: "Bobalna" },
  { nume: "Bobâlna", simplu: "Bobalna" },
  { nume: "Bociu", comuna: "Margau" },
  { nume: "Bodrog", comuna: "Apahida" },
  { nume: "Bogata de Jos", comuna: "Vad" },
  { nume: "Bogata de Sus", comuna: "Vad" },
  { nume: "Bogata", comuna: "Calarasi" },
  { nume: "Boian", comuna: "Ceanu Mare" },
  { nume: "Boj-Cătun", simplu: "Boj-Catun", comuna: "Cojocna" },
  { nume: "Boju", comuna: "Cojocna" },
  { nume: "Bolduț", simplu: "Boldut", comuna: "Ceanu Mare" },
  { nume: "Bologa", comuna: "Poieni" },
  { nume: "Bonț", simplu: "Bont", comuna: "Fizesu Gherlii" },
  { nume: "Bonțida", simplu: "Bontida" },
  { nume: "Borșa-Cătun", simplu: "Borsa-Catun", comuna: "Borsa" },
  { nume: "Borșa-Crestaia", simplu: "Borsa-Crestaia", comuna: "Borsa" },
  { nume: "Borșa", simplu: "Borsa" },
  { nume: "Borzești", simplu: "Borzesti", comuna: "Iara" },
  { nume: "Boteni", comuna: "Mociu" },
  { nume: "Brăișoru", simplu: "Braisoru", comuna: "Sancraiu" },
  { nume: "Bucea", comuna: "Negreni" },
  { nume: "Bunești", simplu: "Bunesti", comuna: "Mintiu Gherlii" },
  { nume: "Buru", comuna: "Iara" },
  { nume: "Buteni", comuna: "Margau" },
  { nume: "Buza" },
  { nume: "Cacova Ierii", comuna: "Iara" },
  { nume: "Căianu Mic", simplu: "Caianu Mic", comuna: "Caianu" },
  { nume: "Căianu-Vamă", simplu: "Caianu-Vama", comuna: "Caianu" },
  { nume: "Căianu", simplu: "Caianu" },
  { nume: "Călărași-Gară", simplu: "Calarasi-Gara", comuna: "Calarasi" },
  { nume: "Călărași", simplu: "Calarasi" },
  { nume: "Călata", simplu: "Calata", comuna: "Calatele" },
  { nume: "Călățele", simplu: "Calatele" },
  { nume: "Calna", comuna: "Vad" },
  { nume: "Cămărașu", simplu: "Camarasu" },
  { nume: "Câmpenești", simplu: "Campenesti", comuna: "Apahida" },
  { nume: "Câmpia Turzii", simplu: "Campia Turzii" },
  { nume: "Căprioara", simplu: "Caprioara", comuna: "Recea-Cristur" },
  { nume: "Căpușu Mare", simplu: "Capusu Mare" },
  { nume: "Căpușu Mic", simplu: "Capusu Mic", comuna: "Capusu Mare" },
  { nume: "Cara", comuna: "Cojocna" },
  { nume: "Cășeiu", simplu: "Caseiu" },
  { nume: "Casele Micești", simplu: "Casele Micesti", comuna: "Feleacu" },
  { nume: "Cătălina", simplu: "Catalina", comuna: "Panticeu" },
  { nume: "Câțcău", simplu: "Catcau" },
  { nume: "Cătina", simplu: "Catina" },
  { nume: "Ceaba", comuna: "Sanmartin" },
  { nume: "Ceanu Mare" },
  { nume: "Ceanu Mic", comuna: "Tureni" },
  { nume: "Cerbești", simplu: "Cerbesti", comuna: "Poieni" },
  { nume: "Cerc", comuna: "Valea Ierii" },
  { nume: "Cetan", comuna: "Vad" },
  { nume: "Cheia", comuna: "Mihai Viteazu" },
  { nume: "Chesău", simplu: "Chesau", comuna: "Mociu" },
  { nume: "Chidea", comuna: "Vultureni" },
  { nume: "Chinteni" },
  { nume: "Chiriș", simplu: "Chiris", comuna: "Geaca" },
  { nume: "Chiuiești", simplu: "Chiuiesti" },
  { nume: "Ciubanca", comuna: "Recea-Cristur" },
  { nume: "Ciubăncuța", simplu: "Ciubancuta", comuna: "Recea-Cristur" },
  { nume: "Ciucea" },
  { nume: "Ciuleni", comuna: "Margau" },
  { nume: "Ciumăfaia", simplu: "Ciumafaia", comuna: "Borsa" },
  { nume: "Ciurgău", simplu: "Ciurgau", comuna: "Ceanu Mare" },
  { nume: "Ciurila" },
  { nume: "Clapa", comuna: "Tritenii De Jos" },
  { nume: "Cluj-Napoca" },
  { nume: "Coasta", comuna: "Bontida" },
  { nume: "Codor", comuna: "Jichisu De Jos" },
  { nume: "Cojocna" },
  { nume: "Colonia", comuna: "Tritenii De Jos" },
  { nume: "Comorâța", simplu: "Comorata", comuna: "Caseiu" },
  { nume: "Comșești", simplu: "Comsesti", comuna: "Tureni" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "Sandulesti" },
  { nume: "Coplean", comuna: "Caseiu" },
  { nume: "Copru", comuna: "Catina" },
  { nume: "Corneni", comuna: "Alunis" },
  { nume: "Cornești", simplu: "Cornesti" },
  { nume: "Cornești", simplu: "Cornesti", comuna: "Garbau" },
  { nume: "Cornești", simplu: "Cornesti", comuna: "Mihai Viteazu" },
  { nume: "Corpadea", comuna: "Apahida" },
  { nume: "Corușu", simplu: "Corusu", comuna: "Baciu" },
  { nume: "Crăești", simplu: "Craesti", comuna: "Petrestii De Jos" },
  { nume: "Crairât", simplu: "Crairat", comuna: "Ploscos" },
  { nume: "Cremenea", comuna: "Bobalna" },
  { nume: "Crișeni", simplu: "Criseni", comuna: "Mociu" },
  { nume: "Cristorel", comuna: "Aschileu" },
  { nume: "Cubleșu Someșan", simplu: "Cublesu Somesan", comuna: "Panticeu" },
  { nume: "Curtuiușu Dejului", simplu: "Curtuiusu Dejului", comuna: "Vad" },
  { nume: "Custura", comuna: "Caseiu" },
  { nume: "Cutca", comuna: "Sanmartin" },
  { nume: "Cuzdrioara" },
  { nume: "Dăbâca", simplu: "Dabaca" },
  { nume: "Dâmbu Mare", simplu: "Dambu Mare", comuna: "Mica" },
  { nume: "Dâmburile", simplu: "Damburile", comuna: "Suatu" },
  { nume: "Dâncu", simplu: "Dancu", comuna: "Aghiresu" },
  { nume: "Dângău Mare", simplu: "Dangau Mare", comuna: "Capusu Mare" },
  { nume: "Dângău Mic", simplu: "Dangau Mic", comuna: "Capusu Mare" },
  { nume: "Dârja", simplu: "Darja", comuna: "Panticeu" },
  { nume: "Daroț", simplu: "Darot", comuna: "Unguras" },
  { nume: "Dealu Botii", comuna: "Belis" },
  { nume: "Dealu Mare", comuna: "Risca" },
  { nume: "Dealu Negru", comuna: "Calatele" },
  { nume: "Dej" },
  { nume: "Deleni", comuna: "Petrestii De Jos" },
  { nume: "Deușu", simplu: "Deusu", comuna: "Chinteni" },
  { nume: "Dezmir", comuna: "Apahida" },
  { nume: "Diviciorii Mari", comuna: "Sanmartin" },
  { nume: "Diviciorii Mici", comuna: "Sanmartin" },
  { nume: "Domoșu", simplu: "Domosu", comuna: "Sancraiu" },
  { nume: "Dorna", comuna: "Aschileu" },
  { nume: "Dorolțu", simplu: "Doroltu", comuna: "Aghiresu" },
  { nume: "Dosu Bricii", comuna: "Chiuiesti" },
  { nume: "Dosu Napului", comuna: "Ceanu Mare" },
  { nume: "Dretea", comuna: "Manastireni" },
  { nume: "Dumbrava", comuna: "Capusu Mare" },
  { nume: "Elciu", comuna: "Recea-Cristur" },
  { nume: "Escu", comuna: "Recea-Cristur" },
  { nume: "Făgetu Ierii", simplu: "Fagetu Ierii", comuna: "Iara" },
  { nume: "Falca", comuna: "Mociu" },
  { nume: "Fânațe", simplu: "Fanate", comuna: "Ceanu Mare" },
  { nume: "Făureni", simplu: "Faureni", comuna: "Vultureni" },
  { nume: "Feiurdeni", comuna: "Chinteni" },
  { nume: "Feldioara", comuna: "Catina" },
  { nume: "Feleacu" },
  { nume: "Filea de Jos", comuna: "Ciurila" },
  { nume: "Filea de Sus", comuna: "Ciurila" },
  { nume: "Finciu", comuna: "Calatele" },
  { nume: "Finișel", simplu: "Finisel", comuna: "Savadisla" },
  { nume: "Fizeșu Gherlii", simplu: "Fizesu Gherlii" },
  { nume: "Florești", simplu: "Floresti" },
  { nume: "Fodora", comuna: "Aschileu" },
  { nume: "Frăsinet", simplu: "Frasinet", comuna: "Baisoara" },
  { nume: "Frata" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Iclod" },
  { nume: "Gădălin", simplu: "Gadalin", comuna: "Jucu" },
  { nume: "Gârbău Dejului", simplu: "Garbau Dejului", comuna: "Caseiu" },
  { nume: "Gârbău", simplu: "Garbau" },
  { nume: "Geaca" },
  { nume: "Gheorghieni", comuna: "Feleacu" },
  { nume: "Gherla" },
  { nume: "Ghirișu Român", simplu: "Ghirisu Roman", comuna: "Mociu" },
  { nume: "Ghirolt", comuna: "Alunis" },
  { nume: "Gilău", simplu: "Gilau" },
  { nume: "Giula", comuna: "Borsa" },
  { nume: "Giurcuța de Jos", simplu: "Giurcuta de Jos", comuna: "Belis" },
  { nume: "Giurcuța de Sus", simplu: "Giurcuta de Sus", comuna: "Belis" },
  { nume: "Gligorești", simplu: "Gligoresti", comuna: "Luna" },
  { nume: "Guga", comuna: "Caseiu" },
  { nume: "Hagău", simplu: "Hagau", comuna: "Catina" },
  { nume: "Hășdate", simplu: "Hasdate", comuna: "Gherla" },
  { nume: "Hășdate", simplu: "Hasdate", comuna: "Savadisla" },
  { nume: "Hodăi Boian", simplu: "Hodai Boian", comuna: "Ceanu Mare" },
  { nume: "Hodaie", comuna: "Catina" },
  { nume: "Hodișu", simplu: "Hodisu", comuna: "Poieni" },
  { nume: "Horlacea", comuna: "Sancraiu" },
  { nume: "Huci", comuna: "Cojocna" },
  { nume: "Huedin" },
  { nume: "Huta", comuna: "Chiuiesti" },
  { nume: "Iacobeni", comuna: "Ceanu Mare" },
  { nume: "Iara" },
  { nume: "Iclod" },
  { nume: "Iclozel", comuna: "Iclod" },
  { nume: "Igriția", simplu: "Igritia", comuna: "Cornesti" },
  { nume: "Inucu", comuna: "Aghiresu" },
  { nume: "Iuriu de Câmpie", simplu: "Iuriu de Campie", comuna: "Cojocna" },
  { nume: "Izvoru Crișului", simplu: "Izvoru Crisului" },
  { nume: "Jichișu de Jos", simplu: "Jichisu de Jos" },
  {
    nume: "Jichișu de Sus",
    simplu: "Jichisu de Sus",
    comuna: "Jichisu De Jos",
  },
  { nume: "Juc-Herghelie", comuna: "Jucu" },
  { nume: "Jucu de Mijloc", comuna: "Jucu" },
  { nume: "Jucu de Sus", comuna: "Jucu" },
  { nume: "Jurca", comuna: "Recea-Cristur" },
  { nume: "Lacu", comuna: "Geaca" },
  { nume: "Lăpuștești", simplu: "Lapustesti", comuna: "Risca" },
  { nume: "Leghia", comuna: "Aghiresu" },
  { nume: "Legii", comuna: "Geaca" },
  { nume: "Leurda", comuna: "Caseiu" },
  { nume: "Lita", comuna: "Savadisla" },
  { nume: "Liteni", comuna: "Savadisla" },
  { nume: "Livada", comuna: "Iclod" },
  { nume: "Livada", comuna: "Petrestii De Jos" },
  { nume: "Lobodaș", simplu: "Lobodas", comuna: "Ploscos" },
  { nume: "Lujerdiu", comuna: "Cornesti" },
  { nume: "Luna de Jos", comuna: "Dabaca" },
  { nume: "Luna de Sus", comuna: "Floresti" },
  { nume: "Luna" },
  {
    nume: "Lunca Bonțului",
    simplu: "Lunca Bontului",
    comuna: "Fizesu Gherlii",
  },
  { nume: "Lunca Vișagului", simplu: "Lunca Visagului", comuna: "Poieni" },
  { nume: "Luncani", comuna: "Luna" },
  { nume: "Lungești", simplu: "Lungesti", comuna: "Iara" },
  { nume: "Macău", simplu: "Macau", comuna: "Aghiresu" },
  { nume: "Măcicașu", simplu: "Macicasu", comuna: "Chinteni" },
  { nume: "Măgoaja", simplu: "Magoaja", comuna: "Chiuiesti" },
  { nume: "Măgura Ierii", simplu: "Magura Ierii", comuna: "Iara" },
  { nume: "Măguri-Răcătău", simplu: "Maguri-Racatau" },
  { nume: "Măguri", simplu: "Maguri", comuna: "Maguri-Racatau" },
  { nume: "Măhal", simplu: "Mahal", comuna: "Sanmartin" },
  { nume: "Maia", comuna: "Bobalna" },
  { nume: "Mănăstirea", simplu: "Manastirea", comuna: "Mica" },
  { nume: "Mănăstireni", simplu: "Manastireni" },
  { nume: "Mănășturel", simplu: "Manasturel", comuna: "Cuzdrioara" },
  {
    nume: "Mănășturu Românesc",
    simplu: "Manasturu Romanesc",
    comuna: "Manastireni",
  },
  { nume: "Mărcești", simplu: "Marcesti", comuna: "Risca" },
  { nume: "Mărgău", simplu: "Margau" },
  { nume: "Mărișel", simplu: "Marisel" },
  { nume: "Mărtinești", simplu: "Martinesti", comuna: "Tureni" },
  { nume: "Mașca", simplu: "Masca", comuna: "Iara" },
  { nume: "Mera", comuna: "Baciu" },
  { nume: "Mica" },
  { nume: "Micești", simplu: "Micesti", comuna: "Tureni" },
  { nume: "Mihai Viteazu" },
  { nume: "Mihăiești", simplu: "Mihaiesti", comuna: "Sanpaul" },
  { nume: "Mintiu Gherlii" },
  { nume: "Moara de Pădure", simplu: "Moara de Padure", comuna: "Baisoara" },
  { nume: "Mociu" },
  { nume: "Moldovenești", simplu: "Moldovenesti" },
  { nume: "Morău", simplu: "Morau", comuna: "Cornesti" },
  { nume: "Moriști", simplu: "Moristi", comuna: "Cojocna" },
  { nume: "Morlaca", comuna: "Poieni" },
  { nume: "Morțești", simplu: "Mortesti", comuna: "Ceanu Mare" },
  { nume: "Muncel", comuna: "Catcau" },
  { nume: "Muntele Băișorii", simplu: "Muntele Baisorii", comuna: "Baisoara" },
  { nume: "Muntele Bocului", comuna: "Baisoara" },
  { nume: "Muntele Cacovei", comuna: "Baisoara" },
  { nume: "Muntele Filii", comuna: "Baisoara" },
  { nume: "Muntele Rece", comuna: "Maguri-Racatau" },
  {
    nume: "Muntele Săcelului",
    simplu: "Muntele Sacelului",
    comuna: "Baisoara",
  },
  {
    nume: "Mureșenii de Câmpie",
    simplu: "Muresenii de Campie",
    comuna: "Palatca",
  },
  { nume: "Nădășelu", simplu: "Nadaselu", comuna: "Garbau" },
  { nume: "Nadășu", simplu: "Nadasu", comuna: "Izvoru Crisului" },
  { nume: "Năoiu", simplu: "Naoiu", comuna: "Camarasu" },
  { nume: "Năsal", simplu: "Nasal", comuna: "Taga" },
  { nume: "Nearșova", simplu: "Nearsova", comuna: "Izvoru Crisului" },
  { nume: "Negreni" },
  { nume: "Nicula", comuna: "Fizesu Gherlii" },
  { nume: "Nima", comuna: "Mintiu Gherlii" },
  { nume: "Nireș", simplu: "Nires", comuna: "Mica" },
  { nume: "Oaș", simplu: "Oas", comuna: "Frata" },
  { nume: "Ocna Dejului", comuna: "Dej" },
  { nume: "Ocolișel", simplu: "Ocolisel", comuna: "Iara" },
  { nume: "Olăriu", simplu: "Olariu", comuna: "Frata" },
  { nume: "Orman", comuna: "Iclod" },
  { nume: "Osoi", comuna: "Recea-Cristur" },
  { nume: "Oșorhel", simplu: "Osorhel", comuna: "Bobalna" },
  { nume: "Pădurea Iacobeni", simplu: "Padurea Iacobeni", comuna: "Frata" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Chinteni" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Ciurila" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Tritenii De Jos" },
  { nume: "Pădurenii", simplu: "Padurenii", comuna: "Mintiu Gherlii" },
  { nume: "Pâglișa", simplu: "Paglisa", comuna: "Dabaca" },
  { nume: "Pălatca", simplu: "Palatca" },
  { nume: "Păniceni", simplu: "Paniceni", comuna: "Capusu Mare" },
  { nume: "Panticeu" },
  { nume: "Pata", comuna: "Apahida" },
  { nume: "Peștera", simplu: "Pestera", comuna: "Dej" },
  { nume: "Petea", comuna: "Palatca" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Mintiu Gherlii" },
  { nume: "Petreștii de Jos", simplu: "Petrestii de Jos" },
  {
    nume: "Petreștii de Mijloc",
    simplu: "Petrestii de Mijloc",
    comuna: "Petrestii De Jos",
  },
  {
    nume: "Petreștii de Sus",
    simplu: "Petrestii de Sus",
    comuna: "Petrestii De Jos",
  },
  { nume: "Pietroasa", comuna: "Moldovenesti" },
  { nume: "Pintic", comuna: "Dej" },
  { nume: "Plăiești", simplu: "Plaiesti", comuna: "Moldovenesti" },
  { nume: "Plaiuri", comuna: "Petrestii De Jos" },
  { nume: "Plopi", comuna: "Valea Ierii" },
  { nume: "Ploscoș", simplu: "Ploscos" },
  { nume: "Podeni", comuna: "Moldovenesti" },
  { nume: "Poiana Frății", simplu: "Poiana Fratii", comuna: "Frata" },
  { nume: "Poiana Horea", comuna: "Belis" },
  { nume: "Poieni" },
  { nume: "Popești", simplu: "Popesti", comuna: "Baciu" },
  { nume: "Prelucele", comuna: "Negreni" },
  { nume: "Pruneni", comuna: "Alunis" },
  { nume: "Pruni", comuna: "Bobalna" },
  { nume: "Pruniș", simplu: "Prunis", comuna: "Ciurila" },
  { nume: "Puini", comuna: "Geaca" },
  { nume: "Pustuța", simplu: "Pustuta", comuna: "Recea-Cristur" },
  { nume: "Răchițele", simplu: "Rachitele", comuna: "Margau" },
  { nume: "Rădaia", simplu: "Radaia", comuna: "Baciu" },
  { nume: "Răscruci", simplu: "Rascruci", comuna: "Bontida" },
  { nume: "Răzbuneni", simplu: "Razbuneni", comuna: "Bobalna" },
  { nume: "Răzoare", simplu: "Razoare", comuna: "Frata" },
  { nume: "Recea-Cristur" },
  { nume: "Rediu", comuna: "Aiton" },
  { nume: "Rișca", simplu: "Risca" },
  { nume: "Rogojel", comuna: "Sacuieu" },
  { nume: "Roșieni", simplu: "Rosieni", comuna: "Mociu" },
  { nume: "Rotunda", comuna: "Buza" },
  { nume: "Rugășești", simplu: "Rugasesti", comuna: "Caseiu" },
  { nume: "Săcălaia", simplu: "Sacalaia", comuna: "Fizesu Gherlii" },
  { nume: "Săcel", simplu: "Sacel", comuna: "Baisoara" },
  { nume: "Săcuieu", simplu: "Sacuieu" },
  { nume: "Salatiu", comuna: "Mintiu Gherlii" },
  { nume: "Sălătruc", simplu: "Salatruc", comuna: "Caseiu" },
  { nume: "Sălicea", simplu: "Salicea", comuna: "Ciurila" },
  { nume: "Sălișca", simplu: "Salisca", comuna: "Catcau" },
  { nume: "Săliște", simplu: "Saliste", comuna: "Ciurila" },
  { nume: "Săliștea Nouă", simplu: "Salistea Noua", comuna: "Baciu" },
  { nume: "Săliștea Veche", simplu: "Salistea Veche", comuna: "Chinteni" },
  { nume: "Sâmboieni", simplu: "Samboieni", comuna: "Sanmartin" },
  { nume: "Sâmboleni", simplu: "Samboleni", comuna: "Camarasu" },
  { nume: "Sâncraiu", simplu: "Sancraiu" },
  { nume: "Săndulești", simplu: "Sandulesti" },
  { nume: "Sânmărghita", simplu: "Sanmarghita", comuna: "Mica" },
  { nume: "Sânmărtin", simplu: "Sanmartin" },
  { nume: "Sânmărtin", simplu: "Sanmartin", comuna: "Chinteni" },
  { nume: "Sânnicoară", simplu: "Sannicoara", comuna: "Apahida" },
  { nume: "Sânpaul", simplu: "Sanpaul" },
  { nume: "Sântejude Vale", simplu: "Santejude Vale", comuna: "Taga" },
  { nume: "Sântejude", simplu: "Santejude", comuna: "Taga" },
  { nume: "Sântioana", simplu: "Santioana", comuna: "Taga" },
  { nume: "Sărădiș", simplu: "Saradis", comuna: "Feleacu" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Panticeu" },
  { nume: "Șardu", simplu: "Sardu", comuna: "Sanpaul" },
  { nume: "Satu Lung", comuna: "Chinteni" },
  { nume: "Șaula", simplu: "Saula", comuna: "Izvoru Crisului" },
  { nume: "Sava", comuna: "Palatca" },
  { nume: "Săvădisla", simplu: "Savadisla" },
  { nume: "Scrind-Frăsinet", simplu: "Scrind-Frasinet", comuna: "Margau" },
  { nume: "Sic" },
  { nume: "Sicfa", comuna: "Unguras" },
  { nume: "Șigău", simplu: "Sigau", comuna: "Jichisu De Jos" },
  { nume: "Silivaș", simplu: "Silivas", comuna: "Gherla" },
  { nume: "Smida", comuna: "Belis" },
  { nume: "Șoimeni", simplu: "Soimeni", comuna: "Vultureni" },
  { nume: "Șomcutu Mic", simplu: "Somcutu Mic", comuna: "Dej" },
  { nume: "Someșu Cald", simplu: "Somesu Cald", comuna: "Gilau" },
  { nume: "Someșu Rece", simplu: "Somesu Rece", comuna: "Gilau" },
  { nume: "Soporu de Câmpie", simplu: "Soporu de Campie", comuna: "Frata" },
  { nume: "Stârcu", simplu: "Starcu", comuna: "Ceanu Mare" },
  { nume: "Stejeriș", simplu: "Stejeris", comuna: "Moldovenesti" },
  { nume: "Stoiana", comuna: "Cornesti" },
  { nume: "Stolna", comuna: "Savadisla" },
  { nume: "Straja", comuna: "Capusu Mare" },
  { nume: "Straja", comuna: "Cojocna" },
  { nume: "Strâmbu", simplu: "Strambu", comuna: "Chiuiesti" },
  { nume: "Strucut", comuna: "Ceanu Mare" },
  { nume: "Suarăș", simplu: "Suaras", comuna: "Bobalna" },
  { nume: "Suatu" },
  { nume: "Sub Coastă", simplu: "Sub Coasta", comuna: "Apahida" },
  { nume: "Suceagu", comuna: "Baciu" },
  { nume: "Sucutard", comuna: "Geaca" },
  { nume: "Sumurducu", comuna: "Sanpaul" },
  { nume: "Surduc", comuna: "Iara" },
  { nume: "Șutu", simplu: "Sutu", comuna: "Ciurila" },
  { nume: "Țaga", simplu: "Taga" },
  { nume: "Târgușor", simplu: "Targusor", comuna: "Sanmartin" },
  { nume: "Tărpiu", simplu: "Tarpiu", comuna: "Jichisu De Jos" },
  { nume: "Tăușeni", simplu: "Tauseni", comuna: "Bontida" },
  { nume: "Tăuți", simplu: "Tauti", comuna: "Floresti" },
  { nume: "Ticu-Colonie", comuna: "Aghiresu" },
  { nume: "Ticu", comuna: "Aghiresu" },
  { nume: "Tiocu de Jos", comuna: "Cornesti" },
  { nume: "Tiocu de Sus", comuna: "Cornesti" },
  { nume: "Tioltiur", comuna: "Cornesti" },
  { nume: "Topa Mică", simplu: "Topa Mica", comuna: "Sanpaul" },
  { nume: "Tranișu", simplu: "Tranisu", comuna: "Poieni" },
  { nume: "Tritenii de Jos" },
  { nume: "Tritenii de Sus", comuna: "Tritenii De Jos" },
  { nume: "Tritenii-Hotar", comuna: "Tritenii De Jos" },
  { nume: "Turda" },
  { nume: "Turea", comuna: "Garbau" },
  { nume: "Tureni" },
  { nume: "Turmași", simplu: "Turmasi", comuna: "Mociu" },
  { nume: "Unguraș", simplu: "Unguras" },
  { nume: "Urca", comuna: "Viisoara" },
  { nume: "Urișor", simplu: "Urisor", comuna: "Caseiu" },
  { nume: "Vad" },
  { nume: "Vaida-Cămăraș", simplu: "Vaida-Camaras", comuna: "Caianu" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Feleacu" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Bobalna" },
  { nume: "Vale", comuna: "Alunis" },
  { nume: "Valea Agrișului", simplu: "Valea Agrisului", comuna: "Iara" },
  { nume: "Valea Caldă", simplu: "Valea Calda", comuna: "Catina" },
  {
    nume: "Valea Cășeielului",
    simplu: "Valea Caseielului",
    comuna: "Chiuiesti",
  },
  { nume: "Valea Cireșoii", simplu: "Valea Ciresoii", comuna: "Mica" },
  { nume: "Valea Drăganului", simplu: "Valea Draganului", comuna: "Poieni" },
  { nume: "Valea Florilor", comuna: "Ploscos" },
  { nume: "Valea Gârboului", simplu: "Valea Garboului", comuna: "Cuzdrioara" },
  { nume: "Valea Groșilor", simplu: "Valea Grosilor", comuna: "Vad" },
  { nume: "Valea Ierii" },
  { nume: "Valea lui Cati", comuna: "Ceanu Mare" },
  { nume: "Valea lui Opriș", simplu: "Valea lui Opris", comuna: "Chiuiesti" },
  { nume: "Valea Luncii", comuna: "Mica" },
  { nume: "Valea Ungurașului", simplu: "Valea Ungurasului", comuna: "Unguras" },
  { nume: "Valea Vadului", comuna: "Iara" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Caianu" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Calatele" },
  { nume: "Vălișoara", simplu: "Valisoara", comuna: "Savadisla" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Ciucea" },
  { nume: "Vechea", comuna: "Chinteni" },
  { nume: "Viișoara", simplu: "Viisoara" },
  { nume: "Vișagu", simplu: "Visagu", comuna: "Sacuieu" },
  { nume: "Vișea", simplu: "Visea", comuna: "Jucu" },
  { nume: "Viștea", simplu: "Vistea", comuna: "Garbau" },
  { nume: "Vlaha", comuna: "Savadisla" },
  { nume: "Vultureni" },
  { nume: "Zorenii de Vale", comuna: "Mociu" },
];
