export const cj = [
  { nume: "Agârbiciu", simplu: "Agarbiciu", comuna: "Capusu Mare" },
  { nume: "Aghireşu-Fabrici", simplu: "Aghiresu-Fabrici", comuna: "Aghiresu" },
  { nume: "Aghireşu", simplu: "Aghiresu" },
  { nume: "Agriş", simplu: "Agris", comuna: "Iara" },
  { nume: "Aiton" },
  { nume: "Aluniş", simplu: "Alunis" },
  { nume: "Alunişu", simplu: "Alunisu", comuna: "Sancraiu" },
  { nume: "Andici", comuna: "Ceanu Mare" },
  { nume: "Antăş", simplu: "Antas", comuna: "Bobalna" },
  { nume: "Apahida" },
  { nume: "Ardeova", comuna: "Manastireni" },
  { nume: "Arghişu", simplu: "Arghisu", comuna: "Aghiresu" },
  { nume: "Aruncuta", comuna: "Suatu" },
  { nume: "Ăşchileu Mare", simplu: "Aschileu Mare", comuna: "Aschileu" },
  { nume: "Ăşchileu Mic", simplu: "Aschileu Mic", comuna: "Aschileu" },
  { nume: "Băbdiu", simplu: "Babdiu", comuna: "Bobalna" },
  { nume: "Băbuţiu", simplu: "Babutiu", comuna: "Vultureni" },
  { nume: "Baciu" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Moldovenesti" },
  { nume: "Bădeşti", simplu: "Badesti", comuna: "Vultureni" },
  { nume: "Băgaciu", simplu: "Bagaciu", comuna: "Palatca" },
  { nume: "Băgara", simplu: "Bagara", comuna: "Aghiresu" },
  { nume: "Băişoara", simplu: "Baisoara" },
  { nume: "Băiţa", simplu: "Baita", comuna: "Gherla" },
  { nume: "Bălceşti", simplu: "Balcesti", comuna: "Belis" },
  { nume: "Bălceşti", simplu: "Balcesti", comuna: "Capusu Mare" },
  { nume: "Bărăi", simplu: "Barai", comuna: "Caianu" },
  { nume: "Bârlea", simplu: "Barlea", comuna: "Cornesti" },
  { nume: "Batin", comuna: "Unguras" },
  { nume: "Bedeciu", comuna: "Manastireni" },
  { nume: "Beliş", simplu: "Belis" },
  { nume: "Berchieşu", simplu: "Berchiesu", comuna: "Frata" },
  { nume: "Berindu", comuna: "Sanpaul" },
  { nume: "Bica", comuna: "Manastireni" },
  { nume: "Bicălatu", simplu: "Bicalatu", comuna: "Huedin" },
  { nume: "Blidăreşti", simplu: "Blidaresti", comuna: "Bobalna" },
  { nume: "Bobâlna", simplu: "Bobalna" },
  { nume: "Bociu", comuna: "Margau" },
  { nume: "Bodrog", comuna: "Apahida" },
  { nume: "Bogata de Jos", comuna: "Vad" },
  { nume: "Bogata de Sus", comuna: "Vad" },
  { nume: "Bogata", comuna: "Calarasi" },
  { nume: "Boian", comuna: "Ceanu Mare" },
  { nume: "Boj-Cătun", simplu: "Boj-Catun", comuna: "Cojocna" },
  { nume: "Boju", comuna: "Cojocna" },
  { nume: "Bolduţ", simplu: "Boldut", comuna: "Ceanu Mare" },
  { nume: "Bologa", comuna: "Poieni" },
  { nume: "Bonţ", simplu: "Bont", comuna: "Fizesu Gherlii" },
  { nume: "Bonţida", simplu: "Bontida" },
  { nume: "Borşa-Cătun", simplu: "Borsa-Catun", comuna: "Borsa" },
  { nume: "Borşa-Crestaia", simplu: "Borsa-Crestaia", comuna: "Borsa" },
  { nume: "Borşa", simplu: "Borsa" },
  { nume: "Borzeşti", simplu: "Borzesti", comuna: "Iara" },
  { nume: "Boteni", comuna: "Mociu" },
  { nume: "Brăişoru", simplu: "Braisoru", comuna: "Sancraiu" },
  { nume: "Bucea", comuna: "Negreni" },
  { nume: "Buneşti", simplu: "Bunesti", comuna: "Mintiu Gherlii" },
  { nume: "Buru", comuna: "Iara" },
  { nume: "Buteni", comuna: "Margau" },
  { nume: "Buza" },
  { nume: "Cacova Ierii", comuna: "Iara" },
  { nume: "Căianu Mic", simplu: "Caianu Mic", comuna: "Caianu" },
  { nume: "Căianu-Vamă", simplu: "Caianu-Vama", comuna: "Caianu" },
  { nume: "Căianu", simplu: "Caianu" },
  { nume: "Călăraşi-Gară", simplu: "Calarasi-Gara", comuna: "Calarasi" },
  { nume: "Călăraşi", simplu: "Calarasi" },
  { nume: "Călata", simplu: "Calata", comuna: "Calatele" },
  { nume: "Călăţele", simplu: "Calatele" },
  { nume: "Calna", comuna: "Vad" },
  { nume: "Cămăraşu", simplu: "Camarasu" },
  { nume: "Câmpeneşti", simplu: "Campenesti", comuna: "Apahida" },
  { nume: "Câmpia Turzii", simplu: "Campia Turzii" },
  { nume: "Căprioara", simplu: "Caprioara", comuna: "Recea-Cristur" },
  { nume: "Căpuşu Mare", simplu: "Capusu Mare" },
  { nume: "Căpuşu Mic", simplu: "Capusu Mic", comuna: "Capusu Mare" },
  { nume: "Cara", comuna: "Cojocna" },
  { nume: "Căşeiu", simplu: "Caseiu" },
  { nume: "Casele Miceşti", simplu: "Casele Micesti", comuna: "Feleacu" },
  { nume: "Cătălina", simplu: "Catalina", comuna: "Panticeu" },
  { nume: "Câţcău", simplu: "Catcau" },
  { nume: "Cătina", simplu: "Catina" },
  { nume: "Ceaba", comuna: "Sanmartin" },
  { nume: "Ceanu Mare" },
  { nume: "Ceanu Mic", comuna: "Tureni" },
  { nume: "Cerbeşti", simplu: "Cerbesti", comuna: "Poieni" },
  { nume: "Cerc", comuna: "Valea Ierii" },
  { nume: "Cetan", comuna: "Vad" },
  { nume: "Cheia", comuna: "Mihai Viteazu" },
  { nume: "Chesău", simplu: "Chesau", comuna: "Mociu" },
  { nume: "Chidea", comuna: "Vultureni" },
  { nume: "Chinteni" },
  { nume: "Chiriş", simplu: "Chiris", comuna: "Geaca" },
  { nume: "Chiuieşti", simplu: "Chiuiesti" },
  { nume: "Ciubanca", comuna: "Recea-Cristur" },
  { nume: "Ciubăncuţa", simplu: "Ciubancuta", comuna: "Recea-Cristur" },
  { nume: "Ciucea" },
  { nume: "Ciuleni", comuna: "Margau" },
  { nume: "Ciumăfaia", simplu: "Ciumafaia", comuna: "Borsa" },
  { nume: "Ciurgău", simplu: "Ciurgau", comuna: "Ceanu Mare" },
  { nume: "Ciurila" },
  { nume: "Clapa", comuna: "Tritenii De Jos" },
  { nume: "Cluj-Napoca" },
  { nume: "Coasta", comuna: "Bontida" },
  { nume: "Codor", comuna: "Jichisu De Jos" },
  { nume: "Cojocna" },
  { nume: "Colonia", comuna: "Tritenii De Jos" },
  { nume: "Comorâţa", simplu: "Comorata", comuna: "Caseiu" },
  { nume: "Comşeşti", simplu: "Comsesti", comuna: "Tureni" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "Sandulesti" },
  { nume: "Coplean", comuna: "Caseiu" },
  { nume: "Copru", comuna: "Catina" },
  { nume: "Corneni", comuna: "Alunis" },
  { nume: "Corneşti", simplu: "Cornesti" },
  { nume: "Corneşti", simplu: "Cornesti", comuna: "Garbau" },
  { nume: "Corneşti", simplu: "Cornesti", comuna: "Mihai Viteazu" },
  { nume: "Corpadea", comuna: "Apahida" },
  { nume: "Coruşu", simplu: "Corusu", comuna: "Baciu" },
  { nume: "Crăeşti", simplu: "Craesti", comuna: "Petrestii De Jos" },
  { nume: "Crairât", simplu: "Crairat", comuna: "Ploscos" },
  { nume: "Cremenea", comuna: "Bobalna" },
  { nume: "Crişeni", simplu: "Criseni", comuna: "Mociu" },
  { nume: "Cristorel", comuna: "Aschileu" },
  { nume: "Cubleşu Someşan", simplu: "Cublesu Somesan", comuna: "Panticeu" },
  { nume: "Curtuiuşu Dejului", simplu: "Curtuiusu Dejului", comuna: "Vad" },
  { nume: "Custura", comuna: "Caseiu" },
  { nume: "Cutca", comuna: "Sanmartin" },
  { nume: "Cuzdrioara" },
  { nume: "Dăbâca", simplu: "Dabaca" },
  { nume: "Dâmbu Mare", simplu: "Dambu Mare", comuna: "Mica" },
  { nume: "Dâmburile", simplu: "Damburile", comuna: "Suatu" },
  { nume: "Dâncu", simplu: "Dancu", comuna: "Aghiresu" },
  { nume: "Dângău Mare", simplu: "Dangau Mare", comuna: "Capusu Mare" },
  { nume: "Dângău Mic", simplu: "Dangau Mic", comuna: "Capusu Mare" },
  { nume: "Dârja", simplu: "Darja", comuna: "Panticeu" },
  { nume: "Daroţ", simplu: "Darot", comuna: "Unguras" },
  { nume: "Dealu Botii", comuna: "Belis" },
  { nume: "Dealu Mare", comuna: "Risca" },
  { nume: "Dealu Negru", comuna: "Calatele" },
  { nume: "Dej" },
  { nume: "Deleni", comuna: "Petrestii De Jos" },
  { nume: "Deuşu", simplu: "Deusu", comuna: "Chinteni" },
  { nume: "Dezmir", comuna: "Apahida" },
  { nume: "Diviciorii Mari", comuna: "Sanmartin" },
  { nume: "Diviciorii Mici", comuna: "Sanmartin" },
  { nume: "Domoşu", simplu: "Domosu", comuna: "Sancraiu" },
  { nume: "Dorna", comuna: "Aschileu" },
  { nume: "Dorolţu", simplu: "Doroltu", comuna: "Aghiresu" },
  { nume: "Dosu Bricii", comuna: "Chiuiesti" },
  { nume: "Dosu Napului", comuna: "Ceanu Mare" },
  { nume: "Dretea", comuna: "Manastireni" },
  { nume: "Dumbrava", comuna: "Capusu Mare" },
  { nume: "Elciu", comuna: "Recea-Cristur" },
  { nume: "Escu", comuna: "Recea-Cristur" },
  { nume: "Făgetu Ierii", simplu: "Fagetu Ierii", comuna: "Iara" },
  { nume: "Falca", comuna: "Mociu" },
  { nume: "Fânaţe", simplu: "Fanate", comuna: "Ceanu Mare" },
  { nume: "Făureni", simplu: "Faureni", comuna: "Vultureni" },
  { nume: "Feiurdeni", comuna: "Chinteni" },
  { nume: "Feldioara", comuna: "Catina" },
  { nume: "Feleacu" },
  { nume: "Filea de Jos", comuna: "Ciurila" },
  { nume: "Filea de Sus", comuna: "Ciurila" },
  { nume: "Finciu", comuna: "Calatele" },
  { nume: "Finişel", simplu: "Finisel", comuna: "Savadisla" },
  { nume: "Fizeşu Gherlii", simplu: "Fizesu Gherlii" },
  { nume: "Floreşti", simplu: "Floresti" },
  { nume: "Fodora", comuna: "Aschileu" },
  { nume: "Frăsinet", simplu: "Frasinet", comuna: "Baisoara" },
  { nume: "Frata" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Iclod" },
  { nume: "Gădălin", simplu: "Gadalin", comuna: "Jucu" },
  { nume: "Gârbău Dejului", simplu: "Garbau Dejului", comuna: "Caseiu" },
  { nume: "Gârbău", simplu: "Garbau" },
  { nume: "Geaca" },
  { nume: "Gheorghieni", comuna: "Feleacu" },
  { nume: "Gherla" },
  { nume: "Ghirişu Român", simplu: "Ghirisu Roman", comuna: "Mociu" },
  { nume: "Ghirolt", comuna: "Alunis" },
  { nume: "Gilău", simplu: "Gilau" },
  { nume: "Giula", comuna: "Borsa" },
  { nume: "Giurcuţa de Jos", simplu: "Giurcuta de Jos", comuna: "Belis" },
  { nume: "Giurcuţa de Sus", simplu: "Giurcuta de Sus", comuna: "Belis" },
  { nume: "Gligoreşti", simplu: "Gligoresti", comuna: "Luna" },
  { nume: "Guga", comuna: "Caseiu" },
  { nume: "Hagău", simplu: "Hagau", comuna: "Catina" },
  { nume: "Hăşdate", simplu: "Hasdate", comuna: "Gherla" },
  { nume: "Hăşdate", simplu: "Hasdate", comuna: "Savadisla" },
  { nume: "Hodăi Boian", simplu: "Hodai Boian", comuna: "Ceanu Mare" },
  { nume: "Hodaie", comuna: "Catina" },
  { nume: "Hodişu", simplu: "Hodisu", comuna: "Poieni" },
  { nume: "Horlacea", comuna: "Sancraiu" },
  { nume: "Huci", comuna: "Cojocna" },
  { nume: "Huedin" },
  { nume: "Huta", comuna: "Chiuiesti" },
  { nume: "Iacobeni", comuna: "Ceanu Mare" },
  { nume: "Iara" },
  { nume: "Iclod" },
  { nume: "Iclozel", comuna: "Iclod" },
  { nume: "Igriţia", simplu: "Igritia", comuna: "Cornesti" },
  { nume: "Inucu", comuna: "Aghiresu" },
  { nume: "Iuriu de Câmpie", simplu: "Iuriu de Campie", comuna: "Cojocna" },
  { nume: "Izvoru Crişului", simplu: "Izvoru Crisului" },
  { nume: "Jichişu de Jos", simplu: "Jichisu de Jos" },
  {
    nume: "Jichişu de Sus",
    simplu: "Jichisu de Sus",
    comuna: "Jichisu De Jos",
  },
  { nume: "Juc-Herghelie", comuna: "Jucu" },
  { nume: "Jucu de Mijloc", comuna: "Jucu" },
  { nume: "Jucu de Sus", comuna: "Jucu" },
  { nume: "Jurca", comuna: "Recea-Cristur" },
  { nume: "Lacu", comuna: "Geaca" },
  { nume: "Lăpuşteşti", simplu: "Lapustesti", comuna: "Risca" },
  { nume: "Leghia", comuna: "Aghiresu" },
  { nume: "Legii", comuna: "Geaca" },
  { nume: "Leurda", comuna: "Caseiu" },
  { nume: "Lita", comuna: "Savadisla" },
  { nume: "Liteni", comuna: "Savadisla" },
  { nume: "Livada", comuna: "Iclod" },
  { nume: "Livada", comuna: "Petrestii De Jos" },
  { nume: "Lobodaş", simplu: "Lobodas", comuna: "Ploscos" },
  { nume: "Lujerdiu", comuna: "Cornesti" },
  { nume: "Luna de Jos", comuna: "Dabaca" },
  { nume: "Luna de Sus", comuna: "Floresti" },
  { nume: "Luna" },
  {
    nume: "Lunca Bonţului",
    simplu: "Lunca Bontului",
    comuna: "Fizesu Gherlii",
  },
  { nume: "Lunca Vişagului", simplu: "Lunca Visagului", comuna: "Poieni" },
  { nume: "Luncani", comuna: "Luna" },
  { nume: "Lungeşti", simplu: "Lungesti", comuna: "Iara" },
  { nume: "Macău", simplu: "Macau", comuna: "Aghiresu" },
  { nume: "Măcicaşu", simplu: "Macicasu", comuna: "Chinteni" },
  { nume: "Măgoaja", simplu: "Magoaja", comuna: "Chiuiesti" },
  { nume: "Măgura Ierii", simplu: "Magura Ierii", comuna: "Iara" },
  { nume: "Măguri-Răcătău", simplu: "Maguri-Racatau" },
  { nume: "Măguri", simplu: "Maguri", comuna: "Maguri-Racatau" },
  { nume: "Măhal", simplu: "Mahal", comuna: "Sanmartin" },
  { nume: "Maia", comuna: "Bobalna" },
  { nume: "Mănăstirea", simplu: "Manastirea", comuna: "Mica" },
  { nume: "Mănăstireni", simplu: "Manastireni" },
  { nume: "Mănăşturel", simplu: "Manasturel", comuna: "Cuzdrioara" },
  {
    nume: "Mănăşturu Românesc",
    simplu: "Manasturu Romanesc",
    comuna: "Manastireni",
  },
  { nume: "Mărceşti", simplu: "Marcesti", comuna: "Risca" },
  { nume: "Mărgău", simplu: "Margau" },
  { nume: "Mărişel", simplu: "Marisel" },
  { nume: "Mărtineşti", simplu: "Martinesti", comuna: "Tureni" },
  { nume: "Maşca", simplu: "Masca", comuna: "Iara" },
  { nume: "Mera", comuna: "Baciu" },
  { nume: "Mica" },
  { nume: "Miceşti", simplu: "Micesti", comuna: "Tureni" },
  { nume: "Mihai Viteazu" },
  { nume: "Mihăieşti", simplu: "Mihaiesti", comuna: "Sanpaul" },
  { nume: "Mintiu Gherlii" },
  { nume: "Moara de Pădure", simplu: "Moara de Padure", comuna: "Baisoara" },
  { nume: "Mociu" },
  { nume: "Moldoveneşti", simplu: "Moldovenesti" },
  { nume: "Morău", simplu: "Morau", comuna: "Cornesti" },
  { nume: "Morişti", simplu: "Moristi", comuna: "Cojocna" },
  { nume: "Morlaca", comuna: "Poieni" },
  { nume: "Morţeşti", simplu: "Mortesti", comuna: "Ceanu Mare" },
  { nume: "Muncel", comuna: "Catcau" },
  { nume: "Muntele Băişorii", simplu: "Muntele Baisorii", comuna: "Baisoara" },
  { nume: "Muntele Bocului", comuna: "Baisoara" },
  { nume: "Muntele Cacovei", comuna: "Baisoara" },
  { nume: "Muntele Filii", comuna: "Baisoara" },
  { nume: "Muntele Rece", comuna: "Maguri-Racatau" },
  {
    nume: "Muntele Săcelului",
    simplu: "Muntele Sacelului",
    comuna: "Baisoara",
  },
  {
    nume: "Mureşenii de Câmpie",
    simplu: "Muresenii de Campie",
    comuna: "Palatca",
  },
  { nume: "Nădăşelu", simplu: "Nadaselu", comuna: "Garbau" },
  { nume: "Nadăşu", simplu: "Nadasu", comuna: "Izvoru Crisului" },
  { nume: "Năoiu", simplu: "Naoiu", comuna: "Camarasu" },
  { nume: "Năsal", simplu: "Nasal", comuna: "Taga" },
  { nume: "Nearşova", simplu: "Nearsova", comuna: "Izvoru Crisului" },
  { nume: "Negreni" },
  { nume: "Nicula", comuna: "Fizesu Gherlii" },
  { nume: "Nima", comuna: "Mintiu Gherlii" },
  { nume: "Nireş", simplu: "Nires", comuna: "Mica" },
  { nume: "Oaş", simplu: "Oas", comuna: "Frata" },
  { nume: "Ocna Dejului", comuna: "Dej" },
  { nume: "Ocolişel", simplu: "Ocolisel", comuna: "Iara" },
  { nume: "Olăriu", simplu: "Olariu", comuna: "Frata" },
  { nume: "Orman", comuna: "Iclod" },
  { nume: "Osoi", comuna: "Recea-Cristur" },
  { nume: "Oşorhel", simplu: "Osorhel", comuna: "Bobalna" },
  { nume: "Pădurea Iacobeni", simplu: "Padurea Iacobeni", comuna: "Frata" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Chinteni" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Ciurila" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Tritenii De Jos" },
  { nume: "Pădurenii", simplu: "Padurenii", comuna: "Mintiu Gherlii" },
  { nume: "Pâglişa", simplu: "Paglisa", comuna: "Dabaca" },
  { nume: "Pălatca", simplu: "Palatca" },
  { nume: "Păniceni", simplu: "Paniceni", comuna: "Capusu Mare" },
  { nume: "Panticeu" },
  { nume: "Pata", comuna: "Apahida" },
  { nume: "Peştera", simplu: "Pestera", comuna: "Dej" },
  { nume: "Petea", comuna: "Palatca" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Mintiu Gherlii" },
  { nume: "Petreştii de Jos", simplu: "Petrestii de Jos" },
  {
    nume: "Petreştii de Mijloc",
    simplu: "Petrestii de Mijloc",
    comuna: "Petrestii De Jos",
  },
  {
    nume: "Petreştii de Sus",
    simplu: "Petrestii de Sus",
    comuna: "Petrestii De Jos",
  },
  { nume: "Pietroasa", comuna: "Moldovenesti" },
  { nume: "Pintic", comuna: "Dej" },
  { nume: "Plăieşti", simplu: "Plaiesti", comuna: "Moldovenesti" },
  { nume: "Plaiuri", comuna: "Petrestii De Jos" },
  { nume: "Plopi", comuna: "Valea Ierii" },
  { nume: "Ploscoş", simplu: "Ploscos" },
  { nume: "Podeni", comuna: "Moldovenesti" },
  { nume: "Poiana Frăţii", simplu: "Poiana Fratii", comuna: "Frata" },
  { nume: "Poiana Horea", comuna: "Belis" },
  { nume: "Poieni" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Baciu" },
  { nume: "Prelucele", comuna: "Negreni" },
  { nume: "Pruneni", comuna: "Alunis" },
  { nume: "Pruni", comuna: "Bobalna" },
  { nume: "Pruniş", simplu: "Prunis", comuna: "Ciurila" },
  { nume: "Puini", comuna: "Geaca" },
  { nume: "Pustuţa", simplu: "Pustuta", comuna: "Recea-Cristur" },
  { nume: "Răchiţele", simplu: "Rachitele", comuna: "Margau" },
  { nume: "Rădaia", simplu: "Radaia", comuna: "Baciu" },
  { nume: "Răscruci", simplu: "Rascruci", comuna: "Bontida" },
  { nume: "Răzbuneni", simplu: "Razbuneni", comuna: "Bobalna" },
  { nume: "Răzoare", simplu: "Razoare", comuna: "Frata" },
  { nume: "Recea-Cristur" },
  { nume: "Rediu", comuna: "Aiton" },
  { nume: "Rişca", simplu: "Risca" },
  { nume: "Rogojel", comuna: "Sacuieu" },
  { nume: "Roşieni", simplu: "Rosieni", comuna: "Mociu" },
  { nume: "Rotunda", comuna: "Buza" },
  { nume: "Rugăşeşti", simplu: "Rugasesti", comuna: "Caseiu" },
  { nume: "Săcălaia", simplu: "Sacalaia", comuna: "Fizesu Gherlii" },
  { nume: "Săcel", simplu: "Sacel", comuna: "Baisoara" },
  { nume: "Săcuieu", simplu: "Sacuieu" },
  { nume: "Salatiu", comuna: "Mintiu Gherlii" },
  { nume: "Sălătruc", simplu: "Salatruc", comuna: "Caseiu" },
  { nume: "Sălicea", simplu: "Salicea", comuna: "Ciurila" },
  { nume: "Sălişca", simplu: "Salisca", comuna: "Catcau" },
  { nume: "Sălişte", simplu: "Saliste", comuna: "Ciurila" },
  { nume: "Săliştea Nouă", simplu: "Salistea Noua", comuna: "Baciu" },
  { nume: "Săliştea Veche", simplu: "Salistea Veche", comuna: "Chinteni" },
  { nume: "Sâmboieni", simplu: "Samboieni", comuna: "Sanmartin" },
  { nume: "Sâmboleni", simplu: "Samboleni", comuna: "Camarasu" },
  { nume: "Sâncraiu", simplu: "Sancraiu" },
  { nume: "Sănduleşti", simplu: "Sandulesti" },
  { nume: "Sânmărghita", simplu: "Sanmarghita", comuna: "Mica" },
  { nume: "Sânmărtin", simplu: "Sanmartin" },
  { nume: "Sânmărtin", simplu: "Sanmartin", comuna: "Chinteni" },
  { nume: "Sânnicoară", simplu: "Sannicoara", comuna: "Apahida" },
  { nume: "Sânpaul", simplu: "Sanpaul" },
  { nume: "Sântejude Vale", simplu: "Santejude Vale", comuna: "Taga" },
  { nume: "Sântejude", simplu: "Santejude", comuna: "Taga" },
  { nume: "Sântioana", simplu: "Santioana", comuna: "Taga" },
  { nume: "Sărădiş", simplu: "Saradis", comuna: "Feleacu" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Panticeu" },
  { nume: "Şardu", simplu: "Sardu", comuna: "Sanpaul" },
  { nume: "Satu Lung", comuna: "Chinteni" },
  { nume: "Şaula", simplu: "Saula", comuna: "Izvoru Crisului" },
  { nume: "Sava", comuna: "Palatca" },
  { nume: "Săvădisla", simplu: "Savadisla" },
  { nume: "Scrind-Frăsinet", simplu: "Scrind-Frasinet", comuna: "Margau" },
  { nume: "Sic" },
  { nume: "Sicfa", comuna: "Unguras" },
  { nume: "Şigău", simplu: "Sigau", comuna: "Jichisu De Jos" },
  { nume: "Silivaş", simplu: "Silivas", comuna: "Gherla" },
  { nume: "Smida", comuna: "Belis" },
  { nume: "Şoimeni", simplu: "Soimeni", comuna: "Vultureni" },
  { nume: "Şomcutu Mic", simplu: "Somcutu Mic", comuna: "Dej" },
  { nume: "Someşu Cald", simplu: "Somesu Cald", comuna: "Gilau" },
  { nume: "Someşu Rece", simplu: "Somesu Rece", comuna: "Gilau" },
  { nume: "Soporu de Câmpie", simplu: "Soporu de Campie", comuna: "Frata" },
  { nume: "Stârcu", simplu: "Starcu", comuna: "Ceanu Mare" },
  { nume: "Stejeriş", simplu: "Stejeris", comuna: "Moldovenesti" },
  { nume: "Stoiana", comuna: "Cornesti" },
  { nume: "Stolna", comuna: "Savadisla" },
  { nume: "Straja", comuna: "Capusu Mare" },
  { nume: "Straja", comuna: "Cojocna" },
  { nume: "Strâmbu", simplu: "Strambu", comuna: "Chiuiesti" },
  { nume: "Strucut", comuna: "Ceanu Mare" },
  { nume: "Suarăş", simplu: "Suaras", comuna: "Bobalna" },
  { nume: "Suatu" },
  { nume: "Sub Coastă", simplu: "Sub Coasta", comuna: "Apahida" },
  { nume: "Suceagu", comuna: "Baciu" },
  { nume: "Sucutard", comuna: "Geaca" },
  { nume: "Sumurducu", comuna: "Sanpaul" },
  { nume: "Surduc", comuna: "Iara" },
  { nume: "Şutu", simplu: "Sutu", comuna: "Ciurila" },
  { nume: "Ţaga", simplu: "Taga" },
  { nume: "Târguşor", simplu: "Targusor", comuna: "Sanmartin" },
  { nume: "Tărpiu", simplu: "Tarpiu", comuna: "Jichisu De Jos" },
  { nume: "Tăuşeni", simplu: "Tauseni", comuna: "Bontida" },
  { nume: "Tăuţi", simplu: "Tauti", comuna: "Floresti" },
  { nume: "Ticu-Colonie", comuna: "Aghiresu" },
  { nume: "Ticu", comuna: "Aghiresu" },
  { nume: "Tiocu de Jos", comuna: "Cornesti" },
  { nume: "Tiocu de Sus", comuna: "Cornesti" },
  { nume: "Tioltiur", comuna: "Cornesti" },
  { nume: "Topa Mică", simplu: "Topa Mica", comuna: "Sanpaul" },
  { nume: "Tranişu", simplu: "Tranisu", comuna: "Poieni" },
  { nume: "Tritenii de Jos" },
  { nume: "Tritenii de Sus", comuna: "Tritenii De Jos" },
  { nume: "Tritenii-Hotar", comuna: "Tritenii De Jos" },
  { nume: "Turda" },
  { nume: "Turea", comuna: "Garbau" },
  { nume: "Tureni" },
  { nume: "Turmaşi", simplu: "Turmasi", comuna: "Mociu" },
  { nume: "Unguraş", simplu: "Unguras" },
  { nume: "Urca", comuna: "Viisoara" },
  { nume: "Urişor", simplu: "Urisor", comuna: "Caseiu" },
  { nume: "Vad" },
  { nume: "Vaida-Cămăraş", simplu: "Vaida-Camaras", comuna: "Caianu" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Feleacu" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Bobalna" },
  { nume: "Vale", comuna: "Alunis" },
  { nume: "Valea Agrişului", simplu: "Valea Agrisului", comuna: "Iara" },
  { nume: "Valea Caldă", simplu: "Valea Calda", comuna: "Catina" },
  {
    nume: "Valea Căşeielului",
    simplu: "Valea Caseielului",
    comuna: "Chiuiesti",
  },
  { nume: "Valea Cireşoii", simplu: "Valea Ciresoii", comuna: "Mica" },
  { nume: "Valea Drăganului", simplu: "Valea Draganului", comuna: "Poieni" },
  { nume: "Valea Florilor", comuna: "Ploscos" },
  { nume: "Valea Gârboului", simplu: "Valea Garboului", comuna: "Cuzdrioara" },
  { nume: "Valea Groşilor", simplu: "Valea Grosilor", comuna: "Vad" },
  { nume: "Valea Ierii" },
  { nume: "Valea lui Cati", comuna: "Ceanu Mare" },
  { nume: "Valea lui Opriş", simplu: "Valea lui Opris", comuna: "Chiuiesti" },
  { nume: "Valea Luncii", comuna: "Mica" },
  { nume: "Valea Unguraşului", simplu: "Valea Ungurasului", comuna: "Unguras" },
  { nume: "Valea Vadului", comuna: "Iara" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Caianu" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Calatele" },
  { nume: "Vălişoara", simplu: "Valisoara", comuna: "Savadisla" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Ciucea" },
  { nume: "Vechea", comuna: "Chinteni" },
  { nume: "Viişoara", simplu: "Viisoara" },
  { nume: "Vişagu", simplu: "Visagu", comuna: "Sacuieu" },
  { nume: "Vişea", simplu: "Visea", comuna: "Jucu" },
  { nume: "Viştea", simplu: "Vistea", comuna: "Garbau" },
  { nume: "Vlaha", comuna: "Savadisla" },
  { nume: "Vultureni" },
  { nume: "Zorenii de Vale", comuna: "Mociu" },
];
