export const ct = [
  { nume: "2 Mai", comuna: "Limanu" },
  { nume: "23 August" },
  { nume: "Abrud", comuna: "Adamclisi" },
  { nume: "Adamclisi" },
  { nume: "Agigea" },
  { nume: "Albești", simplu: "Albesti" },
  { nume: "Aliman" },
  { nume: "Almălău", simplu: "Almalau", comuna: "Ostrov" },
  { nume: "Amzacea" },
  { nume: "Arsa", comuna: "Albesti" },
  { nume: "Băltăgești", simplu: "Baltagesti", comuna: "Crucea" },
  { nume: "Băneasa", simplu: "Baneasa" },
  { nume: "Bărăganu", simplu: "Baraganu" },
  { nume: "Biruința", simplu: "Biruinta", comuna: "Topraisar" },
  { nume: "Brebeni", comuna: "Ion Corvin" },
  { nume: "Bugeac", comuna: "Ostrov" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Pantelimon" },
  { nume: "Canlia", comuna: "Lipnita" },
  { nume: "Cap Aurora", comuna: "Mangalia" },
  { nume: "Capidava", comuna: "Topalu" },
  { nume: "Carvăn", simplu: "Carvan", comuna: "Lipnita" },
  { nume: "Căscioarele", simplu: "Cascioarele", comuna: "Cerchezu" },
  { nume: "Casian", comuna: "Targusor" },
  { nume: "Casicea", comuna: "Amzacea" },
  { nume: "Castelu" },
  { nume: "Cerchezu" },
  { nume: "Cernavodă", simplu: "Cernavoda" },
  { nume: "Cetatea", comuna: "Dobromir" },
  { nume: "Cheia", comuna: "Targusor" },
  { nume: "Chirnogeni" },
  { nume: "Ciobănița", simplu: "Ciobanita", comuna: "Mereni" },
  { nume: "Ciobanu" },
  { nume: "Ciocârlia de Sus", simplu: "Ciocarlia de Sus", comuna: "Ciocarlia" },
  { nume: "Ciocârlia", simplu: "Ciocarlia" },
  { nume: "Cloșca", simplu: "Closca", comuna: "Horia" },
  { nume: "Cobadin" },
  { nume: "Cochirleni", comuna: "Rasova" },
  { nume: "Cogealac" },
  { nume: "Comana" },
  { nume: "Conacu", comuna: "Cobadin" },
  { nume: "Constanța", simplu: "Constanta" },
  { nume: "Corbu" },
  { nume: "Coroana", comuna: "Albesti" },
  { nume: "Coslugea", comuna: "Lipnita" },
  { nume: "Costinești", simplu: "Costinesti" },
  { nume: "Cotu Văii", simplu: "Cotu Vaii", comuna: "Albesti" },
  { nume: "Crângu", simplu: "Crangu", comuna: "Ion Corvin" },
  { nume: "Credința", simplu: "Credinta", comuna: "Chirnogeni" },
  { nume: "Crișan", simplu: "Crisan", comuna: "Crucea" },
  { nume: "Crucea" },
  { nume: "Cuiugiuc", comuna: "Lipnita" },
  { nume: "Cumpăna", simplu: "Cumpana" },
  { nume: "Curcani", comuna: "Cobadin" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Castelu" },
  { nume: "Darabani", comuna: "Negru Voda" },
  { nume: "Deleni" },
  { nume: "Dobromir" },
  { nume: "Dobromiru din Deal", comuna: "Dobromir" },
  { nume: "Dorobanțu", simplu: "Dorobantu", comuna: "Nicolae Balcescu" },
  { nume: "Dropia", comuna: "Tortoman" },
  { nume: "Dulcești", simplu: "Dulcesti", comuna: "23 August" },
  { nume: "Dulgheru", comuna: "Saraiu" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni" },
  { nume: "Dunărea", simplu: "Dunarea", comuna: "Seimeni" },
  { nume: "Dunăreni", simplu: "Dunareni", comuna: "Aliman" },
  { nume: "Eforie Nord", comuna: "Eforie" },
  { nume: "Eforie Sud", comuna: "Eforie" },
  { nume: "Esechioi", comuna: "Ostrov" },
  { nume: "Făclia", simplu: "Faclia", comuna: "Mircea Voda" },
  { nume: "Fântâna Mare", simplu: "Fantana Mare", comuna: "Independenta" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Cogealac" },
  { nume: "Făurei", simplu: "Faurei", comuna: "Baneasa" },
  { nume: "Floriile", comuna: "Aliman" },
  { nume: "Furnica", comuna: "Dumbraveni" },
  { nume: "Gălbiori", simplu: "Galbiori", comuna: "Crucea" },
  { nume: "Galița", simplu: "Galita", comuna: "Ostrov" },
  { nume: "Gârliciu", simplu: "Garliciu" },
  { nume: "Gârlița", simplu: "Garlita", comuna: "Ostrov" },
  {
    nume: "General Scărișoreanu",
    simplu: "General Scarisoreanu",
    comuna: "Amzacea",
  },
  { nume: "Gherghina", comuna: "Mircea Voda" },
  { nume: "Ghindărești", simplu: "Ghindaresti" },
  { nume: "Goruni", comuna: "Lipnita" },
  { nume: "Grădina", simplu: "Gradina", comuna: "Targusor" },
  { nume: "Grăniceru", simplu: "Graniceru", comuna: "Negru Voda" },
  { nume: "Gura Dobrogei", comuna: "Cogealac" },
  { nume: "Hagieni", comuna: "Limanu" },
  { nume: "Hârșova", simplu: "Harsova" },
  { nume: "Hațeg", simplu: "Hateg", comuna: "Adamclisi" },
  { nume: "Horia" },
  { nume: "Independența", simplu: "Independenta" },
  { nume: "Ion Corvin" },
  { nume: "Istria" },
  { nume: "Ivrinezu Mare", comuna: "Pestera" },
  { nume: "Ivrinezu Mic", comuna: "Pestera" },
  { nume: "Izvoarele", comuna: "Lipnita" },
  { nume: "Izvoru Mare", comuna: "Pestera" },
  { nume: "Jupiter", comuna: "Mangalia" },
  { nume: "Lanurile", comuna: "Baraganu" },
  { nume: "Lazu", comuna: "Agigea" },
  { nume: "Lespezi", comuna: "Dobromir" },
  { nume: "Limanu" },
  { nume: "Lipnița", simplu: "Lipnita" },
  { nume: "Lumina" },
  { nume: "Luminița", simplu: "Luminita", comuna: "Corbu" },
  { nume: "Măgura", simplu: "Magura", comuna: "Cerchezu" },
  { nume: "Mamaia-Sat", comuna: "Navodari" },
  { nume: "Mamaia", comuna: "Constanta" },
  { nume: "Mangalia" },
  { nume: "Medgidia" },
  { nume: "Mereni" },
  { nume: "Mihai Viteazu" },
  { nume: "Mihail Kogălniceanu", simplu: "Mihail Kogalniceanu" },
  { nume: "Miorița", simplu: "Miorita", comuna: "Ciobanu" },
  { nume: "Mircea Vodă", simplu: "Mircea Voda" },
  { nume: "Mireasa", comuna: "Targusor" },
  { nume: "Miriștea", simplu: "Miristea", comuna: "Mereni" },
  { nume: "Moșneni", simplu: "Mosneni", comuna: "23 August" },
  { nume: "Movila Verde", comuna: "Independenta" },
  { nume: "Movilița", simplu: "Movilita", comuna: "Topraisar" },
  { nume: "Murfatlar", comuna: "Basarabi" },
  { nume: "Năvodari", simplu: "Navodari" },
  { nume: "Nazarcea", comuna: "Poarta Alba" },
  { nume: "Negrești", simplu: "Negresti", comuna: "Cobadin" },
  { nume: "Negru Vodă", simplu: "Negru Voda" },
  { nume: "Negureni", comuna: "Baneasa" },
  { nume: "Neptun", comuna: "Mangalia" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu" },
  { nume: "Nisipari", comuna: "Castelu" },
  { nume: "Nistorești", simplu: "Nistoresti", comuna: "Pantelimon" },
  { nume: "Nuntași", simplu: "Nuntasi", comuna: "Istria" },
  { nume: "Oituz", comuna: "Lumina" },
  { nume: "Olimp", comuna: "Mangalia" },
  { nume: "Olteni", comuna: "Independenta" },
  { nume: "Oltina" },
  { nume: "Osmancea", comuna: "Mereni" },
  { nume: "Ostrov" },
  { nume: "Ovidiu" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Dobromir" },
  { nume: "Palazu Mare", comuna: "Constanta" },
  { nume: "Palazu Mic", comuna: "Mihail Kogalniceanu" },
  { nume: "Pantelimon de Jos", comuna: "Pantelimon" },
  { nume: "Pantelimon" },
  { nume: "Pecineaga" },
  { nume: "Pelinu", comuna: "Comana" },
  { nume: "Peștera", simplu: "Pestera" },
  { nume: "Petroșani", simplu: "Petrosani", comuna: "Deleni" },
  { nume: "Piatra", comuna: "Mihail Kogalniceanu" },
  { nume: "Pietreni", comuna: "Deleni" },
  { nume: "Plopeni", comuna: "Chirnogeni" },
  { nume: "Poarta Albă", simplu: "Poarta Alba" },
  { nume: "Poiana", comuna: "Ovidiu" },
  { nume: "Potârnichea", simplu: "Potarnichea", comuna: "Topraisar" },
  { nume: "Râmnicu de Jos", simplu: "Ramnicu de Jos", comuna: "Cogealac" },
  { nume: "Râmnicu de Sus", simplu: "Ramnicu de Sus", comuna: "Cogealac" },
  { nume: "Rariștea", simplu: "Raristea", comuna: "Ion Corvin" },
  { nume: "Rasova" },
  { nume: "Răzoarele", simplu: "Razoarele", comuna: "Oltina" },
  { nume: "Remus Opreanu", comuna: "Medgidia" },
  { nume: "Runcu", comuna: "Pantelimon" },
  { nume: "Săcele", simplu: "Sacele" },
  { nume: "Saligny", comuna: "Mircea Voda" },
  { nume: "Sanatoriul Agigea", comuna: "Agigea" },
  { nume: "Saraiu" },
  { nume: "Satu Nou", comuna: "Mircea Voda" },
  { nume: "Satu Nou", comuna: "Oltina" },
  { nume: "Saturn", comuna: "Mangalia" },
  { nume: "Schitu", comuna: "Costinesti" },
  { nume: "Seimeni" },
  { nume: "Seimenii Mici", comuna: "Seimeni" },
  { nume: "Sibioara", comuna: "Lumina" },
  { nume: "Siliștea", simplu: "Silistea" },
  { nume: "Siminoc", comuna: "Basarabi" },
  { nume: "Sinoie", comuna: "Mihai Viteazu" },
  { nume: "Șipotele", simplu: "Sipotele", comuna: "Deleni" },
  { nume: "Șiriu", simplu: "Siriu", comuna: "Crucea" },
  {
    nume: "Stațiunea Zoologică Marină Agigea",
    simplu: "Statiunea Zoologica Marina Agigea",
    comuna: "Agigea",
  },
  { nume: "Ștefan cel Mare", simplu: "Stefan cel Mare", comuna: "Mircea Voda" },
  { nume: "Stejaru", comuna: "Saraiu" },
  { nume: "Straja", comuna: "Cumpana" },
  { nume: "Strunga", comuna: "Oltina" },
  { nume: "Stupina", comuna: "Crucea" },
  { nume: "Târgușor", simplu: "Targusor" },
  { nume: "Tariverde", comuna: "Cogealac" },
  { nume: "Tătaru", simplu: "Tataru", comuna: "Comana" },
  { nume: "Techirghiol" },
  { nume: "Tepeș Vodă", simplu: "Tepes Voda", comuna: "Silistea" },
  { nume: "Țibrinu", simplu: "Tibrinu", comuna: "Mircea Voda" },
  { nume: "Tichilești", simplu: "Tichilesti", comuna: "Horia" },
  { nume: "Topalu" },
  { nume: "Topraisar" },
  { nume: "Tortoman" },
  { nume: "Traian", comuna: "Sacele" },
  { nume: "Tudor Vladimirescu", comuna: "Baneasa" },
  { nume: "Tufani", comuna: "Independenta" },
  { nume: "Tuzla" },
  { nume: "Urluia", comuna: "Adamclisi" },
  { nume: "Vadu Oii", comuna: "Harsova" },
  { nume: "Vadu", comuna: "Corbu" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Negru Voda" },
  { nume: "Valea Dacilor", comuna: "Medgidia" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Dobromir" },
  { nume: "Valu lui Traian" },
  { nume: "Vama Veche", comuna: "Limanu" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Pecineaga" },
  { nume: "Vârtop", simplu: "Vartop", comuna: "Albesti" },
  { nume: "Venus", comuna: "Mangalia" },
  { nume: "Veteranu", comuna: "Pestera" },
  { nume: "Viile", comuna: "Ion Corvin" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Cobadin" },
  { nume: "Viroaga", comuna: "Cerchezu" },
  { nume: "Vlahii", comuna: "Aliman" },
  { nume: "Vulturu" },
  { nume: "Zorile", comuna: "Adamclisi" },
];
