export const dj = [
  { nume: "Adâncata", simplu: "Adancata", comuna: "Goiesti" },
  { nume: "Afumaţi", simplu: "Afumati" },
  { nume: "Albeşti", simplu: "Albesti", comuna: "Simnicu De Sus" },
  { nume: "Almăj", simplu: "Almaj" },
  { nume: "Almăjel", simplu: "Almajel", comuna: "Filiasi" },
  { nume: "Amărăşti", simplu: "Amarasti", comuna: "Farcas" },
  { nume: "Amărăştii de Jos", simplu: "Amarastii de Jos" },
  { nume: "Amărăştii de Sus", simplu: "Amarastii de Sus" },
  { nume: "Apele Vii" },
  { nume: "Argetoaia" },
  { nume: "Bădoşi", simplu: "Badosi", comuna: "Bratovoesti" },
  { nume: "Băileşti", simplu: "Bailesti" },
  { nume: "Balasan", comuna: "Bailesti" },
  { nume: "Balota de Jos", comuna: "Murgasi" },
  { nume: "Balota de Sus", comuna: "Murgasi" },
  { nume: "Balta Verde", comuna: "Podari" },
  { nume: "Bâlta", simplu: "Balta", comuna: "Filiasi" },
  { nume: "Băranu", simplu: "Baranu", comuna: "Argetoaia" },
  { nume: "Bărboi", simplu: "Barboi", comuna: "Grecesti" },
  { nume: "Bârca", simplu: "Barca", comuna: "Birca" },
  { nume: "Basarabi", comuna: "Calafat" },
  { nume: "Başcov", simplu: "Bascov", comuna: "Sopot" },
  { nume: "Bâzdâna", simplu: "Bazdana", comuna: "Calopar" },
  { nume: "Bechet" },
  { nume: "Bechet", comuna: "Orodel" },
  { nume: "Beharca", comuna: "Almaj" },
  { nume: "Belcinu", comuna: "Calopar" },
  { nume: "Beloţ", simplu: "Belot", comuna: "Sopot" },
  { nume: "Beneşti", simplu: "Benesti", comuna: "Dragotesti" },
  { nume: "Berbeşu", simplu: "Berbesu", comuna: "Argetoaia" },
  { nume: "Bistreţ", simplu: "Bistret" },
  { nume: "Bistreţu Nou", simplu: "Bistretu Nou", comuna: "Bistret" },
  { nume: "Bobeanu", comuna: "Dragotesti" },
  { nume: "Bodăieşti", simplu: "Bodaiesti", comuna: "Melinesti" },
  {
    nume: "Bodăieştii de Sus",
    simplu: "Bodaiestii de Sus",
    comuna: "Melinesti",
  },
  { nume: "Bogea", comuna: "Almaj" },
  { nume: "Bojoiu", comuna: "Robanesti" },
  { nume: "Booveni", comuna: "Dranic" },
  { nume: "Botoşeşti-Paia", simplu: "Botosesti-Paia" },
  { nume: "Boureni", comuna: "Afumati" },
  { nume: "Brabeţi", simplu: "Brabeti", comuna: "Daneti" },
  { nume: "Brabova" },
  { nume: "Brădeşti", simplu: "Bradesti" },
  {
    nume: "Brădeştii Bătrâni",
    simplu: "Bradestii Batrani",
    comuna: "Bradesti",
  },
  { nume: "Braloştiţa", simplu: "Bralostita" },
  { nume: "Brânduşa", simplu: "Brandusa", comuna: "Bistret" },
  { nume: "Branişte", simplu: "Braniste", comuna: "Daneti" },
  { nume: "Branişte", simplu: "Braniste", comuna: "Filiasi" },
  { nume: "Branişte", simplu: "Braniste", comuna: "Podari" },
  { nume: "Bratovoeşti", simplu: "Bratovoesti" },
  { nume: "Breasta" },
  { nume: "Bucicani", comuna: "Predesti" },
  { nume: "Bucovăţ", simplu: "Bucovat" },
  { nume: "Bucovicior", comuna: "Vela" },
  { nume: "Bujor", comuna: "Varvoru De Jos" },
  { nume: "Bulzeşti", simplu: "Bulzesti" },
  { nume: "Buşteni", simplu: "Busteni", comuna: "Murgasi" },
  { nume: "Busu", comuna: "Grecesti" },
  { nume: "Busuleţu", simplu: "Busuletu", comuna: "Grecesti" },
  { nume: "Buzduc", comuna: "Dragotesti" },
  { nume: "Căciulăteşti", simplu: "Caciulatesti", comuna: "Dobresti" },
  { nume: "Căciulatu", simplu: "Caciulatu", comuna: "Terpezita" },
  { nume: "Calafat" },
  { nume: "Călăraşi", simplu: "Calarasi" },
  { nume: "Călineşti", simplu: "Calinesti", comuna: "Mischii" },
  { nume: "Calopăr", simplu: "Calopar" },
  { nume: "Călugărei", simplu: "Calugarei", comuna: "Orodel" },
  { nume: "Câmpeni", simplu: "Campeni", comuna: "Pielesti" },
  { nume: "Caraiman", comuna: "Brabova" },
  { nume: "Caraula" },
  { nume: "Cârcea", simplu: "Carcea", comuna: "Cosoveni" },
  { nume: "Cârligei", simplu: "Carligei", comuna: "Bucovat" },
  { nume: "Cârna", simplu: "Carna", comuna: "Goicea" },
  { nume: "Carpen" },
  { nume: "Cârstovani", simplu: "Carstovani", comuna: "Predesti" },
  { nume: "Căruia", simplu: "Caruia", comuna: "Terpezita" },
  { nume: "Castranova" },
  { nume: "Castrele Traiane", comuna: "Plenita" },
  { nume: "Catane", comuna: "Negoi" },
  { nume: "Catanele Noi", comuna: "Negoi" },
  { nume: "Celaru" },
  { nume: "Cerăt", simplu: "Cerat" },
  { nume: "Cernat", comuna: "Sopot" },
  { nume: "Cernăteşti", simplu: "Cernatesti" },
  { nume: "Cernele", comuna: "Craiova" },
  { nume: "Cernelele de Sus", comuna: "Craiova" },
  { nume: "Cetate" },
  { nume: "Cetăţuia", simplu: "Cetatuia", comuna: "Cioroiasi" },
  { nume: "Cetăţuia", simplu: "Cetatuia", comuna: "Vela" },
  { nume: "Chiaşu", simplu: "Chiasu", comuna: "Dabuleni" },
  { nume: "Ciocanele", comuna: "Bralostita" },
  { nume: "Ciocăneşti", simplu: "Ciocanesti", comuna: "Diosti" },
  { nume: "Cioroiaşi", simplu: "Cioroiasi" },
  { nume: "Cioroiu Nou", comuna: "Cioroiasi" },
  { nume: "Ciupercenii Noi" },
  { nume: "Ciupercenii Vechi", comuna: "Calafat" },
  { nume: "Ciutura", comuna: "Varvoru De Jos" },
  { nume: "Cleanov", comuna: "Carpen" },
  { nume: "Comănicea", simplu: "Comanicea", comuna: "Secu" },
  { nume: "Comoşteni", simplu: "Comosteni", comuna: "Gingiova" },
  { nume: "Corlate", comuna: "Izvoare" },
  { nume: "Cornetu", comuna: "Simnicu De Sus" },
  { nume: "Corniţa", simplu: "Cornita", comuna: "Cernatesti" },
  { nume: "Cornu", comuna: "Orodel" },
  { nume: "Coşereni", simplu: "Cosereni", comuna: "Teslui" },
  { nume: "Coşoveni", simplu: "Cosoveni" },
  { nume: "Coţofenii din Dos", simplu: "Cotofenii din Dos" },
  { nume: "Coţofenii din Faţă", simplu: "Cotofenii din Fata", comuna: "Almaj" },
  { nume: "Cotu", comuna: "Breasta" },
  { nume: "Covei", comuna: "Afumati" },
  { nume: "Craiova" },
  { nume: "Criva", comuna: "Varvoru De Jos" },
  { nume: "Crovna", comuna: "Breasta" },
  { nume: "Curmătura", simplu: "Curmatura", comuna: "Giurgita" },
  { nume: "Dăbuleni", simplu: "Dabuleni" },
  { nume: "Daneţi", simplu: "Daneti" },
  { nume: "Deleni", comuna: "Simnicu De Sus" },
  { nume: "Desa" },
  { nume: "Desnăţui", simplu: "Desnatui", comuna: "Vela" },
  { nume: "Dioşti", simplu: "Diosti" },
  { nume: "Dobreşti", simplu: "Dobresti" },
  { nume: "Dobridor", comuna: "Motatei" },
  { nume: "Dobromira", comuna: "Varvoru De Jos" },
  { nume: "Dobroteşti", simplu: "Dobrotesti", comuna: "Amarastii De Sus" },
  { nume: "Domnu Tudor", comuna: "Izvoare" },
  { nume: "Drăgoaia", simplu: "Dragoaia", comuna: "Varvoru De Jos" },
  { nume: "Drăgoteşti", simplu: "Dragotesti" },
  { nume: "Drănic", simplu: "Dranic" },
  { nume: "Dudoviceşti", simplu: "Dudovicesti", comuna: "Simnicu De Sus" },
  { nume: "Duţuleşti", simplu: "Dutulesti", comuna: "Simnicu De Sus" },
  { nume: "Făcăi", simplu: "Facai", comuna: "Craiova" },
  { nume: "Făget", simplu: "Faget", comuna: "Breasta" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Radovan" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Teslui" },
  { nume: "Fântâni", simplu: "Fantani", comuna: "Goiesti" },
  { nume: "Fărcaş", simplu: "Farcas" },
  { nume: "Filaret", comuna: "Giurgita" },
  { nume: "Filiaşi", simplu: "Filiasi" },
  { nume: "Floran", comuna: "Terpezita" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Simnicu De Sus" },
  { nume: "Foişor", simplu: "Foisor", comuna: "Dranic" },
  { nume: "Frasin", comuna: "Predesti" },
  { nume: "Frăţila", simplu: "Fratila", comuna: "Bulzesti" },
  { nume: "Fratoştiţa", simplu: "Fratostita", comuna: "Filiasi" },
  { nume: "Gabru", comuna: "Varvoru De Jos" },
  { nume: "Gaia", comuna: "Murgasi" },
  { nume: "Galicea Mare" },
  { nume: "Galiciuica", comuna: "Giubega" },
  { nume: "Gângiova", simplu: "Gangiova", comuna: "Gingiova" },
  { nume: "Gârleşti", simplu: "Garlesti", comuna: "Ghercesti" },
  { nume: "Gebleşti", simplu: "Geblesti", comuna: "Carpen" },
  { nume: "Georocel", comuna: "Dobresti" },
  { nume: "Georocu Mare", comuna: "Bratovoesti" },
  { nume: "Gherceşti", simplu: "Ghercesti" },
  { nume: "Ghidici", comuna: "Piscu Vechi" },
  { nume: "Ghindeni", comuna: "Malu Mare" },
  { nume: "Ghizdăveşti", simplu: "Ghizdavesti", comuna: "Celaru" },
  { nume: "Gighera" },
  { nume: "Giubega" },
  { nume: "Giurgiţa", simplu: "Giurgita" },
  { nume: "Godeni", comuna: "Melinesti" },
  { nume: "Gogoşeşti", simplu: "Gogosesti", comuna: "Mischii" },
  { nume: "Gogoşiţa", simplu: "Gogosita", comuna: "Gogosu" },
  { nume: "Gogoşu", simplu: "Gogosu" },
  { nume: "Goicea" },
  { nume: "Goieşti", simplu: "Goiesti" },
  { nume: "Golenţi", simplu: "Golenti", comuna: "Calafat" },
  { nume: "Golfin", comuna: "Robanesti" },
  { nume: "Golumbelu", comuna: "Farcas" },
  { nume: "Golumbu", comuna: "Farcas" },
  { nume: "Grădiştea", simplu: "Gradistea", comuna: "Grecesti" },
  { nume: "Greceşti", simplu: "Grecesti" },
  { nume: "Gropanele", comuna: "Grecesti" },
  { nume: "Gruiţa", simplu: "Gruita", comuna: "Goiesti" },
  { nume: "Gubaucea", comuna: "Vela" },
  { nume: "Gura Racului", comuna: "Bulzesti" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Podari" },
  { nume: "Horezu Poenari", comuna: "Valea Stanciului" },
  { nume: "Hunia", comuna: "Maglavit" },
  { nume: "Înfrăţirea", simplu: "Infratirea", comuna: "Bulzesti" },
  { nume: "Întorsura", simplu: "Intorsura", comuna: "Radovan" },
  { nume: "Iordăcheşti", simplu: "Iordachesti", comuna: "Argetoaia" },
  { nume: "Işalniţa", simplu: "Isalnita" },
  { nume: "Italieni", comuna: "Bucovat" },
  { nume: "Izvoare" },
  { nume: "Izvor", comuna: "Simnicu De Sus" },
  { nume: "Izvorul Rece", comuna: "Craiova" },
  { nume: "Jieni", comuna: "Simnicu De Sus" },
  { nume: "Jiul", comuna: "Tuglui" },
  { nume: "Lăcriţa Mare", simplu: "Lacrita Mare", comuna: "Robanesti" },
  { nume: "Lăcriţa Mică", simplu: "Lacrita Mica", comuna: "Robanesti" },
  { nume: "Lânga", simplu: "Langa", comuna: "Pielesti" },
  { nume: "Lazu", comuna: "Terpezita" },
  { nume: "Leamna de Jos", comuna: "Bucovat" },
  { nume: "Leamna de Sus", comuna: "Bucovat" },
  { nume: "Leordoasa", comuna: "Argetoaia" },
  { nume: "Leşile", simplu: "Lesile", comuna: "Simnicu De Sus" },
  { nume: "Leu" },
  { nume: "Lipovu de Sus", comuna: "Lipovu" },
  { nume: "Lipovu" },
  { nume: "Lişteava", simplu: "Listeava", comuna: "Ostroveni" },
  { nume: "Livezi", comuna: "Podari" },
  { nume: "Locusteni", comuna: "Daneti" },
  { nume: "Luncşoru", simplu: "Luncsoru", comuna: "Ghercesti" },
  { nume: "Măceşu de Jos", simplu: "Macesu de Jos" },
  { nume: "Măceşu de Sus", simplu: "Macesu de Sus" },
  { nume: "Maglavit" },
  { nume: "Mălăeşti", simplu: "Malaesti", comuna: "Goiesti" },
  { nume: "Malaica", comuna: "Cerat" },
  { nume: "Malu Mare" },
  { nume: "Malumnic", comuna: "Argetoaia" },
  { nume: "Mărăcinele", simplu: "Maracinele", comuna: "Perisor" },
  { nume: "Marotinu de Jos", comuna: "Celaru" },
  { nume: "Marotinu de Sus", comuna: "Celaru" },
  { nume: "Mârşani", simplu: "Marsani" },
  { nume: "Mârza", simplu: "Marza", comuna: "Salcuta" },
  { nume: "Melineşti", simplu: "Melinesti" },
  { nume: "Meteu", comuna: "Bradesti" },
  { nume: "Mihăiţa", simplu: "Mihaita", comuna: "Cotofenii Din Dos" },
  { nume: "Mileşti", simplu: "Milesti", comuna: "Simnicu De Sus" },
  { nume: "Milovan", comuna: "Predesti" },
  { nume: "Mischii" },
  { nume: "Mlecăneşti", simplu: "Mlecanesti", comuna: "Mischii" },
  { nume: "Mofleni", comuna: "Craiova" },
  { nume: "Mofleşti", simplu: "Moflesti", comuna: "Farcas" },
  { nume: "Mogoşeşti", simplu: "Mogosesti", comuna: "Goiesti" },
  { nume: "Moreni", comuna: "Cetate" },
  { nume: "Mosna", comuna: "Brabova" },
  { nume: "Moşneni", simplu: "Mosneni", comuna: "Almaj" },
  { nume: "Moţăţei Gară", simplu: "Motatei Gara", comuna: "Motatei" },
  { nume: "Moţăţei", simplu: "Motatei" },
  { nume: "Motoci", comuna: "Mischii" },
  { nume: "Muereni", comuna: "Goiesti" },
  { nume: "Muieruşu", simplu: "Muierusu", comuna: "Melinesti" },
  { nume: "Murgaşi", simplu: "Murgasi" },
  { nume: "Murta", comuna: "Dobresti" },
  { nume: "Nedeia", comuna: "Gighera" },
  { nume: "Negoi" },
  { nume: "Negoieşti", simplu: "Negoiesti", comuna: "Melinesti" },
  { nume: "Nisipuri", comuna: "Amarastii De Sus" },
  { nume: "Nistoi", comuna: "Farcas" },
  { nume: "Novac", comuna: "Argetoaia" },
  { nume: "Obedin", comuna: "Breasta" },
  { nume: "Ocolna", comuna: "Amarastii De Jos" },
  { nume: "Odoleni", comuna: "Melinesti" },
  { nume: "Ohaba", comuna: "Melinesti" },
  { nume: "Orodel" },
  { nume: "Ostroveni" },
  { nume: "Padea", comuna: "Dranic" },
  { nume: "Palilula", comuna: "Bucovat" },
  { nume: "Panaghia", comuna: "Calopar" },
  { nume: "Pereni", comuna: "Sopot" },
  { nume: "Perişor", simplu: "Perisor" },
  { nume: "Picăturile", simplu: "Picaturile", comuna: "Murgasi" },
  { nume: "Pieleşti", simplu: "Pielesti" },
  { nume: "Pietroaia", comuna: "Sopot" },
  { nume: "Pioreşti", simplu: "Pioresti", comuna: "Goiesti" },
  { nume: "Piria", comuna: "Argetoaia" },
  { nume: "Piscani", comuna: "Bradesti" },
  { nume: "Piscu Lung", comuna: "Bulzesti" },
  { nume: "Piscu Nou", comuna: "Seaca De Camp" },
  { nume: "Piscu Sadovei", comuna: "Sadova" },
  { nume: "Piscu Vechi" },
  { nume: "Pisculeţ", simplu: "Pisculet", comuna: "Piscu Vechi" },
  { nume: "Pleniţa", simplu: "Plenita" },
  { nume: "Pleşoi", simplu: "Plesoi", comuna: "Predesti" },
  { nume: "Plopşor", simplu: "Plopsor", comuna: "Salcuta" },
  { nume: "Plopu Amărăşti", simplu: "Plopu Amarasti", comuna: "Farcas" },
  { nume: "Plosca", comuna: "Bistret" },
  { nume: "Ploştina", simplu: "Plostina", comuna: "Melinesti" },
  { nume: "Podari" },
  { nume: "Poiana Fântânii", simplu: "Poiana Fantanii", comuna: "Argetoaia" },
  { nume: "Poiana Mare" },
  { nume: "Poienile", comuna: "Bulzesti" },
  { nume: "Pometeşti", simplu: "Pometesti", comuna: "Goiesti" },
  { nume: "Popânzăleşti", simplu: "Popanzalesti", comuna: "Dragotesti" },
  { nume: "Popeasa", comuna: "Goiesti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Melinesti" },
  { nume: "Popoveni", comuna: "Craiova" },
  { nume: "Potmelţu", simplu: "Potmeltu", comuna: "Cotofenii Din Dos" },
  { nume: "Prapor", comuna: "Amarastii De Jos" },
  { nume: "Preajba de Jos", comuna: "Teslui" },
  { nume: "Preajba de Pădure", simplu: "Preajba de Padure", comuna: "Teslui" },
  { nume: "Preajba", comuna: "Malu Mare" },
  { nume: "Predeşti", simplu: "Predesti" },
  { nume: "Predeştii Mici", simplu: "Predestii Mici", comuna: "Predesti" },
  { nume: "Prejoi", comuna: "Bulzesti" },
  { nume: "Prunet", comuna: "Bratovoesti" },
  { nume: "Puţinei", simplu: "Putinei", comuna: "Farcas" },
  { nume: "Puţuri", simplu: "Puturi", comuna: "Castranova" },
  { nume: "Răcarii de Jos", simplu: "Racarii de Jos", comuna: "Bradesti" },
  { nume: "Răcarii de Sus", simplu: "Racarii de Sus", comuna: "Filiasi" },
  { nume: "Răchita de Jos", simplu: "Rachita de Jos", comuna: "Brabova" },
  {
    nume: "Răchita de Sus",
    simplu: "Rachita de Sus",
    comuna: "Seaca De Padure",
  },
  { nume: "Racoviţa", simplu: "Racovita", comuna: "Bralostita" },
  { nume: "Radomir", comuna: "Diosti" },
  { nume: "Radovan" },
  { nume: "Rasnicu Bătrân", simplu: "Rasnicu Batran", comuna: "Cernatesti" },
  { nume: "Rasnicu Oghian", comuna: "Cernatesti" },
  { nume: "Rast" },
  {
    nume: "Robăneştii de Jos",
    simplu: "Robanestii de Jos",
    comuna: "Robanesti",
  },
  {
    nume: "Robăneştii de Sus",
    simplu: "Robanestii de Sus",
    comuna: "Robanesti",
  },
  { nume: "Rojişte", simplu: "Rojiste", comuna: "Bratovoesti" },
  { nume: "Româneşti", simplu: "Romanesti", comuna: "Simnicu De Sus" },
  { nume: "Roşieni", simplu: "Rosieni", comuna: "Breasta" },
  { nume: "Rovine", comuna: "Craiova" },
  { nume: "Rupturile", comuna: "Murgasi" },
  { nume: "Sadova" },
  { nume: "Salcia", comuna: "Argetoaia" },
  { nume: "Sălcuţa", simplu: "Salcuta" },
  { nume: "Sălcuţa", simplu: "Salcuta", comuna: "Calopar" },
  { nume: "Sălişte", simplu: "Saliste", comuna: "Bulzesti" },
  { nume: "Săpata", simplu: "Sapata", comuna: "Macesu De Jos" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Calarasi" },
  { nume: "Sărbătoarea", simplu: "Sarbatoarea", comuna: "Bucovat" },
  { nume: "Sârsca", simplu: "Sarsca", comuna: "Sopot" },
  { nume: "Scăeşti", simplu: "Scaesti" },
  { nume: "Schitu", comuna: "Bralostita" },
  { nume: "Seaca de Câmp", simplu: "Seaca de Camp" },
  { nume: "Seaca de Pădure", simplu: "Seaca de Padure" },
  { nume: "Secu" },
  { nume: "Secui", comuna: "Teasc" },
  { nume: "Seculeşti", simplu: "Seculesti", comuna: "Bulzesti" },
  { nume: "Segarcea" },
  { nume: "Segleţ", simplu: "Seglet", comuna: "Vela" },
  { nume: "Sfârcea", simplu: "Sfarcea", comuna: "Bralostita" },
  { nume: "Siliştea Crucii", simplu: "Silistea Crucii" },
  { nume: "Şimnicu de Jos", simplu: "Simnicu de Jos", comuna: "Craiova" },
  { nume: "Şimnicu de Sus", simplu: "Simnicu de Sus" },
  { nume: "Şitoaia", simplu: "Sitoaia", comuna: "Almaj" },
  { nume: "Smadovicioara de Secu", comuna: "Secu" },
  { nume: "Smârdan", simplu: "Smardan", comuna: "Ciupercenii Noi" },
  { nume: "Soceni", comuna: "Farcas" },
  { nume: "Sopot" },
  { nume: "Soreni", comuna: "Celaru" },
  { nume: "Spineni", comuna: "Melinesti" },
  { nume: "Ştefănel", simplu: "Stefanel", comuna: "Gogosu" },
  { nume: "Ştiubei", simplu: "Stiubei", comuna: "Vela" },
  { nume: "Stoiceşti", simplu: "Stoicesti", comuna: "Bulzesti" },
  { nume: "Suharu", comuna: "Vela" },
  { nume: "Şumandra", simplu: "Sumandra", comuna: "Secu" },
  { nume: "Tălpaş", simplu: "Talpas", comuna: "Farcas" },
  { nume: "Tâmbureşti", simplu: "Tamburesti", comuna: "Bratovoesti" },
  { nume: "Ţandăra", simplu: "Tandara", comuna: "Goiesti" },
  { nume: "Târnava", simplu: "Tarnava", comuna: "Radovan" },
  { nume: "Ţărţăl", simplu: "Tartal", comuna: "Teslui" },
  { nume: "Tatomireşti", simplu: "Tatomiresti", comuna: "Bradesti" },
  { nume: "Teasc" },
  { nume: "Teascu din Deal", comuna: "Argetoaia" },
  { nume: "Teiu", comuna: "Orodel" },
  { nume: "Tencănău", simplu: "Tencanau", comuna: "Salcuta" },
  { nume: "Terpeziţa", simplu: "Terpezita" },
  { nume: "Teslui" },
  { nume: "Ţiu", simplu: "Tiu", comuna: "Cernatesti" },
  { nume: "Toceni", comuna: "Dobresti" },
  { nume: "Ţuglui", simplu: "Tuglui" },
  { nume: "Tunarii Noi", comuna: "Poiana Mare" },
  { nume: "Tunarii Vechi", comuna: "Poiana Mare" },
  { nume: "Ungureni", comuna: "Ghercesti" },
  { nume: "Ungurenii Mici", comuna: "Ghercesti" },
  { nume: "Unirea" },
  { nume: "Urdiniţa", simplu: "Urdinita", comuna: "Brabova" },
  { nume: "Urecheşti", simplu: "Urechesti", comuna: "Mischii" },
  { nume: "Urieni", comuna: "Teslui" },
  { nume: "Ursoaia", comuna: "Argetoaia" },
  { nume: "Urzica Mare", comuna: "Urzicuta" },
  { nume: "Urzicuţa", simplu: "Urzicuta" },
  { nume: "Uscăci", simplu: "Uscaci", comuna: "Filiasi" },
  {
    nume: "Valea Fântânilor",
    simplu: "Valea Fantanilor",
    comuna: "Bralostita",
  },
  { nume: "Valea lui Pătru", simplu: "Valea lui Patru", comuna: "Scaesti" },
  { nume: "Valea Lungului", comuna: "Breasta" },
  { nume: "Valea Mare", comuna: "Melinesti" },
  { nume: "Valea Muierii de Jos", comuna: "Melinesti" },
  { nume: "Valea Stanciului" },
  { nume: "Vârtop", simplu: "Vartop" },
  { nume: "Vârvor", simplu: "Varvor", comuna: "Varvoru De Jos" },
  { nume: "Vârvoru de Jos", simplu: "Varvoru de Jos" },
  { nume: "Vela" },
  { nume: "Veleni", comuna: "Seaca De Padure" },
  { nume: "Velesti", comuna: "Murgasi" },
  { nume: "Verbicioara", comuna: "Verbita" },
  { nume: "Verbiţa", simplu: "Verbita" },
  { nume: "Viişoara Moşneni", simplu: "Viisoara Mosneni", comuna: "Teslui" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Dragotesti" },
  { nume: "Vladimir", comuna: "Goiesti" },
  { nume: "Voita", comuna: "Brabova" },
  { nume: "Zănoaga", simplu: "Zanoaga", comuna: "Leu" },
  { nume: "Zăval", simplu: "Zaval", comuna: "Gighera" },
  { nume: "Zlătari", simplu: "Zlatari", comuna: "Goiesti" },
  { nume: "Zvorsca", comuna: "Amarastii De Sus" },
];
