export const dj = [
  { nume: "Adâncata", simplu: "Adancata", comuna: "Goiesti" },
  { nume: "Afumați", simplu: "Afumati" },
  { nume: "Albești", simplu: "Albesti", comuna: "Simnicu De Sus" },
  { nume: "Almăj", simplu: "Almaj" },
  { nume: "Almăjel", simplu: "Almajel", comuna: "Filiasi" },
  { nume: "Amărăști", simplu: "Amarasti", comuna: "Farcas" },
  { nume: "Amărăștii de Jos", simplu: "Amarastii de Jos" },
  { nume: "Amărăștii de Sus", simplu: "Amarastii de Sus" },
  { nume: "Apele Vii" },
  { nume: "Argetoaia" },
  { nume: "Bădoși", simplu: "Badosi", comuna: "Bratovoesti" },
  { nume: "Băilești", simplu: "Bailesti" },
  { nume: "Balasan", comuna: "Bailesti" },
  { nume: "Balota de Jos", comuna: "Murgasi" },
  { nume: "Balota de Sus", comuna: "Murgasi" },
  { nume: "Balta Verde", comuna: "Podari" },
  { nume: "Bâlta", simplu: "Balta", comuna: "Filiasi" },
  { nume: "Băranu", simplu: "Baranu", comuna: "Argetoaia" },
  { nume: "Bărboi", simplu: "Barboi", comuna: "Grecesti" },
  { nume: "Bârca", simplu: "Barca", comuna: "Birca" },
  { nume: "Basarabi", comuna: "Calafat" },
  { nume: "Bașcov", simplu: "Bascov", comuna: "Sopot" },
  { nume: "Bâzdâna", simplu: "Bazdana", comuna: "Calopar" },
  { nume: "Bechet" },
  { nume: "Bechet", comuna: "Orodel" },
  { nume: "Beharca", comuna: "Almaj" },
  { nume: "Belcinu", comuna: "Calopar" },
  { nume: "Beloț", simplu: "Belot", comuna: "Sopot" },
  { nume: "Benești", simplu: "Benesti", comuna: "Dragotesti" },
  { nume: "Berbeșu", simplu: "Berbesu", comuna: "Argetoaia" },
  { nume: "Bistreț", simplu: "Bistret" },
  { nume: "Bistrețu Nou", simplu: "Bistretu Nou", comuna: "Bistret" },
  { nume: "Bobeanu", comuna: "Dragotesti" },
  { nume: "Bodăiești", simplu: "Bodaiesti", comuna: "Melinesti" },
  {
    nume: "Bodăieștii de Sus",
    simplu: "Bodaiestii de Sus",
    comuna: "Melinesti",
  },
  { nume: "Bogea", comuna: "Almaj" },
  { nume: "Bojoiu", comuna: "Robanesti" },
  { nume: "Booveni", comuna: "Dranic" },
  { nume: "Botoșești-Paia", simplu: "Botosesti-Paia" },
  { nume: "Boureni", comuna: "Afumati" },
  { nume: "Brabeți", simplu: "Brabeti", comuna: "Daneti" },
  { nume: "Brabova" },
  { nume: "Brădești", simplu: "Bradesti" },
  {
    nume: "Brădeștii Bătrâni",
    simplu: "Bradestii Batrani",
    comuna: "Bradesti",
  },
  { nume: "Braloștița", simplu: "Bralostita" },
  { nume: "Brândușa", simplu: "Brandusa", comuna: "Bistret" },
  { nume: "Braniște", simplu: "Braniste", comuna: "Daneti" },
  { nume: "Braniște", simplu: "Braniste", comuna: "Filiasi" },
  { nume: "Braniște", simplu: "Braniste", comuna: "Podari" },
  { nume: "Bratovoești", simplu: "Bratovoesti" },
  { nume: "Breasta" },
  { nume: "Bucicani", comuna: "Predesti" },
  { nume: "Bucovăț", simplu: "Bucovat" },
  { nume: "Bucovicior", comuna: "Vela" },
  { nume: "Bujor", comuna: "Varvoru De Jos" },
  { nume: "Bulzești", simplu: "Bulzesti" },
  { nume: "Bușteni", simplu: "Busteni", comuna: "Murgasi" },
  { nume: "Busu", comuna: "Grecesti" },
  { nume: "Busulețu", simplu: "Busuletu", comuna: "Grecesti" },
  { nume: "Buzduc", comuna: "Dragotesti" },
  { nume: "Căciulătești", simplu: "Caciulatesti", comuna: "Dobresti" },
  { nume: "Căciulatu", simplu: "Caciulatu", comuna: "Terpezita" },
  { nume: "Calafat" },
  { nume: "Călărași", simplu: "Calarasi" },
  { nume: "Călinești", simplu: "Calinesti", comuna: "Mischii" },
  { nume: "Calopăr", simplu: "Calopar" },
  { nume: "Călugărei", simplu: "Calugarei", comuna: "Orodel" },
  { nume: "Câmpeni", simplu: "Campeni", comuna: "Pielesti" },
  { nume: "Caraiman", comuna: "Brabova" },
  { nume: "Caraula" },
  { nume: "Cârcea", simplu: "Carcea", comuna: "Cosoveni" },
  { nume: "Cârligei", simplu: "Carligei", comuna: "Bucovat" },
  { nume: "Cârna", simplu: "Carna", comuna: "Goicea" },
  { nume: "Carpen" },
  { nume: "Cârstovani", simplu: "Carstovani", comuna: "Predesti" },
  { nume: "Căruia", simplu: "Caruia", comuna: "Terpezita" },
  { nume: "Castranova" },
  { nume: "Castrele Traiane", comuna: "Plenita" },
  { nume: "Catane", comuna: "Negoi" },
  { nume: "Catanele Noi", comuna: "Negoi" },
  { nume: "Celaru" },
  { nume: "Cerăt", simplu: "Cerat" },
  { nume: "Cernat", comuna: "Sopot" },
  { nume: "Cernătești", simplu: "Cernatesti" },
  { nume: "Cernele", comuna: "Craiova" },
  { nume: "Cernelele de Sus", comuna: "Craiova" },
  { nume: "Cetate" },
  { nume: "Cetățuia", simplu: "Cetatuia", comuna: "Cioroiasi" },
  { nume: "Cetățuia", simplu: "Cetatuia", comuna: "Vela" },
  { nume: "Chiașu", simplu: "Chiasu", comuna: "Dabuleni" },
  { nume: "Ciocanele", comuna: "Bralostita" },
  { nume: "Ciocănești", simplu: "Ciocanesti", comuna: "Diosti" },
  { nume: "Cioroiași", simplu: "Cioroiasi" },
  { nume: "Cioroiu Nou", comuna: "Cioroiasi" },
  { nume: "Ciupercenii Noi" },
  { nume: "Ciupercenii Vechi", comuna: "Calafat" },
  { nume: "Ciutura", comuna: "Varvoru De Jos" },
  { nume: "Cleanov", comuna: "Carpen" },
  { nume: "Comănicea", simplu: "Comanicea", comuna: "Secu" },
  { nume: "Comoșteni", simplu: "Comosteni", comuna: "Gingiova" },
  { nume: "Corlate", comuna: "Izvoare" },
  { nume: "Cornetu", comuna: "Simnicu De Sus" },
  { nume: "Cornița", simplu: "Cornita", comuna: "Cernatesti" },
  { nume: "Cornu", comuna: "Orodel" },
  { nume: "Coșereni", simplu: "Cosereni", comuna: "Teslui" },
  { nume: "Coșoveni", simplu: "Cosoveni" },
  { nume: "Coțofenii din Dos", simplu: "Cotofenii din Dos" },
  { nume: "Coțofenii din Față", simplu: "Cotofenii din Fata", comuna: "Almaj" },
  { nume: "Cotu", comuna: "Breasta" },
  { nume: "Covei", comuna: "Afumati" },
  { nume: "Craiova" },
  { nume: "Criva", comuna: "Varvoru De Jos" },
  { nume: "Crovna", comuna: "Breasta" },
  { nume: "Curmătura", simplu: "Curmatura", comuna: "Giurgita" },
  { nume: "Dăbuleni", simplu: "Dabuleni" },
  { nume: "Daneți", simplu: "Daneti" },
  { nume: "Deleni", comuna: "Simnicu De Sus" },
  { nume: "Desa" },
  { nume: "Desnățui", simplu: "Desnatui", comuna: "Vela" },
  { nume: "Dioști", simplu: "Diosti" },
  { nume: "Dobrești", simplu: "Dobresti" },
  { nume: "Dobridor", comuna: "Motatei" },
  { nume: "Dobromira", comuna: "Varvoru De Jos" },
  { nume: "Dobrotești", simplu: "Dobrotesti", comuna: "Amarastii De Sus" },
  { nume: "Domnu Tudor", comuna: "Izvoare" },
  { nume: "Drăgoaia", simplu: "Dragoaia", comuna: "Varvoru De Jos" },
  { nume: "Drăgotești", simplu: "Dragotesti" },
  { nume: "Drănic", simplu: "Dranic" },
  { nume: "Dudovicești", simplu: "Dudovicesti", comuna: "Simnicu De Sus" },
  { nume: "Duțulești", simplu: "Dutulesti", comuna: "Simnicu De Sus" },
  { nume: "Făcăi", simplu: "Facai", comuna: "Craiova" },
  { nume: "Făget", simplu: "Faget", comuna: "Breasta" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Radovan" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Teslui" },
  { nume: "Fântâni", simplu: "Fantani", comuna: "Goiesti" },
  { nume: "Fărcaș", simplu: "Farcas" },
  { nume: "Filaret", comuna: "Giurgita" },
  { nume: "Filiași", simplu: "Filiasi" },
  { nume: "Floran", comuna: "Terpezita" },
  { nume: "Florești", simplu: "Floresti", comuna: "Simnicu De Sus" },
  { nume: "Foișor", simplu: "Foisor", comuna: "Dranic" },
  { nume: "Frasin", comuna: "Predesti" },
  { nume: "Frățila", simplu: "Fratila", comuna: "Bulzesti" },
  { nume: "Fratoștița", simplu: "Fratostita", comuna: "Filiasi" },
  { nume: "Gabru", comuna: "Varvoru De Jos" },
  { nume: "Gaia", comuna: "Murgasi" },
  { nume: "Galicea Mare" },
  { nume: "Galiciuica", comuna: "Giubega" },
  { nume: "Gângiova", simplu: "Gangiova", comuna: "Gingiova" },
  { nume: "Gârlești", simplu: "Garlesti", comuna: "Ghercesti" },
  { nume: "Geblești", simplu: "Geblesti", comuna: "Carpen" },
  { nume: "Georocel", comuna: "Dobresti" },
  { nume: "Georocu Mare", comuna: "Bratovoesti" },
  { nume: "Ghercești", simplu: "Ghercesti" },
  { nume: "Ghidici", comuna: "Piscu Vechi" },
  { nume: "Ghindeni", comuna: "Malu Mare" },
  { nume: "Ghizdăvești", simplu: "Ghizdavesti", comuna: "Celaru" },
  { nume: "Gighera" },
  { nume: "Giubega" },
  { nume: "Giurgița", simplu: "Giurgita" },
  { nume: "Godeni", comuna: "Melinesti" },
  { nume: "Gogoșești", simplu: "Gogosesti", comuna: "Mischii" },
  { nume: "Gogoșița", simplu: "Gogosita", comuna: "Gogosu" },
  { nume: "Gogoșu", simplu: "Gogosu" },
  { nume: "Goicea" },
  { nume: "Goiești", simplu: "Goiesti" },
  { nume: "Golenți", simplu: "Golenti", comuna: "Calafat" },
  { nume: "Golfin", comuna: "Robanesti" },
  { nume: "Golumbelu", comuna: "Farcas" },
  { nume: "Golumbu", comuna: "Farcas" },
  { nume: "Grădiștea", simplu: "Gradistea", comuna: "Grecesti" },
  { nume: "Grecești", simplu: "Grecesti" },
  { nume: "Gropanele", comuna: "Grecesti" },
  { nume: "Gruița", simplu: "Gruita", comuna: "Goiesti" },
  { nume: "Gubaucea", comuna: "Vela" },
  { nume: "Gura Racului", comuna: "Bulzesti" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Podari" },
  { nume: "Horezu Poenari", comuna: "Valea Stanciului" },
  { nume: "Hunia", comuna: "Maglavit" },
  { nume: "Înfrățirea", simplu: "Infratirea", comuna: "Bulzesti" },
  { nume: "Întorsura", simplu: "Intorsura", comuna: "Radovan" },
  { nume: "Iordăchești", simplu: "Iordachesti", comuna: "Argetoaia" },
  { nume: "Ișalnița", simplu: "Isalnita" },
  { nume: "Italieni", comuna: "Bucovat" },
  { nume: "Izvoare" },
  { nume: "Izvor", comuna: "Simnicu De Sus" },
  { nume: "Izvorul Rece", comuna: "Craiova" },
  { nume: "Jieni", comuna: "Simnicu De Sus" },
  { nume: "Jiul", comuna: "Tuglui" },
  { nume: "Lăcrița Mare", simplu: "Lacrita Mare", comuna: "Robanesti" },
  { nume: "Lăcrița Mică", simplu: "Lacrita Mica", comuna: "Robanesti" },
  { nume: "Lânga", simplu: "Langa", comuna: "Pielesti" },
  { nume: "Lazu", comuna: "Terpezita" },
  { nume: "Leamna de Jos", comuna: "Bucovat" },
  { nume: "Leamna de Sus", comuna: "Bucovat" },
  { nume: "Leordoasa", comuna: "Argetoaia" },
  { nume: "Leșile", simplu: "Lesile", comuna: "Simnicu De Sus" },
  { nume: "Leu" },
  { nume: "Lipovu de Sus", comuna: "Lipovu" },
  { nume: "Lipovu" },
  { nume: "Lișteava", simplu: "Listeava", comuna: "Ostroveni" },
  { nume: "Livezi", comuna: "Podari" },
  { nume: "Locusteni", comuna: "Daneti" },
  { nume: "Luncșoru", simplu: "Luncsoru", comuna: "Ghercesti" },
  { nume: "Măceșu de Jos", simplu: "Macesu de Jos" },
  { nume: "Măceșu de Sus", simplu: "Macesu de Sus" },
  { nume: "Maglavit" },
  { nume: "Mălăești", simplu: "Malaesti", comuna: "Goiesti" },
  { nume: "Malaica", comuna: "Cerat" },
  { nume: "Malu Mare" },
  { nume: "Malumnic", comuna: "Argetoaia" },
  { nume: "Mărăcinele", simplu: "Maracinele", comuna: "Perisor" },
  { nume: "Marotinu de Jos", comuna: "Celaru" },
  { nume: "Marotinu de Sus", comuna: "Celaru" },
  { nume: "Mârșani", simplu: "Marsani" },
  { nume: "Mârza", simplu: "Marza", comuna: "Salcuta" },
  { nume: "Melinești", simplu: "Melinesti" },
  { nume: "Meteu", comuna: "Bradesti" },
  { nume: "Mihăița", simplu: "Mihaita", comuna: "Cotofenii Din Dos" },
  { nume: "Milești", simplu: "Milesti", comuna: "Simnicu De Sus" },
  { nume: "Milovan", comuna: "Predesti" },
  { nume: "Mischii" },
  { nume: "Mlecănești", simplu: "Mlecanesti", comuna: "Mischii" },
  { nume: "Mofleni", comuna: "Craiova" },
  { nume: "Moflești", simplu: "Moflesti", comuna: "Farcas" },
  { nume: "Mogoșești", simplu: "Mogosesti", comuna: "Goiesti" },
  { nume: "Moreni", comuna: "Cetate" },
  { nume: "Mosna", comuna: "Brabova" },
  { nume: "Moșneni", simplu: "Mosneni", comuna: "Almaj" },
  { nume: "Moțăței Gară", simplu: "Motatei Gara", comuna: "Motatei" },
  { nume: "Moțăței", simplu: "Motatei" },
  { nume: "Motoci", comuna: "Mischii" },
  { nume: "Muereni", comuna: "Goiesti" },
  { nume: "Muierușu", simplu: "Muierusu", comuna: "Melinesti" },
  { nume: "Murgași", simplu: "Murgasi" },
  { nume: "Murta", comuna: "Dobresti" },
  { nume: "Nedeia", comuna: "Gighera" },
  { nume: "Negoi" },
  { nume: "Negoiești", simplu: "Negoiesti", comuna: "Melinesti" },
  { nume: "Nisipuri", comuna: "Amarastii De Sus" },
  { nume: "Nistoi", comuna: "Farcas" },
  { nume: "Novac", comuna: "Argetoaia" },
  { nume: "Obedin", comuna: "Breasta" },
  { nume: "Ocolna", comuna: "Amarastii De Jos" },
  { nume: "Odoleni", comuna: "Melinesti" },
  { nume: "Ohaba", comuna: "Melinesti" },
  { nume: "Orodel" },
  { nume: "Ostroveni" },
  { nume: "Padea", comuna: "Dranic" },
  { nume: "Palilula", comuna: "Bucovat" },
  { nume: "Panaghia", comuna: "Calopar" },
  { nume: "Pereni", comuna: "Sopot" },
  { nume: "Perișor", simplu: "Perisor" },
  { nume: "Picăturile", simplu: "Picaturile", comuna: "Murgasi" },
  { nume: "Pielești", simplu: "Pielesti" },
  { nume: "Pietroaia", comuna: "Sopot" },
  { nume: "Piorești", simplu: "Pioresti", comuna: "Goiesti" },
  { nume: "Piria", comuna: "Argetoaia" },
  { nume: "Piscani", comuna: "Bradesti" },
  { nume: "Piscu Lung", comuna: "Bulzesti" },
  { nume: "Piscu Nou", comuna: "Seaca De Camp" },
  { nume: "Piscu Sadovei", comuna: "Sadova" },
  { nume: "Piscu Vechi" },
  { nume: "Pisculeț", simplu: "Pisculet", comuna: "Piscu Vechi" },
  { nume: "Plenița", simplu: "Plenita" },
  { nume: "Pleșoi", simplu: "Plesoi", comuna: "Predesti" },
  { nume: "Plopșor", simplu: "Plopsor", comuna: "Salcuta" },
  { nume: "Plopu Amărăști", simplu: "Plopu Amarasti", comuna: "Farcas" },
  { nume: "Plosca", comuna: "Bistret" },
  { nume: "Ploștina", simplu: "Plostina", comuna: "Melinesti" },
  { nume: "Podari" },
  { nume: "Poiana Fântânii", simplu: "Poiana Fantanii", comuna: "Argetoaia" },
  { nume: "Poiana Mare" },
  { nume: "Poienile", comuna: "Bulzesti" },
  { nume: "Pometești", simplu: "Pometesti", comuna: "Goiesti" },
  { nume: "Popânzălești", simplu: "Popanzalesti", comuna: "Dragotesti" },
  { nume: "Popeasa", comuna: "Goiesti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Melinesti" },
  { nume: "Popoveni", comuna: "Craiova" },
  { nume: "Potmelțu", simplu: "Potmeltu", comuna: "Cotofenii Din Dos" },
  { nume: "Prapor", comuna: "Amarastii De Jos" },
  { nume: "Preajba de Jos", comuna: "Teslui" },
  { nume: "Preajba de Pădure", simplu: "Preajba de Padure", comuna: "Teslui" },
  { nume: "Preajba", comuna: "Malu Mare" },
  { nume: "Predești", simplu: "Predesti" },
  { nume: "Predeștii Mici", simplu: "Predestii Mici", comuna: "Predesti" },
  { nume: "Prejoi", comuna: "Bulzesti" },
  { nume: "Prunet", comuna: "Bratovoesti" },
  { nume: "Puținei", simplu: "Putinei", comuna: "Farcas" },
  { nume: "Puțuri", simplu: "Puturi", comuna: "Castranova" },
  { nume: "Răcarii de Jos", simplu: "Racarii de Jos", comuna: "Bradesti" },
  { nume: "Răcarii de Sus", simplu: "Racarii de Sus", comuna: "Filiasi" },
  { nume: "Răchita de Jos", simplu: "Rachita de Jos", comuna: "Brabova" },
  {
    nume: "Răchita de Sus",
    simplu: "Rachita de Sus",
    comuna: "Seaca De Padure",
  },
  { nume: "Racovița", simplu: "Racovita", comuna: "Bralostita" },
  { nume: "Radomir", comuna: "Diosti" },
  { nume: "Radovan" },
  { nume: "Rasnicu Bătrân", simplu: "Rasnicu Batran", comuna: "Cernatesti" },
  { nume: "Rasnicu Oghian", comuna: "Cernatesti" },
  { nume: "Rast" },
  {
    nume: "Robăneștii de Jos",
    simplu: "Robanestii de Jos",
    comuna: "Robanesti",
  },
  {
    nume: "Robăneștii de Sus",
    simplu: "Robanestii de Sus",
    comuna: "Robanesti",
  },
  { nume: "Rojiște", simplu: "Rojiste", comuna: "Bratovoesti" },
  { nume: "Românești", simplu: "Romanesti", comuna: "Simnicu De Sus" },
  { nume: "Roșieni", simplu: "Rosieni", comuna: "Breasta" },
  { nume: "Rovine", comuna: "Craiova" },
  { nume: "Rupturile", comuna: "Murgasi" },
  { nume: "Sadova" },
  { nume: "Salcia", comuna: "Argetoaia" },
  { nume: "Sălcuța", simplu: "Salcuta" },
  { nume: "Sălcuța", simplu: "Salcuta", comuna: "Calopar" },
  { nume: "Săliște", simplu: "Saliste", comuna: "Bulzesti" },
  { nume: "Săpata", simplu: "Sapata", comuna: "Macesu De Jos" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Calarasi" },
  { nume: "Sărbătoarea", simplu: "Sarbatoarea", comuna: "Bucovat" },
  { nume: "Sârsca", simplu: "Sarsca", comuna: "Sopot" },
  { nume: "Scăești", simplu: "Scaesti" },
  { nume: "Schitu", comuna: "Bralostita" },
  { nume: "Seaca de Câmp", simplu: "Seaca de Camp" },
  { nume: "Seaca de Pădure", simplu: "Seaca de Padure" },
  { nume: "Secu" },
  { nume: "Secui", comuna: "Teasc" },
  { nume: "Seculești", simplu: "Seculesti", comuna: "Bulzesti" },
  { nume: "Segarcea" },
  { nume: "Segleț", simplu: "Seglet", comuna: "Vela" },
  { nume: "Sfârcea", simplu: "Sfarcea", comuna: "Bralostita" },
  { nume: "Siliștea Crucii", simplu: "Silistea Crucii" },
  { nume: "Șimnicu de Jos", simplu: "Simnicu de Jos", comuna: "Craiova" },
  { nume: "Șimnicu de Sus", simplu: "Simnicu de Sus" },
  { nume: "Șitoaia", simplu: "Sitoaia", comuna: "Almaj" },
  { nume: "Smadovicioara de Secu", comuna: "Secu" },
  { nume: "Smârdan", simplu: "Smardan", comuna: "Ciupercenii Noi" },
  { nume: "Soceni", comuna: "Farcas" },
  { nume: "Sopot" },
  { nume: "Soreni", comuna: "Celaru" },
  { nume: "Spineni", comuna: "Melinesti" },
  { nume: "Ștefănel", simplu: "Stefanel", comuna: "Gogosu" },
  { nume: "Știubei", simplu: "Stiubei", comuna: "Vela" },
  { nume: "Stoicești", simplu: "Stoicesti", comuna: "Bulzesti" },
  { nume: "Suharu", comuna: "Vela" },
  { nume: "Șumandra", simplu: "Sumandra", comuna: "Secu" },
  { nume: "Tălpaș", simplu: "Talpas", comuna: "Farcas" },
  { nume: "Tâmburești", simplu: "Tamburesti", comuna: "Bratovoesti" },
  { nume: "Țandăra", simplu: "Tandara", comuna: "Goiesti" },
  { nume: "Târnava", simplu: "Tarnava", comuna: "Radovan" },
  { nume: "Țărțăl", simplu: "Tartal", comuna: "Teslui" },
  { nume: "Tatomirești", simplu: "Tatomiresti", comuna: "Bradesti" },
  { nume: "Teasc" },
  { nume: "Teascu din Deal", comuna: "Argetoaia" },
  { nume: "Teiu", comuna: "Orodel" },
  { nume: "Tencănău", simplu: "Tencanau", comuna: "Salcuta" },
  { nume: "Terpezița", simplu: "Terpezita" },
  { nume: "Teslui" },
  { nume: "Țiu", simplu: "Tiu", comuna: "Cernatesti" },
  { nume: "Toceni", comuna: "Dobresti" },
  { nume: "Țuglui", simplu: "Tuglui" },
  { nume: "Tunarii Noi", comuna: "Poiana Mare" },
  { nume: "Tunarii Vechi", comuna: "Poiana Mare" },
  { nume: "Ungureni", comuna: "Ghercesti" },
  { nume: "Ungurenii Mici", comuna: "Ghercesti" },
  { nume: "Unirea" },
  { nume: "Urdinița", simplu: "Urdinita", comuna: "Brabova" },
  { nume: "Urechești", simplu: "Urechesti", comuna: "Mischii" },
  { nume: "Urieni", comuna: "Teslui" },
  { nume: "Ursoaia", comuna: "Argetoaia" },
  { nume: "Urzica Mare", comuna: "Urzicuta" },
  { nume: "Urzicuța", simplu: "Urzicuta" },
  { nume: "Uscăci", simplu: "Uscaci", comuna: "Filiasi" },
  {
    nume: "Valea Fântânilor",
    simplu: "Valea Fantanilor",
    comuna: "Bralostita",
  },
  { nume: "Valea lui Pătru", simplu: "Valea lui Patru", comuna: "Scaesti" },
  { nume: "Valea Lungului", comuna: "Breasta" },
  { nume: "Valea Mare", comuna: "Melinesti" },
  { nume: "Valea Muierii de Jos", comuna: "Melinesti" },
  { nume: "Valea Stanciului" },
  { nume: "Vârtop", simplu: "Vartop" },
  { nume: "Vârvor", simplu: "Varvor", comuna: "Varvoru De Jos" },
  { nume: "Vârvoru de Jos", simplu: "Varvoru de Jos" },
  { nume: "Vela" },
  { nume: "Veleni", comuna: "Seaca De Padure" },
  { nume: "Velesti", comuna: "Murgasi" },
  { nume: "Verbicioara", comuna: "Verbita" },
  { nume: "Verbița", simplu: "Verbita" },
  { nume: "Viișoara Moșneni", simplu: "Viisoara Mosneni", comuna: "Teslui" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Dragotesti" },
  { nume: "Vladimir", comuna: "Goiesti" },
  { nume: "Voita", comuna: "Brabova" },
  { nume: "Zănoaga", simplu: "Zanoaga", comuna: "Leu" },
  { nume: "Zăval", simplu: "Zaval", comuna: "Gighera" },
  { nume: "Zlătari", simplu: "Zlatari", comuna: "Goiesti" },
  { nume: "Zvorsca", comuna: "Amarastii De Sus" },
];
