export const db = [
  { nume: "Adânca", simplu: "Adanca", comuna: "Gura Ocnitei" },
  { nume: "Aluniş", simplu: "Alunis", comuna: "Barbuletu" },
  { nume: "Alunişu", simplu: "Alunisu", comuna: "Cornatelu" },
  { nume: "Aninoasa" },
  { nume: "Aninoşani", simplu: "Aninosani", comuna: "Candesti" },
  { nume: "Băceşti", simplu: "Bacesti", comuna: "Valea Lunga" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Runcu" },
  { nume: "Băduleşti", simplu: "Badulesti", comuna: "Crangurile" },
  { nume: "Bălăneşti", simplu: "Balanesti", comuna: "Racari" },
  { nume: "Bâldana", simplu: "Baldana", comuna: "Tartasesti" },
  { nume: "Băleni-Români", simplu: "Baleni-Romani", comuna: "Baleni" },
  { nume: "Băleni-Sârbi", simplu: "Baleni-Sarbi", comuna: "Baleni" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Contesti" },
  { nume: "Băneşti", simplu: "Banesti", comuna: "Salcioara" },
  { nume: "Bărăceni", simplu: "Baraceni", comuna: "Corbii Mari" },
  { nume: "Bărbuceanu", simplu: "Barbuceanu", comuna: "Butimanu" },
  { nume: "Bărbuleţu", simplu: "Barbuletu" },
  { nume: "Bechineşti", simplu: "Bechinesti", comuna: "Finta" },
  { nume: "Bela", comuna: "Pucioasa" },
  { nume: "Berevoeşti", simplu: "Berevoesti", comuna: "Fieni" },
  { nume: "Bezdead" },
  { nume: "Bilciureşti", simplu: "Bilciuresti" },
  { nume: "Blidari", comuna: "Cobia" },
  { nume: "Boboci", comuna: "Dragodana" },
  { nume: "Bolovani", comuna: "Cornatelu" },
  { nume: "Boteni", comuna: "Contesti" },
  { nume: "Brădăţel", simplu: "Bradatel", comuna: "Pucheni" },
  { nume: "Brâncoveanu", simplu: "Brancoveanu", comuna: "Odobesti" },
  { nume: "Brăneşti", simplu: "Branesti" },
  { nume: "Braniştea", simplu: "Branistea" },
  { nume: "Brăteştii de Jos", simplu: "Bratestii de Jos", comuna: "Vacaresti" },
  { nume: "Brebu", comuna: "Runcu" },
  { nume: "Brezoaele" },
  { nume: "Brezoaia", comuna: "Brezoaele" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Bezdead" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Produlesti" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Visina" },
  { nume: "Buciumeni" },
  { nume: "Bucşani", simplu: "Bucsani" },
  { nume: "Bujoreanca", comuna: "Cornesti" },
  { nume: "Bumbuia", comuna: "Gura Foii" },
  { nume: "Bungetu", comuna: "Vacaresti" },
  { nume: "Burduca", comuna: "Dragodana" },
  { nume: "Butimanu" },
  { nume: "Butoiu de Jos", comuna: "Hulubesti" },
  { nume: "Butoiu de Sus", comuna: "Hulubesti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Cobia" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Contesti" },
  { nume: "Cândeşti Deal", simplu: "Candesti Deal", comuna: "Candesti" },
  { nume: "Cândeşti-Vale", simplu: "Candesti-Vale", comuna: "Candesti" },
  { nume: "Căprioru", simplu: "Caprioru", comuna: "Tatarani" },
  { nume: "Căpşuna", simplu: "Capsuna", comuna: "Cobia" },
  { nume: "Capu Coastei", comuna: "Malu Cu Flori" },
  { nume: "Cârlăneşti", simplu: "Carlanesti", comuna: "Virfuri" },
  { nume: "Catanele", comuna: "Gura Foii" },
  { nume: "Cătunu", simplu: "Catunu", comuna: "Cornesti" },
  { nume: "Cătunu", simplu: "Catunu", comuna: "Salcioara" },
  { nume: "Cazaci", comuna: "Nucet" },
  { nume: "Cetăţuia", simplu: "Cetatuia", comuna: "Barbuletu" },
  { nume: "Chirca", comuna: "Mogosani" },
  { nume: "Ciocănari", simplu: "Ciocanari", comuna: "Niculesti" },
  { nume: "Ciocăneşti", simplu: "Ciocanesti" },
  { nume: "Coada Izvorului", comuna: "Petresti" },
  { nume: "Cobiuţa", simplu: "Cobiuta", comuna: "Cobia" },
  { nume: "Cocani", comuna: "Crevedia" },
  { nume: "Cojasca" },
  { nume: "Cojocaru", comuna: "Mogosani" },
  { nume: "Cojoiu", comuna: "Virfuri" },
  { nume: "Colacu", comuna: "Racari" },
  { nume: "Colanu", comuna: "Ulmi" },
  { nume: "Colibaşi", simplu: "Colibasi", comuna: "Iedera" },
  { nume: "Comişani", simplu: "Comisani" },
  { nume: "Conţeşti", simplu: "Contesti" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "Malu Cu Flori" },
  { nume: "Corbii Mari" },
  { nume: "Cornăţelu", simplu: "Cornatelu" },
  { nume: "Corneşti", simplu: "Cornesti" },
  { nume: "Corni", comuna: "Cornatelu" },
  { nume: "Costeşti", simplu: "Costesti", comuna: "Fieni" },
  {
    nume: "Costeştii din Deal",
    simplu: "Costestii din Deal",
    comuna: "Produlesti",
  },
  { nume: "Costeştii din Vale", simplu: "Costestii din Vale" },
  { nume: "Costişata", simplu: "Costisata", comuna: "Bezdead" },
  { nume: "Crăciuneşti", simplu: "Craciunesti", comuna: "Cobia" },
  { nume: "Crângaşi", simplu: "Crangasi", comuna: "Contesti" },
  {
    nume: "Crângurile de Jos",
    simplu: "Crangurile de Jos",
    comuna: "Crangurile",
  },
  {
    nume: "Crângurile de Sus",
    simplu: "Crangurile de Sus",
    comuna: "Crangurile",
  },
  { nume: "Creţu", simplu: "Cretu", comuna: "Ciocanesti" },
  { nume: "Creţuleşti", simplu: "Cretulesti", comuna: "Matasaru" },
  { nume: "Crevedia" },
  { nume: "Cricovu Dulce", comuna: "Iedera" },
  { nume: "Cristeasca", comuna: "Cornesti" },
  { nume: "Crivăţu", simplu: "Crivatu", comuna: "Cornesti" },
  { nume: "Croitori", comuna: "Uliesti" },
  { nume: "Crovu", comuna: "Odobesti" },
  { nume: "Cucuteni", comuna: "Motaieni" },
  { nume: "Cuparu", comuna: "Dragodana" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Salcioara" },
  { nume: "Dâmbovicioara", simplu: "Dambovicioara", comuna: "Branistea" },
  { nume: "Dărmăneşti", simplu: "Darmanesti" },
  { nume: "Dârza", simplu: "Darza", comuna: "Crevedia" },
  { nume: "Dealu Frumos", comuna: "Pietrosita" },
  { nume: "Dealu Mare", comuna: "Buciumeni" },
  { nume: "Decindea", comuna: "Ciocanesti" },
  { nume: "Decindeni", comuna: "Dragomiresti" },
  { nume: "Diaconeşti", simplu: "Diaconesti", comuna: "Pucioasa" },
  { nume: "Dimoiu", comuna: "Ulmi" },
  { nume: "Dobra" },
  { nume: "Dobreşti", simplu: "Dobresti", comuna: "Moroeni" },
  { nume: "Doiceşti", simplu: "Doicesti" },
  { nume: "Dospineşti", simplu: "Dospinesti", comuna: "Visinesti" },
  {
    nume: "Drăgăeşti Pământeni",
    simplu: "Dragaesti Pamanteni",
    comuna: "Manesti",
  },
  {
    nume: "Drăgăeşti Ungureni",
    simplu: "Dragaesti Ungureni",
    comuna: "Manesti",
  },
  { nume: "Dragodana" },
  { nume: "Dragodăneşti", simplu: "Dragodanesti", comuna: "Candesti" },
  { nume: "Dragomireşti", simplu: "Dragomiresti" },
  { nume: "Dumbrava", comuna: "Ulmi" },
  { nume: "După Deal", simplu: "Dupa Deal", comuna: "Barbuletu" },
  { nume: "Făgetu", simplu: "Fagetu", comuna: "Gura Foii" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Cojasca" },
  { nume: "Ferestre", comuna: "Runcu" },
  { nume: "Feţeni", simplu: "Feteni", comuna: "Valea Mare" },
  { nume: "Fieni" },
  { nume: "Fierbinţi", simplu: "Fierbinti", comuna: "Selaru" },
  { nume: "Finta Mare", comuna: "Finta" },
  { nume: "Finta Veche", comuna: "Finta" },
  { nume: "Frasin Deal", comuna: "Cobia" },
  { nume: "Frasin Vale", comuna: "Cobia" },
  { nume: "Frasinu", comuna: "Cornesti" },
  { nume: "Fusea", comuna: "Titu" },
  { nume: "Găeşti", simplu: "Gaesti" },
  { nume: "Gămăneşti", simplu: "Gamanesti", comuna: "Contesti" },
  { nume: "Gârleni", simplu: "Garleni", comuna: "Valea Mare" },
  { nume: "Geangoeşti", simplu: "Geangoesti", comuna: "Dragomiresti" },
  {
    nume: "Gemenea Brătuleşti",
    simplu: "Gemenea Bratulesti",
    comuna: "Voinesti",
  },
  { nume: "Gheboaia", comuna: "Finta" },
  { nume: "Gheboieni", comuna: "Tatarani" },
  { nume: "Ghergani", comuna: "Racari" },
  { nume: "Ghergheşti", simplu: "Gherghesti", comuna: "Petresti" },
  { nume: "Gherghiţeşti", simplu: "Gherghitesti", comuna: "Cobia" },
  { nume: "Ghimpaţi", simplu: "Ghimpati", comuna: "Racari" },
  { nume: "Ghineşti", simplu: "Ghinesti", comuna: "Salcioara" },
  { nume: "Ghirdoveni", comuna: "I. L. Caragiale" },
  { nume: "Glod", comuna: "Moroeni" },
  { nume: "Glodeni" },
  { nume: "Glodeni", comuna: "Pucioasa" },
  { nume: "Glogoveanu", comuna: "Selaru" },
  { nume: "Gorgota", comuna: "Razvad" },
  { nume: "Greci", comuna: "Petresti" },
  { nume: "Grozăveşti", simplu: "Grozavesti", comuna: "Corbii Mari" },
  { nume: "Gulia", comuna: "Tartasesti" },
  {
    nume: "Gura Bărbuleţului",
    simplu: "Gura Barbuletului",
    comuna: "Barbuletu",
  },
  { nume: "Gura Foii" },
  { nume: "Gura Ocniţei", simplu: "Gura Ocnitei" },
  { nume: "Gura Şuţii", simplu: "Gura Sutii" },
  { nume: "Gura Vulcanei", comuna: "Vulcana-Pandele" },
  { nume: "Guşoiu", simplu: "Gusoiu", comuna: "Glodeni" },
  { nume: "Hăbeni", simplu: "Habeni", comuna: "Bucsani" },
  { nume: "Hagioaica", comuna: "Titu" },
  { nume: "Hanu lui Pală", simplu: "Hanu lui Pala", comuna: "Uliesti" },
  { nume: "Heleşteu", simplu: "Helesteu", comuna: "Contesti" },
  { nume: "Hodărăşti", simplu: "Hodarasti", comuna: "Cornesti" },
  { nume: "Hulubeşti", simplu: "Hulubesti" },
  { nume: "I. L. Caragiale" },
  { nume: "Iazu", comuna: "Cojasca" },
  { nume: "Ibrianu", comuna: "Cornesti" },
  { nume: "Iedera de Jos", comuna: "Iedera" },
  { nume: "Iedera de Sus", comuna: "Iedera" },
  { nume: "Ilfoveni", comuna: "Nucet" },
  { nume: "Ioneşti", simplu: "Ionesti", comuna: "Petresti" },
  { nume: "Izvoarele", comuna: "Voinesti" },
  { nume: "Izvoru", comuna: "Valea Lunga" },
  { nume: "Izvoru", comuna: "Visina" },
  { nume: "Jugureni", comuna: "Uliesti" },
  { nume: "Lăculeţe-Gară", simplu: "Laculete-Gara", comuna: "Vulcana-Pandele" },
  { nume: "Lăculeţe", simplu: "Laculete", comuna: "Glodeni" },
  { nume: "Lazuri", comuna: "Comisani" },
  { nume: "Livezile", comuna: "Glodeni" },
  { nume: "Livezile", comuna: "Valea Mare" },
  { nume: "Lucianca", comuna: "Butimanu" },
  { nume: "Lucieni" },
  { nume: "Ludeşti", simplu: "Ludesti" },
  { nume: "Lunca", comuna: "Moroeni" },
  { nume: "Lunca", comuna: "Voinesti" },
  { nume: "Lunguleţu", simplu: "Lunguletu" },
  { nume: "Măgura", simplu: "Magura", comuna: "Bezdead" },
  { nume: "Măgura", simplu: "Magura", comuna: "Hulubesti" },
  { nume: "Malu cu Flori" },
  { nume: "Malu Mierii", comuna: "Glodeni" },
  { nume: "Malurile", comuna: "Pucioasa" },
  { nume: "Mânăstioara", simplu: "Manastioara", comuna: "Uliesti" },
  { nume: "Mănăstirea", simplu: "Manastirea", comuna: "Cobia" },
  { nume: "Mânăstirea", simplu: "Manastirea", comuna: "Crevedia" },
  { nume: "Măneşti", simplu: "Manesti" },
  { nume: "Manga", comuna: "Voinesti" },
  { nume: "Mânjina", simplu: "Manjina", comuna: "Voinesti" },
  { nume: "Mărceşti", simplu: "Marcesti", comuna: "Dobra" },
  {
    nume: "Mărginenii de Sus",
    simplu: "Marginenii de Sus",
    comuna: "Darmanesti",
  },
  { nume: "Mărunţişu", simplu: "Maruntisu", comuna: "Costestii Din Vale" },
  { nume: "Mătăsaru", simplu: "Matasaru" },
  { nume: "Matraca", comuna: "Ulmi" },
  { nume: "Mavrodin", comuna: "Racari" },
  { nume: "Meişoare", simplu: "Meisoare", comuna: "Pucheni" },
  { nume: "Mereni", comuna: "Contesti" },
  { nume: "Mereni", comuna: "Titu" },
  { nume: "Merii", comuna: "Mogosani" },
  { nume: "Merişoru", simplu: "Merisoru", comuna: "Virfuri" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Valeni-Dimbovita" },
  {
    nume: "Micloşanii Mari",
    simplu: "Miclosanii Mari",
    comuna: "Malu Cu Flori",
  },
  {
    nume: "Micloşanii Mici",
    simplu: "Miclosanii Mici",
    comuna: "Malu Cu Flori",
  },
  { nume: "Miculeşti", simplu: "Miculesti", comuna: "Pucioasa" },
  { nume: "Mija", comuna: "I. L. Caragiale" },
  { nume: "Miloşari", simplu: "Milosari", comuna: "Ludesti" },
  { nume: "Mircea Vodă", simplu: "Mircea Voda", comuna: "Salcioara" },
  { nume: "Mislea", comuna: "Cobia" },
  { nume: "Miuleşti", simplu: "Miulesti", comuna: "Odobesti" },
  {
    nume: "Moara din Groapă",
    simplu: "Moara din Groapa",
    comuna: "Corbii Mari",
  },
  { nume: "Moara Nouă", simplu: "Moara Noua", comuna: "Salcioara" },
  { nume: "Mogoşani", simplu: "Mogosani" },
  { nume: "Mogoşeşti", simplu: "Mogosesti", comuna: "Dragomiresti" },
  { nume: "Moreni" },
  { nume: "Moroeni" },
  { nume: "Morteni" },
  { nume: "Moşia Mică", simplu: "Mosia Mica", comuna: "Valea Lunga" },
  { nume: "Moţăieni", simplu: "Motaieni" },
  { nume: "Movila", comuna: "Niculesti" },
  { nume: "Movila", comuna: "Salcioara" },
  { nume: "Muşcel", simplu: "Muscel", comuna: "Moroeni" },
  { nume: "Neajlovu", comuna: "Morteni" },
  { nume: "Nicolaeşti", simplu: "Nicolaesti", comuna: "Vulcana-Bai" },
  { nume: "Niculeşti", simplu: "Niculesti" },
  { nume: "Nisipurile", comuna: "Ulmi" },
  { nume: "Nucet" },
  { nume: "Ochiuri", comuna: "Gura Ocnitei" },
  { nume: "Ocniţa", simplu: "Ocnita" },
  { nume: "Odaia Turcului", comuna: "Matasaru" },
  { nume: "Odobeşti", simplu: "Odobesti" },
  { nume: "Olteni", comuna: "Lucieni" },
  { nume: "Olteni", comuna: "Uliesti" },
  { nume: "Onceşti", simplu: "Oncesti", comuna: "Voinesti" },
  { nume: "Oreasca", comuna: "Lunguletu" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Dragodana" },
  { nume: "Pătroaia Deal", simplu: "Patroaia Deal", comuna: "Crangurile" },
  { nume: "Pătroaia Vale", simplu: "Patroaia Vale", comuna: "Crangurile" },
  { nume: "Perşinari", simplu: "Persinari", comuna: "Vacaresti" },
  { nume: "Petreşti", simplu: "Petresti" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Corbii Mari" },
  { nume: "Piatra", comuna: "Runcu" },
  { nume: "Picior de Munte", comuna: "Dragodana" },
  { nume: "Pietrari", comuna: "Barbuletu" },
  { nume: "Pietroşiţa", simplu: "Pietrosita" },
  { nume: "Pitaru", comuna: "Potlogi" },
  { nume: "Plopu", comuna: "Titu" },
  { nume: "Podu Corbencii", comuna: "Corbii Mari" },
  { nume: "Podu Cristinii", comuna: "Potlogi" },
  { nume: "Podu Rizii", comuna: "Salcioara" },
  { nume: "Poiana" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Poiana" },
  { nume: "Poroinica", comuna: "Matasaru" },
  { nume: "Postârnacu", simplu: "Postarnacu", comuna: "Cornesti" },
  { nume: "Potlogeni Vale", comuna: "Crangurile" },
  { nume: "Potlogeni-Deal", comuna: "Petresti" },
  { nume: "Potlogi" },
  { nume: "Potocelu", comuna: "Ludesti" },
  { nume: "Priboiu", comuna: "Branesti" },
  { nume: "Priboiu", comuna: "Tatarani" },
  { nume: "Priseaca", comuna: "Targoviste" },
  { nume: "Produleşti", simplu: "Produlesti" },
  { nume: "Pucheni" },
  { nume: "Pucheni", comuna: "Moroeni" },
  { nume: "Pucioasa-Sat", comuna: "Pucioasa" },
  { nume: "Pucioasa" },
  { nume: "Puntea de Greci", comuna: "Petresti" },
  { nume: "Puţu cu Salcie", simplu: "Putu cu Salcie", comuna: "Matasaru" },
  { nume: "Răcari", simplu: "Racari" },
  { nume: "Raciu", comuna: "Lucieni" },
  { nume: "Racoviţa", simplu: "Racovita", comuna: "Bucsani" },
  { nume: "Ragu", comuna: "Uliesti" },
  { nume: "Râncăciov", simplu: "Rancaciov", comuna: "Dragomiresti" },
  { nume: "Răscăeţi", simplu: "Rascaeti", comuna: "Visina" },
  { nume: "Răţeşti", simplu: "Ratesti", comuna: "Crangurile" },
  { nume: "Răţoaia", simplu: "Ratoaia", comuna: "Bucsani" },
  { nume: "Râu Alb de Jos", simplu: "Rau Alb de Jos", comuna: "Barbuletu" },
  { nume: "Râu Alb de Sus", simplu: "Rau Alb de Sus", comuna: "Barbuletu" },
  { nume: "Răzvad", simplu: "Razvad" },
  { nume: "Româneşti", simplu: "Romanesti", comuna: "Potlogi" },
  { nume: "Runcu" },
  { nume: "Săbieşti", simplu: "Sabiesti", comuna: "Racari" },
  { nume: "Săcueni", simplu: "Sacueni", comuna: "Gura Ocnitei" },
  { nume: "Sălcioara", simplu: "Salcioara" },
  { nume: "Sălcioara", simplu: "Salcioara", comuna: "Matasaru" },
  { nume: "Sălcuţa", simplu: "Salcuta", comuna: "Titu" },
  { nume: "Samurcaşi", simplu: "Samurcasi", comuna: "Crevedia" },
  { nume: "Saru", comuna: "Valea Mare" },
  { nume: "Săteni", simplu: "Sateni", comuna: "Aninoasa" },
  { nume: "Satu Nou", comuna: "Corbii Mari" },
  { nume: "Săveşti", simplu: "Savesti", comuna: "Branistea" },
  { nume: "Scheiu de Jos", comuna: "Ludesti" },
  { nume: "Scheiu de Sus", comuna: "Ludesti" },
  { nume: "Schela", comuna: "Glodeni" },
  { nume: "Şelaru", simplu: "Selaru" },
  { nume: "Şerbăneasa", simplu: "Serbaneasa", comuna: "Valea Lunga" },
  { nume: "Serdanu", comuna: "Lunguletu" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Lucieni" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Runcu" },
  { nume: "Şipot", simplu: "Sipot", comuna: "Barbuletu" },
  { nume: "Slobozia Moară", simplu: "Slobozia Moara" },
  { nume: "Slobozia", comuna: "Cornatelu" },
  { nume: "Şotânga", simplu: "Sotanga" },
  { nume: "Sperieţeni", simplu: "Sperieteni", comuna: "Gura Sutii" },
  { nume: "Stăneşti", simplu: "Stanesti", comuna: "Racari" },
  { nume: "Stăteşti", simplu: "Statesti", comuna: "Virfuri" },
  { nume: "Stavropolia", comuna: "Uliesti" },
  { nume: "Străoşti", simplu: "Straosti", comuna: "Dragodana" },
  { nume: "Stratoneşti", simplu: "Stratonesti", comuna: "Valea Mare" },
  { nume: "Ştubeie Tisa", simplu: "Stubeie Tisa", comuna: "Valea Lunga" },
  { nume: "Suduleni", comuna: "Voinesti" },
  { nume: "Sultanu", comuna: "Visinesti" },
  { nume: "Suseni Socetu", comuna: "Bilciuresti" },
  { nume: "Şuţa Seacă", simplu: "Suta Seaca", comuna: "Lucieni" },
  { nume: "Şuviţa", simplu: "Suvita", comuna: "Virfuri" },
  { nume: "Târgovişte", simplu: "Targoviste" },
  { nume: "Tărtăşeşti", simplu: "Tartasesti" },
  { nume: "Tătărani", simplu: "Tatarani" },
  { nume: "Teiş", simplu: "Teis", comuna: "Sotanga" },
  { nume: "Teleşti", simplu: "Telesti", comuna: "Ludesti" },
  { nume: "Teţcoiu", simplu: "Tetcoiu", comuna: "Matasaru" },
  { nume: "Titu" },
  { nume: "Toculeşti", simplu: "Toculesti", comuna: "Vulcana-Pandele" },
  { nume: "Tomşani", simplu: "Tomsani", comuna: "Costestii Din Vale" },
  { nume: "Tunari", comuna: "Bezdead" },
  { nume: "Udreşti", simplu: "Udresti", comuna: "Ulmi" },
  { nume: "Ulieşti", simplu: "Uliesti" },
  { nume: "Ulmetu", comuna: "Virfuri" },
  { nume: "Ulmi" },
  { nume: "Ungureni", comuna: "Butimanu" },
  { nume: "Ungureni", comuna: "Corbii Mari" },
  { nume: "Ungureni", comuna: "Cornesti" },
  { nume: "Ungureni", comuna: "Dragomiresti" },
  { nume: "Urseiu", comuna: "Visinesti" },
  { nume: "Urziceanca", comuna: "Ciocanesti" },
  { nume: "Văcăreşti", simplu: "Vacaresti" },
  { nume: "Vadu Stanchii", comuna: "Corbii Mari" },
  { nume: "Valea Caselor", comuna: "Valea Mare" },
  { nume: "Valea Dadei", comuna: "Hulubesti" },
  { nume: "Valea Largă", simplu: "Valea Larga", comuna: "Pucheni" },
  { nume: "Valea Leurzii", comuna: "Buciumeni" },
  { nume: "Valea lui Dan", comuna: "Valea Lunga" },
  {
    nume: "Valea Lungă Gorgota",
    simplu: "Valea Lunga Gorgota",
    comuna: "Valea Lunga",
  },
  {
    nume: "Valea Lungă Ogrea",
    simplu: "Valea Lunga Ogrea",
    comuna: "Valea Lunga",
  },
  {
    nume: "Valea Lungă-Cricov",
    simplu: "Valea Lunga-Cricov",
    comuna: "Valea Lunga",
  },
  { nume: "Valea Mare" },
  { nume: "Valea Mare", comuna: "Candesti" },
  { nume: "Valea Mare", comuna: "Valea Lunga" },
  { nume: "Valea Morii", comuna: "Bezdead" },
  { nume: "Valea Voivozilor", comuna: "Razvad" },
  { nume: "Valea", comuna: "Barbuletu" },
  {
    nume: "Văleni-Dâmboviţa",
    simplu: "Valeni-Dambovita",
    comuna: "Valeni-Dimbovita",
  },
  { nume: "Vârfureni", simplu: "Varfureni", comuna: "Pucheni" },
  { nume: "Vârfuri", simplu: "Varfuri", comuna: "Virfuri" },
  { nume: "Viforâta", simplu: "Viforata", comuna: "Aninoasa" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Ulmi" },
  { nume: "Vişina", simplu: "Visina" },
  { nume: "Vişineşti", simplu: "Visinesti" },
  { nume: "Vizureşti", simplu: "Vizuresti", comuna: "Ciocanesti" },
  { nume: "Vlădeni", simplu: "Vladeni" },
  { nume: "Vlăsceni", simplu: "Vlasceni", comuna: "Potlogi" },
  { nume: "Voia", comuna: "Crangurile" },
  { nume: "Voineşti", simplu: "Voinesti" },
  { nume: "Vulcana de Sus", comuna: "Vulcana-Bai" },
  { nume: "Vulcana-Băi", simplu: "Vulcana-Bai" },
  { nume: "Vulcana-Pandele" },
  { nume: "Vultureanca", comuna: "Visina" },
  { nume: "Zăvoiu", simplu: "Zavoiu", comuna: "Mogosani" },
  { nume: "Zidurile", comuna: "Odobesti" },
];
