export const db = [
  { nume: "Adânca", simplu: "Adanca", comuna: "Gura Ocnitei" },
  { nume: "Aluniș", simplu: "Alunis", comuna: "Barbuletu" },
  { nume: "Alunișu", simplu: "Alunisu", comuna: "Cornatelu" },
  { nume: "Aninoasa" },
  { nume: "Aninoșani", simplu: "Aninosani", comuna: "Candesti" },
  { nume: "Băcești", simplu: "Bacesti", comuna: "Valea Lunga" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Runcu" },
  { nume: "Bădulești", simplu: "Badulesti", comuna: "Crangurile" },
  { nume: "Bălănești", simplu: "Balanesti", comuna: "Racari" },
  { nume: "Bâldana", simplu: "Baldana", comuna: "Tartasesti" },
  { nume: "Băleni-Români", simplu: "Baleni-Romani", comuna: "Baleni" },
  { nume: "Băleni-Sârbi", simplu: "Baleni-Sarbi", comuna: "Baleni" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Contesti" },
  { nume: "Bănești", simplu: "Banesti", comuna: "Salcioara" },
  { nume: "Bărăceni", simplu: "Baraceni", comuna: "Corbii Mari" },
  { nume: "Bărbuceanu", simplu: "Barbuceanu", comuna: "Butimanu" },
  { nume: "Bărbulețu", simplu: "Barbuletu" },
  { nume: "Bechinești", simplu: "Bechinesti", comuna: "Finta" },
  { nume: "Bela", comuna: "Pucioasa" },
  { nume: "Berevoești", simplu: "Berevoesti", comuna: "Fieni" },
  { nume: "Bezdead" },
  { nume: "Bilciurești", simplu: "Bilciuresti" },
  { nume: "Blidari", comuna: "Cobia" },
  { nume: "Boboci", comuna: "Dragodana" },
  { nume: "Bolovani", comuna: "Cornatelu" },
  { nume: "Boteni", comuna: "Contesti" },
  { nume: "Brădățel", simplu: "Bradatel", comuna: "Pucheni" },
  { nume: "Brâncoveanu", simplu: "Brancoveanu", comuna: "Odobesti" },
  { nume: "Brănești", simplu: "Branesti" },
  { nume: "Braniștea", simplu: "Branistea" },
  { nume: "Brăteștii de Jos", simplu: "Bratestii de Jos", comuna: "Vacaresti" },
  { nume: "Brebu", comuna: "Runcu" },
  { nume: "Brezoaele" },
  { nume: "Brezoaia", comuna: "Brezoaele" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Bezdead" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Produlesti" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Visina" },
  { nume: "Buciumeni" },
  { nume: "Bucșani", simplu: "Bucsani" },
  { nume: "Bujoreanca", comuna: "Cornesti" },
  { nume: "Bumbuia", comuna: "Gura Foii" },
  { nume: "Bungetu", comuna: "Vacaresti" },
  { nume: "Burduca", comuna: "Dragodana" },
  { nume: "Butimanu" },
  { nume: "Butoiu de Jos", comuna: "Hulubesti" },
  { nume: "Butoiu de Sus", comuna: "Hulubesti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Cobia" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Contesti" },
  { nume: "Cândești Deal", simplu: "Candesti Deal", comuna: "Candesti" },
  { nume: "Cândești-Vale", simplu: "Candesti-Vale", comuna: "Candesti" },
  { nume: "Căprioru", simplu: "Caprioru", comuna: "Tatarani" },
  { nume: "Căpșuna", simplu: "Capsuna", comuna: "Cobia" },
  { nume: "Capu Coastei", comuna: "Malu Cu Flori" },
  { nume: "Cârlănești", simplu: "Carlanesti", comuna: "Virfuri" },
  { nume: "Catanele", comuna: "Gura Foii" },
  { nume: "Cătunu", simplu: "Catunu", comuna: "Cornesti" },
  { nume: "Cătunu", simplu: "Catunu", comuna: "Salcioara" },
  { nume: "Cazaci", comuna: "Nucet" },
  { nume: "Cetățuia", simplu: "Cetatuia", comuna: "Barbuletu" },
  { nume: "Chirca", comuna: "Mogosani" },
  { nume: "Ciocănari", simplu: "Ciocanari", comuna: "Niculesti" },
  { nume: "Ciocănești", simplu: "Ciocanesti" },
  { nume: "Coada Izvorului", comuna: "Petresti" },
  { nume: "Cobiuța", simplu: "Cobiuta", comuna: "Cobia" },
  { nume: "Cocani", comuna: "Crevedia" },
  { nume: "Cojasca" },
  { nume: "Cojocaru", comuna: "Mogosani" },
  { nume: "Cojoiu", comuna: "Virfuri" },
  { nume: "Colacu", comuna: "Racari" },
  { nume: "Colanu", comuna: "Ulmi" },
  { nume: "Colibași", simplu: "Colibasi", comuna: "Iedera" },
  { nume: "Comișani", simplu: "Comisani" },
  { nume: "Conțești", simplu: "Contesti" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "Malu Cu Flori" },
  { nume: "Corbii Mari" },
  { nume: "Cornățelu", simplu: "Cornatelu" },
  { nume: "Cornești", simplu: "Cornesti" },
  { nume: "Corni", comuna: "Cornatelu" },
  { nume: "Costești", simplu: "Costesti", comuna: "Fieni" },
  {
    nume: "Costeștii din Deal",
    simplu: "Costestii din Deal",
    comuna: "Produlesti",
  },
  { nume: "Costeștii din Vale", simplu: "Costestii din Vale" },
  { nume: "Costișata", simplu: "Costisata", comuna: "Bezdead" },
  { nume: "Crăciunești", simplu: "Craciunesti", comuna: "Cobia" },
  { nume: "Crângași", simplu: "Crangasi", comuna: "Contesti" },
  {
    nume: "Crângurile de Jos",
    simplu: "Crangurile de Jos",
    comuna: "Crangurile",
  },
  {
    nume: "Crângurile de Sus",
    simplu: "Crangurile de Sus",
    comuna: "Crangurile",
  },
  { nume: "Crețu", simplu: "Cretu", comuna: "Ciocanesti" },
  { nume: "Crețulești", simplu: "Cretulesti", comuna: "Matasaru" },
  { nume: "Crevedia" },
  { nume: "Cricovu Dulce", comuna: "Iedera" },
  { nume: "Cristeasca", comuna: "Cornesti" },
  { nume: "Crivățu", simplu: "Crivatu", comuna: "Cornesti" },
  { nume: "Croitori", comuna: "Uliesti" },
  { nume: "Crovu", comuna: "Odobesti" },
  { nume: "Cucuteni", comuna: "Motaieni" },
  { nume: "Cuparu", comuna: "Dragodana" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Salcioara" },
  { nume: "Dâmbovicioara", simplu: "Dambovicioara", comuna: "Branistea" },
  { nume: "Dărmănești", simplu: "Darmanesti" },
  { nume: "Dârza", simplu: "Darza", comuna: "Crevedia" },
  { nume: "Dealu Frumos", comuna: "Pietrosita" },
  { nume: "Dealu Mare", comuna: "Buciumeni" },
  { nume: "Decindea", comuna: "Ciocanesti" },
  { nume: "Decindeni", comuna: "Dragomiresti" },
  { nume: "Diaconești", simplu: "Diaconesti", comuna: "Pucioasa" },
  { nume: "Dimoiu", comuna: "Ulmi" },
  { nume: "Dobra" },
  { nume: "Dobrești", simplu: "Dobresti", comuna: "Moroeni" },
  { nume: "Doicești", simplu: "Doicesti" },
  { nume: "Dospinești", simplu: "Dospinesti", comuna: "Visinesti" },
  {
    nume: "Drăgăești Pământeni",
    simplu: "Dragaesti Pamanteni",
    comuna: "Manesti",
  },
  {
    nume: "Drăgăești Ungureni",
    simplu: "Dragaesti Ungureni",
    comuna: "Manesti",
  },
  { nume: "Dragodana" },
  { nume: "Dragodănești", simplu: "Dragodanesti", comuna: "Candesti" },
  { nume: "Dragomirești", simplu: "Dragomiresti" },
  { nume: "Dumbrava", comuna: "Ulmi" },
  { nume: "După Deal", simplu: "Dupa Deal", comuna: "Barbuletu" },
  { nume: "Făgetu", simplu: "Fagetu", comuna: "Gura Foii" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Cojasca" },
  { nume: "Ferestre", comuna: "Runcu" },
  { nume: "Fețeni", simplu: "Feteni", comuna: "Valea Mare" },
  { nume: "Fieni" },
  { nume: "Fierbinți", simplu: "Fierbinti", comuna: "Selaru" },
  { nume: "Finta Mare", comuna: "Finta" },
  { nume: "Finta Veche", comuna: "Finta" },
  { nume: "Frasin Deal", comuna: "Cobia" },
  { nume: "Frasin Vale", comuna: "Cobia" },
  { nume: "Frasinu", comuna: "Cornesti" },
  { nume: "Fusea", comuna: "Titu" },
  { nume: "Găești", simplu: "Gaesti" },
  { nume: "Gămănești", simplu: "Gamanesti", comuna: "Contesti" },
  { nume: "Gârleni", simplu: "Garleni", comuna: "Valea Mare" },
  { nume: "Geangoești", simplu: "Geangoesti", comuna: "Dragomiresti" },
  {
    nume: "Gemenea Brătulești",
    simplu: "Gemenea Bratulesti",
    comuna: "Voinesti",
  },
  { nume: "Gheboaia", comuna: "Finta" },
  { nume: "Gheboieni", comuna: "Tatarani" },
  { nume: "Ghergani", comuna: "Racari" },
  { nume: "Gherghești", simplu: "Gherghesti", comuna: "Petresti" },
  { nume: "Gherghițești", simplu: "Gherghitesti", comuna: "Cobia" },
  { nume: "Ghimpați", simplu: "Ghimpati", comuna: "Racari" },
  { nume: "Ghinești", simplu: "Ghinesti", comuna: "Salcioara" },
  { nume: "Ghirdoveni", comuna: "I. L. Caragiale" },
  { nume: "Glod", comuna: "Moroeni" },
  { nume: "Glodeni" },
  { nume: "Glodeni", comuna: "Pucioasa" },
  { nume: "Glogoveanu", comuna: "Selaru" },
  { nume: "Gorgota", comuna: "Razvad" },
  { nume: "Greci", comuna: "Petresti" },
  { nume: "Grozăvești", simplu: "Grozavesti", comuna: "Corbii Mari" },
  { nume: "Gulia", comuna: "Tartasesti" },
  {
    nume: "Gura Bărbulețului",
    simplu: "Gura Barbuletului",
    comuna: "Barbuletu",
  },
  { nume: "Gura Foii" },
  { nume: "Gura Ocniței", simplu: "Gura Ocnitei" },
  { nume: "Gura Șuții", simplu: "Gura Sutii" },
  { nume: "Gura Vulcanei", comuna: "Vulcana-Pandele" },
  { nume: "Gușoiu", simplu: "Gusoiu", comuna: "Glodeni" },
  { nume: "Hăbeni", simplu: "Habeni", comuna: "Bucsani" },
  { nume: "Hagioaica", comuna: "Titu" },
  { nume: "Hanu lui Pală", simplu: "Hanu lui Pala", comuna: "Uliesti" },
  { nume: "Heleșteu", simplu: "Helesteu", comuna: "Contesti" },
  { nume: "Hodărăști", simplu: "Hodarasti", comuna: "Cornesti" },
  { nume: "Hulubești", simplu: "Hulubesti" },
  { nume: "I. L. Caragiale" },
  { nume: "Iazu", comuna: "Cojasca" },
  { nume: "Ibrianu", comuna: "Cornesti" },
  { nume: "Iedera de Jos", comuna: "Iedera" },
  { nume: "Iedera de Sus", comuna: "Iedera" },
  { nume: "Ilfoveni", comuna: "Nucet" },
  { nume: "Ionești", simplu: "Ionesti", comuna: "Petresti" },
  { nume: "Izvoarele", comuna: "Voinesti" },
  { nume: "Izvoru", comuna: "Valea Lunga" },
  { nume: "Izvoru", comuna: "Visina" },
  { nume: "Jugureni", comuna: "Uliesti" },
  { nume: "Lăculețe-Gară", simplu: "Laculete-Gara", comuna: "Vulcana-Pandele" },
  { nume: "Lăculețe", simplu: "Laculete", comuna: "Glodeni" },
  { nume: "Lazuri", comuna: "Comisani" },
  { nume: "Livezile", comuna: "Glodeni" },
  { nume: "Livezile", comuna: "Valea Mare" },
  { nume: "Lucianca", comuna: "Butimanu" },
  { nume: "Lucieni" },
  { nume: "Ludești", simplu: "Ludesti" },
  { nume: "Lunca", comuna: "Moroeni" },
  { nume: "Lunca", comuna: "Voinesti" },
  { nume: "Lungulețu", simplu: "Lunguletu" },
  { nume: "Măgura", simplu: "Magura", comuna: "Bezdead" },
  { nume: "Măgura", simplu: "Magura", comuna: "Hulubesti" },
  { nume: "Malu cu Flori" },
  { nume: "Malu Mierii", comuna: "Glodeni" },
  { nume: "Malurile", comuna: "Pucioasa" },
  { nume: "Mânăstioara", simplu: "Manastioara", comuna: "Uliesti" },
  { nume: "Mănăstirea", simplu: "Manastirea", comuna: "Cobia" },
  { nume: "Mânăstirea", simplu: "Manastirea", comuna: "Crevedia" },
  { nume: "Mănești", simplu: "Manesti" },
  { nume: "Manga", comuna: "Voinesti" },
  { nume: "Mânjina", simplu: "Manjina", comuna: "Voinesti" },
  { nume: "Mărcești", simplu: "Marcesti", comuna: "Dobra" },
  {
    nume: "Mărginenii de Sus",
    simplu: "Marginenii de Sus",
    comuna: "Darmanesti",
  },
  { nume: "Mărunțișu", simplu: "Maruntisu", comuna: "Costestii Din Vale" },
  { nume: "Mătăsaru", simplu: "Matasaru" },
  { nume: "Matraca", comuna: "Ulmi" },
  { nume: "Mavrodin", comuna: "Racari" },
  { nume: "Meișoare", simplu: "Meisoare", comuna: "Pucheni" },
  { nume: "Mereni", comuna: "Contesti" },
  { nume: "Mereni", comuna: "Titu" },
  { nume: "Merii", comuna: "Mogosani" },
  { nume: "Merișoru", simplu: "Merisoru", comuna: "Virfuri" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Valeni-Dimbovita" },
  {
    nume: "Micloșanii Mari",
    simplu: "Miclosanii Mari",
    comuna: "Malu Cu Flori",
  },
  {
    nume: "Micloșanii Mici",
    simplu: "Miclosanii Mici",
    comuna: "Malu Cu Flori",
  },
  { nume: "Miculești", simplu: "Miculesti", comuna: "Pucioasa" },
  { nume: "Mija", comuna: "I. L. Caragiale" },
  { nume: "Miloșari", simplu: "Milosari", comuna: "Ludesti" },
  { nume: "Mircea Vodă", simplu: "Mircea Voda", comuna: "Salcioara" },
  { nume: "Mislea", comuna: "Cobia" },
  { nume: "Miulești", simplu: "Miulesti", comuna: "Odobesti" },
  {
    nume: "Moara din Groapă",
    simplu: "Moara din Groapa",
    comuna: "Corbii Mari",
  },
  { nume: "Moara Nouă", simplu: "Moara Noua", comuna: "Salcioara" },
  { nume: "Mogoșani", simplu: "Mogosani" },
  { nume: "Mogoșești", simplu: "Mogosesti", comuna: "Dragomiresti" },
  { nume: "Moreni" },
  { nume: "Moroeni" },
  { nume: "Morteni" },
  { nume: "Moșia Mică", simplu: "Mosia Mica", comuna: "Valea Lunga" },
  { nume: "Moțăieni", simplu: "Motaieni" },
  { nume: "Movila", comuna: "Niculesti" },
  { nume: "Movila", comuna: "Salcioara" },
  { nume: "Mușcel", simplu: "Muscel", comuna: "Moroeni" },
  { nume: "Neajlovu", comuna: "Morteni" },
  { nume: "Nicolaești", simplu: "Nicolaesti", comuna: "Vulcana-Bai" },
  { nume: "Niculești", simplu: "Niculesti" },
  { nume: "Nisipurile", comuna: "Ulmi" },
  { nume: "Nucet" },
  { nume: "Ochiuri", comuna: "Gura Ocnitei" },
  { nume: "Ocnița", simplu: "Ocnita" },
  { nume: "Odaia Turcului", comuna: "Matasaru" },
  { nume: "Odobești", simplu: "Odobesti" },
  { nume: "Olteni", comuna: "Lucieni" },
  { nume: "Olteni", comuna: "Uliesti" },
  { nume: "Oncești", simplu: "Oncesti", comuna: "Voinesti" },
  { nume: "Oreasca", comuna: "Lunguletu" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Dragodana" },
  { nume: "Pătroaia Deal", simplu: "Patroaia Deal", comuna: "Crangurile" },
  { nume: "Pătroaia Vale", simplu: "Patroaia Vale", comuna: "Crangurile" },
  { nume: "Perșinari", simplu: "Persinari", comuna: "Vacaresti" },
  { nume: "Petrești", simplu: "Petresti" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Corbii Mari" },
  { nume: "Piatra", comuna: "Runcu" },
  { nume: "Picior de Munte", comuna: "Dragodana" },
  { nume: "Pietrari", comuna: "Barbuletu" },
  { nume: "Pietroșița", simplu: "Pietrosita" },
  { nume: "Pitaru", comuna: "Potlogi" },
  { nume: "Plopu", comuna: "Titu" },
  { nume: "Podu Corbencii", comuna: "Corbii Mari" },
  { nume: "Podu Cristinii", comuna: "Potlogi" },
  { nume: "Podu Rizii", comuna: "Salcioara" },
  { nume: "Poiana" },
  { nume: "Poienița", simplu: "Poienita", comuna: "Poiana" },
  { nume: "Poroinica", comuna: "Matasaru" },
  { nume: "Postârnacu", simplu: "Postarnacu", comuna: "Cornesti" },
  { nume: "Potlogeni Vale", comuna: "Crangurile" },
  { nume: "Potlogeni-Deal", comuna: "Petresti" },
  { nume: "Potlogi" },
  { nume: "Potocelu", comuna: "Ludesti" },
  { nume: "Priboiu", comuna: "Branesti" },
  { nume: "Priboiu", comuna: "Tatarani" },
  { nume: "Priseaca", comuna: "Targoviste" },
  { nume: "Produlești", simplu: "Produlesti" },
  { nume: "Pucheni" },
  { nume: "Pucheni", comuna: "Moroeni" },
  { nume: "Pucioasa-Sat", comuna: "Pucioasa" },
  { nume: "Pucioasa" },
  { nume: "Puntea de Greci", comuna: "Petresti" },
  { nume: "Puțu cu Salcie", simplu: "Putu cu Salcie", comuna: "Matasaru" },
  { nume: "Răcari", simplu: "Racari" },
  { nume: "Raciu", comuna: "Lucieni" },
  { nume: "Racovița", simplu: "Racovita", comuna: "Bucsani" },
  { nume: "Ragu", comuna: "Uliesti" },
  { nume: "Râncăciov", simplu: "Rancaciov", comuna: "Dragomiresti" },
  { nume: "Răscăeți", simplu: "Rascaeti", comuna: "Visina" },
  { nume: "Rățești", simplu: "Ratesti", comuna: "Crangurile" },
  { nume: "Rățoaia", simplu: "Ratoaia", comuna: "Bucsani" },
  { nume: "Râu Alb de Jos", simplu: "Rau Alb de Jos", comuna: "Barbuletu" },
  { nume: "Râu Alb de Sus", simplu: "Rau Alb de Sus", comuna: "Barbuletu" },
  { nume: "Răzvad", simplu: "Razvad" },
  { nume: "Românești", simplu: "Romanesti", comuna: "Potlogi" },
  { nume: "Runcu" },
  { nume: "Săbiești", simplu: "Sabiesti", comuna: "Racari" },
  { nume: "Săcueni", simplu: "Sacueni", comuna: "Gura Ocnitei" },
  { nume: "Sălcioara", simplu: "Salcioara" },
  { nume: "Sălcioara", simplu: "Salcioara", comuna: "Matasaru" },
  { nume: "Sălcuța", simplu: "Salcuta", comuna: "Titu" },
  { nume: "Samurcași", simplu: "Samurcasi", comuna: "Crevedia" },
  { nume: "Saru", comuna: "Valea Mare" },
  { nume: "Săteni", simplu: "Sateni", comuna: "Aninoasa" },
  { nume: "Satu Nou", comuna: "Corbii Mari" },
  { nume: "Săvești", simplu: "Savesti", comuna: "Branistea" },
  { nume: "Scheiu de Jos", comuna: "Ludesti" },
  { nume: "Scheiu de Sus", comuna: "Ludesti" },
  { nume: "Schela", comuna: "Glodeni" },
  { nume: "Șelaru", simplu: "Selaru" },
  { nume: "Șerbăneasa", simplu: "Serbaneasa", comuna: "Valea Lunga" },
  { nume: "Serdanu", comuna: "Lunguletu" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Lucieni" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Runcu" },
  { nume: "Șipot", simplu: "Sipot", comuna: "Barbuletu" },
  { nume: "Slobozia Moară", simplu: "Slobozia Moara" },
  { nume: "Slobozia", comuna: "Cornatelu" },
  { nume: "Șotânga", simplu: "Sotanga" },
  { nume: "Speriețeni", simplu: "Sperieteni", comuna: "Gura Sutii" },
  { nume: "Stănești", simplu: "Stanesti", comuna: "Racari" },
  { nume: "Stătești", simplu: "Statesti", comuna: "Virfuri" },
  { nume: "Stavropolia", comuna: "Uliesti" },
  { nume: "Străoști", simplu: "Straosti", comuna: "Dragodana" },
  { nume: "Stratonești", simplu: "Stratonesti", comuna: "Valea Mare" },
  { nume: "Ștubeie Tisa", simplu: "Stubeie Tisa", comuna: "Valea Lunga" },
  { nume: "Suduleni", comuna: "Voinesti" },
  { nume: "Sultanu", comuna: "Visinesti" },
  { nume: "Suseni Socetu", comuna: "Bilciuresti" },
  { nume: "Șuța Seacă", simplu: "Suta Seaca", comuna: "Lucieni" },
  { nume: "Șuvița", simplu: "Suvita", comuna: "Virfuri" },
  { nume: "Târgoviște", simplu: "Targoviste" },
  { nume: "Tărtășești", simplu: "Tartasesti" },
  { nume: "Tătărani", simplu: "Tatarani" },
  { nume: "Teiș", simplu: "Teis", comuna: "Sotanga" },
  { nume: "Telești", simplu: "Telesti", comuna: "Ludesti" },
  { nume: "Tețcoiu", simplu: "Tetcoiu", comuna: "Matasaru" },
  { nume: "Titu" },
  { nume: "Toculești", simplu: "Toculesti", comuna: "Vulcana-Pandele" },
  { nume: "Tomșani", simplu: "Tomsani", comuna: "Costestii Din Vale" },
  { nume: "Tunari", comuna: "Bezdead" },
  { nume: "Udrești", simplu: "Udresti", comuna: "Ulmi" },
  { nume: "Uliești", simplu: "Uliesti" },
  { nume: "Ulmetu", comuna: "Virfuri" },
  { nume: "Ulmi" },
  { nume: "Ungureni", comuna: "Butimanu" },
  { nume: "Ungureni", comuna: "Corbii Mari" },
  { nume: "Ungureni", comuna: "Cornesti" },
  { nume: "Ungureni", comuna: "Dragomiresti" },
  { nume: "Urseiu", comuna: "Visinesti" },
  { nume: "Urziceanca", comuna: "Ciocanesti" },
  { nume: "Văcărești", simplu: "Vacaresti" },
  { nume: "Vadu Stanchii", comuna: "Corbii Mari" },
  { nume: "Valea Caselor", comuna: "Valea Mare" },
  { nume: "Valea Dadei", comuna: "Hulubesti" },
  { nume: "Valea Largă", simplu: "Valea Larga", comuna: "Pucheni" },
  { nume: "Valea Leurzii", comuna: "Buciumeni" },
  { nume: "Valea lui Dan", comuna: "Valea Lunga" },
  {
    nume: "Valea Lungă Gorgota",
    simplu: "Valea Lunga Gorgota",
    comuna: "Valea Lunga",
  },
  {
    nume: "Valea Lungă Ogrea",
    simplu: "Valea Lunga Ogrea",
    comuna: "Valea Lunga",
  },
  {
    nume: "Valea Lungă-Cricov",
    simplu: "Valea Lunga-Cricov",
    comuna: "Valea Lunga",
  },
  { nume: "Valea Mare" },
  { nume: "Valea Mare", comuna: "Candesti" },
  { nume: "Valea Mare", comuna: "Valea Lunga" },
  { nume: "Valea Morii", comuna: "Bezdead" },
  { nume: "Valea Voivozilor", comuna: "Razvad" },
  { nume: "Valea", comuna: "Barbuletu" },
  {
    nume: "Văleni-Dâmbovița",
    simplu: "Valeni-Dambovita",
    comuna: "Valeni-Dimbovita",
  },
  { nume: "Vârfureni", simplu: "Varfureni", comuna: "Pucheni" },
  { nume: "Vârfuri", simplu: "Varfuri", comuna: "Virfuri" },
  { nume: "Viforâta", simplu: "Viforata", comuna: "Aninoasa" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Ulmi" },
  { nume: "Vișina", simplu: "Visina" },
  { nume: "Vișinești", simplu: "Visinesti" },
  { nume: "Vizurești", simplu: "Vizuresti", comuna: "Ciocanesti" },
  { nume: "Vlădeni", simplu: "Vladeni" },
  { nume: "Vlăsceni", simplu: "Vlasceni", comuna: "Potlogi" },
  { nume: "Voia", comuna: "Crangurile" },
  { nume: "Voinești", simplu: "Voinesti" },
  { nume: "Vulcana de Sus", comuna: "Vulcana-Bai" },
  { nume: "Vulcana-Băi", simplu: "Vulcana-Bai" },
  { nume: "Vulcana-Pandele" },
  { nume: "Vultureanca", comuna: "Visina" },
  { nume: "Zăvoiu", simplu: "Zavoiu", comuna: "Mogosani" },
  { nume: "Zidurile", comuna: "Odobesti" },
];
