export const db = [
  { nume: "Aninoasa" },
  { nume: "Bezdead" },
  { nume: "Bilciuresti" },
  { nume: "Branistea" },
  { nume: "Brezoaele" },
  { nume: "Branesti" },
  { nume: "Buciumeni" },
  { nume: "Bucsani" },
  { nume: "Butimanu" },
  { nume: "Barbuletu" },
  { nume: "Ciocanesti" },
  { nume: "Cojasca" },
  { nume: "Comisani" },
  { nume: "Contesti" },
  { nume: "Corbii Mari" },
  { nume: "Cornesti" },
  { nume: "Cornatelu" },
  { nume: "Costestii din Vale" },
  { nume: "Crevedia" },
  { nume: "Dobra" },
  { nume: "Doicesti" },
  { nume: "Dragodana" },
  { nume: "Dragomiresti" },
  { nume: "Darmanesti" },
  { nume: "Fieni" },
  { nume: "Glodeni" },
  { nume: "Gura Foii" },
  { nume: "Gura Ocnitei" },
  { nume: "Gura Sutii" },
  { nume: "Gaesti" },
  { nume: "Hulubesti" },
  { nume: "I. L. Caragiale" },
  { nume: "Lucieni" },
  { nume: "Ludesti" },
  { nume: "Lunguletu" },
  { nume: "Malu cu Flori" },
  { nume: "Mogosani" },
  { nume: "Moreni" },
  { nume: "Moroeni" },
  { nume: "Morteni" },
  { nume: "Motaieni" },
  { nume: "Manesti" },
  { nume: "Matasaru" },
  { nume: "Niculesti" },
  { nume: "Nucet" },
  { nume: "Ocnita" },
  { nume: "Odobesti" },
  { nume: "Petresti" },
  { nume: "Pietrosita" },
  { nume: "Poiana" },
  { nume: "Potlogi" },
  { nume: "Produlesti" },
  { nume: "Pucheni" },
  { nume: "Pucioasa" },
  { nume: "Runcu" },
  { nume: "Racari" },
  { nume: "Razvad" },
  { nume: "Slobozia Moara" },
  { nume: "Salcioara" },
  { nume: "Titu" },
  { nume: "Targoviste" },
  { nume: "Tartasesti" },
  { nume: "Tatarani" },
  { nume: "Uliesti" },
  { nume: "Ulmi" },
  { nume: "Valea Mare" },
  { nume: "Visina" },
  { nume: "Visinesti" },
  { nume: "Vladeni" },
  { nume: "Voinesti" },
  { nume: "Vulcana-Bai" },
  { nume: "Vulcana-Pandele" },
  { nume: "Vacaresti" },
  { nume: "Selaru" },
  { nume: "Sotanga" },
  { nume: "Sateni", comuna: "Aninoasa" },
  { nume: "Viforata", comuna: "Aninoasa" },
  { nume: "Baleni-Romani", comuna: "Baleni" },
  { nume: "Baleni-Sarbi", comuna: "Baleni" },
  { nume: "Alunis", comuna: "Barbuletu" },
  { nume: "Cetatuia", comuna: "Barbuletu" },
  { nume: "Dupa Deal", comuna: "Barbuletu" },
  { nume: "Gura Barbuletului", comuna: "Barbuletu" },
  { nume: "Pietrari", comuna: "Barbuletu" },
  { nume: "Rau Alb de Jos", comuna: "Barbuletu" },
  { nume: "Rau Alb de Sus", comuna: "Barbuletu" },
  { nume: "Valea", comuna: "Barbuletu" },
  { nume: "Sipot", comuna: "Barbuletu" },
  { nume: "Brosteni", comuna: "Bezdead" },
  { nume: "Costisata", comuna: "Bezdead" },
  { nume: "Magura", comuna: "Bezdead" },
  { nume: "Tunari", comuna: "Bezdead" },
  { nume: "Valea Morii", comuna: "Bezdead" },
  { nume: "Suseni Socetu", comuna: "Bilciuresti" },
  { nume: "Priboiu", comuna: "Branesti" },
  { nume: "Dambovicioara", comuna: "Branistea" },
  { nume: "Savesti", comuna: "Branistea" },
  { nume: "Brezoaia", comuna: "Brezoaele" },
  { nume: "Dealu Mare", comuna: "Buciumeni" },
  { nume: "Valea Leurzii", comuna: "Buciumeni" },
  { nume: "Habeni", comuna: "Bucsani" },
  { nume: "Racovita", comuna: "Bucsani" },
  { nume: "Ratoaia", comuna: "Bucsani" },
  { nume: "Barbuceanu", comuna: "Butimanu" },
  { nume: "Lucianca", comuna: "Butimanu" },
  { nume: "Ungureni", comuna: "Butimanu" },
  { nume: "Aninosani", comuna: "Candesti" },
  { nume: "Candesti Deal", comuna: "Candesti" },
  { nume: "Candesti-Vale", comuna: "Candesti" },
  { nume: "Dragodanesti", comuna: "Candesti" },
  { nume: "Valea Mare", comuna: "Candesti" },
  { nume: "Cretu", comuna: "Ciocanesti" },
  { nume: "Decindea", comuna: "Ciocanesti" },
  { nume: "Urziceanca", comuna: "Ciocanesti" },
  { nume: "Vizuresti", comuna: "Ciocanesti" },
  { nume: "Blidari", comuna: "Cobia" },
  { nume: "Cobiuta", comuna: "Cobia" },
  { nume: "Craciunesti", comuna: "Cobia" },
  { nume: "Calugareni", comuna: "Cobia" },
  { nume: "Capsuna", comuna: "Cobia" },
  { nume: "Frasin Deal", comuna: "Cobia" },
  { nume: "Frasin Vale", comuna: "Cobia" },
  { nume: "Gherghitesti", comuna: "Cobia" },
  { nume: "Mislea", comuna: "Cobia" },
  { nume: "Manastirea", comuna: "Cobia" },
  { nume: "Fantanele", comuna: "Cojasca" },
  { nume: "Iazu", comuna: "Cojasca" },
  { nume: "Lazuri", comuna: "Comisani" },
  { nume: "Boteni", comuna: "Contesti" },
  { nume: "Balteni", comuna: "Contesti" },
  { nume: "Crangasi", comuna: "Contesti" },
  { nume: "Calugareni", comuna: "Contesti" },
  { nume: "Gamanesti", comuna: "Contesti" },
  { nume: "Helesteu", comuna: "Contesti" },
  { nume: "Mereni", comuna: "Contesti" },
  { nume: "Baraceni", comuna: "Corbii Mari" },
  { nume: "Grozavesti", comuna: "Corbii Mari" },
  { nume: "Moara din Groapa", comuna: "Corbii Mari" },
  { nume: "Petresti", comuna: "Corbii Mari" },
  { nume: "Podu Corbencii", comuna: "Corbii Mari" },
  { nume: "Satu Nou", comuna: "Corbii Mari" },
  { nume: "Ungureni", comuna: "Corbii Mari" },
  { nume: "Vadu Stanchii", comuna: "Corbii Mari" },
  { nume: "Alunisu", comuna: "Cornatelu" },
  { nume: "Bolovani", comuna: "Cornatelu" },
  { nume: "Corni", comuna: "Cornatelu" },
  { nume: "Slobozia", comuna: "Cornatelu" },
  { nume: "Bujoreanca", comuna: "Cornesti" },
  { nume: "Cristeasca", comuna: "Cornesti" },
  { nume: "Crivatu", comuna: "Cornesti" },
  { nume: "Catunu", comuna: "Cornesti" },
  { nume: "Frasinu", comuna: "Cornesti" },
  { nume: "Hodarasti", comuna: "Cornesti" },
  { nume: "Ibrianu", comuna: "Cornesti" },
  { nume: "Postarnacu", comuna: "Cornesti" },
  { nume: "Ungureni", comuna: "Cornesti" },
  { nume: "Maruntisu", comuna: "Costestii Din Vale" },
  { nume: "Tomsani", comuna: "Costestii Din Vale" },
  { nume: "Badulesti", comuna: "Crangurile" },
  { nume: "Crangurile de Jos", comuna: "Crangurile" },
  { nume: "Crangurile de Sus", comuna: "Crangurile" },
  { nume: "Potlogeni Vale", comuna: "Crangurile" },
  { nume: "Patroaia Deal", comuna: "Crangurile" },
  { nume: "Patroaia Vale", comuna: "Crangurile" },
  { nume: "Ratesti", comuna: "Crangurile" },
  { nume: "Voia", comuna: "Crangurile" },
  { nume: "Cocani", comuna: "Crevedia" },
  { nume: "Darza", comuna: "Crevedia" },
  { nume: "Manastirea", comuna: "Crevedia" },
  { nume: "Samurcasi", comuna: "Crevedia" },
  { nume: "Marginenii de Sus", comuna: "Darmanesti" },
  { nume: "Marcesti", comuna: "Dobra" },
  { nume: "Boboci", comuna: "Dragodana" },
  { nume: "Burduca", comuna: "Dragodana" },
  { nume: "Cuparu", comuna: "Dragodana" },
  { nume: "Picior de Munte", comuna: "Dragodana" },
  { nume: "Padureni", comuna: "Dragodana" },
  { nume: "Straosti", comuna: "Dragodana" },
  { nume: "Decindeni", comuna: "Dragomiresti" },
  { nume: "Geangoesti", comuna: "Dragomiresti" },
  { nume: "Mogosesti", comuna: "Dragomiresti" },
  { nume: "Rancaciov", comuna: "Dragomiresti" },
  { nume: "Ungureni", comuna: "Dragomiresti" },
  { nume: "Berevoesti", comuna: "Fieni" },
  { nume: "Costesti", comuna: "Fieni" },
  { nume: "Bechinesti", comuna: "Finta" },
  { nume: "Finta Mare", comuna: "Finta" },
  { nume: "Finta Veche", comuna: "Finta" },
  { nume: "Gheboaia", comuna: "Finta" },
  { nume: "Gusoiu", comuna: "Glodeni" },
  { nume: "Livezile", comuna: "Glodeni" },
  { nume: "Laculete", comuna: "Glodeni" },
  { nume: "Malu Mierii", comuna: "Glodeni" },
  { nume: "Schela", comuna: "Glodeni" },
  { nume: "Bumbuia", comuna: "Gura Foii" },
  { nume: "Catanele", comuna: "Gura Foii" },
  { nume: "Fagetu", comuna: "Gura Foii" },
  { nume: "Adanca", comuna: "Gura Ocnitei" },
  { nume: "Ochiuri", comuna: "Gura Ocnitei" },
  { nume: "Sacueni", comuna: "Gura Ocnitei" },
  { nume: "Sperieteni", comuna: "Gura Sutii" },
  { nume: "Butoiu de Jos", comuna: "Hulubesti" },
  { nume: "Butoiu de Sus", comuna: "Hulubesti" },
  { nume: "Magura", comuna: "Hulubesti" },
  { nume: "Valea Dadei", comuna: "Hulubesti" },
  { nume: "Ghirdoveni", comuna: "I. L. Caragiale" },
  { nume: "Mija", comuna: "I. L. Caragiale" },
  { nume: "Colibasi", comuna: "Iedera" },
  { nume: "Cricovu Dulce", comuna: "Iedera" },
  { nume: "Iedera de Jos", comuna: "Iedera" },
  { nume: "Iedera de Sus", comuna: "Iedera" },
  { nume: "Olteni", comuna: "Lucieni" },
  { nume: "Raciu", comuna: "Lucieni" },
  { nume: "Silistea", comuna: "Lucieni" },
  { nume: "Suta Seaca", comuna: "Lucieni" },
  { nume: "Milosari", comuna: "Ludesti" },
  { nume: "Potocelu", comuna: "Ludesti" },
  { nume: "Scheiu de Jos", comuna: "Ludesti" },
  { nume: "Scheiu de Sus", comuna: "Ludesti" },
  { nume: "Telesti", comuna: "Ludesti" },
  { nume: "Oreasca", comuna: "Lunguletu" },
  { nume: "Serdanu", comuna: "Lunguletu" },
  { nume: "Capu Coastei", comuna: "Malu Cu Flori" },
  { nume: "Copaceni", comuna: "Malu Cu Flori" },
  { nume: "Miclosanii Mari", comuna: "Malu Cu Flori" },
  { nume: "Miclosanii Mici", comuna: "Malu Cu Flori" },
  { nume: "Dragaesti Pamanteni", comuna: "Manesti" },
  { nume: "Dragaesti Ungureni", comuna: "Manesti" },
  { nume: "Cretulesti", comuna: "Matasaru" },
  { nume: "Odaia Turcului", comuna: "Matasaru" },
  { nume: "Poroinica", comuna: "Matasaru" },
  { nume: "Putu cu Salcie", comuna: "Matasaru" },
  { nume: "Salcioara", comuna: "Matasaru" },
  { nume: "Tetcoiu", comuna: "Matasaru" },
  { nume: "Chirca", comuna: "Mogosani" },
  { nume: "Cojocaru", comuna: "Mogosani" },
  { nume: "Merii", comuna: "Mogosani" },
  { nume: "Zavoiu", comuna: "Mogosani" },
  { nume: "Dobresti", comuna: "Moroeni" },
  { nume: "Glod", comuna: "Moroeni" },
  { nume: "Lunca", comuna: "Moroeni" },
  { nume: "Muscel", comuna: "Moroeni" },
  { nume: "Pucheni", comuna: "Moroeni" },
  { nume: "Neajlovu", comuna: "Morteni" },
  { nume: "Cucuteni", comuna: "Motaieni" },
  { nume: "Ciocanari", comuna: "Niculesti" },
  { nume: "Movila", comuna: "Niculesti" },
  { nume: "Cazaci", comuna: "Nucet" },
  { nume: "Ilfoveni", comuna: "Nucet" },
  { nume: "Brancoveanu", comuna: "Odobesti" },
  { nume: "Crovu", comuna: "Odobesti" },
  { nume: "Miulesti", comuna: "Odobesti" },
  { nume: "Zidurile", comuna: "Odobesti" },
  { nume: "Coada Izvorului", comuna: "Petresti" },
  { nume: "Gherghesti", comuna: "Petresti" },
  { nume: "Greci", comuna: "Petresti" },
  { nume: "Ionesti", comuna: "Petresti" },
  { nume: "Potlogeni-Deal", comuna: "Petresti" },
  { nume: "Puntea de Greci", comuna: "Petresti" },
  { nume: "Dealu Frumos", comuna: "Pietrosita" },
  { nume: "Poienita", comuna: "Poiana" },
  { nume: "Pitaru", comuna: "Potlogi" },
  { nume: "Podu Cristinii", comuna: "Potlogi" },
  { nume: "Romanesti", comuna: "Potlogi" },
  { nume: "Vlasceni", comuna: "Potlogi" },
  { nume: "Brosteni", comuna: "Produlesti" },
  { nume: "Costestii din Deal", comuna: "Produlesti" },
  { nume: "Bradatel", comuna: "Pucheni" },
  { nume: "Meisoare", comuna: "Pucheni" },
  { nume: "Valea Larga", comuna: "Pucheni" },
  { nume: "Varfureni", comuna: "Pucheni" },
  { nume: "Bela", comuna: "Pucioasa" },
  { nume: "Diaconesti", comuna: "Pucioasa" },
  { nume: "Glodeni", comuna: "Pucioasa" },
  { nume: "Malurile", comuna: "Pucioasa" },
  { nume: "Miculesti", comuna: "Pucioasa" },
  { nume: "Pucioasa-Sat", comuna: "Pucioasa" },
  { nume: "Balanesti", comuna: "Racari" },
  { nume: "Colacu", comuna: "Racari" },
  { nume: "Ghergani", comuna: "Racari" },
  { nume: "Ghimpati", comuna: "Racari" },
  { nume: "Mavrodin", comuna: "Racari" },
  { nume: "Stanesti", comuna: "Racari" },
  { nume: "Sabiesti", comuna: "Racari" },
  { nume: "Gorgota", comuna: "Razvad" },
  { nume: "Valea Voivozilor", comuna: "Razvad" },
  { nume: "Brebu", comuna: "Runcu" },
  { nume: "Badeni", comuna: "Runcu" },
  { nume: "Ferestre", comuna: "Runcu" },
  { nume: "Piatra", comuna: "Runcu" },
  { nume: "Silistea", comuna: "Runcu" },
  { nume: "Banesti", comuna: "Salcioara" },
  { nume: "Cuza Voda", comuna: "Salcioara" },
  { nume: "Catunu", comuna: "Salcioara" },
  { nume: "Ghinesti", comuna: "Salcioara" },
  { nume: "Mircea Voda", comuna: "Salcioara" },
  { nume: "Moara Noua", comuna: "Salcioara" },
  { nume: "Movila", comuna: "Salcioara" },
  { nume: "Podu Rizii", comuna: "Salcioara" },
  { nume: "Fierbinti", comuna: "Selaru" },
  { nume: "Glogoveanu", comuna: "Selaru" },
  { nume: "Teis", comuna: "Sotanga" },
  { nume: "Priseaca", comuna: "Targoviste" },
  { nume: "Baldana", comuna: "Tartasesti" },
  { nume: "Gulia", comuna: "Tartasesti" },
  { nume: "Caprioru", comuna: "Tatarani" },
  { nume: "Gheboieni", comuna: "Tatarani" },
  { nume: "Priboiu", comuna: "Tatarani" },
  { nume: "Fusea", comuna: "Titu" },
  { nume: "Hagioaica", comuna: "Titu" },
  { nume: "Mereni", comuna: "Titu" },
  { nume: "Plopu", comuna: "Titu" },
  { nume: "Salcuta", comuna: "Titu" },
  { nume: "Croitori", comuna: "Uliesti" },
  { nume: "Hanu lui Pala", comuna: "Uliesti" },
  { nume: "Jugureni", comuna: "Uliesti" },
  { nume: "Manastioara", comuna: "Uliesti" },
  { nume: "Olteni", comuna: "Uliesti" },
  { nume: "Ragu", comuna: "Uliesti" },
  { nume: "Stavropolia", comuna: "Uliesti" },
  { nume: "Colanu", comuna: "Ulmi" },
  { nume: "Dimoiu", comuna: "Ulmi" },
  { nume: "Dumbrava", comuna: "Ulmi" },
  { nume: "Matraca", comuna: "Ulmi" },
  { nume: "Nisipurile", comuna: "Ulmi" },
  { nume: "Udresti", comuna: "Ulmi" },
  { nume: "Viisoara", comuna: "Ulmi" },
  { nume: "Bratestii de Jos", comuna: "Vacaresti" },
  { nume: "Bungetu", comuna: "Vacaresti" },
  { nume: "Persinari", comuna: "Vacaresti" },
  { nume: "Bacesti", comuna: "Valea Lunga" },
  { nume: "Izvoru", comuna: "Valea Lunga" },
  { nume: "Mosia Mica", comuna: "Valea Lunga" },
  { nume: "Valea Lunga Gorgota", comuna: "Valea Lunga" },
  { nume: "Valea Lunga Ogrea", comuna: "Valea Lunga" },
  { nume: "Valea Lunga-Cricov", comuna: "Valea Lunga" },
  { nume: "Valea Mare", comuna: "Valea Lunga" },
  { nume: "Valea lui Dan", comuna: "Valea Lunga" },
  { nume: "Serbaneasa", comuna: "Valea Lunga" },
  { nume: "Stubeie Tisa", comuna: "Valea Lunga" },
  { nume: "Feteni", comuna: "Valea Mare" },
  { nume: "Garleni", comuna: "Valea Mare" },
  { nume: "Livezile", comuna: "Valea Mare" },
  { nume: "Saru", comuna: "Valea Mare" },
  { nume: "Stratonesti", comuna: "Valea Mare" },
  { nume: "Valea Caselor", comuna: "Valea Mare" },
  { nume: "Mesteacan", comuna: "Valeni-Dimbovita" },
  { nume: "Valeni-Dambovita", comuna: "Valeni-Dimbovita" },
  { nume: "Cojoiu", comuna: "Virfuri" },
  { nume: "Carlanesti", comuna: "Virfuri" },
  { nume: "Merisoru", comuna: "Virfuri" },
  { nume: "Statesti", comuna: "Virfuri" },
  { nume: "Ulmetu", comuna: "Virfuri" },
  { nume: "Varfuri", comuna: "Virfuri" },
  { nume: "Suvita", comuna: "Virfuri" },
  { nume: "Brosteni", comuna: "Visina" },
  { nume: "Izvoru", comuna: "Visina" },
  { nume: "Rascaeti", comuna: "Visina" },
  { nume: "Vultureanca", comuna: "Visina" },
  { nume: "Dospinesti", comuna: "Visinesti" },
  { nume: "Sultanu", comuna: "Visinesti" },
  { nume: "Urseiu", comuna: "Visinesti" },
  { nume: "Gemenea Bratulesti", comuna: "Voinesti" },
  { nume: "Izvoarele", comuna: "Voinesti" },
  { nume: "Lunca", comuna: "Voinesti" },
  { nume: "Manga", comuna: "Voinesti" },
  { nume: "Manjina", comuna: "Voinesti" },
  { nume: "Oncesti", comuna: "Voinesti" },
  { nume: "Suduleni", comuna: "Voinesti" },
  { nume: "Nicolaesti", comuna: "Vulcana-Bai" },
  { nume: "Vulcana de Sus", comuna: "Vulcana-Bai" },
  { nume: "Gura Vulcanei", comuna: "Vulcana-Pandele" },
  { nume: "Laculete-Gara", comuna: "Vulcana-Pandele" },
  { nume: "Toculesti", comuna: "Vulcana-Pandele" },
];
