export const dj = [
  { nume: "Afumati" },
  { nume: "Almaj" },
  { nume: "Amarastii de Jos" },
  { nume: "Amarastii de Sus" },
  { nume: "Apele Vii" },
  { nume: "Argetoaia" },
  { nume: "Bechet" },
  { nume: "Bistret" },
  { nume: "Botosesti-Paia" },
  { nume: "Brabova" },
  { nume: "Bralostita" },
  { nume: "Bratovoesti" },
  { nume: "Breasta" },
  { nume: "Bradesti" },
  { nume: "Bucovat" },
  { nume: "Bulzesti" },
  { nume: "Bailesti" },
  { nume: "Calafat" },
  { nume: "Calopar" },
  { nume: "Caraula" },
  { nume: "Carpen" },
  { nume: "Castranova" },
  { nume: "Celaru" },
  { nume: "Cernatesti" },
  { nume: "Cerat" },
  { nume: "Cetate" },
  { nume: "Cioroiasi" },
  { nume: "Ciupercenii Noi" },
  { nume: "Cosoveni" },
  { nume: "Cotofenii din Dos" },
  { nume: "Craiova" },
  { nume: "Calarasi" },
  { nume: "Daneti" },
  { nume: "Desa" },
  { nume: "Diosti" },
  { nume: "Dobresti" },
  { nume: "Dragotesti" },
  { nume: "Dranic" },
  { nume: "Dabuleni" },
  { nume: "Filiasi" },
  { nume: "Farcas" },
  { nume: "Galicea Mare" },
  { nume: "Ghercesti" },
  { nume: "Gighera" },
  { nume: "Giubega" },
  { nume: "Giurgita" },
  { nume: "Gogosu" },
  { nume: "Goicea" },
  { nume: "Goiesti" },
  { nume: "Grecesti" },
  { nume: "Izvoare" },
  { nume: "Isalnita" },
  { nume: "Leu" },
  { nume: "Lipovu" },
  { nume: "Maglavit" },
  { nume: "Malu Mare" },
  { nume: "Melinesti" },
  { nume: "Mischii" },
  { nume: "Motatei" },
  { nume: "Murgasi" },
  { nume: "Marsani" },
  { nume: "Macesu de Jos" },
  { nume: "Macesu de Sus" },
  { nume: "Negoi" },
  { nume: "Orodel" },
  { nume: "Ostroveni" },
  { nume: "Perisor" },
  { nume: "Pielesti" },
  { nume: "Piscu Vechi" },
  { nume: "Plenita" },
  { nume: "Podari" },
  { nume: "Poiana Mare" },
  { nume: "Predesti" },
  { nume: "Radovan" },
  { nume: "Rast" },
  { nume: "Sadova" },
  { nume: "Scaesti" },
  { nume: "Seaca de Camp" },
  { nume: "Seaca de Padure" },
  { nume: "Secu" },
  { nume: "Segarcea" },
  { nume: "Silistea Crucii" },
  { nume: "Sopot" },
  { nume: "Salcuta" },
  { nume: "Teasc" },
  { nume: "Terpezita" },
  { nume: "Teslui" },
  { nume: "Unirea" },
  { nume: "Urzicuta" },
  { nume: "Valea Stanciului" },
  { nume: "Vela" },
  { nume: "Verbita" },
  { nume: "Vartop" },
  { nume: "Varvoru de Jos" },
  { nume: "Simnicu de Sus" },
  { nume: "Tuglui" },
  { nume: "Boureni", comuna: "Afumati" },
  { nume: "Covei", comuna: "Afumati" },
  { nume: "Beharca", comuna: "Almaj" },
  { nume: "Bogea", comuna: "Almaj" },
  { nume: "Cotofenii din Fata", comuna: "Almaj" },
  { nume: "Mosneni", comuna: "Almaj" },
  { nume: "Sitoaia", comuna: "Almaj" },
  { nume: "Ocolna", comuna: "Amarastii De Jos" },
  { nume: "Prapor", comuna: "Amarastii De Jos" },
  { nume: "Dobrotesti", comuna: "Amarastii De Sus" },
  { nume: "Nisipuri", comuna: "Amarastii De Sus" },
  { nume: "Zvorsca", comuna: "Amarastii De Sus" },
  { nume: "Berbesu", comuna: "Argetoaia" },
  { nume: "Baranu", comuna: "Argetoaia" },
  { nume: "Iordachesti", comuna: "Argetoaia" },
  { nume: "Leordoasa", comuna: "Argetoaia" },
  { nume: "Malumnic", comuna: "Argetoaia" },
  { nume: "Novac", comuna: "Argetoaia" },
  { nume: "Piria", comuna: "Argetoaia" },
  { nume: "Poiana Fantanii", comuna: "Argetoaia" },
  { nume: "Salcia", comuna: "Argetoaia" },
  { nume: "Teascu din Deal", comuna: "Argetoaia" },
  { nume: "Ursoaia", comuna: "Argetoaia" },
  { nume: "Balasan", comuna: "Bailesti" },
  { nume: "Barca", comuna: "Birca" },
  { nume: "Bistretu Nou", comuna: "Bistret" },
  { nume: "Brandusa", comuna: "Bistret" },
  { nume: "Plosca", comuna: "Bistret" },
  { nume: "Caraiman", comuna: "Brabova" },
  { nume: "Mosna", comuna: "Brabova" },
  { nume: "Rachita de Jos", comuna: "Brabova" },
  { nume: "Urdinita", comuna: "Brabova" },
  { nume: "Voita", comuna: "Brabova" },
  { nume: "Bradestii Batrani", comuna: "Bradesti" },
  { nume: "Meteu", comuna: "Bradesti" },
  { nume: "Piscani", comuna: "Bradesti" },
  { nume: "Racarii de Jos", comuna: "Bradesti" },
  { nume: "Tatomiresti", comuna: "Bradesti" },
  { nume: "Ciocanele", comuna: "Bralostita" },
  { nume: "Racovita", comuna: "Bralostita" },
  { nume: "Schitu", comuna: "Bralostita" },
  { nume: "Sfarcea", comuna: "Bralostita" },
  { nume: "Valea Fantanilor", comuna: "Bralostita" },
  { nume: "Badosi", comuna: "Bratovoesti" },
  { nume: "Georocu Mare", comuna: "Bratovoesti" },
  { nume: "Prunet", comuna: "Bratovoesti" },
  { nume: "Rojiste", comuna: "Bratovoesti" },
  { nume: "Tamburesti", comuna: "Bratovoesti" },
  { nume: "Cotu", comuna: "Breasta" },
  { nume: "Crovna", comuna: "Breasta" },
  { nume: "Faget", comuna: "Breasta" },
  { nume: "Obedin", comuna: "Breasta" },
  { nume: "Rosieni", comuna: "Breasta" },
  { nume: "Valea Lungului", comuna: "Breasta" },
  { nume: "Carligei", comuna: "Bucovat" },
  { nume: "Italieni", comuna: "Bucovat" },
  { nume: "Leamna de Jos", comuna: "Bucovat" },
  { nume: "Leamna de Sus", comuna: "Bucovat" },
  { nume: "Palilula", comuna: "Bucovat" },
  { nume: "Sarbatoarea", comuna: "Bucovat" },
  { nume: "Fratila", comuna: "Bulzesti" },
  { nume: "Gura Racului", comuna: "Bulzesti" },
  { nume: "Piscu Lung", comuna: "Bulzesti" },
  { nume: "Poienile", comuna: "Bulzesti" },
  { nume: "Prejoi", comuna: "Bulzesti" },
  { nume: "Seculesti", comuna: "Bulzesti" },
  { nume: "Stoicesti", comuna: "Bulzesti" },
  { nume: "Saliste", comuna: "Bulzesti" },
  { nume: "Infratirea", comuna: "Bulzesti" },
  { nume: "Basarabi", comuna: "Calafat" },
  { nume: "Ciupercenii Vechi", comuna: "Calafat" },
  { nume: "Golenti", comuna: "Calafat" },
  { nume: "Sarata", comuna: "Calarasi" },
  { nume: "Belcinu", comuna: "Calopar" },
  { nume: "Bazdana", comuna: "Calopar" },
  { nume: "Panaghia", comuna: "Calopar" },
  { nume: "Salcuta", comuna: "Calopar" },
  { nume: "Cleanov", comuna: "Carpen" },
  { nume: "Geblesti", comuna: "Carpen" },
  { nume: "Puturi", comuna: "Castranova" },
  { nume: "Ghizdavesti", comuna: "Celaru" },
  { nume: "Marotinu de Jos", comuna: "Celaru" },
  { nume: "Marotinu de Sus", comuna: "Celaru" },
  { nume: "Soreni", comuna: "Celaru" },
  { nume: "Malaica", comuna: "Cerat" },
  { nume: "Cornita", comuna: "Cernatesti" },
  { nume: "Rasnicu Batran", comuna: "Cernatesti" },
  { nume: "Rasnicu Oghian", comuna: "Cernatesti" },
  { nume: "Tiu", comuna: "Cernatesti" },
  { nume: "Moreni", comuna: "Cetate" },
  { nume: "Cetatuia", comuna: "Cioroiasi" },
  { nume: "Cioroiu Nou", comuna: "Cioroiasi" },
  { nume: "Smardan", comuna: "Ciupercenii Noi" },
  { nume: "Carcea", comuna: "Cosoveni" },
  { nume: "Mihaita", comuna: "Cotofenii Din Dos" },
  { nume: "Potmeltu", comuna: "Cotofenii Din Dos" },
  { nume: "Cernele", comuna: "Craiova" },
  { nume: "Cernelele de Sus", comuna: "Craiova" },
  { nume: "Facai", comuna: "Craiova" },
  { nume: "Izvorul Rece", comuna: "Craiova" },
  { nume: "Mofleni", comuna: "Craiova" },
  { nume: "Popoveni", comuna: "Craiova" },
  { nume: "Rovine", comuna: "Craiova" },
  { nume: "Simnicu de Jos", comuna: "Craiova" },
  { nume: "Chiasu", comuna: "Dabuleni" },
  { nume: "Brabeti", comuna: "Daneti" },
  { nume: "Braniste", comuna: "Daneti" },
  { nume: "Locusteni", comuna: "Daneti" },
  { nume: "Ciocanesti", comuna: "Diosti" },
  { nume: "Radomir", comuna: "Diosti" },
  { nume: "Caciulatesti", comuna: "Dobresti" },
  { nume: "Georocel", comuna: "Dobresti" },
  { nume: "Murta", comuna: "Dobresti" },
  { nume: "Toceni", comuna: "Dobresti" },
  { nume: "Benesti", comuna: "Dragotesti" },
  { nume: "Bobeanu", comuna: "Dragotesti" },
  { nume: "Buzduc", comuna: "Dragotesti" },
  { nume: "Popanzalesti", comuna: "Dragotesti" },
  { nume: "Viisoara", comuna: "Dragotesti" },
  { nume: "Booveni", comuna: "Dranic" },
  { nume: "Foisor", comuna: "Dranic" },
  { nume: "Padea", comuna: "Dranic" },
  { nume: "Amarasti", comuna: "Farcas" },
  { nume: "Golumbelu", comuna: "Farcas" },
  { nume: "Golumbu", comuna: "Farcas" },
  { nume: "Moflesti", comuna: "Farcas" },
  { nume: "Nistoi", comuna: "Farcas" },
  { nume: "Plopu Amarasti", comuna: "Farcas" },
  { nume: "Putinei", comuna: "Farcas" },
  { nume: "Soceni", comuna: "Farcas" },
  { nume: "Talpas", comuna: "Farcas" },
  { nume: "Almajel", comuna: "Filiasi" },
  { nume: "Braniste", comuna: "Filiasi" },
  { nume: "Balta", comuna: "Filiasi" },
  { nume: "Fratostita", comuna: "Filiasi" },
  { nume: "Racarii de Sus", comuna: "Filiasi" },
  { nume: "Uscaci", comuna: "Filiasi" },
  { nume: "Garlesti", comuna: "Ghercesti" },
  { nume: "Luncsoru", comuna: "Ghercesti" },
  { nume: "Ungureni", comuna: "Ghercesti" },
  { nume: "Ungurenii Mici", comuna: "Ghercesti" },
  { nume: "Nedeia", comuna: "Gighera" },
  { nume: "Zaval", comuna: "Gighera" },
  { nume: "Comosteni", comuna: "Gingiova" },
  { nume: "Gangiova", comuna: "Gingiova" },
  { nume: "Galiciuica", comuna: "Giubega" },
  { nume: "Curmatura", comuna: "Giurgita" },
  { nume: "Filaret", comuna: "Giurgita" },
  { nume: "Gogosita", comuna: "Gogosu" },
  { nume: "Stefanel", comuna: "Gogosu" },
  { nume: "Carna", comuna: "Goicea" },
  { nume: "Adancata", comuna: "Goiesti" },
  { nume: "Fantani", comuna: "Goiesti" },
  { nume: "Gruita", comuna: "Goiesti" },
  { nume: "Mogosesti", comuna: "Goiesti" },
  { nume: "Muereni", comuna: "Goiesti" },
  { nume: "Malaesti", comuna: "Goiesti" },
  { nume: "Pioresti", comuna: "Goiesti" },
  { nume: "Pometesti", comuna: "Goiesti" },
  { nume: "Popeasa", comuna: "Goiesti" },
  { nume: "Vladimir", comuna: "Goiesti" },
  { nume: "Zlatari", comuna: "Goiesti" },
  { nume: "Tandara", comuna: "Goiesti" },
  { nume: "Busu", comuna: "Grecesti" },
  { nume: "Busuletu", comuna: "Grecesti" },
  { nume: "Barboi", comuna: "Grecesti" },
  { nume: "Gropanele", comuna: "Grecesti" },
  { nume: "Gradistea", comuna: "Grecesti" },
  { nume: "Corlate", comuna: "Izvoare" },
  { nume: "Domnu Tudor", comuna: "Izvoare" },
  { nume: "Zanoaga", comuna: "Leu" },
  { nume: "Lipovu de Sus", comuna: "Lipovu" },
  { nume: "Sapata", comuna: "Macesu De Jos" },
  { nume: "Hunia", comuna: "Maglavit" },
  { nume: "Ghindeni", comuna: "Malu Mare" },
  { nume: "Preajba", comuna: "Malu Mare" },
  { nume: "Bodaiesti", comuna: "Melinesti" },
  { nume: "Bodaiestii de Sus", comuna: "Melinesti" },
  { nume: "Godeni", comuna: "Melinesti" },
  { nume: "Muierusu", comuna: "Melinesti" },
  { nume: "Negoiesti", comuna: "Melinesti" },
  { nume: "Odoleni", comuna: "Melinesti" },
  { nume: "Ohaba", comuna: "Melinesti" },
  { nume: "Plostina", comuna: "Melinesti" },
  { nume: "Popesti", comuna: "Melinesti" },
  { nume: "Spineni", comuna: "Melinesti" },
  { nume: "Valea Mare", comuna: "Melinesti" },
  { nume: "Valea Muierii de Jos", comuna: "Melinesti" },
  { nume: "Calinesti", comuna: "Mischii" },
  { nume: "Gogosesti", comuna: "Mischii" },
  { nume: "Mlecanesti", comuna: "Mischii" },
  { nume: "Motoci", comuna: "Mischii" },
  { nume: "Urechesti", comuna: "Mischii" },
  { nume: "Dobridor", comuna: "Motatei" },
  { nume: "Motatei Gara", comuna: "Motatei" },
  { nume: "Balota de Jos", comuna: "Murgasi" },
  { nume: "Balota de Sus", comuna: "Murgasi" },
  { nume: "Busteni", comuna: "Murgasi" },
  { nume: "Gaia", comuna: "Murgasi" },
  { nume: "Picaturile", comuna: "Murgasi" },
  { nume: "Rupturile", comuna: "Murgasi" },
  { nume: "Velesti", comuna: "Murgasi" },
  { nume: "Catane", comuna: "Negoi" },
  { nume: "Catanele Noi", comuna: "Negoi" },
  { nume: "Bechet", comuna: "Orodel" },
  { nume: "Cornu", comuna: "Orodel" },
  { nume: "Calugarei", comuna: "Orodel" },
  { nume: "Teiu", comuna: "Orodel" },
  { nume: "Listeava", comuna: "Ostroveni" },
  { nume: "Maracinele", comuna: "Perisor" },
  { nume: "Campeni", comuna: "Pielesti" },
  { nume: "Langa", comuna: "Pielesti" },
  { nume: "Ghidici", comuna: "Piscu Vechi" },
  { nume: "Pisculet", comuna: "Piscu Vechi" },
  { nume: "Castrele Traiane", comuna: "Plenita" },
  { nume: "Balta Verde", comuna: "Podari" },
  { nume: "Braniste", comuna: "Podari" },
  { nume: "Gura Vaii", comuna: "Podari" },
  { nume: "Livezi", comuna: "Podari" },
  { nume: "Tunarii Noi", comuna: "Poiana Mare" },
  { nume: "Tunarii Vechi", comuna: "Poiana Mare" },
  { nume: "Bucicani", comuna: "Predesti" },
  { nume: "Carstovani", comuna: "Predesti" },
  { nume: "Frasin", comuna: "Predesti" },
  { nume: "Milovan", comuna: "Predesti" },
  { nume: "Plesoi", comuna: "Predesti" },
  { nume: "Predestii Mici", comuna: "Predesti" },
  { nume: "Fantanele", comuna: "Radovan" },
  { nume: "Tarnava", comuna: "Radovan" },
  { nume: "Intorsura", comuna: "Radovan" },
  { nume: "Bojoiu", comuna: "Robanesti" },
  { nume: "Golfin", comuna: "Robanesti" },
  { nume: "Lacrita Mare", comuna: "Robanesti" },
  { nume: "Lacrita Mica", comuna: "Robanesti" },
  { nume: "Robanestii de Jos", comuna: "Robanesti" },
  { nume: "Robanestii de Sus", comuna: "Robanesti" },
  { nume: "Piscu Sadovei", comuna: "Sadova" },
  { nume: "Marza", comuna: "Salcuta" },
  { nume: "Plopsor", comuna: "Salcuta" },
  { nume: "Tencanau", comuna: "Salcuta" },
  { nume: "Valea lui Patru", comuna: "Scaesti" },
  { nume: "Piscu Nou", comuna: "Seaca De Camp" },
  { nume: "Rachita de Sus", comuna: "Seaca De Padure" },
  { nume: "Veleni", comuna: "Seaca De Padure" },
  { nume: "Comanicea", comuna: "Secu" },
  { nume: "Smadovicioara de Secu", comuna: "Secu" },
  { nume: "Sumandra", comuna: "Secu" },
  { nume: "Albesti", comuna: "Simnicu De Sus" },
  { nume: "Cornetu", comuna: "Simnicu De Sus" },
  { nume: "Deleni", comuna: "Simnicu De Sus" },
  { nume: "Dudovicesti", comuna: "Simnicu De Sus" },
  { nume: "Dutulesti", comuna: "Simnicu De Sus" },
  { nume: "Floresti", comuna: "Simnicu De Sus" },
  { nume: "Izvor", comuna: "Simnicu De Sus" },
  { nume: "Jieni", comuna: "Simnicu De Sus" },
  { nume: "Lesile", comuna: "Simnicu De Sus" },
  { nume: "Milesti", comuna: "Simnicu De Sus" },
  { nume: "Romanesti", comuna: "Simnicu De Sus" },
  { nume: "Bascov", comuna: "Sopot" },
  { nume: "Belot", comuna: "Sopot" },
  { nume: "Cernat", comuna: "Sopot" },
  { nume: "Pereni", comuna: "Sopot" },
  { nume: "Pietroaia", comuna: "Sopot" },
  { nume: "Sarsca", comuna: "Sopot" },
  { nume: "Secui", comuna: "Teasc" },
  { nume: "Caciulatu", comuna: "Terpezita" },
  { nume: "Caruia", comuna: "Terpezita" },
  { nume: "Floran", comuna: "Terpezita" },
  { nume: "Lazu", comuna: "Terpezita" },
  { nume: "Cosereni", comuna: "Teslui" },
  { nume: "Fantanele", comuna: "Teslui" },
  { nume: "Preajba de Jos", comuna: "Teslui" },
  { nume: "Preajba de Padure", comuna: "Teslui" },
  { nume: "Urieni", comuna: "Teslui" },
  { nume: "Viisoara Mosneni", comuna: "Teslui" },
  { nume: "Tartal", comuna: "Teslui" },
  { nume: "Jiul", comuna: "Tuglui" },
  { nume: "Urzica Mare", comuna: "Urzicuta" },
  { nume: "Horezu Poenari", comuna: "Valea Stanciului" },
  { nume: "Bujor", comuna: "Varvoru De Jos" },
  { nume: "Ciutura", comuna: "Varvoru De Jos" },
  { nume: "Criva", comuna: "Varvoru De Jos" },
  { nume: "Dobromira", comuna: "Varvoru De Jos" },
  { nume: "Dragoaia", comuna: "Varvoru De Jos" },
  { nume: "Gabru", comuna: "Varvoru De Jos" },
  { nume: "Varvor", comuna: "Varvoru De Jos" },
  { nume: "Bucovicior", comuna: "Vela" },
  { nume: "Cetatuia", comuna: "Vela" },
  { nume: "Desnatui", comuna: "Vela" },
  { nume: "Gubaucea", comuna: "Vela" },
  { nume: "Seglet", comuna: "Vela" },
  { nume: "Suharu", comuna: "Vela" },
  { nume: "Stiubei", comuna: "Vela" },
  { nume: "Verbicioara", comuna: "Verbita" },
];
