// All counties in Romania

export const judete = [
  { auto: "AB", nume: "Alba" },
  { auto: "AR", nume: "Arad" },
  { auto: "AG", nume: "Argeș" },
  { auto: "BC", nume: "Bacău" },
  { auto: "BH", nume: "Bihor" },
  { auto: "BN", nume: "Bistrița-Năsăud" },
  { auto: "BT", nume: "Botoșani" },
  { auto: "BV", nume: "Brașov" },
  { auto: "BR", nume: "Brăila" },
  { auto: "B", nume: "București" },
  { auto: "BZ", nume: "Buzău" },
  { auto: "CS", nume: "Caraș-Severin" },
  { auto: "CL", nume: "Călărași" },
  { auto: "CJ", nume: "Cluj" },
  { auto: "CT", nume: "Constanța" },
  { auto: "CV", nume: "Covasna" },
  { auto: "DB", nume: "Dâmbovița" },
  { auto: "DJ", nume: "Dolj" },
  { auto: "GL", nume: "Galați" },
  { auto: "GR", nume: "Giurgiu" },
  { auto: "GJ", nume: "Gorj" },
  { auto: "HR", nume: "Harghita" },
  { auto: "HD", nume: "Hunedoara" },
  { auto: "IL", nume: "Ialomița" },
  { auto: "IS", nume: "Iași" },
  { auto: "IF", nume: "Ilfov" },
  { auto: "MM", nume: "Maramureș" },
  { auto: "MH", nume: "Mehedinți" },
  { auto: "MS", nume: "Mureș" },
  { auto: "NT", nume: "Neamț" },
  { auto: "OT", nume: "Olt" },
  { auto: "PH", nume: "Prahova" },
  { auto: "SM", nume: "Satu Mare" },
  { auto: "SJ", nume: "Sălaj" },
  { auto: "SB", nume: "Sibiu" },
  { auto: "SV", nume: "Suceava" },
  { auto: "TR", nume: "Teleorman" },
  { auto: "TM", nume: "Timiș" },
  { auto: "TL", nume: "Tulcea" },
  { auto: "VL", nume: "Vâlcea" },
  { auto: "VS", nume: "Vaslui" },
  { auto: "VN", nume: "Vrancea" },
];
