// All counties in Romania

export const judete = [
  { auto: "AB", nume: "Alba" },
  { auto: "AR", nume: "Arad" },
  { auto: "AG", nume: "Arges" },
  { auto: "BC", nume: "Bacau" },
  { auto: "BH", nume: "Bihor" },
  { auto: "BN", nume: "Bistrita-Nasaud" },
  { auto: "BT", nume: "Botosani" },
  { auto: "BV", nume: "Brasov" },
  { auto: "BR", nume: "Braila" },
  { auto: "B", nume: "Bucuresti" },
  { auto: "BZ", nume: "Buzau" },
  { auto: "CS", nume: "Caras-Severin" },
  { auto: "CL", nume: "Calarasi" },
  { auto: "CJ", nume: "Cluj" },
  { auto: "CT", nume: "Constanta" },
  { auto: "CV", nume: "Covasna" },
  { auto: "DB", nume: "Dambovita" },
  { auto: "DJ", nume: "Dolj" },
  { auto: "GL", nume: "Galati" },
  { auto: "GR", nume: "Giurgiu" },
  { auto: "GJ", nume: "Gorj" },
  { auto: "HR", nume: "Harghita" },
  { auto: "HD", nume: "Hunedoara" },
  { auto: "IL", nume: "Ialomita" },
  { auto: "IS", nume: "Iasi" },
  { auto: "IF", nume: "Ilfov" },
  { auto: "MM", nume: "Maramures" },
  { auto: "MH", nume: "Mehedinti" },
  { auto: "MS", nume: "Mures" },
  { auto: "NT", nume: "Neamt" },
  { auto: "OT", nume: "Olt" },
  { auto: "PH", nume: "Prahova" },
  { auto: "SM", nume: "Satu Mare" },
  { auto: "SJ", nume: "Salaj" },
  { auto: "SB", nume: "Sibiu" },
  { auto: "SV", nume: "Suceava" },
  { auto: "TR", nume: "Teleorman" },
  { auto: "TM", nume: "Timis" },
  { auto: "TL", nume: "Tulcea" },
  { auto: "VL", nume: "Valcea" },
  { auto: "VS", nume: "Vaslui" },
  { auto: "VN", nume: "Vrancea" },
];
