export const gl = [
  { nume: "Adam", comuna: "Draguseni" },
  { nume: "Aldești", simplu: "Aldesti", comuna: "Beresti-Meria" },
  { nume: "Bălăbănești", simplu: "Balabanesti" },
  { nume: "Bălășești", simplu: "Balasesti" },
  { nume: "Băleni", simplu: "Baleni" },
  { nume: "Balintești", simplu: "Balintesti", comuna: "Beresti-Meria" },
  { nume: "Băltăreți", simplu: "Baltareti", comuna: "Cosmesti" },
  { nume: "Băneasa", simplu: "Baneasa" },
  { nume: "Barcea" },
  { nume: "Berești-Meria", simplu: "Beresti-Meria" },
  { nume: "Berești", simplu: "Beresti" },
  { nume: "Blânzi", simplu: "Blanzi", comuna: "Corod" },
  { nume: "Brăhășești", simplu: "Brahasesti" },
  { nume: "Brănești", simplu: "Branesti", comuna: "Vladesti" },
  { nume: "Braniștea", simplu: "Branistea" },
  { nume: "Brăniștea", simplu: "Branistea", comuna: "Nicoresti" },
  { nume: "Brătulești", simplu: "Bratulesti", comuna: "Corod" },
  { nume: "Bucești", simplu: "Bucesti", comuna: "Ivesti" },
  { nume: "Buciumeni" },
  { nume: "Bursucani", comuna: "Balabanesti" },
  { nume: "Călmățui", simplu: "Calmatui", comuna: "Grivita" },
  { nume: "Cărăpcești", simplu: "Carapcesti", comuna: "Corod" },
  { nume: "Cârlomănești", simplu: "Carlomanesti", comuna: "Certesti" },
  { nume: "Căuiești", simplu: "Cauiesti", comuna: "Draguseni" },
  { nume: "Cavadinești", simplu: "Cavadinesti" },
  { nume: "Cerțești", simplu: "Certesti" },
  { nume: "Chiraftei", comuna: "Mastacani" },
  { nume: "Ciorăști", simplu: "Ciorasti", comuna: "Priponesti" },
  { nume: "Cișmele", simplu: "Cismele", comuna: "Smardan" },
  { nume: "Ciurești", simplu: "Ciuresti", comuna: "Balasesti" },
  { nume: "Ciureștii Noi", simplu: "Ciurestii Noi", comuna: "Balasesti" },
  { nume: "Coasta Lupei", comuna: "Nicoresti" },
  { nume: "Comănești", simplu: "Comanesti", comuna: "Cavadinesti" },
  { nume: "Condrea", comuna: "Umbraresti" },
  { nume: "Corcioveni", comuna: "Brahasesti" },
  { nume: "Corni" },
  { nume: "Corod" },
  { nume: "Cosițeni", simplu: "Cositeni", comuna: "Brahasesti" },
  { nume: "Cosmești", simplu: "Cosmesti" },
  { nume: "Cosmeștii-Vale", simplu: "Cosmestii-Vale", comuna: "Cosmesti" },
  { nume: "Costache Negri" },
  { nume: "Costi", comuna: "Vanatori" },
  { nume: "Cotoroaia", comuna: "Certesti" },
  { nume: "Crăiești", simplu: "Craiesti", comuna: "Varlezi" },
  { nume: "Crângeni", simplu: "Crangeni", comuna: "Namoloasa" },
  { nume: "Cruceanu", comuna: "Balabanesti" },
  { nume: "Cuca" },
  { nume: "Cudalbi" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Slobozia Conachi" },
  { nume: "Dobrinești", simplu: "Dobrinesti", comuna: "Nicoresti" },
  { nume: "Drăgănești", simplu: "Draganesti" },
  { nume: "Drăgușeni", simplu: "Draguseni" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Scanteiesti" },
  { nume: "Fântâni", simplu: "Fantani", comuna: "Nicoresti" },
  { nume: "Fârțănești", simplu: "Fartanesti" },
  { nume: "Foltești", simplu: "Foltesti" },
  { nume: "Frumușița", simplu: "Frumusita" },
  { nume: "Frunzeasca", comuna: "Munteni" },
  { nume: "Fundeanu", comuna: "Draguseni" },
  { nume: "Fundeni" },
  { nume: "Fundenii Noi", comuna: "Fundeni" },
  { nume: "Furcenii Noi", comuna: "Cosmesti" },
  { nume: "Furcenii Vechi", comuna: "Cosmesti" },
  { nume: "Galați", simplu: "Galati" },
  { nume: "Gănești", simplu: "Ganesti", comuna: "Cavadinesti" },
  { nume: "Gara Berheci", comuna: "Gohor" },
  { nume: "Gara Ghidigeni", comuna: "Ghidigeni" },
  { nume: "Gârbovăț", simplu: "Garbovat", comuna: "Ghidigeni" },
  { nume: "Gefu", comuna: "Ghidigeni" },
  { nume: "Ghidigeni" },
  { nume: "Ghinghești", simplu: "Ghinghesti", comuna: "Draguseni" },
  { nume: "Gohor" },
  { nume: "Grivița", simplu: "Grivita" },
  { nume: "Grozăvești", simplu: "Grozavesti", comuna: "Nicoresti" },
  {
    nume: "Gura Gârbovățului",
    simplu: "Gura Garbovatului",
    comuna: "Ghidigeni",
  },
  { nume: "Hănțești", simplu: "Hantesti", comuna: "Buciumeni" },
  { nume: "Hanu Conachi", comuna: "Fundeni" },
  { nume: "Huștiu", simplu: "Hustiu", comuna: "Priponesti" },
  { nume: "Ijdileni", comuna: "Frumusita" },
  { nume: "Independența", simplu: "Independenta" },
  { nume: "Ionășești", simplu: "Ionasesti", comuna: "Nicoresti" },
  { nume: "Ireasca", comuna: "Gohor" },
  { nume: "Ivești", simplu: "Ivesti" },
  { nume: "Izvoarele", comuna: "Slobozia Conachi" },
  { nume: "Jorăști", simplu: "Jorasti" },
  { nume: "Liești", simplu: "Liesti" },
  { nume: "Liești", simplu: "Liesti", comuna: "Priponesti" },
  { nume: "Lozova", comuna: "Branistea" },
  { nume: "Lunca", comuna: "Jorasti" },
  { nume: "Lungești", simplu: "Lungesti", comuna: "Balabanesti" },
  { nume: "Lungoci", comuna: "Fundeni" },
  { nume: "Lupele", comuna: "Pechea" },
  { nume: "Măcișeni", simplu: "Maciseni", comuna: "Corni" },
  { nume: "Malu Alb", comuna: "Draganesti" },
  { nume: "Mălureni", simplu: "Malureni", comuna: "Nicoresti" },
  { nume: "Mândrești", simplu: "Mandresti", comuna: "Valea Marului" },
  { nume: "Măstăcani", simplu: "Mastacani" },
  { nume: "Matca" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Smardan",
  },
  { nume: "Moscu", comuna: "Targu Bujor" },
  { nume: "Movileni" },
  { nume: "Movileni", comuna: "Sendreni" },
  { nume: "Munteni" },
  { nume: "Nămoloasa Sat", simplu: "Namoloasa Sat", comuna: "Namoloasa" },
  { nume: "Nămoloasa", simplu: "Namoloasa" },
  { nume: "Nărtești", simplu: "Nartesti", comuna: "Gohor" },
  { nume: "Negrea", comuna: "Schela" },
  { nume: "Negrilești", simplu: "Negrilesti", comuna: "Munteni" },
  { nume: "Nicopole", comuna: "Draguseni" },
  { nume: "Nicorești", simplu: "Nicoresti" },
  { nume: "Oancea" },
  { nume: "Odaia Manolache", comuna: "Vanatori" },
  { nume: "Onciu", comuna: "Beresti-Meria" },
  { nume: "Pechea" },
  { nume: "Piscu Corbului", comuna: "Nicoresti" },
  { nume: "Piscu" },
  { nume: "Pleșa", simplu: "Plesa", comuna: "Beresti-Meria" },
  { nume: "Plevna", comuna: "Rediu" },
  { nume: "Podoleni", comuna: "Barcea" },
  { nume: "Poiana", comuna: "Nicoresti" },
  { nume: "Poșta", simplu: "Posta", comuna: "Gohor" },
  { nume: "Priponești", simplu: "Priponesti" },
  {
    nume: "Priponeștii de Jos",
    simplu: "Priponestii de Jos",
    comuna: "Priponesti",
  },
  { nume: "Prodănești", simplu: "Prodanesti", comuna: "Beresti-Meria" },
  { nume: "Pupezeni", comuna: "Balasesti" },
  { nume: "Puricani", comuna: "Beresti-Meria" },
  { nume: "Rădești", simplu: "Radesti", comuna: "Balabanesti" },
  { nume: "Rediu" },
  { nume: "Rogojeni", comuna: "Suceveni" },
  { nume: "Roșcani", simplu: "Roscani", comuna: "Baneasa" },
  { nume: "Salcia", comuna: "Umbraresti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Nicoresti" },
  { nume: "Săseni", simplu: "Saseni", comuna: "Beresti-Meria" },
  { nume: "Satu Nou", comuna: "Cosmesti" },
  { nume: "Scânteiești", simplu: "Scanteiesti" },
  { nume: "Schela" },
  { nume: "Șendreni", simplu: "Sendreni" },
  { nume: "Șerbeștii Vechi", simplu: "Serbestii Vechi", comuna: "Sendreni" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Umbraresti" },
  { nume: "Șipote", simplu: "Sipote", comuna: "Beresti-Meria" },
  { nume: "Șivița", simplu: "Sivita", comuna: "Tulucesti" },
  { nume: "Slivna", comuna: "Beresti-Meria" },
  { nume: "Slobozia Blăneasa", simplu: "Slobozia Blaneasa", comuna: "Munteni" },
  { nume: "Slobozia Conachi" },
  { nume: "Slobozia Corni", comuna: "Ghidigeni" },
  { nume: "Slobozia Oancea", comuna: "Oancea" },
  { nume: "Smârdan", simplu: "Smardan" },
  { nume: "Smulți", simplu: "Smulti" },
  { nume: "Știețești", simplu: "Stietesti", comuna: "Draguseni" },
  { nume: "Stoicani", comuna: "Foltesti" },
  { nume: "Suceveni" },
  { nume: "Suhurlui", comuna: "Rediu" },
  { nume: "Tălpigi", simplu: "Talpigi", comuna: "Ghidigeni" },
  { nume: "Tămăoani", simplu: "Tamaoani", comuna: "Frumusita" },
  { nume: "Tăplău", simplu: "Taplau", comuna: "Ghidigeni" },
  { nume: "Târgu Bujor", simplu: "Targu Bujor" },
  { nume: "Tătarca", simplu: "Tatarca", comuna: "Tulucesti" },
  { nume: "Tecucelu Sec", comuna: "Buciumeni" },
  { nume: "Tecuci" },
  { nume: "Țepu de Sus", simplu: "Tepu de Sus", comuna: "Tepu" },
  { nume: "Țepu", simplu: "Tepu" },
  { nume: "Țigănești", simplu: "Tiganesti", comuna: "Munteni" },
  { nume: "Toflea", comuna: "Brahasesti" },
  { nume: "Torcești", simplu: "Torcesti", comuna: "Umbraresti" },
  { nume: "Traian", comuna: "Branistea" },
  { nume: "Tudor Vladimirescu" },
  { nume: "Tulucești", simplu: "Tulucesti" },
  { nume: "Umbrărești-Deal", simplu: "Umbraresti-Deal", comuna: "Umbraresti" },
  { nume: "Umbrărești", simplu: "Umbraresti" },
  { nume: "Umbrărești", simplu: "Umbraresti", comuna: "Targu Bujor" },
  { nume: "Ungureni", comuna: "Munteni" },
  { nume: "Urlești", simplu: "Urlesti", comuna: "Corni" },
  { nume: "Vădeni", simplu: "Vadeni", comuna: "Cavadinesti" },
  { nume: "Valea Mărului", simplu: "Valea Marului" },
  { nume: "Vameș", simplu: "Vames", comuna: "Piscu" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Vărlezi", simplu: "Varlezi" },
  { nume: "Vasile Alecsandri", comuna: "Branistea" },
  { nume: "Viile", comuna: "Fartanesti" },
  { nume: "Vișina", simplu: "Visina", comuna: "Nicoresti" },
  { nume: "Vizurești", simplu: "Vizuresti", comuna: "Buciumeni" },
  { nume: "Vlădești", simplu: "Vladesti" },
  { nume: "Zărnești", simplu: "Zarnesti", comuna: "Jorasti" },
  { nume: "Zimbru", comuna: "Balabanesti" },
];
