export const gl = [
  { nume: "Adam", comuna: "Draguseni" },
  { nume: "Aldeşti", simplu: "Aldesti", comuna: "Beresti-Meria" },
  { nume: "Bălăbăneşti", simplu: "Balabanesti" },
  { nume: "Bălăşeşti", simplu: "Balasesti" },
  { nume: "Băleni", simplu: "Baleni" },
  { nume: "Balinteşti", simplu: "Balintesti", comuna: "Beresti-Meria" },
  { nume: "Băltăreţi", simplu: "Baltareti", comuna: "Cosmesti" },
  { nume: "Băneasa", simplu: "Baneasa" },
  { nume: "Barcea" },
  { nume: "Bereşti-Meria", simplu: "Beresti-Meria" },
  { nume: "Bereşti", simplu: "Beresti" },
  { nume: "Blânzi", simplu: "Blanzi", comuna: "Corod" },
  { nume: "Brăhăşeşti", simplu: "Brahasesti" },
  { nume: "Brăneşti", simplu: "Branesti", comuna: "Vladesti" },
  { nume: "Braniştea", simplu: "Branistea" },
  { nume: "Brăniştea", simplu: "Branistea", comuna: "Nicoresti" },
  { nume: "Brătuleşti", simplu: "Bratulesti", comuna: "Corod" },
  { nume: "Buceşti", simplu: "Bucesti", comuna: "Ivesti" },
  { nume: "Buciumeni" },
  { nume: "Bursucani", comuna: "Balabanesti" },
  { nume: "Călmăţui", simplu: "Calmatui", comuna: "Grivita" },
  { nume: "Cărăpceşti", simplu: "Carapcesti", comuna: "Corod" },
  { nume: "Cârlomăneşti", simplu: "Carlomanesti", comuna: "Certesti" },
  { nume: "Căuieşti", simplu: "Cauiesti", comuna: "Draguseni" },
  { nume: "Cavadineşti", simplu: "Cavadinesti" },
  { nume: "Cerţeşti", simplu: "Certesti" },
  { nume: "Chiraftei", comuna: "Mastacani" },
  { nume: "Ciorăşti", simplu: "Ciorasti", comuna: "Priponesti" },
  { nume: "Cişmele", simplu: "Cismele", comuna: "Smardan" },
  { nume: "Ciureşti", simplu: "Ciuresti", comuna: "Balasesti" },
  { nume: "Ciureştii Noi", simplu: "Ciurestii Noi", comuna: "Balasesti" },
  { nume: "Coasta Lupei", comuna: "Nicoresti" },
  { nume: "Comăneşti", simplu: "Comanesti", comuna: "Cavadinesti" },
  { nume: "Condrea", comuna: "Umbraresti" },
  { nume: "Corcioveni", comuna: "Brahasesti" },
  { nume: "Corni" },
  { nume: "Corod" },
  { nume: "Cosiţeni", simplu: "Cositeni", comuna: "Brahasesti" },
  { nume: "Cosmeşti", simplu: "Cosmesti" },
  { nume: "Cosmeştii-Vale", simplu: "Cosmestii-Vale", comuna: "Cosmesti" },
  { nume: "Costache Negri" },
  { nume: "Costi", comuna: "Vanatori" },
  { nume: "Cotoroaia", comuna: "Certesti" },
  { nume: "Crăieşti", simplu: "Craiesti", comuna: "Varlezi" },
  { nume: "Crângeni", simplu: "Crangeni", comuna: "Namoloasa" },
  { nume: "Cruceanu", comuna: "Balabanesti" },
  { nume: "Cuca" },
  { nume: "Cudalbi" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Slobozia Conachi" },
  { nume: "Dobrineşti", simplu: "Dobrinesti", comuna: "Nicoresti" },
  { nume: "Drăgăneşti", simplu: "Draganesti" },
  { nume: "Drăguşeni", simplu: "Draguseni" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Scanteiesti" },
  { nume: "Fântâni", simplu: "Fantani", comuna: "Nicoresti" },
  { nume: "Fârţăneşti", simplu: "Fartanesti" },
  { nume: "Folteşti", simplu: "Foltesti" },
  { nume: "Frumuşiţa", simplu: "Frumusita" },
  { nume: "Frunzeasca", comuna: "Munteni" },
  { nume: "Fundeanu", comuna: "Draguseni" },
  { nume: "Fundeni" },
  { nume: "Fundenii Noi", comuna: "Fundeni" },
  { nume: "Furcenii Noi", comuna: "Cosmesti" },
  { nume: "Furcenii Vechi", comuna: "Cosmesti" },
  { nume: "Galaţi", simplu: "Galati" },
  { nume: "Găneşti", simplu: "Ganesti", comuna: "Cavadinesti" },
  { nume: "Gara Berheci", comuna: "Gohor" },
  { nume: "Gara Ghidigeni", comuna: "Ghidigeni" },
  { nume: "Gârbovăţ", simplu: "Garbovat", comuna: "Ghidigeni" },
  { nume: "Gefu", comuna: "Ghidigeni" },
  { nume: "Ghidigeni" },
  { nume: "Ghingheşti", simplu: "Ghinghesti", comuna: "Draguseni" },
  { nume: "Gohor" },
  { nume: "Griviţa", simplu: "Grivita" },
  { nume: "Grozăveşti", simplu: "Grozavesti", comuna: "Nicoresti" },
  {
    nume: "Gura Gârbovăţului",
    simplu: "Gura Garbovatului",
    comuna: "Ghidigeni",
  },
  { nume: "Hănţeşti", simplu: "Hantesti", comuna: "Buciumeni" },
  { nume: "Hanu Conachi", comuna: "Fundeni" },
  { nume: "Huştiu", simplu: "Hustiu", comuna: "Priponesti" },
  { nume: "Ijdileni", comuna: "Frumusita" },
  { nume: "Independenţa", simplu: "Independenta" },
  { nume: "Ionăşeşti", simplu: "Ionasesti", comuna: "Nicoresti" },
  { nume: "Ireasca", comuna: "Gohor" },
  { nume: "Iveşti", simplu: "Ivesti" },
  { nume: "Izvoarele", comuna: "Slobozia Conachi" },
  { nume: "Jorăşti", simplu: "Jorasti" },
  { nume: "Lieşti", simplu: "Liesti" },
  { nume: "Lieşti", simplu: "Liesti", comuna: "Priponesti" },
  { nume: "Lozova", comuna: "Branistea" },
  { nume: "Lunca", comuna: "Jorasti" },
  { nume: "Lungeşti", simplu: "Lungesti", comuna: "Balabanesti" },
  { nume: "Lungoci", comuna: "Fundeni" },
  { nume: "Lupele", comuna: "Pechea" },
  { nume: "Măcişeni", simplu: "Maciseni", comuna: "Corni" },
  { nume: "Malu Alb", comuna: "Draganesti" },
  { nume: "Mălureni", simplu: "Malureni", comuna: "Nicoresti" },
  { nume: "Mândreşti", simplu: "Mandresti", comuna: "Valea Marului" },
  { nume: "Măstăcani", simplu: "Mastacani" },
  { nume: "Matca" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Smardan",
  },
  { nume: "Moscu", comuna: "Targu Bujor" },
  { nume: "Movileni" },
  { nume: "Movileni", comuna: "Sendreni" },
  { nume: "Munteni" },
  { nume: "Nămoloasa Sat", simplu: "Namoloasa Sat", comuna: "Namoloasa" },
  { nume: "Nămoloasa", simplu: "Namoloasa" },
  { nume: "Nărteşti", simplu: "Nartesti", comuna: "Gohor" },
  { nume: "Negrea", comuna: "Schela" },
  { nume: "Negrileşti", simplu: "Negrilesti", comuna: "Munteni" },
  { nume: "Nicopole", comuna: "Draguseni" },
  { nume: "Nicoreşti", simplu: "Nicoresti" },
  { nume: "Oancea" },
  { nume: "Odaia Manolache", comuna: "Vanatori" },
  { nume: "Onciu", comuna: "Beresti-Meria" },
  { nume: "Pechea" },
  { nume: "Piscu Corbului", comuna: "Nicoresti" },
  { nume: "Piscu" },
  { nume: "Pleşa", simplu: "Plesa", comuna: "Beresti-Meria" },
  { nume: "Plevna", comuna: "Rediu" },
  { nume: "Podoleni", comuna: "Barcea" },
  { nume: "Poiana", comuna: "Nicoresti" },
  { nume: "Poşta", simplu: "Posta", comuna: "Gohor" },
  { nume: "Priponeşti", simplu: "Priponesti" },
  {
    nume: "Priponeştii de Jos",
    simplu: "Priponestii de Jos",
    comuna: "Priponesti",
  },
  { nume: "Prodăneşti", simplu: "Prodanesti", comuna: "Beresti-Meria" },
  { nume: "Pupezeni", comuna: "Balasesti" },
  { nume: "Puricani", comuna: "Beresti-Meria" },
  { nume: "Rădeşti", simplu: "Radesti", comuna: "Balabanesti" },
  { nume: "Rediu" },
  { nume: "Rogojeni", comuna: "Suceveni" },
  { nume: "Roşcani", simplu: "Roscani", comuna: "Baneasa" },
  { nume: "Salcia", comuna: "Umbraresti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Nicoresti" },
  { nume: "Săseni", simplu: "Saseni", comuna: "Beresti-Meria" },
  { nume: "Satu Nou", comuna: "Cosmesti" },
  { nume: "Scânteieşti", simplu: "Scanteiesti" },
  { nume: "Schela" },
  { nume: "Şendreni", simplu: "Sendreni" },
  { nume: "Şerbeştii Vechi", simplu: "Serbestii Vechi", comuna: "Sendreni" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Umbraresti" },
  { nume: "Şipote", simplu: "Sipote", comuna: "Beresti-Meria" },
  { nume: "Şiviţa", simplu: "Sivita", comuna: "Tulucesti" },
  { nume: "Slivna", comuna: "Beresti-Meria" },
  { nume: "Slobozia Blăneasa", simplu: "Slobozia Blaneasa", comuna: "Munteni" },
  { nume: "Slobozia Conachi" },
  { nume: "Slobozia Corni", comuna: "Ghidigeni" },
  { nume: "Slobozia Oancea", comuna: "Oancea" },
  { nume: "Smârdan", simplu: "Smardan" },
  { nume: "Smulţi", simplu: "Smulti" },
  { nume: "Ştieţeşti", simplu: "Stietesti", comuna: "Draguseni" },
  { nume: "Stoicani", comuna: "Foltesti" },
  { nume: "Suceveni" },
  { nume: "Suhurlui", comuna: "Rediu" },
  { nume: "Tălpigi", simplu: "Talpigi", comuna: "Ghidigeni" },
  { nume: "Tămăoani", simplu: "Tamaoani", comuna: "Frumusita" },
  { nume: "Tăplău", simplu: "Taplau", comuna: "Ghidigeni" },
  { nume: "Târgu Bujor", simplu: "Targu Bujor" },
  { nume: "Tătarca", simplu: "Tatarca", comuna: "Tulucesti" },
  { nume: "Tecucelu Sec", comuna: "Buciumeni" },
  { nume: "Tecuci" },
  { nume: "Ţepu de Sus", simplu: "Tepu de Sus", comuna: "Tepu" },
  { nume: "Ţepu", simplu: "Tepu" },
  { nume: "Ţigăneşti", simplu: "Tiganesti", comuna: "Munteni" },
  { nume: "Toflea", comuna: "Brahasesti" },
  { nume: "Torceşti", simplu: "Torcesti", comuna: "Umbraresti" },
  { nume: "Traian", comuna: "Branistea" },
  { nume: "Tudor Vladimirescu" },
  { nume: "Tuluceşti", simplu: "Tulucesti" },
  { nume: "Umbrăreşti-Deal", simplu: "Umbraresti-Deal", comuna: "Umbraresti" },
  { nume: "Umbrăreşti", simplu: "Umbraresti" },
  { nume: "Umbrăreşti", simplu: "Umbraresti", comuna: "Targu Bujor" },
  { nume: "Ungureni", comuna: "Munteni" },
  { nume: "Urleşti", simplu: "Urlesti", comuna: "Corni" },
  { nume: "Vădeni", simplu: "Vadeni", comuna: "Cavadinesti" },
  { nume: "Valea Mărului", simplu: "Valea Marului" },
  { nume: "Vameş", simplu: "Vames", comuna: "Piscu" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Vărlezi", simplu: "Varlezi" },
  { nume: "Vasile Alecsandri", comuna: "Branistea" },
  { nume: "Viile", comuna: "Fartanesti" },
  { nume: "Vişina", simplu: "Visina", comuna: "Nicoresti" },
  { nume: "Vizureşti", simplu: "Vizuresti", comuna: "Buciumeni" },
  { nume: "Vlădeşti", simplu: "Vladesti" },
  { nume: "Zărneşti", simplu: "Zarnesti", comuna: "Jorasti" },
  { nume: "Zimbru", comuna: "Balabanesti" },
];
