export const gj = [
  { nume: "Albeni" },
  { nume: "Alexeni", comuna: "Stanesti" },
  { nume: "Alimpeşti", simplu: "Alimpesti" },
  { nume: "Aluniş", simplu: "Alunis", comuna: "Capreni" },
  { nume: "Andreeşti", simplu: "Andreesti", comuna: "Vladimir" },
  { nume: "Aninişu din Deal", simplu: "Aninisu din Deal", comuna: "Crasna" },
  { nume: "Aninişu din Vale", simplu: "Aninisu din Vale", comuna: "Crasna" },
  { nume: "Aninoasa" },
  { nume: "Apa Neagră", simplu: "Apa Neagra", comuna: "Pades" },
  { nume: "Arcani" },
  { nume: "Arjoci", comuna: "Godinesti" },
  { nume: "Arpadia", comuna: "Tantareni" },
  { nume: "Arşeni", simplu: "Arseni", comuna: "Musetesti" },
  { nume: "Arsuri", comuna: "Schela" },
  { nume: "Artanu", comuna: "Negomir" },
  { nume: "Băceşti", simplu: "Bacesti", comuna: "Stejari" },
  { nume: "Bădeşti", simplu: "Badesti", comuna: "Branesti" },
  { nume: "Baia de Fier" },
  { nume: "Bălăceşti", simplu: "Balacesti", comuna: "Bolbosi" },
  { nume: "Bălăneşti", simplu: "Balanesti" },
  { nume: "Bălani", simplu: "Balani", comuna: "Stanesti" },
  { nume: "Bălceşti", simplu: "Balcesti", comuna: "Bengesti-Ciocadia" },
  { nume: "Băleşti", simplu: "Balesti" },
  { nume: "Baloşani", simplu: "Balosani", comuna: "Stejari" },
  { nume: "Bâlta", simplu: "Balta", comuna: "Runcu" },
  { nume: "Bâlteni", simplu: "Balteni" },
  { nume: "Bâltişoara", simplu: "Baltisoara", comuna: "Runcu" },
  { nume: "Baniu", comuna: "Borascu" },
  { nume: "Bărbăteşti", simplu: "Barbatesti" },
  { nume: "Bârcaciu", simplu: "Barcaciu", comuna: "Musetesti" },
  { nume: "Bârseşti", simplu: "Barsesti", comuna: "Targu Jiu" },
  { nume: "Barza", comuna: "Danesti" },
  { nume: "Bârzeiu de Gilort", simplu: "Barzeiu de Gilort", comuna: "Albeni" },
  { nume: "Bârzeiu", simplu: "Barzeiu", comuna: "Berlesti" },
  { nume: "Băzăvani", simplu: "Bazavani", comuna: "Samarinesti" },
  { nume: "Becheni", comuna: "Rosia De Amaradia" },
  { nume: "Bengeşti", simplu: "Bengesti", comuna: "Bengesti-Ciocadia" },
  { nume: "Berceşti", simplu: "Bercesti", comuna: "Novaci" },
  { nume: "Berleşti", simplu: "Berlesti" },
  { nume: "Bibeşti", simplu: "Bibesti", comuna: "Saulesti" },
  { nume: "Bibuleşti", simplu: "Bibulesti", comuna: "Danciulesti" },
  { nume: "Bircii", comuna: "Bengesti-Ciocadia" },
  {
    nume: "Blahniţa de Jos",
    simplu: "Blahnita de Jos",
    comuna: "Tirgu Carbunesti",
  },
  { nume: "Blahniţa de Sus", simplu: "Blahnita de Sus", comuna: "Sacelu" },
  { nume: "Blidari", comuna: "Balanesti" },
  { nume: "Bobaia", comuna: "Aninoasa" },
  { nume: "Boboieşti", simplu: "Boboiesti", comuna: "Ciuperceni" },
  { nume: "Bobu", comuna: "Scoarta" },
  { nume: "Boca", comuna: "Samarinesti" },
  { nume: "Bohorel", comuna: "Negomir" },
  { nume: "Boia", comuna: "Jupanesti" },
  { nume: "Bojinu", comuna: "Cruset" },
  { nume: "Bolboasa", comuna: "Bolbosi" },
  { nume: "Bolboceşti", simplu: "Bolbocesti", comuna: "Albeni" },
  { nume: "Bolboşi", simplu: "Bolbosi" },
  { nume: "Borăscu", simplu: "Borascu" },
  { nume: "Boroşteni", simplu: "Borosteni", comuna: "Pestisani" },
  { nume: "Botorogi", comuna: "Danesti" },
  { nume: "Brădet", simplu: "Bradet", comuna: "Matasari" },
  { nume: "Brădeţel", simplu: "Bradetel", comuna: "Matasari" },
  { nume: "Brădiceni", simplu: "Bradiceni", comuna: "Pestisani" },
  { nume: "Brăneşti", simplu: "Branesti" },
  { nume: "Brăteşti", simplu: "Bratesti", comuna: "Capreni" },
  { nume: "Brătuia", simplu: "Bratuia", comuna: "Danesti" },
  { nume: "Brebenei", comuna: "Branesti" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Plopsoru" },
  { nume: "Broştenii de Sus", simplu: "Brostenii de Sus", comuna: "Plopsoru" },
  { nume: "Bucşana", simplu: "Bucsana", comuna: "Prigoria" },
  { nume: "Bucureasa", comuna: "Danesti" },
  { nume: "Budieni", comuna: "Scoarta" },
  { nume: "Buduhala", comuna: "Telesti" },
  { nume: "Bulbuceni", comuna: "Capreni" },
  { nume: "Bumbeşti-Jiu", simplu: "Bumbesti-Jiu" },
  { nume: "Bumbeşti-Piţic", simplu: "Bumbesti-Pitic" },
  { nume: "Burlani", comuna: "Prigoria" },
  { nume: "Bustuchin" },
  { nume: "Busuioci", comuna: "Hurezani" },
  { nume: "Buzeşti", simplu: "Buzesti", comuna: "Crasna" },
  { nume: "Calapăru", simplu: "Calaparu", comuna: "Borascu" },
  { nume: "Câlceşti", simplu: "Calcesti", comuna: "Godinesti" },
  { nume: "Căleşti", simplu: "Calesti", comuna: "Stanesti" },
  { nume: "Câlnic", simplu: "Calnic" },
  { nume: "Câlnicu de Sus", simplu: "Calnicu de Sus", comuna: "Calnic" },
  { nume: "Călugăreasa", simplu: "Calugareasa", comuna: "Prigoria" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Pades" },
  { nume: "Câmpofeni", simplu: "Campofeni", comuna: "Arcani" },
  { nume: "Câmpu Mare", simplu: "Campu Mare", comuna: "Scoarta" },
  { nume: "Cămuieşti", simplu: "Camuiesti", comuna: "Glogova" },
  { nume: "Cânepeşti", simplu: "Canepesti", comuna: "Balanesti" },
  { nume: "Căpreni", simplu: "Capreni" },
  { nume: "Capu Dealului", comuna: "Branesti" },
  { nume: "Cârbeşti", simplu: "Carbesti", comuna: "Dragutesti" },
  {
    nume: "Cărbuneşti-Sat",
    simplu: "Carbunesti-Sat",
    comuna: "Tirgu Carbunesti",
  },
  { nume: "Cârciu", simplu: "Carciu", comuna: "Vagiulesti" },
  { nume: "Cârligei", simplu: "Carligei", comuna: "Bumbesti-Pitic" },
  { nume: "Cărpiniş", simplu: "Carpinis", comuna: "Crasna" },
  { nume: "Cartiu", comuna: "Turcinesti" },
  { nume: "Cătunele", simplu: "Catunele" },
  { nume: "Ceauru", comuna: "Balesti" },
  { nume: "Celei", comuna: "Tismana" },
  { nume: "Ceplea", comuna: "Plopsoru" },
  {
    nume: "Cerătu de Copăcioasa",
    simplu: "Ceratu de Copacioasa",
    comuna: "Scoarta",
  },
  { nume: "Cerna-Sat", comuna: "Pades" },
  { nume: "Cernădia", simplu: "Cernadia", comuna: "Baia De Fier" },
  { nume: "Cetatea", comuna: "Capreni" },
  { nume: "Chiciora", comuna: "Tantareni" },
  { nume: "Chiliu", comuna: "Godinesti" },
  { nume: "Ciocadia", comuna: "Bengesti-Ciocadia" },
  { nume: "Cionţi", simplu: "Cionti", comuna: "Bustuchin" },
  { nume: "Ciorari", comuna: "Stoina" },
  { nume: "Ciuperceni" },
  {
    nume: "Ciupercenii de Olteţ",
    simplu: "Ciupercenii de Oltet",
    comuna: "Alimpesti",
  },
  { nume: "Cleşneşti", simplu: "Clesnesti", comuna: "Glogova" },
  { nume: "Cloşani", simplu: "Closani", comuna: "Pades" },
  { nume: "Cocoreni", comuna: "Balteni" },
  { nume: "Cocorova", comuna: "Turburea" },
  { nume: "Cojani", comuna: "Tirgu Carbunesti" },
  { nume: "Cojmăneşti", simplu: "Cojmanesti", comuna: "Slivilesti" },
  { nume: "Colibaşi", simplu: "Colibasi", comuna: "Scoarta" },
  { nume: "Colţeşti", simplu: "Coltesti", comuna: "Logresti" },
  { nume: "Condeieşti", simplu: "Condeiesti", comuna: "Negomir" },
  { nume: "Copăcioasa", simplu: "Copacioasa", comuna: "Scoarta" },
  { nume: "Corneşti", simplu: "Cornesti", comuna: "Balesti" },
  { nume: "Cornetu", comuna: "Capreni" },
  { nume: "Corobăi", simplu: "Corobai", comuna: "Dragotesti" },
  { nume: "Corşoru", simplu: "Corsoru", comuna: "Alimpesti" },
  { nume: "Costeni", comuna: "Tismana" },
  { nume: "Costeşti", simplu: "Costesti", comuna: "Aninoasa" },
  { nume: "Covrigi", comuna: "Vagiulesti" },
  { nume: "Crasna din Deal", comuna: "Crasna" },
  { nume: "Crasna" },
  { nume: "Creţeşti", simplu: "Cretesti", comuna: "Tirgu Carbunesti" },
  { nume: "Croici", comuna: "Matasari" },
  { nume: "Cruşet", simplu: "Cruset" },
  { nume: "Curpen", comuna: "Stanesti" },
  { nume: "Cursaru", comuna: "Plopsoru" },
  { nume: "Curteana", comuna: "Tirgu Carbunesti" },
  { nume: "Curtişoara", simplu: "Curtisoara", comuna: "Bumbesti-Jiu" },
  { nume: "Dâmbova", simplu: "Dambova", comuna: "Dragutesti" },
  { nume: "Dănciuleşti", simplu: "Danciulesti" },
  { nume: "Dăneşti", simplu: "Danesti" },
  { nume: "Dealu Leului", comuna: "Stejari" },
  { nume: "Dealu Pomilor", comuna: "Motru" },
  { nume: "Dealu Spirei", comuna: "Capreni" },
  { nume: "Dealu Viei", comuna: "Rosia De Amaradia" },
  { nume: "Dealu Viilor", comuna: "Catunele" },
  { nume: "Deleni", comuna: "Plopsoru" },
  { nume: "Didileşti", simplu: "Didilesti", comuna: "Calnic" },
  { nume: "Dobrana", comuna: "Prigoria" },
  { nume: "Dobriţa", simplu: "Dobrita", comuna: "Runcu" },
  { nume: "Dolceşti", simplu: "Dolcesti", comuna: "Saulesti" },
  { nume: "Doseni", comuna: "Albeni" },
  { nume: "Drăgoeni", simplu: "Dragoeni", comuna: "Targu Jiu" },
  { nume: "Drăgoieşti", simplu: "Dragoiesti", comuna: "Crasna" },
  { nume: "Drăgoteşti", simplu: "Dragotesti" },
  { nume: "Drăguţeşti", simplu: "Dragutesti" },
  { nume: "Duculeşti", simplu: "Duculesti", comuna: "Samarinesti" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Crasna" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Urdari" },
  {
    nume: "Fărcăşeşti Moşneni",
    simplu: "Farcasesti Mosneni",
    comuna: "Farcasesti",
  },
  { nume: "Fărcăşeşti", simplu: "Farcasesti" },
  { nume: "Floreşteni", simplu: "Floresteni", comuna: "Tirgu Carbunesti" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Tantareni" },
  { nume: "Frânceşti", simplu: "Francesti", comuna: "Pestisani" },
  { nume: "Frasin", comuna: "Vladimir" },
  { nume: "Frăteşti", simplu: "Fratesti", comuna: "Lelesti" },
  { nume: "Frumuşei", simplu: "Frumusei", comuna: "Licurici" },
  { nume: "Frunza", comuna: "Logresti" },
  { nume: "Gâlceşti", simplu: "Galcesti", comuna: "Berlesti" },
  { nume: "Găleşoaia", simplu: "Galesoaia", comuna: "Calnic" },
  { nume: "Gămani", simplu: "Gamani", comuna: "Musetesti" },
  { nume: "Gârbovu", simplu: "Garbovu", comuna: "Turceni" },
  { nume: "Găvăneşti", simplu: "Gavanesti", comuna: "Balesti" },
  { nume: "Gilortu", comuna: "Branesti" },
  { nume: "Glodeni", comuna: "Balanesti" },
  { nume: "Glogova" },
  { nume: "Godineşti", simplu: "Godinesti" },
  { nume: "Gornăcel", simplu: "Gornacel", comuna: "Schela" },
  { nume: "Gornoviţa", simplu: "Gornovita", comuna: "Tismana" },
  { nume: "Groşerea", simplu: "Groserea", comuna: "Aninoasa" },
  { nume: "Grui", comuna: "Musetesti" },
  { nume: "Gura Menţi", simplu: "Gura Menti", comuna: "Borascu" },
  { nume: "Gura Şuşiţei", simplu: "Gura Susitei", comuna: "Ionesti" },
  { nume: "Gureni", comuna: "Pestisani" },
  { nume: "Hăieşti", simplu: "Haiesti", comuna: "Sacelu" },
  { nume: "Hălăngeşti", simplu: "Halangesti", comuna: "Danciulesti" },
  { nume: "Hirişeşti", simplu: "Hirisesti", comuna: "Novaci" },
  { nume: "Hobiţa", simplu: "Hobita", comuna: "Pestisani" },
  { nume: "Hodoreasca", comuna: "Calnic" },
  { nume: "Horăşti", simplu: "Horasti", comuna: "Motru" },
  { nume: "Horezu", comuna: "Turcinesti" },
  { nume: "Hotăroasa", simplu: "Hotaroasa", comuna: "Urdari" },
  { nume: "Hurezani" },
  { nume: "Iaşi-Gorj", simplu: "Iasi-Gorj", comuna: "Dragutesti" },
  { nume: "Iezureni", comuna: "Targu Jiu" },
  { nume: "Igirosu", comuna: "Bolbosi" },
  { nume: "Ilieşti", simplu: "Iliesti", comuna: "Ionesti" },
  { nume: "Însurăţei", simplu: "Insuratei", comuna: "Motru" },
  { nume: "Ioneşti", simplu: "Ionesti" },
  { nume: "Iormăneşti", simplu: "Iormanesti", comuna: "Glogova" },
  { nume: "Isvarna", comuna: "Tismana" },
  { nume: "Izvoarele", comuna: "Plopsoru" },
  { nume: "Jeriştea", simplu: "Jeristea", comuna: "Sacelu" },
  { nume: "Jilţu", simplu: "Jiltu", comuna: "Turceni" },
  { nume: "Jupâneşti", simplu: "Jupanesti" },
  { nume: "Larga", comuna: "Samarinesti" },
  { nume: "Lăzăreşti", simplu: "Lazaresti", comuna: "Bumbesti-Jiu" },
  { nume: "Lazuri", comuna: "Scoarta" },
  { nume: "Leleşti", simplu: "Lelesti" },
  { nume: "Leurda", comuna: "Motru" },
  { nume: "Licurici" },
  { nume: "Lihuleşti", simplu: "Lihulesti", comuna: "Berlesti" },
  { nume: "Lintea", comuna: "Scoarta" },
  { nume: "Logreşti Moşteni", simplu: "Logresti Mosteni", comuna: "Logresti" },
  { nume: "Lupoaia", comuna: "Catunele" },
  { nume: "Lupoiţa", simplu: "Lupoita", comuna: "Motru" },
  { nume: "Măceşu", simplu: "Macesu", comuna: "Tirgu Carbunesti" },
  { nume: "Maghereşti", simplu: "Magheresti", comuna: "Sacelu" },
  { nume: "Măiag", simplu: "Maiag", comuna: "Cruset" },
  { nume: "Marineşti", simplu: "Marinesti", comuna: "Cruset" },
  { nume: "Măru", simplu: "Maru", comuna: "Logresti" },
  { nume: "Mătăsari", simplu: "Matasari" },
  { nume: "Măzăroi", simplu: "Mazaroi", comuna: "Stanesti" },
  { nume: "Menţii din Dos", simplu: "Mentii din Dos", comuna: "Borascu" },
  { nume: "Merfuleşti", simplu: "Merfulesti", comuna: "Danesti" },
  { nume: "Miclosu", comuna: "Bolbosi" },
  { nume: "Miculeşti", simplu: "Miculesti", comuna: "Slivilesti" },
  { nume: "Mieluşei", simplu: "Mielusei", comuna: "Stoina" },
  { nume: "Mierea", comuna: "Cruset" },
  { nume: "Miericeaua", comuna: "Cruset" },
  { nume: "Miluta", comuna: "Borascu" },
  { nume: "Mirosloveni", comuna: "Albeni" },
  { nume: "Mogoşani", simplu: "Mogosani", comuna: "Scoarta" },
  { nume: "Moi", comuna: "Balteni" },
  { nume: "Motorgi", comuna: "Bustuchin" },
  { nume: "Motru Sec", comuna: "Pades" },
  { nume: "Motru" },
  { nume: "Murgeşti", simplu: "Murgesti", comuna: "Turceni" },
  { nume: "Murgileşti", simplu: "Murgilesti", comuna: "Vagiulesti" },
  { nume: "Musculeşti", simplu: "Musculesti", comuna: "Barbatesti" },
  { nume: "Muşeteşti", simplu: "Musetesti" },
  { nume: "Nămete", simplu: "Namete", comuna: "Bustuchin" },
  { nume: "Negoieşti", simplu: "Negoiesti", comuna: "Prigoria" },
  { nume: "Negomir" },
  { nume: "Negreni", comuna: "Licurici" },
  { nume: "Nistoreşti", simplu: "Nistoresti", comuna: "Alimpesti" },
  { nume: "Novaci" },
  { nume: "Nucetu", comuna: "Negomir" },
  { nume: "Obârşia", simplu: "Obarsia", comuna: "Danciulesti" },
  { nume: "Obreja", comuna: "Stanesti" },
  { nume: "Ohaba Jiu", comuna: "Bolbosi" },
  { nume: "Ohaba", comuna: "Balanesti" },
  { nume: "Olari", comuna: "Plopsoru" },
  { nume: "Olteanu", comuna: "Glogova" },
  { nume: "Orzeşti", simplu: "Orzesti", comuna: "Pades" },
  { nume: "Orzu", comuna: "Negomir" },
  { nume: "Padeş", simplu: "Pades" },
  { nume: "Păişani", simplu: "Paisani", comuna: "Stoina" },
  { nume: "Păjiştele", simplu: "Pajistele", comuna: "Schela" },
  { nume: "Paltinu", comuna: "Negomir" },
  { nume: "Pârâu Boia", simplu: "Parau Boia", comuna: "Jupanesti" },
  { nume: "Pârâu de Pripor", simplu: "Parau de Pripor", comuna: "Godinesti" },
  { nume: "Pârâu de Vale", simplu: "Parau de Vale", comuna: "Godinesti" },
  { nume: "Pârâu Viu", simplu: "Parau Viu", comuna: "Berlesti" },
  { nume: "Pârâu", simplu: "Parau", comuna: "Branesti" },
  { nume: "Pârvuleşti", simplu: "Parvulesti", comuna: "Stanesti" },
  { nume: "Pegeni", comuna: "Hurezani" },
  { nume: "Peşteana de Jos", simplu: "Pesteana de Jos", comuna: "Farcasesti" },
  { nume: "Peşteana Jiu", simplu: "Pesteana Jiu", comuna: "Balteni" },
  { nume: "Peşteana Vulcan", simplu: "Pesteana Vulcan", comuna: "Ciuperceni" },
  { nume: "Peştişani", simplu: "Pestisani" },
  { nume: "Petrăchei", simplu: "Petrachei", comuna: "Danciulesti" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Barbatesti" },
  { nume: "Picu", comuna: "Ionesti" },
  { nume: "Pieptani", comuna: "Calnic" },
  { nume: "Pinoasa", comuna: "Calnic" },
  { nume: "Piscoiu", comuna: "Stejari" },
  { nume: "Piscuri", comuna: "Plopsoru" },
  {
    nume: "Pişteştii din Deal",
    simplu: "Pistestii din Deal",
    comuna: "Scoarta",
  },
  { nume: "Pleşa", simplu: "Plesa", comuna: "Bumbesti-Jiu" },
  { nume: "Plopşoru", simplu: "Plopsoru" },
  { nume: "Plopu", comuna: "Hurezani" },
  { nume: "Ploştina", simplu: "Plostina", comuna: "Motru" },
  { nume: "Pociovaliştea", simplu: "Pociovalistea", comuna: "Novaci" },
  { nume: "Pocruia", comuna: "Tismana" },
  { nume: "Poiana Seciuri", comuna: "Bustuchin" },
  { nume: "Poiana", comuna: "Turburea" },
  { nume: "Poienari", comuna: "Bumbesti-Pitic" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Bustuchin" },
  { nume: "Pojaru", comuna: "Bustuchin" },
  { nume: "Pojogeni", comuna: "Tirgu Carbunesti" },
  { nume: "Polata", comuna: "Targu Jiu" },
  { nume: "Polovragi" },
  { nume: "Popeşti Stejari", simplu: "Popesti Stejari", comuna: "Stejari" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Logresti" },
  { nume: "Preajba Mare", comuna: "Targu Jiu" },
  { nume: "Prigoria" },
  { nume: "Priporu", comuna: "Ciuperceni" },
  { nume: "Pruneşti", simplu: "Prunesti", comuna: "Albeni" },
  { nume: "Purcaru", comuna: "Saulesti" },
  { nume: "Răchiţi", simplu: "Rachiti", comuna: "Runcu" },
  { nume: "Raci", comuna: "Negomir" },
  { nume: "Racoţi", simplu: "Racoti", comuna: "Tismana" },
  { nume: "Racoviţa", simplu: "Racovita", comuna: "Polovragi" },
  { nume: "Rădineşti", simplu: "Radinesti", comuna: "Danciulesti" },
  { nume: "Radoşi", simplu: "Radosi", comuna: "Crasna" },
  { nume: "Râpa", simplu: "Rapa", comuna: "Motru" },
  { nume: "Rasova", comuna: "Balesti" },
  { nume: "Rasoviţa", simplu: "Rasovita", comuna: "Lelesti" },
  { nume: "Rătez", simplu: "Ratez", comuna: "Godinesti" },
  { nume: "Rogojel", comuna: "Farcasesti" },
  { nume: "Rogojeni", comuna: "Tirgu Carbunesti" },
  { nume: "Romaneşti", simplu: "Romanesti", comuna: "Targu Jiu" },
  { nume: "Roşia de Amaradia", simplu: "Rosia de Amaradia" },
  { nume: "Roşia Jiu", simplu: "Rosia Jiu", comuna: "Farcasesti" },
  { nume: "Roşiuţa", simplu: "Rosiuta", comuna: "Motru" },
  { nume: "Rovinari" },
  { nume: "Ruget", comuna: "Rosia De Amaradia" },
  { nume: "Rugi", comuna: "Turcinesti" },
  { nume: "Runcu" },
  { nume: "Runcurel", comuna: "Matasari" },
  { nume: "Săcelu", simplu: "Sacelu" },
  { nume: "Samarineşti", simplu: "Samarinesti" },
  { nume: "Sâmbotin", simplu: "Sambotin", comuna: "Schela" },
  { nume: "Sănăteşti", simplu: "Sanatesti", comuna: "Arcani" },
  { nume: "Sârbeşti", simplu: "Sarbesti", comuna: "Alimpesti" },
  { nume: "Sărdăneşti", simplu: "Sardanesti", comuna: "Plopsoru" },
  { nume: "Şasa", simplu: "Sasa", comuna: "Danesti" },
  { nume: "Satu Nou", comuna: "Capreni" },
  { nume: "Săuleşti", simplu: "Saulesti" },
  { nume: "Schela" },
  { nume: "Scoarţa", simplu: "Scoarta" },
  { nume: "Scoruşu", simplu: "Scorusu", comuna: "Borascu" },
  { nume: "Scrada", comuna: "Berlesti" },
  { nume: "Scurtu", comuna: "Berlesti" },
  { nume: "Seaca", comuna: "Logresti" },
  { nume: "Seciurile", comuna: "Rosia De Amaradia" },
  { nume: "Seuca", comuna: "Pestisani" },
  { nume: "Şiacu", simplu: "Siacu", comuna: "Slivilesti" },
  { nume: "Şipotu", simplu: "Sipotu", comuna: "Turburea" },
  { nume: "Siteşti", simplu: "Sitesti", comuna: "Novaci" },
  { nume: "Şitoaia", simplu: "Sitoaia", comuna: "Rosia De Amaradia" },
  { nume: "Slămneşti", simplu: "Slamnesti", comuna: "Cruset" },
  { nume: "Slăvuţa", simplu: "Slavuta", comuna: "Cruset" },
  { nume: "Slivileşti", simplu: "Slivilesti" },
  { nume: "Slobozia", comuna: "Targu Jiu" },
  { nume: "Socu", comuna: "Barbatesti" },
  { nume: "Sohodol", comuna: "Tismana" },
  { nume: "Şomăneşti", simplu: "Somanesti", comuna: "Telesti" },
  { nume: "Spahii", comuna: "Turburea" },
  { nume: "Stănceşti Larga", simplu: "Stancesti Larga", comuna: "Musetesti" },
  { nume: "Stănceşti", simplu: "Stancesti", comuna: "Musetesti" },
  { nume: "Stăneşti", simplu: "Stanesti" },
  { nume: "Ştefăneşti", simplu: "Stefanesti", comuna: "Tirgu Carbunesti" },
  { nume: "Steic", comuna: "Catunele" },
  { nume: "Stejari" },
  { nume: "Stejaru", comuna: "Rosia De Amaradia" },
  { nume: "Stejerei", comuna: "Calnic" },
  { nume: "Sterpoaia", comuna: "Aninoasa" },
  { nume: "Ştiucani", simplu: "Stiucani", comuna: "Slivilesti" },
  { nume: "Stoina" },
  { nume: "Stolojani", comuna: "Balesti" },
  { nume: "Strâmba Jiu", simplu: "Stramba Jiu", comuna: "Turceni" },
  { nume: "Strâmba Vulcan", simplu: "Stramba Vulcan", comuna: "Ciuperceni" },
  { nume: "Strâmtu", simplu: "Stramtu", comuna: "Slivilesti" },
  { nume: "Stroieşti", simplu: "Stroiesti", comuna: "Arcani" },
  { nume: "Sura", comuna: "Slivilesti" },
  { nume: "Suseni", comuna: "Runcu" },
  { nume: "Tălpăşeşti", simplu: "Talpasesti", comuna: "Balesti" },
  { nume: "Tâlveşti", simplu: "Talvesti", comuna: "Dragutesti" },
  { nume: "Tămăşeşti", simplu: "Tamasesti", comuna: "Balesti" },
  { nume: "Ţânţăreni", simplu: "Tantareni" },
  { nume: "Ţârculeşti", simplu: "Tarculesti", comuna: "Danesti" },
  {
    nume: "Târgu Cărbuneşti",
    simplu: "Targu Carbunesti",
    comuna: "Tirgu Carbunesti",
  },
  { nume: "Târgu Jiu", simplu: "Targu Jiu" },
  { nume: "Târgu Logreşti", simplu: "Targu Logresti", comuna: "Logresti" },
  { nume: "Tehomir", comuna: "Slivilesti" },
  { nume: "Teleşti", simplu: "Telesti" },
  { nume: "Tetila", comuna: "Bumbesti-Jiu" },
  { nume: "Ţicleni", simplu: "Ticleni" },
  { nume: "Timişeni", simplu: "Timiseni", comuna: "Farcasesti" },
  { nume: "Ţirioi", simplu: "Tirioi", comuna: "Samarinesti" },
  { nume: "Tismana" },
  { nume: "Toiaga", comuna: "Stoina" },
  { nume: "Topeşti", simplu: "Topesti", comuna: "Tismana" },
  { nume: "Totea de Hurezani", comuna: "Hurezani" },
  { nume: "Totea", comuna: "Licurici" },
  { nume: "Trestioara", comuna: "Dragotesti" },
  { nume: "Trocani", comuna: "Danesti" },
  { nume: "Turburea" },
  { nume: "Turceni" },
  { nume: "Turcineşti", simplu: "Turcinesti" },
  { nume: "Ulmet", comuna: "Stoina" },
  { nume: "Ungureni", comuna: "Danesti" },
  { nume: "Urda de Jos", comuna: "Cruset" },
  { nume: "Urda de Sus", comuna: "Stoina" },
  { nume: "Urdari" },
  { nume: "Urecheşti", simplu: "Urechesti", comuna: "Dragutesti" },
  { nume: "Ursaţi", simplu: "Ursati", comuna: "Targu Jiu" },
  { nume: "Ursoaia", comuna: "Negomir" },
  { nume: "Văcarea", simplu: "Vacarea", comuna: "Danesti" },
  { nume: "Văgiuleşti", simplu: "Vagiulesti" },
  { nume: "Vaidei", comuna: "Stanesti" },
  { nume: "Văieni", simplu: "Vaieni", comuna: "Pades" },
  { nume: "Vălari", simplu: "Valari", comuna: "Stanesti" },
  { nume: "Vâlceaua", simplu: "Valceaua", comuna: "Calnic" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Tismana" },
  { nume: "Valea Bisericii", comuna: "Samarinesti" },
  { nume: "Valea cu Apă", simplu: "Valea cu Apa", comuna: "Farcasesti" },
  { nume: "Valea Deşului", simplu: "Valea Desului", comuna: "Vladimir" },
  { nume: "Valea Mânăstirii", simplu: "Valea Manastirii", comuna: "Catunele" },
  { nume: "Valea Mare", comuna: "Runcu" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Samarinesti" },
  { nume: "Valea Motrului", comuna: "Vagiulesti" },
  { nume: "Valea Perilor", comuna: "Catunele" },
  { nume: "Valea Poienii", comuna: "Samarinesti" },
  { nume: "Valea Pojarului", comuna: "Bustuchin" },
  { nume: "Valea Racilor", comuna: "Negomir" },
  { nume: "Valea Viei", comuna: "Turceni" },
  { nume: "Valea", comuna: "Bolbosi" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Plopsoru" },
  { nume: "Văluţa", simplu: "Valuta", comuna: "Cruset" },
  { nume: "Vânata", simplu: "Vanata", comuna: "Tismana" },
  { nume: "Vârt", simplu: "Vart", comuna: "Rovinari" },
  { nume: "Vârtopu", simplu: "Vartopu", comuna: "Ciuperceni" },
  { nume: "Vidin", comuna: "Jupanesti" },
  { nume: "Vierşani", simplu: "Viersani", comuna: "Jupanesti" },
  { nume: "Vladimir" },
  { nume: "Vlăduleni", simplu: "Vladuleni", comuna: "Balteni" },
  { nume: "Voinigeşti", simplu: "Voinigesti", comuna: "Balesti" },
  {
    nume: "Voiteştii de Vale",
    simplu: "Voitestii de Vale",
    comuna: "Balanesti",
  },
  {
    nume: "Voiteştii din Deal",
    simplu: "Voitestii din Deal",
    comuna: "Balanesti",
  },
  { nume: "Zăicoiu", simplu: "Zaicoiu", comuna: "Danciulesti" },
  { nume: "Zorleşti", simplu: "Zorlesti", comuna: "Prigoria" },
  { nume: "Zorzila", comuna: "Ciuperceni" },
];
