export const gl = [
  { nume: "Barcea" },
  { nume: "Beresti" },
  { nume: "Beresti-Meria" },
  { nume: "Branistea" },
  { nume: "Brahasesti" },
  { nume: "Buciumeni" },
  { nume: "Baleni" },
  { nume: "Balabanesti" },
  { nume: "Balasesti" },
  { nume: "Baneasa" },
  { nume: "Cavadinesti" },
  { nume: "Certesti" },
  { nume: "Corni" },
  { nume: "Corod" },
  { nume: "Cosmesti" },
  { nume: "Costache Negri" },
  { nume: "Cuca" },
  { nume: "Cudalbi" },
  { nume: "Draguseni" },
  { nume: "Draganesti" },
  { nume: "Foltesti" },
  { nume: "Frumusita" },
  { nume: "Fundeni" },
  { nume: "Fartanesti" },
  { nume: "Galati" },
  { nume: "Ghidigeni" },
  { nume: "Gohor" },
  { nume: "Grivita" },
  { nume: "Independenta" },
  { nume: "Ivesti" },
  { nume: "Jorasti" },
  { nume: "Liesti" },
  { nume: "Matca" },
  { nume: "Movileni" },
  { nume: "Munteni" },
  { nume: "Mastacani" },
  { nume: "Nicoresti" },
  { nume: "Namoloasa" },
  { nume: "Oancea" },
  { nume: "Pechea" },
  { nume: "Piscu" },
  { nume: "Priponesti" },
  { nume: "Rediu" },
  { nume: "Schela" },
  { nume: "Scanteiesti" },
  { nume: "Slobozia Conachi" },
  { nume: "Smulti" },
  { nume: "Smardan" },
  { nume: "Suceveni" },
  { nume: "Tecuci" },
  { nume: "Tudor Vladimirescu" },
  { nume: "Tulucesti" },
  { nume: "Targu Bujor" },
  { nume: "Umbraresti" },
  { nume: "Valea Marului" },
  { nume: "Vladesti" },
  { nume: "Vanatori" },
  { nume: "Varlezi" },
  { nume: "Sendreni" },
  { nume: "Tepu" },
  { nume: "Bursucani", comuna: "Balabanesti" },
  { nume: "Cruceanu", comuna: "Balabanesti" },
  { nume: "Lungesti", comuna: "Balabanesti" },
  { nume: "Radesti", comuna: "Balabanesti" },
  { nume: "Zimbru", comuna: "Balabanesti" },
  { nume: "Ciuresti", comuna: "Balasesti" },
  { nume: "Ciurestii Noi", comuna: "Balasesti" },
  { nume: "Pupezeni", comuna: "Balasesti" },
  { nume: "Roscani", comuna: "Baneasa" },
  { nume: "Podoleni", comuna: "Barcea" },
  { nume: "Aldesti", comuna: "Beresti-Meria" },
  { nume: "Balintesti", comuna: "Beresti-Meria" },
  { nume: "Onciu", comuna: "Beresti-Meria" },
  { nume: "Plesa", comuna: "Beresti-Meria" },
  { nume: "Prodanesti", comuna: "Beresti-Meria" },
  { nume: "Puricani", comuna: "Beresti-Meria" },
  { nume: "Slivna", comuna: "Beresti-Meria" },
  { nume: "Saseni", comuna: "Beresti-Meria" },
  { nume: "Sipote", comuna: "Beresti-Meria" },
  { nume: "Corcioveni", comuna: "Brahasesti" },
  { nume: "Cositeni", comuna: "Brahasesti" },
  { nume: "Toflea", comuna: "Brahasesti" },
  { nume: "Lozova", comuna: "Branistea" },
  { nume: "Traian", comuna: "Branistea" },
  { nume: "Vasile Alecsandri", comuna: "Branistea" },
  { nume: "Hantesti", comuna: "Buciumeni" },
  { nume: "Tecucelu Sec", comuna: "Buciumeni" },
  { nume: "Vizuresti", comuna: "Buciumeni" },
  { nume: "Comanesti", comuna: "Cavadinesti" },
  { nume: "Ganesti", comuna: "Cavadinesti" },
  { nume: "Vadeni", comuna: "Cavadinesti" },
  { nume: "Cotoroaia", comuna: "Certesti" },
  { nume: "Carlomanesti", comuna: "Certesti" },
  { nume: "Maciseni", comuna: "Corni" },
  { nume: "Urlesti", comuna: "Corni" },
  { nume: "Blanzi", comuna: "Corod" },
  { nume: "Bratulesti", comuna: "Corod" },
  { nume: "Carapcesti", comuna: "Corod" },
  { nume: "Baltareti", comuna: "Cosmesti" },
  { nume: "Cosmestii-Vale", comuna: "Cosmesti" },
  { nume: "Furcenii Noi", comuna: "Cosmesti" },
  { nume: "Furcenii Vechi", comuna: "Cosmesti" },
  { nume: "Satu Nou", comuna: "Cosmesti" },
  { nume: "Malu Alb", comuna: "Draganesti" },
  { nume: "Adam", comuna: "Draguseni" },
  { nume: "Cauiesti", comuna: "Draguseni" },
  { nume: "Fundeanu", comuna: "Draguseni" },
  { nume: "Ghinghesti", comuna: "Draguseni" },
  { nume: "Nicopole", comuna: "Draguseni" },
  { nume: "Stietesti", comuna: "Draguseni" },
  { nume: "Viile", comuna: "Fartanesti" },
  { nume: "Stoicani", comuna: "Foltesti" },
  { nume: "Ijdileni", comuna: "Frumusita" },
  { nume: "Tamaoani", comuna: "Frumusita" },
  { nume: "Fundenii Noi", comuna: "Fundeni" },
  { nume: "Hanu Conachi", comuna: "Fundeni" },
  { nume: "Lungoci", comuna: "Fundeni" },
  { nume: "Gara Ghidigeni", comuna: "Ghidigeni" },
  { nume: "Gefu", comuna: "Ghidigeni" },
  { nume: "Gura Garbovatului", comuna: "Ghidigeni" },
  { nume: "Garbovat", comuna: "Ghidigeni" },
  { nume: "Slobozia Corni", comuna: "Ghidigeni" },
  { nume: "Talpigi", comuna: "Ghidigeni" },
  { nume: "Taplau", comuna: "Ghidigeni" },
  { nume: "Gara Berheci", comuna: "Gohor" },
  { nume: "Ireasca", comuna: "Gohor" },
  { nume: "Nartesti", comuna: "Gohor" },
  { nume: "Posta", comuna: "Gohor" },
  { nume: "Calmatui", comuna: "Grivita" },
  { nume: "Bucesti", comuna: "Ivesti" },
  { nume: "Lunca", comuna: "Jorasti" },
  { nume: "Zarnesti", comuna: "Jorasti" },
  { nume: "Chiraftei", comuna: "Mastacani" },
  { nume: "Frunzeasca", comuna: "Munteni" },
  { nume: "Negrilesti", comuna: "Munteni" },
  { nume: "Slobozia Blaneasa", comuna: "Munteni" },
  { nume: "Ungureni", comuna: "Munteni" },
  { nume: "Tiganesti", comuna: "Munteni" },
  { nume: "Crangeni", comuna: "Namoloasa" },
  { nume: "Namoloasa Sat", comuna: "Namoloasa" },
  { nume: "Branistea", comuna: "Nicoresti" },
  { nume: "Coasta Lupei", comuna: "Nicoresti" },
  { nume: "Dobrinesti", comuna: "Nicoresti" },
  { nume: "Fantani", comuna: "Nicoresti" },
  { nume: "Grozavesti", comuna: "Nicoresti" },
  { nume: "Ionasesti", comuna: "Nicoresti" },
  { nume: "Malureni", comuna: "Nicoresti" },
  { nume: "Piscu Corbului", comuna: "Nicoresti" },
  { nume: "Poiana", comuna: "Nicoresti" },
  { nume: "Sarbi", comuna: "Nicoresti" },
  { nume: "Visina", comuna: "Nicoresti" },
  { nume: "Slobozia Oancea", comuna: "Oancea" },
  { nume: "Lupele", comuna: "Pechea" },
  { nume: "Vames", comuna: "Piscu" },
  { nume: "Ciorasti", comuna: "Priponesti" },
  { nume: "Hustiu", comuna: "Priponesti" },
  { nume: "Liesti", comuna: "Priponesti" },
  { nume: "Priponestii de Jos", comuna: "Priponesti" },
  { nume: "Plevna", comuna: "Rediu" },
  { nume: "Suhurlui", comuna: "Rediu" },
  { nume: "Fantanele", comuna: "Scanteiesti" },
  { nume: "Negrea", comuna: "Schela" },
  { nume: "Movileni", comuna: "Sendreni" },
  { nume: "Serbestii Vechi", comuna: "Sendreni" },
  { nume: "Cuza Voda", comuna: "Slobozia Conachi" },
  { nume: "Izvoarele", comuna: "Slobozia Conachi" },
  { nume: "Cismele", comuna: "Smardan" },
  { nume: "Mihail Kogalniceanu", comuna: "Smardan" },
  { nume: "Rogojeni", comuna: "Suceveni" },
  { nume: "Moscu", comuna: "Targu Bujor" },
  { nume: "Umbraresti", comuna: "Targu Bujor" },
  { nume: "Tepu de Sus", comuna: "Tepu" },
  { nume: "Tatarca", comuna: "Tulucesti" },
  { nume: "Sivita", comuna: "Tulucesti" },
  { nume: "Condrea", comuna: "Umbraresti" },
  { nume: "Salcia", comuna: "Umbraresti" },
  { nume: "Silistea", comuna: "Umbraresti" },
  { nume: "Torcesti", comuna: "Umbraresti" },
  { nume: "Umbraresti-Deal", comuna: "Umbraresti" },
  { nume: "Mandresti", comuna: "Valea Marului" },
  { nume: "Costi", comuna: "Vanatori" },
  { nume: "Odaia Manolache", comuna: "Vanatori" },
  { nume: "Craiesti", comuna: "Varlezi" },
  { nume: "Branesti", comuna: "Vladesti" },
];
