export const gr = [
  { nume: "Adunații-Copăceni", simplu: "Adunatii-Copaceni" },
  { nume: "Anghelești", simplu: "Anghelesti", comuna: "Bucsani" },
  { nume: "Bâcu", simplu: "Bacu", comuna: "Joita" },
  { nume: "Bălanu", simplu: "Balanu", comuna: "Stanesti" },
  { nume: "Băneasa", simplu: "Baneasa" },
  { nume: "Bănești", simplu: "Banesti", comuna: "Iepuresti" },
  { nume: "Bila", comuna: "Schitu" },
  { nume: "Bolintin-Deal" },
  { nume: "Bolintin-Vale" },
  { nume: "Brăniștari", simplu: "Branistari", comuna: "Calugareni" },
  { nume: "Braniștea", simplu: "Branistea", comuna: "Oinacu" },
  { nume: "Bucșani", simplu: "Bucsani" },
  { nume: "Budeni", comuna: "Comana" },
  { nume: "Bulbucata" },
  { nume: "Buturugeni" },
  { nume: "Călugăreni", simplu: "Calugareni" },
  { nume: "Cămineasca", simplu: "Camineasca", comuna: "Schitu" },
  { nume: "Câmpurelu", simplu: "Campurelu", comuna: "Colibasi" },
  { nume: "Carapancea", comuna: "Rasuceni" },
  { nume: "Cărpenișu", simplu: "Carpenisu", comuna: "Gaiseni" },
  { nume: "Cartojani", comuna: "Roata De Jos" },
  { nume: "Căscioarele", simplu: "Cascioarele", comuna: "Gaiseni" },
  { nume: "Căscioarele", simplu: "Cascioarele", comuna: "Ulmi" },
  { nume: "Cetatea", comuna: "Fratesti" },
  { nume: "Cetățuia", simplu: "Cetatuia", comuna: "Gaujani" },
  { nume: "Chirculești", simplu: "Chirculesti", comuna: "Iepuresti" },
  { nume: "Chiriacu", comuna: "Izvoarele" },
  { nume: "Clejani" },
  { nume: "Colibași", simplu: "Colibasi" },
  { nume: "Comana" },
  { nume: "Comasca", comuna: "Oinacu" },
  { nume: "Copaciu", comuna: "Ghimpati" },
  { nume: "Corbeanca", comuna: "Vanatorii Mici" },
  { nume: "Cosoba", comuna: "Joita" },
  { nume: "Coteni", comuna: "Bulbucata" },
  { nume: "Crânguri", simplu: "Cranguri", comuna: "Singureni" },
  { nume: "Crevedia Mare" },
  { nume: "Crevedia Mică", simplu: "Crevedia Mica", comuna: "Crevedia Mare" },
  { nume: "Crivina", comuna: "Bolintin-Vale" },
  {
    nume: "Crucea de Piatră",
    simplu: "Crucea de Piatra",
    comuna: "Calugareni",
  },
  { nume: "Cucuruzu", comuna: "Rasuceni" },
  { nume: "Cupele", comuna: "Vanatorii Mici" },
  { nume: "Daia" },
  {
    nume: "Dărăști-Vlașca",
    simplu: "Darasti-Vlasca",
    comuna: "Adunatii-Copaceni",
  },
  { nume: "Dealu", comuna: "Crevedia Mare" },
  { nume: "Dimitrie Cantemir", comuna: "Izvoarele" },
  { nume: "Dobreni", comuna: "Varasti" },
  { nume: "Drăgăneasca", simplu: "Draganeasca", comuna: "Ulmi" },
  { nume: "Drăgănescu", simplu: "Draganescu", comuna: "Mihailesti" },
  { nume: "Drăghiceanu", simplu: "Draghiceanu", comuna: "Gogosari" },
  { nume: "Făcău", simplu: "Facau", comuna: "Bulbucata" },
  { nume: "Falaștoaca", simplu: "Falastoaca", comuna: "Comana" },
  { nume: "Florești", simplu: "Floresti", comuna: "Floresti-Stoenesti" },
  { nume: "Frasinu", comuna: "Baneasa" },
  { nume: "Frătești", simplu: "Fratesti" },
  { nume: "Găiseanca", simplu: "Gaiseanca", comuna: "Crevedia Mare" },
  { nume: "Găiseni", simplu: "Gaiseni" },
  { nume: "Găujani", simplu: "Gaujani" },
  { nume: "Ghimpați", simplu: "Ghimpati" },
  { nume: "Ghionea", comuna: "Ulmi" },
  { nume: "Ghizdaru", comuna: "Stanesti" },
  { nume: "Giurgiu" },
  { nume: "Gogoșari", simplu: "Gogosari" },
  { nume: "Goleasca", comuna: "Bucsani" },
  { nume: "Gorneni", comuna: "Iepuresti" },
  { nume: "Gostinari" },
  { nume: "Gostinu" },
  { nume: "Grădinari", simplu: "Gradinari" },
  { nume: "Grădiștea", simplu: "Gradistea", comuna: "Comana" },
  { nume: "Greaca" },
  { nume: "Herăști", simplu: "Herasti", comuna: "Hotarele" },
  { nume: "Hobaia", comuna: "Ogrezeni" },
  { nume: "Hodivoaia", comuna: "Putineiu" },
  { nume: "Hotarele" },
  { nume: "Hulubești", simplu: "Hulubesti", comuna: "Calugareni" },
  { nume: "Ianculești", simplu: "Ianculesti", comuna: "Stoenesti" },
  { nume: "Icoana", comuna: "Ulmi" },
  { nume: "Iepurești", simplu: "Iepuresti" },
  { nume: "Isvoarele", comuna: "Hotarele" },
  { nume: "Izvoarele" },
  { nume: "Izvoru", comuna: "Gogosari" },
  { nume: "Izvoru", comuna: "Vanatorii Mici" },
  { nume: "Joița", simplu: "Joita" },
  { nume: "Letca Nouă", simplu: "Letca Noua" },
  { nume: "Letca Veche", comuna: "Letca Noua" },
  { nume: "Malu Spart", comuna: "Bolintin-Vale" },
  { nume: "Malu" },
  { nume: "Mârșa", simplu: "Marsa" },
  { nume: "Mihai Bravu" },
  { nume: "Mihai Vodă", simplu: "Mihai Voda", comuna: "Bolintin-Deal" },
  { nume: "Mihăilești", simplu: "Mihailesti" },
  { nume: "Milcovățu", simplu: "Milcovatu", comuna: "Letca Noua" },
  { nume: "Miloșești", simplu: "Milosesti", comuna: "Hotarele" },
  { nume: "Mirău", simplu: "Mirau", comuna: "Stoenesti" },
  { nume: "Mironești", simplu: "Mironesti", comuna: "Gostinari" },
  { nume: "Mogoșești", simplu: "Mogosesti", comuna: "Adunatii-Copaceni" },
  { nume: "Moșteni", simplu: "Mosteni", comuna: "Ulmi" },
  { nume: "Naipu", comuna: "Ghimpati" },
  { nume: "Neajlov", comuna: "Clejani" },
  { nume: "Novaci", comuna: "Mihailesti" },
  { nume: "Obedeni", comuna: "Bucsani" },
  { nume: "Ogrezeni" },
  { nume: "Oinacu" },
  { nume: "Oncești", simplu: "Oncesti", comuna: "Stanesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Buturugeni" },
  { nume: "Palanca", comuna: "Floresti-Stoenesti" },
  { nume: "Petru Rareș", simplu: "Petru Rares", comuna: "Izvoarele" },
  { nume: "Pietrele", comuna: "Baneasa" },
  { nume: "Pietrișu", simplu: "Pietrisu", comuna: "Gaujani" },
  { nume: "Plopșoru", simplu: "Plopsoru", comuna: "Daia" },
  { nume: "Podișor", simplu: "Podisor", comuna: "Bucsani" },
  { nume: "Podu Doamnei", comuna: "Clejani" },
  {
    nume: "Podu Ilfovățului",
    simplu: "Podu Ilfovatului",
    comuna: "Buturugeni",
  },
  { nume: "Podu Popa Nae", comuna: "Gaiseni" },
  { nume: "Poenari", comuna: "Ulmi" },
  {
    nume: "Poiana lui Stângă",
    simplu: "Poiana lui Stanga",
    comuna: "Vanatorii Mici",
  },
  { nume: "Popești", simplu: "Popesti", comuna: "Mihailesti" },
  { nume: "Poșta", simplu: "Posta", comuna: "Buturugeni" },
  { nume: "Priboiu", comuna: "Crevedia Mare" },
  { nume: "Prundu" },
  { nume: "Puieni", comuna: "Prundu" },
  { nume: "Putineiu" },
  { nume: "Puțu Greci", simplu: "Putu Greci", comuna: "Greaca" },
  { nume: "Radu Vodă", simplu: "Radu Voda", comuna: "Izvoarele" },
  { nume: "Rălești", simplu: "Ralesti", comuna: "Gogosari" },
  { nume: "Răsuceni", simplu: "Rasuceni" },
  { nume: "Remuș", simplu: "Remus", comuna: "Fratesti" },
  { nume: "Roata de Jos" },
  { nume: "Roata Mică", simplu: "Roata Mica", comuna: "Roata De Jos" },
  { nume: "Săbăreni", simplu: "Sabareni", comuna: "Joita" },
  { nume: "Sadina", comuna: "Roata De Jos" },
  { nume: "Satu Nou", comuna: "Rasuceni" },
  { nume: "Schitu" },
  { nume: "Sfântu Gheorghe", simplu: "Sfantu Gheorghe", comuna: "Baneasa" },
  {
    nume: "Sfântu Gheorghe",
    simplu: "Sfantu Gheorghe",
    comuna: "Crevedia Mare",
  },
  { nume: "Singureni" },
  { nume: "Slobozia" },
  { nume: "Stâlpu", simplu: "Stalpu", comuna: "Iepuresti" },
  { nume: "Stănești", simplu: "Stanesti" },
  { nume: "Stejaru", comuna: "Singureni" },
  { nume: "Sterea", comuna: "Clejani" },
  { nume: "Stoenești", simplu: "Stoenesti" },
  { nume: "Stoenești", simplu: "Stoenesti", comuna: "Floresti-Stoenesti" },
  { nume: "Suseni", comuna: "Bolintin-Vale" },
  { nume: "Tântava", simplu: "Tantava", comuna: "Gradinari" },
  { nume: "Teișori", simplu: "Teisori", comuna: "Bulbucata" },
  { nume: "Teiușu", simplu: "Teiusu", comuna: "Hotarele" },
  { nume: "Tomulești", simplu: "Tomulesti", comuna: "Toporu" },
  { nume: "Toporu" },
  { nume: "Trestieni", comuna: "Ulmi" },
  { nume: "Uiești", simplu: "Uiesti", comuna: "Bucsani" },
  { nume: "Ulmi" },
  { nume: "Uzunu", comuna: "Calugareni" },
  { nume: "Vadu Lat", comuna: "Bucsani" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Vanatorii Mici" },
  { nume: "Valea Bujorului", comuna: "Izvoarele" },
  { nume: "Valea Dragului" },
  { nume: "Valea Plopilor", comuna: "Ghimpati" },
  {
    nume: "Valter Mărăcineanu",
    simplu: "Valter Maracineanu",
    comuna: "Iepuresti",
  },
  {
    nume: "Vânătorii Mari",
    simplu: "Vanatorii Mari",
    comuna: "Vanatorii Mici",
  },
  { nume: "Vânătorii Mici", simplu: "Vanatorii Mici" },
  { nume: "Vărăști", simplu: "Varasti" },
  { nume: "Varlaam", comuna: "Adunatii-Copaceni" },
  { nume: "Vedea" },
  { nume: "Vieru", comuna: "Putineiu" },
  { nume: "Vlad Țepeș", simplu: "Vlad Tepes", comuna: "Comana" },
  { nume: "Vlașin", simplu: "Vlasin", comuna: "Schitu" },
  { nume: "Zădăriciu", simplu: "Zadariciu", comuna: "Vanatorii Mici" },
  { nume: "Zboiu", comuna: "Greaca" },
  { nume: "Zorile", comuna: "Gradinari" },
];
