export const gr = [
  { nume: "Adunatii-Copaceni" },
  { nume: "Bolintin-Deal" },
  { nume: "Bolintin-Vale" },
  { nume: "Bucsani" },
  { nume: "Bulbucata" },
  { nume: "Buturugeni" },
  { nume: "Baneasa" },
  { nume: "Clejani" },
  { nume: "Colibasi" },
  { nume: "Comana" },
  { nume: "Crevedia Mare" },
  { nume: "Calugareni" },
  { nume: "Daia" },
  { nume: "Fratesti" },
  { nume: "Ghimpati" },
  { nume: "Giurgiu" },
  { nume: "Gogosari" },
  { nume: "Gostinari" },
  { nume: "Gostinu" },
  { nume: "Greaca" },
  { nume: "Gradinari" },
  { nume: "Gaiseni" },
  { nume: "Gaujani" },
  { nume: "Hotarele" },
  { nume: "Iepuresti" },
  { nume: "Izvoarele" },
  { nume: "Joita" },
  { nume: "Letca Noua" },
  { nume: "Malu" },
  { nume: "Mihai Bravu" },
  { nume: "Mihailesti" },
  { nume: "Marsa" },
  { nume: "Ogrezeni" },
  { nume: "Oinacu" },
  { nume: "Prundu" },
  { nume: "Putineiu" },
  { nume: "Roata de Jos" },
  { nume: "Rasuceni" },
  { nume: "Schitu" },
  { nume: "Singureni" },
  { nume: "Slobozia" },
  { nume: "Stoenesti" },
  { nume: "Stanesti" },
  { nume: "Toporu" },
  { nume: "Ulmi" },
  { nume: "Valea Dragului" },
  { nume: "Vedea" },
  { nume: "Vanatorii Mici" },
  { nume: "Varasti" },
  { nume: "Darasti-Vlasca", comuna: "Adunatii-Copaceni" },
  { nume: "Mogosesti", comuna: "Adunatii-Copaceni" },
  { nume: "Varlaam", comuna: "Adunatii-Copaceni" },
  { nume: "Frasinu", comuna: "Baneasa" },
  { nume: "Pietrele", comuna: "Baneasa" },
  { nume: "Sfantu Gheorghe", comuna: "Baneasa" },
  { nume: "Mihai Voda", comuna: "Bolintin-Deal" },
  { nume: "Crivina", comuna: "Bolintin-Vale" },
  { nume: "Malu Spart", comuna: "Bolintin-Vale" },
  { nume: "Suseni", comuna: "Bolintin-Vale" },
  { nume: "Anghelesti", comuna: "Bucsani" },
  { nume: "Goleasca", comuna: "Bucsani" },
  { nume: "Obedeni", comuna: "Bucsani" },
  { nume: "Podisor", comuna: "Bucsani" },
  { nume: "Uiesti", comuna: "Bucsani" },
  { nume: "Vadu Lat", comuna: "Bucsani" },
  { nume: "Coteni", comuna: "Bulbucata" },
  { nume: "Facau", comuna: "Bulbucata" },
  { nume: "Teisori", comuna: "Bulbucata" },
  { nume: "Podu Ilfovatului", comuna: "Buturugeni" },
  { nume: "Posta", comuna: "Buturugeni" },
  { nume: "Padureni", comuna: "Buturugeni" },
  { nume: "Branistari", comuna: "Calugareni" },
  { nume: "Crucea de Piatra", comuna: "Calugareni" },
  { nume: "Hulubesti", comuna: "Calugareni" },
  { nume: "Uzunu", comuna: "Calugareni" },
  { nume: "Neajlov", comuna: "Clejani" },
  { nume: "Podu Doamnei", comuna: "Clejani" },
  { nume: "Sterea", comuna: "Clejani" },
  { nume: "Campurelu", comuna: "Colibasi" },
  { nume: "Budeni", comuna: "Comana" },
  { nume: "Falastoaca", comuna: "Comana" },
  { nume: "Gradistea", comuna: "Comana" },
  { nume: "Vlad Tepes", comuna: "Comana" },
  { nume: "Crevedia Mica", comuna: "Crevedia Mare" },
  { nume: "Dealu", comuna: "Crevedia Mare" },
  { nume: "Gaiseanca", comuna: "Crevedia Mare" },
  { nume: "Priboiu", comuna: "Crevedia Mare" },
  { nume: "Sfantu Gheorghe", comuna: "Crevedia Mare" },
  { nume: "Plopsoru", comuna: "Daia" },
  { nume: "Floresti", comuna: "Floresti-Stoenesti" },
  { nume: "Palanca", comuna: "Floresti-Stoenesti" },
  { nume: "Stoenesti", comuna: "Floresti-Stoenesti" },
  { nume: "Cetatea", comuna: "Fratesti" },
  { nume: "Remus", comuna: "Fratesti" },
  { nume: "Carpenisu", comuna: "Gaiseni" },
  { nume: "Cascioarele", comuna: "Gaiseni" },
  { nume: "Podu Popa Nae", comuna: "Gaiseni" },
  { nume: "Cetatuia", comuna: "Gaujani" },
  { nume: "Pietrisu", comuna: "Gaujani" },
  { nume: "Copaciu", comuna: "Ghimpati" },
  { nume: "Naipu", comuna: "Ghimpati" },
  { nume: "Valea Plopilor", comuna: "Ghimpati" },
  { nume: "Draghiceanu", comuna: "Gogosari" },
  { nume: "Izvoru", comuna: "Gogosari" },
  { nume: "Ralesti", comuna: "Gogosari" },
  { nume: "Mironesti", comuna: "Gostinari" },
  { nume: "Tantava", comuna: "Gradinari" },
  { nume: "Zorile", comuna: "Gradinari" },
  { nume: "Putu Greci", comuna: "Greaca" },
  { nume: "Zboiu", comuna: "Greaca" },
  { nume: "Herasti", comuna: "Hotarele" },
  { nume: "Isvoarele", comuna: "Hotarele" },
  { nume: "Milosesti", comuna: "Hotarele" },
  { nume: "Teiusu", comuna: "Hotarele" },
  { nume: "Banesti", comuna: "Iepuresti" },
  { nume: "Chirculesti", comuna: "Iepuresti" },
  { nume: "Gorneni", comuna: "Iepuresti" },
  { nume: "Stalpu", comuna: "Iepuresti" },
  { nume: "Valter Maracineanu", comuna: "Iepuresti" },
  { nume: "Chiriacu", comuna: "Izvoarele" },
  { nume: "Dimitrie Cantemir", comuna: "Izvoarele" },
  { nume: "Petru Rares", comuna: "Izvoarele" },
  { nume: "Radu Voda", comuna: "Izvoarele" },
  { nume: "Valea Bujorului", comuna: "Izvoarele" },
  { nume: "Bacu", comuna: "Joita" },
  { nume: "Cosoba", comuna: "Joita" },
  { nume: "Sabareni", comuna: "Joita" },
  { nume: "Letca Veche", comuna: "Letca Noua" },
  { nume: "Milcovatu", comuna: "Letca Noua" },
  { nume: "Draganescu", comuna: "Mihailesti" },
  { nume: "Novaci", comuna: "Mihailesti" },
  { nume: "Popesti", comuna: "Mihailesti" },
  { nume: "Hobaia", comuna: "Ogrezeni" },
  { nume: "Branistea", comuna: "Oinacu" },
  { nume: "Comasca", comuna: "Oinacu" },
  { nume: "Puieni", comuna: "Prundu" },
  { nume: "Hodivoaia", comuna: "Putineiu" },
  { nume: "Vieru", comuna: "Putineiu" },
  { nume: "Carapancea", comuna: "Rasuceni" },
  { nume: "Cucuruzu", comuna: "Rasuceni" },
  { nume: "Satu Nou", comuna: "Rasuceni" },
  { nume: "Cartojani", comuna: "Roata De Jos" },
  { nume: "Roata Mica", comuna: "Roata De Jos" },
  { nume: "Sadina", comuna: "Roata De Jos" },
  { nume: "Bila", comuna: "Schitu" },
  { nume: "Camineasca", comuna: "Schitu" },
  { nume: "Vlasin", comuna: "Schitu" },
  { nume: "Cranguri", comuna: "Singureni" },
  { nume: "Stejaru", comuna: "Singureni" },
  { nume: "Balanu", comuna: "Stanesti" },
  { nume: "Ghizdaru", comuna: "Stanesti" },
  { nume: "Oncesti", comuna: "Stanesti" },
  { nume: "Ianculesti", comuna: "Stoenesti" },
  { nume: "Mirau", comuna: "Stoenesti" },
  { nume: "Tomulesti", comuna: "Toporu" },
  { nume: "Cascioarele", comuna: "Ulmi" },
  { nume: "Draganeasca", comuna: "Ulmi" },
  { nume: "Ghionea", comuna: "Ulmi" },
  { nume: "Icoana", comuna: "Ulmi" },
  { nume: "Mosteni", comuna: "Ulmi" },
  { nume: "Poenari", comuna: "Ulmi" },
  { nume: "Trestieni", comuna: "Ulmi" },
  { nume: "Corbeanca", comuna: "Vanatorii Mici" },
  { nume: "Cupele", comuna: "Vanatorii Mici" },
  { nume: "Izvoru", comuna: "Vanatorii Mici" },
  { nume: "Poiana lui Stanga", comuna: "Vanatorii Mici" },
  { nume: "Valcele", comuna: "Vanatorii Mici" },
  { nume: "Vanatorii Mari", comuna: "Vanatorii Mici" },
  { nume: "Zadariciu", comuna: "Vanatorii Mici" },
  { nume: "Dobreni", comuna: "Varasti" },
];
