export const gj = [
  { nume: "Albeni" },
  { nume: "Alexeni", comuna: "Stanesti" },
  { nume: "Alimpești", simplu: "Alimpesti" },
  { nume: "Aluniș", simplu: "Alunis", comuna: "Capreni" },
  { nume: "Andreești", simplu: "Andreesti", comuna: "Vladimir" },
  { nume: "Aninișu din Deal", simplu: "Aninisu din Deal", comuna: "Crasna" },
  { nume: "Aninișu din Vale", simplu: "Aninisu din Vale", comuna: "Crasna" },
  { nume: "Aninoasa" },
  { nume: "Apa Neagră", simplu: "Apa Neagra", comuna: "Pades" },
  { nume: "Arcani" },
  { nume: "Arjoci", comuna: "Godinesti" },
  { nume: "Arpadia", comuna: "Tantareni" },
  { nume: "Arșeni", simplu: "Arseni", comuna: "Musetesti" },
  { nume: "Arsuri", comuna: "Schela" },
  { nume: "Artanu", comuna: "Negomir" },
  { nume: "Băcești", simplu: "Bacesti", comuna: "Stejari" },
  { nume: "Bădești", simplu: "Badesti", comuna: "Branesti" },
  { nume: "Baia de Fier" },
  { nume: "Bălăcești", simplu: "Balacesti", comuna: "Bolbosi" },
  { nume: "Bălănești", simplu: "Balanesti" },
  { nume: "Bălani", simplu: "Balani", comuna: "Stanesti" },
  { nume: "Bălcești", simplu: "Balcesti", comuna: "Bengesti-Ciocadia" },
  { nume: "Bălești", simplu: "Balesti" },
  { nume: "Baloșani", simplu: "Balosani", comuna: "Stejari" },
  { nume: "Bâlta", simplu: "Balta", comuna: "Runcu" },
  { nume: "Bâlteni", simplu: "Balteni" },
  { nume: "Bâltișoara", simplu: "Baltisoara", comuna: "Runcu" },
  { nume: "Baniu", comuna: "Borascu" },
  { nume: "Bărbătești", simplu: "Barbatesti" },
  { nume: "Bârcaciu", simplu: "Barcaciu", comuna: "Musetesti" },
  { nume: "Bârsești", simplu: "Barsesti", comuna: "Targu Jiu" },
  { nume: "Barza", comuna: "Danesti" },
  { nume: "Bârzeiu de Gilort", simplu: "Barzeiu de Gilort", comuna: "Albeni" },
  { nume: "Bârzeiu", simplu: "Barzeiu", comuna: "Berlesti" },
  { nume: "Băzăvani", simplu: "Bazavani", comuna: "Samarinesti" },
  { nume: "Becheni", comuna: "Rosia De Amaradia" },
  { nume: "Bengești", simplu: "Bengesti", comuna: "Bengesti-Ciocadia" },
  { nume: "Bercești", simplu: "Bercesti", comuna: "Novaci" },
  { nume: "Berlești", simplu: "Berlesti" },
  { nume: "Bibești", simplu: "Bibesti", comuna: "Saulesti" },
  { nume: "Bibulești", simplu: "Bibulesti", comuna: "Danciulesti" },
  { nume: "Bircii", comuna: "Bengesti-Ciocadia" },
  {
    nume: "Blahnița de Jos",
    simplu: "Blahnita de Jos",
    comuna: "Tirgu Carbunesti",
  },
  { nume: "Blahnița de Sus", simplu: "Blahnita de Sus", comuna: "Sacelu" },
  { nume: "Blidari", comuna: "Balanesti" },
  { nume: "Bobaia", comuna: "Aninoasa" },
  { nume: "Boboiești", simplu: "Boboiesti", comuna: "Ciuperceni" },
  { nume: "Bobu", comuna: "Scoarta" },
  { nume: "Boca", comuna: "Samarinesti" },
  { nume: "Bohorel", comuna: "Negomir" },
  { nume: "Boia", comuna: "Jupanesti" },
  { nume: "Bojinu", comuna: "Cruset" },
  { nume: "Bolboasa", comuna: "Bolbosi" },
  { nume: "Bolbocești", simplu: "Bolbocesti", comuna: "Albeni" },
  { nume: "Bolboși", simplu: "Bolbosi" },
  { nume: "Borăscu", simplu: "Borascu" },
  { nume: "Boroșteni", simplu: "Borosteni", comuna: "Pestisani" },
  { nume: "Botorogi", comuna: "Danesti" },
  { nume: "Brădet", simplu: "Bradet", comuna: "Matasari" },
  { nume: "Brădețel", simplu: "Bradetel", comuna: "Matasari" },
  { nume: "Brădiceni", simplu: "Bradiceni", comuna: "Pestisani" },
  { nume: "Brănești", simplu: "Branesti" },
  { nume: "Brătești", simplu: "Bratesti", comuna: "Capreni" },
  { nume: "Brătuia", simplu: "Bratuia", comuna: "Danesti" },
  { nume: "Brebenei", comuna: "Branesti" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Plopsoru" },
  { nume: "Broștenii de Sus", simplu: "Brostenii de Sus", comuna: "Plopsoru" },
  { nume: "Bucșana", simplu: "Bucsana", comuna: "Prigoria" },
  { nume: "Bucureasa", comuna: "Danesti" },
  { nume: "Budieni", comuna: "Scoarta" },
  { nume: "Buduhala", comuna: "Telesti" },
  { nume: "Bulbuceni", comuna: "Capreni" },
  { nume: "Bumbești-Jiu", simplu: "Bumbesti-Jiu" },
  { nume: "Bumbești-Pițic", simplu: "Bumbesti-Pitic" },
  { nume: "Burlani", comuna: "Prigoria" },
  { nume: "Bustuchin" },
  { nume: "Busuioci", comuna: "Hurezani" },
  { nume: "Buzești", simplu: "Buzesti", comuna: "Crasna" },
  { nume: "Calapăru", simplu: "Calaparu", comuna: "Borascu" },
  { nume: "Câlcești", simplu: "Calcesti", comuna: "Godinesti" },
  { nume: "Călești", simplu: "Calesti", comuna: "Stanesti" },
  { nume: "Câlnic", simplu: "Calnic" },
  { nume: "Câlnicu de Sus", simplu: "Calnicu de Sus", comuna: "Calnic" },
  { nume: "Călugăreasa", simplu: "Calugareasa", comuna: "Prigoria" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Pades" },
  { nume: "Câmpofeni", simplu: "Campofeni", comuna: "Arcani" },
  { nume: "Câmpu Mare", simplu: "Campu Mare", comuna: "Scoarta" },
  { nume: "Cămuiești", simplu: "Camuiesti", comuna: "Glogova" },
  { nume: "Cânepești", simplu: "Canepesti", comuna: "Balanesti" },
  { nume: "Căpreni", simplu: "Capreni" },
  { nume: "Capu Dealului", comuna: "Branesti" },
  { nume: "Cârbești", simplu: "Carbesti", comuna: "Dragutesti" },
  {
    nume: "Cărbunești-Sat",
    simplu: "Carbunesti-Sat",
    comuna: "Tirgu Carbunesti",
  },
  { nume: "Cârciu", simplu: "Carciu", comuna: "Vagiulesti" },
  { nume: "Cârligei", simplu: "Carligei", comuna: "Bumbesti-Pitic" },
  { nume: "Cărpiniș", simplu: "Carpinis", comuna: "Crasna" },
  { nume: "Cartiu", comuna: "Turcinesti" },
  { nume: "Cătunele", simplu: "Catunele" },
  { nume: "Ceauru", comuna: "Balesti" },
  { nume: "Celei", comuna: "Tismana" },
  { nume: "Ceplea", comuna: "Plopsoru" },
  {
    nume: "Cerătu de Copăcioasa",
    simplu: "Ceratu de Copacioasa",
    comuna: "Scoarta",
  },
  { nume: "Cerna-Sat", comuna: "Pades" },
  { nume: "Cernădia", simplu: "Cernadia", comuna: "Baia De Fier" },
  { nume: "Cetatea", comuna: "Capreni" },
  { nume: "Chiciora", comuna: "Tantareni" },
  { nume: "Chiliu", comuna: "Godinesti" },
  { nume: "Ciocadia", comuna: "Bengesti-Ciocadia" },
  { nume: "Cionți", simplu: "Cionti", comuna: "Bustuchin" },
  { nume: "Ciorari", comuna: "Stoina" },
  { nume: "Ciuperceni" },
  {
    nume: "Ciupercenii de Olteț",
    simplu: "Ciupercenii de Oltet",
    comuna: "Alimpesti",
  },
  { nume: "Cleșnești", simplu: "Clesnesti", comuna: "Glogova" },
  { nume: "Cloșani", simplu: "Closani", comuna: "Pades" },
  { nume: "Cocoreni", comuna: "Balteni" },
  { nume: "Cocorova", comuna: "Turburea" },
  { nume: "Cojani", comuna: "Tirgu Carbunesti" },
  { nume: "Cojmănești", simplu: "Cojmanesti", comuna: "Slivilesti" },
  { nume: "Colibași", simplu: "Colibasi", comuna: "Scoarta" },
  { nume: "Colțești", simplu: "Coltesti", comuna: "Logresti" },
  { nume: "Condeiești", simplu: "Condeiesti", comuna: "Negomir" },
  { nume: "Copăcioasa", simplu: "Copacioasa", comuna: "Scoarta" },
  { nume: "Cornești", simplu: "Cornesti", comuna: "Balesti" },
  { nume: "Cornetu", comuna: "Capreni" },
  { nume: "Corobăi", simplu: "Corobai", comuna: "Dragotesti" },
  { nume: "Corșoru", simplu: "Corsoru", comuna: "Alimpesti" },
  { nume: "Costeni", comuna: "Tismana" },
  { nume: "Costești", simplu: "Costesti", comuna: "Aninoasa" },
  { nume: "Covrigi", comuna: "Vagiulesti" },
  { nume: "Crasna din Deal", comuna: "Crasna" },
  { nume: "Crasna" },
  { nume: "Crețești", simplu: "Cretesti", comuna: "Tirgu Carbunesti" },
  { nume: "Croici", comuna: "Matasari" },
  { nume: "Crușet", simplu: "Cruset" },
  { nume: "Curpen", comuna: "Stanesti" },
  { nume: "Cursaru", comuna: "Plopsoru" },
  { nume: "Curteana", comuna: "Tirgu Carbunesti" },
  { nume: "Curtișoara", simplu: "Curtisoara", comuna: "Bumbesti-Jiu" },
  { nume: "Dâmbova", simplu: "Dambova", comuna: "Dragutesti" },
  { nume: "Dănciulești", simplu: "Danciulesti" },
  { nume: "Dănești", simplu: "Danesti" },
  { nume: "Dealu Leului", comuna: "Stejari" },
  { nume: "Dealu Pomilor", comuna: "Motru" },
  { nume: "Dealu Spirei", comuna: "Capreni" },
  { nume: "Dealu Viei", comuna: "Rosia De Amaradia" },
  { nume: "Dealu Viilor", comuna: "Catunele" },
  { nume: "Deleni", comuna: "Plopsoru" },
  { nume: "Didilești", simplu: "Didilesti", comuna: "Calnic" },
  { nume: "Dobrana", comuna: "Prigoria" },
  { nume: "Dobrița", simplu: "Dobrita", comuna: "Runcu" },
  { nume: "Dolcești", simplu: "Dolcesti", comuna: "Saulesti" },
  { nume: "Doseni", comuna: "Albeni" },
  { nume: "Drăgoeni", simplu: "Dragoeni", comuna: "Targu Jiu" },
  { nume: "Drăgoiești", simplu: "Dragoiesti", comuna: "Crasna" },
  { nume: "Drăgotești", simplu: "Dragotesti" },
  { nume: "Drăguțești", simplu: "Dragutesti" },
  { nume: "Duculești", simplu: "Duculesti", comuna: "Samarinesti" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Crasna" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Urdari" },
  {
    nume: "Fărcășești Moșneni",
    simplu: "Farcasesti Mosneni",
    comuna: "Farcasesti",
  },
  { nume: "Fărcășești", simplu: "Farcasesti" },
  { nume: "Floreșteni", simplu: "Floresteni", comuna: "Tirgu Carbunesti" },
  { nume: "Florești", simplu: "Floresti", comuna: "Tantareni" },
  { nume: "Frâncești", simplu: "Francesti", comuna: "Pestisani" },
  { nume: "Frasin", comuna: "Vladimir" },
  { nume: "Frătești", simplu: "Fratesti", comuna: "Lelesti" },
  { nume: "Frumușei", simplu: "Frumusei", comuna: "Licurici" },
  { nume: "Frunza", comuna: "Logresti" },
  { nume: "Gâlcești", simplu: "Galcesti", comuna: "Berlesti" },
  { nume: "Găleșoaia", simplu: "Galesoaia", comuna: "Calnic" },
  { nume: "Gămani", simplu: "Gamani", comuna: "Musetesti" },
  { nume: "Gârbovu", simplu: "Garbovu", comuna: "Turceni" },
  { nume: "Găvănești", simplu: "Gavanesti", comuna: "Balesti" },
  { nume: "Gilortu", comuna: "Branesti" },
  { nume: "Glodeni", comuna: "Balanesti" },
  { nume: "Glogova" },
  { nume: "Godinești", simplu: "Godinesti" },
  { nume: "Gornăcel", simplu: "Gornacel", comuna: "Schela" },
  { nume: "Gornovița", simplu: "Gornovita", comuna: "Tismana" },
  { nume: "Groșerea", simplu: "Groserea", comuna: "Aninoasa" },
  { nume: "Grui", comuna: "Musetesti" },
  { nume: "Gura Menți", simplu: "Gura Menti", comuna: "Borascu" },
  { nume: "Gura Șușiței", simplu: "Gura Susitei", comuna: "Ionesti" },
  { nume: "Gureni", comuna: "Pestisani" },
  { nume: "Hăiești", simplu: "Haiesti", comuna: "Sacelu" },
  { nume: "Hălăngești", simplu: "Halangesti", comuna: "Danciulesti" },
  { nume: "Hirișești", simplu: "Hirisesti", comuna: "Novaci" },
  { nume: "Hobița", simplu: "Hobita", comuna: "Pestisani" },
  { nume: "Hodoreasca", comuna: "Calnic" },
  { nume: "Horăști", simplu: "Horasti", comuna: "Motru" },
  { nume: "Horezu", comuna: "Turcinesti" },
  { nume: "Hotăroasa", simplu: "Hotaroasa", comuna: "Urdari" },
  { nume: "Hurezani" },
  { nume: "Iași-Gorj", simplu: "Iasi-Gorj", comuna: "Dragutesti" },
  { nume: "Iezureni", comuna: "Targu Jiu" },
  { nume: "Igirosu", comuna: "Bolbosi" },
  { nume: "Iliești", simplu: "Iliesti", comuna: "Ionesti" },
  { nume: "Însurăței", simplu: "Insuratei", comuna: "Motru" },
  { nume: "Ionești", simplu: "Ionesti" },
  { nume: "Iormănești", simplu: "Iormanesti", comuna: "Glogova" },
  { nume: "Isvarna", comuna: "Tismana" },
  { nume: "Izvoarele", comuna: "Plopsoru" },
  { nume: "Jeriștea", simplu: "Jeristea", comuna: "Sacelu" },
  { nume: "Jilțu", simplu: "Jiltu", comuna: "Turceni" },
  { nume: "Jupânești", simplu: "Jupanesti" },
  { nume: "Larga", comuna: "Samarinesti" },
  { nume: "Lăzărești", simplu: "Lazaresti", comuna: "Bumbesti-Jiu" },
  { nume: "Lazuri", comuna: "Scoarta" },
  { nume: "Lelești", simplu: "Lelesti" },
  { nume: "Leurda", comuna: "Motru" },
  { nume: "Licurici" },
  { nume: "Lihulești", simplu: "Lihulesti", comuna: "Berlesti" },
  { nume: "Lintea", comuna: "Scoarta" },
  { nume: "Logrești Moșteni", simplu: "Logresti Mosteni", comuna: "Logresti" },
  { nume: "Lupoaia", comuna: "Catunele" },
  { nume: "Lupoița", simplu: "Lupoita", comuna: "Motru" },
  { nume: "Măceșu", simplu: "Macesu", comuna: "Tirgu Carbunesti" },
  { nume: "Magherești", simplu: "Magheresti", comuna: "Sacelu" },
  { nume: "Măiag", simplu: "Maiag", comuna: "Cruset" },
  { nume: "Marinești", simplu: "Marinesti", comuna: "Cruset" },
  { nume: "Măru", simplu: "Maru", comuna: "Logresti" },
  { nume: "Mătăsari", simplu: "Matasari" },
  { nume: "Măzăroi", simplu: "Mazaroi", comuna: "Stanesti" },
  { nume: "Menții din Dos", simplu: "Mentii din Dos", comuna: "Borascu" },
  { nume: "Merfulești", simplu: "Merfulesti", comuna: "Danesti" },
  { nume: "Miclosu", comuna: "Bolbosi" },
  { nume: "Miculești", simplu: "Miculesti", comuna: "Slivilesti" },
  { nume: "Mielușei", simplu: "Mielusei", comuna: "Stoina" },
  { nume: "Mierea", comuna: "Cruset" },
  { nume: "Miericeaua", comuna: "Cruset" },
  { nume: "Miluta", comuna: "Borascu" },
  { nume: "Mirosloveni", comuna: "Albeni" },
  { nume: "Mogoșani", simplu: "Mogosani", comuna: "Scoarta" },
  { nume: "Moi", comuna: "Balteni" },
  { nume: "Motorgi", comuna: "Bustuchin" },
  { nume: "Motru Sec", comuna: "Pades" },
  { nume: "Motru" },
  { nume: "Murgești", simplu: "Murgesti", comuna: "Turceni" },
  { nume: "Murgilești", simplu: "Murgilesti", comuna: "Vagiulesti" },
  { nume: "Musculești", simplu: "Musculesti", comuna: "Barbatesti" },
  { nume: "Mușetești", simplu: "Musetesti" },
  { nume: "Nămete", simplu: "Namete", comuna: "Bustuchin" },
  { nume: "Negoiești", simplu: "Negoiesti", comuna: "Prigoria" },
  { nume: "Negomir" },
  { nume: "Negreni", comuna: "Licurici" },
  { nume: "Nistorești", simplu: "Nistoresti", comuna: "Alimpesti" },
  { nume: "Novaci" },
  { nume: "Nucetu", comuna: "Negomir" },
  { nume: "Obârșia", simplu: "Obarsia", comuna: "Danciulesti" },
  { nume: "Obreja", comuna: "Stanesti" },
  { nume: "Ohaba Jiu", comuna: "Bolbosi" },
  { nume: "Ohaba", comuna: "Balanesti" },
  { nume: "Olari", comuna: "Plopsoru" },
  { nume: "Olteanu", comuna: "Glogova" },
  { nume: "Orzești", simplu: "Orzesti", comuna: "Pades" },
  { nume: "Orzu", comuna: "Negomir" },
  { nume: "Padeș", simplu: "Pades" },
  { nume: "Păișani", simplu: "Paisani", comuna: "Stoina" },
  { nume: "Păjiștele", simplu: "Pajistele", comuna: "Schela" },
  { nume: "Paltinu", comuna: "Negomir" },
  { nume: "Pârâu Boia", simplu: "Parau Boia", comuna: "Jupanesti" },
  { nume: "Pârâu de Pripor", simplu: "Parau de Pripor", comuna: "Godinesti" },
  { nume: "Pârâu de Vale", simplu: "Parau de Vale", comuna: "Godinesti" },
  { nume: "Pârâu Viu", simplu: "Parau Viu", comuna: "Berlesti" },
  { nume: "Pârâu", simplu: "Parau", comuna: "Branesti" },
  { nume: "Pârvulești", simplu: "Parvulesti", comuna: "Stanesti" },
  { nume: "Pegeni", comuna: "Hurezani" },
  { nume: "Peșteana de Jos", simplu: "Pesteana de Jos", comuna: "Farcasesti" },
  { nume: "Peșteana Jiu", simplu: "Pesteana Jiu", comuna: "Balteni" },
  { nume: "Peșteana Vulcan", simplu: "Pesteana Vulcan", comuna: "Ciuperceni" },
  { nume: "Peștișani", simplu: "Pestisani" },
  { nume: "Petrăchei", simplu: "Petrachei", comuna: "Danciulesti" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Barbatesti" },
  { nume: "Picu", comuna: "Ionesti" },
  { nume: "Pieptani", comuna: "Calnic" },
  { nume: "Pinoasa", comuna: "Calnic" },
  { nume: "Piscoiu", comuna: "Stejari" },
  { nume: "Piscuri", comuna: "Plopsoru" },
  {
    nume: "Pișteștii din Deal",
    simplu: "Pistestii din Deal",
    comuna: "Scoarta",
  },
  { nume: "Pleșa", simplu: "Plesa", comuna: "Bumbesti-Jiu" },
  { nume: "Plopșoru", simplu: "Plopsoru" },
  { nume: "Plopu", comuna: "Hurezani" },
  { nume: "Ploștina", simplu: "Plostina", comuna: "Motru" },
  { nume: "Pociovaliștea", simplu: "Pociovalistea", comuna: "Novaci" },
  { nume: "Pocruia", comuna: "Tismana" },
  { nume: "Poiana Seciuri", comuna: "Bustuchin" },
  { nume: "Poiana", comuna: "Turburea" },
  { nume: "Poienari", comuna: "Bumbesti-Pitic" },
  { nume: "Poienița", simplu: "Poienita", comuna: "Bustuchin" },
  { nume: "Pojaru", comuna: "Bustuchin" },
  { nume: "Pojogeni", comuna: "Tirgu Carbunesti" },
  { nume: "Polata", comuna: "Targu Jiu" },
  { nume: "Polovragi" },
  { nume: "Popești Stejari", simplu: "Popesti Stejari", comuna: "Stejari" },
  { nume: "Popești", simplu: "Popesti", comuna: "Logresti" },
  { nume: "Preajba Mare", comuna: "Targu Jiu" },
  { nume: "Prigoria" },
  { nume: "Priporu", comuna: "Ciuperceni" },
  { nume: "Prunești", simplu: "Prunesti", comuna: "Albeni" },
  { nume: "Purcaru", comuna: "Saulesti" },
  { nume: "Răchiți", simplu: "Rachiti", comuna: "Runcu" },
  { nume: "Raci", comuna: "Negomir" },
  { nume: "Racoți", simplu: "Racoti", comuna: "Tismana" },
  { nume: "Racovița", simplu: "Racovita", comuna: "Polovragi" },
  { nume: "Rădinești", simplu: "Radinesti", comuna: "Danciulesti" },
  { nume: "Radoși", simplu: "Radosi", comuna: "Crasna" },
  { nume: "Râpa", simplu: "Rapa", comuna: "Motru" },
  { nume: "Rasova", comuna: "Balesti" },
  { nume: "Rasovița", simplu: "Rasovita", comuna: "Lelesti" },
  { nume: "Rătez", simplu: "Ratez", comuna: "Godinesti" },
  { nume: "Rogojel", comuna: "Farcasesti" },
  { nume: "Rogojeni", comuna: "Tirgu Carbunesti" },
  { nume: "Romanești", simplu: "Romanesti", comuna: "Targu Jiu" },
  { nume: "Roșia de Amaradia", simplu: "Rosia de Amaradia" },
  { nume: "Roșia Jiu", simplu: "Rosia Jiu", comuna: "Farcasesti" },
  { nume: "Roșiuța", simplu: "Rosiuta", comuna: "Motru" },
  { nume: "Rovinari" },
  { nume: "Ruget", comuna: "Rosia De Amaradia" },
  { nume: "Rugi", comuna: "Turcinesti" },
  { nume: "Runcu" },
  { nume: "Runcurel", comuna: "Matasari" },
  { nume: "Săcelu", simplu: "Sacelu" },
  { nume: "Samarinești", simplu: "Samarinesti" },
  { nume: "Sâmbotin", simplu: "Sambotin", comuna: "Schela" },
  { nume: "Sănătești", simplu: "Sanatesti", comuna: "Arcani" },
  { nume: "Sârbești", simplu: "Sarbesti", comuna: "Alimpesti" },
  { nume: "Sărdănești", simplu: "Sardanesti", comuna: "Plopsoru" },
  { nume: "Șasa", simplu: "Sasa", comuna: "Danesti" },
  { nume: "Satu Nou", comuna: "Capreni" },
  { nume: "Săulești", simplu: "Saulesti" },
  { nume: "Schela" },
  { nume: "Scoarța", simplu: "Scoarta" },
  { nume: "Scorușu", simplu: "Scorusu", comuna: "Borascu" },
  { nume: "Scrada", comuna: "Berlesti" },
  { nume: "Scurtu", comuna: "Berlesti" },
  { nume: "Seaca", comuna: "Logresti" },
  { nume: "Seciurile", comuna: "Rosia De Amaradia" },
  { nume: "Seuca", comuna: "Pestisani" },
  { nume: "Șiacu", simplu: "Siacu", comuna: "Slivilesti" },
  { nume: "Șipotu", simplu: "Sipotu", comuna: "Turburea" },
  { nume: "Sitești", simplu: "Sitesti", comuna: "Novaci" },
  { nume: "Șitoaia", simplu: "Sitoaia", comuna: "Rosia De Amaradia" },
  { nume: "Slămnești", simplu: "Slamnesti", comuna: "Cruset" },
  { nume: "Slăvuța", simplu: "Slavuta", comuna: "Cruset" },
  { nume: "Slivilești", simplu: "Slivilesti" },
  { nume: "Slobozia", comuna: "Targu Jiu" },
  { nume: "Socu", comuna: "Barbatesti" },
  { nume: "Sohodol", comuna: "Tismana" },
  { nume: "Șomănești", simplu: "Somanesti", comuna: "Telesti" },
  { nume: "Spahii", comuna: "Turburea" },
  { nume: "Stăncești Larga", simplu: "Stancesti Larga", comuna: "Musetesti" },
  { nume: "Stăncești", simplu: "Stancesti", comuna: "Musetesti" },
  { nume: "Stănești", simplu: "Stanesti" },
  { nume: "Ștefănești", simplu: "Stefanesti", comuna: "Tirgu Carbunesti" },
  { nume: "Steic", comuna: "Catunele" },
  { nume: "Stejari" },
  { nume: "Stejaru", comuna: "Rosia De Amaradia" },
  { nume: "Stejerei", comuna: "Calnic" },
  { nume: "Sterpoaia", comuna: "Aninoasa" },
  { nume: "Știucani", simplu: "Stiucani", comuna: "Slivilesti" },
  { nume: "Stoina" },
  { nume: "Stolojani", comuna: "Balesti" },
  { nume: "Strâmba Jiu", simplu: "Stramba Jiu", comuna: "Turceni" },
  { nume: "Strâmba Vulcan", simplu: "Stramba Vulcan", comuna: "Ciuperceni" },
  { nume: "Strâmtu", simplu: "Stramtu", comuna: "Slivilesti" },
  { nume: "Stroiești", simplu: "Stroiesti", comuna: "Arcani" },
  { nume: "Sura", comuna: "Slivilesti" },
  { nume: "Suseni", comuna: "Runcu" },
  { nume: "Tălpășești", simplu: "Talpasesti", comuna: "Balesti" },
  { nume: "Tâlvești", simplu: "Talvesti", comuna: "Dragutesti" },
  { nume: "Tămășești", simplu: "Tamasesti", comuna: "Balesti" },
  { nume: "Țânțăreni", simplu: "Tantareni" },
  { nume: "Țârculești", simplu: "Tarculesti", comuna: "Danesti" },
  {
    nume: "Târgu Cărbunești",
    simplu: "Targu Carbunesti",
    comuna: "Tirgu Carbunesti",
  },
  { nume: "Târgu Jiu", simplu: "Targu Jiu" },
  { nume: "Târgu Logrești", simplu: "Targu Logresti", comuna: "Logresti" },
  { nume: "Tehomir", comuna: "Slivilesti" },
  { nume: "Telești", simplu: "Telesti" },
  { nume: "Tetila", comuna: "Bumbesti-Jiu" },
  { nume: "Țicleni", simplu: "Ticleni" },
  { nume: "Timișeni", simplu: "Timiseni", comuna: "Farcasesti" },
  { nume: "Țirioi", simplu: "Tirioi", comuna: "Samarinesti" },
  { nume: "Tismana" },
  { nume: "Toiaga", comuna: "Stoina" },
  { nume: "Topești", simplu: "Topesti", comuna: "Tismana" },
  { nume: "Totea de Hurezani", comuna: "Hurezani" },
  { nume: "Totea", comuna: "Licurici" },
  { nume: "Trestioara", comuna: "Dragotesti" },
  { nume: "Trocani", comuna: "Danesti" },
  { nume: "Turburea" },
  { nume: "Turceni" },
  { nume: "Turcinești", simplu: "Turcinesti" },
  { nume: "Ulmet", comuna: "Stoina" },
  { nume: "Ungureni", comuna: "Danesti" },
  { nume: "Urda de Jos", comuna: "Cruset" },
  { nume: "Urda de Sus", comuna: "Stoina" },
  { nume: "Urdari" },
  { nume: "Urechești", simplu: "Urechesti", comuna: "Dragutesti" },
  { nume: "Ursați", simplu: "Ursati", comuna: "Targu Jiu" },
  { nume: "Ursoaia", comuna: "Negomir" },
  { nume: "Văcarea", simplu: "Vacarea", comuna: "Danesti" },
  { nume: "Văgiulești", simplu: "Vagiulesti" },
  { nume: "Vaidei", comuna: "Stanesti" },
  { nume: "Văieni", simplu: "Vaieni", comuna: "Pades" },
  { nume: "Vălari", simplu: "Valari", comuna: "Stanesti" },
  { nume: "Vâlceaua", simplu: "Valceaua", comuna: "Calnic" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Tismana" },
  { nume: "Valea Bisericii", comuna: "Samarinesti" },
  { nume: "Valea cu Apă", simplu: "Valea cu Apa", comuna: "Farcasesti" },
  { nume: "Valea Deșului", simplu: "Valea Desului", comuna: "Vladimir" },
  { nume: "Valea Mânăstirii", simplu: "Valea Manastirii", comuna: "Catunele" },
  { nume: "Valea Mare", comuna: "Runcu" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Samarinesti" },
  { nume: "Valea Motrului", comuna: "Vagiulesti" },
  { nume: "Valea Perilor", comuna: "Catunele" },
  { nume: "Valea Poienii", comuna: "Samarinesti" },
  { nume: "Valea Pojarului", comuna: "Bustuchin" },
  { nume: "Valea Racilor", comuna: "Negomir" },
  { nume: "Valea Viei", comuna: "Turceni" },
  { nume: "Valea", comuna: "Bolbosi" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Plopsoru" },
  { nume: "Văluța", simplu: "Valuta", comuna: "Cruset" },
  { nume: "Vânata", simplu: "Vanata", comuna: "Tismana" },
  { nume: "Vârt", simplu: "Vart", comuna: "Rovinari" },
  { nume: "Vârtopu", simplu: "Vartopu", comuna: "Ciuperceni" },
  { nume: "Vidin", comuna: "Jupanesti" },
  { nume: "Vierșani", simplu: "Viersani", comuna: "Jupanesti" },
  { nume: "Vladimir" },
  { nume: "Vlăduleni", simplu: "Vladuleni", comuna: "Balteni" },
  { nume: "Voinigești", simplu: "Voinigesti", comuna: "Balesti" },
  {
    nume: "Voiteștii de Vale",
    simplu: "Voitestii de Vale",
    comuna: "Balanesti",
  },
  {
    nume: "Voiteștii din Deal",
    simplu: "Voitestii din Deal",
    comuna: "Balanesti",
  },
  { nume: "Zăicoiu", simplu: "Zaicoiu", comuna: "Danciulesti" },
  { nume: "Zorlești", simplu: "Zorlesti", comuna: "Prigoria" },
  { nume: "Zorzila", comuna: "Ciuperceni" },
];
