export const gj = [
  { nume: "Albeni" },
  { nume: "Alimpesti" },
  { nume: "Aninoasa" },
  { nume: "Arcani" },
  { nume: "Baia de Fier" },
  { nume: "Berlesti" },
  { nume: "Bolbosi" },
  { nume: "Borascu" },
  { nume: "Branesti" },
  { nume: "Bumbesti-Jiu" },
  { nume: "Bumbesti-Pitic" },
  { nume: "Bustuchin" },
  { nume: "Balteni" },
  { nume: "Balesti" },
  { nume: "Balanesti" },
  { nume: "Barbatesti" },
  { nume: "Ciuperceni" },
  { nume: "Crasna" },
  { nume: "Cruset" },
  { nume: "Calnic" },
  { nume: "Capreni" },
  { nume: "Catunele" },
  { nume: "Dragotesti" },
  { nume: "Dragutesti" },
  { nume: "Danciulesti" },
  { nume: "Danesti" },
  { nume: "Farcasesti" },
  { nume: "Glogova" },
  { nume: "Godinesti" },
  { nume: "Hurezani" },
  { nume: "Ionesti" },
  { nume: "Jupanesti" },
  { nume: "Lelesti" },
  { nume: "Licurici" },
  { nume: "Motru" },
  { nume: "Musetesti" },
  { nume: "Matasari" },
  { nume: "Negomir" },
  { nume: "Novaci" },
  { nume: "Pades" },
  { nume: "Pestisani" },
  { nume: "Plopsoru" },
  { nume: "Polovragi" },
  { nume: "Prigoria" },
  { nume: "Rovinari" },
  { nume: "Rosia de Amaradia" },
  { nume: "Runcu" },
  { nume: "Samarinesti" },
  { nume: "Schela" },
  { nume: "Scoarta" },
  { nume: "Slivilesti" },
  { nume: "Stejari" },
  { nume: "Stoina" },
  { nume: "Stanesti" },
  { nume: "Sacelu" },
  { nume: "Saulesti" },
  { nume: "Telesti" },
  { nume: "Tismana" },
  { nume: "Turburea" },
  { nume: "Turceni" },
  { nume: "Turcinesti" },
  { nume: "Targu Jiu" },
  { nume: "Urdari" },
  { nume: "Vladimir" },
  { nume: "Vagiulesti" },
  { nume: "Ticleni" },
  { nume: "Tantareni" },
  { nume: "Bolbocesti", comuna: "Albeni" },
  { nume: "Barzeiu de Gilort", comuna: "Albeni" },
  { nume: "Doseni", comuna: "Albeni" },
  { nume: "Mirosloveni", comuna: "Albeni" },
  { nume: "Prunesti", comuna: "Albeni" },
  { nume: "Ciupercenii de Oltet", comuna: "Alimpesti" },
  { nume: "Corsoru", comuna: "Alimpesti" },
  { nume: "Nistoresti", comuna: "Alimpesti" },
  { nume: "Sarbesti", comuna: "Alimpesti" },
  { nume: "Bobaia", comuna: "Aninoasa" },
  { nume: "Costesti", comuna: "Aninoasa" },
  { nume: "Groserea", comuna: "Aninoasa" },
  { nume: "Sterpoaia", comuna: "Aninoasa" },
  { nume: "Campofeni", comuna: "Arcani" },
  { nume: "Stroiesti", comuna: "Arcani" },
  { nume: "Sanatesti", comuna: "Arcani" },
  { nume: "Cernadia", comuna: "Baia De Fier" },
  { nume: "Blidari", comuna: "Balanesti" },
  { nume: "Canepesti", comuna: "Balanesti" },
  { nume: "Glodeni", comuna: "Balanesti" },
  { nume: "Ohaba", comuna: "Balanesti" },
  { nume: "Voitestii de Vale", comuna: "Balanesti" },
  { nume: "Voitestii din Deal", comuna: "Balanesti" },
  { nume: "Ceauru", comuna: "Balesti" },
  { nume: "Cornesti", comuna: "Balesti" },
  { nume: "Gavanesti", comuna: "Balesti" },
  { nume: "Rasova", comuna: "Balesti" },
  { nume: "Stolojani", comuna: "Balesti" },
  { nume: "Talpasesti", comuna: "Balesti" },
  { nume: "Tamasesti", comuna: "Balesti" },
  { nume: "Voinigesti", comuna: "Balesti" },
  { nume: "Cocoreni", comuna: "Balteni" },
  { nume: "Moi", comuna: "Balteni" },
  { nume: "Pesteana Jiu", comuna: "Balteni" },
  { nume: "Vladuleni", comuna: "Balteni" },
  { nume: "Musculesti", comuna: "Barbatesti" },
  { nume: "Petresti", comuna: "Barbatesti" },
  { nume: "Socu", comuna: "Barbatesti" },
  { nume: "Bengesti", comuna: "Bengesti-Ciocadia" },
  { nume: "Bircii", comuna: "Bengesti-Ciocadia" },
  { nume: "Balcesti", comuna: "Bengesti-Ciocadia" },
  { nume: "Ciocadia", comuna: "Bengesti-Ciocadia" },
  { nume: "Barzeiu", comuna: "Berlesti" },
  { nume: "Galcesti", comuna: "Berlesti" },
  { nume: "Lihulesti", comuna: "Berlesti" },
  { nume: "Parau Viu", comuna: "Berlesti" },
  { nume: "Scrada", comuna: "Berlesti" },
  { nume: "Scurtu", comuna: "Berlesti" },
  { nume: "Bolboasa", comuna: "Bolbosi" },
  { nume: "Balacesti", comuna: "Bolbosi" },
  { nume: "Igirosu", comuna: "Bolbosi" },
  { nume: "Miclosu", comuna: "Bolbosi" },
  { nume: "Ohaba Jiu", comuna: "Bolbosi" },
  { nume: "Valea", comuna: "Bolbosi" },
  { nume: "Baniu", comuna: "Borascu" },
  { nume: "Calaparu", comuna: "Borascu" },
  { nume: "Gura Menti", comuna: "Borascu" },
  { nume: "Mentii din Dos", comuna: "Borascu" },
  { nume: "Miluta", comuna: "Borascu" },
  { nume: "Scorusu", comuna: "Borascu" },
  { nume: "Brebenei", comuna: "Branesti" },
  { nume: "Badesti", comuna: "Branesti" },
  { nume: "Capu Dealului", comuna: "Branesti" },
  { nume: "Gilortu", comuna: "Branesti" },
  { nume: "Parau", comuna: "Branesti" },
  { nume: "Curtisoara", comuna: "Bumbesti-Jiu" },
  { nume: "Lazaresti", comuna: "Bumbesti-Jiu" },
  { nume: "Plesa", comuna: "Bumbesti-Jiu" },
  { nume: "Tetila", comuna: "Bumbesti-Jiu" },
  { nume: "Carligei", comuna: "Bumbesti-Pitic" },
  { nume: "Poienari", comuna: "Bumbesti-Pitic" },
  { nume: "Cionti", comuna: "Bustuchin" },
  { nume: "Motorgi", comuna: "Bustuchin" },
  { nume: "Namete", comuna: "Bustuchin" },
  { nume: "Poiana Seciuri", comuna: "Bustuchin" },
  { nume: "Poienita", comuna: "Bustuchin" },
  { nume: "Pojaru", comuna: "Bustuchin" },
  { nume: "Valea Pojarului", comuna: "Bustuchin" },
  { nume: "Calnicu de Sus", comuna: "Calnic" },
  { nume: "Didilesti", comuna: "Calnic" },
  { nume: "Galesoaia", comuna: "Calnic" },
  { nume: "Hodoreasca", comuna: "Calnic" },
  { nume: "Pieptani", comuna: "Calnic" },
  { nume: "Pinoasa", comuna: "Calnic" },
  { nume: "Stejerei", comuna: "Calnic" },
  { nume: "Valceaua", comuna: "Calnic" },
  { nume: "Alunis", comuna: "Capreni" },
  { nume: "Bratesti", comuna: "Capreni" },
  { nume: "Bulbuceni", comuna: "Capreni" },
  { nume: "Cetatea", comuna: "Capreni" },
  { nume: "Cornetu", comuna: "Capreni" },
  { nume: "Dealu Spirei", comuna: "Capreni" },
  { nume: "Satu Nou", comuna: "Capreni" },
  { nume: "Dealu Viilor", comuna: "Catunele" },
  { nume: "Lupoaia", comuna: "Catunele" },
  { nume: "Steic", comuna: "Catunele" },
  { nume: "Valea Manastirii", comuna: "Catunele" },
  { nume: "Valea Perilor", comuna: "Catunele" },
  { nume: "Boboiesti", comuna: "Ciuperceni" },
  { nume: "Pesteana Vulcan", comuna: "Ciuperceni" },
  { nume: "Priporu", comuna: "Ciuperceni" },
  { nume: "Stramba Vulcan", comuna: "Ciuperceni" },
  { nume: "Vartopu", comuna: "Ciuperceni" },
  { nume: "Zorzila", comuna: "Ciuperceni" },
  { nume: "Aninisu din Deal", comuna: "Crasna" },
  { nume: "Aninisu din Vale", comuna: "Crasna" },
  { nume: "Buzesti", comuna: "Crasna" },
  { nume: "Crasna din Deal", comuna: "Crasna" },
  { nume: "Carpinis", comuna: "Crasna" },
  { nume: "Dragoiesti", comuna: "Crasna" },
  { nume: "Dumbraveni", comuna: "Crasna" },
  { nume: "Radosi", comuna: "Crasna" },
  { nume: "Bojinu", comuna: "Cruset" },
  { nume: "Marinesti", comuna: "Cruset" },
  { nume: "Mierea", comuna: "Cruset" },
  { nume: "Miericeaua", comuna: "Cruset" },
  { nume: "Maiag", comuna: "Cruset" },
  { nume: "Slamnesti", comuna: "Cruset" },
  { nume: "Slavuta", comuna: "Cruset" },
  { nume: "Urda de Jos", comuna: "Cruset" },
  { nume: "Valuta", comuna: "Cruset" },
  { nume: "Bibulesti", comuna: "Danciulesti" },
  { nume: "Halangesti", comuna: "Danciulesti" },
  { nume: "Obarsia", comuna: "Danciulesti" },
  { nume: "Petrachei", comuna: "Danciulesti" },
  { nume: "Radinesti", comuna: "Danciulesti" },
  { nume: "Zaicoiu", comuna: "Danciulesti" },
  { nume: "Barza", comuna: "Danesti" },
  { nume: "Botorogi", comuna: "Danesti" },
  { nume: "Bratuia", comuna: "Danesti" },
  { nume: "Bucureasa", comuna: "Danesti" },
  { nume: "Merfulesti", comuna: "Danesti" },
  { nume: "Trocani", comuna: "Danesti" },
  { nume: "Ungureni", comuna: "Danesti" },
  { nume: "Vacarea", comuna: "Danesti" },
  { nume: "Sasa", comuna: "Danesti" },
  { nume: "Tarculesti", comuna: "Danesti" },
  { nume: "Corobai", comuna: "Dragotesti" },
  { nume: "Trestioara", comuna: "Dragotesti" },
  { nume: "Carbesti", comuna: "Dragutesti" },
  { nume: "Dambova", comuna: "Dragutesti" },
  { nume: "Iasi-Gorj", comuna: "Dragutesti" },
  { nume: "Talvesti", comuna: "Dragutesti" },
  { nume: "Urechesti", comuna: "Dragutesti" },
  { nume: "Farcasesti Mosneni", comuna: "Farcasesti" },
  { nume: "Pesteana de Jos", comuna: "Farcasesti" },
  { nume: "Rogojel", comuna: "Farcasesti" },
  { nume: "Rosia Jiu", comuna: "Farcasesti" },
  { nume: "Timiseni", comuna: "Farcasesti" },
  { nume: "Valea cu Apa", comuna: "Farcasesti" },
  { nume: "Clesnesti", comuna: "Glogova" },
  { nume: "Camuiesti", comuna: "Glogova" },
  { nume: "Iormanesti", comuna: "Glogova" },
  { nume: "Olteanu", comuna: "Glogova" },
  { nume: "Arjoci", comuna: "Godinesti" },
  { nume: "Chiliu", comuna: "Godinesti" },
  { nume: "Calcesti", comuna: "Godinesti" },
  { nume: "Parau de Pripor", comuna: "Godinesti" },
  { nume: "Parau de Vale", comuna: "Godinesti" },
  { nume: "Ratez", comuna: "Godinesti" },
  { nume: "Busuioci", comuna: "Hurezani" },
  { nume: "Pegeni", comuna: "Hurezani" },
  { nume: "Plopu", comuna: "Hurezani" },
  { nume: "Totea de Hurezani", comuna: "Hurezani" },
  { nume: "Gura Susitei", comuna: "Ionesti" },
  { nume: "Iliesti", comuna: "Ionesti" },
  { nume: "Picu", comuna: "Ionesti" },
  { nume: "Boia", comuna: "Jupanesti" },
  { nume: "Parau Boia", comuna: "Jupanesti" },
  { nume: "Vidin", comuna: "Jupanesti" },
  { nume: "Viersani", comuna: "Jupanesti" },
  { nume: "Fratesti", comuna: "Lelesti" },
  { nume: "Rasovita", comuna: "Lelesti" },
  { nume: "Frumusei", comuna: "Licurici" },
  { nume: "Negreni", comuna: "Licurici" },
  { nume: "Totea", comuna: "Licurici" },
  { nume: "Coltesti", comuna: "Logresti" },
  { nume: "Frunza", comuna: "Logresti" },
  { nume: "Logresti Mosteni", comuna: "Logresti" },
  { nume: "Maru", comuna: "Logresti" },
  { nume: "Popesti", comuna: "Logresti" },
  { nume: "Seaca", comuna: "Logresti" },
  { nume: "Targu Logresti", comuna: "Logresti" },
  { nume: "Bradet", comuna: "Matasari" },
  { nume: "Bradetel", comuna: "Matasari" },
  { nume: "Croici", comuna: "Matasari" },
  { nume: "Runcurel", comuna: "Matasari" },
  { nume: "Dealu Pomilor", comuna: "Motru" },
  { nume: "Horasti", comuna: "Motru" },
  { nume: "Leurda", comuna: "Motru" },
  { nume: "Lupoita", comuna: "Motru" },
  { nume: "Plostina", comuna: "Motru" },
  { nume: "Rosiuta", comuna: "Motru" },
  { nume: "Rapa", comuna: "Motru" },
  { nume: "Insuratei", comuna: "Motru" },
  { nume: "Arseni", comuna: "Musetesti" },
  { nume: "Barcaciu", comuna: "Musetesti" },
  { nume: "Grui", comuna: "Musetesti" },
  { nume: "Gamani", comuna: "Musetesti" },
  { nume: "Stancesti", comuna: "Musetesti" },
  { nume: "Stancesti Larga", comuna: "Musetesti" },
  { nume: "Artanu", comuna: "Negomir" },
  { nume: "Bohorel", comuna: "Negomir" },
  { nume: "Condeiesti", comuna: "Negomir" },
  { nume: "Nucetu", comuna: "Negomir" },
  { nume: "Orzu", comuna: "Negomir" },
  { nume: "Paltinu", comuna: "Negomir" },
  { nume: "Raci", comuna: "Negomir" },
  { nume: "Ursoaia", comuna: "Negomir" },
  { nume: "Valea Racilor", comuna: "Negomir" },
  { nume: "Bercesti", comuna: "Novaci" },
  { nume: "Hirisesti", comuna: "Novaci" },
  { nume: "Pociovalistea", comuna: "Novaci" },
  { nume: "Sitesti", comuna: "Novaci" },
  { nume: "Apa Neagra", comuna: "Pades" },
  { nume: "Cerna-Sat", comuna: "Pades" },
  { nume: "Closani", comuna: "Pades" },
  { nume: "Calugareni", comuna: "Pades" },
  { nume: "Motru Sec", comuna: "Pades" },
  { nume: "Orzesti", comuna: "Pades" },
  { nume: "Vaieni", comuna: "Pades" },
  { nume: "Borosteni", comuna: "Pestisani" },
  { nume: "Bradiceni", comuna: "Pestisani" },
  { nume: "Francesti", comuna: "Pestisani" },
  { nume: "Gureni", comuna: "Pestisani" },
  { nume: "Hobita", comuna: "Pestisani" },
  { nume: "Seuca", comuna: "Pestisani" },
  { nume: "Brosteni", comuna: "Plopsoru" },
  { nume: "Brostenii de Sus", comuna: "Plopsoru" },
  { nume: "Ceplea", comuna: "Plopsoru" },
  { nume: "Cursaru", comuna: "Plopsoru" },
  { nume: "Deleni", comuna: "Plopsoru" },
  { nume: "Izvoarele", comuna: "Plopsoru" },
  { nume: "Olari", comuna: "Plopsoru" },
  { nume: "Piscuri", comuna: "Plopsoru" },
  { nume: "Sardanesti", comuna: "Plopsoru" },
  { nume: "Valeni", comuna: "Plopsoru" },
  { nume: "Racovita", comuna: "Polovragi" },
  { nume: "Bucsana", comuna: "Prigoria" },
  { nume: "Burlani", comuna: "Prigoria" },
  { nume: "Calugareasa", comuna: "Prigoria" },
  { nume: "Dobrana", comuna: "Prigoria" },
  { nume: "Negoiesti", comuna: "Prigoria" },
  { nume: "Zorlesti", comuna: "Prigoria" },
  { nume: "Becheni", comuna: "Rosia De Amaradia" },
  { nume: "Dealu Viei", comuna: "Rosia De Amaradia" },
  { nume: "Ruget", comuna: "Rosia De Amaradia" },
  { nume: "Seciurile", comuna: "Rosia De Amaradia" },
  { nume: "Stejaru", comuna: "Rosia De Amaradia" },
  { nume: "Sitoaia", comuna: "Rosia De Amaradia" },
  { nume: "Vart", comuna: "Rovinari" },
  { nume: "Balta", comuna: "Runcu" },
  { nume: "Baltisoara", comuna: "Runcu" },
  { nume: "Dobrita", comuna: "Runcu" },
  { nume: "Rachiti", comuna: "Runcu" },
  { nume: "Suseni", comuna: "Runcu" },
  { nume: "Valea Mare", comuna: "Runcu" },
  { nume: "Blahnita de Sus", comuna: "Sacelu" },
  { nume: "Haiesti", comuna: "Sacelu" },
  { nume: "Jeristea", comuna: "Sacelu" },
  { nume: "Magheresti", comuna: "Sacelu" },
  { nume: "Boca", comuna: "Samarinesti" },
  { nume: "Bazavani", comuna: "Samarinesti" },
  { nume: "Duculesti", comuna: "Samarinesti" },
  { nume: "Larga", comuna: "Samarinesti" },
  { nume: "Valea Bisericii", comuna: "Samarinesti" },
  { nume: "Valea Mica", comuna: "Samarinesti" },
  { nume: "Valea Poienii", comuna: "Samarinesti" },
  { nume: "Tirioi", comuna: "Samarinesti" },
  { nume: "Bibesti", comuna: "Saulesti" },
  { nume: "Dolcesti", comuna: "Saulesti" },
  { nume: "Purcaru", comuna: "Saulesti" },
  { nume: "Arsuri", comuna: "Schela" },
  { nume: "Gornacel", comuna: "Schela" },
  { nume: "Pajistele", comuna: "Schela" },
  { nume: "Sambotin", comuna: "Schela" },
  { nume: "Bobu", comuna: "Scoarta" },
  { nume: "Budieni", comuna: "Scoarta" },
  { nume: "Ceratu de Copacioasa", comuna: "Scoarta" },
  { nume: "Colibasi", comuna: "Scoarta" },
  { nume: "Copacioasa", comuna: "Scoarta" },
  { nume: "Campu Mare", comuna: "Scoarta" },
  { nume: "Lazuri", comuna: "Scoarta" },
  { nume: "Lintea", comuna: "Scoarta" },
  { nume: "Mogosani", comuna: "Scoarta" },
  { nume: "Pistestii din Deal", comuna: "Scoarta" },
  { nume: "Cojmanesti", comuna: "Slivilesti" },
  { nume: "Miculesti", comuna: "Slivilesti" },
  { nume: "Stramtu", comuna: "Slivilesti" },
  { nume: "Sura", comuna: "Slivilesti" },
  { nume: "Tehomir", comuna: "Slivilesti" },
  { nume: "Siacu", comuna: "Slivilesti" },
  { nume: "Stiucani", comuna: "Slivilesti" },
  { nume: "Alexeni", comuna: "Stanesti" },
  { nume: "Balani", comuna: "Stanesti" },
  { nume: "Curpen", comuna: "Stanesti" },
  { nume: "Calesti", comuna: "Stanesti" },
  { nume: "Mazaroi", comuna: "Stanesti" },
  { nume: "Obreja", comuna: "Stanesti" },
  { nume: "Parvulesti", comuna: "Stanesti" },
  { nume: "Vaidei", comuna: "Stanesti" },
  { nume: "Valari", comuna: "Stanesti" },
  { nume: "Balosani", comuna: "Stejari" },
  { nume: "Bacesti", comuna: "Stejari" },
  { nume: "Dealu Leului", comuna: "Stejari" },
  { nume: "Piscoiu", comuna: "Stejari" },
  { nume: "Popesti Stejari", comuna: "Stejari" },
  { nume: "Ciorari", comuna: "Stoina" },
  { nume: "Mielusei", comuna: "Stoina" },
  { nume: "Paisani", comuna: "Stoina" },
  { nume: "Toiaga", comuna: "Stoina" },
  { nume: "Ulmet", comuna: "Stoina" },
  { nume: "Urda de Sus", comuna: "Stoina" },
  { nume: "Arpadia", comuna: "Tantareni" },
  { nume: "Chiciora", comuna: "Tantareni" },
  { nume: "Floresti", comuna: "Tantareni" },
  { nume: "Barsesti", comuna: "Targu Jiu" },
  { nume: "Dragoeni", comuna: "Targu Jiu" },
  { nume: "Iezureni", comuna: "Targu Jiu" },
  { nume: "Polata", comuna: "Targu Jiu" },
  { nume: "Preajba Mare", comuna: "Targu Jiu" },
  { nume: "Romanesti", comuna: "Targu Jiu" },
  { nume: "Slobozia", comuna: "Targu Jiu" },
  { nume: "Ursati", comuna: "Targu Jiu" },
  { nume: "Buduhala", comuna: "Telesti" },
  { nume: "Somanesti", comuna: "Telesti" },
  { nume: "Blahnita de Jos", comuna: "Tirgu Carbunesti" },
  { nume: "Cojani", comuna: "Tirgu Carbunesti" },
  { nume: "Cretesti", comuna: "Tirgu Carbunesti" },
  { nume: "Curteana", comuna: "Tirgu Carbunesti" },
  { nume: "Carbunesti-Sat", comuna: "Tirgu Carbunesti" },
  { nume: "Floresteni", comuna: "Tirgu Carbunesti" },
  { nume: "Macesu", comuna: "Tirgu Carbunesti" },
  { nume: "Pojogeni", comuna: "Tirgu Carbunesti" },
  { nume: "Rogojeni", comuna: "Tirgu Carbunesti" },
  { nume: "Targu Carbunesti", comuna: "Tirgu Carbunesti" },
  { nume: "Stefanesti", comuna: "Tirgu Carbunesti" },
  { nume: "Celei", comuna: "Tismana" },
  { nume: "Costeni", comuna: "Tismana" },
  { nume: "Gornovita", comuna: "Tismana" },
  { nume: "Isvarna", comuna: "Tismana" },
  { nume: "Pocruia", comuna: "Tismana" },
  { nume: "Racoti", comuna: "Tismana" },
  { nume: "Sohodol", comuna: "Tismana" },
  { nume: "Topesti", comuna: "Tismana" },
  { nume: "Valcele", comuna: "Tismana" },
  { nume: "Vanata", comuna: "Tismana" },
  { nume: "Cocorova", comuna: "Turburea" },
  { nume: "Poiana", comuna: "Turburea" },
  { nume: "Spahii", comuna: "Turburea" },
  { nume: "Sipotu", comuna: "Turburea" },
  { nume: "Garbovu", comuna: "Turceni" },
  { nume: "Jiltu", comuna: "Turceni" },
  { nume: "Murgesti", comuna: "Turceni" },
  { nume: "Stramba Jiu", comuna: "Turceni" },
  { nume: "Valea Viei", comuna: "Turceni" },
  { nume: "Cartiu", comuna: "Turcinesti" },
  { nume: "Horezu", comuna: "Turcinesti" },
  { nume: "Rugi", comuna: "Turcinesti" },
  { nume: "Fantanele", comuna: "Urdari" },
  { nume: "Hotaroasa", comuna: "Urdari" },
  { nume: "Covrigi", comuna: "Vagiulesti" },
  { nume: "Carciu", comuna: "Vagiulesti" },
  { nume: "Murgilesti", comuna: "Vagiulesti" },
  { nume: "Valea Motrului", comuna: "Vagiulesti" },
  { nume: "Andreesti", comuna: "Vladimir" },
  { nume: "Frasin", comuna: "Vladimir" },
  { nume: "Valea Desului", comuna: "Vladimir" },
];
