export const hr = [
  { nume: "Aldea", comuna: "Martinis" },
  { nume: "Alexandrița", simplu: "Alexandrita", comuna: "Felicieni" },
  { nume: "Aluniș", simplu: "Alunis", comuna: "Mugeni" },
  { nume: "Andreeni", comuna: "Avramesti" },
  { nume: "Armășeni", simplu: "Armaseni", comuna: "Ciucsangeorgiu" },
  { nume: "Armășenii Noi", simplu: "Armasenii Noi", comuna: "Ciucsangeorgiu" },
  { nume: "Arvățeni", simplu: "Arvateni", comuna: "Felicieni" },
  { nume: "Atia", comuna: "Corund" },
  { nume: "Atid" },
  { nume: "Avrămești", simplu: "Avramesti" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Martinis" },
  { nume: "Băile Chirui", simplu: "Baile Chirui", comuna: "Lueta" },
  { nume: "Băile Homorod", simplu: "Baile Homorod", comuna: "Vlahita" },
  { nume: "Băile Tușnad", simplu: "Baile Tusnad" },
  { nume: "Bălan", simplu: "Balan" },
  { nume: "Bancu", comuna: "Ciucsangeorgiu" },
  { nume: "Barațcoș", simplu: "Baratcos", comuna: "Lunca De Jos" },
  { nume: "Bârzava", simplu: "Barzava", comuna: "Frumoasa" },
  { nume: "Becaș", simplu: "Becas", comuna: "Praid" },
  { nume: "Bențid", simplu: "Bentid", comuna: "Simonesti" },
  { nume: "Beta", comuna: "Mugeni" },
  { nume: "Betești", simplu: "Betesti", comuna: "Mugeni" },
  { nume: "Bilbor" },
  { nume: "Bisericani", comuna: "Lupeni" },
  { nume: "Bodogaia", comuna: "Secuieni" },
  { nume: "Borsec" },
  { nume: "Borzont", comuna: "Joseni" },
  { nume: "Brădești", simplu: "Bradesti" },
  { nume: "Bucin", comuna: "Joseni" },
  { nume: "Bucin", comuna: "Praid" },
  { nume: "Bulgăreni", simplu: "Bulgareni", comuna: "Lupeni" },
  { nume: "Cădaciu Mare", simplu: "Cadaciu Mare", comuna: "Simonesti" },
  { nume: "Cădaciu Mic", simplu: "Cadaciu Mic", comuna: "Simonesti" },
  { nume: "Călimănel", simplu: "Calimanel", comuna: "Toplita" },
  { nume: "Călnaci", simplu: "Calnaci", comuna: "Subcetate" },
  { nume: "Calonda", comuna: "Corund" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Martinis" },
  { nume: "Căpâlnița", simplu: "Capalnita" },
  { nume: "Capu Corbului", comuna: "Corbu" },
  { nume: "Carpitus", comuna: "Baile Tusnad" },
  { nume: "Cârța", simplu: "Carta" },
  { nume: "Casinu Nou", comuna: "Plaiesii De Jos" },
  { nume: "Cechești", simplu: "Cechesti", comuna: "Avramesti" },
  { nume: "Cehețel", simplu: "Cehetel", comuna: "Simonesti" },
  { nume: "Cetățuia", simplu: "Cetatuia", comuna: "Sansimion" },
  { nume: "Chedia Mare", comuna: "Simonesti" },
  { nume: "Chedia Mică", simplu: "Chedia Mica", comuna: "Simonesti" },
  { nume: "Chileni", comuna: "Suseni" },
  { nume: "Chinușu", simplu: "Chinusu", comuna: "Martinis" },
  { nume: "Ciaracio", comuna: "Siculeni" },
  { nume: "Ciba", comuna: "Miercurea Ciuc" },
  { nume: "Ciceu", comuna: "Siculeni" },
  { nume: "Ciobăniș", simplu: "Ciobanis", comuna: "Ciucsangeorgiu" },
  { nume: "Cireșeni", simplu: "Cireseni", comuna: "Felicieni" },
  { nume: "Ciucani", comuna: "Sanmartin" },
  { nume: "Ciucsângeorgiu", simplu: "Ciucsangeorgiu" },
  { nume: "Ciumani" },
  { nume: "Cobătești", simplu: "Cobatesti", comuna: "Simonesti" },
  { nume: "Comănești", simplu: "Comanesti", comuna: "Martinis" },
  { nume: "Comiat", comuna: "Lunca De Sus" },
  { nume: "Corbu" },
  { nume: "Corund" },
  { nume: "Cotormani", comuna: "Ciucsangeorgiu" },
  { nume: "Covacipeter", comuna: "Gheorgheni" },
  { nume: "Cozmeni" },
  { nume: "Crăciunel", simplu: "Craciunel", comuna: "Ocland" },
  { nume: "Crișeni", simplu: "Criseni", comuna: "Atid" },
  { nume: "Cristuru Secuiesc" },
  { nume: "Cușmed", simplu: "Cusmed", comuna: "Atid" },
  { nume: "Daia", comuna: "Ulies" },
  { nume: "Dănești", simplu: "Danesti" },
  { nume: "Dârjiu", simplu: "Darjiu" },
  { nume: "Dealu Armanului", comuna: "Galautas" },
  { nume: "Dealu" },
  { nume: "Dejuțiu", simplu: "Dejutiu", comuna: "Mugeni" },
  { nume: "Delnița", simplu: "Delnita", comuna: "Pauleni-Ciuc" },
  { nume: "Desag", comuna: "Zetea" },
  { nume: "Ditrău", simplu: "Ditrau" },
  { nume: "Dobeni", comuna: "Mugeni" },
  { nume: "Duda", comuna: "Subcetate" },
  { nume: "Eghersec", comuna: "Ciucsangeorgiu" },
  { nume: "Eliseni", comuna: "Secuieni" },
  { nume: "Făgețel", simplu: "Fagetel", comuna: "Frumoasa" },
  { nume: "Făgețel", simplu: "Fagetel", comuna: "Remetea" },
  { nume: "Fâncel", simplu: "Fancel", comuna: "Dealu" },
  { nume: "Fântâna Brazilor", simplu: "Fantana Brazilor", comuna: "Corund" },
  { nume: "Feliceni", comuna: "Felicieni" },
  { nume: "Filiaș", simplu: "Filias", comuna: "Cristuru Secuiesc" },
  { nume: "Filpea", comuna: "Subcetate" },
  { nume: "Firtănuș", simplu: "Firtanus", comuna: "Avramesti" },
  { nume: "Firtușu", simplu: "Firtusu", comuna: "Lupeni" },
  { nume: "Fitod", comuna: "Sancraieni" },
  { nume: "Forțeni", simplu: "Forteni", comuna: "Felicieni" },
  { nume: "Frumoasa" },
  { nume: "Fundoaia", comuna: "Sarmas" },
  { nume: "Gălăuțaș-Pârău", simplu: "Galautas-Parau", comuna: "Galautas" },
  { nume: "Gălăuțaș", simplu: "Galautas" },
  { nume: "Gheorgheni" },
  { nume: "Ghiduț", simplu: "Ghidut", comuna: "Lazarea" },
  { nume: "Ghipeș", simplu: "Ghipes", comuna: "Martinis" },
  { nume: "Ghiurche", comuna: "Ciucsangeorgiu" },
  { nume: "Goagiu", comuna: "Avramesti" },
  { nume: "Hagota", comuna: "Tulghes" },
  { nume: "Harghita-Băi", simplu: "Harghita-Bai", comuna: "Miercurea Ciuc" },
  { nume: "Hodoșa", simplu: "Hodosa", comuna: "Sarmas" },
  { nume: "Hoghia", comuna: "Felicieni" },
  { nume: "Hosasău", simplu: "Hosasau", comuna: "Sancraieni" },
  { nume: "Iacobeni", comuna: "Plaiesii De Jos" },
  { nume: "Iașu", simplu: "Iasu", comuna: "Ulies" },
  { nume: "Ighiu", comuna: "Ulies" },
  { nume: "Imper", comuna: "Plaiesii De Jos" },
  { nume: "Ineu", comuna: "Carta" },
  { nume: "Inlăceni", simplu: "Inlaceni", comuna: "Atid" },
  { nume: "Izvoare", comuna: "Zetea" },
  { nume: "Izvoru Mureșului", simplu: "Izvoru Muresului", comuna: "Voslabeni" },
  {
    nume: "Izvorul Trotușului",
    simplu: "Izvorul Trotusului",
    comuna: "Lunca De Sus",
  },
  { nume: "Jigodin-Băi", simplu: "Jigodin-Bai", comuna: "Miercurea Ciuc" },
  { nume: "Jolotca", comuna: "Ditrau" },
  { nume: "Joseni" },
  { nume: "Lacu Roșu", simplu: "Lacu Rosu", comuna: "Gheorgheni" },
  { nume: "Laz-Firtănuș", simplu: "Laz-Firtanus", comuna: "Avramesti" },
  { nume: "Laz-Șoimuș", simplu: "Laz-Soimus", comuna: "Avramesti" },
  { nume: "Lăzarea", simplu: "Lazarea" },
  { nume: "Lăzărești", simplu: "Lazaresti", comuna: "Cozmeni" },
  { nume: "Leliceni", comuna: "Sancraieni" },
  { nume: "Liban", comuna: "Suseni" },
  { nume: "Livezi", comuna: "Mihaileni" },
  { nume: "Locodeni", comuna: "Martinis" },
  { nume: "Lueta" },
  { nume: "Lunca de Jos" },
  { nume: "Lunca de Sus" },
  { nume: "Luncani", comuna: "Toplita" },
  { nume: "Lupeni" },
  { nume: "Lutița", simplu: "Lutita", comuna: "Mugeni" },
  { nume: "Mădăraș", simplu: "Madaras" },
  { nume: "Măgheruș", simplu: "Magherus", comuna: "Toplita" },
  { nume: "Mărtiniș", simplu: "Martinis" },
  { nume: "Martonca", comuna: "Remetea" },
  { nume: "Mătișeni", simplu: "Matiseni", comuna: "Mugeni" },
  { nume: "Medișoru Mare", simplu: "Medisoru Mare", comuna: "Simonesti" },
  { nume: "Medișoru Mic", simplu: "Medisoru Mic", comuna: "Avramesti" },
  { nume: "Merești", simplu: "Meresti" },
  { nume: "Miercurea Ciuc" },
  { nume: "Mihăileni", simplu: "Mihaileni" },
  { nume: "Mihăileni", simplu: "Mihaileni", comuna: "Simonesti" },
  { nume: "Minele Lueta", comuna: "Vlahita" },
  { nume: "Misentea", comuna: "Sancraieni" },
  { nume: "Moglănești", simplu: "Moglanesti", comuna: "Toplita" },
  { nume: "Morăreni", simplu: "Morareni", comuna: "Lupeni" },
  { nume: "Mugeni" },
  { nume: "Mujna", comuna: "Darjiu" },
  { nume: "Nădejdea", simplu: "Nadejdea", comuna: "Mihaileni" },
  { nume: "Nicoleni", comuna: "Simonesti" },
  { nume: "Nicolești", simplu: "Nicolesti", comuna: "Frumoasa" },
  { nume: "Nicolești", simplu: "Nicolesti", comuna: "Ulies" },
  { nume: "Nuțeni", simplu: "Nuteni", comuna: "Galautas" },
  { nume: "Obrănești", simplu: "Obranesti", comuna: "Ulies" },
  { nume: "Ocland" },
  { nume: "Ocna de Jos", comuna: "Praid" },
  { nume: "Ocna de Sus", comuna: "Praid" },
  { nume: "Odorheiu Secuiesc" },
  { nume: "Orășeni", simplu: "Oraseni", comuna: "Martinis" },
  { nume: "Oțeni", simplu: "Oteni", comuna: "Felicieni" },
  { nume: "Păltiniș-Ciuc", simplu: "Paltinis-Ciuc", comuna: "Lunca De Sus" },
  { nume: "Păltiniș", simplu: "Paltinis", comuna: "Lupeni" },
  { nume: "Păuleni-Ciuc", simplu: "Pauleni-Ciuc" },
  { nume: "Păuleni", simplu: "Pauleni", comuna: "Lupeni" },
  { nume: "Petecu", comuna: "Ulies" },
  { nume: "Petreni", comuna: "Martinis" },
  { nume: "Pintic", comuna: "Tulghes" },
  { nume: "Plăieșii de Jos", simplu: "Plaiesii de Jos" },
  {
    nume: "Plăieșii de Sus",
    simplu: "Plaiesii de Sus",
    comuna: "Plaiesii De Jos",
  },
  { nume: "Platonești", simplu: "Platonesti", comuna: "Sarmas" },
  { nume: "Plopiș", simplu: "Plopis", comuna: "Galautas" },
  { nume: "Poiana Fagului", comuna: "Lunca De Jos" },
  { nume: "Poiana Târnavei", simplu: "Poiana Tarnavei", comuna: "Zetea" },
  { nume: "Polonița", simplu: "Polonita", comuna: "Felicieni" },
  { nume: "Porumbenii Mari", comuna: "Mugeni" },
  { nume: "Porumbenii Mici", comuna: "Mugeni" },
  { nume: "Potiond", comuna: "Ciucsangeorgiu" },
  { nume: "Praid" },
  { nume: "Preluca", comuna: "Galautas" },
  { nume: "Puntea Lupului", comuna: "Lunca De Jos" },
  { nume: "Răchitiș", simplu: "Rachitis", comuna: "Bilbor" },
  { nume: "Racu", comuna: "Siculeni" },
  { nume: "Rareș", simplu: "Rares", comuna: "Martinis" },
  { nume: "Recea", comuna: "Tulghes" },
  { nume: "Remetea" },
  { nume: "Rugănești", simplu: "Ruganesti", comuna: "Simonesti" },
  { nume: "Runc", comuna: "Sarmas" },
  { nume: "Săcel", simplu: "Sacel" },
  { nume: "Sâncel", simplu: "Sancel", comuna: "Lupeni" },
  { nume: "Sâncrai", simplu: "Sancrai", comuna: "Dealu" },
  { nume: "Sâncrăieni", simplu: "Sancraieni" },
  { nume: "Sândominic", simplu: "Sandominic" },
  { nume: "Sânmartin", simplu: "Sanmartin" },
  { nume: "Sânpaul", simplu: "Sanpaul", comuna: "Martinis" },
  { nume: "Sânsimion", simplu: "Sansimion" },
  { nume: "Sântimbru-Băi", simplu: "Santimbru-Bai", comuna: "Sancraieni" },
  { nume: "Sântimbru", simplu: "Santimbru", comuna: "Sancraieni" },
  { nume: "Sărmaș", simplu: "Sarmas" },
  { nume: "Șașvereș", simplu: "Sasveres", comuna: "Praid" },
  { nume: "Satu Mare", comuna: "Bradesti" },
  { nume: "Satu Mic", comuna: "Lupeni" },
  { nume: "Satu Nou", comuna: "Ocland" },
  { nume: "Satu Nou", comuna: "Siculeni" },
  { nume: "Secu", comuna: "Toplita" },
  { nume: "Secuieni" },
  { nume: "Senetea", comuna: "Suseni" },
  { nume: "Șicasău", simplu: "Sicasau", comuna: "Zetea" },
  { nume: "Șiclod", simplu: "Siclod", comuna: "Atid" },
  { nume: "Siculeni" },
  { nume: "Șimonești", simplu: "Simonesti" },
  { nume: "Sineu", comuna: "Remetea" },
  { nume: "Șoimeni", simplu: "Soimeni", comuna: "Pauleni-Ciuc" },
  { nume: "Șoimușu Mare", simplu: "Soimusu Mare", comuna: "Sacel" },
  { nume: "Șoimușu Mic", simplu: "Soimusu Mic", comuna: "Sacel" },
  { nume: "Sub Cetate", comuna: "Zetea" },
  { nume: "Subcetate" },
  { nume: "Suseni" },
  { nume: "Tăietura", simplu: "Taietura", comuna: "Mugeni" },
  { nume: "Tămașu", simplu: "Tamasu", comuna: "Dealu" },
  { nume: "Tărcești", simplu: "Tarcesti", comuna: "Simonesti" },
  { nume: "Târnovița", simplu: "Tarnovita", comuna: "Bradesti" },
  { nume: "Tăureni", simplu: "Taureni", comuna: "Felicieni" },
  { nume: "Teleac", comuna: "Felicieni" },
  { nume: "Țengheler", simplu: "Tengheler", comuna: "Ditrau" },
  { nume: "Tibod", comuna: "Dealu" },
  { nume: "Toleșeni", simplu: "Toleseni", comuna: "Galautas" },
  { nume: "Tomești", simplu: "Tomesti" },
  { nume: "Toplița", simplu: "Toplita" },
  { nume: "Tulgheș", simplu: "Tulghes" },
  { nume: "Turdeni", comuna: "Simonesti" },
  { nume: "Tușnad", simplu: "Tusnad" },
  { nume: "Tușnadu Nou", simplu: "Tusnadu Nou", comuna: "Tusnad" },
  { nume: "Uilac", comuna: "Sacel" },
  { nume: "Ulcani", comuna: "Dealu" },
  { nume: "Ulieș", simplu: "Ulies" },
  { nume: "Văcărești", simplu: "Vacaresti", comuna: "Mihaileni" },
  { nume: "Vâgani", simplu: "Vagani", comuna: "Toplita" },
  { nume: "Vale", comuna: "Toplita" },
  { nume: "Valea Boroș", simplu: "Valea Boros", comuna: "Lunca De Jos" },
  { nume: "Valea Capelei", comuna: "Lunca De Jos" },
  { nume: "Valea Gârbea", simplu: "Valea Garbea", comuna: "Lunca De Sus" },
  {
    nume: "Valea Întunecoasă",
    simplu: "Valea Intunecoasa",
    comuna: "Lunca De Jos",
  },
  { nume: "Valea lui Antaloc", comuna: "Lunca De Jos" },
  { nume: "Valea lui Pavel", comuna: "Corund" },
  { nume: "Valea Rece", comuna: "Lunca De Jos" },
  { nume: "Valea Rotundă", simplu: "Valea Rotunda", comuna: "Dealu" },
  { nume: "Valea Strâmbă", simplu: "Valea Stramba", comuna: "Suseni" },
  { nume: "Valea Ugra", comuna: "Lunca De Sus" },
  { nume: "Valea Uzului", comuna: "Sanmartin" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Felicieni" },
  { nume: "Vargatac", comuna: "Gheorgheni" },
  { nume: "Vărșag", simplu: "Varsag" },
  { nume: "Vasileni", comuna: "Ulies" },
  { nume: "Vidacut", comuna: "Sacel" },
  { nume: "Visafolio", comuna: "Gheorgheni" },
  { nume: "Vlăhița", simplu: "Vlahita" },
  { nume: "Voșlăbeni", simplu: "Voslabeni" },
  { nume: "Vrabia", comuna: "Tusnad" },
  { nume: "Zăpodea", simplu: "Zapodea", comuna: "Galautas" },
  { nume: "Zencani", comuna: "Toplita" },
  { nume: "Zetea" },
];
