export const hd = [
  { nume: "Aninoasa" },
  { nume: "Baia de Cris" },
  { nume: "Balsa" },
  { nume: "Baru" },
  { nume: "Beriu" },
  { nume: "Blajeni" },
  { nume: "Bosorod" },
  { nume: "Brad" },
  { nume: "Bretea Romana" },
  { nume: "Branisca" },
  { nume: "Buces" },
  { nume: "Bucuresci" },
  { nume: "Bulzestii de Sus" },
  { nume: "Bunila" },
  { nume: "Burjuc" },
  { nume: "Bacia" },
  { nume: "Baita" },
  { nume: "Banita" },
  { nume: "Batrana" },
  { nume: "Cerbal" },
  { nume: "Certeju de Sus" },
  { nume: "Criscior" },
  { nume: "Carjiti" },
  { nume: "Calan" },
  { nume: "Densus" },
  { nume: "Deva" },
  { nume: "Dobra" },
  { nume: "General Berthelot" },
  { nume: "Geoagiu" },
  { nume: "Ghelari" },
  { nume: "Gurasada" },
  { nume: "Hateg" },
  { nume: "Hunedoara" },
  { nume: "Harau" },
  { nume: "Ilia" },
  { nume: "Lelese" },
  { nume: "Lunca Cernii de Jos" },
  { nume: "Luncoiu de Jos" },
  { nume: "Lupeni" },
  { nume: "Lapugiu de Jos" },
  { nume: "Martinesti" },
  { nume: "Orastie" },
  { nume: "Orastioara de Sus" },
  { nume: "Pestisu Mic" },
  { nume: "Petrila" },
  { nume: "Petrosani" },
  { nume: "Pui" },
  { nume: "Rapoltu Mare" },
  { nume: "Ribita" },
  { nume: "Romos" },
  { nume: "Rau de Mori" },
  { nume: "Rachitova" },
  { nume: "Sarmizegetusa" },
  { nume: "Simeria" },
  { nume: "Santamaria-Orlea" },
  { nume: "Salasu de Sus" },
  { nume: "Teliucu Inferior" },
  { nume: "Tomesti" },
  { nume: "Toplita" },
  { nume: "Totesti" },
  { nume: "Turdas" },
  { nume: "Uricani" },
  { nume: "Vata de Jos" },
  { nume: "Vetel" },
  { nume: "Vorta" },
  { nume: "Vulcan" },
  { nume: "Valisoara" },
  { nume: "Zam" },
  { nume: "Soimus" },
  { nume: "Iscroni", comuna: "Aninoasa" },
  { nume: "Petreni", comuna: "Bacia" },
  { nume: "Totia", comuna: "Bacia" },
  { nume: "Tampa", comuna: "Bacia" },
  { nume: "Baldovin", comuna: "Baia De Cris" },
  { nume: "Caraci", comuna: "Baia De Cris" },
  { nume: "Carastau", comuna: "Baia De Cris" },
  { nume: "Lunca", comuna: "Baia De Cris" },
  { nume: "Risca", comuna: "Baia De Cris" },
  { nume: "Risculita", comuna: "Baia De Cris" },
  { nume: "Valeni", comuna: "Baia De Cris" },
  { nume: "Tebea", comuna: "Baia De Cris" },
  { nume: "Barbura", comuna: "Baita" },
  { nume: "Craciunesti", comuna: "Baita" },
  { nume: "Cainelu de Sus", comuna: "Baita" },
  { nume: "Fizes", comuna: "Baita" },
  { nume: "Hartagani", comuna: "Baita" },
  { nume: "Lunca", comuna: "Baita" },
  { nume: "Ormindea", comuna: "Baita" },
  { nume: "Pestera", comuna: "Baita" },
  { nume: "Saliste", comuna: "Baita" },
  { nume: "Trestia", comuna: "Baita" },
  { nume: "Almasu Mic de Munte", comuna: "Balsa" },
  { nume: "Ardeu", comuna: "Balsa" },
  { nume: "Bunesti", comuna: "Balsa" },
  { nume: "Galbina", comuna: "Balsa" },
  { nume: "Mada", comuna: "Balsa" },
  { nume: "Oprisesti", comuna: "Balsa" },
  { nume: "Poiana", comuna: "Balsa" },
  { nume: "Poienita", comuna: "Balsa" },
  { nume: "Rosia", comuna: "Balsa" },
  { nume: "Stauini", comuna: "Balsa" },
  { nume: "Techereu", comuna: "Balsa" },
  { nume: "Voia", comuna: "Balsa" },
  { nume: "Valisoara", comuna: "Balsa" },
  { nume: "Crivadia", comuna: "Banita" },
  { nume: "Merisor", comuna: "Banita" },
  { nume: "Livadia", comuna: "Baru" },
  { nume: "Petros", comuna: "Baru" },
  { nume: "Valea Lupului", comuna: "Baru" },
  { nume: "Fata Rosie", comuna: "Batrana" },
  { nume: "Piatra", comuna: "Batrana" },
  { nume: "Rachitaua", comuna: "Batrana" },
  { nume: "Cucuis", comuna: "Beriu" },
  { nume: "Castau", comuna: "Beriu" },
  { nume: "Magureni", comuna: "Beriu" },
  { nume: "Orastioara de Jos", comuna: "Beriu" },
  { nume: "Poieni", comuna: "Beriu" },
  { nume: "Sereca", comuna: "Beriu" },
  { nume: "Sibisel", comuna: "Beriu" },
  { nume: "Blajeni-Vulcan", comuna: "Blajeni" },
  { nume: "Cris", comuna: "Blajeni" },
  { nume: "Dragu-Brad", comuna: "Blajeni" },
  { nume: "Grosuri", comuna: "Blajeni" },
  { nume: "Plai", comuna: "Blajeni" },
  { nume: "Ret", comuna: "Blajeni" },
  { nume: "Salatruc", comuna: "Blajeni" },
  { nume: "Alun", comuna: "Bosorod" },
  { nume: "Bobaia", comuna: "Bosorod" },
  { nume: "Chitid", comuna: "Bosorod" },
  { nume: "Cioclovina", comuna: "Bosorod" },
  { nume: "Luncani", comuna: "Bosorod" },
  { nume: "Prihodiste", comuna: "Bosorod" },
  { nume: "Tarsa", comuna: "Bosorod" },
  { nume: "Ursici", comuna: "Bosorod" },
  { nume: "Mesteacan", comuna: "Brad" },
  { nume: "Potingani", comuna: "Brad" },
  { nume: "Ruda-Brad", comuna: "Brad" },
  { nume: "Valea Bradului", comuna: "Brad" },
  { nume: "Taratel", comuna: "Brad" },
  { nume: "Boz", comuna: "Branisca" },
  { nume: "Barastii Iliei", comuna: "Branisca" },
  { nume: "Cabesti", comuna: "Branisca" },
  { nume: "Furcsoara", comuna: "Branisca" },
  { nume: "Gialacuta", comuna: "Branisca" },
  { nume: "Rovina", comuna: "Branisca" },
  { nume: "Tarnava", comuna: "Branisca" },
  { nume: "Tarnavita", comuna: "Branisca" },
  { nume: "Bercu", comuna: "Bretea Romana" },
  { nume: "Bretea Streiului", comuna: "Bretea Romana" },
  { nume: "Batalar", comuna: "Bretea Romana" },
  { nume: "Covragiu", comuna: "Bretea Romana" },
  { nume: "Gantaga", comuna: "Bretea Romana" },
  { nume: "Maceu", comuna: "Bretea Romana" },
  { nume: "Ocolisu Mare", comuna: "Bretea Romana" },
  { nume: "Plopi", comuna: "Bretea Romana" },
  { nume: "Rusi", comuna: "Bretea Romana" },
  { nume: "Valcele", comuna: "Bretea Romana" },
  { nume: "Valcelele Bune", comuna: "Bretea Romana" },
  { nume: "Valceluta", comuna: "Bretea Romana" },
  { nume: "Buces-Vulcan", comuna: "Buces" },
  { nume: "Dupapiatra", comuna: "Buces" },
  { nume: "Grohotele", comuna: "Buces" },
  { nume: "Mihaileni", comuna: "Buces" },
  { nume: "Stanija", comuna: "Buces" },
  { nume: "Tarnita", comuna: "Buces" },
  { nume: "Curechiu", comuna: "Bucuresci" },
  { nume: "Merisor", comuna: "Bucuresci" },
  { nume: "Rovina", comuna: "Bucuresci" },
  { nume: "Sesuri", comuna: "Bucuresci" },
  { nume: "Bulzestii de Jos", comuna: "Bulzestii De Sus" },
  { nume: "Giurgesti", comuna: "Bulzestii De Sus" },
  { nume: "Grohot", comuna: "Bulzestii De Sus" },
  { nume: "Paulesti", comuna: "Bulzestii De Sus" },
  { nume: "Rusesti", comuna: "Bulzestii De Sus" },
  { nume: "Stanculesti", comuna: "Bulzestii De Sus" },
  { nume: "Ticera", comuna: "Bulzestii De Sus" },
  { nume: "Tomnatec", comuna: "Bulzestii De Sus" },
  { nume: "Alun", comuna: "Bunila" },
  { nume: "Cernisoara Florese", comuna: "Bunila" },
  { nume: "Poienita Voinii", comuna: "Bunila" },
  { nume: "Vadu Dobrii", comuna: "Bunila" },
  { nume: "Bradatel", comuna: "Burjuc" },
  { nume: "Glodghilesti", comuna: "Burjuc" },
  { nume: "Petresti", comuna: "Burjuc" },
  { nume: "Tisa", comuna: "Burjuc" },
  { nume: "Tatarasti", comuna: "Burjuc" },
  { nume: "Batiz", comuna: "Calan" },
  { nume: "Calanu Mic", comuna: "Calan" },
  { nume: "Grid", comuna: "Calan" },
  { nume: "Nadastia de Jos", comuna: "Calan" },
  { nume: "Nadastia de Sus", comuna: "Calan" },
  { nume: "Ohaba Streiului", comuna: "Calan" },
  { nume: "Strei", comuna: "Calan" },
  { nume: "Strei-Sacel", comuna: "Calan" },
  { nume: "Streisangeorgiu", comuna: "Calan" },
  { nume: "Sancrai", comuna: "Calan" },
  { nume: "Santamaria de Piatra", comuna: "Calan" },
  { nume: "Valea Sangeorgiului", comuna: "Calan" },
  { nume: "Almasu Sec", comuna: "Carjiti" },
  { nume: "Cherghes", comuna: "Carjiti" },
  { nume: "Cozia", comuna: "Carjiti" },
  { nume: "Popesti", comuna: "Carjiti" },
  { nume: "Aranies", comuna: "Cerbal" },
  { nume: "Feregi", comuna: "Cerbal" },
  { nume: "Merisoru de Munte", comuna: "Cerbal" },
  { nume: "Poiana Rachitelii", comuna: "Cerbal" },
  { nume: "Poienita Tomii", comuna: "Cerbal" },
  { nume: "Socet", comuna: "Cerbal" },
  { nume: "Ulm", comuna: "Cerbal" },
  { nume: "Bocsa Mare", comuna: "Certeju De Sus" },
  { nume: "Bocsa Mica", comuna: "Certeju De Sus" },
  { nume: "Hondol", comuna: "Certeju De Sus" },
  { nume: "Magura-Toplita", comuna: "Certeju De Sus" },
  { nume: "Nojag", comuna: "Certeju De Sus" },
  { nume: "Sacaramb", comuna: "Certeju De Sus" },
  { nume: "Toplita Muresului", comuna: "Certeju De Sus" },
  { nume: "Varmaga", comuna: "Certeju De Sus" },
  { nume: "Barza", comuna: "Criscior" },
  { nume: "Valea Arsului", comuna: "Criscior" },
  { nume: "Zdrapti", comuna: "Criscior" },
  { nume: "Criva", comuna: "Densus" },
  { nume: "Hatagel", comuna: "Densus" },
  { nume: "Pesteana", comuna: "Densus" },
  { nume: "Pestenita", comuna: "Densus" },
  { nume: "Poieni", comuna: "Densus" },
  { nume: "Stei", comuna: "Densus" },
  { nume: "Archia", comuna: "Deva" },
  { nume: "Barcea Mica", comuna: "Deva" },
  { nume: "Cristur", comuna: "Deva" },
  { nume: "Santuhalm", comuna: "Deva" },
  { nume: "Abucea", comuna: "Dobra" },
  { nume: "Bujoru", comuna: "Dobra" },
  { nume: "Fagetel", comuna: "Dobra" },
  { nume: "Lapusnic", comuna: "Dobra" },
  { nume: "Mihaiesti", comuna: "Dobra" },
  { nume: "Panc", comuna: "Dobra" },
  { nume: "Panc-Saliste", comuna: "Dobra" },
  { nume: "Roscani", comuna: "Dobra" },
  { nume: "Radulesti", comuna: "Dobra" },
  { nume: "Stretea", comuna: "Dobra" },
  { nume: "Stancesti", comuna: "Dobra" },
  { nume: "Stancesti-Ohaba", comuna: "Dobra" },
  { nume: "Craguis", comuna: "General Berthelot" },
  { nume: "Farcadin", comuna: "General Berthelot" },
  { nume: "Livezi", comuna: "General Berthelot" },
  { nume: "Tustea", comuna: "General Berthelot" },
  { nume: "Aurel Vlaicu", comuna: "Geoagiu" },
  { nume: "Bacaia", comuna: "Geoagiu" },
  { nume: "Bozes", comuna: "Geoagiu" },
  { nume: "Cigmau", comuna: "Geoagiu" },
  { nume: "Gelmar", comuna: "Geoagiu" },
  { nume: "Geoagiu-Bai", comuna: "Geoagiu" },
  { nume: "Homorod", comuna: "Geoagiu" },
  { nume: "Mermezeu-Valeni", comuna: "Geoagiu" },
  { nume: "Renghet", comuna: "Geoagiu" },
  { nume: "Valeni", comuna: "Geoagiu" },
  { nume: "Govajdia", comuna: "Ghelari" },
  { nume: "Plop", comuna: "Ghelari" },
  { nume: "Ruda", comuna: "Ghelari" },
  { nume: "Boiu de Jos", comuna: "Gurasada" },
  { nume: "Boiu de Sus", comuna: "Gurasada" },
  { nume: "Campuri de Sus", comuna: "Gurasada" },
  { nume: "Campuri-Surduc", comuna: "Gurasada" },
  { nume: "Carmazanesti", comuna: "Gurasada" },
  { nume: "Danulesti", comuna: "Gurasada" },
  { nume: "Gothatea", comuna: "Gurasada" },
  { nume: "Runcsor", comuna: "Gurasada" },
  { nume: "Ulies", comuna: "Gurasada" },
  { nume: "Vica", comuna: "Gurasada" },
  { nume: "Banpotoc", comuna: "Harau" },
  { nume: "Barsau", comuna: "Harau" },
  { nume: "Chimindia", comuna: "Harau" },
  { nume: "Nalatvad", comuna: "Hateg" },
  { nume: "Silvasu de Jos", comuna: "Hateg" },
  { nume: "Silvasu de Sus", comuna: "Hateg" },
  { nume: "Bos", comuna: "Hunedoara" },
  { nume: "Gros", comuna: "Hunedoara" },
  { nume: "Hasdat", comuna: "Hunedoara" },
  { nume: "Pestisu Mare", comuna: "Hunedoara" },
  { nume: "Racastia", comuna: "Hunedoara" },
  { nume: "Bacea", comuna: "Ilia" },
  { nume: "Bretea Muresana", comuna: "Ilia" },
  { nume: "Braznic", comuna: "Ilia" },
  { nume: "Cuies", comuna: "Ilia" },
  { nume: "Dumbravita", comuna: "Ilia" },
  { nume: "Sarbi", comuna: "Ilia" },
  { nume: "Sacamas", comuna: "Ilia" },
  { nume: "Valea Lunga", comuna: "Ilia" },
  { nume: "Bastea", comuna: "Lapugiu De Jos" },
  { nume: "Cosesti", comuna: "Lapugiu De Jos" },
  { nume: "Fintoag", comuna: "Lapugiu De Jos" },
  { nume: "Grind", comuna: "Lapugiu De Jos" },
  { nume: "Holdea", comuna: "Lapugiu De Jos" },
  { nume: "Lapugiu de Sus", comuna: "Lapugiu De Jos" },
  { nume: "Lasau", comuna: "Lapugiu De Jos" },
  { nume: "Ohaba", comuna: "Lapugiu De Jos" },
  { nume: "Teiu", comuna: "Lapugiu De Jos" },
  { nume: "Cerisor", comuna: "Lelese" },
  { nume: "Runcu Mare", comuna: "Lelese" },
  { nume: "Sohodol", comuna: "Lelese" },
  { nume: "Ciumita", comuna: "Lunca Cernii De Jos" },
  { nume: "Fantana", comuna: "Lunca Cernii De Jos" },
  { nume: "Gura Bordului", comuna: "Lunca Cernii De Jos" },
  { nume: "Lunca Cernii de Sus", comuna: "Lunca Cernii De Jos" },
  { nume: "Meria", comuna: "Lunca Cernii De Jos" },
  { nume: "Negoiu", comuna: "Lunca Cernii De Jos" },
  { nume: "Valea Babii", comuna: "Lunca Cernii De Jos" },
  { nume: "Dudesti", comuna: "Luncoiu De Jos" },
  { nume: "Luncoiu de Sus", comuna: "Luncoiu De Jos" },
  { nume: "Podele", comuna: "Luncoiu De Jos" },
  { nume: "Stejarel", comuna: "Luncoiu De Jos" },
  { nume: "Dancu Mare", comuna: "Martinesti" },
  { nume: "Dancu Mic", comuna: "Martinesti" },
  { nume: "Jeledinti", comuna: "Martinesti" },
  { nume: "Magura", comuna: "Martinesti" },
  { nume: "Turmas", comuna: "Martinesti" },
  { nume: "Tamasasa", comuna: "Martinesti" },
  { nume: "Bucium", comuna: "Orastioara De Sus" },
  { nume: "Costesti", comuna: "Orastioara De Sus" },
  { nume: "Costesti-Deal", comuna: "Orastioara De Sus" },
  { nume: "Gradistea de Munte", comuna: "Orastioara De Sus" },
  { nume: "Ludestii de Jos", comuna: "Orastioara De Sus" },
  { nume: "Ludestii de Sus", comuna: "Orastioara De Sus" },
  { nume: "Ocolisu Mic", comuna: "Orastioara De Sus" },
  { nume: "Almasu Mic", comuna: "Pestisu Mic" },
  { nume: "Ciulpaz", comuna: "Pestisu Mic" },
  { nume: "Cutin", comuna: "Pestisu Mic" },
  { nume: "Dumbrava", comuna: "Pestisu Mic" },
  { nume: "Josani", comuna: "Pestisu Mic" },
  { nume: "Manerau", comuna: "Pestisu Mic" },
  { nume: "Nandru", comuna: "Pestisu Mic" },
  { nume: "Valea Nandrului", comuna: "Pestisu Mic" },
  { nume: "Cimpa", comuna: "Petrila" },
  { nume: "Jiet", comuna: "Petrila" },
  { nume: "Rascoala", comuna: "Petrila" },
  { nume: "Tirici", comuna: "Petrila" },
  { nume: "Dalja Mare", comuna: "Petrosani" },
  { nume: "Dalja Mica", comuna: "Petrosani" },
  { nume: "Pestera", comuna: "Petrosani" },
  { nume: "Slatinioara", comuna: "Petrosani" },
  { nume: "Baiesti", comuna: "Pui" },
  { nume: "Federi", comuna: "Pui" },
  { nume: "Fizesti", comuna: "Pui" },
  { nume: "Galati", comuna: "Pui" },
  { nume: "Hobita", comuna: "Pui" },
  { nume: "Ohaba-Ponor", comuna: "Pui" },
  { nume: "Ponor", comuna: "Pui" },
  { nume: "Rusor", comuna: "Pui" },
  { nume: "Rau Barbat", comuna: "Pui" },
  { nume: "Uric", comuna: "Pui" },
  { nume: "Serel", comuna: "Pui" },
  { nume: "Boita", comuna: "Rachitova" },
  { nume: "Ciula Mare", comuna: "Rachitova" },
  { nume: "Ciula Mica", comuna: "Rachitova" },
  { nume: "Gotesti", comuna: "Rachitova" },
  { nume: "Mesteacan", comuna: "Rachitova" },
  { nume: "Valioara", comuna: "Rachitova" },
  { nume: "Bobalna", comuna: "Rapoltu Mare" },
  { nume: "Boiu", comuna: "Rapoltu Mare" },
  { nume: "Folt", comuna: "Rapoltu Mare" },
  { nume: "Rapoltel", comuna: "Rapoltu Mare" },
  { nume: "Brazi", comuna: "Rau De Mori" },
  { nume: "Clopotiva", comuna: "Rau De Mori" },
  { nume: "Ohaba-Sibisel", comuna: "Rau De Mori" },
  { nume: "Ostrov", comuna: "Rau De Mori" },
  { nume: "Ostrovel", comuna: "Rau De Mori" },
  { nume: "Ostrovu Mic", comuna: "Rau De Mori" },
  { nume: "Sibisel", comuna: "Rau De Mori" },
  { nume: "Suseni", comuna: "Rau De Mori" },
  { nume: "Unciuc", comuna: "Rau De Mori" },
  { nume: "Valea Daljii", comuna: "Rau De Mori" },
  { nume: "Crisan", comuna: "Ribita" },
  { nume: "Dumbrava de Jos", comuna: "Ribita" },
  { nume: "Dumbrava de Sus", comuna: "Ribita" },
  { nume: "Ribicioara", comuna: "Ribita" },
  { nume: "Uibaresti", comuna: "Ribita" },
  { nume: "Ciungu Mare", comuna: "Romos" },
  { nume: "Pischinti", comuna: "Romos" },
  { nume: "Romosel", comuna: "Romos" },
  { nume: "Vaidei", comuna: "Romos" },
  { nume: "Coroiesti", comuna: "Salasu De Sus" },
  { nume: "Malaiesti", comuna: "Salasu De Sus" },
  { nume: "Nucsoara", comuna: "Salasu De Sus" },
  { nume: "Ohaba de Sub Piatra", comuna: "Salasu De Sus" },
  { nume: "Paros", comuna: "Salasu De Sus" },
  { nume: "Pestera", comuna: "Salasu De Sus" },
  { nume: "Rau Alb", comuna: "Salasu De Sus" },
  { nume: "Rau Mic", comuna: "Salasu De Sus" },
  { nume: "Salasu de Jos", comuna: "Salasu De Sus" },
  { nume: "Zavoi", comuna: "Salasu De Sus" },
  { nume: "Balomir", comuna: "Santamaria-Orlea" },
  { nume: "Bucium-Orlea", comuna: "Santamaria-Orlea" },
  { nume: "Barastii Hategului", comuna: "Santamaria-Orlea" },
  { nume: "Ciopeia", comuna: "Santamaria-Orlea" },
  { nume: "Subcetate", comuna: "Santamaria-Orlea" },
  { nume: "Sanpetru", comuna: "Santamaria-Orlea" },
  { nume: "Sacel", comuna: "Santamaria-Orlea" },
  { nume: "Vadu", comuna: "Santamaria-Orlea" },
  { nume: "Breazova", comuna: "Sarmizegetusa" },
  { nume: "Hobita-Gradiste", comuna: "Sarmizegetusa" },
  { nume: "Paucinesti", comuna: "Sarmizegetusa" },
  { nume: "Zeicani", comuna: "Sarmizegetusa" },
  { nume: "Barcea Mare", comuna: "Simeria" },
  { nume: "Carpinis", comuna: "Simeria" },
  { nume: "Simeria Veche", comuna: "Simeria" },
  { nume: "Santandrei", comuna: "Simeria" },
  { nume: "Uroi", comuna: "Simeria" },
  { nume: "Saulesti", comuna: "Simeria" },
  { nume: "Bejan", comuna: "Soimus" },
  { nume: "Bejan-Tarnavita", comuna: "Soimus" },
  { nume: "Boholt", comuna: "Soimus" },
  { nume: "Balata", comuna: "Soimus" },
  { nume: "Chiscadaga", comuna: "Soimus" },
  { nume: "Cainelu de Jos", comuna: "Soimus" },
  { nume: "Fornadia", comuna: "Soimus" },
  { nume: "Paulis", comuna: "Soimus" },
  { nume: "Sulighete", comuna: "Soimus" },
  { nume: "Cincis-Cerna", comuna: "Teliucu Inferior" },
  { nume: "Izvoarele", comuna: "Teliucu Inferior" },
  { nume: "Teliucu Superior", comuna: "Teliucu Inferior" },
  { nume: "Dobrot", comuna: "Tomesti" },
  { nume: "Leaut", comuna: "Tomesti" },
  { nume: "Livada", comuna: "Tomesti" },
  { nume: "Obarsa", comuna: "Tomesti" },
  { nume: "Steia", comuna: "Tomesti" },
  { nume: "Tiulesti", comuna: "Tomesti" },
  { nume: "Valea Mare de Cris", comuna: "Tomesti" },
  { nume: "Curpenii Silvasului", comuna: "Toplita" },
  { nume: "Dealu Mic", comuna: "Toplita" },
  { nume: "Dabaca", comuna: "Toplita" },
  { nume: "Goles", comuna: "Toplita" },
  { nume: "Hasdau", comuna: "Toplita" },
  { nume: "Mosoru", comuna: "Toplita" },
  { nume: "Valari", comuna: "Toplita" },
  { nume: "Copaci", comuna: "Totesti" },
  { nume: "Carnesti", comuna: "Totesti" },
  { nume: "Paclisa", comuna: "Totesti" },
  { nume: "Reea", comuna: "Totesti" },
  { nume: "Pricaz", comuna: "Turdas" },
  { nume: "Rapas", comuna: "Turdas" },
  { nume: "Spini", comuna: "Turdas" },
  { nume: "Campu lui Neag", comuna: "Uricani" },
  { nume: "Valea de Brazi", comuna: "Uricani" },
  { nume: "Dealu Mare", comuna: "Valisoara" },
  { nume: "Stoieneasa", comuna: "Valisoara" },
  { nume: "Salistioara", comuna: "Valisoara" },
  { nume: "Basarabasa", comuna: "Vata De Jos" },
  { nume: "Birtin", comuna: "Vata De Jos" },
  { nume: "Brotuna", comuna: "Vata De Jos" },
  { nume: "Ciungani", comuna: "Vata De Jos" },
  { nume: "Cazanesti", comuna: "Vata De Jos" },
  { nume: "Ociu", comuna: "Vata De Jos" },
  { nume: "Ocisor", comuna: "Vata De Jos" },
  { nume: "Prihodiste", comuna: "Vata De Jos" },
  { nume: "Pravaleni", comuna: "Vata De Jos" },
  { nume: "Tarnava de Cris", comuna: "Vata De Jos" },
  { nume: "Tatarastii de Cris", comuna: "Vata De Jos" },
  { nume: "Vata de Sus", comuna: "Vata De Jos" },
  { nume: "Boia Barzii", comuna: "Vetel" },
  { nume: "Bretelin", comuna: "Vetel" },
  { nume: "Caoi", comuna: "Vetel" },
  { nume: "Herepeia", comuna: "Vetel" },
  { nume: "Lesnic", comuna: "Vetel" },
  { nume: "Mintia", comuna: "Vetel" },
  { nume: "Muncelu Mare", comuna: "Vetel" },
  { nume: "Muncelu Mic", comuna: "Vetel" },
  { nume: "Runcu Mic", comuna: "Vetel" },
  { nume: "Certeju de Jos", comuna: "Vorta" },
  { nume: "Coaja", comuna: "Vorta" },
  { nume: "Dumesti", comuna: "Vorta" },
  { nume: "Luncsoara", comuna: "Vorta" },
  { nume: "Valea Poienii", comuna: "Vorta" },
  { nume: "Visca", comuna: "Vorta" },
  { nume: "Dealu Babii", comuna: "Vulcan" },
  { nume: "Jiu-Paroseni", comuna: "Vulcan" },
  { nume: "Almas-Saliste", comuna: "Zam" },
  { nume: "Almasel", comuna: "Zam" },
  { nume: "Braseu", comuna: "Zam" },
  { nume: "Cerbia", comuna: "Zam" },
  { nume: "Deleni", comuna: "Zam" },
  { nume: "Godinesti", comuna: "Zam" },
  { nume: "Micanesti", comuna: "Zam" },
  { nume: "Poganesti", comuna: "Zam" },
  { nume: "Pojoga", comuna: "Zam" },
  { nume: "Salciva", comuna: "Zam" },
  { nume: "Tamasesti", comuna: "Zam" },
  { nume: "Valea", comuna: "Zam" },
];
