export const hr = [
  { nume: "Atid" },
  { nume: "Avramesti" },
  { nume: "Bilbor" },
  { nume: "Borsec" },
  { nume: "Bradesti" },
  { nume: "Baile Tusnad" },
  { nume: "Balan" },
  { nume: "Ciucsangeorgiu" },
  { nume: "Ciumani" },
  { nume: "Corbu" },
  { nume: "Corund" },
  { nume: "Cozmeni" },
  { nume: "Cristuru Secuiesc" },
  { nume: "Carta" },
  { nume: "Capalnita" },
  { nume: "Dealu" },
  { nume: "Ditrau" },
  { nume: "Darjiu" },
  { nume: "Danesti" },
  { nume: "Frumoasa" },
  { nume: "Gheorgheni" },
  { nume: "Galautas" },
  { nume: "Joseni" },
  { nume: "Lueta" },
  { nume: "Lunca de Jos" },
  { nume: "Lunca de Sus" },
  { nume: "Lupeni" },
  { nume: "Lazarea" },
  { nume: "Meresti" },
  { nume: "Miercurea Ciuc" },
  { nume: "Mihaileni" },
  { nume: "Mugeni" },
  { nume: "Madaras" },
  { nume: "Martinis" },
  { nume: "Ocland" },
  { nume: "Odorheiu Secuiesc" },
  { nume: "Plaiesii de Jos" },
  { nume: "Praid" },
  { nume: "Pauleni-Ciuc" },
  { nume: "Remetea" },
  { nume: "Secuieni" },
  { nume: "Siculeni" },
  { nume: "Subcetate" },
  { nume: "Suseni" },
  { nume: "Sancraieni" },
  { nume: "Sandominic" },
  { nume: "Sanmartin" },
  { nume: "Sansimion" },
  { nume: "Sacel" },
  { nume: "Sarmas" },
  { nume: "Tomesti" },
  { nume: "Toplita" },
  { nume: "Tulghes" },
  { nume: "Tusnad" },
  { nume: "Ulies" },
  { nume: "Vlahita" },
  { nume: "Voslabeni" },
  { nume: "Varsag" },
  { nume: "Zetea" },
  { nume: "Simonesti" },
  { nume: "Criseni", comuna: "Atid" },
  { nume: "Cusmed", comuna: "Atid" },
  { nume: "Inlaceni", comuna: "Atid" },
  { nume: "Siclod", comuna: "Atid" },
  { nume: "Andreeni", comuna: "Avramesti" },
  { nume: "Cechesti", comuna: "Avramesti" },
  { nume: "Firtanus", comuna: "Avramesti" },
  { nume: "Goagiu", comuna: "Avramesti" },
  { nume: "Laz-Firtanus", comuna: "Avramesti" },
  { nume: "Laz-Soimus", comuna: "Avramesti" },
  { nume: "Medisoru Mic", comuna: "Avramesti" },
  { nume: "Carpitus", comuna: "Baile Tusnad" },
  { nume: "Rachitis", comuna: "Bilbor" },
  { nume: "Satu Mare", comuna: "Bradesti" },
  { nume: "Tarnovita", comuna: "Bradesti" },
  { nume: "Ineu", comuna: "Carta" },
  { nume: "Armaseni", comuna: "Ciucsangeorgiu" },
  { nume: "Armasenii Noi", comuna: "Ciucsangeorgiu" },
  { nume: "Bancu", comuna: "Ciucsangeorgiu" },
  { nume: "Ciobanis", comuna: "Ciucsangeorgiu" },
  { nume: "Cotormani", comuna: "Ciucsangeorgiu" },
  { nume: "Eghersec", comuna: "Ciucsangeorgiu" },
  { nume: "Ghiurche", comuna: "Ciucsangeorgiu" },
  { nume: "Potiond", comuna: "Ciucsangeorgiu" },
  { nume: "Capu Corbului", comuna: "Corbu" },
  { nume: "Atia", comuna: "Corund" },
  { nume: "Calonda", comuna: "Corund" },
  { nume: "Fantana Brazilor", comuna: "Corund" },
  { nume: "Valea lui Pavel", comuna: "Corund" },
  { nume: "Lazaresti", comuna: "Cozmeni" },
  { nume: "Filias", comuna: "Cristuru Secuiesc" },
  { nume: "Mujna", comuna: "Darjiu" },
  { nume: "Fancel", comuna: "Dealu" },
  { nume: "Sancrai", comuna: "Dealu" },
  { nume: "Tibod", comuna: "Dealu" },
  { nume: "Tamasu", comuna: "Dealu" },
  { nume: "Ulcani", comuna: "Dealu" },
  { nume: "Valea Rotunda", comuna: "Dealu" },
  { nume: "Jolotca", comuna: "Ditrau" },
  { nume: "Tengheler", comuna: "Ditrau" },
  { nume: "Alexandrita", comuna: "Felicieni" },
  { nume: "Arvateni", comuna: "Felicieni" },
  { nume: "Cireseni", comuna: "Felicieni" },
  { nume: "Feliceni", comuna: "Felicieni" },
  { nume: "Forteni", comuna: "Felicieni" },
  { nume: "Hoghia", comuna: "Felicieni" },
  { nume: "Oteni", comuna: "Felicieni" },
  { nume: "Polonita", comuna: "Felicieni" },
  { nume: "Teleac", comuna: "Felicieni" },
  { nume: "Taureni", comuna: "Felicieni" },
  { nume: "Valeni", comuna: "Felicieni" },
  { nume: "Barzava", comuna: "Frumoasa" },
  { nume: "Fagetel", comuna: "Frumoasa" },
  { nume: "Nicolesti", comuna: "Frumoasa" },
  { nume: "Dealu Armanului", comuna: "Galautas" },
  { nume: "Galautas-Parau", comuna: "Galautas" },
  { nume: "Nuteni", comuna: "Galautas" },
  { nume: "Plopis", comuna: "Galautas" },
  { nume: "Preluca", comuna: "Galautas" },
  { nume: "Toleseni", comuna: "Galautas" },
  { nume: "Zapodea", comuna: "Galautas" },
  { nume: "Covacipeter", comuna: "Gheorgheni" },
  { nume: "Lacu Rosu", comuna: "Gheorgheni" },
  { nume: "Vargatac", comuna: "Gheorgheni" },
  { nume: "Visafolio", comuna: "Gheorgheni" },
  { nume: "Borzont", comuna: "Joseni" },
  { nume: "Bucin", comuna: "Joseni" },
  { nume: "Ghidut", comuna: "Lazarea" },
  { nume: "Baile Chirui", comuna: "Lueta" },
  { nume: "Baratcos", comuna: "Lunca De Jos" },
  { nume: "Poiana Fagului", comuna: "Lunca De Jos" },
  { nume: "Puntea Lupului", comuna: "Lunca De Jos" },
  { nume: "Valea Boros", comuna: "Lunca De Jos" },
  { nume: "Valea Capelei", comuna: "Lunca De Jos" },
  { nume: "Valea Rece", comuna: "Lunca De Jos" },
  { nume: "Valea lui Antaloc", comuna: "Lunca De Jos" },
  { nume: "Valea Intunecoasa", comuna: "Lunca De Jos" },
  { nume: "Comiat", comuna: "Lunca De Sus" },
  { nume: "Izvorul Trotusului", comuna: "Lunca De Sus" },
  { nume: "Paltinis-Ciuc", comuna: "Lunca De Sus" },
  { nume: "Valea Garbea", comuna: "Lunca De Sus" },
  { nume: "Valea Ugra", comuna: "Lunca De Sus" },
  { nume: "Bisericani", comuna: "Lupeni" },
  { nume: "Bulgareni", comuna: "Lupeni" },
  { nume: "Firtusu", comuna: "Lupeni" },
  { nume: "Morareni", comuna: "Lupeni" },
  { nume: "Paltinis", comuna: "Lupeni" },
  { nume: "Pauleni", comuna: "Lupeni" },
  { nume: "Satu Mic", comuna: "Lupeni" },
  { nume: "Sancel", comuna: "Lupeni" },
  { nume: "Aldea", comuna: "Martinis" },
  { nume: "Badeni", comuna: "Martinis" },
  { nume: "Chinusu", comuna: "Martinis" },
  { nume: "Comanesti", comuna: "Martinis" },
  { nume: "Calugareni", comuna: "Martinis" },
  { nume: "Ghipes", comuna: "Martinis" },
  { nume: "Locodeni", comuna: "Martinis" },
  { nume: "Oraseni", comuna: "Martinis" },
  { nume: "Petreni", comuna: "Martinis" },
  { nume: "Rares", comuna: "Martinis" },
  { nume: "Sanpaul", comuna: "Martinis" },
  { nume: "Ciba", comuna: "Miercurea Ciuc" },
  { nume: "Harghita-Bai", comuna: "Miercurea Ciuc" },
  { nume: "Jigodin-Bai", comuna: "Miercurea Ciuc" },
  { nume: "Livezi", comuna: "Mihaileni" },
  { nume: "Nadejdea", comuna: "Mihaileni" },
  { nume: "Vacaresti", comuna: "Mihaileni" },
  { nume: "Alunis", comuna: "Mugeni" },
  { nume: "Beta", comuna: "Mugeni" },
  { nume: "Betesti", comuna: "Mugeni" },
  { nume: "Dejutiu", comuna: "Mugeni" },
  { nume: "Dobeni", comuna: "Mugeni" },
  { nume: "Lutita", comuna: "Mugeni" },
  { nume: "Matiseni", comuna: "Mugeni" },
  { nume: "Porumbenii Mari", comuna: "Mugeni" },
  { nume: "Porumbenii Mici", comuna: "Mugeni" },
  { nume: "Taietura", comuna: "Mugeni" },
  { nume: "Craciunel", comuna: "Ocland" },
  { nume: "Satu Nou", comuna: "Ocland" },
  { nume: "Delnita", comuna: "Pauleni-Ciuc" },
  { nume: "Soimeni", comuna: "Pauleni-Ciuc" },
  { nume: "Casinu Nou", comuna: "Plaiesii De Jos" },
  { nume: "Iacobeni", comuna: "Plaiesii De Jos" },
  { nume: "Imper", comuna: "Plaiesii De Jos" },
  { nume: "Plaiesii de Sus", comuna: "Plaiesii De Jos" },
  { nume: "Becas", comuna: "Praid" },
  { nume: "Bucin", comuna: "Praid" },
  { nume: "Ocna de Jos", comuna: "Praid" },
  { nume: "Ocna de Sus", comuna: "Praid" },
  { nume: "Sasveres", comuna: "Praid" },
  { nume: "Fagetel", comuna: "Remetea" },
  { nume: "Martonca", comuna: "Remetea" },
  { nume: "Sineu", comuna: "Remetea" },
  { nume: "Uilac", comuna: "Sacel" },
  { nume: "Vidacut", comuna: "Sacel" },
  { nume: "Soimusu Mare", comuna: "Sacel" },
  { nume: "Soimusu Mic", comuna: "Sacel" },
  { nume: "Fitod", comuna: "Sancraieni" },
  { nume: "Hosasau", comuna: "Sancraieni" },
  { nume: "Leliceni", comuna: "Sancraieni" },
  { nume: "Misentea", comuna: "Sancraieni" },
  { nume: "Santimbru", comuna: "Sancraieni" },
  { nume: "Santimbru-Bai", comuna: "Sancraieni" },
  { nume: "Ciucani", comuna: "Sanmartin" },
  { nume: "Valea Uzului", comuna: "Sanmartin" },
  { nume: "Cetatuia", comuna: "Sansimion" },
  { nume: "Fundoaia", comuna: "Sarmas" },
  { nume: "Hodosa", comuna: "Sarmas" },
  { nume: "Platonesti", comuna: "Sarmas" },
  { nume: "Runc", comuna: "Sarmas" },
  { nume: "Bodogaia", comuna: "Secuieni" },
  { nume: "Eliseni", comuna: "Secuieni" },
  { nume: "Ciaracio", comuna: "Siculeni" },
  { nume: "Ciceu", comuna: "Siculeni" },
  { nume: "Racu", comuna: "Siculeni" },
  { nume: "Satu Nou", comuna: "Siculeni" },
  { nume: "Bentid", comuna: "Simonesti" },
  { nume: "Cehetel", comuna: "Simonesti" },
  { nume: "Chedia Mare", comuna: "Simonesti" },
  { nume: "Chedia Mica", comuna: "Simonesti" },
  { nume: "Cobatesti", comuna: "Simonesti" },
  { nume: "Cadaciu Mare", comuna: "Simonesti" },
  { nume: "Cadaciu Mic", comuna: "Simonesti" },
  { nume: "Medisoru Mare", comuna: "Simonesti" },
  { nume: "Mihaileni", comuna: "Simonesti" },
  { nume: "Nicoleni", comuna: "Simonesti" },
  { nume: "Ruganesti", comuna: "Simonesti" },
  { nume: "Turdeni", comuna: "Simonesti" },
  { nume: "Tarcesti", comuna: "Simonesti" },
  { nume: "Calnaci", comuna: "Subcetate" },
  { nume: "Duda", comuna: "Subcetate" },
  { nume: "Filpea", comuna: "Subcetate" },
  { nume: "Chileni", comuna: "Suseni" },
  { nume: "Liban", comuna: "Suseni" },
  { nume: "Senetea", comuna: "Suseni" },
  { nume: "Valea Stramba", comuna: "Suseni" },
  { nume: "Calimanel", comuna: "Toplita" },
  { nume: "Luncani", comuna: "Toplita" },
  { nume: "Moglanesti", comuna: "Toplita" },
  { nume: "Magherus", comuna: "Toplita" },
  { nume: "Secu", comuna: "Toplita" },
  { nume: "Vale", comuna: "Toplita" },
  { nume: "Vagani", comuna: "Toplita" },
  { nume: "Zencani", comuna: "Toplita" },
  { nume: "Hagota", comuna: "Tulghes" },
  { nume: "Pintic", comuna: "Tulghes" },
  { nume: "Recea", comuna: "Tulghes" },
  { nume: "Tusnadu Nou", comuna: "Tusnad" },
  { nume: "Vrabia", comuna: "Tusnad" },
  { nume: "Daia", comuna: "Ulies" },
  { nume: "Iasu", comuna: "Ulies" },
  { nume: "Ighiu", comuna: "Ulies" },
  { nume: "Nicolesti", comuna: "Ulies" },
  { nume: "Obranesti", comuna: "Ulies" },
  { nume: "Petecu", comuna: "Ulies" },
  { nume: "Vasileni", comuna: "Ulies" },
  { nume: "Baile Homorod", comuna: "Vlahita" },
  { nume: "Minele Lueta", comuna: "Vlahita" },
  { nume: "Izvoru Muresului", comuna: "Voslabeni" },
  { nume: "Desag", comuna: "Zetea" },
  { nume: "Izvoare", comuna: "Zetea" },
  { nume: "Poiana Tarnavei", comuna: "Zetea" },
  { nume: "Sub Cetate", comuna: "Zetea" },
  { nume: "Sicasau", comuna: "Zetea" },
];
