export const hd = [
  { nume: "Abucea", comuna: "Dobra" },
  { nume: "Almaş-Sălişte", simplu: "Almas-Saliste", comuna: "Zam" },
  { nume: "Almăşel", simplu: "Almasel", comuna: "Zam" },
  {
    nume: "Almaşu Mic de Munte",
    simplu: "Almasu Mic de Munte",
    comuna: "Balsa",
  },
  { nume: "Almaşu Mic", simplu: "Almasu Mic", comuna: "Pestisu Mic" },
  { nume: "Almaşu Sec", simplu: "Almasu Sec", comuna: "Carjiti" },
  { nume: "Alun", comuna: "Bosorod" },
  { nume: "Alun", comuna: "Bunila" },
  { nume: "Aninoasa" },
  { nume: "Arănieş", simplu: "Aranies", comuna: "Cerbal" },
  { nume: "Archia", comuna: "Deva" },
  { nume: "Ardeu", comuna: "Balsa" },
  { nume: "Aurel Vlaicu", comuna: "Geoagiu" },
  { nume: "Bacâia", simplu: "Bacaia", comuna: "Geoagiu" },
  { nume: "Bacea", comuna: "Ilia" },
  { nume: "Băcia", simplu: "Bacia" },
  { nume: "Baia de Criş", simplu: "Baia de Cris" },
  { nume: "Băieşti", simplu: "Baiesti", comuna: "Pui" },
  { nume: "Băiţa", simplu: "Baita" },
  { nume: "Bălata", simplu: "Balata", comuna: "Soimus" },
  { nume: "Baldovin", comuna: "Baia De Cris" },
  { nume: "Balomir", comuna: "Santamaria-Orlea" },
  { nume: "Balşa", simplu: "Balsa" },
  { nume: "Băniţa", simplu: "Banita" },
  { nume: "Banpotoc", comuna: "Harau" },
  {
    nume: "Bărăştii Haţegului",
    simplu: "Barastii Hategului",
    comuna: "Santamaria-Orlea",
  },
  { nume: "Bărăştii Iliei", simplu: "Barastii Iliei", comuna: "Branisca" },
  { nume: "Barbura", comuna: "Baita" },
  { nume: "Bârcea Mare", simplu: "Barcea Mare", comuna: "Simeria" },
  { nume: "Bârcea Mică", simplu: "Barcea Mica", comuna: "Deva" },
  { nume: "Bârsău", simplu: "Barsau", comuna: "Harau" },
  { nume: "Baru" },
  { nume: "Barza", comuna: "Criscior" },
  { nume: "Basarabasa", comuna: "Vata De Jos" },
  { nume: "Baştea", simplu: "Bastea", comuna: "Lapugiu De Jos" },
  { nume: "Băţălar", simplu: "Batalar", comuna: "Bretea Romana" },
  { nume: "Batiz", comuna: "Calan" },
  { nume: "Bătrâna", simplu: "Batrana" },
  { nume: "Bejan-Târnăviţa", simplu: "Bejan-Tarnavita", comuna: "Soimus" },
  { nume: "Bejan", comuna: "Soimus" },
  { nume: "Bercu", comuna: "Bretea Romana" },
  { nume: "Beriu" },
  { nume: "Birtin", comuna: "Vata De Jos" },
  { nume: "Blăjeni-Vulcan", simplu: "Blajeni-Vulcan", comuna: "Blajeni" },
  { nume: "Blăjeni", simplu: "Blajeni" },
  { nume: "Bobaia", comuna: "Bosorod" },
  { nume: "Bobâlna", simplu: "Bobalna", comuna: "Rapoltu Mare" },
  { nume: "Bocşa Mare", simplu: "Bocsa Mare", comuna: "Certeju De Sus" },
  { nume: "Bocşa Mică", simplu: "Bocsa Mica", comuna: "Certeju De Sus" },
  { nume: "Boholţ", simplu: "Boholt", comuna: "Soimus" },
  { nume: "Boia Bârzii", simplu: "Boia Barzii", comuna: "Vetel" },
  { nume: "Boiţa", simplu: "Boita", comuna: "Rachitova" },
  { nume: "Boiu de Jos", comuna: "Gurasada" },
  { nume: "Boiu de Sus", comuna: "Gurasada" },
  { nume: "Boiu", comuna: "Rapoltu Mare" },
  { nume: "Boş", simplu: "Bos", comuna: "Hunedoara" },
  { nume: "Boşorod", simplu: "Bosorod" },
  { nume: "Boz", comuna: "Branisca" },
  { nume: "Bozeş", simplu: "Bozes", comuna: "Geoagiu" },
  { nume: "Brad" },
  { nume: "Brădăţel", simplu: "Bradatel", comuna: "Burjuc" },
  { nume: "Brănişca", simplu: "Branisca" },
  { nume: "Brăşeu", simplu: "Braseu", comuna: "Zam" },
  { nume: "Brazi", comuna: "Rau De Mori" },
  { nume: "Brâznic", simplu: "Braznic", comuna: "Ilia" },
  { nume: "Breazova", comuna: "Sarmizegetusa" },
  { nume: "Bretea Mureşană", simplu: "Bretea Muresana", comuna: "Ilia" },
  { nume: "Bretea Română", simplu: "Bretea Romana" },
  { nume: "Bretea Streiului", comuna: "Bretea Romana" },
  { nume: "Bretelin", comuna: "Vetel" },
  { nume: "Brotuna", comuna: "Vata De Jos" },
  { nume: "Buceş-Vulcan", simplu: "Buces-Vulcan", comuna: "Buces" },
  { nume: "Buceş", simplu: "Buces" },
  { nume: "Bucium-Orlea", comuna: "Santamaria-Orlea" },
  { nume: "Bucium", comuna: "Orastioara De Sus" },
  { nume: "Bucureşci", simplu: "Bucuresci" },
  { nume: "Bujoru", comuna: "Dobra" },
  {
    nume: "Bulzeştii de Jos",
    simplu: "Bulzestii de Jos",
    comuna: "Bulzestii De Sus",
  },
  { nume: "Bulzeştii de Sus", simplu: "Bulzestii de Sus" },
  { nume: "Buneşti", simplu: "Bunesti", comuna: "Balsa" },
  { nume: "Bunila" },
  { nume: "Burjuc" },
  { nume: "Căbeşti", simplu: "Cabesti", comuna: "Branisca" },
  { nume: "Căinelu de Jos", simplu: "Cainelu de Jos", comuna: "Soimus" },
  { nume: "Căinelu de Sus", simplu: "Cainelu de Sus", comuna: "Baita" },
  { nume: "Călan", simplu: "Calan" },
  { nume: "Călanu Mic", simplu: "Calanu Mic", comuna: "Calan" },
  { nume: "Câmpu lui Neag", simplu: "Campu lui Neag", comuna: "Uricani" },
  { nume: "Câmpuri de Sus", simplu: "Campuri de Sus", comuna: "Gurasada" },
  { nume: "Câmpuri-Surduc", simplu: "Campuri-Surduc", comuna: "Gurasada" },
  { nume: "Căoi", simplu: "Caoi", comuna: "Vetel" },
  { nume: "Căraci", simplu: "Caraci", comuna: "Baia De Cris" },
  { nume: "Cărăstău", simplu: "Carastau", comuna: "Baia De Cris" },
  { nume: "Cârjiţi", simplu: "Carjiti" },
  { nume: "Cărmăzăneşti", simplu: "Carmazanesti", comuna: "Gurasada" },
  { nume: "Cârneşti", simplu: "Carnesti", comuna: "Totesti" },
  { nume: "Cărpiniş", simplu: "Carpinis", comuna: "Simeria" },
  { nume: "Căstău", simplu: "Castau", comuna: "Beriu" },
  { nume: "Căzăneşti", simplu: "Cazanesti", comuna: "Vata De Jos" },
  { nume: "Cerbăl", simplu: "Cerbal" },
  { nume: "Cerbia", comuna: "Zam" },
  { nume: "Cerişor", simplu: "Cerisor", comuna: "Lelese" },
  {
    nume: "Cernişoara Florese",
    simplu: "Cernisoara Florese",
    comuna: "Bunila",
  },
  { nume: "Certeju de Jos", comuna: "Vorta" },
  { nume: "Certeju de Sus" },
  { nume: "Chergheş", simplu: "Cherghes", comuna: "Carjiti" },
  { nume: "Chimindia", comuna: "Harau" },
  { nume: "Chişcădaga", simplu: "Chiscadaga", comuna: "Soimus" },
  { nume: "Chitid", comuna: "Bosorod" },
  { nume: "Cigmău", simplu: "Cigmau", comuna: "Geoagiu" },
  { nume: "Cimpa", comuna: "Petrila" },
  { nume: "Cinciş-Cerna", simplu: "Cincis-Cerna", comuna: "Teliucu Inferior" },
  { nume: "Cioclovina", comuna: "Bosorod" },
  { nume: "Ciopeia", comuna: "Santamaria-Orlea" },
  { nume: "Ciula Mare", comuna: "Rachitova" },
  { nume: "Ciula Mică", simplu: "Ciula Mica", comuna: "Rachitova" },
  { nume: "Ciulpăz", simplu: "Ciulpaz", comuna: "Pestisu Mic" },
  { nume: "Ciumiţa", simplu: "Ciumita", comuna: "Lunca Cernii De Jos" },
  { nume: "Ciungani", comuna: "Vata De Jos" },
  { nume: "Ciungu Mare", comuna: "Romos" },
  { nume: "Clopotiva", comuna: "Rau De Mori" },
  { nume: "Coaja", comuna: "Vorta" },
  { nume: "Copaci", comuna: "Totesti" },
  { nume: "Coroieşti", simplu: "Coroiesti", comuna: "Salasu De Sus" },
  { nume: "Coseşti", simplu: "Cosesti", comuna: "Lapugiu De Jos" },
  {
    nume: "Costeşti-Deal",
    simplu: "Costesti-Deal",
    comuna: "Orastioara De Sus",
  },
  { nume: "Costeşti", simplu: "Costesti", comuna: "Orastioara De Sus" },
  { nume: "Covragiu", comuna: "Bretea Romana" },
  { nume: "Cozia", comuna: "Carjiti" },
  { nume: "Crăciuneşti", simplu: "Craciunesti", comuna: "Baita" },
  { nume: "Crăguiş", simplu: "Craguis", comuna: "General Berthelot" },
  { nume: "Criş", simplu: "Cris", comuna: "Blajeni" },
  { nume: "Crişan", simplu: "Crisan", comuna: "Ribita" },
  { nume: "Crişcior", simplu: "Criscior" },
  { nume: "Cristur", comuna: "Deva" },
  { nume: "Criva", comuna: "Densus" },
  { nume: "Crivadia", comuna: "Banita" },
  { nume: "Cucuiş", simplu: "Cucuis", comuna: "Beriu" },
  { nume: "Cuieş", simplu: "Cuies", comuna: "Ilia" },
  { nume: "Curechiu", comuna: "Bucuresci" },
  {
    nume: "Curpenii Silvaşului",
    simplu: "Curpenii Silvasului",
    comuna: "Toplita",
  },
  { nume: "Cutin", comuna: "Pestisu Mic" },
  { nume: "Dăbâca", simplu: "Dabaca", comuna: "Toplita" },
  { nume: "Dâlja Mare", simplu: "Dalja Mare", comuna: "Petrosani" },
  { nume: "Dâlja Mică", simplu: "Dalja Mica", comuna: "Petrosani" },
  { nume: "Dâncu Mare", simplu: "Dancu Mare", comuna: "Martinesti" },
  { nume: "Dâncu Mic", simplu: "Dancu Mic", comuna: "Martinesti" },
  { nume: "Dănuleşti", simplu: "Danulesti", comuna: "Gurasada" },
  { nume: "Dealu Babii", comuna: "Vulcan" },
  { nume: "Dealu Mare", comuna: "Valisoara" },
  { nume: "Dealu Mic", comuna: "Toplita" },
  { nume: "Deleni", comuna: "Zam" },
  { nume: "Densuş", simplu: "Densus" },
  { nume: "Deva" },
  { nume: "Dobra" },
  { nume: "Dobroţ", simplu: "Dobrot", comuna: "Tomesti" },
  { nume: "Dragu-Brad", comuna: "Blajeni" },
  { nume: "Dudeşti", simplu: "Dudesti", comuna: "Luncoiu De Jos" },
  { nume: "Dumbrava de Jos", comuna: "Ribita" },
  { nume: "Dumbrava de Sus", comuna: "Ribita" },
  { nume: "Dumbrava", comuna: "Pestisu Mic" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita", comuna: "Ilia" },
  { nume: "Dumeşti", simplu: "Dumesti", comuna: "Vorta" },
  { nume: "Dupăpiatră", simplu: "Dupapiatra", comuna: "Buces" },
  { nume: "Făgeţel", simplu: "Fagetel", comuna: "Dobra" },
  { nume: "Fântâna", simplu: "Fantana", comuna: "Lunca Cernii De Jos" },
  { nume: "Fărcădin", simplu: "Farcadin", comuna: "General Berthelot" },
  { nume: "Faţa Roşie", simplu: "Fata Rosie", comuna: "Batrana" },
  { nume: "Federi", comuna: "Pui" },
  { nume: "Feregi", comuna: "Cerbal" },
  { nume: "Fintoag", comuna: "Lapugiu De Jos" },
  { nume: "Fizeş", simplu: "Fizes", comuna: "Baita" },
  { nume: "Fizeşti", simplu: "Fizesti", comuna: "Pui" },
  { nume: "Folt", comuna: "Rapoltu Mare" },
  { nume: "Fornădia", simplu: "Fornadia", comuna: "Soimus" },
  { nume: "Furcşoara", simplu: "Furcsoara", comuna: "Branisca" },
  { nume: "Galaţi", simplu: "Galati", comuna: "Pui" },
  { nume: "Galbina", comuna: "Balsa" },
  { nume: "Gânţaga", simplu: "Gantaga", comuna: "Bretea Romana" },
  { nume: "Gelmar", comuna: "Geoagiu" },
  { nume: "General Berthelot" },
  { nume: "Geoagiu-Băi", simplu: "Geoagiu-Bai", comuna: "Geoagiu" },
  { nume: "Geoagiu" },
  { nume: "Ghelari" },
  { nume: "Gialacuta", comuna: "Branisca" },
  { nume: "Giurgeşti", simplu: "Giurgesti", comuna: "Bulzestii De Sus" },
  { nume: "Glodghileşti", simplu: "Glodghilesti", comuna: "Burjuc" },
  { nume: "Godineşti", simplu: "Godinesti", comuna: "Zam" },
  { nume: "Goleş", simplu: "Goles", comuna: "Toplita" },
  { nume: "Goteşti", simplu: "Gotesti", comuna: "Rachitova" },
  { nume: "Gothatea", comuna: "Gurasada" },
  { nume: "Govăjdia", simplu: "Govajdia", comuna: "Ghelari" },
  {
    nume: "Grădiştea de Munte",
    simplu: "Gradistea de Munte",
    comuna: "Orastioara De Sus",
  },
  { nume: "Grid", comuna: "Calan" },
  { nume: "Grind", comuna: "Lapugiu De Jos" },
  { nume: "Grohot", comuna: "Bulzestii De Sus" },
  { nume: "Grohoţele", simplu: "Grohotele", comuna: "Buces" },
  { nume: "Groş", simplu: "Gros", comuna: "Hunedoara" },
  { nume: "Groşuri", simplu: "Grosuri", comuna: "Blajeni" },
  { nume: "Gura Bordului", comuna: "Lunca Cernii De Jos" },
  { nume: "Gurasada" },
  { nume: "Hărău", simplu: "Harau" },
  { nume: "Hărţăgani", simplu: "Hartagani", comuna: "Baita" },
  { nume: "Hăşdat", simplu: "Hasdat", comuna: "Hunedoara" },
  { nume: "Hăşdău", simplu: "Hasdau", comuna: "Toplita" },
  { nume: "Hăţăgel", simplu: "Hatagel", comuna: "Densus" },
  { nume: "Haţeg", simplu: "Hateg" },
  { nume: "Herepeia", comuna: "Vetel" },
  {
    nume: "Hobiţa-Grădişte",
    simplu: "Hobita-Gradiste",
    comuna: "Sarmizegetusa",
  },
  { nume: "Hobiţa", simplu: "Hobita", comuna: "Pui" },
  { nume: "Holdea", comuna: "Lapugiu De Jos" },
  { nume: "Homorod", comuna: "Geoagiu" },
  { nume: "Hondol", comuna: "Certeju De Sus" },
  { nume: "Hunedoara" },
  { nume: "Ilia" },
  { nume: "Iscroni", comuna: "Aninoasa" },
  { nume: "Izvoarele", comuna: "Teliucu Inferior" },
  { nume: "Jeledinţi", simplu: "Jeledinti", comuna: "Martinesti" },
  { nume: "Jieţ", simplu: "Jiet", comuna: "Petrila" },
  { nume: "Jiu-Paroşeni", simplu: "Jiu-Paroseni", comuna: "Vulcan" },
  { nume: "Josani", comuna: "Pestisu Mic" },
  { nume: "Lăpugiu de Jos", simplu: "Lapugiu de Jos" },
  {
    nume: "Lăpugiu de Sus",
    simplu: "Lapugiu de Sus",
    comuna: "Lapugiu De Jos",
  },
  { nume: "Lăpuşnic", simplu: "Lapusnic", comuna: "Dobra" },
  { nume: "Lăsău", simplu: "Lasau", comuna: "Lapugiu De Jos" },
  { nume: "Leauţ", simplu: "Leaut", comuna: "Tomesti" },
  { nume: "Lelese" },
  { nume: "Leşnic", simplu: "Lesnic", comuna: "Vetel" },
  { nume: "Livada", comuna: "Tomesti" },
  { nume: "Livadia", comuna: "Baru" },
  { nume: "Livezi", comuna: "General Berthelot" },
  {
    nume: "Ludeştii de Jos",
    simplu: "Ludestii de Jos",
    comuna: "Orastioara De Sus",
  },
  {
    nume: "Ludeştii de Sus",
    simplu: "Ludestii de Sus",
    comuna: "Orastioara De Sus",
  },
  { nume: "Lunca Cernii de Jos" },
  { nume: "Lunca Cernii de Sus", comuna: "Lunca Cernii De Jos" },
  { nume: "Lunca", comuna: "Baia De Cris" },
  { nume: "Lunca", comuna: "Baita" },
  { nume: "Luncani", comuna: "Bosorod" },
  { nume: "Luncoiu de Jos" },
  { nume: "Luncoiu de Sus", comuna: "Luncoiu De Jos" },
  { nume: "Luncşoara", simplu: "Luncsoara", comuna: "Vorta" },
  { nume: "Lupeni" },
  { nume: "Măceu", simplu: "Maceu", comuna: "Bretea Romana" },
  { nume: "Mada", comuna: "Balsa" },
  {
    nume: "Măgura-Topliţa",
    simplu: "Magura-Toplita",
    comuna: "Certeju De Sus",
  },
  { nume: "Măgura", simplu: "Magura", comuna: "Martinesti" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Beriu" },
  { nume: "Mălăieşti", simplu: "Malaiesti", comuna: "Salasu De Sus" },
  { nume: "Mănerău", simplu: "Manerau", comuna: "Pestisu Mic" },
  { nume: "Mărtineşti", simplu: "Martinesti" },
  { nume: "Meria", comuna: "Lunca Cernii De Jos" },
  { nume: "Merişor", simplu: "Merisor", comuna: "Banita" },
  { nume: "Merişor", simplu: "Merisor", comuna: "Bucuresci" },
  { nume: "Merişoru de Munte", simplu: "Merisoru de Munte", comuna: "Cerbal" },
  { nume: "Mermezeu-Văleni", simplu: "Mermezeu-Valeni", comuna: "Geoagiu" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Brad" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Rachitova" },
  { nume: "Micăneşti", simplu: "Micanesti", comuna: "Zam" },
  { nume: "Mihăieşti", simplu: "Mihaiesti", comuna: "Dobra" },
  { nume: "Mihăileni", simplu: "Mihaileni", comuna: "Buces" },
  { nume: "Mintia", comuna: "Vetel" },
  { nume: "Mosoru", comuna: "Toplita" },
  { nume: "Muncelu Mare", comuna: "Vetel" },
  { nume: "Muncelu Mic", comuna: "Vetel" },
  { nume: "Nădăştia de Jos", simplu: "Nadastia de Jos", comuna: "Calan" },
  { nume: "Nădăştia de Sus", simplu: "Nadastia de Sus", comuna: "Calan" },
  { nume: "Nălaţvad", simplu: "Nalatvad", comuna: "Hateg" },
  { nume: "Nandru", comuna: "Pestisu Mic" },
  { nume: "Negoiu", comuna: "Lunca Cernii De Jos" },
  { nume: "Nojag", comuna: "Certeju De Sus" },
  { nume: "Nucşoara", simplu: "Nucsoara", comuna: "Salasu De Sus" },
  { nume: "Obârşa", simplu: "Obarsa", comuna: "Tomesti" },
  { nume: "Ocişor", simplu: "Ocisor", comuna: "Vata De Jos" },
  { nume: "Ociu", comuna: "Vata De Jos" },
  { nume: "Ocolişu Mare", simplu: "Ocolisu Mare", comuna: "Bretea Romana" },
  { nume: "Ocolişu Mic", simplu: "Ocolisu Mic", comuna: "Orastioara De Sus" },
  {
    nume: "Ohaba de Sub Piatră",
    simplu: "Ohaba de Sub Piatra",
    comuna: "Salasu De Sus",
  },
  { nume: "Ohaba Streiului", comuna: "Calan" },
  { nume: "Ohaba-Ponor", comuna: "Pui" },
  { nume: "Ohaba-Sibişel", simplu: "Ohaba-Sibisel", comuna: "Rau De Mori" },
  { nume: "Ohaba", comuna: "Lapugiu De Jos" },
  { nume: "Oprişeşti", simplu: "Oprisesti", comuna: "Balsa" },
  { nume: "Orăştie", simplu: "Orastie" },
  { nume: "Orăştioara de Jos", simplu: "Orastioara de Jos", comuna: "Beriu" },
  { nume: "Orăştioara de Sus", simplu: "Orastioara de Sus" },
  { nume: "Ormindea", comuna: "Baita" },
  { nume: "Ostrov", comuna: "Rau De Mori" },
  { nume: "Ostrovel", comuna: "Rau De Mori" },
  { nume: "Ostrovu Mic", comuna: "Rau De Mori" },
  { nume: "Păclişa", simplu: "Paclisa", comuna: "Totesti" },
  { nume: "Panc-Sălişte", simplu: "Panc-Saliste", comuna: "Dobra" },
  { nume: "Panc", comuna: "Dobra" },
  { nume: "Paroş", simplu: "Paros", comuna: "Salasu De Sus" },
  { nume: "Păucineşti", simplu: "Paucinesti", comuna: "Sarmizegetusa" },
  { nume: "Păuleşti", simplu: "Paulesti", comuna: "Bulzestii De Sus" },
  { nume: "Păuliş", simplu: "Paulis", comuna: "Soimus" },
  { nume: "Peşteana", simplu: "Pesteana", comuna: "Densus" },
  { nume: "Peşteniţa", simplu: "Pestenita", comuna: "Densus" },
  { nume: "Peştera", simplu: "Pestera", comuna: "Baita" },
  { nume: "Peştera", simplu: "Pestera", comuna: "Petrosani" },
  { nume: "Peştera", simplu: "Pestera", comuna: "Salasu De Sus" },
  { nume: "Peştişu Mare", simplu: "Pestisu Mare", comuna: "Hunedoara" },
  { nume: "Pestişu Mic", simplu: "Pestisu Mic" },
  { nume: "Petreni", comuna: "Bacia" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Burjuc" },
  { nume: "Petrila" },
  { nume: "Petros", comuna: "Baru" },
  { nume: "Petroşani", simplu: "Petrosani" },
  { nume: "Piatra", comuna: "Batrana" },
  { nume: "Pişchinţi", simplu: "Pischinti", comuna: "Romos" },
  { nume: "Plai", comuna: "Blajeni" },
  { nume: "Plop", comuna: "Ghelari" },
  { nume: "Plopi", comuna: "Bretea Romana" },
  { nume: "Podele", comuna: "Luncoiu De Jos" },
  { nume: "Pogăneşti", simplu: "Poganesti", comuna: "Zam" },
  { nume: "Poiana Răchiţelii", simplu: "Poiana Rachitelii", comuna: "Cerbal" },
  { nume: "Poiana", comuna: "Balsa" },
  { nume: "Poieni", comuna: "Beriu" },
  { nume: "Poieni", comuna: "Densus" },
  { nume: "Poieniţa Tomii", simplu: "Poienita Tomii", comuna: "Cerbal" },
  { nume: "Poieniţa Voinii", simplu: "Poienita Voinii", comuna: "Bunila" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Balsa" },
  { nume: "Pojoga", comuna: "Zam" },
  { nume: "Ponor", comuna: "Pui" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Carjiti" },
  { nume: "Potingani", comuna: "Brad" },
  { nume: "Prăvăleni", simplu: "Pravaleni", comuna: "Vata De Jos" },
  { nume: "Pricaz", comuna: "Turdas" },
  { nume: "Prihodişte", simplu: "Prihodiste", comuna: "Bosorod" },
  { nume: "Prihodişte", simplu: "Prihodiste", comuna: "Vata De Jos" },
  { nume: "Pui" },
  { nume: "Răcăştia", simplu: "Racastia", comuna: "Hunedoara" },
  { nume: "Răchiţaua", simplu: "Rachitaua", comuna: "Batrana" },
  { nume: "Răchitova", simplu: "Rachitova" },
  { nume: "Răduleşti", simplu: "Radulesti", comuna: "Dobra" },
  { nume: "Râpaş", simplu: "Rapas", comuna: "Turdas" },
  { nume: "Rapolţel", simplu: "Rapoltel", comuna: "Rapoltu Mare" },
  { nume: "Rapoltu Mare" },
  { nume: "Răscoala", simplu: "Rascoala", comuna: "Petrila" },
  { nume: "Râu Alb", simplu: "Rau Alb", comuna: "Salasu De Sus" },
  { nume: "Râu Bărbat", simplu: "Rau Barbat", comuna: "Pui" },
  { nume: "Râu de Mori", simplu: "Rau de Mori" },
  { nume: "Râu Mic", simplu: "Rau Mic", comuna: "Salasu De Sus" },
  { nume: "Reea", comuna: "Totesti" },
  { nume: "Renghet", comuna: "Geoagiu" },
  { nume: "Reţ", simplu: "Ret", comuna: "Blajeni" },
  { nume: "Ribicioara", comuna: "Ribita" },
  { nume: "Ribiţa", simplu: "Ribita" },
  { nume: "Rişca", simplu: "Risca", comuna: "Baia De Cris" },
  { nume: "Rişculiţa", simplu: "Risculita", comuna: "Baia De Cris" },
  { nume: "Romos" },
  { nume: "Romoşel", simplu: "Romosel", comuna: "Romos" },
  { nume: "Roşcani", simplu: "Roscani", comuna: "Dobra" },
  { nume: "Roşia", simplu: "Rosia", comuna: "Balsa" },
  { nume: "Rovina", comuna: "Branisca" },
  { nume: "Rovina", comuna: "Bucuresci" },
  { nume: "Ruda-Brad", comuna: "Brad" },
  { nume: "Ruda", comuna: "Ghelari" },
  { nume: "Runcşor", simplu: "Runcsor", comuna: "Gurasada" },
  { nume: "Runcu Mare", comuna: "Lelese" },
  { nume: "Runcu Mic", comuna: "Vetel" },
  { nume: "Ruseşti", simplu: "Rusesti", comuna: "Bulzestii De Sus" },
  { nume: "Ruşi", simplu: "Rusi", comuna: "Bretea Romana" },
  { nume: "Ruşor", simplu: "Rusor", comuna: "Pui" },
  { nume: "Săcămaş", simplu: "Sacamas", comuna: "Ilia" },
  { nume: "Săcărâmb", simplu: "Sacaramb", comuna: "Certeju De Sus" },
  { nume: "Săcel", simplu: "Sacel", comuna: "Santamaria-Orlea" },
  { nume: "Sălaşu de Jos", simplu: "Salasu de Jos", comuna: "Salasu De Sus" },
  { nume: "Sălaşu de Sus", simplu: "Salasu de Sus" },
  { nume: "Sălătruc", simplu: "Salatruc", comuna: "Blajeni" },
  { nume: "Sălciva", simplu: "Salciva", comuna: "Zam" },
  { nume: "Sălişte", simplu: "Saliste", comuna: "Baita" },
  { nume: "Săliştioara", simplu: "Salistioara", comuna: "Valisoara" },
  { nume: "Sâncrai", simplu: "Sancrai", comuna: "Calan" },
  { nume: "Sânpetru", simplu: "Sanpetru", comuna: "Santamaria-Orlea" },
  {
    nume: "Sântămăria de Piatră",
    simplu: "Santamaria de Piatra",
    comuna: "Calan",
  },
  { nume: "Sântămăria-Orlea", simplu: "Santamaria-Orlea" },
  { nume: "Sântandrei", simplu: "Santandrei", comuna: "Simeria" },
  { nume: "Sântuhalm", simplu: "Santuhalm", comuna: "Deva" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Ilia" },
  { nume: "Sarmizegetusa" },
  { nume: "Şăuleşti", simplu: "Saulesti", comuna: "Simeria" },
  { nume: "Sereca", comuna: "Beriu" },
  { nume: "Şerel", simplu: "Serel", comuna: "Pui" },
  { nume: "Şesuri", simplu: "Sesuri", comuna: "Bucuresci" },
  { nume: "Sibişel", simplu: "Sibisel", comuna: "Beriu" },
  { nume: "Sibişel", simplu: "Sibisel", comuna: "Rau De Mori" },
  { nume: "Silvaşu de Jos", simplu: "Silvasu de Jos", comuna: "Hateg" },
  { nume: "Silvaşu de Sus", simplu: "Silvasu de Sus", comuna: "Hateg" },
  { nume: "Simeria Veche", comuna: "Simeria" },
  { nume: "Simeria" },
  { nume: "Slătinioara", simplu: "Slatinioara", comuna: "Petrosani" },
  { nume: "Socet", comuna: "Cerbal" },
  { nume: "Sohodol", comuna: "Lelese" },
  { nume: "Şoimuş", simplu: "Soimus" },
  { nume: "Spini", comuna: "Turdas" },
  { nume: "Stânceşti-Ohaba", simplu: "Stancesti-Ohaba", comuna: "Dobra" },
  { nume: "Stânceşti", simplu: "Stancesti", comuna: "Dobra" },
  { nume: "Stănculeşti", simplu: "Stanculesti", comuna: "Bulzestii De Sus" },
  { nume: "Stănija", simplu: "Stanija", comuna: "Buces" },
  { nume: "Stăuini", simplu: "Stauini", comuna: "Balsa" },
  { nume: "Ştei", simplu: "Stei", comuna: "Densus" },
  { nume: "Steia", comuna: "Tomesti" },
  { nume: "Stejărel", simplu: "Stejarel", comuna: "Luncoiu De Jos" },
  { nume: "Stoieneasa", comuna: "Valisoara" },
  { nume: "Strei-Săcel", simplu: "Strei-Sacel", comuna: "Calan" },
  { nume: "Strei", comuna: "Calan" },
  { nume: "Streisângeorgiu", simplu: "Streisangeorgiu", comuna: "Calan" },
  { nume: "Stretea", comuna: "Dobra" },
  { nume: "Subcetate", comuna: "Santamaria-Orlea" },
  { nume: "Sulighete", comuna: "Soimus" },
  { nume: "Suseni", comuna: "Rau De Mori" },
  { nume: "Tămăşasa", simplu: "Tamasasa", comuna: "Martinesti" },
  { nume: "Tămăşeşti", simplu: "Tamasesti", comuna: "Zam" },
  { nume: "Tâmpa", simplu: "Tampa", comuna: "Bacia" },
  { nume: "Ţărăţel", simplu: "Taratel", comuna: "Brad" },
  { nume: "Târnava de Criş", simplu: "Tarnava de Cris", comuna: "Vata De Jos" },
  { nume: "Târnava", simplu: "Tarnava", comuna: "Branisca" },
  { nume: "Târnăviţa", simplu: "Tarnavita", comuna: "Branisca" },
  { nume: "Tarniţa", simplu: "Tarnita", comuna: "Buces" },
  { nume: "Târsa", simplu: "Tarsa", comuna: "Bosorod" },
  { nume: "Tătărăşti", simplu: "Tatarasti", comuna: "Burjuc" },
  {
    nume: "Tătărăştii de Criş",
    simplu: "Tatarastii de Cris",
    comuna: "Vata De Jos",
  },
  { nume: "Ţebea", simplu: "Tebea", comuna: "Baia De Cris" },
  { nume: "Techereu", comuna: "Balsa" },
  { nume: "Teiu", comuna: "Lapugiu De Jos" },
  { nume: "Teliucu Inferior" },
  { nume: "Teliucu Superior", comuna: "Teliucu Inferior" },
  { nume: "Ticera", comuna: "Bulzestii De Sus" },
  { nume: "Tirici", comuna: "Petrila" },
  { nume: "Tisa", comuna: "Burjuc" },
  { nume: "Tiuleşti", simplu: "Tiulesti", comuna: "Tomesti" },
  { nume: "Tomeşti", simplu: "Tomesti" },
  { nume: "Tomnatec", comuna: "Bulzestii De Sus" },
  {
    nume: "Topliţa Mureşului",
    simplu: "Toplita Muresului",
    comuna: "Certeju De Sus",
  },
  { nume: "Topliţa", simplu: "Toplita" },
  { nume: "Toteşti", simplu: "Totesti" },
  { nume: "Totia", comuna: "Bacia" },
  { nume: "Trestia", comuna: "Baita" },
  { nume: "Turdaş", simplu: "Turdas" },
  { nume: "Turmaş", simplu: "Turmas", comuna: "Martinesti" },
  { nume: "Tuştea", simplu: "Tustea", comuna: "General Berthelot" },
  { nume: "Uibăreşti", simplu: "Uibaresti", comuna: "Ribita" },
  { nume: "Ulieş", simplu: "Ulies", comuna: "Gurasada" },
  { nume: "Ulm", comuna: "Cerbal" },
  { nume: "Unciuc", comuna: "Rau De Mori" },
  { nume: "Uric", comuna: "Pui" },
  { nume: "Uricani" },
  { nume: "Uroi", comuna: "Simeria" },
  { nume: "Ursici", comuna: "Bosorod" },
  { nume: "Vadu Dobrii", comuna: "Bunila" },
  { nume: "Vadu", comuna: "Santamaria-Orlea" },
  { nume: "Vaidei", comuna: "Romos" },
  { nume: "Vălari", simplu: "Valari", comuna: "Toplita" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Bretea Romana" },
  { nume: "Vâlcelele Bune", simplu: "Valcelele Bune", comuna: "Bretea Romana" },
  { nume: "Vâlceluţa", simplu: "Valceluta", comuna: "Bretea Romana" },
  { nume: "Valea Arsului", comuna: "Criscior" },
  { nume: "Valea Babii", comuna: "Lunca Cernii De Jos" },
  { nume: "Valea Bradului", comuna: "Brad" },
  { nume: "Valea Dâljii", simplu: "Valea Daljii", comuna: "Rau De Mori" },
  { nume: "Valea de Brazi", comuna: "Uricani" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Ilia" },
  { nume: "Valea Lupului", comuna: "Baru" },
  {
    nume: "Valea Mare de Criş",
    simplu: "Valea Mare de Cris",
    comuna: "Tomesti",
  },
  { nume: "Valea Nandrului", comuna: "Pestisu Mic" },
  { nume: "Valea Poienii", comuna: "Vorta" },
  {
    nume: "Valea Sângeorgiului",
    simplu: "Valea Sangeorgiului",
    comuna: "Calan",
  },
  { nume: "Valea", comuna: "Zam" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Baia De Cris" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Geoagiu" },
  { nume: "Vălioara", simplu: "Valioara", comuna: "Rachitova" },
  { nume: "Vălişoara", simplu: "Valisoara" },
  { nume: "Vălişoara", simplu: "Valisoara", comuna: "Balsa" },
  { nume: "Vărmaga", simplu: "Varmaga", comuna: "Certeju De Sus" },
  { nume: "Vaţa de Jos", simplu: "Vata de Jos" },
  { nume: "Vaţa de Sus", simplu: "Vata de Sus", comuna: "Vata De Jos" },
  { nume: "Veţel", simplu: "Vetel" },
  { nume: "Vica", comuna: "Gurasada" },
  { nume: "Visca", comuna: "Vorta" },
  { nume: "Voia", comuna: "Balsa" },
  { nume: "Vorţa", simplu: "Vorta" },
  { nume: "Vulcan" },
  { nume: "Zam" },
  { nume: "Zăvoi", simplu: "Zavoi", comuna: "Salasu De Sus" },
  { nume: "Zdrapţi", simplu: "Zdrapti", comuna: "Criscior" },
  { nume: "Zeicani", comuna: "Sarmizegetusa" },
];
