export const hd = [
  { nume: "Abucea", comuna: "Dobra" },
  { nume: "Almaș-Săliște", simplu: "Almas-Saliste", comuna: "Zam" },
  { nume: "Almășel", simplu: "Almasel", comuna: "Zam" },
  {
    nume: "Almașu Mic de Munte",
    simplu: "Almasu Mic de Munte",
    comuna: "Balsa",
  },
  { nume: "Almașu Mic", simplu: "Almasu Mic", comuna: "Pestisu Mic" },
  { nume: "Almașu Sec", simplu: "Almasu Sec", comuna: "Carjiti" },
  { nume: "Alun", comuna: "Bosorod" },
  { nume: "Alun", comuna: "Bunila" },
  { nume: "Aninoasa" },
  { nume: "Arănieș", simplu: "Aranies", comuna: "Cerbal" },
  { nume: "Archia", comuna: "Deva" },
  { nume: "Ardeu", comuna: "Balsa" },
  { nume: "Aurel Vlaicu", comuna: "Geoagiu" },
  { nume: "Bacâia", simplu: "Bacaia", comuna: "Geoagiu" },
  { nume: "Bacea", comuna: "Ilia" },
  { nume: "Băcia", simplu: "Bacia" },
  { nume: "Baia de Criș", simplu: "Baia de Cris" },
  { nume: "Băiești", simplu: "Baiesti", comuna: "Pui" },
  { nume: "Băița", simplu: "Baita" },
  { nume: "Bălata", simplu: "Balata", comuna: "Soimus" },
  { nume: "Baldovin", comuna: "Baia De Cris" },
  { nume: "Balomir", comuna: "Santamaria-Orlea" },
  { nume: "Balșa", simplu: "Balsa" },
  { nume: "Bănița", simplu: "Banita" },
  { nume: "Banpotoc", comuna: "Harau" },
  {
    nume: "Bărăștii Hațegului",
    simplu: "Barastii Hategului",
    comuna: "Santamaria-Orlea",
  },
  { nume: "Bărăștii Iliei", simplu: "Barastii Iliei", comuna: "Branisca" },
  { nume: "Barbura", comuna: "Baita" },
  { nume: "Bârcea Mare", simplu: "Barcea Mare", comuna: "Simeria" },
  { nume: "Bârcea Mică", simplu: "Barcea Mica", comuna: "Deva" },
  { nume: "Bârsău", simplu: "Barsau", comuna: "Harau" },
  { nume: "Baru" },
  { nume: "Barza", comuna: "Criscior" },
  { nume: "Basarabasa", comuna: "Vata De Jos" },
  { nume: "Baștea", simplu: "Bastea", comuna: "Lapugiu De Jos" },
  { nume: "Bățălar", simplu: "Batalar", comuna: "Bretea Romana" },
  { nume: "Batiz", comuna: "Calan" },
  { nume: "Bătrâna", simplu: "Batrana" },
  { nume: "Bejan-Târnăvița", simplu: "Bejan-Tarnavita", comuna: "Soimus" },
  { nume: "Bejan", comuna: "Soimus" },
  { nume: "Bercu", comuna: "Bretea Romana" },
  { nume: "Beriu" },
  { nume: "Birtin", comuna: "Vata De Jos" },
  { nume: "Blăjeni-Vulcan", simplu: "Blajeni-Vulcan", comuna: "Blajeni" },
  { nume: "Blăjeni", simplu: "Blajeni" },
  { nume: "Bobaia", comuna: "Bosorod" },
  { nume: "Bobâlna", simplu: "Bobalna", comuna: "Rapoltu Mare" },
  { nume: "Bocșa Mare", simplu: "Bocsa Mare", comuna: "Certeju De Sus" },
  { nume: "Bocșa Mică", simplu: "Bocsa Mica", comuna: "Certeju De Sus" },
  { nume: "Boholț", simplu: "Boholt", comuna: "Soimus" },
  { nume: "Boia Bârzii", simplu: "Boia Barzii", comuna: "Vetel" },
  { nume: "Boița", simplu: "Boita", comuna: "Rachitova" },
  { nume: "Boiu de Jos", comuna: "Gurasada" },
  { nume: "Boiu de Sus", comuna: "Gurasada" },
  { nume: "Boiu", comuna: "Rapoltu Mare" },
  { nume: "Boș", simplu: "Bos", comuna: "Hunedoara" },
  { nume: "Boșorod", simplu: "Bosorod" },
  { nume: "Boz", comuna: "Branisca" },
  { nume: "Bozeș", simplu: "Bozes", comuna: "Geoagiu" },
  { nume: "Brad" },
  { nume: "Brădățel", simplu: "Bradatel", comuna: "Burjuc" },
  { nume: "Brănișca", simplu: "Branisca" },
  { nume: "Brășeu", simplu: "Braseu", comuna: "Zam" },
  { nume: "Brazi", comuna: "Rau De Mori" },
  { nume: "Brâznic", simplu: "Braznic", comuna: "Ilia" },
  { nume: "Breazova", comuna: "Sarmizegetusa" },
  { nume: "Bretea Mureșană", simplu: "Bretea Muresana", comuna: "Ilia" },
  { nume: "Bretea Română", simplu: "Bretea Romana" },
  { nume: "Bretea Streiului", comuna: "Bretea Romana" },
  { nume: "Bretelin", comuna: "Vetel" },
  { nume: "Brotuna", comuna: "Vata De Jos" },
  { nume: "Buceș-Vulcan", simplu: "Buces-Vulcan", comuna: "Buces" },
  { nume: "Buceș", simplu: "Buces" },
  { nume: "Bucium-Orlea", comuna: "Santamaria-Orlea" },
  { nume: "Bucium", comuna: "Orastioara De Sus" },
  { nume: "Bucureșci", simplu: "Bucuresci" },
  { nume: "Bujoru", comuna: "Dobra" },
  {
    nume: "Bulzeștii de Jos",
    simplu: "Bulzestii de Jos",
    comuna: "Bulzestii De Sus",
  },
  { nume: "Bulzeștii de Sus", simplu: "Bulzestii de Sus" },
  { nume: "Bunești", simplu: "Bunesti", comuna: "Balsa" },
  { nume: "Bunila" },
  { nume: "Burjuc" },
  { nume: "Căbești", simplu: "Cabesti", comuna: "Branisca" },
  { nume: "Căinelu de Jos", simplu: "Cainelu de Jos", comuna: "Soimus" },
  { nume: "Căinelu de Sus", simplu: "Cainelu de Sus", comuna: "Baita" },
  { nume: "Călan", simplu: "Calan" },
  { nume: "Călanu Mic", simplu: "Calanu Mic", comuna: "Calan" },
  { nume: "Câmpu lui Neag", simplu: "Campu lui Neag", comuna: "Uricani" },
  { nume: "Câmpuri de Sus", simplu: "Campuri de Sus", comuna: "Gurasada" },
  { nume: "Câmpuri-Surduc", simplu: "Campuri-Surduc", comuna: "Gurasada" },
  { nume: "Căoi", simplu: "Caoi", comuna: "Vetel" },
  { nume: "Căraci", simplu: "Caraci", comuna: "Baia De Cris" },
  { nume: "Cărăstău", simplu: "Carastau", comuna: "Baia De Cris" },
  { nume: "Cârjiți", simplu: "Carjiti" },
  { nume: "Cărmăzănești", simplu: "Carmazanesti", comuna: "Gurasada" },
  { nume: "Cârnești", simplu: "Carnesti", comuna: "Totesti" },
  { nume: "Cărpiniș", simplu: "Carpinis", comuna: "Simeria" },
  { nume: "Căstău", simplu: "Castau", comuna: "Beriu" },
  { nume: "Căzănești", simplu: "Cazanesti", comuna: "Vata De Jos" },
  { nume: "Cerbăl", simplu: "Cerbal" },
  { nume: "Cerbia", comuna: "Zam" },
  { nume: "Cerișor", simplu: "Cerisor", comuna: "Lelese" },
  {
    nume: "Cernișoara Florese",
    simplu: "Cernisoara Florese",
    comuna: "Bunila",
  },
  { nume: "Certeju de Jos", comuna: "Vorta" },
  { nume: "Certeju de Sus" },
  { nume: "Chergheș", simplu: "Cherghes", comuna: "Carjiti" },
  { nume: "Chimindia", comuna: "Harau" },
  { nume: "Chișcădaga", simplu: "Chiscadaga", comuna: "Soimus" },
  { nume: "Chitid", comuna: "Bosorod" },
  { nume: "Cigmău", simplu: "Cigmau", comuna: "Geoagiu" },
  { nume: "Cimpa", comuna: "Petrila" },
  { nume: "Cinciș-Cerna", simplu: "Cincis-Cerna", comuna: "Teliucu Inferior" },
  { nume: "Cioclovina", comuna: "Bosorod" },
  { nume: "Ciopeia", comuna: "Santamaria-Orlea" },
  { nume: "Ciula Mare", comuna: "Rachitova" },
  { nume: "Ciula Mică", simplu: "Ciula Mica", comuna: "Rachitova" },
  { nume: "Ciulpăz", simplu: "Ciulpaz", comuna: "Pestisu Mic" },
  { nume: "Ciumița", simplu: "Ciumita", comuna: "Lunca Cernii De Jos" },
  { nume: "Ciungani", comuna: "Vata De Jos" },
  { nume: "Ciungu Mare", comuna: "Romos" },
  { nume: "Clopotiva", comuna: "Rau De Mori" },
  { nume: "Coaja", comuna: "Vorta" },
  { nume: "Copaci", comuna: "Totesti" },
  { nume: "Coroiești", simplu: "Coroiesti", comuna: "Salasu De Sus" },
  { nume: "Cosești", simplu: "Cosesti", comuna: "Lapugiu De Jos" },
  {
    nume: "Costești-Deal",
    simplu: "Costesti-Deal",
    comuna: "Orastioara De Sus",
  },
  { nume: "Costești", simplu: "Costesti", comuna: "Orastioara De Sus" },
  { nume: "Covragiu", comuna: "Bretea Romana" },
  { nume: "Cozia", comuna: "Carjiti" },
  { nume: "Crăciunești", simplu: "Craciunesti", comuna: "Baita" },
  { nume: "Crăguiș", simplu: "Craguis", comuna: "General Berthelot" },
  { nume: "Criș", simplu: "Cris", comuna: "Blajeni" },
  { nume: "Crișan", simplu: "Crisan", comuna: "Ribita" },
  { nume: "Crișcior", simplu: "Criscior" },
  { nume: "Cristur", comuna: "Deva" },
  { nume: "Criva", comuna: "Densus" },
  { nume: "Crivadia", comuna: "Banita" },
  { nume: "Cucuiș", simplu: "Cucuis", comuna: "Beriu" },
  { nume: "Cuieș", simplu: "Cuies", comuna: "Ilia" },
  { nume: "Curechiu", comuna: "Bucuresci" },
  {
    nume: "Curpenii Silvașului",
    simplu: "Curpenii Silvasului",
    comuna: "Toplita",
  },
  { nume: "Cutin", comuna: "Pestisu Mic" },
  { nume: "Dăbâca", simplu: "Dabaca", comuna: "Toplita" },
  { nume: "Dâlja Mare", simplu: "Dalja Mare", comuna: "Petrosani" },
  { nume: "Dâlja Mică", simplu: "Dalja Mica", comuna: "Petrosani" },
  { nume: "Dâncu Mare", simplu: "Dancu Mare", comuna: "Martinesti" },
  { nume: "Dâncu Mic", simplu: "Dancu Mic", comuna: "Martinesti" },
  { nume: "Dănulești", simplu: "Danulesti", comuna: "Gurasada" },
  { nume: "Dealu Babii", comuna: "Vulcan" },
  { nume: "Dealu Mare", comuna: "Valisoara" },
  { nume: "Dealu Mic", comuna: "Toplita" },
  { nume: "Deleni", comuna: "Zam" },
  { nume: "Densuș", simplu: "Densus" },
  { nume: "Deva" },
  { nume: "Dobra" },
  { nume: "Dobroț", simplu: "Dobrot", comuna: "Tomesti" },
  { nume: "Dragu-Brad", comuna: "Blajeni" },
  { nume: "Dudești", simplu: "Dudesti", comuna: "Luncoiu De Jos" },
  { nume: "Dumbrava de Jos", comuna: "Ribita" },
  { nume: "Dumbrava de Sus", comuna: "Ribita" },
  { nume: "Dumbrava", comuna: "Pestisu Mic" },
  { nume: "Dumbrăvița", simplu: "Dumbravita", comuna: "Ilia" },
  { nume: "Dumești", simplu: "Dumesti", comuna: "Vorta" },
  { nume: "Dupăpiatră", simplu: "Dupapiatra", comuna: "Buces" },
  { nume: "Făgețel", simplu: "Fagetel", comuna: "Dobra" },
  { nume: "Fântâna", simplu: "Fantana", comuna: "Lunca Cernii De Jos" },
  { nume: "Fărcădin", simplu: "Farcadin", comuna: "General Berthelot" },
  { nume: "Fața Roșie", simplu: "Fata Rosie", comuna: "Batrana" },
  { nume: "Federi", comuna: "Pui" },
  { nume: "Feregi", comuna: "Cerbal" },
  { nume: "Fintoag", comuna: "Lapugiu De Jos" },
  { nume: "Fizeș", simplu: "Fizes", comuna: "Baita" },
  { nume: "Fizești", simplu: "Fizesti", comuna: "Pui" },
  { nume: "Folt", comuna: "Rapoltu Mare" },
  { nume: "Fornădia", simplu: "Fornadia", comuna: "Soimus" },
  { nume: "Furcșoara", simplu: "Furcsoara", comuna: "Branisca" },
  { nume: "Galați", simplu: "Galati", comuna: "Pui" },
  { nume: "Galbina", comuna: "Balsa" },
  { nume: "Gânțaga", simplu: "Gantaga", comuna: "Bretea Romana" },
  { nume: "Gelmar", comuna: "Geoagiu" },
  { nume: "General Berthelot" },
  { nume: "Geoagiu-Băi", simplu: "Geoagiu-Bai", comuna: "Geoagiu" },
  { nume: "Geoagiu" },
  { nume: "Ghelari" },
  { nume: "Gialacuta", comuna: "Branisca" },
  { nume: "Giurgești", simplu: "Giurgesti", comuna: "Bulzestii De Sus" },
  { nume: "Glodghilești", simplu: "Glodghilesti", comuna: "Burjuc" },
  { nume: "Godinești", simplu: "Godinesti", comuna: "Zam" },
  { nume: "Goleș", simplu: "Goles", comuna: "Toplita" },
  { nume: "Gotești", simplu: "Gotesti", comuna: "Rachitova" },
  { nume: "Gothatea", comuna: "Gurasada" },
  { nume: "Govăjdia", simplu: "Govajdia", comuna: "Ghelari" },
  {
    nume: "Grădiștea de Munte",
    simplu: "Gradistea de Munte",
    comuna: "Orastioara De Sus",
  },
  { nume: "Grid", comuna: "Calan" },
  { nume: "Grind", comuna: "Lapugiu De Jos" },
  { nume: "Grohot", comuna: "Bulzestii De Sus" },
  { nume: "Grohoțele", simplu: "Grohotele", comuna: "Buces" },
  { nume: "Groș", simplu: "Gros", comuna: "Hunedoara" },
  { nume: "Groșuri", simplu: "Grosuri", comuna: "Blajeni" },
  { nume: "Gura Bordului", comuna: "Lunca Cernii De Jos" },
  { nume: "Gurasada" },
  { nume: "Hărău", simplu: "Harau" },
  { nume: "Hărțăgani", simplu: "Hartagani", comuna: "Baita" },
  { nume: "Hășdat", simplu: "Hasdat", comuna: "Hunedoara" },
  { nume: "Hășdău", simplu: "Hasdau", comuna: "Toplita" },
  { nume: "Hățăgel", simplu: "Hatagel", comuna: "Densus" },
  { nume: "Hațeg", simplu: "Hateg" },
  { nume: "Herepeia", comuna: "Vetel" },
  {
    nume: "Hobița-Grădiște",
    simplu: "Hobita-Gradiste",
    comuna: "Sarmizegetusa",
  },
  { nume: "Hobița", simplu: "Hobita", comuna: "Pui" },
  { nume: "Holdea", comuna: "Lapugiu De Jos" },
  { nume: "Homorod", comuna: "Geoagiu" },
  { nume: "Hondol", comuna: "Certeju De Sus" },
  { nume: "Hunedoara" },
  { nume: "Ilia" },
  { nume: "Iscroni", comuna: "Aninoasa" },
  { nume: "Izvoarele", comuna: "Teliucu Inferior" },
  { nume: "Jeledinți", simplu: "Jeledinti", comuna: "Martinesti" },
  { nume: "Jieț", simplu: "Jiet", comuna: "Petrila" },
  { nume: "Jiu-Paroșeni", simplu: "Jiu-Paroseni", comuna: "Vulcan" },
  { nume: "Josani", comuna: "Pestisu Mic" },
  { nume: "Lăpugiu de Jos", simplu: "Lapugiu de Jos" },
  {
    nume: "Lăpugiu de Sus",
    simplu: "Lapugiu de Sus",
    comuna: "Lapugiu De Jos",
  },
  { nume: "Lăpușnic", simplu: "Lapusnic", comuna: "Dobra" },
  { nume: "Lăsău", simplu: "Lasau", comuna: "Lapugiu De Jos" },
  { nume: "Leauț", simplu: "Leaut", comuna: "Tomesti" },
  { nume: "Lelese" },
  { nume: "Leșnic", simplu: "Lesnic", comuna: "Vetel" },
  { nume: "Livada", comuna: "Tomesti" },
  { nume: "Livadia", comuna: "Baru" },
  { nume: "Livezi", comuna: "General Berthelot" },
  {
    nume: "Ludeștii de Jos",
    simplu: "Ludestii de Jos",
    comuna: "Orastioara De Sus",
  },
  {
    nume: "Ludeștii de Sus",
    simplu: "Ludestii de Sus",
    comuna: "Orastioara De Sus",
  },
  { nume: "Lunca Cernii de Jos" },
  { nume: "Lunca Cernii de Sus", comuna: "Lunca Cernii De Jos" },
  { nume: "Lunca", comuna: "Baia De Cris" },
  { nume: "Lunca", comuna: "Baita" },
  { nume: "Luncani", comuna: "Bosorod" },
  { nume: "Luncoiu de Jos" },
  { nume: "Luncoiu de Sus", comuna: "Luncoiu De Jos" },
  { nume: "Luncșoara", simplu: "Luncsoara", comuna: "Vorta" },
  { nume: "Lupeni" },
  { nume: "Măceu", simplu: "Maceu", comuna: "Bretea Romana" },
  { nume: "Mada", comuna: "Balsa" },
  {
    nume: "Măgura-Toplița",
    simplu: "Magura-Toplita",
    comuna: "Certeju De Sus",
  },
  { nume: "Măgura", simplu: "Magura", comuna: "Martinesti" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Beriu" },
  { nume: "Mălăiești", simplu: "Malaiesti", comuna: "Salasu De Sus" },
  { nume: "Mănerău", simplu: "Manerau", comuna: "Pestisu Mic" },
  { nume: "Mărtinești", simplu: "Martinesti" },
  { nume: "Meria", comuna: "Lunca Cernii De Jos" },
  { nume: "Merișor", simplu: "Merisor", comuna: "Banita" },
  { nume: "Merișor", simplu: "Merisor", comuna: "Bucuresci" },
  { nume: "Merișoru de Munte", simplu: "Merisoru de Munte", comuna: "Cerbal" },
  { nume: "Mermezeu-Văleni", simplu: "Mermezeu-Valeni", comuna: "Geoagiu" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Brad" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Rachitova" },
  { nume: "Micănești", simplu: "Micanesti", comuna: "Zam" },
  { nume: "Mihăiești", simplu: "Mihaiesti", comuna: "Dobra" },
  { nume: "Mihăileni", simplu: "Mihaileni", comuna: "Buces" },
  { nume: "Mintia", comuna: "Vetel" },
  { nume: "Mosoru", comuna: "Toplita" },
  { nume: "Muncelu Mare", comuna: "Vetel" },
  { nume: "Muncelu Mic", comuna: "Vetel" },
  { nume: "Nădăștia de Jos", simplu: "Nadastia de Jos", comuna: "Calan" },
  { nume: "Nădăștia de Sus", simplu: "Nadastia de Sus", comuna: "Calan" },
  { nume: "Nălațvad", simplu: "Nalatvad", comuna: "Hateg" },
  { nume: "Nandru", comuna: "Pestisu Mic" },
  { nume: "Negoiu", comuna: "Lunca Cernii De Jos" },
  { nume: "Nojag", comuna: "Certeju De Sus" },
  { nume: "Nucșoara", simplu: "Nucsoara", comuna: "Salasu De Sus" },
  { nume: "Obârșa", simplu: "Obarsa", comuna: "Tomesti" },
  { nume: "Ocișor", simplu: "Ocisor", comuna: "Vata De Jos" },
  { nume: "Ociu", comuna: "Vata De Jos" },
  { nume: "Ocolișu Mare", simplu: "Ocolisu Mare", comuna: "Bretea Romana" },
  { nume: "Ocolișu Mic", simplu: "Ocolisu Mic", comuna: "Orastioara De Sus" },
  {
    nume: "Ohaba de Sub Piatră",
    simplu: "Ohaba de Sub Piatra",
    comuna: "Salasu De Sus",
  },
  { nume: "Ohaba Streiului", comuna: "Calan" },
  { nume: "Ohaba-Ponor", comuna: "Pui" },
  { nume: "Ohaba-Sibișel", simplu: "Ohaba-Sibisel", comuna: "Rau De Mori" },
  { nume: "Ohaba", comuna: "Lapugiu De Jos" },
  { nume: "Oprișești", simplu: "Oprisesti", comuna: "Balsa" },
  { nume: "Orăștie", simplu: "Orastie" },
  { nume: "Orăștioara de Jos", simplu: "Orastioara de Jos", comuna: "Beriu" },
  { nume: "Orăștioara de Sus", simplu: "Orastioara de Sus" },
  { nume: "Ormindea", comuna: "Baita" },
  { nume: "Ostrov", comuna: "Rau De Mori" },
  { nume: "Ostrovel", comuna: "Rau De Mori" },
  { nume: "Ostrovu Mic", comuna: "Rau De Mori" },
  { nume: "Păclișa", simplu: "Paclisa", comuna: "Totesti" },
  { nume: "Panc-Săliște", simplu: "Panc-Saliste", comuna: "Dobra" },
  { nume: "Panc", comuna: "Dobra" },
  { nume: "Paroș", simplu: "Paros", comuna: "Salasu De Sus" },
  { nume: "Păucinești", simplu: "Paucinesti", comuna: "Sarmizegetusa" },
  { nume: "Păulești", simplu: "Paulesti", comuna: "Bulzestii De Sus" },
  { nume: "Păuliș", simplu: "Paulis", comuna: "Soimus" },
  { nume: "Peșteana", simplu: "Pesteana", comuna: "Densus" },
  { nume: "Peștenița", simplu: "Pestenita", comuna: "Densus" },
  { nume: "Peștera", simplu: "Pestera", comuna: "Baita" },
  { nume: "Peștera", simplu: "Pestera", comuna: "Petrosani" },
  { nume: "Peștera", simplu: "Pestera", comuna: "Salasu De Sus" },
  { nume: "Peștișu Mare", simplu: "Pestisu Mare", comuna: "Hunedoara" },
  { nume: "Pestișu Mic", simplu: "Pestisu Mic" },
  { nume: "Petreni", comuna: "Bacia" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Burjuc" },
  { nume: "Petrila" },
  { nume: "Petros", comuna: "Baru" },
  { nume: "Petroșani", simplu: "Petrosani" },
  { nume: "Piatra", comuna: "Batrana" },
  { nume: "Pișchinți", simplu: "Pischinti", comuna: "Romos" },
  { nume: "Plai", comuna: "Blajeni" },
  { nume: "Plop", comuna: "Ghelari" },
  { nume: "Plopi", comuna: "Bretea Romana" },
  { nume: "Podele", comuna: "Luncoiu De Jos" },
  { nume: "Pogănești", simplu: "Poganesti", comuna: "Zam" },
  { nume: "Poiana Răchițelii", simplu: "Poiana Rachitelii", comuna: "Cerbal" },
  { nume: "Poiana", comuna: "Balsa" },
  { nume: "Poieni", comuna: "Beriu" },
  { nume: "Poieni", comuna: "Densus" },
  { nume: "Poienița Tomii", simplu: "Poienita Tomii", comuna: "Cerbal" },
  { nume: "Poienița Voinii", simplu: "Poienita Voinii", comuna: "Bunila" },
  { nume: "Poienița", simplu: "Poienita", comuna: "Balsa" },
  { nume: "Pojoga", comuna: "Zam" },
  { nume: "Ponor", comuna: "Pui" },
  { nume: "Popești", simplu: "Popesti", comuna: "Carjiti" },
  { nume: "Potingani", comuna: "Brad" },
  { nume: "Prăvăleni", simplu: "Pravaleni", comuna: "Vata De Jos" },
  { nume: "Pricaz", comuna: "Turdas" },
  { nume: "Prihodiște", simplu: "Prihodiste", comuna: "Bosorod" },
  { nume: "Prihodiște", simplu: "Prihodiste", comuna: "Vata De Jos" },
  { nume: "Pui" },
  { nume: "Răcăștia", simplu: "Racastia", comuna: "Hunedoara" },
  { nume: "Răchițaua", simplu: "Rachitaua", comuna: "Batrana" },
  { nume: "Răchitova", simplu: "Rachitova" },
  { nume: "Rădulești", simplu: "Radulesti", comuna: "Dobra" },
  { nume: "Râpaș", simplu: "Rapas", comuna: "Turdas" },
  { nume: "Rapolțel", simplu: "Rapoltel", comuna: "Rapoltu Mare" },
  { nume: "Rapoltu Mare" },
  { nume: "Răscoala", simplu: "Rascoala", comuna: "Petrila" },
  { nume: "Râu Alb", simplu: "Rau Alb", comuna: "Salasu De Sus" },
  { nume: "Râu Bărbat", simplu: "Rau Barbat", comuna: "Pui" },
  { nume: "Râu de Mori", simplu: "Rau de Mori" },
  { nume: "Râu Mic", simplu: "Rau Mic", comuna: "Salasu De Sus" },
  { nume: "Reea", comuna: "Totesti" },
  { nume: "Renghet", comuna: "Geoagiu" },
  { nume: "Reț", simplu: "Ret", comuna: "Blajeni" },
  { nume: "Ribicioara", comuna: "Ribita" },
  { nume: "Ribița", simplu: "Ribita" },
  { nume: "Rișca", simplu: "Risca", comuna: "Baia De Cris" },
  { nume: "Rișculița", simplu: "Risculita", comuna: "Baia De Cris" },
  { nume: "Romos" },
  { nume: "Romoșel", simplu: "Romosel", comuna: "Romos" },
  { nume: "Roșcani", simplu: "Roscani", comuna: "Dobra" },
  { nume: "Roșia", simplu: "Rosia", comuna: "Balsa" },
  { nume: "Rovina", comuna: "Branisca" },
  { nume: "Rovina", comuna: "Bucuresci" },
  { nume: "Ruda-Brad", comuna: "Brad" },
  { nume: "Ruda", comuna: "Ghelari" },
  { nume: "Runcșor", simplu: "Runcsor", comuna: "Gurasada" },
  { nume: "Runcu Mare", comuna: "Lelese" },
  { nume: "Runcu Mic", comuna: "Vetel" },
  { nume: "Rusești", simplu: "Rusesti", comuna: "Bulzestii De Sus" },
  { nume: "Ruși", simplu: "Rusi", comuna: "Bretea Romana" },
  { nume: "Rușor", simplu: "Rusor", comuna: "Pui" },
  { nume: "Săcămaș", simplu: "Sacamas", comuna: "Ilia" },
  { nume: "Săcărâmb", simplu: "Sacaramb", comuna: "Certeju De Sus" },
  { nume: "Săcel", simplu: "Sacel", comuna: "Santamaria-Orlea" },
  { nume: "Sălașu de Jos", simplu: "Salasu de Jos", comuna: "Salasu De Sus" },
  { nume: "Sălașu de Sus", simplu: "Salasu de Sus" },
  { nume: "Sălătruc", simplu: "Salatruc", comuna: "Blajeni" },
  { nume: "Sălciva", simplu: "Salciva", comuna: "Zam" },
  { nume: "Săliște", simplu: "Saliste", comuna: "Baita" },
  { nume: "Săliștioara", simplu: "Salistioara", comuna: "Valisoara" },
  { nume: "Sâncrai", simplu: "Sancrai", comuna: "Calan" },
  { nume: "Sânpetru", simplu: "Sanpetru", comuna: "Santamaria-Orlea" },
  {
    nume: "Sântămăria de Piatră",
    simplu: "Santamaria de Piatra",
    comuna: "Calan",
  },
  { nume: "Sântămăria-Orlea", simplu: "Santamaria-Orlea" },
  { nume: "Sântandrei", simplu: "Santandrei", comuna: "Simeria" },
  { nume: "Sântuhalm", simplu: "Santuhalm", comuna: "Deva" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Ilia" },
  { nume: "Sarmizegetusa" },
  { nume: "Șăulești", simplu: "Saulesti", comuna: "Simeria" },
  { nume: "Sereca", comuna: "Beriu" },
  { nume: "Șerel", simplu: "Serel", comuna: "Pui" },
  { nume: "Șesuri", simplu: "Sesuri", comuna: "Bucuresci" },
  { nume: "Sibișel", simplu: "Sibisel", comuna: "Beriu" },
  { nume: "Sibișel", simplu: "Sibisel", comuna: "Rau De Mori" },
  { nume: "Silvașu de Jos", simplu: "Silvasu de Jos", comuna: "Hateg" },
  { nume: "Silvașu de Sus", simplu: "Silvasu de Sus", comuna: "Hateg" },
  { nume: "Simeria Veche", comuna: "Simeria" },
  { nume: "Simeria" },
  { nume: "Slătinioara", simplu: "Slatinioara", comuna: "Petrosani" },
  { nume: "Socet", comuna: "Cerbal" },
  { nume: "Sohodol", comuna: "Lelese" },
  { nume: "Șoimuș", simplu: "Soimus" },
  { nume: "Spini", comuna: "Turdas" },
  { nume: "Stâncești-Ohaba", simplu: "Stancesti-Ohaba", comuna: "Dobra" },
  { nume: "Stâncești", simplu: "Stancesti", comuna: "Dobra" },
  { nume: "Stănculești", simplu: "Stanculesti", comuna: "Bulzestii De Sus" },
  { nume: "Stănija", simplu: "Stanija", comuna: "Buces" },
  { nume: "Stăuini", simplu: "Stauini", comuna: "Balsa" },
  { nume: "Ștei", simplu: "Stei", comuna: "Densus" },
  { nume: "Steia", comuna: "Tomesti" },
  { nume: "Stejărel", simplu: "Stejarel", comuna: "Luncoiu De Jos" },
  { nume: "Stoieneasa", comuna: "Valisoara" },
  { nume: "Strei-Săcel", simplu: "Strei-Sacel", comuna: "Calan" },
  { nume: "Strei", comuna: "Calan" },
  { nume: "Streisângeorgiu", simplu: "Streisangeorgiu", comuna: "Calan" },
  { nume: "Stretea", comuna: "Dobra" },
  { nume: "Subcetate", comuna: "Santamaria-Orlea" },
  { nume: "Sulighete", comuna: "Soimus" },
  { nume: "Suseni", comuna: "Rau De Mori" },
  { nume: "Tămășasa", simplu: "Tamasasa", comuna: "Martinesti" },
  { nume: "Tămășești", simplu: "Tamasesti", comuna: "Zam" },
  { nume: "Tâmpa", simplu: "Tampa", comuna: "Bacia" },
  { nume: "Țărățel", simplu: "Taratel", comuna: "Brad" },
  { nume: "Târnava de Criș", simplu: "Tarnava de Cris", comuna: "Vata De Jos" },
  { nume: "Târnava", simplu: "Tarnava", comuna: "Branisca" },
  { nume: "Târnăvița", simplu: "Tarnavita", comuna: "Branisca" },
  { nume: "Tarnița", simplu: "Tarnita", comuna: "Buces" },
  { nume: "Târsa", simplu: "Tarsa", comuna: "Bosorod" },
  { nume: "Tătărăști", simplu: "Tatarasti", comuna: "Burjuc" },
  {
    nume: "Tătărăștii de Criș",
    simplu: "Tatarastii de Cris",
    comuna: "Vata De Jos",
  },
  { nume: "Țebea", simplu: "Tebea", comuna: "Baia De Cris" },
  { nume: "Techereu", comuna: "Balsa" },
  { nume: "Teiu", comuna: "Lapugiu De Jos" },
  { nume: "Teliucu Inferior" },
  { nume: "Teliucu Superior", comuna: "Teliucu Inferior" },
  { nume: "Ticera", comuna: "Bulzestii De Sus" },
  { nume: "Tirici", comuna: "Petrila" },
  { nume: "Tisa", comuna: "Burjuc" },
  { nume: "Tiulești", simplu: "Tiulesti", comuna: "Tomesti" },
  { nume: "Tomești", simplu: "Tomesti" },
  { nume: "Tomnatec", comuna: "Bulzestii De Sus" },
  {
    nume: "Toplița Mureșului",
    simplu: "Toplita Muresului",
    comuna: "Certeju De Sus",
  },
  { nume: "Toplița", simplu: "Toplita" },
  { nume: "Totești", simplu: "Totesti" },
  { nume: "Totia", comuna: "Bacia" },
  { nume: "Trestia", comuna: "Baita" },
  { nume: "Turdaș", simplu: "Turdas" },
  { nume: "Turmaș", simplu: "Turmas", comuna: "Martinesti" },
  { nume: "Tuștea", simplu: "Tustea", comuna: "General Berthelot" },
  { nume: "Uibărești", simplu: "Uibaresti", comuna: "Ribita" },
  { nume: "Ulieș", simplu: "Ulies", comuna: "Gurasada" },
  { nume: "Ulm", comuna: "Cerbal" },
  { nume: "Unciuc", comuna: "Rau De Mori" },
  { nume: "Uric", comuna: "Pui" },
  { nume: "Uricani" },
  { nume: "Uroi", comuna: "Simeria" },
  { nume: "Ursici", comuna: "Bosorod" },
  { nume: "Vadu Dobrii", comuna: "Bunila" },
  { nume: "Vadu", comuna: "Santamaria-Orlea" },
  { nume: "Vaidei", comuna: "Romos" },
  { nume: "Vălari", simplu: "Valari", comuna: "Toplita" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Bretea Romana" },
  { nume: "Vâlcelele Bune", simplu: "Valcelele Bune", comuna: "Bretea Romana" },
  { nume: "Vâlceluța", simplu: "Valceluta", comuna: "Bretea Romana" },
  { nume: "Valea Arsului", comuna: "Criscior" },
  { nume: "Valea Babii", comuna: "Lunca Cernii De Jos" },
  { nume: "Valea Bradului", comuna: "Brad" },
  { nume: "Valea Dâljii", simplu: "Valea Daljii", comuna: "Rau De Mori" },
  { nume: "Valea de Brazi", comuna: "Uricani" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Ilia" },
  { nume: "Valea Lupului", comuna: "Baru" },
  {
    nume: "Valea Mare de Criș",
    simplu: "Valea Mare de Cris",
    comuna: "Tomesti",
  },
  { nume: "Valea Nandrului", comuna: "Pestisu Mic" },
  { nume: "Valea Poienii", comuna: "Vorta" },
  {
    nume: "Valea Sângeorgiului",
    simplu: "Valea Sangeorgiului",
    comuna: "Calan",
  },
  { nume: "Valea", comuna: "Zam" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Baia De Cris" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Geoagiu" },
  { nume: "Vălioara", simplu: "Valioara", comuna: "Rachitova" },
  { nume: "Vălișoara", simplu: "Valisoara" },
  { nume: "Vălișoara", simplu: "Valisoara", comuna: "Balsa" },
  { nume: "Vărmaga", simplu: "Varmaga", comuna: "Certeju De Sus" },
  { nume: "Vața de Jos", simplu: "Vata de Jos" },
  { nume: "Vața de Sus", simplu: "Vata de Sus", comuna: "Vata De Jos" },
  { nume: "Vețel", simplu: "Vetel" },
  { nume: "Vica", comuna: "Gurasada" },
  { nume: "Visca", comuna: "Vorta" },
  { nume: "Voia", comuna: "Balsa" },
  { nume: "Vorța", simplu: "Vorta" },
  { nume: "Vulcan" },
  { nume: "Zam" },
  { nume: "Zăvoi", simplu: "Zavoi", comuna: "Salasu De Sus" },
  { nume: "Zdrapți", simplu: "Zdrapti", comuna: "Criscior" },
  { nume: "Zeicani", comuna: "Sarmizegetusa" },
];
