export const hr = [
  { nume: "Aldea", comuna: "Martinis" },
  { nume: "Alexandriţa", simplu: "Alexandrita", comuna: "Felicieni" },
  { nume: "Aluniş", simplu: "Alunis", comuna: "Mugeni" },
  { nume: "Andreeni", comuna: "Avramesti" },
  { nume: "Armăşeni", simplu: "Armaseni", comuna: "Ciucsangeorgiu" },
  { nume: "Armăşenii Noi", simplu: "Armasenii Noi", comuna: "Ciucsangeorgiu" },
  { nume: "Arvăţeni", simplu: "Arvateni", comuna: "Felicieni" },
  { nume: "Atia", comuna: "Corund" },
  { nume: "Atid" },
  { nume: "Avrămeşti", simplu: "Avramesti" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Martinis" },
  { nume: "Băile Chirui", simplu: "Baile Chirui", comuna: "Lueta" },
  { nume: "Băile Homorod", simplu: "Baile Homorod", comuna: "Vlahita" },
  { nume: "Băile Tuşnad", simplu: "Baile Tusnad" },
  { nume: "Bălan", simplu: "Balan" },
  { nume: "Bancu", comuna: "Ciucsangeorgiu" },
  { nume: "Baraţcoş", simplu: "Baratcos", comuna: "Lunca De Jos" },
  { nume: "Bârzava", simplu: "Barzava", comuna: "Frumoasa" },
  { nume: "Becaş", simplu: "Becas", comuna: "Praid" },
  { nume: "Benţid", simplu: "Bentid", comuna: "Simonesti" },
  { nume: "Beta", comuna: "Mugeni" },
  { nume: "Beteşti", simplu: "Betesti", comuna: "Mugeni" },
  { nume: "Bilbor" },
  { nume: "Bisericani", comuna: "Lupeni" },
  { nume: "Bodogaia", comuna: "Secuieni" },
  { nume: "Borsec" },
  { nume: "Borzont", comuna: "Joseni" },
  { nume: "Brădeşti", simplu: "Bradesti" },
  { nume: "Bucin", comuna: "Joseni" },
  { nume: "Bucin", comuna: "Praid" },
  { nume: "Bulgăreni", simplu: "Bulgareni", comuna: "Lupeni" },
  { nume: "Cădaciu Mare", simplu: "Cadaciu Mare", comuna: "Simonesti" },
  { nume: "Cădaciu Mic", simplu: "Cadaciu Mic", comuna: "Simonesti" },
  { nume: "Călimănel", simplu: "Calimanel", comuna: "Toplita" },
  { nume: "Călnaci", simplu: "Calnaci", comuna: "Subcetate" },
  { nume: "Calonda", comuna: "Corund" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Martinis" },
  { nume: "Căpâlniţa", simplu: "Capalnita" },
  { nume: "Capu Corbului", comuna: "Corbu" },
  { nume: "Carpitus", comuna: "Baile Tusnad" },
  { nume: "Cârţa", simplu: "Carta" },
  { nume: "Casinu Nou", comuna: "Plaiesii De Jos" },
  { nume: "Cecheşti", simplu: "Cechesti", comuna: "Avramesti" },
  { nume: "Ceheţel", simplu: "Cehetel", comuna: "Simonesti" },
  { nume: "Cetăţuia", simplu: "Cetatuia", comuna: "Sansimion" },
  { nume: "Chedia Mare", comuna: "Simonesti" },
  { nume: "Chedia Mică", simplu: "Chedia Mica", comuna: "Simonesti" },
  { nume: "Chileni", comuna: "Suseni" },
  { nume: "Chinuşu", simplu: "Chinusu", comuna: "Martinis" },
  { nume: "Ciaracio", comuna: "Siculeni" },
  { nume: "Ciba", comuna: "Miercurea Ciuc" },
  { nume: "Ciceu", comuna: "Siculeni" },
  { nume: "Ciobăniş", simplu: "Ciobanis", comuna: "Ciucsangeorgiu" },
  { nume: "Cireşeni", simplu: "Cireseni", comuna: "Felicieni" },
  { nume: "Ciucani", comuna: "Sanmartin" },
  { nume: "Ciucsângeorgiu", simplu: "Ciucsangeorgiu" },
  { nume: "Ciumani" },
  { nume: "Cobăteşti", simplu: "Cobatesti", comuna: "Simonesti" },
  { nume: "Comăneşti", simplu: "Comanesti", comuna: "Martinis" },
  { nume: "Comiat", comuna: "Lunca De Sus" },
  { nume: "Corbu" },
  { nume: "Corund" },
  { nume: "Cotormani", comuna: "Ciucsangeorgiu" },
  { nume: "Covacipeter", comuna: "Gheorgheni" },
  { nume: "Cozmeni" },
  { nume: "Crăciunel", simplu: "Craciunel", comuna: "Ocland" },
  { nume: "Crişeni", simplu: "Criseni", comuna: "Atid" },
  { nume: "Cristuru Secuiesc" },
  { nume: "Cuşmed", simplu: "Cusmed", comuna: "Atid" },
  { nume: "Daia", comuna: "Ulies" },
  { nume: "Dăneşti", simplu: "Danesti" },
  { nume: "Dârjiu", simplu: "Darjiu" },
  { nume: "Dealu Armanului", comuna: "Galautas" },
  { nume: "Dealu" },
  { nume: "Dejuţiu", simplu: "Dejutiu", comuna: "Mugeni" },
  { nume: "Delniţa", simplu: "Delnita", comuna: "Pauleni-Ciuc" },
  { nume: "Desag", comuna: "Zetea" },
  { nume: "Ditrău", simplu: "Ditrau" },
  { nume: "Dobeni", comuna: "Mugeni" },
  { nume: "Duda", comuna: "Subcetate" },
  { nume: "Eghersec", comuna: "Ciucsangeorgiu" },
  { nume: "Eliseni", comuna: "Secuieni" },
  { nume: "Făgeţel", simplu: "Fagetel", comuna: "Frumoasa" },
  { nume: "Făgeţel", simplu: "Fagetel", comuna: "Remetea" },
  { nume: "Fâncel", simplu: "Fancel", comuna: "Dealu" },
  { nume: "Fântâna Brazilor", simplu: "Fantana Brazilor", comuna: "Corund" },
  { nume: "Feliceni", comuna: "Felicieni" },
  { nume: "Filiaş", simplu: "Filias", comuna: "Cristuru Secuiesc" },
  { nume: "Filpea", comuna: "Subcetate" },
  { nume: "Firtănuş", simplu: "Firtanus", comuna: "Avramesti" },
  { nume: "Firtuşu", simplu: "Firtusu", comuna: "Lupeni" },
  { nume: "Fitod", comuna: "Sancraieni" },
  { nume: "Forţeni", simplu: "Forteni", comuna: "Felicieni" },
  { nume: "Frumoasa" },
  { nume: "Fundoaia", comuna: "Sarmas" },
  { nume: "Gălăuţaş-Pârău", simplu: "Galautas-Parau", comuna: "Galautas" },
  { nume: "Gălăuţaş", simplu: "Galautas" },
  { nume: "Gheorgheni" },
  { nume: "Ghiduţ", simplu: "Ghidut", comuna: "Lazarea" },
  { nume: "Ghipeş", simplu: "Ghipes", comuna: "Martinis" },
  { nume: "Ghiurche", comuna: "Ciucsangeorgiu" },
  { nume: "Goagiu", comuna: "Avramesti" },
  { nume: "Hagota", comuna: "Tulghes" },
  { nume: "Harghita-Băi", simplu: "Harghita-Bai", comuna: "Miercurea Ciuc" },
  { nume: "Hodoşa", simplu: "Hodosa", comuna: "Sarmas" },
  { nume: "Hoghia", comuna: "Felicieni" },
  { nume: "Hosasău", simplu: "Hosasau", comuna: "Sancraieni" },
  { nume: "Iacobeni", comuna: "Plaiesii De Jos" },
  { nume: "Iaşu", simplu: "Iasu", comuna: "Ulies" },
  { nume: "Ighiu", comuna: "Ulies" },
  { nume: "Imper", comuna: "Plaiesii De Jos" },
  { nume: "Ineu", comuna: "Carta" },
  { nume: "Inlăceni", simplu: "Inlaceni", comuna: "Atid" },
  { nume: "Izvoare", comuna: "Zetea" },
  { nume: "Izvoru Mureşului", simplu: "Izvoru Muresului", comuna: "Voslabeni" },
  {
    nume: "Izvorul Trotuşului",
    simplu: "Izvorul Trotusului",
    comuna: "Lunca De Sus",
  },
  { nume: "Jigodin-Băi", simplu: "Jigodin-Bai", comuna: "Miercurea Ciuc" },
  { nume: "Jolotca", comuna: "Ditrau" },
  { nume: "Joseni" },
  { nume: "Lacu Roşu", simplu: "Lacu Rosu", comuna: "Gheorgheni" },
  { nume: "Laz-Firtănuş", simplu: "Laz-Firtanus", comuna: "Avramesti" },
  { nume: "Laz-Şoimuş", simplu: "Laz-Soimus", comuna: "Avramesti" },
  { nume: "Lăzarea", simplu: "Lazarea" },
  { nume: "Lăzăreşti", simplu: "Lazaresti", comuna: "Cozmeni" },
  { nume: "Leliceni", comuna: "Sancraieni" },
  { nume: "Liban", comuna: "Suseni" },
  { nume: "Livezi", comuna: "Mihaileni" },
  { nume: "Locodeni", comuna: "Martinis" },
  { nume: "Lueta" },
  { nume: "Lunca de Jos" },
  { nume: "Lunca de Sus" },
  { nume: "Luncani", comuna: "Toplita" },
  { nume: "Lupeni" },
  { nume: "Lutiţa", simplu: "Lutita", comuna: "Mugeni" },
  { nume: "Mădăraş", simplu: "Madaras" },
  { nume: "Măgheruş", simplu: "Magherus", comuna: "Toplita" },
  { nume: "Mărtiniş", simplu: "Martinis" },
  { nume: "Martonca", comuna: "Remetea" },
  { nume: "Mătişeni", simplu: "Matiseni", comuna: "Mugeni" },
  { nume: "Medişoru Mare", simplu: "Medisoru Mare", comuna: "Simonesti" },
  { nume: "Medişoru Mic", simplu: "Medisoru Mic", comuna: "Avramesti" },
  { nume: "Mereşti", simplu: "Meresti" },
  { nume: "Miercurea Ciuc" },
  { nume: "Mihăileni", simplu: "Mihaileni" },
  { nume: "Mihăileni", simplu: "Mihaileni", comuna: "Simonesti" },
  { nume: "Minele Lueta", comuna: "Vlahita" },
  { nume: "Misentea", comuna: "Sancraieni" },
  { nume: "Moglăneşti", simplu: "Moglanesti", comuna: "Toplita" },
  { nume: "Morăreni", simplu: "Morareni", comuna: "Lupeni" },
  { nume: "Mugeni" },
  { nume: "Mujna", comuna: "Darjiu" },
  { nume: "Nădejdea", simplu: "Nadejdea", comuna: "Mihaileni" },
  { nume: "Nicoleni", comuna: "Simonesti" },
  { nume: "Nicoleşti", simplu: "Nicolesti", comuna: "Frumoasa" },
  { nume: "Nicoleşti", simplu: "Nicolesti", comuna: "Ulies" },
  { nume: "Nuţeni", simplu: "Nuteni", comuna: "Galautas" },
  { nume: "Obrăneşti", simplu: "Obranesti", comuna: "Ulies" },
  { nume: "Ocland" },
  { nume: "Ocna de Jos", comuna: "Praid" },
  { nume: "Ocna de Sus", comuna: "Praid" },
  { nume: "Odorheiu Secuiesc" },
  { nume: "Orăşeni", simplu: "Oraseni", comuna: "Martinis" },
  { nume: "Oţeni", simplu: "Oteni", comuna: "Felicieni" },
  { nume: "Păltiniş-Ciuc", simplu: "Paltinis-Ciuc", comuna: "Lunca De Sus" },
  { nume: "Păltiniş", simplu: "Paltinis", comuna: "Lupeni" },
  { nume: "Păuleni-Ciuc", simplu: "Pauleni-Ciuc" },
  { nume: "Păuleni", simplu: "Pauleni", comuna: "Lupeni" },
  { nume: "Petecu", comuna: "Ulies" },
  { nume: "Petreni", comuna: "Martinis" },
  { nume: "Pintic", comuna: "Tulghes" },
  { nume: "Plăieşii de Jos", simplu: "Plaiesii de Jos" },
  {
    nume: "Plăieşii de Sus",
    simplu: "Plaiesii de Sus",
    comuna: "Plaiesii De Jos",
  },
  { nume: "Platoneşti", simplu: "Platonesti", comuna: "Sarmas" },
  { nume: "Plopiş", simplu: "Plopis", comuna: "Galautas" },
  { nume: "Poiana Fagului", comuna: "Lunca De Jos" },
  { nume: "Poiana Târnavei", simplu: "Poiana Tarnavei", comuna: "Zetea" },
  { nume: "Poloniţa", simplu: "Polonita", comuna: "Felicieni" },
  { nume: "Porumbenii Mari", comuna: "Mugeni" },
  { nume: "Porumbenii Mici", comuna: "Mugeni" },
  { nume: "Potiond", comuna: "Ciucsangeorgiu" },
  { nume: "Praid" },
  { nume: "Preluca", comuna: "Galautas" },
  { nume: "Puntea Lupului", comuna: "Lunca De Jos" },
  { nume: "Răchitiş", simplu: "Rachitis", comuna: "Bilbor" },
  { nume: "Racu", comuna: "Siculeni" },
  { nume: "Rareş", simplu: "Rares", comuna: "Martinis" },
  { nume: "Recea", comuna: "Tulghes" },
  { nume: "Remetea" },
  { nume: "Rugăneşti", simplu: "Ruganesti", comuna: "Simonesti" },
  { nume: "Runc", comuna: "Sarmas" },
  { nume: "Săcel", simplu: "Sacel" },
  { nume: "Sâncel", simplu: "Sancel", comuna: "Lupeni" },
  { nume: "Sâncrai", simplu: "Sancrai", comuna: "Dealu" },
  { nume: "Sâncrăieni", simplu: "Sancraieni" },
  { nume: "Sândominic", simplu: "Sandominic" },
  { nume: "Sânmartin", simplu: "Sanmartin" },
  { nume: "Sânpaul", simplu: "Sanpaul", comuna: "Martinis" },
  { nume: "Sânsimion", simplu: "Sansimion" },
  { nume: "Sântimbru-Băi", simplu: "Santimbru-Bai", comuna: "Sancraieni" },
  { nume: "Sântimbru", simplu: "Santimbru", comuna: "Sancraieni" },
  { nume: "Sărmaş", simplu: "Sarmas" },
  { nume: "Şaşvereş", simplu: "Sasveres", comuna: "Praid" },
  { nume: "Satu Mare", comuna: "Bradesti" },
  { nume: "Satu Mic", comuna: "Lupeni" },
  { nume: "Satu Nou", comuna: "Ocland" },
  { nume: "Satu Nou", comuna: "Siculeni" },
  { nume: "Secu", comuna: "Toplita" },
  { nume: "Secuieni" },
  { nume: "Senetea", comuna: "Suseni" },
  { nume: "Şicasău", simplu: "Sicasau", comuna: "Zetea" },
  { nume: "Şiclod", simplu: "Siclod", comuna: "Atid" },
  { nume: "Siculeni" },
  { nume: "Şimoneşti", simplu: "Simonesti" },
  { nume: "Sineu", comuna: "Remetea" },
  { nume: "Şoimeni", simplu: "Soimeni", comuna: "Pauleni-Ciuc" },
  { nume: "Şoimuşu Mare", simplu: "Soimusu Mare", comuna: "Sacel" },
  { nume: "Şoimuşu Mic", simplu: "Soimusu Mic", comuna: "Sacel" },
  { nume: "Sub Cetate", comuna: "Zetea" },
  { nume: "Subcetate" },
  { nume: "Suseni" },
  { nume: "Tăietura", simplu: "Taietura", comuna: "Mugeni" },
  { nume: "Tămaşu", simplu: "Tamasu", comuna: "Dealu" },
  { nume: "Tărceşti", simplu: "Tarcesti", comuna: "Simonesti" },
  { nume: "Târnoviţa", simplu: "Tarnovita", comuna: "Bradesti" },
  { nume: "Tăureni", simplu: "Taureni", comuna: "Felicieni" },
  { nume: "Teleac", comuna: "Felicieni" },
  { nume: "Ţengheler", simplu: "Tengheler", comuna: "Ditrau" },
  { nume: "Tibod", comuna: "Dealu" },
  { nume: "Toleşeni", simplu: "Toleseni", comuna: "Galautas" },
  { nume: "Tomeşti", simplu: "Tomesti" },
  { nume: "Topliţa", simplu: "Toplita" },
  { nume: "Tulgheş", simplu: "Tulghes" },
  { nume: "Turdeni", comuna: "Simonesti" },
  { nume: "Tuşnad", simplu: "Tusnad" },
  { nume: "Tuşnadu Nou", simplu: "Tusnadu Nou", comuna: "Tusnad" },
  { nume: "Uilac", comuna: "Sacel" },
  { nume: "Ulcani", comuna: "Dealu" },
  { nume: "Ulieş", simplu: "Ulies" },
  { nume: "Văcăreşti", simplu: "Vacaresti", comuna: "Mihaileni" },
  { nume: "Vâgani", simplu: "Vagani", comuna: "Toplita" },
  { nume: "Vale", comuna: "Toplita" },
  { nume: "Valea Boroş", simplu: "Valea Boros", comuna: "Lunca De Jos" },
  { nume: "Valea Capelei", comuna: "Lunca De Jos" },
  { nume: "Valea Gârbea", simplu: "Valea Garbea", comuna: "Lunca De Sus" },
  {
    nume: "Valea Întunecoasă",
    simplu: "Valea Intunecoasa",
    comuna: "Lunca De Jos",
  },
  { nume: "Valea lui Antaloc", comuna: "Lunca De Jos" },
  { nume: "Valea lui Pavel", comuna: "Corund" },
  { nume: "Valea Rece", comuna: "Lunca De Jos" },
  { nume: "Valea Rotundă", simplu: "Valea Rotunda", comuna: "Dealu" },
  { nume: "Valea Strâmbă", simplu: "Valea Stramba", comuna: "Suseni" },
  { nume: "Valea Ugra", comuna: "Lunca De Sus" },
  { nume: "Valea Uzului", comuna: "Sanmartin" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Felicieni" },
  { nume: "Vargatac", comuna: "Gheorgheni" },
  { nume: "Vărşag", simplu: "Varsag" },
  { nume: "Vasileni", comuna: "Ulies" },
  { nume: "Vidacut", comuna: "Sacel" },
  { nume: "Visafolio", comuna: "Gheorgheni" },
  { nume: "Vlăhiţa", simplu: "Vlahita" },
  { nume: "Voşlăbeni", simplu: "Voslabeni" },
  { nume: "Vrabia", comuna: "Tusnad" },
  { nume: "Zăpodea", simplu: "Zapodea", comuna: "Galautas" },
  { nume: "Zencani", comuna: "Toplita" },
  { nume: "Zetea" },
];
