export const is = [
  { nume: "Albești", simplu: "Albesti", comuna: "Braesti" },
  { nume: "Alexandru cel Bun", comuna: "Vladeni" },
  { nume: "Alexandru I. Cuza" },
  { nume: "Alexeni", comuna: "Tibana" },
  { nume: "Alexești", simplu: "Alexesti", comuna: "Ipatele" },
  { nume: "Andrieșeni", simplu: "Andrieseni" },
  { nume: "Arama", comuna: "Coarnele Caprei" },
  { nume: "Aroneanu" },
  { nume: "Avântu", simplu: "Avantu", comuna: "Romanesti" },
  { nume: "Bâcu", simplu: "Bacu", comuna: "Ipatele" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Scobinti" },
  { nume: "Bahluiu", comuna: "Cotnari" },
  { nume: "Băiceni", simplu: "Baiceni", comuna: "Cucuteni" },
  { nume: "Băiceni", simplu: "Baiceni", comuna: "Todiresti" },
  { nume: "Balciu", comuna: "Miroslava" },
  { nume: "Balș", simplu: "Bals" },
  { nume: "Bălțați", simplu: "Baltati" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Probota" },
  { nume: "Bălușești", simplu: "Balusesti", comuna: "Dagata" },
  { nume: "Banu", comuna: "Dumesti" },
  { nume: "Bărbătești", simplu: "Barbatesti", comuna: "Cucuteni" },
  { nume: "Bârlești", simplu: "Barlesti", comuna: "Erbiceni" },
  { nume: "Bârnova", simplu: "Barnova" },
  { nume: "Belcești", simplu: "Belcesti" },
  { nume: "Berezlogi", comuna: "Siretel" },
  { nume: "Bivolari" },
  { nume: "Blaga", comuna: "Schitu Duca" },
  { nume: "Blăgești", simplu: "Blagesti", comuna: "Pascani" },
  { nume: "Boatca", comuna: "Dagata" },
  { nume: "Bocnița", simplu: "Bocnita", comuna: "Sinesti" },
  { nume: "Bodești", simplu: "Bodesti", comuna: "Scanteia" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Horlesti" },
  { nume: "Bogonos", comuna: "Letcani" },
  { nume: "Bohotin", comuna: "Raducaneni" },
  { nume: "Bojila", comuna: "Madarjac" },
  { nume: "Boldești", simplu: "Boldesti", comuna: "Todiresti" },
  { nume: "Boroșești", simplu: "Borosesti", comuna: "Scanteia" },
  { nume: "Borosoaia", comuna: "Plugari" },
  { nume: "Borșa", simplu: "Borsa", comuna: "Vladeni" },
  { nume: "Bosia", comuna: "Ungheni" },
  { nume: "Boșteni", simplu: "Bosteni", comuna: "Pascani" },
  { nume: "Boureni", comuna: "Bals" },
  { nume: "Boureni", comuna: "Motca" },
  { nume: "Brădicești", simplu: "Bradicesti", comuna: "Dolhesti" },
  { nume: "Brăești", simplu: "Braesti" },
  { nume: "Bran", comuna: "Golaiesti" },
  { nume: "Brătești", simplu: "Bratesti", comuna: "Stolniceni-Prajescu" },
  { nume: "Brătuleni", simplu: "Bratuleni", comuna: "Miroslava" },
  { nume: "Brătulești", simplu: "Bratulesti", comuna: "Strunga" },
  { nume: "Breazu", comuna: "Rediu" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Vladeni" },
  { nume: "Buda", comuna: "Braesti" },
  { nume: "Buda", comuna: "Lespezi" },
  { nume: "Budăi", simplu: "Budai", comuna: "Podu Iloaiei" },
  { nume: "Budești", simplu: "Budesti", comuna: "Mogosesti" },
  { nume: "Buhăeni", simplu: "Buhaeni", comuna: "Andrieseni" },
  { nume: "Buhalnița", simplu: "Buhalnita", comuna: "Ceplenita" },
  { nume: "Bulbucani", comuna: "Gropnita" },
  { nume: "Bursuc-Deal", comuna: "Lespezi" },
  { nume: "Bursuc-Vale", comuna: "Lespezi" },
  { nume: "Buruienești", simplu: "Buruienesti", comuna: "Bivolari" },
  { nume: "Butea" },
  { nume: "Buzdug", comuna: "Dagata" },
  { nume: "Buznea", comuna: "Ion Neculce" },
  { nume: "Cărbunari", simplu: "Carbunari", comuna: "Grajduri" },
  { nume: "Cârjoaia", simplu: "Carjoaia", comuna: "Cotnari" },
  { nume: "Cârlig", simplu: "Carlig", comuna: "Popricani" },
  { nume: "Cârniceni", simplu: "Carniceni", comuna: "Tiganasi" },
  { nume: "Căuești", simplu: "Cauesti", comuna: "Scheia" },
  { nume: "Ceplenița", simplu: "Ceplenita" },
  { nume: "Cercu", comuna: "Barnova" },
  { nume: "Chicerea", comuna: "Tomesti" },
  { nume: "Chilișoaia", simplu: "Chilisoaia", comuna: "Dumesti" },
  { nume: "Chiperești", simplu: "Chiperesti", comuna: "Tutora" },
  { nume: "Chișcăreni", simplu: "Chiscareni", comuna: "Sipote" },
  { nume: "Cilibiu", comuna: "Golaiesti" },
  { nume: "Cioca-Boca", comuna: "Scheia" },
  { nume: "Ciocârlești", simplu: "Ciocarlesti", comuna: "Scanteia" },
  { nume: "Ciohorăni", simplu: "Ciohorani", comuna: "Miroslovesti" },
  { nume: "Ciortești", simplu: "Ciortesti" },
  { nume: "Cireșeni", simplu: "Cireseni", comuna: "Cotnari" },
  { nume: "Ciurbești", simplu: "Ciurbesti", comuna: "Miroslava" },
  { nume: "Ciurea" },
  { nume: "Coada Stâncii", simplu: "Coada Stancii", comuna: "Ungheni" },
  { nume: "Coarnele Caprei" },
  { nume: "Coasta Măgurii", simplu: "Coasta Magurii", comuna: "Targu Frumos" },
  { nume: "Cogeasca", comuna: "Letcani" },
  { nume: "Colțu Cornii", simplu: "Coltu Cornii", comuna: "Grozesti" },
  { nume: "Comarna" },
  { nume: "Conțești", simplu: "Contesti", comuna: "Valea Seaca" },
  { nume: "Corcodel", comuna: "Grajduri" },
  { nume: "Cornești", simplu: "Cornesti", comuna: "Miroslava" },
  { nume: "Coropceni", comuna: "Ciortesti" },
  { nume: "Cosițeni", simplu: "Cositeni", comuna: "Podu Iloaiei" },
  { nume: "Costești", simplu: "Costesti" },
  { nume: "Costuleni" },
  { nume: "Cotârgaci", simplu: "Cotargaci", comuna: "Baltati" },
  { nume: "Cotnari" },
  { nume: "Cotu lui Ivan", comuna: "Golaiesti" },
  { nume: "Cotu Morii", comuna: "Popricani" },
  { nume: "Covasna", comuna: "Costuleni" },
  { nume: "Cozia", comuna: "Costuleni" },
  { nume: "Cozmești", simplu: "Cozmesti" },
  { nume: "Cozmești", simplu: "Cozmesti", comuna: "Stolniceni-Prajescu" },
  { nume: "Cristești", simplu: "Cristesti" },
  { nume: "Cristești", simplu: "Cristesti", comuna: "Braesti" },
  { nume: "Cristești", simplu: "Cristesti", comuna: "Holboca" },
  { nume: "Crivești", simplu: "Crivesti", comuna: "Strunga" },
  { nume: "Crivești", simplu: "Crivesti", comuna: "Vanatori" },
  { nume: "Crucea", comuna: "Lungani" },
  { nume: "Cucova", comuna: "Strunga" },
  { nume: "Cucuteni" },
  { nume: "Cucuteni", comuna: "Letcani" },
  { nume: "Curagău", simplu: "Curagau", comuna: "Comarna" },
  { nume: "Curături", simplu: "Curaturi", comuna: "Ciurea" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Ipatele" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Popricani" },
  { nume: "Dădești", simplu: "Dadesti", comuna: "Targu Frumos" },
  { nume: "Dagâța", simplu: "Dagata" },
  { nume: "Dancaș", simplu: "Dancas", comuna: "Miroslava" },
  { nume: "Dancu", comuna: "Holboca" },
  { nume: "Deleni" },
  { nume: "Deleni", comuna: "Ciortesti" },
  { nume: "Dobrovăț", simplu: "Dobrovat" },
  { nume: "Dolhești", simplu: "Dolhesti" },
  { nume: "Domnița", simplu: "Domnita", comuna: "Tibana" },
  { nume: "Dorobanț", simplu: "Dorobant", comuna: "Aroneanu" },
  { nume: "Doroșcani", simplu: "Doroscani", comuna: "Popesti" },
  { nume: "Drăgănești", simplu: "Draganesti", comuna: "Andrieseni" },
  { nume: "Drăgușeni", simplu: "Draguseni" },
  { nume: "Dumbrava", comuna: "Ciurea" },
  { nume: "Dumbrava", comuna: "Lespezi" },
  { nume: "Dumbrăvița", simplu: "Dumbravita", comuna: "Ruginoasa" },
  { nume: "Dumești", simplu: "Dumesti" },
  {
    nume: "Dumitreștii Gălății",
    simplu: "Dumitrestii Galatii",
    comuna: "Schitu Duca",
  },
  { nume: "Erbiceni" },
  { nume: "Făgăt", simplu: "Fagat", comuna: "Cotnari" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Andrieseni" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Fintinele" },
  { nume: "Fărcășeni", simplu: "Farcaseni", comuna: "Strunga" },
  { nume: "Fedeleșeni", simplu: "Fedeleseni", comuna: "Strunga" },
  { nume: "Feredeni", comuna: "Deleni" },
  { nume: "Fetești", simplu: "Fetesti", comuna: "Scobinti" },
  { nume: "Filiași", simplu: "Filiasi", comuna: "Baltati" },
  { nume: "Focuri" },
  { nume: "Forăști", simplu: "Forasti", comuna: "Gropnita" },
  { nume: "Frăsuleni", simplu: "Frasuleni", comuna: "Victoria" },
  { nume: "Frenciugi", comuna: "Scheia" },
  { nume: "Frumușica", simplu: "Frumusica", comuna: "Madarjac" },
  { nume: "Gănești", simplu: "Ganesti", comuna: "Targu Frumos" },
  { nume: "Gârbești", simplu: "Garbesti", comuna: "Tibana" },
  { nume: "Gâștești", simplu: "Gastesti", comuna: "Pascani" },
  { nume: "Găureni", simplu: "Gaureni", comuna: "Miroslava" },
  { nume: "Giurgești", simplu: "Giurgesti", comuna: "Targu Frumos" },
  { nume: "Glăvănești", simplu: "Glavanesti", comuna: "Andrieseni" },
  {
    nume: "Glodenii Gândului",
    simplu: "Glodenii Gandului",
    comuna: "Tibanesti",
  },
  { nume: "Goești", simplu: "Goesti", comuna: "Lungani" },
  { nume: "Golăiești", simplu: "Golaiesti" },
  { nume: "Gorban" },
  { nume: "Goruni", comuna: "Tomesti" },
  { nume: "Grădinari", simplu: "Gradinari", comuna: "Golaiesti" },
  { nume: "Grajduri" },
  { nume: "Griești", simplu: "Griesti", comuna: "Tibanesti" },
  { nume: "Gropnița", simplu: "Gropnita" },
  { nume: "Grozești", simplu: "Grozesti" },
  { nume: "Gura Bâdiliței", simplu: "Gura Badilitei", comuna: "Vanatori" },
  { nume: "Gura Bohotin", comuna: "Gorban" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Strunga" },
  { nume: "Hăbășești", simplu: "Habasesti", comuna: "Strunga" },
  { nume: "Hadâmbu", simplu: "Hadambu", comuna: "Mogosesti" },
  { nume: "Hălăucești", simplu: "Halaucesti" },
  { nume: "Hălceni", simplu: "Halceni", comuna: "Sipote" },
  { nume: "Hândrești", simplu: "Handresti", comuna: "Oteleni" },
  { nume: "Hârlău", simplu: "Harlau" },
  { nume: "Hărmăneasa", simplu: "Harmaneasa", comuna: "Helesteni" },
  { nume: "Hărmăneștii Noi", simplu: "Harmanestii Noi", comuna: "Todiresti" },
  {
    nume: "Hărmăneștii Vechi",
    simplu: "Harmanestii Vechi",
    comuna: "Todiresti",
  },
  { nume: "Hărpășești", simplu: "Harpasesti", comuna: "Popesti" },
  { nume: "Hârtoape", simplu: "Hartoape", comuna: "Vanatori" },
  { nume: "Heci", comuna: "Lespezi" },
  { nume: "Heleșteni", simplu: "Helesteni" },
  { nume: "Hermeziu", comuna: "Trifesti" },
  { nume: "Hilița", simplu: "Hilita", comuna: "Costuleni" },
  { nume: "Hlincea", comuna: "Ciurea" },
  { nume: "Hodora", comuna: "Cotnari" },
  { nume: "Hoisești", simplu: "Hoisesti", comuna: "Dumesti" },
  { nume: "Holboca" },
  { nume: "Holm", comuna: "Podu Iloaiei" },
  { nume: "Homița", simplu: "Homita", comuna: "Cristesti" },
  { nume: "Horlești", simplu: "Horlesti" },
  { nume: "Horlești", simplu: "Horlesti", comuna: "Rediu" },
  { nume: "Horodiștea", simplu: "Horodistea", comuna: "Cotnari" },
  { nume: "Horpaz", comuna: "Miroslava" },
  { nume: "Humosu", comuna: "Siretel" },
  { nume: "Iacobeni", comuna: "Vladeni" },
  { nume: "Iași", simplu: "Iasi" },
  { nume: "Iazu Nou", comuna: "Sipote" },
  { nume: "Iazu Vechi", comuna: "Sipote" },
  { nume: "Icușeni", simplu: "Icuseni", comuna: "Victoria" },
  { nume: "Iepureni", comuna: "Andrieseni" },
  { nume: "Iepureni", comuna: "Movileni" },
  { nume: "Ion Neculce", comuna: "Targu Frumos" },
  { nume: "Iorcani", comuna: "Tatarusi" },
  { nume: "Iosupeni", comuna: "Cotnari" },
  { nume: "Ipatele" },
  { nume: "Isaiia", comuna: "Raducaneni" },
  { nume: "Iugani", comuna: "Mircesti" },
  { nume: "Izvoarele", comuna: "Rachiteni" },
  { nume: "Jigoreni", comuna: "Tibanesti" },
  { nume: "Kogălniceni", simplu: "Kogalniceni", comuna: "Alexandru I. Cuza" },
  { nume: "Larga-Jijia", comuna: "Movileni" },
  { nume: "Leahu-Nacu", comuna: "Deleni" },
  { nume: "Lespezi" },
  { nume: "Lețcani", simplu: "Letcani" },
  { nume: "Liteni", comuna: "Belcesti" },
  { nume: "Luceni", comuna: "Victoria" },
  { nume: "Lunca Cetățuii", simplu: "Lunca Cetatuii", comuna: "Ciurea" },
  { nume: "Lunca Rateș", simplu: "Lunca Rates", comuna: "Scanteia" },
  { nume: "Lunca", comuna: "Grajduri" },
  { nume: "Lunca", comuna: "Pascani" },
  { nume: "Luncași", simplu: "Luncasi", comuna: "Halaucesti" },
  { nume: "Lungani" },
  { nume: "Lungani", comuna: "Voinesti" },
  { nume: "Lupăria", simplu: "Luparia", comuna: "Cotnari" },
  { nume: "Măcărești", simplu: "Macaresti", comuna: "Prisacani" },
  { nume: "Mădârjac", simplu: "Madarjac" },
  { nume: "Mădârjești", simplu: "Madarjesti", comuna: "Baltati" },
  { nume: "Mălăești", simplu: "Malaesti", comuna: "Gropnita" },
  { nume: "Mănăstirea", simplu: "Manastirea", comuna: "Dagata" },
  { nume: "Mânjești", simplu: "Manjesti", comuna: "Mogosesti" },
  { nume: "Mânzătești", simplu: "Manzatesti", comuna: "Ungheni" },
  { nume: "Maxut", comuna: "Deleni" },
  { nume: "Medeleni", comuna: "Golaiesti" },
  { nume: "Miclăușeni", simplu: "Miclauseni", comuna: "Butea" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Tiganasi",
  },
  { nume: "Mircești", simplu: "Mircesti" },
  { nume: "Mironeasa" },
  { nume: "Miroslava" },
  { nume: "Miroslovești", simplu: "Miroslovesti" },
  { nume: "Mitești", simplu: "Mitesti", comuna: "Miroslovesti" },
  { nume: "Mitoc", comuna: "Sipote" },
  { nume: "Moara Ciornei", comuna: "Tibana" },
  { nume: "Mogoșești-Siret", simplu: "Mogosesti-Siret" },
  { nume: "Mogoșești", simplu: "Mogosesti" },
  { nume: "Moimești", simplu: "Moimesti", comuna: "Popricani" },
  { nume: "Moreni", comuna: "Prisacani" },
  { nume: "Moșna", simplu: "Mosna" },
  { nume: "Moțca", simplu: "Motca" },
  { nume: "Movileni" },
  { nume: "Movileni", comuna: "Helesteni" },
  { nume: "Muncelu de Sus", comuna: "Mogosesti-Siret" },
  { nume: "Munteni", comuna: "Belcesti" },
  { nume: "Oboroceni", comuna: "Helesteni" },
  { nume: "Obrijeni", comuna: "Popesti" },
  { nume: "Onești", simplu: "Onesti", comuna: "Plugari" },
  { nume: "Oprișeni", simplu: "Opriseni", comuna: "Tutora" },
  { nume: "Oproaia", comuna: "Tibana" },
  { nume: "Orzeni", comuna: "Holboca" },
  { nume: "Osoi", comuna: "Comarna" },
  { nume: "Osoi", comuna: "Sinesti" },
  { nume: "Oțeleni", simplu: "Oteleni" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Grajduri" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Popesti" },
  { nume: "Pârcovaci", simplu: "Parcovaci", comuna: "Harlau" },
  { nume: "Pașcani", simplu: "Pascani" },
  { nume: "Păun", simplu: "Paun", comuna: "Barnova" },
  { nume: "Păușești", simplu: "Pausesti", comuna: "Dumesti" },
  { nume: "Perieni", comuna: "Probota" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Golaiesti" },
  { nume: "Petroșica", simplu: "Petrosica", comuna: "Coarnele Caprei" },
  { nume: "Picioru Lupului", comuna: "Ciurea" },
  { nume: "Pietrăria", simplu: "Pietraria", comuna: "Barnova" },
  { nume: "Pietriș", simplu: "Pietris", comuna: "Dolhesti" },
  { nume: "Pietrosu", comuna: "Tatarusi" },
  { nume: "Piscu Rusului", comuna: "Dagata" },
  { nume: "Plugari" },
  { nume: "Pocreaca", comuna: "Schitu Duca" },
  { nume: "Podișu", simplu: "Podisu", comuna: "Baltati" },
  { nume: "Podolenii de Jos", comuna: "Cozmesti" },
  { nume: "Podolenii de Sus", comuna: "Cozmesti" },
  { nume: "Podu Hagiului", comuna: "Gorban" },
  { nume: "Podu Iloaiei" },
  { nume: "Podu Jijiei", comuna: "Golaiesti" },
  { nume: "Poiana cu Cetate", comuna: "Grajduri" },
  { nume: "Poiana de Sus", comuna: "Tibana" },
  { nume: "Poiana Mănăstirii", simplu: "Poiana Manastirii", comuna: "Tibana" },
  { nume: "Poiana Mărului", simplu: "Poiana Marului", comuna: "Ceplenita" },
  { nume: "Poiana Șcheii", simplu: "Poiana Scheii", comuna: "Scheia" },
  { nume: "Poiana", comuna: "Deleni" },
  { nume: "Poiana", comuna: "Schitu Duca" },
  { nume: "Poieni", comuna: "Schitu Duca" },
  { nume: "Poienile", comuna: "Dagata" },
  { nume: "Popești", simplu: "Popesti" },
  { nume: "Popricani" },
  { nume: "Potângeni", simplu: "Potangeni", comuna: "Movileni" },
  { nume: "Prigoreni", comuna: "Ion Neculce" },
  { nume: "Prisăcani", simplu: "Prisacani" },
  { nume: "Probota" },
  { nume: "Proselnici", comuna: "Miroslava" },
  { nume: "Răchiteni", simplu: "Rachiteni" },
  { nume: "Rădeni", simplu: "Radeni", comuna: "Roscani" },
  { nume: "Răducăneni", simplu: "Raducaneni" },
  { nume: "Răsboieni", simplu: "Rasboieni", comuna: "Tibanesti" },
  { nume: "Războieni", simplu: "Razboieni", comuna: "Ion Neculce" },
  { nume: "Recea", comuna: "Tibanesti" },
  { nume: "Rediu Aldei", comuna: "Aroneanu" },
  { nume: "Rediu Mitropoliei", comuna: "Popricani" },
  { nume: "Rediu" },
  { nume: "Rediu", comuna: "Braesti" },
  { nume: "Rediu", comuna: "Ruginoasa" },
  { nume: "Rediu", comuna: "Scanteia" },
  { nume: "Românești", simplu: "Romanesti" },
  { nume: "Roșcani", simplu: "Roscani", comuna: "Trifesti" },
  { nume: "Roșu", simplu: "Rosu", comuna: "Raducaneni" },
  { nume: "Rotăria", simplu: "Rotaria", comuna: "Ciortesti" },
  { nume: "Ruginoasa" },
  { nume: "Runcu", comuna: "Tibana" },
  { nume: "Rusenii Noi", comuna: "Holboca" },
  { nume: "Rusenii Vechi", comuna: "Holboca" },
  { nume: "Săcărești", simplu: "Sacaresti", comuna: "Cucuteni" },
  { nume: "Sălăgeni", simplu: "Salageni", comuna: "Grozesti" },
  { nume: "Sângeri", simplu: "Sangeri", comuna: "Gropnita" },
  { nume: "Sârca", simplu: "Sarca", comuna: "Baltati" },
  { nume: "Satu Nou", comuna: "Belcesti" },
  { nume: "Satu Nou", comuna: "Scheia" },
  { nume: "Satu Nou", comuna: "Schitu Duca" },
  { nume: "Satu Nou", comuna: "Siretel" },
  { nume: "Săveni", simplu: "Saveni", comuna: "Gropnita" },
  { nume: "Scânteia", simplu: "Scanteia" },
  { nume: "Scheia", comuna: "Alexandru I. Cuza" },
  { nume: "Șcheia", simplu: "Scheia" },
  { nume: "Schitu Duca" },
  {
    nume: "Schitu Hadâmbului",
    simplu: "Schitu Hadambului",
    comuna: "Mironeasa",
  },
  { nume: "Schitu Stavnic", comuna: "Voinesti" },
  { nume: "Scobâlțeni", simplu: "Scobalteni", comuna: "Podu Iloaiei" },
  { nume: "Scobinți", simplu: "Scobinti" },
  { nume: "Scoposeni", comuna: "Gorban" },
  { nume: "Scoposeni", comuna: "Horlesti" },
  { nume: "Sculeni", comuna: "Victoria" },
  { nume: "Șendreni", simplu: "Sendreni", comuna: "Victoria" },
  { nume: "Șerbești", simplu: "Serbesti", comuna: "Ciortesti" },
  { nume: "Sinești", simplu: "Sinesti" },
  { nume: "Șipote", simplu: "Sipote" },
  { nume: "Sirețel", simplu: "Siretel" },
  { nume: "Slobozia", comuna: "Ciurea" },
  { nume: "Slobozia", comuna: "Deleni" },
  { nume: "Slobozia", comuna: "Schitu Duca" },
  { nume: "Slobozia", comuna: "Siretel" },
  { nume: "Slobozia", comuna: "Voinesti" },
  { nume: "Soci", comuna: "Miroslovesti" },
  { nume: "Sodomeni", comuna: "Pascani" },
  { nume: "Soloneț", simplu: "Solonet", comuna: "Bivolari" },
  { nume: "Șorogani", simplu: "Sorogani", comuna: "Aroneanu" },
  { nume: "Spineni", comuna: "Andrieseni" },
  { nume: "Spinoasa", comuna: "Erbiceni" },
  { nume: "Sprânceana", simplu: "Spranceana", comuna: "Erbiceni" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Comarna" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Victoria" },
  { nume: "Stejarii", comuna: "Tiganasi" },
  { nume: "Sticlăria", simplu: "Sticlaria", comuna: "Scobinti" },
  { nume: "Stolniceni-Prăjescu", simplu: "Stolniceni-Prajescu" },
  { nume: "Stornești", simplu: "Stornesti", comuna: "Sinesti" },
  { nume: "Stroești", simplu: "Stroesti", comuna: "Todiresti" },
  { nume: "Strunga" },
  { nume: "Suhuleț", simplu: "Suhulet", comuna: "Tansa" },
  { nume: "Tabăra", simplu: "Tabara", comuna: "Bivolari" },
  { nume: "Tansa" },
  { nume: "Tansa", comuna: "Belcesti" },
  { nume: "Târgu Frumos", simplu: "Targu Frumos" },
  { nume: "Tarnița", simplu: "Tarnita", comuna: "Dagata" },
  { nume: "Tătăruși", simplu: "Tatarusi" },
  { nume: "Tăutești", simplu: "Tautesti", comuna: "Rediu" },
  { nume: "Țibana", simplu: "Tibana" },
  { nume: "Țibănești", simplu: "Tibanesti" },
  { nume: "Țigănăși", simplu: "Tiganasi" },
  { nume: "Țipilești", simplu: "Tipilesti", comuna: "Popricani" },
  { nume: "Todirel", comuna: "Barnova" },
  { nume: "Todirești", simplu: "Todiresti" },
  { nume: "Tomești", simplu: "Tomesti" },
  { nume: "Topile", comuna: "Valea Seaca" },
  { nume: "Totoești", simplu: "Totoesti", comuna: "Erbiceni" },
  { nume: "Traian", comuna: "Bivolari" },
  { nume: "Trifești", simplu: "Trifesti" },
  { nume: "Tudor Vladimirescu", comuna: "Mogosesti-Siret" },
  { nume: "Tufeștii de Sus", simplu: "Tufestii de Sus", comuna: "Scanteia" },
  { nume: "Tungujei", comuna: "Tibanesti" },
  { nume: "Țuțora", simplu: "Tutora" },
  { nume: "Uda", comuna: "Tatarusi" },
  { nume: "Ulmi", comuna: "Belcesti" },
  { nume: "Ungheni" },
  { nume: "Uricani", comuna: "Miroslava" },
  { nume: "Ursărești", simplu: "Ursaresti", comuna: "Mircesti" },
  { nume: "Urșița", simplu: "Ursita", comuna: "Mironeasa" },
  { nume: "Ursoaia", comuna: "Romanesti" },
  { nume: "Vadu Vejei", comuna: "Tibana" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Vladeni" },
  { nume: "Vâlcica", simplu: "Valcica", comuna: "Tatarusi" },
  { nume: "Valea Adâncă", simplu: "Valea Adanca", comuna: "Miroslava" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Holboca" },
  { nume: "Valea Lupului" },
  { nume: "Valea Oilor", comuna: "Baltati" },
  { nume: "Valea Racului", comuna: "Cotnari" },
  { nume: "Valea Satului", comuna: "Grajduri" },
  { nume: "Valea Seacă", simplu: "Valea Seaca" },
  { nume: "Valea Ursului", comuna: "Miroslava" },
  { nume: "Vălenii", simplu: "Valenii", comuna: "Tibanesti" },
  { nume: "Vama", comuna: "Popesti" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Popricani" },
  { nume: "Vascani", comuna: "Ruginoasa" },
  { nume: "Verșeni", simplu: "Verseni", comuna: "Miroslovesti" },
  { nume: "Victoria" },
  { nume: "Vișan", simplu: "Visan", comuna: "Barnova" },
  { nume: "Vlădeni", simplu: "Vladeni" },
  { nume: "Vlădiceni", simplu: "Vladiceni", comuna: "Tomesti" },
  { nume: "Vlădnicuț", simplu: "Vladnicut", comuna: "Vanatori" },
  { nume: "Vladomira", comuna: "Trifesti" },
  { nume: "Vocotești", simplu: "Vocotesti", comuna: "Voinesti" },
  { nume: "Voinești", simplu: "Voinesti" },
  { nume: "Volintirești", simplu: "Volintiresti", comuna: "Alexandru I. Cuza" },
  { nume: "Vorovești", simplu: "Vorovesti", comuna: "Miroslava" },
  { nume: "Vulturi", comuna: "Popricani" },
  { nume: "Zaboloteni", comuna: "Trifesti" },
  { nume: "Zagavia", comuna: "Scobinti" },
  { nume: "Zbereni", comuna: "Cotnari" },
  { nume: "Zberoaia", comuna: "Gorban" },
  { nume: "Zece Prăjini", simplu: "Zece Prajini", comuna: "Dagata" },
  { nume: "Zlodica", comuna: "Ceplenita" },
  { nume: "Zmeu", comuna: "Lungani" },
];
