export const il = [
  { nume: "Adâncata", simplu: "Adancata" },
  { nume: "Albeşti", simplu: "Albesti" },
  { nume: "Alexeni" },
  { nume: "Amara Nouă", simplu: "Amara Noua", comuna: "Amara" },
  { nume: "Amara" },
  { nume: "Andrăşeşti", simplu: "Andrasesti" },
  { nume: "Armăşeşti", simplu: "Armasesti" },
  { nume: "Axintele" },
  { nume: "Balaciu" },
  { nume: "Bărbătescu", simplu: "Barbatescu", comuna: "Axintele" },
  { nume: "Bărbuleşti", simplu: "Barbulesti", comuna: "Armasesti" },
  { nume: "Bărcăneşti", simplu: "Barcanesti" },
  { nume: "Bataluri", comuna: "Albesti" },
  { nume: "Biţina-Pământeni", simplu: "Bitina-Pamanteni", comuna: "Movilita" },
  { nume: "Biţina-Ungureni", simplu: "Bitina-Ungureni", comuna: "Movilita" },
  { nume: "Bora", comuna: "Slobozia" },
  { nume: "Borăneşti", simplu: "Boranesti", comuna: "Cosereni" },
  { nume: "Borduşani", simplu: "Bordusani" },
  { nume: "Borduşelu", simplu: "Borduselu", comuna: "Ciochina" },
  { nume: "Boteni", comuna: "Sinesti" },
  { nume: "Brazii" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Ion Roata" },
  { nume: "Bucşa", simplu: "Bucsa", comuna: "Valea Ciorii" },
  { nume: "Bucu" },
  { nume: "Bueşti", simplu: "Buesti", comuna: "Albesti" },
  { nume: "Buliga", comuna: "Fetesti" },
  { nume: "Butoiu", comuna: "Sfantu Gheorghe" },
  { nume: "Cătruneşti", simplu: "Catrunesti", comuna: "Sinesti" },
  { nume: "Căzăneşti", simplu: "Cazanesti" },
  { nume: "Cegani", comuna: "Bordusani" },
  {
    nume: "Chiroiu-Pamânteni",
    simplu: "Chiroiu-Pamanteni",
    comuna: "Dragoesti",
  },
  { nume: "Chiroiu-Satu Nou", comuna: "Dragoesti" },
  { nume: "Chiroiu-Ungureni", comuna: "Dragoesti" },
  { nume: "Ciocârlia", simplu: "Ciocarlia" },
  { nume: "Ciochina" },
  { nume: "Ciulniţa", simplu: "Ciulnita" },
  { nume: "Cocora" },
  { nume: "Colelia", comuna: "Cocora" },
  { nume: "Condeeşti", simplu: "Condeesti", comuna: "Barcanesti" },
  { nume: "Copuzu", comuna: "Balaciu" },
  { nume: "Cosâmbeşti", simplu: "Cosambesti" },
  { nume: "Coşereni", simplu: "Cosereni" },
  { nume: "Cotorca", comuna: "Ciocarlia" },
  { nume: "Crăsanii de Jos", simplu: "Crasanii de Jos", comuna: "Balaciu" },
  { nume: "Crăsanii de Sus", simplu: "Crasanii de Sus", comuna: "Balaciu" },
  { nume: "Crunţi", simplu: "Crunti", comuna: "Reviga" },
  { nume: "Drăgoeşti", simplu: "Dragoesti" },
  { nume: "Dridu-Snagov", comuna: "Dridu" },
  { nume: "Dridu" },
  { nume: "Dumitreşti", simplu: "Dumitresti", comuna: "Valea Ciorii" },
  { nume: "Făcăeni", simplu: "Facaeni" },
  { nume: "Feteşti-Gară", simplu: "Fetesti-Gara", comuna: "Fetesti" },
  { nume: "Feteşti", simplu: "Fetesti" },
  { nume: "Fierbinţi-Târg", simplu: "Fierbinti-Targ" },
  {
    nume: "Fierbinţii de Jos",
    simplu: "Fierbintii de Jos",
    comuna: "Fierbinti-Targ",
  },
  {
    nume: "Fierbinţii de Sus",
    simplu: "Fierbintii de Sus",
    comuna: "Fierbinti-Targ",
  },
  { nume: "Frăţileşti", simplu: "Fratilesti", comuna: "Saveni" },
  { nume: "Fundata", comuna: "Perieti" },
  { nume: "Gârbovi", simplu: "Garbovi" },
  { nume: "Gheorghe Doja" },
  { nume: "Gheorghe Lazăr", simplu: "Gheorghe Lazar" },
  { nume: "Gimbăşani", simplu: "Gimbasani", comuna: "Cosambesti" },
  { nume: "Giurgeni" },
  { nume: "Grecii de Jos", comuna: "Fierbinti-Targ" },
  { nume: "Grindaşi", simplu: "Grindasi", comuna: "Valea Macrisului" },
  { nume: "Grindu" },
  { nume: "Griviţa", simplu: "Grivita" },
  {
    nume: "Gura Ialomiţei",
    simplu: "Gura Ialomitei",
    comuna: "Mihail Kogalniceanu",
  },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Suditi" },
  { nume: "Hagieni", comuna: "Mihail Kogalniceanu" },
  { nume: "Hagieşti", simplu: "Hagiesti", comuna: "Sinesti" },
  { nume: "Horia", comuna: "Axintele" },
  { nume: "Iazu", comuna: "Scanteia" },
  { nume: "Ion Ghica", comuna: "Ciulnita" },
  { nume: "Ion Roată", simplu: "Ion Roata" },
  { nume: "Ivăneşti", simplu: "Ivanesti", comuna: "Ciulnita" },
  { nume: "Jilavele" },
  { nume: "Lăcusteni", simplu: "Lacusteni", comuna: "Saveni" },
  { nume: "Lilieci", comuna: "Sinesti" },
  { nume: "Livedea", comuna: "Sinesti" },
  { nume: "Luciu", comuna: "Mihail Kogalniceanu" },
  { nume: "Maia", comuna: "Brazii" },
  { nume: "Maltezi", comuna: "Stelnica" },
  { nume: "Malu Roşu", simplu: "Malu Rosu", comuna: "Armasesti" },
  { nume: "Malu", comuna: "Sfantu Gheorghe" },
  { nume: "Manasia" },
  { nume: "Mărculeşti", simplu: "Marculesti", comuna: "Cosambesti" },
  { nume: "Marsilieni", comuna: "Albesti" },
  { nume: "Mihail Kogălniceanu", simplu: "Mihail Kogalniceanu" },
  { nume: "Miloşeşti", simplu: "Milosesti" },
  { nume: "Mircea cel Bătrân", simplu: "Mircea cel Batran", comuna: "Reviga" },
  { nume: "Misleanu", comuna: "Perieti" },
  { nume: "Moldoveni", comuna: "Dridu" },
  { nume: "Movila" },
  { nume: "Movileanca", comuna: "Brazii" },
  { nume: "Moviliţa", simplu: "Movilita" },
  { nume: "Munteni-Buzău", simplu: "Munteni-Buzau" },
  { nume: "Murgeanca", comuna: "Valea Ciorii" },
  { nume: "Nenişori", simplu: "Nenisori", comuna: "Armasesti" },
  { nume: "Nicoleşti", simplu: "Nicolesti", comuna: "Milosesti" },
  { nume: "Ograda", comuna: "Bucu" },
  { nume: "Orboeşti", simplu: "Orboesti", comuna: "Andrasesti" },
  { nume: "Orezu", comuna: "Ciochina" },
  { nume: "Păltinişu", simplu: "Paltinisu", comuna: "Perieti" },
  { nume: "Patru Fraţi", simplu: "Patru Frati", comuna: "Adancata" },
  { nume: "Perieţi", simplu: "Perieti" },
  { nume: "Piersica", comuna: "Ciochina" },
  { nume: "Platoneşti", simplu: "Platonesti", comuna: "Saveni" },
  { nume: "Poiana", comuna: "Ciulnita" },
  { nume: "Progresu", comuna: "Facaeni" },
  { nume: "Raşi", simplu: "Rasi", comuna: "Salcioara" },
  { nume: "Răsimnicea", simplu: "Rasimnicea", comuna: "Brazii" },
  { nume: "Retezatu", comuna: "Stelnica" },
  { nume: "Reviga" },
  { nume: "Roşiori", simplu: "Rosiori", comuna: "Movilita" },
  { nume: "Rovine", comuna: "Reviga" },
  { nume: "Sălcioara", simplu: "Salcioara" },
  { nume: "Sărăţeni", simplu: "Sarateni", comuna: "Balaciu" },
  { nume: "Săveni", simplu: "Saveni" },
  { nume: "Scânteia", simplu: "Scanteia" },
  { nume: "Sfântu Gheorghe", simplu: "Sfantu Gheorghe" },
  { nume: "Sineşti", simplu: "Sinesti" },
  { nume: "Sinteşti", simplu: "Sintesti", comuna: "Cosereni" },
  { nume: "Slătioarele", simplu: "Slatioarele", comuna: "Jilavele" },
  { nume: "Slobozia Nouă", simplu: "Slobozia Noua", comuna: "Slobozia" },
  { nume: "Slobozia" },
  { nume: "Smirna", comuna: "Grivita" },
  { nume: "Stejaru", comuna: "Perieti" },
  { nume: "Stelnica" },
  { nume: "Sudiţi", simplu: "Suditi" },
  { nume: "Ţăndărei", simplu: "Tandarei" },
  { nume: "Tovărăşia", simplu: "Tovarasia", comuna: "Milosesti" },
  { nume: "Traian" },
  { nume: "Urziceni" },
  { nume: "Valea Bisericii", comuna: "Dragoesti" },
  { nume: "Valea Ciorii" },
  { nume: "Valea Măcrişului", simplu: "Valea Macrisului" },
  { nume: "Vlădeni", simplu: "Vladeni" },
  { nume: "Vlaşca", simplu: "Vlasca", comuna: "Fetesti" },
];
