export const is = [
  { nume: "Alexandru I. Cuza" },
  { nume: "Andrieseni" },
  { nume: "Aroneanu" },
  { nume: "Bals" },
  { nume: "Belcesti" },
  { nume: "Bivolari" },
  { nume: "Braesti" },
  { nume: "Butea" },
  { nume: "Barnova" },
  { nume: "Baltati" },
  { nume: "Ceplenita" },
  { nume: "Ciortesti" },
  { nume: "Ciurea" },
  { nume: "Coarnele Caprei" },
  { nume: "Comarna" },
  { nume: "Costesti" },
  { nume: "Costuleni" },
  { nume: "Cotnari" },
  { nume: "Cozmesti" },
  { nume: "Cristesti" },
  { nume: "Cucuteni" },
  { nume: "Dagata" },
  { nume: "Deleni" },
  { nume: "Dobrovat" },
  { nume: "Dolhesti" },
  { nume: "Draguseni" },
  { nume: "Dumesti" },
  { nume: "Erbiceni" },
  { nume: "Focuri" },
  { nume: "Golaiesti" },
  { nume: "Gorban" },
  { nume: "Grajduri" },
  { nume: "Gropnita" },
  { nume: "Grozesti" },
  { nume: "Helesteni" },
  { nume: "Holboca" },
  { nume: "Horlesti" },
  { nume: "Harlau" },
  { nume: "Halaucesti" },
  { nume: "Iasi" },
  { nume: "Ipatele" },
  { nume: "Lespezi" },
  { nume: "Letcani" },
  { nume: "Lungani" },
  { nume: "Mircesti" },
  { nume: "Mironeasa" },
  { nume: "Miroslava" },
  { nume: "Miroslovesti" },
  { nume: "Mogosesti" },
  { nume: "Mogosesti-Siret" },
  { nume: "Movileni" },
  { nume: "Mosna" },
  { nume: "Motca" },
  { nume: "Madarjac" },
  { nume: "Oteleni" },
  { nume: "Pascani" },
  { nume: "Plugari" },
  { nume: "Podu Iloaiei" },
  { nume: "Popesti" },
  { nume: "Popricani" },
  { nume: "Prisacani" },
  { nume: "Probota" },
  { nume: "Rediu" },
  { nume: "Romanesti" },
  { nume: "Ruginoasa" },
  { nume: "Rachiteni" },
  { nume: "Raducaneni" },
  { nume: "Schitu Duca" },
  { nume: "Scobinti" },
  { nume: "Scanteia" },
  { nume: "Sinesti" },
  { nume: "Siretel" },
  { nume: "Stolniceni-Prajescu" },
  { nume: "Strunga" },
  { nume: "Tansa" },
  { nume: "Todiresti" },
  { nume: "Tomesti" },
  { nume: "Trifesti" },
  { nume: "Targu Frumos" },
  { nume: "Tatarusi" },
  { nume: "Ungheni" },
  { nume: "Valea Lupului" },
  { nume: "Valea Seaca" },
  { nume: "Victoria" },
  { nume: "Vladeni" },
  { nume: "Voinesti" },
  { nume: "Vanatori" },
  { nume: "Scheia" },
  { nume: "Sipote" },
  { nume: "Tibana" },
  { nume: "Tibanesti" },
  { nume: "Tiganasi" },
  { nume: "Tutora" },
  { nume: "Kogalniceni", comuna: "Alexandru I. Cuza" },
  { nume: "Scheia", comuna: "Alexandru I. Cuza" },
  { nume: "Volintiresti", comuna: "Alexandru I. Cuza" },
  { nume: "Buhaeni", comuna: "Andrieseni" },
  { nume: "Draganesti", comuna: "Andrieseni" },
  { nume: "Fantanele", comuna: "Andrieseni" },
  { nume: "Glavanesti", comuna: "Andrieseni" },
  { nume: "Iepureni", comuna: "Andrieseni" },
  { nume: "Spineni", comuna: "Andrieseni" },
  { nume: "Dorobant", comuna: "Aroneanu" },
  { nume: "Rediu Aldei", comuna: "Aroneanu" },
  { nume: "Sorogani", comuna: "Aroneanu" },
  { nume: "Boureni", comuna: "Bals" },
  { nume: "Cotargaci", comuna: "Baltati" },
  { nume: "Filiasi", comuna: "Baltati" },
  { nume: "Madarjesti", comuna: "Baltati" },
  { nume: "Podisu", comuna: "Baltati" },
  { nume: "Sarca", comuna: "Baltati" },
  { nume: "Valea Oilor", comuna: "Baltati" },
  { nume: "Cercu", comuna: "Barnova" },
  { nume: "Pietraria", comuna: "Barnova" },
  { nume: "Paun", comuna: "Barnova" },
  { nume: "Todirel", comuna: "Barnova" },
  { nume: "Visan", comuna: "Barnova" },
  { nume: "Liteni", comuna: "Belcesti" },
  { nume: "Munteni", comuna: "Belcesti" },
  { nume: "Satu Nou", comuna: "Belcesti" },
  { nume: "Tansa", comuna: "Belcesti" },
  { nume: "Ulmi", comuna: "Belcesti" },
  { nume: "Buruienesti", comuna: "Bivolari" },
  { nume: "Solonet", comuna: "Bivolari" },
  { nume: "Tabara", comuna: "Bivolari" },
  { nume: "Traian", comuna: "Bivolari" },
  { nume: "Albesti", comuna: "Braesti" },
  { nume: "Buda", comuna: "Braesti" },
  { nume: "Cristesti", comuna: "Braesti" },
  { nume: "Rediu", comuna: "Braesti" },
  { nume: "Miclauseni", comuna: "Butea" },
  { nume: "Buhalnita", comuna: "Ceplenita" },
  { nume: "Poiana Marului", comuna: "Ceplenita" },
  { nume: "Zlodica", comuna: "Ceplenita" },
  { nume: "Coropceni", comuna: "Ciortesti" },
  { nume: "Deleni", comuna: "Ciortesti" },
  { nume: "Rotaria", comuna: "Ciortesti" },
  { nume: "Serbesti", comuna: "Ciortesti" },
  { nume: "Curaturi", comuna: "Ciurea" },
  { nume: "Dumbrava", comuna: "Ciurea" },
  { nume: "Hlincea", comuna: "Ciurea" },
  { nume: "Lunca Cetatuii", comuna: "Ciurea" },
  { nume: "Picioru Lupului", comuna: "Ciurea" },
  { nume: "Slobozia", comuna: "Ciurea" },
  { nume: "Arama", comuna: "Coarnele Caprei" },
  { nume: "Petrosica", comuna: "Coarnele Caprei" },
  { nume: "Curagau", comuna: "Comarna" },
  { nume: "Osoi", comuna: "Comarna" },
  { nume: "Stanca", comuna: "Comarna" },
  { nume: "Covasna", comuna: "Costuleni" },
  { nume: "Cozia", comuna: "Costuleni" },
  { nume: "Hilita", comuna: "Costuleni" },
  { nume: "Bahluiu", comuna: "Cotnari" },
  { nume: "Cireseni", comuna: "Cotnari" },
  { nume: "Carjoaia", comuna: "Cotnari" },
  { nume: "Fagat", comuna: "Cotnari" },
  { nume: "Hodora", comuna: "Cotnari" },
  { nume: "Horodistea", comuna: "Cotnari" },
  { nume: "Iosupeni", comuna: "Cotnari" },
  { nume: "Luparia", comuna: "Cotnari" },
  { nume: "Valea Racului", comuna: "Cotnari" },
  { nume: "Zbereni", comuna: "Cotnari" },
  { nume: "Podolenii de Jos", comuna: "Cozmesti" },
  { nume: "Podolenii de Sus", comuna: "Cozmesti" },
  { nume: "Homita", comuna: "Cristesti" },
  { nume: "Baiceni", comuna: "Cucuteni" },
  { nume: "Barbatesti", comuna: "Cucuteni" },
  { nume: "Sacaresti", comuna: "Cucuteni" },
  { nume: "Boatca", comuna: "Dagata" },
  { nume: "Buzdug", comuna: "Dagata" },
  { nume: "Balusesti", comuna: "Dagata" },
  { nume: "Manastirea", comuna: "Dagata" },
  { nume: "Piscu Rusului", comuna: "Dagata" },
  { nume: "Poienile", comuna: "Dagata" },
  { nume: "Tarnita", comuna: "Dagata" },
  { nume: "Zece Prajini", comuna: "Dagata" },
  { nume: "Feredeni", comuna: "Deleni" },
  { nume: "Leahu-Nacu", comuna: "Deleni" },
  { nume: "Maxut", comuna: "Deleni" },
  { nume: "Poiana", comuna: "Deleni" },
  { nume: "Slobozia", comuna: "Deleni" },
  { nume: "Bradicesti", comuna: "Dolhesti" },
  { nume: "Pietris", comuna: "Dolhesti" },
  { nume: "Banu", comuna: "Dumesti" },
  { nume: "Chilisoaia", comuna: "Dumesti" },
  { nume: "Hoisesti", comuna: "Dumesti" },
  { nume: "Pausesti", comuna: "Dumesti" },
  { nume: "Barlesti", comuna: "Erbiceni" },
  { nume: "Spinoasa", comuna: "Erbiceni" },
  { nume: "Spranceana", comuna: "Erbiceni" },
  { nume: "Totoesti", comuna: "Erbiceni" },
  { nume: "Fantanele", comuna: "Fintinele" },
  { nume: "Bran", comuna: "Golaiesti" },
  { nume: "Cilibiu", comuna: "Golaiesti" },
  { nume: "Cotu lui Ivan", comuna: "Golaiesti" },
  { nume: "Gradinari", comuna: "Golaiesti" },
  { nume: "Medeleni", comuna: "Golaiesti" },
  { nume: "Petresti", comuna: "Golaiesti" },
  { nume: "Podu Jijiei", comuna: "Golaiesti" },
  { nume: "Gura Bohotin", comuna: "Gorban" },
  { nume: "Podu Hagiului", comuna: "Gorban" },
  { nume: "Scoposeni", comuna: "Gorban" },
  { nume: "Zberoaia", comuna: "Gorban" },
  { nume: "Corcodel", comuna: "Grajduri" },
  { nume: "Carbunari", comuna: "Grajduri" },
  { nume: "Lunca", comuna: "Grajduri" },
  { nume: "Poiana cu Cetate", comuna: "Grajduri" },
  { nume: "Padureni", comuna: "Grajduri" },
  { nume: "Valea Satului", comuna: "Grajduri" },
  { nume: "Bulbucani", comuna: "Gropnita" },
  { nume: "Forasti", comuna: "Gropnita" },
  { nume: "Malaesti", comuna: "Gropnita" },
  { nume: "Sangeri", comuna: "Gropnita" },
  { nume: "Saveni", comuna: "Gropnita" },
  { nume: "Coltu Cornii", comuna: "Grozesti" },
  { nume: "Salageni", comuna: "Grozesti" },
  { nume: "Luncasi", comuna: "Halaucesti" },
  { nume: "Parcovaci", comuna: "Harlau" },
  { nume: "Harmaneasa", comuna: "Helesteni" },
  { nume: "Movileni", comuna: "Helesteni" },
  { nume: "Oboroceni", comuna: "Helesteni" },
  { nume: "Cristesti", comuna: "Holboca" },
  { nume: "Dancu", comuna: "Holboca" },
  { nume: "Orzeni", comuna: "Holboca" },
  { nume: "Rusenii Noi", comuna: "Holboca" },
  { nume: "Rusenii Vechi", comuna: "Holboca" },
  { nume: "Valea Lunga", comuna: "Holboca" },
  { nume: "Bogdanesti", comuna: "Horlesti" },
  { nume: "Scoposeni", comuna: "Horlesti" },
  { nume: "Buznea", comuna: "Ion Neculce" },
  { nume: "Prigoreni", comuna: "Ion Neculce" },
  { nume: "Razboieni", comuna: "Ion Neculce" },
  { nume: "Alexesti", comuna: "Ipatele" },
  { nume: "Bacu", comuna: "Ipatele" },
  { nume: "Cuza Voda", comuna: "Ipatele" },
  { nume: "Buda", comuna: "Lespezi" },
  { nume: "Bursuc-Deal", comuna: "Lespezi" },
  { nume: "Bursuc-Vale", comuna: "Lespezi" },
  { nume: "Dumbrava", comuna: "Lespezi" },
  { nume: "Heci", comuna: "Lespezi" },
  { nume: "Bogonos", comuna: "Letcani" },
  { nume: "Cogeasca", comuna: "Letcani" },
  { nume: "Cucuteni", comuna: "Letcani" },
  { nume: "Crucea", comuna: "Lungani" },
  { nume: "Goesti", comuna: "Lungani" },
  { nume: "Zmeu", comuna: "Lungani" },
  { nume: "Bojila", comuna: "Madarjac" },
  { nume: "Frumusica", comuna: "Madarjac" },
  { nume: "Iugani", comuna: "Mircesti" },
  { nume: "Ursaresti", comuna: "Mircesti" },
  { nume: "Schitu Hadambului", comuna: "Mironeasa" },
  { nume: "Ursita", comuna: "Mironeasa" },
  { nume: "Balciu", comuna: "Miroslava" },
  { nume: "Bratuleni", comuna: "Miroslava" },
  { nume: "Ciurbesti", comuna: "Miroslava" },
  { nume: "Cornesti", comuna: "Miroslava" },
  { nume: "Dancas", comuna: "Miroslava" },
  { nume: "Gaureni", comuna: "Miroslava" },
  { nume: "Horpaz", comuna: "Miroslava" },
  { nume: "Proselnici", comuna: "Miroslava" },
  { nume: "Uricani", comuna: "Miroslava" },
  { nume: "Valea Adanca", comuna: "Miroslava" },
  { nume: "Valea Ursului", comuna: "Miroslava" },
  { nume: "Vorovesti", comuna: "Miroslava" },
  { nume: "Ciohorani", comuna: "Miroslovesti" },
  { nume: "Mitesti", comuna: "Miroslovesti" },
  { nume: "Soci", comuna: "Miroslovesti" },
  { nume: "Verseni", comuna: "Miroslovesti" },
  { nume: "Budesti", comuna: "Mogosesti" },
  { nume: "Hadambu", comuna: "Mogosesti" },
  { nume: "Manjesti", comuna: "Mogosesti" },
  { nume: "Muncelu de Sus", comuna: "Mogosesti-Siret" },
  { nume: "Tudor Vladimirescu", comuna: "Mogosesti-Siret" },
  { nume: "Boureni", comuna: "Motca" },
  { nume: "Iepureni", comuna: "Movileni" },
  { nume: "Larga-Jijia", comuna: "Movileni" },
  { nume: "Potangeni", comuna: "Movileni" },
  { nume: "Handresti", comuna: "Oteleni" },
  { nume: "Blagesti", comuna: "Pascani" },
  { nume: "Bosteni", comuna: "Pascani" },
  { nume: "Gastesti", comuna: "Pascani" },
  { nume: "Lunca", comuna: "Pascani" },
  { nume: "Sodomeni", comuna: "Pascani" },
  { nume: "Borosoaia", comuna: "Plugari" },
  { nume: "Onesti", comuna: "Plugari" },
  { nume: "Budai", comuna: "Podu Iloaiei" },
  { nume: "Cositeni", comuna: "Podu Iloaiei" },
  { nume: "Holm", comuna: "Podu Iloaiei" },
  { nume: "Scobalteni", comuna: "Podu Iloaiei" },
  { nume: "Doroscani", comuna: "Popesti" },
  { nume: "Harpasesti", comuna: "Popesti" },
  { nume: "Obrijeni", comuna: "Popesti" },
  { nume: "Padureni", comuna: "Popesti" },
  { nume: "Vama", comuna: "Popesti" },
  { nume: "Cotu Morii", comuna: "Popricani" },
  { nume: "Cuza Voda", comuna: "Popricani" },
  { nume: "Carlig", comuna: "Popricani" },
  { nume: "Moimesti", comuna: "Popricani" },
  { nume: "Rediu Mitropoliei", comuna: "Popricani" },
  { nume: "Vulturi", comuna: "Popricani" },
  { nume: "Vanatori", comuna: "Popricani" },
  { nume: "Tipilesti", comuna: "Popricani" },
  { nume: "Moreni", comuna: "Prisacani" },
  { nume: "Macaresti", comuna: "Prisacani" },
  { nume: "Balteni", comuna: "Probota" },
  { nume: "Perieni", comuna: "Probota" },
  { nume: "Izvoarele", comuna: "Rachiteni" },
  { nume: "Bohotin", comuna: "Raducaneni" },
  { nume: "Isaiia", comuna: "Raducaneni" },
  { nume: "Rosu", comuna: "Raducaneni" },
  { nume: "Breazu", comuna: "Rediu" },
  { nume: "Horlesti", comuna: "Rediu" },
  { nume: "Tautesti", comuna: "Rediu" },
  { nume: "Avantu", comuna: "Romanesti" },
  { nume: "Ursoaia", comuna: "Romanesti" },
  { nume: "Radeni", comuna: "Roscani" },
  { nume: "Dumbravita", comuna: "Ruginoasa" },
  { nume: "Rediu", comuna: "Ruginoasa" },
  { nume: "Vascani", comuna: "Ruginoasa" },
  { nume: "Bodesti", comuna: "Scanteia" },
  { nume: "Borosesti", comuna: "Scanteia" },
  { nume: "Ciocarlesti", comuna: "Scanteia" },
  { nume: "Lunca Rates", comuna: "Scanteia" },
  { nume: "Rediu", comuna: "Scanteia" },
  { nume: "Tufestii de Sus", comuna: "Scanteia" },
  { nume: "Cioca-Boca", comuna: "Scheia" },
  { nume: "Cauesti", comuna: "Scheia" },
  { nume: "Frenciugi", comuna: "Scheia" },
  { nume: "Poiana Scheii", comuna: "Scheia" },
  { nume: "Satu Nou", comuna: "Scheia" },
  { nume: "Blaga", comuna: "Schitu Duca" },
  { nume: "Dumitrestii Galatii", comuna: "Schitu Duca" },
  { nume: "Pocreaca", comuna: "Schitu Duca" },
  { nume: "Poiana", comuna: "Schitu Duca" },
  { nume: "Poieni", comuna: "Schitu Duca" },
  { nume: "Satu Nou", comuna: "Schitu Duca" },
  { nume: "Slobozia", comuna: "Schitu Duca" },
  { nume: "Badeni", comuna: "Scobinti" },
  { nume: "Fetesti", comuna: "Scobinti" },
  { nume: "Sticlaria", comuna: "Scobinti" },
  { nume: "Zagavia", comuna: "Scobinti" },
  { nume: "Bocnita", comuna: "Sinesti" },
  { nume: "Osoi", comuna: "Sinesti" },
  { nume: "Stornesti", comuna: "Sinesti" },
  { nume: "Chiscareni", comuna: "Sipote" },
  { nume: "Halceni", comuna: "Sipote" },
  { nume: "Iazu Nou", comuna: "Sipote" },
  { nume: "Iazu Vechi", comuna: "Sipote" },
  { nume: "Mitoc", comuna: "Sipote" },
  { nume: "Berezlogi", comuna: "Siretel" },
  { nume: "Humosu", comuna: "Siretel" },
  { nume: "Satu Nou", comuna: "Siretel" },
  { nume: "Slobozia", comuna: "Siretel" },
  { nume: "Bratesti", comuna: "Stolniceni-Prajescu" },
  { nume: "Cozmesti", comuna: "Stolniceni-Prajescu" },
  { nume: "Bratulesti", comuna: "Strunga" },
  { nume: "Crivesti", comuna: "Strunga" },
  { nume: "Cucova", comuna: "Strunga" },
  { nume: "Fedeleseni", comuna: "Strunga" },
  { nume: "Farcaseni", comuna: "Strunga" },
  { nume: "Gura Vaii", comuna: "Strunga" },
  { nume: "Habasesti", comuna: "Strunga" },
  { nume: "Suhulet", comuna: "Tansa" },
  { nume: "Coasta Magurii", comuna: "Targu Frumos" },
  { nume: "Dadesti", comuna: "Targu Frumos" },
  { nume: "Giurgesti", comuna: "Targu Frumos" },
  { nume: "Ganesti", comuna: "Targu Frumos" },
  { nume: "Ion Neculce", comuna: "Targu Frumos" },
  { nume: "Iorcani", comuna: "Tatarusi" },
  { nume: "Pietrosu", comuna: "Tatarusi" },
  { nume: "Uda", comuna: "Tatarusi" },
  { nume: "Valcica", comuna: "Tatarusi" },
  { nume: "Alexeni", comuna: "Tibana" },
  { nume: "Domnita", comuna: "Tibana" },
  { nume: "Garbesti", comuna: "Tibana" },
  { nume: "Moara Ciornei", comuna: "Tibana" },
  { nume: "Oproaia", comuna: "Tibana" },
  { nume: "Poiana Manastirii", comuna: "Tibana" },
  { nume: "Poiana de Sus", comuna: "Tibana" },
  { nume: "Runcu", comuna: "Tibana" },
  { nume: "Vadu Vejei", comuna: "Tibana" },
  { nume: "Glodenii Gandului", comuna: "Tibanesti" },
  { nume: "Griesti", comuna: "Tibanesti" },
  { nume: "Jigoreni", comuna: "Tibanesti" },
  { nume: "Recea", comuna: "Tibanesti" },
  { nume: "Rasboieni", comuna: "Tibanesti" },
  { nume: "Tungujei", comuna: "Tibanesti" },
  { nume: "Valenii", comuna: "Tibanesti" },
  { nume: "Carniceni", comuna: "Tiganasi" },
  { nume: "Mihail Kogalniceanu", comuna: "Tiganasi" },
  { nume: "Stejarii", comuna: "Tiganasi" },
  { nume: "Boldesti", comuna: "Todiresti" },
  { nume: "Baiceni", comuna: "Todiresti" },
  { nume: "Harmanestii Noi", comuna: "Todiresti" },
  { nume: "Harmanestii Vechi", comuna: "Todiresti" },
  { nume: "Stroesti", comuna: "Todiresti" },
  { nume: "Chicerea", comuna: "Tomesti" },
  { nume: "Goruni", comuna: "Tomesti" },
  { nume: "Vladiceni", comuna: "Tomesti" },
  { nume: "Hermeziu", comuna: "Trifesti" },
  { nume: "Roscani", comuna: "Trifesti" },
  { nume: "Vladomira", comuna: "Trifesti" },
  { nume: "Zaboloteni", comuna: "Trifesti" },
  { nume: "Chiperesti", comuna: "Tutora" },
  { nume: "Opriseni", comuna: "Tutora" },
  { nume: "Bosia", comuna: "Ungheni" },
  { nume: "Coada Stancii", comuna: "Ungheni" },
  { nume: "Manzatesti", comuna: "Ungheni" },
  { nume: "Contesti", comuna: "Valea Seaca" },
  { nume: "Topile", comuna: "Valea Seaca" },
  { nume: "Crivesti", comuna: "Vanatori" },
  { nume: "Gura Badilitei", comuna: "Vanatori" },
  { nume: "Hartoape", comuna: "Vanatori" },
  { nume: "Vladnicut", comuna: "Vanatori" },
  { nume: "Frasuleni", comuna: "Victoria" },
  { nume: "Icuseni", comuna: "Victoria" },
  { nume: "Luceni", comuna: "Victoria" },
  { nume: "Sculeni", comuna: "Victoria" },
  { nume: "Stanca", comuna: "Victoria" },
  { nume: "Sendreni", comuna: "Victoria" },
  { nume: "Alexandru cel Bun", comuna: "Vladeni" },
  { nume: "Borsa", comuna: "Vladeni" },
  { nume: "Brosteni", comuna: "Vladeni" },
  { nume: "Iacobeni", comuna: "Vladeni" },
  { nume: "Valcelele", comuna: "Vladeni" },
  { nume: "Lungani", comuna: "Voinesti" },
  { nume: "Schitu Stavnic", comuna: "Voinesti" },
  { nume: "Slobozia", comuna: "Voinesti" },
  { nume: "Vocotesti", comuna: "Voinesti" },
];
