export const ilf = [
  { nume: "1 Decembrie" },
  { nume: "Afumați", simplu: "Afumati" },
  { nume: "Alunișu", simplu: "Alunisu", comuna: "Magurele" },
  { nume: "Bălăceanca", simplu: "Balaceanca", comuna: "Cernica" },
  { nume: "Balotești", simplu: "Balotesti" },
  { nume: "Balta Neagră", simplu: "Balta Neagra", comuna: "Nuci" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Peris" },
  { nume: "Berceni" },
  { nume: "Bragadiru" },
  { nume: "Brănești", simplu: "Branesti" },
  { nume: "Buciumeni", comuna: "Buftea" },
  { nume: "Buda", comuna: "Cornetu" },
  { nume: "Buftea" },
  { nume: "Buriaș", simplu: "Burias", comuna: "Peris" },
  { nume: "Căciulați", simplu: "Caciulati", comuna: "Moara Vlasiei" },
  { nume: "Căldăraru", simplu: "Caldararu", comuna: "Cernica" },
  { nume: "Cățelu", simplu: "Catelu", comuna: "Glina" },
  { nume: "Cernica" },
  { nume: "Chiajna" },
  { nume: "Chitila" },
  { nume: "Cioflinceni", comuna: "Snagov" },
  { nume: "Ciolpani" },
  { nume: "Ciorogârla", simplu: "Ciorogarla" },
  { nume: "Clinceni" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "1 Decembrie" },
  { nume: "Corbeanca" },
  { nume: "Cornetu" },
  { nume: "Cozieni", comuna: "Ganeasa" },
  { nume: "Creața", simplu: "Creata", comuna: "Dascalu" },
  { nume: "Crețești", simplu: "Cretesti", comuna: "Vidra" },
  { nume: "Crețuleasca", simplu: "Cretuleasca", comuna: "Stefanestii De Jos" },
  { nume: "Dărăști-Ilfov", simplu: "Darasti-Ilfov" },
  { nume: "Dârvari", simplu: "Darvari", comuna: "Ciorogarla" },
  { nume: "Dascălu", simplu: "Dascalu" },
  { nume: "Dimieni", comuna: "Tunari" },
  { nume: "Dobroești", simplu: "Dobroesti", comuna: "Dobroiesti" },
  { nume: "Domnești", simplu: "Domnesti" },
  {
    nume: "Dragomirești-Deal",
    simplu: "Dragomiresti-Deal",
    comuna: "Dragomiresti-Vale",
  },
  { nume: "Dragomirești-Vale", simplu: "Dragomiresti-Vale" },
  { nume: "Dudu", comuna: "Chiajna" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Balotesti" },
  { nume: "Dumitrana", comuna: "Magurele" },
  { nume: "Fundeni", comuna: "Dobroiesti" },
  { nume: "Gagu", comuna: "Dascalu" },
  { nume: "Găneasa", simplu: "Ganeasa" },
  { nume: "Ghermănești", simplu: "Ghermanesti", comuna: "Snagov" },
  { nume: "Glina" },
  { nume: "Grădiștea", simplu: "Gradistea" },
  { nume: "Gruiu" },
  { nume: "Islaz", comuna: "Branesti" },
  { nume: "Izvorani", comuna: "Ciolpani" },
  { nume: "Jilava" },
  { nume: "Lipia", comuna: "Gruiu" },
  { nume: "Lupăria", simplu: "Luparia", comuna: "Ciolpani" },
  { nume: "Măgurele", simplu: "Magurele" },
  { nume: "Măineasca", simplu: "Maineasca", comuna: "Petrachioaia" },
  { nume: "Manolache", comuna: "Glina" },
  { nume: "Merii Petchii", comuna: "Nuci" },
  { nume: "Micșuneștii Mari", simplu: "Micsunestii Mari", comuna: "Nuci" },
  { nume: "Micșuneștii-Moară", simplu: "Micsunestii-Moara", comuna: "Nuci" },
  { nume: "Moara Domnească", simplu: "Moara Domneasca", comuna: "Ganeasa" },
  { nume: "Moara Vlăsiei", simplu: "Moara Vlasiei" },
  { nume: "Mogoșoaia", simplu: "Mogosoaia" },
  { nume: "Nuci" },
  { nume: "Odăile", simplu: "Odaile", comuna: "Otopeni" },
  { nume: "Olteni", comuna: "Clinceni" },
  { nume: "Ordoreanu", comuna: "Clinceni" },
  { nume: "Ostratu", comuna: "Corbeanca" },
  { nume: "Otopeni" },
  { nume: "Pantelimon" },
  { nume: "Pasărea", simplu: "Pasarea", comuna: "Branesti" },
  { nume: "Periș", simplu: "Peris" },
  { nume: "Petrăchioaia", simplu: "Petrachioaia" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Corbeanca" },
  { nume: "Piscu", comuna: "Ciolpani" },
  { nume: "Piteasca", comuna: "Ganeasa" },
  { nume: "Popești Leordeni", simplu: "Popesti Leordeni" },
  { nume: "Poșta", simplu: "Posta", comuna: "Cernica" },
  { nume: "Pruni", comuna: "Magurele" },
  { nume: "Roșu", simplu: "Rosu", comuna: "Chiajna" },
  { nume: "Rudeni", comuna: "Chitila" },
  { nume: "Runcu", comuna: "Dascalu" },
  { nume: "Săftica", simplu: "Saftica", comuna: "Balotesti" },
  { nume: "Șanțu Florești", simplu: "Santu Floresti", comuna: "Gruiu" },
  {
    nume: "Siliștea Snagovului",
    simplu: "Silistea Snagovului",
    comuna: "Gruiu",
  },
  { nume: "Șindrilița", simplu: "Sindrilita", comuna: "Ganeasa" },
  { nume: "Sintești", simplu: "Sintesti", comuna: "Vidra" },
  { nume: "Sitaru", comuna: "Gradistea" },
  { nume: "Snagov" },
  { nume: "Ștefăneștii de Jos", simplu: "Stefanestii de Jos" },
  {
    nume: "Ștefăneștii de Sus",
    simplu: "Stefanestii de Sus",
    comuna: "Stefanestii De Jos",
  },
  { nume: "Surlari", comuna: "Petrachioaia" },
  { nume: "Tamași", simplu: "Tamasi", comuna: "Corbeanca" },
  { nume: "Tâncăbești", simplu: "Tancabesti", comuna: "Snagov" },
  { nume: "Tânganu", simplu: "Tanganu", comuna: "Cernica" },
  { nume: "Țegheș", simplu: "Teghes", comuna: "Domnesti" },
  { nume: "Tunari" },
  { nume: "Vadu Anei", comuna: "Branesti" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Petrachioaia" },
  { nume: "Vârteju", simplu: "Varteju", comuna: "Magurele" },
  { nume: "Vidra" },
  { nume: "Vlădiceasca", simplu: "Vladiceasca", comuna: "Snagov" },
  { nume: "Voluntari" },
  { nume: "Zurbaua", comuna: "Dragomiresti-Vale" },
];
