export const il = [
  { nume: "Adâncata", simplu: "Adancata" },
  { nume: "Albești", simplu: "Albesti" },
  { nume: "Alexeni" },
  { nume: "Amara Nouă", simplu: "Amara Noua", comuna: "Amara" },
  { nume: "Amara" },
  { nume: "Andrășești", simplu: "Andrasesti" },
  { nume: "Armășești", simplu: "Armasesti" },
  { nume: "Axintele" },
  { nume: "Balaciu" },
  { nume: "Bărbătescu", simplu: "Barbatescu", comuna: "Axintele" },
  { nume: "Bărbulești", simplu: "Barbulesti", comuna: "Armasesti" },
  { nume: "Bărcănești", simplu: "Barcanesti" },
  { nume: "Bataluri", comuna: "Albesti" },
  { nume: "Bițina-Pământeni", simplu: "Bitina-Pamanteni", comuna: "Movilita" },
  { nume: "Bițina-Ungureni", simplu: "Bitina-Ungureni", comuna: "Movilita" },
  { nume: "Bora", comuna: "Slobozia" },
  { nume: "Borănești", simplu: "Boranesti", comuna: "Cosereni" },
  { nume: "Bordușani", simplu: "Bordusani" },
  { nume: "Bordușelu", simplu: "Borduselu", comuna: "Ciochina" },
  { nume: "Boteni", comuna: "Sinesti" },
  { nume: "Brazii" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Ion Roata" },
  { nume: "Bucșa", simplu: "Bucsa", comuna: "Valea Ciorii" },
  { nume: "Bucu" },
  { nume: "Buești", simplu: "Buesti", comuna: "Albesti" },
  { nume: "Buliga", comuna: "Fetesti" },
  { nume: "Butoiu", comuna: "Sfantu Gheorghe" },
  { nume: "Cătrunești", simplu: "Catrunesti", comuna: "Sinesti" },
  { nume: "Căzănești", simplu: "Cazanesti" },
  { nume: "Cegani", comuna: "Bordusani" },
  {
    nume: "Chiroiu-Pamânteni",
    simplu: "Chiroiu-Pamanteni",
    comuna: "Dragoesti",
  },
  { nume: "Chiroiu-Satu Nou", comuna: "Dragoesti" },
  { nume: "Chiroiu-Ungureni", comuna: "Dragoesti" },
  { nume: "Ciocârlia", simplu: "Ciocarlia" },
  { nume: "Ciochina" },
  { nume: "Ciulnița", simplu: "Ciulnita" },
  { nume: "Cocora" },
  { nume: "Colelia", comuna: "Cocora" },
  { nume: "Condeești", simplu: "Condeesti", comuna: "Barcanesti" },
  { nume: "Copuzu", comuna: "Balaciu" },
  { nume: "Cosâmbești", simplu: "Cosambesti" },
  { nume: "Coșereni", simplu: "Cosereni" },
  { nume: "Cotorca", comuna: "Ciocarlia" },
  { nume: "Crăsanii de Jos", simplu: "Crasanii de Jos", comuna: "Balaciu" },
  { nume: "Crăsanii de Sus", simplu: "Crasanii de Sus", comuna: "Balaciu" },
  { nume: "Crunți", simplu: "Crunti", comuna: "Reviga" },
  { nume: "Drăgoești", simplu: "Dragoesti" },
  { nume: "Dridu-Snagov", comuna: "Dridu" },
  { nume: "Dridu" },
  { nume: "Dumitrești", simplu: "Dumitresti", comuna: "Valea Ciorii" },
  { nume: "Făcăeni", simplu: "Facaeni" },
  { nume: "Fetești-Gară", simplu: "Fetesti-Gara", comuna: "Fetesti" },
  { nume: "Fetești", simplu: "Fetesti" },
  { nume: "Fierbinți-Târg", simplu: "Fierbinti-Targ" },
  {
    nume: "Fierbinții de Jos",
    simplu: "Fierbintii de Jos",
    comuna: "Fierbinti-Targ",
  },
  {
    nume: "Fierbinții de Sus",
    simplu: "Fierbintii de Sus",
    comuna: "Fierbinti-Targ",
  },
  { nume: "Frățilești", simplu: "Fratilesti", comuna: "Saveni" },
  { nume: "Fundata", comuna: "Perieti" },
  { nume: "Gârbovi", simplu: "Garbovi" },
  { nume: "Gheorghe Doja" },
  { nume: "Gheorghe Lazăr", simplu: "Gheorghe Lazar" },
  { nume: "Gimbășani", simplu: "Gimbasani", comuna: "Cosambesti" },
  { nume: "Giurgeni" },
  { nume: "Grecii de Jos", comuna: "Fierbinti-Targ" },
  { nume: "Grindași", simplu: "Grindasi", comuna: "Valea Macrisului" },
  { nume: "Grindu" },
  { nume: "Grivița", simplu: "Grivita" },
  {
    nume: "Gura Ialomiței",
    simplu: "Gura Ialomitei",
    comuna: "Mihail Kogalniceanu",
  },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Suditi" },
  { nume: "Hagieni", comuna: "Mihail Kogalniceanu" },
  { nume: "Hagiești", simplu: "Hagiesti", comuna: "Sinesti" },
  { nume: "Horia", comuna: "Axintele" },
  { nume: "Iazu", comuna: "Scanteia" },
  { nume: "Ion Ghica", comuna: "Ciulnita" },
  { nume: "Ion Roată", simplu: "Ion Roata" },
  { nume: "Ivănești", simplu: "Ivanesti", comuna: "Ciulnita" },
  { nume: "Jilavele" },
  { nume: "Lăcusteni", simplu: "Lacusteni", comuna: "Saveni" },
  { nume: "Lilieci", comuna: "Sinesti" },
  { nume: "Livedea", comuna: "Sinesti" },
  { nume: "Luciu", comuna: "Mihail Kogalniceanu" },
  { nume: "Maia", comuna: "Brazii" },
  { nume: "Maltezi", comuna: "Stelnica" },
  { nume: "Malu Roșu", simplu: "Malu Rosu", comuna: "Armasesti" },
  { nume: "Malu", comuna: "Sfantu Gheorghe" },
  { nume: "Manasia" },
  { nume: "Mărculești", simplu: "Marculesti", comuna: "Cosambesti" },
  { nume: "Marsilieni", comuna: "Albesti" },
  { nume: "Mihail Kogălniceanu", simplu: "Mihail Kogalniceanu" },
  { nume: "Miloșești", simplu: "Milosesti" },
  { nume: "Mircea cel Bătrân", simplu: "Mircea cel Batran", comuna: "Reviga" },
  { nume: "Misleanu", comuna: "Perieti" },
  { nume: "Moldoveni", comuna: "Dridu" },
  { nume: "Movila" },
  { nume: "Movileanca", comuna: "Brazii" },
  { nume: "Movilița", simplu: "Movilita" },
  { nume: "Munteni-Buzău", simplu: "Munteni-Buzau" },
  { nume: "Murgeanca", comuna: "Valea Ciorii" },
  { nume: "Nenișori", simplu: "Nenisori", comuna: "Armasesti" },
  { nume: "Nicolești", simplu: "Nicolesti", comuna: "Milosesti" },
  { nume: "Ograda", comuna: "Bucu" },
  { nume: "Orboești", simplu: "Orboesti", comuna: "Andrasesti" },
  { nume: "Orezu", comuna: "Ciochina" },
  { nume: "Păltinișu", simplu: "Paltinisu", comuna: "Perieti" },
  { nume: "Patru Frați", simplu: "Patru Frati", comuna: "Adancata" },
  { nume: "Perieți", simplu: "Perieti" },
  { nume: "Piersica", comuna: "Ciochina" },
  { nume: "Platonești", simplu: "Platonesti", comuna: "Saveni" },
  { nume: "Poiana", comuna: "Ciulnita" },
  { nume: "Progresu", comuna: "Facaeni" },
  { nume: "Rași", simplu: "Rasi", comuna: "Salcioara" },
  { nume: "Răsimnicea", simplu: "Rasimnicea", comuna: "Brazii" },
  { nume: "Retezatu", comuna: "Stelnica" },
  { nume: "Reviga" },
  { nume: "Roșiori", simplu: "Rosiori", comuna: "Movilita" },
  { nume: "Rovine", comuna: "Reviga" },
  { nume: "Sălcioara", simplu: "Salcioara" },
  { nume: "Sărățeni", simplu: "Sarateni", comuna: "Balaciu" },
  { nume: "Săveni", simplu: "Saveni" },
  { nume: "Scânteia", simplu: "Scanteia" },
  { nume: "Sfântu Gheorghe", simplu: "Sfantu Gheorghe" },
  { nume: "Sinești", simplu: "Sinesti" },
  { nume: "Sintești", simplu: "Sintesti", comuna: "Cosereni" },
  { nume: "Slătioarele", simplu: "Slatioarele", comuna: "Jilavele" },
  { nume: "Slobozia Nouă", simplu: "Slobozia Noua", comuna: "Slobozia" },
  { nume: "Slobozia" },
  { nume: "Smirna", comuna: "Grivita" },
  { nume: "Stejaru", comuna: "Perieti" },
  { nume: "Stelnica" },
  { nume: "Sudiți", simplu: "Suditi" },
  { nume: "Țăndărei", simplu: "Tandarei" },
  { nume: "Tovărășia", simplu: "Tovarasia", comuna: "Milosesti" },
  { nume: "Traian" },
  { nume: "Urziceni" },
  { nume: "Valea Bisericii", comuna: "Dragoesti" },
  { nume: "Valea Ciorii" },
  { nume: "Valea Măcrișului", simplu: "Valea Macrisului" },
  { nume: "Vlădeni", simplu: "Vladeni" },
  { nume: "Vlașca", simplu: "Vlasca", comuna: "Fetesti" },
];
