export const is = [
  { nume: "Albeşti", simplu: "Albesti", comuna: "Braesti" },
  { nume: "Alexandru cel Bun", comuna: "Vladeni" },
  { nume: "Alexandru I. Cuza" },
  { nume: "Alexeni", comuna: "Tibana" },
  { nume: "Alexeşti", simplu: "Alexesti", comuna: "Ipatele" },
  { nume: "Andrieşeni", simplu: "Andrieseni" },
  { nume: "Arama", comuna: "Coarnele Caprei" },
  { nume: "Aroneanu" },
  { nume: "Avântu", simplu: "Avantu", comuna: "Romanesti" },
  { nume: "Bâcu", simplu: "Bacu", comuna: "Ipatele" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Scobinti" },
  { nume: "Bahluiu", comuna: "Cotnari" },
  { nume: "Băiceni", simplu: "Baiceni", comuna: "Cucuteni" },
  { nume: "Băiceni", simplu: "Baiceni", comuna: "Todiresti" },
  { nume: "Balciu", comuna: "Miroslava" },
  { nume: "Balş", simplu: "Bals" },
  { nume: "Bălţaţi", simplu: "Baltati" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Probota" },
  { nume: "Băluşeşti", simplu: "Balusesti", comuna: "Dagata" },
  { nume: "Banu", comuna: "Dumesti" },
  { nume: "Bărbăteşti", simplu: "Barbatesti", comuna: "Cucuteni" },
  { nume: "Bârleşti", simplu: "Barlesti", comuna: "Erbiceni" },
  { nume: "Bârnova", simplu: "Barnova" },
  { nume: "Belceşti", simplu: "Belcesti" },
  { nume: "Berezlogi", comuna: "Siretel" },
  { nume: "Bivolari" },
  { nume: "Blaga", comuna: "Schitu Duca" },
  { nume: "Blăgeşti", simplu: "Blagesti", comuna: "Pascani" },
  { nume: "Boatca", comuna: "Dagata" },
  { nume: "Bocniţa", simplu: "Bocnita", comuna: "Sinesti" },
  { nume: "Bodeşti", simplu: "Bodesti", comuna: "Scanteia" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Horlesti" },
  { nume: "Bogonos", comuna: "Letcani" },
  { nume: "Bohotin", comuna: "Raducaneni" },
  { nume: "Bojila", comuna: "Madarjac" },
  { nume: "Boldeşti", simplu: "Boldesti", comuna: "Todiresti" },
  { nume: "Boroşeşti", simplu: "Borosesti", comuna: "Scanteia" },
  { nume: "Borosoaia", comuna: "Plugari" },
  { nume: "Borşa", simplu: "Borsa", comuna: "Vladeni" },
  { nume: "Bosia", comuna: "Ungheni" },
  { nume: "Boşteni", simplu: "Bosteni", comuna: "Pascani" },
  { nume: "Boureni", comuna: "Bals" },
  { nume: "Boureni", comuna: "Motca" },
  { nume: "Brădiceşti", simplu: "Bradicesti", comuna: "Dolhesti" },
  { nume: "Brăeşti", simplu: "Braesti" },
  { nume: "Bran", comuna: "Golaiesti" },
  { nume: "Brăteşti", simplu: "Bratesti", comuna: "Stolniceni-Prajescu" },
  { nume: "Brătuleni", simplu: "Bratuleni", comuna: "Miroslava" },
  { nume: "Brătuleşti", simplu: "Bratulesti", comuna: "Strunga" },
  { nume: "Breazu", comuna: "Rediu" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Vladeni" },
  { nume: "Buda", comuna: "Braesti" },
  { nume: "Buda", comuna: "Lespezi" },
  { nume: "Budăi", simplu: "Budai", comuna: "Podu Iloaiei" },
  { nume: "Budeşti", simplu: "Budesti", comuna: "Mogosesti" },
  { nume: "Buhăeni", simplu: "Buhaeni", comuna: "Andrieseni" },
  { nume: "Buhalniţa", simplu: "Buhalnita", comuna: "Ceplenita" },
  { nume: "Bulbucani", comuna: "Gropnita" },
  { nume: "Bursuc-Deal", comuna: "Lespezi" },
  { nume: "Bursuc-Vale", comuna: "Lespezi" },
  { nume: "Buruieneşti", simplu: "Buruienesti", comuna: "Bivolari" },
  { nume: "Butea" },
  { nume: "Buzdug", comuna: "Dagata" },
  { nume: "Buznea", comuna: "Ion Neculce" },
  { nume: "Cărbunari", simplu: "Carbunari", comuna: "Grajduri" },
  { nume: "Cârjoaia", simplu: "Carjoaia", comuna: "Cotnari" },
  { nume: "Cârlig", simplu: "Carlig", comuna: "Popricani" },
  { nume: "Cârniceni", simplu: "Carniceni", comuna: "Tiganasi" },
  { nume: "Căueşti", simplu: "Cauesti", comuna: "Scheia" },
  { nume: "Cepleniţa", simplu: "Ceplenita" },
  { nume: "Cercu", comuna: "Barnova" },
  { nume: "Chicerea", comuna: "Tomesti" },
  { nume: "Chilişoaia", simplu: "Chilisoaia", comuna: "Dumesti" },
  { nume: "Chipereşti", simplu: "Chiperesti", comuna: "Tutora" },
  { nume: "Chişcăreni", simplu: "Chiscareni", comuna: "Sipote" },
  { nume: "Cilibiu", comuna: "Golaiesti" },
  { nume: "Cioca-Boca", comuna: "Scheia" },
  { nume: "Ciocârleşti", simplu: "Ciocarlesti", comuna: "Scanteia" },
  { nume: "Ciohorăni", simplu: "Ciohorani", comuna: "Miroslovesti" },
  { nume: "Ciorteşti", simplu: "Ciortesti" },
  { nume: "Cireşeni", simplu: "Cireseni", comuna: "Cotnari" },
  { nume: "Ciurbeşti", simplu: "Ciurbesti", comuna: "Miroslava" },
  { nume: "Ciurea" },
  { nume: "Coada Stâncii", simplu: "Coada Stancii", comuna: "Ungheni" },
  { nume: "Coarnele Caprei" },
  { nume: "Coasta Măgurii", simplu: "Coasta Magurii", comuna: "Targu Frumos" },
  { nume: "Cogeasca", comuna: "Letcani" },
  { nume: "Colţu Cornii", simplu: "Coltu Cornii", comuna: "Grozesti" },
  { nume: "Comarna" },
  { nume: "Conţeşti", simplu: "Contesti", comuna: "Valea Seaca" },
  { nume: "Corcodel", comuna: "Grajduri" },
  { nume: "Corneşti", simplu: "Cornesti", comuna: "Miroslava" },
  { nume: "Coropceni", comuna: "Ciortesti" },
  { nume: "Cosiţeni", simplu: "Cositeni", comuna: "Podu Iloaiei" },
  { nume: "Costeşti", simplu: "Costesti" },
  { nume: "Costuleni" },
  { nume: "Cotârgaci", simplu: "Cotargaci", comuna: "Baltati" },
  { nume: "Cotnari" },
  { nume: "Cotu lui Ivan", comuna: "Golaiesti" },
  { nume: "Cotu Morii", comuna: "Popricani" },
  { nume: "Covasna", comuna: "Costuleni" },
  { nume: "Cozia", comuna: "Costuleni" },
  { nume: "Cozmeşti", simplu: "Cozmesti" },
  { nume: "Cozmeşti", simplu: "Cozmesti", comuna: "Stolniceni-Prajescu" },
  { nume: "Cristeşti", simplu: "Cristesti" },
  { nume: "Cristeşti", simplu: "Cristesti", comuna: "Braesti" },
  { nume: "Cristeşti", simplu: "Cristesti", comuna: "Holboca" },
  { nume: "Criveşti", simplu: "Crivesti", comuna: "Strunga" },
  { nume: "Criveşti", simplu: "Crivesti", comuna: "Vanatori" },
  { nume: "Crucea", comuna: "Lungani" },
  { nume: "Cucova", comuna: "Strunga" },
  { nume: "Cucuteni" },
  { nume: "Cucuteni", comuna: "Letcani" },
  { nume: "Curagău", simplu: "Curagau", comuna: "Comarna" },
  { nume: "Curături", simplu: "Curaturi", comuna: "Ciurea" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Ipatele" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Popricani" },
  { nume: "Dădeşti", simplu: "Dadesti", comuna: "Targu Frumos" },
  { nume: "Dagâţa", simplu: "Dagata" },
  { nume: "Dancaş", simplu: "Dancas", comuna: "Miroslava" },
  { nume: "Dancu", comuna: "Holboca" },
  { nume: "Deleni" },
  { nume: "Deleni", comuna: "Ciortesti" },
  { nume: "Dobrovăţ", simplu: "Dobrovat" },
  { nume: "Dolheşti", simplu: "Dolhesti" },
  { nume: "Domniţa", simplu: "Domnita", comuna: "Tibana" },
  { nume: "Dorobanţ", simplu: "Dorobant", comuna: "Aroneanu" },
  { nume: "Doroşcani", simplu: "Doroscani", comuna: "Popesti" },
  { nume: "Drăgăneşti", simplu: "Draganesti", comuna: "Andrieseni" },
  { nume: "Drăguşeni", simplu: "Draguseni" },
  { nume: "Dumbrava", comuna: "Ciurea" },
  { nume: "Dumbrava", comuna: "Lespezi" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita", comuna: "Ruginoasa" },
  { nume: "Dumeşti", simplu: "Dumesti" },
  {
    nume: "Dumitreştii Gălăţii",
    simplu: "Dumitrestii Galatii",
    comuna: "Schitu Duca",
  },
  { nume: "Erbiceni" },
  { nume: "Făgăt", simplu: "Fagat", comuna: "Cotnari" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Andrieseni" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Fintinele" },
  { nume: "Fărcăşeni", simplu: "Farcaseni", comuna: "Strunga" },
  { nume: "Fedeleşeni", simplu: "Fedeleseni", comuna: "Strunga" },
  { nume: "Feredeni", comuna: "Deleni" },
  { nume: "Feteşti", simplu: "Fetesti", comuna: "Scobinti" },
  { nume: "Filiaşi", simplu: "Filiasi", comuna: "Baltati" },
  { nume: "Focuri" },
  { nume: "Forăşti", simplu: "Forasti", comuna: "Gropnita" },
  { nume: "Frăsuleni", simplu: "Frasuleni", comuna: "Victoria" },
  { nume: "Frenciugi", comuna: "Scheia" },
  { nume: "Frumuşica", simplu: "Frumusica", comuna: "Madarjac" },
  { nume: "Găneşti", simplu: "Ganesti", comuna: "Targu Frumos" },
  { nume: "Gârbeşti", simplu: "Garbesti", comuna: "Tibana" },
  { nume: "Gâşteşti", simplu: "Gastesti", comuna: "Pascani" },
  { nume: "Găureni", simplu: "Gaureni", comuna: "Miroslava" },
  { nume: "Giurgeşti", simplu: "Giurgesti", comuna: "Targu Frumos" },
  { nume: "Glăvăneşti", simplu: "Glavanesti", comuna: "Andrieseni" },
  {
    nume: "Glodenii Gândului",
    simplu: "Glodenii Gandului",
    comuna: "Tibanesti",
  },
  { nume: "Goeşti", simplu: "Goesti", comuna: "Lungani" },
  { nume: "Golăieşti", simplu: "Golaiesti" },
  { nume: "Gorban" },
  { nume: "Goruni", comuna: "Tomesti" },
  { nume: "Grădinari", simplu: "Gradinari", comuna: "Golaiesti" },
  { nume: "Grajduri" },
  { nume: "Grieşti", simplu: "Griesti", comuna: "Tibanesti" },
  { nume: "Gropniţa", simplu: "Gropnita" },
  { nume: "Grozeşti", simplu: "Grozesti" },
  { nume: "Gura Bâdiliţei", simplu: "Gura Badilitei", comuna: "Vanatori" },
  { nume: "Gura Bohotin", comuna: "Gorban" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Strunga" },
  { nume: "Hăbăşeşti", simplu: "Habasesti", comuna: "Strunga" },
  { nume: "Hadâmbu", simplu: "Hadambu", comuna: "Mogosesti" },
  { nume: "Hălăuceşti", simplu: "Halaucesti" },
  { nume: "Hălceni", simplu: "Halceni", comuna: "Sipote" },
  { nume: "Hândreşti", simplu: "Handresti", comuna: "Oteleni" },
  { nume: "Hârlău", simplu: "Harlau" },
  { nume: "Hărmăneasa", simplu: "Harmaneasa", comuna: "Helesteni" },
  { nume: "Hărmăneştii Noi", simplu: "Harmanestii Noi", comuna: "Todiresti" },
  {
    nume: "Hărmăneştii Vechi",
    simplu: "Harmanestii Vechi",
    comuna: "Todiresti",
  },
  { nume: "Hărpăşeşti", simplu: "Harpasesti", comuna: "Popesti" },
  { nume: "Hârtoape", simplu: "Hartoape", comuna: "Vanatori" },
  { nume: "Heci", comuna: "Lespezi" },
  { nume: "Heleşteni", simplu: "Helesteni" },
  { nume: "Hermeziu", comuna: "Trifesti" },
  { nume: "Hiliţa", simplu: "Hilita", comuna: "Costuleni" },
  { nume: "Hlincea", comuna: "Ciurea" },
  { nume: "Hodora", comuna: "Cotnari" },
  { nume: "Hoiseşti", simplu: "Hoisesti", comuna: "Dumesti" },
  { nume: "Holboca" },
  { nume: "Holm", comuna: "Podu Iloaiei" },
  { nume: "Homiţa", simplu: "Homita", comuna: "Cristesti" },
  { nume: "Horleşti", simplu: "Horlesti" },
  { nume: "Horleşti", simplu: "Horlesti", comuna: "Rediu" },
  { nume: "Horodiştea", simplu: "Horodistea", comuna: "Cotnari" },
  { nume: "Horpaz", comuna: "Miroslava" },
  { nume: "Humosu", comuna: "Siretel" },
  { nume: "Iacobeni", comuna: "Vladeni" },
  { nume: "Iaşi", simplu: "Iasi" },
  { nume: "Iazu Nou", comuna: "Sipote" },
  { nume: "Iazu Vechi", comuna: "Sipote" },
  { nume: "Icuşeni", simplu: "Icuseni", comuna: "Victoria" },
  { nume: "Iepureni", comuna: "Andrieseni" },
  { nume: "Iepureni", comuna: "Movileni" },
  { nume: "Ion Neculce", comuna: "Targu Frumos" },
  { nume: "Iorcani", comuna: "Tatarusi" },
  { nume: "Iosupeni", comuna: "Cotnari" },
  { nume: "Ipatele" },
  { nume: "Isaiia", comuna: "Raducaneni" },
  { nume: "Iugani", comuna: "Mircesti" },
  { nume: "Izvoarele", comuna: "Rachiteni" },
  { nume: "Jigoreni", comuna: "Tibanesti" },
  { nume: "Kogălniceni", simplu: "Kogalniceni", comuna: "Alexandru I. Cuza" },
  { nume: "Larga-Jijia", comuna: "Movileni" },
  { nume: "Leahu-Nacu", comuna: "Deleni" },
  { nume: "Lespezi" },
  { nume: "Leţcani", simplu: "Letcani" },
  { nume: "Liteni", comuna: "Belcesti" },
  { nume: "Luceni", comuna: "Victoria" },
  { nume: "Lunca Cetăţuii", simplu: "Lunca Cetatuii", comuna: "Ciurea" },
  { nume: "Lunca Rateş", simplu: "Lunca Rates", comuna: "Scanteia" },
  { nume: "Lunca", comuna: "Grajduri" },
  { nume: "Lunca", comuna: "Pascani" },
  { nume: "Luncaşi", simplu: "Luncasi", comuna: "Halaucesti" },
  { nume: "Lungani" },
  { nume: "Lungani", comuna: "Voinesti" },
  { nume: "Lupăria", simplu: "Luparia", comuna: "Cotnari" },
  { nume: "Măcăreşti", simplu: "Macaresti", comuna: "Prisacani" },
  { nume: "Mădârjac", simplu: "Madarjac" },
  { nume: "Mădârjeşti", simplu: "Madarjesti", comuna: "Baltati" },
  { nume: "Mălăeşti", simplu: "Malaesti", comuna: "Gropnita" },
  { nume: "Mănăstirea", simplu: "Manastirea", comuna: "Dagata" },
  { nume: "Mânjeşti", simplu: "Manjesti", comuna: "Mogosesti" },
  { nume: "Mânzăteşti", simplu: "Manzatesti", comuna: "Ungheni" },
  { nume: "Maxut", comuna: "Deleni" },
  { nume: "Medeleni", comuna: "Golaiesti" },
  { nume: "Miclăuşeni", simplu: "Miclauseni", comuna: "Butea" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Tiganasi",
  },
  { nume: "Mirceşti", simplu: "Mircesti" },
  { nume: "Mironeasa" },
  { nume: "Miroslava" },
  { nume: "Mirosloveşti", simplu: "Miroslovesti" },
  { nume: "Miteşti", simplu: "Mitesti", comuna: "Miroslovesti" },
  { nume: "Mitoc", comuna: "Sipote" },
  { nume: "Moara Ciornei", comuna: "Tibana" },
  { nume: "Mogoşeşti-Siret", simplu: "Mogosesti-Siret" },
  { nume: "Mogoşeşti", simplu: "Mogosesti" },
  { nume: "Moimeşti", simplu: "Moimesti", comuna: "Popricani" },
  { nume: "Moreni", comuna: "Prisacani" },
  { nume: "Moşna", simplu: "Mosna" },
  { nume: "Moţca", simplu: "Motca" },
  { nume: "Movileni" },
  { nume: "Movileni", comuna: "Helesteni" },
  { nume: "Muncelu de Sus", comuna: "Mogosesti-Siret" },
  { nume: "Munteni", comuna: "Belcesti" },
  { nume: "Oboroceni", comuna: "Helesteni" },
  { nume: "Obrijeni", comuna: "Popesti" },
  { nume: "Oneşti", simplu: "Onesti", comuna: "Plugari" },
  { nume: "Oprişeni", simplu: "Opriseni", comuna: "Tutora" },
  { nume: "Oproaia", comuna: "Tibana" },
  { nume: "Orzeni", comuna: "Holboca" },
  { nume: "Osoi", comuna: "Comarna" },
  { nume: "Osoi", comuna: "Sinesti" },
  { nume: "Oţeleni", simplu: "Oteleni" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Grajduri" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Popesti" },
  { nume: "Pârcovaci", simplu: "Parcovaci", comuna: "Harlau" },
  { nume: "Paşcani", simplu: "Pascani" },
  { nume: "Păun", simplu: "Paun", comuna: "Barnova" },
  { nume: "Păuşeşti", simplu: "Pausesti", comuna: "Dumesti" },
  { nume: "Perieni", comuna: "Probota" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Golaiesti" },
  { nume: "Petroşica", simplu: "Petrosica", comuna: "Coarnele Caprei" },
  { nume: "Picioru Lupului", comuna: "Ciurea" },
  { nume: "Pietrăria", simplu: "Pietraria", comuna: "Barnova" },
  { nume: "Pietriş", simplu: "Pietris", comuna: "Dolhesti" },
  { nume: "Pietrosu", comuna: "Tatarusi" },
  { nume: "Piscu Rusului", comuna: "Dagata" },
  { nume: "Plugari" },
  { nume: "Pocreaca", comuna: "Schitu Duca" },
  { nume: "Podişu", simplu: "Podisu", comuna: "Baltati" },
  { nume: "Podolenii de Jos", comuna: "Cozmesti" },
  { nume: "Podolenii de Sus", comuna: "Cozmesti" },
  { nume: "Podu Hagiului", comuna: "Gorban" },
  { nume: "Podu Iloaiei" },
  { nume: "Podu Jijiei", comuna: "Golaiesti" },
  { nume: "Poiana cu Cetate", comuna: "Grajduri" },
  { nume: "Poiana de Sus", comuna: "Tibana" },
  { nume: "Poiana Mănăstirii", simplu: "Poiana Manastirii", comuna: "Tibana" },
  { nume: "Poiana Mărului", simplu: "Poiana Marului", comuna: "Ceplenita" },
  { nume: "Poiana Şcheii", simplu: "Poiana Scheii", comuna: "Scheia" },
  { nume: "Poiana", comuna: "Deleni" },
  { nume: "Poiana", comuna: "Schitu Duca" },
  { nume: "Poieni", comuna: "Schitu Duca" },
  { nume: "Poienile", comuna: "Dagata" },
  { nume: "Popeşti", simplu: "Popesti" },
  { nume: "Popricani" },
  { nume: "Potângeni", simplu: "Potangeni", comuna: "Movileni" },
  { nume: "Prigoreni", comuna: "Ion Neculce" },
  { nume: "Prisăcani", simplu: "Prisacani" },
  { nume: "Probota" },
  { nume: "Proselnici", comuna: "Miroslava" },
  { nume: "Răchiteni", simplu: "Rachiteni" },
  { nume: "Rădeni", simplu: "Radeni", comuna: "Roscani" },
  { nume: "Răducăneni", simplu: "Raducaneni" },
  { nume: "Răsboieni", simplu: "Rasboieni", comuna: "Tibanesti" },
  { nume: "Războieni", simplu: "Razboieni", comuna: "Ion Neculce" },
  { nume: "Recea", comuna: "Tibanesti" },
  { nume: "Rediu Aldei", comuna: "Aroneanu" },
  { nume: "Rediu Mitropoliei", comuna: "Popricani" },
  { nume: "Rediu" },
  { nume: "Rediu", comuna: "Braesti" },
  { nume: "Rediu", comuna: "Ruginoasa" },
  { nume: "Rediu", comuna: "Scanteia" },
  { nume: "Româneşti", simplu: "Romanesti" },
  { nume: "Roşcani", simplu: "Roscani", comuna: "Trifesti" },
  { nume: "Roşu", simplu: "Rosu", comuna: "Raducaneni" },
  { nume: "Rotăria", simplu: "Rotaria", comuna: "Ciortesti" },
  { nume: "Ruginoasa" },
  { nume: "Runcu", comuna: "Tibana" },
  { nume: "Rusenii Noi", comuna: "Holboca" },
  { nume: "Rusenii Vechi", comuna: "Holboca" },
  { nume: "Săcăreşti", simplu: "Sacaresti", comuna: "Cucuteni" },
  { nume: "Sălăgeni", simplu: "Salageni", comuna: "Grozesti" },
  { nume: "Sângeri", simplu: "Sangeri", comuna: "Gropnita" },
  { nume: "Sârca", simplu: "Sarca", comuna: "Baltati" },
  { nume: "Satu Nou", comuna: "Belcesti" },
  { nume: "Satu Nou", comuna: "Scheia" },
  { nume: "Satu Nou", comuna: "Schitu Duca" },
  { nume: "Satu Nou", comuna: "Siretel" },
  { nume: "Săveni", simplu: "Saveni", comuna: "Gropnita" },
  { nume: "Scânteia", simplu: "Scanteia" },
  { nume: "Scheia", comuna: "Alexandru I. Cuza" },
  { nume: "Şcheia", simplu: "Scheia" },
  { nume: "Schitu Duca" },
  {
    nume: "Schitu Hadâmbului",
    simplu: "Schitu Hadambului",
    comuna: "Mironeasa",
  },
  { nume: "Schitu Stavnic", comuna: "Voinesti" },
  { nume: "Scobâlţeni", simplu: "Scobalteni", comuna: "Podu Iloaiei" },
  { nume: "Scobinţi", simplu: "Scobinti" },
  { nume: "Scoposeni", comuna: "Gorban" },
  { nume: "Scoposeni", comuna: "Horlesti" },
  { nume: "Sculeni", comuna: "Victoria" },
  { nume: "Şendreni", simplu: "Sendreni", comuna: "Victoria" },
  { nume: "Şerbeşti", simplu: "Serbesti", comuna: "Ciortesti" },
  { nume: "Sineşti", simplu: "Sinesti" },
  { nume: "Şipote", simplu: "Sipote" },
  { nume: "Sireţel", simplu: "Siretel" },
  { nume: "Slobozia", comuna: "Ciurea" },
  { nume: "Slobozia", comuna: "Deleni" },
  { nume: "Slobozia", comuna: "Schitu Duca" },
  { nume: "Slobozia", comuna: "Siretel" },
  { nume: "Slobozia", comuna: "Voinesti" },
  { nume: "Soci", comuna: "Miroslovesti" },
  { nume: "Sodomeni", comuna: "Pascani" },
  { nume: "Soloneţ", simplu: "Solonet", comuna: "Bivolari" },
  { nume: "Şorogani", simplu: "Sorogani", comuna: "Aroneanu" },
  { nume: "Spineni", comuna: "Andrieseni" },
  { nume: "Spinoasa", comuna: "Erbiceni" },
  { nume: "Sprânceana", simplu: "Spranceana", comuna: "Erbiceni" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Comarna" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Victoria" },
  { nume: "Stejarii", comuna: "Tiganasi" },
  { nume: "Sticlăria", simplu: "Sticlaria", comuna: "Scobinti" },
  { nume: "Stolniceni-Prăjescu", simplu: "Stolniceni-Prajescu" },
  { nume: "Storneşti", simplu: "Stornesti", comuna: "Sinesti" },
  { nume: "Stroeşti", simplu: "Stroesti", comuna: "Todiresti" },
  { nume: "Strunga" },
  { nume: "Suhuleţ", simplu: "Suhulet", comuna: "Tansa" },
  { nume: "Tabăra", simplu: "Tabara", comuna: "Bivolari" },
  { nume: "Tansa" },
  { nume: "Tansa", comuna: "Belcesti" },
  { nume: "Târgu Frumos", simplu: "Targu Frumos" },
  { nume: "Tarniţa", simplu: "Tarnita", comuna: "Dagata" },
  { nume: "Tătăruşi", simplu: "Tatarusi" },
  { nume: "Tăuteşti", simplu: "Tautesti", comuna: "Rediu" },
  { nume: "Ţibana", simplu: "Tibana" },
  { nume: "Ţibăneşti", simplu: "Tibanesti" },
  { nume: "Ţigănăşi", simplu: "Tiganasi" },
  { nume: "Ţipileşti", simplu: "Tipilesti", comuna: "Popricani" },
  { nume: "Todirel", comuna: "Barnova" },
  { nume: "Todireşti", simplu: "Todiresti" },
  { nume: "Tomeşti", simplu: "Tomesti" },
  { nume: "Topile", comuna: "Valea Seaca" },
  { nume: "Totoeşti", simplu: "Totoesti", comuna: "Erbiceni" },
  { nume: "Traian", comuna: "Bivolari" },
  { nume: "Trifeşti", simplu: "Trifesti" },
  { nume: "Tudor Vladimirescu", comuna: "Mogosesti-Siret" },
  { nume: "Tufeştii de Sus", simplu: "Tufestii de Sus", comuna: "Scanteia" },
  { nume: "Tungujei", comuna: "Tibanesti" },
  { nume: "Ţuţora", simplu: "Tutora" },
  { nume: "Uda", comuna: "Tatarusi" },
  { nume: "Ulmi", comuna: "Belcesti" },
  { nume: "Ungheni" },
  { nume: "Uricani", comuna: "Miroslava" },
  { nume: "Ursăreşti", simplu: "Ursaresti", comuna: "Mircesti" },
  { nume: "Urşiţa", simplu: "Ursita", comuna: "Mironeasa" },
  { nume: "Ursoaia", comuna: "Romanesti" },
  { nume: "Vadu Vejei", comuna: "Tibana" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Vladeni" },
  { nume: "Vâlcica", simplu: "Valcica", comuna: "Tatarusi" },
  { nume: "Valea Adâncă", simplu: "Valea Adanca", comuna: "Miroslava" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Holboca" },
  { nume: "Valea Lupului" },
  { nume: "Valea Oilor", comuna: "Baltati" },
  { nume: "Valea Racului", comuna: "Cotnari" },
  { nume: "Valea Satului", comuna: "Grajduri" },
  { nume: "Valea Seacă", simplu: "Valea Seaca" },
  { nume: "Valea Ursului", comuna: "Miroslava" },
  { nume: "Vălenii", simplu: "Valenii", comuna: "Tibanesti" },
  { nume: "Vama", comuna: "Popesti" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Popricani" },
  { nume: "Vascani", comuna: "Ruginoasa" },
  { nume: "Verşeni", simplu: "Verseni", comuna: "Miroslovesti" },
  { nume: "Victoria" },
  { nume: "Vişan", simplu: "Visan", comuna: "Barnova" },
  { nume: "Vlădeni", simplu: "Vladeni" },
  { nume: "Vlădiceni", simplu: "Vladiceni", comuna: "Tomesti" },
  { nume: "Vlădnicuţ", simplu: "Vladnicut", comuna: "Vanatori" },
  { nume: "Vladomira", comuna: "Trifesti" },
  { nume: "Vocoteşti", simplu: "Vocotesti", comuna: "Voinesti" },
  { nume: "Voineşti", simplu: "Voinesti" },
  { nume: "Volintireşti", simplu: "Volintiresti", comuna: "Alexandru I. Cuza" },
  { nume: "Voroveşti", simplu: "Vorovesti", comuna: "Miroslava" },
  { nume: "Vulturi", comuna: "Popricani" },
  { nume: "Zaboloteni", comuna: "Trifesti" },
  { nume: "Zagavia", comuna: "Scobinti" },
  { nume: "Zbereni", comuna: "Cotnari" },
  { nume: "Zberoaia", comuna: "Gorban" },
  { nume: "Zece Prăjini", simplu: "Zece Prajini", comuna: "Dagata" },
  { nume: "Zlodica", comuna: "Ceplenita" },
  { nume: "Zmeu", comuna: "Lungani" },
];
