export const ilf = [
  { nume: "1 Decembrie" },
  { nume: "Afumati" },
  { nume: "Balotesti" },
  { nume: "Berceni" },
  { nume: "Bragadiru" },
  { nume: "Branesti" },
  { nume: "Buftea" },
  { nume: "Cernica" },
  { nume: "Chiajna" },
  { nume: "Chitila" },
  { nume: "Ciolpani" },
  { nume: "Ciorogarla" },
  { nume: "Clinceni" },
  { nume: "Corbeanca" },
  { nume: "Cornetu" },
  { nume: "Dascalu" },
  { nume: "Domnesti" },
  { nume: "Dragomiresti-Vale" },
  { nume: "Darasti-Ilfov" },
  { nume: "Glina" },
  { nume: "Gruiu" },
  { nume: "Gradistea" },
  { nume: "Ganeasa" },
  { nume: "Jilava" },
  { nume: "Moara Vlasiei" },
  { nume: "Mogosoaia" },
  { nume: "Magurele" },
  { nume: "Nuci" },
  { nume: "Otopeni" },
  { nume: "Pantelimon" },
  { nume: "Peris" },
  { nume: "Petrachioaia" },
  { nume: "Popesti Leordeni" },
  { nume: "Snagov" },
  { nume: "Tunari" },
  { nume: "Vidra" },
  { nume: "Voluntari" },
  { nume: "Stefanestii de Jos" },
  { nume: "Copaceni", comuna: "1 Decembrie" },
  { nume: "Dumbraveni", comuna: "Balotesti" },
  { nume: "Saftica", comuna: "Balotesti" },
  { nume: "Islaz", comuna: "Branesti" },
  { nume: "Pasarea", comuna: "Branesti" },
  { nume: "Vadu Anei", comuna: "Branesti" },
  { nume: "Buciumeni", comuna: "Buftea" },
  { nume: "Balaceanca", comuna: "Cernica" },
  { nume: "Caldararu", comuna: "Cernica" },
  { nume: "Posta", comuna: "Cernica" },
  { nume: "Tanganu", comuna: "Cernica" },
  { nume: "Dudu", comuna: "Chiajna" },
  { nume: "Rosu", comuna: "Chiajna" },
  { nume: "Rudeni", comuna: "Chitila" },
  { nume: "Izvorani", comuna: "Ciolpani" },
  { nume: "Luparia", comuna: "Ciolpani" },
  { nume: "Piscu", comuna: "Ciolpani" },
  { nume: "Darvari", comuna: "Ciorogarla" },
  { nume: "Olteni", comuna: "Clinceni" },
  { nume: "Ordoreanu", comuna: "Clinceni" },
  { nume: "Ostratu", comuna: "Corbeanca" },
  { nume: "Petresti", comuna: "Corbeanca" },
  { nume: "Tamasi", comuna: "Corbeanca" },
  { nume: "Buda", comuna: "Cornetu" },
  { nume: "Creata", comuna: "Dascalu" },
  { nume: "Gagu", comuna: "Dascalu" },
  { nume: "Runcu", comuna: "Dascalu" },
  { nume: "Dobroesti", comuna: "Dobroiesti" },
  { nume: "Fundeni", comuna: "Dobroiesti" },
  { nume: "Teghes", comuna: "Domnesti" },
  { nume: "Dragomiresti-Deal", comuna: "Dragomiresti-Vale" },
  { nume: "Zurbaua", comuna: "Dragomiresti-Vale" },
  { nume: "Cozieni", comuna: "Ganeasa" },
  { nume: "Moara Domneasca", comuna: "Ganeasa" },
  { nume: "Piteasca", comuna: "Ganeasa" },
  { nume: "Sindrilita", comuna: "Ganeasa" },
  { nume: "Catelu", comuna: "Glina" },
  { nume: "Manolache", comuna: "Glina" },
  { nume: "Sitaru", comuna: "Gradistea" },
  { nume: "Lipia", comuna: "Gruiu" },
  { nume: "Silistea Snagovului", comuna: "Gruiu" },
  { nume: "Santu Floresti", comuna: "Gruiu" },
  { nume: "Alunisu", comuna: "Magurele" },
  { nume: "Dumitrana", comuna: "Magurele" },
  { nume: "Pruni", comuna: "Magurele" },
  { nume: "Varteju", comuna: "Magurele" },
  { nume: "Caciulati", comuna: "Moara Vlasiei" },
  { nume: "Balta Neagra", comuna: "Nuci" },
  { nume: "Merii Petchii", comuna: "Nuci" },
  { nume: "Micsunestii Mari", comuna: "Nuci" },
  { nume: "Micsunestii-Moara", comuna: "Nuci" },
  { nume: "Odaile", comuna: "Otopeni" },
  { nume: "Burias", comuna: "Peris" },
  { nume: "Balteni", comuna: "Peris" },
  { nume: "Maineasca", comuna: "Petrachioaia" },
  { nume: "Surlari", comuna: "Petrachioaia" },
  { nume: "Vanatori", comuna: "Petrachioaia" },
  { nume: "Cioflinceni", comuna: "Snagov" },
  { nume: "Ghermanesti", comuna: "Snagov" },
  { nume: "Tancabesti", comuna: "Snagov" },
  { nume: "Vladiceasca", comuna: "Snagov" },
  { nume: "Cretuleasca", comuna: "Stefanestii De Jos" },
  { nume: "Stefanestii de Sus", comuna: "Stefanestii De Jos" },
  { nume: "Dimieni", comuna: "Tunari" },
  { nume: "Cretesti", comuna: "Vidra" },
  { nume: "Sintesti", comuna: "Vidra" },
];
