export const ilf = [
  { nume: "1 Decembrie" },
  { nume: "Afumaţi", simplu: "Afumati" },
  { nume: "Alunişu", simplu: "Alunisu", comuna: "Magurele" },
  { nume: "Bălăceanca", simplu: "Balaceanca", comuna: "Cernica" },
  { nume: "Baloteşti", simplu: "Balotesti" },
  { nume: "Balta Neagră", simplu: "Balta Neagra", comuna: "Nuci" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Peris" },
  { nume: "Berceni" },
  { nume: "Bragadiru" },
  { nume: "Brăneşti", simplu: "Branesti" },
  { nume: "Buciumeni", comuna: "Buftea" },
  { nume: "Buda", comuna: "Cornetu" },
  { nume: "Buftea" },
  { nume: "Buriaş", simplu: "Burias", comuna: "Peris" },
  { nume: "Căciulaţi", simplu: "Caciulati", comuna: "Moara Vlasiei" },
  { nume: "Căldăraru", simplu: "Caldararu", comuna: "Cernica" },
  { nume: "Căţelu", simplu: "Catelu", comuna: "Glina" },
  { nume: "Cernica" },
  { nume: "Chiajna" },
  { nume: "Chitila" },
  { nume: "Cioflinceni", comuna: "Snagov" },
  { nume: "Ciolpani" },
  { nume: "Ciorogârla", simplu: "Ciorogarla" },
  { nume: "Clinceni" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "1 Decembrie" },
  { nume: "Corbeanca" },
  { nume: "Cornetu" },
  { nume: "Cozieni", comuna: "Ganeasa" },
  { nume: "Creaţa", simplu: "Creata", comuna: "Dascalu" },
  { nume: "Creţeşti", simplu: "Cretesti", comuna: "Vidra" },
  { nume: "Creţuleasca", simplu: "Cretuleasca", comuna: "Stefanestii De Jos" },
  { nume: "Dărăşti-Ilfov", simplu: "Darasti-Ilfov" },
  { nume: "Dârvari", simplu: "Darvari", comuna: "Ciorogarla" },
  { nume: "Dascălu", simplu: "Dascalu" },
  { nume: "Dimieni", comuna: "Tunari" },
  { nume: "Dobroeşti", simplu: "Dobroesti", comuna: "Dobroiesti" },
  { nume: "Domneşti", simplu: "Domnesti" },
  {
    nume: "Dragomireşti-Deal",
    simplu: "Dragomiresti-Deal",
    comuna: "Dragomiresti-Vale",
  },
  { nume: "Dragomireşti-Vale", simplu: "Dragomiresti-Vale" },
  { nume: "Dudu", comuna: "Chiajna" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Balotesti" },
  { nume: "Dumitrana", comuna: "Magurele" },
  { nume: "Fundeni", comuna: "Dobroiesti" },
  { nume: "Gagu", comuna: "Dascalu" },
  { nume: "Găneasa", simplu: "Ganeasa" },
  { nume: "Ghermăneşti", simplu: "Ghermanesti", comuna: "Snagov" },
  { nume: "Glina" },
  { nume: "Grădiştea", simplu: "Gradistea" },
  { nume: "Gruiu" },
  { nume: "Islaz", comuna: "Branesti" },
  { nume: "Izvorani", comuna: "Ciolpani" },
  { nume: "Jilava" },
  { nume: "Lipia", comuna: "Gruiu" },
  { nume: "Lupăria", simplu: "Luparia", comuna: "Ciolpani" },
  { nume: "Măgurele", simplu: "Magurele" },
  { nume: "Măineasca", simplu: "Maineasca", comuna: "Petrachioaia" },
  { nume: "Manolache", comuna: "Glina" },
  { nume: "Merii Petchii", comuna: "Nuci" },
  { nume: "Micşuneştii Mari", simplu: "Micsunestii Mari", comuna: "Nuci" },
  { nume: "Micşuneştii-Moară", simplu: "Micsunestii-Moara", comuna: "Nuci" },
  { nume: "Moara Domnească", simplu: "Moara Domneasca", comuna: "Ganeasa" },
  { nume: "Moara Vlăsiei", simplu: "Moara Vlasiei" },
  { nume: "Mogoşoaia", simplu: "Mogosoaia" },
  { nume: "Nuci" },
  { nume: "Odăile", simplu: "Odaile", comuna: "Otopeni" },
  { nume: "Olteni", comuna: "Clinceni" },
  { nume: "Ordoreanu", comuna: "Clinceni" },
  { nume: "Ostratu", comuna: "Corbeanca" },
  { nume: "Otopeni" },
  { nume: "Pantelimon" },
  { nume: "Pasărea", simplu: "Pasarea", comuna: "Branesti" },
  { nume: "Periş", simplu: "Peris" },
  { nume: "Petrăchioaia", simplu: "Petrachioaia" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Corbeanca" },
  { nume: "Piscu", comuna: "Ciolpani" },
  { nume: "Piteasca", comuna: "Ganeasa" },
  { nume: "Popeşti Leordeni", simplu: "Popesti Leordeni" },
  { nume: "Poşta", simplu: "Posta", comuna: "Cernica" },
  { nume: "Pruni", comuna: "Magurele" },
  { nume: "Roşu", simplu: "Rosu", comuna: "Chiajna" },
  { nume: "Rudeni", comuna: "Chitila" },
  { nume: "Runcu", comuna: "Dascalu" },
  { nume: "Săftica", simplu: "Saftica", comuna: "Balotesti" },
  { nume: "Şanţu Floreşti", simplu: "Santu Floresti", comuna: "Gruiu" },
  {
    nume: "Siliştea Snagovului",
    simplu: "Silistea Snagovului",
    comuna: "Gruiu",
  },
  { nume: "Şindriliţa", simplu: "Sindrilita", comuna: "Ganeasa" },
  { nume: "Sinteşti", simplu: "Sintesti", comuna: "Vidra" },
  { nume: "Sitaru", comuna: "Gradistea" },
  { nume: "Snagov" },
  { nume: "Ştefăneştii de Jos", simplu: "Stefanestii de Jos" },
  {
    nume: "Ştefăneştii de Sus",
    simplu: "Stefanestii de Sus",
    comuna: "Stefanestii De Jos",
  },
  { nume: "Surlari", comuna: "Petrachioaia" },
  { nume: "Tamaşi", simplu: "Tamasi", comuna: "Corbeanca" },
  { nume: "Tâncăbeşti", simplu: "Tancabesti", comuna: "Snagov" },
  { nume: "Tânganu", simplu: "Tanganu", comuna: "Cernica" },
  { nume: "Ţegheş", simplu: "Teghes", comuna: "Domnesti" },
  { nume: "Tunari" },
  { nume: "Vadu Anei", comuna: "Branesti" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Petrachioaia" },
  { nume: "Vârteju", simplu: "Varteju", comuna: "Magurele" },
  { nume: "Vidra" },
  { nume: "Vlădiceasca", simplu: "Vladiceasca", comuna: "Snagov" },
  { nume: "Voluntari" },
  { nume: "Zurbaua", comuna: "Dragomiresti-Vale" },
];
