export const il = [
  { nume: "Adancata" },
  { nume: "Albesti" },
  { nume: "Alexeni" },
  { nume: "Amara" },
  { nume: "Andrasesti" },
  { nume: "Armasesti" },
  { nume: "Axintele" },
  { nume: "Balaciu" },
  { nume: "Bordusani" },
  { nume: "Brazii" },
  { nume: "Bucu" },
  { nume: "Barcanesti" },
  { nume: "Ciochina" },
  { nume: "Ciocarlia" },
  { nume: "Ciulnita" },
  { nume: "Cocora" },
  { nume: "Cosambesti" },
  { nume: "Cosereni" },
  { nume: "Cazanesti" },
  { nume: "Dridu" },
  { nume: "Dragoesti" },
  { nume: "Fetesti" },
  { nume: "Fierbinti-Targ" },
  { nume: "Facaeni" },
  { nume: "Gheorghe Doja" },
  { nume: "Gheorghe Lazar" },
  { nume: "Giurgeni" },
  { nume: "Grindu" },
  { nume: "Grivita" },
  { nume: "Garbovi" },
  { nume: "Ion Roata" },
  { nume: "Jilavele" },
  { nume: "Manasia" },
  { nume: "Mihail Kogalniceanu" },
  { nume: "Milosesti" },
  { nume: "Movila" },
  { nume: "Movilita" },
  { nume: "Munteni-Buzau" },
  { nume: "Perieti" },
  { nume: "Reviga" },
  { nume: "Scanteia" },
  { nume: "Sfantu Gheorghe" },
  { nume: "Sinesti" },
  { nume: "Slobozia" },
  { nume: "Stelnica" },
  { nume: "Suditi" },
  { nume: "Salcioara" },
  { nume: "Saveni" },
  { nume: "Traian" },
  { nume: "Urziceni" },
  { nume: "Valea Ciorii" },
  { nume: "Valea Macrisului" },
  { nume: "Vladeni" },
  { nume: "Tandarei" },
  { nume: "Patru Frati", comuna: "Adancata" },
  { nume: "Bataluri", comuna: "Albesti" },
  { nume: "Buesti", comuna: "Albesti" },
  { nume: "Marsilieni", comuna: "Albesti" },
  { nume: "Amara Noua", comuna: "Amara" },
  { nume: "Orboesti", comuna: "Andrasesti" },
  { nume: "Barbulesti", comuna: "Armasesti" },
  { nume: "Malu Rosu", comuna: "Armasesti" },
  { nume: "Nenisori", comuna: "Armasesti" },
  { nume: "Barbatescu", comuna: "Axintele" },
  { nume: "Horia", comuna: "Axintele" },
  { nume: "Copuzu", comuna: "Balaciu" },
  { nume: "Crasanii de Jos", comuna: "Balaciu" },
  { nume: "Crasanii de Sus", comuna: "Balaciu" },
  { nume: "Sarateni", comuna: "Balaciu" },
  { nume: "Condeesti", comuna: "Barcanesti" },
  { nume: "Cegani", comuna: "Bordusani" },
  { nume: "Maia", comuna: "Brazii" },
  { nume: "Movileanca", comuna: "Brazii" },
  { nume: "Rasimnicea", comuna: "Brazii" },
  { nume: "Ograda", comuna: "Bucu" },
  { nume: "Cotorca", comuna: "Ciocarlia" },
  { nume: "Borduselu", comuna: "Ciochina" },
  { nume: "Orezu", comuna: "Ciochina" },
  { nume: "Piersica", comuna: "Ciochina" },
  { nume: "Ion Ghica", comuna: "Ciulnita" },
  { nume: "Ivanesti", comuna: "Ciulnita" },
  { nume: "Poiana", comuna: "Ciulnita" },
  { nume: "Colelia", comuna: "Cocora" },
  { nume: "Gimbasani", comuna: "Cosambesti" },
  { nume: "Marculesti", comuna: "Cosambesti" },
  { nume: "Boranesti", comuna: "Cosereni" },
  { nume: "Sintesti", comuna: "Cosereni" },
  { nume: "Chiroiu-Pamanteni", comuna: "Dragoesti" },
  { nume: "Chiroiu-Satu Nou", comuna: "Dragoesti" },
  { nume: "Chiroiu-Ungureni", comuna: "Dragoesti" },
  { nume: "Valea Bisericii", comuna: "Dragoesti" },
  { nume: "Dridu-Snagov", comuna: "Dridu" },
  { nume: "Moldoveni", comuna: "Dridu" },
  { nume: "Progresu", comuna: "Facaeni" },
  { nume: "Buliga", comuna: "Fetesti" },
  { nume: "Fetesti-Gara", comuna: "Fetesti" },
  { nume: "Vlasca", comuna: "Fetesti" },
  { nume: "Fierbintii de Jos", comuna: "Fierbinti-Targ" },
  { nume: "Fierbintii de Sus", comuna: "Fierbinti-Targ" },
  { nume: "Grecii de Jos", comuna: "Fierbinti-Targ" },
  { nume: "Smirna", comuna: "Grivita" },
  { nume: "Brosteni", comuna: "Ion Roata" },
  { nume: "Slatioarele", comuna: "Jilavele" },
  { nume: "Gura Ialomitei", comuna: "Mihail Kogalniceanu" },
  { nume: "Hagieni", comuna: "Mihail Kogalniceanu" },
  { nume: "Luciu", comuna: "Mihail Kogalniceanu" },
  { nume: "Nicolesti", comuna: "Milosesti" },
  { nume: "Tovarasia", comuna: "Milosesti" },
  { nume: "Bitina-Pamanteni", comuna: "Movilita" },
  { nume: "Bitina-Ungureni", comuna: "Movilita" },
  { nume: "Rosiori", comuna: "Movilita" },
  { nume: "Fundata", comuna: "Perieti" },
  { nume: "Misleanu", comuna: "Perieti" },
  { nume: "Paltinisu", comuna: "Perieti" },
  { nume: "Stejaru", comuna: "Perieti" },
  { nume: "Crunti", comuna: "Reviga" },
  { nume: "Mircea cel Batran", comuna: "Reviga" },
  { nume: "Rovine", comuna: "Reviga" },
  { nume: "Rasi", comuna: "Salcioara" },
  { nume: "Fratilesti", comuna: "Saveni" },
  { nume: "Lacusteni", comuna: "Saveni" },
  { nume: "Platonesti", comuna: "Saveni" },
  { nume: "Iazu", comuna: "Scanteia" },
  { nume: "Butoiu", comuna: "Sfantu Gheorghe" },
  { nume: "Malu", comuna: "Sfantu Gheorghe" },
  { nume: "Boteni", comuna: "Sinesti" },
  { nume: "Catrunesti", comuna: "Sinesti" },
  { nume: "Hagiesti", comuna: "Sinesti" },
  { nume: "Lilieci", comuna: "Sinesti" },
  { nume: "Livedea", comuna: "Sinesti" },
  { nume: "Bora", comuna: "Slobozia" },
  { nume: "Slobozia Noua", comuna: "Slobozia" },
  { nume: "Maltezi", comuna: "Stelnica" },
  { nume: "Retezatu", comuna: "Stelnica" },
  { nume: "Gura Vaii", comuna: "Suditi" },
  { nume: "Bucsa", comuna: "Valea Ciorii" },
  { nume: "Dumitresti", comuna: "Valea Ciorii" },
  { nume: "Murgeanca", comuna: "Valea Ciorii" },
  { nume: "Grindasi", comuna: "Valea Macrisului" },
];
