export const ms = [
  { nume: "Abud", comuna: "Ghindari" },
  { nume: "Abuș", simplu: "Abus", comuna: "Mica" },
  { nume: "Acățari", simplu: "Acatari" },
  { nume: "Adămuș", simplu: "Adamus" },
  { nume: "Adrian", comuna: "Gurghiu" },
  { nume: "Adrianu Mare", comuna: "Galesti" },
  { nume: "Adrianu Mic", comuna: "Galesti" },
  { nume: "Agrișteu", simplu: "Agristeu", comuna: "Balauseri" },
  { nume: "Albești", simplu: "Albesti" },
  { nume: "Aluniș", simplu: "Alunis" },
  { nume: "Andreneasa", comuna: "Rastolita" },
  { nume: "Angofa", comuna: "Sighisoara" },
  { nume: "Apalina", comuna: "Reghin" },
  { nume: "Apold" },
  { nume: "Archita", comuna: "Vanatori" },
  { nume: "Arșița", simplu: "Arsita", comuna: "Hodac" },
  { nume: "Ațintiș", simplu: "Atintis" },
  { nume: "Aurel Vlaicu", comuna: "Sighisoara" },
  { nume: "Avrămești", simplu: "Avramesti", comuna: "Ludus" },
  { nume: "Băgaciu", simplu: "Bagaciu" },
  { nume: "Bahnea" },
  { nume: "Băița", simplu: "Baita", comuna: "Lunca" },
  { nume: "Băla", simplu: "Bala" },
  { nume: "Bălăușeri", simplu: "Balauseri" },
  { nume: "Balda", comuna: "Sarmasu" },
  { nume: "Band" },
  { nume: "Bâra", simplu: "Bara", comuna: "Magherani" },
  { nume: "Bărboși", simplu: "Barbosi", comuna: "Zau De Campie" },
  { nume: "Bărdești", simplu: "Bardesti", comuna: "Santana De Mures" },
  { nume: "Bârlibaș", simplu: "Barlibas", comuna: "Sanpetru De Campie" },
  { nume: "Bârlibășoaia", simplu: "Barlibasoaia", comuna: "Albesti" },
  { nume: "Bârza", simplu: "Barza", comuna: "Sanger" },
  { nume: "Batoș", simplu: "Batos" },
  { nume: "Bedeni", comuna: "Galesti" },
  { nume: "Beica de Jos" },
  { nume: "Beica de Sus", comuna: "Beica De Jos" },
  { nume: "Bereni", comuna: "Magherani" },
  { nume: "Berghia", comuna: "Panet" },
  { nume: "Bernadea", comuna: "Bahnea" },
  { nume: "Beu", comuna: "Miercurea Nirajului" },
  { nume: "Bezid", comuna: "Sangeorgiu De Padure" },
  { nume: "Bezidu Nou", comuna: "Sangeorgiu De Padure" },
  { nume: "Bicașu", simplu: "Bicasu", comuna: "Hodac" },
  { nume: "Bichiș", simplu: "Bichis" },
  { nume: "Bistra Mureșului", simplu: "Bistra Muresului", comuna: "Deda" },
  { nume: "Blidireasa", comuna: "Ibanesti" },
  { nume: "Bobohalma", comuna: "Tarnaveni" },
  { nume: "Bogata" },
  { nume: "Boiu", comuna: "Albesti" },
  { nume: "Bolintineni", comuna: "Pasareni" },
  { nume: "Bologaia", comuna: "Pogaceaua" },
  { nume: "Bord", comuna: "Cucerdea" },
  { nume: "Bordoșiu", simplu: "Bordosiu", comuna: "Fantanele" },
  { nume: "Borzia", comuna: "Rastolita" },
  { nume: "Botei", comuna: "Zau De Campie" },
  { nume: "Botez", comuna: "Atintis" },
  { nume: "Botorca", comuna: "Tarnaveni" },
  { nume: "Bozed", comuna: "Ceuasu De Campie" },
  { nume: "Bozeni", comuna: "Livezeni" },
  { nume: "Brădețelu", simplu: "Bradetelu", comuna: "Ibanesti" },
  { nume: "Brâncovenești", simplu: "Brancovenesti" },
  { nume: "Breaza" },
  { nume: "Budiu Mic", comuna: "Craciunesti" },
  { nume: "Bujor-Hodaie", comuna: "Zau De Campie" },
  { nume: "Bujor", comuna: "Mihesu De Campie" },
  { nume: "Căciulata", simplu: "Caciulata", comuna: "Riciu" },
  { nume: "Căcuciu", simplu: "Cacuciu", comuna: "Beica De Jos" },
  { nume: "Călimănești", simplu: "Calimanesti", comuna: "Fantanele" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Eremitu" },
  { nume: "Călușeri", simplu: "Caluseri", comuna: "Ernei" },
  { nume: "Câmpenița", simplu: "Campenita", comuna: "Ceuasu De Campie" },
  { nume: "Câmpu Cetății", simplu: "Campu Cetatii", comuna: "Eremitu" },
  { nume: "Cându", simplu: "Candu", comuna: "Magherani" },
  { nume: "Căpâlna de Sus", simplu: "Capalna de Sus", comuna: "Mica" },
  { nume: "Căpeți", simplu: "Capeti", comuna: "Sovata" },
  { nume: "Căpușu de Câmpie", simplu: "Capusu de Campie", comuna: "Iclanzel" },
  { nume: "Cașva", simplu: "Casva", comuna: "Gurghiu" },
  { nume: "Cecălaca", simplu: "Cecalaca", comuna: "Atintis" },
  { nume: "Ceie", comuna: "Ghindari" },
  { nume: "Cerghid", comuna: "Ungheni" },
  { nume: "Cerghizel", comuna: "Ungheni" },
  { nume: "Ceuaș", simplu: "Ceuas", comuna: "Mica" },
  { nume: "Ceuașu de Câmpie", simplu: "Ceuasu de Campie" },
  { nume: "Chendu", comuna: "Balauseri" },
  { nume: "Chețani", simplu: "Chetani" },
  { nume: "Chibed" },
  { nume: "Chiheru de Jos" },
  { nume: "Chiheru de Sus", comuna: "Chiheru De Jos" },
  { nume: "Chinari", comuna: "Santana De Mures" },
  { nume: "Chinciuș", simplu: "Chincius", comuna: "Adamus" },
  { nume: "Chirileu", comuna: "Sanpaul" },
  { nume: "Chisălița", simplu: "Chisalita", comuna: "Iclanzel" },
  { nume: "Ciba", comuna: "Crăciunești" },
  { nume: "Cibu", comuna: "Fantanele" },
  { nume: "Cinta", comuna: "Craciunesti" },
  { nume: "Cioarga", comuna: "Ludus" },
  { nume: "Ciobotani", comuna: "Stanceni" },
  { nume: "Cipăieni", simplu: "Cipaieni", comuna: "Sanger" },
  { nume: "Cipău", simplu: "Cipau", comuna: "Iernut" },
  { nume: "Ciretea", comuna: "Zau De Campie" },
  { nume: "Cirhagău", simplu: "Cirhagau", comuna: "Mihesu De Campie" },
  { nume: "Ciulea", comuna: "Pogaceaua" },
  { nume: "Ciurgău", simplu: "Ciurgau", comuna: "Ludus" },
  { nume: "Cloașterf", simplu: "Cloasterf", comuna: "Saschiz" },
  { nume: "Coasta Grindului", comuna: "Chetani" },
  { nume: "Coasta Mare", comuna: "Riciu" },
  { nume: "Comori", comuna: "Gurghiu" },
  { nume: "Corbești", simplu: "Corbesti", comuna: "Acatari" },
  { nume: "Cordoș", simplu: "Cordos", comuna: "Chetani" },
  { nume: "Cornești", simplu: "Cornesti", comuna: "Adamus" },
  { nume: "Cornești", simplu: "Cornesti", comuna: "Craciunesti" },
  { nume: "Coroi", comuna: "Coroisanmartin" },
  { nume: "Coroisânmărtin", simplu: "Coroisanmartin" },
  { nume: "Corunca", comuna: "Livezeni" },
  { nume: "Cotorinău", simplu: "Cotorinau", comuna: "Riciu" },
  { nume: "Cotuș", simplu: "Cotus", comuna: "Sangeorgiu De Mures" },
  { nume: "Cozma" },
  { nume: "Crăciunești", simplu: "Craciunesti" },
  { nume: "Crăiești", simplu: "Craiesti" },
  { nume: "Crăiești", simplu: "Craiesti", comuna: "Adamus" },
  { nume: "Criș", simplu: "Cris", comuna: "Danes" },
  { nume: "Cristești", simplu: "Cristesti" },
  { nume: "Cucerdea" },
  { nume: "Cuci" },
  { nume: "Cuieșd", simplu: "Cuiesd", comuna: "Panet" },
  { nume: "Culpiu", comuna: "Ceuasu De Campie" },
  { nume: "Cund", comuna: "Bahnea" },
  { nume: "Curețe", simplu: "Curete", comuna: "Riciu" },
  { nume: "Curteni", comuna: "Santana De Mures" },
  { nume: "Cuștelnic", simplu: "Custelnic", comuna: "Tarnaveni" },
  { nume: "Daia", comuna: "Apold" },
  { nume: "Daia", comuna: "Bahnea" },
  { nume: "Dalu", comuna: "Sanger" },
  { nume: "Dâmbău", simplu: "Dambau", comuna: "Adamus" },
  { nume: "Dâmbu", simplu: "Dambu", comuna: "Sanpetru De Campie" },
  { nume: "Dămieni", simplu: "Damieni", comuna: "Eremitu" },
  { nume: "Daneș", simplu: "Danes" },
  { nume: "Dătășeni", simplu: "Dataseni", comuna: "Cuci" },
  { nume: "Deag", comuna: "Iernut" },
  { nume: "Deaj", comuna: "Mica" },
  { nume: "Deda" },
  { nume: "Dedrad", comuna: "Batos" },
  { nume: "Deleni", comuna: "Ideciu De Jos" },
  { nume: "Deleni", comuna: "Pogaceaua" },
  { nume: "Delenii", comuna: "Bagaciu" },
  { nume: "Dileu Nou", comuna: "Sanpaul" },
  { nume: "Dileu Vechi", comuna: "Ogra" },
  { nume: "Dobra", comuna: "Papiu Ilarian" },
  { nume: "Drăculea Bandului", simplu: "Draculea Bandului", comuna: "Band" },
  { nume: "Drojdii", comuna: "Magherani" },
  { nume: "Dubiștea de Pădure", simplu: "Dubistea de Padure", comuna: "Hodac" },
  { nume: "Dulcea", comuna: "Ibanesti" },
  { nume: "Dumbrava", comuna: "Vatava" },
  { nume: "Dumbrăvioara", simplu: "Dumbravioara", comuna: "Ernei" },
  { nume: "Dumitreni", comuna: "Balauseri" },
  { nume: "Dumitreștii", simplu: "Dumitrestii", comuna: "Miercurea Nirajului" },
  { nume: "După Deal", simplu: "Dupa Deal", comuna: "Cuci" },
  { nume: "După Deal", simplu: "Dupa Deal", comuna: "Iclanzel" },
  { nume: "Ercea", comuna: "Bala" },
  { nume: "Eremieni", comuna: "Magherani" },
  { nume: "Eremitu" },
  { nume: "Ernei" },
  { nume: "Fânațe", simplu: "Fanate", comuna: "Band" },
  { nume: "Fânațe", simplu: "Fanate", comuna: "Faragau" },
  { nume: "Fânațe", simplu: "Fanate", comuna: "Iclanzel" },
  { nume: "Fânațe", simplu: "Fanate", comuna: "Taureni" },
  {
    nume: "Fânațele Căpușului",
    simplu: "Fanatele Capusului",
    comuna: "Iclanzel",
  },
  {
    nume: "Fânațele Mădărașului",
    simplu: "Fanatele Madarasului",
    comuna: "Band",
  },
  { nume: "Fânațele Socolului", simplu: "Fanatele Socolului", comuna: "Cozma" },
  { nume: "Fântâna Babii", simplu: "Fantana Babii", comuna: "Pogaceaua" },
  { nume: "Fântânele", simplu: "Fantanele" },
  { nume: "Fărăgău", simplu: "Faragau" },
  { nume: "Feleag", comuna: "Vanatori" },
  { nume: "Filea", comuna: "Deda" },
  { nume: "Filitelnic", comuna: "Balauseri" },
  { nume: "Filpișu Mare", simplu: "Filpisu Mare", comuna: "Breaza" },
  { nume: "Filpișu Mic", simplu: "Filpisu Mic", comuna: "Breaza" },
  { nume: "Fițcău", simplu: "Fitcau", comuna: "Alunis" },
  { nume: "Foi", comuna: "Crăciunești" },
  { nume: "Frunzeni", comuna: "Lunca" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Ludus" },
  { nume: "Fundoaia", comuna: "Gurghiu" },
  { nume: "Găiești", simplu: "Gaiesti", comuna: "Acatari" },
  { nume: "Gălăoaia", simplu: "Galaoaia", comuna: "Rastolita" },
  { nume: "Gălățeni", simplu: "Galateni", comuna: "Pasareni" },
  { nume: "Gălești", simplu: "Galesti" },
  { nume: "Gâmbuț", simplu: "Gambut", comuna: "Bichis" },
  { nume: "Gănești", simplu: "Ganesti" },
  {
    nume: "Gaura Sângerului",
    simplu: "Gaura Sangerului",
    comuna: "Zau De Campie",
  },
  { nume: "Gheja", comuna: "Ludus" },
  { nume: "Gheorghe Doja" },
  { nume: "Ghidașteu", simplu: "Ghidasteu", comuna: "Iclanzel" },
  { nume: "Ghindari" },
  { nume: "Ghinești", simplu: "Ghinesti", comuna: "Neaua" },
  { nume: "Giuluș", simplu: "Giulus", comuna: "Ogra" },
  { nume: "Giurgiș", simplu: "Giurgis", comuna: "Chetani" },
  { nume: "Glăjărie", simplu: "Glajarie", comuna: "Gurghiu" },
  { nume: "Glodeni" },
  { nume: "Gogan", comuna: "Bahnea" },
  { nume: "Goreni", comuna: "Batos" },
  { nume: "Gornești", simplu: "Gornesti" },
  { nume: "Grădini", simplu: "Gradini", comuna: "Valea Larga" },
  { nume: "Grâușorul", simplu: "Grausorul", comuna: "Vargata" },
  { nume: "Grebenișu de Câmpie", simplu: "Grebenisu de Campie" },
  { nume: "Grindeni", comuna: "Chetani" },
  {
    nume: "Groapa Rădăii",
    simplu: "Groapa Radaii",
    comuna: "Mihesu De Campie",
  },
  { nume: "Gruișor", simplu: "Gruisor", comuna: "Acatari" },
  { nume: "Gurghiu" },
  { nume: "Habic", comuna: "Petelea" },
  { nume: "Hădăreni", simplu: "Hadareni", comuna: "Chetani" },
  { nume: "Hagău", simplu: "Hagau", comuna: "Riciu" },
  { nume: "Hărănglab", simplu: "Haranglab", comuna: "Mica" },
  { nume: "Hărțău", simplu: "Hartau", comuna: "Panet" },
  { nume: "Herepea", comuna: "Adamus" },
  { nume: "Herghelia", comuna: "Ceuasu De Campie" },
  { nume: "Hetiur", comuna: "Sighisoara" },
  { nume: "Hodac" },
  { nume: "Hodaia", comuna: "Faragau" },
  { nume: "Hodoșa", simplu: "Hodosa" },
  { nume: "Iara de Mureș", simplu: "Iara de Mures", comuna: "Gornesti" },
  { nume: "Ibănești-Pădure", simplu: "Ibanesti-Padure", comuna: "Ibanesti" },
  { nume: "Ibănești", simplu: "Ibanesti" },
  { nume: "Icland", comuna: "Ernei" },
  { nume: "Iclandu Mare", comuna: "Iclanzel" },
  { nume: "Iclănzel", simplu: "Iclanzel" },
  { nume: "Ideciu de Jos" },
  { nume: "Ideciu de Sus", comuna: "Ideciu De Jos" },
  { nume: "Idicel-Pădure", simplu: "Idicel-Padure", comuna: "Brancovenesti" },
  { nume: "Idicel", comuna: "Brancovenesti" },
  { nume: "Idiciu", comuna: "Bahnea" },
  { nume: "Idrifaia", comuna: "Suplac" },
  { nume: "Iernut" },
  { nume: "Iernuțeni", simplu: "Iernuteni", comuna: "Reghin" },
  { nume: "Ihod", comuna: "Hodosa" },
  { nume: "Ilieni", comuna: "Gheorghe Doja" },
  { nume: "Ilieși", simplu: "Iliesi", comuna: "Sovata" },
  { nume: "Ilioara", comuna: "Gornesti" },
  { nume: "Iod", comuna: "Rastolita" },
  { nume: "Isla", comuna: "Hodosa" },
  { nume: "Iștan-Tău", simplu: "Istan-Tau", comuna: "Band" },
  { nume: "Iștihaza", simplu: "Istihaza", comuna: "Atintis" },
  { nume: "Ivănești", simplu: "Ivanesti", comuna: "Livezeni" },
  { nume: "Jabenița", simplu: "Jabenita", comuna: "Solovastru" },
  { nume: "Jacodu", comuna: "Vetca" },
  { nume: "Jacu", comuna: "Albesti" },
  { nume: "Lăpușna", simplu: "Lapusna", comuna: "Ibanesti" },
  { nume: "Larga", comuna: "Gurghiu" },
  { nume: "Larga", comuna: "Sarmasu" },
  { nume: "Lăscud", simplu: "Lascud", comuna: "Ogra" },
  { nume: "Laslău Mare", simplu: "Laslau Mare", comuna: "Suplac" },
  { nume: "Laslău Mic", simplu: "Laslau Mic", comuna: "Suplac" },
  { nume: "Lăureni", simplu: "Laureni", comuna: "Miercurea Nirajului" },
  { nume: "Lechincioara", comuna: "Sincai" },
  { nume: "Lechința", simplu: "Lechinta", comuna: "Iernut" },
  { nume: "Lefaia", comuna: "Craiesti" },
  { nume: "Leniș", simplu: "Lenis", comuna: "Riciu" },
  { nume: "Leordeni", comuna: "Gheorghe Doja" },
  { nume: "Leorința-Șăulia", simplu: "Leorinta-Saulia", comuna: "Saulia" },
  { nume: "Leorința", simplu: "Leorinta", comuna: "Grebenisu De Campie" },
  { nume: "Lepindea", comuna: "Bahnea" },
  { nume: "Linț", simplu: "Lint", comuna: "Chetani" },
  { nume: "Livezeni" },
  { nume: "Logig", comuna: "Lunca" },
  { nume: "Loțu", simplu: "Lotu", comuna: "Sangeorgiu De Padure" },
  { nume: "Luduș", simplu: "Ludus" },
  { nume: "Luieriu", comuna: "Suseni" },
  { nume: "Lunca Bradului" },
  { nume: "Lunca Mureșului", simplu: "Lunca Muresului", comuna: "Alunis" },
  { nume: "Lunca" },
  { nume: "Măcicășești", simplu: "Macicasesti", comuna: "Saulia" },
  { nume: "Mădăraș", simplu: "Madaras", comuna: "Band" },
  { nume: "Mădărășeni", simplu: "Madaraseni", comuna: "Iclanzel" },
  { nume: "Măgherani", simplu: "Magherani" },
  { nume: "Măgheruș", simplu: "Magherus", comuna: "Nades" },
  { nume: "Maia", comuna: "Magherani" },
  { nume: "Maiad", comuna: "Galesti" },
  { nume: "Maiorești", simplu: "Maioresti", comuna: "Rusii-Munti" },
  { nume: "Mălăești", simplu: "Malaesti", comuna: "Valea Larga" },
  { nume: "Maldaoci", comuna: "Atintis" },
  { nume: "Malea", comuna: "Zau De Campie" },
  { nume: "Mărășești", simplu: "Marasesti", comuna: "Band" },
  { nume: "Mărculeni", simplu: "Marculeni", comuna: "Magherani" },
  { nume: "Mătrici", simplu: "Matrici", comuna: "Eremitu" },
  { nume: "Merișor", simplu: "Merisor", comuna: "Glodeni" },
  { nume: "Merișoru", simplu: "Merisoru", comuna: "Papiu Ilarian" },
  { nume: "Meștera", simplu: "Mestera", comuna: "Stanceni" },
  { nume: "Mica" },
  { nume: "Miercurea Nirajului" },
  { nume: "Mihai Viteazu", comuna: "Saschiz" },
  { nume: "Miheșu de Câmpie", simplu: "Mihesu de Campie" },
  { nume: "Milășel", simplu: "Milasel", comuna: "Craiesti" },
  { nume: "Mirigioaia", comuna: "Hodac" },
  { nume: "Mitrești", simplu: "Mitresti", comuna: "Vargata" },
  { nume: "Moara de Jos", comuna: "Taureni" },
  { nume: "Mogoaia", comuna: "Mihesu De Campie" },
  { nume: "Moișa", simplu: "Moisa", comuna: "Glodeni" },
  { nume: "Morăreni", simplu: "Morareni", comuna: "Rusii-Munti" },
  { nume: "Morești", simplu: "Moresti", comuna: "Ungheni" },
  { nume: "Moruț", simplu: "Morut", comuna: "Sarmasu" },
  { nume: "Moșuni", simplu: "Mosuni", comuna: "Miercurea Nirajului" },
  { nume: "Mura Mare", comuna: "Gornesti" },
  { nume: "Mura Mică", simplu: "Mura Mica", comuna: "Gornesti" },
  { nume: "Mureni", comuna: "Vanatori" },
  { nume: "Mureșeni", simplu: "Mureseni", comuna: "Targu Mures" },
  { nume: "Murgești", simplu: "Murgesti", comuna: "Acatari" },
  { nume: "Nadășa", simplu: "Nadasa", comuna: "Beica De Jos" },
  { nume: "Nadeș", simplu: "Nades" },
  { nume: "Nandra", comuna: "Bichis" },
  { nume: "Nazna", comuna: "Sancraiu De Mures" },
  { nume: "Neagra", comuna: "Lunca Bradului" },
  { nume: "Neaua" },
  { nume: "Negrenii de Câmpie", simplu: "Negrenii de Campie", comuna: "Band" },
  { nume: "Nicolești", simplu: "Nicolesti", comuna: "Crăciunești" },
  { nume: "Nima Milășelului", simplu: "Nima Milaselului", comuna: "Craiesti" },
  { nume: "Nima Râciului", simplu: "Nima Raciului", comuna: "Riciu" },
  { nume: "Oarba de Mureș", simplu: "Oarba de Mures", comuna: "Iernut" },
  { nume: "Obârșie", simplu: "Obarsie", comuna: "Riciu" },
  { nume: "Odrihei", comuna: "Coroisanmartin" },
  { nume: "Ogra" },
  { nume: "Onuca", comuna: "Faragau" },
  { nume: "Ormeniș", simplu: "Ormenis", comuna: "Viisoara" },
  { nume: "Oroiu", comuna: "Band" },
  { nume: "Orosia", comuna: "Cuci" },
  { nume: "Orșova-Pădure", simplu: "Orsova-Padure", comuna: "Gurghiu" },
  { nume: "Orșova", simplu: "Orsova", comuna: "Gurghiu" },
  { nume: "Ozd", comuna: "Bichis" },
  { nume: "Păcureni", simplu: "Pacureni", comuna: "Glodeni" },
  { nume: "Pădurea", simplu: "Padurea", comuna: "Saulia" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Gornesti" },
  { nume: "Păingeni", simplu: "Paingeni", comuna: "Glodeni" },
  { nume: "Pănet", simplu: "Panet" },
  { nume: "Papiu Ilarian" },
  { nume: "Pârâu Crucii", simplu: "Parau Crucii", comuna: "Pogaceaua" },
  { nume: "Pârâu Crucii", simplu: "Parau Crucii", comuna: "Riciu" },
  { nume: "Pârâu Mare", simplu: "Parau Mare", comuna: "Ibanesti" },
  { nume: "Păsăreni", simplu: "Pasareni" },
  { nume: "Păucișoara", simplu: "Paucisoara", comuna: "Ganesti" },
  { nume: "Păuloaia", simplu: "Pauloaia", comuna: "Gurghiu" },
  { nume: "Periș", simplu: "Peris", comuna: "Gornesti" },
  { nume: "Petea", comuna: "Band" },
  { nume: "Petelea" },
  {
    nume: "Petrilaca de Mureș",
    simplu: "Petrilaca de Mures",
    comuna: "Gornesti",
  },
  { nume: "Petrilaca", comuna: "Cuci" },
  { nume: "Pietriș", simplu: "Pietris", comuna: "Deda" },
  { nume: "Pipea", comuna: "Nades" },
  { nume: "Poarta", comuna: "Faragau" },
  { nume: "Poduri", comuna: "Valea Larga" },
  { nume: "Pogăceaua", simplu: "Pogaceaua" },
  { nume: "Poienița", simplu: "Poienita", comuna: "Livezeni" },
  { nume: "Porumbac", comuna: "Iernut" },
  { nume: "Porumbeni", comuna: "Ceuasu De Campie" },
  { nume: "Pripoare", comuna: "Sanger" },
  { nume: "Pusta", comuna: "Sincai" },
  { nume: "Racameț", simplu: "Racamet", comuna: "Iernut" },
  { nume: "Râciu", simplu: "Raciu", comuna: "Riciu" },
  { nume: "Ranta", comuna: "Bogata" },
  { nume: "Râpa de Jos", simplu: "Rapa de Jos", comuna: "Vatava" },
  { nume: "Răstolița", simplu: "Rastolita" },
  { nume: "Răzoare", simplu: "Razoare", comuna: "Mihesu De Campie" },
  { nume: "Recea", comuna: "Ungheni" },
  { nume: "Reghin" },
  { nume: "Remetea", comuna: "Targu Mures" },
  { nume: "Rigmani", comuna: "Neaua" },
  { nume: "Rora", comuna: "Sighisoara" },
  { nume: "Roșiori", simplu: "Rosiori", comuna: "Ludus" },
  { nume: "Roteni", comuna: "Acatari" },
  { nume: "Roua", comuna: "Fantanele" },
  { nume: "Rușii-Munți", simplu: "Rusii-Munti" },
  { nume: "Săbed", simplu: "Sabed", comuna: "Ceuasu De Campie" },
  { nume: "Săcădat", simplu: "Sacadat", comuna: "Sovata" },
  {
    nume: "Săcalu de Pădure",
    simplu: "Sacalu de Padure",
    comuna: "Brancovenesti",
  },
  { nume: "Săcăreni", simplu: "Sacareni", comuna: "Ernei" },
  { nume: "Șaeș", simplu: "Saes", comuna: "Apold" },
  { nume: "Sălard", simplu: "Salard", comuna: "Lunca Bradului" },
  { nume: "Sălașuri", simplu: "Salasuri", comuna: "Vetca" },
  { nume: "Sălcud", simplu: "Salcud", comuna: "Iernut" },
  { nume: "Sâmbriaș", simplu: "Sambrias", comuna: "Hodosa" },
  { nume: "Sâncraiu de Mureș", simplu: "Sancraiu de Mures" },
  { nume: "Șandru", simplu: "Sandru", comuna: "Papiu Ilarian" },
  {
    nume: "Sângeorgiu de Câmpie",
    simplu: "Sangeorgiu de Campie",
    comuna: "Sanpetru De Campie",
  },
  { nume: "Sângeorgiu de Mureș", simplu: "Sangeorgiu de Mures" },
  { nume: "Sângeorgiu de Pădure", simplu: "Sangeorgiu de Padure" },
  { nume: "Sânger", simplu: "Sanger" },
  { nume: "Sângeru de Pădure", simplu: "Sangeru de Padure", comuna: "Ernei" },
  { nume: "Sâniacob", simplu: "Saniacob", comuna: "Atintis" },
  { nume: "Sânișor", simplu: "Sanisor", comuna: "Livezeni" },
  { nume: "Sânmărghita", simplu: "Sanmarghita", comuna: "Sanpaul" },
  {
    nume: "Sânmărtinu de Câmpie",
    simplu: "Sanmartinu de Campie",
    comuna: "Riciu",
  },
  {
    nume: "Sânmihai de Pădure",
    simplu: "Sanmihai de Padure",
    comuna: "Beica De Jos",
  },
  { nume: "Sânpaul", simplu: "Sanpaul" },
  { nume: "Sânpetru de Câmpie", simplu: "Sanpetru de Campie" },
  { nume: "Sânsimion", simplu: "Sansimion", comuna: "Neaua" },
  { nume: "Sântana de Mureș", simplu: "Santana de Mures" },
  { nume: "Sântioana de Mureș", simplu: "Santioana de Mures", comuna: "Panet" },
  { nume: "Sântioana", simplu: "Santioana", comuna: "Viisoara" },
  { nume: "Sântu", simplu: "Santu", comuna: "Lunca" },
  { nume: "Sânvăsii", simplu: "Sanvasii", comuna: "Gălești" },
  { nume: "Șapartoc", simplu: "Sapartoc", comuna: "Albesti" },
  { nume: "Sărățeni", simplu: "Sarateni", comuna: "Sovata" },
  {
    nume: "Șardu Nirajului",
    simplu: "Sardu Nirajului",
    comuna: "Miercurea Nirajului",
  },
  { nume: "Sărmășel-Gară", simplu: "Sarmasel-Gara", comuna: "Sarmasu" },
  { nume: "Sărmășel", simplu: "Sarmasel", comuna: "Sarmasu" },
  { nume: "Sarmașu", simplu: "Sarmasu" },
  { nume: "Saschiz" },
  { nume: "Satu Nou", comuna: "Gheorghe Doja" },
  { nume: "Satu Nou", comuna: "Sanpetru De Campie" },
  { nume: "Șăulia", simplu: "Saulia" },
  { nume: "Șăulița", simplu: "Saulita", comuna: "Mihesu De Campie" },
  { nume: "Șăușa", simplu: "Sausa", comuna: "Ungheni" },
  { nume: "Scurta", comuna: "Pogaceaua" },
  { nume: "Sebeș", simplu: "Sebes", comuna: "Rusii-Munti" },
  { nume: "Seleuș", simplu: "Seleus", comuna: "Danes" },
  { nume: "Seleuș", simplu: "Seleus", comuna: "Zagar" },
  { nume: "Senereuș", simplu: "Senereus", comuna: "Balauseri" },
  { nume: "Șerbeni", simplu: "Serbeni", comuna: "Beica De Jos" },
  { nume: "Seuca", comuna: "Gănești" },
  { nume: "Șeulia de Mureș", simplu: "Seulia de Mures", comuna: "Cucerdea" },
  { nume: "Sfântu Gheorghe", simplu: "Sfantu Gheorghe", comuna: "Iernut" },
  { nume: "Sicele", comuna: "Pogaceaua" },
  { nume: "Sighișoara", simplu: "Sighisoara" },
  { nume: "Șilea Nirajului", simplu: "Silea Nirajului", comuna: "Magherani" },
  { nume: "Șincai-Fânațe", simplu: "Sincai-Fanate", comuna: "Sincai" },
  { nume: "Șincai", simplu: "Sincai" },
  { nume: "Șoard", simplu: "Soard", comuna: "Vanatori" },
  { nume: "Socolu de Câmpie", simplu: "Socolu de Campie", comuna: "Cozma" },
  { nume: "Șoimuș", simplu: "Soimus", comuna: "Coroisanmartin" },
  { nume: "Solocma", comuna: "Ghindari" },
  { nume: "Solovăstru", simplu: "Solovastru" },
  { nume: "Șomoștelnic", simplu: "Somostelnic", comuna: "Mica" },
  { nume: "Șoromiclea", simplu: "Soromiclea", comuna: "Sighisoara" },
  { nume: "Sovata" },
  { nume: "Stânceni", simplu: "Stanceni" },
  { nume: "Ștefanca", simplu: "Stefanca", comuna: "Mihesu De Campie" },
  { nume: "Ștefăneaca", simplu: "Stefaneaca", comuna: "Zau De Campie" },
  { nume: "Stejărenii", simplu: "Stejarenii", comuna: "Danes" },
  { nume: "Stejeriș", simplu: "Stejeris", comuna: "Acatari" },
  { nume: "Sub Pădure", simplu: "Sub Padure", comuna: "Ganesti" },
  { nume: "Suplac" },
  { nume: "Suseni" },
  { nume: "Suveica", comuna: "Acatari" },
  { nume: "Tăblășeni", simplu: "Tablaseni", comuna: "Iclanzel" },
  { nume: "Tâmpa", simplu: "Tampa", comuna: "Miercurea Nirajului" },
  { nume: "Târgu Mureș", simplu: "Targu Mures" },
  { nume: "Târnăveni", simplu: "Tarnaveni" },
  { nume: "Tău", simplu: "Tau", comuna: "Zau De Campie" },
  { nume: "Tăureni", simplu: "Taureni" },
  { nume: "Teleac", comuna: "Gornesti" },
  { nume: "Țigmandru", simplu: "Tigmandru", comuna: "Nades" },
  { nume: "Țiptelnic", simplu: "Tiptelnic", comuna: "Band" },
  { nume: "Tireu", comuna: "Ibanesti" },
  { nume: "Tirimia", comuna: "Gheorghe Doja" },
  { nume: "Tirimioara", comuna: "Craciunesti" },
  { nume: "Tisieu", comuna: "Ibanesti" },
  { nume: "Titiana", comuna: "Sarmasu" },
  { nume: "Toaca", comuna: "Hodac" },
  { nume: "Tofalău", simplu: "Tofalau", comuna: "Sangeorgiu De Mures" },
  { nume: "Toldal", comuna: "Voivodeni" },
  { nume: "Tonciu", comuna: "Faragau" },
  { nume: "Țopa", simplu: "Topa", comuna: "Albesti" },
  { nume: "Torba", comuna: "Magherani" },
  { nume: "Trei Sate", comuna: "Ghindari" },
  { nume: "Troița", simplu: "Troita", comuna: "Galesti" },
  { nume: "Tușinu", simplu: "Tusinu", comuna: "Sanpetru De Campie" },
  { nume: "Uila", comuna: "Batos" },
  { nume: "Ulieș", simplu: "Ulies", comuna: "Riciu" },
  { nume: "Ungheni" },
  { nume: "Uricea", comuna: "Hodac" },
  { nume: "Urisiu de Jos", comuna: "Chiheru De Jos" },
  { nume: "Urisiu de Sus", comuna: "Chiheru De Jos" },
  { nume: "Ursoaia", comuna: "Papiu Ilarian" },
  { nume: "Vădaș", simplu: "Vadas", comuna: "Neaua" },
  { nume: "Vadu", comuna: "Vargata" },
  { nume: "Vaidacuța", simplu: "Vaidacuta", comuna: "Suplac" },
  { nume: "Vaideiu", comuna: "Ogra" },
  { nume: "Valea Albeștiului", simplu: "Valea Albestiului", comuna: "Albesti" },
  { nume: "Valea Dăii", simplu: "Valea Daii", comuna: "Albesti" },
  { nume: "Valea Frăției", simplu: "Valea Fratiei", comuna: "Valea Larga" },
  { nume: "Valea Glodului", comuna: "Valea Larga" },
  { nume: "Valea Iclandului", comuna: "Iclanzel" },
  { nume: "Valea Izvoarelor", comuna: "Sanpaul" },
  { nume: "Valea Largă", simplu: "Valea Larga" },
  { nume: "Valea Mare", comuna: "Band" },
  { nume: "Valea Pădurii", simplu: "Valea Padurii", comuna: "Valea Larga" },
  { nume: "Valea Rece", comuna: "Band" },
  {
    nume: "Valea Sânmărtinului",
    simplu: "Valea Sanmartinului",
    comuna: "Riciu",
  },
  {
    nume: "Valea Sânpetrului",
    simplu: "Valea Sanpetrului",
    comuna: "Grebenisu De Campie",
  },
  {
    nume: "Valea Sânpetrului",
    simplu: "Valea Sanpetrului",
    comuna: "Pogaceaua",
  },
  {
    nume: "Valea Șapartocului",
    simplu: "Valea Sapartocului",
    comuna: "Albesti",
  },
  { nume: "Valea Sasului", comuna: "Cozma" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Riciu" },
  { nume: "Valea Șurii", simplu: "Valea Surii", comuna: "Valea Larga" },
  { nume: "Valea Ulieșului", simplu: "Valea Uliesului", comuna: "Riciu" },
  { nume: "Valea Ungurului", comuna: "Cozma" },
  { nume: "Valea Urieșului", simplu: "Valea Uriesului", comuna: "Valea Larga" },
  { nume: "Valea", comuna: "Vargata" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Pogaceaua" },
  {
    nume: "Vălenii de Mureș",
    simplu: "Valenii de Mures",
    comuna: "Brancovenesti",
  },
  { nume: "Vălenii", simplu: "Valenii", comuna: "Acatari" },
  { nume: "Vălișoara", simplu: "Valisoara", comuna: "Sanger" },
  { nume: "Vălureni", simplu: "Valureni", comuna: "Cristesti" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Vărgata", simplu: "Vargata" },
  { nume: "Vătava", simplu: "Vatava" },
  { nume: "Venchi", comuna: "Sighisoara" },
  { nume: "Veța", simplu: "Veta", comuna: "Miercurea Nirajului" },
  { nume: "Vețca", simplu: "Vetca" },
  { nume: "Vidrasău", simplu: "Vidrasau", comuna: "Ungheni" },
  { nume: "Viforoasa", comuna: "Fantanele" },
  { nume: "Viilor", comuna: "Sighisoara" },
  { nume: "Viișoara", simplu: "Viisoara" },
  { nume: "Vișinelu", simplu: "Visinelu", comuna: "Sarmasu" },
  { nume: "Voiniceni", comuna: "Ceuasu De Campie" },
  { nume: "Voivodeni" },
  { nume: "Vulcan", comuna: "Apold" },
  { nume: "Zagăr", simplu: "Zagar" },
  { nume: "Zăpodea", simplu: "Zapodea", comuna: "Sanger" },
  { nume: "Zau de Câmpie", simplu: "Zau de Campie" },
  { nume: "Zimți", simplu: "Zimti", comuna: "Ibanesti" },
];
