export const ms = [
  { nume: "Acatari" },
  { nume: "Adamus" },
  { nume: "Albesti" },
  { nume: "Alunis" },
  { nume: "Apold" },
  { nume: "Atintis" },
  { nume: "Bahnea" },
  { nume: "Band" },
  { nume: "Batos" },
  { nume: "Beica de Jos" },
  { nume: "Bichis" },
  { nume: "Bogata" },
  { nume: "Breaza" },
  { nume: "Brancovenesti" },
  { nume: "Bagaciu" },
  { nume: "Bala" },
  { nume: "Balauseri" },
  { nume: "Ceuasu de Campie" },
  { nume: "Chetani" },
  { nume: "Chibed" },
  { nume: "Chiheru de Jos" },
  { nume: "Coroisanmartin" },
  { nume: "Cozma" },
  { nume: "Cristesti" },
  { nume: "Craciunesti" },
  { nume: "Craiesti" },
  { nume: "Cucerdea" },
  { nume: "Cuci" },
  { nume: "Danes" },
  { nume: "Deda" },
  { nume: "Eremitu" },
  { nume: "Ernei" },
  { nume: "Fantanele" },
  { nume: "Faragau" },
  { nume: "Gheorghe Doja" },
  { nume: "Ghindari" },
  { nume: "Glodeni" },
  { nume: "Gornesti" },
  { nume: "Grebenisu de Campie" },
  { nume: "Gurghiu" },
  { nume: "Galesti" },
  { nume: "Ganesti" },
  { nume: "Hodac" },
  { nume: "Hodosa" },
  { nume: "Ibanesti" },
  { nume: "Iclanzel" },
  { nume: "Ideciu de Jos" },
  { nume: "Iernut" },
  { nume: "Livezeni" },
  { nume: "Ludus" },
  { nume: "Lunca" },
  { nume: "Lunca Bradului" },
  { nume: "Mica" },
  { nume: "Miercurea Nirajului" },
  { nume: "Mihesu de Campie" },
  { nume: "Magherani" },
  { nume: "Nades" },
  { nume: "Neaua" },
  { nume: "Ogra" },
  { nume: "Papiu Ilarian" },
  { nume: "Petelea" },
  { nume: "Pogaceaua" },
  { nume: "Panet" },
  { nume: "Pasareni" },
  { nume: "Reghin" },
  { nume: "Rusii-Munti" },
  { nume: "Rastolita" },
  { nume: "Sarmasu" },
  { nume: "Saschiz" },
  { nume: "Sighisoara" },
  { nume: "Solovastru" },
  { nume: "Sovata" },
  { nume: "Stanceni" },
  { nume: "Suplac" },
  { nume: "Suseni" },
  { nume: "Sancraiu de Mures" },
  { nume: "Sangeorgiu de Mures" },
  { nume: "Sangeorgiu de Padure" },
  { nume: "Sanger" },
  { nume: "Sanpaul" },
  { nume: "Sanpetru de Campie" },
  { nume: "Santana de Mures" },
  { nume: "Targu Mures" },
  { nume: "Tarnaveni" },
  { nume: "Taureni" },
  { nume: "Ungheni" },
  { nume: "Valea Larga" },
  { nume: "Vetca" },
  { nume: "Viisoara" },
  { nume: "Voivodeni" },
  { nume: "Vanatori" },
  { nume: "Vargata" },
  { nume: "Vatava" },
  { nume: "Zagar" },
  { nume: "Zau de Campie" },
  { nume: "Sincai" },
  { nume: "Saulia" },
  { nume: "Corbesti", comuna: "Acatari" },
  { nume: "Gruisor", comuna: "Acatari" },
  { nume: "Gaiesti", comuna: "Acatari" },
  { nume: "Murgesti", comuna: "Acatari" },
  { nume: "Roteni", comuna: "Acatari" },
  { nume: "Stejeris", comuna: "Acatari" },
  { nume: "Suveica", comuna: "Acatari" },
  { nume: "Valenii", comuna: "Acatari" },
  { nume: "Chincius", comuna: "Adamus" },
  { nume: "Cornesti", comuna: "Adamus" },
  { nume: "Craiesti", comuna: "Adamus" },
  { nume: "Dambau", comuna: "Adamus" },
  { nume: "Herepea", comuna: "Adamus" },
  { nume: "Boiu", comuna: "Albesti" },
  { nume: "Barlibasoaia", comuna: "Albesti" },
  { nume: "Jacu", comuna: "Albesti" },
  { nume: "Valea Albestiului", comuna: "Albesti" },
  { nume: "Valea Daii", comuna: "Albesti" },
  { nume: "Valea Sapartocului", comuna: "Albesti" },
  { nume: "Sapartoc", comuna: "Albesti" },
  { nume: "Topa", comuna: "Albesti" },
  { nume: "Fitcau", comuna: "Alunis" },
  { nume: "Lunca Muresului", comuna: "Alunis" },
  { nume: "Daia", comuna: "Apold" },
  { nume: "Vulcan", comuna: "Apold" },
  { nume: "Saes", comuna: "Apold" },
  { nume: "Botez", comuna: "Atintis" },
  { nume: "Cecalaca", comuna: "Atintis" },
  { nume: "Istihaza", comuna: "Atintis" },
  { nume: "Maldaoci", comuna: "Atintis" },
  { nume: "Saniacob", comuna: "Atintis" },
  { nume: "Delenii", comuna: "Bagaciu" },
  { nume: "Bernadea", comuna: "Bahnea" },
  { nume: "Cund", comuna: "Bahnea" },
  { nume: "Daia", comuna: "Bahnea" },
  { nume: "Gogan", comuna: "Bahnea" },
  { nume: "Idiciu", comuna: "Bahnea" },
  { nume: "Lepindea", comuna: "Bahnea" },
  { nume: "Ercea", comuna: "Bala" },
  { nume: "Agristeu", comuna: "Balauseri" },
  { nume: "Chendu", comuna: "Balauseri" },
  { nume: "Dumitreni", comuna: "Balauseri" },
  { nume: "Filitelnic", comuna: "Balauseri" },
  { nume: "Senereus", comuna: "Balauseri" },
  { nume: "Draculea Bandului", comuna: "Band" },
  { nume: "Fanate", comuna: "Band" },
  { nume: "Fanatele Madarasului", comuna: "Band" },
  { nume: "Istan-Tau", comuna: "Band" },
  { nume: "Madaras", comuna: "Band" },
  { nume: "Marasesti", comuna: "Band" },
  { nume: "Negrenii de Campie", comuna: "Band" },
  { nume: "Oroiu", comuna: "Band" },
  { nume: "Petea", comuna: "Band" },
  { nume: "Valea Mare", comuna: "Band" },
  { nume: "Valea Rece", comuna: "Band" },
  { nume: "Tiptelnic", comuna: "Band" },
  { nume: "Dedrad", comuna: "Batos" },
  { nume: "Goreni", comuna: "Batos" },
  { nume: "Uila", comuna: "Batos" },
  { nume: "Beica de Sus", comuna: "Beica De Jos" },
  { nume: "Cacuciu", comuna: "Beica De Jos" },
  { nume: "Nadasa", comuna: "Beica De Jos" },
  { nume: "Sanmihai de Padure", comuna: "Beica De Jos" },
  { nume: "Serbeni", comuna: "Beica De Jos" },
  { nume: "Gambut", comuna: "Bichis" },
  { nume: "Nandra", comuna: "Bichis" },
  { nume: "Ozd", comuna: "Bichis" },
  { nume: "Ranta", comuna: "Bogata" },
  { nume: "Idicel", comuna: "Brancovenesti" },
  { nume: "Idicel-Padure", comuna: "Brancovenesti" },
  { nume: "Sacalu de Padure", comuna: "Brancovenesti" },
  { nume: "Valenii de Mures", comuna: "Brancovenesti" },
  { nume: "Filpisu Mare", comuna: "Breaza" },
  { nume: "Filpisu Mic", comuna: "Breaza" },
  { nume: "Bozed", comuna: "Ceuasu De Campie" },
  { nume: "Culpiu", comuna: "Ceuasu De Campie" },
  { nume: "Campenita", comuna: "Ceuasu De Campie" },
  { nume: "Herghelia", comuna: "Ceuasu De Campie" },
  { nume: "Porumbeni", comuna: "Ceuasu De Campie" },
  { nume: "Sabed", comuna: "Ceuasu De Campie" },
  { nume: "Voiniceni", comuna: "Ceuasu De Campie" },
  { nume: "Coasta Grindului", comuna: "Chetani" },
  { nume: "Cordos", comuna: "Chetani" },
  { nume: "Giurgis", comuna: "Chetani" },
  { nume: "Grindeni", comuna: "Chetani" },
  { nume: "Hadareni", comuna: "Chetani" },
  { nume: "Lint", comuna: "Chetani" },
  { nume: "Chiheru de Sus", comuna: "Chiheru De Jos" },
  { nume: "Urisiu de Jos", comuna: "Chiheru De Jos" },
  { nume: "Urisiu de Sus", comuna: "Chiheru De Jos" },
  { nume: "Coroi", comuna: "Coroisanmartin" },
  { nume: "Odrihei", comuna: "Coroisanmartin" },
  { nume: "Soimus", comuna: "Coroisanmartin" },
  { nume: "Fanatele Socolului", comuna: "Cozma" },
  { nume: "Socolu de Campie", comuna: "Cozma" },
  { nume: "Valea Sasului", comuna: "Cozma" },
  { nume: "Valea Ungurului", comuna: "Cozma" },
  { nume: "Budiu Mic", comuna: "Craciunesti" },
  { nume: "Cinta", comuna: "Craciunesti" },
  { nume: "Cornesti", comuna: "Craciunesti" },
  { nume: "Tirimioara", comuna: "Craciunesti" },
  { nume: "Lefaia", comuna: "Craiesti" },
  { nume: "Milasel", comuna: "Craiesti" },
  { nume: "Nima Milaselului", comuna: "Craiesti" },
  { nume: "Valureni", comuna: "Cristesti" },
  { nume: "Ciba", comuna: "Crăciunești" },
  { nume: "Foi", comuna: "Crăciunești" },
  { nume: "Nicolesti", comuna: "Crăciunești" },
  { nume: "Bord", comuna: "Cucerdea" },
  { nume: "Seulia de Mures", comuna: "Cucerdea" },
  { nume: "Dupa Deal", comuna: "Cuci" },
  { nume: "Dataseni", comuna: "Cuci" },
  { nume: "Orosia", comuna: "Cuci" },
  { nume: "Petrilaca", comuna: "Cuci" },
  { nume: "Cris", comuna: "Danes" },
  { nume: "Seleus", comuna: "Danes" },
  { nume: "Stejarenii", comuna: "Danes" },
  { nume: "Bistra Muresului", comuna: "Deda" },
  { nume: "Filea", comuna: "Deda" },
  { nume: "Pietris", comuna: "Deda" },
  { nume: "Campu Cetatii", comuna: "Eremitu" },
  { nume: "Calugareni", comuna: "Eremitu" },
  { nume: "Damieni", comuna: "Eremitu" },
  { nume: "Matrici", comuna: "Eremitu" },
  { nume: "Caluseri", comuna: "Ernei" },
  { nume: "Dumbravioara", comuna: "Ernei" },
  { nume: "Icland", comuna: "Ernei" },
  { nume: "Sangeru de Padure", comuna: "Ernei" },
  { nume: "Sacareni", comuna: "Ernei" },
  { nume: "Bordosiu", comuna: "Fantanele" },
  { nume: "Cibu", comuna: "Fantanele" },
  { nume: "Calimanesti", comuna: "Fantanele" },
  { nume: "Roua", comuna: "Fantanele" },
  { nume: "Viforoasa", comuna: "Fantanele" },
  { nume: "Fanate", comuna: "Faragau" },
  { nume: "Hodaia", comuna: "Faragau" },
  { nume: "Onuca", comuna: "Faragau" },
  { nume: "Poarta", comuna: "Faragau" },
  { nume: "Tonciu", comuna: "Faragau" },
  { nume: "Adrianu Mare", comuna: "Galesti" },
  { nume: "Adrianu Mic", comuna: "Galesti" },
  { nume: "Bedeni", comuna: "Galesti" },
  { nume: "Maiad", comuna: "Galesti" },
  { nume: "Troita", comuna: "Galesti" },
  { nume: "Paucisoara", comuna: "Ganesti" },
  { nume: "Sub Padure", comuna: "Ganesti" },
  { nume: "Ilieni", comuna: "Gheorghe Doja" },
  { nume: "Leordeni", comuna: "Gheorghe Doja" },
  { nume: "Satu Nou", comuna: "Gheorghe Doja" },
  { nume: "Tirimia", comuna: "Gheorghe Doja" },
  { nume: "Abud", comuna: "Ghindari" },
  { nume: "Ceie", comuna: "Ghindari" },
  { nume: "Solocma", comuna: "Ghindari" },
  { nume: "Trei Sate", comuna: "Ghindari" },
  { nume: "Merisor", comuna: "Glodeni" },
  { nume: "Moisa", comuna: "Glodeni" },
  { nume: "Pacureni", comuna: "Glodeni" },
  { nume: "Paingeni", comuna: "Glodeni" },
  { nume: "Iara de Mures", comuna: "Gornesti" },
  { nume: "Ilioara", comuna: "Gornesti" },
  { nume: "Mura Mare", comuna: "Gornesti" },
  { nume: "Mura Mica", comuna: "Gornesti" },
  { nume: "Peris", comuna: "Gornesti" },
  { nume: "Petrilaca de Mures", comuna: "Gornesti" },
  { nume: "Padureni", comuna: "Gornesti" },
  { nume: "Teleac", comuna: "Gornesti" },
  { nume: "Leorinta", comuna: "Grebenisu De Campie" },
  { nume: "Valea Sanpetrului", comuna: "Grebenisu De Campie" },
  { nume: "Adrian", comuna: "Gurghiu" },
  { nume: "Casva", comuna: "Gurghiu" },
  { nume: "Comori", comuna: "Gurghiu" },
  { nume: "Fundoaia", comuna: "Gurghiu" },
  { nume: "Glajarie", comuna: "Gurghiu" },
  { nume: "Larga", comuna: "Gurghiu" },
  { nume: "Orsova", comuna: "Gurghiu" },
  { nume: "Orsova-Padure", comuna: "Gurghiu" },
  { nume: "Pauloaia", comuna: "Gurghiu" },
  { nume: "Sanvasii", comuna: "Gălești" },
  { nume: "Seuca", comuna: "Gănești" },
  { nume: "Arsita", comuna: "Hodac" },
  { nume: "Bicasu", comuna: "Hodac" },
  { nume: "Dubistea de Padure", comuna: "Hodac" },
  { nume: "Mirigioaia", comuna: "Hodac" },
  { nume: "Toaca", comuna: "Hodac" },
  { nume: "Uricea", comuna: "Hodac" },
  { nume: "Ihod", comuna: "Hodosa" },
  { nume: "Isla", comuna: "Hodosa" },
  { nume: "Sambrias", comuna: "Hodosa" },
  { nume: "Blidireasa", comuna: "Ibanesti" },
  { nume: "Bradetelu", comuna: "Ibanesti" },
  { nume: "Dulcea", comuna: "Ibanesti" },
  { nume: "Ibanesti-Padure", comuna: "Ibanesti" },
  { nume: "Lapusna", comuna: "Ibanesti" },
  { nume: "Parau Mare", comuna: "Ibanesti" },
  { nume: "Tireu", comuna: "Ibanesti" },
  { nume: "Tisieu", comuna: "Ibanesti" },
  { nume: "Zimti", comuna: "Ibanesti" },
  { nume: "Chisalita", comuna: "Iclanzel" },
  { nume: "Capusu de Campie", comuna: "Iclanzel" },
  { nume: "Dupa Deal", comuna: "Iclanzel" },
  { nume: "Fanate", comuna: "Iclanzel" },
  { nume: "Fanatele Capusului", comuna: "Iclanzel" },
  { nume: "Ghidasteu", comuna: "Iclanzel" },
  { nume: "Iclandu Mare", comuna: "Iclanzel" },
  { nume: "Madaraseni", comuna: "Iclanzel" },
  { nume: "Tablaseni", comuna: "Iclanzel" },
  { nume: "Valea Iclandului", comuna: "Iclanzel" },
  { nume: "Deleni", comuna: "Ideciu De Jos" },
  { nume: "Ideciu de Sus", comuna: "Ideciu De Jos" },
  { nume: "Cipau", comuna: "Iernut" },
  { nume: "Deag", comuna: "Iernut" },
  { nume: "Lechinta", comuna: "Iernut" },
  { nume: "Oarba de Mures", comuna: "Iernut" },
  { nume: "Porumbac", comuna: "Iernut" },
  { nume: "Racamet", comuna: "Iernut" },
  { nume: "Sfantu Gheorghe", comuna: "Iernut" },
  { nume: "Salcud", comuna: "Iernut" },
  { nume: "Bozeni", comuna: "Livezeni" },
  { nume: "Corunca", comuna: "Livezeni" },
  { nume: "Ivanesti", comuna: "Livezeni" },
  { nume: "Poienita", comuna: "Livezeni" },
  { nume: "Sanisor", comuna: "Livezeni" },
  { nume: "Avramesti", comuna: "Ludus" },
  { nume: "Cioarga", comuna: "Ludus" },
  { nume: "Ciurgau", comuna: "Ludus" },
  { nume: "Fundatura", comuna: "Ludus" },
  { nume: "Gheja", comuna: "Ludus" },
  { nume: "Rosiori", comuna: "Ludus" },
  { nume: "Baita", comuna: "Lunca" },
  { nume: "Frunzeni", comuna: "Lunca" },
  { nume: "Logig", comuna: "Lunca" },
  { nume: "Santu", comuna: "Lunca" },
  { nume: "Neagra", comuna: "Lunca Bradului" },
  { nume: "Salard", comuna: "Lunca Bradului" },
  { nume: "Bereni", comuna: "Magherani" },
  { nume: "Bara", comuna: "Magherani" },
  { nume: "Candu", comuna: "Magherani" },
  { nume: "Drojdii", comuna: "Magherani" },
  { nume: "Eremieni", comuna: "Magherani" },
  { nume: "Maia", comuna: "Magherani" },
  { nume: "Marculeni", comuna: "Magherani" },
  { nume: "Torba", comuna: "Magherani" },
  { nume: "Silea Nirajului", comuna: "Magherani" },
  { nume: "Abus", comuna: "Mica" },
  { nume: "Ceuas", comuna: "Mica" },
  { nume: "Capalna de Sus", comuna: "Mica" },
  { nume: "Deaj", comuna: "Mica" },
  { nume: "Haranglab", comuna: "Mica" },
  { nume: "Somostelnic", comuna: "Mica" },
  { nume: "Beu", comuna: "Miercurea Nirajului" },
  { nume: "Dumitrestii", comuna: "Miercurea Nirajului" },
  { nume: "Laureni", comuna: "Miercurea Nirajului" },
  { nume: "Mosuni", comuna: "Miercurea Nirajului" },
  { nume: "Tampa", comuna: "Miercurea Nirajului" },
  { nume: "Veta", comuna: "Miercurea Nirajului" },
  { nume: "Sardu Nirajului", comuna: "Miercurea Nirajului" },
  { nume: "Bujor", comuna: "Mihesu De Campie" },
  { nume: "Cirhagau", comuna: "Mihesu De Campie" },
  { nume: "Groapa Radaii", comuna: "Mihesu De Campie" },
  { nume: "Mogoaia", comuna: "Mihesu De Campie" },
  { nume: "Razoare", comuna: "Mihesu De Campie" },
  { nume: "Stefanca", comuna: "Mihesu De Campie" },
  { nume: "Saulita", comuna: "Mihesu De Campie" },
  { nume: "Magherus", comuna: "Nades" },
  { nume: "Pipea", comuna: "Nades" },
  { nume: "Tigmandru", comuna: "Nades" },
  { nume: "Ghinesti", comuna: "Neaua" },
  { nume: "Rigmani", comuna: "Neaua" },
  { nume: "Sansimion", comuna: "Neaua" },
  { nume: "Vadas", comuna: "Neaua" },
  { nume: "Dileu Vechi", comuna: "Ogra" },
  { nume: "Giulus", comuna: "Ogra" },
  { nume: "Lascud", comuna: "Ogra" },
  { nume: "Vaideiu", comuna: "Ogra" },
  { nume: "Berghia", comuna: "Panet" },
  { nume: "Cuiesd", comuna: "Panet" },
  { nume: "Hartau", comuna: "Panet" },
  { nume: "Santioana de Mures", comuna: "Panet" },
  { nume: "Dobra", comuna: "Papiu Ilarian" },
  { nume: "Merisoru", comuna: "Papiu Ilarian" },
  { nume: "Ursoaia", comuna: "Papiu Ilarian" },
  { nume: "Sandru", comuna: "Papiu Ilarian" },
  { nume: "Bolintineni", comuna: "Pasareni" },
  { nume: "Galateni", comuna: "Pasareni" },
  { nume: "Habic", comuna: "Petelea" },
  { nume: "Bologaia", comuna: "Pogaceaua" },
  { nume: "Ciulea", comuna: "Pogaceaua" },
  { nume: "Deleni", comuna: "Pogaceaua" },
  { nume: "Fantana Babii", comuna: "Pogaceaua" },
  { nume: "Parau Crucii", comuna: "Pogaceaua" },
  { nume: "Scurta", comuna: "Pogaceaua" },
  { nume: "Sicele", comuna: "Pogaceaua" },
  { nume: "Valea Sanpetrului", comuna: "Pogaceaua" },
  { nume: "Valeni", comuna: "Pogaceaua" },
  { nume: "Andreneasa", comuna: "Rastolita" },
  { nume: "Borzia", comuna: "Rastolita" },
  { nume: "Galaoaia", comuna: "Rastolita" },
  { nume: "Iod", comuna: "Rastolita" },
  { nume: "Apalina", comuna: "Reghin" },
  { nume: "Iernuteni", comuna: "Reghin" },
  { nume: "Coasta Mare", comuna: "Riciu" },
  { nume: "Cotorinau", comuna: "Riciu" },
  { nume: "Curete", comuna: "Riciu" },
  { nume: "Caciulata", comuna: "Riciu" },
  { nume: "Hagau", comuna: "Riciu" },
  { nume: "Lenis", comuna: "Riciu" },
  { nume: "Nima Raciului", comuna: "Riciu" },
  { nume: "Obarsie", comuna: "Riciu" },
  { nume: "Parau Crucii", comuna: "Riciu" },
  { nume: "Raciu", comuna: "Riciu" },
  { nume: "Sanmartinu de Campie", comuna: "Riciu" },
  { nume: "Ulies", comuna: "Riciu" },
  { nume: "Valea Seaca", comuna: "Riciu" },
  { nume: "Valea Sanmartinului", comuna: "Riciu" },
  { nume: "Valea Uliesului", comuna: "Riciu" },
  { nume: "Maioresti", comuna: "Rusii-Munti" },
  { nume: "Morareni", comuna: "Rusii-Munti" },
  { nume: "Sebes", comuna: "Rusii-Munti" },
  { nume: "Nazna", comuna: "Sancraiu De Mures" },
  { nume: "Cotus", comuna: "Sangeorgiu De Mures" },
  { nume: "Tofalau", comuna: "Sangeorgiu De Mures" },
  { nume: "Bezid", comuna: "Sangeorgiu De Padure" },
  { nume: "Bezidu Nou", comuna: "Sangeorgiu De Padure" },
  { nume: "Lotu", comuna: "Sangeorgiu De Padure" },
  { nume: "Barza", comuna: "Sanger" },
  { nume: "Cipaieni", comuna: "Sanger" },
  { nume: "Dalu", comuna: "Sanger" },
  { nume: "Pripoare", comuna: "Sanger" },
  { nume: "Valisoara", comuna: "Sanger" },
  { nume: "Zapodea", comuna: "Sanger" },
  { nume: "Chirileu", comuna: "Sanpaul" },
  { nume: "Dileu Nou", comuna: "Sanpaul" },
  { nume: "Sanmarghita", comuna: "Sanpaul" },
  { nume: "Valea Izvoarelor", comuna: "Sanpaul" },
  { nume: "Barlibas", comuna: "Sanpetru De Campie" },
  { nume: "Dambu", comuna: "Sanpetru De Campie" },
  { nume: "Satu Nou", comuna: "Sanpetru De Campie" },
  { nume: "Sangeorgiu de Campie", comuna: "Sanpetru De Campie" },
  { nume: "Tusinu", comuna: "Sanpetru De Campie" },
  { nume: "Bardesti", comuna: "Santana De Mures" },
  { nume: "Chinari", comuna: "Santana De Mures" },
  { nume: "Curteni", comuna: "Santana De Mures" },
  { nume: "Balda", comuna: "Sarmasu" },
  { nume: "Larga", comuna: "Sarmasu" },
  { nume: "Morut", comuna: "Sarmasu" },
  { nume: "Sarmasel", comuna: "Sarmasu" },
  { nume: "Sarmasel-Gara", comuna: "Sarmasu" },
  { nume: "Titiana", comuna: "Sarmasu" },
  { nume: "Visinelu", comuna: "Sarmasu" },
  { nume: "Cloasterf", comuna: "Saschiz" },
  { nume: "Mihai Viteazu", comuna: "Saschiz" },
  { nume: "Leorinta-Saulia", comuna: "Saulia" },
  { nume: "Macicasesti", comuna: "Saulia" },
  { nume: "Padurea", comuna: "Saulia" },
  { nume: "Angofa", comuna: "Sighisoara" },
  { nume: "Aurel Vlaicu", comuna: "Sighisoara" },
  { nume: "Hetiur", comuna: "Sighisoara" },
  { nume: "Rora", comuna: "Sighisoara" },
  { nume: "Venchi", comuna: "Sighisoara" },
  { nume: "Viilor", comuna: "Sighisoara" },
  { nume: "Soromiclea", comuna: "Sighisoara" },
  { nume: "Lechincioara", comuna: "Sincai" },
  { nume: "Pusta", comuna: "Sincai" },
  { nume: "Sincai-Fanate", comuna: "Sincai" },
  { nume: "Jabenita", comuna: "Solovastru" },
  { nume: "Capeti", comuna: "Sovata" },
  { nume: "Iliesi", comuna: "Sovata" },
  { nume: "Sacadat", comuna: "Sovata" },
  { nume: "Sarateni", comuna: "Sovata" },
  { nume: "Ciobotani", comuna: "Stanceni" },
  { nume: "Mestera", comuna: "Stanceni" },
  { nume: "Idrifaia", comuna: "Suplac" },
  { nume: "Laslau Mare", comuna: "Suplac" },
  { nume: "Laslau Mic", comuna: "Suplac" },
  { nume: "Vaidacuta", comuna: "Suplac" },
  { nume: "Luieriu", comuna: "Suseni" },
  { nume: "Mureseni", comuna: "Targu Mures" },
  { nume: "Remetea", comuna: "Targu Mures" },
  { nume: "Bobohalma", comuna: "Tarnaveni" },
  { nume: "Botorca", comuna: "Tarnaveni" },
  { nume: "Custelnic", comuna: "Tarnaveni" },
  { nume: "Fanate", comuna: "Taureni" },
  { nume: "Moara de Jos", comuna: "Taureni" },
  { nume: "Cerghid", comuna: "Ungheni" },
  { nume: "Cerghizel", comuna: "Ungheni" },
  { nume: "Moresti", comuna: "Ungheni" },
  { nume: "Recea", comuna: "Ungheni" },
  { nume: "Vidrasau", comuna: "Ungheni" },
  { nume: "Sausa", comuna: "Ungheni" },
  { nume: "Gradini", comuna: "Valea Larga" },
  { nume: "Malaesti", comuna: "Valea Larga" },
  { nume: "Poduri", comuna: "Valea Larga" },
  { nume: "Valea Fratiei", comuna: "Valea Larga" },
  { nume: "Valea Glodului", comuna: "Valea Larga" },
  { nume: "Valea Padurii", comuna: "Valea Larga" },
  { nume: "Valea Uriesului", comuna: "Valea Larga" },
  { nume: "Valea Surii", comuna: "Valea Larga" },
  { nume: "Archita", comuna: "Vanatori" },
  { nume: "Feleag", comuna: "Vanatori" },
  { nume: "Mureni", comuna: "Vanatori" },
  { nume: "Soard", comuna: "Vanatori" },
  { nume: "Grausorul", comuna: "Vargata" },
  { nume: "Mitresti", comuna: "Vargata" },
  { nume: "Vadu", comuna: "Vargata" },
  { nume: "Valea", comuna: "Vargata" },
  { nume: "Dumbrava", comuna: "Vatava" },
  { nume: "Rapa de Jos", comuna: "Vatava" },
  { nume: "Jacodu", comuna: "Vetca" },
  { nume: "Salasuri", comuna: "Vetca" },
  { nume: "Ormenis", comuna: "Viisoara" },
  { nume: "Santioana", comuna: "Viisoara" },
  { nume: "Toldal", comuna: "Voivodeni" },
  { nume: "Seleus", comuna: "Zagar" },
  { nume: "Botei", comuna: "Zau De Campie" },
  { nume: "Bujor-Hodaie", comuna: "Zau De Campie" },
  { nume: "Barbosi", comuna: "Zau De Campie" },
  { nume: "Ciretea", comuna: "Zau De Campie" },
  { nume: "Gaura Sangerului", comuna: "Zau De Campie" },
  { nume: "Malea", comuna: "Zau De Campie" },
  { nume: "Tau", comuna: "Zau De Campie" },
  { nume: "Stefaneaca", comuna: "Zau De Campie" },
];
