export const mh = [
  { nume: "Baia de Arama" },
  { nume: "Bala" },
  { nume: "Balta" },
  { nume: "Breznita-Motru" },
  { nume: "Breznita-Ocol" },
  { nume: "Brosteni" },
  { nume: "Burila Mare" },
  { nume: "Butoiesti" },
  { nume: "Bacles" },
  { nume: "Balvanesti" },
  { nume: "Balacita" },
  { nume: "Ciresu" },
  { nume: "Corcova" },
  { nume: "Corlatel" },
  { nume: "Cujmir" },
  { nume: "Cazanesti" },
  { nume: "Devesel" },
  { nume: "Drobeta-Turnu Severin" },
  { nume: "Dubova" },
  { nume: "Darvari" },
  { nume: "Eselnita" },
  { nume: "Floresti" },
  { nume: "Godeanu" },
  { nume: "Gogosu" },
  { nume: "Greci" },
  { nume: "Grozesti" },
  { nume: "Gruia" },
  { nume: "Garla Mare" },
  { nume: "Hinova" },
  { nume: "Husnicioara" },
  { nume: "Ilovita" },
  { nume: "Ilovat" },
  { nume: "Isverna" },
  { nume: "Izvoru Barzii" },
  { nume: "Jiana" },
  { nume: "Livezile" },
  { nume: "Malovat" },
  { nume: "Obarsia de Camp" },
  { nume: "Obarsia-Closani" },
  { nume: "Oprisor" },
  { nume: "Orsova" },
  { nume: "Podeni" },
  { nume: "Ponoarele" },
  { nume: "Poroina Mare" },
  { nume: "Pristol" },
  { nume: "Prunisor" },
  { nume: "Punghina" },
  { nume: "Patulele" },
  { nume: "Rogova" },
  { nume: "Salcia" },
  { nume: "Strehaia" },
  { nume: "Stangaceaua" },
  { nume: "Svinita" },
  { nume: "Tamna" },
  { nume: "Vladaia" },
  { nume: "Voloiac" },
  { nume: "Vanju Mare" },
  { nume: "Vanjulet" },
  { nume: "Vanatori" },
  { nume: "Simian" },
  { nume: "Sisesti" },
  { nume: "Sovarna" },
  { nume: "Corzu", comuna: "Bacles" },
  { nume: "Giura", comuna: "Bacles" },
  { nume: "Petra", comuna: "Bacles" },
  { nume: "Podu Grosului", comuna: "Bacles" },
  { nume: "Selistiuta", comuna: "Bacles" },
  { nume: "Smadovita", comuna: "Bacles" },
  { nume: "Bratilovu", comuna: "Baia De Arama" },
  { nume: "Brebina", comuna: "Baia De Arama" },
  { nume: "Dealu Mare", comuna: "Baia De Arama" },
  { nume: "Marasesti", comuna: "Baia De Arama" },
  { nume: "Negoesti", comuna: "Baia De Arama" },
  { nume: "Pistrita", comuna: "Baia De Arama" },
  { nume: "Stanesti", comuna: "Baia De Arama" },
  { nume: "Titerlesti", comuna: "Baia De Arama" },
  { nume: "Bala de Sus", comuna: "Bala" },
  { nume: "Bratesul", comuna: "Bala" },
  { nume: "Brativoesti", comuna: "Bala" },
  { nume: "Comanesti", comuna: "Bala" },
  { nume: "Crainici", comuna: "Bala" },
  { nume: "Campu Mare", comuna: "Bala" },
  { nume: "Carsu", comuna: "Bala" },
  { nume: "Dalma", comuna: "Bala" },
  { nume: "Iupca", comuna: "Bala" },
  { nume: "Molani", comuna: "Bala" },
  { nume: "Rudina", comuna: "Bala" },
  { nume: "Runcusoru", comuna: "Bala" },
  { nume: "Sardanesti", comuna: "Bala" },
  { nume: "Vidimiresti", comuna: "Bala" },
  { nume: "Dobra", comuna: "Balacita" },
  { nume: "Gvardinita", comuna: "Balacita" },
  { nume: "Coada Cornetului", comuna: "Balta" },
  { nume: "Costesti", comuna: "Balta" },
  { nume: "Gornovita", comuna: "Balta" },
  { nume: "Nevatu", comuna: "Balta" },
  { nume: "Prejna", comuna: "Balta" },
  { nume: "Sfodea", comuna: "Balta" },
  { nume: "Balvanestii de Jos", comuna: "Balvanesti" },
  { nume: "Calinestii de Jos", comuna: "Balvanesti" },
  { nume: "Calinestii de Sus", comuna: "Balvanesti" },
  { nume: "Parlagele", comuna: "Balvanesti" },
  { nume: "Cosovat", comuna: "Breznita-Motru" },
  { nume: "Deleni", comuna: "Breznita-Motru" },
  { nume: "Fauroaia", comuna: "Breznita-Motru" },
  { nume: "Plai", comuna: "Breznita-Motru" },
  { nume: "Talapanu", comuna: "Breznita-Motru" },
  { nume: "Valea Teiului", comuna: "Breznita-Motru" },
  { nume: "Jidostita", comuna: "Breznita-Ocol" },
  { nume: "Magheru", comuna: "Breznita-Ocol" },
  { nume: "Susita", comuna: "Breznita-Ocol" },
  { nume: "Capatanesti", comuna: "Brosteni" },
  { nume: "Luncsoara", comuna: "Brosteni" },
  { nume: "Lupsa de Jos", comuna: "Brosteni" },
  { nume: "Lupsa de Sus", comuna: "Brosteni" },
  { nume: "Meris", comuna: "Brosteni" },
  { nume: "Crivina", comuna: "Burila Mare" },
  { nume: "Izvoru Frumos", comuna: "Burila Mare" },
  { nume: "Vrancea", comuna: "Burila Mare" },
  { nume: "Tiganasi", comuna: "Burila Mare" },
  { nume: "Arginesti", comuna: "Butoiesti" },
  { nume: "Buicesti", comuna: "Butoiesti" },
  { nume: "Gura Motrului", comuna: "Butoiesti" },
  { nume: "Jugastru", comuna: "Butoiesti" },
  { nume: "Pluta", comuna: "Butoiesti" },
  { nume: "Radutesti", comuna: "Butoiesti" },
  { nume: "Tantaru", comuna: "Butoiesti" },
  { nume: "Ercea", comuna: "Cazanesti" },
  { nume: "Govodarva", comuna: "Cazanesti" },
  { nume: "Garbovatu de Sus", comuna: "Cazanesti" },
  { nume: "Ilovu", comuna: "Cazanesti" },
  { nume: "Jignita", comuna: "Cazanesti" },
  { nume: "Poiana", comuna: "Cazanesti" },
  { nume: "Paltinisu", comuna: "Cazanesti" },
  { nume: "Rosia", comuna: "Cazanesti" },
  { nume: "Severinesti", comuna: "Cazanesti" },
  { nume: "Suharu", comuna: "Cazanesti" },
  { nume: "Valea Cosustei", comuna: "Cazanesti" },
  { nume: "Bunoaica", comuna: "Ciresu" },
  { nume: "Jupanesti", comuna: "Ciresu" },
  { nume: "Negrusa", comuna: "Ciresu" },
  { nume: "Breta", comuna: "Corcova" },
  { nume: "Cernaia", comuna: "Corcova" },
  { nume: "Cordun", comuna: "Corcova" },
  { nume: "Croica", comuna: "Corcova" },
  { nume: "Garbovatu de Jos", comuna: "Corcova" },
  { nume: "Imoasa", comuna: "Corcova" },
  { nume: "Jirov", comuna: "Corcova" },
  { nume: "Maru Rosu", comuna: "Corcova" },
  { nume: "Puscasu", comuna: "Corcova" },
  { nume: "Parvulesti", comuna: "Corcova" },
  { nume: "Stejaru", comuna: "Corcova" },
  { nume: "Vladasesti", comuna: "Corcova" },
  { nume: "Valea Anilor", comuna: "Corlatel" },
  { nume: "Aurora", comuna: "Cujmir" },
  { nume: "Cujmiru Mic", comuna: "Cujmir" },
  { nume: "Gemeni", comuna: "Darvari" },
  { nume: "Batoti", comuna: "Devesel" },
  { nume: "Bistretu", comuna: "Devesel" },
  { nume: "Dunarea Mica", comuna: "Devesel" },
  { nume: "Scapau", comuna: "Devesel" },
  { nume: "Tismana", comuna: "Devesel" },
  { nume: "Dudasu Schelei", comuna: "Drobeta-Turnu Severin" },
  { nume: "Gura Vaii", comuna: "Drobeta-Turnu Severin" },
  { nume: "Schela Cladovei", comuna: "Drobeta-Turnu Severin" },
  { nume: "Baia Noua", comuna: "Dubova" },
  { nume: "Eibenthal", comuna: "Dubova" },
  { nume: "Albulesti", comuna: "Dumbrava" },
  { nume: "Bragleasa", comuna: "Dumbrava" },
  { nume: "Dumbrava de Jos", comuna: "Dumbrava" },
  { nume: "Dumbrava de Mijloc", comuna: "Dumbrava" },
  { nume: "Dumbrava de Sus", comuna: "Dumbrava" },
  { nume: "Golineasa", comuna: "Dumbrava" },
  { nume: "Higiu", comuna: "Dumbrava" },
  { nume: "Rocsoreni", comuna: "Dumbrava" },
  { nume: "Valea Marcului", comuna: "Dumbrava" },
  { nume: "Varodia", comuna: "Dumbrava" },
  { nume: "Vladica", comuna: "Dumbrava" },
  { nume: "Copacioasa", comuna: "Floresti" },
  { nume: "Gardoaia", comuna: "Floresti" },
  { nume: "Livezi", comuna: "Floresti" },
  { nume: "Mosneni", comuna: "Floresti" },
  { nume: "Pesteana", comuna: "Floresti" },
  { nume: "Pestenuta", comuna: "Floresti" },
  { nume: "Stroesti", comuna: "Floresti" },
  { nume: "Zegujani", comuna: "Floresti" },
  { nume: "Vrata", comuna: "Garla Mare" },
  { nume: "Marga", comuna: "Godeanu" },
  { nume: "Paunesti", comuna: "Godeanu" },
  { nume: "Siroca", comuna: "Godeanu" },
  { nume: "Balta Verde", comuna: "Gogosu" },
  { nume: "Burila Mica", comuna: "Gogosu" },
  { nume: "Ostrovu Mare", comuna: "Gogosu" },
  { nume: "Blidaru", comuna: "Greci" },
  { nume: "Baltanele", comuna: "Greci" },
  { nume: "Salatruc", comuna: "Greci" },
  { nume: "Valea Petrii", comuna: "Greci" },
  { nume: "Visina", comuna: "Greci" },
  { nume: "Carceni", comuna: "Grozesti" },
  { nume: "Pasarani", comuna: "Grozesti" },
  { nume: "Susita", comuna: "Grozesti" },
  { nume: "Izvoarele", comuna: "Gruia" },
  { nume: "Poiana Gruii", comuna: "Gruia" },
  { nume: "Bistrita", comuna: "Hinova" },
  { nume: "Carjei", comuna: "Hinova" },
  { nume: "Ostrovu Corbului", comuna: "Hinova" },
  { nume: "Alunisul", comuna: "Husnicioara" },
  { nume: "Borogea", comuna: "Husnicioara" },
  { nume: "Baditesti", comuna: "Husnicioara" },
  { nume: "Celnata", comuna: "Husnicioara" },
  { nume: "Dumbravita", comuna: "Husnicioara" },
  { nume: "Marmanu", comuna: "Husnicioara" },
  { nume: "Opranesti", comuna: "Husnicioara" },
  { nume: "Peri", comuna: "Husnicioara" },
  { nume: "Priboiesti", comuna: "Husnicioara" },
  { nume: "Selisteni", comuna: "Husnicioara" },
  { nume: "Budanesti", comuna: "Ilovat" },
  { nume: "Cracu Lung", comuna: "Ilovat" },
  { nume: "Dalbocita", comuna: "Ilovat" },
  { nume: "Firizu", comuna: "Ilovat" },
  { nume: "Racova", comuna: "Ilovat" },
  { nume: "Bahna", comuna: "Ilovita" },
  { nume: "Moisesti", comuna: "Ilovita" },
  { nume: "Busesti", comuna: "Isverna" },
  { nume: "Cerna-Varf", comuna: "Isverna" },
  { nume: "Draghesti", comuna: "Isverna" },
  { nume: "Giurgiani", comuna: "Isverna" },
  { nume: "Nadanova", comuna: "Isverna" },
  { nume: "Selistea", comuna: "Isverna" },
  { nume: "Turtaba", comuna: "Isverna" },
  { nume: "Balotesti", comuna: "Izvoru Barzii" },
  { nume: "Halanga", comuna: "Izvoru Barzii" },
  { nume: "Putinei", comuna: "Izvoru Barzii" },
  { nume: "Rascolesti", comuna: "Izvoru Barzii" },
  { nume: "Schinteiesti", comuna: "Izvoru Barzii" },
  { nume: "Schitu Topolnitei", comuna: "Izvoru Barzii" },
  { nume: "Cioroboreni", comuna: "Jiana" },
  { nume: "Danceu", comuna: "Jiana" },
  { nume: "Jiana Mare", comuna: "Jiana" },
  { nume: "Jiana Veche", comuna: "Jiana" },
  { nume: "Izvoru Anestilor", comuna: "Livezile" },
  { nume: "Izvoralu de Jos", comuna: "Livezile" },
  { nume: "Petris", comuna: "Livezile" },
  { nume: "Stefan Odobleja", comuna: "Livezile" },
  { nume: "23 August", comuna: "Malovat" },
  { nume: "Bobaita", comuna: "Malovat" },
  { nume: "Barda", comuna: "Malovat" },
  { nume: "Colibasi", comuna: "Malovat" },
  { nume: "Lazu", comuna: "Malovat" },
  { nume: "Negresti", comuna: "Malovat" },
  { nume: "Izimsa", comuna: "Obarsia De Camp" },
  { nume: "Godeanu", comuna: "Obarsia-Closani" },
  { nume: "Prisaceaua", comuna: "Oprisor" },
  { nume: "Biban", comuna: "Padina" },
  { nume: "Iablanita", comuna: "Padina" },
  { nume: "Olteanca", comuna: "Padina" },
  { nume: "Padina Mare", comuna: "Padina" },
  { nume: "Padina Mica", comuna: "Padina" },
  { nume: "Slasoma", comuna: "Padina" },
  { nume: "Viasu", comuna: "Patulele" },
  { nume: "Gornenti", comuna: "Podeni" },
  { nume: "Malarisca", comuna: "Podeni" },
  { nume: "Branzeni", comuna: "Ponoarele" },
  { nume: "Buicani", comuna: "Ponoarele" },
  { nume: "Baraiacu", comuna: "Ponoarele" },
  { nume: "Baluta", comuna: "Ponoarele" },
  { nume: "Ceptureni", comuna: "Ponoarele" },
  { nume: "Cracu Muntelui", comuna: "Ponoarele" },
  { nume: "Delureni", comuna: "Ponoarele" },
  { nume: "Gheorghesti", comuna: "Ponoarele" },
  { nume: "Gardaneasa", comuna: "Ponoarele" },
  { nume: "Ludu", comuna: "Ponoarele" },
  { nume: "Proitesti", comuna: "Ponoarele" },
  { nume: "Raiculesti", comuna: "Ponoarele" },
  { nume: "Valea Ursului", comuna: "Ponoarele" },
  { nume: "Sipotu", comuna: "Ponoarele" },
  { nume: "Fantanile Negre", comuna: "Poroina Mare" },
  { nume: "Stignita", comuna: "Poroina Mare" },
  { nume: "Sipotu", comuna: "Poroina Mare" },
  { nume: "Cozia", comuna: "Pristol" },
  { nume: "Arvatesti", comuna: "Prunisor" },
  { nume: "Balota", comuna: "Prunisor" },
  { nume: "Baltanele", comuna: "Prunisor" },
  { nume: "Cervenita", comuna: "Prunisor" },
  { nume: "Dragotesti", comuna: "Prunisor" },
  { nume: "Fantana Domneasca", comuna: "Prunisor" },
  { nume: "Ghelmegioaia", comuna: "Prunisor" },
  { nume: "Gutu", comuna: "Prunisor" },
  { nume: "Garnita", comuna: "Prunisor" },
  { nume: "Igiroasa", comuna: "Prunisor" },
  { nume: "Lumnic", comuna: "Prunisor" },
  { nume: "Mijarca", comuna: "Prunisor" },
  { nume: "Prunaru", comuna: "Prunisor" },
  { nume: "Zegaia", comuna: "Prunisor" },
  { nume: "Cearangu", comuna: "Punghina" },
  { nume: "Drincea", comuna: "Punghina" },
  { nume: "Magurele", comuna: "Punghina" },
  { nume: "Recea", comuna: "Punghina" },
  { nume: "Satu Nou", comuna: "Punghina" },
  { nume: "Poroinita", comuna: "Rogova" },
  { nume: "Cerneti", comuna: "Simian" },
  { nume: "Dedovita Noua", comuna: "Simian" },
  { nume: "Dedovita Veche", comuna: "Simian" },
  { nume: "Dudasu", comuna: "Simian" },
  { nume: "Erghevita", comuna: "Simian" },
  { nume: "Poroina", comuna: "Simian" },
  { nume: "Valea Copcii", comuna: "Simian" },
  { nume: "Ciovarnasani", comuna: "Sisesti" },
  { nume: "Cocorova", comuna: "Sisesti" },
  { nume: "Craguesti", comuna: "Sisesti" },
  { nume: "Caramidaru", comuna: "Sisesti" },
  { nume: "Noaptesa", comuna: "Sisesti" },
  { nume: "Ohaba", comuna: "Sovarna" },
  { nume: "Studina", comuna: "Sovarna" },
  { nume: "Breznicioara", comuna: "Stangaceaua" },
  { nume: "Barlogeni", comuna: "Stangaceaua" },
  { nume: "Ceranganul", comuna: "Stangaceaua" },
  { nume: "Fata Motrului", comuna: "Stangaceaua" },
  { nume: "Posta Veche", comuna: "Stangaceaua" },
  { nume: "Satu Mare", comuna: "Stangaceaua" },
  { nume: "Tarsa", comuna: "Stangaceaua" },
  { nume: "Ciochiuta", comuna: "Strehaia" },
  { nume: "Comanda", comuna: "Strehaia" },
  { nume: "Hurducesti", comuna: "Strehaia" },
  { nume: "Lunca Banului", comuna: "Strehaia" },
  { nume: "Menti", comuna: "Strehaia" },
  { nume: "Motruleni", comuna: "Strehaia" },
  { nume: "Slatinicu Mare", comuna: "Strehaia" },
  { nume: "Slatinicu Mic", comuna: "Strehaia" },
  { nume: "Stancesti", comuna: "Strehaia" },
  { nume: "Adunatii Teiului", comuna: "Tamna" },
  { nume: "Boceni", comuna: "Tamna" },
  { nume: "Colaret", comuna: "Tamna" },
  { nume: "Cremenea", comuna: "Tamna" },
  { nume: "Fata Cremenii", comuna: "Tamna" },
  { nume: "Izvoralu", comuna: "Tamna" },
  { nume: "Manu", comuna: "Tamna" },
  { nume: "Pavat", comuna: "Tamna" },
  { nume: "Plopi", comuna: "Tamna" },
  { nume: "Valea Ursului", comuna: "Tamna" },
  { nume: "Branistea", comuna: "Vanatori" },
  { nume: "Goanta", comuna: "Vanatori" },
  { nume: "Rosiori", comuna: "Vanatori" },
  { nume: "Bucura", comuna: "Vanju Mare" },
  { nume: "Nicolae Balcescu", comuna: "Vanju Mare" },
  { nume: "Orevita Mare", comuna: "Vanju Mare" },
  { nume: "Traian", comuna: "Vanju Mare" },
  { nume: "Hotarani", comuna: "Vanjulet" },
  { nume: "Almajel", comuna: "Vladaia" },
  { nume: "Scorila", comuna: "Vladaia" },
  { nume: "Stircovita", comuna: "Vladaia" },
  { nume: "Cotoroaia", comuna: "Voloiac" },
  { nume: "Lac", comuna: "Voloiac" },
  { nume: "Ruptura", comuna: "Voloiac" },
  { nume: "Sperlesti", comuna: "Voloiac" },
  { nume: "Valea Buna", comuna: "Voloiac" },
  { nume: "Voloicel", comuna: "Voloiac" },
  { nume: "Titirigi", comuna: "Voloiac" },
];
