export const ms = [
  { nume: "Abud", comuna: "Ghindari" },
  { nume: "Abuş", simplu: "Abus", comuna: "Mica" },
  { nume: "Acăţari", simplu: "Acatari" },
  { nume: "Adămuş", simplu: "Adamus" },
  { nume: "Adrian", comuna: "Gurghiu" },
  { nume: "Adrianu Mare", comuna: "Galesti" },
  { nume: "Adrianu Mic", comuna: "Galesti" },
  { nume: "Agrişteu", simplu: "Agristeu", comuna: "Balauseri" },
  { nume: "Albeşti", simplu: "Albesti" },
  { nume: "Aluniş", simplu: "Alunis" },
  { nume: "Andreneasa", comuna: "Rastolita" },
  { nume: "Angofa", comuna: "Sighisoara" },
  { nume: "Apalina", comuna: "Reghin" },
  { nume: "Apold" },
  { nume: "Archita", comuna: "Vanatori" },
  { nume: "Arşiţa", simplu: "Arsita", comuna: "Hodac" },
  { nume: "Aţintiş", simplu: "Atintis" },
  { nume: "Aurel Vlaicu", comuna: "Sighisoara" },
  { nume: "Avrămeşti", simplu: "Avramesti", comuna: "Ludus" },
  { nume: "Băgaciu", simplu: "Bagaciu" },
  { nume: "Bahnea" },
  { nume: "Băiţa", simplu: "Baita", comuna: "Lunca" },
  { nume: "Băla", simplu: "Bala" },
  { nume: "Bălăuşeri", simplu: "Balauseri" },
  { nume: "Balda", comuna: "Sarmasu" },
  { nume: "Band" },
  { nume: "Bâra", simplu: "Bara", comuna: "Magherani" },
  { nume: "Bărboşi", simplu: "Barbosi", comuna: "Zau De Campie" },
  { nume: "Bărdeşti", simplu: "Bardesti", comuna: "Santana De Mures" },
  { nume: "Bârlibaş", simplu: "Barlibas", comuna: "Sanpetru De Campie" },
  { nume: "Bârlibăşoaia", simplu: "Barlibasoaia", comuna: "Albesti" },
  { nume: "Bârza", simplu: "Barza", comuna: "Sanger" },
  { nume: "Batoş", simplu: "Batos" },
  { nume: "Bedeni", comuna: "Galesti" },
  { nume: "Beica de Jos" },
  { nume: "Beica de Sus", comuna: "Beica De Jos" },
  { nume: "Bereni", comuna: "Magherani" },
  { nume: "Berghia", comuna: "Panet" },
  { nume: "Bernadea", comuna: "Bahnea" },
  { nume: "Beu", comuna: "Miercurea Nirajului" },
  { nume: "Bezid", comuna: "Sangeorgiu De Padure" },
  { nume: "Bezidu Nou", comuna: "Sangeorgiu De Padure" },
  { nume: "Bicaşu", simplu: "Bicasu", comuna: "Hodac" },
  { nume: "Bichiş", simplu: "Bichis" },
  { nume: "Bistra Mureşului", simplu: "Bistra Muresului", comuna: "Deda" },
  { nume: "Blidireasa", comuna: "Ibanesti" },
  { nume: "Bobohalma", comuna: "Tarnaveni" },
  { nume: "Bogata" },
  { nume: "Boiu", comuna: "Albesti" },
  { nume: "Bolintineni", comuna: "Pasareni" },
  { nume: "Bologaia", comuna: "Pogaceaua" },
  { nume: "Bord", comuna: "Cucerdea" },
  { nume: "Bordoşiu", simplu: "Bordosiu", comuna: "Fantanele" },
  { nume: "Borzia", comuna: "Rastolita" },
  { nume: "Botei", comuna: "Zau De Campie" },
  { nume: "Botez", comuna: "Atintis" },
  { nume: "Botorca", comuna: "Tarnaveni" },
  { nume: "Bozed", comuna: "Ceuasu De Campie" },
  { nume: "Bozeni", comuna: "Livezeni" },
  { nume: "Brădeţelu", simplu: "Bradetelu", comuna: "Ibanesti" },
  { nume: "Brâncoveneşti", simplu: "Brancovenesti" },
  { nume: "Breaza" },
  { nume: "Budiu Mic", comuna: "Craciunesti" },
  { nume: "Bujor-Hodaie", comuna: "Zau De Campie" },
  { nume: "Bujor", comuna: "Mihesu De Campie" },
  { nume: "Căciulata", simplu: "Caciulata", comuna: "Riciu" },
  { nume: "Căcuciu", simplu: "Cacuciu", comuna: "Beica De Jos" },
  { nume: "Călimăneşti", simplu: "Calimanesti", comuna: "Fantanele" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Eremitu" },
  { nume: "Căluşeri", simplu: "Caluseri", comuna: "Ernei" },
  { nume: "Câmpeniţa", simplu: "Campenita", comuna: "Ceuasu De Campie" },
  { nume: "Câmpu Cetăţii", simplu: "Campu Cetatii", comuna: "Eremitu" },
  { nume: "Cându", simplu: "Candu", comuna: "Magherani" },
  { nume: "Căpâlna de Sus", simplu: "Capalna de Sus", comuna: "Mica" },
  { nume: "Căpeţi", simplu: "Capeti", comuna: "Sovata" },
  { nume: "Căpuşu de Câmpie", simplu: "Capusu de Campie", comuna: "Iclanzel" },
  { nume: "Caşva", simplu: "Casva", comuna: "Gurghiu" },
  { nume: "Cecălaca", simplu: "Cecalaca", comuna: "Atintis" },
  { nume: "Ceie", comuna: "Ghindari" },
  { nume: "Cerghid", comuna: "Ungheni" },
  { nume: "Cerghizel", comuna: "Ungheni" },
  { nume: "Ceuaş", simplu: "Ceuas", comuna: "Mica" },
  { nume: "Ceuaşu de Câmpie", simplu: "Ceuasu de Campie" },
  { nume: "Chendu", comuna: "Balauseri" },
  { nume: "Cheţani", simplu: "Chetani" },
  { nume: "Chibed" },
  { nume: "Chiheru de Jos" },
  { nume: "Chiheru de Sus", comuna: "Chiheru De Jos" },
  { nume: "Chinari", comuna: "Santana De Mures" },
  { nume: "Chinciuş", simplu: "Chincius", comuna: "Adamus" },
  { nume: "Chirileu", comuna: "Sanpaul" },
  { nume: "Chisăliţa", simplu: "Chisalita", comuna: "Iclanzel" },
  { nume: "Ciba", comuna: "Crăciunești" },
  { nume: "Cibu", comuna: "Fantanele" },
  { nume: "Cinta", comuna: "Craciunesti" },
  { nume: "Cioarga", comuna: "Ludus" },
  { nume: "Ciobotani", comuna: "Stanceni" },
  { nume: "Cipăieni", simplu: "Cipaieni", comuna: "Sanger" },
  { nume: "Cipău", simplu: "Cipau", comuna: "Iernut" },
  { nume: "Ciretea", comuna: "Zau De Campie" },
  { nume: "Cirhagău", simplu: "Cirhagau", comuna: "Mihesu De Campie" },
  { nume: "Ciulea", comuna: "Pogaceaua" },
  { nume: "Ciurgău", simplu: "Ciurgau", comuna: "Ludus" },
  { nume: "Cloaşterf", simplu: "Cloasterf", comuna: "Saschiz" },
  { nume: "Coasta Grindului", comuna: "Chetani" },
  { nume: "Coasta Mare", comuna: "Riciu" },
  { nume: "Comori", comuna: "Gurghiu" },
  { nume: "Corbeşti", simplu: "Corbesti", comuna: "Acatari" },
  { nume: "Cordoş", simplu: "Cordos", comuna: "Chetani" },
  { nume: "Corneşti", simplu: "Cornesti", comuna: "Adamus" },
  { nume: "Corneşti", simplu: "Cornesti", comuna: "Craciunesti" },
  { nume: "Coroi", comuna: "Coroisanmartin" },
  { nume: "Coroisânmărtin", simplu: "Coroisanmartin" },
  { nume: "Corunca", comuna: "Livezeni" },
  { nume: "Cotorinău", simplu: "Cotorinau", comuna: "Riciu" },
  { nume: "Cotuş", simplu: "Cotus", comuna: "Sangeorgiu De Mures" },
  { nume: "Cozma" },
  { nume: "Crăciuneşti", simplu: "Craciunesti" },
  { nume: "Crăieşti", simplu: "Craiesti" },
  { nume: "Crăieşti", simplu: "Craiesti", comuna: "Adamus" },
  { nume: "Criş", simplu: "Cris", comuna: "Danes" },
  { nume: "Cristeşti", simplu: "Cristesti" },
  { nume: "Cucerdea" },
  { nume: "Cuci" },
  { nume: "Cuieşd", simplu: "Cuiesd", comuna: "Panet" },
  { nume: "Culpiu", comuna: "Ceuasu De Campie" },
  { nume: "Cund", comuna: "Bahnea" },
  { nume: "Cureţe", simplu: "Curete", comuna: "Riciu" },
  { nume: "Curteni", comuna: "Santana De Mures" },
  { nume: "Cuştelnic", simplu: "Custelnic", comuna: "Tarnaveni" },
  { nume: "Daia", comuna: "Apold" },
  { nume: "Daia", comuna: "Bahnea" },
  { nume: "Dalu", comuna: "Sanger" },
  { nume: "Dâmbău", simplu: "Dambau", comuna: "Adamus" },
  { nume: "Dâmbu", simplu: "Dambu", comuna: "Sanpetru De Campie" },
  { nume: "Dămieni", simplu: "Damieni", comuna: "Eremitu" },
  { nume: "Daneş", simplu: "Danes" },
  { nume: "Dătăşeni", simplu: "Dataseni", comuna: "Cuci" },
  { nume: "Deag", comuna: "Iernut" },
  { nume: "Deaj", comuna: "Mica" },
  { nume: "Deda" },
  { nume: "Dedrad", comuna: "Batos" },
  { nume: "Deleni", comuna: "Ideciu De Jos" },
  { nume: "Deleni", comuna: "Pogaceaua" },
  { nume: "Delenii", comuna: "Bagaciu" },
  { nume: "Dileu Nou", comuna: "Sanpaul" },
  { nume: "Dileu Vechi", comuna: "Ogra" },
  { nume: "Dobra", comuna: "Papiu Ilarian" },
  { nume: "Drăculea Bandului", simplu: "Draculea Bandului", comuna: "Band" },
  { nume: "Drojdii", comuna: "Magherani" },
  { nume: "Dubiştea de Pădure", simplu: "Dubistea de Padure", comuna: "Hodac" },
  { nume: "Dulcea", comuna: "Ibanesti" },
  { nume: "Dumbrava", comuna: "Vatava" },
  { nume: "Dumbrăvioara", simplu: "Dumbravioara", comuna: "Ernei" },
  { nume: "Dumitreni", comuna: "Balauseri" },
  { nume: "Dumitreştii", simplu: "Dumitrestii", comuna: "Miercurea Nirajului" },
  { nume: "După Deal", simplu: "Dupa Deal", comuna: "Cuci" },
  { nume: "După Deal", simplu: "Dupa Deal", comuna: "Iclanzel" },
  { nume: "Ercea", comuna: "Bala" },
  { nume: "Eremieni", comuna: "Magherani" },
  { nume: "Eremitu" },
  { nume: "Ernei" },
  { nume: "Fânaţe", simplu: "Fanate", comuna: "Band" },
  { nume: "Fânaţe", simplu: "Fanate", comuna: "Faragau" },
  { nume: "Fânaţe", simplu: "Fanate", comuna: "Iclanzel" },
  { nume: "Fânaţe", simplu: "Fanate", comuna: "Taureni" },
  {
    nume: "Fânaţele Căpuşului",
    simplu: "Fanatele Capusului",
    comuna: "Iclanzel",
  },
  {
    nume: "Fânaţele Mădăraşului",
    simplu: "Fanatele Madarasului",
    comuna: "Band",
  },
  { nume: "Fânaţele Socolului", simplu: "Fanatele Socolului", comuna: "Cozma" },
  { nume: "Fântâna Babii", simplu: "Fantana Babii", comuna: "Pogaceaua" },
  { nume: "Fântânele", simplu: "Fantanele" },
  { nume: "Fărăgău", simplu: "Faragau" },
  { nume: "Feleag", comuna: "Vanatori" },
  { nume: "Filea", comuna: "Deda" },
  { nume: "Filitelnic", comuna: "Balauseri" },
  { nume: "Filpişu Mare", simplu: "Filpisu Mare", comuna: "Breaza" },
  { nume: "Filpişu Mic", simplu: "Filpisu Mic", comuna: "Breaza" },
  { nume: "Fiţcău", simplu: "Fitcau", comuna: "Alunis" },
  { nume: "Foi", comuna: "Crăciunești" },
  { nume: "Frunzeni", comuna: "Lunca" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Ludus" },
  { nume: "Fundoaia", comuna: "Gurghiu" },
  { nume: "Găieşti", simplu: "Gaiesti", comuna: "Acatari" },
  { nume: "Gălăoaia", simplu: "Galaoaia", comuna: "Rastolita" },
  { nume: "Gălăţeni", simplu: "Galateni", comuna: "Pasareni" },
  { nume: "Găleşti", simplu: "Galesti" },
  { nume: "Gâmbuţ", simplu: "Gambut", comuna: "Bichis" },
  { nume: "Găneşti", simplu: "Ganesti" },
  {
    nume: "Gaura Sângerului",
    simplu: "Gaura Sangerului",
    comuna: "Zau De Campie",
  },
  { nume: "Gheja", comuna: "Ludus" },
  { nume: "Gheorghe Doja" },
  { nume: "Ghidaşteu", simplu: "Ghidasteu", comuna: "Iclanzel" },
  { nume: "Ghindari" },
  { nume: "Ghineşti", simplu: "Ghinesti", comuna: "Neaua" },
  { nume: "Giuluş", simplu: "Giulus", comuna: "Ogra" },
  { nume: "Giurgiş", simplu: "Giurgis", comuna: "Chetani" },
  { nume: "Glăjărie", simplu: "Glajarie", comuna: "Gurghiu" },
  { nume: "Glodeni" },
  { nume: "Gogan", comuna: "Bahnea" },
  { nume: "Goreni", comuna: "Batos" },
  { nume: "Gorneşti", simplu: "Gornesti" },
  { nume: "Grădini", simplu: "Gradini", comuna: "Valea Larga" },
  { nume: "Grâuşorul", simplu: "Grausorul", comuna: "Vargata" },
  { nume: "Grebenişu de Câmpie", simplu: "Grebenisu de Campie" },
  { nume: "Grindeni", comuna: "Chetani" },
  {
    nume: "Groapa Rădăii",
    simplu: "Groapa Radaii",
    comuna: "Mihesu De Campie",
  },
  { nume: "Gruişor", simplu: "Gruisor", comuna: "Acatari" },
  { nume: "Gurghiu" },
  { nume: "Habic", comuna: "Petelea" },
  { nume: "Hădăreni", simplu: "Hadareni", comuna: "Chetani" },
  { nume: "Hagău", simplu: "Hagau", comuna: "Riciu" },
  { nume: "Hărănglab", simplu: "Haranglab", comuna: "Mica" },
  { nume: "Hărţău", simplu: "Hartau", comuna: "Panet" },
  { nume: "Herepea", comuna: "Adamus" },
  { nume: "Herghelia", comuna: "Ceuasu De Campie" },
  { nume: "Hetiur", comuna: "Sighisoara" },
  { nume: "Hodac" },
  { nume: "Hodaia", comuna: "Faragau" },
  { nume: "Hodoşa", simplu: "Hodosa" },
  { nume: "Iara de Mureş", simplu: "Iara de Mures", comuna: "Gornesti" },
  { nume: "Ibăneşti-Pădure", simplu: "Ibanesti-Padure", comuna: "Ibanesti" },
  { nume: "Ibăneşti", simplu: "Ibanesti" },
  { nume: "Icland", comuna: "Ernei" },
  { nume: "Iclandu Mare", comuna: "Iclanzel" },
  { nume: "Iclănzel", simplu: "Iclanzel" },
  { nume: "Ideciu de Jos" },
  { nume: "Ideciu de Sus", comuna: "Ideciu De Jos" },
  { nume: "Idicel-Pădure", simplu: "Idicel-Padure", comuna: "Brancovenesti" },
  { nume: "Idicel", comuna: "Brancovenesti" },
  { nume: "Idiciu", comuna: "Bahnea" },
  { nume: "Idrifaia", comuna: "Suplac" },
  { nume: "Iernut" },
  { nume: "Iernuţeni", simplu: "Iernuteni", comuna: "Reghin" },
  { nume: "Ihod", comuna: "Hodosa" },
  { nume: "Ilieni", comuna: "Gheorghe Doja" },
  { nume: "Ilieşi", simplu: "Iliesi", comuna: "Sovata" },
  { nume: "Ilioara", comuna: "Gornesti" },
  { nume: "Iod", comuna: "Rastolita" },
  { nume: "Isla", comuna: "Hodosa" },
  { nume: "Iştan-Tău", simplu: "Istan-Tau", comuna: "Band" },
  { nume: "Iştihaza", simplu: "Istihaza", comuna: "Atintis" },
  { nume: "Ivăneşti", simplu: "Ivanesti", comuna: "Livezeni" },
  { nume: "Jabeniţa", simplu: "Jabenita", comuna: "Solovastru" },
  { nume: "Jacodu", comuna: "Vetca" },
  { nume: "Jacu", comuna: "Albesti" },
  { nume: "Lăpuşna", simplu: "Lapusna", comuna: "Ibanesti" },
  { nume: "Larga", comuna: "Gurghiu" },
  { nume: "Larga", comuna: "Sarmasu" },
  { nume: "Lăscud", simplu: "Lascud", comuna: "Ogra" },
  { nume: "Laslău Mare", simplu: "Laslau Mare", comuna: "Suplac" },
  { nume: "Laslău Mic", simplu: "Laslau Mic", comuna: "Suplac" },
  { nume: "Lăureni", simplu: "Laureni", comuna: "Miercurea Nirajului" },
  { nume: "Lechincioara", comuna: "Sincai" },
  { nume: "Lechinţa", simplu: "Lechinta", comuna: "Iernut" },
  { nume: "Lefaia", comuna: "Craiesti" },
  { nume: "Leniş", simplu: "Lenis", comuna: "Riciu" },
  { nume: "Leordeni", comuna: "Gheorghe Doja" },
  { nume: "Leorinţa-Şăulia", simplu: "Leorinta-Saulia", comuna: "Saulia" },
  { nume: "Leorinţa", simplu: "Leorinta", comuna: "Grebenisu De Campie" },
  { nume: "Lepindea", comuna: "Bahnea" },
  { nume: "Linţ", simplu: "Lint", comuna: "Chetani" },
  { nume: "Livezeni" },
  { nume: "Logig", comuna: "Lunca" },
  { nume: "Loţu", simplu: "Lotu", comuna: "Sangeorgiu De Padure" },
  { nume: "Luduş", simplu: "Ludus" },
  { nume: "Luieriu", comuna: "Suseni" },
  { nume: "Lunca Bradului" },
  { nume: "Lunca Mureşului", simplu: "Lunca Muresului", comuna: "Alunis" },
  { nume: "Lunca" },
  { nume: "Măcicăşeşti", simplu: "Macicasesti", comuna: "Saulia" },
  { nume: "Mădăraş", simplu: "Madaras", comuna: "Band" },
  { nume: "Mădărăşeni", simplu: "Madaraseni", comuna: "Iclanzel" },
  { nume: "Măgherani", simplu: "Magherani" },
  { nume: "Măgheruş", simplu: "Magherus", comuna: "Nades" },
  { nume: "Maia", comuna: "Magherani" },
  { nume: "Maiad", comuna: "Galesti" },
  { nume: "Maioreşti", simplu: "Maioresti", comuna: "Rusii-Munti" },
  { nume: "Mălăeşti", simplu: "Malaesti", comuna: "Valea Larga" },
  { nume: "Maldaoci", comuna: "Atintis" },
  { nume: "Malea", comuna: "Zau De Campie" },
  { nume: "Mărăşeşti", simplu: "Marasesti", comuna: "Band" },
  { nume: "Mărculeni", simplu: "Marculeni", comuna: "Magherani" },
  { nume: "Mătrici", simplu: "Matrici", comuna: "Eremitu" },
  { nume: "Merişor", simplu: "Merisor", comuna: "Glodeni" },
  { nume: "Merişoru", simplu: "Merisoru", comuna: "Papiu Ilarian" },
  { nume: "Meştera", simplu: "Mestera", comuna: "Stanceni" },
  { nume: "Mica" },
  { nume: "Miercurea Nirajului" },
  { nume: "Mihai Viteazu", comuna: "Saschiz" },
  { nume: "Miheşu de Câmpie", simplu: "Mihesu de Campie" },
  { nume: "Milăşel", simplu: "Milasel", comuna: "Craiesti" },
  { nume: "Mirigioaia", comuna: "Hodac" },
  { nume: "Mitreşti", simplu: "Mitresti", comuna: "Vargata" },
  { nume: "Moara de Jos", comuna: "Taureni" },
  { nume: "Mogoaia", comuna: "Mihesu De Campie" },
  { nume: "Moişa", simplu: "Moisa", comuna: "Glodeni" },
  { nume: "Morăreni", simplu: "Morareni", comuna: "Rusii-Munti" },
  { nume: "Moreşti", simplu: "Moresti", comuna: "Ungheni" },
  { nume: "Moruţ", simplu: "Morut", comuna: "Sarmasu" },
  { nume: "Moşuni", simplu: "Mosuni", comuna: "Miercurea Nirajului" },
  { nume: "Mura Mare", comuna: "Gornesti" },
  { nume: "Mura Mică", simplu: "Mura Mica", comuna: "Gornesti" },
  { nume: "Mureni", comuna: "Vanatori" },
  { nume: "Mureşeni", simplu: "Mureseni", comuna: "Targu Mures" },
  { nume: "Murgeşti", simplu: "Murgesti", comuna: "Acatari" },
  { nume: "Nadăşa", simplu: "Nadasa", comuna: "Beica De Jos" },
  { nume: "Nadeş", simplu: "Nades" },
  { nume: "Nandra", comuna: "Bichis" },
  { nume: "Nazna", comuna: "Sancraiu De Mures" },
  { nume: "Neagra", comuna: "Lunca Bradului" },
  { nume: "Neaua" },
  { nume: "Negrenii de Câmpie", simplu: "Negrenii de Campie", comuna: "Band" },
  { nume: "Nicoleşti", simplu: "Nicolesti", comuna: "Crăciunești" },
  { nume: "Nima Milăşelului", simplu: "Nima Milaselului", comuna: "Craiesti" },
  { nume: "Nima Râciului", simplu: "Nima Raciului", comuna: "Riciu" },
  { nume: "Oarba de Mureş", simplu: "Oarba de Mures", comuna: "Iernut" },
  { nume: "Obârşie", simplu: "Obarsie", comuna: "Riciu" },
  { nume: "Odrihei", comuna: "Coroisanmartin" },
  { nume: "Ogra" },
  { nume: "Onuca", comuna: "Faragau" },
  { nume: "Ormeniş", simplu: "Ormenis", comuna: "Viisoara" },
  { nume: "Oroiu", comuna: "Band" },
  { nume: "Orosia", comuna: "Cuci" },
  { nume: "Orşova-Pădure", simplu: "Orsova-Padure", comuna: "Gurghiu" },
  { nume: "Orşova", simplu: "Orsova", comuna: "Gurghiu" },
  { nume: "Ozd", comuna: "Bichis" },
  { nume: "Păcureni", simplu: "Pacureni", comuna: "Glodeni" },
  { nume: "Pădurea", simplu: "Padurea", comuna: "Saulia" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Gornesti" },
  { nume: "Păingeni", simplu: "Paingeni", comuna: "Glodeni" },
  { nume: "Pănet", simplu: "Panet" },
  { nume: "Papiu Ilarian" },
  { nume: "Pârâu Crucii", simplu: "Parau Crucii", comuna: "Pogaceaua" },
  { nume: "Pârâu Crucii", simplu: "Parau Crucii", comuna: "Riciu" },
  { nume: "Pârâu Mare", simplu: "Parau Mare", comuna: "Ibanesti" },
  { nume: "Păsăreni", simplu: "Pasareni" },
  { nume: "Păucişoara", simplu: "Paucisoara", comuna: "Ganesti" },
  { nume: "Păuloaia", simplu: "Pauloaia", comuna: "Gurghiu" },
  { nume: "Periş", simplu: "Peris", comuna: "Gornesti" },
  { nume: "Petea", comuna: "Band" },
  { nume: "Petelea" },
  {
    nume: "Petrilaca de Mureş",
    simplu: "Petrilaca de Mures",
    comuna: "Gornesti",
  },
  { nume: "Petrilaca", comuna: "Cuci" },
  { nume: "Pietriş", simplu: "Pietris", comuna: "Deda" },
  { nume: "Pipea", comuna: "Nades" },
  { nume: "Poarta", comuna: "Faragau" },
  { nume: "Poduri", comuna: "Valea Larga" },
  { nume: "Pogăceaua", simplu: "Pogaceaua" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Livezeni" },
  { nume: "Porumbac", comuna: "Iernut" },
  { nume: "Porumbeni", comuna: "Ceuasu De Campie" },
  { nume: "Pripoare", comuna: "Sanger" },
  { nume: "Pusta", comuna: "Sincai" },
  { nume: "Racameţ", simplu: "Racamet", comuna: "Iernut" },
  { nume: "Râciu", simplu: "Raciu", comuna: "Riciu" },
  { nume: "Ranta", comuna: "Bogata" },
  { nume: "Râpa de Jos", simplu: "Rapa de Jos", comuna: "Vatava" },
  { nume: "Răstoliţa", simplu: "Rastolita" },
  { nume: "Răzoare", simplu: "Razoare", comuna: "Mihesu De Campie" },
  { nume: "Recea", comuna: "Ungheni" },
  { nume: "Reghin" },
  { nume: "Remetea", comuna: "Targu Mures" },
  { nume: "Rigmani", comuna: "Neaua" },
  { nume: "Rora", comuna: "Sighisoara" },
  { nume: "Roşiori", simplu: "Rosiori", comuna: "Ludus" },
  { nume: "Roteni", comuna: "Acatari" },
  { nume: "Roua", comuna: "Fantanele" },
  { nume: "Ruşii-Munţi", simplu: "Rusii-Munti" },
  { nume: "Săbed", simplu: "Sabed", comuna: "Ceuasu De Campie" },
  { nume: "Săcădat", simplu: "Sacadat", comuna: "Sovata" },
  {
    nume: "Săcalu de Pădure",
    simplu: "Sacalu de Padure",
    comuna: "Brancovenesti",
  },
  { nume: "Săcăreni", simplu: "Sacareni", comuna: "Ernei" },
  { nume: "Şaeş", simplu: "Saes", comuna: "Apold" },
  { nume: "Sălard", simplu: "Salard", comuna: "Lunca Bradului" },
  { nume: "Sălaşuri", simplu: "Salasuri", comuna: "Vetca" },
  { nume: "Sălcud", simplu: "Salcud", comuna: "Iernut" },
  { nume: "Sâmbriaş", simplu: "Sambrias", comuna: "Hodosa" },
  { nume: "Sâncraiu de Mureş", simplu: "Sancraiu de Mures" },
  { nume: "Şandru", simplu: "Sandru", comuna: "Papiu Ilarian" },
  {
    nume: "Sângeorgiu de Câmpie",
    simplu: "Sangeorgiu de Campie",
    comuna: "Sanpetru De Campie",
  },
  { nume: "Sângeorgiu de Mureş", simplu: "Sangeorgiu de Mures" },
  { nume: "Sângeorgiu de Pădure", simplu: "Sangeorgiu de Padure" },
  { nume: "Sânger", simplu: "Sanger" },
  { nume: "Sângeru de Pădure", simplu: "Sangeru de Padure", comuna: "Ernei" },
  { nume: "Sâniacob", simplu: "Saniacob", comuna: "Atintis" },
  { nume: "Sânişor", simplu: "Sanisor", comuna: "Livezeni" },
  { nume: "Sânmărghita", simplu: "Sanmarghita", comuna: "Sanpaul" },
  {
    nume: "Sânmărtinu de Câmpie",
    simplu: "Sanmartinu de Campie",
    comuna: "Riciu",
  },
  {
    nume: "Sânmihai de Pădure",
    simplu: "Sanmihai de Padure",
    comuna: "Beica De Jos",
  },
  { nume: "Sânpaul", simplu: "Sanpaul" },
  { nume: "Sânpetru de Câmpie", simplu: "Sanpetru de Campie" },
  { nume: "Sânsimion", simplu: "Sansimion", comuna: "Neaua" },
  { nume: "Sântana de Mureş", simplu: "Santana de Mures" },
  { nume: "Sântioana de Mureş", simplu: "Santioana de Mures", comuna: "Panet" },
  { nume: "Sântioana", simplu: "Santioana", comuna: "Viisoara" },
  { nume: "Sântu", simplu: "Santu", comuna: "Lunca" },
  { nume: "Sânvăsii", simplu: "Sanvasii", comuna: "Gălești" },
  { nume: "Şapartoc", simplu: "Sapartoc", comuna: "Albesti" },
  { nume: "Sărăţeni", simplu: "Sarateni", comuna: "Sovata" },
  {
    nume: "Şardu Nirajului",
    simplu: "Sardu Nirajului",
    comuna: "Miercurea Nirajului",
  },
  { nume: "Sărmăşel-Gară", simplu: "Sarmasel-Gara", comuna: "Sarmasu" },
  { nume: "Sărmăşel", simplu: "Sarmasel", comuna: "Sarmasu" },
  { nume: "Sarmaşu", simplu: "Sarmasu" },
  { nume: "Saschiz" },
  { nume: "Satu Nou", comuna: "Gheorghe Doja" },
  { nume: "Satu Nou", comuna: "Sanpetru De Campie" },
  { nume: "Şăulia", simplu: "Saulia" },
  { nume: "Şăuliţa", simplu: "Saulita", comuna: "Mihesu De Campie" },
  { nume: "Şăuşa", simplu: "Sausa", comuna: "Ungheni" },
  { nume: "Scurta", comuna: "Pogaceaua" },
  { nume: "Sebeş", simplu: "Sebes", comuna: "Rusii-Munti" },
  { nume: "Seleuş", simplu: "Seleus", comuna: "Danes" },
  { nume: "Seleuş", simplu: "Seleus", comuna: "Zagar" },
  { nume: "Senereuş", simplu: "Senereus", comuna: "Balauseri" },
  { nume: "Şerbeni", simplu: "Serbeni", comuna: "Beica De Jos" },
  { nume: "Seuca", comuna: "Gănești" },
  { nume: "Şeulia de Mureş", simplu: "Seulia de Mures", comuna: "Cucerdea" },
  { nume: "Sfântu Gheorghe", simplu: "Sfantu Gheorghe", comuna: "Iernut" },
  { nume: "Sicele", comuna: "Pogaceaua" },
  { nume: "Sighişoara", simplu: "Sighisoara" },
  { nume: "Şilea Nirajului", simplu: "Silea Nirajului", comuna: "Magherani" },
  { nume: "Şincai-Fânaţe", simplu: "Sincai-Fanate", comuna: "Sincai" },
  { nume: "Şincai", simplu: "Sincai" },
  { nume: "Şoard", simplu: "Soard", comuna: "Vanatori" },
  { nume: "Socolu de Câmpie", simplu: "Socolu de Campie", comuna: "Cozma" },
  { nume: "Şoimuş", simplu: "Soimus", comuna: "Coroisanmartin" },
  { nume: "Solocma", comuna: "Ghindari" },
  { nume: "Solovăstru", simplu: "Solovastru" },
  { nume: "Şomoştelnic", simplu: "Somostelnic", comuna: "Mica" },
  { nume: "Şoromiclea", simplu: "Soromiclea", comuna: "Sighisoara" },
  { nume: "Sovata" },
  { nume: "Stânceni", simplu: "Stanceni" },
  { nume: "Ştefanca", simplu: "Stefanca", comuna: "Mihesu De Campie" },
  { nume: "Ştefăneaca", simplu: "Stefaneaca", comuna: "Zau De Campie" },
  { nume: "Stejărenii", simplu: "Stejarenii", comuna: "Danes" },
  { nume: "Stejeriş", simplu: "Stejeris", comuna: "Acatari" },
  { nume: "Sub Pădure", simplu: "Sub Padure", comuna: "Ganesti" },
  { nume: "Suplac" },
  { nume: "Suseni" },
  { nume: "Suveica", comuna: "Acatari" },
  { nume: "Tăblăşeni", simplu: "Tablaseni", comuna: "Iclanzel" },
  { nume: "Tâmpa", simplu: "Tampa", comuna: "Miercurea Nirajului" },
  { nume: "Târgu Mureş", simplu: "Targu Mures" },
  { nume: "Târnăveni", simplu: "Tarnaveni" },
  { nume: "Tău", simplu: "Tau", comuna: "Zau De Campie" },
  { nume: "Tăureni", simplu: "Taureni" },
  { nume: "Teleac", comuna: "Gornesti" },
  { nume: "Ţigmandru", simplu: "Tigmandru", comuna: "Nades" },
  { nume: "Ţiptelnic", simplu: "Tiptelnic", comuna: "Band" },
  { nume: "Tireu", comuna: "Ibanesti" },
  { nume: "Tirimia", comuna: "Gheorghe Doja" },
  { nume: "Tirimioara", comuna: "Craciunesti" },
  { nume: "Tisieu", comuna: "Ibanesti" },
  { nume: "Titiana", comuna: "Sarmasu" },
  { nume: "Toaca", comuna: "Hodac" },
  { nume: "Tofalău", simplu: "Tofalau", comuna: "Sangeorgiu De Mures" },
  { nume: "Toldal", comuna: "Voivodeni" },
  { nume: "Tonciu", comuna: "Faragau" },
  { nume: "Ţopa", simplu: "Topa", comuna: "Albesti" },
  { nume: "Torba", comuna: "Magherani" },
  { nume: "Trei Sate", comuna: "Ghindari" },
  { nume: "Troiţa", simplu: "Troita", comuna: "Galesti" },
  { nume: "Tuşinu", simplu: "Tusinu", comuna: "Sanpetru De Campie" },
  { nume: "Uila", comuna: "Batos" },
  { nume: "Ulieş", simplu: "Ulies", comuna: "Riciu" },
  { nume: "Ungheni" },
  { nume: "Uricea", comuna: "Hodac" },
  { nume: "Urisiu de Jos", comuna: "Chiheru De Jos" },
  { nume: "Urisiu de Sus", comuna: "Chiheru De Jos" },
  { nume: "Ursoaia", comuna: "Papiu Ilarian" },
  { nume: "Vădaş", simplu: "Vadas", comuna: "Neaua" },
  { nume: "Vadu", comuna: "Vargata" },
  { nume: "Vaidacuţa", simplu: "Vaidacuta", comuna: "Suplac" },
  { nume: "Vaideiu", comuna: "Ogra" },
  { nume: "Valea Albeştiului", simplu: "Valea Albestiului", comuna: "Albesti" },
  { nume: "Valea Dăii", simplu: "Valea Daii", comuna: "Albesti" },
  { nume: "Valea Frăţiei", simplu: "Valea Fratiei", comuna: "Valea Larga" },
  { nume: "Valea Glodului", comuna: "Valea Larga" },
  { nume: "Valea Iclandului", comuna: "Iclanzel" },
  { nume: "Valea Izvoarelor", comuna: "Sanpaul" },
  { nume: "Valea Largă", simplu: "Valea Larga" },
  { nume: "Valea Mare", comuna: "Band" },
  { nume: "Valea Pădurii", simplu: "Valea Padurii", comuna: "Valea Larga" },
  { nume: "Valea Rece", comuna: "Band" },
  {
    nume: "Valea Sânmărtinului",
    simplu: "Valea Sanmartinului",
    comuna: "Riciu",
  },
  {
    nume: "Valea Sânpetrului",
    simplu: "Valea Sanpetrului",
    comuna: "Grebenisu De Campie",
  },
  {
    nume: "Valea Sânpetrului",
    simplu: "Valea Sanpetrului",
    comuna: "Pogaceaua",
  },
  {
    nume: "Valea Şapartocului",
    simplu: "Valea Sapartocului",
    comuna: "Albesti",
  },
  { nume: "Valea Sasului", comuna: "Cozma" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Riciu" },
  { nume: "Valea Şurii", simplu: "Valea Surii", comuna: "Valea Larga" },
  { nume: "Valea Ulieşului", simplu: "Valea Uliesului", comuna: "Riciu" },
  { nume: "Valea Ungurului", comuna: "Cozma" },
  { nume: "Valea Urieşului", simplu: "Valea Uriesului", comuna: "Valea Larga" },
  { nume: "Valea", comuna: "Vargata" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Pogaceaua" },
  {
    nume: "Vălenii de Mureş",
    simplu: "Valenii de Mures",
    comuna: "Brancovenesti",
  },
  { nume: "Vălenii", simplu: "Valenii", comuna: "Acatari" },
  { nume: "Vălişoara", simplu: "Valisoara", comuna: "Sanger" },
  { nume: "Vălureni", simplu: "Valureni", comuna: "Cristesti" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Vărgata", simplu: "Vargata" },
  { nume: "Vătava", simplu: "Vatava" },
  { nume: "Venchi", comuna: "Sighisoara" },
  { nume: "Veţa", simplu: "Veta", comuna: "Miercurea Nirajului" },
  { nume: "Veţca", simplu: "Vetca" },
  { nume: "Vidrasău", simplu: "Vidrasau", comuna: "Ungheni" },
  { nume: "Viforoasa", comuna: "Fantanele" },
  { nume: "Viilor", comuna: "Sighisoara" },
  { nume: "Viişoara", simplu: "Viisoara" },
  { nume: "Vişinelu", simplu: "Visinelu", comuna: "Sarmasu" },
  { nume: "Voiniceni", comuna: "Ceuasu De Campie" },
  { nume: "Voivodeni" },
  { nume: "Vulcan", comuna: "Apold" },
  { nume: "Zagăr", simplu: "Zagar" },
  { nume: "Zăpodea", simplu: "Zapodea", comuna: "Sanger" },
  { nume: "Zau de Câmpie", simplu: "Zau de Campie" },
  { nume: "Zimţi", simplu: "Zimti", comuna: "Ibanesti" },
];
