export const mm = [
  { nume: "Ardusat" },
  { nume: "Arduzel", comuna: "Ulmeni" },
  { nume: "Arieşu de Câmp", simplu: "Ariesu de Camp", comuna: "Ardusat" },
  { nume: "Arieşu de Pădure", simplu: "Ariesu de Padure", comuna: "Satulung" },
  { nume: "Ariniş", simplu: "Arinis" },
  { nume: "Aspra", comuna: "Vima Mica" },
  { nume: "Asuaju de Jos", comuna: "Asuaju De Sus" },
  { nume: "Asuaju de Sus" },
  { nume: "Baba", comuna: "Coroieni" },
  { nume: "Baia Mare" },
  { nume: "Baia Sprie" },
  { nume: "Băile Borşa", simplu: "Baile Borsa", comuna: "Borsa" },
  { nume: "Băiţa de Sub Codru", simplu: "Baita de Sub Codru" },
  { nume: "Băiţa", simplu: "Baita", comuna: "Tautii-Magheraus" },
  { nume: "Băiuţ", simplu: "Baiut" },
  { nume: "Bârgău", simplu: "Bargau", comuna: "Cicarlau" },
  { nume: "Bârsana", simplu: "Barsana" },
  { nume: "Băseşti", simplu: "Basesti" },
  { nume: "Berbeşti", simplu: "Berbesti", comuna: "Giulesti" },
  { nume: "Berchez", comuna: "Remetea Chioarului" },
  { nume: "Berchezoaia", comuna: "Remetea Chioarului" },
  { nume: "Berinţa", simplu: "Berinta", comuna: "Copalnic-Manastur" },
  { nume: "Bicaz" },
  { nume: "Bistra" },
  { nume: "Blidari", comuna: "Baia Mare" },
  { nume: "Bocicoel", comuna: "Bogdan Voda" },
  { nume: "Bocicoiu Mare" },
  { nume: "Bogdan Vodă", simplu: "Bogdan Voda" },
  { nume: "Boiereni", comuna: "Targu Lapus" },
  { nume: "Boiu Mare" },
  { nume: "Bontăieni", simplu: "Bontaieni", comuna: "Sisesti" },
  { nume: "Borcut", comuna: "Targu Lapus" },
  { nume: "Borşa", simplu: "Borsa" },
  { nume: "Botiza" },
  { nume: "Bozânta Mare", simplu: "Bozanta Mare", comuna: "Tautii-Magheraus" },
  { nume: "Bozânta Mică", simplu: "Bozanta Mica", comuna: "Recea" },
  { nume: "Breb", comuna: "Ocna Sugatag" },
  { nume: "Brebeni", comuna: "Cernesti" },
  { nume: "Buciumi", comuna: "Somcuta Mare" },
  { nume: "Budeşti", simplu: "Budesti" },
  { nume: "Buşag", simplu: "Busag", comuna: "Tautii-Magheraus" },
  { nume: "Buteasa", comuna: "Somcuta Mare" },
  { nume: "Buzeşti", simplu: "Buzesti", comuna: "Farcasa" },
  { nume: "Călineşti", simplu: "Calinesti" },
  { nume: "Câmpulung la Tisa", simplu: "Campulung la Tisa" },
  { nume: "Cărbunari", simplu: "Carbunari", comuna: "Dumbravita" },
  { nume: "Cărpiniş", simplu: "Carpinis", comuna: "Copalnic-Manastur" },
  { nume: "Cătălina", simplu: "Catalina", comuna: "Sacalaseni" },
  { nume: "Cavnic" },
  { nume: "Cerneşti", simplu: "Cernesti" },
  { nume: "Cetăţele", simplu: "Cetatele", comuna: "Sisesti" },
  { nume: "Chechiş", simplu: "Chechis", comuna: "Dumbravita" },
  { nume: "Chelinţa", simplu: "Chelinta", comuna: "Ulmeni" },
  { nume: "Chiuzbaia", comuna: "Baia Sprie" },
  { nume: "Cicârlău", simplu: "Cicarlau" },
  { nume: "Ciocotiş", simplu: "Ciocotis", comuna: "Cernesti" },
  { nume: "Ciolt", comuna: "Somcuta Mare" },
  { nume: "Ciuta", comuna: "Bicaz" },
  { nume: "Coaş", simplu: "Coas", comuna: "Sacalaseni" },
  { nume: "Codru Butesii", comuna: "Somcuta Mare" },
  { nume: "Coltău", simplu: "Coltau", comuna: "Sacalaseni" },
  { nume: "Colţirea", simplu: "Coltirea", comuna: "Ardusat" },
  { nume: "Copalnic-Deal", comuna: "Copalnic-Manastur" },
  { nume: "Copalnic-Mănăştur", simplu: "Copalnic-Manastur" },
  { nume: "Copalnic", comuna: "Copalnic-Manastur" },
  { nume: "Corneşti", simplu: "Cornesti", comuna: "Calinesti" },
  { nume: "Corni", comuna: "Bicaz" },
  { nume: "Coroieni" },
  { nume: "Coruia", comuna: "Sacalaseni" },
  { nume: "Costeni", comuna: "Cupseni" },
  { nume: "Coştiui", simplu: "Costiui", comuna: "Rona De Sus" },
  { nume: "Crăciuneşti", simplu: "Craciunesti", comuna: "Bocicoiu Mare" },
  { nume: "Crasna Vişeului", simplu: "Crasna Viseului", comuna: "Bistra" },
  { nume: "Cufoaia", comuna: "Targu Lapus" },
  { nume: "Culcea", comuna: "Sacalaseni" },
  { nume: "Cupşeni", simplu: "Cupseni" },
  {
    nume: "Curtuiuşu Mare",
    simplu: "Curtuiusu Mare",
    comuna: "Valea Chioarului",
  },
  {
    nume: "Curtuiuşu Mic",
    simplu: "Curtuiusu Mic",
    comuna: "Copalnic-Manastur",
  },
  { nume: "Dămăcuşeni", simplu: "Damacuseni", comuna: "Targu Lapus" },
  { nume: "Dăneşti", simplu: "Danesti", comuna: "Sisesti" },
  {
    nume: "Dăneştii Chioarului",
    simplu: "Danestii Chioarului",
    comuna: "Miresu Mare",
  },
  { nume: "Dealu Corbului", comuna: "Vima Mica" },
  { nume: "Dealu Mare", comuna: "Coroieni" },
  { nume: "Deseşti", simplu: "Desesti" },
  {
    nume: "Dobricu Lăpuşului",
    simplu: "Dobricu Lapusului",
    comuna: "Targu Lapus",
  },
  { nume: "Drăghia", simplu: "Draghia", comuna: "Coroieni" },
  { nume: "Dragomireşti", simplu: "Dragomiresti" },
  { nume: "Dumbrava", comuna: "Targu Lapus" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita" },
  { nume: "Duruşa", simplu: "Durusa", comuna: "Valea Chioarului" },
  { nume: "Fânaţe", simplu: "Fanate", comuna: "Cernesti" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Targu Lapus" },
  { nume: "Fărcaşa", simplu: "Farcasa" },
  { nume: "Făureşti", simplu: "Fauresti", comuna: "Copalnic-Manastur" },
  { nume: "Fereşti", simplu: "Feresti", comuna: "Giulesti" },
  { nume: "Fericea", comuna: "Valea Chioarului" },
  { nume: "Fersig", comuna: "Satulung" },
  { nume: "Finteuşu Mare", simplu: "Finteusu Mare", comuna: "Somcuta Mare" },
  { nume: "Finteuşu Mic", simplu: "Finteusu Mic", comuna: "Satulung" },
  { nume: "Firiza", comuna: "Baia Mare" },
  {
    nume: "Frâncenii Boiului",
    simplu: "Francenii Boiului",
    comuna: "Boiu Mare",
  },
  { nume: "Gârdani", simplu: "Gardani", comuna: "Salsig" },
  { nume: "Giuleşti", simplu: "Giulesti" },
  { nume: "Glod", comuna: "Stramtura" },
  { nume: "Groape", comuna: "Targu Lapus" },
  { nume: "Groşi", simplu: "Grosi" },
  { nume: "Groşii Ţibleşului", simplu: "Grosii Tiblesului" },
  { nume: "Handalu Ilbei", comuna: "Cicarlau" },
  { nume: "Hărniceşti", simplu: "Harnicesti", comuna: "Desesti" },
  { nume: "Hideaga", comuna: "Satulung" },
  { nume: "Hoteni", comuna: "Ocna Sugatag" },
  { nume: "Hovrila", comuna: "Somcuta Mare" },
  { nume: "Iadăra", simplu: "Iadara", comuna: "Miresu Mare" },
  { nume: "Iapa", comuna: "Sighetu Marmatiei" },
  { nume: "Ieud" },
  { nume: "Ilba", comuna: "Cicarlau" },
  { nume: "Inău", simplu: "Inau", comuna: "Targu Lapus" },
  { nume: "Întrerâuri", simplu: "Intrerauri", comuna: "Sacalaseni" },
  { nume: "Izvoarele", comuna: "Cernesti" },
  { nume: "Jugăstreni", simplu: "Jugastreni", comuna: "Vima Mica" },
  { nume: "Lăpuş", simplu: "Lapus" },
  { nume: "Lăpuşel", simplu: "Lapusel", comuna: "Recea" },
  { nume: "Larga", comuna: "Suciu De Sus" },
  { nume: "Lăschia", simplu: "Laschia", comuna: "Copalnic-Manastur" },
  { nume: "Lazu Baciului", comuna: "Sighetu Marmatiei" },
  { nume: "Leordina" },
  { nume: "Libotin", comuna: "Cupseni" },
  { nume: "Lucăceşti", simplu: "Lucacesti", comuna: "Miresu Mare" },
  { nume: "Lunca la Tisa", comuna: "Bocicoiu Mare" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Cernesti" },
  { nume: "Mănăstirea", simplu: "Manastirea", comuna: "Giulesti" },
  { nume: "Mânău", simplu: "Manau", comuna: "Ulmeni" },
  { nume: "Mara", comuna: "Desesti" },
  { nume: "Merişor", simplu: "Merisor", comuna: "Tautii-Magheraus" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Valea Chioarului" },
  { nume: "Mireşu Mare", simplu: "Miresu Mare" },
  { nume: "Mocira", comuna: "Recea" },
  { nume: "Mogoşeşti", simplu: "Mogosesti", comuna: "Satulung" },
  { nume: "Moisei" },
  { nume: "Năneşti", simplu: "Nanesti", comuna: "Barsana" },
  { nume: "Negreia", comuna: "Sisesti" },
  { nume: "Nistru", comuna: "Tautii-Magheraus" },
  { nume: "Oarţa de Jos", simplu: "Oarta de Jos" },
  { nume: "Oarţa de Sus", simplu: "Oarta de Sus", comuna: "Oarta De Jos" },
  { nume: "Ocna Şugatag", simplu: "Ocna Sugatag" },
  { nume: "Ocoliş", simplu: "Ocolis", comuna: "Grosi" },
  { nume: "Odeşti", simplu: "Odesti", comuna: "Basesti" },
  { nume: "Onceşti", simplu: "Oncesti", comuna: "Barsana" },
  { nume: "Orţiţa", simplu: "Ortita", comuna: "Oarta De Jos" },
  { nume: "Peteritea", comuna: "Vima Mica" },
  { nume: "Petrova" },
  { nume: "Piatra", comuna: "Remeti" },
  { nume: "Plopiş", simplu: "Plopis", comuna: "Sisesti" },
  { nume: "Poiana Botizii", comuna: "Baiut" },
  { nume: "Poienile de Sub Munte" },
  { nume: "Poienile Izei" },
  { nume: "Posta", comuna: "Remetea Chioarului" },
  { nume: "Preluca Nouă", simplu: "Preluca Noua", comuna: "Copalnic-Manastur" },
  { nume: "Preluca Veche", comuna: "Copalnic-Manastur" },
  { nume: "Pribileşti", simplu: "Pribilesti", comuna: "Satulung" },
  { nume: "Prislop", comuna: "Boiu Mare" },
  { nume: "Răzoare", simplu: "Razoare", comuna: "Targu Lapus" },
  { nume: "Recea" },
  { nume: "Remecioara", comuna: "Remetea Chioarului" },
  { nume: "Remetea Chioarului" },
  { nume: "Remeţi pe Someş", simplu: "Remeti pe Somes", comuna: "Miresu Mare" },
  { nume: "Remeţi", simplu: "Remeti" },
  { nume: "Repedea" },
  { nume: "Rodina", comuna: "Arinis" },
  { nume: "Rogoz", comuna: "Targu Lapus" },
  { nume: "Rohia", comuna: "Targu Lapus" },
  { nume: "Romăneşti", simplu: "Romanesti", comuna: "Boiu Mare" },
  { nume: "Rona de Jos" },
  { nume: "Rona de Sus" },
  { nume: "Rozavlea" },
  { nume: "Rus", comuna: "Dumbravita" },
  { nume: "Ruscova" },
  { nume: "Ruşor", simplu: "Rusor", comuna: "Copalnic-Manastur" },
  { nume: "Săbişa", simplu: "Sabisa", comuna: "Seini" },
  { nume: "Săcălăşeni", simplu: "Sacalaseni" },
  { nume: "Săcel", simplu: "Sacel" },
  { nume: "Sălişte", simplu: "Saliste", comuna: "Basesti" },
  { nume: "Săliştea de Sus", simplu: "Salistea de Sus" },
  { nume: "Sălniţa", simplu: "Salnita", comuna: "Vima Mica" },
  { nume: "Sălsig", simplu: "Salsig" },
  { nume: "Salta", comuna: "Rozavlea" },
  { nume: "Săpânţa", simplu: "Sapanta" },
  { nume: "Sarasău", simplu: "Sarasau" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Budesti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Farcasa" },
  { nume: "Săsar", simplu: "Sasar", comuna: "Recea" },
  { nume: "Sat-Şugatag", simplu: "Sat-Sugatag", comuna: "Ocna Sugatag" },
  { nume: "Satu Nou de Jos", comuna: "Grosi" },
  { nume: "Satu Nou de Sus", comuna: "Baia Sprie" },
  { nume: "Satulung" },
  { nume: "Seini" },
  { nume: "Şieu", simplu: "Sieu" },
  { nume: "Sighetu Marmaţiei", simplu: "Sighetu Marmatiei" },
  { nume: "Şindreşti", simplu: "Sindresti", comuna: "Dumbravita" },
  { nume: "Şiseşti", simplu: "Sisesti" },
  { nume: "Slătioara", simplu: "Slatioara", comuna: "Stramtura" },
  { nume: "Şomcuţa Mare", simplu: "Somcuta Mare" },
  { nume: "Someş-Uileac", simplu: "Somes-Uileac", comuna: "Ulmeni" },
  { nume: "Stejera", comuna: "Miresu Mare" },
  { nume: "Stoiceni", comuna: "Targu Lapus" },
  { nume: "Strâmbu-Băiuţ", simplu: "Strambu-Baiut", comuna: "Baiut" },
  { nume: "Strâmtura", simplu: "Stramtura" },
  { nume: "Stremţ", simplu: "Stremt", comuna: "Basesti" },
  { nume: "Suciu de Jos", comuna: "Suciu De Sus" },
  { nume: "Suciu de Sus" },
  { nume: "Şugău", simplu: "Sugau", comuna: "Sighetu Marmatiei" },
  { nume: "Şurdeşti", simplu: "Surdesti", comuna: "Sisesti" },
  { nume: "Tămaia", simplu: "Tamaia", comuna: "Farcasa" },
  { nume: "Tămăşeşti", simplu: "Tamasesti", comuna: "Arinis" },
  { nume: "Târgu Lăpuş", simplu: "Targu Lapus" },
  { nume: "Tăuţii de Sus", simplu: "Tautii de Sus", comuna: "Baia Sprie" },
  { nume: "Tăuţii-Măgherăuş", simplu: "Tautii-Magheraus" },
  { nume: "Teceu Mic", comuna: "Remeti" },
  { nume: "Ţicău", simplu: "Ticau", comuna: "Ulmeni" },
  { nume: "Tisa", comuna: "Bocicoiu Mare" },
  { nume: "Tohat", comuna: "Ulmeni" },
  { nume: "Trestia", comuna: "Cernesti" },
  { nume: "Tulghieş", simplu: "Tulghies", comuna: "Miresu Mare" },
  { nume: "Ulmeni" },
  { nume: "Ulmoasa", comuna: "Tautii-Magheraus" },
  { nume: "Unguraş", simplu: "Unguras", comuna: "Dumbravita" },
  { nume: "Ungureni", comuna: "Cupseni" },
  { nume: "Urmeniş", simplu: "Urmenis", comuna: "Baita De Sub Codru" },
  { nume: "Vad", comuna: "Copalnic-Manastur" },
  { nume: "Vadu Izei" },
  { nume: "Valea Chioarului" },
  {
    nume: "Valea Cufundoasă",
    simplu: "Valea Cufundoasa",
    comuna: "Sighetu Marmatiei",
  },
  { nume: "Valea Hotarului", comuna: "Sighetu Marmatiei" },
  { nume: "Valea Neagră", simplu: "Valea Neagra", comuna: "Baia Mare" },
  { nume: "Valea Stejarului", comuna: "Vadu Izei" },
  { nume: "Valea Vişeului", simplu: "Valea Viseului", comuna: "Bistra" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Calinesti" },
  {
    nume: "Vălenii Lăpuşului",
    simplu: "Valenii Lapusului",
    comuna: "Coroieni",
  },
  {
    nume: "Vălenii Şomcutei",
    simplu: "Valenii Somcutei",
    comuna: "Somcuta Mare",
  },
  { nume: "Vărai", simplu: "Varai", comuna: "Valea Chioarului" },
  { nume: "Vicea", comuna: "Ulmeni" },
  { nume: "Viile Apei", comuna: "Seini" },
  { nume: "Vima Mare", comuna: "Vima Mica" },
  { nume: "Vima Mică", simplu: "Vima Mica" },
  { nume: "Vişeu de Jos", simplu: "Viseu de Jos" },
  {
    nume: "Vişeu de Mijloc",
    simplu: "Viseu de Mijloc",
    comuna: "Viseu De Sus",
  },
  { nume: "Vişeu de Sus", simplu: "Viseu de Sus" },
];
