export const mm = [
  { nume: "Ardusat" },
  { nume: "Arinis" },
  { nume: "Asuaju de Sus" },
  { nume: "Baia Mare" },
  { nume: "Baia Sprie" },
  { nume: "Bicaz" },
  { nume: "Bistra" },
  { nume: "Bocicoiu Mare" },
  { nume: "Bogdan Voda" },
  { nume: "Boiu Mare" },
  { nume: "Borsa" },
  { nume: "Botiza" },
  { nume: "Budesti" },
  { nume: "Barsana" },
  { nume: "Baiut" },
  { nume: "Baita de Sub Codru" },
  { nume: "Basesti" },
  { nume: "Cavnic" },
  { nume: "Cernesti" },
  { nume: "Cicarlau" },
  { nume: "Copalnic-Manastur" },
  { nume: "Coroieni" },
  { nume: "Cupseni" },
  { nume: "Campulung la Tisa" },
  { nume: "Calinesti" },
  { nume: "Desesti" },
  { nume: "Dragomiresti" },
  { nume: "Dumbravita" },
  { nume: "Farcasa" },
  { nume: "Giulesti" },
  { nume: "Grosi" },
  { nume: "Grosii Tiblesului" },
  { nume: "Ieud" },
  { nume: "Leordina" },
  { nume: "Lapus" },
  { nume: "Miresu Mare" },
  { nume: "Moisei" },
  { nume: "Oarta de Jos" },
  { nume: "Ocna Sugatag" },
  { nume: "Petrova" },
  { nume: "Poienile Izei" },
  { nume: "Poienile de Sub Munte" },
  { nume: "Recea" },
  { nume: "Remetea Chioarului" },
  { nume: "Remeti" },
  { nume: "Repedea" },
  { nume: "Rona de Jos" },
  { nume: "Rona de Sus" },
  { nume: "Rozavlea" },
  { nume: "Ruscova" },
  { nume: "Sarasau" },
  { nume: "Satulung" },
  { nume: "Seini" },
  { nume: "Sighetu Marmatiei" },
  { nume: "Stramtura" },
  { nume: "Suciu de Sus" },
  { nume: "Sacel" },
  { nume: "Sacalaseni" },
  { nume: "Salistea de Sus" },
  { nume: "Salsig" },
  { nume: "Sapanta" },
  { nume: "Targu Lapus" },
  { nume: "Tautii-Magheraus" },
  { nume: "Ulmeni" },
  { nume: "Vadu Izei" },
  { nume: "Valea Chioarului" },
  { nume: "Vima Mica" },
  { nume: "Viseu de Jos" },
  { nume: "Viseu de Sus" },
  { nume: "Sieu" },
  { nume: "Sisesti" },
  { nume: "Somcuta Mare" },
  { nume: "Ariesu de Camp", comuna: "Ardusat" },
  { nume: "Coltirea", comuna: "Ardusat" },
  { nume: "Rodina", comuna: "Arinis" },
  { nume: "Tamasesti", comuna: "Arinis" },
  { nume: "Asuaju de Jos", comuna: "Asuaju De Sus" },
  { nume: "Blidari", comuna: "Baia Mare" },
  { nume: "Firiza", comuna: "Baia Mare" },
  { nume: "Valea Neagra", comuna: "Baia Mare" },
  { nume: "Chiuzbaia", comuna: "Baia Sprie" },
  { nume: "Satu Nou de Sus", comuna: "Baia Sprie" },
  { nume: "Tautii de Sus", comuna: "Baia Sprie" },
  { nume: "Urmenis", comuna: "Baita De Sub Codru" },
  { nume: "Poiana Botizii", comuna: "Baiut" },
  { nume: "Strambu-Baiut", comuna: "Baiut" },
  { nume: "Nanesti", comuna: "Barsana" },
  { nume: "Oncesti", comuna: "Barsana" },
  { nume: "Odesti", comuna: "Basesti" },
  { nume: "Stremt", comuna: "Basesti" },
  { nume: "Saliste", comuna: "Basesti" },
  { nume: "Ciuta", comuna: "Bicaz" },
  { nume: "Corni", comuna: "Bicaz" },
  { nume: "Crasna Viseului", comuna: "Bistra" },
  { nume: "Valea Viseului", comuna: "Bistra" },
  { nume: "Craciunesti", comuna: "Bocicoiu Mare" },
  { nume: "Lunca la Tisa", comuna: "Bocicoiu Mare" },
  { nume: "Tisa", comuna: "Bocicoiu Mare" },
  { nume: "Bocicoel", comuna: "Bogdan Voda" },
  { nume: "Francenii Boiului", comuna: "Boiu Mare" },
  { nume: "Prislop", comuna: "Boiu Mare" },
  { nume: "Romanesti", comuna: "Boiu Mare" },
  { nume: "Baile Borsa", comuna: "Borsa" },
  { nume: "Sarbi", comuna: "Budesti" },
  { nume: "Cornesti", comuna: "Calinesti" },
  { nume: "Valeni", comuna: "Calinesti" },
  { nume: "Brebeni", comuna: "Cernesti" },
  { nume: "Ciocotis", comuna: "Cernesti" },
  { nume: "Fanate", comuna: "Cernesti" },
  { nume: "Izvoarele", comuna: "Cernesti" },
  { nume: "Magureni", comuna: "Cernesti" },
  { nume: "Trestia", comuna: "Cernesti" },
  { nume: "Bargau", comuna: "Cicarlau" },
  { nume: "Handalu Ilbei", comuna: "Cicarlau" },
  { nume: "Ilba", comuna: "Cicarlau" },
  { nume: "Berinta", comuna: "Copalnic-Manastur" },
  { nume: "Copalnic", comuna: "Copalnic-Manastur" },
  { nume: "Copalnic-Deal", comuna: "Copalnic-Manastur" },
  { nume: "Curtuiusu Mic", comuna: "Copalnic-Manastur" },
  { nume: "Carpinis", comuna: "Copalnic-Manastur" },
  { nume: "Fauresti", comuna: "Copalnic-Manastur" },
  { nume: "Laschia", comuna: "Copalnic-Manastur" },
  { nume: "Preluca Noua", comuna: "Copalnic-Manastur" },
  { nume: "Preluca Veche", comuna: "Copalnic-Manastur" },
  { nume: "Rusor", comuna: "Copalnic-Manastur" },
  { nume: "Vad", comuna: "Copalnic-Manastur" },
  { nume: "Baba", comuna: "Coroieni" },
  { nume: "Dealu Mare", comuna: "Coroieni" },
  { nume: "Draghia", comuna: "Coroieni" },
  { nume: "Valenii Lapusului", comuna: "Coroieni" },
  { nume: "Costeni", comuna: "Cupseni" },
  { nume: "Libotin", comuna: "Cupseni" },
  { nume: "Ungureni", comuna: "Cupseni" },
  { nume: "Harnicesti", comuna: "Desesti" },
  { nume: "Mara", comuna: "Desesti" },
  { nume: "Chechis", comuna: "Dumbravita" },
  { nume: "Carbunari", comuna: "Dumbravita" },
  { nume: "Rus", comuna: "Dumbravita" },
  { nume: "Unguras", comuna: "Dumbravita" },
  { nume: "Sindresti", comuna: "Dumbravita" },
  { nume: "Buzesti", comuna: "Farcasa" },
  { nume: "Sarbi", comuna: "Farcasa" },
  { nume: "Tamaia", comuna: "Farcasa" },
  { nume: "Berbesti", comuna: "Giulesti" },
  { nume: "Feresti", comuna: "Giulesti" },
  { nume: "Manastirea", comuna: "Giulesti" },
  { nume: "Ocolis", comuna: "Grosi" },
  { nume: "Satu Nou de Jos", comuna: "Grosi" },
  { nume: "Danestii Chioarului", comuna: "Miresu Mare" },
  { nume: "Iadara", comuna: "Miresu Mare" },
  { nume: "Lucacesti", comuna: "Miresu Mare" },
  { nume: "Remeti pe Somes", comuna: "Miresu Mare" },
  { nume: "Stejera", comuna: "Miresu Mare" },
  { nume: "Tulghies", comuna: "Miresu Mare" },
  { nume: "Oarta de Sus", comuna: "Oarta De Jos" },
  { nume: "Ortita", comuna: "Oarta De Jos" },
  { nume: "Breb", comuna: "Ocna Sugatag" },
  { nume: "Hoteni", comuna: "Ocna Sugatag" },
  { nume: "Sat-Sugatag", comuna: "Ocna Sugatag" },
  { nume: "Bozanta Mica", comuna: "Recea" },
  { nume: "Lapusel", comuna: "Recea" },
  { nume: "Mocira", comuna: "Recea" },
  { nume: "Sasar", comuna: "Recea" },
  { nume: "Berchez", comuna: "Remetea Chioarului" },
  { nume: "Berchezoaia", comuna: "Remetea Chioarului" },
  { nume: "Posta", comuna: "Remetea Chioarului" },
  { nume: "Remecioara", comuna: "Remetea Chioarului" },
  { nume: "Piatra", comuna: "Remeti" },
  { nume: "Teceu Mic", comuna: "Remeti" },
  { nume: "Costiui", comuna: "Rona De Sus" },
  { nume: "Salta", comuna: "Rozavlea" },
  { nume: "Coas", comuna: "Sacalaseni" },
  { nume: "Coltau", comuna: "Sacalaseni" },
  { nume: "Coruia", comuna: "Sacalaseni" },
  { nume: "Culcea", comuna: "Sacalaseni" },
  { nume: "Catalina", comuna: "Sacalaseni" },
  { nume: "Intrerauri", comuna: "Sacalaseni" },
  { nume: "Gardani", comuna: "Salsig" },
  { nume: "Ariesu de Padure", comuna: "Satulung" },
  { nume: "Fersig", comuna: "Satulung" },
  { nume: "Finteusu Mic", comuna: "Satulung" },
  { nume: "Hideaga", comuna: "Satulung" },
  { nume: "Mogosesti", comuna: "Satulung" },
  { nume: "Pribilesti", comuna: "Satulung" },
  { nume: "Sabisa", comuna: "Seini" },
  { nume: "Viile Apei", comuna: "Seini" },
  { nume: "Iapa", comuna: "Sighetu Marmatiei" },
  { nume: "Lazu Baciului", comuna: "Sighetu Marmatiei" },
  { nume: "Valea Cufundoasa", comuna: "Sighetu Marmatiei" },
  { nume: "Valea Hotarului", comuna: "Sighetu Marmatiei" },
  { nume: "Sugau", comuna: "Sighetu Marmatiei" },
  { nume: "Bontaieni", comuna: "Sisesti" },
  { nume: "Cetatele", comuna: "Sisesti" },
  { nume: "Danesti", comuna: "Sisesti" },
  { nume: "Negreia", comuna: "Sisesti" },
  { nume: "Plopis", comuna: "Sisesti" },
  { nume: "Surdesti", comuna: "Sisesti" },
  { nume: "Buciumi", comuna: "Somcuta Mare" },
  { nume: "Buteasa", comuna: "Somcuta Mare" },
  { nume: "Ciolt", comuna: "Somcuta Mare" },
  { nume: "Codru Butesii", comuna: "Somcuta Mare" },
  { nume: "Finteusu Mare", comuna: "Somcuta Mare" },
  { nume: "Hovrila", comuna: "Somcuta Mare" },
  { nume: "Valenii Somcutei", comuna: "Somcuta Mare" },
  { nume: "Glod", comuna: "Stramtura" },
  { nume: "Slatioara", comuna: "Stramtura" },
  { nume: "Larga", comuna: "Suciu De Sus" },
  { nume: "Suciu de Jos", comuna: "Suciu De Sus" },
  { nume: "Boiereni", comuna: "Targu Lapus" },
  { nume: "Borcut", comuna: "Targu Lapus" },
  { nume: "Cufoaia", comuna: "Targu Lapus" },
  { nume: "Dobricu Lapusului", comuna: "Targu Lapus" },
  { nume: "Dumbrava", comuna: "Targu Lapus" },
  { nume: "Damacuseni", comuna: "Targu Lapus" },
  { nume: "Fantanele", comuna: "Targu Lapus" },
  { nume: "Groape", comuna: "Targu Lapus" },
  { nume: "Inau", comuna: "Targu Lapus" },
  { nume: "Rogoz", comuna: "Targu Lapus" },
  { nume: "Rohia", comuna: "Targu Lapus" },
  { nume: "Razoare", comuna: "Targu Lapus" },
  { nume: "Stoiceni", comuna: "Targu Lapus" },
  { nume: "Bozanta Mare", comuna: "Tautii-Magheraus" },
  { nume: "Busag", comuna: "Tautii-Magheraus" },
  { nume: "Baita", comuna: "Tautii-Magheraus" },
  { nume: "Merisor", comuna: "Tautii-Magheraus" },
  { nume: "Nistru", comuna: "Tautii-Magheraus" },
  { nume: "Ulmoasa", comuna: "Tautii-Magheraus" },
  { nume: "Arduzel", comuna: "Ulmeni" },
  { nume: "Chelinta", comuna: "Ulmeni" },
  { nume: "Manau", comuna: "Ulmeni" },
  { nume: "Somes-Uileac", comuna: "Ulmeni" },
  { nume: "Tohat", comuna: "Ulmeni" },
  { nume: "Vicea", comuna: "Ulmeni" },
  { nume: "Ticau", comuna: "Ulmeni" },
  { nume: "Valea Stejarului", comuna: "Vadu Izei" },
  { nume: "Curtuiusu Mare", comuna: "Valea Chioarului" },
  { nume: "Durusa", comuna: "Valea Chioarului" },
  { nume: "Fericea", comuna: "Valea Chioarului" },
  { nume: "Mesteacan", comuna: "Valea Chioarului" },
  { nume: "Varai", comuna: "Valea Chioarului" },
  { nume: "Aspra", comuna: "Vima Mica" },
  { nume: "Dealu Corbului", comuna: "Vima Mica" },
  { nume: "Jugastreni", comuna: "Vima Mica" },
  { nume: "Peteritea", comuna: "Vima Mica" },
  { nume: "Salnita", comuna: "Vima Mica" },
  { nume: "Vima Mare", comuna: "Vima Mica" },
  { nume: "Viseu de Mijloc", comuna: "Viseu De Sus" },
];
