export const mh = [
  { nume: "23 August", comuna: "Malovat" },
  { nume: "Adunații Teiului", simplu: "Adunatii Teiului", comuna: "Tamna" },
  { nume: "Albulești", simplu: "Albulesti", comuna: "Dumbrava" },
  { nume: "Almăjel", simplu: "Almajel", comuna: "Vladaia" },
  { nume: "Alunișul", simplu: "Alunisul", comuna: "Husnicioara" },
  { nume: "Arginești", simplu: "Arginesti", comuna: "Butoiesti" },
  { nume: "Arvătești", simplu: "Arvatesti", comuna: "Prunisor" },
  { nume: "Aurora", comuna: "Cujmir" },
  { nume: "Bâcleș", simplu: "Bacles" },
  { nume: "Bădițești", simplu: "Baditesti", comuna: "Husnicioara" },
  { nume: "Bahna", comuna: "Ilovita" },
  { nume: "Baia de Aramă", simplu: "Baia de Arama" },
  { nume: "Baia Nouă", simplu: "Baia Noua", comuna: "Dubova" },
  { nume: "Bala de Sus", comuna: "Bala" },
  { nume: "Bala" },
  { nume: "Bălăcița", simplu: "Balacita" },
  { nume: "Balota", comuna: "Prunisor" },
  { nume: "Balotești", simplu: "Balotesti", comuna: "Izvoru Barzii" },
  { nume: "Balta Verde", comuna: "Gogosu" },
  { nume: "Balta" },
  { nume: "Bâltanele", simplu: "Baltanele", comuna: "Greci" },
  { nume: "Bâltanele", simplu: "Baltanele", comuna: "Prunisor" },
  { nume: "Băluța", simplu: "Baluta", comuna: "Ponoarele" },
  { nume: "Bâlvănești", simplu: "Balvanesti" },
  {
    nume: "Bâlvăneștii de Jos",
    simplu: "Balvanestii de Jos",
    comuna: "Balvanesti",
  },
  { nume: "Bârâiacu", simplu: "Baraiacu", comuna: "Ponoarele" },
  { nume: "Bârda", simplu: "Barda", comuna: "Malovat" },
  { nume: "Bârlogeni", simplu: "Barlogeni", comuna: "Stangaceaua" },
  { nume: "Batoți", simplu: "Batoti", comuna: "Devesel" },
  { nume: "Biban", comuna: "Padina" },
  { nume: "Bistrețu", simplu: "Bistretu", comuna: "Devesel" },
  { nume: "Bistrița", simplu: "Bistrita", comuna: "Hinova" },
  { nume: "Blidaru", comuna: "Greci" },
  { nume: "Bobaița", simplu: "Bobaita", comuna: "Malovat" },
  { nume: "Boceni", comuna: "Tamna" },
  { nume: "Borogea", comuna: "Husnicioara" },
  { nume: "Brâgleasa", simplu: "Bragleasa", comuna: "Dumbrava" },
  { nume: "Braniștea", simplu: "Branistea", comuna: "Vanatori" },
  { nume: "Brânzeni", simplu: "Branzeni", comuna: "Ponoarele" },
  { nume: "Brateșul", simplu: "Bratesul", comuna: "Bala" },
  { nume: "Bratilovu", comuna: "Baia De Arama" },
  { nume: "Brativoești", simplu: "Brativoesti", comuna: "Bala" },
  { nume: "Brebina", comuna: "Baia De Arama" },
  { nume: "Breța", simplu: "Breta", comuna: "Corcova" },
  { nume: "Breznicioara", comuna: "Stangaceaua" },
  { nume: "Breznița-Motru", simplu: "Breznita-Motru" },
  { nume: "Breznița-Ocol", simplu: "Breznita-Ocol" },
  { nume: "Broșteni", simplu: "Brosteni" },
  { nume: "Bucura", comuna: "Vanju Mare" },
  { nume: "Budănești", simplu: "Budanesti", comuna: "Ilovat" },
  { nume: "Buicani", comuna: "Ponoarele" },
  { nume: "Buicești", simplu: "Buicesti", comuna: "Butoiesti" },
  { nume: "Bunoaica", comuna: "Ciresu" },
  { nume: "Burila Mare" },
  { nume: "Burila Mică", simplu: "Burila Mica", comuna: "Gogosu" },
  { nume: "Busești", simplu: "Busesti", comuna: "Isverna" },
  { nume: "Butoiești", simplu: "Butoiesti" },
  {
    nume: "Călineștii de Jos",
    simplu: "Calinestii de Jos",
    comuna: "Balvanesti",
  },
  {
    nume: "Călineștii de Sus",
    simplu: "Calinestii de Sus",
    comuna: "Balvanesti",
  },
  { nume: "Câmpu Mare", simplu: "Campu Mare", comuna: "Bala" },
  { nume: "Căpățânești", simplu: "Capatanesti", comuna: "Brosteni" },
  { nume: "Cărămidaru", simplu: "Caramidaru", comuna: "Sisesti" },
  { nume: "Cârceni", simplu: "Carceni", comuna: "Grozesti" },
  { nume: "Cârjei", simplu: "Carjei", comuna: "Hinova" },
  { nume: "Cârșu", simplu: "Carsu", comuna: "Bala" },
  { nume: "Căzănești", simplu: "Cazanesti" },
  { nume: "Cearângu", simplu: "Cearangu", comuna: "Punghina" },
  { nume: "Celnata", comuna: "Husnicioara" },
  { nume: "Ceptureni", comuna: "Ponoarele" },
  { nume: "Cerânganul", simplu: "Ceranganul", comuna: "Stangaceaua" },
  { nume: "Cerna-Vârf", simplu: "Cerna-Varf", comuna: "Isverna" },
  { nume: "Cernaia", comuna: "Corcova" },
  { nume: "Cerneți", simplu: "Cerneti", comuna: "Simian" },
  { nume: "Cervenița", simplu: "Cervenita", comuna: "Prunisor" },
  { nume: "Ciochiuța", simplu: "Ciochiuta", comuna: "Strehaia" },
  { nume: "Cioroboreni", comuna: "Jiana" },
  { nume: "Ciovârnășani", simplu: "Ciovarnasani", comuna: "Sisesti" },
  { nume: "Cireșu", simplu: "Ciresu" },
  { nume: "Coada Cornetului", comuna: "Balta" },
  { nume: "Cocorova", comuna: "Sisesti" },
  { nume: "Colareț", simplu: "Colaret", comuna: "Tamna" },
  { nume: "Colibași", simplu: "Colibasi", comuna: "Malovat" },
  { nume: "Comanda", comuna: "Strehaia" },
  { nume: "Comănești", simplu: "Comanesti", comuna: "Bala" },
  { nume: "Copăcioasa", simplu: "Copacioasa", comuna: "Floresti" },
  { nume: "Corcova" },
  { nume: "Cordun", comuna: "Corcova" },
  { nume: "Corlățel", simplu: "Corlatel" },
  { nume: "Corzu", comuna: "Bacles" },
  { nume: "Cosovăț", simplu: "Cosovat", comuna: "Breznita-Motru" },
  { nume: "Costești", simplu: "Costesti", comuna: "Balta" },
  { nume: "Cotoroaia", comuna: "Voloiac" },
  { nume: "Cozia", comuna: "Pristol" },
  { nume: "Cracu Lung", comuna: "Ilovat" },
  { nume: "Cracu Muntelui", comuna: "Ponoarele" },
  { nume: "Crăguești", simplu: "Craguesti", comuna: "Sisesti" },
  { nume: "Crainici", comuna: "Bala" },
  { nume: "Cremenea", comuna: "Tamna" },
  { nume: "Crivina", comuna: "Burila Mare" },
  { nume: "Croica", comuna: "Corcova" },
  { nume: "Cujmir" },
  { nume: "Cujmiru Mic", comuna: "Cujmir" },
  { nume: "Dâlbocița", simplu: "Dalbocita", comuna: "Ilovat" },
  { nume: "Dâlma", simplu: "Dalma", comuna: "Bala" },
  { nume: "Dănceu", simplu: "Danceu", comuna: "Jiana" },
  { nume: "Dârvari", simplu: "Darvari" },
  { nume: "Dealu Mare", comuna: "Baia De Arama" },
  { nume: "Dedovița Nouă", simplu: "Dedovita Noua", comuna: "Simian" },
  { nume: "Dedovița Veche", simplu: "Dedovita Veche", comuna: "Simian" },
  { nume: "Deleni", comuna: "Breznita-Motru" },
  { nume: "Delureni", comuna: "Ponoarele" },
  { nume: "Devesel" },
  { nume: "Dobra", comuna: "Balacita" },
  { nume: "Drăghești", simplu: "Draghesti", comuna: "Isverna" },
  { nume: "Dragotești", simplu: "Dragotesti", comuna: "Prunisor" },
  { nume: "Drincea", comuna: "Punghina" },
  { nume: "Drobeta-Turnu Severin" },
  { nume: "Dubova" },
  {
    nume: "Dudașu Schelei",
    simplu: "Dudasu Schelei",
    comuna: "Drobeta-Turnu Severin",
  },
  { nume: "Dudașu", simplu: "Dudasu", comuna: "Simian" },
  { nume: "Dumbrava de Jos", comuna: "Dumbrava" },
  { nume: "Dumbrava de Mijloc", comuna: "Dumbrava" },
  { nume: "Dumbrava de Sus", comuna: "Dumbrava" },
  { nume: "Dumbrăvița", simplu: "Dumbravita", comuna: "Husnicioara" },
  { nume: "Dunărea Mică", simplu: "Dunarea Mica", comuna: "Devesel" },
  { nume: "Eibenthal", comuna: "Dubova" },
  { nume: "Ercea", comuna: "Cazanesti" },
  { nume: "Erghevița", simplu: "Erghevita", comuna: "Simian" },
  { nume: "Eșelnița", simplu: "Eselnita" },
  {
    nume: "Fântâna Domnească",
    simplu: "Fantana Domneasca",
    comuna: "Prunisor",
  },
  {
    nume: "Fântânile Negre",
    simplu: "Fantanile Negre",
    comuna: "Poroina Mare",
  },
  { nume: "Fața Cremenii", simplu: "Fata Cremenii", comuna: "Tamna" },
  { nume: "Fața Motrului", simplu: "Fata Motrului", comuna: "Stangaceaua" },
  { nume: "Făuroaia", simplu: "Fauroaia", comuna: "Breznita-Motru" },
  { nume: "Firizu", comuna: "Ilovat" },
  { nume: "Florești", simplu: "Floresti" },
  { nume: "Gârbovățu de Jos", simplu: "Garbovatu de Jos", comuna: "Corcova" },
  { nume: "Gârbovățu de Sus", simplu: "Garbovatu de Sus", comuna: "Cazanesti" },
  { nume: "Gărdăneasa", simplu: "Gardaneasa", comuna: "Ponoarele" },
  { nume: "Gârdoaia", simplu: "Gardoaia", comuna: "Floresti" },
  { nume: "Gârla Mare", simplu: "Garla Mare" },
  { nume: "Gârnița", simplu: "Garnita", comuna: "Prunisor" },
  { nume: "Gemeni", comuna: "Darvari" },
  { nume: "Ghelmegioaia", comuna: "Prunisor" },
  { nume: "Gheorghești", simplu: "Gheorghesti", comuna: "Ponoarele" },
  { nume: "Giura", comuna: "Bacles" },
  { nume: "Giurgiani", comuna: "Isverna" },
  { nume: "Goanța", simplu: "Goanta", comuna: "Vanatori" },
  { nume: "Godeanu" },
  { nume: "Godeanu", comuna: "Obarsia-Closani" },
  { nume: "Gogoșu", simplu: "Gogosu" },
  { nume: "Golineasa", comuna: "Dumbrava" },
  { nume: "Gornenți", simplu: "Gornenti", comuna: "Podeni" },
  { nume: "Gornovița", simplu: "Gornovita", comuna: "Balta" },
  { nume: "Govodarva", comuna: "Cazanesti" },
  { nume: "Greci" },
  { nume: "Grozești", simplu: "Grozesti" },
  { nume: "Gruia" },
  { nume: "Gura Motrului", comuna: "Butoiesti" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Drobeta-Turnu Severin" },
  { nume: "Gutu", comuna: "Prunisor" },
  { nume: "Gvardinița", simplu: "Gvardinita", comuna: "Balacita" },
  { nume: "Halânga", simplu: "Halanga", comuna: "Izvoru Barzii" },
  { nume: "Higiu", comuna: "Dumbrava" },
  { nume: "Hinova" },
  { nume: "Hotărani", simplu: "Hotarani", comuna: "Vanjulet" },
  { nume: "Hurducești", simplu: "Hurducesti", comuna: "Strehaia" },
  { nume: "Husnicioara" },
  { nume: "Iablanița", simplu: "Iablanita", comuna: "Padina" },
  { nume: "Igiroasa", comuna: "Prunisor" },
  { nume: "Ilovăț", simplu: "Ilovat" },
  { nume: "Ilovița", simplu: "Ilovita" },
  { nume: "Ilovu", comuna: "Cazanesti" },
  { nume: "Imoasa", comuna: "Corcova" },
  { nume: "Isverna" },
  { nume: "Iupca", comuna: "Bala" },
  { nume: "Izimșa", simplu: "Izimsa", comuna: "Obarsia De Camp" },
  { nume: "Izvoarele", comuna: "Gruia" },
  { nume: "Izvorălu de Jos", simplu: "Izvoralu de Jos", comuna: "Livezile" },
  { nume: "Izvorălu", simplu: "Izvoralu", comuna: "Tamna" },
  { nume: "Izvoru Aneștilor", simplu: "Izvoru Anestilor", comuna: "Livezile" },
  { nume: "Izvoru Bârzii", simplu: "Izvoru Barzii" },
  { nume: "Izvoru Frumos", comuna: "Burila Mare" },
  { nume: "Jiana Mare", comuna: "Jiana" },
  { nume: "Jiana Veche", comuna: "Jiana" },
  { nume: "Jiana" },
  { nume: "Jidoștița", simplu: "Jidostita", comuna: "Breznita-Ocol" },
  { nume: "Jignița", simplu: "Jignita", comuna: "Cazanesti" },
  { nume: "Jirov", comuna: "Corcova" },
  { nume: "Jugastru", comuna: "Butoiesti" },
  { nume: "Jupânești", simplu: "Jupanesti", comuna: "Ciresu" },
  { nume: "Lac", comuna: "Voloiac" },
  { nume: "Lazu", comuna: "Malovat" },
  { nume: "Livezi", comuna: "Floresti" },
  { nume: "Livezile" },
  { nume: "Ludu", comuna: "Ponoarele" },
  { nume: "Lumnic", comuna: "Prunisor" },
  { nume: "Lunca Banului", comuna: "Strehaia" },
  { nume: "Luncșoara", simplu: "Luncsoara", comuna: "Brosteni" },
  { nume: "Lupșa de Jos", simplu: "Lupsa de Jos", comuna: "Brosteni" },
  { nume: "Lupșa de Sus", simplu: "Lupsa de Sus", comuna: "Brosteni" },
  { nume: "Magheru", comuna: "Breznita-Ocol" },
  { nume: "Măgurele", simplu: "Magurele", comuna: "Punghina" },
  { nume: "Mălărișca", simplu: "Malarisca", comuna: "Podeni" },
  { nume: "Malovăț", simplu: "Malovat" },
  { nume: "Manu", comuna: "Tamna" },
  { nume: "Mărășești", simplu: "Marasesti", comuna: "Baia De Arama" },
  { nume: "Marga", comuna: "Godeanu" },
  { nume: "Marmanu", comuna: "Husnicioara" },
  { nume: "Măru Roșu", simplu: "Maru Rosu", comuna: "Corcova" },
  { nume: "Menți", simplu: "Menti", comuna: "Strehaia" },
  { nume: "Meriș", simplu: "Meris", comuna: "Brosteni" },
  { nume: "Mijarca", comuna: "Prunisor" },
  { nume: "Moisești", simplu: "Moisesti", comuna: "Ilovita" },
  { nume: "Molani", comuna: "Bala" },
  { nume: "Moșneni", simplu: "Mosneni", comuna: "Floresti" },
  { nume: "Motruleni", comuna: "Strehaia" },
  { nume: "Nadanova", comuna: "Isverna" },
  { nume: "Negoești", simplu: "Negoesti", comuna: "Baia De Arama" },
  { nume: "Negrești", simplu: "Negresti", comuna: "Malovat" },
  { nume: "Negrușa", simplu: "Negrusa", comuna: "Ciresu" },
  { nume: "Nevățu", simplu: "Nevatu", comuna: "Balta" },
  {
    nume: "Nicolae Bălcescu",
    simplu: "Nicolae Balcescu",
    comuna: "Vanju Mare",
  },
  { nume: "Noapteșa", simplu: "Noaptesa", comuna: "Sisesti" },
  { nume: "Obârșia de Câmp", simplu: "Obarsia de Camp" },
  { nume: "Obârșia-Cloșani", simplu: "Obarsia-Closani" },
  { nume: "Ohaba", comuna: "Sovarna" },
  { nume: "Olteanca", comuna: "Padina" },
  { nume: "Oprănești", simplu: "Opranesti", comuna: "Husnicioara" },
  { nume: "Oprișor", simplu: "Oprisor" },
  { nume: "Orevița Mare", simplu: "Orevita Mare", comuna: "Vanju Mare" },
  { nume: "Orșova", simplu: "Orsova" },
  { nume: "Ostrovu Corbului", comuna: "Hinova" },
  { nume: "Ostrovu Mare", comuna: "Gogosu" },
  { nume: "Pădina Mare", simplu: "Padina Mare", comuna: "Padina" },
  { nume: "Pădina Mică", simplu: "Padina Mica", comuna: "Padina" },
  { nume: "Păltinișu", simplu: "Paltinisu", comuna: "Cazanesti" },
  { nume: "Pârlagele", simplu: "Parlagele", comuna: "Balvanesti" },
  { nume: "Pârvulești", simplu: "Parvulesti", comuna: "Corcova" },
  { nume: "Păsărani", simplu: "Pasarani", comuna: "Grozesti" },
  { nume: "Pătulele", simplu: "Patulele" },
  { nume: "Păunești", simplu: "Paunesti", comuna: "Godeanu" },
  { nume: "Pavăț", simplu: "Pavat", comuna: "Tamna" },
  { nume: "Peri", comuna: "Husnicioara" },
  { nume: "Peșteana", simplu: "Pesteana", comuna: "Floresti" },
  { nume: "Peștenuța", simplu: "Pestenuta", comuna: "Floresti" },
  { nume: "Petra", comuna: "Bacles" },
  { nume: "Petriș", simplu: "Petris", comuna: "Livezile" },
  { nume: "Pistrița", simplu: "Pistrita", comuna: "Baia De Arama" },
  { nume: "Plai", comuna: "Breznita-Motru" },
  { nume: "Plopi", comuna: "Tamna" },
  { nume: "Pluta", comuna: "Butoiesti" },
  { nume: "Podeni" },
  { nume: "Podu Grosului", comuna: "Bacles" },
  { nume: "Poiana Gruii", comuna: "Gruia" },
  { nume: "Poiana", comuna: "Cazanesti" },
  { nume: "Ponoarele" },
  { nume: "Poroina Mare" },
  { nume: "Poroina", comuna: "Simian" },
  { nume: "Poroinița", simplu: "Poroinita", comuna: "Rogova" },
  { nume: "Poșta Veche", simplu: "Posta Veche", comuna: "Stangaceaua" },
  { nume: "Prejna", comuna: "Balta" },
  { nume: "Priboiești", simplu: "Priboiesti", comuna: "Husnicioara" },
  { nume: "Prisăceaua", simplu: "Prisaceaua", comuna: "Oprisor" },
  { nume: "Pristol" },
  { nume: "Proitești", simplu: "Proitesti", comuna: "Ponoarele" },
  { nume: "Prunaru", comuna: "Prunisor" },
  { nume: "Prunișor", simplu: "Prunisor" },
  { nume: "Punghina" },
  { nume: "Pușcașu", simplu: "Puscasu", comuna: "Corcova" },
  { nume: "Puținei", simplu: "Putinei", comuna: "Izvoru Barzii" },
  { nume: "Racova", comuna: "Ilovat" },
  { nume: "Răduțești", simplu: "Radutesti", comuna: "Butoiesti" },
  { nume: "Răiculești", simplu: "Raiculesti", comuna: "Ponoarele" },
  { nume: "Răscolești", simplu: "Rascolesti", comuna: "Izvoru Barzii" },
  { nume: "Recea", comuna: "Punghina" },
  { nume: "Rocșoreni", simplu: "Rocsoreni", comuna: "Dumbrava" },
  { nume: "Rogova" },
  { nume: "Roșia", simplu: "Rosia", comuna: "Cazanesti" },
  { nume: "Roșiori", simplu: "Rosiori", comuna: "Vanatori" },
  { nume: "Rudina", comuna: "Bala" },
  { nume: "Runcușoru", simplu: "Runcusoru", comuna: "Bala" },
  { nume: "Ruptura", comuna: "Voloiac" },
  { nume: "Sălătruc", simplu: "Salatruc", comuna: "Greci" },
  { nume: "Salcia" },
  { nume: "Sărdănești", simplu: "Sardanesti", comuna: "Bala" },
  { nume: "Satu Mare", comuna: "Stangaceaua" },
  { nume: "Satu Nou", comuna: "Punghina" },
  { nume: "Scăpău", simplu: "Scapau", comuna: "Devesel" },
  { nume: "Schela Cladovei", comuna: "Drobeta-Turnu Severin" },
  { nume: "Schinteiești", simplu: "Schinteiesti", comuna: "Izvoru Barzii" },
  {
    nume: "Schitu Topolniței",
    simplu: "Schitu Topolnitei",
    comuna: "Izvoru Barzii",
  },
  { nume: "Scorila", comuna: "Vladaia" },
  { nume: "Seliștea", simplu: "Selistea", comuna: "Isverna" },
  { nume: "Selișteni", simplu: "Selisteni", comuna: "Husnicioara" },
  { nume: "Seliștiuța", simplu: "Selistiuta", comuna: "Bacles" },
  { nume: "Severinești", simplu: "Severinesti", comuna: "Cazanesti" },
  { nume: "Sfodea", comuna: "Balta" },
  { nume: "Șimian", simplu: "Simian" },
  { nume: "Șipotu", simplu: "Sipotu", comuna: "Ponoarele" },
  { nume: "Șipotu", simplu: "Sipotu", comuna: "Poroina Mare" },
  { nume: "Șiroca", simplu: "Siroca", comuna: "Godeanu" },
  { nume: "Șișești", simplu: "Sisesti" },
  { nume: "Slașoma", simplu: "Slasoma", comuna: "Padina" },
  { nume: "Slătinicu Mare", simplu: "Slatinicu Mare", comuna: "Strehaia" },
  { nume: "Slătinicu Mic", simplu: "Slatinicu Mic", comuna: "Strehaia" },
  { nume: "Smadovița", simplu: "Smadovita", comuna: "Bacles" },
  { nume: "Șovarna", simplu: "Sovarna" },
  { nume: "Sperlești", simplu: "Sperlesti", comuna: "Voloiac" },
  { nume: "Stăncești", simplu: "Stancesti", comuna: "Strehaia" },
  { nume: "Stănești", simplu: "Stanesti", comuna: "Baia De Arama" },
  { nume: "Stângăceaua", simplu: "Stangaceaua" },
  { nume: "Ștefan Odobleja", simplu: "Stefan Odobleja", comuna: "Livezile" },
  { nume: "Stejaru", comuna: "Corcova" },
  { nume: "Stignița", simplu: "Stignita", comuna: "Poroina Mare" },
  { nume: "Ștircovița", simplu: "Stircovita", comuna: "Vladaia" },
  { nume: "Strehaia" },
  { nume: "Stroești", simplu: "Stroesti", comuna: "Floresti" },
  { nume: "Studina", comuna: "Sovarna" },
  { nume: "Suharu", comuna: "Cazanesti" },
  { nume: "Șușița", simplu: "Susita", comuna: "Breznita-Ocol" },
  { nume: "Șușița", simplu: "Susita", comuna: "Grozesti" },
  { nume: "Svinița", simplu: "Svinita" },
  { nume: "Tălăpanu", simplu: "Talapanu", comuna: "Breznita-Motru" },
  { nume: "Tâmna", simplu: "Tamna" },
  { nume: "Tânțaru", simplu: "Tantaru", comuna: "Butoiesti" },
  { nume: "Târsa", simplu: "Tarsa", comuna: "Stangaceaua" },
  { nume: "Țigănași", simplu: "Tiganasi", comuna: "Burila Mare" },
  { nume: "Tismana", comuna: "Devesel" },
  { nume: "Titerlești", simplu: "Titerlesti", comuna: "Baia De Arama" },
  { nume: "Țițirigi", simplu: "Titirigi", comuna: "Voloiac" },
  { nume: "Traian", comuna: "Vanju Mare" },
  { nume: "Turtaba", comuna: "Isverna" },
  { nume: "Valea Anilor", comuna: "Corlatel" },
  { nume: "Valea Bună", simplu: "Valea Buna", comuna: "Voloiac" },
  { nume: "Valea Copcii", comuna: "Simian" },
  { nume: "Valea Coșuștei", simplu: "Valea Cosustei", comuna: "Cazanesti" },
  { nume: "Valea Marcului", comuna: "Dumbrava" },
  { nume: "Valea Petrii", comuna: "Greci" },
  { nume: "Valea Teiului", comuna: "Breznita-Motru" },
  { nume: "Valea Ursului", comuna: "Ponoarele" },
  { nume: "Valea Ursului", comuna: "Tamna" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Vânju Mare", simplu: "Vanju Mare" },
  { nume: "Vânjuleț", simplu: "Vanjulet" },
  { nume: "Varodia", comuna: "Dumbrava" },
  { nume: "Viașu", simplu: "Viasu", comuna: "Patulele" },
  { nume: "Vidimirești", simplu: "Vidimiresti", comuna: "Bala" },
  { nume: "Vișina", simplu: "Visina", comuna: "Greci" },
  { nume: "Vlădaia", simplu: "Vladaia" },
  { nume: "Vlădășești", simplu: "Vladasesti", comuna: "Corcova" },
  { nume: "Vlădica", simplu: "Vladica", comuna: "Dumbrava" },
  { nume: "Voloiac" },
  { nume: "Voloicel", comuna: "Voloiac" },
  { nume: "Vrancea", comuna: "Burila Mare" },
  { nume: "Vrata", comuna: "Garla Mare" },
  { nume: "Zegaia", comuna: "Prunisor" },
  { nume: "Zegujani", comuna: "Floresti" },
];
