export const mm = [
  { nume: "Ardusat" },
  { nume: "Arduzel", comuna: "Ulmeni" },
  { nume: "Arieșu de Câmp", simplu: "Ariesu de Camp", comuna: "Ardusat" },
  { nume: "Arieșu de Pădure", simplu: "Ariesu de Padure", comuna: "Satulung" },
  { nume: "Ariniș", simplu: "Arinis" },
  { nume: "Aspra", comuna: "Vima Mica" },
  { nume: "Asuaju de Jos", comuna: "Asuaju De Sus" },
  { nume: "Asuaju de Sus" },
  { nume: "Baba", comuna: "Coroieni" },
  { nume: "Baia Mare" },
  { nume: "Baia Sprie" },
  { nume: "Băile Borșa", simplu: "Baile Borsa", comuna: "Borsa" },
  { nume: "Băița de Sub Codru", simplu: "Baita de Sub Codru" },
  { nume: "Băița", simplu: "Baita", comuna: "Tautii-Magheraus" },
  { nume: "Băiuț", simplu: "Baiut" },
  { nume: "Bârgău", simplu: "Bargau", comuna: "Cicarlau" },
  { nume: "Bârsana", simplu: "Barsana" },
  { nume: "Băsești", simplu: "Basesti" },
  { nume: "Berbești", simplu: "Berbesti", comuna: "Giulesti" },
  { nume: "Berchez", comuna: "Remetea Chioarului" },
  { nume: "Berchezoaia", comuna: "Remetea Chioarului" },
  { nume: "Berința", simplu: "Berinta", comuna: "Copalnic-Manastur" },
  { nume: "Bicaz" },
  { nume: "Bistra" },
  { nume: "Blidari", comuna: "Baia Mare" },
  { nume: "Bocicoel", comuna: "Bogdan Voda" },
  { nume: "Bocicoiu Mare" },
  { nume: "Bogdan Vodă", simplu: "Bogdan Voda" },
  { nume: "Boiereni", comuna: "Targu Lapus" },
  { nume: "Boiu Mare" },
  { nume: "Bontăieni", simplu: "Bontaieni", comuna: "Sisesti" },
  { nume: "Borcut", comuna: "Targu Lapus" },
  { nume: "Borșa", simplu: "Borsa" },
  { nume: "Botiza" },
  { nume: "Bozânta Mare", simplu: "Bozanta Mare", comuna: "Tautii-Magheraus" },
  { nume: "Bozânta Mică", simplu: "Bozanta Mica", comuna: "Recea" },
  { nume: "Breb", comuna: "Ocna Sugatag" },
  { nume: "Brebeni", comuna: "Cernesti" },
  { nume: "Buciumi", comuna: "Somcuta Mare" },
  { nume: "Budești", simplu: "Budesti" },
  { nume: "Bușag", simplu: "Busag", comuna: "Tautii-Magheraus" },
  { nume: "Buteasa", comuna: "Somcuta Mare" },
  { nume: "Buzești", simplu: "Buzesti", comuna: "Farcasa" },
  { nume: "Călinești", simplu: "Calinesti" },
  { nume: "Câmpulung la Tisa", simplu: "Campulung la Tisa" },
  { nume: "Cărbunari", simplu: "Carbunari", comuna: "Dumbravita" },
  { nume: "Cărpiniș", simplu: "Carpinis", comuna: "Copalnic-Manastur" },
  { nume: "Cătălina", simplu: "Catalina", comuna: "Sacalaseni" },
  { nume: "Cavnic" },
  { nume: "Cernești", simplu: "Cernesti" },
  { nume: "Cetățele", simplu: "Cetatele", comuna: "Sisesti" },
  { nume: "Chechiș", simplu: "Chechis", comuna: "Dumbravita" },
  { nume: "Chelința", simplu: "Chelinta", comuna: "Ulmeni" },
  { nume: "Chiuzbaia", comuna: "Baia Sprie" },
  { nume: "Cicârlău", simplu: "Cicarlau" },
  { nume: "Ciocotiș", simplu: "Ciocotis", comuna: "Cernesti" },
  { nume: "Ciolt", comuna: "Somcuta Mare" },
  { nume: "Ciuta", comuna: "Bicaz" },
  { nume: "Coaș", simplu: "Coas", comuna: "Sacalaseni" },
  { nume: "Codru Butesii", comuna: "Somcuta Mare" },
  { nume: "Coltău", simplu: "Coltau", comuna: "Sacalaseni" },
  { nume: "Colțirea", simplu: "Coltirea", comuna: "Ardusat" },
  { nume: "Copalnic-Deal", comuna: "Copalnic-Manastur" },
  { nume: "Copalnic-Mănăștur", simplu: "Copalnic-Manastur" },
  { nume: "Copalnic", comuna: "Copalnic-Manastur" },
  { nume: "Cornești", simplu: "Cornesti", comuna: "Calinesti" },
  { nume: "Corni", comuna: "Bicaz" },
  { nume: "Coroieni" },
  { nume: "Coruia", comuna: "Sacalaseni" },
  { nume: "Costeni", comuna: "Cupseni" },
  { nume: "Coștiui", simplu: "Costiui", comuna: "Rona De Sus" },
  { nume: "Crăciunești", simplu: "Craciunesti", comuna: "Bocicoiu Mare" },
  { nume: "Crasna Vișeului", simplu: "Crasna Viseului", comuna: "Bistra" },
  { nume: "Cufoaia", comuna: "Targu Lapus" },
  { nume: "Culcea", comuna: "Sacalaseni" },
  { nume: "Cupșeni", simplu: "Cupseni" },
  {
    nume: "Curtuiușu Mare",
    simplu: "Curtuiusu Mare",
    comuna: "Valea Chioarului",
  },
  {
    nume: "Curtuiușu Mic",
    simplu: "Curtuiusu Mic",
    comuna: "Copalnic-Manastur",
  },
  { nume: "Dămăcușeni", simplu: "Damacuseni", comuna: "Targu Lapus" },
  { nume: "Dănești", simplu: "Danesti", comuna: "Sisesti" },
  {
    nume: "Dăneștii Chioarului",
    simplu: "Danestii Chioarului",
    comuna: "Miresu Mare",
  },
  { nume: "Dealu Corbului", comuna: "Vima Mica" },
  { nume: "Dealu Mare", comuna: "Coroieni" },
  { nume: "Desești", simplu: "Desesti" },
  {
    nume: "Dobricu Lăpușului",
    simplu: "Dobricu Lapusului",
    comuna: "Targu Lapus",
  },
  { nume: "Drăghia", simplu: "Draghia", comuna: "Coroieni" },
  { nume: "Dragomirești", simplu: "Dragomiresti" },
  { nume: "Dumbrava", comuna: "Targu Lapus" },
  { nume: "Dumbrăvița", simplu: "Dumbravita" },
  { nume: "Durușa", simplu: "Durusa", comuna: "Valea Chioarului" },
  { nume: "Fânațe", simplu: "Fanate", comuna: "Cernesti" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Targu Lapus" },
  { nume: "Fărcașa", simplu: "Farcasa" },
  { nume: "Făurești", simplu: "Fauresti", comuna: "Copalnic-Manastur" },
  { nume: "Ferești", simplu: "Feresti", comuna: "Giulesti" },
  { nume: "Fericea", comuna: "Valea Chioarului" },
  { nume: "Fersig", comuna: "Satulung" },
  { nume: "Finteușu Mare", simplu: "Finteusu Mare", comuna: "Somcuta Mare" },
  { nume: "Finteușu Mic", simplu: "Finteusu Mic", comuna: "Satulung" },
  { nume: "Firiza", comuna: "Baia Mare" },
  {
    nume: "Frâncenii Boiului",
    simplu: "Francenii Boiului",
    comuna: "Boiu Mare",
  },
  { nume: "Gârdani", simplu: "Gardani", comuna: "Salsig" },
  { nume: "Giulești", simplu: "Giulesti" },
  { nume: "Glod", comuna: "Stramtura" },
  { nume: "Groape", comuna: "Targu Lapus" },
  { nume: "Groși", simplu: "Grosi" },
  { nume: "Groșii Țibleșului", simplu: "Grosii Tiblesului" },
  { nume: "Handalu Ilbei", comuna: "Cicarlau" },
  { nume: "Hărnicești", simplu: "Harnicesti", comuna: "Desesti" },
  { nume: "Hideaga", comuna: "Satulung" },
  { nume: "Hoteni", comuna: "Ocna Sugatag" },
  { nume: "Hovrila", comuna: "Somcuta Mare" },
  { nume: "Iadăra", simplu: "Iadara", comuna: "Miresu Mare" },
  { nume: "Iapa", comuna: "Sighetu Marmatiei" },
  { nume: "Ieud" },
  { nume: "Ilba", comuna: "Cicarlau" },
  { nume: "Inău", simplu: "Inau", comuna: "Targu Lapus" },
  { nume: "Întrerâuri", simplu: "Intrerauri", comuna: "Sacalaseni" },
  { nume: "Izvoarele", comuna: "Cernesti" },
  { nume: "Jugăstreni", simplu: "Jugastreni", comuna: "Vima Mica" },
  { nume: "Lăpuș", simplu: "Lapus" },
  { nume: "Lăpușel", simplu: "Lapusel", comuna: "Recea" },
  { nume: "Larga", comuna: "Suciu De Sus" },
  { nume: "Lăschia", simplu: "Laschia", comuna: "Copalnic-Manastur" },
  { nume: "Lazu Baciului", comuna: "Sighetu Marmatiei" },
  { nume: "Leordina" },
  { nume: "Libotin", comuna: "Cupseni" },
  { nume: "Lucăcești", simplu: "Lucacesti", comuna: "Miresu Mare" },
  { nume: "Lunca la Tisa", comuna: "Bocicoiu Mare" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Cernesti" },
  { nume: "Mănăstirea", simplu: "Manastirea", comuna: "Giulesti" },
  { nume: "Mânău", simplu: "Manau", comuna: "Ulmeni" },
  { nume: "Mara", comuna: "Desesti" },
  { nume: "Merișor", simplu: "Merisor", comuna: "Tautii-Magheraus" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Valea Chioarului" },
  { nume: "Mireșu Mare", simplu: "Miresu Mare" },
  { nume: "Mocira", comuna: "Recea" },
  { nume: "Mogoșești", simplu: "Mogosesti", comuna: "Satulung" },
  { nume: "Moisei" },
  { nume: "Nănești", simplu: "Nanesti", comuna: "Barsana" },
  { nume: "Negreia", comuna: "Sisesti" },
  { nume: "Nistru", comuna: "Tautii-Magheraus" },
  { nume: "Oarța de Jos", simplu: "Oarta de Jos" },
  { nume: "Oarța de Sus", simplu: "Oarta de Sus", comuna: "Oarta De Jos" },
  { nume: "Ocna Șugatag", simplu: "Ocna Sugatag" },
  { nume: "Ocoliș", simplu: "Ocolis", comuna: "Grosi" },
  { nume: "Odești", simplu: "Odesti", comuna: "Basesti" },
  { nume: "Oncești", simplu: "Oncesti", comuna: "Barsana" },
  { nume: "Orțița", simplu: "Ortita", comuna: "Oarta De Jos" },
  { nume: "Peteritea", comuna: "Vima Mica" },
  { nume: "Petrova" },
  { nume: "Piatra", comuna: "Remeti" },
  { nume: "Plopiș", simplu: "Plopis", comuna: "Sisesti" },
  { nume: "Poiana Botizii", comuna: "Baiut" },
  { nume: "Poienile de Sub Munte" },
  { nume: "Poienile Izei" },
  { nume: "Posta", comuna: "Remetea Chioarului" },
  { nume: "Preluca Nouă", simplu: "Preluca Noua", comuna: "Copalnic-Manastur" },
  { nume: "Preluca Veche", comuna: "Copalnic-Manastur" },
  { nume: "Pribilești", simplu: "Pribilesti", comuna: "Satulung" },
  { nume: "Prislop", comuna: "Boiu Mare" },
  { nume: "Răzoare", simplu: "Razoare", comuna: "Targu Lapus" },
  { nume: "Recea" },
  { nume: "Remecioara", comuna: "Remetea Chioarului" },
  { nume: "Remetea Chioarului" },
  { nume: "Remeți pe Someș", simplu: "Remeti pe Somes", comuna: "Miresu Mare" },
  { nume: "Remeți", simplu: "Remeti" },
  { nume: "Repedea" },
  { nume: "Rodina", comuna: "Arinis" },
  { nume: "Rogoz", comuna: "Targu Lapus" },
  { nume: "Rohia", comuna: "Targu Lapus" },
  { nume: "Romănești", simplu: "Romanesti", comuna: "Boiu Mare" },
  { nume: "Rona de Jos" },
  { nume: "Rona de Sus" },
  { nume: "Rozavlea" },
  { nume: "Rus", comuna: "Dumbravita" },
  { nume: "Ruscova" },
  { nume: "Rușor", simplu: "Rusor", comuna: "Copalnic-Manastur" },
  { nume: "Săbișa", simplu: "Sabisa", comuna: "Seini" },
  { nume: "Săcălășeni", simplu: "Sacalaseni" },
  { nume: "Săcel", simplu: "Sacel" },
  { nume: "Săliște", simplu: "Saliste", comuna: "Basesti" },
  { nume: "Săliștea de Sus", simplu: "Salistea de Sus" },
  { nume: "Sălnița", simplu: "Salnita", comuna: "Vima Mica" },
  { nume: "Sălsig", simplu: "Salsig" },
  { nume: "Salta", comuna: "Rozavlea" },
  { nume: "Săpânța", simplu: "Sapanta" },
  { nume: "Sarasău", simplu: "Sarasau" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Budesti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Farcasa" },
  { nume: "Săsar", simplu: "Sasar", comuna: "Recea" },
  { nume: "Sat-Șugatag", simplu: "Sat-Sugatag", comuna: "Ocna Sugatag" },
  { nume: "Satu Nou de Jos", comuna: "Grosi" },
  { nume: "Satu Nou de Sus", comuna: "Baia Sprie" },
  { nume: "Satulung" },
  { nume: "Seini" },
  { nume: "Șieu", simplu: "Sieu" },
  { nume: "Sighetu Marmației", simplu: "Sighetu Marmatiei" },
  { nume: "Șindrești", simplu: "Sindresti", comuna: "Dumbravita" },
  { nume: "Șisești", simplu: "Sisesti" },
  { nume: "Slătioara", simplu: "Slatioara", comuna: "Stramtura" },
  { nume: "Șomcuța Mare", simplu: "Somcuta Mare" },
  { nume: "Someș-Uileac", simplu: "Somes-Uileac", comuna: "Ulmeni" },
  { nume: "Stejera", comuna: "Miresu Mare" },
  { nume: "Stoiceni", comuna: "Targu Lapus" },
  { nume: "Strâmbu-Băiuț", simplu: "Strambu-Baiut", comuna: "Baiut" },
  { nume: "Strâmtura", simplu: "Stramtura" },
  { nume: "Stremț", simplu: "Stremt", comuna: "Basesti" },
  { nume: "Suciu de Jos", comuna: "Suciu De Sus" },
  { nume: "Suciu de Sus" },
  { nume: "Șugău", simplu: "Sugau", comuna: "Sighetu Marmatiei" },
  { nume: "Șurdești", simplu: "Surdesti", comuna: "Sisesti" },
  { nume: "Tămaia", simplu: "Tamaia", comuna: "Farcasa" },
  { nume: "Tămășești", simplu: "Tamasesti", comuna: "Arinis" },
  { nume: "Târgu Lăpuș", simplu: "Targu Lapus" },
  { nume: "Tăuții de Sus", simplu: "Tautii de Sus", comuna: "Baia Sprie" },
  { nume: "Tăuții-Măgherăuș", simplu: "Tautii-Magheraus" },
  { nume: "Teceu Mic", comuna: "Remeti" },
  { nume: "Țicău", simplu: "Ticau", comuna: "Ulmeni" },
  { nume: "Tisa", comuna: "Bocicoiu Mare" },
  { nume: "Tohat", comuna: "Ulmeni" },
  { nume: "Trestia", comuna: "Cernesti" },
  { nume: "Tulghieș", simplu: "Tulghies", comuna: "Miresu Mare" },
  { nume: "Ulmeni" },
  { nume: "Ulmoasa", comuna: "Tautii-Magheraus" },
  { nume: "Unguraș", simplu: "Unguras", comuna: "Dumbravita" },
  { nume: "Ungureni", comuna: "Cupseni" },
  { nume: "Urmeniș", simplu: "Urmenis", comuna: "Baita De Sub Codru" },
  { nume: "Vad", comuna: "Copalnic-Manastur" },
  { nume: "Vadu Izei" },
  { nume: "Valea Chioarului" },
  {
    nume: "Valea Cufundoasă",
    simplu: "Valea Cufundoasa",
    comuna: "Sighetu Marmatiei",
  },
  { nume: "Valea Hotarului", comuna: "Sighetu Marmatiei" },
  { nume: "Valea Neagră", simplu: "Valea Neagra", comuna: "Baia Mare" },
  { nume: "Valea Stejarului", comuna: "Vadu Izei" },
  { nume: "Valea Vișeului", simplu: "Valea Viseului", comuna: "Bistra" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Calinesti" },
  {
    nume: "Vălenii Lăpușului",
    simplu: "Valenii Lapusului",
    comuna: "Coroieni",
  },
  {
    nume: "Vălenii Șomcutei",
    simplu: "Valenii Somcutei",
    comuna: "Somcuta Mare",
  },
  { nume: "Vărai", simplu: "Varai", comuna: "Valea Chioarului" },
  { nume: "Vicea", comuna: "Ulmeni" },
  { nume: "Viile Apei", comuna: "Seini" },
  { nume: "Vima Mare", comuna: "Vima Mica" },
  { nume: "Vima Mică", simplu: "Vima Mica" },
  { nume: "Vișeu de Jos", simplu: "Viseu de Jos" },
  {
    nume: "Vișeu de Mijloc",
    simplu: "Viseu de Mijloc",
    comuna: "Viseu De Sus",
  },
  { nume: "Vișeu de Sus", simplu: "Viseu de Sus" },
];
