export const mh = [
  { nume: "23 August", comuna: "Malovat" },
  { nume: "Adunaţii Teiului", simplu: "Adunatii Teiului", comuna: "Tamna" },
  { nume: "Albuleşti", simplu: "Albulesti", comuna: "Dumbrava" },
  { nume: "Almăjel", simplu: "Almajel", comuna: "Vladaia" },
  { nume: "Alunişul", simplu: "Alunisul", comuna: "Husnicioara" },
  { nume: "Argineşti", simplu: "Arginesti", comuna: "Butoiesti" },
  { nume: "Arvăteşti", simplu: "Arvatesti", comuna: "Prunisor" },
  { nume: "Aurora", comuna: "Cujmir" },
  { nume: "Bâcleş", simplu: "Bacles" },
  { nume: "Bădiţeşti", simplu: "Baditesti", comuna: "Husnicioara" },
  { nume: "Bahna", comuna: "Ilovita" },
  { nume: "Baia de Aramă", simplu: "Baia de Arama" },
  { nume: "Baia Nouă", simplu: "Baia Noua", comuna: "Dubova" },
  { nume: "Bala de Sus", comuna: "Bala" },
  { nume: "Bala" },
  { nume: "Bălăciţa", simplu: "Balacita" },
  { nume: "Balota", comuna: "Prunisor" },
  { nume: "Baloteşti", simplu: "Balotesti", comuna: "Izvoru Barzii" },
  { nume: "Balta Verde", comuna: "Gogosu" },
  { nume: "Balta" },
  { nume: "Bâltanele", simplu: "Baltanele", comuna: "Greci" },
  { nume: "Bâltanele", simplu: "Baltanele", comuna: "Prunisor" },
  { nume: "Băluţa", simplu: "Baluta", comuna: "Ponoarele" },
  { nume: "Bâlvăneşti", simplu: "Balvanesti" },
  {
    nume: "Bâlvăneştii de Jos",
    simplu: "Balvanestii de Jos",
    comuna: "Balvanesti",
  },
  { nume: "Bârâiacu", simplu: "Baraiacu", comuna: "Ponoarele" },
  { nume: "Bârda", simplu: "Barda", comuna: "Malovat" },
  { nume: "Bârlogeni", simplu: "Barlogeni", comuna: "Stangaceaua" },
  { nume: "Batoţi", simplu: "Batoti", comuna: "Devesel" },
  { nume: "Biban", comuna: "Padina" },
  { nume: "Bistreţu", simplu: "Bistretu", comuna: "Devesel" },
  { nume: "Bistriţa", simplu: "Bistrita", comuna: "Hinova" },
  { nume: "Blidaru", comuna: "Greci" },
  { nume: "Bobaiţa", simplu: "Bobaita", comuna: "Malovat" },
  { nume: "Boceni", comuna: "Tamna" },
  { nume: "Borogea", comuna: "Husnicioara" },
  { nume: "Brâgleasa", simplu: "Bragleasa", comuna: "Dumbrava" },
  { nume: "Braniştea", simplu: "Branistea", comuna: "Vanatori" },
  { nume: "Brânzeni", simplu: "Branzeni", comuna: "Ponoarele" },
  { nume: "Brateşul", simplu: "Bratesul", comuna: "Bala" },
  { nume: "Bratilovu", comuna: "Baia De Arama" },
  { nume: "Brativoeşti", simplu: "Brativoesti", comuna: "Bala" },
  { nume: "Brebina", comuna: "Baia De Arama" },
  { nume: "Breţa", simplu: "Breta", comuna: "Corcova" },
  { nume: "Breznicioara", comuna: "Stangaceaua" },
  { nume: "Brezniţa-Motru", simplu: "Breznita-Motru" },
  { nume: "Brezniţa-Ocol", simplu: "Breznita-Ocol" },
  { nume: "Broşteni", simplu: "Brosteni" },
  { nume: "Bucura", comuna: "Vanju Mare" },
  { nume: "Budăneşti", simplu: "Budanesti", comuna: "Ilovat" },
  { nume: "Buicani", comuna: "Ponoarele" },
  { nume: "Buiceşti", simplu: "Buicesti", comuna: "Butoiesti" },
  { nume: "Bunoaica", comuna: "Ciresu" },
  { nume: "Burila Mare" },
  { nume: "Burila Mică", simplu: "Burila Mica", comuna: "Gogosu" },
  { nume: "Buseşti", simplu: "Busesti", comuna: "Isverna" },
  { nume: "Butoieşti", simplu: "Butoiesti" },
  {
    nume: "Călineştii de Jos",
    simplu: "Calinestii de Jos",
    comuna: "Balvanesti",
  },
  {
    nume: "Călineştii de Sus",
    simplu: "Calinestii de Sus",
    comuna: "Balvanesti",
  },
  { nume: "Câmpu Mare", simplu: "Campu Mare", comuna: "Bala" },
  { nume: "Căpăţâneşti", simplu: "Capatanesti", comuna: "Brosteni" },
  { nume: "Cărămidaru", simplu: "Caramidaru", comuna: "Sisesti" },
  { nume: "Cârceni", simplu: "Carceni", comuna: "Grozesti" },
  { nume: "Cârjei", simplu: "Carjei", comuna: "Hinova" },
  { nume: "Cârşu", simplu: "Carsu", comuna: "Bala" },
  { nume: "Căzăneşti", simplu: "Cazanesti" },
  { nume: "Cearângu", simplu: "Cearangu", comuna: "Punghina" },
  { nume: "Celnata", comuna: "Husnicioara" },
  { nume: "Ceptureni", comuna: "Ponoarele" },
  { nume: "Cerânganul", simplu: "Ceranganul", comuna: "Stangaceaua" },
  { nume: "Cerna-Vârf", simplu: "Cerna-Varf", comuna: "Isverna" },
  { nume: "Cernaia", comuna: "Corcova" },
  { nume: "Cerneţi", simplu: "Cerneti", comuna: "Simian" },
  { nume: "Cerveniţa", simplu: "Cervenita", comuna: "Prunisor" },
  { nume: "Ciochiuţa", simplu: "Ciochiuta", comuna: "Strehaia" },
  { nume: "Cioroboreni", comuna: "Jiana" },
  { nume: "Ciovârnăşani", simplu: "Ciovarnasani", comuna: "Sisesti" },
  { nume: "Cireşu", simplu: "Ciresu" },
  { nume: "Coada Cornetului", comuna: "Balta" },
  { nume: "Cocorova", comuna: "Sisesti" },
  { nume: "Colareţ", simplu: "Colaret", comuna: "Tamna" },
  { nume: "Colibaşi", simplu: "Colibasi", comuna: "Malovat" },
  { nume: "Comanda", comuna: "Strehaia" },
  { nume: "Comăneşti", simplu: "Comanesti", comuna: "Bala" },
  { nume: "Copăcioasa", simplu: "Copacioasa", comuna: "Floresti" },
  { nume: "Corcova" },
  { nume: "Cordun", comuna: "Corcova" },
  { nume: "Corlăţel", simplu: "Corlatel" },
  { nume: "Corzu", comuna: "Bacles" },
  { nume: "Cosovăţ", simplu: "Cosovat", comuna: "Breznita-Motru" },
  { nume: "Costeşti", simplu: "Costesti", comuna: "Balta" },
  { nume: "Cotoroaia", comuna: "Voloiac" },
  { nume: "Cozia", comuna: "Pristol" },
  { nume: "Cracu Lung", comuna: "Ilovat" },
  { nume: "Cracu Muntelui", comuna: "Ponoarele" },
  { nume: "Crăgueşti", simplu: "Craguesti", comuna: "Sisesti" },
  { nume: "Crainici", comuna: "Bala" },
  { nume: "Cremenea", comuna: "Tamna" },
  { nume: "Crivina", comuna: "Burila Mare" },
  { nume: "Croica", comuna: "Corcova" },
  { nume: "Cujmir" },
  { nume: "Cujmiru Mic", comuna: "Cujmir" },
  { nume: "Dâlbociţa", simplu: "Dalbocita", comuna: "Ilovat" },
  { nume: "Dâlma", simplu: "Dalma", comuna: "Bala" },
  { nume: "Dănceu", simplu: "Danceu", comuna: "Jiana" },
  { nume: "Dârvari", simplu: "Darvari" },
  { nume: "Dealu Mare", comuna: "Baia De Arama" },
  { nume: "Dedoviţa Nouă", simplu: "Dedovita Noua", comuna: "Simian" },
  { nume: "Dedoviţa Veche", simplu: "Dedovita Veche", comuna: "Simian" },
  { nume: "Deleni", comuna: "Breznita-Motru" },
  { nume: "Delureni", comuna: "Ponoarele" },
  { nume: "Devesel" },
  { nume: "Dobra", comuna: "Balacita" },
  { nume: "Drăgheşti", simplu: "Draghesti", comuna: "Isverna" },
  { nume: "Dragoteşti", simplu: "Dragotesti", comuna: "Prunisor" },
  { nume: "Drincea", comuna: "Punghina" },
  { nume: "Drobeta-Turnu Severin" },
  { nume: "Dubova" },
  {
    nume: "Dudaşu Schelei",
    simplu: "Dudasu Schelei",
    comuna: "Drobeta-Turnu Severin",
  },
  { nume: "Dudaşu", simplu: "Dudasu", comuna: "Simian" },
  { nume: "Dumbrava de Jos", comuna: "Dumbrava" },
  { nume: "Dumbrava de Mijloc", comuna: "Dumbrava" },
  { nume: "Dumbrava de Sus", comuna: "Dumbrava" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita", comuna: "Husnicioara" },
  { nume: "Dunărea Mică", simplu: "Dunarea Mica", comuna: "Devesel" },
  { nume: "Eibenthal", comuna: "Dubova" },
  { nume: "Ercea", comuna: "Cazanesti" },
  { nume: "Ergheviţa", simplu: "Erghevita", comuna: "Simian" },
  { nume: "Eşelniţa", simplu: "Eselnita" },
  {
    nume: "Fântâna Domnească",
    simplu: "Fantana Domneasca",
    comuna: "Prunisor",
  },
  {
    nume: "Fântânile Negre",
    simplu: "Fantanile Negre",
    comuna: "Poroina Mare",
  },
  { nume: "Faţa Cremenii", simplu: "Fata Cremenii", comuna: "Tamna" },
  { nume: "Faţa Motrului", simplu: "Fata Motrului", comuna: "Stangaceaua" },
  { nume: "Făuroaia", simplu: "Fauroaia", comuna: "Breznita-Motru" },
  { nume: "Firizu", comuna: "Ilovat" },
  { nume: "Floreşti", simplu: "Floresti" },
  { nume: "Gârbovăţu de Jos", simplu: "Garbovatu de Jos", comuna: "Corcova" },
  { nume: "Gârbovăţu de Sus", simplu: "Garbovatu de Sus", comuna: "Cazanesti" },
  { nume: "Gărdăneasa", simplu: "Gardaneasa", comuna: "Ponoarele" },
  { nume: "Gârdoaia", simplu: "Gardoaia", comuna: "Floresti" },
  { nume: "Gârla Mare", simplu: "Garla Mare" },
  { nume: "Gârniţa", simplu: "Garnita", comuna: "Prunisor" },
  { nume: "Gemeni", comuna: "Darvari" },
  { nume: "Ghelmegioaia", comuna: "Prunisor" },
  { nume: "Gheorgheşti", simplu: "Gheorghesti", comuna: "Ponoarele" },
  { nume: "Giura", comuna: "Bacles" },
  { nume: "Giurgiani", comuna: "Isverna" },
  { nume: "Goanţa", simplu: "Goanta", comuna: "Vanatori" },
  { nume: "Godeanu" },
  { nume: "Godeanu", comuna: "Obarsia-Closani" },
  { nume: "Gogoşu", simplu: "Gogosu" },
  { nume: "Golineasa", comuna: "Dumbrava" },
  { nume: "Gornenţi", simplu: "Gornenti", comuna: "Podeni" },
  { nume: "Gornoviţa", simplu: "Gornovita", comuna: "Balta" },
  { nume: "Govodarva", comuna: "Cazanesti" },
  { nume: "Greci" },
  { nume: "Grozeşti", simplu: "Grozesti" },
  { nume: "Gruia" },
  { nume: "Gura Motrului", comuna: "Butoiesti" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Drobeta-Turnu Severin" },
  { nume: "Gutu", comuna: "Prunisor" },
  { nume: "Gvardiniţa", simplu: "Gvardinita", comuna: "Balacita" },
  { nume: "Halânga", simplu: "Halanga", comuna: "Izvoru Barzii" },
  { nume: "Higiu", comuna: "Dumbrava" },
  { nume: "Hinova" },
  { nume: "Hotărani", simplu: "Hotarani", comuna: "Vanjulet" },
  { nume: "Hurduceşti", simplu: "Hurducesti", comuna: "Strehaia" },
  { nume: "Husnicioara" },
  { nume: "Iablaniţa", simplu: "Iablanita", comuna: "Padina" },
  { nume: "Igiroasa", comuna: "Prunisor" },
  { nume: "Ilovăţ", simplu: "Ilovat" },
  { nume: "Iloviţa", simplu: "Ilovita" },
  { nume: "Ilovu", comuna: "Cazanesti" },
  { nume: "Imoasa", comuna: "Corcova" },
  { nume: "Isverna" },
  { nume: "Iupca", comuna: "Bala" },
  { nume: "Izimşa", simplu: "Izimsa", comuna: "Obarsia De Camp" },
  { nume: "Izvoarele", comuna: "Gruia" },
  { nume: "Izvorălu de Jos", simplu: "Izvoralu de Jos", comuna: "Livezile" },
  { nume: "Izvorălu", simplu: "Izvoralu", comuna: "Tamna" },
  { nume: "Izvoru Aneştilor", simplu: "Izvoru Anestilor", comuna: "Livezile" },
  { nume: "Izvoru Bârzii", simplu: "Izvoru Barzii" },
  { nume: "Izvoru Frumos", comuna: "Burila Mare" },
  { nume: "Jiana Mare", comuna: "Jiana" },
  { nume: "Jiana Veche", comuna: "Jiana" },
  { nume: "Jiana" },
  { nume: "Jidoştiţa", simplu: "Jidostita", comuna: "Breznita-Ocol" },
  { nume: "Jigniţa", simplu: "Jignita", comuna: "Cazanesti" },
  { nume: "Jirov", comuna: "Corcova" },
  { nume: "Jugastru", comuna: "Butoiesti" },
  { nume: "Jupâneşti", simplu: "Jupanesti", comuna: "Ciresu" },
  { nume: "Lac", comuna: "Voloiac" },
  { nume: "Lazu", comuna: "Malovat" },
  { nume: "Livezi", comuna: "Floresti" },
  { nume: "Livezile" },
  { nume: "Ludu", comuna: "Ponoarele" },
  { nume: "Lumnic", comuna: "Prunisor" },
  { nume: "Lunca Banului", comuna: "Strehaia" },
  { nume: "Luncşoara", simplu: "Luncsoara", comuna: "Brosteni" },
  { nume: "Lupşa de Jos", simplu: "Lupsa de Jos", comuna: "Brosteni" },
  { nume: "Lupşa de Sus", simplu: "Lupsa de Sus", comuna: "Brosteni" },
  { nume: "Magheru", comuna: "Breznita-Ocol" },
  { nume: "Măgurele", simplu: "Magurele", comuna: "Punghina" },
  { nume: "Mălărişca", simplu: "Malarisca", comuna: "Podeni" },
  { nume: "Malovăţ", simplu: "Malovat" },
  { nume: "Manu", comuna: "Tamna" },
  { nume: "Mărăşeşti", simplu: "Marasesti", comuna: "Baia De Arama" },
  { nume: "Marga", comuna: "Godeanu" },
  { nume: "Marmanu", comuna: "Husnicioara" },
  { nume: "Măru Roşu", simplu: "Maru Rosu", comuna: "Corcova" },
  { nume: "Menţi", simplu: "Menti", comuna: "Strehaia" },
  { nume: "Meriş", simplu: "Meris", comuna: "Brosteni" },
  { nume: "Mijarca", comuna: "Prunisor" },
  { nume: "Moiseşti", simplu: "Moisesti", comuna: "Ilovita" },
  { nume: "Molani", comuna: "Bala" },
  { nume: "Moşneni", simplu: "Mosneni", comuna: "Floresti" },
  { nume: "Motruleni", comuna: "Strehaia" },
  { nume: "Nadanova", comuna: "Isverna" },
  { nume: "Negoeşti", simplu: "Negoesti", comuna: "Baia De Arama" },
  { nume: "Negreşti", simplu: "Negresti", comuna: "Malovat" },
  { nume: "Negruşa", simplu: "Negrusa", comuna: "Ciresu" },
  { nume: "Nevăţu", simplu: "Nevatu", comuna: "Balta" },
  {
    nume: "Nicolae Bălcescu",
    simplu: "Nicolae Balcescu",
    comuna: "Vanju Mare",
  },
  { nume: "Noapteşa", simplu: "Noaptesa", comuna: "Sisesti" },
  { nume: "Obârşia de Câmp", simplu: "Obarsia de Camp" },
  { nume: "Obârşia-Cloşani", simplu: "Obarsia-Closani" },
  { nume: "Ohaba", comuna: "Sovarna" },
  { nume: "Olteanca", comuna: "Padina" },
  { nume: "Oprăneşti", simplu: "Opranesti", comuna: "Husnicioara" },
  { nume: "Oprişor", simplu: "Oprisor" },
  { nume: "Oreviţa Mare", simplu: "Orevita Mare", comuna: "Vanju Mare" },
  { nume: "Orşova", simplu: "Orsova" },
  { nume: "Ostrovu Corbului", comuna: "Hinova" },
  { nume: "Ostrovu Mare", comuna: "Gogosu" },
  { nume: "Pădina Mare", simplu: "Padina Mare", comuna: "Padina" },
  { nume: "Pădina Mică", simplu: "Padina Mica", comuna: "Padina" },
  { nume: "Păltinişu", simplu: "Paltinisu", comuna: "Cazanesti" },
  { nume: "Pârlagele", simplu: "Parlagele", comuna: "Balvanesti" },
  { nume: "Pârvuleşti", simplu: "Parvulesti", comuna: "Corcova" },
  { nume: "Păsărani", simplu: "Pasarani", comuna: "Grozesti" },
  { nume: "Pătulele", simplu: "Patulele" },
  { nume: "Păuneşti", simplu: "Paunesti", comuna: "Godeanu" },
  { nume: "Pavăţ", simplu: "Pavat", comuna: "Tamna" },
  { nume: "Peri", comuna: "Husnicioara" },
  { nume: "Peşteana", simplu: "Pesteana", comuna: "Floresti" },
  { nume: "Peştenuţa", simplu: "Pestenuta", comuna: "Floresti" },
  { nume: "Petra", comuna: "Bacles" },
  { nume: "Petriş", simplu: "Petris", comuna: "Livezile" },
  { nume: "Pistriţa", simplu: "Pistrita", comuna: "Baia De Arama" },
  { nume: "Plai", comuna: "Breznita-Motru" },
  { nume: "Plopi", comuna: "Tamna" },
  { nume: "Pluta", comuna: "Butoiesti" },
  { nume: "Podeni" },
  { nume: "Podu Grosului", comuna: "Bacles" },
  { nume: "Poiana Gruii", comuna: "Gruia" },
  { nume: "Poiana", comuna: "Cazanesti" },
  { nume: "Ponoarele" },
  { nume: "Poroina Mare" },
  { nume: "Poroina", comuna: "Simian" },
  { nume: "Poroiniţa", simplu: "Poroinita", comuna: "Rogova" },
  { nume: "Poşta Veche", simplu: "Posta Veche", comuna: "Stangaceaua" },
  { nume: "Prejna", comuna: "Balta" },
  { nume: "Priboieşti", simplu: "Priboiesti", comuna: "Husnicioara" },
  { nume: "Prisăceaua", simplu: "Prisaceaua", comuna: "Oprisor" },
  { nume: "Pristol" },
  { nume: "Proiteşti", simplu: "Proitesti", comuna: "Ponoarele" },
  { nume: "Prunaru", comuna: "Prunisor" },
  { nume: "Prunişor", simplu: "Prunisor" },
  { nume: "Punghina" },
  { nume: "Puşcaşu", simplu: "Puscasu", comuna: "Corcova" },
  { nume: "Puţinei", simplu: "Putinei", comuna: "Izvoru Barzii" },
  { nume: "Racova", comuna: "Ilovat" },
  { nume: "Răduţeşti", simplu: "Radutesti", comuna: "Butoiesti" },
  { nume: "Răiculeşti", simplu: "Raiculesti", comuna: "Ponoarele" },
  { nume: "Răscoleşti", simplu: "Rascolesti", comuna: "Izvoru Barzii" },
  { nume: "Recea", comuna: "Punghina" },
  { nume: "Rocşoreni", simplu: "Rocsoreni", comuna: "Dumbrava" },
  { nume: "Rogova" },
  { nume: "Roşia", simplu: "Rosia", comuna: "Cazanesti" },
  { nume: "Roşiori", simplu: "Rosiori", comuna: "Vanatori" },
  { nume: "Rudina", comuna: "Bala" },
  { nume: "Runcuşoru", simplu: "Runcusoru", comuna: "Bala" },
  { nume: "Ruptura", comuna: "Voloiac" },
  { nume: "Sălătruc", simplu: "Salatruc", comuna: "Greci" },
  { nume: "Salcia" },
  { nume: "Sărdăneşti", simplu: "Sardanesti", comuna: "Bala" },
  { nume: "Satu Mare", comuna: "Stangaceaua" },
  { nume: "Satu Nou", comuna: "Punghina" },
  { nume: "Scăpău", simplu: "Scapau", comuna: "Devesel" },
  { nume: "Schela Cladovei", comuna: "Drobeta-Turnu Severin" },
  { nume: "Schinteieşti", simplu: "Schinteiesti", comuna: "Izvoru Barzii" },
  {
    nume: "Schitu Topolniţei",
    simplu: "Schitu Topolnitei",
    comuna: "Izvoru Barzii",
  },
  { nume: "Scorila", comuna: "Vladaia" },
  { nume: "Seliştea", simplu: "Selistea", comuna: "Isverna" },
  { nume: "Selişteni", simplu: "Selisteni", comuna: "Husnicioara" },
  { nume: "Seliştiuţa", simplu: "Selistiuta", comuna: "Bacles" },
  { nume: "Severineşti", simplu: "Severinesti", comuna: "Cazanesti" },
  { nume: "Sfodea", comuna: "Balta" },
  { nume: "Şimian", simplu: "Simian" },
  { nume: "Şipotu", simplu: "Sipotu", comuna: "Ponoarele" },
  { nume: "Şipotu", simplu: "Sipotu", comuna: "Poroina Mare" },
  { nume: "Şiroca", simplu: "Siroca", comuna: "Godeanu" },
  { nume: "Şişeşti", simplu: "Sisesti" },
  { nume: "Slaşoma", simplu: "Slasoma", comuna: "Padina" },
  { nume: "Slătinicu Mare", simplu: "Slatinicu Mare", comuna: "Strehaia" },
  { nume: "Slătinicu Mic", simplu: "Slatinicu Mic", comuna: "Strehaia" },
  { nume: "Smadoviţa", simplu: "Smadovita", comuna: "Bacles" },
  { nume: "Şovarna", simplu: "Sovarna" },
  { nume: "Sperleşti", simplu: "Sperlesti", comuna: "Voloiac" },
  { nume: "Stănceşti", simplu: "Stancesti", comuna: "Strehaia" },
  { nume: "Stăneşti", simplu: "Stanesti", comuna: "Baia De Arama" },
  { nume: "Stângăceaua", simplu: "Stangaceaua" },
  { nume: "Ştefan Odobleja", simplu: "Stefan Odobleja", comuna: "Livezile" },
  { nume: "Stejaru", comuna: "Corcova" },
  { nume: "Stigniţa", simplu: "Stignita", comuna: "Poroina Mare" },
  { nume: "Ştircoviţa", simplu: "Stircovita", comuna: "Vladaia" },
  { nume: "Strehaia" },
  { nume: "Stroeşti", simplu: "Stroesti", comuna: "Floresti" },
  { nume: "Studina", comuna: "Sovarna" },
  { nume: "Suharu", comuna: "Cazanesti" },
  { nume: "Şuşiţa", simplu: "Susita", comuna: "Breznita-Ocol" },
  { nume: "Şuşiţa", simplu: "Susita", comuna: "Grozesti" },
  { nume: "Sviniţa", simplu: "Svinita" },
  { nume: "Tălăpanu", simplu: "Talapanu", comuna: "Breznita-Motru" },
  { nume: "Tâmna", simplu: "Tamna" },
  { nume: "Tânţaru", simplu: "Tantaru", comuna: "Butoiesti" },
  { nume: "Târsa", simplu: "Tarsa", comuna: "Stangaceaua" },
  { nume: "Ţigănaşi", simplu: "Tiganasi", comuna: "Burila Mare" },
  { nume: "Tismana", comuna: "Devesel" },
  { nume: "Titerleşti", simplu: "Titerlesti", comuna: "Baia De Arama" },
  { nume: "Ţiţirigi", simplu: "Titirigi", comuna: "Voloiac" },
  { nume: "Traian", comuna: "Vanju Mare" },
  { nume: "Turtaba", comuna: "Isverna" },
  { nume: "Valea Anilor", comuna: "Corlatel" },
  { nume: "Valea Bună", simplu: "Valea Buna", comuna: "Voloiac" },
  { nume: "Valea Copcii", comuna: "Simian" },
  { nume: "Valea Coşuştei", simplu: "Valea Cosustei", comuna: "Cazanesti" },
  { nume: "Valea Marcului", comuna: "Dumbrava" },
  { nume: "Valea Petrii", comuna: "Greci" },
  { nume: "Valea Teiului", comuna: "Breznita-Motru" },
  { nume: "Valea Ursului", comuna: "Ponoarele" },
  { nume: "Valea Ursului", comuna: "Tamna" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Vânju Mare", simplu: "Vanju Mare" },
  { nume: "Vânjuleţ", simplu: "Vanjulet" },
  { nume: "Varodia", comuna: "Dumbrava" },
  { nume: "Viaşu", simplu: "Viasu", comuna: "Patulele" },
  { nume: "Vidimireşti", simplu: "Vidimiresti", comuna: "Bala" },
  { nume: "Vişina", simplu: "Visina", comuna: "Greci" },
  { nume: "Vlădaia", simplu: "Vladaia" },
  { nume: "Vlădăşeşti", simplu: "Vladasesti", comuna: "Corcova" },
  { nume: "Vlădica", simplu: "Vladica", comuna: "Dumbrava" },
  { nume: "Voloiac" },
  { nume: "Voloicel", comuna: "Voloiac" },
  { nume: "Vrancea", comuna: "Burila Mare" },
  { nume: "Vrata", comuna: "Garla Mare" },
  { nume: "Zegaia", comuna: "Prunisor" },
  { nume: "Zegujani", comuna: "Floresti" },
];
