export const nt = [
  { nume: "Adjudeni", comuna: "Tamaseni" },
  { nume: "Agapia" },
  { nume: "Agârcia", simplu: "Agarcia", comuna: "Alexandru Cel Bun" },
  { nume: "Almaș", simplu: "Almas", comuna: "Garcina" },
  { nume: "Arămești", simplu: "Aramesti", comuna: "Bahna" },
  { nume: "Arămoaia", simplu: "Aramoaia", comuna: "Tupilati" },
  { nume: "Ardeluța", simplu: "Ardeluta", comuna: "Tarcau" },
  { nume: "Averești", simplu: "Averesti", comuna: "Ion Creanga" },
  { nume: "Bahna Mare", comuna: "Bargauani" },
  { nume: "Bahna" },
  { nume: "Băhnișoara", simplu: "Bahnisoara", comuna: "Bahna" },
  { nume: "Bălănești", simplu: "Balanesti", comuna: "Bargauani" },
  { nume: "Bălțătești", simplu: "Baltatesti" },
  { nume: "Bălușești", simplu: "Balusesti", comuna: "Dochia" },
  { nume: "Bălușești", simplu: "Balusesti", comuna: "Icusesti" },
  { nume: "Băneasa", simplu: "Baneasa", comuna: "Bozieni" },
  { nume: "Baratca", comuna: "Bargauani" },
  { nume: "Bărcănești", simplu: "Barcanesti", comuna: "Candesti" },
  { nume: "Bârgauani", simplu: "Bargauani" },
  { nume: "Bârjoveni", simplu: "Barjoveni", comuna: "Secuieni" },
  { nume: "Bârnadu", simplu: "Barnadu", comuna: "Bicaz-Chei" },
  { nume: "Barticești", simplu: "Barticesti", comuna: "Botesti" },
  { nume: "Bașta", simplu: "Basta", comuna: "Secuieni" },
  { nume: "Bătrânești", simplu: "Batranesti", comuna: "Icusesti" },
  { nume: "Bețești", simplu: "Betesti", comuna: "Rediu" },
  { nume: "Bicaz-Chei" },
  { nume: "Bicaz" },
  { nume: "Bicazu Ardelean" },
  { nume: "Bira" },
  { nume: "Bisericani", comuna: "Alexandru Cel Bun" },
  { nume: "Bistricioara", comuna: "Ceahlau" },
  { nume: "Bistrița", simplu: "Bistrita", comuna: "Alexandru Cel Bun" },
  { nume: "Blebea", comuna: "Targu Neamt" },
  { nume: "Boboiești", simplu: "Boboiesti", comuna: "Pipirig" },
  { nume: "Bodești", simplu: "Bodesti" },
  { nume: "Bodeștii de Jos", simplu: "Bodestii de Jos", comuna: "Bodesti" },
  { nume: "Boghicea", comuna: "Bira" },
  { nume: "Bogzești", simplu: "Bogzesti", comuna: "Secuieni" },
  { nume: "Boiștea", simplu: "Boistea", comuna: "Petricani" },
  { nume: "Borca" },
  { nume: "Bordea", comuna: "Stefan Cel Mare" },
  { nume: "Borlești", simplu: "Borlesti" },
  { nume: "Borniș", simplu: "Bornis", comuna: "Dragomiresti" },
  { nume: "Borșeni", simplu: "Borseni", comuna: "Razboieni" },
  { nume: "Botești", simplu: "Botesti" },
  { nume: "Boțești", simplu: "Botesti", comuna: "Girov" },
  { nume: "Bozieni" },
  { nume: "Bozienii de Sus", comuna: "Ruginoasa" },
  { nume: "Bradu", comuna: "Grinties" },
  { nume: "Brășăuți", simplu: "Brasauti", comuna: "Dumbrava Rosie" },
  { nume: "Brateș", simplu: "Brates", comuna: "Tarcau" },
  { nume: "Breaza", comuna: "Bargauani" },
  { nume: "Brițcani", simplu: "Britcani", comuna: "Dulcesti" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Bahna" },
  { nume: "Brusturi", comuna: "Brusturi-Draganesti" },
  { nume: "Bucium", comuna: "Valea Ursului" },
  { nume: "Budești", simplu: "Budesti", comuna: "Faurei" },
  { nume: "Buhalnița", simplu: "Buhalnita", comuna: "Hangu" },
  { nume: "Buhonca", comuna: "Doljesti" },
  { nume: "Bunghi", comuna: "Poienari" },
  { nume: "Buruienești", simplu: "Buruienesti", comuna: "Doljesti" },
  { nume: "Bușmei", simplu: "Busmei", comuna: "Farcasa" },
  { nume: "Butnărești", simplu: "Butnaresti", comuna: "Secuieni" },
  { nume: "Căciulești", simplu: "Caciulesti", comuna: "Girov" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Poiana Teiului" },
  { nume: "Cândesti", simplu: "Candesti" },
  { nume: "Capșa", simplu: "Capsa", comuna: "Bicaz" },
  { nume: "Cârlig", simplu: "Carlig", comuna: "Dulcesti" },
  { nume: "Cârligi", simplu: "Carligi", comuna: "Stefan Cel Mare" },
  { nume: "Cășăria", simplu: "Casaria", comuna: "Dobreni" },
  { nume: "Căușeni", simplu: "Causeni", comuna: "Bira" },
  { nume: "Cazaci", comuna: "Tarcau" },
  { nume: "Ceahlău", simplu: "Ceahlau" },
  { nume: "Certieni", comuna: "Bargauani" },
  { nume: "Chicerea", comuna: "Stanita" },
  { nume: "Chilia", comuna: "Bargauani" },
  { nume: "Chilii", comuna: "Valea Ursului" },
  { nume: "Chintinici", comuna: "Roznov" },
  { nume: "Chirițeni", simplu: "Chiriteni", comuna: "Hangu" },
  { nume: "Ciornei", comuna: "Oniceni" },
  { nume: "Ciritei", comuna: "Piatra Neamt" },
  { nume: "Ciurea", comuna: "Poienari" },
  { nume: "Climești", simplu: "Climesti", comuna: "Faurei" },
  { nume: "Cordun" },
  { nume: "Corhana", comuna: "Dulcesti" },
  { nume: "Corni", comuna: "Bodesti" },
  { nume: "Costișa", simplu: "Costisa" },
  { nume: "Cotu Vameș", simplu: "Cotu Vames", comuna: "Horia" },
  { nume: "Crăcăoani", simplu: "Cracaoani" },
  { nume: "Cracăul Negru", simplu: "Cracaul Negru", comuna: "Cracaoani" },
  { nume: "Crăiești", simplu: "Craiesti", comuna: "Bozieni" },
  { nume: "Cuci", comuna: "Bozieni" },
  { nume: "Cuejdiu", comuna: "Garcina" },
  { nume: "Curechiștea", simplu: "Curechistea", comuna: "Grumazesti" },
  { nume: "Cut", comuna: "Dumbrava Rosie" },
  { nume: "Dămuc", simplu: "Damuc" },
  { nume: "Dănești", simplu: "Danesti", comuna: "Girov" },
  { nume: "Dârloaia", simplu: "Darloaia", comuna: "Bargauani" },
  { nume: "David", comuna: "Botesti" },
  { nume: "Davideni", comuna: "Tibucani" },
  { nume: "Deleni", comuna: "Stefan Cel Mare" },
  { nume: "Doamna", comuna: "Piatra Neamt" },
  { nume: "Dobreni" },
  { nume: "Dochia" },
  { nume: "Dodeni", comuna: "Bicaz" },
  { nume: "Doina", comuna: "Girov" },
  { nume: "Dolhești", simplu: "Dolhesti", comuna: "Pipirig" },
  { nume: "Doljești", simplu: "Doljesti" },
  { nume: "Dornești", simplu: "Dornesti", comuna: "Costisa" },
  { nume: "Drăgănești", simplu: "Draganesti", comuna: "Brusturi-Draganesti" },
  { nume: "Dragomirești", simplu: "Dragomiresti" },
  { nume: "Dragova", comuna: "Candesti" },
  { nume: "Dreptu", comuna: "Poiana Teiului" },
  { nume: "Dulcești", simplu: "Dulcesti" },
  { nume: "Dumbrava Deal", comuna: "Savinesti" },
  { nume: "Dumbrava Roșie", simplu: "Dumbrava Rosie" },
  { nume: "Dumbrava", comuna: "Timisesti" },
  { nume: "Dușești", simplu: "Dusesti", comuna: "Stefan Cel Mare" },
  { nume: "Farcașa", simplu: "Farcasa" },
  { nume: "Făurei", simplu: "Faurei" },
  { nume: "Filioara", comuna: "Agapia" },
  { nume: "Frumosu", comuna: "Farcasa" },
  { nume: "Frunzeni", comuna: "Costisa" },
  { nume: "Gâdinți", simplu: "Gadinti", comuna: "Sagna" },
  { nume: "Galu", comuna: "Poiana Teiului" },
  { nume: "Gârcina", simplu: "Garcina" },
  { nume: "Ghelăiești", simplu: "Ghelaiesti", comuna: "Bargauani" },
  { nume: "Gherăești", simplu: "Gheraesti" },
  { nume: "Gherăeștii Noi", simplu: "Gheraestii Noi", comuna: "Gheraesti" },
  { nume: "Gherman", comuna: "Bicaz-Chei" },
  { nume: "Ghidion", comuna: "Stanita" },
  { nume: "Ghigoiești", simplu: "Ghigoiesti", comuna: "Stefan Cel Mare" },
  { nume: "Ghindăoani", simplu: "Ghindaoani" },
  { nume: "Girov" },
  { nume: "Giulești", simplu: "Giulesti", comuna: "Secuieni" },
  { nume: "Giurgeni", comuna: "Valea Ursului" },
  { nume: "Gorun", comuna: "Oniceni" },
  { nume: "Goșmani", simplu: "Gosmani", comuna: "Romani" },
  { nume: "Grințieș", simplu: "Grinties" },
  { nume: "Groși", simplu: "Grosi", comuna: "Brusturi-Draganesti" },
  { nume: "Grozăvești", simplu: "Grozavesti", comuna: "Hangu" },
  { nume: "Grumăzești", simplu: "Grumazesti" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Girov" },
  { nume: "Hamzoaia", comuna: "Tasca" },
  { nume: "Hangu" },
  { nume: "Hanul Ancuței", simplu: "Hanul Ancutei", comuna: "Tupilati" },
  { nume: "Hârțești", simplu: "Hartesti", comuna: "Margineni" },
  { nume: "Hârtop", simplu: "Hartop", comuna: "Bargauani" },
  { nume: "Hlăpești", simplu: "Hlapesti", comuna: "Dragomiresti" },
  { nume: "Hociungi", comuna: "Moldoveni" },
  { nume: "Hoisești", simplu: "Hoisesti", comuna: "Margineni" },
  { nume: "Holm", comuna: "Poienari" },
  { nume: "Homiceni", comuna: "Bargauani" },
  { nume: "Horia" },
  { nume: "Huisurez", comuna: "Damuc" },
  { nume: "Humulești", simplu: "Humulesti", comuna: "Targu Neamt" },
  { nume: "Humuleștii Noi", simplu: "Humulestii Noi", comuna: "Targu Neamt" },
  { nume: "Icușești", simplu: "Icusesti" },
  { nume: "Ingărești", simplu: "Ingaresti", comuna: "Urecheni" },
  { nume: "Ion Creangă", simplu: "Ion Creanga" },
  { nume: "Itrinești", simplu: "Itrinesti", comuna: "Margineni" },
  { nume: "Iucșa", simplu: "Iucsa", comuna: "Bozieni" },
  { nume: "Ivaneș", simplu: "Ivanes", comuna: "Bicaz-Chei" },
  { nume: "Izvoare", comuna: "Bahna" },
  { nume: "Izvoare", comuna: "Dumbrava Rosie" },
  { nume: "Izvoru Muntelui", comuna: "Bicaz" },
  { nume: "Izvoru", comuna: "Ion Creanga" },
  { nume: "Izvorul Alb", comuna: "Bicaz" },
  { nume: "Leghin", comuna: "Pipirig" },
  { nume: "Liliac", comuna: "Bahna" },
  { nume: "Linsești", simplu: "Linsesti", comuna: "Oniceni" },
  { nume: "Luminiș", simplu: "Luminis", comuna: "Piatra Soimului" },
  { nume: "Lunca Moldovei", comuna: "Pastraveni" },
  { nume: "Lunca", comuna: "Borca" },
  { nume: "Lunca", comuna: "Oniceni" },
  { nume: "Lunca", comuna: "Vanatori-Neamt" },
  { nume: "Luțca", simplu: "Lutca", comuna: "Sagna" },
  { nume: "Mădei", simplu: "Madei", comuna: "Borca" },
  { nume: "Magazia", comuna: "Cracaoani" },
  {
    nume: "Mânăstirea Neamț",
    simplu: "Manastirea Neamt",
    comuna: "Vanatori-Neamt",
  },
  { nume: "Mănoaia", simplu: "Manoaia", comuna: "Costisa" },
  { nume: "Mărgineni", simplu: "Margineni" },
  { nume: "Mărmureni", simplu: "Marmureni", comuna: "Oniceni" },
  { nume: "Mastacăn", simplu: "Mastacan", comuna: "Borlesti" },
  { nume: "Mastacăn", simplu: "Mastacan", comuna: "Dragomiresti" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Icusesti" },
  { nume: "Micșunești", simplu: "Micsunesti", comuna: "Faurei" },
  { nume: "Miron Costin", comuna: "Trifesti" },
  { nume: "Mitocu Bălan", simplu: "Mitocu Balan", comuna: "Cracaoani" },
  { nume: "Moldoveni" },
  { nume: "Moreni", comuna: "Botesti" },
  { nume: "Muncelu de Jos", comuna: "Valea Ursului" },
  { nume: "Muncelu", comuna: "Ion Creanga" },
  { nume: "Munteni", comuna: "Botesti" },
  { nume: "Neagra", comuna: "Tasca" },
  { nume: "Nechit", comuna: "Borlesti" },
  { nume: "Negrești", simplu: "Negresti", comuna: "Bira" },
  { nume: "Negrești", simplu: "Negresti", comuna: "Dobreni" },
  { nume: "Negritești", simplu: "Negritesti", comuna: "Podoleni" },
  { nume: "Negulești", simplu: "Negulesti", comuna: "Piatra Soimului" },
  { nume: "Nemțișor", simplu: "Nemtisor", comuna: "Vanatori-Neamt" },
  { nume: "Netezi", comuna: "Grumazesti" },
  { nume: "Nisiporești", simplu: "Nisiporesti", comuna: "Botesti" },
  { nume: "Nistria", comuna: "Bira" },
  { nume: "Oanțu", simplu: "Oantu", comuna: "Pangarati" },
  { nume: "Oglinzi", comuna: "Raucesti" },
  { nume: "Oniceni" },
  { nume: "Orțăști", simplu: "Ortasti", comuna: "Brusturi-Draganesti" },
  { nume: "Oșlobeni", simplu: "Oslobeni", comuna: "Bodesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Candesti" },
  { nume: "Pâncești", simplu: "Pancesti", comuna: "Poienari" },
  { nume: "Pângărăcior", simplu: "Pangaracior", comuna: "Pangarati" },
  { nume: "Pângarați", simplu: "Pangarati" },
  { nume: "Pârâul Cârjei", simplu: "Paraul Carjei", comuna: "Borca" },
  {
    nume: "Pârâul Fagului",
    simplu: "Paraul Fagului",
    comuna: "Poiana Teiului",
  },
  { nume: "Pârâul Mare", simplu: "Paraul Mare", comuna: "Ceahlau" },
  { nume: "Pârâul Pântei", simplu: "Paraul Pantei", comuna: "Borca" },
  { nume: "Păstrăveni", simplu: "Pastraveni" },
  { nume: "Pâțâligeni", simplu: "Pataligeni", comuna: "Pipirig" },
  { nume: "Patricheni", comuna: "Poienari" },
  { nume: "Petricani" },
  { nume: "Petru Vodă", simplu: "Petru Voda", comuna: "Poiana Teiului" },
  { nume: "Piatra Șoimului", simplu: "Piatra Soimului" },
  { nume: "Piatra-Neamț", simplu: "Piatra-Neamt", comuna: "Piatra Neamt" },
  { nume: "Pietrosu", comuna: "Oniceni" },
  { nume: "Pildești", simplu: "Pildesti", comuna: "Cordun" },
  { nume: "Pipirig" },
  { nume: "Plăieșu", simplu: "Plaiesu", comuna: "Timisesti" },
  { nume: "Plugari", comuna: "Urecheni" },
  { nume: "Pluton", comuna: "Pipirig" },
  { nume: "Podoleni" },
  { nume: "Poiana Crăcăoani", simplu: "Poiana Cracaoani", comuna: "Cracaoani" },
  { nume: "Poiana Humei", comuna: "Oniceni" },
  { nume: "Poiana Largului", comuna: "Poiana Teiului" },
  { nume: "Poiana Teiului" },
  { nume: "Poiana", comuna: "Brusturi-Draganesti" },
  { nume: "Poiana", comuna: "Dobreni" },
  { nume: "Poiana", comuna: "Dulcesti" },
  { nume: "Poiana", comuna: "Grinties" },
  { nume: "Poiana", comuna: "Pangarati" },
  { nume: "Poienari" },
  { nume: "Poieni", comuna: "Piatra Soimului" },
  { nume: "Poienile Oancei", comuna: "Stanita" },
  { nume: "Poloboc", comuna: "Rediu" },
  { nume: "Popești", simplu: "Popesti", comuna: "Farcasa" },
  { nume: "Popești", simplu: "Popesti", comuna: "Girov" },
  { nume: "Potoci", comuna: "Bicaz" },
  { nume: "Prăjești", simplu: "Prajesti", comuna: "Secuieni" },
  { nume: "Preluca", comuna: "Pangarati" },
  { nume: "Preutești", simplu: "Preutesti", comuna: "Timisesti" },
  { nume: "Pustieta", comuna: "Oniceni" },
  { nume: "Rădeni", simplu: "Radeni", comuna: "Pastraveni" },
  { nume: "Râșca", simplu: "Rasca", comuna: "Brusturi-Draganesti" },
  { nume: "Răucești", simplu: "Raucesti" },
  { nume: "Războieni", simplu: "Razboieni" },
  {
    nume: "Războienii de Jos",
    simplu: "Razboienii de Jos",
    comuna: "Razboieni",
  },
  { nume: "Recea", comuna: "Ion Creanga" },
  { nume: "Rediu" },
  { nume: "Rediu", comuna: "Bira" },
  { nume: "Rocna", comuna: "Icusesti" },
  { nume: "Roman" },
  { nume: "Români", simplu: "Romani" },
  { nume: "Roșeni", simplu: "Roseni", comuna: "Poiana Teiului" },
  { nume: "Roșiori", simplu: "Rosiori", comuna: "Dulcesti" },
  { nume: "Rotunda", comuna: "Doljesti" },
  { nume: "Roznov" },
  { nume: "Ruginești", simplu: "Ruginesti", comuna: "Hangu" },
  { nume: "Ruginoasa" },
  { nume: "Ruseni", comuna: "Borlesti" },
  { nume: "Ruseni", comuna: "Poiana Teiului" },
  { nume: "Săbăoani", simplu: "Sabaoani" },
  { nume: "Sabasa", comuna: "Borca" },
  { nume: "Săcăleni", simplu: "Sacaleni", comuna: "Poienari" },
  { nume: "Săcălușești", simplu: "Sacalusesti", comuna: "Agapia" },
  { nume: "Sagna" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Dobreni" },
  { nume: "Săvești", simplu: "Savesti", comuna: "Raucesti" },
  { nume: "Săvinești", simplu: "Savinesti" },
  { nume: "Săvinești", simplu: "Savinesti", comuna: "Poiana Teiului" },
  { nume: "Scăricica", simplu: "Scaricica", comuna: "Alexandru Cel Bun" },
  { nume: "Schitu Tarcău", simplu: "Schitu Tarcau", comuna: "Tarcau" },
  { nume: "Secu", comuna: "Bicaz" },
  { nume: "Secuieni" },
  { nume: "Secuienii Noi", comuna: "Secuieni" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Romani" },
  { nume: "Simionești", simplu: "Simionesti", comuna: "Cordun" },
  { nume: "Slobozia", comuna: "Bira" },
  { nume: "Slobozia", comuna: "Roznov" },
  { nume: "Socea", comuna: "Rediu" },
  { nume: "Soci", comuna: "Borca" },
  { nume: "Soci", comuna: "Stefan Cel Mare" },
  { nume: "Șoimărești", simplu: "Soimaresti", comuna: "Brusturi-Draganesti" },
  { nume: "Solca", comuna: "Oniceni" },
  { nume: "Șovoaia", simplu: "Sovoaia", comuna: "Borlesti" },
  { nume: "Spiești", simplu: "Spiesti", comuna: "Pastraveni" },
  { nume: "Spiridonești", simplu: "Spiridonesti", comuna: "Icusesti" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Pipirig" },
  { nume: "Stănița", simplu: "Stanita" },
  { nume: "Ștefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Stejaru", comuna: "Farcasa" },
  { nume: "Stejaru", comuna: "Ion Creanga" },
  { nume: "Stejaru", comuna: "Pangarati" },
  { nume: "Straja", comuna: "Tarcau" },
  { nume: "Tabăra", simplu: "Tabara", comuna: "Icusesti" },
  { nume: "Talpa", comuna: "Bargauani" },
  { nume: "Tălpălăi", simplu: "Talpalai", comuna: "Poienari" },
  { nume: "Tămășeni", simplu: "Tamaseni" },
  { nume: "Tarcău", simplu: "Tarcau" },
  { nume: "Țârdenii Mici", simplu: "Tardenii Mici", comuna: "Candesti" },
  { nume: "Târgu Neamț", simplu: "Targu Neamt" },
  { nume: "Târpești", simplu: "Tarpesti", comuna: "Petricani" },
  { nume: "Târzia", simplu: "Tarzia", comuna: "Brusturi-Draganesti" },
  { nume: "Tașca", simplu: "Tasca" },
  { nume: "Tazlău", simplu: "Tazlau" },
  { nume: "Telec", comuna: "Bicazu Ardelean" },
  { nume: "Tețcani", simplu: "Tetcani", comuna: "Gheraesti" },
  { nume: "Țibucani", simplu: "Tibucani" },
  { nume: "Țibucanii de Jos", simplu: "Tibucanii de Jos", comuna: "Tibucani" },
  { nume: "Ticoș-Floarea", simplu: "Ticos-Floarea", comuna: "Tasca" },
  { nume: "Ticoș", simplu: "Ticos", comuna: "Bicazu Ardelean" },
  { nume: "Timișești", simplu: "Timisesti" },
  { nume: "Todireni", comuna: "Stanita" },
  { nume: "Țolici", simplu: "Tolici", comuna: "Petricani" },
  { nume: "Topoliceni", comuna: "Poiana Teiului" },
  { nume: "Topolița", simplu: "Topolita", comuna: "Grumazesti" },
  { nume: "Totoiești", simplu: "Totoiesti", comuna: "Tupilati" },
  { nume: "Traian", comuna: "Sabaoani" },
  { nume: "Traian", comuna: "Zanesti" },
  { nume: "Trei Fântâni", simplu: "Trei Fantani", comuna: "Damuc" },
  { nume: "Trifești", simplu: "Trifesti" },
  { nume: "Tupilați", simplu: "Tupilati" },
  { nume: "Turturești", simplu: "Turturesti", comuna: "Girov" },
  { nume: "Țuțcanii din Deal", simplu: "Tutcanii din Deal", comuna: "Bahna" },
  { nume: "Țuțcanii din Vale", simplu: "Tutcanii din Vale", comuna: "Bahna" },
  { nume: "Uncești", simplu: "Uncesti", comuna: "Secuieni" },
  { nume: "Ungheni", comuna: "Raucesti" },
  { nume: "Unghi", comuna: "Dragomiresti" },
  { nume: "Urecheni" },
  { nume: "Vad", comuna: "Dragomiresti" },
  { nume: "Vădurele", simplu: "Vadurele", comuna: "Alexandru Cel Bun" },
  { nume: "Vădurele", simplu: "Vadurele", comuna: "Candesti" },
  { nume: "Vaduri", comuna: "Alexandru Cel Bun" },
  { nume: "Valea Albă", simplu: "Valea Alba", comuna: "Razboieni" },
  { nume: "Valea Arini", comuna: "Baltatesti" },
  { nume: "Valea Enei", comuna: "Oniceni" },
  { nume: "Valea Mare", comuna: "Razboieni" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Baltatesti" },
  { nume: "Valea Ursului" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Botesti" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Piatra Neamt" },
  { nume: "Vânători-Neamț", simplu: "Vanatori-Neamt" },
  { nume: "Varatec", comuna: "Agapia" },
  { nume: "Veja", comuna: "Stanita" },
  { nume: "Verșești", simplu: "Versesti", comuna: "Girov" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Alexandru Cel Bun" },
  { nume: "Vlădiceni", simplu: "Vladiceni", comuna: "Bargauani" },
  { nume: "Vlădnicele", simplu: "Vladnicele", comuna: "Stanita" },
  { nume: "Vulpășești", simplu: "Vulpasesti", comuna: "Sagna" },
  { nume: "Zănești", simplu: "Zanesti" },
  { nume: "Zvorănești", simplu: "Zvoranesti", comuna: "Timisesti" },
];
