export const nt = [
  { nume: "Adjudeni", comuna: "Tamaseni" },
  { nume: "Agapia" },
  { nume: "Agârcia", simplu: "Agarcia", comuna: "Alexandru Cel Bun" },
  { nume: "Almaş", simplu: "Almas", comuna: "Garcina" },
  { nume: "Arămeşti", simplu: "Aramesti", comuna: "Bahna" },
  { nume: "Arămoaia", simplu: "Aramoaia", comuna: "Tupilati" },
  { nume: "Ardeluţa", simplu: "Ardeluta", comuna: "Tarcau" },
  { nume: "Avereşti", simplu: "Averesti", comuna: "Ion Creanga" },
  { nume: "Bahna Mare", comuna: "Bargauani" },
  { nume: "Bahna" },
  { nume: "Băhnişoara", simplu: "Bahnisoara", comuna: "Bahna" },
  { nume: "Bălăneşti", simplu: "Balanesti", comuna: "Bargauani" },
  { nume: "Bălţăteşti", simplu: "Baltatesti" },
  { nume: "Băluşeşti", simplu: "Balusesti", comuna: "Dochia" },
  { nume: "Băluşeşti", simplu: "Balusesti", comuna: "Icusesti" },
  { nume: "Băneasa", simplu: "Baneasa", comuna: "Bozieni" },
  { nume: "Baratca", comuna: "Bargauani" },
  { nume: "Bărcăneşti", simplu: "Barcanesti", comuna: "Candesti" },
  { nume: "Bârgauani", simplu: "Bargauani" },
  { nume: "Bârjoveni", simplu: "Barjoveni", comuna: "Secuieni" },
  { nume: "Bârnadu", simplu: "Barnadu", comuna: "Bicaz-Chei" },
  { nume: "Barticeşti", simplu: "Barticesti", comuna: "Botesti" },
  { nume: "Başta", simplu: "Basta", comuna: "Secuieni" },
  { nume: "Bătrâneşti", simplu: "Batranesti", comuna: "Icusesti" },
  { nume: "Beţeşti", simplu: "Betesti", comuna: "Rediu" },
  { nume: "Bicaz-Chei" },
  { nume: "Bicaz" },
  { nume: "Bicazu Ardelean" },
  { nume: "Bira" },
  { nume: "Bisericani", comuna: "Alexandru Cel Bun" },
  { nume: "Bistricioara", comuna: "Ceahlau" },
  { nume: "Bistriţa", simplu: "Bistrita", comuna: "Alexandru Cel Bun" },
  { nume: "Blebea", comuna: "Targu Neamt" },
  { nume: "Boboieşti", simplu: "Boboiesti", comuna: "Pipirig" },
  { nume: "Bodeşti", simplu: "Bodesti" },
  { nume: "Bodeştii de Jos", simplu: "Bodestii de Jos", comuna: "Bodesti" },
  { nume: "Boghicea", comuna: "Bira" },
  { nume: "Bogzeşti", simplu: "Bogzesti", comuna: "Secuieni" },
  { nume: "Boiştea", simplu: "Boistea", comuna: "Petricani" },
  { nume: "Borca" },
  { nume: "Bordea", comuna: "Stefan Cel Mare" },
  { nume: "Borleşti", simplu: "Borlesti" },
  { nume: "Borniş", simplu: "Bornis", comuna: "Dragomiresti" },
  { nume: "Borşeni", simplu: "Borseni", comuna: "Razboieni" },
  { nume: "Boteşti", simplu: "Botesti" },
  { nume: "Boţeşti", simplu: "Botesti", comuna: "Girov" },
  { nume: "Bozieni" },
  { nume: "Bozienii de Sus", comuna: "Ruginoasa" },
  { nume: "Bradu", comuna: "Grinties" },
  { nume: "Brăşăuţi", simplu: "Brasauti", comuna: "Dumbrava Rosie" },
  { nume: "Brateş", simplu: "Brates", comuna: "Tarcau" },
  { nume: "Breaza", comuna: "Bargauani" },
  { nume: "Briţcani", simplu: "Britcani", comuna: "Dulcesti" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Bahna" },
  { nume: "Brusturi", comuna: "Brusturi-Draganesti" },
  { nume: "Bucium", comuna: "Valea Ursului" },
  { nume: "Budeşti", simplu: "Budesti", comuna: "Faurei" },
  { nume: "Buhalniţa", simplu: "Buhalnita", comuna: "Hangu" },
  { nume: "Buhonca", comuna: "Doljesti" },
  { nume: "Bunghi", comuna: "Poienari" },
  { nume: "Buruieneşti", simplu: "Buruienesti", comuna: "Doljesti" },
  { nume: "Buşmei", simplu: "Busmei", comuna: "Farcasa" },
  { nume: "Butnăreşti", simplu: "Butnaresti", comuna: "Secuieni" },
  { nume: "Căciuleşti", simplu: "Caciulesti", comuna: "Girov" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Poiana Teiului" },
  { nume: "Cândesti", simplu: "Candesti" },
  { nume: "Capşa", simplu: "Capsa", comuna: "Bicaz" },
  { nume: "Cârlig", simplu: "Carlig", comuna: "Dulcesti" },
  { nume: "Cârligi", simplu: "Carligi", comuna: "Stefan Cel Mare" },
  { nume: "Căşăria", simplu: "Casaria", comuna: "Dobreni" },
  { nume: "Căuşeni", simplu: "Causeni", comuna: "Bira" },
  { nume: "Cazaci", comuna: "Tarcau" },
  { nume: "Ceahlău", simplu: "Ceahlau" },
  { nume: "Certieni", comuna: "Bargauani" },
  { nume: "Chicerea", comuna: "Stanita" },
  { nume: "Chilia", comuna: "Bargauani" },
  { nume: "Chilii", comuna: "Valea Ursului" },
  { nume: "Chintinici", comuna: "Roznov" },
  { nume: "Chiriţeni", simplu: "Chiriteni", comuna: "Hangu" },
  { nume: "Ciornei", comuna: "Oniceni" },
  { nume: "Ciritei", comuna: "Piatra Neamt" },
  { nume: "Ciurea", comuna: "Poienari" },
  { nume: "Climeşti", simplu: "Climesti", comuna: "Faurei" },
  { nume: "Cordun" },
  { nume: "Corhana", comuna: "Dulcesti" },
  { nume: "Corni", comuna: "Bodesti" },
  { nume: "Costişa", simplu: "Costisa" },
  { nume: "Cotu Vameş", simplu: "Cotu Vames", comuna: "Horia" },
  { nume: "Crăcăoani", simplu: "Cracaoani" },
  { nume: "Cracăul Negru", simplu: "Cracaul Negru", comuna: "Cracaoani" },
  { nume: "Crăieşti", simplu: "Craiesti", comuna: "Bozieni" },
  { nume: "Cuci", comuna: "Bozieni" },
  { nume: "Cuejdiu", comuna: "Garcina" },
  { nume: "Curechiştea", simplu: "Curechistea", comuna: "Grumazesti" },
  { nume: "Cut", comuna: "Dumbrava Rosie" },
  { nume: "Dămuc", simplu: "Damuc" },
  { nume: "Dăneşti", simplu: "Danesti", comuna: "Girov" },
  { nume: "Dârloaia", simplu: "Darloaia", comuna: "Bargauani" },
  { nume: "David", comuna: "Botesti" },
  { nume: "Davideni", comuna: "Tibucani" },
  { nume: "Deleni", comuna: "Stefan Cel Mare" },
  { nume: "Doamna", comuna: "Piatra Neamt" },
  { nume: "Dobreni" },
  { nume: "Dochia" },
  { nume: "Dodeni", comuna: "Bicaz" },
  { nume: "Doina", comuna: "Girov" },
  { nume: "Dolheşti", simplu: "Dolhesti", comuna: "Pipirig" },
  { nume: "Doljeşti", simplu: "Doljesti" },
  { nume: "Dorneşti", simplu: "Dornesti", comuna: "Costisa" },
  { nume: "Drăgăneşti", simplu: "Draganesti", comuna: "Brusturi-Draganesti" },
  { nume: "Dragomireşti", simplu: "Dragomiresti" },
  { nume: "Dragova", comuna: "Candesti" },
  { nume: "Dreptu", comuna: "Poiana Teiului" },
  { nume: "Dulceşti", simplu: "Dulcesti" },
  { nume: "Dumbrava Deal", comuna: "Savinesti" },
  { nume: "Dumbrava Roşie", simplu: "Dumbrava Rosie" },
  { nume: "Dumbrava", comuna: "Timisesti" },
  { nume: "Duşeşti", simplu: "Dusesti", comuna: "Stefan Cel Mare" },
  { nume: "Farcaşa", simplu: "Farcasa" },
  { nume: "Făurei", simplu: "Faurei" },
  { nume: "Filioara", comuna: "Agapia" },
  { nume: "Frumosu", comuna: "Farcasa" },
  { nume: "Frunzeni", comuna: "Costisa" },
  { nume: "Gâdinţi", simplu: "Gadinti", comuna: "Sagna" },
  { nume: "Galu", comuna: "Poiana Teiului" },
  { nume: "Gârcina", simplu: "Garcina" },
  { nume: "Ghelăieşti", simplu: "Ghelaiesti", comuna: "Bargauani" },
  { nume: "Gherăeşti", simplu: "Gheraesti" },
  { nume: "Gherăeştii Noi", simplu: "Gheraestii Noi", comuna: "Gheraesti" },
  { nume: "Gherman", comuna: "Bicaz-Chei" },
  { nume: "Ghidion", comuna: "Stanita" },
  { nume: "Ghigoieşti", simplu: "Ghigoiesti", comuna: "Stefan Cel Mare" },
  { nume: "Ghindăoani", simplu: "Ghindaoani" },
  { nume: "Girov" },
  { nume: "Giuleşti", simplu: "Giulesti", comuna: "Secuieni" },
  { nume: "Giurgeni", comuna: "Valea Ursului" },
  { nume: "Gorun", comuna: "Oniceni" },
  { nume: "Goşmani", simplu: "Gosmani", comuna: "Romani" },
  { nume: "Grinţieş", simplu: "Grinties" },
  { nume: "Groşi", simplu: "Grosi", comuna: "Brusturi-Draganesti" },
  { nume: "Grozăveşti", simplu: "Grozavesti", comuna: "Hangu" },
  { nume: "Grumăzeşti", simplu: "Grumazesti" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Girov" },
  { nume: "Hamzoaia", comuna: "Tasca" },
  { nume: "Hangu" },
  { nume: "Hanul Ancuţei", simplu: "Hanul Ancutei", comuna: "Tupilati" },
  { nume: "Hârţeşti", simplu: "Hartesti", comuna: "Margineni" },
  { nume: "Hârtop", simplu: "Hartop", comuna: "Bargauani" },
  { nume: "Hlăpeşti", simplu: "Hlapesti", comuna: "Dragomiresti" },
  { nume: "Hociungi", comuna: "Moldoveni" },
  { nume: "Hoiseşti", simplu: "Hoisesti", comuna: "Margineni" },
  { nume: "Holm", comuna: "Poienari" },
  { nume: "Homiceni", comuna: "Bargauani" },
  { nume: "Horia" },
  { nume: "Huisurez", comuna: "Damuc" },
  { nume: "Humuleşti", simplu: "Humulesti", comuna: "Targu Neamt" },
  { nume: "Humuleştii Noi", simplu: "Humulestii Noi", comuna: "Targu Neamt" },
  { nume: "Icuşeşti", simplu: "Icusesti" },
  { nume: "Ingăreşti", simplu: "Ingaresti", comuna: "Urecheni" },
  { nume: "Ion Creangă", simplu: "Ion Creanga" },
  { nume: "Itrineşti", simplu: "Itrinesti", comuna: "Margineni" },
  { nume: "Iucşa", simplu: "Iucsa", comuna: "Bozieni" },
  { nume: "Ivaneş", simplu: "Ivanes", comuna: "Bicaz-Chei" },
  { nume: "Izvoare", comuna: "Bahna" },
  { nume: "Izvoare", comuna: "Dumbrava Rosie" },
  { nume: "Izvoru Muntelui", comuna: "Bicaz" },
  { nume: "Izvoru", comuna: "Ion Creanga" },
  { nume: "Izvorul Alb", comuna: "Bicaz" },
  { nume: "Leghin", comuna: "Pipirig" },
  { nume: "Liliac", comuna: "Bahna" },
  { nume: "Linseşti", simplu: "Linsesti", comuna: "Oniceni" },
  { nume: "Luminiş", simplu: "Luminis", comuna: "Piatra Soimului" },
  { nume: "Lunca Moldovei", comuna: "Pastraveni" },
  { nume: "Lunca", comuna: "Borca" },
  { nume: "Lunca", comuna: "Oniceni" },
  { nume: "Lunca", comuna: "Vanatori-Neamt" },
  { nume: "Luţca", simplu: "Lutca", comuna: "Sagna" },
  { nume: "Mădei", simplu: "Madei", comuna: "Borca" },
  { nume: "Magazia", comuna: "Cracaoani" },
  {
    nume: "Mânăstirea Neamţ",
    simplu: "Manastirea Neamt",
    comuna: "Vanatori-Neamt",
  },
  { nume: "Mănoaia", simplu: "Manoaia", comuna: "Costisa" },
  { nume: "Mărgineni", simplu: "Margineni" },
  { nume: "Mărmureni", simplu: "Marmureni", comuna: "Oniceni" },
  { nume: "Mastacăn", simplu: "Mastacan", comuna: "Borlesti" },
  { nume: "Mastacăn", simplu: "Mastacan", comuna: "Dragomiresti" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Icusesti" },
  { nume: "Micşuneşti", simplu: "Micsunesti", comuna: "Faurei" },
  { nume: "Miron Costin", comuna: "Trifesti" },
  { nume: "Mitocu Bălan", simplu: "Mitocu Balan", comuna: "Cracaoani" },
  { nume: "Moldoveni" },
  { nume: "Moreni", comuna: "Botesti" },
  { nume: "Muncelu de Jos", comuna: "Valea Ursului" },
  { nume: "Muncelu", comuna: "Ion Creanga" },
  { nume: "Munteni", comuna: "Botesti" },
  { nume: "Neagra", comuna: "Tasca" },
  { nume: "Nechit", comuna: "Borlesti" },
  { nume: "Negreşti", simplu: "Negresti", comuna: "Bira" },
  { nume: "Negreşti", simplu: "Negresti", comuna: "Dobreni" },
  { nume: "Negriteşti", simplu: "Negritesti", comuna: "Podoleni" },
  { nume: "Neguleşti", simplu: "Negulesti", comuna: "Piatra Soimului" },
  { nume: "Nemţişor", simplu: "Nemtisor", comuna: "Vanatori-Neamt" },
  { nume: "Netezi", comuna: "Grumazesti" },
  { nume: "Nisiporeşti", simplu: "Nisiporesti", comuna: "Botesti" },
  { nume: "Nistria", comuna: "Bira" },
  { nume: "Oanţu", simplu: "Oantu", comuna: "Pangarati" },
  { nume: "Oglinzi", comuna: "Raucesti" },
  { nume: "Oniceni" },
  { nume: "Orţăşti", simplu: "Ortasti", comuna: "Brusturi-Draganesti" },
  { nume: "Oşlobeni", simplu: "Oslobeni", comuna: "Bodesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Candesti" },
  { nume: "Pânceşti", simplu: "Pancesti", comuna: "Poienari" },
  { nume: "Pângărăcior", simplu: "Pangaracior", comuna: "Pangarati" },
  { nume: "Pângaraţi", simplu: "Pangarati" },
  { nume: "Pârâul Cârjei", simplu: "Paraul Carjei", comuna: "Borca" },
  {
    nume: "Pârâul Fagului",
    simplu: "Paraul Fagului",
    comuna: "Poiana Teiului",
  },
  { nume: "Pârâul Mare", simplu: "Paraul Mare", comuna: "Ceahlau" },
  { nume: "Pârâul Pântei", simplu: "Paraul Pantei", comuna: "Borca" },
  { nume: "Păstrăveni", simplu: "Pastraveni" },
  { nume: "Pâţâligeni", simplu: "Pataligeni", comuna: "Pipirig" },
  { nume: "Patricheni", comuna: "Poienari" },
  { nume: "Petricani" },
  { nume: "Petru Vodă", simplu: "Petru Voda", comuna: "Poiana Teiului" },
  { nume: "Piatra Şoimului", simplu: "Piatra Soimului" },
  { nume: "Piatra-Neamţ", simplu: "Piatra-Neamt", comuna: "Piatra Neamt" },
  { nume: "Pietrosu", comuna: "Oniceni" },
  { nume: "Pildeşti", simplu: "Pildesti", comuna: "Cordun" },
  { nume: "Pipirig" },
  { nume: "Plăieşu", simplu: "Plaiesu", comuna: "Timisesti" },
  { nume: "Plugari", comuna: "Urecheni" },
  { nume: "Pluton", comuna: "Pipirig" },
  { nume: "Podoleni" },
  { nume: "Poiana Crăcăoani", simplu: "Poiana Cracaoani", comuna: "Cracaoani" },
  { nume: "Poiana Humei", comuna: "Oniceni" },
  { nume: "Poiana Largului", comuna: "Poiana Teiului" },
  { nume: "Poiana Teiului" },
  { nume: "Poiana", comuna: "Brusturi-Draganesti" },
  { nume: "Poiana", comuna: "Dobreni" },
  { nume: "Poiana", comuna: "Dulcesti" },
  { nume: "Poiana", comuna: "Grinties" },
  { nume: "Poiana", comuna: "Pangarati" },
  { nume: "Poienari" },
  { nume: "Poieni", comuna: "Piatra Soimului" },
  { nume: "Poienile Oancei", comuna: "Stanita" },
  { nume: "Poloboc", comuna: "Rediu" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Farcasa" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Girov" },
  { nume: "Potoci", comuna: "Bicaz" },
  { nume: "Prăjeşti", simplu: "Prajesti", comuna: "Secuieni" },
  { nume: "Preluca", comuna: "Pangarati" },
  { nume: "Preuteşti", simplu: "Preutesti", comuna: "Timisesti" },
  { nume: "Pustieta", comuna: "Oniceni" },
  { nume: "Rădeni", simplu: "Radeni", comuna: "Pastraveni" },
  { nume: "Râşca", simplu: "Rasca", comuna: "Brusturi-Draganesti" },
  { nume: "Răuceşti", simplu: "Raucesti" },
  { nume: "Războieni", simplu: "Razboieni" },
  {
    nume: "Războienii de Jos",
    simplu: "Razboienii de Jos",
    comuna: "Razboieni",
  },
  { nume: "Recea", comuna: "Ion Creanga" },
  { nume: "Rediu" },
  { nume: "Rediu", comuna: "Bira" },
  { nume: "Rocna", comuna: "Icusesti" },
  { nume: "Roman" },
  { nume: "Români", simplu: "Romani" },
  { nume: "Roşeni", simplu: "Roseni", comuna: "Poiana Teiului" },
  { nume: "Roşiori", simplu: "Rosiori", comuna: "Dulcesti" },
  { nume: "Rotunda", comuna: "Doljesti" },
  { nume: "Roznov" },
  { nume: "Rugineşti", simplu: "Ruginesti", comuna: "Hangu" },
  { nume: "Ruginoasa" },
  { nume: "Ruseni", comuna: "Borlesti" },
  { nume: "Ruseni", comuna: "Poiana Teiului" },
  { nume: "Săbăoani", simplu: "Sabaoani" },
  { nume: "Sabasa", comuna: "Borca" },
  { nume: "Săcăleni", simplu: "Sacaleni", comuna: "Poienari" },
  { nume: "Săcăluşeşti", simplu: "Sacalusesti", comuna: "Agapia" },
  { nume: "Sagna" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Dobreni" },
  { nume: "Săveşti", simplu: "Savesti", comuna: "Raucesti" },
  { nume: "Săvineşti", simplu: "Savinesti" },
  { nume: "Săvineşti", simplu: "Savinesti", comuna: "Poiana Teiului" },
  { nume: "Scăricica", simplu: "Scaricica", comuna: "Alexandru Cel Bun" },
  { nume: "Schitu Tarcău", simplu: "Schitu Tarcau", comuna: "Tarcau" },
  { nume: "Secu", comuna: "Bicaz" },
  { nume: "Secuieni" },
  { nume: "Secuienii Noi", comuna: "Secuieni" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Romani" },
  { nume: "Simioneşti", simplu: "Simionesti", comuna: "Cordun" },
  { nume: "Slobozia", comuna: "Bira" },
  { nume: "Slobozia", comuna: "Roznov" },
  { nume: "Socea", comuna: "Rediu" },
  { nume: "Soci", comuna: "Borca" },
  { nume: "Soci", comuna: "Stefan Cel Mare" },
  { nume: "Şoimăreşti", simplu: "Soimaresti", comuna: "Brusturi-Draganesti" },
  { nume: "Solca", comuna: "Oniceni" },
  { nume: "Şovoaia", simplu: "Sovoaia", comuna: "Borlesti" },
  { nume: "Spieşti", simplu: "Spiesti", comuna: "Pastraveni" },
  { nume: "Spiridoneşti", simplu: "Spiridonesti", comuna: "Icusesti" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Pipirig" },
  { nume: "Stăniţa", simplu: "Stanita" },
  { nume: "Ştefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Stejaru", comuna: "Farcasa" },
  { nume: "Stejaru", comuna: "Ion Creanga" },
  { nume: "Stejaru", comuna: "Pangarati" },
  { nume: "Straja", comuna: "Tarcau" },
  { nume: "Tabăra", simplu: "Tabara", comuna: "Icusesti" },
  { nume: "Talpa", comuna: "Bargauani" },
  { nume: "Tălpălăi", simplu: "Talpalai", comuna: "Poienari" },
  { nume: "Tămăşeni", simplu: "Tamaseni" },
  { nume: "Tarcău", simplu: "Tarcau" },
  { nume: "Ţârdenii Mici", simplu: "Tardenii Mici", comuna: "Candesti" },
  { nume: "Târgu Neamţ", simplu: "Targu Neamt" },
  { nume: "Târpeşti", simplu: "Tarpesti", comuna: "Petricani" },
  { nume: "Târzia", simplu: "Tarzia", comuna: "Brusturi-Draganesti" },
  { nume: "Taşca", simplu: "Tasca" },
  { nume: "Tazlău", simplu: "Tazlau" },
  { nume: "Telec", comuna: "Bicazu Ardelean" },
  { nume: "Teţcani", simplu: "Tetcani", comuna: "Gheraesti" },
  { nume: "Ţibucani", simplu: "Tibucani" },
  { nume: "Ţibucanii de Jos", simplu: "Tibucanii de Jos", comuna: "Tibucani" },
  { nume: "Ticoş-Floarea", simplu: "Ticos-Floarea", comuna: "Tasca" },
  { nume: "Ticoş", simplu: "Ticos", comuna: "Bicazu Ardelean" },
  { nume: "Timişeşti", simplu: "Timisesti" },
  { nume: "Todireni", comuna: "Stanita" },
  { nume: "Ţolici", simplu: "Tolici", comuna: "Petricani" },
  { nume: "Topoliceni", comuna: "Poiana Teiului" },
  { nume: "Topoliţa", simplu: "Topolita", comuna: "Grumazesti" },
  { nume: "Totoieşti", simplu: "Totoiesti", comuna: "Tupilati" },
  { nume: "Traian", comuna: "Sabaoani" },
  { nume: "Traian", comuna: "Zanesti" },
  { nume: "Trei Fântâni", simplu: "Trei Fantani", comuna: "Damuc" },
  { nume: "Trifeşti", simplu: "Trifesti" },
  { nume: "Tupilaţi", simplu: "Tupilati" },
  { nume: "Turtureşti", simplu: "Turturesti", comuna: "Girov" },
  { nume: "Ţuţcanii din Deal", simplu: "Tutcanii din Deal", comuna: "Bahna" },
  { nume: "Ţuţcanii din Vale", simplu: "Tutcanii din Vale", comuna: "Bahna" },
  { nume: "Unceşti", simplu: "Uncesti", comuna: "Secuieni" },
  { nume: "Ungheni", comuna: "Raucesti" },
  { nume: "Unghi", comuna: "Dragomiresti" },
  { nume: "Urecheni" },
  { nume: "Vad", comuna: "Dragomiresti" },
  { nume: "Vădurele", simplu: "Vadurele", comuna: "Alexandru Cel Bun" },
  { nume: "Vădurele", simplu: "Vadurele", comuna: "Candesti" },
  { nume: "Vaduri", comuna: "Alexandru Cel Bun" },
  { nume: "Valea Albă", simplu: "Valea Alba", comuna: "Razboieni" },
  { nume: "Valea Arini", comuna: "Baltatesti" },
  { nume: "Valea Enei", comuna: "Oniceni" },
  { nume: "Valea Mare", comuna: "Razboieni" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Baltatesti" },
  { nume: "Valea Ursului" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Botesti" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Piatra Neamt" },
  { nume: "Vânători-Neamţ", simplu: "Vanatori-Neamt" },
  { nume: "Varatec", comuna: "Agapia" },
  { nume: "Veja", comuna: "Stanita" },
  { nume: "Verşeşti", simplu: "Versesti", comuna: "Girov" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Alexandru Cel Bun" },
  { nume: "Vlădiceni", simplu: "Vladiceni", comuna: "Bargauani" },
  { nume: "Vlădnicele", simplu: "Vladnicele", comuna: "Stanita" },
  { nume: "Vulpăşeşti", simplu: "Vulpasesti", comuna: "Sagna" },
  { nume: "Zăneşti", simplu: "Zanesti" },
  { nume: "Zvorăneşti", simplu: "Zvoranesti", comuna: "Timisesti" },
];
