export const nt = [
  { nume: "Agapia" },
  { nume: "Bahna" },
  { nume: "Bicaz" },
  { nume: "Bicaz-Chei" },
  { nume: "Bicazu Ardelean" },
  { nume: "Bira" },
  { nume: "Bodesti" },
  { nume: "Borca" },
  { nume: "Borlesti" },
  { nume: "Botesti" },
  { nume: "Bozieni" },
  { nume: "Bargauani" },
  { nume: "Baltatesti" },
  { nume: "Ceahlau" },
  { nume: "Cordun" },
  { nume: "Costisa" },
  { nume: "Cracaoani" },
  { nume: "Candesti" },
  { nume: "Dobreni" },
  { nume: "Dochia" },
  { nume: "Doljesti" },
  { nume: "Dragomiresti" },
  { nume: "Dulcesti" },
  { nume: "Dumbrava Rosie" },
  { nume: "Damuc" },
  { nume: "Farcasa" },
  { nume: "Faurei" },
  { nume: "Gheraesti" },
  { nume: "Ghindaoani" },
  { nume: "Girov" },
  { nume: "Grinties" },
  { nume: "Grumazesti" },
  { nume: "Garcina" },
  { nume: "Hangu" },
  { nume: "Horia" },
  { nume: "Icusesti" },
  { nume: "Ion Creanga" },
  { nume: "Moldoveni" },
  { nume: "Margineni" },
  { nume: "Oniceni" },
  { nume: "Petricani" },
  { nume: "Piatra Soimului" },
  { nume: "Pipirig" },
  { nume: "Podoleni" },
  { nume: "Poiana Teiului" },
  { nume: "Poienari" },
  { nume: "Pangarati" },
  { nume: "Pastraveni" },
  { nume: "Rediu" },
  { nume: "Roman" },
  { nume: "Romani" },
  { nume: "Roznov" },
  { nume: "Ruginoasa" },
  { nume: "Raucesti" },
  { nume: "Razboieni" },
  { nume: "Sagna" },
  { nume: "Secuieni" },
  { nume: "Stanita" },
  { nume: "Sabaoani" },
  { nume: "Savinesti" },
  { nume: "Tarcau" },
  { nume: "Tazlau" },
  { nume: "Tasca" },
  { nume: "Timisesti" },
  { nume: "Trifesti" },
  { nume: "Tupilati" },
  { nume: "Targu Neamt" },
  { nume: "Tamaseni" },
  { nume: "Urecheni" },
  { nume: "Valea Ursului" },
  { nume: "Vanatori-Neamt" },
  { nume: "Zanesti" },
  { nume: "Stefan cel Mare" },
  { nume: "Tibucani" },
  { nume: "Filioara", comuna: "Agapia" },
  { nume: "Sacalusesti", comuna: "Agapia" },
  { nume: "Varatec", comuna: "Agapia" },
  { nume: "Agarcia", comuna: "Alexandru Cel Bun" },
  { nume: "Bisericani", comuna: "Alexandru Cel Bun" },
  { nume: "Bistrita", comuna: "Alexandru Cel Bun" },
  { nume: "Scaricica", comuna: "Alexandru Cel Bun" },
  { nume: "Vaduri", comuna: "Alexandru Cel Bun" },
  { nume: "Viisoara", comuna: "Alexandru Cel Bun" },
  { nume: "Vadurele", comuna: "Alexandru Cel Bun" },
  { nume: "Aramesti", comuna: "Bahna" },
  { nume: "Brosteni", comuna: "Bahna" },
  { nume: "Bahnisoara", comuna: "Bahna" },
  { nume: "Izvoare", comuna: "Bahna" },
  { nume: "Liliac", comuna: "Bahna" },
  { nume: "Tutcanii din Deal", comuna: "Bahna" },
  { nume: "Tutcanii din Vale", comuna: "Bahna" },
  { nume: "Valea Arini", comuna: "Baltatesti" },
  { nume: "Valea Seaca", comuna: "Baltatesti" },
  { nume: "Bahna Mare", comuna: "Bargauani" },
  { nume: "Baratca", comuna: "Bargauani" },
  { nume: "Breaza", comuna: "Bargauani" },
  { nume: "Balanesti", comuna: "Bargauani" },
  { nume: "Certieni", comuna: "Bargauani" },
  { nume: "Chilia", comuna: "Bargauani" },
  { nume: "Darloaia", comuna: "Bargauani" },
  { nume: "Ghelaiesti", comuna: "Bargauani" },
  { nume: "Homiceni", comuna: "Bargauani" },
  { nume: "Hartop", comuna: "Bargauani" },
  { nume: "Talpa", comuna: "Bargauani" },
  { nume: "Vladiceni", comuna: "Bargauani" },
  { nume: "Capsa", comuna: "Bicaz" },
  { nume: "Dodeni", comuna: "Bicaz" },
  { nume: "Izvoru Muntelui", comuna: "Bicaz" },
  { nume: "Izvorul Alb", comuna: "Bicaz" },
  { nume: "Potoci", comuna: "Bicaz" },
  { nume: "Secu", comuna: "Bicaz" },
  { nume: "Barnadu", comuna: "Bicaz-Chei" },
  { nume: "Gherman", comuna: "Bicaz-Chei" },
  { nume: "Ivanes", comuna: "Bicaz-Chei" },
  { nume: "Telec", comuna: "Bicazu Ardelean" },
  { nume: "Ticos", comuna: "Bicazu Ardelean" },
  { nume: "Boghicea", comuna: "Bira" },
  { nume: "Causeni", comuna: "Bira" },
  { nume: "Negresti", comuna: "Bira" },
  { nume: "Nistria", comuna: "Bira" },
  { nume: "Rediu", comuna: "Bira" },
  { nume: "Slobozia", comuna: "Bira" },
  { nume: "Bodestii de Jos", comuna: "Bodesti" },
  { nume: "Corni", comuna: "Bodesti" },
  { nume: "Oslobeni", comuna: "Bodesti" },
  { nume: "Lunca", comuna: "Borca" },
  { nume: "Madei", comuna: "Borca" },
  { nume: "Paraul Carjei", comuna: "Borca" },
  { nume: "Paraul Pantei", comuna: "Borca" },
  { nume: "Sabasa", comuna: "Borca" },
  { nume: "Soci", comuna: "Borca" },
  { nume: "Mastacan", comuna: "Borlesti" },
  { nume: "Nechit", comuna: "Borlesti" },
  { nume: "Ruseni", comuna: "Borlesti" },
  { nume: "Sovoaia", comuna: "Borlesti" },
  { nume: "Barticesti", comuna: "Botesti" },
  { nume: "David", comuna: "Botesti" },
  { nume: "Moreni", comuna: "Botesti" },
  { nume: "Munteni", comuna: "Botesti" },
  { nume: "Nisiporesti", comuna: "Botesti" },
  { nume: "Valeni", comuna: "Botesti" },
  { nume: "Baneasa", comuna: "Bozieni" },
  { nume: "Craiesti", comuna: "Bozieni" },
  { nume: "Cuci", comuna: "Bozieni" },
  { nume: "Iucsa", comuna: "Bozieni" },
  { nume: "Brusturi", comuna: "Brusturi-Draganesti" },
  { nume: "Draganesti", comuna: "Brusturi-Draganesti" },
  { nume: "Grosi", comuna: "Brusturi-Draganesti" },
  { nume: "Ortasti", comuna: "Brusturi-Draganesti" },
  { nume: "Poiana", comuna: "Brusturi-Draganesti" },
  { nume: "Rasca", comuna: "Brusturi-Draganesti" },
  { nume: "Tarzia", comuna: "Brusturi-Draganesti" },
  { nume: "Soimaresti", comuna: "Brusturi-Draganesti" },
  { nume: "Barcanesti", comuna: "Candesti" },
  { nume: "Dragova", comuna: "Candesti" },
  { nume: "Padureni", comuna: "Candesti" },
  { nume: "Vadurele", comuna: "Candesti" },
  { nume: "Tardenii Mici", comuna: "Candesti" },
  { nume: "Bistricioara", comuna: "Ceahlau" },
  { nume: "Paraul Mare", comuna: "Ceahlau" },
  { nume: "Pildesti", comuna: "Cordun" },
  { nume: "Simionesti", comuna: "Cordun" },
  { nume: "Dornesti", comuna: "Costisa" },
  { nume: "Frunzeni", comuna: "Costisa" },
  { nume: "Manoaia", comuna: "Costisa" },
  { nume: "Cracaul Negru", comuna: "Cracaoani" },
  { nume: "Magazia", comuna: "Cracaoani" },
  { nume: "Mitocu Balan", comuna: "Cracaoani" },
  { nume: "Poiana Cracaoani", comuna: "Cracaoani" },
  { nume: "Huisurez", comuna: "Damuc" },
  { nume: "Trei Fantani", comuna: "Damuc" },
  { nume: "Casaria", comuna: "Dobreni" },
  { nume: "Negresti", comuna: "Dobreni" },
  { nume: "Poiana", comuna: "Dobreni" },
  { nume: "Sarata", comuna: "Dobreni" },
  { nume: "Balusesti", comuna: "Dochia" },
  { nume: "Buhonca", comuna: "Doljesti" },
  { nume: "Buruienesti", comuna: "Doljesti" },
  { nume: "Rotunda", comuna: "Doljesti" },
  { nume: "Bornis", comuna: "Dragomiresti" },
  { nume: "Hlapesti", comuna: "Dragomiresti" },
  { nume: "Mastacan", comuna: "Dragomiresti" },
  { nume: "Unghi", comuna: "Dragomiresti" },
  { nume: "Vad", comuna: "Dragomiresti" },
  { nume: "Britcani", comuna: "Dulcesti" },
  { nume: "Corhana", comuna: "Dulcesti" },
  { nume: "Carlig", comuna: "Dulcesti" },
  { nume: "Poiana", comuna: "Dulcesti" },
  { nume: "Rosiori", comuna: "Dulcesti" },
  { nume: "Brasauti", comuna: "Dumbrava Rosie" },
  { nume: "Cut", comuna: "Dumbrava Rosie" },
  { nume: "Izvoare", comuna: "Dumbrava Rosie" },
  { nume: "Busmei", comuna: "Farcasa" },
  { nume: "Frumosu", comuna: "Farcasa" },
  { nume: "Popesti", comuna: "Farcasa" },
  { nume: "Stejaru", comuna: "Farcasa" },
  { nume: "Budesti", comuna: "Faurei" },
  { nume: "Climesti", comuna: "Faurei" },
  { nume: "Micsunesti", comuna: "Faurei" },
  { nume: "Almas", comuna: "Garcina" },
  { nume: "Cuejdiu", comuna: "Garcina" },
  { nume: "Gheraestii Noi", comuna: "Gheraesti" },
  { nume: "Tetcani", comuna: "Gheraesti" },
  { nume: "Botesti", comuna: "Girov" },
  { nume: "Caciulesti", comuna: "Girov" },
  { nume: "Doina", comuna: "Girov" },
  { nume: "Danesti", comuna: "Girov" },
  { nume: "Gura Vaii", comuna: "Girov" },
  { nume: "Popesti", comuna: "Girov" },
  { nume: "Turturesti", comuna: "Girov" },
  { nume: "Versesti", comuna: "Girov" },
  { nume: "Bradu", comuna: "Grinties" },
  { nume: "Poiana", comuna: "Grinties" },
  { nume: "Curechistea", comuna: "Grumazesti" },
  { nume: "Netezi", comuna: "Grumazesti" },
  { nume: "Topolita", comuna: "Grumazesti" },
  { nume: "Buhalnita", comuna: "Hangu" },
  { nume: "Chiriteni", comuna: "Hangu" },
  { nume: "Grozavesti", comuna: "Hangu" },
  { nume: "Ruginesti", comuna: "Hangu" },
  { nume: "Cotu Vames", comuna: "Horia" },
  { nume: "Balusesti", comuna: "Icusesti" },
  { nume: "Batranesti", comuna: "Icusesti" },
  { nume: "Mesteacan", comuna: "Icusesti" },
  { nume: "Rocna", comuna: "Icusesti" },
  { nume: "Spiridonesti", comuna: "Icusesti" },
  { nume: "Tabara", comuna: "Icusesti" },
  { nume: "Averesti", comuna: "Ion Creanga" },
  { nume: "Izvoru", comuna: "Ion Creanga" },
  { nume: "Muncelu", comuna: "Ion Creanga" },
  { nume: "Recea", comuna: "Ion Creanga" },
  { nume: "Stejaru", comuna: "Ion Creanga" },
  { nume: "Hoisesti", comuna: "Margineni" },
  { nume: "Hartesti", comuna: "Margineni" },
  { nume: "Itrinesti", comuna: "Margineni" },
  { nume: "Hociungi", comuna: "Moldoveni" },
  { nume: "Ciornei", comuna: "Oniceni" },
  { nume: "Gorun", comuna: "Oniceni" },
  { nume: "Linsesti", comuna: "Oniceni" },
  { nume: "Lunca", comuna: "Oniceni" },
  { nume: "Marmureni", comuna: "Oniceni" },
  { nume: "Pietrosu", comuna: "Oniceni" },
  { nume: "Poiana Humei", comuna: "Oniceni" },
  { nume: "Pustieta", comuna: "Oniceni" },
  { nume: "Solca", comuna: "Oniceni" },
  { nume: "Valea Enei", comuna: "Oniceni" },
  { nume: "Oantu", comuna: "Pangarati" },
  { nume: "Poiana", comuna: "Pangarati" },
  { nume: "Preluca", comuna: "Pangarati" },
  { nume: "Pangaracior", comuna: "Pangarati" },
  { nume: "Stejaru", comuna: "Pangarati" },
  { nume: "Lunca Moldovei", comuna: "Pastraveni" },
  { nume: "Radeni", comuna: "Pastraveni" },
  { nume: "Spiesti", comuna: "Pastraveni" },
  { nume: "Boistea", comuna: "Petricani" },
  { nume: "Tarpesti", comuna: "Petricani" },
  { nume: "Tolici", comuna: "Petricani" },
  { nume: "Ciritei", comuna: "Piatra Neamt" },
  { nume: "Doamna", comuna: "Piatra Neamt" },
  { nume: "Piatra-Neamt", comuna: "Piatra Neamt" },
  { nume: "Valeni", comuna: "Piatra Neamt" },
  { nume: "Luminis", comuna: "Piatra Soimului" },
  { nume: "Negulesti", comuna: "Piatra Soimului" },
  { nume: "Poieni", comuna: "Piatra Soimului" },
  { nume: "Boboiesti", comuna: "Pipirig" },
  { nume: "Dolhesti", comuna: "Pipirig" },
  { nume: "Leghin", comuna: "Pipirig" },
  { nume: "Pluton", comuna: "Pipirig" },
  { nume: "Pataligeni", comuna: "Pipirig" },
  { nume: "Stanca", comuna: "Pipirig" },
  { nume: "Negritesti", comuna: "Podoleni" },
  { nume: "Calugareni", comuna: "Poiana Teiului" },
  { nume: "Dreptu", comuna: "Poiana Teiului" },
  { nume: "Galu", comuna: "Poiana Teiului" },
  { nume: "Petru Voda", comuna: "Poiana Teiului" },
  { nume: "Poiana Largului", comuna: "Poiana Teiului" },
  { nume: "Paraul Fagului", comuna: "Poiana Teiului" },
  { nume: "Roseni", comuna: "Poiana Teiului" },
  { nume: "Ruseni", comuna: "Poiana Teiului" },
  { nume: "Savinesti", comuna: "Poiana Teiului" },
  { nume: "Topoliceni", comuna: "Poiana Teiului" },
  { nume: "Bunghi", comuna: "Poienari" },
  { nume: "Ciurea", comuna: "Poienari" },
  { nume: "Holm", comuna: "Poienari" },
  { nume: "Patricheni", comuna: "Poienari" },
  { nume: "Pancesti", comuna: "Poienari" },
  { nume: "Sacaleni", comuna: "Poienari" },
  { nume: "Talpalai", comuna: "Poienari" },
  { nume: "Oglinzi", comuna: "Raucesti" },
  { nume: "Savesti", comuna: "Raucesti" },
  { nume: "Ungheni", comuna: "Raucesti" },
  { nume: "Borseni", comuna: "Razboieni" },
  { nume: "Razboienii de Jos", comuna: "Razboieni" },
  { nume: "Valea Alba", comuna: "Razboieni" },
  { nume: "Valea Mare", comuna: "Razboieni" },
  { nume: "Betesti", comuna: "Rediu" },
  { nume: "Poloboc", comuna: "Rediu" },
  { nume: "Socea", comuna: "Rediu" },
  { nume: "Gosmani", comuna: "Romani" },
  { nume: "Silistea", comuna: "Romani" },
  { nume: "Chintinici", comuna: "Roznov" },
  { nume: "Slobozia", comuna: "Roznov" },
  { nume: "Bozienii de Sus", comuna: "Ruginoasa" },
  { nume: "Traian", comuna: "Sabaoani" },
  { nume: "Gadinti", comuna: "Sagna" },
  { nume: "Lutca", comuna: "Sagna" },
  { nume: "Vulpasesti", comuna: "Sagna" },
  { nume: "Dumbrava Deal", comuna: "Savinesti" },
  { nume: "Basta", comuna: "Secuieni" },
  { nume: "Bogzesti", comuna: "Secuieni" },
  { nume: "Butnaresti", comuna: "Secuieni" },
  { nume: "Barjoveni", comuna: "Secuieni" },
  { nume: "Giulesti", comuna: "Secuieni" },
  { nume: "Prajesti", comuna: "Secuieni" },
  { nume: "Secuienii Noi", comuna: "Secuieni" },
  { nume: "Uncesti", comuna: "Secuieni" },
  { nume: "Chicerea", comuna: "Stanita" },
  { nume: "Ghidion", comuna: "Stanita" },
  { nume: "Poienile Oancei", comuna: "Stanita" },
  { nume: "Todireni", comuna: "Stanita" },
  { nume: "Veja", comuna: "Stanita" },
  { nume: "Vladnicele", comuna: "Stanita" },
  { nume: "Bordea", comuna: "Stefan Cel Mare" },
  { nume: "Carligi", comuna: "Stefan Cel Mare" },
  { nume: "Deleni", comuna: "Stefan Cel Mare" },
  { nume: "Dusesti", comuna: "Stefan Cel Mare" },
  { nume: "Ghigoiesti", comuna: "Stefan Cel Mare" },
  { nume: "Soci", comuna: "Stefan Cel Mare" },
  { nume: "Adjudeni", comuna: "Tamaseni" },
  { nume: "Ardeluta", comuna: "Tarcau" },
  { nume: "Brates", comuna: "Tarcau" },
  { nume: "Cazaci", comuna: "Tarcau" },
  { nume: "Schitu Tarcau", comuna: "Tarcau" },
  { nume: "Straja", comuna: "Tarcau" },
  { nume: "Blebea", comuna: "Targu Neamt" },
  { nume: "Humulesti", comuna: "Targu Neamt" },
  { nume: "Humulestii Noi", comuna: "Targu Neamt" },
  { nume: "Hamzoaia", comuna: "Tasca" },
  { nume: "Neagra", comuna: "Tasca" },
  { nume: "Ticos-Floarea", comuna: "Tasca" },
  { nume: "Davideni", comuna: "Tibucani" },
  { nume: "Tibucanii de Jos", comuna: "Tibucani" },
  { nume: "Dumbrava", comuna: "Timisesti" },
  { nume: "Plaiesu", comuna: "Timisesti" },
  { nume: "Preutesti", comuna: "Timisesti" },
  { nume: "Zvoranesti", comuna: "Timisesti" },
  { nume: "Miron Costin", comuna: "Trifesti" },
  { nume: "Aramoaia", comuna: "Tupilati" },
  { nume: "Hanul Ancutei", comuna: "Tupilati" },
  { nume: "Totoiesti", comuna: "Tupilati" },
  { nume: "Ingaresti", comuna: "Urecheni" },
  { nume: "Plugari", comuna: "Urecheni" },
  { nume: "Bucium", comuna: "Valea Ursului" },
  { nume: "Chilii", comuna: "Valea Ursului" },
  { nume: "Giurgeni", comuna: "Valea Ursului" },
  { nume: "Muncelu de Jos", comuna: "Valea Ursului" },
  { nume: "Lunca", comuna: "Vanatori-Neamt" },
  { nume: "Manastirea Neamt", comuna: "Vanatori-Neamt" },
  { nume: "Nemtisor", comuna: "Vanatori-Neamt" },
  { nume: "Traian", comuna: "Zanesti" },
];
