export const ot = [
  { nume: "Afumați", simplu: "Afumati", comuna: "Leleasca" },
  { nume: "Albești", simplu: "Albesti", comuna: "Poboru" },
  { nume: "Alimănești", simplu: "Alimanesti", comuna: "Izvoarele" },
  { nume: "Alunișu", simplu: "Alunisu", comuna: "Spineni" },
  { nume: "Arcești Cot", simplu: "Arcesti Cot", comuna: "Plesoiu" },
  { nume: "Arcești", simplu: "Arcesti", comuna: "Plesoiu" },
  { nume: "Arvăteasca", simplu: "Arvateasca", comuna: "Studina" },
  { nume: "Băbiciu", simplu: "Babiciu" },
  { nume: "Bacea", comuna: "Movileni" },
  { nume: "Bâgești", simplu: "Bagesti", comuna: "Fagetelu" },
  { nume: "Bălănești", simplu: "Balanesti", comuna: "Maruntei" },
  { nume: "Baldovinești", simplu: "Baldovinesti" },
  { nume: "Băleasa", simplu: "Baleasa", comuna: "Baldovinesti" },
  { nume: "Balș", simplu: "Bals" },
  { nume: "Bălțați", simplu: "Baltati", comuna: "Scornicesti" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Perieti" },
  { nume: "Bărăști", simplu: "Barasti", comuna: "Colonesti" },
  { nume: "Bărăști", simplu: "Barasti", comuna: "Morunglav" },
  {
    nume: "Bărăștii de Cepturi",
    simplu: "Barastii de Cepturi",
    comuna: "Barasti",
  },
  { nume: "Bărăștii de Vede", simplu: "Barastii de Vede", comuna: "Barasti" },
  { nume: "Bărbălăi", simplu: "Barbalai", comuna: "Tatulesti" },
  { nume: "Bârca", simplu: "Barca", comuna: "Valea Mare" },
  { nume: "Bărcănești", simplu: "Barcanesti", comuna: "Valcele" },
  {
    nume: "Bârseștii de Sus",
    simplu: "Barsestii de Sus",
    comuna: "Sprancenata",
  },
  { nume: "Barza", comuna: "Tufeni" },
  { nume: "Bârza", simplu: "Barza" },
  { nume: "Bătăreni", simplu: "Batareni", comuna: "Colonesti" },
  { nume: "Batia", comuna: "Dobroteasa" },
  { nume: "Bechet", comuna: "Bobicesti" },
  { nume: "Beculești", simplu: "Beculesti", comuna: "Carlogani" },
  { nume: "Belgun", comuna: "Bobicesti" },
  { nume: "Beria de Jos", comuna: "Oporelu" },
  { nume: "Beria de Sus", comuna: "Oporelu" },
  { nume: "Berindei", comuna: "Daneasa" },
  { nume: "Bircii", comuna: "Scornicesti" },
  { nume: "Bistrița Nouă", simplu: "Bistrita Noua", comuna: "Piatra-Olt" },
  { nume: "Blaj", comuna: "Voineasa" },
  { nume: "Bobicești", simplu: "Bobicesti" },
  { nume: "Bobu", comuna: "Dobrun" },
  { nume: "Bondrea", comuna: "Cezieni" },
  { nume: "Boroești", simplu: "Boroesti", comuna: "Barasti" },
  { nume: "Brâncoveni", simplu: "Brancoveni" },
  { nume: "Braneț", simplu: "Branet", comuna: "Barza" },
  { nume: "Brastavățu", simplu: "Brastavatu" },
  { nume: "Brebeni" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Baldovinesti" },
  { nume: "Bucinișu Mic", simplu: "Bucinisu Mic", comuna: "Bucinisu" },
  { nume: "Bucinișu", simplu: "Bucinisu" },
  { nume: "Buicești", simplu: "Buicesti", comuna: "Priseaca" },
  { nume: "Bulimanu", comuna: "Vitomiresti" },
  { nume: "Burdulești", simplu: "Burdulesti", comuna: "Corbu" },
  { nume: "Bușca", simplu: "Busca", comuna: "Mihaesti" },
  { nume: "Buta", comuna: "Crampoia" },
  { nume: "Butoi", comuna: "Parscoveni" },
  { nume: "Buzești", simplu: "Buzesti", comuna: "Corbu" },
  { nume: "Călinești", simplu: "Calinesti", comuna: "Radomiresti" },
  { nume: "Călui", simplu: "Calui", comuna: "Oboga" },
  { nume: "Câmpu Mare", simplu: "Campu Mare", comuna: "Dobroteasa" },
  { nume: "Câmpu Părului", simplu: "Campu Parului", comuna: "Obarsia" },
  { nume: "Cândelești", simplu: "Candelesti", comuna: "Topana" },
  { nume: "Caracal" },
  { nume: "Cârlogani", simplu: "Carlogani" },
  { nume: "Cârstani", simplu: "Carstani", comuna: "Colonesti" },
  { nume: "Catanele", comuna: "Schitu" },
  { nume: "Căzănești", simplu: "Cazanesti", comuna: "Verguleasa" },
  { nume: "Cepari", comuna: "Carlogani" },
  { nume: "Cepești", simplu: "Cepesti", comuna: "Cungrea" },
  { nume: "Cerbeni", comuna: "Samburesti" },
  { nume: "Cezieni" },
  { nume: "Chelbești", simplu: "Chelbesti", comuna: "Colonesti" },
  {
    nume: "Cherleștii din Deal",
    simplu: "Cherlestii din Deal",
    comuna: "Teslui",
  },
  {
    nume: "Cherleștii Moșteni",
    simplu: "Cherlestii Mosteni",
    comuna: "Teslui",
  },
  { nume: "Chilia", comuna: "Fagetelu" },
  { nume: "Chilii", comuna: "Dobrun" },
  { nume: "Chintești", simplu: "Chintesti", comuna: "Bobicesti" },
  { nume: "Chițeasca", simplu: "Chiteasca", comuna: "Scornicesti" },
  { nume: "Cilieni" },
  { nume: "Ciocănești", simplu: "Ciocanesti", comuna: "Barasti" },
  { nume: "Cioflanu", comuna: "Daneasa" },
  { nume: "Ciorâca", simplu: "Cioraca", comuna: "Topana" },
  { nume: "Cioroiașu", simplu: "Cioroiasu", comuna: "Falcoiu" },
  { nume: "Cioroiu", comuna: "Falcoiu" },
  { nume: "Cireașov", simplu: "Cireasov", comuna: "Slatina" },
  { nume: "Ciurești", simplu: "Ciuresti", comuna: "Corbu" },
  { nume: "Cocorăști", simplu: "Cocorasti", comuna: "Plesoiu" },
  { nume: "Cojgărei", simplu: "Cojgarei", comuna: "Topana" },
  { nume: "Colibași", simplu: "Colibasi", comuna: "Strejesti" },
  { nume: "Colonești", simplu: "Colonesti" },
  { nume: "Comanca", comuna: "Deveselu" },
  { nume: "Comănești", simplu: "Comanesti", comuna: "Bobicesti" },
  { nume: "Comani", comuna: "Draganesti-Olt" },
  { nume: "Comănița", simplu: "Comanita", comuna: "Teslui" },
  { nume: "Constantinești", simplu: "Constantinesti", comuna: "Scornicesti" },
  { nume: "Corabia" },
  { nume: "Corbeni", comuna: "Bals" },
  { nume: "Corbu" },
  { nume: "Corbu", comuna: "Teslui" },
  { nume: "Corlătești", simplu: "Corlatesti", comuna: "Cezieni" },
  { nume: "Cornățelu", simplu: "Cornatelu", comuna: "Poboru" },
  { nume: "Coteana" },
  { nume: "Coteni", comuna: "Obarsia" },
  { nume: "Cotorbești", simplu: "Cotorbesti", comuna: "Vulpeni" },
  { nume: "Crăciunei", simplu: "Craciunei", comuna: "Radomiresti" },
  { nume: "Crâmpoia", simplu: "Crampoia" },
  { nume: "Creți", simplu: "Creti", comuna: "Poboru" },
  { nume: "Criva de Jos", comuna: "Piatra-Olt" },
  { nume: "Criva de Sus", comuna: "Piatra-Olt" },
  { nume: "Crușovu", simplu: "Crusovu", comuna: "Brastavatu" },
  { nume: "Cucueți", simplu: "Cucueti", comuna: "Verguleasa" },
  { nume: "Cungrea" },
  { nume: "Curtișoara", simplu: "Curtisoara" },
  { nume: "Curtișoara", simplu: "Curtisoara", comuna: "Dobretu" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Spineni" },
  { nume: "Dâmburile", simplu: "Damburile", comuna: "Baldovinesti" },
  { nume: "Dăneasa", simplu: "Daneasa" },
  { nume: "Davidești", simplu: "Davidesti", comuna: "Spineni" },
  { nume: "Dejești", simplu: "Dejesti", comuna: "Vitomiresti" },
  { nume: "Deleni", comuna: "Teslui" },
  { nume: "Deveselu" },
  { nume: "Dienci", comuna: "Vulturesti" },
  { nume: "Doanca", comuna: "Tia Mare" },
  { nume: "Doba", comuna: "Plesoiu" },
  { nume: "Dobrețu", simplu: "Dobretu" },
  { nume: "Dobriceni", comuna: "Iancu Jianu" },
  { nume: "Dobrosloveni" },
  { nume: "Dobroteasa" },
  { nume: "Dobrotinet", comuna: "Curtisoara" },
  { nume: "Dobrun" },
  { nume: "Donești", simplu: "Donesti", comuna: "Vitomiresti" },
  { nume: "Drăgănești-Olt", simplu: "Draganesti-Olt" },
  { nume: "Drăghiceni", simplu: "Draghiceni" },
  { nume: "Dranovățu", simplu: "Dranovatu", comuna: "Ganeasa" },
  { nume: "Dumitrești", simplu: "Dumitresti", comuna: "Verguleasa" },
  { nume: "Enoșești", simplu: "Enosesti", comuna: "Piatra-Olt" },
  { nume: "Făgețelu", simplu: "Fagetelu" },
  { nume: "Fălcoiu", simplu: "Falcoiu" },
  { nume: "Fărcașele", simplu: "Farcasele" },
  { nume: "Fărcașu de Jos", simplu: "Farcasu de Jos", comuna: "Farcasele" },
  { nume: "Floru", comuna: "Icoana" },
  { nume: "Frăsinet Gară", simplu: "Frasinet Gara", comuna: "Vladila" },
  { nume: "Frăsinetu", simplu: "Frasinetu", comuna: "Dobrosloveni" },
  { nume: "Frunzaru", comuna: "Sprancenata" },
  { nume: "Găneasa", simplu: "Ganeasa" },
  { nume: "Gârcov", simplu: "Garcov" },
  { nume: "Găvănești", simplu: "Gavanesti", comuna: "Baldovinesti" },
  { nume: "Ghimpați", simplu: "Ghimpati", comuna: "Farcasele" },
  { nume: "Ghimpețeni", simplu: "Ghimpeteni", comuna: "Nicolae Titulescu" },
  {
    nume: "Ghimpețenii Noi",
    simplu: "Ghimpetenii Noi",
    comuna: "Nicolae Titulescu",
  },
  { nume: "Ghioșani", simplu: "Ghiosani", comuna: "Morunglav" },
  { nume: "Giuvărăști", simplu: "Giuvarasti" },
  { nume: "Gostavățu", simplu: "Gostavatu" },
  { nume: "Govora", comuna: "Bobicesti" },
  { nume: "Grădinari", simplu: "Gradinari" },
  { nume: "Grădinile", simplu: "Gradinile", comuna: "Studina" },
  { nume: "Grădiștea", simplu: "Gradistea", comuna: "Ganeasa" },
  { nume: "Greci", comuna: "Osica De Sus" },
  { nume: "Greci", comuna: "Schitu" },
  { nume: "Greerești", simplu: "Greeresti", comuna: "Leleasca" },
  { nume: "Grojdibodu" },
  { nume: "Gropșani", simplu: "Gropsani", comuna: "Vulpeni" },
  { nume: "Grozăvești", simplu: "Grozavesti", comuna: "Draghiceni" },
  { nume: "Gruiu", comuna: "Fagetelu" },
  { nume: "Gubandru", comuna: "Baldovinesti" },
  { nume: "Guești", simplu: "Guesti", comuna: "Colonesti" },
  { nume: "Gura Căluiu", simplu: "Gura Caluiu", comuna: "Oboga" },
  { nume: "Gura Padinii", comuna: "Orlea" },
  { nume: "Horezu", comuna: "Dobretu" },
  { nume: "Hotărani", simplu: "Hotarani", comuna: "Farcasele" },
  { nume: "Hotaru", comuna: "Grojdibodu" },
  { nume: "Ianca Nouă", simplu: "Ianca Noua", comuna: "Stefan Cel Mare" },
  { nume: "Ianca" },
  { nume: "Iancu Jianu" },
  { nume: "Ibănești", simplu: "Ibanesti", comuna: "Cungrea" },
  { nume: "Icoana" },
  { nume: "Ionicești", simplu: "Ionicesti", comuna: "Samburesti" },
  { nume: "Ipotești", simplu: "Ipotesti", comuna: "Milcov" },
  { nume: "Isaci", comuna: "Fagetelu" },
  { nume: "Izbiceni" },
  { nume: "Izvoarele" },
  { nume: "Izvoru", comuna: "Ganeasa" },
  { nume: "Jieni", comuna: "Rusanesti" },
  { nume: "Jitaru", comuna: "Scornicesti" },
  { nume: "Lăunele", simplu: "Launele", comuna: "Samburesti" },
  { nume: "Lăzărești", simplu: "Lazaresti", comuna: "Barasti" },
  { nume: "Leleasca" },
  { nume: "Leotești", simplu: "Leotesti", comuna: "Bobicesti" },
  { nume: "Liiceni", comuna: "Draghiceni" },
  { nume: "Linia din Vale", comuna: "Curtisoara" },
  { nume: "Lisa", comuna: "Schitu" },
  { nume: "Lunca", comuna: "Tatulesti" },
  { nume: "Măgura", simplu: "Magura", comuna: "Perieti" },
  { nume: "Măgura", simplu: "Magura", comuna: "Tatulesti" },
  { nume: "Malu Roșu", simplu: "Malu Rosu", comuna: "Maruntei" },
  { nume: "Mamura", comuna: "Strejesti" },
  { nume: "Mandra", comuna: "Valeni" },
  { nume: "Mănulești", simplu: "Manulesti", comuna: "Samburesti" },
  { nume: "Mardale", comuna: "Vulpeni" },
  { nume: "Mărgăritești", simplu: "Margaritesti", comuna: "Voineasa" },
  { nume: "Mărgheni", simplu: "Margheni", comuna: "Brancoveni" },
  {
    nume: "Mărgineni Slobozia",
    simplu: "Margineni Slobozia",
    comuna: "Scornicesti",
  },
  { nume: "Mărunței", simplu: "Maruntei" },
  { nume: "Mărunței", simplu: "Maruntei", comuna: "Colonesti" },
  { nume: "Mereni", comuna: "Barasti" },
  { nume: "Mierleștii de Sus", simplu: "Mierlestii de Sus", comuna: "Perieti" },
  { nume: "Mierlicești", simplu: "Mierlicesti", comuna: "Leleasca" },
  { nume: "Miești", simplu: "Miesti", comuna: "Cungrea" },
  { nume: "Mihăești", simplu: "Mihaesti" },
  {
    nume: "Mihăilești Popești",
    simplu: "Mihailesti Popesti",
    comuna: "Scornicesti",
  },
  { nume: "Milcoveni", comuna: "Corbu" },
  { nume: "Milcovu din Deal", comuna: "Milcov" },
  { nume: "Milcovu din Vale", comuna: "Milcov" },
  { nume: "Mircești", simplu: "Mircesti", comuna: "Tatulesti" },
  { nume: "Mirila", comuna: "Bobicesti" },
  { nume: "Mogoșești", simplu: "Mogosesti", comuna: "Scornicesti" },
  { nume: "Momaiu", comuna: "Tatulesti" },
  { nume: "Morunești", simplu: "Morunesti", comuna: "Morunglav" },
  { nume: "Morunglav" },
  { nume: "Moșteni", simplu: "Mosteni", comuna: "Schitu" },
  { nume: "Moțoești", simplu: "Motoesti", comuna: "Barasti" },
  { nume: "Movileni" },
  { nume: "Năvârgeni", simplu: "Navargeni", comuna: "Colonesti" },
  { nume: "Negreni", comuna: "Scornicesti" },
  { nume: "Nicolae Titulescu" },
  { nume: "Obârșia Nouă", simplu: "Obarsia Noua", comuna: "Obarsia" },
  { nume: "Obârșia", simplu: "Obarsia" },
  { nume: "Oboga" },
  { nume: "Ociogi", comuna: "Brancoveni" },
  { nume: "Olari", comuna: "Parscoveni" },
  { nume: "Oltișoru", simplu: "Oltisoru", comuna: "Ganeasa" },
  { nume: "Oporelu" },
  { nume: "Optășani", simplu: "Optasani", comuna: "Spineni" },
  { nume: "Optași", simplu: "Optasi", comuna: "Optasi-Magura" },
  { nume: "Orlea Nouă", simplu: "Orlea Noua", comuna: "Orlea" },
  { nume: "Orlea" },
  { nume: "Osica de Jos", comuna: "Dobrun" },
  { nume: "Osica de Sus" },
  { nume: "Ostrov", comuna: "Osica De Sus" },
  { nume: "Oteștii de Jos", simplu: "Otestii de Jos", comuna: "Cungrea" },
  { nume: "Oteștii de Sus", simplu: "Otestii de Sus", comuna: "Cungrea" },
  { nume: "Peretu", comuna: "Osica De Sus" },
  { nume: "Perieți", simplu: "Perieti" },
  { nume: "Pescărești", simplu: "Pescaresti", comuna: "Vulpeni" },
  { nume: "Pestra", comuna: "Daneasa" },
  { nume: "Petculești", simplu: "Petculesti", comuna: "Gradinari" },
  { nume: "Piatra-Olt" },
  { nume: "Piatra", comuna: "Piatra-Olt" },
  { nume: "Pielcani", comuna: "Fagetelu" },
  { nume: "Pietriș", simplu: "Pietris", comuna: "Baldovinesti" },
  { nume: "Pietrișu", simplu: "Pietrisu", comuna: "Curtisoara" },
  { nume: "Pîrșcoveni", simplu: "Parscoveni", comuna: "Parscoveni" },
  { nume: "Piscani", comuna: "Scornicesti" },
  { nume: "Plăviceanca", simplu: "Plaviceanca", comuna: "Studina" },
  { nume: "Plăviceni", simplu: "Plaviceni", comuna: "Scarisoara" },
  { nume: "Pleșoiu", simplu: "Plesoiu" },
  { nume: "Plopșorelu", simplu: "Plopsorelu", comuna: "Vulpeni" },
  { nume: "Poboru" },
  { nume: "Poganu", comuna: "Verguleasa" },
  { nume: "Poiana Mare", comuna: "Morunglav" },
  { nume: "Poiana", comuna: "Radomiresti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Barasti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Valeni" },
  {
    nume: "Potcoava Fălcoeni",
    simplu: "Potcoava Falcoeni",
    comuna: "Potcoava",
  },
  { nume: "Potcoava" },
  { nume: "Potelu", comuna: "Ianca" },
  { nume: "Potlogeni", comuna: "Tia Mare" },
  { nume: "Potopinu", comuna: "Dobrosloveni" },
  { nume: "Preotești", simplu: "Preotesti", comuna: "Iancu Jianu" },
  { nume: "Prisaca", comuna: "Vulpeni" },
  { nume: "Priseaca" },
  { nume: "Proaspeți", simplu: "Proaspeti", comuna: "Curtisoara" },
  { nume: "Profa", comuna: "Spineni" },
  { nume: "Racovița", simplu: "Racovita", comuna: "Voineasa" },
  { nume: "Rădești", simplu: "Radesti", comuna: "Oporelu" },
  { nume: "Radomirești", simplu: "Radomiresti" },
  { nume: "Raițiu", simplu: "Raitiu", comuna: "Curtisoara" },
  { nume: "Recea", comuna: "Valea Mare" },
  { nume: "Redea" },
  { nume: "Redișoara", simplu: "Redisoara", comuna: "Redea" },
  { nume: "Reșca", simplu: "Resca", comuna: "Dobrosloveni" },
  { nume: "Reșcuța", simplu: "Rescuta", comuna: "Dobrosloveni" },
  { nume: "Româna", simplu: "Romana", comuna: "Bals" },
  { nume: "Roșienii Mari", simplu: "Rosienii Mari", comuna: "Dobrun" },
  { nume: "Roșienii Mici", simplu: "Rosienii Mici", comuna: "Dobrun" },
  { nume: "Rotunda" },
  { nume: "Rudari", comuna: "Scarisoara" },
  { nume: "Runcu Mare", comuna: "Gradinari" },
  { nume: "Rusănești", simplu: "Rusanesti" },
  {
    nume: "Rusăneștii de Sus",
    simplu: "Rusanestii de Sus",
    comuna: "Voineasa",
  },
  { nume: "Rusciori", comuna: "Scornicesti" },
  { nume: "Salcia", comuna: "Slatioara" },
  { nume: "Săltănești", simplu: "Saltanesti", comuna: "Priseaca" },
  { nume: "Sâmburești", simplu: "Samburesti" },
  { nume: "Satu Nou", comuna: "Gradinari" },
  { nume: "Satu Nou", comuna: "Orlea" },
  { nume: "Scărișoara", simplu: "Scarisoara" },
  { nume: "Schitu Deleni", comuna: "Teslui" },
  { nume: "Schitu din Deal", comuna: "Plesoiu" },
  { nume: "Schitu din Vale", comuna: "Plesoiu" },
  { nume: "Schitu" },
  { nume: "Scorbura", comuna: "Carlogani" },
  { nume: "Scornicești", simplu: "Scornicesti" },
  { nume: "Seaca" },
  { nume: "Seaca", comuna: "Poboru" },
  { nume: "Șerbănești", simplu: "Serbanesti" },
  {
    nume: "Șerbăneștii de Sus",
    simplu: "Serbanestii de Sus",
    comuna: "Serbanesti",
  },
  { nume: "Simniceni", comuna: "Vulpeni" },
  { nume: "Sinești", simplu: "Sinesti", comuna: "Potcoava" },
  { nume: "Slatina" },
  { nume: "Slătioara", simplu: "Slatioara" },
  { nume: "Slăveni", simplu: "Slaveni", comuna: "Gostavatu" },
  { nume: "Șopârlița", simplu: "Soparlita", comuna: "Parscoveni" },
  { nume: "Spătaru", simplu: "Spataru", comuna: "Cungrea" },
  { nume: "Spineni" },
  { nume: "Sprâncenata", simplu: "Sprancenata" },
  { nume: "Stănuleasa", simplu: "Stanuleasa", comuna: "Samburesti" },
  { nume: "Stănuleasa", simplu: "Stanuleasa", comuna: "Vitomiresti" },
  { nume: "Stăvaru", simplu: "Stavaru", comuna: "Urzica" },
  { nume: "Ștefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Stejaru", comuna: "Milcov" },
  { nume: "Stoborăști", simplu: "Stoborasti", comuna: "Tufeni" },
  { nume: "Stoenești", simplu: "Stoenesti" },
  { nume: "Stoicănești", simplu: "Stoicanesti" },
  { nume: "Strejești", simplu: "Strejesti" },
  {
    nume: "Strejeștii de Sus",
    simplu: "Strejestii de Sus",
    comuna: "Strejesti",
  },
  { nume: "Strugurelu", comuna: "Serbanesti" },
  { nume: "Studina" },
  { nume: "Studinița", simplu: "Studinita", comuna: "Studina" },
  { nume: "Stupina", comuna: "Carlogani" },
  { nume: "Șuica", simplu: "Suica", comuna: "Scornicesti" },
  { nume: "Surpeni", comuna: "Poboru" },
  { nume: "Tabaci", comuna: "Vulpeni" },
  { nume: "Tabonu", comuna: "Obarsia" },
  { nume: "Tătulești", simplu: "Tatulesti" },
  { nume: "Teiș", simplu: "Teis", comuna: "Bals" },
  { nume: "Teiuș", simplu: "Teius", comuna: "Scornicesti" },
  { nume: "Teiușu", simplu: "Teiusu", comuna: "Brebeni" },
  { nume: "Teslui" },
  { nume: "Tia Mare" },
  { nume: "Tirișneag", simplu: "Tirisneag", comuna: "Valeni" },
  { nume: "Tomeni", comuna: "Osica De Sus" },
  { nume: "Tonești", simplu: "Tonesti", comuna: "Leleasca" },
  { nume: "Tonești", simplu: "Tonesti", comuna: "Samburesti" },
  { nume: "Topana" },
  { nume: "Traian" },
  { nume: "Trepteni", comuna: "Vitomiresti" },
  { nume: "Trufinești", simplu: "Trufinesti", comuna: "Potcoava" },
  { nume: "Tudor Vladimirescu", comuna: "Corabia" },
  { nume: "Tufaru", comuna: "Leleasca" },
  { nume: "Tufeni" },
  { nume: "Turia", comuna: "Valea Mare" },
  { nume: "Ulmet", comuna: "Dobrun" },
  { nume: "Ulmi", comuna: "Milcov" },
  { nume: "Ungureni", comuna: "Topana" },
  { nume: "Uria", comuna: "Sprancenata" },
  { nume: "Ursa", comuna: "Garcov" },
  { nume: "Urși", simplu: "Ursi", comuna: "Leleasca" },
  { nume: "Ursoaia", comuna: "Icoana" },
  { nume: "Urzica" },
  { nume: "Vădastra", simplu: "Vadastra" },
  { nume: "Vădăstrița", simplu: "Vadastrita" },
  { nume: "Vâlcele", simplu: "Valcele" },
  { nume: "Vâlcelele de Sus", simplu: "Valcelele de Sus", comuna: "Valcele" },
  { nume: "Valea Fetei", comuna: "Verguleasa" },
  { nume: "Valea lui Alb", comuna: "Vulturesti" },
  { nume: "Valea Mare" },
  { nume: "Valea Merilor", comuna: "Potcoava" },
  { nume: "Valea Satului", comuna: "Vulpeni" },
  { nume: "Valea Soarelui", comuna: "Redea" },
  { nume: "Văleni", simplu: "Valeni" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Brancoveni" },
  { nume: "Vânești", simplu: "Vanesti", comuna: "Verguleasa" },
  { nume: "Vârtopu", simplu: "Vartopu", comuna: "Corabia" },
  { nume: "Verguleasa" },
  { nume: "Vineți", simplu: "Vineti", comuna: "Spineni" },
  { nume: "Vișina Nouă", simplu: "Visina Noua", comuna: "Vadastra" },
  { nume: "Vișina", simplu: "Visina" },
  { nume: "Vitănești", simplu: "Vitanesti", comuna: "Optasi-Magura" },
  { nume: "Vitomirești", simplu: "Vitomiresti" },
  { nume: "Vlădila Nouă", simplu: "Vladila Noua", comuna: "Vladila" },
  { nume: "Vlădila", simplu: "Vladila" },
  { nume: "Vlăduleni", simplu: "Vladuleni", comuna: "Osica De Sus" },
  { nume: "Vlaici", comuna: "Colonesti" },
  { nume: "Vlăngărești", simplu: "Vlangaresti", comuna: "Vulturesti" },
  { nume: "Voineasa" },
  { nume: "Vulpeni" },
  { nume: "Vulpești", simplu: "Vulpesti", comuna: "Dobroteasa" },
  { nume: "Vulturești", simplu: "Vulturesti" },
  { nume: "Zănoaga", simplu: "Zanoaga", comuna: "Daneasa" },
  { nume: "Zorleasca", comuna: "Valea Mare" },
];
