export const ot = [
  { nume: "Baldovinesti" },
  { nume: "Bals" },
  { nume: "Bobicesti" },
  { nume: "Brastavatu" },
  { nume: "Brebeni" },
  { nume: "Brancoveni" },
  { nume: "Bucinisu" },
  { nume: "Barza" },
  { nume: "Babiciu" },
  { nume: "Caracal" },
  { nume: "Cezieni" },
  { nume: "Cilieni" },
  { nume: "Colonesti" },
  { nume: "Corabia" },
  { nume: "Corbu" },
  { nume: "Coteana" },
  { nume: "Crampoia" },
  { nume: "Cungrea" },
  { nume: "Curtisoara" },
  { nume: "Carlogani" },
  { nume: "Deveselu" },
  { nume: "Dobretu" },
  { nume: "Dobrosloveni" },
  { nume: "Dobroteasa" },
  { nume: "Dobrun" },
  { nume: "Draghiceni" },
  { nume: "Draganesti-Olt" },
  { nume: "Daneasa" },
  { nume: "Fagetelu" },
  { nume: "Falcoiu" },
  { nume: "Farcasele" },
  { nume: "Giuvarasti" },
  { nume: "Gostavatu" },
  { nume: "Grojdibodu" },
  { nume: "Gradinari" },
  { nume: "Garcov" },
  { nume: "Ganeasa" },
  { nume: "Ianca" },
  { nume: "Iancu Jianu" },
  { nume: "Icoana" },
  { nume: "Izbiceni" },
  { nume: "Izvoarele" },
  { nume: "Leleasca" },
  { nume: "Mihaesti" },
  { nume: "Morunglav" },
  { nume: "Movileni" },
  { nume: "Maruntei" },
  { nume: "Nicolae Titulescu" },
  { nume: "Oboga" },
  { nume: "Obarsia" },
  { nume: "Oporelu" },
  { nume: "Orlea" },
  { nume: "Osica de Sus" },
  { nume: "Perieti" },
  { nume: "Piatra-Olt" },
  { nume: "Plesoiu" },
  { nume: "Poboru" },
  { nume: "Potcoava" },
  { nume: "Priseaca" },
  { nume: "Radomiresti" },
  { nume: "Redea" },
  { nume: "Rotunda" },
  { nume: "Rusanesti" },
  { nume: "Schitu" },
  { nume: "Scornicesti" },
  { nume: "Scarisoara" },
  { nume: "Seaca" },
  { nume: "Slatina" },
  { nume: "Slatioara" },
  { nume: "Spineni" },
  { nume: "Sprancenata" },
  { nume: "Stoenesti" },
  { nume: "Stoicanesti" },
  { nume: "Strejesti" },
  { nume: "Studina" },
  { nume: "Samburesti" },
  { nume: "Teslui" },
  { nume: "Tia Mare" },
  { nume: "Topana" },
  { nume: "Traian" },
  { nume: "Tufeni" },
  { nume: "Tatulesti" },
  { nume: "Urzica" },
  { nume: "Valea Mare" },
  { nume: "Verguleasa" },
  { nume: "Vitomiresti" },
  { nume: "Visina" },
  { nume: "Vladila" },
  { nume: "Voineasa" },
  { nume: "Vulpeni" },
  { nume: "Vulturesti" },
  { nume: "Valcele" },
  { nume: "Vadastra" },
  { nume: "Vadastrita" },
  { nume: "Valeni" },
  { nume: "Serbanesti" },
  { nume: "Stefan cel Mare" },
  { nume: "Brosteni", comuna: "Baldovinesti" },
  { nume: "Baleasa", comuna: "Baldovinesti" },
  { nume: "Damburile", comuna: "Baldovinesti" },
  { nume: "Gubandru", comuna: "Baldovinesti" },
  { nume: "Gavanesti", comuna: "Baldovinesti" },
  { nume: "Pietris", comuna: "Baldovinesti" },
  { nume: "Corbeni", comuna: "Bals" },
  { nume: "Romana", comuna: "Bals" },
  { nume: "Teis", comuna: "Bals" },
  { nume: "Boroesti", comuna: "Barasti" },
  { nume: "Barastii de Cepturi", comuna: "Barasti" },
  { nume: "Barastii de Vede", comuna: "Barasti" },
  { nume: "Ciocanesti", comuna: "Barasti" },
  { nume: "Lazaresti", comuna: "Barasti" },
  { nume: "Mereni", comuna: "Barasti" },
  { nume: "Motoesti", comuna: "Barasti" },
  { nume: "Popesti", comuna: "Barasti" },
  { nume: "Branet", comuna: "Barza" },
  { nume: "Bechet", comuna: "Bobicesti" },
  { nume: "Belgun", comuna: "Bobicesti" },
  { nume: "Chintesti", comuna: "Bobicesti" },
  { nume: "Comanesti", comuna: "Bobicesti" },
  { nume: "Govora", comuna: "Bobicesti" },
  { nume: "Leotesti", comuna: "Bobicesti" },
  { nume: "Mirila", comuna: "Bobicesti" },
  { nume: "Margheni", comuna: "Brancoveni" },
  { nume: "Ociogi", comuna: "Brancoveni" },
  { nume: "Valeni", comuna: "Brancoveni" },
  { nume: "Crusovu", comuna: "Brastavatu" },
  { nume: "Teiusu", comuna: "Brebeni" },
  { nume: "Bucinisu Mic", comuna: "Bucinisu" },
  { nume: "Beculesti", comuna: "Carlogani" },
  { nume: "Cepari", comuna: "Carlogani" },
  { nume: "Scorbura", comuna: "Carlogani" },
  { nume: "Stupina", comuna: "Carlogani" },
  { nume: "Bondrea", comuna: "Cezieni" },
  { nume: "Corlatesti", comuna: "Cezieni" },
  { nume: "Barasti", comuna: "Colonesti" },
  { nume: "Batareni", comuna: "Colonesti" },
  { nume: "Chelbesti", comuna: "Colonesti" },
  { nume: "Carstani", comuna: "Colonesti" },
  { nume: "Guesti", comuna: "Colonesti" },
  { nume: "Maruntei", comuna: "Colonesti" },
  { nume: "Navargeni", comuna: "Colonesti" },
  { nume: "Vlaici", comuna: "Colonesti" },
  { nume: "Tudor Vladimirescu", comuna: "Corabia" },
  { nume: "Vartopu", comuna: "Corabia" },
  { nume: "Burdulesti", comuna: "Corbu" },
  { nume: "Buzesti", comuna: "Corbu" },
  { nume: "Ciuresti", comuna: "Corbu" },
  { nume: "Milcoveni", comuna: "Corbu" },
  { nume: "Buta", comuna: "Crampoia" },
  { nume: "Cepesti", comuna: "Cungrea" },
  { nume: "Ibanesti", comuna: "Cungrea" },
  { nume: "Miesti", comuna: "Cungrea" },
  { nume: "Otestii de Jos", comuna: "Cungrea" },
  { nume: "Otestii de Sus", comuna: "Cungrea" },
  { nume: "Spataru", comuna: "Cungrea" },
  { nume: "Dobrotinet", comuna: "Curtisoara" },
  { nume: "Linia din Vale", comuna: "Curtisoara" },
  { nume: "Pietrisu", comuna: "Curtisoara" },
  { nume: "Proaspeti", comuna: "Curtisoara" },
  { nume: "Raitiu", comuna: "Curtisoara" },
  { nume: "Berindei", comuna: "Daneasa" },
  { nume: "Cioflanu", comuna: "Daneasa" },
  { nume: "Pestra", comuna: "Daneasa" },
  { nume: "Zanoaga", comuna: "Daneasa" },
  { nume: "Comanca", comuna: "Deveselu" },
  { nume: "Curtisoara", comuna: "Dobretu" },
  { nume: "Horezu", comuna: "Dobretu" },
  { nume: "Frasinetu", comuna: "Dobrosloveni" },
  { nume: "Potopinu", comuna: "Dobrosloveni" },
  { nume: "Resca", comuna: "Dobrosloveni" },
  { nume: "Rescuta", comuna: "Dobrosloveni" },
  { nume: "Batia", comuna: "Dobroteasa" },
  { nume: "Campu Mare", comuna: "Dobroteasa" },
  { nume: "Vulpesti", comuna: "Dobroteasa" },
  { nume: "Bobu", comuna: "Dobrun" },
  { nume: "Chilii", comuna: "Dobrun" },
  { nume: "Osica de Jos", comuna: "Dobrun" },
  { nume: "Rosienii Mari", comuna: "Dobrun" },
  { nume: "Rosienii Mici", comuna: "Dobrun" },
  { nume: "Ulmet", comuna: "Dobrun" },
  { nume: "Comani", comuna: "Draganesti-Olt" },
  { nume: "Grozavesti", comuna: "Draghiceni" },
  { nume: "Liiceni", comuna: "Draghiceni" },
  { nume: "Bagesti", comuna: "Fagetelu" },
  { nume: "Chilia", comuna: "Fagetelu" },
  { nume: "Gruiu", comuna: "Fagetelu" },
  { nume: "Isaci", comuna: "Fagetelu" },
  { nume: "Pielcani", comuna: "Fagetelu" },
  { nume: "Cioroiasu", comuna: "Falcoiu" },
  { nume: "Cioroiu", comuna: "Falcoiu" },
  { nume: "Farcasu de Jos", comuna: "Farcasele" },
  { nume: "Ghimpati", comuna: "Farcasele" },
  { nume: "Hotarani", comuna: "Farcasele" },
  { nume: "Dranovatu", comuna: "Ganeasa" },
  { nume: "Gradistea", comuna: "Ganeasa" },
  { nume: "Izvoru", comuna: "Ganeasa" },
  { nume: "Oltisoru", comuna: "Ganeasa" },
  { nume: "Ursa", comuna: "Garcov" },
  { nume: "Slaveni", comuna: "Gostavatu" },
  { nume: "Petculesti", comuna: "Gradinari" },
  { nume: "Runcu Mare", comuna: "Gradinari" },
  { nume: "Satu Nou", comuna: "Gradinari" },
  { nume: "Hotaru", comuna: "Grojdibodu" },
  { nume: "Potelu", comuna: "Ianca" },
  { nume: "Dobriceni", comuna: "Iancu Jianu" },
  { nume: "Preotesti", comuna: "Iancu Jianu" },
  { nume: "Floru", comuna: "Icoana" },
  { nume: "Ursoaia", comuna: "Icoana" },
  { nume: "Alimanesti", comuna: "Izvoarele" },
  { nume: "Afumati", comuna: "Leleasca" },
  { nume: "Greeresti", comuna: "Leleasca" },
  { nume: "Mierlicesti", comuna: "Leleasca" },
  { nume: "Tonesti", comuna: "Leleasca" },
  { nume: "Tufaru", comuna: "Leleasca" },
  { nume: "Ursi", comuna: "Leleasca" },
  { nume: "Balanesti", comuna: "Maruntei" },
  { nume: "Malu Rosu", comuna: "Maruntei" },
  { nume: "Busca", comuna: "Mihaesti" },
  { nume: "Ipotesti", comuna: "Milcov" },
  { nume: "Milcovu din Deal", comuna: "Milcov" },
  { nume: "Milcovu din Vale", comuna: "Milcov" },
  { nume: "Stejaru", comuna: "Milcov" },
  { nume: "Ulmi", comuna: "Milcov" },
  { nume: "Barasti", comuna: "Morunglav" },
  { nume: "Ghiosani", comuna: "Morunglav" },
  { nume: "Morunesti", comuna: "Morunglav" },
  { nume: "Poiana Mare", comuna: "Morunglav" },
  { nume: "Bacea", comuna: "Movileni" },
  { nume: "Ghimpeteni", comuna: "Nicolae Titulescu" },
  { nume: "Ghimpetenii Noi", comuna: "Nicolae Titulescu" },
  { nume: "Coteni", comuna: "Obarsia" },
  { nume: "Campu Parului", comuna: "Obarsia" },
  { nume: "Obarsia Noua", comuna: "Obarsia" },
  { nume: "Tabonu", comuna: "Obarsia" },
  { nume: "Calui", comuna: "Oboga" },
  { nume: "Gura Caluiu", comuna: "Oboga" },
  { nume: "Beria de Jos", comuna: "Oporelu" },
  { nume: "Beria de Sus", comuna: "Oporelu" },
  { nume: "Radesti", comuna: "Oporelu" },
  { nume: "Optasi", comuna: "Optasi-Magura" },
  { nume: "Vitanesti", comuna: "Optasi-Magura" },
  { nume: "Gura Padinii", comuna: "Orlea" },
  { nume: "Orlea Noua", comuna: "Orlea" },
  { nume: "Satu Nou", comuna: "Orlea" },
  { nume: "Greci", comuna: "Osica De Sus" },
  { nume: "Ostrov", comuna: "Osica De Sus" },
  { nume: "Peretu", comuna: "Osica De Sus" },
  { nume: "Tomeni", comuna: "Osica De Sus" },
  { nume: "Vladuleni", comuna: "Osica De Sus" },
  { nume: "Butoi", comuna: "Parscoveni" },
  { nume: "Olari", comuna: "Parscoveni" },
  { nume: "Parscoveni", comuna: "Parscoveni" },
  { nume: "Soparlita", comuna: "Parscoveni" },
  { nume: "Balteni", comuna: "Perieti" },
  { nume: "Mierlestii de Sus", comuna: "Perieti" },
  { nume: "Magura", comuna: "Perieti" },
  { nume: "Bistrita Noua", comuna: "Piatra-Olt" },
  { nume: "Criva de Jos", comuna: "Piatra-Olt" },
  { nume: "Criva de Sus", comuna: "Piatra-Olt" },
  { nume: "Enosesti", comuna: "Piatra-Olt" },
  { nume: "Piatra", comuna: "Piatra-Olt" },
  { nume: "Arcesti", comuna: "Plesoiu" },
  { nume: "Arcesti Cot", comuna: "Plesoiu" },
  { nume: "Cocorasti", comuna: "Plesoiu" },
  { nume: "Doba", comuna: "Plesoiu" },
  { nume: "Schitu din Deal", comuna: "Plesoiu" },
  { nume: "Schitu din Vale", comuna: "Plesoiu" },
  { nume: "Albesti", comuna: "Poboru" },
  { nume: "Cornatelu", comuna: "Poboru" },
  { nume: "Creti", comuna: "Poboru" },
  { nume: "Seaca", comuna: "Poboru" },
  { nume: "Surpeni", comuna: "Poboru" },
  { nume: "Potcoava Falcoeni", comuna: "Potcoava" },
  { nume: "Sinesti", comuna: "Potcoava" },
  { nume: "Trufinesti", comuna: "Potcoava" },
  { nume: "Valea Merilor", comuna: "Potcoava" },
  { nume: "Buicesti", comuna: "Priseaca" },
  { nume: "Saltanesti", comuna: "Priseaca" },
  { nume: "Craciunei", comuna: "Radomiresti" },
  { nume: "Calinesti", comuna: "Radomiresti" },
  { nume: "Poiana", comuna: "Radomiresti" },
  { nume: "Redisoara", comuna: "Redea" },
  { nume: "Valea Soarelui", comuna: "Redea" },
  { nume: "Jieni", comuna: "Rusanesti" },
  { nume: "Cerbeni", comuna: "Samburesti" },
  { nume: "Ionicesti", comuna: "Samburesti" },
  { nume: "Launele", comuna: "Samburesti" },
  { nume: "Manulesti", comuna: "Samburesti" },
  { nume: "Stanuleasa", comuna: "Samburesti" },
  { nume: "Tonesti", comuna: "Samburesti" },
  { nume: "Plaviceni", comuna: "Scarisoara" },
  { nume: "Rudari", comuna: "Scarisoara" },
  { nume: "Catanele", comuna: "Schitu" },
  { nume: "Greci", comuna: "Schitu" },
  { nume: "Lisa", comuna: "Schitu" },
  { nume: "Mosteni", comuna: "Schitu" },
  { nume: "Bircii", comuna: "Scornicesti" },
  { nume: "Baltati", comuna: "Scornicesti" },
  { nume: "Chiteasca", comuna: "Scornicesti" },
  { nume: "Constantinesti", comuna: "Scornicesti" },
  { nume: "Jitaru", comuna: "Scornicesti" },
  { nume: "Mihailesti Popesti", comuna: "Scornicesti" },
  { nume: "Mogosesti", comuna: "Scornicesti" },
  { nume: "Margineni Slobozia", comuna: "Scornicesti" },
  { nume: "Negreni", comuna: "Scornicesti" },
  { nume: "Piscani", comuna: "Scornicesti" },
  { nume: "Rusciori", comuna: "Scornicesti" },
  { nume: "Teius", comuna: "Scornicesti" },
  { nume: "Suica", comuna: "Scornicesti" },
  { nume: "Strugurelu", comuna: "Serbanesti" },
  { nume: "Serbanestii de Sus", comuna: "Serbanesti" },
  { nume: "Cireasov", comuna: "Slatina" },
  { nume: "Salcia", comuna: "Slatioara" },
  { nume: "Alunisu", comuna: "Spineni" },
  { nume: "Cuza Voda", comuna: "Spineni" },
  { nume: "Davidesti", comuna: "Spineni" },
  { nume: "Optasani", comuna: "Spineni" },
  { nume: "Profa", comuna: "Spineni" },
  { nume: "Vineti", comuna: "Spineni" },
  { nume: "Barsestii de Sus", comuna: "Sprancenata" },
  { nume: "Frunzaru", comuna: "Sprancenata" },
  { nume: "Uria", comuna: "Sprancenata" },
  { nume: "Ianca Noua", comuna: "Stefan Cel Mare" },
  { nume: "Colibasi", comuna: "Strejesti" },
  { nume: "Mamura", comuna: "Strejesti" },
  { nume: "Strejestii de Sus", comuna: "Strejesti" },
  { nume: "Arvateasca", comuna: "Studina" },
  { nume: "Gradinile", comuna: "Studina" },
  { nume: "Plaviceanca", comuna: "Studina" },
  { nume: "Studinita", comuna: "Studina" },
  { nume: "Barbalai", comuna: "Tatulesti" },
  { nume: "Lunca", comuna: "Tatulesti" },
  { nume: "Mircesti", comuna: "Tatulesti" },
  { nume: "Momaiu", comuna: "Tatulesti" },
  { nume: "Magura", comuna: "Tatulesti" },
  { nume: "Cherlestii Mosteni", comuna: "Teslui" },
  { nume: "Cherlestii din Deal", comuna: "Teslui" },
  { nume: "Comanita", comuna: "Teslui" },
  { nume: "Corbu", comuna: "Teslui" },
  { nume: "Deleni", comuna: "Teslui" },
  { nume: "Schitu Deleni", comuna: "Teslui" },
  { nume: "Doanca", comuna: "Tia Mare" },
  { nume: "Potlogeni", comuna: "Tia Mare" },
  { nume: "Cioraca", comuna: "Topana" },
  { nume: "Cojgarei", comuna: "Topana" },
  { nume: "Candelesti", comuna: "Topana" },
  { nume: "Ungureni", comuna: "Topana" },
  { nume: "Barza", comuna: "Tufeni" },
  { nume: "Stoborasti", comuna: "Tufeni" },
  { nume: "Stavaru", comuna: "Urzica" },
  { nume: "Visina Noua", comuna: "Vadastra" },
  { nume: "Barcanesti", comuna: "Valcele" },
  { nume: "Valcelele de Sus", comuna: "Valcele" },
  { nume: "Barca", comuna: "Valea Mare" },
  { nume: "Recea", comuna: "Valea Mare" },
  { nume: "Turia", comuna: "Valea Mare" },
  { nume: "Zorleasca", comuna: "Valea Mare" },
  { nume: "Mandra", comuna: "Valeni" },
  { nume: "Popesti", comuna: "Valeni" },
  { nume: "Tirisneag", comuna: "Valeni" },
  { nume: "Cucueti", comuna: "Verguleasa" },
  { nume: "Cazanesti", comuna: "Verguleasa" },
  { nume: "Dumitresti", comuna: "Verguleasa" },
  { nume: "Poganu", comuna: "Verguleasa" },
  { nume: "Valea Fetei", comuna: "Verguleasa" },
  { nume: "Vanesti", comuna: "Verguleasa" },
  { nume: "Bulimanu", comuna: "Vitomiresti" },
  { nume: "Dejesti", comuna: "Vitomiresti" },
  { nume: "Donesti", comuna: "Vitomiresti" },
  { nume: "Stanuleasa", comuna: "Vitomiresti" },
  { nume: "Trepteni", comuna: "Vitomiresti" },
  { nume: "Frasinet Gara", comuna: "Vladila" },
  { nume: "Vladila Noua", comuna: "Vladila" },
  { nume: "Blaj", comuna: "Voineasa" },
  { nume: "Margaritesti", comuna: "Voineasa" },
  { nume: "Racovita", comuna: "Voineasa" },
  { nume: "Rusanestii de Sus", comuna: "Voineasa" },
  { nume: "Cotorbesti", comuna: "Vulpeni" },
  { nume: "Gropsani", comuna: "Vulpeni" },
  { nume: "Mardale", comuna: "Vulpeni" },
  { nume: "Pescaresti", comuna: "Vulpeni" },
  { nume: "Plopsorelu", comuna: "Vulpeni" },
  { nume: "Prisaca", comuna: "Vulpeni" },
  { nume: "Simniceni", comuna: "Vulpeni" },
  { nume: "Tabaci", comuna: "Vulpeni" },
  { nume: "Valea Satului", comuna: "Vulpeni" },
  { nume: "Dienci", comuna: "Vulturesti" },
  { nume: "Valea lui Alb", comuna: "Vulturesti" },
  { nume: "Vlangaresti", comuna: "Vulturesti" },
];
