export const ot = [
  { nume: "Afumaţi", simplu: "Afumati", comuna: "Leleasca" },
  { nume: "Albeşti", simplu: "Albesti", comuna: "Poboru" },
  { nume: "Alimăneşti", simplu: "Alimanesti", comuna: "Izvoarele" },
  { nume: "Alunişu", simplu: "Alunisu", comuna: "Spineni" },
  { nume: "Arceşti Cot", simplu: "Arcesti Cot", comuna: "Plesoiu" },
  { nume: "Arceşti", simplu: "Arcesti", comuna: "Plesoiu" },
  { nume: "Arvăteasca", simplu: "Arvateasca", comuna: "Studina" },
  { nume: "Băbiciu", simplu: "Babiciu" },
  { nume: "Bacea", comuna: "Movileni" },
  { nume: "Bâgeşti", simplu: "Bagesti", comuna: "Fagetelu" },
  { nume: "Bălăneşti", simplu: "Balanesti", comuna: "Maruntei" },
  { nume: "Baldovineşti", simplu: "Baldovinesti" },
  { nume: "Băleasa", simplu: "Baleasa", comuna: "Baldovinesti" },
  { nume: "Balş", simplu: "Bals" },
  { nume: "Bălţaţi", simplu: "Baltati", comuna: "Scornicesti" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Perieti" },
  { nume: "Bărăşti", simplu: "Barasti", comuna: "Colonesti" },
  { nume: "Bărăşti", simplu: "Barasti", comuna: "Morunglav" },
  {
    nume: "Bărăştii de Cepturi",
    simplu: "Barastii de Cepturi",
    comuna: "Barasti",
  },
  { nume: "Bărăştii de Vede", simplu: "Barastii de Vede", comuna: "Barasti" },
  { nume: "Bărbălăi", simplu: "Barbalai", comuna: "Tatulesti" },
  { nume: "Bârca", simplu: "Barca", comuna: "Valea Mare" },
  { nume: "Bărcăneşti", simplu: "Barcanesti", comuna: "Valcele" },
  {
    nume: "Bârseştii de Sus",
    simplu: "Barsestii de Sus",
    comuna: "Sprancenata",
  },
  { nume: "Barza", comuna: "Tufeni" },
  { nume: "Bârza", simplu: "Barza" },
  { nume: "Bătăreni", simplu: "Batareni", comuna: "Colonesti" },
  { nume: "Batia", comuna: "Dobroteasa" },
  { nume: "Bechet", comuna: "Bobicesti" },
  { nume: "Beculeşti", simplu: "Beculesti", comuna: "Carlogani" },
  { nume: "Belgun", comuna: "Bobicesti" },
  { nume: "Beria de Jos", comuna: "Oporelu" },
  { nume: "Beria de Sus", comuna: "Oporelu" },
  { nume: "Berindei", comuna: "Daneasa" },
  { nume: "Bircii", comuna: "Scornicesti" },
  { nume: "Bistriţa Nouă", simplu: "Bistrita Noua", comuna: "Piatra-Olt" },
  { nume: "Blaj", comuna: "Voineasa" },
  { nume: "Bobiceşti", simplu: "Bobicesti" },
  { nume: "Bobu", comuna: "Dobrun" },
  { nume: "Bondrea", comuna: "Cezieni" },
  { nume: "Boroeşti", simplu: "Boroesti", comuna: "Barasti" },
  { nume: "Brâncoveni", simplu: "Brancoveni" },
  { nume: "Braneţ", simplu: "Branet", comuna: "Barza" },
  { nume: "Brastavăţu", simplu: "Brastavatu" },
  { nume: "Brebeni" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Baldovinesti" },
  { nume: "Bucinişu Mic", simplu: "Bucinisu Mic", comuna: "Bucinisu" },
  { nume: "Bucinişu", simplu: "Bucinisu" },
  { nume: "Buiceşti", simplu: "Buicesti", comuna: "Priseaca" },
  { nume: "Bulimanu", comuna: "Vitomiresti" },
  { nume: "Burduleşti", simplu: "Burdulesti", comuna: "Corbu" },
  { nume: "Buşca", simplu: "Busca", comuna: "Mihaesti" },
  { nume: "Buta", comuna: "Crampoia" },
  { nume: "Butoi", comuna: "Parscoveni" },
  { nume: "Buzeşti", simplu: "Buzesti", comuna: "Corbu" },
  { nume: "Călineşti", simplu: "Calinesti", comuna: "Radomiresti" },
  { nume: "Călui", simplu: "Calui", comuna: "Oboga" },
  { nume: "Câmpu Mare", simplu: "Campu Mare", comuna: "Dobroteasa" },
  { nume: "Câmpu Părului", simplu: "Campu Parului", comuna: "Obarsia" },
  { nume: "Cândeleşti", simplu: "Candelesti", comuna: "Topana" },
  { nume: "Caracal" },
  { nume: "Cârlogani", simplu: "Carlogani" },
  { nume: "Cârstani", simplu: "Carstani", comuna: "Colonesti" },
  { nume: "Catanele", comuna: "Schitu" },
  { nume: "Căzăneşti", simplu: "Cazanesti", comuna: "Verguleasa" },
  { nume: "Cepari", comuna: "Carlogani" },
  { nume: "Cepeşti", simplu: "Cepesti", comuna: "Cungrea" },
  { nume: "Cerbeni", comuna: "Samburesti" },
  { nume: "Cezieni" },
  { nume: "Chelbeşti", simplu: "Chelbesti", comuna: "Colonesti" },
  {
    nume: "Cherleştii din Deal",
    simplu: "Cherlestii din Deal",
    comuna: "Teslui",
  },
  {
    nume: "Cherleştii Moşteni",
    simplu: "Cherlestii Mosteni",
    comuna: "Teslui",
  },
  { nume: "Chilia", comuna: "Fagetelu" },
  { nume: "Chilii", comuna: "Dobrun" },
  { nume: "Chinteşti", simplu: "Chintesti", comuna: "Bobicesti" },
  { nume: "Chiţeasca", simplu: "Chiteasca", comuna: "Scornicesti" },
  { nume: "Cilieni" },
  { nume: "Ciocăneşti", simplu: "Ciocanesti", comuna: "Barasti" },
  { nume: "Cioflanu", comuna: "Daneasa" },
  { nume: "Ciorâca", simplu: "Cioraca", comuna: "Topana" },
  { nume: "Cioroiaşu", simplu: "Cioroiasu", comuna: "Falcoiu" },
  { nume: "Cioroiu", comuna: "Falcoiu" },
  { nume: "Cireaşov", simplu: "Cireasov", comuna: "Slatina" },
  { nume: "Ciureşti", simplu: "Ciuresti", comuna: "Corbu" },
  { nume: "Cocorăşti", simplu: "Cocorasti", comuna: "Plesoiu" },
  { nume: "Cojgărei", simplu: "Cojgarei", comuna: "Topana" },
  { nume: "Colibaşi", simplu: "Colibasi", comuna: "Strejesti" },
  { nume: "Coloneşti", simplu: "Colonesti" },
  { nume: "Comanca", comuna: "Deveselu" },
  { nume: "Comăneşti", simplu: "Comanesti", comuna: "Bobicesti" },
  { nume: "Comani", comuna: "Draganesti-Olt" },
  { nume: "Comăniţa", simplu: "Comanita", comuna: "Teslui" },
  { nume: "Constantineşti", simplu: "Constantinesti", comuna: "Scornicesti" },
  { nume: "Corabia" },
  { nume: "Corbeni", comuna: "Bals" },
  { nume: "Corbu" },
  { nume: "Corbu", comuna: "Teslui" },
  { nume: "Corlăteşti", simplu: "Corlatesti", comuna: "Cezieni" },
  { nume: "Cornăţelu", simplu: "Cornatelu", comuna: "Poboru" },
  { nume: "Coteana" },
  { nume: "Coteni", comuna: "Obarsia" },
  { nume: "Cotorbeşti", simplu: "Cotorbesti", comuna: "Vulpeni" },
  { nume: "Crăciunei", simplu: "Craciunei", comuna: "Radomiresti" },
  { nume: "Crâmpoia", simplu: "Crampoia" },
  { nume: "Creţi", simplu: "Creti", comuna: "Poboru" },
  { nume: "Criva de Jos", comuna: "Piatra-Olt" },
  { nume: "Criva de Sus", comuna: "Piatra-Olt" },
  { nume: "Cruşovu", simplu: "Crusovu", comuna: "Brastavatu" },
  { nume: "Cucueţi", simplu: "Cucueti", comuna: "Verguleasa" },
  { nume: "Cungrea" },
  { nume: "Curtişoara", simplu: "Curtisoara" },
  { nume: "Curtişoara", simplu: "Curtisoara", comuna: "Dobretu" },
  { nume: "Cuza Vodă", simplu: "Cuza Voda", comuna: "Spineni" },
  { nume: "Dâmburile", simplu: "Damburile", comuna: "Baldovinesti" },
  { nume: "Dăneasa", simplu: "Daneasa" },
  { nume: "Davideşti", simplu: "Davidesti", comuna: "Spineni" },
  { nume: "Dejeşti", simplu: "Dejesti", comuna: "Vitomiresti" },
  { nume: "Deleni", comuna: "Teslui" },
  { nume: "Deveselu" },
  { nume: "Dienci", comuna: "Vulturesti" },
  { nume: "Doanca", comuna: "Tia Mare" },
  { nume: "Doba", comuna: "Plesoiu" },
  { nume: "Dobreţu", simplu: "Dobretu" },
  { nume: "Dobriceni", comuna: "Iancu Jianu" },
  { nume: "Dobrosloveni" },
  { nume: "Dobroteasa" },
  { nume: "Dobrotinet", comuna: "Curtisoara" },
  { nume: "Dobrun" },
  { nume: "Doneşti", simplu: "Donesti", comuna: "Vitomiresti" },
  { nume: "Drăgăneşti-Olt", simplu: "Draganesti-Olt" },
  { nume: "Drăghiceni", simplu: "Draghiceni" },
  { nume: "Dranovăţu", simplu: "Dranovatu", comuna: "Ganeasa" },
  { nume: "Dumitreşti", simplu: "Dumitresti", comuna: "Verguleasa" },
  { nume: "Enoşeşti", simplu: "Enosesti", comuna: "Piatra-Olt" },
  { nume: "Făgeţelu", simplu: "Fagetelu" },
  { nume: "Fălcoiu", simplu: "Falcoiu" },
  { nume: "Fărcaşele", simplu: "Farcasele" },
  { nume: "Fărcaşu de Jos", simplu: "Farcasu de Jos", comuna: "Farcasele" },
  { nume: "Floru", comuna: "Icoana" },
  { nume: "Frăsinet Gară", simplu: "Frasinet Gara", comuna: "Vladila" },
  { nume: "Frăsinetu", simplu: "Frasinetu", comuna: "Dobrosloveni" },
  { nume: "Frunzaru", comuna: "Sprancenata" },
  { nume: "Găneasa", simplu: "Ganeasa" },
  { nume: "Gârcov", simplu: "Garcov" },
  { nume: "Găvăneşti", simplu: "Gavanesti", comuna: "Baldovinesti" },
  { nume: "Ghimpaţi", simplu: "Ghimpati", comuna: "Farcasele" },
  { nume: "Ghimpeţeni", simplu: "Ghimpeteni", comuna: "Nicolae Titulescu" },
  {
    nume: "Ghimpeţenii Noi",
    simplu: "Ghimpetenii Noi",
    comuna: "Nicolae Titulescu",
  },
  { nume: "Ghioşani", simplu: "Ghiosani", comuna: "Morunglav" },
  { nume: "Giuvărăşti", simplu: "Giuvarasti" },
  { nume: "Gostavăţu", simplu: "Gostavatu" },
  { nume: "Govora", comuna: "Bobicesti" },
  { nume: "Grădinari", simplu: "Gradinari" },
  { nume: "Grădinile", simplu: "Gradinile", comuna: "Studina" },
  { nume: "Grădiştea", simplu: "Gradistea", comuna: "Ganeasa" },
  { nume: "Greci", comuna: "Osica De Sus" },
  { nume: "Greci", comuna: "Schitu" },
  { nume: "Greereşti", simplu: "Greeresti", comuna: "Leleasca" },
  { nume: "Grojdibodu" },
  { nume: "Gropşani", simplu: "Gropsani", comuna: "Vulpeni" },
  { nume: "Grozăveşti", simplu: "Grozavesti", comuna: "Draghiceni" },
  { nume: "Gruiu", comuna: "Fagetelu" },
  { nume: "Gubandru", comuna: "Baldovinesti" },
  { nume: "Gueşti", simplu: "Guesti", comuna: "Colonesti" },
  { nume: "Gura Căluiu", simplu: "Gura Caluiu", comuna: "Oboga" },
  { nume: "Gura Padinii", comuna: "Orlea" },
  { nume: "Horezu", comuna: "Dobretu" },
  { nume: "Hotărani", simplu: "Hotarani", comuna: "Farcasele" },
  { nume: "Hotaru", comuna: "Grojdibodu" },
  { nume: "Ianca Nouă", simplu: "Ianca Noua", comuna: "Stefan Cel Mare" },
  { nume: "Ianca" },
  { nume: "Iancu Jianu" },
  { nume: "Ibăneşti", simplu: "Ibanesti", comuna: "Cungrea" },
  { nume: "Icoana" },
  { nume: "Ioniceşti", simplu: "Ionicesti", comuna: "Samburesti" },
  { nume: "Ipoteşti", simplu: "Ipotesti", comuna: "Milcov" },
  { nume: "Isaci", comuna: "Fagetelu" },
  { nume: "Izbiceni" },
  { nume: "Izvoarele" },
  { nume: "Izvoru", comuna: "Ganeasa" },
  { nume: "Jieni", comuna: "Rusanesti" },
  { nume: "Jitaru", comuna: "Scornicesti" },
  { nume: "Lăunele", simplu: "Launele", comuna: "Samburesti" },
  { nume: "Lăzăreşti", simplu: "Lazaresti", comuna: "Barasti" },
  { nume: "Leleasca" },
  { nume: "Leoteşti", simplu: "Leotesti", comuna: "Bobicesti" },
  { nume: "Liiceni", comuna: "Draghiceni" },
  { nume: "Linia din Vale", comuna: "Curtisoara" },
  { nume: "Lisa", comuna: "Schitu" },
  { nume: "Lunca", comuna: "Tatulesti" },
  { nume: "Măgura", simplu: "Magura", comuna: "Perieti" },
  { nume: "Măgura", simplu: "Magura", comuna: "Tatulesti" },
  { nume: "Malu Roşu", simplu: "Malu Rosu", comuna: "Maruntei" },
  { nume: "Mamura", comuna: "Strejesti" },
  { nume: "Mandra", comuna: "Valeni" },
  { nume: "Mănuleşti", simplu: "Manulesti", comuna: "Samburesti" },
  { nume: "Mardale", comuna: "Vulpeni" },
  { nume: "Mărgăriteşti", simplu: "Margaritesti", comuna: "Voineasa" },
  { nume: "Mărgheni", simplu: "Margheni", comuna: "Brancoveni" },
  {
    nume: "Mărgineni Slobozia",
    simplu: "Margineni Slobozia",
    comuna: "Scornicesti",
  },
  { nume: "Mărunţei", simplu: "Maruntei" },
  { nume: "Mărunţei", simplu: "Maruntei", comuna: "Colonesti" },
  { nume: "Mereni", comuna: "Barasti" },
  { nume: "Mierleştii de Sus", simplu: "Mierlestii de Sus", comuna: "Perieti" },
  { nume: "Mierliceşti", simplu: "Mierlicesti", comuna: "Leleasca" },
  { nume: "Mieşti", simplu: "Miesti", comuna: "Cungrea" },
  { nume: "Mihăeşti", simplu: "Mihaesti" },
  {
    nume: "Mihăileşti Popeşti",
    simplu: "Mihailesti Popesti",
    comuna: "Scornicesti",
  },
  { nume: "Milcoveni", comuna: "Corbu" },
  { nume: "Milcovu din Deal", comuna: "Milcov" },
  { nume: "Milcovu din Vale", comuna: "Milcov" },
  { nume: "Mirceşti", simplu: "Mircesti", comuna: "Tatulesti" },
  { nume: "Mirila", comuna: "Bobicesti" },
  { nume: "Mogoşeşti", simplu: "Mogosesti", comuna: "Scornicesti" },
  { nume: "Momaiu", comuna: "Tatulesti" },
  { nume: "Moruneşti", simplu: "Morunesti", comuna: "Morunglav" },
  { nume: "Morunglav" },
  { nume: "Moşteni", simplu: "Mosteni", comuna: "Schitu" },
  { nume: "Moţoeşti", simplu: "Motoesti", comuna: "Barasti" },
  { nume: "Movileni" },
  { nume: "Năvârgeni", simplu: "Navargeni", comuna: "Colonesti" },
  { nume: "Negreni", comuna: "Scornicesti" },
  { nume: "Nicolae Titulescu" },
  { nume: "Obârşia Nouă", simplu: "Obarsia Noua", comuna: "Obarsia" },
  { nume: "Obârşia", simplu: "Obarsia" },
  { nume: "Oboga" },
  { nume: "Ociogi", comuna: "Brancoveni" },
  { nume: "Olari", comuna: "Parscoveni" },
  { nume: "Oltişoru", simplu: "Oltisoru", comuna: "Ganeasa" },
  { nume: "Oporelu" },
  { nume: "Optăşani", simplu: "Optasani", comuna: "Spineni" },
  { nume: "Optaşi", simplu: "Optasi", comuna: "Optasi-Magura" },
  { nume: "Orlea Nouă", simplu: "Orlea Noua", comuna: "Orlea" },
  { nume: "Orlea" },
  { nume: "Osica de Jos", comuna: "Dobrun" },
  { nume: "Osica de Sus" },
  { nume: "Ostrov", comuna: "Osica De Sus" },
  { nume: "Oteştii de Jos", simplu: "Otestii de Jos", comuna: "Cungrea" },
  { nume: "Oteştii de Sus", simplu: "Otestii de Sus", comuna: "Cungrea" },
  { nume: "Peretu", comuna: "Osica De Sus" },
  { nume: "Perieţi", simplu: "Perieti" },
  { nume: "Pescăreşti", simplu: "Pescaresti", comuna: "Vulpeni" },
  { nume: "Pestra", comuna: "Daneasa" },
  { nume: "Petculeşti", simplu: "Petculesti", comuna: "Gradinari" },
  { nume: "Piatra-Olt" },
  { nume: "Piatra", comuna: "Piatra-Olt" },
  { nume: "Pielcani", comuna: "Fagetelu" },
  { nume: "Pietriş", simplu: "Pietris", comuna: "Baldovinesti" },
  { nume: "Pietrişu", simplu: "Pietrisu", comuna: "Curtisoara" },
  { nume: "Pîrşcoveni", simplu: "Parscoveni", comuna: "Parscoveni" },
  { nume: "Piscani", comuna: "Scornicesti" },
  { nume: "Plăviceanca", simplu: "Plaviceanca", comuna: "Studina" },
  { nume: "Plăviceni", simplu: "Plaviceni", comuna: "Scarisoara" },
  { nume: "Pleşoiu", simplu: "Plesoiu" },
  { nume: "Plopşorelu", simplu: "Plopsorelu", comuna: "Vulpeni" },
  { nume: "Poboru" },
  { nume: "Poganu", comuna: "Verguleasa" },
  { nume: "Poiana Mare", comuna: "Morunglav" },
  { nume: "Poiana", comuna: "Radomiresti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Barasti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Valeni" },
  {
    nume: "Potcoava Fălcoeni",
    simplu: "Potcoava Falcoeni",
    comuna: "Potcoava",
  },
  { nume: "Potcoava" },
  { nume: "Potelu", comuna: "Ianca" },
  { nume: "Potlogeni", comuna: "Tia Mare" },
  { nume: "Potopinu", comuna: "Dobrosloveni" },
  { nume: "Preoteşti", simplu: "Preotesti", comuna: "Iancu Jianu" },
  { nume: "Prisaca", comuna: "Vulpeni" },
  { nume: "Priseaca" },
  { nume: "Proaspeţi", simplu: "Proaspeti", comuna: "Curtisoara" },
  { nume: "Profa", comuna: "Spineni" },
  { nume: "Racoviţa", simplu: "Racovita", comuna: "Voineasa" },
  { nume: "Rădeşti", simplu: "Radesti", comuna: "Oporelu" },
  { nume: "Radomireşti", simplu: "Radomiresti" },
  { nume: "Raiţiu", simplu: "Raitiu", comuna: "Curtisoara" },
  { nume: "Recea", comuna: "Valea Mare" },
  { nume: "Redea" },
  { nume: "Redişoara", simplu: "Redisoara", comuna: "Redea" },
  { nume: "Reşca", simplu: "Resca", comuna: "Dobrosloveni" },
  { nume: "Reşcuţa", simplu: "Rescuta", comuna: "Dobrosloveni" },
  { nume: "Româna", simplu: "Romana", comuna: "Bals" },
  { nume: "Roşienii Mari", simplu: "Rosienii Mari", comuna: "Dobrun" },
  { nume: "Roşienii Mici", simplu: "Rosienii Mici", comuna: "Dobrun" },
  { nume: "Rotunda" },
  { nume: "Rudari", comuna: "Scarisoara" },
  { nume: "Runcu Mare", comuna: "Gradinari" },
  { nume: "Rusăneşti", simplu: "Rusanesti" },
  {
    nume: "Rusăneştii de Sus",
    simplu: "Rusanestii de Sus",
    comuna: "Voineasa",
  },
  { nume: "Rusciori", comuna: "Scornicesti" },
  { nume: "Salcia", comuna: "Slatioara" },
  { nume: "Săltăneşti", simplu: "Saltanesti", comuna: "Priseaca" },
  { nume: "Sâmbureşti", simplu: "Samburesti" },
  { nume: "Satu Nou", comuna: "Gradinari" },
  { nume: "Satu Nou", comuna: "Orlea" },
  { nume: "Scărişoara", simplu: "Scarisoara" },
  { nume: "Schitu Deleni", comuna: "Teslui" },
  { nume: "Schitu din Deal", comuna: "Plesoiu" },
  { nume: "Schitu din Vale", comuna: "Plesoiu" },
  { nume: "Schitu" },
  { nume: "Scorbura", comuna: "Carlogani" },
  { nume: "Scorniceşti", simplu: "Scornicesti" },
  { nume: "Seaca" },
  { nume: "Seaca", comuna: "Poboru" },
  { nume: "Şerbăneşti", simplu: "Serbanesti" },
  {
    nume: "Şerbăneştii de Sus",
    simplu: "Serbanestii de Sus",
    comuna: "Serbanesti",
  },
  { nume: "Simniceni", comuna: "Vulpeni" },
  { nume: "Sineşti", simplu: "Sinesti", comuna: "Potcoava" },
  { nume: "Slatina" },
  { nume: "Slătioara", simplu: "Slatioara" },
  { nume: "Slăveni", simplu: "Slaveni", comuna: "Gostavatu" },
  { nume: "Şopârliţa", simplu: "Soparlita", comuna: "Parscoveni" },
  { nume: "Spătaru", simplu: "Spataru", comuna: "Cungrea" },
  { nume: "Spineni" },
  { nume: "Sprâncenata", simplu: "Sprancenata" },
  { nume: "Stănuleasa", simplu: "Stanuleasa", comuna: "Samburesti" },
  { nume: "Stănuleasa", simplu: "Stanuleasa", comuna: "Vitomiresti" },
  { nume: "Stăvaru", simplu: "Stavaru", comuna: "Urzica" },
  { nume: "Ştefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Stejaru", comuna: "Milcov" },
  { nume: "Stoborăşti", simplu: "Stoborasti", comuna: "Tufeni" },
  { nume: "Stoeneşti", simplu: "Stoenesti" },
  { nume: "Stoicăneşti", simplu: "Stoicanesti" },
  { nume: "Strejeşti", simplu: "Strejesti" },
  {
    nume: "Strejeştii de Sus",
    simplu: "Strejestii de Sus",
    comuna: "Strejesti",
  },
  { nume: "Strugurelu", comuna: "Serbanesti" },
  { nume: "Studina" },
  { nume: "Studiniţa", simplu: "Studinita", comuna: "Studina" },
  { nume: "Stupina", comuna: "Carlogani" },
  { nume: "Şuica", simplu: "Suica", comuna: "Scornicesti" },
  { nume: "Surpeni", comuna: "Poboru" },
  { nume: "Tabaci", comuna: "Vulpeni" },
  { nume: "Tabonu", comuna: "Obarsia" },
  { nume: "Tătuleşti", simplu: "Tatulesti" },
  { nume: "Teiş", simplu: "Teis", comuna: "Bals" },
  { nume: "Teiuş", simplu: "Teius", comuna: "Scornicesti" },
  { nume: "Teiuşu", simplu: "Teiusu", comuna: "Brebeni" },
  { nume: "Teslui" },
  { nume: "Tia Mare" },
  { nume: "Tirişneag", simplu: "Tirisneag", comuna: "Valeni" },
  { nume: "Tomeni", comuna: "Osica De Sus" },
  { nume: "Toneşti", simplu: "Tonesti", comuna: "Leleasca" },
  { nume: "Toneşti", simplu: "Tonesti", comuna: "Samburesti" },
  { nume: "Topana" },
  { nume: "Traian" },
  { nume: "Trepteni", comuna: "Vitomiresti" },
  { nume: "Trufineşti", simplu: "Trufinesti", comuna: "Potcoava" },
  { nume: "Tudor Vladimirescu", comuna: "Corabia" },
  { nume: "Tufaru", comuna: "Leleasca" },
  { nume: "Tufeni" },
  { nume: "Turia", comuna: "Valea Mare" },
  { nume: "Ulmet", comuna: "Dobrun" },
  { nume: "Ulmi", comuna: "Milcov" },
  { nume: "Ungureni", comuna: "Topana" },
  { nume: "Uria", comuna: "Sprancenata" },
  { nume: "Ursa", comuna: "Garcov" },
  { nume: "Urşi", simplu: "Ursi", comuna: "Leleasca" },
  { nume: "Ursoaia", comuna: "Icoana" },
  { nume: "Urzica" },
  { nume: "Vădastra", simplu: "Vadastra" },
  { nume: "Vădăstriţa", simplu: "Vadastrita" },
  { nume: "Vâlcele", simplu: "Valcele" },
  { nume: "Vâlcelele de Sus", simplu: "Valcelele de Sus", comuna: "Valcele" },
  { nume: "Valea Fetei", comuna: "Verguleasa" },
  { nume: "Valea lui Alb", comuna: "Vulturesti" },
  { nume: "Valea Mare" },
  { nume: "Valea Merilor", comuna: "Potcoava" },
  { nume: "Valea Satului", comuna: "Vulpeni" },
  { nume: "Valea Soarelui", comuna: "Redea" },
  { nume: "Văleni", simplu: "Valeni" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Brancoveni" },
  { nume: "Vâneşti", simplu: "Vanesti", comuna: "Verguleasa" },
  { nume: "Vârtopu", simplu: "Vartopu", comuna: "Corabia" },
  { nume: "Verguleasa" },
  { nume: "Vineţi", simplu: "Vineti", comuna: "Spineni" },
  { nume: "Vişina Nouă", simplu: "Visina Noua", comuna: "Vadastra" },
  { nume: "Vişina", simplu: "Visina" },
  { nume: "Vităneşti", simplu: "Vitanesti", comuna: "Optasi-Magura" },
  { nume: "Vitomireşti", simplu: "Vitomiresti" },
  { nume: "Vlădila Nouă", simplu: "Vladila Noua", comuna: "Vladila" },
  { nume: "Vlădila", simplu: "Vladila" },
  { nume: "Vlăduleni", simplu: "Vladuleni", comuna: "Osica De Sus" },
  { nume: "Vlaici", comuna: "Colonesti" },
  { nume: "Vlăngăreşti", simplu: "Vlangaresti", comuna: "Vulturesti" },
  { nume: "Voineasa" },
  { nume: "Vulpeni" },
  { nume: "Vulpeşti", simplu: "Vulpesti", comuna: "Dobroteasa" },
  { nume: "Vultureşti", simplu: "Vulturesti" },
  { nume: "Zănoaga", simplu: "Zanoaga", comuna: "Daneasa" },
  { nume: "Zorleasca", comuna: "Valea Mare" },
];
