export const ph = [
  { nume: "Adunati" },
  { nume: "Albesti-Paleologu" },
  { nume: "Alunis" },
  { nume: "Apostolache" },
  { nume: "Aricestii Rahtivani" },
  { nume: "Aricestii Zeletin" },
  { nume: "Azuga" },
  { nume: "Baba Ana" },
  { nume: "Balta Doamnei" },
  { nume: "Berceni" },
  { nume: "Bertea" },
  { nume: "Blejoi" },
  { nume: "Boldesti-Scaeni" },
  { nume: "Bucov" },
  { nume: "Busteni" },
  { nume: "Baicoi" },
  { nume: "Baltesti" },
  { nume: "Banesti" },
  { nume: "Barcanesti" },
  { nume: "Cerasu" },
  { nume: "Chiojdeanca" },
  { nume: "Cocorastii Mislii" },
  { nume: "Colceag" },
  { nume: "Comarnic" },
  { nume: "Campina" },
  { nume: "Calugareni" },
  { nume: "Carbunesti" },
  { nume: "Draganesti" },
  { nume: "Dumbrava" },
  { nume: "Dumbravesti" },
  { nume: "Filipestii de Padure" },
  { nume: "Filipestii de Targ" },
  { nume: "Floresti" },
  { nume: "Fantanele" },
  { nume: "Gherghita" },
  { nume: "Gorgota" },
  { nume: "Gornet" },
  { nume: "Gornet-Cricov" },
  { nume: "Gura Vadului" },
  { nume: "Gura Vitioarei" },
  { nume: "Iordacheanu" },
  { nume: "Izvoarele" },
  { nume: "Jugureni" },
  { nume: "Lapos" },
  { nume: "Lipanesti" },
  { nume: "Mizil" },
  { nume: "Magurele" },
  { nume: "Magureni" },
  { nume: "Manesti" },
  { nume: "Ploiesti" },
  { nume: "Plopeni" },
  { nume: "Plopu" },
  { nume: "Podenii Noi" },
  { nume: "Poiana Campina" },
  { nume: "Poienarii Burchii" },
  { nume: "Provita de Jos" },
  { nume: "Provita de Sus" },
  { nume: "Puchenii Mari" },
  { nume: "Pacureti" },
  { nume: "Paulesti" },
  { nume: "Rafov" },
  { nume: "Salcia" },
  { nume: "Scorteni" },
  { nume: "Secaria" },
  { nume: "Sinaia" },
  { nume: "Slanic" },
  { nume: "Starchiojd" },
  { nume: "Surani" },
  { nume: "Sangeru" },
  { nume: "Salciile" },
  { nume: "Talea" },
  { nume: "Teisani" },
  { nume: "Telega" },
  { nume: "Tinosu" },
  { nume: "Tomsani" },
  { nume: "Targsoru Vechi" },
  { nume: "Tataru" },
  { nume: "Urlati" },
  { nume: "Valea Calugareasca" },
  { nume: "Valcanesti" },
  { nume: "Valenii de Munte" },
  { nume: "Varbilau" },
  { nume: "Sirna" },
  { nume: "Soimari" },
  { nume: "Sotrile" },
  { nume: "Stefesti" },
  { nume: "Ocina de Jos", comuna: "Adunati" },
  { nume: "Ocina de Sus", comuna: "Adunati" },
  { nume: "Albesti-Muru", comuna: "Albesti-Paleologu" },
  { nume: "Cioceni", comuna: "Albesti-Paleologu" },
  { nume: "Vadu Parului", comuna: "Albesti-Paleologu" },
  { nume: "Ostrovu", comuna: "Alunis" },
  { nume: "Buzota", comuna: "Apostolache" },
  { nume: "Marlogea", comuna: "Apostolache" },
  { nume: "Udresti", comuna: "Apostolache" },
  { nume: "Valea Cricovului", comuna: "Apostolache" },
  { nume: "Buda", comuna: "Aricestii Rahtivani" },
  { nume: "Nedelea", comuna: "Aricestii Rahtivani" },
  { nume: "Stoenesti", comuna: "Aricestii Rahtivani" },
  { nume: "Targsoru Nou", comuna: "Aricestii Rahtivani" },
  { nume: "Albinari", comuna: "Aricestii Zeletin" },
  { nume: "Ciresanu", comuna: "Baba Ana" },
  { nume: "Conduratu", comuna: "Baba Ana" },
  { nume: "Crangurile", comuna: "Baba Ana" },
  { nume: "Satu Nou", comuna: "Baba Ana" },
  { nume: "Dambu", comuna: "Baicoi" },
  { nume: "Liliesti", comuna: "Baicoi" },
  { nume: "Schela", comuna: "Baicoi" },
  { nume: "Tufeni", comuna: "Baicoi" },
  { nume: "Tintea", comuna: "Baicoi" },
  { nume: "Bara", comuna: "Balta Doamnei" },
  { nume: "Curcubeu", comuna: "Balta Doamnei" },
  { nume: "Lacu Turcului", comuna: "Balta Doamnei" },
  { nume: "Izesti", comuna: "Baltesti" },
  { nume: "Podenii Vechi", comuna: "Baltesti" },
  { nume: "Urleta", comuna: "Banesti" },
  { nume: "Ghighiu", comuna: "Barcanesti" },
  { nume: "Puscasi", comuna: "Barcanesti" },
  { nume: "Romanesti", comuna: "Barcanesti" },
  { nume: "Tatarani", comuna: "Barcanesti" },
  { nume: "Cartierul Dambu", comuna: "Berceni" },
  { nume: "Corlatesti", comuna: "Berceni" },
  { nume: "Catunu", comuna: "Berceni" },
  { nume: "Moara Noua", comuna: "Berceni" },
  { nume: "Lutu Rosu", comuna: "Bertea" },
  { nume: "Ploiestiori", comuna: "Blejoi" },
  { nume: "Tantareni", comuna: "Blejoi" },
  { nume: "Boldesti", comuna: "Boldesti-Gradistea" },
  { nume: "Gradistea", comuna: "Boldesti-Gradistea" },
  { nume: "Seciu", comuna: "Boldesti-Scaeni" },
  { nume: "Brazii de Jos", comuna: "Brazi" },
  { nume: "Brazii de Sus", comuna: "Brazi" },
  { nume: "Batesti", comuna: "Brazi" },
  { nume: "Negoiesti", comuna: "Brazi" },
  { nume: "Popesti", comuna: "Brazi" },
  { nume: "Stejaru", comuna: "Brazi" },
  { nume: "Breaza de Jos", comuna: "Breaza" },
  { nume: "Breaza de Sus", comuna: "Breaza" },
  { nume: "Frasinet", comuna: "Breaza" },
  { nume: "Gura Beliei", comuna: "Breaza" },
  { nume: "Irimesti", comuna: "Breaza" },
  { nume: "Nistoresti", comuna: "Breaza" },
  { nume: "Podu Corbului", comuna: "Breaza" },
  { nume: "Podu Vadului", comuna: "Breaza" },
  { nume: "Surdesti", comuna: "Breaza" },
  { nume: "Valea Tarsei", comuna: "Breaza" },
  { nume: "Brebu Megiesesc", comuna: "Brebu" },
  { nume: "Brebu Manastirei", comuna: "Brebu" },
  { nume: "Pietriceaua", comuna: "Brebu" },
  { nume: "Podu Cheii", comuna: "Brebu" },
  { nume: "Bighilin", comuna: "Bucov" },
  { nume: "Chitorani", comuna: "Bucov" },
  { nume: "Pleasa", comuna: "Bucov" },
  { nume: "Valea Orlei", comuna: "Bucov" },
  { nume: "Poiana Tapului", comuna: "Busteni" },
  { nume: "Valea Scheilor", comuna: "Calugareni" },
  { nume: "Gogeasca", comuna: "Carbunesti" },
  { nume: "Ceptura de Jos", comuna: "Ceptura" },
  { nume: "Ceptura de Sus", comuna: "Ceptura" },
  { nume: "Malu Rosu", comuna: "Ceptura" },
  { nume: "Rotari", comuna: "Ceptura" },
  { nume: "Soimesti", comuna: "Ceptura" },
  { nume: "Slon", comuna: "Cerasu" },
  { nume: "Valea Borului", comuna: "Cerasu" },
  { nume: "Valea Bradetului", comuna: "Cerasu" },
  { nume: "Valea Lespezii", comuna: "Cerasu" },
  { nume: "Valea Tocii", comuna: "Cerasu" },
  { nume: "Nucet", comuna: "Chiojdeanca" },
  { nume: "Trenu", comuna: "Chiojdeanca" },
  { nume: "Cioranii de Jos", comuna: "Ciorani" },
  { nume: "Cioranii de Sus", comuna: "Ciorani" },
  { nume: "Goruna", comuna: "Cocorastii Mislii" },
  { nume: "Tiparesti", comuna: "Cocorastii Mislii" },
  { nume: "Inotesti", comuna: "Colceag" },
  { nume: "Parepa-Rusani", comuna: "Colceag" },
  { nume: "Valcelele", comuna: "Colceag" },
  { nume: "Ghiosesti", comuna: "Comarnic" },
  { nume: "Podu Lung", comuna: "Comarnic" },
  { nume: "Poiana", comuna: "Comarnic" },
  { nume: "Posada", comuna: "Comarnic" },
  { nume: "Cornu de Jos", comuna: "Cornu" },
  { nume: "Cornu de Sus", comuna: "Cornu" },
  { nume: "Valea Oprii", comuna: "Cornu" },
  { nume: "Cosmina de Jos", comuna: "Cosminele" },
  { nume: "Cosmina de Sus", comuna: "Cosminele" },
  { nume: "Draghicesti", comuna: "Cosminele" },
  { nume: "Poiana Trestiei", comuna: "Cosminele" },
  { nume: "Belciug", comuna: "Draganesti" },
  { nume: "Baraitaru", comuna: "Draganesti" },
  { nume: "Cornu de Jos", comuna: "Draganesti" },
  { nume: "Hatcarau", comuna: "Draganesti" },
  { nume: "Meri", comuna: "Draganesti" },
  { nume: "Tufani", comuna: "Draganesti" },
  { nume: "Ciocrac", comuna: "Drajna" },
  { nume: "Catunu", comuna: "Drajna" },
  { nume: "Drajna de Jos", comuna: "Drajna" },
  { nume: "Drajna de Sus", comuna: "Drajna" },
  { nume: "Faget", comuna: "Drajna" },
  { nume: "Ogretin", comuna: "Drajna" },
  { nume: "Piatra", comuna: "Drajna" },
  { nume: "Pitigoi", comuna: "Drajna" },
  { nume: "Plai", comuna: "Drajna" },
  { nume: "Podurile", comuna: "Drajna" },
  { nume: "Poiana Mierlei", comuna: "Drajna" },
  { nume: "Ciupelnita", comuna: "Dumbrava" },
  { nume: "Cornu de Sus", comuna: "Dumbrava" },
  { nume: "Trestienii de Jos", comuna: "Dumbrava" },
  { nume: "Trestienii de Sus", comuna: "Dumbrava" },
  { nume: "Zanoaga", comuna: "Dumbrava" },
  { nume: "Gavanel", comuna: "Dumbravesti" },
  { nume: "Malaestii de Jos", comuna: "Dumbravesti" },
  { nume: "Malaestii de Sus", comuna: "Dumbravesti" },
  { nume: "Plopeni", comuna: "Dumbravesti" },
  { nume: "Sfarleanca", comuna: "Dumbravesti" },
  { nume: "Bozieni", comuna: "Fantanele" },
  { nume: "Ghinoaica", comuna: "Fantanele" },
  { nume: "Ungureni", comuna: "Fantanele" },
  { nume: "Vadu Sapat", comuna: "Fantanele" },
  { nume: "Ditesti", comuna: "Filipestii De Padure" },
  { nume: "Minieri", comuna: "Filipestii De Padure" },
  { nume: "Silistea Dealului", comuna: "Filipestii De Padure" },
  { nume: "Bratasanca", comuna: "Filipestii De Targ" },
  { nume: "Ezeni", comuna: "Filipestii De Targ" },
  { nume: "Marginenii de Jos", comuna: "Filipestii De Targ" },
  { nume: "Ungureni", comuna: "Filipestii De Targ" },
  { nume: "Cap Rosu", comuna: "Floresti" },
  { nume: "Calinesti", comuna: "Floresti" },
  { nume: "Catina", comuna: "Floresti" },
  { nume: "Novacesti", comuna: "Floresti" },
  { nume: "Fulga de Jos", comuna: "Fulga" },
  { nume: "Fulga de Sus", comuna: "Fulga" },
  { nume: "Fanari", comuna: "Gherghita" },
  { nume: "Independenta", comuna: "Gherghita" },
  { nume: "Malamuc", comuna: "Gherghita" },
  { nume: "Olari", comuna: "Gherghita" },
  { nume: "Olarii Vechi", comuna: "Gherghita" },
  { nume: "Ungureni", comuna: "Gherghita" },
  { nume: "Crivina", comuna: "Gorgota" },
  { nume: "Fanari", comuna: "Gorgota" },
  { nume: "Poienarii Apostoli", comuna: "Gorgota" },
  { nume: "Potigrafu", comuna: "Gorgota" },
  { nume: "Bogdanesti", comuna: "Gornet" },
  { nume: "Cuib", comuna: "Gornet" },
  { nume: "Nucet", comuna: "Gornet" },
  { nume: "Coserele", comuna: "Gornet-Cricov" },
  { nume: "Dobrota", comuna: "Gornet-Cricov" },
  { nume: "Priseaca", comuna: "Gornet-Cricov" },
  { nume: "Valea Seaca", comuna: "Gornet-Cricov" },
  { nume: "Tarculesti", comuna: "Gornet-Cricov" },
  { nume: "Persunari", comuna: "Gura Vadului" },
  { nume: "Tohani", comuna: "Gura Vadului" },
  { nume: "Bughea de Jos", comuna: "Gura Vitioarei" },
  { nume: "Fundeni", comuna: "Gura Vitioarei" },
  { nume: "Fagetu", comuna: "Gura Vitioarei" },
  { nume: "Poiana Copaceni", comuna: "Gura Vitioarei" },
  { nume: "Mocesti", comuna: "Iordacheanu" },
  { nume: "Plavia", comuna: "Iordacheanu" },
  { nume: "Straosti", comuna: "Iordacheanu" },
  { nume: "Valea Cucului", comuna: "Iordacheanu" },
  { nume: "Varbila", comuna: "Iordacheanu" },
  { nume: "Cernesti", comuna: "Izvoarele" },
  { nume: "Chiritesti", comuna: "Izvoarele" },
  { nume: "Homoraciu", comuna: "Izvoarele" },
  { nume: "Malu Vanat", comuna: "Izvoarele" },
  { nume: "Schiulesti", comuna: "Izvoarele" },
  { nume: "Boboci", comuna: "Jugureni" },
  { nume: "Marginea Padurii", comuna: "Jugureni" },
  { nume: "Valea Unghiului", comuna: "Jugureni" },
  { nume: "Glod", comuna: "Lapos" },
  { nume: "Laposel", comuna: "Lapos" },
  { nume: "Pietricica", comuna: "Lapos" },
  { nume: "Satu Nou", comuna: "Lipanesti" },
  { nume: "Zamfira", comuna: "Lipanesti" },
  { nume: "Sipotu", comuna: "Lipanesti" },
  { nume: "Coada Malului", comuna: "Magurele" },
  { nume: "Iazu", comuna: "Magurele" },
  { nume: "Cocorastii Caplii", comuna: "Magureni" },
  { nume: "Lunca Prahovei", comuna: "Magureni" },
  { nume: "Cheia", comuna: "Maneciu" },
  { nume: "Chiciureni", comuna: "Maneciu" },
  { nume: "Costeni", comuna: "Maneciu" },
  { nume: "Facaieni", comuna: "Maneciu" },
  { nume: "Gheaba", comuna: "Maneciu" },
  { nume: "Manastirea Suzana", comuna: "Maneciu" },
  { nume: "Maneciu-Pamanteni", comuna: "Maneciu" },
  { nume: "Maneciu-Ungureni", comuna: "Maneciu" },
  { nume: "Plaietu", comuna: "Maneciu" },
  { nume: "Baltita", comuna: "Manesti" },
  { nume: "Chesnoiu", comuna: "Manesti" },
  { nume: "Coada Izvorului", comuna: "Manesti" },
  { nume: "Cocorastii Colt", comuna: "Manesti" },
  { nume: "Cocorastii Grind", comuna: "Manesti" },
  { nume: "Coltu de Jos", comuna: "Manesti" },
  { nume: "Ghioldum", comuna: "Manesti" },
  { nume: "Gura Crivatului", comuna: "Manesti" },
  { nume: "Persunari", comuna: "Manesti" },
  { nume: "Piatra", comuna: "Manesti" },
  { nume: "Satu de Sus", comuna: "Manesti" },
  { nume: "Zalhanaua", comuna: "Manesti" },
  { nume: "Fefelei", comuna: "Mizil" },
  { nume: "Barzila", comuna: "Pacureti" },
  { nume: "Curmatura", comuna: "Pacureti" },
  { nume: "Matita", comuna: "Pacureti" },
  { nume: "Slavu", comuna: "Pacureti" },
  { nume: "Cocosesti", comuna: "Paulesti" },
  { nume: "Gageni", comuna: "Paulesti" },
  { nume: "Paulestii Noi", comuna: "Paulesti" },
  { nume: "Galmeia", comuna: "Plopu" },
  { nume: "Harsa", comuna: "Plopu" },
  { nume: "Nisipoasa", comuna: "Plopu" },
  { nume: "Ghiocel", comuna: "Podenii Noi" },
  { nume: "Mehedinta", comuna: "Podenii Noi" },
  { nume: "Nevesteasca", comuna: "Podenii Noi" },
  { nume: "Podu lui Galben", comuna: "Podenii Noi" },
  { nume: "Popesti", comuna: "Podenii Noi" },
  { nume: "Rahova", comuna: "Podenii Noi" },
  { nume: "Sfacaru", comuna: "Podenii Noi" },
  { nume: "Salcioara", comuna: "Podenii Noi" },
  { nume: "Valea Dulce", comuna: "Podenii Noi" },
  { nume: "Bobolia", comuna: "Poiana Campina" },
  { nume: "Pietrisu", comuna: "Poiana Campina" },
  { nume: "Ragman", comuna: "Poiana Campina" },
  { nume: "Carbunari", comuna: "Poienarii Burchii" },
  { nume: "Ologeni", comuna: "Poienarii Burchii" },
  { nume: "Pioresti", comuna: "Poienarii Burchii" },
  { nume: "Podu Valeni", comuna: "Poienarii Burchii" },
  { nume: "Poienarii Rali", comuna: "Poienarii Burchii" },
  { nume: "Poienarii Vechi", comuna: "Poienarii Burchii" },
  { nume: "Tatarai", comuna: "Poienarii Burchii" },
  { nume: "Bodesti", comuna: "Posesti" },
  { nume: "Merdeala", comuna: "Posesti" },
  { nume: "Nucsoara de Jos", comuna: "Posesti" },
  { nume: "Nucsoara de Sus", comuna: "Posesti" },
  { nume: "Posestii Ungureni", comuna: "Posesti" },
  { nume: "Posestii-Pamanteni", comuna: "Posesti" },
  { nume: "Tarlesti", comuna: "Posesti" },
  { nume: "Valea Plopului", comuna: "Posesti" },
  { nume: "Valea Screzii", comuna: "Posesti" },
  { nume: "Valea Stupinii", comuna: "Posesti" },
  { nume: "Bobicesti", comuna: "Predeal-Sarari" },
  { nume: "Poienile", comuna: "Predeal-Sarari" },
  { nume: "Predeal", comuna: "Predeal-Sarari" },
  { nume: "Sarari", comuna: "Predeal-Sarari" },
  { nume: "Saratel", comuna: "Predeal-Sarari" },
  { nume: "Tulburea", comuna: "Predeal-Sarari" },
  { nume: "Tulburea Valeni", comuna: "Predeal-Sarari" },
  { nume: "Vitioara de Sus", comuna: "Predeal-Sarari" },
  { nume: "Zambroaia", comuna: "Predeal-Sarari" },
  { nume: "Draganeasa", comuna: "Provita De Jos" },
  { nume: "Piatra", comuna: "Provita De Jos" },
  { nume: "Izvoru", comuna: "Provita De Sus" },
  { nume: "Plaiu", comuna: "Provita De Sus" },
  { nume: "Valea Bradului", comuna: "Provita De Sus" },
  { nume: "Miroslavesti", comuna: "Puchenii Mari" },
  { nume: "Moara", comuna: "Puchenii Mari" },
  { nume: "Odaile", comuna: "Puchenii Mari" },
  { nume: "Pietrosani", comuna: "Puchenii Mari" },
  { nume: "Puchenii Mici", comuna: "Puchenii Mari" },
  { nume: "Puchenii Mosneni", comuna: "Puchenii Mari" },
  { nume: "Antofiloaia", comuna: "Rafov" },
  { nume: "Buchilasi", comuna: "Rafov" },
  { nume: "Buda", comuna: "Rafov" },
  { nume: "Goga", comuna: "Rafov" },
  { nume: "Moara Domneasca", comuna: "Rafov" },
  { nume: "Malaiesti", comuna: "Rafov" },
  { nume: "Palanca", comuna: "Rafov" },
  { nume: "Sicrita", comuna: "Rafov" },
  { nume: "Butuci", comuna: "Sangeru" },
  { nume: "Miresu Mare", comuna: "Sangeru" },
  { nume: "Miresu Mic", comuna: "Sangeru" },
  { nume: "Piatra Mica", comuna: "Sangeru" },
  { nume: "Tisa", comuna: "Sangeru" },
  { nume: "Bordenii Mari", comuna: "Scorteni" },
  { nume: "Bordenii Mici", comuna: "Scorteni" },
  { nume: "Mislea", comuna: "Scorteni" },
  { nume: "Sarca", comuna: "Scorteni" },
  { nume: "Bratesti", comuna: "Sirna" },
  { nume: "Coceana", comuna: "Sirna" },
  { nume: "Habud", comuna: "Sirna" },
  { nume: "Tariceni", comuna: "Sirna" },
  { nume: "Varnita", comuna: "Sirna" },
  { nume: "Grosani", comuna: "Slanic" },
  { nume: "Prajani", comuna: "Slanic" },
  { nume: "Lopatnita", comuna: "Soimari" },
  { nume: "Magura", comuna: "Soimari" },
  { nume: "Lunca Mare", comuna: "Sotrile" },
  { nume: "Plaiu Cornului", comuna: "Sotrile" },
  { nume: "Plaiu Campinei", comuna: "Sotrile" },
  { nume: "Seciuri", comuna: "Sotrile" },
  { nume: "Vistieru", comuna: "Sotrile" },
  { nume: "Bradet", comuna: "Starchiojd" },
  { nume: "Batrani", comuna: "Starchiojd" },
  { nume: "Gresia", comuna: "Starchiojd" },
  { nume: "Poiana Mare", comuna: "Starchiojd" },
  { nume: "Rotarea", comuna: "Starchiojd" },
  { nume: "Valea Anei", comuna: "Starchiojd" },
  { nume: "Zmeuret", comuna: "Starchiojd" },
  { nume: "Scurtesti", comuna: "Stefesti" },
  { nume: "Tarsoreni", comuna: "Stefesti" },
  { nume: "Pacuri", comuna: "Surani" },
  { nume: "Plaiu", comuna: "Talea" },
  { nume: "Strejnicu", comuna: "Targsoru Vechi" },
  { nume: "Stancesti", comuna: "Targsoru Vechi" },
  { nume: "Zahanaua", comuna: "Targsoru Vechi" },
  { nume: "Podgoria", comuna: "Tataru" },
  { nume: "Silistea", comuna: "Tataru" },
  { nume: "Bugnea de Sus", comuna: "Teisani" },
  { nume: "Olteni", comuna: "Teisani" },
  { nume: "Valea Stalpului", comuna: "Teisani" },
  { nume: "Stubeiu", comuna: "Teisani" },
  { nume: "Bosilcesti", comuna: "Telega" },
  { nume: "Bustenari", comuna: "Telega" },
  { nume: "Doftana", comuna: "Telega" },
  { nume: "Melicesti", comuna: "Telega" },
  { nume: "Tontesti", comuna: "Telega" },
  { nume: "Pisculesti", comuna: "Tinosu" },
  { nume: "Predesti", comuna: "Tinosu" },
  { nume: "Loloiasca", comuna: "Tomsani" },
  { nume: "Magula", comuna: "Tomsani" },
  { nume: "Satucu", comuna: "Tomsani" },
  { nume: "Arionestii Noi", comuna: "Urlati" },
  { nume: "Arionestii Vechi", comuna: "Urlati" },
  { nume: "Cherba", comuna: "Urlati" },
  { nume: "Jercalai", comuna: "Urlati" },
  { nume: "Maruntis", comuna: "Urlati" },
  { nume: "Orzoaia de Jos", comuna: "Urlati" },
  { nume: "Orzoaia de Sus", comuna: "Urlati" },
  { nume: "Schiau", comuna: "Urlati" },
  { nume: "Ulmi", comuna: "Urlati" },
  { nume: "Valea Bobului", comuna: "Urlati" },
  { nume: "Valea Crangului", comuna: "Urlati" },
  { nume: "Valea Mieilor", comuna: "Urlati" },
  { nume: "Valea Nucetului", comuna: "Urlati" },
  { nume: "Valea Pietrei", comuna: "Urlati" },
  { nume: "Valea Seman", comuna: "Urlati" },
  { nume: "Valea Urloii", comuna: "Urlati" },
  { nume: "Carjari", comuna: "Valcanesti" },
  { nume: "Trestioara", comuna: "Valcanesti" },
  { nume: "Arva", comuna: "Valea Calugareasca" },
  { nume: "Coslegi", comuna: "Valea Calugareasca" },
  { nume: "Darvari", comuna: "Valea Calugareasca" },
  { nume: "Pantazi", comuna: "Valea Calugareasca" },
  { nume: "Rachieri", comuna: "Valea Calugareasca" },
  { nume: "Radila", comuna: "Valea Calugareasca" },
  { nume: "Schiau", comuna: "Valea Calugareasca" },
  { nume: "Valea Larga", comuna: "Valea Calugareasca" },
  { nume: "Valea Mantei", comuna: "Valea Calugareasca" },
  { nume: "Valea Nicovani", comuna: "Valea Calugareasca" },
  { nume: "Valea Poienii", comuna: "Valea Calugareasca" },
  { nume: "Valea Popii", comuna: "Valea Calugareasca" },
  { nume: "Valea Ursoii", comuna: "Valea Calugareasca" },
  { nume: "Varfurile", comuna: "Valea Calugareasca" },
  { nume: "Tesila", comuna: "Valea Doftanei" },
  { nume: "Traisteni", comuna: "Valea Doftanei" },
  { nume: "Cotofenesti", comuna: "Varbilau" },
  { nume: "Livadea", comuna: "Varbilau" },
  { nume: "Podu Ursului", comuna: "Varbilau" },
  { nume: "Poiana Varbilau", comuna: "Varbilau" },
];
