export const ph = [
  { nume: "Adunați", simplu: "Adunati" },
  { nume: "Albești-Muru", simplu: "Albesti-Muru", comuna: "Albesti-Paleologu" },
  { nume: "Albești-Paleologu", simplu: "Albesti-Paleologu" },
  { nume: "Albinari", comuna: "Aricestii Zeletin" },
  { nume: "Aluniș", simplu: "Alunis" },
  { nume: "Antofiloaia", comuna: "Rafov" },
  { nume: "Apostolache" },
  { nume: "Ariceștii Rahtivani", simplu: "Aricestii Rahtivani" },
  { nume: "Ariceștii Zeletin", simplu: "Aricestii Zeletin" },
  { nume: "Arioneștii Noi", simplu: "Arionestii Noi", comuna: "Urlati" },
  { nume: "Arioneștii Vechi", simplu: "Arionestii Vechi", comuna: "Urlati" },
  { nume: "Arva", comuna: "Valea Calugareasca" },
  { nume: "Azuga" },
  { nume: "Baba Ana" },
  { nume: "Băicoi", simplu: "Baicoi" },
  { nume: "Balta Doamnei" },
  { nume: "Bălțești", simplu: "Baltesti" },
  { nume: "Băltița", simplu: "Baltita", comuna: "Manesti" },
  { nume: "Bănești", simplu: "Banesti" },
  { nume: "Bâra", simplu: "Bara", comuna: "Balta Doamnei" },
  { nume: "Bărăitaru", simplu: "Baraitaru", comuna: "Draganesti" },
  { nume: "Bărcănești", simplu: "Barcanesti" },
  { nume: "Bărzila", simplu: "Barzila", comuna: "Pacureti" },
  { nume: "Bătești", simplu: "Batesti", comuna: "Brazi" },
  { nume: "Bătrâni", simplu: "Batrani", comuna: "Starchiojd" },
  { nume: "Belciug", comuna: "Draganesti" },
  { nume: "Berceni" },
  { nume: "Bertea" },
  { nume: "Bighilin", comuna: "Bucov" },
  { nume: "Blejoi" },
  { nume: "Bobicești", simplu: "Bobicesti", comuna: "Predeal-Sarari" },
  { nume: "Boboci", comuna: "Jugureni" },
  { nume: "Bobolia", comuna: "Poiana Campina" },
  { nume: "Bodești", simplu: "Bodesti", comuna: "Posesti" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Gornet" },
  { nume: "Boldești-Scăeni", simplu: "Boldesti-Scaeni" },
  { nume: "Boldești", simplu: "Boldesti", comuna: "Boldesti-Gradistea" },
  { nume: "Bordenii Mari", comuna: "Scorteni" },
  { nume: "Bordenii Mici", comuna: "Scorteni" },
  { nume: "Boșilcești", simplu: "Bosilcesti", comuna: "Telega" },
  { nume: "Bozieni", comuna: "Fantanele" },
  { nume: "Brădet", simplu: "Bradet", comuna: "Starchiojd" },
  { nume: "Brătășanca", simplu: "Bratasanca", comuna: "Filipestii De Targ" },
  { nume: "Brătești", simplu: "Bratesti", comuna: "Sirna" },
  { nume: "Brazii de Jos", comuna: "Brazi" },
  { nume: "Brazii de Sus", comuna: "Brazi" },
  { nume: "Breaza de Jos", comuna: "Breaza" },
  { nume: "Breaza de Sus", comuna: "Breaza" },
  { nume: "Brebu Mânăstirei", simplu: "Brebu Manastirei", comuna: "Brebu" },
  { nume: "Brebu Megieșesc", simplu: "Brebu Megiesesc", comuna: "Brebu" },
  { nume: "Buchilași", simplu: "Buchilasi", comuna: "Rafov" },
  { nume: "Bucov" },
  { nume: "Buda", comuna: "Aricestii Rahtivani" },
  { nume: "Buda", comuna: "Rafov" },
  { nume: "Bughea de Jos", comuna: "Gura Vitioarei" },
  { nume: "Bugnea de Sus", comuna: "Teisani" },
  { nume: "Buștenari", simplu: "Bustenari", comuna: "Telega" },
  { nume: "Bușteni", simplu: "Busteni" },
  { nume: "Butuci", comuna: "Sangeru" },
  { nume: "Buzota", comuna: "Apostolache" },
  { nume: "Călinești", simplu: "Calinesti", comuna: "Floresti" },
  { nume: "Călugăreni", simplu: "Calugareni" },
  { nume: "Câmpina", simplu: "Campina" },
  { nume: "Cap Roșu", simplu: "Cap Rosu", comuna: "Floresti" },
  { nume: "Cărbunari", simplu: "Carbunari", comuna: "Poienarii Burchii" },
  { nume: "Cărbunești", simplu: "Carbunesti" },
  { nume: "Cârjari", simplu: "Carjari", comuna: "Valcanesti" },
  { nume: "Cartierul Dâmbu", simplu: "Cartierul Dambu", comuna: "Berceni" },
  { nume: "Cătina", simplu: "Catina", comuna: "Floresti" },
  { nume: "Cătunu", simplu: "Catunu", comuna: "Berceni" },
  { nume: "Cătunu", simplu: "Catunu", comuna: "Drajna" },
  { nume: "Ceptura de Jos", comuna: "Ceptura" },
  { nume: "Ceptura de Sus", comuna: "Ceptura" },
  { nume: "Cerașu", simplu: "Cerasu" },
  { nume: "Cernești", simplu: "Cernesti", comuna: "Izvoarele" },
  { nume: "Cheia", comuna: "Maneciu" },
  { nume: "Cherba", comuna: "Urlati" },
  { nume: "Cheșnoiu", simplu: "Chesnoiu", comuna: "Manesti" },
  { nume: "Chiciureni", comuna: "Maneciu" },
  { nume: "Chiojdeanca" },
  { nume: "Chirițești", simplu: "Chiritesti", comuna: "Izvoarele" },
  { nume: "Chițorani", simplu: "Chitorani", comuna: "Bucov" },
  { nume: "Cioceni", comuna: "Albesti-Paleologu" },
  { nume: "Ciocrac", comuna: "Drajna" },
  { nume: "Cioranii de Jos", comuna: "Ciorani" },
  { nume: "Cioranii de Sus", comuna: "Ciorani" },
  { nume: "Cireșanu", simplu: "Ciresanu", comuna: "Baba Ana" },
  { nume: "Ciupelnița", simplu: "Ciupelnita", comuna: "Dumbrava" },
  { nume: "Coada Izvorului", comuna: "Manesti" },
  { nume: "Coada Malului", comuna: "Magurele" },
  { nume: "Coceana", comuna: "Sirna" },
  {
    nume: "Cocorăștii Caplii",
    simplu: "Cocorastii Caplii",
    comuna: "Magureni",
  },
  { nume: "Cocorăștii Colț", simplu: "Cocorastii Colt", comuna: "Manesti" },
  { nume: "Cocorăștii Grind", simplu: "Cocorastii Grind", comuna: "Manesti" },
  { nume: "Cocorăștii Mislii", simplu: "Cocorastii Mislii" },
  { nume: "Cocoșești", simplu: "Cocosesti", comuna: "Paulesti" },
  { nume: "Colceag" },
  { nume: "Colțu de Jos", simplu: "Coltu de Jos", comuna: "Manesti" },
  { nume: "Comarnic" },
  { nume: "Conduratu", comuna: "Baba Ana" },
  { nume: "Corlătești", simplu: "Corlatesti", comuna: "Berceni" },
  { nume: "Cornu de Jos", comuna: "Cornu" },
  { nume: "Cornu de Jos", comuna: "Draganesti" },
  { nume: "Cornu de Sus", comuna: "Cornu" },
  { nume: "Cornu de Sus", comuna: "Dumbrava" },
  { nume: "Coșerele", simplu: "Coserele", comuna: "Gornet-Cricov" },
  { nume: "Coslegi", comuna: "Valea Calugareasca" },
  { nume: "Cosmina de Jos", comuna: "Cosminele" },
  { nume: "Cosmina de Sus", comuna: "Cosminele" },
  { nume: "Costeni", comuna: "Maneciu" },
  { nume: "Coțofenești", simplu: "Cotofenesti", comuna: "Varbilau" },
  { nume: "Crângurile", simplu: "Crangurile", comuna: "Baba Ana" },
  { nume: "Crivina", comuna: "Gorgota" },
  { nume: "Cuib", comuna: "Gornet" },
  { nume: "Curcubeu", comuna: "Balta Doamnei" },
  { nume: "Curmătura", simplu: "Curmatura", comuna: "Pacureti" },
  { nume: "Dâmbu", simplu: "Dambu", comuna: "Baicoi" },
  { nume: "Dârvari", simplu: "Darvari", comuna: "Valea Calugareasca" },
  { nume: "Dițești", simplu: "Ditesti", comuna: "Filipestii De Padure" },
  { nume: "Dobrota", comuna: "Gornet-Cricov" },
  { nume: "Doftana", comuna: "Telega" },
  { nume: "Drăgăneasa", simplu: "Draganeasa", comuna: "Provita De Jos" },
  { nume: "Drăgănești", simplu: "Draganesti" },
  { nume: "Drăghicești", simplu: "Draghicesti", comuna: "Cosminele" },
  { nume: "Drajna de Jos", comuna: "Drajna" },
  { nume: "Drajna de Sus", comuna: "Drajna" },
  { nume: "Dumbrava" },
  { nume: "Dumbrăvești", simplu: "Dumbravesti" },
  { nume: "Ezeni", comuna: "Filipestii De Targ" },
  { nume: "Făcăieni", simplu: "Facaieni", comuna: "Maneciu" },
  { nume: "Făget", simplu: "Faget", comuna: "Drajna" },
  { nume: "Făgetu", simplu: "Fagetu", comuna: "Gura Vitioarei" },
  { nume: "Fânari", simplu: "Fanari", comuna: "Gherghita" },
  { nume: "Fânari", simplu: "Fanari", comuna: "Gorgota" },
  { nume: "Fântânele", simplu: "Fantanele" },
  { nume: "Fefelei", comuna: "Mizil" },
  { nume: "Filipeștii de Pădure", simplu: "Filipestii de Padure" },
  { nume: "Filipeștii de Târg", simplu: "Filipestii de Targ" },
  { nume: "Florești", simplu: "Floresti" },
  { nume: "Frăsinet", simplu: "Frasinet", comuna: "Breaza" },
  { nume: "Fulga de Jos", comuna: "Fulga" },
  { nume: "Fulga de Sus", comuna: "Fulga" },
  { nume: "Fundeni", comuna: "Gura Vitioarei" },
  { nume: "Găgeni", simplu: "Gageni", comuna: "Paulesti" },
  { nume: "Gâlmeia", simplu: "Galmeia", comuna: "Plopu" },
  { nume: "Găvănel", simplu: "Gavanel", comuna: "Dumbravesti" },
  { nume: "Gheaba", comuna: "Maneciu" },
  { nume: "Gherghița", simplu: "Gherghita" },
  { nume: "Ghighiu", comuna: "Barcanesti" },
  { nume: "Ghinoaica", comuna: "Fantanele" },
  { nume: "Ghiocel", comuna: "Podenii Noi" },
  { nume: "Ghioldum", comuna: "Manesti" },
  { nume: "Ghioșești", simplu: "Ghiosesti", comuna: "Comarnic" },
  { nume: "Glod", comuna: "Lapos" },
  { nume: "Goga", comuna: "Rafov" },
  { nume: "Gogeasca", comuna: "Carbunesti" },
  { nume: "Gorgota" },
  { nume: "Gornet-Cricov" },
  { nume: "Gornet" },
  { nume: "Goruna", comuna: "Cocorastii Mislii" },
  { nume: "Gradiștea", simplu: "Gradistea", comuna: "Boldesti-Gradistea" },
  { nume: "Gresia", comuna: "Starchiojd" },
  { nume: "Groșani", simplu: "Grosani", comuna: "Slanic" },
  { nume: "Gura Beliei", comuna: "Breaza" },
  { nume: "Gura Crivățului", simplu: "Gura Crivatului", comuna: "Manesti" },
  { nume: "Gura Vadului" },
  { nume: "Gura Vitioarei" },
  { nume: "Hăbud", simplu: "Habud", comuna: "Sirna" },
  { nume: "Hârșa", simplu: "Harsa", comuna: "Plopu" },
  { nume: "Hătcărău", simplu: "Hatcarau", comuna: "Draganesti" },
  { nume: "Homorâciu", simplu: "Homoraciu", comuna: "Izvoarele" },
  { nume: "Iazu", comuna: "Magurele" },
  { nume: "Independența", simplu: "Independenta", comuna: "Gherghita" },
  { nume: "Inotești", simplu: "Inotesti", comuna: "Colceag" },
  { nume: "Iordăcheanu", simplu: "Iordacheanu" },
  { nume: "Irimești", simplu: "Irimesti", comuna: "Breaza" },
  { nume: "Izești", simplu: "Izesti", comuna: "Baltesti" },
  { nume: "Izvoarele" },
  { nume: "Izvoru", comuna: "Provita De Sus" },
  { nume: "Jercălăi", simplu: "Jercalai", comuna: "Urlati" },
  { nume: "Jugureni" },
  { nume: "Lacu Turcului", comuna: "Balta Doamnei" },
  { nume: "Lapoș", simplu: "Lapos" },
  { nume: "Lăpoșel", simplu: "Laposel", comuna: "Lapos" },
  { nume: "Liliești", simplu: "Liliesti", comuna: "Baicoi" },
  { nume: "Lipănești", simplu: "Lipanesti" },
  { nume: "Livadea", comuna: "Varbilau" },
  { nume: "Loloiasca", comuna: "Tomsani" },
  { nume: "Lopatnița", simplu: "Lopatnita", comuna: "Soimari" },
  { nume: "Lunca Mare", comuna: "Sotrile" },
  { nume: "Lunca Prahovei", comuna: "Magureni" },
  { nume: "Lutu Roșu", simplu: "Lutu Rosu", comuna: "Bertea" },
  { nume: "Magula", comuna: "Tomsani" },
  { nume: "Măgura", simplu: "Magura", comuna: "Soimari" },
  { nume: "Măgurele", simplu: "Magurele" },
  { nume: "Măgureni", simplu: "Magureni" },
  {
    nume: "Mălăeștii de Jos",
    simplu: "Malaestii de Jos",
    comuna: "Dumbravesti",
  },
  {
    nume: "Mălăeștii de Sus",
    simplu: "Malaestii de Sus",
    comuna: "Dumbravesti",
  },
  { nume: "Mălăiești", simplu: "Malaiesti", comuna: "Rafov" },
  { nume: "Malamuc", comuna: "Gherghita" },
  { nume: "Malu Roșu", simplu: "Malu Rosu", comuna: "Ceptura" },
  { nume: "Malu Vânăt", simplu: "Malu Vanat", comuna: "Izvoarele" },
  { nume: "Mânăstirea Suzana", simplu: "Manastirea Suzana", comuna: "Maneciu" },
  { nume: "Măneciu-Pământeni", simplu: "Maneciu-Pamanteni", comuna: "Maneciu" },
  { nume: "Măneciu-Ungureni", simplu: "Maneciu-Ungureni", comuna: "Maneciu" },
  { nume: "Mănești", simplu: "Manesti" },
  { nume: "Marginea Pădurii", simplu: "Marginea Padurii", comuna: "Jugureni" },
  {
    nume: "Mărginenii de Jos",
    simplu: "Marginenii de Jos",
    comuna: "Filipestii De Targ",
  },
  { nume: "Mârlogea", simplu: "Marlogea", comuna: "Apostolache" },
  { nume: "Mărunțiș", simplu: "Maruntis", comuna: "Urlati" },
  { nume: "Matița", simplu: "Matita", comuna: "Pacureti" },
  { nume: "Mehedința", simplu: "Mehedinta", comuna: "Podenii Noi" },
  { nume: "Melicești", simplu: "Melicesti", comuna: "Telega" },
  { nume: "Merdeala", comuna: "Posesti" },
  { nume: "Meri", comuna: "Draganesti" },
  { nume: "Minieri", comuna: "Filipestii De Padure" },
  { nume: "Mireșu Mare", simplu: "Miresu Mare", comuna: "Sangeru" },
  { nume: "Mireșu Mic", simplu: "Miresu Mic", comuna: "Sangeru" },
  { nume: "Miroslăvești", simplu: "Miroslavesti", comuna: "Puchenii Mari" },
  { nume: "Mislea", comuna: "Scorteni" },
  { nume: "Mizil" },
  { nume: "Moara Domnească", simplu: "Moara Domneasca", comuna: "Rafov" },
  { nume: "Moara Nouă", simplu: "Moara Noua", comuna: "Berceni" },
  { nume: "Moara", comuna: "Puchenii Mari" },
  { nume: "Mocești", simplu: "Mocesti", comuna: "Iordacheanu" },
  { nume: "Nedelea", comuna: "Aricestii Rahtivani" },
  { nume: "Negoiești", simplu: "Negoiesti", comuna: "Brazi" },
  { nume: "Nevesteasca", comuna: "Podenii Noi" },
  { nume: "Nisipoasa", comuna: "Plopu" },
  { nume: "Nistorești", simplu: "Nistoresti", comuna: "Breaza" },
  { nume: "Novăcești", simplu: "Novacesti", comuna: "Floresti" },
  { nume: "Nucet", comuna: "Chiojdeanca" },
  { nume: "Nucet", comuna: "Gornet" },
  { nume: "Nucșoara de Jos", simplu: "Nucsoara de Jos", comuna: "Posesti" },
  { nume: "Nucșoara de Sus", simplu: "Nucsoara de Sus", comuna: "Posesti" },
  { nume: "Ocina de Jos", comuna: "Adunati" },
  { nume: "Ocina de Sus", comuna: "Adunati" },
  { nume: "Odăile", simplu: "Odaile", comuna: "Puchenii Mari" },
  { nume: "Ogretin", comuna: "Drajna" },
  { nume: "Olari", comuna: "Gherghita" },
  { nume: "Olarii Vechi", comuna: "Gherghita" },
  { nume: "Ologeni", comuna: "Poienarii Burchii" },
  { nume: "Olteni", comuna: "Teisani" },
  { nume: "Orzoaia de Jos", comuna: "Urlati" },
  { nume: "Orzoaia de Sus", comuna: "Urlati" },
  { nume: "Ostrovu", comuna: "Alunis" },
  { nume: "Păcureți", simplu: "Pacureti" },
  { nume: "Păcuri", simplu: "Pacuri", comuna: "Surani" },
  { nume: "Palanca", comuna: "Rafov" },
  { nume: "Pantazi", comuna: "Valea Calugareasca" },
  { nume: "Parepa-Rușani", simplu: "Parepa-Rusani", comuna: "Colceag" },
  { nume: "Păulești", simplu: "Paulesti" },
  { nume: "Păuleștii Noi", simplu: "Paulestii Noi", comuna: "Paulesti" },
  { nume: "Perșunari", simplu: "Persunari", comuna: "Gura Vadului" },
  { nume: "Perșunari", simplu: "Persunari", comuna: "Manesti" },
  { nume: "Piatra Mică", simplu: "Piatra Mica", comuna: "Sangeru" },
  { nume: "Piatra", comuna: "Drajna" },
  { nume: "Piatra", comuna: "Manesti" },
  { nume: "Piatra", comuna: "Provita De Jos" },
  { nume: "Pietriceaua", comuna: "Brebu" },
  { nume: "Pietricica", comuna: "Lapos" },
  { nume: "Pietrișu", simplu: "Pietrisu", comuna: "Poiana Campina" },
  { nume: "Pietroșani", simplu: "Pietrosani", comuna: "Puchenii Mari" },
  { nume: "Piorești", simplu: "Pioresti", comuna: "Poienarii Burchii" },
  { nume: "Pisculești", simplu: "Pisculesti", comuna: "Tinosu" },
  { nume: "Pițigoi", simplu: "Pitigoi", comuna: "Drajna" },
  { nume: "Plai", comuna: "Drajna" },
  { nume: "Plăiețu", simplu: "Plaietu", comuna: "Maneciu" },
  { nume: "Plaiu Câmpinei", simplu: "Plaiu Campinei", comuna: "Sotrile" },
  { nume: "Plaiu Cornului", comuna: "Sotrile" },
  { nume: "Plaiu", comuna: "Provita De Sus" },
  { nume: "Plaiu", comuna: "Talea" },
  { nume: "Plavia", comuna: "Iordacheanu" },
  { nume: "Pleașa", simplu: "Pleasa", comuna: "Bucov" },
  { nume: "Ploiești", simplu: "Ploiesti" },
  { nume: "Ploieștiori", simplu: "Ploiestiori", comuna: "Blejoi" },
  { nume: "Plopeni" },
  { nume: "Plopeni", comuna: "Dumbravesti" },
  { nume: "Plopu" },
  { nume: "Podenii Noi" },
  { nume: "Podenii Vechi", comuna: "Baltesti" },
  { nume: "Podgoria", comuna: "Tataru" },
  { nume: "Podu Cheii", comuna: "Brebu" },
  { nume: "Podu Corbului", comuna: "Breaza" },
  { nume: "Podu lui Galben", comuna: "Podenii Noi" },
  { nume: "Podu Lung", comuna: "Comarnic" },
  { nume: "Podu Ursului", comuna: "Varbilau" },
  { nume: "Podu Vadului", comuna: "Breaza" },
  { nume: "Podu Văleni", simplu: "Podu Valeni", comuna: "Poienarii Burchii" },
  { nume: "Podurile", comuna: "Drajna" },
  { nume: "Poiana Câmpina", simplu: "Poiana Campina" },
  {
    nume: "Poiana Copăceni",
    simplu: "Poiana Copaceni",
    comuna: "Gura Vitioarei",
  },
  { nume: "Poiana Mare", comuna: "Starchiojd" },
  { nume: "Poiana Mierlei", comuna: "Drajna" },
  { nume: "Poiana Țapului", simplu: "Poiana Tapului", comuna: "Busteni" },
  { nume: "Poiana Trestiei", comuna: "Cosminele" },
  { nume: "Poiana Vărbilău", simplu: "Poiana Varbilau", comuna: "Varbilau" },
  { nume: "Poiana", comuna: "Comarnic" },
  { nume: "Poienarii Apostoli", comuna: "Gorgota" },
  { nume: "Poienarii Burchii" },
  { nume: "Poienarii Rali", comuna: "Poienarii Burchii" },
  { nume: "Poienarii Vechi", comuna: "Poienarii Burchii" },
  { nume: "Poienile", comuna: "Predeal-Sarari" },
  { nume: "Popești", simplu: "Popesti", comuna: "Brazi" },
  { nume: "Popești", simplu: "Popesti", comuna: "Podenii Noi" },
  { nume: "Posada", comuna: "Comarnic" },
  { nume: "Poseștii Ungureni", simplu: "Posestii Ungureni", comuna: "Posesti" },
  {
    nume: "Poseștii-Pământeni",
    simplu: "Posestii-Pamanteni",
    comuna: "Posesti",
  },
  { nume: "Potigrafu", comuna: "Gorgota" },
  { nume: "Prăjani", simplu: "Prajani", comuna: "Slanic" },
  { nume: "Predeal", comuna: "Predeal-Sarari" },
  { nume: "Predești", simplu: "Predesti", comuna: "Tinosu" },
  { nume: "Priseaca", comuna: "Gornet-Cricov" },
  { nume: "Provița de Jos", simplu: "Provita de Jos" },
  { nume: "Provița de Sus", simplu: "Provita de Sus" },
  { nume: "Puchenii Mari" },
  { nume: "Puchenii Mici", comuna: "Puchenii Mari" },
  {
    nume: "Puchenii Moșneni",
    simplu: "Puchenii Mosneni",
    comuna: "Puchenii Mari",
  },
  { nume: "Pușcași", simplu: "Puscasi", comuna: "Barcanesti" },
  { nume: "Rachieri", comuna: "Valea Calugareasca" },
  { nume: "Radila", comuna: "Valea Calugareasca" },
  { nume: "Râfov", simplu: "Rafov" },
  { nume: "Răgman", simplu: "Ragman", comuna: "Poiana Campina" },
  { nume: "Rahova", comuna: "Podenii Noi" },
  { nume: "Românești", simplu: "Romanesti", comuna: "Barcanesti" },
  { nume: "Rotarea", comuna: "Starchiojd" },
  { nume: "Rotari", comuna: "Ceptura" },
  { nume: "Salcia" },
  { nume: "Sălciile", simplu: "Salciile" },
  { nume: "Sălcioara", simplu: "Salcioara", comuna: "Podenii Noi" },
  { nume: "Sângeru", simplu: "Sangeru" },
  { nume: "Sărari", simplu: "Sarari", comuna: "Predeal-Sarari" },
  { nume: "Sărățel", simplu: "Saratel", comuna: "Predeal-Sarari" },
  { nume: "Sârca", simplu: "Sarca", comuna: "Scorteni" },
  { nume: "Satu de Sus", comuna: "Manesti" },
  { nume: "Satu Nou", comuna: "Baba Ana" },
  { nume: "Satu Nou", comuna: "Lipanesti" },
  { nume: "Sătucu", simplu: "Satucu", comuna: "Tomsani" },
  { nume: "Schela", comuna: "Baicoi" },
  { nume: "Schiau", comuna: "Urlati" },
  { nume: "Schiau", comuna: "Valea Calugareasca" },
  { nume: "Schiulești", simplu: "Schiulesti", comuna: "Izvoarele" },
  { nume: "Scorțeni", simplu: "Scorteni" },
  { nume: "Scurtești", simplu: "Scurtesti", comuna: "Stefesti" },
  { nume: "Secăria", simplu: "Secaria" },
  { nume: "Seciu", comuna: "Boldesti-Scaeni" },
  { nume: "Seciuri", comuna: "Sotrile" },
  { nume: "Sfăcăru", simplu: "Sfacaru", comuna: "Podenii Noi" },
  { nume: "Sfârleanca", simplu: "Sfarleanca", comuna: "Dumbravesti" },
  { nume: "Sicrita", comuna: "Rafov" },
  {
    nume: "Siliștea Dealului",
    simplu: "Silistea Dealului",
    comuna: "Filipestii De Padure",
  },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Tataru" },
  { nume: "Sinaia" },
  { nume: "Șipotu", simplu: "Sipotu", comuna: "Lipanesti" },
  { nume: "Șirna", simplu: "Sirna" },
  { nume: "Slănic", simplu: "Slanic" },
  { nume: "Slavu", comuna: "Pacureti" },
  { nume: "Slon", comuna: "Cerasu" },
  { nume: "Șoimari", simplu: "Soimari" },
  { nume: "Șoimești", simplu: "Soimesti", comuna: "Ceptura" },
  { nume: "Șotrile", simplu: "Sotrile" },
  { nume: "Stăncești", simplu: "Stancesti", comuna: "Targsoru Vechi" },
  { nume: "Starchiojd" },
  { nume: "Ștefești", simplu: "Stefesti" },
  { nume: "Stejaru", comuna: "Brazi" },
  { nume: "Stoenești", simplu: "Stoenesti", comuna: "Aricestii Rahtivani" },
  { nume: "Străoști", simplu: "Straosti", comuna: "Iordacheanu" },
  { nume: "Strejnicu", comuna: "Targsoru Vechi" },
  { nume: "Ștubeiu", simplu: "Stubeiu", comuna: "Teisani" },
  { nume: "Surani" },
  { nume: "Surdești", simplu: "Surdesti", comuna: "Breaza" },
  { nume: "Talea" },
  { nume: "Țânțăreni", simplu: "Tantareni", comuna: "Blejoi" },
  { nume: "Țărculești", simplu: "Tarculesti", comuna: "Gornet-Cricov" },
  {
    nume: "Târgșoru Nou",
    simplu: "Targsoru Nou",
    comuna: "Aricestii Rahtivani",
  },
  { nume: "Târgșoru Vechi", simplu: "Targsoru Vechi" },
  { nume: "Tăriceni", simplu: "Tariceni", comuna: "Sirna" },
  { nume: "Târlești", simplu: "Tarlesti", comuna: "Posesti" },
  { nume: "Târșoreni", simplu: "Tarsoreni", comuna: "Stefesti" },
  { nume: "Tătărăi", simplu: "Tatarai", comuna: "Poienarii Burchii" },
  { nume: "Tătărani", simplu: "Tatarani", comuna: "Barcanesti" },
  { nume: "Tătaru", simplu: "Tataru" },
  { nume: "Teișani", simplu: "Teisani" },
  { nume: "Telega" },
  { nume: "Teșila", simplu: "Tesila", comuna: "Valea Doftanei" },
  { nume: "Tinosu" },
  { nume: "Țintea", simplu: "Tintea", comuna: "Baicoi" },
  { nume: "Țipărești", simplu: "Tiparesti", comuna: "Cocorastii Mislii" },
  { nume: "Tisa", comuna: "Sangeru" },
  { nume: "Tohani", comuna: "Gura Vadului" },
  { nume: "Tomșani", simplu: "Tomsani" },
  { nume: "Țonțești", simplu: "Tontesti", comuna: "Telega" },
  { nume: "Trăisteni", simplu: "Traisteni", comuna: "Valea Doftanei" },
  { nume: "Trenu", comuna: "Chiojdeanca" },
  { nume: "Trestienii de Jos", comuna: "Dumbrava" },
  { nume: "Trestienii de Sus", comuna: "Dumbrava" },
  { nume: "Trestioara", comuna: "Valcanesti" },
  { nume: "Tufani", comuna: "Draganesti" },
  { nume: "Tufeni", comuna: "Baicoi" },
  {
    nume: "Tulburea Văleni",
    simplu: "Tulburea Valeni",
    comuna: "Predeal-Sarari",
  },
  { nume: "Tulburea", comuna: "Predeal-Sarari" },
  { nume: "Udrești", simplu: "Udresti", comuna: "Apostolache" },
  { nume: "Ulmi", comuna: "Urlati" },
  { nume: "Ungureni", comuna: "Fantanele" },
  { nume: "Ungureni", comuna: "Filipestii De Targ" },
  { nume: "Ungureni", comuna: "Gherghita" },
  { nume: "Urlați", simplu: "Urlati" },
  { nume: "Urleta", comuna: "Banesti" },
  { nume: "Vadu Părului", simplu: "Vadu Parului", comuna: "Albesti-Paleologu" },
  { nume: "Vadu Săpat", simplu: "Vadu Sapat", comuna: "Fantanele" },
  { nume: "Vâlcănești", simplu: "Valcanesti" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Colceag" },
  { nume: "Valea Anei", comuna: "Starchiojd" },
  { nume: "Valea Bobului", comuna: "Urlati" },
  { nume: "Valea Borului", comuna: "Cerasu" },
  { nume: "Valea Brădetului", simplu: "Valea Bradetului", comuna: "Cerasu" },
  { nume: "Valea Bradului", comuna: "Provita De Sus" },
  { nume: "Valea Călugărească", simplu: "Valea Calugareasca" },
  { nume: "Valea Crângului", simplu: "Valea Crangului", comuna: "Urlati" },
  { nume: "Valea Cricovului", comuna: "Apostolache" },
  { nume: "Valea Cucului", comuna: "Iordacheanu" },
  { nume: "Valea Dulce", comuna: "Podenii Noi" },
  { nume: "Valea Largă", simplu: "Valea Larga", comuna: "Valea Calugareasca" },
  { nume: "Valea Lespezii", comuna: "Cerasu" },
  { nume: "Valea Mantei", comuna: "Valea Calugareasca" },
  { nume: "Valea Mieilor", comuna: "Urlati" },
  { nume: "Valea Nicovani", comuna: "Valea Calugareasca" },
  { nume: "Valea Nucetului", comuna: "Urlati" },
  { nume: "Valea Oprii", comuna: "Cornu" },
  { nume: "Valea Orlei", comuna: "Bucov" },
  { nume: "Valea Pietrei", comuna: "Urlati" },
  { nume: "Valea Plopului", comuna: "Posesti" },
  { nume: "Valea Poienii", comuna: "Valea Calugareasca" },
  { nume: "Valea Popii", comuna: "Valea Calugareasca" },
  { nume: "Valea Scheilor", comuna: "Calugareni" },
  { nume: "Valea Screzii", comuna: "Posesti" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Gornet-Cricov" },
  { nume: "Valea Seman", comuna: "Urlati" },
  { nume: "Valea Stâlpului", simplu: "Valea Stalpului", comuna: "Teisani" },
  { nume: "Valea Stupinii", comuna: "Posesti" },
  { nume: "Valea Târsei", simplu: "Valea Tarsei", comuna: "Breaza" },
  { nume: "Valea Tocii", comuna: "Cerasu" },
  { nume: "Valea Unghiului", comuna: "Jugureni" },
  { nume: "Valea Urloii", comuna: "Urlati" },
  { nume: "Valea Ursoii", comuna: "Valea Calugareasca" },
  { nume: "Vălenii de Munte", simplu: "Valenii de Munte" },
  { nume: "Vărbila", simplu: "Varbila", comuna: "Iordacheanu" },
  { nume: "Vărbilău", simplu: "Varbilau" },
  { nume: "Vârfurile", simplu: "Varfurile", comuna: "Valea Calugareasca" },
  { nume: "Varnița", simplu: "Varnita", comuna: "Sirna" },
  { nume: "Vistieru", comuna: "Sotrile" },
  { nume: "Vitioara de Sus", comuna: "Predeal-Sarari" },
  { nume: "Zahanaua", comuna: "Targsoru Vechi" },
  { nume: "Zalhanaua", comuna: "Manesti" },
  { nume: "Zâmbroaia", simplu: "Zambroaia", comuna: "Predeal-Sarari" },
  { nume: "Zamfira", comuna: "Lipanesti" },
  { nume: "Zănoaga", simplu: "Zanoaga", comuna: "Dumbrava" },
  { nume: "Zmeuret", comuna: "Starchiojd" },
];
