export const sm = [
  { nume: "Acâş", simplu: "Acas", comuna: "Acis" },
  { nume: "Aciua", comuna: "Pomi" },
  { nume: "Adrian", comuna: "Livada" },
  { nume: "Ady Endre", comuna: "Cauas" },
  { nume: "Agriş", simplu: "Agris", comuna: "Botiz" },
  { nume: "Aliceni", comuna: "Tarsolt" },
  { nume: "Aliza", comuna: "Terebesti" },
  { nume: "Amaţi", simplu: "Amati", comuna: "Paulesti" },
  { nume: "Ambud", comuna: "Paulesti" },
  { nume: "Andrid" },
  { nume: "Apa" },
  { nume: "Apateu", comuna: "Culciu" },
  { nume: "Ardud-Vii", comuna: "Ardud" },
  { nume: "Ardud" },
  { nume: "Atea", comuna: "Dorolt" },
  { nume: "Baba Novac", comuna: "Ardud" },
  { nume: "Băbăşeşti", simplu: "Babasesti", comuna: "Mediesu Aurit" },
  { nume: "Băbeşti", simplu: "Babesti", comuna: "Halmeu" },
  { nume: "Babţa", simplu: "Babta", comuna: "Bogdand" },
  { nume: "Bârsău de Jos", simplu: "Barsau de Jos", comuna: "Barsau" },
  { nume: "Bârsău de Sus", simplu: "Barsau de Sus", comuna: "Barsau" },
  { nume: "Bătarci", simplu: "Batarci" },
  { nume: "Becheni", comuna: "Sauca" },
  { nume: "Beltiug" },
  { nume: "Bercu Nou", comuna: "Micula" },
  { nume: "Bercu", comuna: "Lazuri" },
  { nume: "Berea", comuna: "Sanislau" },
  { nume: "Berindan", comuna: "Odoreu" },
  { nume: "Berveni" },
  { nume: "Bicău", simplu: "Bicau", comuna: "Pomi" },
  { nume: "Bixad" },
  { nume: "Blaja", comuna: "Tasnad" },
  { nume: "Bocicău", simplu: "Bocicau", comuna: "Tarna Mare" },
  { nume: "Bogdand" },
  { nume: "Boghiş", simplu: "Boghis", comuna: "Doba" },
  { nume: "Boineşti", simplu: "Boinesti", comuna: "Bixad" },
  { nume: "Bolda", comuna: "Beltiug" },
  { nume: "Borleşti", simplu: "Borlesti", comuna: "Pomi" },
  { nume: "Botiz" },
  { nume: "Călineşti-Oaş", simplu: "Calinesti-Oas" },
  { nume: "Cămărzana", simplu: "Camarzana" },
  { nume: "Cămin", simplu: "Camin" },
  { nume: "Căpleni", simplu: "Capleni" },
  { nume: "Cărăşeu", simplu: "Caraseu", comuna: "Culciu" },
  { nume: "Carei" },
  { nume: "Căuaş", simplu: "Cauas" },
  { nume: "Cean", comuna: "Sauca" },
  { nume: "Cehal" },
  { nume: "Cehăluţ", simplu: "Cehalut", comuna: "Cehal" },
  { nume: "Certeze" },
  { nume: "Chegea", comuna: "Sacaseni" },
  { nume: "Chereuşa", simplu: "Chereusa", comuna: "Santau" },
  { nume: "Chilia", comuna: "Homoroade" },
  { nume: "Chisău", simplu: "Chisau", comuna: "Sauca" },
  { nume: "Cidreag", comuna: "Halmeu" },
  { nume: "Cig", comuna: "Tasnad" },
  { nume: "Cioncheşti", simplu: "Cionchesti", comuna: "Viile Satu Mare" },
  { nume: "Ciumeşti", simplu: "Ciumesti", comuna: "Sanislau" },
  { nume: "Ciuperceni", comuna: "Botiz" },
  { nume: "Coca", comuna: "Calinesti-Oas" },
  { nume: "Comlăuşa", simplu: "Comlausa", comuna: "Batarci" },
  { nume: "Corod", comuna: "Culciu" },
  { nume: "Corund", comuna: "Bogdand" },
  { nume: "Craidorolţ", simplu: "Craidorolt" },
  { nume: "Crişeni", simplu: "Criseni", comuna: "Craidorolt" },
  { nume: "Crucişor", simplu: "Crucisor" },
  { nume: "Cucu", comuna: "Odoreu" },
  { nume: "Culciu Mare", comuna: "Culciu" },
  { nume: "Culciu Mic", comuna: "Culciu" },
  { nume: "Cuţa", simplu: "Cuta", comuna: "Socond" },
  { nume: "Dacia", comuna: "Doba" },
  { nume: "Dara", comuna: "Dorolt" },
  { nume: "Decebal", comuna: "Vetis" },
  { nume: "Dindeşti", simplu: "Dindesti", comuna: "Andrid" },
  { nume: "Dindeştiu Mic", simplu: "Dindestiu Mic", comuna: "Petresti" },
  { nume: "Doba" },
  { nume: "Dobolţ", simplu: "Dobolt", comuna: "Halmeu" },
  { nume: "Dobra", comuna: "Supur" },
  { nume: "Domăneşti", simplu: "Domanesti", comuna: "Moftin" },
  { nume: "Dorolţ", simplu: "Dorolt" },
  { nume: "Drăguşeni", simplu: "Draguseni", comuna: "Turulung" },
  { nume: "Dumbrava", comuna: "Livada" },
  { nume: "Eriu Sâncrai", simplu: "Eriu Sancrai", comuna: "Craidorolt" },
  { nume: "Eteni", comuna: "Odoreu" },
  { nume: "Foieni" },
  { nume: "Ganaş", simplu: "Ganas", comuna: "Acis" },
  { nume: "Gelu", comuna: "Terebesti" },
  { nume: "Gerăuşa", simplu: "Gerausa", comuna: "Ardud" },
  { nume: "Ghenci", comuna: "Cauas" },
  { nume: "Gherţa Mare", simplu: "Gherta Mare", comuna: "Turt" },
  { nume: "Gherţa Mică", simplu: "Gherta Mica" },
  { nume: "Ghileşti", simplu: "Ghilesti", comuna: "Cauas" },
  { nume: "Ghilvaci", comuna: "Moftin" },
  { nume: "Ghirişa", simplu: "Ghirisa", comuna: "Beltiug" },
  { nume: "Ghirolt", comuna: "Moftin" },
  { nume: "Giorocuta", comuna: "Supur" },
  { nume: "Giungi", comuna: "Beltiug" },
  { nume: "Giurtelecu Hododului", comuna: "Hodod" },
  { nume: "Halmeu Vii", comuna: "Halmeu" },
  { nume: "Halmeu" },
  { nume: "Hodişa", simplu: "Hodisa", comuna: "Socond" },
  { nume: "Hodod" },
  { nume: "Homorodu de Jos", comuna: "Homoroade" },
  { nume: "Homorodu de Mijloc", comuna: "Homoroade" },
  { nume: "Homorodu de Sus", comuna: "Homoroade" },
  { nume: "Horea", comuna: "Sanislau" },
  { nume: "Hotoan", comuna: "Cauas" },
  { nume: "Hrip", comuna: "Paulesti" },
  { nume: "Hurezu Mare", comuna: "Supur" },
  { nume: "Huta Certeze", comuna: "Certeze" },
  { nume: "Ianculeşti", simplu: "Ianculesti", comuna: "Carei" },
  { nume: "Iegherişte", simplu: "Iegheriste", comuna: "Crucisor" },
  { nume: "Iojib", comuna: "Mediesu Aurit" },
  { nume: "Irina", comuna: "Andrid" },
  { nume: "Istrău", simplu: "Istrau", comuna: "Moftin" },
  { nume: "Lazuri" },
  { nume: "Lechinţa", simplu: "Lechinta", comuna: "Calinesti-Oas" },
  { nume: "Lelei", comuna: "Hodod" },
  { nume: "Lipău", simplu: "Lipau", comuna: "Culciu" },
  { nume: "Livada Mică", simplu: "Livada Mica", comuna: "Livada" },
  { nume: "Livada" },
  { nume: "Lucăceni", simplu: "Lucaceni", comuna: "Berveni" },
  { nume: "Luna", comuna: "Negresti-Oas" },
  { nume: "Lunca Apei", comuna: "Apa" },
  { nume: "Mădăras", simplu: "Madaras", comuna: "Ardud" },
  { nume: "Măriuş", simplu: "Marius", comuna: "Valea Vinului" },
  { nume: "Marna Nouă", simplu: "Marna Noua", comuna: "Sanislau" },
  { nume: "Mărtineşti", simplu: "Martinesti", comuna: "Odoreu" },
  { nume: "Medieş Râturi", simplu: "Medies Raturi", comuna: "Mediesu Aurit" },
  { nume: "Medieş Vii", simplu: "Medies Vii", comuna: "Mediesu Aurit" },
  { nume: "Medieşu Aurit", simplu: "Mediesu Aurit" },
  { nume: "Medişa", simplu: "Medisa", comuna: "Viile Satu Mare" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Halmeu" },
  { nume: "Micula Nouă", simplu: "Micula Noua", comuna: "Micula" },
  { nume: "Micula" },
  { nume: "Mihăieni", simplu: "Mihaieni", comuna: "Acis" },
  { nume: "Moftinu Mare", comuna: "Moftin" },
  { nume: "Moftinu Mic", comuna: "Moftin" },
  { nume: "Moişeni", simplu: "Moiseni", comuna: "Certeze" },
  { nume: "Nadişu Hododului", simplu: "Nadisu Hododului", comuna: "Hodod" },
  { nume: "Necopoi", comuna: "Homoroade" },
  { nume: "Negreşti-Oaş", simplu: "Negresti-Oas" },
  { nume: "Nisipeni", comuna: "Lazuri" },
  { nume: "Noroieni", comuna: "Lazuri" },
  { nume: "Oar", comuna: "Vetis" },
  { nume: "Odoreu" },
  { nume: "Oraşu Nou-Vii", simplu: "Orasu Nou-Vii", comuna: "Orasu Nou" },
  { nume: "Oraşu Nou", simplu: "Orasu Nou" },
  { nume: "Orbău", simplu: "Orbau", comuna: "Cehal" },
  { nume: "Păşunea Mare", simplu: "Pasunea Mare", comuna: "Calinesti-Oas" },
  { nume: "Păuleşti", simplu: "Paulesti" },
  { nume: "Paulian", comuna: "Doba" },
  { nume: "Peleş", simplu: "Peles", comuna: "Lazuri" },
  { nume: "Pelişor", simplu: "Pelisor", comuna: "Lazuri" },
  { nume: "Petea", comuna: "Dorolt" },
  { nume: "Petin", comuna: "Paulesti" },
  { nume: "Petreşti", simplu: "Petresti" },
  { nume: "Pir" },
  { nume: "Piru Nou", comuna: "Pir" },
  { nume: "Pişcari", simplu: "Piscari", comuna: "Terebesti" },
  { nume: "Pişcolt", simplu: "Piscolt" },
  { nume: "Poiana Codrului", comuna: "Crucisor" },
  { nume: "Pomi" },
  { nume: "Portiţa", simplu: "Portita", comuna: "Tiream" },
  { nume: "Porumbeşti", simplu: "Porumbesti", comuna: "Halmeu" },
  { nume: "Potău", simplu: "Potau", comuna: "Mediesu Aurit" },
  { nume: "Prilog Vii", comuna: "Orasu Nou" },
  { nume: "Prilog", comuna: "Orasu Nou" },
  { nume: "Racova", comuna: "Supur" },
  { nume: "Racşa Vii", simplu: "Racsa Vii", comuna: "Orasu Nou" },
  { nume: "Racşa", simplu: "Racsa", comuna: "Orasu Nou" },
  { nume: "Răduleşti", simplu: "Radulesti", comuna: "Cauas" },
  { nume: "Răteşti", simplu: "Ratesti", comuna: "Beltiug" },
  { nume: "Raţiu", simplu: "Ratiu", comuna: "Tasnad" },
  { nume: "Remetea Oaşului", simplu: "Remetea Oasului", comuna: "Orasu Nou" },
  { nume: "Resighea", comuna: "Piscolt" },
  { nume: "Româneşti", simplu: "Romanesti", comuna: "Mediesu Aurit" },
  { nume: "Roşiori", simplu: "Rosiori", comuna: "Valea Vinului" },
  { nume: "Ruşeni", simplu: "Ruseni", comuna: "Paulesti" },
  { nume: "Săcăşeni", simplu: "Sacaseni" },
  { nume: "Sâi", simplu: "Sai", comuna: "Valea Vinului" },
  { nume: "Şandra", simplu: "Sandra", comuna: "Beltiug" },
  { nume: "Sanislău", simplu: "Sanislau" },
  { nume: "Sânmiclăuş", simplu: "Sanmiclaus", comuna: "Moftin" },
  { nume: "Santău", simplu: "Santau" },
  { nume: "Sărătura", simplu: "Saratura", comuna: "Ardud" },
  { nume: "Sărăuad", simplu: "Sarauad", comuna: "Tasnad" },
  { nume: "Sărvăzel", simplu: "Sarvazel", comuna: "Pir" },
  { nume: "Sătmărel", simplu: "Satmarel", comuna: "Satu Mare" },
  { nume: "Satu Mare" },
  { nume: "Satu Mic", comuna: "Craidorolt" },
  { nume: "Săuca", simplu: "Sauca" },
  { nume: "Scărişoara Nouă", simplu: "Scarisoara Noua", comuna: "Piscolt" },
  { nume: "Sechereşa", simplu: "Secheresa", comuna: "Supur" },
  { nume: "Ser", comuna: "Bogdand" },
  { nume: "Silvaş", simplu: "Silvas", comuna: "Sauca" },
  { nume: "Şirlău", simplu: "Sirlau", comuna: "Batarci" },
  { nume: "Socond" },
  { nume: "Soconzel", comuna: "Socond" },
  { nume: "Solduba", comuna: "Homoroade" },
  { nume: "Someşeni", simplu: "Someseni", comuna: "Apa" },
  { nume: "Stâna", simplu: "Stana", comuna: "Socond" },
  { nume: "Sudurău", simplu: "Sudurau", comuna: "Santau" },
  { nume: "Supuru de Jos", comuna: "Supur" },
  { nume: "Supuru de Sus", comuna: "Supur" },
  { nume: "Tămăşeni", simplu: "Tamaseni", comuna: "Batarci" },
  { nume: "Tarna Mare" },
  { nume: "Târşolţ", simplu: "Tarsolt" },
  { nume: "Tăşnad", simplu: "Tasnad" },
  { nume: "Tătăreşti", simplu: "Tataresti", comuna: "Viile Satu Mare" },
  { nume: "Ţeghea", simplu: "Teghea", comuna: "Craidorolt" },
  { nume: "Terebeşti", simplu: "Terebesti" },
  { nume: "Tireac", comuna: "Viile Satu Mare" },
  { nume: "Tiream" },
  { nume: "Traian", comuna: "Doba" },
  { nume: "Trip", comuna: "Bixad" },
  { nume: "Tur", comuna: "Negresti-Oas" },
  { nume: "Turţ Băi", simplu: "Turt Bai", comuna: "Turt" },
  { nume: "Turţ", simplu: "Turt" },
  { nume: "Turulung Vii", comuna: "Turulung" },
  { nume: "Turulung" },
  { nume: "Unimăt", simplu: "Unimat", comuna: "Acis" },
  { nume: "Urziceni Pădure", simplu: "Urziceni Padure", comuna: "Urziceni" },
  { nume: "Urziceni" },
  { nume: "Văgaş", simplu: "Vagas", comuna: "Tarna Mare" },
  { nume: "Valea Morii", comuna: "Tasnad" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Tarna Mare" },
  { nume: "Valea Vinului" },
  { nume: "Vama" },
  { nume: "Vânătoreşti", simplu: "Vanatoresti", comuna: "Odoreu" },
  { nume: "Vetiş", simplu: "Vetis" },
  { nume: "Vezendiu", comuna: "Tiream" },
  { nume: "Viile Satu Mare" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Sanislau" },
];
