export const sb = [
  { nume: "Aciliu", comuna: "Saliste" },
  { nume: "Agârbiciu", simplu: "Agarbiciu", comuna: "Axente Sever" },
  { nume: "Agnita" },
  { nume: "Alămor", simplu: "Alamor", comuna: "Loamnes" },
  { nume: "Albi", comuna: "Slimnic" },
  { nume: "Alma Vii", comuna: "Mosna" },
  { nume: "Alma", comuna: "Atel" },
  { nume: "Alțina", simplu: "Altina" },
  { nume: "Amnaș", simplu: "Amnas", comuna: "Saliste" },
  { nume: "Apoldu de Jos" },
  { nume: "Apoldu de Sus", comuna: "Miercurea Sibiului" },
  { nume: "Apoș", simplu: "Apos", comuna: "Birghis" },
  { nume: "Armeni", comuna: "Loamnes" },
  { nume: "Arpașu de Jos", simplu: "Arpasu de Jos" },
  { nume: "Arpașu de Sus", simplu: "Arpasu de Sus", comuna: "Arpasu De Jos" },
  { nume: "Ațel", simplu: "Atel" },
  { nume: "Avrig" },
  { nume: "Axente Sever" },
  { nume: "Bârghiș", simplu: "Barghis", comuna: "Birghis" },
  { nume: "Bazna" },
  { nume: "Benești", simplu: "Benesti", comuna: "Altina" },
  { nume: "Biertan" },
  { nume: "Blăjel", simplu: "Blajel" },
  { nume: "Boarta", comuna: "Seica Mare" },
  { nume: "Bogatu Român", simplu: "Bogatu Roman", comuna: "Pauca" },
  { nume: "Boian", comuna: "Bazna" },
  { nume: "Boița", simplu: "Boita", comuna: "Talmaciu" },
  { nume: "Brădeni", simplu: "Bradeni" },
  { nume: "Bradu", comuna: "Avrig" },
  { nume: "Brateiu" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Pauca" },
  { nume: "Bruiu" },
  { nume: "Buia", comuna: "Seica Mare" },
  { nume: "Bungard", comuna: "Selimbar" },
  { nume: "Buzd", comuna: "Brateiu" },
  { nume: "Cârța", simplu: "Carta" },
  { nume: "Cârțișoara", simplu: "Cartisoara" },
  { nume: "Cașolț", simplu: "Casolt", comuna: "Rosia" },
  { nume: "Chesler", comuna: "Micasasa" },
  { nume: "Chirpăr", simplu: "Chirpar" },
  { nume: "Cisnădie", simplu: "Cisnadie" },
  { nume: "Cisnădioara", simplu: "Cisnadioara", comuna: "Cisnadie" },
  { nume: "Colonia Tălmaciu", simplu: "Colonia Talmaciu", comuna: "Talmaciu" },
  { nume: "Colonia Târnava", simplu: "Colonia Tarnava", comuna: "Tarnava" },
  { nume: "Colun", comuna: "Porumbacu De Jos" },
  { nume: "Copșa Mare", simplu: "Copsa Mare", comuna: "Biertan" },
  { nume: "Copșa Mică", simplu: "Copsa Mica" },
  { nume: "Cornățel", simplu: "Cornatel", comuna: "Rosia" },
  { nume: "Coveș", simplu: "Coves", comuna: "Agnita" },
  { nume: "Crinț", simplu: "Crint", comuna: "Saliste" },
  { nume: "Cristian" },
  { nume: "Curciu", comuna: "Darlos" },
  { nume: "Daia", comuna: "Rosia" },
  { nume: "Dârlos", simplu: "Darlos" },
  { nume: "Dealu Frumos", comuna: "Merghindeal" },
  { nume: "Dobârca", simplu: "Dobarca", comuna: "Miercurea Sibiului" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni" },
  { nume: "Dupuș", simplu: "Dupus", comuna: "Atel" },
  { nume: "Ernea", comuna: "Dumbraveni" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Saliste" },
  { nume: "Florești", simplu: "Floresti", comuna: "Laslea" },
  { nume: "Fofeldea", comuna: "Nocrich" },
  { nume: "Galeș", simplu: "Gales", comuna: "Saliste" },
  { nume: "Gherdeal", comuna: "Bruiu" },
  { nume: "Ghijasa de Jos", comuna: "Nocrich" },
  { nume: "Ghijasa de Sus", comuna: "Altina" },
  { nume: "Giacăș", simplu: "Giacas", comuna: "Atel" },
  { nume: "Glâmboaca", simplu: "Glamboaca", comuna: "Avrig" },
  { nume: "Gura Râului", simplu: "Gura Raului" },
  { nume: "Gusu", comuna: "Ludos" },
  { nume: "Hamba", comuna: "Sura Mare" },
  { nume: "Hașag", simplu: "Hasag", comuna: "Loamnes" },
  { nume: "Hoghilag" },
  { nume: "Hosman", comuna: "Nocrich" },
  { nume: "Iacobeni" },
  { nume: "Ighișu Nou", simplu: "Ighisu Nou", comuna: "Medias" },
  { nume: "Ighișu Vechi", simplu: "Ighisu Vechi", comuna: "Birghis" },
  { nume: "Ilimbav", comuna: "Marpod" },
  { nume: "Jina" },
  { nume: "Laslea" },
  { nume: "Lazaret", comuna: "Talmaciu" },
  { nume: "Loamneș", simplu: "Loamnes" },
  { nume: "Lotrioara", comuna: "Talmaciu" },
  { nume: "Ludoș", simplu: "Ludos" },
  { nume: "Mag", comuna: "Saliste" },
  { nume: "Mălâncrav", simplu: "Malancrav", comuna: "Laslea" },
  { nume: "Mândra", simplu: "Mandra", comuna: "Loamnes" },
  { nume: "Marpod" },
  { nume: "Mârșa", simplu: "Marsa", comuna: "Avrig" },
  { nume: "Mediaș", simplu: "Medias" },
  { nume: "Merghindeal" },
  { nume: "Metiș", simplu: "Metis", comuna: "Mihaileni" },
  { nume: "Micăsasa", simplu: "Micasasa" },
  { nume: "Miercurea Sibiului" },
  { nume: "Mighindoala", comuna: "Seica Mare" },
  { nume: "Mihăileni", simplu: "Mihaileni" },
  { nume: "Moardăș", simplu: "Moardas", comuna: "Mihaileni" },
  { nume: "Mohu", comuna: "Selimbar" },
  { nume: "Moșna", simplu: "Mosna" },
  { nume: "Motiș", simplu: "Motis", comuna: "Valea Viilor" },
  { nume: "Movile", comuna: "Iacobeni" },
  { nume: "Nemșa", simplu: "Nemsa", comuna: "Mosna" },
  { nume: "Netuș", simplu: "Netus", comuna: "Iacobeni" },
  { nume: "Nocrich" },
  { nume: "Noiștat", simplu: "Noistat", comuna: "Iacobeni" },
  { nume: "Nou Săsesc", simplu: "Nou Sasesc", comuna: "Laslea" },
  { nume: "Nou", comuna: "Rosia" },
  { nume: "Noul Român", simplu: "Noul Roman", comuna: "Arpasu De Jos" },
  { nume: "Nucet", comuna: "Rosia" },
  { nume: "Ocna Sibiului" },
  { nume: "Orlat" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Slimnic" },
  { nume: "Paltin", comuna: "Talmaciu" },
  { nume: "Păltiniș", simplu: "Paltinis", comuna: "Sibiu" },
  { nume: "Păuca", simplu: "Pauca" },
  { nume: "Păucea", simplu: "Paucea", comuna: "Blajel" },
  { nume: "Pelișor", simplu: "Pelisor", comuna: "Birghis" },
  { nume: "Petiș", simplu: "Petis", comuna: "Seica Mare" },
  { nume: "Poiana Sibiului" },
  { nume: "Poienița", simplu: "Poienita", comuna: "Carta" },
  { nume: "Poplaca" },
  { nume: "Porumbacu de Jos" },
  { nume: "Porumbacu de Sus", comuna: "Porumbacu De Jos" },
  { nume: "Presaca", comuna: "Pauca" },
  { nume: "Prislop", comuna: "Rasinari" },
  { nume: "Prod", comuna: "Hoghilag" },
  { nume: "Racovița", simplu: "Racovita" },
  { nume: "Rășinari", simplu: "Rasinari" },
  { nume: "Râu Sadului", simplu: "Rau Sadului" },
  { nume: "Răvășel", simplu: "Ravasel", comuna: "Mihaileni" },
  { nume: "Retiș", simplu: "Retis", comuna: "Bradeni" },
  { nume: "Richiș", simplu: "Richis", comuna: "Biertan" },
  { nume: "Roandola", comuna: "Laslea" },
  { nume: "Rod", comuna: "Tilisca" },
  { nume: "Romanești", simplu: "Romanesti", comuna: "Blajel" },
  { nume: "Roșia", simplu: "Rosia" },
  { nume: "Ruja", comuna: "Agnita" },
  { nume: "Rusciori", comuna: "Sura Mica" },
  { nume: "Ruși", simplu: "Rusi", comuna: "Slimnic" },
  { nume: "Săcădate", simplu: "Sacadate", comuna: "Avrig" },
  { nume: "Săcel", simplu: "Sacel", comuna: "Saliste" },
  { nume: "Sădinca", simplu: "Sadinca", comuna: "Loamnes" },
  { nume: "Sadu" },
  { nume: "Șalcău", simplu: "Salcau", comuna: "Mihaileni" },
  { nume: "Săliște", simplu: "Saliste" },
  { nume: "Sângătin", simplu: "Sangatin", comuna: "Apoldu De Jos" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Porumbacu De Jos" },
  {
    nume: "Șaroș pe Târnave",
    simplu: "Saros pe Tarnave",
    comuna: "Dumbraveni",
  },
  { nume: "Săsăuș", simplu: "Sasaus", comuna: "Chirpar" },
  { nume: "Scoreiu", comuna: "Porumbacu De Jos" },
  { nume: "Sebeșu de Jos", simplu: "Sebesu de Jos", comuna: "Turnu Rosu" },
  { nume: "Sebeșu de Sus", simplu: "Sebesu de Sus", comuna: "Racovita" },
  { nume: "Șeica Mare", simplu: "Seica Mare" },
  { nume: "Șeica Mică", simplu: "Seica Mica" },
  { nume: "Șelimbăr", simplu: "Selimbar" },
  { nume: "Sibiel", comuna: "Saliste" },
  { nume: "Sibiu" },
  { nume: "Slimnic" },
  { nume: "Șmig", simplu: "Smig", comuna: "Atel" },
  { nume: "Șoala", simplu: "Soala", comuna: "Axente Sever" },
  { nume: "Șomartin", simplu: "Somartin", comuna: "Bruiu" },
  { nume: "Soroștin", simplu: "Sorostin", comuna: "Seica Mica" },
  { nume: "Stejărișu", simplu: "Stejarisu", comuna: "Iacobeni" },
  { nume: "Ștenea", simplu: "Stenea", comuna: "Seica Mare" },
  { nume: "Șura Mare", simplu: "Sura Mare" },
  { nume: "Șura Mică", simplu: "Sura Mica" },
  { nume: "Tălmăcel", simplu: "Talmacel", comuna: "Talmaciu" },
  { nume: "Tălmaciu", simplu: "Talmaciu" },
  { nume: "Țapu", simplu: "Tapu", comuna: "Micasasa" },
  { nume: "Târnava", simplu: "Tarnava" },
  { nume: "Țeline", simplu: "Teline", comuna: "Bradeni" },
  { nume: "Țichindeal", simplu: "Tichindeal", comuna: "Nocrich" },
  { nume: "Tilișca", simplu: "Tilisca" },
  { nume: "Topârcea", simplu: "Toparcea", comuna: "Ocna Sibiului" },
  { nume: "Turnu Roșu", simplu: "Turnu Rosu" },
  { nume: "Valchid", comuna: "Hoghilag" },
  { nume: "Vale", comuna: "Saliste" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Darlos" },
  { nume: "Valea Viilor" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Micasasa" },
  { nume: "Vărd", simplu: "Vard", comuna: "Chirpar" },
  { nume: "Vecerd", comuna: "Birghis" },
  { nume: "Velț", simplu: "Velt", comuna: "Bazna" },
  { nume: "Veseud", comuna: "Chirpar" },
  { nume: "Veseud", comuna: "Slimnic" },
  { nume: "Veștem", simplu: "Vestem", comuna: "Selimbar" },
  { nume: "Vurpăr", simplu: "Vurpar" },
  { nume: "Zlagna", comuna: "Birghis" },
];
