export const sv = [
  { nume: "Adâncata", simplu: "Adancata" },
  { nume: "Antoceni", comuna: "Forasti" },
  { nume: "Arbore" },
  { nume: "Argel", comuna: "Moldovita" },
  { nume: "Argestru", comuna: "Vatra Dornei" },
  { nume: "Arghira", comuna: "Preutesti" },
  { nume: "Arţari", simplu: "Artari", comuna: "Hantesti" },
  { nume: "Bădeuţi", simplu: "Badeuti", comuna: "Milisauti" },
  { nume: "Badragi", comuna: "Zamostea" },
  { nume: "Bahna Arin", comuna: "Preutesti" },
  { nume: "Baia" },
  { nume: "Baineţ", simplu: "Bainet", comuna: "Musenita" },
  { nume: "Băişeşti", simplu: "Baisesti", comuna: "Cornu Luncii" },
  { nume: "Bălăceana", simplu: "Balaceana", comuna: "Ciprian Porumbescu" },
  { nume: "Bălcăuţi", simplu: "Balcauti" },
  { nume: "Bălineşti", simplu: "Balinesti", comuna: "Gramesti" },
  { nume: "Bănceşti", simplu: "Bancesti", comuna: "Musenita" },
  { nume: "Băneşti", simplu: "Banesti", comuna: "Fantanele" },
  { nume: "Bărăşti", simplu: "Barasti", comuna: "Boroaia" },
  { nume: "Basarabi", comuna: "Preutesti" },
  { nume: "Benia", comuna: "Moldova-Sulita" },
  { nume: "Berchişeşti", simplu: "Berchisesti", comuna: "Dragoiesti" },
  { nume: "Bereşti", simplu: "Beresti", comuna: "Hantesti" },
  { nume: "Bilca" },
  { nume: "Bivolăria", simplu: "Bivolaria", comuna: "Vicovu De Sus" },
  { nume: "Bobeica", comuna: "Izvoarele Sucevei" },
  { nume: "Bodnăreni", simplu: "Bodnareni", comuna: "Arbore" },
  { nume: "Bogata", comuna: "Baia" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti" },
  { nume: "Boroaia" },
  { nume: "Bosanci" },
  { nume: "Boteşti", simplu: "Botesti", comuna: "Horodniceni" },
  { nume: "Botoş", simplu: "Botos", comuna: "Ciocanesti" },
  { nume: "Botoşana", simplu: "Botosana" },
  {
    nume: "Botoşaniţa Mare",
    simplu: "Botosanita Mare",
    comuna: "Calafindesti",
  },
  { nume: "Botoşaniţa Mică", simplu: "Botosanita Mica", comuna: "Gramesti" },
  { nume: "Botuş", simplu: "Botus", comuna: "Fundu Moldovei" },
  { nume: "Botuşel", simplu: "Botusel", comuna: "Fundu Moldovei" },
  { nume: "Boura", comuna: "Forasti" },
  { nume: "Brădăţel", simplu: "Bradatel", comuna: "Horodniceni" },
  { nume: "Brăieşti", simplu: "Braiesti", comuna: "Cornu Luncii" },
  { nume: "Braniştea", simplu: "Branistea", comuna: "Fundu Moldovei" },
  { nume: "Braşca", simplu: "Brasca", comuna: "Ciprian Porumbescu" },
  { nume: "Breaza de Sus", comuna: "Breaza" },
  { nume: "Breaza" },
  { nume: "Brodina de Jos", comuna: "Brodina" },
  { nume: "Brodina" },
  { nume: "Brodina", comuna: "Izvoarele Sucevei" },
  { nume: "Broşteni", simplu: "Brosteni" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Draguseni" },
  { nume: "Bucşoaia", simplu: "Bucsoaia", comuna: "Frasin" },
  { nume: "Buda", comuna: "Rasca" },
  { nume: "Buda", comuna: "Zvoristea" },
  { nume: "Budeni", comuna: "Dolhasca" },
  { nume: "Bulai", comuna: "Moara" },
  { nume: "Buneşti", simplu: "Bunesti" },
  { nume: "Burla", comuna: "Volovat" },
  { nume: "Bursuceni", comuna: "Veresti" },
  { nume: "Cacica" },
  { nume: "Cajvana" },
  { nume: "Calafindeşti", simplu: "Calafindesti" },
  {
    nume: "Călineşti-Vasilache",
    simplu: "Calinesti-Vasilache",
    comuna: "Darmanesti",
  },
  { nume: "Călineşti", simplu: "Calinesti", comuna: "Darmanesti" },
  { nume: "Călineşti", simplu: "Calinesti", comuna: "Serbauti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Adancata" },
  { nume: "Cămârzani", simplu: "Camarzani", comuna: "Vadu Moldovei" },
  { nume: "Câmpulung Moldovenesc", simplu: "Campulung Moldovenesc" },
  { nume: "Capu Câmpului", simplu: "Capu Campului" },
  { nume: "Capu Codrului", comuna: "Paltinoasa" },
  { nume: "Cârlibaba Nouă", simplu: "Carlibaba Noua", comuna: "Carlibaba" },
  { nume: "Cârlibaba", simplu: "Carlibaba" },
  { nume: "Căsoi", simplu: "Casoi", comuna: "Poiana Stampei" },
  { nume: "Catrinari", comuna: "Panaci" },
  { nume: "Chilişeni", simplu: "Chiliseni", comuna: "Udesti" },
  { nume: "Chiril", comuna: "Crucea" },
  { nume: "Ciocăneşti", simplu: "Ciocanesti" },
  { nume: "Ciomârtan", simplu: "Ciomartan", comuna: "Zamostea" },
  { nume: "Ciprian Porumbescu" },
  { nume: "Ciumârna", simplu: "Ciumarna", comuna: "Vatra Moldovitei" },
  { nume: "Ciumuleşti", simplu: "Ciumulesti", comuna: "Vadu Moldovei" },
  { nume: "Climăuţi", simplu: "Climauti", comuna: "Musenita" },
  { nume: "Clit", comuna: "Arbore" },
  { nume: "Codru", comuna: "Cajvana" },
  { nume: "Cojocăreni", simplu: "Cojocareni", comuna: "Zamostea" },
  { nume: "Cojoci", comuna: "Crucea" },
  { nume: "Colacu", comuna: "Fundu Moldovei" },
  { nume: "Comăneşti", simplu: "Comanesti" },
  { nume: "Corlata", comuna: "Dragoiesti" },
  { nume: "Corni", comuna: "Liteni" },
  { nume: "Cornu Luncii" },
  { nume: "Corocăieşti", simplu: "Corocaiesti", comuna: "Veresti" },
  { nume: "Corpaci", comuna: "Zamostea" },
  { nume: "Coşna", simplu: "Cosna" },
  { nume: "Costâna", simplu: "Costana", comuna: "Todiresti" },
  { nume: "Costileva", comuna: "Ulma" },
  { nume: "Costişa", simplu: "Costisa", comuna: "Fratautii Noi" },
  { nume: "Cotârgaşi", simplu: "Cotargasi", comuna: "Brosteni" },
  { nume: "Cotu Băii", simplu: "Cotu Baii", comuna: "Fantana Mare" },
  { nume: "Cotu Dobei", comuna: "Fantanele" },
  { nume: "Coverca", comuna: "Panaci" },
  { nume: "Cozăneşti", simplu: "Cozanesti", comuna: "Dorna-Arini" },
  { nume: "Crucea" },
  { nume: "Cumpărătura", simplu: "Cumparatura", comuna: "Bosanci" },
  { nume: "Cununschi", comuna: "Brodina" },
  { nume: "Dănila", simplu: "Danila", comuna: "Darmanesti" },
  { nume: "Dărmăneşti", simplu: "Darmanesti" },
  { nume: "Dârmoxa", simplu: "Darmoxa", comuna: "Brosteni" },
  { nume: "Dealu Floreni", comuna: "Dorna Candrenilor" },
  { nume: "Dealu", comuna: "Zvoristea" },
  { nume: "Deia", comuna: "Frumosu" },
  { nume: "Deleni", comuna: "Partestii De Jos" },
  { nume: "Delniţa", simplu: "Delnita", comuna: "Fundu Moldovei" },
  { nume: "Deluţ", simplu: "Delut", comuna: "Fundu Moldovei" },
  { nume: "Demacuşa", simplu: "Demacusa", comuna: "Moldovita" },
  { nume: "Dolhasca" },
  { nume: "Dolheştii Mici", simplu: "Dolhestii Mici", comuna: "Dolhesti" },
  { nume: "Dolheştii-Mari", simplu: "Dolhestii-Mari", comuna: "Dolhesti" },
  { nume: "Dorna Candrenilor" },
  { nume: "Dorna-Arini" },
  { nume: "Dorneşti", simplu: "Dornesti" },
  { nume: "Dornişoara", simplu: "Dornisoara", comuna: "Poiana Stampei" },
  { nume: "Doroteia", comuna: "Frasin" },
  { nume: "Drăgoiasa", simplu: "Dragoiasa", comuna: "Panaci" },
  { nume: "Drăgoieşti", simplu: "Dragoiesti" },
  { nume: "Dragomirna", comuna: "Mitocu Dragomirnei" },
  { nume: "Dragoşa", simplu: "Dragosa", comuna: "Frumosu" },
  { nume: "Drăguşeni", simplu: "Draguseni" },
  { nume: "Dubiuşca", simplu: "Dubiusca", comuna: "Brodina" },
  { nume: "Dumbrava", comuna: "Cornu Luncii" },
  { nume: "Dumbrava", comuna: "Granicesti" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Rasca" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita", comuna: "Vadu Moldovei" },
  { nume: "Ehreşte", simplu: "Ehreste", comuna: "Brodina" },
  { nume: "Falcău", simplu: "Falcau", comuna: "Brodina" },
  { nume: "Fălticeni", simplu: "Falticeni" },
  { nume: "Fântâna Mare", simplu: "Fantana Mare" },
  { nume: "Fântânele", simplu: "Fantanele" },
  { nume: "Feteşti", simplu: "Fetesti", comuna: "Adancata" },
  { nume: "Florinta", comuna: "Scheia" },
  { nume: "Forăşti", simplu: "Forasti" },
  { nume: "Frasin" },
  { nume: "Frasin", comuna: "Brosteni" },
  { nume: "Frătăuţii Noi", simplu: "Fratautii Noi" },
  { nume: "Frătăuţii Vechi", simplu: "Fratautii Vechi" },
  { nume: "Frumoasa", comuna: "Moara" },
  { nume: "Frumosu" },
  { nume: "Fundu Moldovei" },
  { nume: "Găineşti", simplu: "Gainesti", comuna: "Slatina" },
  { nume: "Gălăneşti", simplu: "Galanesti" },
  { nume: "Gara Leu", comuna: "Draguseni" },
  { nume: "Gara", comuna: "Milisauti" },
  { nume: "Gemenea", comuna: "Stulpicani" },
  { nume: "Gheorghiţeni", simplu: "Gheorghiteni", comuna: "Dorna-Arini" },
  { nume: "Giuleşti", simplu: "Giulesti", comuna: "Boroaia" },
  { nume: "Giurgeşti", simplu: "Giurgesti", comuna: "Vulturesti" },
  { nume: "Glodu", comuna: "Panaci" },
  { nume: "Grămeşti", simplu: "Gramesti" },
  { nume: "Grăniceşti", simplu: "Granicesti" },
  { nume: "Grigoreşti", simplu: "Grigoresti", comuna: "Siminicea" },
  { nume: "Groapa Vlădichii", simplu: "Groapa Vladichii", comuna: "Moara" },
  { nume: "Gropeni", comuna: "Balcauti" },
  { nume: "Gulia", comuna: "Dolhasca" },
  { nume: "Gura Haitii", comuna: "Saru Dornei" },
  { nume: "Gura Humorului" },
  { nume: "Gura Putnei", comuna: "Putna" },
  { nume: "Gura Solcii", comuna: "Granicesti" },
  { nume: "Hăleasa", simplu: "Haleasa", comuna: "Brosteni" },
  { nume: "Hancea", comuna: "Veresti" },
  { nume: "Hănţeşti", simplu: "Hantesti" },
  { nume: "Hârtop", simplu: "Hartop", comuna: "Preutesti" },
  { nume: "Herla", comuna: "Slatina" },
  { nume: "Holda", comuna: "Brosteni" },
  { nume: "Holdiţa", simplu: "Holdita", comuna: "Brosteni" },
  { nume: "Horodnic de Jos", comuna: "Horodnic" },
  { nume: "Horodnic de Sus" },
  { nume: "Horodniceni" },
  { nume: "Hreaţca", simplu: "Hreatca", comuna: "Vulturesti" },
  { nume: "Humoreni", comuna: "Comanesti" },
  { nume: "Hurjuieni", comuna: "Galanesti" },
  { nume: "Huşi", simplu: "Husi", comuna: "Preutesti" },
  { nume: "Iacobeni" },
  { nume: "Iacobeşti", simplu: "Iacobesti", comuna: "Granicesti" },
  { nume: "Iaslovăţ", simplu: "Iaslovat" },
  { nume: "Iaz", comuna: "Dornesti" },
  { nume: "Iedu", comuna: "Carlibaba" },
  { nume: "Iesle", comuna: "Malini" },
  { nume: "Ilişeşti", simplu: "Ilisesti", comuna: "Ciprian Porumbescu" },
  { nume: "Ioneasa", comuna: "Vadu Moldovei" },
  { nume: "Ipoteşti", simplu: "Ipotesti" },
  { nume: "Izvoarele Sucevei" },
  { nume: "Jacota", comuna: "Vulturesti" },
  { nume: "Jahalia", comuna: "Rasca" },
  { nume: "Lămăşeni", simplu: "Lamaseni", comuna: "Radaseni" },
  { nume: "Leucuşeşti", simplu: "Leucusesti", comuna: "Preutesti" },
  { nume: "Lipoveni", comuna: "Mitocu Dragomirnei" },
  { nume: "Lisaura", comuna: "Ipotesti" },
  { nume: "Liteni" },
  { nume: "Liteni", comuna: "Moara" },
  { nume: "Lucăceşti", simplu: "Lucacesti", comuna: "Dragoiesti" },
  { nume: "Lunca", comuna: "Milisauti" },
  { nume: "Lunca", comuna: "Zamostea" },
  { nume: "Luncuşoara", simplu: "Luncusoara", comuna: "Udesti" },
  { nume: "Lungeni", comuna: "Brosteni" },
  { nume: "Lupcina", comuna: "Ulma" },
  { nume: "Măgura", simplu: "Magura", comuna: "Ulma" },
  { nume: "Maidan", comuna: "Cacica" },
  { nume: "Mălini", simplu: "Malini" },
  { nume: "Mănăstioara", simplu: "Manastioara", comuna: "Siret" },
  { nume: "Mănăstioara", simplu: "Manastioara", comuna: "Udesti" },
  { nume: "Mănăstirea Humorului", simplu: "Manastirea Humorului" },
  { nume: "Măneuţi", simplu: "Maneuti", comuna: "Fratautii Vechi" },
  { nume: "Manolea", comuna: "Forasti" },
  { nume: "Marginea" },
  { nume: "Măriţei", simplu: "Maritei", comuna: "Darmanesti" },
  { nume: "Măriţeia Mică", simplu: "Mariteia Mica", comuna: "Darmanesti" },
  { nume: "Măzănăeşti", simplu: "Mazanaesti", comuna: "Dragoiesti" },
  { nume: "Mereni", comuna: "Salcea" },
  { nume: "Mereşti", simplu: "Meresti", comuna: "Vulturesti" },
  { nume: "Mestecăniş", simplu: "Mestecanis", comuna: "Iacobeni" },
  { nume: "Mesteceni", comuna: "Vadu Moldovei" },
  { nume: "Mihăieşti", simplu: "Mihaiesti", comuna: "Horodniceni" },
  { nume: "Mihoveni", comuna: "Scheia" },
  { nume: "Milişăuţi", simplu: "Milisauti" },
  { nume: "Mironu", comuna: "Valea Moldovei" },
  { nume: "Mitocaşi", simplu: "Mitocasi", comuna: "Mitocu Dragomirnei" },
  { nume: "Mitocu Dragomirnei" },
  { nume: "Moara Carp", comuna: "Moara" },
  { nume: "Moara Nica", comuna: "Moara" },
  { nume: "Moişa", simplu: "Moisa", comuna: "Boroaia" },
  { nume: "Moldova-Suliţa", simplu: "Moldova-Sulita" },
  { nume: "Moldoviţa", simplu: "Moldovita" },
  { nume: "Molid", comuna: "Vama" },
  { nume: "Movileni", comuna: "Vadu Moldovei" },
  { nume: "Muşeniţa", simplu: "Musenita" },
  { nume: "Neagra Şarului", simplu: "Neagra Sarului", comuna: "Saru Dornei" },
  { nume: "Neagra", comuna: "Brosteni" },
  { nume: "Negostina", comuna: "Balcauti" },
  { nume: "Negrileasa", comuna: "Stulpicani" },
  { nume: "Nicani", comuna: "Zamostea" },
  { nume: "Nigoteşti", simplu: "Nigotesti", comuna: "Vadu Moldovei" },
  { nume: "Nisipitu", comuna: "Ulma" },
  { nume: "Norocu", comuna: "Brodina" },
  { nume: "Obcina", comuna: "Fundu Moldovei" },
  { nume: "Oniceni", comuna: "Forasti" },
  { nume: "Ortoaia", comuna: "Dorna-Arini" },
  { nume: "Osoi", comuna: "Vulturesti" },
  { nume: "Ostra" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Siret" },
  { nume: "Păiseni", simplu: "Paiseni", comuna: "Cornu Luncii" },
  { nume: "Paltin", comuna: "Brodina" },
  { nume: "Păltiniş", simplu: "Paltinis", comuna: "Panaci" },
  { nume: "Păltinoasa", simplu: "Paltinoasa" },
  { nume: "Paltinu", comuna: "Vatra Moldovitei" },
  { nume: "Panaci" },
  { nume: "Pâraie", simplu: "Paraie", comuna: "Malini" },
  { nume: "Pârâu Negrei", simplu: "Parau Negrei", comuna: "Breaza" },
  { nume: "Părhăuţi", simplu: "Parhauti", comuna: "Todiresti" },
  { nume: "Pârteştii de Jos", simplu: "Partestii de Jos" },
  { nume: "Pârteştii de Sus", simplu: "Partestii de Sus", comuna: "Cacica" },
  { nume: "Pătrăuţi", simplu: "Patrauti" },
  { nume: "Petia", comuna: "Bunesti" },
  { nume: "Pietroasa", comuna: "Brosteni" },
  { nume: "Pilugani", comuna: "Poiana Stampei" },
  { nume: "Plai", comuna: "Fundu Moldovei" },
  { nume: "Plaiu Şarului", simplu: "Plaiu Sarului", comuna: "Saru Dornei" },
  { nume: "Plăvălari", simplu: "Plavalari", comuna: "Udesti" },
  { nume: "Pleşa", simplu: "Plesa", comuna: "Manastirea Humorului" },
  { nume: "Pleşeşti", simplu: "Plesesti", comuna: "Vulturesti" },
  { nume: "Plopeni", comuna: "Salcea" },
  { nume: "Plutoniţa", simplu: "Plutonita", comuna: "Frasin" },
  { nume: "Pocoleni", comuna: "Radaseni" },
  { nume: "Podeni", comuna: "Bunesti" },
  { nume: "Podu Coşnei", simplu: "Podu Cosnei", comuna: "Cosna" },
  { nume: "Poiana Mărului", simplu: "Poiana Marului", comuna: "Malini" },
  { nume: "Poiana Micului", comuna: "Manastirea Humorului" },
  { nume: "Poiana Negrii", comuna: "Dorna Candrenilor" },
  { nume: "Poiana Stampei" },
  { nume: "Poiana", comuna: "Dolhasca" },
  { nume: "Poiana", comuna: "Zvoristea" },
  { nume: "Poienari", comuna: "Dolhasca" },
  { nume: "Poieni-Solca", comuna: "Solca" },
  { nume: "Poieni-Suceava", comuna: "Udesti" },
  { nume: "Pojorâta", simplu: "Pojorata" },
  { nume: "Prăleni", simplu: "Praleni", comuna: "Poiana Stampei" },
  { nume: "Praxia", comuna: "Fantana Mare" },
  { nume: "Prelipca", comuna: "Salcea" },
  { nume: "Preuteşti", simplu: "Preutesti" },
  { nume: "Prisaca Dornei", comuna: "Vama" },
  { nume: "Probota", comuna: "Dolhasca" },
  { nume: "Putna" },
  { nume: "Racova", comuna: "Udesti" },
  { nume: "Rădăşeni", simplu: "Radaseni" },
  { nume: "Rădăuţi", simplu: "Radauti" },
  { nume: "Râşca", simplu: "Rasca" },
  { nume: "Raşca", simplu: "Rasca", comuna: "Moldovita" },
  { nume: "Răuţeni", simplu: "Rauteni", comuna: "Zamostea" },
  { nume: "Reuseni", comuna: "Udesti" },
  { nume: "Româneşti", simplu: "Romanesti", comuna: "Cosna" },
  { nume: "Româneşti", simplu: "Romanesti", comuna: "Granicesti" },
  { nume: "Roşcani", simplu: "Roscani", comuna: "Liteni" },
  { nume: "Roşiori", simplu: "Rosiori", comuna: "Forasti" },
  { nume: "Roşu", simplu: "Rosu", comuna: "Vatra Dornei" },
  { nume: "Rotopăneşti", simplu: "Rotopanesti", comuna: "Horodniceni" },
  { nume: "Rotunda", comuna: "Liteni" },
  { nume: "Rudeşti", simplu: "Rudesti", comuna: "Gramesti" },
  { nume: "Runcu", comuna: "Cacica" },
  { nume: "Rusca", comuna: "Dorna-Arini" },
  { nume: "Ruşi", simplu: "Rusi", comuna: "Forasti" },
  { nume: "Ruşii-Mănăstioara", simplu: "Rusii-Manastioara", comuna: "Udesti" },
  { nume: "Săcuţa", simplu: "Sacuta", comuna: "Boroaia" },
  { nume: "Sadău", simplu: "Sadau", comuna: "Brodina" },
  { nume: "Sadova" },
  { nume: "Sălăgeni", simplu: "Salageni", comuna: "Dumbraveni" },
  { nume: "Salcea" },
  { nume: "Sârghieşti", simplu: "Sarghiesti", comuna: "Todiresti" },
  { nume: "Sărişor", simplu: "Sarisor", comuna: "Saru Dornei" },
  { nume: "Sărişoru Mare", simplu: "Sarisoru Mare", comuna: "Saru Dornei" },
  { nume: "Şaru Bucovinei", simplu: "Saru Bucovinei", comuna: "Saru Dornei" },
  { nume: "Şarul Dornei", simplu: "Sarul Dornei", comuna: "Saru Dornei" },
  { nume: "Sasca Mare", comuna: "Cornu Luncii" },
  { nume: "Sasca Mică", simplu: "Sasca Mica", comuna: "Cornu Luncii" },
  { nume: "Sasca Nouă", simplu: "Sasca Noua", comuna: "Cornu Luncii" },
  { nume: "Satu Mare" },
  { nume: "Satu Mare", comuna: "Crucea" },
  { nume: "Şcheia", simplu: "Scheia" },
  { nume: "Securiceni", comuna: "Udesti" },
  { nume: "Şerbăneşti", simplu: "Serbanesti", comuna: "Zvoristea" },
  { nume: "Şerbăuţi", simplu: "Serbauti" },
  { nume: "Şes", simplu: "Ses", comuna: "Bunesti" },
  { nume: "Şesuri", simplu: "Sesuri", comuna: "Carlibaba" },
  { nume: "Sfântu Ilie", simplu: "Sfantu Ilie", comuna: "Scheia" },
  { nume: "Siliştea Nouă", simplu: "Silistea Noua", comuna: "Dolhasca" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Liteni" },
  { nume: "Siminicea" },
  { nume: "Şinca", simplu: "Sinca", comuna: "Cornu Luncii" },
  { nume: "Siret" },
  { nume: "Slatina" },
  { nume: "Slătioara", simplu: "Slatioara", comuna: "Rasca" },
  { nume: "Slătioara", simplu: "Slatioara", comuna: "Stulpicani" },
  { nume: "Slobozia Sucevei", comuna: "Granicesti" },
  { nume: "Slobozia", comuna: "Fantanele" },
  { nume: "Slobozia", comuna: "Zvoristea" },
  { nume: "Smida Ungurenilor", comuna: "Fundu Moldovei" },
  { nume: "Solca" },
  { nume: "Şoldăneşti", simplu: "Soldanesti", comuna: "Falticeni" },
  { nume: "Soloneţ", simplu: "Solonet", comuna: "Todiresti" },
  { nume: "Soloneţu Nou", simplu: "Solonetu Nou", comuna: "Cacica" },
  { nume: "Spătăreşti", simplu: "Spataresti", comuna: "Fantana Mare" },
  { nume: "Stamate", comuna: "Fantanele" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Zvoristea" },
  { nume: "Stâncuţa", simplu: "Stancuta", comuna: "Zvoristea" },
  { nume: "Ştirbăţ", simplu: "Stirbat", comuna: "Udesti" },
  { nume: "Straja" },
  { nume: "Strâmtura", simplu: "Stramtura", comuna: "Vama" },
  { nume: "Stroieşti", simplu: "Stroiesti" },
  { nume: "Stulpicani" },
  { nume: "Suceava" },
  { nume: "Suceviţa", simplu: "Sucevita" },
  { nume: "Sunători", simplu: "Sunatori", comuna: "Dorna-Arini" },
  { nume: "Ţarna Mare", simplu: "Tarna Mare", comuna: "Falticeni" },
  { nume: "Tărnicioara", simplu: "Tarnicioara", comuna: "Ostra" },
  { nume: "Tătaru", simplu: "Tataru", comuna: "Poiana Stampei" },
  { nume: "Tăuteşti", simplu: "Tautesti", comuna: "Zamostea" },
  { nume: "Teşna", simplu: "Tesna", comuna: "Cosna" },
  { nume: "Teşna", simplu: "Tesna", comuna: "Poiana Stampei" },
  { nume: "Ţibău", simplu: "Tibau", comuna: "Carlibaba" },
  { nume: "Ţibeni", simplu: "Tibeni", comuna: "Satu Mare" },
  { nume: "Tişăuţi", simplu: "Tisauti", comuna: "Ipotesti" },
  { nume: "Todireni", comuna: "Vatra Dornei" },
  { nume: "Todireşti", simplu: "Todiresti" },
  { nume: "Ţoleşti", simplu: "Tolesti", comuna: "Forasti" },
  { nume: "Trei Movile", comuna: "Scheia" },
  { nume: "Udeşti", simplu: "Udesti" },
  { nume: "Uideşti", simplu: "Uidesti", comuna: "Forasti" },
  { nume: "Ulma" },
  { nume: "Unceşti", simplu: "Uncesti", comuna: "Bunesti" },
  { nume: "Vadu Moldovei" },
  { nume: "Vadu Negrilesei", comuna: "Stulpicani" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Stroiesti" },
  { nume: "Valea Bancului", comuna: "Cosna" },
  { nume: "Valea Bourei", comuna: "Dolhesti" },
  { nume: "Valea Glodului", comuna: "Vulturesti" },
  { nume: "Valea Moldovei" },
  { nume: "Valea Poienei", comuna: "Dolhasca" },
  { nume: "Valea Putnei", comuna: "Pojorata" },
  { nume: "Valea Stânei", simplu: "Valea Stanei", comuna: "Carlibaba" },
  { nume: "Văleni-Stânişoara", simplu: "Valeni-Stanisoara", comuna: "Malini" },
  { nume: "Vama" },
  { nume: "Văratec", simplu: "Varatec", comuna: "Salcea" },
  {
    nume: "Vârfu Dealului",
    simplu: "Varfu Dealului",
    comuna: "Partestii De Jos",
  },
  { nume: "Varvata", comuna: "Partestii De Jos" },
  { nume: "Văşcăuţi", simplu: "Vascauti", comuna: "Musenita" },
  { nume: "Vatra Dornei" },
  { nume: "Vatra Moldoviţei", simplu: "Vatra Moldovitei" },
  { nume: "Verbia", comuna: "Gramesti" },
  { nume: "Vercicani", comuna: "Liteni" },
  { nume: "Vereşti", simplu: "Veresti" },
  { nume: "Vicovu de Jos" },
  { nume: "Vicovu de Sus" },
  { nume: "Vicşani", simplu: "Vicsani", comuna: "Musenita" },
  { nume: "Voievodeasa", comuna: "Sucevita" },
  { nume: "Voitinel", comuna: "Galanesti" },
  { nume: "Volovăţ", simplu: "Volovat" },
  { nume: "Vornicenii Mari", comuna: "Moara" },
  { nume: "Vornicenii Mici", comuna: "Moara" },
  { nume: "Voroneţ", simplu: "Voronet", comuna: "Gura Humorului" },
  { nume: "Vultureşti", simplu: "Vulturesti" },
  { nume: "Zahareşti", simplu: "Zaharesti", comuna: "Stroiesti" },
  { nume: "Zalomestra", comuna: "Brodina" },
  { nume: "Zamostea" },
  { nume: "Zvoriştea", simplu: "Zvoristea" },
];
