export const sv = [
  { nume: "Adancata" },
  { nume: "Arbore" },
  { nume: "Baia" },
  { nume: "Bilca" },
  { nume: "Bogdanesti" },
  { nume: "Boroaia" },
  { nume: "Bosanci" },
  { nume: "Botosana" },
  { nume: "Breaza" },
  { nume: "Brodina" },
  { nume: "Brosteni" },
  { nume: "Bunesti" },
  { nume: "Balcauti" },
  { nume: "Cacica" },
  { nume: "Cajvana" },
  { nume: "Calafindesti" },
  { nume: "Capu Campului" },
  { nume: "Ciocanesti" },
  { nume: "Ciprian Porumbescu" },
  { nume: "Comanesti" },
  { nume: "Cornu Luncii" },
  { nume: "Cosna" },
  { nume: "Crucea" },
  { nume: "Campulung Moldovenesc" },
  { nume: "Carlibaba" },
  { nume: "Dolhasca" },
  { nume: "Dorna Candrenilor" },
  { nume: "Dorna-Arini" },
  { nume: "Dornesti" },
  { nume: "Dragoiesti" },
  { nume: "Draguseni" },
  { nume: "Dumbraveni" },
  { nume: "Darmanesti" },
  { nume: "Forasti" },
  { nume: "Frasin" },
  { nume: "Frumosu" },
  { nume: "Fratautii Noi" },
  { nume: "Fratautii Vechi" },
  { nume: "Fundu Moldovei" },
  { nume: "Fantana Mare" },
  { nume: "Fantanele" },
  { nume: "Falticeni" },
  { nume: "Gramesti" },
  { nume: "Granicesti" },
  { nume: "Gura Humorului" },
  { nume: "Galanesti" },
  { nume: "Horodnic de Sus" },
  { nume: "Horodniceni" },
  { nume: "Hantesti" },
  { nume: "Iacobeni" },
  { nume: "Iaslovat" },
  { nume: "Ipotesti" },
  { nume: "Izvoarele Sucevei" },
  { nume: "Liteni" },
  { nume: "Marginea" },
  { nume: "Milisauti" },
  { nume: "Mitocu Dragomirnei" },
  { nume: "Moldova-Sulita" },
  { nume: "Moldovita" },
  { nume: "Musenita" },
  { nume: "Malini" },
  { nume: "Manastirea Humorului" },
  { nume: "Ostra" },
  { nume: "Panaci" },
  { nume: "Poiana Stampei" },
  { nume: "Pojorata" },
  { nume: "Preutesti" },
  { nume: "Putna" },
  { nume: "Partestii de Jos" },
  { nume: "Paltinoasa" },
  { nume: "Patrauti" },
  { nume: "Rasca" },
  { nume: "Radauti" },
  { nume: "Radaseni" },
  { nume: "Sadova" },
  { nume: "Salcea" },
  { nume: "Satu Mare" },
  { nume: "Siminicea" },
  { nume: "Siret" },
  { nume: "Slatina" },
  { nume: "Solca" },
  { nume: "Straja" },
  { nume: "Stroiesti" },
  { nume: "Stulpicani" },
  { nume: "Suceava" },
  { nume: "Sucevita" },
  { nume: "Todiresti" },
  { nume: "Udesti" },
  { nume: "Ulma" },
  { nume: "Vadu Moldovei" },
  { nume: "Valea Moldovei" },
  { nume: "Vama" },
  { nume: "Vatra Dornei" },
  { nume: "Vatra Moldovitei" },
  { nume: "Veresti" },
  { nume: "Vicovu de Jos" },
  { nume: "Vicovu de Sus" },
  { nume: "Volovat" },
  { nume: "Vulturesti" },
  { nume: "Zamostea" },
  { nume: "Zvoristea" },
  { nume: "Scheia" },
  { nume: "Serbauti" },
  { nume: "Calugareni", comuna: "Adancata" },
  { nume: "Fetesti", comuna: "Adancata" },
  { nume: "Bodnareni", comuna: "Arbore" },
  { nume: "Clit", comuna: "Arbore" },
  { nume: "Bogata", comuna: "Baia" },
  { nume: "Gropeni", comuna: "Balcauti" },
  { nume: "Negostina", comuna: "Balcauti" },
  { nume: "Barasti", comuna: "Boroaia" },
  { nume: "Giulesti", comuna: "Boroaia" },
  { nume: "Moisa", comuna: "Boroaia" },
  { nume: "Sacuta", comuna: "Boroaia" },
  { nume: "Cumparatura", comuna: "Bosanci" },
  { nume: "Breaza de Sus", comuna: "Breaza" },
  { nume: "Parau Negrei", comuna: "Breaza" },
  { nume: "Brodina de Jos", comuna: "Brodina" },
  { nume: "Cununschi", comuna: "Brodina" },
  { nume: "Dubiusca", comuna: "Brodina" },
  { nume: "Ehreste", comuna: "Brodina" },
  { nume: "Falcau", comuna: "Brodina" },
  { nume: "Norocu", comuna: "Brodina" },
  { nume: "Paltin", comuna: "Brodina" },
  { nume: "Sadau", comuna: "Brodina" },
  { nume: "Zalomestra", comuna: "Brodina" },
  { nume: "Cotargasi", comuna: "Brosteni" },
  { nume: "Darmoxa", comuna: "Brosteni" },
  { nume: "Frasin", comuna: "Brosteni" },
  { nume: "Holda", comuna: "Brosteni" },
  { nume: "Holdita", comuna: "Brosteni" },
  { nume: "Haleasa", comuna: "Brosteni" },
  { nume: "Lungeni", comuna: "Brosteni" },
  { nume: "Neagra", comuna: "Brosteni" },
  { nume: "Pietroasa", comuna: "Brosteni" },
  { nume: "Petia", comuna: "Bunesti" },
  { nume: "Podeni", comuna: "Bunesti" },
  { nume: "Uncesti", comuna: "Bunesti" },
  { nume: "Ses", comuna: "Bunesti" },
  { nume: "Maidan", comuna: "Cacica" },
  { nume: "Partestii de Sus", comuna: "Cacica" },
  { nume: "Runcu", comuna: "Cacica" },
  { nume: "Solonetu Nou", comuna: "Cacica" },
  { nume: "Codru", comuna: "Cajvana" },
  { nume: "Botosanita Mare", comuna: "Calafindesti" },
  { nume: "Carlibaba Noua", comuna: "Carlibaba" },
  { nume: "Iedu", comuna: "Carlibaba" },
  { nume: "Valea Stanei", comuna: "Carlibaba" },
  { nume: "Sesuri", comuna: "Carlibaba" },
  { nume: "Tibau", comuna: "Carlibaba" },
  { nume: "Botos", comuna: "Ciocanesti" },
  { nume: "Brasca", comuna: "Ciprian Porumbescu" },
  { nume: "Balaceana", comuna: "Ciprian Porumbescu" },
  { nume: "Ilisesti", comuna: "Ciprian Porumbescu" },
  { nume: "Humoreni", comuna: "Comanesti" },
  { nume: "Braiesti", comuna: "Cornu Luncii" },
  { nume: "Baisesti", comuna: "Cornu Luncii" },
  { nume: "Dumbrava", comuna: "Cornu Luncii" },
  { nume: "Paiseni", comuna: "Cornu Luncii" },
  { nume: "Sasca Mare", comuna: "Cornu Luncii" },
  { nume: "Sasca Mica", comuna: "Cornu Luncii" },
  { nume: "Sasca Noua", comuna: "Cornu Luncii" },
  { nume: "Sinca", comuna: "Cornu Luncii" },
  { nume: "Podu Cosnei", comuna: "Cosna" },
  { nume: "Romanesti", comuna: "Cosna" },
  { nume: "Tesna", comuna: "Cosna" },
  { nume: "Valea Bancului", comuna: "Cosna" },
  { nume: "Chiril", comuna: "Crucea" },
  { nume: "Cojoci", comuna: "Crucea" },
  { nume: "Satu Mare", comuna: "Crucea" },
  { nume: "Calinesti", comuna: "Darmanesti" },
  { nume: "Calinesti-Vasilache", comuna: "Darmanesti" },
  { nume: "Danila", comuna: "Darmanesti" },
  { nume: "Maritei", comuna: "Darmanesti" },
  { nume: "Mariteia Mica", comuna: "Darmanesti" },
  { nume: "Budeni", comuna: "Dolhasca" },
  { nume: "Gulia", comuna: "Dolhasca" },
  { nume: "Poiana", comuna: "Dolhasca" },
  { nume: "Poienari", comuna: "Dolhasca" },
  { nume: "Probota", comuna: "Dolhasca" },
  { nume: "Silistea Noua", comuna: "Dolhasca" },
  { nume: "Valea Poienei", comuna: "Dolhasca" },
  { nume: "Dolhestii Mici", comuna: "Dolhesti" },
  { nume: "Dolhestii-Mari", comuna: "Dolhesti" },
  { nume: "Valea Bourei", comuna: "Dolhesti" },
  { nume: "Dealu Floreni", comuna: "Dorna Candrenilor" },
  { nume: "Poiana Negrii", comuna: "Dorna Candrenilor" },
  { nume: "Cozanesti", comuna: "Dorna-Arini" },
  { nume: "Gheorghiteni", comuna: "Dorna-Arini" },
  { nume: "Ortoaia", comuna: "Dorna-Arini" },
  { nume: "Rusca", comuna: "Dorna-Arini" },
  { nume: "Sunatori", comuna: "Dorna-Arini" },
  { nume: "Iaz", comuna: "Dornesti" },
  { nume: "Berchisesti", comuna: "Dragoiesti" },
  { nume: "Corlata", comuna: "Dragoiesti" },
  { nume: "Lucacesti", comuna: "Dragoiesti" },
  { nume: "Mazanaesti", comuna: "Dragoiesti" },
  { nume: "Brosteni", comuna: "Draguseni" },
  { nume: "Gara Leu", comuna: "Draguseni" },
  { nume: "Salageni", comuna: "Dumbraveni" },
  { nume: "Soldanesti", comuna: "Falticeni" },
  { nume: "Tarna Mare", comuna: "Falticeni" },
  { nume: "Cotu Baii", comuna: "Fantana Mare" },
  { nume: "Praxia", comuna: "Fantana Mare" },
  { nume: "Spataresti", comuna: "Fantana Mare" },
  { nume: "Banesti", comuna: "Fantanele" },
  { nume: "Cotu Dobei", comuna: "Fantanele" },
  { nume: "Slobozia", comuna: "Fantanele" },
  { nume: "Stamate", comuna: "Fantanele" },
  { nume: "Antoceni", comuna: "Forasti" },
  { nume: "Boura", comuna: "Forasti" },
  { nume: "Manolea", comuna: "Forasti" },
  { nume: "Oniceni", comuna: "Forasti" },
  { nume: "Rosiori", comuna: "Forasti" },
  { nume: "Rusi", comuna: "Forasti" },
  { nume: "Uidesti", comuna: "Forasti" },
  { nume: "Tolesti", comuna: "Forasti" },
  { nume: "Bucsoaia", comuna: "Frasin" },
  { nume: "Doroteia", comuna: "Frasin" },
  { nume: "Plutonita", comuna: "Frasin" },
  { nume: "Costisa", comuna: "Fratautii Noi" },
  { nume: "Maneuti", comuna: "Fratautii Vechi" },
  { nume: "Deia", comuna: "Frumosu" },
  { nume: "Dragosa", comuna: "Frumosu" },
  { nume: "Botus", comuna: "Fundu Moldovei" },
  { nume: "Botusel", comuna: "Fundu Moldovei" },
  { nume: "Branistea", comuna: "Fundu Moldovei" },
  { nume: "Colacu", comuna: "Fundu Moldovei" },
  { nume: "Delnita", comuna: "Fundu Moldovei" },
  { nume: "Delut", comuna: "Fundu Moldovei" },
  { nume: "Obcina", comuna: "Fundu Moldovei" },
  { nume: "Plai", comuna: "Fundu Moldovei" },
  { nume: "Smida Ungurenilor", comuna: "Fundu Moldovei" },
  { nume: "Hurjuieni", comuna: "Galanesti" },
  { nume: "Voitinel", comuna: "Galanesti" },
  { nume: "Botosanita Mica", comuna: "Gramesti" },
  { nume: "Balinesti", comuna: "Gramesti" },
  { nume: "Rudesti", comuna: "Gramesti" },
  { nume: "Verbia", comuna: "Gramesti" },
  { nume: "Dumbrava", comuna: "Granicesti" },
  { nume: "Gura Solcii", comuna: "Granicesti" },
  { nume: "Iacobesti", comuna: "Granicesti" },
  { nume: "Romanesti", comuna: "Granicesti" },
  { nume: "Slobozia Sucevei", comuna: "Granicesti" },
  { nume: "Voronet", comuna: "Gura Humorului" },
  { nume: "Artari", comuna: "Hantesti" },
  { nume: "Beresti", comuna: "Hantesti" },
  { nume: "Horodnic de Jos", comuna: "Horodnic" },
  { nume: "Botesti", comuna: "Horodniceni" },
  { nume: "Bradatel", comuna: "Horodniceni" },
  { nume: "Mihaiesti", comuna: "Horodniceni" },
  { nume: "Rotopanesti", comuna: "Horodniceni" },
  { nume: "Mestecanis", comuna: "Iacobeni" },
  { nume: "Lisaura", comuna: "Ipotesti" },
  { nume: "Tisauti", comuna: "Ipotesti" },
  { nume: "Bobeica", comuna: "Izvoarele Sucevei" },
  { nume: "Brodina", comuna: "Izvoarele Sucevei" },
  { nume: "Corni", comuna: "Liteni" },
  { nume: "Rotunda", comuna: "Liteni" },
  { nume: "Roscani", comuna: "Liteni" },
  { nume: "Silistea", comuna: "Liteni" },
  { nume: "Vercicani", comuna: "Liteni" },
  { nume: "Iesle", comuna: "Malini" },
  { nume: "Poiana Marului", comuna: "Malini" },
  { nume: "Paraie", comuna: "Malini" },
  { nume: "Valeni-Stanisoara", comuna: "Malini" },
  { nume: "Plesa", comuna: "Manastirea Humorului" },
  { nume: "Poiana Micului", comuna: "Manastirea Humorului" },
  { nume: "Badeuti", comuna: "Milisauti" },
  { nume: "Gara", comuna: "Milisauti" },
  { nume: "Lunca", comuna: "Milisauti" },
  { nume: "Dragomirna", comuna: "Mitocu Dragomirnei" },
  { nume: "Lipoveni", comuna: "Mitocu Dragomirnei" },
  { nume: "Mitocasi", comuna: "Mitocu Dragomirnei" },
  { nume: "Bulai", comuna: "Moara" },
  { nume: "Frumoasa", comuna: "Moara" },
  { nume: "Groapa Vladichii", comuna: "Moara" },
  { nume: "Liteni", comuna: "Moara" },
  { nume: "Moara Carp", comuna: "Moara" },
  { nume: "Moara Nica", comuna: "Moara" },
  { nume: "Vornicenii Mari", comuna: "Moara" },
  { nume: "Vornicenii Mici", comuna: "Moara" },
  { nume: "Benia", comuna: "Moldova-Sulita" },
  { nume: "Argel", comuna: "Moldovita" },
  { nume: "Demacusa", comuna: "Moldovita" },
  { nume: "Rasca", comuna: "Moldovita" },
  { nume: "Bainet", comuna: "Musenita" },
  { nume: "Bancesti", comuna: "Musenita" },
  { nume: "Climauti", comuna: "Musenita" },
  { nume: "Vicsani", comuna: "Musenita" },
  { nume: "Vascauti", comuna: "Musenita" },
  { nume: "Tarnicioara", comuna: "Ostra" },
  { nume: "Capu Codrului", comuna: "Paltinoasa" },
  { nume: "Catrinari", comuna: "Panaci" },
  { nume: "Coverca", comuna: "Panaci" },
  { nume: "Dragoiasa", comuna: "Panaci" },
  { nume: "Glodu", comuna: "Panaci" },
  { nume: "Paltinis", comuna: "Panaci" },
  { nume: "Deleni", comuna: "Partestii De Jos" },
  { nume: "Varvata", comuna: "Partestii De Jos" },
  { nume: "Varfu Dealului", comuna: "Partestii De Jos" },
  { nume: "Casoi", comuna: "Poiana Stampei" },
  { nume: "Dornisoara", comuna: "Poiana Stampei" },
  { nume: "Pilugani", comuna: "Poiana Stampei" },
  { nume: "Praleni", comuna: "Poiana Stampei" },
  { nume: "Tesna", comuna: "Poiana Stampei" },
  { nume: "Tataru", comuna: "Poiana Stampei" },
  { nume: "Valea Putnei", comuna: "Pojorata" },
  { nume: "Arghira", comuna: "Preutesti" },
  { nume: "Bahna Arin", comuna: "Preutesti" },
  { nume: "Basarabi", comuna: "Preutesti" },
  { nume: "Husi", comuna: "Preutesti" },
  { nume: "Hartop", comuna: "Preutesti" },
  { nume: "Leucusesti", comuna: "Preutesti" },
  { nume: "Gura Putnei", comuna: "Putna" },
  { nume: "Lamaseni", comuna: "Radaseni" },
  { nume: "Pocoleni", comuna: "Radaseni" },
  { nume: "Buda", comuna: "Rasca" },
  { nume: "Dumbraveni", comuna: "Rasca" },
  { nume: "Jahalia", comuna: "Rasca" },
  { nume: "Slatioara", comuna: "Rasca" },
  { nume: "Mereni", comuna: "Salcea" },
  { nume: "Plopeni", comuna: "Salcea" },
  { nume: "Prelipca", comuna: "Salcea" },
  { nume: "Varatec", comuna: "Salcea" },
  { nume: "Gura Haitii", comuna: "Saru Dornei" },
  { nume: "Neagra Sarului", comuna: "Saru Dornei" },
  { nume: "Plaiu Sarului", comuna: "Saru Dornei" },
  { nume: "Sarisor", comuna: "Saru Dornei" },
  { nume: "Sarisoru Mare", comuna: "Saru Dornei" },
  { nume: "Saru Bucovinei", comuna: "Saru Dornei" },
  { nume: "Sarul Dornei", comuna: "Saru Dornei" },
  { nume: "Tibeni", comuna: "Satu Mare" },
  { nume: "Florinta", comuna: "Scheia" },
  { nume: "Mihoveni", comuna: "Scheia" },
  { nume: "Sfantu Ilie", comuna: "Scheia" },
  { nume: "Trei Movile", comuna: "Scheia" },
  { nume: "Calinesti", comuna: "Serbauti" },
  { nume: "Grigoresti", comuna: "Siminicea" },
  { nume: "Manastioara", comuna: "Siret" },
  { nume: "Padureni", comuna: "Siret" },
  { nume: "Gainesti", comuna: "Slatina" },
  { nume: "Herla", comuna: "Slatina" },
  { nume: "Poieni-Solca", comuna: "Solca" },
  { nume: "Valcelele", comuna: "Stroiesti" },
  { nume: "Zaharesti", comuna: "Stroiesti" },
  { nume: "Gemenea", comuna: "Stulpicani" },
  { nume: "Negrileasa", comuna: "Stulpicani" },
  { nume: "Slatioara", comuna: "Stulpicani" },
  { nume: "Vadu Negrilesei", comuna: "Stulpicani" },
  { nume: "Voievodeasa", comuna: "Sucevita" },
  { nume: "Costana", comuna: "Todiresti" },
  { nume: "Parhauti", comuna: "Todiresti" },
  { nume: "Solonet", comuna: "Todiresti" },
  { nume: "Sarghiesti", comuna: "Todiresti" },
  { nume: "Chiliseni", comuna: "Udesti" },
  { nume: "Luncusoara", comuna: "Udesti" },
  { nume: "Manastioara", comuna: "Udesti" },
  { nume: "Plavalari", comuna: "Udesti" },
  { nume: "Poieni-Suceava", comuna: "Udesti" },
  { nume: "Racova", comuna: "Udesti" },
  { nume: "Reuseni", comuna: "Udesti" },
  { nume: "Rusii-Manastioara", comuna: "Udesti" },
  { nume: "Securiceni", comuna: "Udesti" },
  { nume: "Stirbat", comuna: "Udesti" },
  { nume: "Costileva", comuna: "Ulma" },
  { nume: "Lupcina", comuna: "Ulma" },
  { nume: "Magura", comuna: "Ulma" },
  { nume: "Nisipitu", comuna: "Ulma" },
  { nume: "Ciumulesti", comuna: "Vadu Moldovei" },
  { nume: "Camarzani", comuna: "Vadu Moldovei" },
  { nume: "Dumbravita", comuna: "Vadu Moldovei" },
  { nume: "Ioneasa", comuna: "Vadu Moldovei" },
  { nume: "Mesteceni", comuna: "Vadu Moldovei" },
  { nume: "Movileni", comuna: "Vadu Moldovei" },
  { nume: "Nigotesti", comuna: "Vadu Moldovei" },
  { nume: "Mironu", comuna: "Valea Moldovei" },
  { nume: "Molid", comuna: "Vama" },
  { nume: "Prisaca Dornei", comuna: "Vama" },
  { nume: "Stramtura", comuna: "Vama" },
  { nume: "Argestru", comuna: "Vatra Dornei" },
  { nume: "Rosu", comuna: "Vatra Dornei" },
  { nume: "Todireni", comuna: "Vatra Dornei" },
  { nume: "Ciumarna", comuna: "Vatra Moldovitei" },
  { nume: "Paltinu", comuna: "Vatra Moldovitei" },
  { nume: "Bursuceni", comuna: "Veresti" },
  { nume: "Corocaiesti", comuna: "Veresti" },
  { nume: "Hancea", comuna: "Veresti" },
  { nume: "Bivolaria", comuna: "Vicovu De Sus" },
  { nume: "Burla", comuna: "Volovat" },
  { nume: "Giurgesti", comuna: "Vulturesti" },
  { nume: "Hreatca", comuna: "Vulturesti" },
  { nume: "Jacota", comuna: "Vulturesti" },
  { nume: "Meresti", comuna: "Vulturesti" },
  { nume: "Osoi", comuna: "Vulturesti" },
  { nume: "Plesesti", comuna: "Vulturesti" },
  { nume: "Valea Glodului", comuna: "Vulturesti" },
  { nume: "Badragi", comuna: "Zamostea" },
  { nume: "Ciomartan", comuna: "Zamostea" },
  { nume: "Cojocareni", comuna: "Zamostea" },
  { nume: "Corpaci", comuna: "Zamostea" },
  { nume: "Lunca", comuna: "Zamostea" },
  { nume: "Nicani", comuna: "Zamostea" },
  { nume: "Rauteni", comuna: "Zamostea" },
  { nume: "Tautesti", comuna: "Zamostea" },
  { nume: "Buda", comuna: "Zvoristea" },
  { nume: "Dealu", comuna: "Zvoristea" },
  { nume: "Poiana", comuna: "Zvoristea" },
  { nume: "Slobozia", comuna: "Zvoristea" },
  { nume: "Stanca", comuna: "Zvoristea" },
  { nume: "Stancuta", comuna: "Zvoristea" },
  { nume: "Serbanesti", comuna: "Zvoristea" },
];
