export const sj = [
  { nume: "Agrij" },
  { nume: "Almasu" },
  { nume: "Benesat" },
  { nume: "Bobota" },
  { nume: "Bocsa" },
  { nume: "Buciumi" },
  { nume: "Babeni" },
  { nume: "Balan" },
  { nume: "Banisor" },
  { nume: "Camar" },
  { nume: "Carastelec" },
  { nume: "Cehu Silvaniei" },
  { nume: "Chiesd" },
  { nume: "Cizer" },
  { nume: "Coseiu" },
  { nume: "Crasna" },
  { nume: "Creaca" },
  { nume: "Cristolt" },
  { nume: "Criseni" },
  { nume: "Cuzaplac" },
  { nume: "Dobrin" },
  { nume: "Dragu" },
  { nume: "Fildu de Jos" },
  { nume: "Galgau" },
  { nume: "Garbou" },
  { nume: "Halmasd" },
  { nume: "Hereclean" },
  { nume: "Hida" },
  { nume: "Horoatu Crasnei" },
  { nume: "Ileanda" },
  { nume: "Ip" },
  { nume: "Jibou" },
  { nume: "Letca" },
  { nume: "Lozna" },
  { nume: "Marca" },
  { nume: "Mesesenii de Jos" },
  { nume: "Mirsid" },
  { nume: "Maeriste" },
  { nume: "Nusfalau" },
  { nume: "Napradea" },
  { nume: "Pericei" },
  { nume: "Plopis" },
  { nume: "Poiana Blenchii" },
  { nume: "Romanasi" },
  { nume: "Rus" },
  { nume: "Somes-Odorhei" },
  { nume: "Surduc" },
  { nume: "Sag" },
  { nume: "Sanmihaiu Almasului" },
  { nume: "Salatig" },
  { nume: "Treznea" },
  { nume: "Valcau de Jos" },
  { nume: "Varsolt" },
  { nume: "Zalha" },
  { nume: "Zalau" },
  { nume: "Zimbor" },
  { nume: "Samsud" },
  { nume: "Simisna" },
  { nume: "Simleu Silvaniei" },
  { nume: "Sarmasag" },
  { nume: "Rastoltu Desert", comuna: "Agrij" },
  { nume: "Babiu", comuna: "Almasu" },
  { nume: "Cutis", comuna: "Almasu" },
  { nume: "Jebucu", comuna: "Almasu" },
  { nume: "Mesteacanu", comuna: "Almasu" },
  { nume: "Petrinzel", comuna: "Almasu" },
  { nume: "Sfaras", comuna: "Almasu" },
  { nume: "Stana", comuna: "Almasu" },
  { nume: "Taudu", comuna: "Almasu" },
  { nume: "Ciocmani", comuna: "Babeni" },
  { nume: "Clit", comuna: "Babeni" },
  { nume: "Pirosa", comuna: "Babeni" },
  { nume: "Poienita", comuna: "Babeni" },
  { nume: "Chechis", comuna: "Balan" },
  { nume: "Chendrea", comuna: "Balan" },
  { nume: "Galgau Almasului", comuna: "Balan" },
  { nume: "Galpaia", comuna: "Balan" },
  { nume: "Ban", comuna: "Banisor" },
  { nume: "Peceiu", comuna: "Banisor" },
  { nume: "Alunis", comuna: "Benesat" },
  { nume: "Biusa", comuna: "Benesat" },
  { nume: "Dersida", comuna: "Bobota" },
  { nume: "Zalnoc", comuna: "Bobota" },
  { nume: "Borla", comuna: "Bocsa" },
  { nume: "Campia", comuna: "Bocsa" },
  { nume: "Salajeni", comuna: "Bocsa" },
  { nume: "Bodia", comuna: "Buciumi" },
  { nume: "Bogdana", comuna: "Buciumi" },
  { nume: "Huta", comuna: "Buciumi" },
  { nume: "Rastolt", comuna: "Buciumi" },
  { nume: "Sangeorgiu de Meses", comuna: "Buciumi" },
  { nume: "Padureni", comuna: "Camar" },
  { nume: "Dumuslau", comuna: "Carastelec" },
  { nume: "Horoatu Cehului", comuna: "Cehu Silvaniei" },
  { nume: "Motis", comuna: "Cehu Silvaniei" },
  { nume: "Nadis", comuna: "Cehu Silvaniei" },
  { nume: "Ulciug", comuna: "Cehu Silvaniei" },
  { nume: "Colonia Sighetu Silvaniei", comuna: "Chiesd" },
  { nume: "Sighetu Silvaniei", comuna: "Chiesd" },
  { nume: "Plesca", comuna: "Cizer" },
  { nume: "Pria", comuna: "Cizer" },
  { nume: "Archid", comuna: "Coseiu" },
  { nume: "Chilioara", comuna: "Coseiu" },
  { nume: "Huseni", comuna: "Crasna" },
  { nume: "Marin", comuna: "Crasna" },
  { nume: "Ratin", comuna: "Crasna" },
  { nume: "Borza", comuna: "Creaca" },
  { nume: "Brebi", comuna: "Creaca" },
  { nume: "Brusturi", comuna: "Creaca" },
  { nume: "Ciglean", comuna: "Creaca" },
  { nume: "Jac", comuna: "Creaca" },
  { nume: "Lupoaia", comuna: "Creaca" },
  { nume: "Prodanesti", comuna: "Creaca" },
  { nume: "Viile Jacului", comuna: "Creaca" },
  { nume: "Cristur Criseni", comuna: "Criseni" },
  { nume: "Garceiu", comuna: "Criseni" },
  { nume: "Muncel", comuna: "Cristolt" },
  { nume: "Poiana Ontii", comuna: "Cristolt" },
  { nume: "Valeni", comuna: "Cristolt" },
  { nume: "Cublesu", comuna: "Cuzaplac" },
  { nume: "Galaseni", comuna: "Cuzaplac" },
  { nume: "Mierta", comuna: "Cuzaplac" },
  { nume: "Petrindu", comuna: "Cuzaplac" },
  { nume: "Ruginoasa", comuna: "Cuzaplac" },
  { nume: "Stoboru", comuna: "Cuzaplac" },
  { nume: "Tamasa", comuna: "Cuzaplac" },
  { nume: "Deleni", comuna: "Dobrin" },
  { nume: "Doba", comuna: "Dobrin" },
  { nume: "Naimon", comuna: "Dobrin" },
  { nume: "Sancraiu Silvaniei", comuna: "Dobrin" },
  { nume: "Verveghiu", comuna: "Dobrin" },
  { nume: "Adalin", comuna: "Dragu" },
  { nume: "Fantanele", comuna: "Dragu" },
  { nume: "Ugrutiu", comuna: "Dragu" },
  { nume: "Voivodeni", comuna: "Dragu" },
  { nume: "Fildu de Mijloc", comuna: "Fildu De Jos" },
  { nume: "Fildu de Sus", comuna: "Fildu De Jos" },
  { nume: "Tetisu", comuna: "Fildu De Jos" },
  { nume: "Barsau Mare", comuna: "Galgau" },
  { nume: "Chizeni", comuna: "Galgau" },
  { nume: "Capalna", comuna: "Galgau" },
  { nume: "Dobrocina", comuna: "Galgau" },
  { nume: "Fodora", comuna: "Galgau" },
  { nume: "Francenii de Piatra", comuna: "Galgau" },
  { nume: "Glod", comuna: "Galgau" },
  { nume: "Gura Vladesei", comuna: "Galgau" },
  { nume: "Bezded", comuna: "Garbou" },
  { nume: "Cernuc", comuna: "Garbou" },
  { nume: "Calacea", comuna: "Garbou" },
  { nume: "Fabrica", comuna: "Garbou" },
  { nume: "Popteleac", comuna: "Garbou" },
  { nume: "Solomon", comuna: "Garbou" },
  { nume: "Aleus", comuna: "Halmasd" },
  { nume: "Cerisa", comuna: "Halmasd" },
  { nume: "Drighiu", comuna: "Halmasd" },
  { nume: "Fufez", comuna: "Halmasd" },
  { nume: "Badon", comuna: "Hereclean" },
  { nume: "Bocsita", comuna: "Hereclean" },
  { nume: "Diosod", comuna: "Hereclean" },
  { nume: "Guruslau", comuna: "Hereclean" },
  { nume: "Panic", comuna: "Hereclean" },
  { nume: "Baica", comuna: "Hida" },
  { nume: "Miluani", comuna: "Hida" },
  { nume: "Paduris", comuna: "Hida" },
  { nume: "Racas", comuna: "Hida" },
  { nume: "Stupini", comuna: "Hida" },
  { nume: "Sanpetru Almasului", comuna: "Hida" },
  { nume: "Trestia", comuna: "Hida" },
  { nume: "Hurez", comuna: "Horoatu Crasnei" },
  { nume: "Starciu", comuna: "Horoatu Crasnei" },
  { nume: "Seredeiu", comuna: "Horoatu Crasnei" },
  { nume: "Bizusa Bai", comuna: "Ileanda" },
  { nume: "Barsauta", comuna: "Ileanda" },
  { nume: "Dolheni", comuna: "Ileanda" },
  { nume: "Dabaceni", comuna: "Ileanda" },
  { nume: "Luminisu", comuna: "Ileanda" },
  { nume: "Maleni", comuna: "Ileanda" },
  { nume: "Negreni", comuna: "Ileanda" },
  { nume: "Perii Vadului", comuna: "Ileanda" },
  { nume: "Podisu", comuna: "Ileanda" },
  { nume: "Rogna", comuna: "Ileanda" },
  { nume: "Rastoci", comuna: "Ileanda" },
  { nume: "Sasa", comuna: "Ileanda" },
  { nume: "Cosniciu de Jos", comuna: "Ip" },
  { nume: "Cosniciu de Sus", comuna: "Ip" },
  { nume: "Zauan", comuna: "Ip" },
  { nume: "Zauan Bai", comuna: "Ip" },
  { nume: "Cuceu", comuna: "Jibou" },
  { nume: "Husia", comuna: "Jibou" },
  { nume: "Rona", comuna: "Jibou" },
  { nume: "Var", comuna: "Jibou" },
  { nume: "Ciula", comuna: "Letca" },
  { nume: "Cozla", comuna: "Letca" },
  { nume: "Cuciulat", comuna: "Letca" },
  { nume: "Lemniu", comuna: "Letca" },
  { nume: "Purcaret", comuna: "Letca" },
  { nume: "Toplita", comuna: "Letca" },
  { nume: "Valisoara", comuna: "Letca" },
  { nume: "Soimuseni", comuna: "Letca" },
  { nume: "Cormenis", comuna: "Lozna" },
  { nume: "Preluci", comuna: "Lozna" },
  { nume: "Valea Lesului", comuna: "Lozna" },
  { nume: "Valea Loznei", comuna: "Lozna" },
  { nume: "Cristelec", comuna: "Maeriste" },
  { nume: "Doh", comuna: "Maeriste" },
  { nume: "Giurtelecu Simleului", comuna: "Maeriste" },
  { nume: "Maladia", comuna: "Maeriste" },
  { nume: "Uileacu Simleului", comuna: "Maeriste" },
  { nume: "Lesmir", comuna: "Marca" },
  { nume: "Marca Huta", comuna: "Marca" },
  { nume: "Port", comuna: "Marca" },
  { nume: "Sumal", comuna: "Marca" },
  { nume: "Aghires", comuna: "Mesesenii De Jos" },
  { nume: "Fetindia", comuna: "Mesesenii De Jos" },
  { nume: "Mesesenii de Sus", comuna: "Mesesenii De Jos" },
  { nume: "Firminis", comuna: "Mirsid" },
  { nume: "Moigrad-Porolissum", comuna: "Mirsid" },
  { nume: "Popeni", comuna: "Mirsid" },
  { nume: "Cheud", comuna: "Napradea" },
  { nume: "Somes Guruslau", comuna: "Napradea" },
  { nume: "Tranis", comuna: "Napradea" },
  { nume: "Vadurele", comuna: "Napradea" },
  { nume: "Bilghez", comuna: "Nusfalau" },
  { nume: "Boghis", comuna: "Nusfalau" },
  { nume: "Bozies", comuna: "Nusfalau" },
  { nume: "Badacin", comuna: "Pericei" },
  { nume: "Periceiu Mic", comuna: "Pericei" },
  { nume: "Sici", comuna: "Pericei" },
  { nume: "Fagetu", comuna: "Plopis" },
  { nume: "Iaz", comuna: "Plopis" },
  { nume: "Falcusa", comuna: "Poiana Blenchii" },
  { nume: "Gostila", comuna: "Poiana Blenchii" },
  { nume: "Magura", comuna: "Poiana Blenchii" },
  { nume: "Chichisa", comuna: "Romanasi" },
  { nume: "Ciumarna", comuna: "Romanasi" },
  { nume: "Poarta Salajului", comuna: "Romanasi" },
  { nume: "Pausa", comuna: "Romanasi" },
  { nume: "Romita", comuna: "Romanasi" },
  { nume: "Buzas", comuna: "Rus" },
  { nume: "Fantanele Rus", comuna: "Rus" },
  { nume: "Fizes", comuna: "Sag" },
  { nume: "Mal", comuna: "Sag" },
  { nume: "Sarbi", comuna: "Sag" },
  { nume: "Tusa", comuna: "Sag" },
  { nume: "Bulgari", comuna: "Salatig" },
  { nume: "Deja", comuna: "Salatig" },
  { nume: "Mineu", comuna: "Salatig" },
  { nume: "Notig", comuna: "Salatig" },
  { nume: "Valea Pomilor", comuna: "Samsud" },
  { nume: "Bercea", comuna: "Sanmihaiu Almasului" },
  { nume: "Santa Maria", comuna: "Sanmihaiu Almasului" },
  { nume: "Ilisua", comuna: "Sarmasag" },
  { nume: "Lompirt", comuna: "Sarmasag" },
  { nume: "Moiad", comuna: "Sarmasag" },
  { nume: "Poiana Magura", comuna: "Sarmasag" },
  { nume: "Tarmure", comuna: "Sarmasag" },
  { nume: "Hasmas", comuna: "Simisna" },
  { nume: "Bic", comuna: "Simleu Silvaniei" },
  { nume: "Cehei", comuna: "Simleu Silvaniei" },
  { nume: "Pusta", comuna: "Simleu Silvaniei" },
  { nume: "Barsa", comuna: "Somes-Odorhei" },
  { nume: "Domnin", comuna: "Somes-Odorhei" },
  { nume: "Inau", comuna: "Somes-Odorhei" },
  { nume: "Soimus", comuna: "Somes-Odorhei" },
  { nume: "Braglez", comuna: "Surduc" },
  { nume: "Cristoltel", comuna: "Surduc" },
  { nume: "Solona", comuna: "Surduc" },
  { nume: "Testioara", comuna: "Surduc" },
  { nume: "Tihau", comuna: "Surduc" },
  { nume: "Turbuta", comuna: "Surduc" },
  { nume: "Bozna", comuna: "Treznea" },
  { nume: "Lazuri", comuna: "Valcau De Jos" },
  { nume: "Preoteasa", comuna: "Valcau De Jos" },
  { nume: "Ratovei", comuna: "Valcau De Jos" },
  { nume: "Sub Cetate", comuna: "Valcau De Jos" },
  { nume: "Valcau de Sus", comuna: "Valcau De Jos" },
  { nume: "Recea", comuna: "Varsolt" },
  { nume: "Recea Mica", comuna: "Varsolt" },
  { nume: "Stana", comuna: "Zalau" },
  { nume: "Ceaca", comuna: "Zalha" },
  { nume: "Ciureni", comuna: "Zalha" },
  { nume: "Valea Ciurenilor", comuna: "Zalha" },
  { nume: "Valea Hranei", comuna: "Zalha" },
  { nume: "Valea Lunga", comuna: "Zalha" },
  { nume: "Vartesca", comuna: "Zalha" },
  { nume: "Chendremal", comuna: "Zimbor" },
  { nume: "Dolu", comuna: "Zimbor" },
  { nume: "Sutoru", comuna: "Zimbor" },
  { nume: "Sancraiu Almasului", comuna: "Zimbor" },
];
