export const sm = [
  { nume: "Acâș", simplu: "Acas", comuna: "Acis" },
  { nume: "Aciua", comuna: "Pomi" },
  { nume: "Adrian", comuna: "Livada" },
  { nume: "Ady Endre", comuna: "Cauas" },
  { nume: "Agriș", simplu: "Agris", comuna: "Botiz" },
  { nume: "Aliceni", comuna: "Tarsolt" },
  { nume: "Aliza", comuna: "Terebesti" },
  { nume: "Amați", simplu: "Amati", comuna: "Paulesti" },
  { nume: "Ambud", comuna: "Paulesti" },
  { nume: "Andrid" },
  { nume: "Apa" },
  { nume: "Apateu", comuna: "Culciu" },
  { nume: "Ardud-Vii", comuna: "Ardud" },
  { nume: "Ardud" },
  { nume: "Atea", comuna: "Dorolt" },
  { nume: "Baba Novac", comuna: "Ardud" },
  { nume: "Băbășești", simplu: "Babasesti", comuna: "Mediesu Aurit" },
  { nume: "Băbești", simplu: "Babesti", comuna: "Halmeu" },
  { nume: "Babța", simplu: "Babta", comuna: "Bogdand" },
  { nume: "Bârsău de Jos", simplu: "Barsau de Jos", comuna: "Barsau" },
  { nume: "Bârsău de Sus", simplu: "Barsau de Sus", comuna: "Barsau" },
  { nume: "Bătarci", simplu: "Batarci" },
  { nume: "Becheni", comuna: "Sauca" },
  { nume: "Beltiug" },
  { nume: "Bercu Nou", comuna: "Micula" },
  { nume: "Bercu", comuna: "Lazuri" },
  { nume: "Berea", comuna: "Sanislau" },
  { nume: "Berindan", comuna: "Odoreu" },
  { nume: "Berveni" },
  { nume: "Bicău", simplu: "Bicau", comuna: "Pomi" },
  { nume: "Bixad" },
  { nume: "Blaja", comuna: "Tasnad" },
  { nume: "Bocicău", simplu: "Bocicau", comuna: "Tarna Mare" },
  { nume: "Bogdand" },
  { nume: "Boghiș", simplu: "Boghis", comuna: "Doba" },
  { nume: "Boinești", simplu: "Boinesti", comuna: "Bixad" },
  { nume: "Bolda", comuna: "Beltiug" },
  { nume: "Borlești", simplu: "Borlesti", comuna: "Pomi" },
  { nume: "Botiz" },
  { nume: "Călinești-Oaș", simplu: "Calinesti-Oas" },
  { nume: "Cămărzana", simplu: "Camarzana" },
  { nume: "Cămin", simplu: "Camin" },
  { nume: "Căpleni", simplu: "Capleni" },
  { nume: "Cărășeu", simplu: "Caraseu", comuna: "Culciu" },
  { nume: "Carei" },
  { nume: "Căuaș", simplu: "Cauas" },
  { nume: "Cean", comuna: "Sauca" },
  { nume: "Cehal" },
  { nume: "Cehăluț", simplu: "Cehalut", comuna: "Cehal" },
  { nume: "Certeze" },
  { nume: "Chegea", comuna: "Sacaseni" },
  { nume: "Chereușa", simplu: "Chereusa", comuna: "Santau" },
  { nume: "Chilia", comuna: "Homoroade" },
  { nume: "Chisău", simplu: "Chisau", comuna: "Sauca" },
  { nume: "Cidreag", comuna: "Halmeu" },
  { nume: "Cig", comuna: "Tasnad" },
  { nume: "Cionchești", simplu: "Cionchesti", comuna: "Viile Satu Mare" },
  { nume: "Ciumești", simplu: "Ciumesti", comuna: "Sanislau" },
  { nume: "Ciuperceni", comuna: "Botiz" },
  { nume: "Coca", comuna: "Calinesti-Oas" },
  { nume: "Comlăușa", simplu: "Comlausa", comuna: "Batarci" },
  { nume: "Corod", comuna: "Culciu" },
  { nume: "Corund", comuna: "Bogdand" },
  { nume: "Craidorolț", simplu: "Craidorolt" },
  { nume: "Crișeni", simplu: "Criseni", comuna: "Craidorolt" },
  { nume: "Crucișor", simplu: "Crucisor" },
  { nume: "Cucu", comuna: "Odoreu" },
  { nume: "Culciu Mare", comuna: "Culciu" },
  { nume: "Culciu Mic", comuna: "Culciu" },
  { nume: "Cuța", simplu: "Cuta", comuna: "Socond" },
  { nume: "Dacia", comuna: "Doba" },
  { nume: "Dara", comuna: "Dorolt" },
  { nume: "Decebal", comuna: "Vetis" },
  { nume: "Dindești", simplu: "Dindesti", comuna: "Andrid" },
  { nume: "Dindeștiu Mic", simplu: "Dindestiu Mic", comuna: "Petresti" },
  { nume: "Doba" },
  { nume: "Dobolț", simplu: "Dobolt", comuna: "Halmeu" },
  { nume: "Dobra", comuna: "Supur" },
  { nume: "Domănești", simplu: "Domanesti", comuna: "Moftin" },
  { nume: "Dorolț", simplu: "Dorolt" },
  { nume: "Drăgușeni", simplu: "Draguseni", comuna: "Turulung" },
  { nume: "Dumbrava", comuna: "Livada" },
  { nume: "Eriu Sâncrai", simplu: "Eriu Sancrai", comuna: "Craidorolt" },
  { nume: "Eteni", comuna: "Odoreu" },
  { nume: "Foieni" },
  { nume: "Ganaș", simplu: "Ganas", comuna: "Acis" },
  { nume: "Gelu", comuna: "Terebesti" },
  { nume: "Gerăușa", simplu: "Gerausa", comuna: "Ardud" },
  { nume: "Ghenci", comuna: "Cauas" },
  { nume: "Gherța Mare", simplu: "Gherta Mare", comuna: "Turt" },
  { nume: "Gherța Mică", simplu: "Gherta Mica" },
  { nume: "Ghilești", simplu: "Ghilesti", comuna: "Cauas" },
  { nume: "Ghilvaci", comuna: "Moftin" },
  { nume: "Ghirișa", simplu: "Ghirisa", comuna: "Beltiug" },
  { nume: "Ghirolt", comuna: "Moftin" },
  { nume: "Giorocuta", comuna: "Supur" },
  { nume: "Giungi", comuna: "Beltiug" },
  { nume: "Giurtelecu Hododului", comuna: "Hodod" },
  { nume: "Halmeu Vii", comuna: "Halmeu" },
  { nume: "Halmeu" },
  { nume: "Hodișa", simplu: "Hodisa", comuna: "Socond" },
  { nume: "Hodod" },
  { nume: "Homorodu de Jos", comuna: "Homoroade" },
  { nume: "Homorodu de Mijloc", comuna: "Homoroade" },
  { nume: "Homorodu de Sus", comuna: "Homoroade" },
  { nume: "Horea", comuna: "Sanislau" },
  { nume: "Hotoan", comuna: "Cauas" },
  { nume: "Hrip", comuna: "Paulesti" },
  { nume: "Hurezu Mare", comuna: "Supur" },
  { nume: "Huta Certeze", comuna: "Certeze" },
  { nume: "Ianculești", simplu: "Ianculesti", comuna: "Carei" },
  { nume: "Iegheriște", simplu: "Iegheriste", comuna: "Crucisor" },
  { nume: "Iojib", comuna: "Mediesu Aurit" },
  { nume: "Irina", comuna: "Andrid" },
  { nume: "Istrău", simplu: "Istrau", comuna: "Moftin" },
  { nume: "Lazuri" },
  { nume: "Lechința", simplu: "Lechinta", comuna: "Calinesti-Oas" },
  { nume: "Lelei", comuna: "Hodod" },
  { nume: "Lipău", simplu: "Lipau", comuna: "Culciu" },
  { nume: "Livada Mică", simplu: "Livada Mica", comuna: "Livada" },
  { nume: "Livada" },
  { nume: "Lucăceni", simplu: "Lucaceni", comuna: "Berveni" },
  { nume: "Luna", comuna: "Negresti-Oas" },
  { nume: "Lunca Apei", comuna: "Apa" },
  { nume: "Mădăras", simplu: "Madaras", comuna: "Ardud" },
  { nume: "Măriuș", simplu: "Marius", comuna: "Valea Vinului" },
  { nume: "Marna Nouă", simplu: "Marna Noua", comuna: "Sanislau" },
  { nume: "Mărtinești", simplu: "Martinesti", comuna: "Odoreu" },
  { nume: "Medieș Râturi", simplu: "Medies Raturi", comuna: "Mediesu Aurit" },
  { nume: "Medieș Vii", simplu: "Medies Vii", comuna: "Mediesu Aurit" },
  { nume: "Medieșu Aurit", simplu: "Mediesu Aurit" },
  { nume: "Medișa", simplu: "Medisa", comuna: "Viile Satu Mare" },
  { nume: "Mesteacăn", simplu: "Mesteacan", comuna: "Halmeu" },
  { nume: "Micula Nouă", simplu: "Micula Noua", comuna: "Micula" },
  { nume: "Micula" },
  { nume: "Mihăieni", simplu: "Mihaieni", comuna: "Acis" },
  { nume: "Moftinu Mare", comuna: "Moftin" },
  { nume: "Moftinu Mic", comuna: "Moftin" },
  { nume: "Moișeni", simplu: "Moiseni", comuna: "Certeze" },
  { nume: "Nadișu Hododului", simplu: "Nadisu Hododului", comuna: "Hodod" },
  { nume: "Necopoi", comuna: "Homoroade" },
  { nume: "Negrești-Oaș", simplu: "Negresti-Oas" },
  { nume: "Nisipeni", comuna: "Lazuri" },
  { nume: "Noroieni", comuna: "Lazuri" },
  { nume: "Oar", comuna: "Vetis" },
  { nume: "Odoreu" },
  { nume: "Orașu Nou-Vii", simplu: "Orasu Nou-Vii", comuna: "Orasu Nou" },
  { nume: "Orașu Nou", simplu: "Orasu Nou" },
  { nume: "Orbău", simplu: "Orbau", comuna: "Cehal" },
  { nume: "Pășunea Mare", simplu: "Pasunea Mare", comuna: "Calinesti-Oas" },
  { nume: "Păulești", simplu: "Paulesti" },
  { nume: "Paulian", comuna: "Doba" },
  { nume: "Peleș", simplu: "Peles", comuna: "Lazuri" },
  { nume: "Pelișor", simplu: "Pelisor", comuna: "Lazuri" },
  { nume: "Petea", comuna: "Dorolt" },
  { nume: "Petin", comuna: "Paulesti" },
  { nume: "Petrești", simplu: "Petresti" },
  { nume: "Pir" },
  { nume: "Piru Nou", comuna: "Pir" },
  { nume: "Pișcari", simplu: "Piscari", comuna: "Terebesti" },
  { nume: "Pișcolt", simplu: "Piscolt" },
  { nume: "Poiana Codrului", comuna: "Crucisor" },
  { nume: "Pomi" },
  { nume: "Portița", simplu: "Portita", comuna: "Tiream" },
  { nume: "Porumbești", simplu: "Porumbesti", comuna: "Halmeu" },
  { nume: "Potău", simplu: "Potau", comuna: "Mediesu Aurit" },
  { nume: "Prilog Vii", comuna: "Orasu Nou" },
  { nume: "Prilog", comuna: "Orasu Nou" },
  { nume: "Racova", comuna: "Supur" },
  { nume: "Racșa Vii", simplu: "Racsa Vii", comuna: "Orasu Nou" },
  { nume: "Racșa", simplu: "Racsa", comuna: "Orasu Nou" },
  { nume: "Rădulești", simplu: "Radulesti", comuna: "Cauas" },
  { nume: "Rătești", simplu: "Ratesti", comuna: "Beltiug" },
  { nume: "Rațiu", simplu: "Ratiu", comuna: "Tasnad" },
  { nume: "Remetea Oașului", simplu: "Remetea Oasului", comuna: "Orasu Nou" },
  { nume: "Resighea", comuna: "Piscolt" },
  { nume: "Românești", simplu: "Romanesti", comuna: "Mediesu Aurit" },
  { nume: "Roșiori", simplu: "Rosiori", comuna: "Valea Vinului" },
  { nume: "Rușeni", simplu: "Ruseni", comuna: "Paulesti" },
  { nume: "Săcășeni", simplu: "Sacaseni" },
  { nume: "Sâi", simplu: "Sai", comuna: "Valea Vinului" },
  { nume: "Șandra", simplu: "Sandra", comuna: "Beltiug" },
  { nume: "Sanislău", simplu: "Sanislau" },
  { nume: "Sânmiclăuș", simplu: "Sanmiclaus", comuna: "Moftin" },
  { nume: "Santău", simplu: "Santau" },
  { nume: "Sărătura", simplu: "Saratura", comuna: "Ardud" },
  { nume: "Sărăuad", simplu: "Sarauad", comuna: "Tasnad" },
  { nume: "Sărvăzel", simplu: "Sarvazel", comuna: "Pir" },
  { nume: "Sătmărel", simplu: "Satmarel", comuna: "Satu Mare" },
  { nume: "Satu Mare" },
  { nume: "Satu Mic", comuna: "Craidorolt" },
  { nume: "Săuca", simplu: "Sauca" },
  { nume: "Scărișoara Nouă", simplu: "Scarisoara Noua", comuna: "Piscolt" },
  { nume: "Sechereșa", simplu: "Secheresa", comuna: "Supur" },
  { nume: "Ser", comuna: "Bogdand" },
  { nume: "Silvaș", simplu: "Silvas", comuna: "Sauca" },
  { nume: "Șirlău", simplu: "Sirlau", comuna: "Batarci" },
  { nume: "Socond" },
  { nume: "Soconzel", comuna: "Socond" },
  { nume: "Solduba", comuna: "Homoroade" },
  { nume: "Someșeni", simplu: "Someseni", comuna: "Apa" },
  { nume: "Stâna", simplu: "Stana", comuna: "Socond" },
  { nume: "Sudurău", simplu: "Sudurau", comuna: "Santau" },
  { nume: "Supuru de Jos", comuna: "Supur" },
  { nume: "Supuru de Sus", comuna: "Supur" },
  { nume: "Tămășeni", simplu: "Tamaseni", comuna: "Batarci" },
  { nume: "Tarna Mare" },
  { nume: "Târșolț", simplu: "Tarsolt" },
  { nume: "Tășnad", simplu: "Tasnad" },
  { nume: "Tătărești", simplu: "Tataresti", comuna: "Viile Satu Mare" },
  { nume: "Țeghea", simplu: "Teghea", comuna: "Craidorolt" },
  { nume: "Terebești", simplu: "Terebesti" },
  { nume: "Tireac", comuna: "Viile Satu Mare" },
  { nume: "Tiream" },
  { nume: "Traian", comuna: "Doba" },
  { nume: "Trip", comuna: "Bixad" },
  { nume: "Tur", comuna: "Negresti-Oas" },
  { nume: "Turț Băi", simplu: "Turt Bai", comuna: "Turt" },
  { nume: "Turț", simplu: "Turt" },
  { nume: "Turulung Vii", comuna: "Turulung" },
  { nume: "Turulung" },
  { nume: "Unimăt", simplu: "Unimat", comuna: "Acis" },
  { nume: "Urziceni Pădure", simplu: "Urziceni Padure", comuna: "Urziceni" },
  { nume: "Urziceni" },
  { nume: "Văgaș", simplu: "Vagas", comuna: "Tarna Mare" },
  { nume: "Valea Morii", comuna: "Tasnad" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Tarna Mare" },
  { nume: "Valea Vinului" },
  { nume: "Vama" },
  { nume: "Vânătorești", simplu: "Vanatoresti", comuna: "Odoreu" },
  { nume: "Vetiș", simplu: "Vetis" },
  { nume: "Vezendiu", comuna: "Tiream" },
  { nume: "Viile Satu Mare" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Sanislau" },
];
