export const sm = [
  { nume: "Andrid" },
  { nume: "Apa" },
  { nume: "Ardud" },
  { nume: "Beltiug" },
  { nume: "Berveni" },
  { nume: "Bixad" },
  { nume: "Bogdand" },
  { nume: "Botiz" },
  { nume: "Batarci" },
  { nume: "Carei" },
  { nume: "Cehal" },
  { nume: "Certeze" },
  { nume: "Craidorolt" },
  { nume: "Crucisor" },
  { nume: "Calinesti-Oas" },
  { nume: "Camin" },
  { nume: "Camarzana" },
  { nume: "Capleni" },
  { nume: "Cauas" },
  { nume: "Doba" },
  { nume: "Dorolt" },
  { nume: "Foieni" },
  { nume: "Gherta Mica" },
  { nume: "Halmeu" },
  { nume: "Hodod" },
  { nume: "Lazuri" },
  { nume: "Livada" },
  { nume: "Mediesu Aurit" },
  { nume: "Micula" },
  { nume: "Negresti-Oas" },
  { nume: "Odoreu" },
  { nume: "Orasu Nou" },
  { nume: "Petresti" },
  { nume: "Pir" },
  { nume: "Piscolt" },
  { nume: "Pomi" },
  { nume: "Paulesti" },
  { nume: "Sanislau" },
  { nume: "Santau" },
  { nume: "Satu Mare" },
  { nume: "Socond" },
  { nume: "Sacaseni" },
  { nume: "Sauca" },
  { nume: "Tarna Mare" },
  { nume: "Terebesti" },
  { nume: "Tiream" },
  { nume: "Turulung" },
  { nume: "Turt" },
  { nume: "Tarsolt" },
  { nume: "Tasnad" },
  { nume: "Urziceni" },
  { nume: "Valea Vinului" },
  { nume: "Vama" },
  { nume: "Vetis" },
  { nume: "Viile Satu Mare" },
  { nume: "Acas", comuna: "Acis" },
  { nume: "Ganas", comuna: "Acis" },
  { nume: "Mihaieni", comuna: "Acis" },
  { nume: "Unimat", comuna: "Acis" },
  { nume: "Dindesti", comuna: "Andrid" },
  { nume: "Irina", comuna: "Andrid" },
  { nume: "Lunca Apei", comuna: "Apa" },
  { nume: "Someseni", comuna: "Apa" },
  { nume: "Ardud-Vii", comuna: "Ardud" },
  { nume: "Baba Novac", comuna: "Ardud" },
  { nume: "Gerausa", comuna: "Ardud" },
  { nume: "Madaras", comuna: "Ardud" },
  { nume: "Saratura", comuna: "Ardud" },
  { nume: "Barsau de Jos", comuna: "Barsau" },
  { nume: "Barsau de Sus", comuna: "Barsau" },
  { nume: "Comlausa", comuna: "Batarci" },
  { nume: "Tamaseni", comuna: "Batarci" },
  { nume: "Sirlau", comuna: "Batarci" },
  { nume: "Bolda", comuna: "Beltiug" },
  { nume: "Ghirisa", comuna: "Beltiug" },
  { nume: "Giungi", comuna: "Beltiug" },
  { nume: "Ratesti", comuna: "Beltiug" },
  { nume: "Sandra", comuna: "Beltiug" },
  { nume: "Lucaceni", comuna: "Berveni" },
  { nume: "Boinesti", comuna: "Bixad" },
  { nume: "Trip", comuna: "Bixad" },
  { nume: "Babta", comuna: "Bogdand" },
  { nume: "Corund", comuna: "Bogdand" },
  { nume: "Ser", comuna: "Bogdand" },
  { nume: "Agris", comuna: "Botiz" },
  { nume: "Ciuperceni", comuna: "Botiz" },
  { nume: "Coca", comuna: "Calinesti-Oas" },
  { nume: "Lechinta", comuna: "Calinesti-Oas" },
  { nume: "Pasunea Mare", comuna: "Calinesti-Oas" },
  { nume: "Ianculesti", comuna: "Carei" },
  { nume: "Ady Endre", comuna: "Cauas" },
  { nume: "Ghenci", comuna: "Cauas" },
  { nume: "Ghilesti", comuna: "Cauas" },
  { nume: "Hotoan", comuna: "Cauas" },
  { nume: "Radulesti", comuna: "Cauas" },
  { nume: "Cehalut", comuna: "Cehal" },
  { nume: "Orbau", comuna: "Cehal" },
  { nume: "Huta Certeze", comuna: "Certeze" },
  { nume: "Moiseni", comuna: "Certeze" },
  { nume: "Criseni", comuna: "Craidorolt" },
  { nume: "Eriu Sancrai", comuna: "Craidorolt" },
  { nume: "Satu Mic", comuna: "Craidorolt" },
  { nume: "Teghea", comuna: "Craidorolt" },
  { nume: "Iegheriste", comuna: "Crucisor" },
  { nume: "Poiana Codrului", comuna: "Crucisor" },
  { nume: "Apateu", comuna: "Culciu" },
  { nume: "Corod", comuna: "Culciu" },
  { nume: "Culciu Mare", comuna: "Culciu" },
  { nume: "Culciu Mic", comuna: "Culciu" },
  { nume: "Caraseu", comuna: "Culciu" },
  { nume: "Lipau", comuna: "Culciu" },
  { nume: "Boghis", comuna: "Doba" },
  { nume: "Dacia", comuna: "Doba" },
  { nume: "Paulian", comuna: "Doba" },
  { nume: "Traian", comuna: "Doba" },
  { nume: "Atea", comuna: "Dorolt" },
  { nume: "Dara", comuna: "Dorolt" },
  { nume: "Petea", comuna: "Dorolt" },
  { nume: "Babesti", comuna: "Halmeu" },
  { nume: "Cidreag", comuna: "Halmeu" },
  { nume: "Dobolt", comuna: "Halmeu" },
  { nume: "Halmeu Vii", comuna: "Halmeu" },
  { nume: "Mesteacan", comuna: "Halmeu" },
  { nume: "Porumbesti", comuna: "Halmeu" },
  { nume: "Giurtelecu Hododului", comuna: "Hodod" },
  { nume: "Lelei", comuna: "Hodod" },
  { nume: "Nadisu Hododului", comuna: "Hodod" },
  { nume: "Chilia", comuna: "Homoroade" },
  { nume: "Homorodu de Jos", comuna: "Homoroade" },
  { nume: "Homorodu de Mijloc", comuna: "Homoroade" },
  { nume: "Homorodu de Sus", comuna: "Homoroade" },
  { nume: "Necopoi", comuna: "Homoroade" },
  { nume: "Solduba", comuna: "Homoroade" },
  { nume: "Bercu", comuna: "Lazuri" },
  { nume: "Nisipeni", comuna: "Lazuri" },
  { nume: "Noroieni", comuna: "Lazuri" },
  { nume: "Peles", comuna: "Lazuri" },
  { nume: "Pelisor", comuna: "Lazuri" },
  { nume: "Adrian", comuna: "Livada" },
  { nume: "Dumbrava", comuna: "Livada" },
  { nume: "Livada Mica", comuna: "Livada" },
  { nume: "Babasesti", comuna: "Mediesu Aurit" },
  { nume: "Iojib", comuna: "Mediesu Aurit" },
  { nume: "Medies Raturi", comuna: "Mediesu Aurit" },
  { nume: "Medies Vii", comuna: "Mediesu Aurit" },
  { nume: "Potau", comuna: "Mediesu Aurit" },
  { nume: "Romanesti", comuna: "Mediesu Aurit" },
  { nume: "Bercu Nou", comuna: "Micula" },
  { nume: "Micula Noua", comuna: "Micula" },
  { nume: "Domanesti", comuna: "Moftin" },
  { nume: "Ghilvaci", comuna: "Moftin" },
  { nume: "Ghirolt", comuna: "Moftin" },
  { nume: "Istrau", comuna: "Moftin" },
  { nume: "Moftinu Mare", comuna: "Moftin" },
  { nume: "Moftinu Mic", comuna: "Moftin" },
  { nume: "Sanmiclaus", comuna: "Moftin" },
  { nume: "Luna", comuna: "Negresti-Oas" },
  { nume: "Tur", comuna: "Negresti-Oas" },
  { nume: "Berindan", comuna: "Odoreu" },
  { nume: "Cucu", comuna: "Odoreu" },
  { nume: "Eteni", comuna: "Odoreu" },
  { nume: "Martinesti", comuna: "Odoreu" },
  { nume: "Vanatoresti", comuna: "Odoreu" },
  { nume: "Orasu Nou-Vii", comuna: "Orasu Nou" },
  { nume: "Prilog", comuna: "Orasu Nou" },
  { nume: "Prilog Vii", comuna: "Orasu Nou" },
  { nume: "Racsa", comuna: "Orasu Nou" },
  { nume: "Racsa Vii", comuna: "Orasu Nou" },
  { nume: "Remetea Oasului", comuna: "Orasu Nou" },
  { nume: "Amati", comuna: "Paulesti" },
  { nume: "Ambud", comuna: "Paulesti" },
  { nume: "Hrip", comuna: "Paulesti" },
  { nume: "Petin", comuna: "Paulesti" },
  { nume: "Ruseni", comuna: "Paulesti" },
  { nume: "Dindestiu Mic", comuna: "Petresti" },
  { nume: "Piru Nou", comuna: "Pir" },
  { nume: "Sarvazel", comuna: "Pir" },
  { nume: "Resighea", comuna: "Piscolt" },
  { nume: "Scarisoara Noua", comuna: "Piscolt" },
  { nume: "Aciua", comuna: "Pomi" },
  { nume: "Bicau", comuna: "Pomi" },
  { nume: "Borlesti", comuna: "Pomi" },
  { nume: "Chegea", comuna: "Sacaseni" },
  { nume: "Berea", comuna: "Sanislau" },
  { nume: "Ciumesti", comuna: "Sanislau" },
  { nume: "Horea", comuna: "Sanislau" },
  { nume: "Marna Noua", comuna: "Sanislau" },
  { nume: "Viisoara", comuna: "Sanislau" },
  { nume: "Chereusa", comuna: "Santau" },
  { nume: "Sudurau", comuna: "Santau" },
  { nume: "Satmarel", comuna: "Satu Mare" },
  { nume: "Becheni", comuna: "Sauca" },
  { nume: "Cean", comuna: "Sauca" },
  { nume: "Chisau", comuna: "Sauca" },
  { nume: "Silvas", comuna: "Sauca" },
  { nume: "Cuta", comuna: "Socond" },
  { nume: "Hodisa", comuna: "Socond" },
  { nume: "Soconzel", comuna: "Socond" },
  { nume: "Stana", comuna: "Socond" },
  { nume: "Dobra", comuna: "Supur" },
  { nume: "Giorocuta", comuna: "Supur" },
  { nume: "Hurezu Mare", comuna: "Supur" },
  { nume: "Racova", comuna: "Supur" },
  { nume: "Secheresa", comuna: "Supur" },
  { nume: "Supuru de Jos", comuna: "Supur" },
  { nume: "Supuru de Sus", comuna: "Supur" },
  { nume: "Bocicau", comuna: "Tarna Mare" },
  { nume: "Valea Seaca", comuna: "Tarna Mare" },
  { nume: "Vagas", comuna: "Tarna Mare" },
  { nume: "Aliceni", comuna: "Tarsolt" },
  { nume: "Blaja", comuna: "Tasnad" },
  { nume: "Cig", comuna: "Tasnad" },
  { nume: "Ratiu", comuna: "Tasnad" },
  { nume: "Sarauad", comuna: "Tasnad" },
  { nume: "Valea Morii", comuna: "Tasnad" },
  { nume: "Aliza", comuna: "Terebesti" },
  { nume: "Gelu", comuna: "Terebesti" },
  { nume: "Piscari", comuna: "Terebesti" },
  { nume: "Portita", comuna: "Tiream" },
  { nume: "Vezendiu", comuna: "Tiream" },
  { nume: "Gherta Mare", comuna: "Turt" },
  { nume: "Turt Bai", comuna: "Turt" },
  { nume: "Draguseni", comuna: "Turulung" },
  { nume: "Turulung Vii", comuna: "Turulung" },
  { nume: "Urziceni Padure", comuna: "Urziceni" },
  { nume: "Marius", comuna: "Valea Vinului" },
  { nume: "Rosiori", comuna: "Valea Vinului" },
  { nume: "Sai", comuna: "Valea Vinului" },
  { nume: "Decebal", comuna: "Vetis" },
  { nume: "Oar", comuna: "Vetis" },
  { nume: "Cionchesti", comuna: "Viile Satu Mare" },
  { nume: "Medisa", comuna: "Viile Satu Mare" },
  { nume: "Tireac", comuna: "Viile Satu Mare" },
  { nume: "Tataresti", comuna: "Viile Satu Mare" },
];
