export const sj = [
  { nume: "Adalin", comuna: "Dragu" },
  { nume: "Aghireş", simplu: "Aghires", comuna: "Mesesenii De Jos" },
  { nume: "Agrij" },
  { nume: "Aleuş", simplu: "Aleus", comuna: "Halmasd" },
  { nume: "Almaşu", simplu: "Almasu" },
  { nume: "Aluniş", simplu: "Alunis", comuna: "Benesat" },
  { nume: "Archid", comuna: "Coseiu" },
  { nume: "Băbeni", simplu: "Babeni" },
  { nume: "Băbiu", simplu: "Babiu", comuna: "Almasu" },
  { nume: "Bădăcin", simplu: "Badacin", comuna: "Pericei" },
  { nume: "Badon", comuna: "Hereclean" },
  { nume: "Baica", comuna: "Hida" },
  { nume: "Bălan", simplu: "Balan" },
  { nume: "Ban", comuna: "Banisor" },
  { nume: "Bănişor", simplu: "Banisor" },
  { nume: "Bârsa", simplu: "Barsa", comuna: "Somes-Odorhei" },
  { nume: "Bârsău Mare", simplu: "Barsau Mare", comuna: "Galgau" },
  { nume: "Bârsăuţa", simplu: "Barsauta", comuna: "Ileanda" },
  { nume: "Benesat" },
  { nume: "Bercea", comuna: "Sanmihaiu Almasului" },
  { nume: "Bezded", comuna: "Garbou" },
  { nume: "Bic", comuna: "Simleu Silvaniei" },
  { nume: "Bilghez", comuna: "Nusfalau" },
  { nume: "Biuşa", simplu: "Biusa", comuna: "Benesat" },
  { nume: "Bizuşa Băi", simplu: "Bizusa Bai", comuna: "Ileanda" },
  { nume: "Bobota" },
  { nume: "Bocşa", simplu: "Bocsa" },
  { nume: "Bocşiţa", simplu: "Bocsita", comuna: "Hereclean" },
  { nume: "Bodia", comuna: "Buciumi" },
  { nume: "Bogdana", comuna: "Buciumi" },
  { nume: "Boghiş", simplu: "Boghis", comuna: "Nusfalau" },
  { nume: "Borla", comuna: "Bocsa" },
  { nume: "Borza", comuna: "Creaca" },
  { nume: "Bozieş", simplu: "Bozies", comuna: "Nusfalau" },
  { nume: "Bozna", comuna: "Treznea" },
  { nume: "Brâglez", simplu: "Braglez", comuna: "Surduc" },
  { nume: "Brebi", comuna: "Creaca" },
  { nume: "Brusturi", comuna: "Creaca" },
  { nume: "Buciumi" },
  { nume: "Bulgari", comuna: "Salatig" },
  { nume: "Buzaş", simplu: "Buzas", comuna: "Rus" },
  { nume: "Călacea", simplu: "Calacea", comuna: "Garbou" },
  { nume: "Camăr", simplu: "Camar" },
  { nume: "Câmpia", simplu: "Campia", comuna: "Bocsa" },
  { nume: "Căpâlna", simplu: "Capalna", comuna: "Galgau" },
  { nume: "Carastelec" },
  { nume: "Ceaca", comuna: "Zalha" },
  { nume: "Cehei", comuna: "Simleu Silvaniei" },
  { nume: "Cehu Silvaniei" },
  { nume: "Cerişa", simplu: "Cerisa", comuna: "Halmasd" },
  { nume: "Cernuc", comuna: "Garbou" },
  { nume: "Chechiş", simplu: "Chechis", comuna: "Balan" },
  { nume: "Chendrea", comuna: "Balan" },
  { nume: "Chendremal", comuna: "Zimbor" },
  { nume: "Cheud", comuna: "Napradea" },
  { nume: "Chichişa", simplu: "Chichisa", comuna: "Romanasi" },
  { nume: "Chieşd", simplu: "Chiesd" },
  { nume: "Chilioara", comuna: "Coseiu" },
  { nume: "Chizeni", comuna: "Galgau" },
  { nume: "Ciglean", comuna: "Creaca" },
  { nume: "Ciocmani", comuna: "Babeni" },
  { nume: "Ciula", comuna: "Letca" },
  { nume: "Ciumărna", simplu: "Ciumarna", comuna: "Romanasi" },
  { nume: "Ciureni", comuna: "Zalha" },
  { nume: "Cizer" },
  { nume: "Cliţ", simplu: "Clit", comuna: "Babeni" },
  { nume: "Colonia Sighetu Silvaniei", comuna: "Chiesd" },
  { nume: "Cormeniş", simplu: "Cormenis", comuna: "Lozna" },
  { nume: "Coşeiu", simplu: "Coseiu" },
  { nume: "Cosniciu de Jos", comuna: "Ip" },
  { nume: "Cosniciu de Sus", comuna: "Ip" },
  { nume: "Cozla", comuna: "Letca" },
  { nume: "Crasna" },
  { nume: "Creaca" },
  { nume: "Crişeni", simplu: "Criseni" },
  { nume: "Criştelec", simplu: "Cristelec", comuna: "Maeriste" },
  { nume: "Cristolţ", simplu: "Cristolt" },
  { nume: "Cristolţel", simplu: "Cristoltel", comuna: "Surduc" },
  { nume: "Cristur Crişeni", simplu: "Cristur Criseni", comuna: "Criseni" },
  { nume: "Cubleşu", simplu: "Cublesu", comuna: "Cuzaplac" },
  { nume: "Cuceu", comuna: "Jibou" },
  { nume: "Cuciulat", comuna: "Letca" },
  { nume: "Cutiş", simplu: "Cutis", comuna: "Almasu" },
  { nume: "Cuzăplac", simplu: "Cuzaplac" },
  { nume: "Dăbâceni", simplu: "Dabaceni", comuna: "Ileanda" },
  { nume: "Deja", comuna: "Salatig" },
  { nume: "Deleni", comuna: "Dobrin" },
  { nume: "Derşida", simplu: "Dersida", comuna: "Bobota" },
  { nume: "Dioşod", simplu: "Diosod", comuna: "Hereclean" },
  { nume: "Doba", comuna: "Dobrin" },
  { nume: "Dobrin" },
  { nume: "Dobrocina", comuna: "Galgau" },
  { nume: "Doh", comuna: "Maeriste" },
  { nume: "Dolheni", comuna: "Ileanda" },
  { nume: "Dolu", comuna: "Zimbor" },
  { nume: "Domnin", comuna: "Somes-Odorhei" },
  { nume: "Dragu" },
  { nume: "Drighiu", comuna: "Halmasd" },
  { nume: "Dumuslău", simplu: "Dumuslau", comuna: "Carastelec" },
  { nume: "Fabrica", comuna: "Garbou" },
  { nume: "Făgetu", simplu: "Fagetu", comuna: "Plopis" },
  { nume: "Fălcuşa", simplu: "Falcusa", comuna: "Poiana Blenchii" },
  { nume: "Fântânele Rus", simplu: "Fantanele Rus", comuna: "Rus" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Dragu" },
  { nume: "Fetindia", comuna: "Mesesenii De Jos" },
  { nume: "Fildu de Jos" },
  { nume: "Fildu de Mijloc", comuna: "Fildu De Jos" },
  { nume: "Fildu de Sus", comuna: "Fildu De Jos" },
  { nume: "Firminiş", simplu: "Firminis", comuna: "Mirsid" },
  { nume: "Fizeş", simplu: "Fizes", comuna: "Sag" },
  { nume: "Fodora", comuna: "Galgau" },
  {
    nume: "Frâncenii de Piatră",
    simplu: "Francenii de Piatra",
    comuna: "Galgau",
  },
  { nume: "Fufez", comuna: "Halmasd" },
  { nume: "Gălăşeni", simplu: "Galaseni", comuna: "Cuzaplac" },
  { nume: "Gâlgău Almaşului", simplu: "Galgau Almasului", comuna: "Balan" },
  { nume: "Gâlgău", simplu: "Galgau" },
  { nume: "Gălpâia", simplu: "Galpaia", comuna: "Balan" },
  { nume: "Gârbou", simplu: "Garbou" },
  { nume: "Gârceiu", simplu: "Garceiu", comuna: "Criseni" },
  {
    nume: "Giurtelecu Şimleului",
    simplu: "Giurtelecu Simleului",
    comuna: "Maeriste",
  },
  { nume: "Glod", comuna: "Galgau" },
  { nume: "Gostila", comuna: "Poiana Blenchii" },
  { nume: "Gura Vlădesei", simplu: "Gura Vladesei", comuna: "Galgau" },
  { nume: "Guruslău", simplu: "Guruslau", comuna: "Hereclean" },
  { nume: "Halmăşd", simplu: "Halmasd" },
  { nume: "Hăşmaş", simplu: "Hasmas", comuna: "Simisna" },
  { nume: "Hereclean" },
  { nume: "Hida" },
  { nume: "Horoatu Cehului", comuna: "Cehu Silvaniei" },
  { nume: "Horoatu Crasnei" },
  { nume: "Hurez", comuna: "Horoatu Crasnei" },
  { nume: "Huseni", comuna: "Crasna" },
  { nume: "Husia", comuna: "Jibou" },
  { nume: "Huta", comuna: "Buciumi" },
  { nume: "Iaz", comuna: "Plopis" },
  { nume: "Ileanda" },
  { nume: "Ilişua", simplu: "Ilisua", comuna: "Sarmasag" },
  { nume: "Inău", simplu: "Inau", comuna: "Somes-Odorhei" },
  { nume: "Ip" },
  { nume: "Jac", comuna: "Creaca" },
  { nume: "Jebucu", comuna: "Almasu" },
  { nume: "Jibou" },
  { nume: "Lazuri", comuna: "Valcau De Jos" },
  { nume: "Lemniu", comuna: "Letca" },
  { nume: "Leşmir", simplu: "Lesmir", comuna: "Marca" },
  { nume: "Letca" },
  { nume: "Lompirt", comuna: "Sarmasag" },
  { nume: "Lozna" },
  { nume: "Luminişu", simplu: "Luminisu", comuna: "Ileanda" },
  { nume: "Lupoaia", comuna: "Creaca" },
  { nume: "Măerişte", simplu: "Maeriste" },
  { nume: "Măgura", simplu: "Magura", comuna: "Poiana Blenchii" },
  { nume: "Mal", comuna: "Sag" },
  { nume: "Mălădia", simplu: "Maladia", comuna: "Maeriste" },
  { nume: "Măleni", simplu: "Maleni", comuna: "Ileanda" },
  { nume: "Marca Huta", comuna: "Marca" },
  { nume: "Marca" },
  { nume: "Marin", comuna: "Crasna" },
  { nume: "Meseşenii de Jos", simplu: "Mesesenii de Jos" },
  {
    nume: "Meseşenii de Sus",
    simplu: "Mesesenii de Sus",
    comuna: "Mesesenii De Jos",
  },
  { nume: "Mesteacănu", simplu: "Mesteacanu", comuna: "Almasu" },
  { nume: "Mierţa", simplu: "Mierta", comuna: "Cuzaplac" },
  { nume: "Miluani", comuna: "Hida" },
  { nume: "Mineu", comuna: "Salatig" },
  { nume: "Mirşid", simplu: "Mirsid" },
  { nume: "Moiad", comuna: "Sarmasag" },
  { nume: "Moigrad-Porolissum", comuna: "Mirsid" },
  { nume: "Motiş", simplu: "Motis", comuna: "Cehu Silvaniei" },
  { nume: "Muncel", comuna: "Cristolt" },
  { nume: "Nadiş", simplu: "Nadis", comuna: "Cehu Silvaniei" },
  { nume: "Naimon", comuna: "Dobrin" },
  { nume: "Năpradea", simplu: "Napradea" },
  { nume: "Negreni", comuna: "Ileanda" },
  { nume: "Noţig", simplu: "Notig", comuna: "Salatig" },
  { nume: "Nuşfalău", simplu: "Nusfalau" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Camar" },
  { nume: "Păduriş", simplu: "Paduris", comuna: "Hida" },
  { nume: "Panic", comuna: "Hereclean" },
  { nume: "Păuşa", simplu: "Pausa", comuna: "Romanasi" },
  { nume: "Peceiu", comuna: "Banisor" },
  { nume: "Pericei" },
  { nume: "Periceiu Mic", comuna: "Pericei" },
  { nume: "Perii Vadului", comuna: "Ileanda" },
  { nume: "Petrindu", comuna: "Cuzaplac" },
  { nume: "Petrinzel", comuna: "Almasu" },
  { nume: "Piroşa", simplu: "Pirosa", comuna: "Babeni" },
  { nume: "Plesca", comuna: "Cizer" },
  { nume: "Plopiş", simplu: "Plopis" },
  { nume: "Poarta Sălajului", simplu: "Poarta Salajului", comuna: "Romanasi" },
  { nume: "Podişu", simplu: "Podisu", comuna: "Ileanda" },
  { nume: "Poiana Blenchii" },
  { nume: "Poiana Măgura", simplu: "Poiana Magura", comuna: "Sarmasag" },
  { nume: "Poiana Onţii", simplu: "Poiana Ontii", comuna: "Cristolt" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Babeni" },
  { nume: "Popeni", comuna: "Mirsid" },
  { nume: "Popteleac", comuna: "Garbou" },
  { nume: "Porţ", simplu: "Port", comuna: "Marca" },
  { nume: "Preluci", comuna: "Lozna" },
  { nume: "Preoteasa", comuna: "Valcau De Jos" },
  { nume: "Pria", comuna: "Cizer" },
  { nume: "Prodăneşti", simplu: "Prodanesti", comuna: "Creaca" },
  { nume: "Purcăreţ", simplu: "Purcaret", comuna: "Letca" },
  { nume: "Pusta", comuna: "Simleu Silvaniei" },
  { nume: "Racâş", simplu: "Racas", comuna: "Hida" },
  { nume: "Răstoci", simplu: "Rastoci", comuna: "Ileanda" },
  { nume: "Răstolţ", simplu: "Rastolt", comuna: "Buciumi" },
  { nume: "Răstolţu Deşert", simplu: "Rastoltu Desert", comuna: "Agrij" },
  { nume: "Ratin", comuna: "Crasna" },
  { nume: "Ratovei", comuna: "Valcau De Jos" },
  { nume: "Recea Mică", simplu: "Recea Mica", comuna: "Varsolt" },
  { nume: "Recea", comuna: "Varsolt" },
  { nume: "Rogna", comuna: "Ileanda" },
  { nume: "Românaşi", simplu: "Romanasi" },
  { nume: "Romita", comuna: "Romanasi" },
  { nume: "Rona", comuna: "Jibou" },
  { nume: "Ruginoasa", comuna: "Cuzaplac" },
  { nume: "Rus" },
  { nume: "Sâg", simplu: "Sag" },
  { nume: "Sălăjeni", simplu: "Salajeni", comuna: "Bocsa" },
  { nume: "Sălăţig", simplu: "Salatig" },
  { nume: "Şamşud", simplu: "Samsud" },
  {
    nume: "Sâncraiu Almaşului",
    simplu: "Sancraiu Almasului",
    comuna: "Zimbor",
  },
  {
    nume: "Sâncraiu Silvaniei",
    simplu: "Sancraiu Silvaniei",
    comuna: "Dobrin",
  },
  {
    nume: "Sângeorgiu de Meseş",
    simplu: "Sangeorgiu de Meses",
    comuna: "Buciumi",
  },
  { nume: "Sânmihaiu Almaşului", simplu: "Sanmihaiu Almasului" },
  { nume: "Sânpetru Almaşului", simplu: "Sanpetru Almasului", comuna: "Hida" },
  { nume: "Sântă Măria", simplu: "Santa Maria", comuna: "Sanmihaiu Almasului" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Sag" },
  { nume: "Şărmăşag", simplu: "Sarmasag" },
  { nume: "Şasa", simplu: "Sasa", comuna: "Ileanda" },
  { nume: "Şeredeiu", simplu: "Seredeiu", comuna: "Horoatu Crasnei" },
  { nume: "Sfăraş", simplu: "Sfaras", comuna: "Almasu" },
  { nume: "Sici", comuna: "Pericei" },
  { nume: "Sighetu Silvaniei", comuna: "Chiesd" },
  { nume: "Şimişna", simplu: "Simisna" },
  { nume: "Şimleu Silvaniei", simplu: "Simleu Silvaniei" },
  { nume: "Şoimuş", simplu: "Soimus", comuna: "Somes-Odorhei" },
  { nume: "Şoimuşeni", simplu: "Soimuseni", comuna: "Letca" },
  { nume: "Solomon", comuna: "Garbou" },
  { nume: "Solona", comuna: "Surduc" },
  { nume: "Someş Guruslău", simplu: "Somes Guruslau", comuna: "Napradea" },
  { nume: "Someş-Odorhei", simplu: "Somes-Odorhei" },
  { nume: "Stana", comuna: "Almasu" },
  { nume: "Stâna", simplu: "Stana", comuna: "Zalau" },
  { nume: "Stârciu", simplu: "Starciu", comuna: "Horoatu Crasnei" },
  { nume: "Stoboru", comuna: "Cuzaplac" },
  { nume: "Stupini", comuna: "Hida" },
  { nume: "Sub Cetate", comuna: "Valcau De Jos" },
  { nume: "Şumal", simplu: "Sumal", comuna: "Marca" },
  { nume: "Surduc" },
  { nume: "Sutoru", comuna: "Zimbor" },
  { nume: "Tămasa", simplu: "Tamasa", comuna: "Cuzaplac" },
  { nume: "Ţărmure", simplu: "Tarmure", comuna: "Sarmasag" },
  { nume: "Ţăudu", simplu: "Taudu", comuna: "Almasu" },
  { nume: "Teştioara", simplu: "Testioara", comuna: "Surduc" },
  { nume: "Tetişu", simplu: "Tetisu", comuna: "Fildu De Jos" },
  { nume: "Tihău", simplu: "Tihau", comuna: "Surduc" },
  { nume: "Topliţa", simplu: "Toplita", comuna: "Letca" },
  { nume: "Traniş", simplu: "Tranis", comuna: "Napradea" },
  { nume: "Trestia", comuna: "Hida" },
  { nume: "Treznea" },
  { nume: "Turbuţa", simplu: "Turbuta", comuna: "Surduc" },
  { nume: "Tusa", comuna: "Sag" },
  { nume: "Ugruţiu", simplu: "Ugrutiu", comuna: "Dragu" },
  {
    nume: "Uileacu Şimleului",
    simplu: "Uileacu Simleului",
    comuna: "Maeriste",
  },
  { nume: "Ulciug", comuna: "Cehu Silvaniei" },
  { nume: "Vădurele", simplu: "Vadurele", comuna: "Napradea" },
  { nume: "Valcău de Jos", simplu: "Valcau de Jos" },
  { nume: "Valcău de Sus", simplu: "Valcau de Sus", comuna: "Valcau De Jos" },
  { nume: "Valea Ciurenilor", comuna: "Zalha" },
  { nume: "Valea Hranei", comuna: "Zalha" },
  { nume: "Valea Leşului", simplu: "Valea Lesului", comuna: "Lozna" },
  { nume: "Valea Loznei", comuna: "Lozna" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Zalha" },
  { nume: "Valea Pomilor", comuna: "Samsud" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Cristolt" },
  { nume: "Vălişoara", simplu: "Valisoara", comuna: "Letca" },
  { nume: "Var", comuna: "Jibou" },
  { nume: "Vârşolţ", simplu: "Varsolt" },
  { nume: "Vârteşca", simplu: "Vartesca", comuna: "Zalha" },
  { nume: "Verveghiu", comuna: "Dobrin" },
  { nume: "Viile Jacului", comuna: "Creaca" },
  { nume: "Voivodeni", comuna: "Dragu" },
  { nume: "Zalău", simplu: "Zalau" },
  { nume: "Zalha" },
  { nume: "Zalnoc", comuna: "Bobota" },
  { nume: "Zăuan Băi", simplu: "Zauan Bai", comuna: "Ip" },
  { nume: "Zăuan", simplu: "Zauan", comuna: "Ip" },
  { nume: "Zimbor" },
];
