export const sb = [
  { nume: "Agnita" },
  { nume: "Altina" },
  { nume: "Apoldu de Jos" },
  { nume: "Arpasu de Jos" },
  { nume: "Avrig" },
  { nume: "Axente Sever" },
  { nume: "Atel" },
  { nume: "Bazna" },
  { nume: "Biertan" },
  { nume: "Blajel" },
  { nume: "Brateiu" },
  { nume: "Bruiu" },
  { nume: "Bradeni" },
  { nume: "Chirpar" },
  { nume: "Cisnadie" },
  { nume: "Copsa Mica" },
  { nume: "Cristian" },
  { nume: "Carta" },
  { nume: "Cartisoara" },
  { nume: "Dumbraveni" },
  { nume: "Darlos" },
  { nume: "Gura Raului" },
  { nume: "Hoghilag" },
  { nume: "Iacobeni" },
  { nume: "Jina" },
  { nume: "Laslea" },
  { nume: "Loamnes" },
  { nume: "Ludos" },
  { nume: "Marpod" },
  { nume: "Medias" },
  { nume: "Merghindeal" },
  { nume: "Micasasa" },
  { nume: "Miercurea Sibiului" },
  { nume: "Mihaileni" },
  { nume: "Mosna" },
  { nume: "Nocrich" },
  { nume: "Ocna Sibiului" },
  { nume: "Orlat" },
  { nume: "Poiana Sibiului" },
  { nume: "Poplaca" },
  { nume: "Porumbacu de Jos" },
  { nume: "Pauca" },
  { nume: "Racovita" },
  { nume: "Rosia" },
  { nume: "Rau Sadului" },
  { nume: "Rasinari" },
  { nume: "Sadu" },
  { nume: "Sibiu" },
  { nume: "Slimnic" },
  { nume: "Saliste" },
  { nume: "Tilisca" },
  { nume: "Turnu Rosu" },
  { nume: "Tarnava" },
  { nume: "Talmaciu" },
  { nume: "Valea Viilor" },
  { nume: "Vurpar" },
  { nume: "Seica Mare" },
  { nume: "Seica Mica" },
  { nume: "Selimbar" },
  { nume: "Sura Mare" },
  { nume: "Sura Mica" },
  { nume: "Coves", comuna: "Agnita" },
  { nume: "Ruja", comuna: "Agnita" },
  { nume: "Benesti", comuna: "Altina" },
  { nume: "Ghijasa de Sus", comuna: "Altina" },
  { nume: "Sangatin", comuna: "Apoldu De Jos" },
  { nume: "Arpasu de Sus", comuna: "Arpasu De Jos" },
  { nume: "Noul Roman", comuna: "Arpasu De Jos" },
  { nume: "Alma", comuna: "Atel" },
  { nume: "Dupus", comuna: "Atel" },
  { nume: "Giacas", comuna: "Atel" },
  { nume: "Smig", comuna: "Atel" },
  { nume: "Bradu", comuna: "Avrig" },
  { nume: "Glamboaca", comuna: "Avrig" },
  { nume: "Marsa", comuna: "Avrig" },
  { nume: "Sacadate", comuna: "Avrig" },
  { nume: "Agarbiciu", comuna: "Axente Sever" },
  { nume: "Soala", comuna: "Axente Sever" },
  { nume: "Boian", comuna: "Bazna" },
  { nume: "Velt", comuna: "Bazna" },
  { nume: "Copsa Mare", comuna: "Biertan" },
  { nume: "Richis", comuna: "Biertan" },
  { nume: "Apos", comuna: "Birghis" },
  { nume: "Barghis", comuna: "Birghis" },
  { nume: "Ighisu Vechi", comuna: "Birghis" },
  { nume: "Pelisor", comuna: "Birghis" },
  { nume: "Vecerd", comuna: "Birghis" },
  { nume: "Zlagna", comuna: "Birghis" },
  { nume: "Paucea", comuna: "Blajel" },
  { nume: "Romanesti", comuna: "Blajel" },
  { nume: "Retis", comuna: "Bradeni" },
  { nume: "Teline", comuna: "Bradeni" },
  { nume: "Buzd", comuna: "Brateiu" },
  { nume: "Gherdeal", comuna: "Bruiu" },
  { nume: "Somartin", comuna: "Bruiu" },
  { nume: "Poienita", comuna: "Carta" },
  { nume: "Sasaus", comuna: "Chirpar" },
  { nume: "Veseud", comuna: "Chirpar" },
  { nume: "Vard", comuna: "Chirpar" },
  { nume: "Cisnadioara", comuna: "Cisnadie" },
  { nume: "Curciu", comuna: "Darlos" },
  { nume: "Valea Lunga", comuna: "Darlos" },
  { nume: "Ernea", comuna: "Dumbraveni" },
  { nume: "Saros pe Tarnave", comuna: "Dumbraveni" },
  { nume: "Prod", comuna: "Hoghilag" },
  { nume: "Valchid", comuna: "Hoghilag" },
  { nume: "Movile", comuna: "Iacobeni" },
  { nume: "Netus", comuna: "Iacobeni" },
  { nume: "Noistat", comuna: "Iacobeni" },
  { nume: "Stejarisu", comuna: "Iacobeni" },
  { nume: "Floresti", comuna: "Laslea" },
  { nume: "Malancrav", comuna: "Laslea" },
  { nume: "Nou Sasesc", comuna: "Laslea" },
  { nume: "Roandola", comuna: "Laslea" },
  { nume: "Alamor", comuna: "Loamnes" },
  { nume: "Armeni", comuna: "Loamnes" },
  { nume: "Hasag", comuna: "Loamnes" },
  { nume: "Mandra", comuna: "Loamnes" },
  { nume: "Sadinca", comuna: "Loamnes" },
  { nume: "Gusu", comuna: "Ludos" },
  { nume: "Ilimbav", comuna: "Marpod" },
  { nume: "Ighisu Nou", comuna: "Medias" },
  { nume: "Dealu Frumos", comuna: "Merghindeal" },
  { nume: "Chesler", comuna: "Micasasa" },
  { nume: "Valeni", comuna: "Micasasa" },
  { nume: "Tapu", comuna: "Micasasa" },
  { nume: "Apoldu de Sus", comuna: "Miercurea Sibiului" },
  { nume: "Dobarca", comuna: "Miercurea Sibiului" },
  { nume: "Metis", comuna: "Mihaileni" },
  { nume: "Moardas", comuna: "Mihaileni" },
  { nume: "Ravasel", comuna: "Mihaileni" },
  { nume: "Salcau", comuna: "Mihaileni" },
  { nume: "Alma Vii", comuna: "Mosna" },
  { nume: "Nemsa", comuna: "Mosna" },
  { nume: "Fofeldea", comuna: "Nocrich" },
  { nume: "Ghijasa de Jos", comuna: "Nocrich" },
  { nume: "Hosman", comuna: "Nocrich" },
  { nume: "Tichindeal", comuna: "Nocrich" },
  { nume: "Toparcea", comuna: "Ocna Sibiului" },
  { nume: "Bogatu Roman", comuna: "Pauca" },
  { nume: "Brosteni", comuna: "Pauca" },
  { nume: "Presaca", comuna: "Pauca" },
  { nume: "Colun", comuna: "Porumbacu De Jos" },
  { nume: "Porumbacu de Sus", comuna: "Porumbacu De Jos" },
  { nume: "Scoreiu", comuna: "Porumbacu De Jos" },
  { nume: "Sarata", comuna: "Porumbacu De Jos" },
  { nume: "Sebesu de Sus", comuna: "Racovita" },
  { nume: "Prislop", comuna: "Rasinari" },
  { nume: "Casolt", comuna: "Rosia" },
  { nume: "Cornatel", comuna: "Rosia" },
  { nume: "Daia", comuna: "Rosia" },
  { nume: "Nou", comuna: "Rosia" },
  { nume: "Nucet", comuna: "Rosia" },
  { nume: "Aciliu", comuna: "Saliste" },
  { nume: "Amnas", comuna: "Saliste" },
  { nume: "Crint", comuna: "Saliste" },
  { nume: "Fantanele", comuna: "Saliste" },
  { nume: "Gales", comuna: "Saliste" },
  { nume: "Mag", comuna: "Saliste" },
  { nume: "Sibiel", comuna: "Saliste" },
  { nume: "Sacel", comuna: "Saliste" },
  { nume: "Vale", comuna: "Saliste" },
  { nume: "Boarta", comuna: "Seica Mare" },
  { nume: "Buia", comuna: "Seica Mare" },
  { nume: "Mighindoala", comuna: "Seica Mare" },
  { nume: "Petis", comuna: "Seica Mare" },
  { nume: "Stenea", comuna: "Seica Mare" },
  { nume: "Sorostin", comuna: "Seica Mica" },
  { nume: "Bungard", comuna: "Selimbar" },
  { nume: "Mohu", comuna: "Selimbar" },
  { nume: "Vestem", comuna: "Selimbar" },
  { nume: "Paltinis", comuna: "Sibiu" },
  { nume: "Albi", comuna: "Slimnic" },
  { nume: "Padureni", comuna: "Slimnic" },
  { nume: "Rusi", comuna: "Slimnic" },
  { nume: "Veseud", comuna: "Slimnic" },
  { nume: "Hamba", comuna: "Sura Mare" },
  { nume: "Rusciori", comuna: "Sura Mica" },
  { nume: "Boita", comuna: "Talmaciu" },
  { nume: "Colonia Talmaciu", comuna: "Talmaciu" },
  { nume: "Lazaret", comuna: "Talmaciu" },
  { nume: "Lotrioara", comuna: "Talmaciu" },
  { nume: "Paltin", comuna: "Talmaciu" },
  { nume: "Talmacel", comuna: "Talmaciu" },
  { nume: "Colonia Tarnava", comuna: "Tarnava" },
  { nume: "Rod", comuna: "Tilisca" },
  { nume: "Sebesu de Jos", comuna: "Turnu Rosu" },
  { nume: "Motis", comuna: "Valea Viilor" },
];
