export const sv = [
  { nume: "Adâncata", simplu: "Adancata" },
  { nume: "Antoceni", comuna: "Forasti" },
  { nume: "Arbore" },
  { nume: "Argel", comuna: "Moldovita" },
  { nume: "Argestru", comuna: "Vatra Dornei" },
  { nume: "Arghira", comuna: "Preutesti" },
  { nume: "Arțari", simplu: "Artari", comuna: "Hantesti" },
  { nume: "Bădeuți", simplu: "Badeuti", comuna: "Milisauti" },
  { nume: "Badragi", comuna: "Zamostea" },
  { nume: "Bahna Arin", comuna: "Preutesti" },
  { nume: "Baia" },
  { nume: "Baineț", simplu: "Bainet", comuna: "Musenita" },
  { nume: "Băișești", simplu: "Baisesti", comuna: "Cornu Luncii" },
  { nume: "Bălăceana", simplu: "Balaceana", comuna: "Ciprian Porumbescu" },
  { nume: "Bălcăuți", simplu: "Balcauti" },
  { nume: "Bălinești", simplu: "Balinesti", comuna: "Gramesti" },
  { nume: "Băncești", simplu: "Bancesti", comuna: "Musenita" },
  { nume: "Bănești", simplu: "Banesti", comuna: "Fantanele" },
  { nume: "Bărăști", simplu: "Barasti", comuna: "Boroaia" },
  { nume: "Basarabi", comuna: "Preutesti" },
  { nume: "Benia", comuna: "Moldova-Sulita" },
  { nume: "Berchișești", simplu: "Berchisesti", comuna: "Dragoiesti" },
  { nume: "Berești", simplu: "Beresti", comuna: "Hantesti" },
  { nume: "Bilca" },
  { nume: "Bivolăria", simplu: "Bivolaria", comuna: "Vicovu De Sus" },
  { nume: "Bobeica", comuna: "Izvoarele Sucevei" },
  { nume: "Bodnăreni", simplu: "Bodnareni", comuna: "Arbore" },
  { nume: "Bogata", comuna: "Baia" },
  { nume: "Bogdănești", simplu: "Bogdanesti" },
  { nume: "Boroaia" },
  { nume: "Bosanci" },
  { nume: "Botești", simplu: "Botesti", comuna: "Horodniceni" },
  { nume: "Botoș", simplu: "Botos", comuna: "Ciocanesti" },
  { nume: "Botoșana", simplu: "Botosana" },
  {
    nume: "Botoșanița Mare",
    simplu: "Botosanita Mare",
    comuna: "Calafindesti",
  },
  { nume: "Botoșanița Mică", simplu: "Botosanita Mica", comuna: "Gramesti" },
  { nume: "Botuș", simplu: "Botus", comuna: "Fundu Moldovei" },
  { nume: "Botușel", simplu: "Botusel", comuna: "Fundu Moldovei" },
  { nume: "Boura", comuna: "Forasti" },
  { nume: "Brădățel", simplu: "Bradatel", comuna: "Horodniceni" },
  { nume: "Brăiești", simplu: "Braiesti", comuna: "Cornu Luncii" },
  { nume: "Braniștea", simplu: "Branistea", comuna: "Fundu Moldovei" },
  { nume: "Brașca", simplu: "Brasca", comuna: "Ciprian Porumbescu" },
  { nume: "Breaza de Sus", comuna: "Breaza" },
  { nume: "Breaza" },
  { nume: "Brodina de Jos", comuna: "Brodina" },
  { nume: "Brodina" },
  { nume: "Brodina", comuna: "Izvoarele Sucevei" },
  { nume: "Broșteni", simplu: "Brosteni" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Draguseni" },
  { nume: "Bucșoaia", simplu: "Bucsoaia", comuna: "Frasin" },
  { nume: "Buda", comuna: "Rasca" },
  { nume: "Buda", comuna: "Zvoristea" },
  { nume: "Budeni", comuna: "Dolhasca" },
  { nume: "Bulai", comuna: "Moara" },
  { nume: "Bunești", simplu: "Bunesti" },
  { nume: "Burla", comuna: "Volovat" },
  { nume: "Bursuceni", comuna: "Veresti" },
  { nume: "Cacica" },
  { nume: "Cajvana" },
  { nume: "Calafindești", simplu: "Calafindesti" },
  {
    nume: "Călinești-Vasilache",
    simplu: "Calinesti-Vasilache",
    comuna: "Darmanesti",
  },
  { nume: "Călinești", simplu: "Calinesti", comuna: "Darmanesti" },
  { nume: "Călinești", simplu: "Calinesti", comuna: "Serbauti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Adancata" },
  { nume: "Cămârzani", simplu: "Camarzani", comuna: "Vadu Moldovei" },
  { nume: "Câmpulung Moldovenesc", simplu: "Campulung Moldovenesc" },
  { nume: "Capu Câmpului", simplu: "Capu Campului" },
  { nume: "Capu Codrului", comuna: "Paltinoasa" },
  { nume: "Cârlibaba Nouă", simplu: "Carlibaba Noua", comuna: "Carlibaba" },
  { nume: "Cârlibaba", simplu: "Carlibaba" },
  { nume: "Căsoi", simplu: "Casoi", comuna: "Poiana Stampei" },
  { nume: "Catrinari", comuna: "Panaci" },
  { nume: "Chilișeni", simplu: "Chiliseni", comuna: "Udesti" },
  { nume: "Chiril", comuna: "Crucea" },
  { nume: "Ciocănești", simplu: "Ciocanesti" },
  { nume: "Ciomârtan", simplu: "Ciomartan", comuna: "Zamostea" },
  { nume: "Ciprian Porumbescu" },
  { nume: "Ciumârna", simplu: "Ciumarna", comuna: "Vatra Moldovitei" },
  { nume: "Ciumulești", simplu: "Ciumulesti", comuna: "Vadu Moldovei" },
  { nume: "Climăuți", simplu: "Climauti", comuna: "Musenita" },
  { nume: "Clit", comuna: "Arbore" },
  { nume: "Codru", comuna: "Cajvana" },
  { nume: "Cojocăreni", simplu: "Cojocareni", comuna: "Zamostea" },
  { nume: "Cojoci", comuna: "Crucea" },
  { nume: "Colacu", comuna: "Fundu Moldovei" },
  { nume: "Comănești", simplu: "Comanesti" },
  { nume: "Corlata", comuna: "Dragoiesti" },
  { nume: "Corni", comuna: "Liteni" },
  { nume: "Cornu Luncii" },
  { nume: "Corocăiești", simplu: "Corocaiesti", comuna: "Veresti" },
  { nume: "Corpaci", comuna: "Zamostea" },
  { nume: "Coșna", simplu: "Cosna" },
  { nume: "Costâna", simplu: "Costana", comuna: "Todiresti" },
  { nume: "Costileva", comuna: "Ulma" },
  { nume: "Costișa", simplu: "Costisa", comuna: "Fratautii Noi" },
  { nume: "Cotârgași", simplu: "Cotargasi", comuna: "Brosteni" },
  { nume: "Cotu Băii", simplu: "Cotu Baii", comuna: "Fantana Mare" },
  { nume: "Cotu Dobei", comuna: "Fantanele" },
  { nume: "Coverca", comuna: "Panaci" },
  { nume: "Cozănești", simplu: "Cozanesti", comuna: "Dorna-Arini" },
  { nume: "Crucea" },
  { nume: "Cumpărătura", simplu: "Cumparatura", comuna: "Bosanci" },
  { nume: "Cununschi", comuna: "Brodina" },
  { nume: "Dănila", simplu: "Danila", comuna: "Darmanesti" },
  { nume: "Dărmănești", simplu: "Darmanesti" },
  { nume: "Dârmoxa", simplu: "Darmoxa", comuna: "Brosteni" },
  { nume: "Dealu Floreni", comuna: "Dorna Candrenilor" },
  { nume: "Dealu", comuna: "Zvoristea" },
  { nume: "Deia", comuna: "Frumosu" },
  { nume: "Deleni", comuna: "Partestii De Jos" },
  { nume: "Delnița", simplu: "Delnita", comuna: "Fundu Moldovei" },
  { nume: "Deluț", simplu: "Delut", comuna: "Fundu Moldovei" },
  { nume: "Demacușa", simplu: "Demacusa", comuna: "Moldovita" },
  { nume: "Dolhasca" },
  { nume: "Dolheștii Mici", simplu: "Dolhestii Mici", comuna: "Dolhesti" },
  { nume: "Dolheștii-Mari", simplu: "Dolhestii-Mari", comuna: "Dolhesti" },
  { nume: "Dorna Candrenilor" },
  { nume: "Dorna-Arini" },
  { nume: "Dornești", simplu: "Dornesti" },
  { nume: "Dornișoara", simplu: "Dornisoara", comuna: "Poiana Stampei" },
  { nume: "Doroteia", comuna: "Frasin" },
  { nume: "Drăgoiasa", simplu: "Dragoiasa", comuna: "Panaci" },
  { nume: "Drăgoiești", simplu: "Dragoiesti" },
  { nume: "Dragomirna", comuna: "Mitocu Dragomirnei" },
  { nume: "Dragoșa", simplu: "Dragosa", comuna: "Frumosu" },
  { nume: "Drăgușeni", simplu: "Draguseni" },
  { nume: "Dubiușca", simplu: "Dubiusca", comuna: "Brodina" },
  { nume: "Dumbrava", comuna: "Cornu Luncii" },
  { nume: "Dumbrava", comuna: "Granicesti" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Rasca" },
  { nume: "Dumbrăvița", simplu: "Dumbravita", comuna: "Vadu Moldovei" },
  { nume: "Ehrește", simplu: "Ehreste", comuna: "Brodina" },
  { nume: "Falcău", simplu: "Falcau", comuna: "Brodina" },
  { nume: "Fălticeni", simplu: "Falticeni" },
  { nume: "Fântâna Mare", simplu: "Fantana Mare" },
  { nume: "Fântânele", simplu: "Fantanele" },
  { nume: "Fetești", simplu: "Fetesti", comuna: "Adancata" },
  { nume: "Florinta", comuna: "Scheia" },
  { nume: "Forăști", simplu: "Forasti" },
  { nume: "Frasin" },
  { nume: "Frasin", comuna: "Brosteni" },
  { nume: "Frătăuții Noi", simplu: "Fratautii Noi" },
  { nume: "Frătăuții Vechi", simplu: "Fratautii Vechi" },
  { nume: "Frumoasa", comuna: "Moara" },
  { nume: "Frumosu" },
  { nume: "Fundu Moldovei" },
  { nume: "Găinești", simplu: "Gainesti", comuna: "Slatina" },
  { nume: "Gălănești", simplu: "Galanesti" },
  { nume: "Gara Leu", comuna: "Draguseni" },
  { nume: "Gara", comuna: "Milisauti" },
  { nume: "Gemenea", comuna: "Stulpicani" },
  { nume: "Gheorghițeni", simplu: "Gheorghiteni", comuna: "Dorna-Arini" },
  { nume: "Giulești", simplu: "Giulesti", comuna: "Boroaia" },
  { nume: "Giurgești", simplu: "Giurgesti", comuna: "Vulturesti" },
  { nume: "Glodu", comuna: "Panaci" },
  { nume: "Grămești", simplu: "Gramesti" },
  { nume: "Grănicești", simplu: "Granicesti" },
  { nume: "Grigorești", simplu: "Grigoresti", comuna: "Siminicea" },
  { nume: "Groapa Vlădichii", simplu: "Groapa Vladichii", comuna: "Moara" },
  { nume: "Gropeni", comuna: "Balcauti" },
  { nume: "Gulia", comuna: "Dolhasca" },
  { nume: "Gura Haitii", comuna: "Saru Dornei" },
  { nume: "Gura Humorului" },
  { nume: "Gura Putnei", comuna: "Putna" },
  { nume: "Gura Solcii", comuna: "Granicesti" },
  { nume: "Hăleasa", simplu: "Haleasa", comuna: "Brosteni" },
  { nume: "Hancea", comuna: "Veresti" },
  { nume: "Hănțești", simplu: "Hantesti" },
  { nume: "Hârtop", simplu: "Hartop", comuna: "Preutesti" },
  { nume: "Herla", comuna: "Slatina" },
  { nume: "Holda", comuna: "Brosteni" },
  { nume: "Holdița", simplu: "Holdita", comuna: "Brosteni" },
  { nume: "Horodnic de Jos", comuna: "Horodnic" },
  { nume: "Horodnic de Sus" },
  { nume: "Horodniceni" },
  { nume: "Hreațca", simplu: "Hreatca", comuna: "Vulturesti" },
  { nume: "Humoreni", comuna: "Comanesti" },
  { nume: "Hurjuieni", comuna: "Galanesti" },
  { nume: "Huși", simplu: "Husi", comuna: "Preutesti" },
  { nume: "Iacobeni" },
  { nume: "Iacobești", simplu: "Iacobesti", comuna: "Granicesti" },
  { nume: "Iaslovăț", simplu: "Iaslovat" },
  { nume: "Iaz", comuna: "Dornesti" },
  { nume: "Iedu", comuna: "Carlibaba" },
  { nume: "Iesle", comuna: "Malini" },
  { nume: "Ilișești", simplu: "Ilisesti", comuna: "Ciprian Porumbescu" },
  { nume: "Ioneasa", comuna: "Vadu Moldovei" },
  { nume: "Ipotești", simplu: "Ipotesti" },
  { nume: "Izvoarele Sucevei" },
  { nume: "Jacota", comuna: "Vulturesti" },
  { nume: "Jahalia", comuna: "Rasca" },
  { nume: "Lămășeni", simplu: "Lamaseni", comuna: "Radaseni" },
  { nume: "Leucușești", simplu: "Leucusesti", comuna: "Preutesti" },
  { nume: "Lipoveni", comuna: "Mitocu Dragomirnei" },
  { nume: "Lisaura", comuna: "Ipotesti" },
  { nume: "Liteni" },
  { nume: "Liteni", comuna: "Moara" },
  { nume: "Lucăcești", simplu: "Lucacesti", comuna: "Dragoiesti" },
  { nume: "Lunca", comuna: "Milisauti" },
  { nume: "Lunca", comuna: "Zamostea" },
  { nume: "Luncușoara", simplu: "Luncusoara", comuna: "Udesti" },
  { nume: "Lungeni", comuna: "Brosteni" },
  { nume: "Lupcina", comuna: "Ulma" },
  { nume: "Măgura", simplu: "Magura", comuna: "Ulma" },
  { nume: "Maidan", comuna: "Cacica" },
  { nume: "Mălini", simplu: "Malini" },
  { nume: "Mănăstioara", simplu: "Manastioara", comuna: "Siret" },
  { nume: "Mănăstioara", simplu: "Manastioara", comuna: "Udesti" },
  { nume: "Mănăstirea Humorului", simplu: "Manastirea Humorului" },
  { nume: "Măneuți", simplu: "Maneuti", comuna: "Fratautii Vechi" },
  { nume: "Manolea", comuna: "Forasti" },
  { nume: "Marginea" },
  { nume: "Măriței", simplu: "Maritei", comuna: "Darmanesti" },
  { nume: "Mărițeia Mică", simplu: "Mariteia Mica", comuna: "Darmanesti" },
  { nume: "Măzănăești", simplu: "Mazanaesti", comuna: "Dragoiesti" },
  { nume: "Mereni", comuna: "Salcea" },
  { nume: "Merești", simplu: "Meresti", comuna: "Vulturesti" },
  { nume: "Mestecăniș", simplu: "Mestecanis", comuna: "Iacobeni" },
  { nume: "Mesteceni", comuna: "Vadu Moldovei" },
  { nume: "Mihăiești", simplu: "Mihaiesti", comuna: "Horodniceni" },
  { nume: "Mihoveni", comuna: "Scheia" },
  { nume: "Milișăuți", simplu: "Milisauti" },
  { nume: "Mironu", comuna: "Valea Moldovei" },
  { nume: "Mitocași", simplu: "Mitocasi", comuna: "Mitocu Dragomirnei" },
  { nume: "Mitocu Dragomirnei" },
  { nume: "Moara Carp", comuna: "Moara" },
  { nume: "Moara Nica", comuna: "Moara" },
  { nume: "Moișa", simplu: "Moisa", comuna: "Boroaia" },
  { nume: "Moldova-Sulița", simplu: "Moldova-Sulita" },
  { nume: "Moldovița", simplu: "Moldovita" },
  { nume: "Molid", comuna: "Vama" },
  { nume: "Movileni", comuna: "Vadu Moldovei" },
  { nume: "Mușenița", simplu: "Musenita" },
  { nume: "Neagra Șarului", simplu: "Neagra Sarului", comuna: "Saru Dornei" },
  { nume: "Neagra", comuna: "Brosteni" },
  { nume: "Negostina", comuna: "Balcauti" },
  { nume: "Negrileasa", comuna: "Stulpicani" },
  { nume: "Nicani", comuna: "Zamostea" },
  { nume: "Nigotești", simplu: "Nigotesti", comuna: "Vadu Moldovei" },
  { nume: "Nisipitu", comuna: "Ulma" },
  { nume: "Norocu", comuna: "Brodina" },
  { nume: "Obcina", comuna: "Fundu Moldovei" },
  { nume: "Oniceni", comuna: "Forasti" },
  { nume: "Ortoaia", comuna: "Dorna-Arini" },
  { nume: "Osoi", comuna: "Vulturesti" },
  { nume: "Ostra" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Siret" },
  { nume: "Păiseni", simplu: "Paiseni", comuna: "Cornu Luncii" },
  { nume: "Paltin", comuna: "Brodina" },
  { nume: "Păltiniș", simplu: "Paltinis", comuna: "Panaci" },
  { nume: "Păltinoasa", simplu: "Paltinoasa" },
  { nume: "Paltinu", comuna: "Vatra Moldovitei" },
  { nume: "Panaci" },
  { nume: "Pâraie", simplu: "Paraie", comuna: "Malini" },
  { nume: "Pârâu Negrei", simplu: "Parau Negrei", comuna: "Breaza" },
  { nume: "Părhăuți", simplu: "Parhauti", comuna: "Todiresti" },
  { nume: "Pârteștii de Jos", simplu: "Partestii de Jos" },
  { nume: "Pârteștii de Sus", simplu: "Partestii de Sus", comuna: "Cacica" },
  { nume: "Pătrăuți", simplu: "Patrauti" },
  { nume: "Petia", comuna: "Bunesti" },
  { nume: "Pietroasa", comuna: "Brosteni" },
  { nume: "Pilugani", comuna: "Poiana Stampei" },
  { nume: "Plai", comuna: "Fundu Moldovei" },
  { nume: "Plaiu Șarului", simplu: "Plaiu Sarului", comuna: "Saru Dornei" },
  { nume: "Plăvălari", simplu: "Plavalari", comuna: "Udesti" },
  { nume: "Pleșa", simplu: "Plesa", comuna: "Manastirea Humorului" },
  { nume: "Pleșești", simplu: "Plesesti", comuna: "Vulturesti" },
  { nume: "Plopeni", comuna: "Salcea" },
  { nume: "Plutonița", simplu: "Plutonita", comuna: "Frasin" },
  { nume: "Pocoleni", comuna: "Radaseni" },
  { nume: "Podeni", comuna: "Bunesti" },
  { nume: "Podu Coșnei", simplu: "Podu Cosnei", comuna: "Cosna" },
  { nume: "Poiana Mărului", simplu: "Poiana Marului", comuna: "Malini" },
  { nume: "Poiana Micului", comuna: "Manastirea Humorului" },
  { nume: "Poiana Negrii", comuna: "Dorna Candrenilor" },
  { nume: "Poiana Stampei" },
  { nume: "Poiana", comuna: "Dolhasca" },
  { nume: "Poiana", comuna: "Zvoristea" },
  { nume: "Poienari", comuna: "Dolhasca" },
  { nume: "Poieni-Solca", comuna: "Solca" },
  { nume: "Poieni-Suceava", comuna: "Udesti" },
  { nume: "Pojorâta", simplu: "Pojorata" },
  { nume: "Prăleni", simplu: "Praleni", comuna: "Poiana Stampei" },
  { nume: "Praxia", comuna: "Fantana Mare" },
  { nume: "Prelipca", comuna: "Salcea" },
  { nume: "Preutești", simplu: "Preutesti" },
  { nume: "Prisaca Dornei", comuna: "Vama" },
  { nume: "Probota", comuna: "Dolhasca" },
  { nume: "Putna" },
  { nume: "Racova", comuna: "Udesti" },
  { nume: "Rădășeni", simplu: "Radaseni" },
  { nume: "Rădăuți", simplu: "Radauti" },
  { nume: "Râșca", simplu: "Rasca" },
  { nume: "Rașca", simplu: "Rasca", comuna: "Moldovita" },
  { nume: "Răuțeni", simplu: "Rauteni", comuna: "Zamostea" },
  { nume: "Reuseni", comuna: "Udesti" },
  { nume: "Românești", simplu: "Romanesti", comuna: "Cosna" },
  { nume: "Românești", simplu: "Romanesti", comuna: "Granicesti" },
  { nume: "Roșcani", simplu: "Roscani", comuna: "Liteni" },
  { nume: "Roșiori", simplu: "Rosiori", comuna: "Forasti" },
  { nume: "Roșu", simplu: "Rosu", comuna: "Vatra Dornei" },
  { nume: "Rotopănești", simplu: "Rotopanesti", comuna: "Horodniceni" },
  { nume: "Rotunda", comuna: "Liteni" },
  { nume: "Rudești", simplu: "Rudesti", comuna: "Gramesti" },
  { nume: "Runcu", comuna: "Cacica" },
  { nume: "Rusca", comuna: "Dorna-Arini" },
  { nume: "Ruși", simplu: "Rusi", comuna: "Forasti" },
  { nume: "Rușii-Mănăstioara", simplu: "Rusii-Manastioara", comuna: "Udesti" },
  { nume: "Săcuța", simplu: "Sacuta", comuna: "Boroaia" },
  { nume: "Sadău", simplu: "Sadau", comuna: "Brodina" },
  { nume: "Sadova" },
  { nume: "Sălăgeni", simplu: "Salageni", comuna: "Dumbraveni" },
  { nume: "Salcea" },
  { nume: "Sârghiești", simplu: "Sarghiesti", comuna: "Todiresti" },
  { nume: "Sărișor", simplu: "Sarisor", comuna: "Saru Dornei" },
  { nume: "Sărișoru Mare", simplu: "Sarisoru Mare", comuna: "Saru Dornei" },
  { nume: "Șaru Bucovinei", simplu: "Saru Bucovinei", comuna: "Saru Dornei" },
  { nume: "Șarul Dornei", simplu: "Sarul Dornei", comuna: "Saru Dornei" },
  { nume: "Sasca Mare", comuna: "Cornu Luncii" },
  { nume: "Sasca Mică", simplu: "Sasca Mica", comuna: "Cornu Luncii" },
  { nume: "Sasca Nouă", simplu: "Sasca Noua", comuna: "Cornu Luncii" },
  { nume: "Satu Mare" },
  { nume: "Satu Mare", comuna: "Crucea" },
  { nume: "Șcheia", simplu: "Scheia" },
  { nume: "Securiceni", comuna: "Udesti" },
  { nume: "Șerbănești", simplu: "Serbanesti", comuna: "Zvoristea" },
  { nume: "Șerbăuți", simplu: "Serbauti" },
  { nume: "Șes", simplu: "Ses", comuna: "Bunesti" },
  { nume: "Șesuri", simplu: "Sesuri", comuna: "Carlibaba" },
  { nume: "Sfântu Ilie", simplu: "Sfantu Ilie", comuna: "Scheia" },
  { nume: "Siliștea Nouă", simplu: "Silistea Noua", comuna: "Dolhasca" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Liteni" },
  { nume: "Siminicea" },
  { nume: "Șinca", simplu: "Sinca", comuna: "Cornu Luncii" },
  { nume: "Siret" },
  { nume: "Slatina" },
  { nume: "Slătioara", simplu: "Slatioara", comuna: "Rasca" },
  { nume: "Slătioara", simplu: "Slatioara", comuna: "Stulpicani" },
  { nume: "Slobozia Sucevei", comuna: "Granicesti" },
  { nume: "Slobozia", comuna: "Fantanele" },
  { nume: "Slobozia", comuna: "Zvoristea" },
  { nume: "Smida Ungurenilor", comuna: "Fundu Moldovei" },
  { nume: "Solca" },
  { nume: "Șoldănești", simplu: "Soldanesti", comuna: "Falticeni" },
  { nume: "Soloneț", simplu: "Solonet", comuna: "Todiresti" },
  { nume: "Solonețu Nou", simplu: "Solonetu Nou", comuna: "Cacica" },
  { nume: "Spătărești", simplu: "Spataresti", comuna: "Fantana Mare" },
  { nume: "Stamate", comuna: "Fantanele" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Zvoristea" },
  { nume: "Stâncuța", simplu: "Stancuta", comuna: "Zvoristea" },
  { nume: "Știrbăț", simplu: "Stirbat", comuna: "Udesti" },
  { nume: "Straja" },
  { nume: "Strâmtura", simplu: "Stramtura", comuna: "Vama" },
  { nume: "Stroiești", simplu: "Stroiesti" },
  { nume: "Stulpicani" },
  { nume: "Suceava" },
  { nume: "Sucevița", simplu: "Sucevita" },
  { nume: "Sunători", simplu: "Sunatori", comuna: "Dorna-Arini" },
  { nume: "Țarna Mare", simplu: "Tarna Mare", comuna: "Falticeni" },
  { nume: "Tărnicioara", simplu: "Tarnicioara", comuna: "Ostra" },
  { nume: "Tătaru", simplu: "Tataru", comuna: "Poiana Stampei" },
  { nume: "Tăutești", simplu: "Tautesti", comuna: "Zamostea" },
  { nume: "Teșna", simplu: "Tesna", comuna: "Cosna" },
  { nume: "Teșna", simplu: "Tesna", comuna: "Poiana Stampei" },
  { nume: "Țibău", simplu: "Tibau", comuna: "Carlibaba" },
  { nume: "Țibeni", simplu: "Tibeni", comuna: "Satu Mare" },
  { nume: "Tișăuți", simplu: "Tisauti", comuna: "Ipotesti" },
  { nume: "Todireni", comuna: "Vatra Dornei" },
  { nume: "Todirești", simplu: "Todiresti" },
  { nume: "Țolești", simplu: "Tolesti", comuna: "Forasti" },
  { nume: "Trei Movile", comuna: "Scheia" },
  { nume: "Udești", simplu: "Udesti" },
  { nume: "Uidești", simplu: "Uidesti", comuna: "Forasti" },
  { nume: "Ulma" },
  { nume: "Uncești", simplu: "Uncesti", comuna: "Bunesti" },
  { nume: "Vadu Moldovei" },
  { nume: "Vadu Negrilesei", comuna: "Stulpicani" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Stroiesti" },
  { nume: "Valea Bancului", comuna: "Cosna" },
  { nume: "Valea Bourei", comuna: "Dolhesti" },
  { nume: "Valea Glodului", comuna: "Vulturesti" },
  { nume: "Valea Moldovei" },
  { nume: "Valea Poienei", comuna: "Dolhasca" },
  { nume: "Valea Putnei", comuna: "Pojorata" },
  { nume: "Valea Stânei", simplu: "Valea Stanei", comuna: "Carlibaba" },
  { nume: "Văleni-Stânișoara", simplu: "Valeni-Stanisoara", comuna: "Malini" },
  { nume: "Vama" },
  { nume: "Văratec", simplu: "Varatec", comuna: "Salcea" },
  {
    nume: "Vârfu Dealului",
    simplu: "Varfu Dealului",
    comuna: "Partestii De Jos",
  },
  { nume: "Varvata", comuna: "Partestii De Jos" },
  { nume: "Vășcăuți", simplu: "Vascauti", comuna: "Musenita" },
  { nume: "Vatra Dornei" },
  { nume: "Vatra Moldoviței", simplu: "Vatra Moldovitei" },
  { nume: "Verbia", comuna: "Gramesti" },
  { nume: "Vercicani", comuna: "Liteni" },
  { nume: "Verești", simplu: "Veresti" },
  { nume: "Vicovu de Jos" },
  { nume: "Vicovu de Sus" },
  { nume: "Vicșani", simplu: "Vicsani", comuna: "Musenita" },
  { nume: "Voievodeasa", comuna: "Sucevita" },
  { nume: "Voitinel", comuna: "Galanesti" },
  { nume: "Volovăț", simplu: "Volovat" },
  { nume: "Vornicenii Mari", comuna: "Moara" },
  { nume: "Vornicenii Mici", comuna: "Moara" },
  { nume: "Voroneț", simplu: "Voronet", comuna: "Gura Humorului" },
  { nume: "Vulturești", simplu: "Vulturesti" },
  { nume: "Zaharești", simplu: "Zaharesti", comuna: "Stroiesti" },
  { nume: "Zalomestra", comuna: "Brodina" },
  { nume: "Zamostea" },
  { nume: "Zvoriștea", simplu: "Zvoristea" },
];
