export const sb = [
  { nume: "Aciliu", comuna: "Saliste" },
  { nume: "Agârbiciu", simplu: "Agarbiciu", comuna: "Axente Sever" },
  { nume: "Agnita" },
  { nume: "Alămor", simplu: "Alamor", comuna: "Loamnes" },
  { nume: "Albi", comuna: "Slimnic" },
  { nume: "Alma Vii", comuna: "Mosna" },
  { nume: "Alma", comuna: "Atel" },
  { nume: "Alţina", simplu: "Altina" },
  { nume: "Amnaş", simplu: "Amnas", comuna: "Saliste" },
  { nume: "Apoldu de Jos" },
  { nume: "Apoldu de Sus", comuna: "Miercurea Sibiului" },
  { nume: "Apoş", simplu: "Apos", comuna: "Birghis" },
  { nume: "Armeni", comuna: "Loamnes" },
  { nume: "Arpaşu de Jos", simplu: "Arpasu de Jos" },
  { nume: "Arpaşu de Sus", simplu: "Arpasu de Sus", comuna: "Arpasu De Jos" },
  { nume: "Aţel", simplu: "Atel" },
  { nume: "Avrig" },
  { nume: "Axente Sever" },
  { nume: "Bârghiş", simplu: "Barghis", comuna: "Birghis" },
  { nume: "Bazna" },
  { nume: "Beneşti", simplu: "Benesti", comuna: "Altina" },
  { nume: "Biertan" },
  { nume: "Blăjel", simplu: "Blajel" },
  { nume: "Boarta", comuna: "Seica Mare" },
  { nume: "Bogatu Român", simplu: "Bogatu Roman", comuna: "Pauca" },
  { nume: "Boian", comuna: "Bazna" },
  { nume: "Boiţa", simplu: "Boita", comuna: "Talmaciu" },
  { nume: "Brădeni", simplu: "Bradeni" },
  { nume: "Bradu", comuna: "Avrig" },
  { nume: "Brateiu" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Pauca" },
  { nume: "Bruiu" },
  { nume: "Buia", comuna: "Seica Mare" },
  { nume: "Bungard", comuna: "Selimbar" },
  { nume: "Buzd", comuna: "Brateiu" },
  { nume: "Cârţa", simplu: "Carta" },
  { nume: "Cârţişoara", simplu: "Cartisoara" },
  { nume: "Caşolţ", simplu: "Casolt", comuna: "Rosia" },
  { nume: "Chesler", comuna: "Micasasa" },
  { nume: "Chirpăr", simplu: "Chirpar" },
  { nume: "Cisnădie", simplu: "Cisnadie" },
  { nume: "Cisnădioara", simplu: "Cisnadioara", comuna: "Cisnadie" },
  { nume: "Colonia Tălmaciu", simplu: "Colonia Talmaciu", comuna: "Talmaciu" },
  { nume: "Colonia Târnava", simplu: "Colonia Tarnava", comuna: "Tarnava" },
  { nume: "Colun", comuna: "Porumbacu De Jos" },
  { nume: "Copşa Mare", simplu: "Copsa Mare", comuna: "Biertan" },
  { nume: "Copşa Mică", simplu: "Copsa Mica" },
  { nume: "Cornăţel", simplu: "Cornatel", comuna: "Rosia" },
  { nume: "Coveş", simplu: "Coves", comuna: "Agnita" },
  { nume: "Crinţ", simplu: "Crint", comuna: "Saliste" },
  { nume: "Cristian" },
  { nume: "Curciu", comuna: "Darlos" },
  { nume: "Daia", comuna: "Rosia" },
  { nume: "Dârlos", simplu: "Darlos" },
  { nume: "Dealu Frumos", comuna: "Merghindeal" },
  { nume: "Dobârca", simplu: "Dobarca", comuna: "Miercurea Sibiului" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni" },
  { nume: "Dupuş", simplu: "Dupus", comuna: "Atel" },
  { nume: "Ernea", comuna: "Dumbraveni" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Saliste" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Laslea" },
  { nume: "Fofeldea", comuna: "Nocrich" },
  { nume: "Galeş", simplu: "Gales", comuna: "Saliste" },
  { nume: "Gherdeal", comuna: "Bruiu" },
  { nume: "Ghijasa de Jos", comuna: "Nocrich" },
  { nume: "Ghijasa de Sus", comuna: "Altina" },
  { nume: "Giacăş", simplu: "Giacas", comuna: "Atel" },
  { nume: "Glâmboaca", simplu: "Glamboaca", comuna: "Avrig" },
  { nume: "Gura Râului", simplu: "Gura Raului" },
  { nume: "Gusu", comuna: "Ludos" },
  { nume: "Hamba", comuna: "Sura Mare" },
  { nume: "Haşag", simplu: "Hasag", comuna: "Loamnes" },
  { nume: "Hoghilag" },
  { nume: "Hosman", comuna: "Nocrich" },
  { nume: "Iacobeni" },
  { nume: "Ighişu Nou", simplu: "Ighisu Nou", comuna: "Medias" },
  { nume: "Ighişu Vechi", simplu: "Ighisu Vechi", comuna: "Birghis" },
  { nume: "Ilimbav", comuna: "Marpod" },
  { nume: "Jina" },
  { nume: "Laslea" },
  { nume: "Lazaret", comuna: "Talmaciu" },
  { nume: "Loamneş", simplu: "Loamnes" },
  { nume: "Lotrioara", comuna: "Talmaciu" },
  { nume: "Ludoş", simplu: "Ludos" },
  { nume: "Mag", comuna: "Saliste" },
  { nume: "Mălâncrav", simplu: "Malancrav", comuna: "Laslea" },
  { nume: "Mândra", simplu: "Mandra", comuna: "Loamnes" },
  { nume: "Marpod" },
  { nume: "Mârşa", simplu: "Marsa", comuna: "Avrig" },
  { nume: "Mediaş", simplu: "Medias" },
  { nume: "Merghindeal" },
  { nume: "Metiş", simplu: "Metis", comuna: "Mihaileni" },
  { nume: "Micăsasa", simplu: "Micasasa" },
  { nume: "Miercurea Sibiului" },
  { nume: "Mighindoala", comuna: "Seica Mare" },
  { nume: "Mihăileni", simplu: "Mihaileni" },
  { nume: "Moardăş", simplu: "Moardas", comuna: "Mihaileni" },
  { nume: "Mohu", comuna: "Selimbar" },
  { nume: "Moşna", simplu: "Mosna" },
  { nume: "Motiş", simplu: "Motis", comuna: "Valea Viilor" },
  { nume: "Movile", comuna: "Iacobeni" },
  { nume: "Nemşa", simplu: "Nemsa", comuna: "Mosna" },
  { nume: "Netuş", simplu: "Netus", comuna: "Iacobeni" },
  { nume: "Nocrich" },
  { nume: "Noiştat", simplu: "Noistat", comuna: "Iacobeni" },
  { nume: "Nou Săsesc", simplu: "Nou Sasesc", comuna: "Laslea" },
  { nume: "Nou", comuna: "Rosia" },
  { nume: "Noul Român", simplu: "Noul Roman", comuna: "Arpasu De Jos" },
  { nume: "Nucet", comuna: "Rosia" },
  { nume: "Ocna Sibiului" },
  { nume: "Orlat" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Slimnic" },
  { nume: "Paltin", comuna: "Talmaciu" },
  { nume: "Păltiniş", simplu: "Paltinis", comuna: "Sibiu" },
  { nume: "Păuca", simplu: "Pauca" },
  { nume: "Păucea", simplu: "Paucea", comuna: "Blajel" },
  { nume: "Pelişor", simplu: "Pelisor", comuna: "Birghis" },
  { nume: "Petiş", simplu: "Petis", comuna: "Seica Mare" },
  { nume: "Poiana Sibiului" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Carta" },
  { nume: "Poplaca" },
  { nume: "Porumbacu de Jos" },
  { nume: "Porumbacu de Sus", comuna: "Porumbacu De Jos" },
  { nume: "Presaca", comuna: "Pauca" },
  { nume: "Prislop", comuna: "Rasinari" },
  { nume: "Prod", comuna: "Hoghilag" },
  { nume: "Racoviţa", simplu: "Racovita" },
  { nume: "Răşinari", simplu: "Rasinari" },
  { nume: "Râu Sadului", simplu: "Rau Sadului" },
  { nume: "Răvăşel", simplu: "Ravasel", comuna: "Mihaileni" },
  { nume: "Retiş", simplu: "Retis", comuna: "Bradeni" },
  { nume: "Richiş", simplu: "Richis", comuna: "Biertan" },
  { nume: "Roandola", comuna: "Laslea" },
  { nume: "Rod", comuna: "Tilisca" },
  { nume: "Romaneşti", simplu: "Romanesti", comuna: "Blajel" },
  { nume: "Roşia", simplu: "Rosia" },
  { nume: "Ruja", comuna: "Agnita" },
  { nume: "Rusciori", comuna: "Sura Mica" },
  { nume: "Ruşi", simplu: "Rusi", comuna: "Slimnic" },
  { nume: "Săcădate", simplu: "Sacadate", comuna: "Avrig" },
  { nume: "Săcel", simplu: "Sacel", comuna: "Saliste" },
  { nume: "Sădinca", simplu: "Sadinca", comuna: "Loamnes" },
  { nume: "Sadu" },
  { nume: "Şalcău", simplu: "Salcau", comuna: "Mihaileni" },
  { nume: "Sălişte", simplu: "Saliste" },
  { nume: "Sângătin", simplu: "Sangatin", comuna: "Apoldu De Jos" },
  { nume: "Sărata", simplu: "Sarata", comuna: "Porumbacu De Jos" },
  {
    nume: "Şaroş pe Târnave",
    simplu: "Saros pe Tarnave",
    comuna: "Dumbraveni",
  },
  { nume: "Săsăuş", simplu: "Sasaus", comuna: "Chirpar" },
  { nume: "Scoreiu", comuna: "Porumbacu De Jos" },
  { nume: "Sebeşu de Jos", simplu: "Sebesu de Jos", comuna: "Turnu Rosu" },
  { nume: "Sebeşu de Sus", simplu: "Sebesu de Sus", comuna: "Racovita" },
  { nume: "Şeica Mare", simplu: "Seica Mare" },
  { nume: "Şeica Mică", simplu: "Seica Mica" },
  { nume: "Şelimbăr", simplu: "Selimbar" },
  { nume: "Sibiel", comuna: "Saliste" },
  { nume: "Sibiu" },
  { nume: "Slimnic" },
  { nume: "Şmig", simplu: "Smig", comuna: "Atel" },
  { nume: "Şoala", simplu: "Soala", comuna: "Axente Sever" },
  { nume: "Şomartin", simplu: "Somartin", comuna: "Bruiu" },
  { nume: "Soroştin", simplu: "Sorostin", comuna: "Seica Mica" },
  { nume: "Stejărişu", simplu: "Stejarisu", comuna: "Iacobeni" },
  { nume: "Ştenea", simplu: "Stenea", comuna: "Seica Mare" },
  { nume: "Şura Mare", simplu: "Sura Mare" },
  { nume: "Şura Mică", simplu: "Sura Mica" },
  { nume: "Tălmăcel", simplu: "Talmacel", comuna: "Talmaciu" },
  { nume: "Tălmaciu", simplu: "Talmaciu" },
  { nume: "Ţapu", simplu: "Tapu", comuna: "Micasasa" },
  { nume: "Târnava", simplu: "Tarnava" },
  { nume: "Ţeline", simplu: "Teline", comuna: "Bradeni" },
  { nume: "Ţichindeal", simplu: "Tichindeal", comuna: "Nocrich" },
  { nume: "Tilişca", simplu: "Tilisca" },
  { nume: "Topârcea", simplu: "Toparcea", comuna: "Ocna Sibiului" },
  { nume: "Turnu Roşu", simplu: "Turnu Rosu" },
  { nume: "Valchid", comuna: "Hoghilag" },
  { nume: "Vale", comuna: "Saliste" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Darlos" },
  { nume: "Valea Viilor" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Micasasa" },
  { nume: "Vărd", simplu: "Vard", comuna: "Chirpar" },
  { nume: "Vecerd", comuna: "Birghis" },
  { nume: "Velţ", simplu: "Velt", comuna: "Bazna" },
  { nume: "Veseud", comuna: "Chirpar" },
  { nume: "Veseud", comuna: "Slimnic" },
  { nume: "Veştem", simplu: "Vestem", comuna: "Selimbar" },
  { nume: "Vurpăr", simplu: "Vurpar" },
  { nume: "Zlagna", comuna: "Birghis" },
];
