export const tm = [
  { nume: "Balint" },
  { nume: "Banloc" },
  { nume: "Bara" },
  { nume: "Beba Veche" },
  { nume: "Becicherecu Mic" },
  { nume: "Belint" },
  { nume: "Bethausen" },
  { nume: "Biled" },
  { nume: "Bogda" },
  { nume: "Boldur" },
  { nume: "Brestovat" },
  { nume: "Buzias" },
  { nume: "Barna" },
  { nume: "Cenad" },
  { nume: "Cenei" },
  { nume: "Cheveresu Mare" },
  { nume: "Ciacova" },
  { nume: "Comlosu Mare" },
  { nume: "Costeiu" },
  { nume: "Criciova" },
  { nume: "Curtea" },
  { nume: "Carpinis" },
  { nume: "Darova" },
  { nume: "Denta" },
  { nume: "Deta" },
  { nume: "Dudestii Vechi" },
  { nume: "Dumbrava" },
  { nume: "Dumbravita" },
  { nume: "Foeni" },
  { nume: "Fardea" },
  { nume: "Faget" },
  { nume: "Gavojdia" },
  { nume: "Ghiroda" },
  { nume: "Ghizela" },
  { nume: "Giarmata" },
  { nume: "Giera" },
  { nume: "Giroc" },
  { nume: "Giulvaz" },
  { nume: "Gataia" },
  { nume: "Jamu Mare" },
  { nume: "Jebel" },
  { nume: "Jimbolia" },
  { nume: "Lenauheim" },
  { nume: "Liebling" },
  { nume: "Lovrin" },
  { nume: "Lugoj" },
  { nume: "Margina" },
  { nume: "Masloc" },
  { nume: "Moravita" },
  { nume: "Mosnita Noua" },
  { nume: "Manastiur" },
  { nume: "Nitchidorf" },
  { nume: "Nadrag" },
  { nume: "Ohaba Lunga" },
  { nume: "Ortisoara" },
  { nume: "Peciu Nou" },
  { nume: "Periam" },
  { nume: "Pietroasa" },
  { nume: "Pischia" },
  { nume: "Racovita" },
  { nume: "Recas" },
  { nume: "Remetea Mare" },
  { nume: "Sacosu Turcesc" },
  { nume: "Satchinez" },
  { nume: "Secas" },
  { nume: "Sanandrei" },
  { nume: "Sanmihaiu Roman" },
  { nume: "Sannicolau Mare" },
  { nume: "Sanpetru Mare" },
  { nume: "Sacalaz" },
  { nume: "Teremia Mare" },
  { nume: "Timisoara" },
  { nume: "Tomesti" },
  { nume: "Topolovatu Mare" },
  { nume: "Tormac" },
  { nume: "Traian Vuia" },
  { nume: "Uivar" },
  { nume: "Varias" },
  { nume: "Victor Vlad Delamarina" },
  { nume: "Voiteg" },
  { nume: "Sag" },
  { nume: "Stiuca" },
  { nume: "Bodo", comuna: "Balint" },
  { nume: "Fadimac", comuna: "Balint" },
  { nume: "Targoviste", comuna: "Balint" },
  { nume: "Dolat", comuna: "Banloc" },
  { nume: "Livezile", comuna: "Banloc" },
  { nume: "Ofsenita", comuna: "Banloc" },
  { nume: "Partos", comuna: "Banloc" },
  { nume: "Soca", comuna: "Banloc" },
  { nume: "Dobresti", comuna: "Bara" },
  { nume: "Lapusnic", comuna: "Bara" },
  { nume: "Radmanesti", comuna: "Bara" },
  { nume: "Spata", comuna: "Bara" },
  { nume: "Botesti", comuna: "Barna" },
  { nume: "Botinesti", comuna: "Barna" },
  { nume: "Drinova", comuna: "Barna" },
  { nume: "Juresti", comuna: "Barna" },
  { nume: "Poganesti", comuna: "Barna" },
  { nume: "Sarazani", comuna: "Barna" },
  { nume: "Cherestur", comuna: "Beba Veche" },
  { nume: "Pordeanu", comuna: "Beba Veche" },
  { nume: "Dudestii Noi", comuna: "Becicherecu Mic" },
  { nume: "Babsa", comuna: "Belint" },
  { nume: "Chizatau", comuna: "Belint" },
  { nume: "Gruni", comuna: "Belint" },
  { nume: "Cladova", comuna: "Bethausen" },
  { nume: "Cliciova", comuna: "Bethausen" },
  { nume: "Cutina", comuna: "Bethausen" },
  { nume: "Leucusesti", comuna: "Bethausen" },
  { nume: "Nevrincea", comuna: "Bethausen" },
  { nume: "Uihei", comuna: "Biled" },
  { nume: "Sandra", comuna: "Biled" },
  { nume: "Altringen", comuna: "Bogda" },
  { nume: "Buzad", comuna: "Bogda" },
  { nume: "Charlotenburg", comuna: "Bogda" },
  { nume: "Comeat", comuna: "Bogda" },
  { nume: "Sintar", comuna: "Bogda" },
  { nume: "Jabar", comuna: "Boldur" },
  { nume: "Ohaba-Forgaci", comuna: "Boldur" },
  { nume: "Sinersig", comuna: "Boldur" },
  { nume: "Cosarii", comuna: "Brestovat" },
  { nume: "Hodos", comuna: "Brestovat" },
  { nume: "Lucaret", comuna: "Brestovat" },
  { nume: "Tes", comuna: "Brestovat" },
  { nume: "Bacova", comuna: "Buzias" },
  { nume: "Silagiu", comuna: "Buzias" },
  { nume: "Iecea Mare", comuna: "Carpinis" },
  { nume: "Iecea Mica", comuna: "Carpinis" },
  { nume: "Bobda", comuna: "Cenei" },
  { nume: "Checea", comuna: "Cenei" },
  { nume: "Dragsina", comuna: "Cheveresu Mare" },
  { nume: "Vucova", comuna: "Cheveresu Mare" },
  { nume: "Cebza", comuna: "Ciacova" },
  { nume: "Gad", comuna: "Ciacova" },
  { nume: "Ghilad", comuna: "Ciacova" },
  { nume: "Macedonia", comuna: "Ciacova" },
  { nume: "Obad", comuna: "Ciacova" },
  { nume: "Petroman", comuna: "Ciacova" },
  { nume: "Comlosu Mic", comuna: "Comlosu Mare" },
  { nume: "Lunga", comuna: "Comlosu Mare" },
  { nume: "Hezeris", comuna: "Costeiu" },
  { nume: "Paru", comuna: "Costeiu" },
  { nume: "Valea Lunga Romana", comuna: "Costeiu" },
  { nume: "Tipari", comuna: "Costeiu" },
  { nume: "Ciresu", comuna: "Criciova" },
  { nume: "Ciresu Mic", comuna: "Criciova" },
  { nume: "Jdioara", comuna: "Criciova" },
  { nume: "Cosava", comuna: "Curtea" },
  { nume: "Homojdia", comuna: "Curtea" },
  { nume: "Hodos", comuna: "Darova" },
  { nume: "Sacosu Mare", comuna: "Darova" },
  { nume: "Brestea", comuna: "Denta" },
  { nume: "Rovinita Mare", comuna: "Denta" },
  { nume: "Rovinita Mica", comuna: "Denta" },
  { nume: "Opatita", comuna: "Deta" },
  { nume: "Cheglevici", comuna: "Dudestii Vechi" },
  { nume: "Colonia Bulgara", comuna: "Dudestii Vechi" },
  { nume: "Valcani", comuna: "Dudestii Vechi" },
  { nume: "Bucovat", comuna: "Dumbrava" },
  { nume: "Rachita", comuna: "Dumbrava" },
  { nume: "Begheiu Mic", comuna: "Faget" },
  { nume: "Bichigi", comuna: "Faget" },
  { nume: "Branesti", comuna: "Faget" },
  { nume: "Bunea Mare", comuna: "Faget" },
  { nume: "Bunea Mica", comuna: "Faget" },
  { nume: "Batesti", comuna: "Faget" },
  { nume: "Colonia Mica", comuna: "Faget" },
  { nume: "Jupanesti", comuna: "Faget" },
  { nume: "Povargina", comuna: "Faget" },
  { nume: "Temeresti", comuna: "Faget" },
  { nume: "Dragsinesti", comuna: "Fardea" },
  { nume: "Gladna Montana", comuna: "Fardea" },
  { nume: "Gladna Romana", comuna: "Fardea" },
  { nume: "Hauzesti", comuna: "Fardea" },
  { nume: "Matnicu Mic", comuna: "Fardea" },
  { nume: "Zolt", comuna: "Fardea" },
  { nume: "Cruceni", comuna: "Foeni" },
  { nume: "Berecuta", comuna: "Gataia" },
  { nume: "Birda", comuna: "Gataia" },
  { nume: "Butin", comuna: "Gataia" },
  { nume: "Manastire", comuna: "Gataia" },
  { nume: "Percosova", comuna: "Gataia" },
  { nume: "Sculia", comuna: "Gataia" },
  { nume: "Sangeorge", comuna: "Gataia" },
  { nume: "Semlacu Mare", comuna: "Gataia" },
  { nume: "Semlacu Mic", comuna: "Gataia" },
  { nume: "Jena", comuna: "Gavojdia" },
  { nume: "Lugojel", comuna: "Gavojdia" },
  { nume: "Salbagel", comuna: "Gavojdia" },
  { nume: "Giarmata-Vii", comuna: "Ghiroda" },
  { nume: "Hisias", comuna: "Ghizela" },
  { nume: "Paniova", comuna: "Ghizela" },
  { nume: "Sanovita", comuna: "Ghizela" },
  { nume: "Cerneteaz", comuna: "Giarmata" },
  { nume: "Granicerii", comuna: "Giera" },
  { nume: "Toager", comuna: "Giera" },
  { nume: "Chisoda", comuna: "Giroc" },
  { nume: "Crai Nou", comuna: "Giulvaz" },
  { nume: "Ivanda", comuna: "Giulvaz" },
  { nume: "Rudna", comuna: "Giulvaz" },
  { nume: "Clopodia", comuna: "Jamu Mare" },
  { nume: "Ferendia", comuna: "Jamu Mare" },
  { nume: "Gherman", comuna: "Jamu Mare" },
  { nume: "Latunas", comuna: "Jamu Mare" },
  { nume: "Padureni", comuna: "Jebel" },
  { nume: "Bulgarus", comuna: "Lenauheim" },
  { nume: "Grabat", comuna: "Lenauheim" },
  { nume: "Cerna", comuna: "Liebling" },
  { nume: "Iosif", comuna: "Liebling" },
  { nume: "Gottlob", comuna: "Lovrin" },
  { nume: "Tomnatic", comuna: "Lovrin" },
  { nume: "Vizejdia", comuna: "Lovrin" },
  { nume: "Maguri", comuna: "Lugoj" },
  { nume: "Tapia", comuna: "Lugoj" },
  { nume: "Padurani", comuna: "Manastiur" },
  { nume: "Remetea-Lunca", comuna: "Manastiur" },
  { nume: "Topla", comuna: "Manastiur" },
  { nume: "Breazova", comuna: "Margina" },
  { nume: "Bulza", comuna: "Margina" },
  { nume: "Cosevita", comuna: "Margina" },
  { nume: "Costeiu de Sus", comuna: "Margina" },
  { nume: "Grosi", comuna: "Margina" },
  { nume: "Nemesesti", comuna: "Margina" },
  { nume: "Sintesti", comuna: "Margina" },
  { nume: "Zorani", comuna: "Margina" },
  { nume: "Alios", comuna: "Masloc" },
  { nume: "Fibis", comuna: "Masloc" },
  { nume: "Remetea Mica", comuna: "Masloc" },
  { nume: "Dejan", comuna: "Moravita" },
  { nume: "Gaiu Mic", comuna: "Moravita" },
  { nume: "Stamora Germana", comuna: "Moravita" },
  { nume: "Albina", comuna: "Mosnita Noua" },
  { nume: "Mosnita Veche", comuna: "Mosnita Noua" },
  { nume: "Rudicica", comuna: "Mosnita Noua" },
  { nume: "Urseni", comuna: "Mosnita Noua" },
  { nume: "Crivina", comuna: "Nadrag" },
  { nume: "Blajova", comuna: "Nitchidorf" },
  { nume: "Duboz", comuna: "Nitchidorf" },
  { nume: "Dubesti", comuna: "Ohaba Lunga" },
  { nume: "Iersnic", comuna: "Ohaba Lunga" },
  { nume: "Ohaba Romana", comuna: "Ohaba Lunga" },
  { nume: "Cornesti", comuna: "Ortisoara" },
  { nume: "Calacea", comuna: "Ortisoara" },
  { nume: "Seceani", comuna: "Ortisoara" },
  { nume: "Dinias", comuna: "Peciu Nou" },
  { nume: "Sanmartinu Sarbesc", comuna: "Peciu Nou" },
  { nume: "Pesac", comuna: "Periam" },
  { nume: "Crivina de Sus", comuna: "Pietroasa" },
  { nume: "Farasesti", comuna: "Pietroasa" },
  { nume: "Poieni", comuna: "Pietroasa" },
  { nume: "Bencecu de Jos", comuna: "Pischia" },
  { nume: "Bencecu de Sus", comuna: "Pischia" },
  { nume: "Murani", comuna: "Pischia" },
  { nume: "Salciua Noua", comuna: "Pischia" },
  { nume: "Capat", comuna: "Racovita" },
  { nume: "Dragoiesti", comuna: "Racovita" },
  { nume: "Ficatar", comuna: "Racovita" },
  { nume: "Hitias", comuna: "Racovita" },
  { nume: "Sarbova", comuna: "Racovita" },
  { nume: "Bazos", comuna: "Recas" },
  { nume: "Herneacova", comuna: "Recas" },
  { nume: "Izvin", comuna: "Recas" },
  { nume: "Nadas", comuna: "Recas" },
  { nume: "Petrovaselo", comuna: "Recas" },
  { nume: "Stanciova", comuna: "Recas" },
  { nume: "Bazosu Nou", comuna: "Remetea Mare" },
  { nume: "Bucovat", comuna: "Remetea Mare" },
  { nume: "Ianova", comuna: "Remetea Mare" },
  { nume: "Beregsau Mare", comuna: "Sacalaz" },
  { nume: "Beregsau Mic", comuna: "Sacalaz" },
  { nume: "Berini", comuna: "Sacosu Turcesc" },
  { nume: "Icloda", comuna: "Sacosu Turcesc" },
  { nume: "Otvesti", comuna: "Sacosu Turcesc" },
  { nume: "Stamora Romana", comuna: "Sacosu Turcesc" },
  { nume: "Uliuc", comuna: "Sacosu Turcesc" },
  { nume: "Unip", comuna: "Sacosu Turcesc" },
  { nume: "Parta", comuna: "Sag" },
  { nume: "Carani", comuna: "Sanandrei" },
  { nume: "Covaci", comuna: "Sanandrei" },
  { nume: "Sanmihaiu German", comuna: "Sanmihaiu Roman" },
  { nume: "Utvin", comuna: "Sanmihaiu Roman" },
  { nume: "Igris", comuna: "Sanpetru Mare" },
  { nume: "Saravale", comuna: "Sanpetru Mare" },
  { nume: "Barateaz", comuna: "Satchinez" },
  { nume: "Hodoni", comuna: "Satchinez" },
  { nume: "Cheches", comuna: "Secas" },
  { nume: "Crivobara", comuna: "Secas" },
  { nume: "Vizma", comuna: "Secas" },
  { nume: "Dragomiresti", comuna: "Stiuca" },
  { nume: "Olosag", comuna: "Stiuca" },
  { nume: "Zgribesti", comuna: "Stiuca" },
  { nume: "Nerau", comuna: "Teremia Mare" },
  { nume: "Teremia Mica", comuna: "Teremia Mare" },
  { nume: "Balosesti", comuna: "Tomesti" },
  { nume: "Colonia Fabricii", comuna: "Tomesti" },
  { nume: "Luncanii de Jos", comuna: "Tomesti" },
  { nume: "Luncanii de Sus", comuna: "Tomesti" },
  { nume: "Romanesti", comuna: "Tomesti" },
  { nume: "Cralovat", comuna: "Topolovatu Mare" },
  { nume: "Ictar-Budinti", comuna: "Topolovatu Mare" },
  { nume: "Iosifalau", comuna: "Topolovatu Mare" },
  { nume: "Sustra", comuna: "Topolovatu Mare" },
  { nume: "Topolovatu Mic", comuna: "Topolovatu Mare" },
  { nume: "Cadar", comuna: "Tormac" },
  { nume: "Sipet", comuna: "Tormac" },
  { nume: "Jupani", comuna: "Traian Vuia" },
  { nume: "Sudrias", comuna: "Traian Vuia" },
  { nume: "Surducu Mic", comuna: "Traian Vuia" },
  { nume: "Susani", comuna: "Traian Vuia" },
  { nume: "Saceni", comuna: "Traian Vuia" },
  { nume: "Iohanisfeld", comuna: "Uivar" },
  { nume: "Otelec", comuna: "Uivar" },
  { nume: "Pustinis", comuna: "Uivar" },
  { nume: "Rauti", comuna: "Uivar" },
  { nume: "Sanmartinu Maghiar", comuna: "Uivar" },
  { nume: "Gelu", comuna: "Varias" },
  { nume: "Sanpetru Mic", comuna: "Varias" },
  { nume: "Herendesti", comuna: "Victor Vlad Delamarina" },
  { nume: "Honorici", comuna: "Victor Vlad Delamarina" },
  { nume: "Petroasa Mare", comuna: "Victor Vlad Delamarina" },
  { nume: "Pini", comuna: "Victor Vlad Delamarina" },
  { nume: "Padureni", comuna: "Victor Vlad Delamarina" },
  { nume: "Visag", comuna: "Victor Vlad Delamarina" },
  { nume: "Folea", comuna: "Voiteg" },
];
