export const tl = [
  { nume: "Babadag" },
  { nume: "Baia" },
  { nume: "Beidaud" },
  { nume: "C.a. Rosetti" },
  { nume: "Carcaliu" },
  { nume: "Casimcea" },
  { nume: "Ceamurlia de Jos" },
  { nume: "Ceatalchioi" },
  { nume: "Cerna" },
  { nume: "Chilia Veche" },
  { nume: "Ciucurova" },
  { nume: "Crisan" },
  { nume: "Dorobantu" },
  { nume: "Daeni" },
  { nume: "Frecatei" },
  { nume: "Greci" },
  { nume: "Grindu" },
  { nume: "Hamcearca" },
  { nume: "Horia" },
  { nume: "I.c.brătianu", simplu: "I.c.bratianu" },
  { nume: "Isaccea" },
  { nume: "Izvoarele" },
  { nume: "Jijila" },
  { nume: "Jurilovca" },
  { nume: "Luncavita" },
  { nume: "Mahmudia" },
  { nume: "Maliuc" },
  { nume: "Mihai Bravu" },
  { nume: "Mihail Kogalniceanu" },
  { nume: "Murighiol" },
  { nume: "Macin" },
  { nume: "Nalbant" },
  { nume: "Niculitel" },
  { nume: "Nufaru" },
  { nume: "Ostrov" },
  { nume: "Pardina" },
  { nume: "Peceneaga" },
  { nume: "Sarichioi" },
  { nume: "Sfantu Gheorghe" },
  { nume: "Slava Cercheza" },
  { nume: "Smardan" },
  { nume: "Somova" },
  { nume: "Stejaru" },
  { nume: "Sulina" },
  { nume: "Topolog" },
  { nume: "Tulcea" },
  { nume: "Turcoaia" },
  { nume: "Valea Nucarilor" },
  { nume: "Vacareni" },
  { nume: "Camena", comuna: "Baia" },
  { nume: "Caugagia", comuna: "Baia" },
  { nume: "Ceamurlia de Sus", comuna: "Baia" },
  { nume: "Panduru", comuna: "Baia" },
  { nume: "Neatarnarea", comuna: "Beidaud" },
  { nume: "Sarighiol de Deal", comuna: "Beidaud" },
  { nume: "Cardon", comuna: "C.A. Rosetti" },
  { nume: "Letea", comuna: "C.A. Rosetti" },
  { nume: "Periprava", comuna: "C.A. Rosetti" },
  { nume: "Sfistofca", comuna: "C.A. Rosetti" },
  { nume: "Cismeaua Noua", comuna: "Casimcea" },
  { nume: "Corugea", comuna: "Casimcea" },
  { nume: "Haidar", comuna: "Casimcea" },
  { nume: "Rahman", comuna: "Casimcea" },
  { nume: "Razboieni", comuna: "Casimcea" },
  { nume: "Stanca", comuna: "Casimcea" },
  { nume: "Lunca", comuna: "Ceamurlia De Jos" },
  { nume: "Plauru", comuna: "Ceatalchioi" },
  { nume: "Patlageanca", comuna: "Ceatalchioi" },
  { nume: "Salceni", comuna: "Ceatalchioi" },
  { nume: "General Praporgescu", comuna: "Cerna" },
  { nume: "Mircea Voda", comuna: "Cerna" },
  { nume: "Traian", comuna: "Cerna" },
  { nume: "Caslita", comuna: "Chilia Veche" },
  { nume: "Ostrovu Tataru", comuna: "Chilia Veche" },
  { nume: "Tatanir", comuna: "Chilia Veche" },
  { nume: "Atmagea", comuna: "Ciucurova" },
  { nume: "Fantana Mare", comuna: "Ciucurova" },
  { nume: "Caraorman", comuna: "Crisan" },
  { nume: "Mila 23", comuna: "Crisan" },
  { nume: "Ardealu", comuna: "Dorobantu" },
  { nume: "Carjelari", comuna: "Dorobantu" },
  { nume: "Fantana Oilor", comuna: "Dorobantu" },
  { nume: "Mesteru", comuna: "Dorobantu" },
  { nume: "Cataloi", comuna: "Frecatei" },
  { nume: "Posta", comuna: "Frecatei" },
  { nume: "Telita", comuna: "Frecatei" },
  { nume: "Balabancea", comuna: "Hamcearca" },
  { nume: "Caprioara", comuna: "Hamcearca" },
  { nume: "Nifon", comuna: "Hamcearca" },
  { nume: "Closca", comuna: "Horia" },
  { nume: "Floresti", comuna: "Horia" },
  { nume: "Revarsarea", comuna: "Isaccea" },
  { nume: "Tichilesti", comuna: "Isaccea" },
  { nume: "Alba", comuna: "Izvoarele" },
  { nume: "Iulia", comuna: "Izvoarele" },
  { nume: "Valea Teilor", comuna: "Izvoarele" },
  { nume: "Garvan", comuna: "Jijila" },
  { nume: "Salcioara", comuna: "Jurilovca" },
  { nume: "Visina", comuna: "Jurilovca" },
  { nume: "Rachelu", comuna: "Luncavita" },
  { nume: "Bestepe", comuna: "Mahmudia" },
  { nume: "Baltenii de Jos", comuna: "Mahmudia" },
  { nume: "Baltenii de Sus", comuna: "Mahmudia" },
  { nume: "Gorgova", comuna: "Maliuc" },
  { nume: "Ilganii de Sus", comuna: "Maliuc" },
  { nume: "Partizani", comuna: "Maliuc" },
  { nume: "Vulturu", comuna: "Maliuc" },
  { nume: "Satu Nou", comuna: "Mihai Bravu" },
  { nume: "Turda", comuna: "Mihai Bravu" },
  { nume: "Lastuni", comuna: "Mihail Kogalniceanu" },
  { nume: "Randunica", comuna: "Mihail Kogalniceanu" },
  { nume: "Colina", comuna: "Murighiol" },
  { nume: "Dunavatu de Jos", comuna: "Murighiol" },
  { nume: "Dunavatu de Sus", comuna: "Murighiol" },
  { nume: "Plopul", comuna: "Murighiol" },
  { nume: "Sarinasuf", comuna: "Murighiol" },
  { nume: "Uzlina", comuna: "Murighiol" },
  { nume: "Nicolae Balcescu", comuna: "Nalbant" },
  { nume: "Trestenic", comuna: "Nalbant" },
  { nume: "Ilganii de Jos", comuna: "Nufaru" },
  { nume: "Malcoci", comuna: "Nufaru" },
  { nume: "Victoria", comuna: "Nufaru" },
  { nume: "Piatra", comuna: "Ostrov" },
  { nume: "Enisala", comuna: "Sarichioi" },
  { nume: "Sabangia", comuna: "Sarichioi" },
  { nume: "Visterna", comuna: "Sarichioi" },
  { nume: "Zebil", comuna: "Sarichioi" },
  { nume: "Slava Rusa", comuna: "Slava Cercheza" },
  { nume: "Mineri", comuna: "Somova" },
  { nume: "Parches", comuna: "Somova" },
  { nume: "Mina Altan Tepe", comuna: "Stejaru" },
  { nume: "Vasile Alecsandri", comuna: "Stejaru" },
  { nume: "Calfa", comuna: "Topolog" },
  { nume: "Cerbu", comuna: "Topolog" },
  { nume: "Fagarasu Nou", comuna: "Topolog" },
  { nume: "Luminita", comuna: "Topolog" },
  { nume: "Magurele", comuna: "Topolog" },
  { nume: "Sambata Noua", comuna: "Topolog" },
  { nume: "Tudor Vladimirescu", comuna: "Tulcea" },
  { nume: "Agighiol", comuna: "Valea Nucarilor" },
  { nume: "Iazurile", comuna: "Valea Nucarilor" },
];
