export const tm = [
  { nume: "Albina", comuna: "Mosnita Noua" },
  { nume: "Alioș", simplu: "Alios", comuna: "Masloc" },
  { nume: "Altringen", comuna: "Bogda" },
  { nume: "Babșa", simplu: "Babsa", comuna: "Belint" },
  { nume: "Bacova", comuna: "Buzias" },
  { nume: "Balinț", simplu: "Balint" },
  { nume: "Baloșești", simplu: "Balosesti", comuna: "Tomesti" },
  { nume: "Banloc" },
  { nume: "Bara" },
  { nume: "Bărăteaz", simplu: "Barateaz", comuna: "Satchinez" },
  { nume: "Bârna", simplu: "Barna" },
  { nume: "Bătești", simplu: "Batesti", comuna: "Faget" },
  { nume: "Bazoș", simplu: "Bazos", comuna: "Recas" },
  { nume: "Bazoșu Nou", simplu: "Bazosu Nou", comuna: "Remetea Mare" },
  { nume: "Beba Veche" },
  { nume: "Becicherecu Mic" },
  { nume: "Begheiu Mic", comuna: "Faget" },
  { nume: "Belinț", simplu: "Belint" },
  { nume: "Bencecu de Jos", comuna: "Pischia" },
  { nume: "Bencecu de Sus", comuna: "Pischia" },
  { nume: "Berecuța", simplu: "Berecuta", comuna: "Gataia" },
  { nume: "Beregsău Mare", simplu: "Beregsau Mare", comuna: "Sacalaz" },
  { nume: "Beregsău Mic", simplu: "Beregsau Mic", comuna: "Sacalaz" },
  { nume: "Berini", comuna: "Sacosu Turcesc" },
  { nume: "Bethausen" },
  { nume: "Bichigi", comuna: "Faget" },
  { nume: "Biled" },
  { nume: "Birda", comuna: "Gataia" },
  { nume: "Blajova", comuna: "Nitchidorf" },
  { nume: "Bobda", comuna: "Cenei" },
  { nume: "Bodo", comuna: "Balint" },
  { nume: "Bogda" },
  { nume: "Boldur" },
  { nume: "Botești", simplu: "Botesti", comuna: "Barna" },
  { nume: "Botinești", simplu: "Botinesti", comuna: "Barna" },
  { nume: "Brănești", simplu: "Branesti", comuna: "Faget" },
  { nume: "Breazova", comuna: "Margina" },
  { nume: "Breștea", simplu: "Brestea", comuna: "Denta" },
  { nume: "Brestovăț", simplu: "Brestovat" },
  { nume: "Bucovăț", simplu: "Bucovat", comuna: "Dumbrava" },
  { nume: "Bucovăț", simplu: "Bucovat", comuna: "Remetea Mare" },
  { nume: "Bulgăruș", simplu: "Bulgarus", comuna: "Lenauheim" },
  { nume: "Bulza", comuna: "Margina" },
  { nume: "Bunea Mare", comuna: "Faget" },
  { nume: "Bunea Mică", simplu: "Bunea Mica", comuna: "Faget" },
  { nume: "Butin", comuna: "Gataia" },
  { nume: "Buzad", comuna: "Bogda" },
  { nume: "Buziaș", simplu: "Buzias" },
  { nume: "Cadar", comuna: "Tormac" },
  { nume: "Călacea", simplu: "Calacea", comuna: "Ortisoara" },
  { nume: "Căpăt", simplu: "Capat", comuna: "Racovita" },
  { nume: "Carani", comuna: "Sanandrei" },
  { nume: "Cărpiniș", simplu: "Carpinis" },
  { nume: "Cebza", comuna: "Ciacova" },
  { nume: "Cenad" },
  { nume: "Cenei" },
  { nume: "Cerna", comuna: "Liebling" },
  { nume: "Cerneteaz", comuna: "Giarmata" },
  { nume: "Charlotenburg", comuna: "Bogda" },
  { nume: "Checea", comuna: "Cenei" },
  { nume: "Checheș", simplu: "Cheches", comuna: "Secas" },
  { nume: "Cheglevici", comuna: "Dudestii Vechi" },
  { nume: "Cherestur", comuna: "Beba Veche" },
  { nume: "Chevereșu Mare", simplu: "Cheveresu Mare" },
  { nume: "Chișoda", simplu: "Chisoda", comuna: "Giroc" },
  { nume: "Chizătău", simplu: "Chizatau", comuna: "Belint" },
  { nume: "Ciacova" },
  { nume: "Cireșu Mic", simplu: "Ciresu Mic", comuna: "Criciova" },
  { nume: "Cireșu", simplu: "Ciresu", comuna: "Criciova" },
  { nume: "Cladova", comuna: "Bethausen" },
  { nume: "Cliciova", comuna: "Bethausen" },
  { nume: "Clopodia", comuna: "Jamu Mare" },
  {
    nume: "Colonia Bulgară",
    simplu: "Colonia Bulgara",
    comuna: "Dudestii Vechi",
  },
  { nume: "Colonia Fabricii", comuna: "Tomesti" },
  { nume: "Colonia Mică", simplu: "Colonia Mica", comuna: "Faget" },
  { nume: "Comeat", comuna: "Bogda" },
  { nume: "Comloșu Mare", simplu: "Comlosu Mare" },
  { nume: "Comloșu Mic", simplu: "Comlosu Mic", comuna: "Comlosu Mare" },
  { nume: "Cornești", simplu: "Cornesti", comuna: "Ortisoara" },
  { nume: "Coșarii", simplu: "Cosarii", comuna: "Brestovat" },
  { nume: "Coșava", simplu: "Cosava", comuna: "Curtea" },
  { nume: "Coșevița", simplu: "Cosevita", comuna: "Margina" },
  { nume: "Coșteiu de Sus", simplu: "Costeiu de Sus", comuna: "Margina" },
  { nume: "Coșteiu", simplu: "Costeiu" },
  { nume: "Covaci", comuna: "Sanandrei" },
  { nume: "Crai Nou", comuna: "Giulvaz" },
  { nume: "Cralovăț", simplu: "Cralovat", comuna: "Topolovatu Mare" },
  { nume: "Criciova" },
  { nume: "Crivina de Sus", comuna: "Pietroasa" },
  { nume: "Crivina", comuna: "Nadrag" },
  { nume: "Crivobara", comuna: "Secas" },
  { nume: "Cruceni", comuna: "Foeni" },
  { nume: "Curtea" },
  { nume: "Cutina", comuna: "Bethausen" },
  { nume: "Darova" },
  { nume: "Dejan", comuna: "Moravita" },
  { nume: "Denta" },
  { nume: "Deta" },
  { nume: "Diniaș", simplu: "Dinias", comuna: "Peciu Nou" },
  { nume: "Dobrești", simplu: "Dobresti", comuna: "Bara" },
  { nume: "Dolaț", simplu: "Dolat", comuna: "Banloc" },
  { nume: "Drăgoiești", simplu: "Dragoiesti", comuna: "Racovita" },
  { nume: "Dragomirești", simplu: "Dragomiresti", comuna: "Stiuca" },
  { nume: "Dragșina", simplu: "Dragsina", comuna: "Cheveresu Mare" },
  { nume: "Drăgsinești", simplu: "Dragsinesti", comuna: "Fardea" },
  { nume: "Drinova", comuna: "Barna" },
  { nume: "Dubești", simplu: "Dubesti", comuna: "Ohaba Lunga" },
  { nume: "Duboz", comuna: "Nitchidorf" },
  { nume: "Dudeștii Noi", simplu: "Dudestii Noi", comuna: "Becicherecu Mic" },
  { nume: "Dudeștii Vechi", simplu: "Dudestii Vechi" },
  { nume: "Dumbrava" },
  { nume: "Dumbrăvița", simplu: "Dumbravita" },
  { nume: "Fădimac", simplu: "Fadimac", comuna: "Balint" },
  { nume: "Făget", simplu: "Faget" },
  { nume: "Fărășești", simplu: "Farasesti", comuna: "Pietroasa" },
  { nume: "Fârdea", simplu: "Fardea" },
  { nume: "Ferendia", comuna: "Jamu Mare" },
  { nume: "Fibiș", simplu: "Fibis", comuna: "Masloc" },
  { nume: "Ficătar", simplu: "Ficatar", comuna: "Racovita" },
  { nume: "Foeni" },
  { nume: "Folea", comuna: "Voiteg" },
  { nume: "Gad", comuna: "Ciacova" },
  { nume: "Gaiu Mic", comuna: "Moravita" },
  { nume: "Gătaia", simplu: "Gataia" },
  { nume: "Gavojdia" },
  { nume: "Gelu", comuna: "Varias" },
  { nume: "Gherman", comuna: "Jamu Mare" },
  { nume: "Ghilad", comuna: "Ciacova" },
  { nume: "Ghiroda" },
  { nume: "Ghizela" },
  { nume: "Giarmata-Vii", comuna: "Ghiroda" },
  { nume: "Giarmata" },
  { nume: "Giera" },
  { nume: "Giroc" },
  { nume: "Giulvăz", simplu: "Giulvaz" },
  { nume: "Gladna Montană", simplu: "Gladna Montana", comuna: "Fardea" },
  { nume: "Gladna Româna", simplu: "Gladna Romana", comuna: "Fardea" },
  { nume: "Gottlob", comuna: "Lovrin" },
  { nume: "Grabăț", simplu: "Grabat", comuna: "Lenauheim" },
  { nume: "Grănicerii", simplu: "Granicerii", comuna: "Giera" },
  { nume: "Groși", simplu: "Grosi", comuna: "Margina" },
  { nume: "Gruni", comuna: "Belint" },
  { nume: "Hăuzești", simplu: "Hauzesti", comuna: "Fardea" },
  {
    nume: "Herendești",
    simplu: "Herendesti",
    comuna: "Victor Vlad Delamarina",
  },
  { nume: "Herneacova", comuna: "Recas" },
  { nume: "Hezeriș", simplu: "Hezeris", comuna: "Costeiu" },
  { nume: "Hisiaș", simplu: "Hisias", comuna: "Ghizela" },
  { nume: "Hitiaș", simplu: "Hitias", comuna: "Racovita" },
  { nume: "Hodoni", comuna: "Satchinez" },
  { nume: "Hodoș", simplu: "Hodos", comuna: "Brestovat" },
  { nume: "Hodoș", simplu: "Hodos", comuna: "Darova" },
  { nume: "Homojdia", comuna: "Curtea" },
  { nume: "Honorici", comuna: "Victor Vlad Delamarina" },
  { nume: "Ianova", comuna: "Remetea Mare" },
  { nume: "Icloda", comuna: "Sacosu Turcesc" },
  { nume: "Ictar-Budinți", simplu: "Ictar-Budinti", comuna: "Topolovatu Mare" },
  { nume: "Iecea Mare", comuna: "Carpinis" },
  { nume: "Iecea Mică", simplu: "Iecea Mica", comuna: "Carpinis" },
  { nume: "Ierșnic", simplu: "Iersnic", comuna: "Ohaba Lunga" },
  { nume: "Igriș", simplu: "Igris", comuna: "Sanpetru Mare" },
  { nume: "Iohanisfeld", comuna: "Uivar" },
  { nume: "Iosif", comuna: "Liebling" },
  { nume: "Iosifalău", simplu: "Iosifalau", comuna: "Topolovatu Mare" },
  { nume: "Ivanda", comuna: "Giulvaz" },
  { nume: "Izvin", comuna: "Recas" },
  { nume: "Jabăr", simplu: "Jabar", comuna: "Boldur" },
  { nume: "Jamu Mare" },
  { nume: "Jdioara", comuna: "Criciova" },
  { nume: "Jebel" },
  { nume: "Jena", comuna: "Gavojdia" },
  { nume: "Jimbolia" },
  { nume: "Jupânești", simplu: "Jupanesti", comuna: "Faget" },
  { nume: "Jupani", comuna: "Traian Vuia" },
  { nume: "Jurești", simplu: "Juresti", comuna: "Barna" },
  { nume: "Lăpușnic", simplu: "Lapusnic", comuna: "Bara" },
  { nume: "Lățunaș", simplu: "Latunas", comuna: "Jamu Mare" },
  { nume: "Lenauheim" },
  { nume: "Leucușești", simplu: "Leucusesti", comuna: "Bethausen" },
  { nume: "Liebling" },
  { nume: "Livezile", comuna: "Banloc" },
  { nume: "Lovrin" },
  { nume: "Lucareț", simplu: "Lucaret", comuna: "Brestovat" },
  { nume: "Lugoj" },
  { nume: "Lugojel", comuna: "Gavojdia" },
  { nume: "Luncanii de Jos", comuna: "Tomesti" },
  { nume: "Luncanii de Sus", comuna: "Tomesti" },
  { nume: "Lunga", comuna: "Comlosu Mare" },
  { nume: "Macedonia", comuna: "Ciacova" },
  { nume: "Măguri", simplu: "Maguri", comuna: "Lugoj" },
  { nume: "Mânăstire", simplu: "Manastire", comuna: "Gataia" },
  { nume: "Mănăștiur", simplu: "Manastiur" },
  { nume: "Margina" },
  { nume: "Mașloc", simplu: "Masloc" },
  { nume: "Mâtnicu Mic", simplu: "Matnicu Mic", comuna: "Fardea" },
  { nume: "Moravița", simplu: "Moravita" },
  { nume: "Moșnița Nouă", simplu: "Mosnita Noua" },
  { nume: "Moșnița Veche", simplu: "Mosnita Veche", comuna: "Mosnita Noua" },
  { nume: "Murani", comuna: "Pischia" },
  { nume: "Nadăș", simplu: "Nadas", comuna: "Recas" },
  { nume: "Nădrag", simplu: "Nadrag" },
  { nume: "Nemeșești", simplu: "Nemesesti", comuna: "Margina" },
  { nume: "Nerău", simplu: "Nerau", comuna: "Teremia Mare" },
  { nume: "Nevrincea", comuna: "Bethausen" },
  { nume: "Nițchidorf", simplu: "Nitchidorf" },
  { nume: "Obad", comuna: "Ciacova" },
  { nume: "Ofsenița", simplu: "Ofsenita", comuna: "Banloc" },
  { nume: "Ohaba Lungă", simplu: "Ohaba Lunga" },
  { nume: "Ohaba Română", simplu: "Ohaba Romana", comuna: "Ohaba Lunga" },
  { nume: "Ohaba-Forgaci", comuna: "Boldur" },
  { nume: "Oloșag", simplu: "Olosag", comuna: "Stiuca" },
  { nume: "Opatița", simplu: "Opatita", comuna: "Deta" },
  { nume: "Orțișoara", simplu: "Ortisoara" },
  { nume: "Otelec", comuna: "Uivar" },
  { nume: "Otvești", simplu: "Otvesti", comuna: "Sacosu Turcesc" },
  { nume: "Pădurani", simplu: "Padurani", comuna: "Manastiur" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Jebel" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Victor Vlad Delamarina" },
  { nume: "Paniova", comuna: "Ghizela" },
  { nume: "Parța", simplu: "Parta", comuna: "Sag" },
  { nume: "Partoș", simplu: "Partos", comuna: "Banloc" },
  { nume: "Păru", simplu: "Paru", comuna: "Costeiu" },
  { nume: "Peciu Nou" },
  { nume: "Percosova", comuna: "Gataia" },
  { nume: "Periam" },
  { nume: "Pesac", comuna: "Periam" },
  { nume: "Petroasa Mare", comuna: "Victor Vlad Delamarina" },
  { nume: "Petroman", comuna: "Ciacova" },
  { nume: "Petrovaselo", comuna: "Recas" },
  { nume: "Pietroasa" },
  { nume: "Pini", comuna: "Victor Vlad Delamarina" },
  { nume: "Pișchia", simplu: "Pischia" },
  { nume: "Pogănești", simplu: "Poganesti", comuna: "Barna" },
  { nume: "Poieni", comuna: "Pietroasa" },
  { nume: "Pordeanu", comuna: "Beba Veche" },
  { nume: "Povârgina", simplu: "Povargina", comuna: "Faget" },
  { nume: "Pustiniș", simplu: "Pustinis", comuna: "Uivar" },
  { nume: "Răchita", simplu: "Rachita", comuna: "Dumbrava" },
  { nume: "Racovița", simplu: "Racovita" },
  { nume: "Rădmănești", simplu: "Radmanesti", comuna: "Bara" },
  { nume: "Răuți", simplu: "Rauti", comuna: "Uivar" },
  { nume: "Recaș", simplu: "Recas" },
  { nume: "Remetea Mare" },
  { nume: "Remetea Mică", simplu: "Remetea Mica", comuna: "Masloc" },
  { nume: "Remetea-Luncă", simplu: "Remetea-Lunca", comuna: "Manastiur" },
  { nume: "Românești", simplu: "Romanesti", comuna: "Tomesti" },
  { nume: "Rovinița Mare", simplu: "Rovinita Mare", comuna: "Denta" },
  { nume: "Rovinița Mică", simplu: "Rovinita Mica", comuna: "Denta" },
  { nume: "Rudicica", comuna: "Mosnita Noua" },
  { nume: "Rudna", comuna: "Giulvaz" },
  { nume: "Săcălaz", simplu: "Sacalaz" },
  { nume: "Săceni", simplu: "Saceni", comuna: "Traian Vuia" },
  { nume: "Sacoșu Mare", simplu: "Sacosu Mare", comuna: "Darova" },
  { nume: "Sacoșu Turcesc", simplu: "Sacosu Turcesc" },
  { nume: "Șag", simplu: "Sag" },
  { nume: "Sălbăgel", simplu: "Salbagel", comuna: "Gavojdia" },
  { nume: "Sălciua Nouă", simplu: "Salciua Noua", comuna: "Pischia" },
  { nume: "Sânandrei", simplu: "Sanandrei" },
  { nume: "Șandra", simplu: "Sandra", comuna: "Biled" },
  { nume: "Sângeorge", simplu: "Sangeorge", comuna: "Gataia" },
  { nume: "Sânmartinu Maghiar", simplu: "Sanmartinu Maghiar", comuna: "Uivar" },
  {
    nume: "Sânmartinu Sârbesc",
    simplu: "Sanmartinu Sarbesc",
    comuna: "Peciu Nou",
  },
  {
    nume: "Sânmihaiu German",
    simplu: "Sanmihaiu German",
    comuna: "Sanmihaiu Roman",
  },
  { nume: "Sânmihaiu Român", simplu: "Sanmihaiu Roman" },
  { nume: "Sânnicolau Mare", simplu: "Sannicolau Mare" },
  { nume: "Șanovița", simplu: "Sanovita", comuna: "Ghizela" },
  { nume: "Sânpetru Mare", simplu: "Sanpetru Mare" },
  { nume: "Sânpetru Mic", simplu: "Sanpetru Mic", comuna: "Varias" },
  { nume: "Saravale", comuna: "Sanpetru Mare" },
  { nume: "Sărăzani", simplu: "Sarazani", comuna: "Barna" },
  { nume: "Sârbova", simplu: "Sarbova", comuna: "Racovita" },
  { nume: "Satchinez" },
  { nume: "Sculia", comuna: "Gataia" },
  { nume: "Secaș", simplu: "Secas" },
  { nume: "Seceani", comuna: "Ortisoara" },
  { nume: "Șemlacu Mare", simplu: "Semlacu Mare", comuna: "Gataia" },
  { nume: "Șemlacu Mic", simplu: "Semlacu Mic", comuna: "Gataia" },
  { nume: "Silagiu", comuna: "Buzias" },
  { nume: "Sinersig", comuna: "Boldur" },
  { nume: "Sintar", comuna: "Bogda" },
  { nume: "Sintești", simplu: "Sintesti", comuna: "Margina" },
  { nume: "Șipet", simplu: "Sipet", comuna: "Tormac" },
  { nume: "Soca", comuna: "Banloc" },
  { nume: "Spata", comuna: "Bara" },
  { nume: "Stamora Germană", simplu: "Stamora Germana", comuna: "Moravita" },
  {
    nume: "Stamora Română",
    simplu: "Stamora Romana",
    comuna: "Sacosu Turcesc",
  },
  { nume: "Stanciova", comuna: "Recas" },
  { nume: "Știuca", simplu: "Stiuca" },
  { nume: "Sudriaș", simplu: "Sudrias", comuna: "Traian Vuia" },
  { nume: "Surducu Mic", comuna: "Traian Vuia" },
  { nume: "Susani", comuna: "Traian Vuia" },
  { nume: "Suștra", simplu: "Sustra", comuna: "Topolovatu Mare" },
  { nume: "Tapia", comuna: "Lugoj" },
  { nume: "Târgoviște", simplu: "Targoviste", comuna: "Balint" },
  { nume: "Temerești", simplu: "Temeresti", comuna: "Faget" },
  { nume: "Teremia Mare" },
  { nume: "Teremia Mică", simplu: "Teremia Mica", comuna: "Teremia Mare" },
  { nume: "Teș", simplu: "Tes", comuna: "Brestovat" },
  { nume: "Timișoara", simplu: "Timisoara" },
  { nume: "Țipari", simplu: "Tipari", comuna: "Costeiu" },
  { nume: "Toager", comuna: "Giera" },
  { nume: "Tomești", simplu: "Tomesti" },
  { nume: "Tomnatic", comuna: "Lovrin" },
  { nume: "Topla", comuna: "Manastiur" },
  { nume: "Topolovățu Mare", simplu: "Topolovatu Mare" },
  {
    nume: "Topolovățu Mic",
    simplu: "Topolovatu Mic",
    comuna: "Topolovatu Mare",
  },
  { nume: "Tormac" },
  { nume: "Traian Vuia" },
  { nume: "Uihei", comuna: "Biled" },
  { nume: "Uivar" },
  { nume: "Uliuc", comuna: "Sacosu Turcesc" },
  { nume: "Unip", comuna: "Sacosu Turcesc" },
  { nume: "Urseni", comuna: "Mosnita Noua" },
  { nume: "Utvin", comuna: "Sanmihaiu Roman" },
  { nume: "Vălcani", simplu: "Valcani", comuna: "Dudestii Vechi" },
  {
    nume: "Valea Lungă Română",
    simplu: "Valea Lunga Romana",
    comuna: "Costeiu",
  },
  { nume: "Variaș", simplu: "Varias" },
  { nume: "Victor Vlad Delamarina" },
  { nume: "Vișag", simplu: "Visag", comuna: "Victor Vlad Delamarina" },
  { nume: "Vizejdia", comuna: "Lovrin" },
  { nume: "Vizma", comuna: "Secas" },
  { nume: "Voiteg" },
  { nume: "Vucova", comuna: "Cheveresu Mare" },
  { nume: "Zgribești", simplu: "Zgribesti", comuna: "Stiuca" },
  { nume: "Zolt", comuna: "Fardea" },
  { nume: "Zorani", comuna: "Margina" },
];
