export const tr = [
  { nume: "Alexandria" },
  { nume: "Balaci" },
  { nume: "Blejesti" },
  { nume: "Bogdana" },
  { nume: "Botoroaga" },
  { nume: "Bragadiru" },
  { nume: "Branceni" },
  { nume: "Bujoreni" },
  { nume: "Bujoru" },
  { nume: "Buzescu" },
  { nume: "Babaita" },
  { nume: "Cervenia" },
  { nume: "Ciuperceni" },
  { nume: "Contesti" },
  { nume: "Cosmesti" },
  { nume: "Crevenicu" },
  { nume: "Crangeni" },
  { nume: "Crangu" },
  { nume: "Calinesti" },
  { nume: "Calmatuiu" },
  { nume: "Calmatuiu de Sus" },
  { nume: "Didesti" },
  { nume: "Dobrotesti" },
  { nume: "Dracsenei" },
  { nume: "Draganesti de Vede" },
  { nume: "Draganesti-Vlasca" },
  { nume: "Frumoasa" },
  { nume: "Furculesti" },
  { nume: "Gratia" },
  { nume: "Galateni" },
  { nume: "Islaz" },
  { nume: "Izvoarele" },
  { nume: "Lisa" },
  { nume: "Lita" },
  { nume: "Lunca" },
  { nume: "Mavrodin" },
  { nume: "Mosteni" },
  { nume: "Marzanesti" },
  { nume: "Magura" },
  { nume: "Maldaeni" },
  { nume: "Nanov" },
  { nume: "Necsesti" },
  { nume: "Nenciulesti" },
  { nume: "Nasturelu" },
  { nume: "Olteni" },
  { nume: "Peretu" },
  { nume: "Piatra" },
  { nume: "Pietrosani" },
  { nume: "Plopii-Slavitesti" },
  { nume: "Plosca" },
  { nume: "Poeni" },
  { nume: "Poroschia" },
  { nume: "Putineiu" },
  { nume: "Rosiori de Vede" },
  { nume: "Rasmiresti" },
  { nume: "Salcia" },
  { nume: "Scrioastea" },
  { nume: "Scurtu Mare" },
  { nume: "Seaca" },
  { nume: "Segarcea-Vale" },
  { nume: "Sfintesti" },
  { nume: "Silistea" },
  { nume: "Silistea-Gumesti" },
  { nume: "Slobozia Mandra" },
  { nume: "Smardioasa" },
  { nume: "Stejaru" },
  { nume: "Suhaia" },
  { nume: "Sarbeni" },
  { nume: "Saceni" },
  { nume: "Traian" },
  { nume: "Trivalea-Mosteni" },
  { nume: "Troianul" },
  { nume: "Turnu Magurele" },
  { nume: "Tatarastii de Jos" },
  { nume: "Tatarastii de Sus" },
  { nume: "Vedea" },
  { nume: "Videle" },
  { nume: "Viisoara" },
  { nume: "Vitanesti" },
  { nume: "Zimnicea" },
  { nume: "Zambreasca" },
  { nume: "Storobaneasa" },
  { nume: "Tiganesti" },
  { nume: "Clanita", comuna: "Babaita" },
  { nume: "Frasinet", comuna: "Babaita" },
  { nume: "Merisani", comuna: "Babaita" },
  { nume: "Burdeni", comuna: "Balaci" },
  { nume: "Tecuci", comuna: "Balaci" },
  { nume: "Baciu", comuna: "Blejesti" },
  { nume: "Sericu", comuna: "Blejesti" },
  { nume: "Brosteanca", comuna: "Bogdana" },
  { nume: "Ulmeni", comuna: "Bogdana" },
  { nume: "Urluiu", comuna: "Bogdana" },
  { nume: "Calugaru", comuna: "Botoroaga" },
  { nume: "Tunari", comuna: "Botoroaga" },
  { nume: "Tarnava", comuna: "Botoroaga" },
  { nume: "Valea Ciresului", comuna: "Botoroaga" },
  { nume: "Darvas", comuna: "Bujoreni" },
  { nume: "Prunaru", comuna: "Bujoreni" },
  { nume: "Antonesti", comuna: "Calinesti" },
  { nume: "Copaceanca", comuna: "Calinesti" },
  { nume: "Licuriciu", comuna: "Calinesti" },
  { nume: "Marita", comuna: "Calinesti" },
  { nume: "Bujoru", comuna: "Calmatuiu" },
  { nume: "Caravaneti", comuna: "Calmatuiu" },
  { nume: "Nicolae Balcescu", comuna: "Calmatuiu" },
  { nume: "Bacalesti", comuna: "Calmatuiu De Sus" },
  { nume: "Ionascu", comuna: "Calmatuiu De Sus" },
  { nume: "Baldovinesti", comuna: "Ciolanesti" },
  { nume: "Ciolanestii din Deal", comuna: "Ciolanesti" },
  { nume: "Ciolanestii din Vale", comuna: "Ciolanesti" },
  { nume: "Poiana", comuna: "Ciuperceni" },
  { nume: "Ciuperceni", comuna: "Cosmesti" },
  { nume: "Balta Sarata", comuna: "Crangeni" },
  { nume: "Dorobantu", comuna: "Crangeni" },
  { nume: "Stejaru", comuna: "Crangeni" },
  { nume: "Dracea", comuna: "Crangu" },
  { nume: "Florica", comuna: "Crangu" },
  { nume: "Secara", comuna: "Crangu" },
  { nume: "Zlata", comuna: "Crangu" },
  { nume: "Radulesti", comuna: "Crevenicu" },
  { nume: "Satu Nou", comuna: "Didesti" },
  { nume: "Insuratei", comuna: "Didesti" },
  { nume: "Merisani", comuna: "Dobrotesti" },
  { nume: "Beuca", comuna: "Dracsenei" },
  { nume: "Dracsani", comuna: "Dracsenei" },
  { nume: "Odobeasca", comuna: "Dracsenei" },
  { nume: "Plopi", comuna: "Dracsenei" },
  { nume: "Satul Vechi", comuna: "Dracsenei" },
  { nume: "Magura cu Liliac", comuna: "Draganesti De Vede" },
  { nume: "Vacaresti", comuna: "Draganesti De Vede" },
  { nume: "Comoara", comuna: "Draganesti-Vlasca" },
  { nume: "Vaceni", comuna: "Draganesti-Vlasca" },
  { nume: "Pauleasca", comuna: "Frumoasa" },
  { nume: "Mosteni", comuna: "Furculesti" },
  { nume: "Spatarei", comuna: "Furculesti" },
  { nume: "Voievoda", comuna: "Furculesti" },
  { nume: "Bascoveni", comuna: "Galateni" },
  { nume: "Gradisteanca", comuna: "Galateni" },
  { nume: "Ciurari-Deal", comuna: "Gratia" },
  { nume: "Draghinesti", comuna: "Gratia" },
  { nume: "Moldoveni", comuna: "Islaz" },
  { nume: "Vanatori", comuna: "Lisa" },
  { nume: "Pleasov", comuna: "Lunca" },
  { nume: "Prundu", comuna: "Lunca" },
  { nume: "Saelele", comuna: "Lunca" },
  { nume: "Guruieni", comuna: "Magura" },
  { nume: "Cernetu", comuna: "Marzanesti" },
  { nume: "Teleormanu", comuna: "Marzanesti" },
  { nume: "Valea Parului", comuna: "Marzanesti" },
  { nume: "Merenii de Jos", comuna: "Mereni" },
  { nume: "Merenii de Sus", comuna: "Mereni" },
  { nume: "Stefeni", comuna: "Mereni" },
  { nume: "Zimnicele", comuna: "Nasturelu" },
  { nume: "Belciug", comuna: "Necsesti" },
  { nume: "Gardesti", comuna: "Necsesti" },
  { nume: "Paru Rotund", comuna: "Nenciulesti" },
  { nume: "Perii Brosteni", comuna: "Olteni" },
  { nume: "Laceni", comuna: "Orbeasca" },
  { nume: "Orbeasca de Jos", comuna: "Orbeasca" },
  { nume: "Orbeasca de Sus", comuna: "Orbeasca" },
  { nume: "Beciu", comuna: "Plopii-Slavitesti" },
  { nume: "Brancoveanca", comuna: "Plopii-Slavitesti" },
  { nume: "Barsestii de Jos", comuna: "Plopii-Slavitesti" },
  { nume: "Dudu", comuna: "Plopii-Slavitesti" },
  { nume: "Smardan", comuna: "Plopii-Slavitesti" },
  { nume: "Banov", comuna: "Poeni" },
  { nume: "Bratesti", comuna: "Poeni" },
  { nume: "Catunu", comuna: "Poeni" },
  { nume: "Preajba", comuna: "Poeni" },
  { nume: "Vatasi", comuna: "Poeni" },
  { nume: "Tavarlau", comuna: "Poeni" },
  { nume: "Calomfiresti", comuna: "Poroschia" },
  { nume: "Baduleasa", comuna: "Putineiu" },
  { nume: "Carlomanu", comuna: "Putineiu" },
  { nume: "Cetatea", comuna: "Radoiesti" },
  { nume: "Radoiesti-Deal", comuna: "Radoiesti" },
  { nume: "Radoiesti-Vale", comuna: "Radoiesti" },
  { nume: "Ludaneasca", comuna: "Rasmiresti" },
  { nume: "Butculesti", comuna: "Saceni" },
  { nume: "Ciurari", comuna: "Saceni" },
  { nume: "Baneasa", comuna: "Salcia" },
  { nume: "Tudor Vladimirescu", comuna: "Salcia" },
  { nume: "Sarbenii de Jos", comuna: "Sarbeni" },
  { nume: "Udeni", comuna: "Sarbeni" },
  { nume: "Brebina", comuna: "Scrioastea" },
  { nume: "Cucueti", comuna: "Scrioastea" },
  { nume: "Viile", comuna: "Scrioastea" },
  { nume: "Albeni", comuna: "Scurtu Mare" },
  { nume: "Dracesti", comuna: "Scurtu Mare" },
  { nume: "Negrilesti", comuna: "Scurtu Mare" },
  { nume: "Scurtu-Slavesti", comuna: "Scurtu Mare" },
  { nume: "Valea Postei", comuna: "Scurtu Mare" },
  { nume: "Navodari", comuna: "Seaca" },
  { nume: "Olteanca", comuna: "Segarcea-Vale" },
  { nume: "Segarcea-Deal", comuna: "Segarcea-Vale" },
  { nume: "Butesti", comuna: "Silistea" },
  { nume: "Purani", comuna: "Silistea" },
  { nume: "Puranii de Sus", comuna: "Silistea" },
  { nume: "Silistea Mica", comuna: "Silistea" },
  { nume: "Uda-Clocociov", comuna: "Slobozia Mandra" },
  { nume: "Uda-Paciurea", comuna: "Slobozia Mandra" },
  { nume: "Soimu", comuna: "Smardioasa" },
  { nume: "Bratcovu", comuna: "Stejaru" },
  { nume: "Gresia", comuna: "Stejaru" },
  { nume: "Socetu", comuna: "Stejaru" },
  { nume: "Beiu", comuna: "Storobaneasa" },
  { nume: "Fantanele", comuna: "Suhaia" },
  { nume: "Linia Costii", comuna: "Talpa" },
  { nume: "Rotaresti", comuna: "Talpa" },
  { nume: "Talpa Postei", comuna: "Talpa" },
  { nume: "Talpa-Bascoveni", comuna: "Talpa" },
  { nume: "Talpa-Ograzile", comuna: "Talpa" },
  { nume: "Lada", comuna: "Tatarastii De Jos" },
  { nume: "Negreni", comuna: "Tatarastii De Jos" },
  { nume: "Negrenii de Sus", comuna: "Tatarastii De Jos" },
  { nume: "Negrenii-Osebiti", comuna: "Tatarastii De Jos" },
  { nume: "Obartu", comuna: "Tatarastii De Jos" },
  { nume: "Slavesti", comuna: "Tatarastii De Jos" },
  { nume: "Dobreni", comuna: "Tatarastii De Sus" },
  { nume: "Udupu", comuna: "Tatarastii De Sus" },
  { nume: "Bratasani", comuna: "Trivalea-Mosteni" },
  { nume: "Deparati", comuna: "Trivalea-Mosteni" },
  { nume: "Dulceni", comuna: "Troianul" },
  { nume: "Vatra", comuna: "Troianul" },
  { nume: "Garagau", comuna: "Vartoape" },
  { nume: "Vartoapele de Jos", comuna: "Vartoape" },
  { nume: "Vartoapele de Sus", comuna: "Vartoape" },
  { nume: "Albesti", comuna: "Vedea" },
  { nume: "Cosoteni", comuna: "Vedea" },
  { nume: "Dulceanca", comuna: "Vedea" },
  { nume: "Meri", comuna: "Vedea" },
  { nume: "Cosoaia", comuna: "Videle" },
  { nume: "Purani", comuna: "Vitanesti" },
  { nume: "Schitu Poienari", comuna: "Vitanesti" },
  { nume: "Silistea", comuna: "Vitanesti" },
];
