export const tr = [
  { nume: "Albeni", comuna: "Scurtu Mare" },
  { nume: "Albeşti", simplu: "Albesti", comuna: "Vedea" },
  { nume: "Alexandria" },
  { nume: "Antoneşti", simplu: "Antonesti", comuna: "Calinesti" },
  { nume: "Băbăiţa", simplu: "Babaita" },
  { nume: "Băcăleşti", simplu: "Bacalesti", comuna: "Calmatuiu De Sus" },
  { nume: "Baciu", comuna: "Blejesti" },
  { nume: "Băduleasa", simplu: "Baduleasa", comuna: "Putineiu" },
  { nume: "Balaci" },
  { nume: "Baldovineşti", simplu: "Baldovinesti", comuna: "Ciolanesti" },
  { nume: "Balta Sărată", simplu: "Balta Sarata", comuna: "Crangeni" },
  { nume: "Băneasa", simplu: "Baneasa", comuna: "Salcia" },
  { nume: "Banov", comuna: "Poeni" },
  {
    nume: "Bârseştii de Jos",
    simplu: "Barsestii de Jos",
    comuna: "Plopii-Slavitesti",
  },
  { nume: "Bâscoveni", simplu: "Bascoveni", comuna: "Galateni" },
  { nume: "Beciu", comuna: "Plopii-Slavitesti" },
  { nume: "Beiu", comuna: "Storobaneasa" },
  { nume: "Belciug", comuna: "Necsesti" },
  { nume: "Beuca", comuna: "Dracsenei" },
  { nume: "Blejeşti", simplu: "Blejesti" },
  { nume: "Bogdana" },
  { nume: "Botoroaga" },
  { nume: "Bragadiru" },
  { nume: "Brânceni", simplu: "Branceni" },
  { nume: "Brâncoveanca", simplu: "Brancoveanca", comuna: "Plopii-Slavitesti" },
  { nume: "Brătăşani", simplu: "Bratasani", comuna: "Trivalea-Mosteni" },
  { nume: "Bratcovu", comuna: "Stejaru" },
  { nume: "Brăteşti", simplu: "Bratesti", comuna: "Poeni" },
  { nume: "Brebina", comuna: "Scrioastea" },
  { nume: "Broşteanca", simplu: "Brosteanca", comuna: "Bogdana" },
  { nume: "Bujoreni" },
  { nume: "Bujoru" },
  { nume: "Bujoru", comuna: "Calmatuiu" },
  { nume: "Burdeni", comuna: "Balaci" },
  { nume: "Butculeşti", simplu: "Butculesti", comuna: "Saceni" },
  { nume: "Buteşti", simplu: "Butesti", comuna: "Silistea" },
  { nume: "Buzescu" },
  { nume: "Călineşti", simplu: "Calinesti" },
  { nume: "Călmăţuiu de Sus", simplu: "Calmatuiu de Sus" },
  { nume: "Călmăţuiu", simplu: "Calmatuiu" },
  { nume: "Calomfireşti", simplu: "Calomfiresti", comuna: "Poroschia" },
  { nume: "Călugaru", simplu: "Calugaru", comuna: "Botoroaga" },
  { nume: "Caravaneţi", simplu: "Caravaneti", comuna: "Calmatuiu" },
  { nume: "Cârlomanu", simplu: "Carlomanu", comuna: "Putineiu" },
  { nume: "Cătunu", simplu: "Catunu", comuna: "Poeni" },
  { nume: "Cernetu", comuna: "Marzanesti" },
  { nume: "Cervenia" },
  { nume: "Cetatea", comuna: "Radoiesti" },
  {
    nume: "Ciolăneştii din Deal",
    simplu: "Ciolanestii din Deal",
    comuna: "Ciolanesti",
  },
  {
    nume: "Ciolăneştii din Vale",
    simplu: "Ciolanestii din Vale",
    comuna: "Ciolanesti",
  },
  { nume: "Ciuperceni" },
  { nume: "Ciuperceni", comuna: "Cosmesti" },
  { nume: "Ciurari-Deal", comuna: "Gratia" },
  { nume: "Ciurari", comuna: "Saceni" },
  { nume: "Clăniţa", simplu: "Clanita", comuna: "Babaita" },
  { nume: "Comoara", comuna: "Draganesti-Vlasca" },
  { nume: "Conţeşti", simplu: "Contesti" },
  { nume: "Copăceanca", simplu: "Copaceanca", comuna: "Calinesti" },
  { nume: "Cosmeşti", simplu: "Cosmesti" },
  { nume: "Coşoaia", simplu: "Cosoaia", comuna: "Videle" },
  { nume: "Coşoteni", simplu: "Cosoteni", comuna: "Vedea" },
  { nume: "Crângeni", simplu: "Crangeni" },
  { nume: "Crângu", simplu: "Crangu" },
  { nume: "Crevenicu" },
  { nume: "Cucueţi", simplu: "Cucueti", comuna: "Scrioastea" },
  { nume: "Dărvaş", simplu: "Darvas", comuna: "Bujoreni" },
  { nume: "Deparaţi", simplu: "Deparati", comuna: "Trivalea-Mosteni" },
  { nume: "Dideşti", simplu: "Didesti" },
  { nume: "Dobreni", comuna: "Tatarastii De Sus" },
  { nume: "Dobroteşti", simplu: "Dobrotesti" },
  { nume: "Dorobanţu", simplu: "Dorobantu", comuna: "Crangeni" },
  { nume: "Dracea", comuna: "Crangu" },
  { nume: "Drăceşti", simplu: "Dracesti", comuna: "Scurtu Mare" },
  { nume: "Drăcşani", simplu: "Dracsani", comuna: "Dracsenei" },
  { nume: "Drăcşenei", simplu: "Dracsenei" },
  { nume: "Drăgăneşti de Vede", simplu: "Draganesti de Vede" },
  { nume: "Drăgăneşti-Vlaşca", simplu: "Draganesti-Vlasca" },
  { nume: "Drăghineşti", simplu: "Draghinesti", comuna: "Gratia" },
  { nume: "Dudu", comuna: "Plopii-Slavitesti" },
  { nume: "Dulceanca", comuna: "Vedea" },
  { nume: "Dulceni", comuna: "Troianul" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Suhaia" },
  { nume: "Florica", comuna: "Crangu" },
  { nume: "Frăsinet", simplu: "Frasinet", comuna: "Babaita" },
  { nume: "Frumoasa" },
  { nume: "Furculeşti", simplu: "Furculesti" },
  { nume: "Gălăteni", simplu: "Galateni" },
  { nume: "Gărăgău", simplu: "Garagau", comuna: "Vartoape" },
  { nume: "Gârdeşti", simplu: "Gardesti", comuna: "Necsesti" },
  { nume: "Grădişteanca", simplu: "Gradisteanca", comuna: "Galateni" },
  { nume: "Gratia" },
  { nume: "Gresia", comuna: "Stejaru" },
  { nume: "Guruieni", comuna: "Magura" },
  { nume: "Însurăţei", simplu: "Insuratei", comuna: "Didesti" },
  { nume: "Ionaşcu", simplu: "Ionascu", comuna: "Calmatuiu De Sus" },
  { nume: "Islaz" },
  { nume: "Izvoarele" },
  { nume: "Lăceni", simplu: "Laceni", comuna: "Orbeasca" },
  { nume: "Lada", comuna: "Tatarastii De Jos" },
  { nume: "Licuriciu", comuna: "Calinesti" },
  { nume: "Linia Costii", comuna: "Talpa" },
  { nume: "Lisa" },
  { nume: "Liţa", simplu: "Lita" },
  { nume: "Ludăneasca", simplu: "Ludaneasca", comuna: "Rasmiresti" },
  { nume: "Lunca" },
  {
    nume: "Măgura cu Liliac",
    simplu: "Magura cu Liliac",
    comuna: "Draganesti De Vede",
  },
  { nume: "Măgura", simplu: "Magura" },
  { nume: "Măldăeni", simplu: "Maldaeni" },
  { nume: "Mariţa", simplu: "Marita", comuna: "Calinesti" },
  { nume: "Mârzăneşti", simplu: "Marzanesti" },
  { nume: "Mavrodin" },
  { nume: "Merenii de Jos", comuna: "Mereni" },
  { nume: "Merenii de Sus", comuna: "Mereni" },
  { nume: "Meri", comuna: "Vedea" },
  { nume: "Merişani", simplu: "Merisani", comuna: "Babaita" },
  { nume: "Merişani", simplu: "Merisani", comuna: "Dobrotesti" },
  { nume: "Moldoveni", comuna: "Islaz" },
  { nume: "Moşteni", simplu: "Mosteni" },
  { nume: "Moşteni", simplu: "Mosteni", comuna: "Furculesti" },
  { nume: "Nanov" },
  { nume: "Năsturelu", simplu: "Nasturelu" },
  { nume: "Năvodari", simplu: "Navodari", comuna: "Seaca" },
  { nume: "Necşeşti", simplu: "Necsesti" },
  { nume: "Negreni", comuna: "Tatarastii De Jos" },
  { nume: "Negrenii de Sus", comuna: "Tatarastii De Jos" },
  {
    nume: "Negrenii-Osebiţi",
    simplu: "Negrenii-Osebiti",
    comuna: "Tatarastii De Jos",
  },
  { nume: "Negrileşti", simplu: "Negrilesti", comuna: "Scurtu Mare" },
  { nume: "Nenciuleşti", simplu: "Nenciulesti" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu", comuna: "Calmatuiu" },
  { nume: "Obârtu", simplu: "Obartu", comuna: "Tatarastii De Jos" },
  { nume: "Odobeasca", comuna: "Dracsenei" },
  { nume: "Olteanca", comuna: "Segarcea-Vale" },
  { nume: "Olteni" },
  { nume: "Orbeasca de Jos", comuna: "Orbeasca" },
  { nume: "Orbeasca de Sus", comuna: "Orbeasca" },
  { nume: "Păru Rotund", simplu: "Paru Rotund", comuna: "Nenciulesti" },
  { nume: "Păuleasca", simplu: "Pauleasca", comuna: "Frumoasa" },
  { nume: "Peretu" },
  { nume: "Perii Broşteni", simplu: "Perii Brosteni", comuna: "Olteni" },
  { nume: "Piatra" },
  { nume: "Pietroşani", simplu: "Pietrosani" },
  { nume: "Pleaşov", simplu: "Pleasov", comuna: "Lunca" },
  { nume: "Plopi", comuna: "Dracsenei" },
  { nume: "Plopii-Slăviteşti", simplu: "Plopii-Slavitesti" },
  { nume: "Plosca" },
  { nume: "Poeni" },
  { nume: "Poiana", comuna: "Ciuperceni" },
  { nume: "Poroschia" },
  { nume: "Preajba", comuna: "Poeni" },
  { nume: "Prunaru", comuna: "Bujoreni" },
  { nume: "Prundu", comuna: "Lunca" },
  { nume: "Purani", comuna: "Silistea" },
  { nume: "Purani", comuna: "Vitanesti" },
  { nume: "Puranii de Sus", comuna: "Silistea" },
  { nume: "Putineiu" },
  { nume: "Rădoieşti-Deal", simplu: "Radoiesti-Deal", comuna: "Radoiesti" },
  { nume: "Rădoieşti-Vale", simplu: "Radoiesti-Vale", comuna: "Radoiesti" },
  { nume: "Răduleşti", simplu: "Radulesti", comuna: "Crevenicu" },
  { nume: "Răsmireşti", simplu: "Rasmiresti" },
  { nume: "Rosiori de Vede" },
  { nume: "Rotăreşti", simplu: "Rotaresti", comuna: "Talpa" },
  { nume: "Săceni", simplu: "Saceni" },
  { nume: "Saelele", comuna: "Lunca" },
  { nume: "Salcia" },
  { nume: "Sârbeni", simplu: "Sarbeni" },
  { nume: "Sârbenii de Jos", simplu: "Sarbenii de Jos", comuna: "Sarbeni" },
  { nume: "Satu Nou", comuna: "Didesti" },
  { nume: "Satul Vechi", comuna: "Dracsenei" },
  { nume: "Schitu Poienari", comuna: "Vitanesti" },
  { nume: "Scrioaştea", simplu: "Scrioastea" },
  { nume: "Scurtu Mare" },
  { nume: "Scurtu-Slăveşti", simplu: "Scurtu-Slavesti", comuna: "Scurtu Mare" },
  { nume: "Seaca" },
  { nume: "Secara", comuna: "Crangu" },
  { nume: "Segarcea-Deal", comuna: "Segarcea-Vale" },
  { nume: "Segarcea-Vale" },
  { nume: "Sericu", comuna: "Blejesti" },
  { nume: "Sfinţeşti", simplu: "Sfintesti" },
  { nume: "Siliştea Mică", simplu: "Silistea Mica", comuna: "Silistea" },
  { nume: "Siliştea-Gumeşti", simplu: "Silistea-Gumesti" },
  { nume: "Siliştea", simplu: "Silistea" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Vitanesti" },
  { nume: "Slăveşti", simplu: "Slavesti", comuna: "Tatarastii De Jos" },
  { nume: "Slobozia Mândra", simplu: "Slobozia Mandra" },
  { nume: "Smârdan", simplu: "Smardan", comuna: "Plopii-Slavitesti" },
  { nume: "Smârdioasa", simplu: "Smardioasa" },
  { nume: "Socetu", comuna: "Stejaru" },
  { nume: "Şoimu", simplu: "Soimu", comuna: "Smardioasa" },
  { nume: "Spătărei", simplu: "Spatarei", comuna: "Furculesti" },
  { nume: "Ştefeni", simplu: "Stefeni", comuna: "Mereni" },
  { nume: "Stejaru" },
  { nume: "Stejaru", comuna: "Crangeni" },
  { nume: "Ştorobăneasa", simplu: "Storobaneasa" },
  { nume: "Suhaia" },
  { nume: "Talpa Poştei", simplu: "Talpa Postei", comuna: "Talpa" },
  { nume: "Talpa-Bâscoveni", simplu: "Talpa-Bascoveni", comuna: "Talpa" },
  { nume: "Talpa-Ogrăzile", simplu: "Talpa-Ograzile", comuna: "Talpa" },
  { nume: "Târnava", simplu: "Tarnava", comuna: "Botoroaga" },
  { nume: "Tătărăştii de Jos", simplu: "Tatarastii de Jos" },
  { nume: "Tătărăştii de Sus", simplu: "Tatarastii de Sus" },
  { nume: "Ţăvârlău", simplu: "Tavarlau", comuna: "Poeni" },
  { nume: "Tecuci", comuna: "Balaci" },
  { nume: "Teleormanu", comuna: "Marzanesti" },
  { nume: "Ţigăneşti", simplu: "Tiganesti" },
  { nume: "Traian" },
  { nume: "Trivalea-Moşteni", simplu: "Trivalea-Mosteni" },
  { nume: "Troianul" },
  { nume: "Tudor Vladimirescu", comuna: "Salcia" },
  { nume: "Tunari", comuna: "Botoroaga" },
  { nume: "Turnu Măgurele", simplu: "Turnu Magurele" },
  { nume: "Uda-Clocociov", comuna: "Slobozia Mandra" },
  { nume: "Uda-Paciurea", comuna: "Slobozia Mandra" },
  { nume: "Udeni", comuna: "Sarbeni" },
  { nume: "Udupu", comuna: "Tatarastii De Sus" },
  { nume: "Ulmeni", comuna: "Bogdana" },
  { nume: "Urluiu", comuna: "Bogdana" },
  { nume: "Văcăreşti", simplu: "Vacaresti", comuna: "Draganesti De Vede" },
  { nume: "Văceni", simplu: "Vaceni", comuna: "Draganesti-Vlasca" },
  { nume: "Valea Cireşului", simplu: "Valea Ciresului", comuna: "Botoroaga" },
  { nume: "Valea Părului", simplu: "Valea Parului", comuna: "Marzanesti" },
  { nume: "Valea Poştei", simplu: "Valea Postei", comuna: "Scurtu Mare" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Lisa" },
  {
    nume: "Vârtoapele de Jos",
    simplu: "Vartoapele de Jos",
    comuna: "Vartoape",
  },
  {
    nume: "Vârtoapele de Sus",
    simplu: "Vartoapele de Sus",
    comuna: "Vartoape",
  },
  { nume: "Vătaşi", simplu: "Vatasi", comuna: "Poeni" },
  { nume: "Vatra", comuna: "Troianul" },
  { nume: "Vedea" },
  { nume: "Videle" },
  { nume: "Viile", comuna: "Scrioastea" },
  { nume: "Viişoara", simplu: "Viisoara" },
  { nume: "Vitanesti" },
  { nume: "Voievoda", comuna: "Furculesti" },
  { nume: "Zâmbreasca", simplu: "Zambreasca" },
  { nume: "Zimnicea" },
  { nume: "Zimnicele", comuna: "Nasturelu" },
  { nume: "Zlata", comuna: "Crangu" },
];
