export const tr = [
  { nume: "Albeni", comuna: "Scurtu Mare" },
  { nume: "Albești", simplu: "Albesti", comuna: "Vedea" },
  { nume: "Alexandria" },
  { nume: "Antonești", simplu: "Antonesti", comuna: "Calinesti" },
  { nume: "Băbăița", simplu: "Babaita" },
  { nume: "Băcălești", simplu: "Bacalesti", comuna: "Calmatuiu De Sus" },
  { nume: "Baciu", comuna: "Blejesti" },
  { nume: "Băduleasa", simplu: "Baduleasa", comuna: "Putineiu" },
  { nume: "Balaci" },
  { nume: "Baldovinești", simplu: "Baldovinesti", comuna: "Ciolanesti" },
  { nume: "Balta Sărată", simplu: "Balta Sarata", comuna: "Crangeni" },
  { nume: "Băneasa", simplu: "Baneasa", comuna: "Salcia" },
  { nume: "Banov", comuna: "Poeni" },
  {
    nume: "Bârseștii de Jos",
    simplu: "Barsestii de Jos",
    comuna: "Plopii-Slavitesti",
  },
  { nume: "Bâscoveni", simplu: "Bascoveni", comuna: "Galateni" },
  { nume: "Beciu", comuna: "Plopii-Slavitesti" },
  { nume: "Beiu", comuna: "Storobaneasa" },
  { nume: "Belciug", comuna: "Necsesti" },
  { nume: "Beuca", comuna: "Dracsenei" },
  { nume: "Blejești", simplu: "Blejesti" },
  { nume: "Bogdana" },
  { nume: "Botoroaga" },
  { nume: "Bragadiru" },
  { nume: "Brânceni", simplu: "Branceni" },
  { nume: "Brâncoveanca", simplu: "Brancoveanca", comuna: "Plopii-Slavitesti" },
  { nume: "Brătășani", simplu: "Bratasani", comuna: "Trivalea-Mosteni" },
  { nume: "Bratcovu", comuna: "Stejaru" },
  { nume: "Brătești", simplu: "Bratesti", comuna: "Poeni" },
  { nume: "Brebina", comuna: "Scrioastea" },
  { nume: "Broșteanca", simplu: "Brosteanca", comuna: "Bogdana" },
  { nume: "Bujoreni" },
  { nume: "Bujoru" },
  { nume: "Bujoru", comuna: "Calmatuiu" },
  { nume: "Burdeni", comuna: "Balaci" },
  { nume: "Butculești", simplu: "Butculesti", comuna: "Saceni" },
  { nume: "Butești", simplu: "Butesti", comuna: "Silistea" },
  { nume: "Buzescu" },
  { nume: "Călinești", simplu: "Calinesti" },
  { nume: "Călmățuiu de Sus", simplu: "Calmatuiu de Sus" },
  { nume: "Călmățuiu", simplu: "Calmatuiu" },
  { nume: "Calomfirești", simplu: "Calomfiresti", comuna: "Poroschia" },
  { nume: "Călugaru", simplu: "Calugaru", comuna: "Botoroaga" },
  { nume: "Caravaneți", simplu: "Caravaneti", comuna: "Calmatuiu" },
  { nume: "Cârlomanu", simplu: "Carlomanu", comuna: "Putineiu" },
  { nume: "Cătunu", simplu: "Catunu", comuna: "Poeni" },
  { nume: "Cernetu", comuna: "Marzanesti" },
  { nume: "Cervenia" },
  { nume: "Cetatea", comuna: "Radoiesti" },
  {
    nume: "Ciolăneștii din Deal",
    simplu: "Ciolanestii din Deal",
    comuna: "Ciolanesti",
  },
  {
    nume: "Ciolăneștii din Vale",
    simplu: "Ciolanestii din Vale",
    comuna: "Ciolanesti",
  },
  { nume: "Ciuperceni" },
  { nume: "Ciuperceni", comuna: "Cosmesti" },
  { nume: "Ciurari-Deal", comuna: "Gratia" },
  { nume: "Ciurari", comuna: "Saceni" },
  { nume: "Clănița", simplu: "Clanita", comuna: "Babaita" },
  { nume: "Comoara", comuna: "Draganesti-Vlasca" },
  { nume: "Conțești", simplu: "Contesti" },
  { nume: "Copăceanca", simplu: "Copaceanca", comuna: "Calinesti" },
  { nume: "Cosmești", simplu: "Cosmesti" },
  { nume: "Coșoaia", simplu: "Cosoaia", comuna: "Videle" },
  { nume: "Coșoteni", simplu: "Cosoteni", comuna: "Vedea" },
  { nume: "Crângeni", simplu: "Crangeni" },
  { nume: "Crângu", simplu: "Crangu" },
  { nume: "Crevenicu" },
  { nume: "Cucueți", simplu: "Cucueti", comuna: "Scrioastea" },
  { nume: "Dărvaș", simplu: "Darvas", comuna: "Bujoreni" },
  { nume: "Deparați", simplu: "Deparati", comuna: "Trivalea-Mosteni" },
  { nume: "Didești", simplu: "Didesti" },
  { nume: "Dobreni", comuna: "Tatarastii De Sus" },
  { nume: "Dobrotești", simplu: "Dobrotesti" },
  { nume: "Dorobanțu", simplu: "Dorobantu", comuna: "Crangeni" },
  { nume: "Dracea", comuna: "Crangu" },
  { nume: "Drăcești", simplu: "Dracesti", comuna: "Scurtu Mare" },
  { nume: "Drăcșani", simplu: "Dracsani", comuna: "Dracsenei" },
  { nume: "Drăcșenei", simplu: "Dracsenei" },
  { nume: "Drăgănești de Vede", simplu: "Draganesti de Vede" },
  { nume: "Drăgănești-Vlașca", simplu: "Draganesti-Vlasca" },
  { nume: "Drăghinești", simplu: "Draghinesti", comuna: "Gratia" },
  { nume: "Dudu", comuna: "Plopii-Slavitesti" },
  { nume: "Dulceanca", comuna: "Vedea" },
  { nume: "Dulceni", comuna: "Troianul" },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Suhaia" },
  { nume: "Florica", comuna: "Crangu" },
  { nume: "Frăsinet", simplu: "Frasinet", comuna: "Babaita" },
  { nume: "Frumoasa" },
  { nume: "Furculești", simplu: "Furculesti" },
  { nume: "Gălăteni", simplu: "Galateni" },
  { nume: "Gărăgău", simplu: "Garagau", comuna: "Vartoape" },
  { nume: "Gârdești", simplu: "Gardesti", comuna: "Necsesti" },
  { nume: "Grădișteanca", simplu: "Gradisteanca", comuna: "Galateni" },
  { nume: "Gratia" },
  { nume: "Gresia", comuna: "Stejaru" },
  { nume: "Guruieni", comuna: "Magura" },
  { nume: "Însurăței", simplu: "Insuratei", comuna: "Didesti" },
  { nume: "Ionașcu", simplu: "Ionascu", comuna: "Calmatuiu De Sus" },
  { nume: "Islaz" },
  { nume: "Izvoarele" },
  { nume: "Lăceni", simplu: "Laceni", comuna: "Orbeasca" },
  { nume: "Lada", comuna: "Tatarastii De Jos" },
  { nume: "Licuriciu", comuna: "Calinesti" },
  { nume: "Linia Costii", comuna: "Talpa" },
  { nume: "Lisa" },
  { nume: "Lița", simplu: "Lita" },
  { nume: "Ludăneasca", simplu: "Ludaneasca", comuna: "Rasmiresti" },
  { nume: "Lunca" },
  {
    nume: "Măgura cu Liliac",
    simplu: "Magura cu Liliac",
    comuna: "Draganesti De Vede",
  },
  { nume: "Măgura", simplu: "Magura" },
  { nume: "Măldăeni", simplu: "Maldaeni" },
  { nume: "Marița", simplu: "Marita", comuna: "Calinesti" },
  { nume: "Mârzănești", simplu: "Marzanesti" },
  { nume: "Mavrodin" },
  { nume: "Merenii de Jos", comuna: "Mereni" },
  { nume: "Merenii de Sus", comuna: "Mereni" },
  { nume: "Meri", comuna: "Vedea" },
  { nume: "Merișani", simplu: "Merisani", comuna: "Babaita" },
  { nume: "Merișani", simplu: "Merisani", comuna: "Dobrotesti" },
  { nume: "Moldoveni", comuna: "Islaz" },
  { nume: "Moșteni", simplu: "Mosteni" },
  { nume: "Moșteni", simplu: "Mosteni", comuna: "Furculesti" },
  { nume: "Nanov" },
  { nume: "Năsturelu", simplu: "Nasturelu" },
  { nume: "Năvodari", simplu: "Navodari", comuna: "Seaca" },
  { nume: "Necșești", simplu: "Necsesti" },
  { nume: "Negreni", comuna: "Tatarastii De Jos" },
  { nume: "Negrenii de Sus", comuna: "Tatarastii De Jos" },
  {
    nume: "Negrenii-Osebiți",
    simplu: "Negrenii-Osebiti",
    comuna: "Tatarastii De Jos",
  },
  { nume: "Negrilești", simplu: "Negrilesti", comuna: "Scurtu Mare" },
  { nume: "Nenciulești", simplu: "Nenciulesti" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu", comuna: "Calmatuiu" },
  { nume: "Obârtu", simplu: "Obartu", comuna: "Tatarastii De Jos" },
  { nume: "Odobeasca", comuna: "Dracsenei" },
  { nume: "Olteanca", comuna: "Segarcea-Vale" },
  { nume: "Olteni" },
  { nume: "Orbeasca de Jos", comuna: "Orbeasca" },
  { nume: "Orbeasca de Sus", comuna: "Orbeasca" },
  { nume: "Păru Rotund", simplu: "Paru Rotund", comuna: "Nenciulesti" },
  { nume: "Păuleasca", simplu: "Pauleasca", comuna: "Frumoasa" },
  { nume: "Peretu" },
  { nume: "Perii Broșteni", simplu: "Perii Brosteni", comuna: "Olteni" },
  { nume: "Piatra" },
  { nume: "Pietroșani", simplu: "Pietrosani" },
  { nume: "Pleașov", simplu: "Pleasov", comuna: "Lunca" },
  { nume: "Plopi", comuna: "Dracsenei" },
  { nume: "Plopii-Slăvitești", simplu: "Plopii-Slavitesti" },
  { nume: "Plosca" },
  { nume: "Poeni" },
  { nume: "Poiana", comuna: "Ciuperceni" },
  { nume: "Poroschia" },
  { nume: "Preajba", comuna: "Poeni" },
  { nume: "Prunaru", comuna: "Bujoreni" },
  { nume: "Prundu", comuna: "Lunca" },
  { nume: "Purani", comuna: "Silistea" },
  { nume: "Purani", comuna: "Vitanesti" },
  { nume: "Puranii de Sus", comuna: "Silistea" },
  { nume: "Putineiu" },
  { nume: "Rădoiești-Deal", simplu: "Radoiesti-Deal", comuna: "Radoiesti" },
  { nume: "Rădoiești-Vale", simplu: "Radoiesti-Vale", comuna: "Radoiesti" },
  { nume: "Rădulești", simplu: "Radulesti", comuna: "Crevenicu" },
  { nume: "Răsmirești", simplu: "Rasmiresti" },
  { nume: "Rosiori de Vede" },
  { nume: "Rotărești", simplu: "Rotaresti", comuna: "Talpa" },
  { nume: "Săceni", simplu: "Saceni" },
  { nume: "Saelele", comuna: "Lunca" },
  { nume: "Salcia" },
  { nume: "Sârbeni", simplu: "Sarbeni" },
  { nume: "Sârbenii de Jos", simplu: "Sarbenii de Jos", comuna: "Sarbeni" },
  { nume: "Satu Nou", comuna: "Didesti" },
  { nume: "Satul Vechi", comuna: "Dracsenei" },
  { nume: "Schitu Poienari", comuna: "Vitanesti" },
  { nume: "Scrioaștea", simplu: "Scrioastea" },
  { nume: "Scurtu Mare" },
  { nume: "Scurtu-Slăvești", simplu: "Scurtu-Slavesti", comuna: "Scurtu Mare" },
  { nume: "Seaca" },
  { nume: "Secara", comuna: "Crangu" },
  { nume: "Segarcea-Deal", comuna: "Segarcea-Vale" },
  { nume: "Segarcea-Vale" },
  { nume: "Sericu", comuna: "Blejesti" },
  { nume: "Sfințești", simplu: "Sfintesti" },
  { nume: "Siliștea Mică", simplu: "Silistea Mica", comuna: "Silistea" },
  { nume: "Siliștea-Gumești", simplu: "Silistea-Gumesti" },
  { nume: "Siliștea", simplu: "Silistea" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Vitanesti" },
  { nume: "Slăvești", simplu: "Slavesti", comuna: "Tatarastii De Jos" },
  { nume: "Slobozia Mândra", simplu: "Slobozia Mandra" },
  { nume: "Smârdan", simplu: "Smardan", comuna: "Plopii-Slavitesti" },
  { nume: "Smârdioasa", simplu: "Smardioasa" },
  { nume: "Socetu", comuna: "Stejaru" },
  { nume: "Șoimu", simplu: "Soimu", comuna: "Smardioasa" },
  { nume: "Spătărei", simplu: "Spatarei", comuna: "Furculesti" },
  { nume: "Ștefeni", simplu: "Stefeni", comuna: "Mereni" },
  { nume: "Stejaru" },
  { nume: "Stejaru", comuna: "Crangeni" },
  { nume: "Ștorobăneasa", simplu: "Storobaneasa" },
  { nume: "Suhaia" },
  { nume: "Talpa Poștei", simplu: "Talpa Postei", comuna: "Talpa" },
  { nume: "Talpa-Bâscoveni", simplu: "Talpa-Bascoveni", comuna: "Talpa" },
  { nume: "Talpa-Ogrăzile", simplu: "Talpa-Ograzile", comuna: "Talpa" },
  { nume: "Târnava", simplu: "Tarnava", comuna: "Botoroaga" },
  { nume: "Tătărăștii de Jos", simplu: "Tatarastii de Jos" },
  { nume: "Tătărăștii de Sus", simplu: "Tatarastii de Sus" },
  { nume: "Țăvârlău", simplu: "Tavarlau", comuna: "Poeni" },
  { nume: "Tecuci", comuna: "Balaci" },
  { nume: "Teleormanu", comuna: "Marzanesti" },
  { nume: "Țigănești", simplu: "Tiganesti" },
  { nume: "Traian" },
  { nume: "Trivalea-Moșteni", simplu: "Trivalea-Mosteni" },
  { nume: "Troianul" },
  { nume: "Tudor Vladimirescu", comuna: "Salcia" },
  { nume: "Tunari", comuna: "Botoroaga" },
  { nume: "Turnu Măgurele", simplu: "Turnu Magurele" },
  { nume: "Uda-Clocociov", comuna: "Slobozia Mandra" },
  { nume: "Uda-Paciurea", comuna: "Slobozia Mandra" },
  { nume: "Udeni", comuna: "Sarbeni" },
  { nume: "Udupu", comuna: "Tatarastii De Sus" },
  { nume: "Ulmeni", comuna: "Bogdana" },
  { nume: "Urluiu", comuna: "Bogdana" },
  { nume: "Văcărești", simplu: "Vacaresti", comuna: "Draganesti De Vede" },
  { nume: "Văceni", simplu: "Vaceni", comuna: "Draganesti-Vlasca" },
  { nume: "Valea Cireșului", simplu: "Valea Ciresului", comuna: "Botoroaga" },
  { nume: "Valea Părului", simplu: "Valea Parului", comuna: "Marzanesti" },
  { nume: "Valea Poștei", simplu: "Valea Postei", comuna: "Scurtu Mare" },
  { nume: "Vânători", simplu: "Vanatori", comuna: "Lisa" },
  {
    nume: "Vârtoapele de Jos",
    simplu: "Vartoapele de Jos",
    comuna: "Vartoape",
  },
  {
    nume: "Vârtoapele de Sus",
    simplu: "Vartoapele de Sus",
    comuna: "Vartoape",
  },
  { nume: "Vătași", simplu: "Vatasi", comuna: "Poeni" },
  { nume: "Vatra", comuna: "Troianul" },
  { nume: "Vedea" },
  { nume: "Videle" },
  { nume: "Viile", comuna: "Scrioastea" },
  { nume: "Viișoara", simplu: "Viisoara" },
  { nume: "Vitanesti" },
  { nume: "Voievoda", comuna: "Furculesti" },
  { nume: "Zâmbreasca", simplu: "Zambreasca" },
  { nume: "Zimnicea" },
  { nume: "Zimnicele", comuna: "Nasturelu" },
  { nume: "Zlata", comuna: "Crangu" },
];
