export const tm = [
  { nume: "Albina", comuna: "Mosnita Noua" },
  { nume: "Alioş", simplu: "Alios", comuna: "Masloc" },
  { nume: "Altringen", comuna: "Bogda" },
  { nume: "Babşa", simplu: "Babsa", comuna: "Belint" },
  { nume: "Bacova", comuna: "Buzias" },
  { nume: "Balinţ", simplu: "Balint" },
  { nume: "Baloşeşti", simplu: "Balosesti", comuna: "Tomesti" },
  { nume: "Banloc" },
  { nume: "Bara" },
  { nume: "Bărăteaz", simplu: "Barateaz", comuna: "Satchinez" },
  { nume: "Bârna", simplu: "Barna" },
  { nume: "Băteşti", simplu: "Batesti", comuna: "Faget" },
  { nume: "Bazoş", simplu: "Bazos", comuna: "Recas" },
  { nume: "Bazoşu Nou", simplu: "Bazosu Nou", comuna: "Remetea Mare" },
  { nume: "Beba Veche" },
  { nume: "Becicherecu Mic" },
  { nume: "Begheiu Mic", comuna: "Faget" },
  { nume: "Belinţ", simplu: "Belint" },
  { nume: "Bencecu de Jos", comuna: "Pischia" },
  { nume: "Bencecu de Sus", comuna: "Pischia" },
  { nume: "Berecuţa", simplu: "Berecuta", comuna: "Gataia" },
  { nume: "Beregsău Mare", simplu: "Beregsau Mare", comuna: "Sacalaz" },
  { nume: "Beregsău Mic", simplu: "Beregsau Mic", comuna: "Sacalaz" },
  { nume: "Berini", comuna: "Sacosu Turcesc" },
  { nume: "Bethausen" },
  { nume: "Bichigi", comuna: "Faget" },
  { nume: "Biled" },
  { nume: "Birda", comuna: "Gataia" },
  { nume: "Blajova", comuna: "Nitchidorf" },
  { nume: "Bobda", comuna: "Cenei" },
  { nume: "Bodo", comuna: "Balint" },
  { nume: "Bogda" },
  { nume: "Boldur" },
  { nume: "Boteşti", simplu: "Botesti", comuna: "Barna" },
  { nume: "Botineşti", simplu: "Botinesti", comuna: "Barna" },
  { nume: "Brăneşti", simplu: "Branesti", comuna: "Faget" },
  { nume: "Breazova", comuna: "Margina" },
  { nume: "Breştea", simplu: "Brestea", comuna: "Denta" },
  { nume: "Brestovăţ", simplu: "Brestovat" },
  { nume: "Bucovăţ", simplu: "Bucovat", comuna: "Dumbrava" },
  { nume: "Bucovăţ", simplu: "Bucovat", comuna: "Remetea Mare" },
  { nume: "Bulgăruş", simplu: "Bulgarus", comuna: "Lenauheim" },
  { nume: "Bulza", comuna: "Margina" },
  { nume: "Bunea Mare", comuna: "Faget" },
  { nume: "Bunea Mică", simplu: "Bunea Mica", comuna: "Faget" },
  { nume: "Butin", comuna: "Gataia" },
  { nume: "Buzad", comuna: "Bogda" },
  { nume: "Buziaş", simplu: "Buzias" },
  { nume: "Cadar", comuna: "Tormac" },
  { nume: "Călacea", simplu: "Calacea", comuna: "Ortisoara" },
  { nume: "Căpăt", simplu: "Capat", comuna: "Racovita" },
  { nume: "Carani", comuna: "Sanandrei" },
  { nume: "Cărpiniş", simplu: "Carpinis" },
  { nume: "Cebza", comuna: "Ciacova" },
  { nume: "Cenad" },
  { nume: "Cenei" },
  { nume: "Cerna", comuna: "Liebling" },
  { nume: "Cerneteaz", comuna: "Giarmata" },
  { nume: "Charlotenburg", comuna: "Bogda" },
  { nume: "Checea", comuna: "Cenei" },
  { nume: "Checheş", simplu: "Cheches", comuna: "Secas" },
  { nume: "Cheglevici", comuna: "Dudestii Vechi" },
  { nume: "Cherestur", comuna: "Beba Veche" },
  { nume: "Chevereşu Mare", simplu: "Cheveresu Mare" },
  { nume: "Chişoda", simplu: "Chisoda", comuna: "Giroc" },
  { nume: "Chizătău", simplu: "Chizatau", comuna: "Belint" },
  { nume: "Ciacova" },
  { nume: "Cireşu Mic", simplu: "Ciresu Mic", comuna: "Criciova" },
  { nume: "Cireşu", simplu: "Ciresu", comuna: "Criciova" },
  { nume: "Cladova", comuna: "Bethausen" },
  { nume: "Cliciova", comuna: "Bethausen" },
  { nume: "Clopodia", comuna: "Jamu Mare" },
  {
    nume: "Colonia Bulgară",
    simplu: "Colonia Bulgara",
    comuna: "Dudestii Vechi",
  },
  { nume: "Colonia Fabricii", comuna: "Tomesti" },
  { nume: "Colonia Mică", simplu: "Colonia Mica", comuna: "Faget" },
  { nume: "Comeat", comuna: "Bogda" },
  { nume: "Comloşu Mare", simplu: "Comlosu Mare" },
  { nume: "Comloşu Mic", simplu: "Comlosu Mic", comuna: "Comlosu Mare" },
  { nume: "Corneşti", simplu: "Cornesti", comuna: "Ortisoara" },
  { nume: "Coşarii", simplu: "Cosarii", comuna: "Brestovat" },
  { nume: "Coşava", simplu: "Cosava", comuna: "Curtea" },
  { nume: "Coşeviţa", simplu: "Cosevita", comuna: "Margina" },
  { nume: "Coşteiu de Sus", simplu: "Costeiu de Sus", comuna: "Margina" },
  { nume: "Coşteiu", simplu: "Costeiu" },
  { nume: "Covaci", comuna: "Sanandrei" },
  { nume: "Crai Nou", comuna: "Giulvaz" },
  { nume: "Cralovăţ", simplu: "Cralovat", comuna: "Topolovatu Mare" },
  { nume: "Criciova" },
  { nume: "Crivina de Sus", comuna: "Pietroasa" },
  { nume: "Crivina", comuna: "Nadrag" },
  { nume: "Crivobara", comuna: "Secas" },
  { nume: "Cruceni", comuna: "Foeni" },
  { nume: "Curtea" },
  { nume: "Cutina", comuna: "Bethausen" },
  { nume: "Darova" },
  { nume: "Dejan", comuna: "Moravita" },
  { nume: "Denta" },
  { nume: "Deta" },
  { nume: "Diniaş", simplu: "Dinias", comuna: "Peciu Nou" },
  { nume: "Dobreşti", simplu: "Dobresti", comuna: "Bara" },
  { nume: "Dolaţ", simplu: "Dolat", comuna: "Banloc" },
  { nume: "Drăgoieşti", simplu: "Dragoiesti", comuna: "Racovita" },
  { nume: "Dragomireşti", simplu: "Dragomiresti", comuna: "Stiuca" },
  { nume: "Dragşina", simplu: "Dragsina", comuna: "Cheveresu Mare" },
  { nume: "Drăgsineşti", simplu: "Dragsinesti", comuna: "Fardea" },
  { nume: "Drinova", comuna: "Barna" },
  { nume: "Dubeşti", simplu: "Dubesti", comuna: "Ohaba Lunga" },
  { nume: "Duboz", comuna: "Nitchidorf" },
  { nume: "Dudeştii Noi", simplu: "Dudestii Noi", comuna: "Becicherecu Mic" },
  { nume: "Dudeştii Vechi", simplu: "Dudestii Vechi" },
  { nume: "Dumbrava" },
  { nume: "Dumbrăviţa", simplu: "Dumbravita" },
  { nume: "Fădimac", simplu: "Fadimac", comuna: "Balint" },
  { nume: "Făget", simplu: "Faget" },
  { nume: "Fărăşeşti", simplu: "Farasesti", comuna: "Pietroasa" },
  { nume: "Fârdea", simplu: "Fardea" },
  { nume: "Ferendia", comuna: "Jamu Mare" },
  { nume: "Fibiş", simplu: "Fibis", comuna: "Masloc" },
  { nume: "Ficătar", simplu: "Ficatar", comuna: "Racovita" },
  { nume: "Foeni" },
  { nume: "Folea", comuna: "Voiteg" },
  { nume: "Gad", comuna: "Ciacova" },
  { nume: "Gaiu Mic", comuna: "Moravita" },
  { nume: "Gătaia", simplu: "Gataia" },
  { nume: "Gavojdia" },
  { nume: "Gelu", comuna: "Varias" },
  { nume: "Gherman", comuna: "Jamu Mare" },
  { nume: "Ghilad", comuna: "Ciacova" },
  { nume: "Ghiroda" },
  { nume: "Ghizela" },
  { nume: "Giarmata-Vii", comuna: "Ghiroda" },
  { nume: "Giarmata" },
  { nume: "Giera" },
  { nume: "Giroc" },
  { nume: "Giulvăz", simplu: "Giulvaz" },
  { nume: "Gladna Montană", simplu: "Gladna Montana", comuna: "Fardea" },
  { nume: "Gladna Româna", simplu: "Gladna Romana", comuna: "Fardea" },
  { nume: "Gottlob", comuna: "Lovrin" },
  { nume: "Grabăţ", simplu: "Grabat", comuna: "Lenauheim" },
  { nume: "Grănicerii", simplu: "Granicerii", comuna: "Giera" },
  { nume: "Groşi", simplu: "Grosi", comuna: "Margina" },
  { nume: "Gruni", comuna: "Belint" },
  { nume: "Hăuzeşti", simplu: "Hauzesti", comuna: "Fardea" },
  {
    nume: "Herendeşti",
    simplu: "Herendesti",
    comuna: "Victor Vlad Delamarina",
  },
  { nume: "Herneacova", comuna: "Recas" },
  { nume: "Hezeriş", simplu: "Hezeris", comuna: "Costeiu" },
  { nume: "Hisiaş", simplu: "Hisias", comuna: "Ghizela" },
  { nume: "Hitiaş", simplu: "Hitias", comuna: "Racovita" },
  { nume: "Hodoni", comuna: "Satchinez" },
  { nume: "Hodoş", simplu: "Hodos", comuna: "Brestovat" },
  { nume: "Hodoş", simplu: "Hodos", comuna: "Darova" },
  { nume: "Homojdia", comuna: "Curtea" },
  { nume: "Honorici", comuna: "Victor Vlad Delamarina" },
  { nume: "Ianova", comuna: "Remetea Mare" },
  { nume: "Icloda", comuna: "Sacosu Turcesc" },
  { nume: "Ictar-Budinţi", simplu: "Ictar-Budinti", comuna: "Topolovatu Mare" },
  { nume: "Iecea Mare", comuna: "Carpinis" },
  { nume: "Iecea Mică", simplu: "Iecea Mica", comuna: "Carpinis" },
  { nume: "Ierşnic", simplu: "Iersnic", comuna: "Ohaba Lunga" },
  { nume: "Igriş", simplu: "Igris", comuna: "Sanpetru Mare" },
  { nume: "Iohanisfeld", comuna: "Uivar" },
  { nume: "Iosif", comuna: "Liebling" },
  { nume: "Iosifalău", simplu: "Iosifalau", comuna: "Topolovatu Mare" },
  { nume: "Ivanda", comuna: "Giulvaz" },
  { nume: "Izvin", comuna: "Recas" },
  { nume: "Jabăr", simplu: "Jabar", comuna: "Boldur" },
  { nume: "Jamu Mare" },
  { nume: "Jdioara", comuna: "Criciova" },
  { nume: "Jebel" },
  { nume: "Jena", comuna: "Gavojdia" },
  { nume: "Jimbolia" },
  { nume: "Jupâneşti", simplu: "Jupanesti", comuna: "Faget" },
  { nume: "Jupani", comuna: "Traian Vuia" },
  { nume: "Jureşti", simplu: "Juresti", comuna: "Barna" },
  { nume: "Lăpuşnic", simplu: "Lapusnic", comuna: "Bara" },
  { nume: "Lăţunaş", simplu: "Latunas", comuna: "Jamu Mare" },
  { nume: "Lenauheim" },
  { nume: "Leucuşeşti", simplu: "Leucusesti", comuna: "Bethausen" },
  { nume: "Liebling" },
  { nume: "Livezile", comuna: "Banloc" },
  { nume: "Lovrin" },
  { nume: "Lucareţ", simplu: "Lucaret", comuna: "Brestovat" },
  { nume: "Lugoj" },
  { nume: "Lugojel", comuna: "Gavojdia" },
  { nume: "Luncanii de Jos", comuna: "Tomesti" },
  { nume: "Luncanii de Sus", comuna: "Tomesti" },
  { nume: "Lunga", comuna: "Comlosu Mare" },
  { nume: "Macedonia", comuna: "Ciacova" },
  { nume: "Măguri", simplu: "Maguri", comuna: "Lugoj" },
  { nume: "Mânăstire", simplu: "Manastire", comuna: "Gataia" },
  { nume: "Mănăştiur", simplu: "Manastiur" },
  { nume: "Margina" },
  { nume: "Maşloc", simplu: "Masloc" },
  { nume: "Mâtnicu Mic", simplu: "Matnicu Mic", comuna: "Fardea" },
  { nume: "Moraviţa", simplu: "Moravita" },
  { nume: "Moşniţa Nouă", simplu: "Mosnita Noua" },
  { nume: "Moşniţa Veche", simplu: "Mosnita Veche", comuna: "Mosnita Noua" },
  { nume: "Murani", comuna: "Pischia" },
  { nume: "Nadăş", simplu: "Nadas", comuna: "Recas" },
  { nume: "Nădrag", simplu: "Nadrag" },
  { nume: "Nemeşeşti", simplu: "Nemesesti", comuna: "Margina" },
  { nume: "Nerău", simplu: "Nerau", comuna: "Teremia Mare" },
  { nume: "Nevrincea", comuna: "Bethausen" },
  { nume: "Niţchidorf", simplu: "Nitchidorf" },
  { nume: "Obad", comuna: "Ciacova" },
  { nume: "Ofseniţa", simplu: "Ofsenita", comuna: "Banloc" },
  { nume: "Ohaba Lungă", simplu: "Ohaba Lunga" },
  { nume: "Ohaba Română", simplu: "Ohaba Romana", comuna: "Ohaba Lunga" },
  { nume: "Ohaba-Forgaci", comuna: "Boldur" },
  { nume: "Oloşag", simplu: "Olosag", comuna: "Stiuca" },
  { nume: "Opatiţa", simplu: "Opatita", comuna: "Deta" },
  { nume: "Orţişoara", simplu: "Ortisoara" },
  { nume: "Otelec", comuna: "Uivar" },
  { nume: "Otveşti", simplu: "Otvesti", comuna: "Sacosu Turcesc" },
  { nume: "Pădurani", simplu: "Padurani", comuna: "Manastiur" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Jebel" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Victor Vlad Delamarina" },
  { nume: "Paniova", comuna: "Ghizela" },
  { nume: "Parţa", simplu: "Parta", comuna: "Sag" },
  { nume: "Partoş", simplu: "Partos", comuna: "Banloc" },
  { nume: "Păru", simplu: "Paru", comuna: "Costeiu" },
  { nume: "Peciu Nou" },
  { nume: "Percosova", comuna: "Gataia" },
  { nume: "Periam" },
  { nume: "Pesac", comuna: "Periam" },
  { nume: "Petroasa Mare", comuna: "Victor Vlad Delamarina" },
  { nume: "Petroman", comuna: "Ciacova" },
  { nume: "Petrovaselo", comuna: "Recas" },
  { nume: "Pietroasa" },
  { nume: "Pini", comuna: "Victor Vlad Delamarina" },
  { nume: "Pişchia", simplu: "Pischia" },
  { nume: "Pogăneşti", simplu: "Poganesti", comuna: "Barna" },
  { nume: "Poieni", comuna: "Pietroasa" },
  { nume: "Pordeanu", comuna: "Beba Veche" },
  { nume: "Povârgina", simplu: "Povargina", comuna: "Faget" },
  { nume: "Pustiniş", simplu: "Pustinis", comuna: "Uivar" },
  { nume: "Răchita", simplu: "Rachita", comuna: "Dumbrava" },
  { nume: "Racoviţa", simplu: "Racovita" },
  { nume: "Rădmăneşti", simplu: "Radmanesti", comuna: "Bara" },
  { nume: "Răuţi", simplu: "Rauti", comuna: "Uivar" },
  { nume: "Recaş", simplu: "Recas" },
  { nume: "Remetea Mare" },
  { nume: "Remetea Mică", simplu: "Remetea Mica", comuna: "Masloc" },
  { nume: "Remetea-Luncă", simplu: "Remetea-Lunca", comuna: "Manastiur" },
  { nume: "Româneşti", simplu: "Romanesti", comuna: "Tomesti" },
  { nume: "Roviniţa Mare", simplu: "Rovinita Mare", comuna: "Denta" },
  { nume: "Roviniţa Mică", simplu: "Rovinita Mica", comuna: "Denta" },
  { nume: "Rudicica", comuna: "Mosnita Noua" },
  { nume: "Rudna", comuna: "Giulvaz" },
  { nume: "Săcălaz", simplu: "Sacalaz" },
  { nume: "Săceni", simplu: "Saceni", comuna: "Traian Vuia" },
  { nume: "Sacoşu Mare", simplu: "Sacosu Mare", comuna: "Darova" },
  { nume: "Sacoşu Turcesc", simplu: "Sacosu Turcesc" },
  { nume: "Şag", simplu: "Sag" },
  { nume: "Sălbăgel", simplu: "Salbagel", comuna: "Gavojdia" },
  { nume: "Sălciua Nouă", simplu: "Salciua Noua", comuna: "Pischia" },
  { nume: "Sânandrei", simplu: "Sanandrei" },
  { nume: "Şandra", simplu: "Sandra", comuna: "Biled" },
  { nume: "Sângeorge", simplu: "Sangeorge", comuna: "Gataia" },
  { nume: "Sânmartinu Maghiar", simplu: "Sanmartinu Maghiar", comuna: "Uivar" },
  {
    nume: "Sânmartinu Sârbesc",
    simplu: "Sanmartinu Sarbesc",
    comuna: "Peciu Nou",
  },
  {
    nume: "Sânmihaiu German",
    simplu: "Sanmihaiu German",
    comuna: "Sanmihaiu Roman",
  },
  { nume: "Sânmihaiu Român", simplu: "Sanmihaiu Roman" },
  { nume: "Sânnicolau Mare", simplu: "Sannicolau Mare" },
  { nume: "Şanoviţa", simplu: "Sanovita", comuna: "Ghizela" },
  { nume: "Sânpetru Mare", simplu: "Sanpetru Mare" },
  { nume: "Sânpetru Mic", simplu: "Sanpetru Mic", comuna: "Varias" },
  { nume: "Saravale", comuna: "Sanpetru Mare" },
  { nume: "Sărăzani", simplu: "Sarazani", comuna: "Barna" },
  { nume: "Sârbova", simplu: "Sarbova", comuna: "Racovita" },
  { nume: "Satchinez" },
  { nume: "Sculia", comuna: "Gataia" },
  { nume: "Secaş", simplu: "Secas" },
  { nume: "Seceani", comuna: "Ortisoara" },
  { nume: "Şemlacu Mare", simplu: "Semlacu Mare", comuna: "Gataia" },
  { nume: "Şemlacu Mic", simplu: "Semlacu Mic", comuna: "Gataia" },
  { nume: "Silagiu", comuna: "Buzias" },
  { nume: "Sinersig", comuna: "Boldur" },
  { nume: "Sintar", comuna: "Bogda" },
  { nume: "Sinteşti", simplu: "Sintesti", comuna: "Margina" },
  { nume: "Şipet", simplu: "Sipet", comuna: "Tormac" },
  { nume: "Soca", comuna: "Banloc" },
  { nume: "Spata", comuna: "Bara" },
  { nume: "Stamora Germană", simplu: "Stamora Germana", comuna: "Moravita" },
  {
    nume: "Stamora Română",
    simplu: "Stamora Romana",
    comuna: "Sacosu Turcesc",
  },
  { nume: "Stanciova", comuna: "Recas" },
  { nume: "Ştiuca", simplu: "Stiuca" },
  { nume: "Sudriaş", simplu: "Sudrias", comuna: "Traian Vuia" },
  { nume: "Surducu Mic", comuna: "Traian Vuia" },
  { nume: "Susani", comuna: "Traian Vuia" },
  { nume: "Suştra", simplu: "Sustra", comuna: "Topolovatu Mare" },
  { nume: "Tapia", comuna: "Lugoj" },
  { nume: "Târgovişte", simplu: "Targoviste", comuna: "Balint" },
  { nume: "Temereşti", simplu: "Temeresti", comuna: "Faget" },
  { nume: "Teremia Mare" },
  { nume: "Teremia Mică", simplu: "Teremia Mica", comuna: "Teremia Mare" },
  { nume: "Teş", simplu: "Tes", comuna: "Brestovat" },
  { nume: "Timişoara", simplu: "Timisoara" },
  { nume: "Ţipari", simplu: "Tipari", comuna: "Costeiu" },
  { nume: "Toager", comuna: "Giera" },
  { nume: "Tomeşti", simplu: "Tomesti" },
  { nume: "Tomnatic", comuna: "Lovrin" },
  { nume: "Topla", comuna: "Manastiur" },
  { nume: "Topolovăţu Mare", simplu: "Topolovatu Mare" },
  {
    nume: "Topolovăţu Mic",
    simplu: "Topolovatu Mic",
    comuna: "Topolovatu Mare",
  },
  { nume: "Tormac" },
  { nume: "Traian Vuia" },
  { nume: "Uihei", comuna: "Biled" },
  { nume: "Uivar" },
  { nume: "Uliuc", comuna: "Sacosu Turcesc" },
  { nume: "Unip", comuna: "Sacosu Turcesc" },
  { nume: "Urseni", comuna: "Mosnita Noua" },
  { nume: "Utvin", comuna: "Sanmihaiu Roman" },
  { nume: "Vălcani", simplu: "Valcani", comuna: "Dudestii Vechi" },
  {
    nume: "Valea Lungă Română",
    simplu: "Valea Lunga Romana",
    comuna: "Costeiu",
  },
  { nume: "Variaş", simplu: "Varias" },
  { nume: "Victor Vlad Delamarina" },
  { nume: "Vişag", simplu: "Visag", comuna: "Victor Vlad Delamarina" },
  { nume: "Vizejdia", comuna: "Lovrin" },
  { nume: "Vizma", comuna: "Secas" },
  { nume: "Voiteg" },
  { nume: "Vucova", comuna: "Cheveresu Mare" },
  { nume: "Zgribeşti", simplu: "Zgribesti", comuna: "Stiuca" },
  { nume: "Zolt", comuna: "Fardea" },
  { nume: "Zorani", comuna: "Margina" },
];
