export const tl = [
  { nume: "Agighiol", comuna: "Valea Nucarilor" },
  { nume: "Alba", comuna: "Izvoarele" },
  { nume: "Ardealu", comuna: "Dorobantu" },
  { nume: "Atmagea", comuna: "Ciucurova" },
  { nume: "Babadag" },
  { nume: "Baia" },
  { nume: "Balabancea", comuna: "Hamcearca" },
  { nume: "Băltenii de Jos", simplu: "Baltenii de Jos", comuna: "Mahmudia" },
  { nume: "Băltenii de Sus", simplu: "Baltenii de Sus", comuna: "Mahmudia" },
  { nume: "Beidaud" },
  { nume: "Beştepe", simplu: "Bestepe", comuna: "Mahmudia" },
  { nume: "C.a. Rosetti" },
  { nume: "Calfa", comuna: "Topolog" },
  { nume: "Camena", comuna: "Baia" },
  { nume: "Căprioara", simplu: "Caprioara", comuna: "Hamcearca" },
  { nume: "Caraorman", comuna: "Crisan" },
  { nume: "Carcaliu" },
  { nume: "Cardon", comuna: "C.A. Rosetti" },
  { nume: "Cârjelari", simplu: "Carjelari", comuna: "Dorobantu" },
  { nume: "Casimcea" },
  { nume: "Câşliţa", simplu: "Caslita", comuna: "Chilia Veche" },
  { nume: "Cataloi", comuna: "Frecatei" },
  { nume: "Caugagia", comuna: "Baia" },
  { nume: "Ceamurlia de Jos" },
  { nume: "Ceamurlia de Sus", comuna: "Baia" },
  { nume: "Ceatalchioi" },
  { nume: "Cerbu", comuna: "Topolog" },
  { nume: "Cerna" },
  { nume: "Chilia Veche" },
  { nume: "Cişmeaua Nouă", simplu: "Cismeaua Noua", comuna: "Casimcea" },
  { nume: "Ciucurova" },
  { nume: "Cloşca", simplu: "Closca", comuna: "Horia" },
  { nume: "Colina", comuna: "Murighiol" },
  { nume: "Corugea", comuna: "Casimcea" },
  { nume: "Crişan", simplu: "Crisan" },
  { nume: "Dăeni", simplu: "Daeni" },
  { nume: "Dorobanţu", simplu: "Dorobantu" },
  { nume: "Dunavăţu de Jos", simplu: "Dunavatu de Jos", comuna: "Murighiol" },
  { nume: "Dunavăţu de Sus", simplu: "Dunavatu de Sus", comuna: "Murighiol" },
  { nume: "Enisala", comuna: "Sarichioi" },
  { nume: "Făgăraşu Nou", simplu: "Fagarasu Nou", comuna: "Topolog" },
  { nume: "Fântâna Mare", simplu: "Fantana Mare", comuna: "Ciucurova" },
  { nume: "Fântâna Oilor", simplu: "Fantana Oilor", comuna: "Dorobantu" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Horia" },
  { nume: "Frecăţei", simplu: "Frecatei" },
  { nume: "Garvăn", simplu: "Garvan", comuna: "Jijila" },
  { nume: "General Praporgescu", comuna: "Cerna" },
  { nume: "Gorgova", comuna: "Maliuc" },
  { nume: "Greci" },
  { nume: "Grindu" },
  { nume: "Haidar", comuna: "Casimcea" },
  { nume: "Hamcearca" },
  { nume: "Horia" },
  { nume: "I.c.brătianu", simplu: "I.c.bratianu" },
  { nume: "Iazurile", comuna: "Valea Nucarilor" },
  { nume: "Ilganii de Jos", comuna: "Nufaru" },
  { nume: "Ilganii de Sus", comuna: "Maliuc" },
  { nume: "Isaccea" },
  { nume: "Iulia", comuna: "Izvoarele" },
  { nume: "Izvoarele" },
  { nume: "Jijila" },
  { nume: "Jurilovca" },
  { nume: "Lăstuni", simplu: "Lastuni", comuna: "Mihail Kogalniceanu" },
  { nume: "Letea", comuna: "C.A. Rosetti" },
  { nume: "Luminiţa", simplu: "Luminita", comuna: "Topolog" },
  { nume: "Lunca", comuna: "Ceamurlia De Jos" },
  { nume: "Luncaviţa", simplu: "Luncavita" },
  { nume: "Măcin", simplu: "Macin" },
  { nume: "Măgurele", simplu: "Magurele", comuna: "Topolog" },
  { nume: "Mahmudia" },
  { nume: "Malcoci", comuna: "Nufaru" },
  { nume: "Maliuc" },
  { nume: "Meşteru", simplu: "Mesteru", comuna: "Dorobantu" },
  { nume: "Mihai Bravu" },
  { nume: "Mihail Kogălniceanu", simplu: "Mihail Kogalniceanu" },
  { nume: "Mila 23", comuna: "Crisan" },
  { nume: "Mina Altân Tepe", simplu: "Mina Altan Tepe", comuna: "Stejaru" },
  { nume: "Mineri", comuna: "Somova" },
  { nume: "Mircea Vodă", simplu: "Mircea Voda", comuna: "Cerna" },
  { nume: "Murighiol" },
  { nume: "Nalbant" },
  { nume: "Neatârnarea", simplu: "Neatarnarea", comuna: "Beidaud" },
  { nume: "Nicolae Bălcescu", simplu: "Nicolae Balcescu", comuna: "Nalbant" },
  { nume: "Niculiţel", simplu: "Niculitel" },
  { nume: "Nifon", comuna: "Hamcearca" },
  { nume: "Nufăru", simplu: "Nufaru" },
  { nume: "Ostrov" },
  { nume: "Ostrovu Tătaru", simplu: "Ostrovu Tataru", comuna: "Chilia Veche" },
  { nume: "Panduru", comuna: "Baia" },
  { nume: "Parcheş", simplu: "Parches", comuna: "Somova" },
  { nume: "Pardina" },
  { nume: "Partizani", comuna: "Maliuc" },
  { nume: "Pătlăgeanca", simplu: "Patlageanca", comuna: "Ceatalchioi" },
  { nume: "Peceneaga" },
  { nume: "Periprava", comuna: "C.A. Rosetti" },
  { nume: "Piatra", comuna: "Ostrov" },
  { nume: "Plauru", comuna: "Ceatalchioi" },
  { nume: "Plopul", comuna: "Murighiol" },
  { nume: "Poşta", simplu: "Posta", comuna: "Frecatei" },
  { nume: "Rachelu", comuna: "Luncavita" },
  { nume: "Rahman", comuna: "Casimcea" },
  { nume: "Rândunica", simplu: "Randunica", comuna: "Mihail Kogalniceanu" },
  { nume: "Războieni", simplu: "Razboieni", comuna: "Casimcea" },
  { nume: "Revărsarea", simplu: "Revarsarea", comuna: "Isaccea" },
  { nume: "Sabangia", comuna: "Sarichioi" },
  { nume: "Sălceni", simplu: "Salceni", comuna: "Ceatalchioi" },
  { nume: "Sălcioara", simplu: "Salcioara", comuna: "Jurilovca" },
  { nume: "Sâmbăta Nouă", simplu: "Sambata Noua", comuna: "Topolog" },
  { nume: "Sarichioi" },
  { nume: "Sarighiol de Deal", comuna: "Beidaud" },
  { nume: "Sarinasuf", comuna: "Murighiol" },
  { nume: "Satu Nou", comuna: "Mihai Bravu" },
  { nume: "Sfântu Gheorghe", simplu: "Sfantu Gheorghe" },
  { nume: "Sfiştofca", simplu: "Sfistofca", comuna: "C.A. Rosetti" },
  { nume: "Slava Cercheză", simplu: "Slava Cercheza" },
  { nume: "Slava Rusă", simplu: "Slava Rusa", comuna: "Slava Cercheza" },
  { nume: "Smârdan", simplu: "Smardan" },
  { nume: "Somova" },
  { nume: "Stânca", simplu: "Stanca", comuna: "Casimcea" },
  { nume: "Stejaru" },
  { nume: "Sulina" },
  { nume: "Tatanir", comuna: "Chilia Veche" },
  { nume: "Teliţa", simplu: "Telita", comuna: "Frecatei" },
  { nume: "Tichileşti", simplu: "Tichilesti", comuna: "Isaccea" },
  { nume: "Topolog" },
  { nume: "Traian", comuna: "Cerna" },
  { nume: "Trestenic", comuna: "Nalbant" },
  { nume: "Tudor Vladimirescu", comuna: "Tulcea" },
  { nume: "Tulcea" },
  { nume: "Turcoaia" },
  { nume: "Turda", comuna: "Mihai Bravu" },
  { nume: "Uzlina", comuna: "Murighiol" },
  { nume: "Văcăreni", simplu: "Vacareni" },
  { nume: "Valea Nucarilor" },
  { nume: "Valea Teilor", comuna: "Izvoarele" },
  { nume: "Vasile Alecsandri", comuna: "Stejaru" },
  { nume: "Victoria", comuna: "Nufaru" },
  { nume: "Vişina", simplu: "Visina", comuna: "Jurilovca" },
  { nume: "Visterna", comuna: "Sarichioi" },
  { nume: "Vulturu", comuna: "Maliuc" },
  { nume: "Zebil", comuna: "Sarichioi" },
];
