export const vs = [
  { nume: "1 Decembrie", comuna: "Banca" },
  { nume: "Albești", simplu: "Albesti" },
  { nume: "Albești", simplu: "Albesti", comuna: "Delesti" },
  { nume: "Albina", comuna: "Ivanesti" },
  { nume: "Albița", simplu: "Albita", comuna: "Dranceni" },
  { nume: "Alexandru Vlahuță", simplu: "Alexandru Vlahuta" },
  { nume: "Armășeni", simplu: "Armaseni", comuna: "Bacesti" },
  { nume: "Armășeni", simplu: "Armaseni", comuna: "Bunesti-Averesti" },
  { nume: "Armășoaia", simplu: "Armasoaia", comuna: "Pungesti" },
  { nume: "Arșița", simplu: "Arsita", comuna: "Bogdana" },
  { nume: "Arsura" },
  { nume: "Averești", simplu: "Averesti", comuna: "Bunesti-Averesti" },
  { nume: "Avrămești", simplu: "Avramesti", comuna: "Voinesti" },
  { nume: "Băbușa", simplu: "Babusa", comuna: "Bacesti" },
  { nume: "Băbuța", simplu: "Babuta", comuna: "Dragomiresti" },
  { nume: "Băcani", simplu: "Bacani" },
  { nume: "Băcăoani", simplu: "Bacaoani", comuna: "Muntenii De Jos" },
  { nume: "Băcești", simplu: "Bacesti" },
  { nume: "Bădeana", simplu: "Badeana", comuna: "Tutova" },
  { nume: "Bahnari", comuna: "Vaslui" },
  { nume: "Băile Drânceni", simplu: "Baile Dranceni", comuna: "Dranceni" },
  { nume: "Bălești", simplu: "Balesti", comuna: "Delesti" },
  { nume: "Băltățeni", simplu: "Baltateni", comuna: "Bacani" },
  { nume: "Bălțați", simplu: "Baltati", comuna: "Tatarani" },
  { nume: "Bălteni-Deal", simplu: "Balteni-Deal", comuna: "Balteni" },
  { nume: "Bălteni", simplu: "Balteni" },
  { nume: "Banca" },
  { nume: "Băncești", simplu: "Bancesti", comuna: "Voinesti" },
  { nume: "Barboși", simplu: "Barbosi", comuna: "Hoceni" },
  { nume: "Bârlad", simplu: "Barlad", comuna: "Birlad" },
  { nume: "Bârlălești", simplu: "Barlalesti", comuna: "Epureni" },
  { nume: "Bărtăluș-Mocani", simplu: "Bartalus-Mocani", comuna: "Puiesti" },
  { nume: "Bărtăluș-Răzeși", simplu: "Bartalus-Razesi", comuna: "Puiesti" },
  { nume: "Bârzești", simplu: "Barzesti", comuna: "Stefan Cel Mare" },
  { nume: "Bejenești", simplu: "Bejenesti", comuna: "Laza" },
  { nume: "Belcești", simplu: "Belcesti", comuna: "Ivesti" },
  { nume: "Belzeni", comuna: "Dragomiresti" },
  { nume: "Benești", simplu: "Benesti", comuna: "Tanacu" },
  { nume: "Bereasa", comuna: "Danesti" },
  { nume: "Berezeni" },
  { nume: "Blăgești", simplu: "Blagesti" },
  { nume: "Bleșca", simplu: "Blesca", comuna: "Ivanesti" },
  { nume: "Bobești", simplu: "Bobesti", comuna: "Duda-Epureni" },
  { nume: "Bogdana-Voloseni", comuna: "Stanilesti" },
  { nume: "Bogdana" },
  { nume: "Bogdănești", simplu: "Bogdanesti" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Falciu" },
  { nume: "Bogdănița", simplu: "Bogdanita" },
  { nume: "Bogești", simplu: "Bogesti", comuna: "Pogana" },
  { nume: "Bolați", simplu: "Bolati", comuna: "Rebricea" },
  { nume: "Borodești", simplu: "Borodesti", comuna: "Tutova" },
  { nume: "Boțești", simplu: "Botesti" },
  { nume: "Boțoaia", simplu: "Botoaia", comuna: "Danesti" },
  { nume: "Botoi", comuna: "Dragomiresti" },
  { nume: "Boușori", simplu: "Bousori", comuna: "Solesti" },
  { nume: "Bozia", comuna: "Falciu" },
  { nume: "Brădești", simplu: "Bradesti", comuna: "Vinderei" },
  { nume: "Brăhășoaia", simplu: "Brahasoaia", comuna: "Stefan Cel Mare" },
  { nume: "Brodoc", comuna: "Vaslui" },
  { nume: "Broscoșești", simplu: "Broscosesti", comuna: "Lunca Banului" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Ivanesti" },
  { nume: "Buda", comuna: "Alexandru Vlahuta" },
  { nume: "Buda", comuna: "Bogdanesti" },
  { nume: "Buda", comuna: "Osesti" },
  { nume: "Budești", simplu: "Budesti", comuna: "Cretesti" },
  { nume: "Budu Cantemir", comuna: "Stanilesti" },
  { nume: "Buhăiești", simplu: "Buhaiesti", comuna: "Vulturesti" },
  { nume: "Bulboaca", comuna: "Deleni" },
  { nume: "Bumbăta", simplu: "Bumbata", comuna: "Vetrisoaia" },
  { nume: "Bunești", simplu: "Bunesti", comuna: "Bunesti-Averesti" },
  { nume: "Bursuci", comuna: "Epureni" },
  { nume: "Buscata", comuna: "Ivanesti" },
  { nume: "Butucăria", simplu: "Butucaria", comuna: "Zapodeni" },
  { nume: "Călimănești", simplu: "Calimanesti", comuna: "Puiesti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Stefan Cel Mare" },
  { nume: "Cănțălărești", simplu: "Cantalaresti", comuna: "Stefan Cel Mare" },
  { nume: "Căpotești", simplu: "Capotesti", comuna: "Padureni" },
  { nume: "Căpușneni", simplu: "Capusneni", comuna: "Lipovat" },
  { nume: "Cârja", simplu: "Carja", comuna: "Murgeni" },
  { nume: "Cârjoani", simplu: "Carjoani", comuna: "Pogana" },
  { nume: "Cârțibași", simplu: "Cartibasi", comuna: "Bogdanita" },
  { nume: "Căzănești", simplu: "Cazanesti", comuna: "Negresti" },
  { nume: "Cepești", simplu: "Cepesti", comuna: "Bogdanita" },
  { nume: "Cetățuia", simplu: "Cetatuia", comuna: "Puiesti" },
  { nume: "Chersăcosu", simplu: "Chersacosu", comuna: "Stanilesti" },
  { nume: "Chetrești", simplu: "Chetresti", comuna: "Balteni" },
  { nume: "Chetrosu", comuna: "Gherghesti" },
  { nume: "Chilieni", comuna: "Coroiesti" },
  { nume: "Chircești", simplu: "Chircesti", comuna: "Miclesti" },
  { nume: "Chițcani", simplu: "Chitcani", comuna: "Costesti" },
  { nume: "Chițoc", simplu: "Chitoc", comuna: "Lipovat" },
  { nume: "Cioatele", comuna: "Negresti" },
  { nume: "Ciocani", comuna: "Perieni" },
  { nume: "Ciofeni", comuna: "Zapodeni" },
  { nume: "Ciortolom", comuna: "Tutova" },
  { nume: "Ciuperca", comuna: "Dragomiresti" },
  { nume: "Codăești", simplu: "Codaesti" },
  { nume: "Codreni", comuna: "Rosiesti" },
  { nume: "Condrea", comuna: "Lunca Banului" },
  { nume: "Copăceana", simplu: "Copaceana", comuna: "Falciu" },
  { nume: "Corbu", comuna: "Lipovat" },
  { nume: "Corni-Albești", simplu: "Corni-Albesti", comuna: "Albesti" },
  { nume: "Corobănești", simplu: "Corobanesti", comuna: "Voinesti" },
  { nume: "Corodești", simplu: "Corodesti", comuna: "Gherghesti" },
  { nume: "Coroiești", simplu: "Coroiesti" },
  { nume: "Coroiești", simplu: "Coroiesti", comuna: "Bogdanita" },
  {
    nume: "Coroieștii de Sus",
    simplu: "Coroiestii de Sus",
    comuna: "Coroiesti",
  },
  { nume: "Coroiu", comuna: "Tutova" },
  { nume: "Coșca", simplu: "Cosca", comuna: "Ivanesti" },
  { nume: "Coșești", simplu: "Cosesti", comuna: "Ivanesti" },
  { nume: "Costești", simplu: "Costesti" },
  { nume: "Cotic", comuna: "Todiresti" },
  { nume: "Cozmești", simplu: "Cozmesti", comuna: "Delesti" },
  { nume: "Crăciunești", simplu: "Craciunesti", comuna: "Rebricea" },
  { nume: "Crâng", simplu: "Crang", comuna: "Perieni" },
  { nume: "Crângu Nou", simplu: "Crangu Nou", comuna: "Perieni" },
  { nume: "Crasna", comuna: "Albesti" },
  { nume: "Crăsnășeni", simplu: "Crasnaseni", comuna: "Tatarani" },
  { nume: "Crețești", simplu: "Cretesti" },
  { nume: "Crețeștii de Sus", simplu: "Cretestii de Sus", comuna: "Cretesti" },
  { nume: "Cristești", simplu: "Cristesti", comuna: "Puiesti" },
  { nume: "Crivești", simplu: "Crivesti", comuna: "Tutova" },
  { nume: "Cujba", comuna: "Tacuta" },
  { nume: "Cursești-Deal", simplu: "Cursesti-Deal", comuna: "Pungesti" },
  { nume: "Cursești-Vale", simplu: "Cursesti-Vale", comuna: "Pungesti" },
  { nume: "Curteni", comuna: "Oltenesti" },
  { nume: "Dănești", simplu: "Danesti" },
  { nume: "Davidești", simplu: "Davidesti", comuna: "Padureni" },
  { nume: "Dealu Mare", comuna: "Zorleni" },
  { nume: "Dealu Secării", simplu: "Dealu Secarii", comuna: "Poienesti" },
  { nume: "Delea", comuna: "Zapodeni" },
  { nume: "Deleni" },
  { nume: "Deleni", comuna: "Hoceni" },
  { nume: "Delești", simplu: "Delesti" },
  { nume: "Dinga", comuna: "Costesti" },
  { nume: "Doagele", comuna: "Dragomiresti" },
  { nume: "Dobroslovești", simplu: "Dobroslovesti", comuna: "Zapodeni" },
  { nume: "Docăneasa", simplu: "Docaneasa", comuna: "Vinderei" },
  { nume: "Docani", comuna: "Vinderei" },
  { nume: "Dodești", simplu: "Dodesti", comuna: "Viisoara" },
  { nume: "Drăgești", simplu: "Dragesti", comuna: "Todiresti" },
  { nume: "Dragomănești", simplu: "Dragomanesti", comuna: "Gherghesti" },
  { nume: "Dragomirești", simplu: "Dragomiresti" },
  { nume: "Drânceni", simplu: "Dranceni" },
  { nume: "Draxeni", comuna: "Rebricea" },
  { nume: "Drăxeni", simplu: "Draxeni", comuna: "Gherghesti" },
  { nume: "Drujești", simplu: "Drujesti", comuna: "Bacani" },
  { nume: "Duda", comuna: "Duda-Epureni" },
  { nume: "Dumasca", comuna: "Tacuta" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Garceni" },
  { nume: "Dumești", simplu: "Dumesti" },
  { nume: "Dumeștii Vechi", simplu: "Dumestii Vechi", comuna: "Dumesti" },
  { nume: "Emil Racoviță", simplu: "Emil Racovita", comuna: "Danesti" },
  { nume: "Epureni" },
  { nume: "Epureni", comuna: "Duda-Epureni" },
  { nume: "Fălciu", simplu: "Falciu" },
  {
    nume: "Fântâna Blănarului",
    simplu: "Fantana Blanarului",
    comuna: "Bogdana",
  },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Puiesti" },
  { nume: "Fâstâci", simplu: "Fastaci", comuna: "Delesti" },
  { nume: "Fedești", simplu: "Fedesti", comuna: "Suletea" },
  { nume: "Ferești", simplu: "Feresti", comuna: "Valeni" },
  { nume: "Floreni", comuna: "Murgeni" },
  { nume: "Florești", simplu: "Floresti", comuna: "Poienesti" },
  { nume: "Focșa", simplu: "Focsa", comuna: "Lunca Banului" },
  { nume: "Focșeașca", simplu: "Focseasca", comuna: "Tacuta" },
  { nume: "Frasinu", comuna: "Poienesti" },
  { nume: "Fruntișeni", simplu: "Fruntiseni", comuna: "Grivita" },
  { nume: "Fulgu", comuna: "Puiesti" },
  { nume: "Fundătura Mare", simplu: "Fundatura Mare", comuna: "Ivanesti" },
  { nume: "Fundătura Mică", simplu: "Fundatura Mica", comuna: "Ivanesti" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Arsura" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Delesti" },
  { nume: "Fundu Văii", simplu: "Fundu Vaii", comuna: "Lipovat" },
  { nume: "Fundu Văii", simplu: "Fundu Vaii", comuna: "Poienesti" },
  { nume: "Găgești", simplu: "Gagesti" },
  { nume: "Gâlțești", simplu: "Galtesti", comuna: "Puiesti" },
  { nume: "Gănești", simplu: "Ganesti", comuna: "Botesti" },
  { nume: "Gara Banca", comuna: "Banca" },
  { nume: "Gara Docăneasa", simplu: "Gara Docaneasa", comuna: "Vinderei" },
  { nume: "Gara Roșiești", simplu: "Gara Rosiesti", comuna: "Rosiesti" },
  { nume: "Gara Tălășman", simplu: "Gara Talasman", comuna: "Vinderei" },
  { nume: "Gârceni", simplu: "Garceni" },
  { nume: "Gârdești", simplu: "Gardesti", comuna: "Voinesti" },
  { nume: "Găvanu", simplu: "Gavanu", comuna: "Bogdana" },
  { nume: "Ghergheleu", comuna: "Codaesti" },
  { nume: "Gherghești", simplu: "Gherghesti" },
  { nume: "Ghermănești", simplu: "Ghermanesti", comuna: "Banca" },
  { nume: "Ghermănești", simplu: "Ghermanesti", comuna: "Dranceni" },
  { nume: "Ghicani", comuna: "Alexandru Vlahuta" },
  { nume: "Ghireasca", comuna: "Malusteni" },
  { nume: "Giurcani", comuna: "Gagesti" },
  { nume: "Giurgești", simplu: "Giurgesti", comuna: "Tatarani" },
  { nume: "Glodeni", comuna: "Negresti" },
  { nume: "Grăjdeni", simplu: "Grajdeni", comuna: "Grivita" },
  { nume: "Grivița", simplu: "Grivita" },
  { nume: "Grumezoaia", comuna: "Dimitrie Cantemir" },
  { nume: "Gugești", simplu: "Gugesti", comuna: "Botesti" },
  { nume: "Gura Albești", simplu: "Gura Albesti", comuna: "Albesti" },
  { nume: "Gura Idrici", comuna: "Rosiesti" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Stanilesti" },
  { nume: "Gușiței", simplu: "Gusitei", comuna: "Dimitrie Cantemir" },
  { nume: "Hălărești", simplu: "Halaresti", comuna: "Iana" },
  { nume: "Halta Dodești", simplu: "Halta Dodesti", comuna: "Viisoara" },
  { nume: "Hârsova", simplu: "Harsova", comuna: "Delesti" },
  { nume: "Hârșoveni", simplu: "Harsoveni", comuna: "Ivanesti" },
  { nume: "Hoceni" },
  { nume: "Hordila", comuna: "Pungesti" },
  { nume: "Hordilești", simplu: "Hordilesti", comuna: "Delesti" },
  { nume: "Horga", comuna: "Epureni" },
  { nume: "Horoiata", comuna: "Bogdanesti" },
  { nume: "Hreasca", comuna: "Coroiesti" },
  { nume: "Huc", comuna: "Todiresti" },
  { nume: "Hupca", comuna: "Bogdanesti" },
  { nume: "Hurdugi", comuna: "Dimitrie Cantemir" },
  { nume: "Huși", simplu: "Husi" },
  { nume: "Iana" },
  { nume: "Iaz", comuna: "Solesti" },
  { nume: "Ibănești", simplu: "Ibanesti" },
  { nume: "Idrici", comuna: "Rosiesti" },
  { nume: "Iezer", comuna: "Puiesti" },
  { nume: "Iezerel", comuna: "Ivanesti" },
  { nume: "Igești", simplu: "Igesti", comuna: "Blagesti" },
  { nume: "Ivănești", simplu: "Ivanesti" },
  { nume: "Ivănești", simplu: "Ivanesti", comuna: "Padureni" },
  { nume: "Ivești", simplu: "Ivesti" },
  { nume: "Jigălia", simplu: "Jigalia", comuna: "Suletea" },
  { nume: "Lacu Babei", comuna: "Bogdana" },
  { nume: "Lălești", simplu: "Lalesti", comuna: "Puiesti" },
  { nume: "Lățești", simplu: "Latesti", comuna: "Murgeni" },
  { nume: "Laza" },
  { nume: "Lazu", comuna: "Gherghesti" },
  { nume: "Leoști", simplu: "Leosti", comuna: "Padureni" },
  { nume: "Leoști", simplu: "Leosti", comuna: "Tatarani" },
  { nume: "Lipovăț", simplu: "Lipovat" },
  { nume: "Lunca Banului" },
  { nume: "Lunca Veche", comuna: "Lunca Banului" },
  { nume: "Lunca", comuna: "Gherghesti" },
  { nume: "Lupești", simplu: "Lupesti", comuna: "Malusteni" },
  { nume: "Măcrești", simplu: "Macresti", comuna: "Rebricea" },
  { nume: "Măcrești", simplu: "Macresti", comuna: "Zapodeni" },
  { nume: "Mălăiești", simplu: "Malaiesti", comuna: "Vutcani" },
  { nume: "Mălușteni", simplu: "Malusteni" },
  { nume: "Mânăstirea", simplu: "Manastirea", comuna: "Delesti" },
  { nume: "Mânăstirea", simplu: "Manastirea", comuna: "Malusteni" },
  { nume: "Mânjești", simplu: "Manjesti", comuna: "Muntenii De Jos" },
  { nume: "Mantu", comuna: "Tatarani" },
  { nume: "Mânzătești", simplu: "Manzatesti", comuna: "Malusteni" },
  { nume: "Mânzați", simplu: "Manzati", comuna: "Ibanesti" },
  { nume: "Mărășeni", simplu: "Maraseni", comuna: "Stefan Cel Mare" },
  { nume: "Mărășești", simplu: "Marasesti", comuna: "Voinesti" },
  { nume: "Măscurei", simplu: "Mascurei", comuna: "Pogana" },
  { nume: "Miclești", simplu: "Miclesti" },
  { nume: "Miclești", simplu: "Miclesti", comuna: "Banca" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Arsura",
  },
  { nume: "Mircești", simplu: "Mircesti", comuna: "Tacuta" },
  { nume: "Mireni", comuna: "Coroiesti" },
  { nume: "Mitoc", comuna: "Banca" },
  { nume: "Moara Domnească", simplu: "Moara Domneasca", comuna: "Valeni" },
  { nume: "Moara Grecilor", comuna: "Vaslui" },
  { nume: "Morăreni", simplu: "Morareni", comuna: "Alexandru Vlahuta" },
  { nume: "Moreni", comuna: "Deleni" },
  { nume: "Movileni", comuna: "Coroiesti" },
  { nume: "Muntenești", simplu: "Muntenesti", comuna: "Stefan Cel Mare" },
  { nume: "Muntenii de Jos" },
  { nume: "Muntenii de Sus", comuna: "Tanacu" },
  { nume: "Murgeni" },
  { nume: "Mușata", simplu: "Musata", comuna: "Berezeni" },
  { nume: "Negrești", simplu: "Negresti" },
  { nume: "Obârșeni", simplu: "Obarseni", comuna: "Vinderei" },
  { nume: "Obârșeni", simplu: "Obarseni", comuna: "Voinesti" },
  {
    nume: "Obârșenii Lingurari",
    simplu: "Obarsenii Lingurari",
    comuna: "Voinesti",
  },
  { nume: "Odaia Bogdana", comuna: "Falciu" },
  { nume: "Odaia Bursucani", comuna: "Grivita" },
  { nume: "Oltenești", simplu: "Oltenesti" },
  { nume: "Oprișița", simplu: "Oprisita", comuna: "Poienesti" },
  { nume: "Orgoiești", simplu: "Orgoiesti", comuna: "Bogdanesti" },
  { nume: "Oșești", simplu: "Osesti" },
  { nume: "Oțeleni", simplu: "Oteleni", comuna: "Hoceni" },
  { nume: "Oțetoaia", simplu: "Otetoaia", comuna: "Lunca Banului" },
  { nume: "Păcurărești", simplu: "Pacuraresti", comuna: "Coroiesti" },
  { nume: "Pădureni", simplu: "Padureni" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Osesti" },
  { nume: "Pâhna", simplu: "Pahna", comuna: "Oltenesti" },
  { nume: "Pâhnești", simplu: "Pahnesti", comuna: "Arsura" },
  { nume: "Păltiniș", simplu: "Paltinis", comuna: "Bacesti" },
  { nume: "Parpanița", simplu: "Parpanita", comuna: "Negresti" },
  { nume: "Pârvești", simplu: "Parvesti", comuna: "Costesti" },
  { nume: "Peicani", comuna: "Gagesti" },
  { nume: "Perieni" },
  { nume: "Plopeni", comuna: "Bogdana" },
  { nume: "Plopi", comuna: "Bunesti-Averesti" },
  { nume: "Plopoasa", comuna: "Todiresti" },
  { nume: "Plotonești", simplu: "Plotonesti", comuna: "Dimitrie Cantemir" },
  { nume: "Pochidia", comuna: "Tutova" },
  { nume: "Podeni", comuna: "Vulturesti" },
  { nume: "Podu Oprii", comuna: "Bunesti-Averesti" },
  { nume: "Podu Petriș", simplu: "Podu Petris", comuna: "Perieni" },
  { nume: "Pogana" },
  { nume: "Pogănești", simplu: "Poganesti", comuna: "Stanilesti" },
  { nume: "Pogonești", simplu: "Pogonesti", comuna: "Ivesti" },
  { nume: "Poiana lui Alexa", comuna: "Laza" },
  { nume: "Poiana Pietrei", comuna: "Dragomiresti" },
  { nume: "Poiana", comuna: "Negresti" },
  { nume: "Poienești-Deal", simplu: "Poienesti-Deal", comuna: "Poienesti" },
  { nume: "Poienești", simplu: "Poienesti" },
  { nume: "Polocin", comuna: "Ivesti" },
  { nume: "Popeni", comuna: "Gagesti" },
  { nume: "Popeni", comuna: "Zorleni" },
  { nume: "Popești", simplu: "Popesti", comuna: "Dragomiresti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Miclesti" },
  { nume: "Portari", comuna: "Zapodeni" },
  { nume: "Poșta Elan", simplu: "Posta Elan", comuna: "Vutcani" },
  { nume: "Pribești", simplu: "Pribesti", comuna: "Codaesti" },
  { nume: "Protopopești", simplu: "Protopopesti", comuna: "Tacuta" },
  { nume: "Puiești", simplu: "Puiesti" },
  { nume: "Pungești", simplu: "Pungesti" },
  { nume: "Puntișeni", simplu: "Puntiseni", comuna: "Costesti" },
  { nume: "Pușcași", simplu: "Puscasi", comuna: "Laza" },
  { nume: "Puțu Olarului", simplu: "Putu Olarului", comuna: "Ibanesti" },
  { nume: "Racova", comuna: "Garceni" },
  { nume: "Racovița", simplu: "Racovita", comuna: "Garceni" },
  { nume: "Rădăești", simplu: "Radaesti", comuna: "Bogdanita" },
  { nume: "Rădeni", simplu: "Radeni", comuna: "Dragomiresti" },
  { nume: "Rădești", simplu: "Radesti", comuna: "Costesti" },
  { nume: "Răducani", simplu: "Raducani", comuna: "Lunca Banului" },
  { nume: "Răduiești", simplu: "Raduiesti", comuna: "Delesti" },
  { nume: "Rafaila", comuna: "Todiresti" },
  { nume: "Raiu", comuna: "Murgeni" },
  { nume: "Rânceni", simplu: "Ranceni", comuna: "Berezeni" },
  { nume: "Rânzești", simplu: "Ranzesti", comuna: "Falciu" },
  { nume: "Rapșa", simplu: "Rapsa", comuna: "Pungesti" },
  { nume: "Rășcani", simplu: "Rascani", comuna: "Danesti" },
  { nume: "Rășcani", simplu: "Rascani", comuna: "Suletea" },
  { nume: "Râșești", simplu: "Rasesti", comuna: "Dranceni" },
  { nume: "Râșnița", simplu: "Rasnita", comuna: "Laza" },
  { nume: "Rateșu Cuzei", simplu: "Ratesu Cuzei", comuna: "Rebricea" },
  { nume: "Rebricea" },
  { nume: "Recea", comuna: "Iana" },
  { nume: "Rediu Galian", comuna: "Codaesti" },
  { nume: "Rediu", comuna: "Hoceni" },
  { nume: "Rediu", comuna: "Rosiesti" },
  { nume: "Rediu", comuna: "Vaslui" },
  { nume: "Roșiești", simplu: "Rosiesti" },
  { nume: "Roșiori", simplu: "Rosiori", comuna: "Bunesti-Averesti" },
  { nume: "Rotari", comuna: "Puiesti" },
  { nume: "Rugăria", simplu: "Rugaria", comuna: "Voinesti" },
  { nume: "Rusca", comuna: "Padureni" },
  { nume: "Ruși", simplu: "Rusi", comuna: "Puiesti" },
  { nume: "Sălceni", simplu: "Salceni", comuna: "Tutova" },
  { nume: "Sălcioara", simplu: "Salcioara", comuna: "Banca" },
  { nume: "Sărățeni", simplu: "Sarateni", comuna: "Murgeni" },
  { nume: "Săratu", simplu: "Saratu", comuna: "Stanilesti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Banca" },
  { nume: "Sasova", comuna: "Rebricea" },
  { nume: "Satu Nou", comuna: "Banca" },
  { nume: "Satu Nou", comuna: "Berezeni" },
  { nume: "Satu Nou", comuna: "Cretesti" },
  { nume: "Satu Nou", comuna: "Solesti" },
  { nume: "Satu Nou", comuna: "Tanacu" },
  { nume: "Satu Nou", comuna: "Tutova" },
  { nume: "Sauca", comuna: "Laza" },
  { nume: "Schineni", comuna: "Murgeni" },
  { nume: "Schinetea", comuna: "Dumesti" },
  { nume: "Schitu", comuna: "Bogdanita" },
  { nume: "Secuia", comuna: "Muntenii De Jos" },
  { nume: "Semenea", comuna: "Dragomiresti" },
  { nume: "Șerbotești", simplu: "Serbotesti", comuna: "Solesti" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Iana" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Pungesti" },
  { nume: "Siliștea", simplu: "Silistea", comuna: "Todiresti" },
  { nume: "Simila", comuna: "Zorleni" },
  { nume: "Similișoara", simplu: "Similisoara", comuna: "Bogdana" },
  { nume: "Sipeni", comuna: "Blagesti" },
  { nume: "Șișcani", simplu: "Siscani", comuna: "Hoceni" },
  { nume: "Slobozia", comuna: "Garceni" },
  { nume: "Soci", comuna: "Gherghesti" },
  { nume: "Sofieni", comuna: "Tacuta" },
  { nume: "Sofronești", simplu: "Sofronesti", comuna: "Todiresti" },
  { nume: "Solești", simplu: "Solesti" },
  { nume: "Șopârleni", simplu: "Soparleni", comuna: "Dranceni" },
  { nume: "Stâncășeni", simplu: "Stancaseni", comuna: "Voinesti" },
  { nume: "Stănilești", simplu: "Stanilesti" },
  { nume: "Ștefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Stejaru", comuna: "Pungesti" },
  { nume: "Știoborăni", simplu: "Stioborani", comuna: "Solesti" },
  { nume: "Stoișești", simplu: "Stoisesti", comuna: "Banca" },
  { nume: "Strâmtura-Mitoc", simplu: "Stramtura-Mitoc", comuna: "Banca" },
  { nume: "Stroiești", simplu: "Stroiesti", comuna: "Tatarani" },
  { nume: "Stuhuleț", simplu: "Stuhulet", comuna: "Berezeni" },
  { nume: "Suceveni", comuna: "Bogdana" },
  { nume: "Șuletea", simplu: "Suletea" },
  { nume: "Suseni", comuna: "Bacani" },
  { nume: "Tăbălăești", simplu: "Tabalaesti", comuna: "Bunesti-Averesti" },
  { nume: "Tăcuta", simplu: "Tacuta" },
  { nume: "Tălpigeni", simplu: "Talpigeni", comuna: "Botesti" },
  { nume: "Tanacu" },
  { nume: "Târzii", simplu: "Tarzii", comuna: "Oltenesti" },
  { nume: "Tătărăni", simplu: "Tatarani" },
  { nume: "Tătărăni", simplu: "Tatarani", comuna: "Danesti" },
  { nume: "Tatomirești", simplu: "Tatomiresti", comuna: "Rebricea" },
  { nume: "Teișoru", simplu: "Teisoru", comuna: "Laza" },
  { nume: "Telejna", comuna: "Zapodeni" },
  { nume: "Țibăneștii Buhlii", simplu: "Tibanestii Buhlii", comuna: "Bacesti" },
  { nume: "Țifu", simplu: "Tifu", comuna: "Banca" },
  { nume: "Todireni", comuna: "Padureni" },
  { nume: "Todirești", simplu: "Todiresti" },
  { nume: "Tomești", simplu: "Tomesti", comuna: "Pogana" },
  { nume: "Tomșa", simplu: "Tomsa", comuna: "Hoceni" },
  { nume: "Toporăști", simplu: "Toporasti", comuna: "Pungesti" },
  { nume: "Trestiana", comuna: "Grivita" },
  { nume: "Trohan", comuna: "Garceni" },
  { nume: "Tufeștii de Jos", simplu: "Tufestii de Jos", comuna: "Rebricea" },
  { nume: "Tulești", simplu: "Tulesti", comuna: "Dragomiresti" },
  { nume: "Tunsești", simplu: "Tunsesti", comuna: "Bogdanita" },
  { nume: "Tupilați", simplu: "Tupilati", comuna: "Gagesti" },
  { nume: "Țuțcani", simplu: "Tutcani", comuna: "Malusteni" },
  { nume: "Tutova" },
  { nume: "Ulea", comuna: "Bogdanesti" },
  { nume: "Uncești", simplu: "Uncesti", comuna: "Zapodeni" },
  { nume: "Unțești", simplu: "Untesti", comuna: "Bogdanesti" },
  { nume: "Urdești", simplu: "Urdesti", comuna: "Viisoara" },
  { nume: "Uricari", comuna: "Voinesti" },
  { nume: "Urlați", simplu: "Urlati", comuna: "Dimitrie Cantemir" },
  { nume: "Ursoaia", comuna: "Ivanesti" },
  { nume: "Vadurile", comuna: "Iana" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Osesti" },
  { nume: "Valea Grecului", comuna: "Duda-Epureni" },
  { nume: "Valea lui Bosie", comuna: "Tatarani" },
  { nume: "Valea lui Darie", comuna: "Rosiesti" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Vinderei" },
  { nume: "Valea Lupului", comuna: "Gherghesti" },
  { nume: "Valea Mare", comuna: "Dumesti" },
  { nume: "Valea Mare", comuna: "Ivanesti" },
  { nume: "Valea Mare", comuna: "Negresti" },
  { nume: "Valea Oanei", comuna: "Ivanesti" },
  { nume: "Valea Popii", comuna: "Todiresti" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Tatarani" },
  { nume: "Valea Siliștei", simplu: "Valea Silistei", comuna: "Solesti" },
  { nume: "Valea Târgului", simplu: "Valea Targului", comuna: "Laza" },
  { nume: "Văleni", simplu: "Valeni" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Padureni" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Viisoara" },
  { nume: "Vaslui" },
  { nume: "Verdeș", simplu: "Verdes", comuna: "Bogdana" },
  { nume: "Vetrișoaia", simplu: "Vetrisoaia" },
  { nume: "Viișoara", simplu: "Viisoara" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Todiresti" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Vaslui" },
  { nume: "Viltotești", simplu: "Viltotesti", comuna: "Viisoara" },
  { nume: "Vinderei" },
  { nume: "Vinețești", simplu: "Vinetesti", comuna: "Oltenesti" },
  { nume: "Vișinari", simplu: "Visinari", comuna: "Bogdanesti" },
  { nume: "Vizureni", comuna: "Tutova" },
  { nume: "Vlădești", simplu: "Vladesti", comuna: "Bogdanesti" },
  { nume: "Vladia", comuna: "Dragomiresti" },
  { nume: "Voinești", simplu: "Voinesti" },
  { nume: "Voinești", simplu: "Voinesti", comuna: "Vulturesti" },
  { nume: "Vovriești", simplu: "Vovriesti", comuna: "Bacesti" },
  { nume: "Vulpășeni", simplu: "Vulpaseni", comuna: "Bacani" },
  { nume: "Vulturești", simplu: "Vulturesti" },
  { nume: "Vutcani" },
  { nume: "Zăpodeni", simplu: "Zapodeni" },
  { nume: "Zgura", comuna: "Oltenesti" },
  { nume: "Zizinca", comuna: "Deleni" },
  { nume: "Zorleni" },
];
