export const vs = [
  { nume: "1 Decembrie", comuna: "Banca" },
  { nume: "Albeşti", simplu: "Albesti" },
  { nume: "Albeşti", simplu: "Albesti", comuna: "Delesti" },
  { nume: "Albina", comuna: "Ivanesti" },
  { nume: "Albiţa", simplu: "Albita", comuna: "Dranceni" },
  { nume: "Alexandru Vlahuţă", simplu: "Alexandru Vlahuta" },
  { nume: "Armăşeni", simplu: "Armaseni", comuna: "Bacesti" },
  { nume: "Armăşeni", simplu: "Armaseni", comuna: "Bunesti-Averesti" },
  { nume: "Armăşoaia", simplu: "Armasoaia", comuna: "Pungesti" },
  { nume: "Arşiţa", simplu: "Arsita", comuna: "Bogdana" },
  { nume: "Arsura" },
  { nume: "Avereşti", simplu: "Averesti", comuna: "Bunesti-Averesti" },
  { nume: "Avrămeşti", simplu: "Avramesti", comuna: "Voinesti" },
  { nume: "Băbuşa", simplu: "Babusa", comuna: "Bacesti" },
  { nume: "Băbuţa", simplu: "Babuta", comuna: "Dragomiresti" },
  { nume: "Băcani", simplu: "Bacani" },
  { nume: "Băcăoani", simplu: "Bacaoani", comuna: "Muntenii De Jos" },
  { nume: "Băceşti", simplu: "Bacesti" },
  { nume: "Bădeana", simplu: "Badeana", comuna: "Tutova" },
  { nume: "Bahnari", comuna: "Vaslui" },
  { nume: "Băile Drânceni", simplu: "Baile Dranceni", comuna: "Dranceni" },
  { nume: "Băleşti", simplu: "Balesti", comuna: "Delesti" },
  { nume: "Băltăţeni", simplu: "Baltateni", comuna: "Bacani" },
  { nume: "Bălţaţi", simplu: "Baltati", comuna: "Tatarani" },
  { nume: "Bălteni-Deal", simplu: "Balteni-Deal", comuna: "Balteni" },
  { nume: "Bălteni", simplu: "Balteni" },
  { nume: "Banca" },
  { nume: "Bănceşti", simplu: "Bancesti", comuna: "Voinesti" },
  { nume: "Barboşi", simplu: "Barbosi", comuna: "Hoceni" },
  { nume: "Bârlad", simplu: "Barlad", comuna: "Birlad" },
  { nume: "Bârlăleşti", simplu: "Barlalesti", comuna: "Epureni" },
  { nume: "Bărtăluş-Mocani", simplu: "Bartalus-Mocani", comuna: "Puiesti" },
  { nume: "Bărtăluş-Răzeşi", simplu: "Bartalus-Razesi", comuna: "Puiesti" },
  { nume: "Bârzeşti", simplu: "Barzesti", comuna: "Stefan Cel Mare" },
  { nume: "Bejeneşti", simplu: "Bejenesti", comuna: "Laza" },
  { nume: "Belceşti", simplu: "Belcesti", comuna: "Ivesti" },
  { nume: "Belzeni", comuna: "Dragomiresti" },
  { nume: "Beneşti", simplu: "Benesti", comuna: "Tanacu" },
  { nume: "Bereasa", comuna: "Danesti" },
  { nume: "Berezeni" },
  { nume: "Blăgeşti", simplu: "Blagesti" },
  { nume: "Bleşca", simplu: "Blesca", comuna: "Ivanesti" },
  { nume: "Bobeşti", simplu: "Bobesti", comuna: "Duda-Epureni" },
  { nume: "Bogdana-Voloseni", comuna: "Stanilesti" },
  { nume: "Bogdana" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Falciu" },
  { nume: "Bogdăniţa", simplu: "Bogdanita" },
  { nume: "Bogeşti", simplu: "Bogesti", comuna: "Pogana" },
  { nume: "Bolaţi", simplu: "Bolati", comuna: "Rebricea" },
  { nume: "Borodeşti", simplu: "Borodesti", comuna: "Tutova" },
  { nume: "Boţeşti", simplu: "Botesti" },
  { nume: "Boţoaia", simplu: "Botoaia", comuna: "Danesti" },
  { nume: "Botoi", comuna: "Dragomiresti" },
  { nume: "Bouşori", simplu: "Bousori", comuna: "Solesti" },
  { nume: "Bozia", comuna: "Falciu" },
  { nume: "Brădeşti", simplu: "Bradesti", comuna: "Vinderei" },
  { nume: "Brăhăşoaia", simplu: "Brahasoaia", comuna: "Stefan Cel Mare" },
  { nume: "Brodoc", comuna: "Vaslui" },
  { nume: "Broscoşeşti", simplu: "Broscosesti", comuna: "Lunca Banului" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Ivanesti" },
  { nume: "Buda", comuna: "Alexandru Vlahuta" },
  { nume: "Buda", comuna: "Bogdanesti" },
  { nume: "Buda", comuna: "Osesti" },
  { nume: "Budeşti", simplu: "Budesti", comuna: "Cretesti" },
  { nume: "Budu Cantemir", comuna: "Stanilesti" },
  { nume: "Buhăieşti", simplu: "Buhaiesti", comuna: "Vulturesti" },
  { nume: "Bulboaca", comuna: "Deleni" },
  { nume: "Bumbăta", simplu: "Bumbata", comuna: "Vetrisoaia" },
  { nume: "Buneşti", simplu: "Bunesti", comuna: "Bunesti-Averesti" },
  { nume: "Bursuci", comuna: "Epureni" },
  { nume: "Buscata", comuna: "Ivanesti" },
  { nume: "Butucăria", simplu: "Butucaria", comuna: "Zapodeni" },
  { nume: "Călimăneşti", simplu: "Calimanesti", comuna: "Puiesti" },
  { nume: "Călugăreni", simplu: "Calugareni", comuna: "Stefan Cel Mare" },
  { nume: "Cănţălăreşti", simplu: "Cantalaresti", comuna: "Stefan Cel Mare" },
  { nume: "Căpoteşti", simplu: "Capotesti", comuna: "Padureni" },
  { nume: "Căpuşneni", simplu: "Capusneni", comuna: "Lipovat" },
  { nume: "Cârja", simplu: "Carja", comuna: "Murgeni" },
  { nume: "Cârjoani", simplu: "Carjoani", comuna: "Pogana" },
  { nume: "Cârţibaşi", simplu: "Cartibasi", comuna: "Bogdanita" },
  { nume: "Căzăneşti", simplu: "Cazanesti", comuna: "Negresti" },
  { nume: "Cepeşti", simplu: "Cepesti", comuna: "Bogdanita" },
  { nume: "Cetăţuia", simplu: "Cetatuia", comuna: "Puiesti" },
  { nume: "Chersăcosu", simplu: "Chersacosu", comuna: "Stanilesti" },
  { nume: "Chetreşti", simplu: "Chetresti", comuna: "Balteni" },
  { nume: "Chetrosu", comuna: "Gherghesti" },
  { nume: "Chilieni", comuna: "Coroiesti" },
  { nume: "Chirceşti", simplu: "Chircesti", comuna: "Miclesti" },
  { nume: "Chiţcani", simplu: "Chitcani", comuna: "Costesti" },
  { nume: "Chiţoc", simplu: "Chitoc", comuna: "Lipovat" },
  { nume: "Cioatele", comuna: "Negresti" },
  { nume: "Ciocani", comuna: "Perieni" },
  { nume: "Ciofeni", comuna: "Zapodeni" },
  { nume: "Ciortolom", comuna: "Tutova" },
  { nume: "Ciuperca", comuna: "Dragomiresti" },
  { nume: "Codăeşti", simplu: "Codaesti" },
  { nume: "Codreni", comuna: "Rosiesti" },
  { nume: "Condrea", comuna: "Lunca Banului" },
  { nume: "Copăceana", simplu: "Copaceana", comuna: "Falciu" },
  { nume: "Corbu", comuna: "Lipovat" },
  { nume: "Corni-Albeşti", simplu: "Corni-Albesti", comuna: "Albesti" },
  { nume: "Corobăneşti", simplu: "Corobanesti", comuna: "Voinesti" },
  { nume: "Corodeşti", simplu: "Corodesti", comuna: "Gherghesti" },
  { nume: "Coroieşti", simplu: "Coroiesti" },
  { nume: "Coroieşti", simplu: "Coroiesti", comuna: "Bogdanita" },
  {
    nume: "Coroieştii de Sus",
    simplu: "Coroiestii de Sus",
    comuna: "Coroiesti",
  },
  { nume: "Coroiu", comuna: "Tutova" },
  { nume: "Coşca", simplu: "Cosca", comuna: "Ivanesti" },
  { nume: "Coşeşti", simplu: "Cosesti", comuna: "Ivanesti" },
  { nume: "Costeşti", simplu: "Costesti" },
  { nume: "Cotic", comuna: "Todiresti" },
  { nume: "Cozmeşti", simplu: "Cozmesti", comuna: "Delesti" },
  { nume: "Crăciuneşti", simplu: "Craciunesti", comuna: "Rebricea" },
  { nume: "Crâng", simplu: "Crang", comuna: "Perieni" },
  { nume: "Crângu Nou", simplu: "Crangu Nou", comuna: "Perieni" },
  { nume: "Crasna", comuna: "Albesti" },
  { nume: "Crăsnăşeni", simplu: "Crasnaseni", comuna: "Tatarani" },
  { nume: "Creţeşti", simplu: "Cretesti" },
  { nume: "Creţeştii de Sus", simplu: "Cretestii de Sus", comuna: "Cretesti" },
  { nume: "Cristeşti", simplu: "Cristesti", comuna: "Puiesti" },
  { nume: "Criveşti", simplu: "Crivesti", comuna: "Tutova" },
  { nume: "Cujba", comuna: "Tacuta" },
  { nume: "Curseşti-Deal", simplu: "Cursesti-Deal", comuna: "Pungesti" },
  { nume: "Curseşti-Vale", simplu: "Cursesti-Vale", comuna: "Pungesti" },
  { nume: "Curteni", comuna: "Oltenesti" },
  { nume: "Dăneşti", simplu: "Danesti" },
  { nume: "Davideşti", simplu: "Davidesti", comuna: "Padureni" },
  { nume: "Dealu Mare", comuna: "Zorleni" },
  { nume: "Dealu Secării", simplu: "Dealu Secarii", comuna: "Poienesti" },
  { nume: "Delea", comuna: "Zapodeni" },
  { nume: "Deleni" },
  { nume: "Deleni", comuna: "Hoceni" },
  { nume: "Deleşti", simplu: "Delesti" },
  { nume: "Dinga", comuna: "Costesti" },
  { nume: "Doagele", comuna: "Dragomiresti" },
  { nume: "Dobrosloveşti", simplu: "Dobroslovesti", comuna: "Zapodeni" },
  { nume: "Docăneasa", simplu: "Docaneasa", comuna: "Vinderei" },
  { nume: "Docani", comuna: "Vinderei" },
  { nume: "Dodeşti", simplu: "Dodesti", comuna: "Viisoara" },
  { nume: "Drăgeşti", simplu: "Dragesti", comuna: "Todiresti" },
  { nume: "Dragomăneşti", simplu: "Dragomanesti", comuna: "Gherghesti" },
  { nume: "Dragomireşti", simplu: "Dragomiresti" },
  { nume: "Drânceni", simplu: "Dranceni" },
  { nume: "Draxeni", comuna: "Rebricea" },
  { nume: "Drăxeni", simplu: "Draxeni", comuna: "Gherghesti" },
  { nume: "Drujeşti", simplu: "Drujesti", comuna: "Bacani" },
  { nume: "Duda", comuna: "Duda-Epureni" },
  { nume: "Dumasca", comuna: "Tacuta" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni", comuna: "Garceni" },
  { nume: "Dumeşti", simplu: "Dumesti" },
  { nume: "Dumeştii Vechi", simplu: "Dumestii Vechi", comuna: "Dumesti" },
  { nume: "Emil Racoviţă", simplu: "Emil Racovita", comuna: "Danesti" },
  { nume: "Epureni" },
  { nume: "Epureni", comuna: "Duda-Epureni" },
  { nume: "Fălciu", simplu: "Falciu" },
  {
    nume: "Fântâna Blănarului",
    simplu: "Fantana Blanarului",
    comuna: "Bogdana",
  },
  { nume: "Fântânele", simplu: "Fantanele", comuna: "Puiesti" },
  { nume: "Fâstâci", simplu: "Fastaci", comuna: "Delesti" },
  { nume: "Fedeşti", simplu: "Fedesti", comuna: "Suletea" },
  { nume: "Fereşti", simplu: "Feresti", comuna: "Valeni" },
  { nume: "Floreni", comuna: "Murgeni" },
  { nume: "Floreşti", simplu: "Floresti", comuna: "Poienesti" },
  { nume: "Focşa", simplu: "Focsa", comuna: "Lunca Banului" },
  { nume: "Focşeaşca", simplu: "Focseasca", comuna: "Tacuta" },
  { nume: "Frasinu", comuna: "Poienesti" },
  { nume: "Fruntişeni", simplu: "Fruntiseni", comuna: "Grivita" },
  { nume: "Fulgu", comuna: "Puiesti" },
  { nume: "Fundătura Mare", simplu: "Fundatura Mare", comuna: "Ivanesti" },
  { nume: "Fundătura Mică", simplu: "Fundatura Mica", comuna: "Ivanesti" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Arsura" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Delesti" },
  { nume: "Fundu Văii", simplu: "Fundu Vaii", comuna: "Lipovat" },
  { nume: "Fundu Văii", simplu: "Fundu Vaii", comuna: "Poienesti" },
  { nume: "Găgeşti", simplu: "Gagesti" },
  { nume: "Gâlţeşti", simplu: "Galtesti", comuna: "Puiesti" },
  { nume: "Găneşti", simplu: "Ganesti", comuna: "Botesti" },
  { nume: "Gara Banca", comuna: "Banca" },
  { nume: "Gara Docăneasa", simplu: "Gara Docaneasa", comuna: "Vinderei" },
  { nume: "Gara Roşieşti", simplu: "Gara Rosiesti", comuna: "Rosiesti" },
  { nume: "Gara Tălăşman", simplu: "Gara Talasman", comuna: "Vinderei" },
  { nume: "Gârceni", simplu: "Garceni" },
  { nume: "Gârdeşti", simplu: "Gardesti", comuna: "Voinesti" },
  { nume: "Găvanu", simplu: "Gavanu", comuna: "Bogdana" },
  { nume: "Ghergheleu", comuna: "Codaesti" },
  { nume: "Ghergheşti", simplu: "Gherghesti" },
  { nume: "Ghermăneşti", simplu: "Ghermanesti", comuna: "Banca" },
  { nume: "Ghermăneşti", simplu: "Ghermanesti", comuna: "Dranceni" },
  { nume: "Ghicani", comuna: "Alexandru Vlahuta" },
  { nume: "Ghireasca", comuna: "Malusteni" },
  { nume: "Giurcani", comuna: "Gagesti" },
  { nume: "Giurgeşti", simplu: "Giurgesti", comuna: "Tatarani" },
  { nume: "Glodeni", comuna: "Negresti" },
  { nume: "Grăjdeni", simplu: "Grajdeni", comuna: "Grivita" },
  { nume: "Griviţa", simplu: "Grivita" },
  { nume: "Grumezoaia", comuna: "Dimitrie Cantemir" },
  { nume: "Gugeşti", simplu: "Gugesti", comuna: "Botesti" },
  { nume: "Gura Albeşti", simplu: "Gura Albesti", comuna: "Albesti" },
  { nume: "Gura Idrici", comuna: "Rosiesti" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Stanilesti" },
  { nume: "Guşiţei", simplu: "Gusitei", comuna: "Dimitrie Cantemir" },
  { nume: "Hălăreşti", simplu: "Halaresti", comuna: "Iana" },
  { nume: "Halta Dodeşti", simplu: "Halta Dodesti", comuna: "Viisoara" },
  { nume: "Hârsova", simplu: "Harsova", comuna: "Delesti" },
  { nume: "Hârşoveni", simplu: "Harsoveni", comuna: "Ivanesti" },
  { nume: "Hoceni" },
  { nume: "Hordila", comuna: "Pungesti" },
  { nume: "Hordileşti", simplu: "Hordilesti", comuna: "Delesti" },
  { nume: "Horga", comuna: "Epureni" },
  { nume: "Horoiata", comuna: "Bogdanesti" },
  { nume: "Hreasca", comuna: "Coroiesti" },
  { nume: "Huc", comuna: "Todiresti" },
  { nume: "Hupca", comuna: "Bogdanesti" },
  { nume: "Hurdugi", comuna: "Dimitrie Cantemir" },
  { nume: "Huşi", simplu: "Husi" },
  { nume: "Iana" },
  { nume: "Iaz", comuna: "Solesti" },
  { nume: "Ibăneşti", simplu: "Ibanesti" },
  { nume: "Idrici", comuna: "Rosiesti" },
  { nume: "Iezer", comuna: "Puiesti" },
  { nume: "Iezerel", comuna: "Ivanesti" },
  { nume: "Igeşti", simplu: "Igesti", comuna: "Blagesti" },
  { nume: "Ivăneşti", simplu: "Ivanesti" },
  { nume: "Ivăneşti", simplu: "Ivanesti", comuna: "Padureni" },
  { nume: "Iveşti", simplu: "Ivesti" },
  { nume: "Jigălia", simplu: "Jigalia", comuna: "Suletea" },
  { nume: "Lacu Babei", comuna: "Bogdana" },
  { nume: "Lăleşti", simplu: "Lalesti", comuna: "Puiesti" },
  { nume: "Lăţeşti", simplu: "Latesti", comuna: "Murgeni" },
  { nume: "Laza" },
  { nume: "Lazu", comuna: "Gherghesti" },
  { nume: "Leoşti", simplu: "Leosti", comuna: "Padureni" },
  { nume: "Leoşti", simplu: "Leosti", comuna: "Tatarani" },
  { nume: "Lipovăţ", simplu: "Lipovat" },
  { nume: "Lunca Banului" },
  { nume: "Lunca Veche", comuna: "Lunca Banului" },
  { nume: "Lunca", comuna: "Gherghesti" },
  { nume: "Lupeşti", simplu: "Lupesti", comuna: "Malusteni" },
  { nume: "Măcreşti", simplu: "Macresti", comuna: "Rebricea" },
  { nume: "Măcreşti", simplu: "Macresti", comuna: "Zapodeni" },
  { nume: "Mălăieşti", simplu: "Malaiesti", comuna: "Vutcani" },
  { nume: "Măluşteni", simplu: "Malusteni" },
  { nume: "Mânăstirea", simplu: "Manastirea", comuna: "Delesti" },
  { nume: "Mânăstirea", simplu: "Manastirea", comuna: "Malusteni" },
  { nume: "Mânjeşti", simplu: "Manjesti", comuna: "Muntenii De Jos" },
  { nume: "Mantu", comuna: "Tatarani" },
  { nume: "Mânzăteşti", simplu: "Manzatesti", comuna: "Malusteni" },
  { nume: "Mânzaţi", simplu: "Manzati", comuna: "Ibanesti" },
  { nume: "Mărăşeni", simplu: "Maraseni", comuna: "Stefan Cel Mare" },
  { nume: "Mărăşeşti", simplu: "Marasesti", comuna: "Voinesti" },
  { nume: "Măscurei", simplu: "Mascurei", comuna: "Pogana" },
  { nume: "Micleşti", simplu: "Miclesti" },
  { nume: "Micleşti", simplu: "Miclesti", comuna: "Banca" },
  {
    nume: "Mihail Kogălniceanu",
    simplu: "Mihail Kogalniceanu",
    comuna: "Arsura",
  },
  { nume: "Mirceşti", simplu: "Mircesti", comuna: "Tacuta" },
  { nume: "Mireni", comuna: "Coroiesti" },
  { nume: "Mitoc", comuna: "Banca" },
  { nume: "Moara Domnească", simplu: "Moara Domneasca", comuna: "Valeni" },
  { nume: "Moara Grecilor", comuna: "Vaslui" },
  { nume: "Morăreni", simplu: "Morareni", comuna: "Alexandru Vlahuta" },
  { nume: "Moreni", comuna: "Deleni" },
  { nume: "Movileni", comuna: "Coroiesti" },
  { nume: "Munteneşti", simplu: "Muntenesti", comuna: "Stefan Cel Mare" },
  { nume: "Muntenii de Jos" },
  { nume: "Muntenii de Sus", comuna: "Tanacu" },
  { nume: "Murgeni" },
  { nume: "Muşata", simplu: "Musata", comuna: "Berezeni" },
  { nume: "Negreşti", simplu: "Negresti" },
  { nume: "Obârşeni", simplu: "Obarseni", comuna: "Vinderei" },
  { nume: "Obârşeni", simplu: "Obarseni", comuna: "Voinesti" },
  {
    nume: "Obârşenii Lingurari",
    simplu: "Obarsenii Lingurari",
    comuna: "Voinesti",
  },
  { nume: "Odaia Bogdana", comuna: "Falciu" },
  { nume: "Odaia Bursucani", comuna: "Grivita" },
  { nume: "Olteneşti", simplu: "Oltenesti" },
  { nume: "Oprişiţa", simplu: "Oprisita", comuna: "Poienesti" },
  { nume: "Orgoieşti", simplu: "Orgoiesti", comuna: "Bogdanesti" },
  { nume: "Oşeşti", simplu: "Osesti" },
  { nume: "Oţeleni", simplu: "Oteleni", comuna: "Hoceni" },
  { nume: "Oţetoaia", simplu: "Otetoaia", comuna: "Lunca Banului" },
  { nume: "Păcurăreşti", simplu: "Pacuraresti", comuna: "Coroiesti" },
  { nume: "Pădureni", simplu: "Padureni" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Osesti" },
  { nume: "Pâhna", simplu: "Pahna", comuna: "Oltenesti" },
  { nume: "Pâhneşti", simplu: "Pahnesti", comuna: "Arsura" },
  { nume: "Păltiniş", simplu: "Paltinis", comuna: "Bacesti" },
  { nume: "Parpaniţa", simplu: "Parpanita", comuna: "Negresti" },
  { nume: "Pârveşti", simplu: "Parvesti", comuna: "Costesti" },
  { nume: "Peicani", comuna: "Gagesti" },
  { nume: "Perieni" },
  { nume: "Plopeni", comuna: "Bogdana" },
  { nume: "Plopi", comuna: "Bunesti-Averesti" },
  { nume: "Plopoasa", comuna: "Todiresti" },
  { nume: "Plotoneşti", simplu: "Plotonesti", comuna: "Dimitrie Cantemir" },
  { nume: "Pochidia", comuna: "Tutova" },
  { nume: "Podeni", comuna: "Vulturesti" },
  { nume: "Podu Oprii", comuna: "Bunesti-Averesti" },
  { nume: "Podu Petriş", simplu: "Podu Petris", comuna: "Perieni" },
  { nume: "Pogana" },
  { nume: "Pogăneşti", simplu: "Poganesti", comuna: "Stanilesti" },
  { nume: "Pogoneşti", simplu: "Pogonesti", comuna: "Ivesti" },
  { nume: "Poiana lui Alexa", comuna: "Laza" },
  { nume: "Poiana Pietrei", comuna: "Dragomiresti" },
  { nume: "Poiana", comuna: "Negresti" },
  { nume: "Poieneşti-Deal", simplu: "Poienesti-Deal", comuna: "Poienesti" },
  { nume: "Poieneşti", simplu: "Poienesti" },
  { nume: "Polocin", comuna: "Ivesti" },
  { nume: "Popeni", comuna: "Gagesti" },
  { nume: "Popeni", comuna: "Zorleni" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Dragomiresti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Miclesti" },
  { nume: "Portari", comuna: "Zapodeni" },
  { nume: "Poşta Elan", simplu: "Posta Elan", comuna: "Vutcani" },
  { nume: "Pribeşti", simplu: "Pribesti", comuna: "Codaesti" },
  { nume: "Protopopeşti", simplu: "Protopopesti", comuna: "Tacuta" },
  { nume: "Puieşti", simplu: "Puiesti" },
  { nume: "Pungeşti", simplu: "Pungesti" },
  { nume: "Puntişeni", simplu: "Puntiseni", comuna: "Costesti" },
  { nume: "Puşcaşi", simplu: "Puscasi", comuna: "Laza" },
  { nume: "Puţu Olarului", simplu: "Putu Olarului", comuna: "Ibanesti" },
  { nume: "Racova", comuna: "Garceni" },
  { nume: "Racoviţa", simplu: "Racovita", comuna: "Garceni" },
  { nume: "Rădăeşti", simplu: "Radaesti", comuna: "Bogdanita" },
  { nume: "Rădeni", simplu: "Radeni", comuna: "Dragomiresti" },
  { nume: "Rădeşti", simplu: "Radesti", comuna: "Costesti" },
  { nume: "Răducani", simplu: "Raducani", comuna: "Lunca Banului" },
  { nume: "Răduieşti", simplu: "Raduiesti", comuna: "Delesti" },
  { nume: "Rafaila", comuna: "Todiresti" },
  { nume: "Raiu", comuna: "Murgeni" },
  { nume: "Rânceni", simplu: "Ranceni", comuna: "Berezeni" },
  { nume: "Rânzeşti", simplu: "Ranzesti", comuna: "Falciu" },
  { nume: "Rapşa", simplu: "Rapsa", comuna: "Pungesti" },
  { nume: "Răşcani", simplu: "Rascani", comuna: "Danesti" },
  { nume: "Răşcani", simplu: "Rascani", comuna: "Suletea" },
  { nume: "Râşeşti", simplu: "Rasesti", comuna: "Dranceni" },
  { nume: "Râşniţa", simplu: "Rasnita", comuna: "Laza" },
  { nume: "Rateşu Cuzei", simplu: "Ratesu Cuzei", comuna: "Rebricea" },
  { nume: "Rebricea" },
  { nume: "Recea", comuna: "Iana" },
  { nume: "Rediu Galian", comuna: "Codaesti" },
  { nume: "Rediu", comuna: "Hoceni" },
  { nume: "Rediu", comuna: "Rosiesti" },
  { nume: "Rediu", comuna: "Vaslui" },
  { nume: "Roşieşti", simplu: "Rosiesti" },
  { nume: "Roşiori", simplu: "Rosiori", comuna: "Bunesti-Averesti" },
  { nume: "Rotari", comuna: "Puiesti" },
  { nume: "Rugăria", simplu: "Rugaria", comuna: "Voinesti" },
  { nume: "Rusca", comuna: "Padureni" },
  { nume: "Ruşi", simplu: "Rusi", comuna: "Puiesti" },
  { nume: "Sălceni", simplu: "Salceni", comuna: "Tutova" },
  { nume: "Sălcioara", simplu: "Salcioara", comuna: "Banca" },
  { nume: "Sărăţeni", simplu: "Sarateni", comuna: "Murgeni" },
  { nume: "Săratu", simplu: "Saratu", comuna: "Stanilesti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Banca" },
  { nume: "Sasova", comuna: "Rebricea" },
  { nume: "Satu Nou", comuna: "Banca" },
  { nume: "Satu Nou", comuna: "Berezeni" },
  { nume: "Satu Nou", comuna: "Cretesti" },
  { nume: "Satu Nou", comuna: "Solesti" },
  { nume: "Satu Nou", comuna: "Tanacu" },
  { nume: "Satu Nou", comuna: "Tutova" },
  { nume: "Sauca", comuna: "Laza" },
  { nume: "Schineni", comuna: "Murgeni" },
  { nume: "Schinetea", comuna: "Dumesti" },
  { nume: "Schitu", comuna: "Bogdanita" },
  { nume: "Secuia", comuna: "Muntenii De Jos" },
  { nume: "Semenea", comuna: "Dragomiresti" },
  { nume: "Şerboteşti", simplu: "Serbotesti", comuna: "Solesti" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Iana" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Pungesti" },
  { nume: "Siliştea", simplu: "Silistea", comuna: "Todiresti" },
  { nume: "Simila", comuna: "Zorleni" },
  { nume: "Similişoara", simplu: "Similisoara", comuna: "Bogdana" },
  { nume: "Sipeni", comuna: "Blagesti" },
  { nume: "Şişcani", simplu: "Siscani", comuna: "Hoceni" },
  { nume: "Slobozia", comuna: "Garceni" },
  { nume: "Soci", comuna: "Gherghesti" },
  { nume: "Sofieni", comuna: "Tacuta" },
  { nume: "Sofroneşti", simplu: "Sofronesti", comuna: "Todiresti" },
  { nume: "Soleşti", simplu: "Solesti" },
  { nume: "Şopârleni", simplu: "Soparleni", comuna: "Dranceni" },
  { nume: "Stâncăşeni", simplu: "Stancaseni", comuna: "Voinesti" },
  { nume: "Stănileşti", simplu: "Stanilesti" },
  { nume: "Ştefan cel Mare", simplu: "Stefan cel Mare" },
  { nume: "Stejaru", comuna: "Pungesti" },
  { nume: "Ştioborăni", simplu: "Stioborani", comuna: "Solesti" },
  { nume: "Stoişeşti", simplu: "Stoisesti", comuna: "Banca" },
  { nume: "Strâmtura-Mitoc", simplu: "Stramtura-Mitoc", comuna: "Banca" },
  { nume: "Stroieşti", simplu: "Stroiesti", comuna: "Tatarani" },
  { nume: "Stuhuleţ", simplu: "Stuhulet", comuna: "Berezeni" },
  { nume: "Suceveni", comuna: "Bogdana" },
  { nume: "Şuletea", simplu: "Suletea" },
  { nume: "Suseni", comuna: "Bacani" },
  { nume: "Tăbălăeşti", simplu: "Tabalaesti", comuna: "Bunesti-Averesti" },
  { nume: "Tăcuta", simplu: "Tacuta" },
  { nume: "Tălpigeni", simplu: "Talpigeni", comuna: "Botesti" },
  { nume: "Tanacu" },
  { nume: "Târzii", simplu: "Tarzii", comuna: "Oltenesti" },
  { nume: "Tătărăni", simplu: "Tatarani" },
  { nume: "Tătărăni", simplu: "Tatarani", comuna: "Danesti" },
  { nume: "Tatomireşti", simplu: "Tatomiresti", comuna: "Rebricea" },
  { nume: "Teişoru", simplu: "Teisoru", comuna: "Laza" },
  { nume: "Telejna", comuna: "Zapodeni" },
  { nume: "Ţibăneştii Buhlii", simplu: "Tibanestii Buhlii", comuna: "Bacesti" },
  { nume: "Ţifu", simplu: "Tifu", comuna: "Banca" },
  { nume: "Todireni", comuna: "Padureni" },
  { nume: "Todireşti", simplu: "Todiresti" },
  { nume: "Tomeşti", simplu: "Tomesti", comuna: "Pogana" },
  { nume: "Tomşa", simplu: "Tomsa", comuna: "Hoceni" },
  { nume: "Toporăşti", simplu: "Toporasti", comuna: "Pungesti" },
  { nume: "Trestiana", comuna: "Grivita" },
  { nume: "Trohan", comuna: "Garceni" },
  { nume: "Tufeştii de Jos", simplu: "Tufestii de Jos", comuna: "Rebricea" },
  { nume: "Tuleşti", simplu: "Tulesti", comuna: "Dragomiresti" },
  { nume: "Tunseşti", simplu: "Tunsesti", comuna: "Bogdanita" },
  { nume: "Tupilaţi", simplu: "Tupilati", comuna: "Gagesti" },
  { nume: "Ţuţcani", simplu: "Tutcani", comuna: "Malusteni" },
  { nume: "Tutova" },
  { nume: "Ulea", comuna: "Bogdanesti" },
  { nume: "Unceşti", simplu: "Uncesti", comuna: "Zapodeni" },
  { nume: "Unţeşti", simplu: "Untesti", comuna: "Bogdanesti" },
  { nume: "Urdeşti", simplu: "Urdesti", comuna: "Viisoara" },
  { nume: "Uricari", comuna: "Voinesti" },
  { nume: "Urlaţi", simplu: "Urlati", comuna: "Dimitrie Cantemir" },
  { nume: "Ursoaia", comuna: "Ivanesti" },
  { nume: "Vadurile", comuna: "Iana" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Osesti" },
  { nume: "Valea Grecului", comuna: "Duda-Epureni" },
  { nume: "Valea lui Bosie", comuna: "Tatarani" },
  { nume: "Valea lui Darie", comuna: "Rosiesti" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Vinderei" },
  { nume: "Valea Lupului", comuna: "Gherghesti" },
  { nume: "Valea Mare", comuna: "Dumesti" },
  { nume: "Valea Mare", comuna: "Ivanesti" },
  { nume: "Valea Mare", comuna: "Negresti" },
  { nume: "Valea Oanei", comuna: "Ivanesti" },
  { nume: "Valea Popii", comuna: "Todiresti" },
  { nume: "Valea Seacă", simplu: "Valea Seaca", comuna: "Tatarani" },
  { nume: "Valea Siliştei", simplu: "Valea Silistei", comuna: "Solesti" },
  { nume: "Valea Târgului", simplu: "Valea Targului", comuna: "Laza" },
  { nume: "Văleni", simplu: "Valeni" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Padureni" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Viisoara" },
  { nume: "Vaslui" },
  { nume: "Verdeş", simplu: "Verdes", comuna: "Bogdana" },
  { nume: "Vetrişoaia", simplu: "Vetrisoaia" },
  { nume: "Viişoara", simplu: "Viisoara" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Todiresti" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Vaslui" },
  { nume: "Viltoteşti", simplu: "Viltotesti", comuna: "Viisoara" },
  { nume: "Vinderei" },
  { nume: "Vineţeşti", simplu: "Vinetesti", comuna: "Oltenesti" },
  { nume: "Vişinari", simplu: "Visinari", comuna: "Bogdanesti" },
  { nume: "Vizureni", comuna: "Tutova" },
  { nume: "Vlădeşti", simplu: "Vladesti", comuna: "Bogdanesti" },
  { nume: "Vladia", comuna: "Dragomiresti" },
  { nume: "Voineşti", simplu: "Voinesti" },
  { nume: "Voineşti", simplu: "Voinesti", comuna: "Vulturesti" },
  { nume: "Vovrieşti", simplu: "Vovriesti", comuna: "Bacesti" },
  { nume: "Vulpăşeni", simplu: "Vulpaseni", comuna: "Bacani" },
  { nume: "Vultureşti", simplu: "Vulturesti" },
  { nume: "Vutcani" },
  { nume: "Zăpodeni", simplu: "Zapodeni" },
  { nume: "Zgura", comuna: "Oltenesti" },
  { nume: "Zizinca", comuna: "Deleni" },
  { nume: "Zorleni" },
];
