export const vl = [
  { nume: "Afânata", simplu: "Afanata", comuna: "Fartatesti" },
  { nume: "Aldeşti", simplu: "Aldesti", comuna: "Golesti" },
  { nume: "Alunu" },
  { nume: "Amărăşti", simplu: "Amarasti" },
  { nume: "Andreieşti", simplu: "Andreiesti", comuna: "Muereasca" },
  { nume: "Aninoasa", comuna: "Glavile" },
  { nume: "Aranghel", comuna: "Ramnicu Valcea" },
  { nume: "Aricioaia", comuna: "Sirineasa" },
  { nume: "Armăşeşti", simplu: "Armasesti", comuna: "Cernisoara" },
  { nume: "Arsanca", comuna: "Mihaesti" },
  { nume: "Aureşti", simplu: "Auresti", comuna: "Orlesti" },
  { nume: "Avrămeşti", simplu: "Avramesti", comuna: "Scundu" },
  { nume: "Băbeni-Olteţu", simplu: "Babeni-Oltetu", comuna: "Fauresti" },
  { nume: "Băbeni", simplu: "Babeni" },
  { nume: "Băbueşti", simplu: "Babuesti", comuna: "Daesti" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Danicei" },
  { nume: "Băiaşa", simplu: "Baiasa", comuna: "Roesti" },
  { nume: "Băiaşu", simplu: "Baiasu", comuna: "Perisani" },
  { nume: "Băjenari", simplu: "Bajenari", comuna: "Roesti" },
  { nume: "Balaciu", comuna: "Rosiile" },
  { nume: "Bălceşti", simplu: "Balcesti" },
  { nume: "Balomireasa", comuna: "Stoilesti" },
  { nume: "Balota", comuna: "Racovita" },
  { nume: "Bălşoara", simplu: "Balsoara", comuna: "Madulari" },
  { nume: "Băltăţeni", simplu: "Baltateni", comuna: "Tomsani" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Copaceni" },
  { nume: "Băluţoaia", simplu: "Balutoaia", comuna: "Francesti" },
  { nume: "Băneşti", simplu: "Banesti", comuna: "Nicolae Balcescu" },
  { nume: "Bănţeşti", simplu: "Bantesti", comuna: "Madulari" },
  { nume: "Bărbărigeni", simplu: "Barbarigeni", comuna: "Roesti" },
  { nume: "Bărbăteşti", simplu: "Barbatesti" },
  { nume: "Bărbuceni", simplu: "Barbuceni", comuna: "Prundeni" },
  { nume: "Barcanele", comuna: "Pausesti" },
  { nume: "Bărcăneşti", simplu: "Barcanesti", comuna: "Stanesti" },
  { nume: "Bârlogu", simplu: "Barlogu", comuna: "Stoenesti" },
  { nume: "Băroiu", simplu: "Baroiu", comuna: "Tetoiu" },
  { nume: "Bârseşti", simplu: "Barsesti", comuna: "Budesti" },
  { nume: "Bârseşti", simplu: "Barsesti", comuna: "Mihaesti" },
  { nume: "Bârsoiu", simplu: "Barsoiu", comuna: "Stoilesti" },
  { nume: "Barza", comuna: "Budesti" },
  { nume: "Bârzeşti", simplu: "Barzesti", comuna: "Barbatesti" },
  { nume: "Bătăşani", simplu: "Batasani", comuna: "Valea Mare" },
  { nume: "Becşani", simplu: "Becsani", comuna: "Fartatesti" },
  { nume: "Beneşti", simplu: "Benesti", comuna: "Balcesti" },
  { nume: "Berbeşti", simplu: "Berbesti" },
  { nume: "Berbeşti", simplu: "Berbesti", comuna: "Lalosu" },
  { nume: "Bercioiu", comuna: "Budesti" },
  { nume: "Bereşti", simplu: "Beresti", comuna: "Lapusata" },
  { nume: "Berislăveşti", simplu: "Berislavesti" },
  { nume: "Bistriţa", simplu: "Bistrita", comuna: "Costesti" },
  { nume: "Blănoiu", simplu: "Blanoiu", comuna: "Racovita" },
  { nume: "Blejani", comuna: "Scundu" },
  { nume: "Blidari", comuna: "Golesti" },
  { nume: "Bocşa", simplu: "Bocsa", comuna: "Maciuca" },
  { nume: "Bodeşti", simplu: "Bodesti", comuna: "Alunu" },
  { nume: "Bodeşti", simplu: "Bodesti", comuna: "Barbatesti" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Bujoreni" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Otesani" },
  { nume: "Bogdăneşti", simplu: "Bogdanesti", comuna: "Tomsani" },
  { nume: "Boişoara", simplu: "Boisoara" },
  { nume: "Bonciu", comuna: "Babeni" },
  { nume: "Bondoci", comuna: "Copaceni" },
  { nume: "Boroşeşti", simplu: "Borosesti", comuna: "Sutesti" },
  { nume: "Botorani", comuna: "Maciuca" },
  { nume: "Brădişor", simplu: "Bradisor", comuna: "Berislavesti" },
  { nume: "Bradu-Clocotici", comuna: "Racovita" },
  { nume: "Bratia din Deal", comuna: "Galicea" },
  { nume: "Bratia din Vale", comuna: "Galicea" },
  { nume: "Bratoveşti", simplu: "Bratovesti", comuna: "Titesti" },
  { nume: "Brezoi" },
  { nume: "Broşteni", simplu: "Brosteni", comuna: "Lapusata" },
  { nume: "Buciumeni", comuna: "Dragoesti" },
  { nume: "Bucşani", simplu: "Bucsani", comuna: "Ionesti" },
  { nume: "Buda", comuna: "Ocnele Mari" },
  { nume: "Budele", comuna: "Tetoiu" },
  { nume: "Budeşti", simplu: "Budesti" },
  { nume: "Budeşti", simplu: "Budesti", comuna: "Fauresti" },
  { nume: "Budurăşti", simplu: "Budurasti", comuna: "Stoenesti" },
  { nume: "Bujoreni" },
  { nume: "Bulagei", comuna: "Stoilesti" },
  { nume: "Buleta", comuna: "Mihaesti" },
  { nume: "Bumbueşti", simplu: "Bumbuesti", comuna: "Boisoara" },
  { nume: "Buneşti", simplu: "Bunesti" },
  { nume: "Bungeţani", simplu: "Bungetani", comuna: "Fauresti" },
  { nume: "Burdăleşti", simplu: "Burdalesti", comuna: "Gusoeni" },
  { nume: "Butanu", comuna: "Zatreni" },
  { nume: "Buzdugan", comuna: "Pausesti" },
  { nume: "Căciulata", simplu: "Caciulata", comuna: "Calimanesti" },
  { nume: "Câinenii Mari", simplu: "Cainenii Mari", comuna: "Caineni" },
  { nume: "Câinenii Mici", simplu: "Cainenii Mici", comuna: "Caineni" },
  { nume: "Căligi", simplu: "Caligi", comuna: "Runcu" },
  { nume: "Călimăneşti", simplu: "Calimanesti" },
  { nume: "Călina", simplu: "Calina", comuna: "Prundeni" },
  { nume: "Călineşti", simplu: "Calinesti", comuna: "Brezoi" },
  { nume: "Capu Dealului", comuna: "Babeni" },
  { nume: "Cărcădieşti", simplu: "Carcadiesti", comuna: "Lungesti" },
  { nume: "Cârlogani", simplu: "Carlogani", comuna: "Balcesti" },
  { nume: "Cârstăneşti", simplu: "Carstanesti", comuna: "Otesani" },
  { nume: "Casa Veche", comuna: "Olanu" },
  { nume: "Căţetu", simplu: "Catetu", comuna: "Fartatesti" },
  { nume: "Căzăneşti", simplu: "Cazanesti", comuna: "Ghioroiu" },
  { nume: "Căzăneşti", simplu: "Cazanesti", comuna: "Milcoiu" },
  { nume: "Căzăneşti", simplu: "Cazanesti", comuna: "Ramnicu Valcea" },
  { nume: "Ceretu", comuna: "Danicei" },
  { nume: "Cermegeşti", simplu: "Cermegesti", comuna: "Ladesti" },
  { nume: "Cermegeşti", simplu: "Cermegesti", comuna: "Pesceana" },
  { nume: "Cerna", comuna: "Vaideeni" },
  { nume: "Cernelele", comuna: "Pausesti" },
  { nume: "Cernişoara", simplu: "Cernisoara" },
  { nume: "Cetăţeaua", simplu: "Cetateaua", comuna: "Sutesti" },
  { nume: "Cheia", comuna: "Baile Olanesti" },
  { nume: "Cherăşti", simplu: "Cherasti", comuna: "Rosiile" },
  { nume: "Chiceni", comuna: "Tomsani" },
  { nume: "Chirculeşti", simplu: "Chirculesti", comuna: "Balcesti" },
  { nume: "Chiriceşti", simplu: "Chiricesti", comuna: "Ladesti" },
  { nume: "Cioboţi", simplu: "Cioboti", comuna: "Olanu" },
  { nume: "Ciocâltei", simplu: "Ciocaltei", comuna: "Roesti" },
  { nume: "Ciocănari", simplu: "Ciocanari", comuna: "Maciuca" },
  { nume: "Cioponeşti", simplu: "Cioponesti", comuna: "Stanesti" },
  { nume: "Ciorăşti", simplu: "Ciorasti", comuna: "Sirineasa" },
  { nume: "Ciorteşti", simplu: "Ciortesti", comuna: "Zatreni" },
  { nume: "Cireşu", simplu: "Ciresu", comuna: "Stroesti" },
  { nume: "Cireşul", simplu: "Ciresul", comuna: "Danicei" },
  { nume: "Ciucheţi", simplu: "Ciucheti", comuna: "Sinesti" },
  { nume: "Ciumagi", comuna: "Ladesti" },
  { nume: "Ciungetu", comuna: "Malaia" },
  { nume: "Ciuteşti", simplu: "Ciutesti", comuna: "Milcoiu" },
  { nume: "Coasta Cerbului", comuna: "Slatioara" },
  { nume: "Coasta Mare", comuna: "Bunesti" },
  { nume: "Coasta", comuna: "Golesti" },
  { nume: "Coasta", comuna: "Pausesti-Maglasi" },
  { nume: "Cocoru", comuna: "Galicea" },
  { nume: "Colelia", comuna: "Fauresti" },
  { nume: "Colteşti", simplu: "Coltesti", comuna: "Alunu" },
  { nume: "Comanca", comuna: "Baile Olanesti" },
  { nume: "Condoieşti", simplu: "Condoiesti", comuna: "Stefanesti" },
  { nume: "Contea", comuna: "Zatreni" },
  { nume: "Copăcelu", simplu: "Copacelu", comuna: "Ramnicu Valcea" },
  { nume: "Copăceni", simplu: "Copaceni" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "Racovita" },
  { nume: "Corbii din Vale", comuna: "Nicolae Balcescu" },
  { nume: "Corbu", comuna: "Brezoi" },
  { nume: "Cornet", comuna: "Vaideeni" },
  { nume: "Coşani", simplu: "Cosani", comuna: "Francesti" },
  { nume: "Cosota", comuna: "Ocnele Mari" },
  { nume: "Costeşti", simplu: "Costesti" },
  { nume: "Crângu", simplu: "Crangu", comuna: "Scundu" },
  { nume: "Cremenari", comuna: "Galicea" },
  { nume: "Creţeni", simplu: "Creteni" },
  { nume: "Cuceşti", simplu: "Cucesti", comuna: "Otesani" },
  { nume: "Cuci", comuna: "Fartatesti" },
  { nume: "Cucoiu", comuna: "Titesti" },
  { nume: "Cuculeşti", simplu: "Cuculesti", comuna: "Stanesti" },
  { nume: "Cueni", comuna: "Roesti" },
  { nume: "Curăturile", simplu: "Curaturile", comuna: "Baile Govora" },
  { nume: "Curtea", comuna: "Popesti" },
  { nume: "Dăeşti", simplu: "Daesti" },
  { nume: "Dăeşti", simplu: "Daesti", comuna: "Popesti" },
  { nume: "Dămţeni", simplu: "Damteni", comuna: "Berbesti" },
  { nume: "Dăncăi", simplu: "Dancai", comuna: "Fartatesti" },
  { nume: "Dângeşti", simplu: "Dangesti", comuna: "Berislavesti" },
  { nume: "Dealu Aluniş", simplu: "Dealu Alunis", comuna: "Berbesti" },
  { nume: "Dealu Bisericii", comuna: "Sinesti" },
  { nume: "Dealu Corni", comuna: "Ladesti" },
  { nume: "Dealu Glămeia", simplu: "Dealu Glameia", comuna: "Zatreni" },
  { nume: "Dealu Lăunele", simplu: "Dealu Launele", comuna: "Danicei" },
  { nume: "Dealu Malului", comuna: "Ramnicu Valcea" },
  { nume: "Dealu Mare", comuna: "Galicea" },
  { nume: "Dealu Mare", comuna: "Gusoeni" },
  { nume: "Dealu Mare", comuna: "Ionesti" },
  { nume: "Dealu Scheiului", comuna: "Danicei" },
  { nume: "Dealu Văleni", simplu: "Dealu Valeni", comuna: "Zatreni" },
  { nume: "Dejoi", comuna: "Fartatesti" },
  { nume: "Deleni", comuna: "Stoenesti" },
  { nume: "Delureni", comuna: "Ionesti" },
  { nume: "Delureni", comuna: "Stoilesti" },
  { nume: "Delureni", comuna: "Valea Mare" },
  { nume: "Dezrobiţi", simplu: "Dezrobiti", comuna: "Francesti" },
  { nume: "Diaconeşti", simplu: "Diaconesti", comuna: "Gradistea" },
  { nume: "Dianu", comuna: "Stroesti" },
  { nume: "Diculeşti", simplu: "Diculesti", comuna: "Fauresti" },
  { nume: "Dimuleşti", simplu: "Dimulesti", comuna: "Madulari" },
  { nume: "Dobreşti", simplu: "Dobresti", comuna: "Danicei" },
  { nume: "Dobricea", comuna: "Gradistea" },
  { nume: "Dobriceni", comuna: "Stoenesti" },
  { nume: "Dobruşa", simplu: "Dobrusa", comuna: "Stefanesti" },
  { nume: "Dosu Râului", simplu: "Dosu Raului", comuna: "Nicolae Balcescu" },
  { nume: "Dozeşti", simplu: "Dozesti", comuna: "Fartatesti" },
  { nume: "Drăgăneşti", simplu: "Draganesti", comuna: "Brezoi" },
  { nume: "Drăgăneşti", simplu: "Draganesti", comuna: "Golesti" },
  { nume: "Drăganu", simplu: "Draganu", comuna: "Valea Mare" },
  { nume: "Drăgăşani", simplu: "Dragasani" },
  { nume: "Drăgioiu", simplu: "Dragioiu", comuna: "Olanu" },
  { nume: "Drăgoeşti", simplu: "Dragoesti" },
  { nume: "Drăguleşti", simplu: "Dragulesti", comuna: "Danicei" },
  { nume: "Dumbrava", comuna: "Lungesti" },
  { nume: "Dumbrăveşti", simplu: "Dumbravesti", comuna: "Tomsani" },
  { nume: "Făcăi", simplu: "Facai", comuna: "Ocnele Mari" },
  { nume: "Fârtăţeşti", simplu: "Fartatesti" },
  { nume: "Făureşti", simplu: "Fauresti" },
  { nume: "Făureşti", simplu: "Fauresti", comuna: "Zatreni" },
  { nume: "Fedeleşoiu", simplu: "Fedelesoiu", comuna: "Daesti" },
  { nume: "Feţeni", simplu: "Feteni", comuna: "Ramnicu Valcea" },
  { nume: "Fireşti", simplu: "Firesti", comuna: "Bunesti" },
  { nume: "Firijba", comuna: "Popesti" },
  { nume: "Fişcălia", simplu: "Fiscalia", comuna: "Ionesti" },
  { nume: "Foleştii de Jos", simplu: "Folestii de Jos", comuna: "Tomsani" },
  { nume: "Foleştii de Sus", simplu: "Folestii de Sus", comuna: "Tomsani" },
  { nume: "Foteşti", simplu: "Fotesti", comuna: "Ionesti" },
  { nume: "Frânceşti-Coasta", simplu: "Francesti-Coasta", comuna: "Muereasca" },
  { nume: "Frânceşti", simplu: "Francesti" },
  { nume: "Frăsina", simplu: "Frasina", comuna: "Roesti" },
  { nume: "Fumureni", comuna: "Lungesti" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Vladesti" },
  { nume: "Găgeni", simplu: "Gageni", comuna: "Ladesti" },
  { nume: "Găineşti", simplu: "Gainesti", comuna: "Fauresti" },
  { nume: "Galicea" },
  { nume: "Gâltofani", simplu: "Galtofani", comuna: "Nicolae Balcescu" },
  { nume: "Găneşti", simplu: "Ganesti", comuna: "Zatreni" },
  { nume: "Gănţulei", simplu: "Gantulei", comuna: "Lungesti" },
  { nume: "Gârnicet", simplu: "Garnicet", comuna: "Fartatesti" },
  { nume: "Gârnicetu", simplu: "Garnicetu", comuna: "Stanesti" },
  { nume: "Gătejeşti", simplu: "Gatejesti", comuna: "Baile Govora" },
  { nume: "Găujani", simplu: "Gaujani", comuna: "Boisoara" },
  { nume: "Găvăneşti", simplu: "Gavanesti", comuna: "Muereasca" },
  { nume: "Geamăna", simplu: "Geamana", comuna: "Dragoesti" },
  { nume: "Geamăna", simplu: "Geamana", comuna: "Stoilesti" },
  { nume: "Genuneni", comuna: "Francesti" },
  { nume: "Ghindari", comuna: "Lalosu" },
  { nume: "Ghiobeşti", simplu: "Ghiobesti", comuna: "Stoilesti" },
  { nume: "Ghioroiu" },
  { nume: "Gibeşti", simplu: "Gibesti", comuna: "Golesti" },
  { nume: "Ginerica", comuna: "Nicolae Balcescu" },
  { nume: "Giuleşti", simplu: "Giulesti", comuna: "Fartatesti" },
  {
    nume: "Giuleştii de Sus",
    simplu: "Giulestii de Sus",
    comuna: "Fartatesti",
  },
  { nume: "Giurgiuveni", comuna: "Golesti" },
  { nume: "Giuroiu", comuna: "Stoilesti" },
  { nume: "Glăvile", simplu: "Glavile" },
  { nume: "Glodu", comuna: "Danicei" },
  { nume: "Golotreni", comuna: "Brezoi" },
  { nume: "Goranu", comuna: "Ramnicu Valcea" },
  { nume: "Goruneşti", simplu: "Gorunesti", comuna: "Balcesti" },
  { nume: "Goruneşti", simplu: "Gorunesti", comuna: "Slatioara" },
  { nume: "Govora", comuna: "Mihaesti" },
  { nume: "Grădiştea", simplu: "Gradistea" },
  { nume: "Grebleşti", simplu: "Greblesti", comuna: "Caineni" },
  { nume: "Greci", comuna: "Mateesti" },
  { nume: "Gropeni", comuna: "Runcu" },
  { nume: "Groşi", simplu: "Grosi", comuna: "Cernisoara" },
  { nume: "Gruieri", comuna: "Stoenesti" },
  { nume: "Gruiu Lupului", comuna: "Racovita" },
  { nume: "Gruiu", comuna: "Stoenesti" },
  { nume: "Guguianca", comuna: "Ionesti" },
  { nume: "Gura Crucilor", comuna: "Danicei" },
  { nume: "Gura Suhaşului", simplu: "Gura Suhasului", comuna: "Ocnele Mari" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Bujoreni" },
  { nume: "Gurguiata", comuna: "Baile Olanesti" },
  { nume: "Gurişoara", simplu: "Gurisoara", comuna: "Mihaesti" },
  { nume: "Guşoeni", simplu: "Gusoeni" },
  { nume: "Guşoianca", simplu: "Gusoianca", comuna: "Gusoeni" },
  { nume: "Herăşti", simplu: "Herasti", comuna: "Ghioroiu" },
  { nume: "Horezu" },
  { nume: "Hotărasa", simplu: "Hotarasa", comuna: "Copaceni" },
  { nume: "Hotarele", comuna: "Muereasca" },
  { nume: "Hotăroaia", simplu: "Hotaroaia", comuna: "Rosiile" },
  { nume: "Iacovile", comuna: "Madulari" },
  { nume: "Ifrimeşti", simplu: "Ifrimesti", comuna: "Horezu" },
  { nume: "Igoiu", comuna: "Alunu" },
  { nume: "Ilaciu", comuna: "Alunu" },
  { nume: "Ioneşti", simplu: "Ionesti" },
  { nume: "Irimeşti", simplu: "Irimesti", comuna: "Balcesti" },
  { nume: "Izbăseşti", simplu: "Izbasesti", comuna: "Milcoiu" },
  { nume: "Izvoraşu", simplu: "Izvorasu", comuna: "Sutesti" },
  { nume: "Izvoru Rece", comuna: "Stoilesti" },
  { nume: "Izvoru Rece", comuna: "Vaideeni" },
  { nume: "Izvoru", comuna: "Creteni" },
  { nume: "Jaroştea", simplu: "Jarostea", comuna: "Glavile" },
  { nume: "Jiblea Nouă", simplu: "Jiblea Noua", comuna: "Calimanesti" },
  { nume: "Jiblea Veche", comuna: "Calimanesti" },
  { nume: "Lăcusteni", simplu: "Lacusteni", comuna: "Zatreni" },
  { nume: "Lăcustenii de Jos", simplu: "Lacustenii de Jos", comuna: "Zatreni" },
  { nume: "Lăcustenii de Sus", simplu: "Lacustenii de Sus", comuna: "Zatreni" },
  { nume: "Lădeşti", simplu: "Ladesti" },
  { nume: "Laloşu", simplu: "Lalosu" },
  { nume: "Lăunele de Jos", simplu: "Launele de Jos", comuna: "Danicei" },
  { nume: "Lespezi", comuna: "Ramnicu Valcea" },
  { nume: "Linia Dealului", comuna: "Stanesti" },
  { nume: "Linia Hanului", comuna: "Nicolae Balcescu" },
  { nume: "Linia pe Vale", comuna: "Danicei" },
  { nume: "Linia", comuna: "Budesti" },
  { nume: "Linia", comuna: "Gradistea" },
  { nume: "Livadia", comuna: "Baile Olanesti" },
  { nume: "Livezi" },
  { nume: "Lunca", comuna: "Bujoreni" },
  { nume: "Lunca", comuna: "Ocnele Mari" },
  { nume: "Lungeşti", simplu: "Lungesti" },
  { nume: "Lupoaia", comuna: "Pesceana" },
  { nume: "Lupuieşti", simplu: "Lupuiesti", comuna: "Rosiile" },
  { nume: "Măciuceni", simplu: "Maciuceni", comuna: "Maciuca" },
  { nume: "Mădulari", simplu: "Madulari" },
  { nume: "Mădulari", simplu: "Madulari", comuna: "Cernisoara" },
  { nume: "Măgura", simplu: "Magura", comuna: "Mihaesti" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Gusoeni" },
  { nume: "Malaia" },
  { nume: "Măldăreşti", simplu: "Maldaresti" },
  { nume: "Măldăreşti", simplu: "Maldaresti", comuna: "Ladesti" },
  { nume: "Măldăreşti", simplu: "Maldaresti", comuna: "Maciuca" },
  {
    nume: "Măldăreştii de Jos",
    simplu: "Maldarestii de Jos",
    comuna: "Maldaresti",
  },
  { nume: "Malu Alb", comuna: "Bujoreni" },
  { nume: "Malu Vârtop", simplu: "Malu Vartop", comuna: "Bujoreni" },
  { nume: "Malu", comuna: "Stoilesti" },
  { nume: "Mamu", comuna: "Madulari" },
  { nume: "Mănăileşti", simplu: "Manailesti", comuna: "Francesti" },
  { nume: "Măneasa", simplu: "Maneasa", comuna: "Tetoiu" },
  { nume: "Mângureni", simplu: "Mangureni", comuna: "Nicolae Balcescu" },
  { nume: "Mănicea", simplu: "Manicea", comuna: "Zatreni" },
  { nume: "Marcea", comuna: "Ionesti" },
  { nume: "Mărcuşu", simplu: "Marcusu", comuna: "Fauresti" },
  { nume: "Mărgineni", simplu: "Margineni", comuna: "Valea Mare" },
  { nume: "Măriceşti", simplu: "Maricesti", comuna: "Fartatesti" },
  { nume: "Mariţa", simplu: "Marita", comuna: "Vaideeni" },
  { nume: "Mateeşti", simplu: "Mateesti" },
  { nume: "Măzăraru", simplu: "Mazararu", comuna: "Nicolae Balcescu" },
  { nume: "Măzili", simplu: "Mazili", comuna: "Sutesti" },
  { nume: "Mecea", comuna: "Zatreni" },
  { nume: "Meieni", comuna: "Popesti" },
  { nume: "Mereşeşti", simplu: "Meresesti", comuna: "Amarasti" },
  { nume: "Mierea", comuna: "Ghioroiu" },
  { nume: "Mihăeşti", simplu: "Mihaesti" },
  { nume: "Mijaţi", simplu: "Mijati", comuna: "Lapusata" },
  { nume: "Mijlocu", comuna: "Sinesti" },
  { nume: "Milcoiu" },
  { nume: "Mileşti", simplu: "Milesti", comuna: "Fauresti" },
  { nume: "Milostea", comuna: "Slatioara" },
  { nume: "Mireşti", simplu: "Miresti", comuna: "Tomsani" },
  { nume: "Mitrofani", comuna: "Sutesti" },
  { nume: "Mlăceni", simplu: "Mlaceni", comuna: "Perisani" },
  { nume: "Modoia", comuna: "Cernisoara" },
  { nume: "Mogeşti", simplu: "Mogesti", comuna: "Slatioara" },
  { nume: "Mogoşeşti", simplu: "Mogosesti", comuna: "Stoenesti" },
  { nume: "Mologeşti", simplu: "Mologesti", comuna: "Lalosu" },
  { nume: "Moşoroaşa", simplu: "Mosoroasa", comuna: "Baile Olanesti" },
  { nume: "Moşteni", simplu: "Mosteni", comuna: "Francesti" },
  { nume: "Mreneşti", simplu: "Mrenesti", comuna: "Creteni" },
  { nume: "Muereasca de Sus", comuna: "Muereasca" },
  { nume: "Muereasca" },
  { nume: "Munteni", comuna: "Mihaesti" },
  { nume: "Neghineşti", simplu: "Neghinesti", comuna: "Stoenesti" },
  { nume: "Negraia", comuna: "Pesceana" },
  { nume: "Negreni", comuna: "Mihaesti" },
  { nume: "Negruleşti", simplu: "Negrulesti", comuna: "Barbatesti" },
  { nume: "Nemoiu", comuna: "Amarasti" },
  { nume: "Nenciuleşti", simplu: "Nenciulesti", comuna: "Tetoiu" },
  { nume: "Neţeşti", simplu: "Netesti", comuna: "Stoilesti" },
  { nume: "Nicoleşti", simplu: "Nicolesti", comuna: "Olanu" },
  { nume: "Nisipi", comuna: "Fartatesti" },
  { nume: "Obârşia", simplu: "Obarsia", comuna: "Cernisoara" },
  { nume: "Obislavu", comuna: "Gradistea" },
  { nume: "Obogeni", comuna: "Stoilesti" },
  { nume: "Obroceşti", simplu: "Obrocesti", comuna: "Stroesti" },
  { nume: "Ocniţa", simplu: "Ocnita", comuna: "Ocnele Mari" },
  { nume: "Ocracu", comuna: "Alunu" },
  { nume: "Olăneşti", simplu: "Olanesti", comuna: "Baile Olanesti" },
  { nume: "Olanu" },
  { nume: "Olteanca", comuna: "Glavile" },
  { nume: "Olteanca", comuna: "Ladesti" },
  { nume: "Olteni", comuna: "Bujoreni" },
  { nume: "Olteţani", simplu: "Oltetani", comuna: "Lalosu" },
  { nume: "Olteţu", simplu: "Oltetu", comuna: "Zatreni" },
  { nume: "Opăteşti", simplu: "Opatesti", comuna: "Golesti" },
  { nume: "Orleşti", simplu: "Orlesti" },
  { nume: "Ostroveni", comuna: "Galicea" },
  { nume: "Oteşani", simplu: "Otesani" },
  { nume: "Otetelişu", simplu: "Otetelisu", comuna: "Balcesti" },
  { nume: "Oveselu", comuna: "Maciuca" },
  { nume: "Padina", comuna: "Amarasti" },
  { nume: "Pădureţu", simplu: "Paduretu", comuna: "Babeni" },
  { nume: "Palanga", comuna: "Amarasti" },
  { nume: "Pârâienii de Jos", simplu: "Paraienii de Jos", comuna: "Livezi" },
  {
    nume: "Pârâienii de Mijloc",
    simplu: "Paraienii de Mijloc",
    comuna: "Livezi",
  },
  { nume: "Pârâienii de Sus", simplu: "Paraienii de Sus", comuna: "Livezi" },
  { nume: "Părăuşani", simplu: "Parausani", comuna: "Livezi" },
  { nume: "Păsărei", simplu: "Pasarei", comuna: "Rosiile" },
  { nume: "Păscoaia", simplu: "Pascoaia", comuna: "Brezoi" },
  { nume: "Păsculeşti", simplu: "Pasculesti", comuna: "Ladesti" },
  { nume: "Păteşti", simplu: "Patesti", comuna: "Salatrucel" },
  { nume: "Păuşa", simplu: "Pausa", comuna: "Calimanesti" },
  { nume: "Păuşeşti-Măglaşi", simplu: "Pausesti-Maglasi" },
  { nume: "Păuseşti-Otăsău", simplu: "Pausesti-Otasau", comuna: "Pausesti" },
  { nume: "Păuşeşti", simplu: "Pausesti" },
  { nume: "Perişani", simplu: "Perisani" },
  { nume: "Perteşti", simplu: "Pertesti", comuna: "Rosiile" },
  { nume: "Pesceana" },
  { nume: "Pietrari" },
  { nume: "Pietrari", comuna: "Pausesti-Maglasi" },
  { nume: "Pietrarii de Sus", comuna: "Pietrari" },
  { nume: "Pietreni", comuna: "Costesti" },
  { nume: "Pietrişu", simplu: "Pietrisu", comuna: "Baile Olanesti" },
  { nume: "Pietroasa", comuna: "Valea Mare" },
  { nume: "Piscu Mare", comuna: "Stoenesti" },
  { nume: "Piscu Pietrei", comuna: "Budesti" },
  { nume: "Piscu Scoarţei", simplu: "Piscu Scoartei", comuna: "Roesti" },
  { nume: "Pleaşa", simplu: "Pleasa", comuna: "Vladesti" },
  { nume: "Pleseşti", simplu: "Plesesti", comuna: "Rosiile" },
  { nume: "Pleşoiu", simplu: "Plesoiu", comuna: "Livezi" },
  { nume: "Pleşoiu", simplu: "Plesoiu", comuna: "Nicolae Balcescu" },
  { nume: "Podeni", comuna: "Perisani" },
  { nume: "Poenari", comuna: "Ramnicu Valcea" },
  { nume: "Poeniţa", simplu: "Poenita", comuna: "Golesti" },
  { nume: "Poiana", comuna: "Perisani" },
  { nume: "Poienari", comuna: "Ghioroiu" },
  { nume: "Pojogi-Cerna", comuna: "Stroesti" },
  { nume: "Popeşti", simplu: "Popesti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Fartatesti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Golesti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Ladesti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Maciuca" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Nicolae Balcescu" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Sinesti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Stoenesti" },
  { nume: "Popeşti", simplu: "Popesti", comuna: "Tetoiu" },
  { nume: "Portăreşti", simplu: "Portaresti", comuna: "Lalosu" },
  { nume: "Prajila", comuna: "Baile Govora" },
  { nume: "Predeşti", simplu: "Predesti", comuna: "Nicolae Balcescu" },
  { nume: "Preoteşti", simplu: "Preotesti", comuna: "Balcesti" },
  { nume: "Priba", comuna: "Ramnicu Valcea" },
  { nume: "Priloage", comuna: "Caineni" },
  { nume: "Pripoara", comuna: "Muereasca" },
  { nume: "Pripoare", comuna: "Perisani" },
  { nume: "Priporu", comuna: "Vladesti" },
  { nume: "Procopoaia", comuna: "Orlesti" },
  { nume: "Prodăneşti", simplu: "Prodanesti", comuna: "Ionesti" },
  { nume: "Proieni", comuna: "Brezoi" },
  { nume: "Prundeni" },
  { nume: "Racoviţa", simplu: "Racovita" },
  { nume: "Racoviţa", simplu: "Racovita", comuna: "Budesti" },
  { nume: "Racu", comuna: "Sutesti" },
  { nume: "Rădăcineşti", simplu: "Radacinesti", comuna: "Berislavesti" },
  { nume: "Râmeşti", simplu: "Ramesti", comuna: "Horezu" },
  { nume: "Râmeşti", simplu: "Ramesti", comuna: "Susani" },
  { nume: "Râmnicu Vâlcea", simplu: "Ramnicu Valcea" },
  { nume: "Râpa Cărămizii", simplu: "Rapa Caramizii", comuna: "Roesti" },
  { nume: "Râpăneşti", simplu: "Rapanesti", comuna: "Bunesti" },
  { nume: "Răţăleşti", simplu: "Ratalesti", comuna: "Rosiile" },
  { nume: "Râu Vadului", simplu: "Rau Vadului", comuna: "Caineni" },
  { nume: "Râureni", simplu: "Raureni", comuna: "Ramnicu Valcea" },
  { nume: "Robaia", comuna: "Berislavesti" },
  { nume: "Robeşti", simplu: "Robesti", comuna: "Caineni" },
  { nume: "Roeşti", simplu: "Roesti" },
  { nume: "Roeşti", simplu: "Roesti", comuna: "Pesceana" },
  { nume: "Româneşti", simplu: "Romanesti", comuna: "Rosiile" },
  { nume: "Români", simplu: "Romani", comuna: "Babeni" },
  { nume: "Romanii de Jos", comuna: "Horezu" },
  { nume: "Romanii de Sus", comuna: "Horezu" },
  { nume: "Roşia", simplu: "Rosia", comuna: "Alunu" },
  { nume: "Roşiile", simplu: "Rosiile" },
  { nume: "Roşioara", simplu: "Rosioara", comuna: "Berbesti" },
  { nume: "Roşoveni", simplu: "Rosoveni", comuna: "Maldaresti" },
  { nume: "Rotărăşti", simplu: "Rotarasti", comuna: "Nicolae Balcescu" },
  { nume: "Ruda", comuna: "Budesti" },
  { nume: "Rugetu", comuna: "Mihaesti" },
  { nume: "Rugetu", comuna: "Slatioara" },
  { nume: "Runcu" },
  { nume: "Rusăneşti", simplu: "Rusanesti", comuna: "Fartatesti" },
  { nume: "Saioci", comuna: "Roesti" },
  { nume: "Sălătrucel", simplu: "Salatrucel" },
  { nume: "Săliştea", simplu: "Salistea", comuna: "Malaia" },
  { nume: "Săliştea", simplu: "Salistea", comuna: "Ramnicu Valcea" },
  { nume: "Sânbotin", simplu: "Sanbotin", comuna: "Daesti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Susani" },
  { nume: "Sărsăneşti", simplu: "Sarsanesti", comuna: "Cernisoara" },
  { nume: "Săruleşti", simplu: "Sarulesti", comuna: "Lapusata" },
  { nume: "Săşcioara", simplu: "Sascioara", comuna: "Zatreni" },
  { nume: "Satu Poieni", comuna: "Balcesti" },
  { nume: "Scaioşi", simplu: "Scaiosi", comuna: "Orlesti" },
  { nume: "Scărişoara", simplu: "Scarisoara", comuna: "Mihaesti" },
  { nume: "Scăueni", simplu: "Scaueni", comuna: "Berislavesti" },
  { nume: "Schitu", comuna: "Nicolae Balcescu" },
  { nume: "Scoruşu", simplu: "Scorusu", comuna: "Lapusata" },
  { nume: "Scundu" },
  { nume: "Seaca", comuna: "Calimanesti" },
  { nume: "Seaca", comuna: "Salatrucel" },
  { nume: "Seciu", comuna: "Fartatesti" },
  { nume: "Şerbăneasa", simplu: "Serbaneasa", comuna: "Nicolae Balcescu" },
  { nume: "Şerbăneşti", simplu: "Serbanesti", comuna: "Lapusata" },
  { nume: "Şerbăneşti", simplu: "Serbanesti", comuna: "Pausesti" },
  { nume: "Şerbăneşti", simplu: "Serbanesti", comuna: "Salatrucel" },
  { nume: "Şerbăneşti", simplu: "Serbanesti", comuna: "Stefanesti" },
  { nume: "Silea", comuna: "Orlesti" },
  { nume: "Sineşti", simplu: "Sinesti" },
  { nume: "Şirineasa", simplu: "Sirineasa" },
  { nume: "Slătioara", simplu: "Slatioara" },
  { nume: "Slătioarele", simplu: "Slatioarele", comuna: "Ocnele Mari" },
  { nume: "Slăviteşti", simplu: "Slavitesti", comuna: "Sirineasa" },
  { nume: "Snamăna", simplu: "Snamana", comuna: "Runcu" },
  { nume: "Şoliceşti", simplu: "Solicesti", comuna: "Pausesti" },
  { nume: "Şotani", simplu: "Sotani", comuna: "Fartatesti" },
  { nume: "Spârleni", simplu: "Sparleni", comuna: "Gusoeni" },
  { nume: "Spinu", comuna: "Perisani" },
  { nume: "Stănculeşti", simplu: "Stanculesti", comuna: "Fartatesti" },
  { nume: "Stăneşti-Lunca", simplu: "Stanesti-Lunca", comuna: "Lungesti" },
  { nume: "Stăneşti", simplu: "Stanesti" },
  { nume: "Stăneşti", simplu: "Stanesti", comuna: "Stoilesti" },
  { nume: "Stanomiru", comuna: "Zatreni" },
  { nume: "Ştefăneşti", simplu: "Stefanesti" },
  { nume: "Ştefăneşti", simplu: "Stefanesti", comuna: "Maciuca" },
  { nume: "Ştirbeşti", simplu: "Stirbesti", comuna: "Ghioroiu" },
  { nume: "Stoeneşti", simplu: "Stoenesti" },
  { nume: "Stoeneşti", simplu: "Stoenesti", comuna: "Berislavesti" },
  { nume: "Stoicăneşti", simplu: "Stoicanesti", comuna: "Olanu" },
  { nume: "Stoiculeşti", simplu: "Stoiculesti", comuna: "Susani" },
  { nume: "Stoileşti", simplu: "Stoilesti" },
  { nume: "Stolniceni", comuna: "Ramnicu Valcea" },
  { nume: "Străchineşti", simplu: "Strachinesti", comuna: "Gradistea" },
  { nume: "Streminoasa", comuna: "Creteni" },
  { nume: "Stroeşti", simplu: "Stroesti" },
  { nume: "Stupărei", simplu: "Stuparei", comuna: "Mihaesti" },
  { nume: "Sub Deal", comuna: "Otesani" },
  { nume: "Suieşti", simplu: "Suiesti", comuna: "Stanesti" },
  { nume: "Surdoiu", comuna: "Perisani" },
  { nume: "Şuricaru", simplu: "Suricaru", comuna: "Milcoiu" },
  { nume: "Surpatele", comuna: "Francesti" },
  { nume: "Surpaţi", simplu: "Surpati", comuna: "Runcu" },
  { nume: "Şuşani", simplu: "Susani" },
  { nume: "Suseni", comuna: "Stoenesti" },
  { nume: "Şuta", simplu: "Suta", comuna: "Muereasca" },
  { nume: "Suteşti", simplu: "Sutesti" },
  { nume: "Tănăseşti", simplu: "Tanasesti", comuna: "Horezu" },
  { nume: "Tanislavi", comuna: "Fartatesti" },
  { nume: "Târgu Gânguleşti", simplu: "Targu Gangulesti", comuna: "Berbesti" },
  { nume: "Tătărani", simplu: "Tatarani", comuna: "Babeni" },
  { nume: "Ţeica", simplu: "Teica", comuna: "Ocnele Mari" },
  { nume: "Teiu", comuna: "Galicea" },
  { nume: "Teiul", comuna: "Amarasti" },
  { nume: "Teiuşu", simplu: "Teiusu", comuna: "Bunesti" },
  { nume: "Telecheşti", simplu: "Telechesti", comuna: "Maldaresti" },
  { nume: "Ţepeşti", simplu: "Tepesti", comuna: "Tetoiu" },
  { nume: "Tepşenari", simplu: "Tepsenari", comuna: "Milcoiu" },
  { nume: "Tetoiu" },
  { nume: "Tighina", comuna: "Voicesti" },
  { nume: "Tina", comuna: "Livezi" },
  { nume: "Tisa", comuna: "Baile Olanesti" },
  { nume: "Titeşti", simplu: "Titesti" },
  { nume: "Titireci", comuna: "Bunesti" },
  { nume: "Tomşani", simplu: "Tomsani" },
  { nume: "Troian", comuna: "Ramnicu Valcea" },
  { nume: "Trundin", comuna: "Vladesti" },
  { nume: "Tufanii", comuna: "Nicolae Balcescu" },
  { nume: "Tulei-Câmpeni", simplu: "Tulei-Campeni", comuna: "Golesti" },
  { nume: "Turburea", comuna: "Gradistea" },
  { nume: "Turceşti", simplu: "Turcesti", comuna: "Mateesti" },
  { nume: "Tuţuleşti", simplu: "Tutulesti", comuna: "Racovita" },
  { nume: "Ţuţuru", simplu: "Tuturu", comuna: "Gradistea" },
  { nume: "Udreşti", simplu: "Udresti", comuna: "Danicei" },
  { nume: "Ulmeţel", simplu: "Ulmetel", comuna: "Pausesti-Maglasi" },
  { nume: "Ulmetu", comuna: "Copaceni" },
  { nume: "Urşani", simplu: "Ursani", comuna: "Horezu" },
  { nume: "Urşi", simplu: "Ursi", comuna: "Popesti" },
  { nume: "Urşi", simplu: "Ursi", comuna: "Stoilesti" },
  { nume: "Ursoaia", comuna: "Pesceana" },
  { nume: "Urzica", comuna: "Sinesti" },
  { nume: "Uşurei", simplu: "Usurei", comuna: "Susani" },
  { nume: "Vaideeni" },
  { nume: "Valea Alunişului", simplu: "Valea Alunisului", comuna: "Sirineasa" },
  { nume: "Valea Babei", comuna: "Runcu" },
  {
    nume: "Valea Bălcească",
    simplu: "Valea Balceasca",
    comuna: "Nicolae Balcescu",
  },
  { nume: "Valea Caselor", comuna: "Dragasani" },
  { nume: "Valea Caselor", comuna: "Popesti" },
  { nume: "Valea Cheii", comuna: "Pausesti-Maglasi" },
  { nume: "Valea Grădiştei", simplu: "Valea Gradistei", comuna: "Gradistea" },
  { nume: "Valea lui Stan", comuna: "Brezoi" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Stanesti" },
  { nume: "Valea Măceşului", simplu: "Valea Macesului", comuna: "Voineasa" },
  { nume: "Valea Mare" },
  { nume: "Valea Mare", comuna: "Babeni" },
  { nume: "Valea Mare", comuna: "Berbesti" },
  { nume: "Valea Râului", simplu: "Valea Raului", comuna: "Galicea" },
  { nume: "Valea Scheiului", comuna: "Danicei" },
  { nume: "Valea Ursului", comuna: "Fartatesti" },
  { nume: "Valea Văleni", simplu: "Valea Valeni", comuna: "Zatreni" },
  { nume: "Valea Viei", comuna: "Nicolae Balcescu" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Pausesti" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Zatreni" },
  { nume: "Vărateci", simplu: "Varateci", comuna: "Runcu" },
  { nume: "Văratica", simplu: "Varatica", comuna: "Brezoi" },
  { nume: "Văratici", simplu: "Varatici", comuna: "Costesti" },
  { nume: "Vârleni", simplu: "Varleni", comuna: "Stanesti" },
  { nume: "Vătăşeşti", simplu: "Vatasesti", comuna: "Golesti" },
  { nume: "Verdea", comuna: "Sutesti" },
  { nume: "Veţelu", simplu: "Vetelu", comuna: "Copaceni" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Francesti" },
  { nume: "Vlădeşti", simplu: "Vladesti" },
  { nume: "Vlăduceni", simplu: "Vladuceni", comuna: "Pausesti-Maglasi" },
  { nume: "Vlăduleşti", simplu: "Vladulesti", comuna: "Stoilesti" },
  { nume: "Voiceşti", simplu: "Voicesti" },
  {
    nume: "Voiceştii din Vale",
    simplu: "Voicestii din Vale",
    comuna: "Voicesti",
  },
  { nume: "Voiculeasa", comuna: "Glavile" },
  { nume: "Voineasa" },
  { nume: "Voineşiţa", simplu: "Voinesita", comuna: "Voineasa" },
  { nume: "Vulpueşti", simplu: "Vulpuesti", comuna: "Mihaesti" },
  { nume: "Zărneni", simplu: "Zarneni", comuna: "Dragasani" },
  { nume: "Zărneşti", simplu: "Zarnesti", comuna: "Lapusata" },
  { nume: "Zătreni", simplu: "Zatreni" },
  { nume: "Zătrenii de Sus", simplu: "Zatrenii de Sus", comuna: "Zatreni" },
  { nume: "Zăvideni", simplu: "Zavideni", comuna: "Prundeni" },
  { nume: "Zăvoieni", simplu: "Zavoieni", comuna: "Maciuca" },
  { nume: "Zgubea", comuna: "Rosiile" },
  { nume: "Zlătărei", simplu: "Zlatarei", comuna: "Dragasani" },
  { nume: "Zmeurătu", simplu: "Zmeuratu", comuna: "Stoenesti" },
];
