export const vl = [
  { nume: "Afânata", simplu: "Afanata", comuna: "Fartatesti" },
  { nume: "Aldești", simplu: "Aldesti", comuna: "Golesti" },
  { nume: "Alunu" },
  { nume: "Amărăști", simplu: "Amarasti" },
  { nume: "Andreiești", simplu: "Andreiesti", comuna: "Muereasca" },
  { nume: "Aninoasa", comuna: "Glavile" },
  { nume: "Aranghel", comuna: "Ramnicu Valcea" },
  { nume: "Aricioaia", comuna: "Sirineasa" },
  { nume: "Armășești", simplu: "Armasesti", comuna: "Cernisoara" },
  { nume: "Arsanca", comuna: "Mihaesti" },
  { nume: "Aurești", simplu: "Auresti", comuna: "Orlesti" },
  { nume: "Avrămești", simplu: "Avramesti", comuna: "Scundu" },
  { nume: "Băbeni-Oltețu", simplu: "Babeni-Oltetu", comuna: "Fauresti" },
  { nume: "Băbeni", simplu: "Babeni" },
  { nume: "Băbuești", simplu: "Babuesti", comuna: "Daesti" },
  { nume: "Bădeni", simplu: "Badeni", comuna: "Danicei" },
  { nume: "Băiașa", simplu: "Baiasa", comuna: "Roesti" },
  { nume: "Băiașu", simplu: "Baiasu", comuna: "Perisani" },
  { nume: "Băjenari", simplu: "Bajenari", comuna: "Roesti" },
  { nume: "Balaciu", comuna: "Rosiile" },
  { nume: "Bălcești", simplu: "Balcesti" },
  { nume: "Balomireasa", comuna: "Stoilesti" },
  { nume: "Balota", comuna: "Racovita" },
  { nume: "Bălșoara", simplu: "Balsoara", comuna: "Madulari" },
  { nume: "Băltățeni", simplu: "Baltateni", comuna: "Tomsani" },
  { nume: "Bălteni", simplu: "Balteni", comuna: "Copaceni" },
  { nume: "Băluțoaia", simplu: "Balutoaia", comuna: "Francesti" },
  { nume: "Bănești", simplu: "Banesti", comuna: "Nicolae Balcescu" },
  { nume: "Bănțești", simplu: "Bantesti", comuna: "Madulari" },
  { nume: "Bărbărigeni", simplu: "Barbarigeni", comuna: "Roesti" },
  { nume: "Bărbătești", simplu: "Barbatesti" },
  { nume: "Bărbuceni", simplu: "Barbuceni", comuna: "Prundeni" },
  { nume: "Barcanele", comuna: "Pausesti" },
  { nume: "Bărcănești", simplu: "Barcanesti", comuna: "Stanesti" },
  { nume: "Bârlogu", simplu: "Barlogu", comuna: "Stoenesti" },
  { nume: "Băroiu", simplu: "Baroiu", comuna: "Tetoiu" },
  { nume: "Bârsești", simplu: "Barsesti", comuna: "Budesti" },
  { nume: "Bârsești", simplu: "Barsesti", comuna: "Mihaesti" },
  { nume: "Bârsoiu", simplu: "Barsoiu", comuna: "Stoilesti" },
  { nume: "Barza", comuna: "Budesti" },
  { nume: "Bârzești", simplu: "Barzesti", comuna: "Barbatesti" },
  { nume: "Bătășani", simplu: "Batasani", comuna: "Valea Mare" },
  { nume: "Becșani", simplu: "Becsani", comuna: "Fartatesti" },
  { nume: "Benești", simplu: "Benesti", comuna: "Balcesti" },
  { nume: "Berbești", simplu: "Berbesti" },
  { nume: "Berbești", simplu: "Berbesti", comuna: "Lalosu" },
  { nume: "Bercioiu", comuna: "Budesti" },
  { nume: "Berești", simplu: "Beresti", comuna: "Lapusata" },
  { nume: "Berislăvești", simplu: "Berislavesti" },
  { nume: "Bistrița", simplu: "Bistrita", comuna: "Costesti" },
  { nume: "Blănoiu", simplu: "Blanoiu", comuna: "Racovita" },
  { nume: "Blejani", comuna: "Scundu" },
  { nume: "Blidari", comuna: "Golesti" },
  { nume: "Bocșa", simplu: "Bocsa", comuna: "Maciuca" },
  { nume: "Bodești", simplu: "Bodesti", comuna: "Alunu" },
  { nume: "Bodești", simplu: "Bodesti", comuna: "Barbatesti" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Bujoreni" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Otesani" },
  { nume: "Bogdănești", simplu: "Bogdanesti", comuna: "Tomsani" },
  { nume: "Boișoara", simplu: "Boisoara" },
  { nume: "Bonciu", comuna: "Babeni" },
  { nume: "Bondoci", comuna: "Copaceni" },
  { nume: "Boroșești", simplu: "Borosesti", comuna: "Sutesti" },
  { nume: "Botorani", comuna: "Maciuca" },
  { nume: "Brădișor", simplu: "Bradisor", comuna: "Berislavesti" },
  { nume: "Bradu-Clocotici", comuna: "Racovita" },
  { nume: "Bratia din Deal", comuna: "Galicea" },
  { nume: "Bratia din Vale", comuna: "Galicea" },
  { nume: "Bratovești", simplu: "Bratovesti", comuna: "Titesti" },
  { nume: "Brezoi" },
  { nume: "Broșteni", simplu: "Brosteni", comuna: "Lapusata" },
  { nume: "Buciumeni", comuna: "Dragoesti" },
  { nume: "Bucșani", simplu: "Bucsani", comuna: "Ionesti" },
  { nume: "Buda", comuna: "Ocnele Mari" },
  { nume: "Budele", comuna: "Tetoiu" },
  { nume: "Budești", simplu: "Budesti" },
  { nume: "Budești", simplu: "Budesti", comuna: "Fauresti" },
  { nume: "Budurăști", simplu: "Budurasti", comuna: "Stoenesti" },
  { nume: "Bujoreni" },
  { nume: "Bulagei", comuna: "Stoilesti" },
  { nume: "Buleta", comuna: "Mihaesti" },
  { nume: "Bumbuești", simplu: "Bumbuesti", comuna: "Boisoara" },
  { nume: "Bunești", simplu: "Bunesti" },
  { nume: "Bungețani", simplu: "Bungetani", comuna: "Fauresti" },
  { nume: "Burdălești", simplu: "Burdalesti", comuna: "Gusoeni" },
  { nume: "Butanu", comuna: "Zatreni" },
  { nume: "Buzdugan", comuna: "Pausesti" },
  { nume: "Căciulata", simplu: "Caciulata", comuna: "Calimanesti" },
  { nume: "Câinenii Mari", simplu: "Cainenii Mari", comuna: "Caineni" },
  { nume: "Câinenii Mici", simplu: "Cainenii Mici", comuna: "Caineni" },
  { nume: "Căligi", simplu: "Caligi", comuna: "Runcu" },
  { nume: "Călimănești", simplu: "Calimanesti" },
  { nume: "Călina", simplu: "Calina", comuna: "Prundeni" },
  { nume: "Călinești", simplu: "Calinesti", comuna: "Brezoi" },
  { nume: "Capu Dealului", comuna: "Babeni" },
  { nume: "Cărcădiești", simplu: "Carcadiesti", comuna: "Lungesti" },
  { nume: "Cârlogani", simplu: "Carlogani", comuna: "Balcesti" },
  { nume: "Cârstănești", simplu: "Carstanesti", comuna: "Otesani" },
  { nume: "Casa Veche", comuna: "Olanu" },
  { nume: "Cățetu", simplu: "Catetu", comuna: "Fartatesti" },
  { nume: "Căzănești", simplu: "Cazanesti", comuna: "Ghioroiu" },
  { nume: "Căzănești", simplu: "Cazanesti", comuna: "Milcoiu" },
  { nume: "Căzănești", simplu: "Cazanesti", comuna: "Ramnicu Valcea" },
  { nume: "Ceretu", comuna: "Danicei" },
  { nume: "Cermegești", simplu: "Cermegesti", comuna: "Ladesti" },
  { nume: "Cermegești", simplu: "Cermegesti", comuna: "Pesceana" },
  { nume: "Cerna", comuna: "Vaideeni" },
  { nume: "Cernelele", comuna: "Pausesti" },
  { nume: "Cernișoara", simplu: "Cernisoara" },
  { nume: "Cetățeaua", simplu: "Cetateaua", comuna: "Sutesti" },
  { nume: "Cheia", comuna: "Baile Olanesti" },
  { nume: "Cherăști", simplu: "Cherasti", comuna: "Rosiile" },
  { nume: "Chiceni", comuna: "Tomsani" },
  { nume: "Chirculești", simplu: "Chirculesti", comuna: "Balcesti" },
  { nume: "Chiricești", simplu: "Chiricesti", comuna: "Ladesti" },
  { nume: "Cioboți", simplu: "Cioboti", comuna: "Olanu" },
  { nume: "Ciocâltei", simplu: "Ciocaltei", comuna: "Roesti" },
  { nume: "Ciocănari", simplu: "Ciocanari", comuna: "Maciuca" },
  { nume: "Cioponești", simplu: "Cioponesti", comuna: "Stanesti" },
  { nume: "Ciorăști", simplu: "Ciorasti", comuna: "Sirineasa" },
  { nume: "Ciortești", simplu: "Ciortesti", comuna: "Zatreni" },
  { nume: "Cireșu", simplu: "Ciresu", comuna: "Stroesti" },
  { nume: "Cireșul", simplu: "Ciresul", comuna: "Danicei" },
  { nume: "Ciucheți", simplu: "Ciucheti", comuna: "Sinesti" },
  { nume: "Ciumagi", comuna: "Ladesti" },
  { nume: "Ciungetu", comuna: "Malaia" },
  { nume: "Ciutești", simplu: "Ciutesti", comuna: "Milcoiu" },
  { nume: "Coasta Cerbului", comuna: "Slatioara" },
  { nume: "Coasta Mare", comuna: "Bunesti" },
  { nume: "Coasta", comuna: "Golesti" },
  { nume: "Coasta", comuna: "Pausesti-Maglasi" },
  { nume: "Cocoru", comuna: "Galicea" },
  { nume: "Colelia", comuna: "Fauresti" },
  { nume: "Coltești", simplu: "Coltesti", comuna: "Alunu" },
  { nume: "Comanca", comuna: "Baile Olanesti" },
  { nume: "Condoiești", simplu: "Condoiesti", comuna: "Stefanesti" },
  { nume: "Contea", comuna: "Zatreni" },
  { nume: "Copăcelu", simplu: "Copacelu", comuna: "Ramnicu Valcea" },
  { nume: "Copăceni", simplu: "Copaceni" },
  { nume: "Copăceni", simplu: "Copaceni", comuna: "Racovita" },
  { nume: "Corbii din Vale", comuna: "Nicolae Balcescu" },
  { nume: "Corbu", comuna: "Brezoi" },
  { nume: "Cornet", comuna: "Vaideeni" },
  { nume: "Coșani", simplu: "Cosani", comuna: "Francesti" },
  { nume: "Cosota", comuna: "Ocnele Mari" },
  { nume: "Costești", simplu: "Costesti" },
  { nume: "Crângu", simplu: "Crangu", comuna: "Scundu" },
  { nume: "Cremenari", comuna: "Galicea" },
  { nume: "Crețeni", simplu: "Creteni" },
  { nume: "Cucești", simplu: "Cucesti", comuna: "Otesani" },
  { nume: "Cuci", comuna: "Fartatesti" },
  { nume: "Cucoiu", comuna: "Titesti" },
  { nume: "Cuculești", simplu: "Cuculesti", comuna: "Stanesti" },
  { nume: "Cueni", comuna: "Roesti" },
  { nume: "Curăturile", simplu: "Curaturile", comuna: "Baile Govora" },
  { nume: "Curtea", comuna: "Popesti" },
  { nume: "Dăești", simplu: "Daesti" },
  { nume: "Dăești", simplu: "Daesti", comuna: "Popesti" },
  { nume: "Dămțeni", simplu: "Damteni", comuna: "Berbesti" },
  { nume: "Dăncăi", simplu: "Dancai", comuna: "Fartatesti" },
  { nume: "Dângești", simplu: "Dangesti", comuna: "Berislavesti" },
  { nume: "Dealu Aluniș", simplu: "Dealu Alunis", comuna: "Berbesti" },
  { nume: "Dealu Bisericii", comuna: "Sinesti" },
  { nume: "Dealu Corni", comuna: "Ladesti" },
  { nume: "Dealu Glămeia", simplu: "Dealu Glameia", comuna: "Zatreni" },
  { nume: "Dealu Lăunele", simplu: "Dealu Launele", comuna: "Danicei" },
  { nume: "Dealu Malului", comuna: "Ramnicu Valcea" },
  { nume: "Dealu Mare", comuna: "Galicea" },
  { nume: "Dealu Mare", comuna: "Gusoeni" },
  { nume: "Dealu Mare", comuna: "Ionesti" },
  { nume: "Dealu Scheiului", comuna: "Danicei" },
  { nume: "Dealu Văleni", simplu: "Dealu Valeni", comuna: "Zatreni" },
  { nume: "Dejoi", comuna: "Fartatesti" },
  { nume: "Deleni", comuna: "Stoenesti" },
  { nume: "Delureni", comuna: "Ionesti" },
  { nume: "Delureni", comuna: "Stoilesti" },
  { nume: "Delureni", comuna: "Valea Mare" },
  { nume: "Dezrobiți", simplu: "Dezrobiti", comuna: "Francesti" },
  { nume: "Diaconești", simplu: "Diaconesti", comuna: "Gradistea" },
  { nume: "Dianu", comuna: "Stroesti" },
  { nume: "Diculești", simplu: "Diculesti", comuna: "Fauresti" },
  { nume: "Dimulești", simplu: "Dimulesti", comuna: "Madulari" },
  { nume: "Dobrești", simplu: "Dobresti", comuna: "Danicei" },
  { nume: "Dobricea", comuna: "Gradistea" },
  { nume: "Dobriceni", comuna: "Stoenesti" },
  { nume: "Dobrușa", simplu: "Dobrusa", comuna: "Stefanesti" },
  { nume: "Dosu Râului", simplu: "Dosu Raului", comuna: "Nicolae Balcescu" },
  { nume: "Dozești", simplu: "Dozesti", comuna: "Fartatesti" },
  { nume: "Drăgănești", simplu: "Draganesti", comuna: "Brezoi" },
  { nume: "Drăgănești", simplu: "Draganesti", comuna: "Golesti" },
  { nume: "Drăganu", simplu: "Draganu", comuna: "Valea Mare" },
  { nume: "Drăgășani", simplu: "Dragasani" },
  { nume: "Drăgioiu", simplu: "Dragioiu", comuna: "Olanu" },
  { nume: "Drăgoești", simplu: "Dragoesti" },
  { nume: "Drăgulești", simplu: "Dragulesti", comuna: "Danicei" },
  { nume: "Dumbrava", comuna: "Lungesti" },
  { nume: "Dumbrăvești", simplu: "Dumbravesti", comuna: "Tomsani" },
  { nume: "Făcăi", simplu: "Facai", comuna: "Ocnele Mari" },
  { nume: "Fârtățești", simplu: "Fartatesti" },
  { nume: "Făurești", simplu: "Fauresti" },
  { nume: "Făurești", simplu: "Fauresti", comuna: "Zatreni" },
  { nume: "Fedeleșoiu", simplu: "Fedelesoiu", comuna: "Daesti" },
  { nume: "Fețeni", simplu: "Feteni", comuna: "Ramnicu Valcea" },
  { nume: "Firești", simplu: "Firesti", comuna: "Bunesti" },
  { nume: "Firijba", comuna: "Popesti" },
  { nume: "Fișcălia", simplu: "Fiscalia", comuna: "Ionesti" },
  { nume: "Foleștii de Jos", simplu: "Folestii de Jos", comuna: "Tomsani" },
  { nume: "Foleștii de Sus", simplu: "Folestii de Sus", comuna: "Tomsani" },
  { nume: "Fotești", simplu: "Fotesti", comuna: "Ionesti" },
  { nume: "Frâncești-Coasta", simplu: "Francesti-Coasta", comuna: "Muereasca" },
  { nume: "Frâncești", simplu: "Francesti" },
  { nume: "Frăsina", simplu: "Frasina", comuna: "Roesti" },
  { nume: "Fumureni", comuna: "Lungesti" },
  { nume: "Fundătura", simplu: "Fundatura", comuna: "Vladesti" },
  { nume: "Găgeni", simplu: "Gageni", comuna: "Ladesti" },
  { nume: "Găinești", simplu: "Gainesti", comuna: "Fauresti" },
  { nume: "Galicea" },
  { nume: "Gâltofani", simplu: "Galtofani", comuna: "Nicolae Balcescu" },
  { nume: "Gănești", simplu: "Ganesti", comuna: "Zatreni" },
  { nume: "Gănțulei", simplu: "Gantulei", comuna: "Lungesti" },
  { nume: "Gârnicet", simplu: "Garnicet", comuna: "Fartatesti" },
  { nume: "Gârnicetu", simplu: "Garnicetu", comuna: "Stanesti" },
  { nume: "Gătejești", simplu: "Gatejesti", comuna: "Baile Govora" },
  { nume: "Găujani", simplu: "Gaujani", comuna: "Boisoara" },
  { nume: "Găvănești", simplu: "Gavanesti", comuna: "Muereasca" },
  { nume: "Geamăna", simplu: "Geamana", comuna: "Dragoesti" },
  { nume: "Geamăna", simplu: "Geamana", comuna: "Stoilesti" },
  { nume: "Genuneni", comuna: "Francesti" },
  { nume: "Ghindari", comuna: "Lalosu" },
  { nume: "Ghiobești", simplu: "Ghiobesti", comuna: "Stoilesti" },
  { nume: "Ghioroiu" },
  { nume: "Gibești", simplu: "Gibesti", comuna: "Golesti" },
  { nume: "Ginerica", comuna: "Nicolae Balcescu" },
  { nume: "Giulești", simplu: "Giulesti", comuna: "Fartatesti" },
  {
    nume: "Giuleștii de Sus",
    simplu: "Giulestii de Sus",
    comuna: "Fartatesti",
  },
  { nume: "Giurgiuveni", comuna: "Golesti" },
  { nume: "Giuroiu", comuna: "Stoilesti" },
  { nume: "Glăvile", simplu: "Glavile" },
  { nume: "Glodu", comuna: "Danicei" },
  { nume: "Golotreni", comuna: "Brezoi" },
  { nume: "Goranu", comuna: "Ramnicu Valcea" },
  { nume: "Gorunești", simplu: "Gorunesti", comuna: "Balcesti" },
  { nume: "Gorunești", simplu: "Gorunesti", comuna: "Slatioara" },
  { nume: "Govora", comuna: "Mihaesti" },
  { nume: "Grădiștea", simplu: "Gradistea" },
  { nume: "Greblești", simplu: "Greblesti", comuna: "Caineni" },
  { nume: "Greci", comuna: "Mateesti" },
  { nume: "Gropeni", comuna: "Runcu" },
  { nume: "Groși", simplu: "Grosi", comuna: "Cernisoara" },
  { nume: "Gruieri", comuna: "Stoenesti" },
  { nume: "Gruiu Lupului", comuna: "Racovita" },
  { nume: "Gruiu", comuna: "Stoenesti" },
  { nume: "Guguianca", comuna: "Ionesti" },
  { nume: "Gura Crucilor", comuna: "Danicei" },
  { nume: "Gura Suhașului", simplu: "Gura Suhasului", comuna: "Ocnele Mari" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Bujoreni" },
  { nume: "Gurguiata", comuna: "Baile Olanesti" },
  { nume: "Gurișoara", simplu: "Gurisoara", comuna: "Mihaesti" },
  { nume: "Gușoeni", simplu: "Gusoeni" },
  { nume: "Gușoianca", simplu: "Gusoianca", comuna: "Gusoeni" },
  { nume: "Herăști", simplu: "Herasti", comuna: "Ghioroiu" },
  { nume: "Horezu" },
  { nume: "Hotărasa", simplu: "Hotarasa", comuna: "Copaceni" },
  { nume: "Hotarele", comuna: "Muereasca" },
  { nume: "Hotăroaia", simplu: "Hotaroaia", comuna: "Rosiile" },
  { nume: "Iacovile", comuna: "Madulari" },
  { nume: "Ifrimești", simplu: "Ifrimesti", comuna: "Horezu" },
  { nume: "Igoiu", comuna: "Alunu" },
  { nume: "Ilaciu", comuna: "Alunu" },
  { nume: "Ionești", simplu: "Ionesti" },
  { nume: "Irimești", simplu: "Irimesti", comuna: "Balcesti" },
  { nume: "Izbăsești", simplu: "Izbasesti", comuna: "Milcoiu" },
  { nume: "Izvorașu", simplu: "Izvorasu", comuna: "Sutesti" },
  { nume: "Izvoru Rece", comuna: "Stoilesti" },
  { nume: "Izvoru Rece", comuna: "Vaideeni" },
  { nume: "Izvoru", comuna: "Creteni" },
  { nume: "Jaroștea", simplu: "Jarostea", comuna: "Glavile" },
  { nume: "Jiblea Nouă", simplu: "Jiblea Noua", comuna: "Calimanesti" },
  { nume: "Jiblea Veche", comuna: "Calimanesti" },
  { nume: "Lăcusteni", simplu: "Lacusteni", comuna: "Zatreni" },
  { nume: "Lăcustenii de Jos", simplu: "Lacustenii de Jos", comuna: "Zatreni" },
  { nume: "Lăcustenii de Sus", simplu: "Lacustenii de Sus", comuna: "Zatreni" },
  { nume: "Lădești", simplu: "Ladesti" },
  { nume: "Laloșu", simplu: "Lalosu" },
  { nume: "Lăunele de Jos", simplu: "Launele de Jos", comuna: "Danicei" },
  { nume: "Lespezi", comuna: "Ramnicu Valcea" },
  { nume: "Linia Dealului", comuna: "Stanesti" },
  { nume: "Linia Hanului", comuna: "Nicolae Balcescu" },
  { nume: "Linia pe Vale", comuna: "Danicei" },
  { nume: "Linia", comuna: "Budesti" },
  { nume: "Linia", comuna: "Gradistea" },
  { nume: "Livadia", comuna: "Baile Olanesti" },
  { nume: "Livezi" },
  { nume: "Lunca", comuna: "Bujoreni" },
  { nume: "Lunca", comuna: "Ocnele Mari" },
  { nume: "Lungești", simplu: "Lungesti" },
  { nume: "Lupoaia", comuna: "Pesceana" },
  { nume: "Lupuiești", simplu: "Lupuiesti", comuna: "Rosiile" },
  { nume: "Măciuceni", simplu: "Maciuceni", comuna: "Maciuca" },
  { nume: "Mădulari", simplu: "Madulari" },
  { nume: "Mădulari", simplu: "Madulari", comuna: "Cernisoara" },
  { nume: "Măgura", simplu: "Magura", comuna: "Mihaesti" },
  { nume: "Măgureni", simplu: "Magureni", comuna: "Gusoeni" },
  { nume: "Malaia" },
  { nume: "Măldărești", simplu: "Maldaresti" },
  { nume: "Măldărești", simplu: "Maldaresti", comuna: "Ladesti" },
  { nume: "Măldărești", simplu: "Maldaresti", comuna: "Maciuca" },
  {
    nume: "Măldăreștii de Jos",
    simplu: "Maldarestii de Jos",
    comuna: "Maldaresti",
  },
  { nume: "Malu Alb", comuna: "Bujoreni" },
  { nume: "Malu Vârtop", simplu: "Malu Vartop", comuna: "Bujoreni" },
  { nume: "Malu", comuna: "Stoilesti" },
  { nume: "Mamu", comuna: "Madulari" },
  { nume: "Mănăilești", simplu: "Manailesti", comuna: "Francesti" },
  { nume: "Măneasa", simplu: "Maneasa", comuna: "Tetoiu" },
  { nume: "Mângureni", simplu: "Mangureni", comuna: "Nicolae Balcescu" },
  { nume: "Mănicea", simplu: "Manicea", comuna: "Zatreni" },
  { nume: "Marcea", comuna: "Ionesti" },
  { nume: "Mărcușu", simplu: "Marcusu", comuna: "Fauresti" },
  { nume: "Mărgineni", simplu: "Margineni", comuna: "Valea Mare" },
  { nume: "Măricești", simplu: "Maricesti", comuna: "Fartatesti" },
  { nume: "Marița", simplu: "Marita", comuna: "Vaideeni" },
  { nume: "Mateești", simplu: "Mateesti" },
  { nume: "Măzăraru", simplu: "Mazararu", comuna: "Nicolae Balcescu" },
  { nume: "Măzili", simplu: "Mazili", comuna: "Sutesti" },
  { nume: "Mecea", comuna: "Zatreni" },
  { nume: "Meieni", comuna: "Popesti" },
  { nume: "Mereșești", simplu: "Meresesti", comuna: "Amarasti" },
  { nume: "Mierea", comuna: "Ghioroiu" },
  { nume: "Mihăești", simplu: "Mihaesti" },
  { nume: "Mijați", simplu: "Mijati", comuna: "Lapusata" },
  { nume: "Mijlocu", comuna: "Sinesti" },
  { nume: "Milcoiu" },
  { nume: "Milești", simplu: "Milesti", comuna: "Fauresti" },
  { nume: "Milostea", comuna: "Slatioara" },
  { nume: "Mirești", simplu: "Miresti", comuna: "Tomsani" },
  { nume: "Mitrofani", comuna: "Sutesti" },
  { nume: "Mlăceni", simplu: "Mlaceni", comuna: "Perisani" },
  { nume: "Modoia", comuna: "Cernisoara" },
  { nume: "Mogești", simplu: "Mogesti", comuna: "Slatioara" },
  { nume: "Mogoșești", simplu: "Mogosesti", comuna: "Stoenesti" },
  { nume: "Mologești", simplu: "Mologesti", comuna: "Lalosu" },
  { nume: "Moșoroașa", simplu: "Mosoroasa", comuna: "Baile Olanesti" },
  { nume: "Moșteni", simplu: "Mosteni", comuna: "Francesti" },
  { nume: "Mrenești", simplu: "Mrenesti", comuna: "Creteni" },
  { nume: "Muereasca de Sus", comuna: "Muereasca" },
  { nume: "Muereasca" },
  { nume: "Munteni", comuna: "Mihaesti" },
  { nume: "Neghinești", simplu: "Neghinesti", comuna: "Stoenesti" },
  { nume: "Negraia", comuna: "Pesceana" },
  { nume: "Negreni", comuna: "Mihaesti" },
  { nume: "Negrulești", simplu: "Negrulesti", comuna: "Barbatesti" },
  { nume: "Nemoiu", comuna: "Amarasti" },
  { nume: "Nenciulești", simplu: "Nenciulesti", comuna: "Tetoiu" },
  { nume: "Nețești", simplu: "Netesti", comuna: "Stoilesti" },
  { nume: "Nicolești", simplu: "Nicolesti", comuna: "Olanu" },
  { nume: "Nisipi", comuna: "Fartatesti" },
  { nume: "Obârșia", simplu: "Obarsia", comuna: "Cernisoara" },
  { nume: "Obislavu", comuna: "Gradistea" },
  { nume: "Obogeni", comuna: "Stoilesti" },
  { nume: "Obrocești", simplu: "Obrocesti", comuna: "Stroesti" },
  { nume: "Ocnița", simplu: "Ocnita", comuna: "Ocnele Mari" },
  { nume: "Ocracu", comuna: "Alunu" },
  { nume: "Olănești", simplu: "Olanesti", comuna: "Baile Olanesti" },
  { nume: "Olanu" },
  { nume: "Olteanca", comuna: "Glavile" },
  { nume: "Olteanca", comuna: "Ladesti" },
  { nume: "Olteni", comuna: "Bujoreni" },
  { nume: "Oltețani", simplu: "Oltetani", comuna: "Lalosu" },
  { nume: "Oltețu", simplu: "Oltetu", comuna: "Zatreni" },
  { nume: "Opătești", simplu: "Opatesti", comuna: "Golesti" },
  { nume: "Orlești", simplu: "Orlesti" },
  { nume: "Ostroveni", comuna: "Galicea" },
  { nume: "Oteșani", simplu: "Otesani" },
  { nume: "Otetelișu", simplu: "Otetelisu", comuna: "Balcesti" },
  { nume: "Oveselu", comuna: "Maciuca" },
  { nume: "Padina", comuna: "Amarasti" },
  { nume: "Pădurețu", simplu: "Paduretu", comuna: "Babeni" },
  { nume: "Palanga", comuna: "Amarasti" },
  { nume: "Pârâienii de Jos", simplu: "Paraienii de Jos", comuna: "Livezi" },
  {
    nume: "Pârâienii de Mijloc",
    simplu: "Paraienii de Mijloc",
    comuna: "Livezi",
  },
  { nume: "Pârâienii de Sus", simplu: "Paraienii de Sus", comuna: "Livezi" },
  { nume: "Părăușani", simplu: "Parausani", comuna: "Livezi" },
  { nume: "Păsărei", simplu: "Pasarei", comuna: "Rosiile" },
  { nume: "Păscoaia", simplu: "Pascoaia", comuna: "Brezoi" },
  { nume: "Păsculești", simplu: "Pasculesti", comuna: "Ladesti" },
  { nume: "Pătești", simplu: "Patesti", comuna: "Salatrucel" },
  { nume: "Păușa", simplu: "Pausa", comuna: "Calimanesti" },
  { nume: "Păușești-Măglași", simplu: "Pausesti-Maglasi" },
  { nume: "Păusești-Otăsău", simplu: "Pausesti-Otasau", comuna: "Pausesti" },
  { nume: "Păușești", simplu: "Pausesti" },
  { nume: "Perișani", simplu: "Perisani" },
  { nume: "Pertești", simplu: "Pertesti", comuna: "Rosiile" },
  { nume: "Pesceana" },
  { nume: "Pietrari" },
  { nume: "Pietrari", comuna: "Pausesti-Maglasi" },
  { nume: "Pietrarii de Sus", comuna: "Pietrari" },
  { nume: "Pietreni", comuna: "Costesti" },
  { nume: "Pietrișu", simplu: "Pietrisu", comuna: "Baile Olanesti" },
  { nume: "Pietroasa", comuna: "Valea Mare" },
  { nume: "Piscu Mare", comuna: "Stoenesti" },
  { nume: "Piscu Pietrei", comuna: "Budesti" },
  { nume: "Piscu Scoarței", simplu: "Piscu Scoartei", comuna: "Roesti" },
  { nume: "Pleașa", simplu: "Pleasa", comuna: "Vladesti" },
  { nume: "Plesești", simplu: "Plesesti", comuna: "Rosiile" },
  { nume: "Pleșoiu", simplu: "Plesoiu", comuna: "Livezi" },
  { nume: "Pleșoiu", simplu: "Plesoiu", comuna: "Nicolae Balcescu" },
  { nume: "Podeni", comuna: "Perisani" },
  { nume: "Poenari", comuna: "Ramnicu Valcea" },
  { nume: "Poenița", simplu: "Poenita", comuna: "Golesti" },
  { nume: "Poiana", comuna: "Perisani" },
  { nume: "Poienari", comuna: "Ghioroiu" },
  { nume: "Pojogi-Cerna", comuna: "Stroesti" },
  { nume: "Popești", simplu: "Popesti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Fartatesti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Golesti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Ladesti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Maciuca" },
  { nume: "Popești", simplu: "Popesti", comuna: "Nicolae Balcescu" },
  { nume: "Popești", simplu: "Popesti", comuna: "Sinesti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Stoenesti" },
  { nume: "Popești", simplu: "Popesti", comuna: "Tetoiu" },
  { nume: "Portărești", simplu: "Portaresti", comuna: "Lalosu" },
  { nume: "Prajila", comuna: "Baile Govora" },
  { nume: "Predești", simplu: "Predesti", comuna: "Nicolae Balcescu" },
  { nume: "Preotești", simplu: "Preotesti", comuna: "Balcesti" },
  { nume: "Priba", comuna: "Ramnicu Valcea" },
  { nume: "Priloage", comuna: "Caineni" },
  { nume: "Pripoara", comuna: "Muereasca" },
  { nume: "Pripoare", comuna: "Perisani" },
  { nume: "Priporu", comuna: "Vladesti" },
  { nume: "Procopoaia", comuna: "Orlesti" },
  { nume: "Prodănești", simplu: "Prodanesti", comuna: "Ionesti" },
  { nume: "Proieni", comuna: "Brezoi" },
  { nume: "Prundeni" },
  { nume: "Racovița", simplu: "Racovita" },
  { nume: "Racovița", simplu: "Racovita", comuna: "Budesti" },
  { nume: "Racu", comuna: "Sutesti" },
  { nume: "Rădăcinești", simplu: "Radacinesti", comuna: "Berislavesti" },
  { nume: "Râmești", simplu: "Ramesti", comuna: "Horezu" },
  { nume: "Râmești", simplu: "Ramesti", comuna: "Susani" },
  { nume: "Râmnicu Vâlcea", simplu: "Ramnicu Valcea" },
  { nume: "Râpa Cărămizii", simplu: "Rapa Caramizii", comuna: "Roesti" },
  { nume: "Râpănești", simplu: "Rapanesti", comuna: "Bunesti" },
  { nume: "Rățălești", simplu: "Ratalesti", comuna: "Rosiile" },
  { nume: "Râu Vadului", simplu: "Rau Vadului", comuna: "Caineni" },
  { nume: "Râureni", simplu: "Raureni", comuna: "Ramnicu Valcea" },
  { nume: "Robaia", comuna: "Berislavesti" },
  { nume: "Robești", simplu: "Robesti", comuna: "Caineni" },
  { nume: "Roești", simplu: "Roesti" },
  { nume: "Roești", simplu: "Roesti", comuna: "Pesceana" },
  { nume: "Românești", simplu: "Romanesti", comuna: "Rosiile" },
  { nume: "Români", simplu: "Romani", comuna: "Babeni" },
  { nume: "Romanii de Jos", comuna: "Horezu" },
  { nume: "Romanii de Sus", comuna: "Horezu" },
  { nume: "Roșia", simplu: "Rosia", comuna: "Alunu" },
  { nume: "Roșiile", simplu: "Rosiile" },
  { nume: "Roșioara", simplu: "Rosioara", comuna: "Berbesti" },
  { nume: "Roșoveni", simplu: "Rosoveni", comuna: "Maldaresti" },
  { nume: "Rotărăști", simplu: "Rotarasti", comuna: "Nicolae Balcescu" },
  { nume: "Ruda", comuna: "Budesti" },
  { nume: "Rugetu", comuna: "Mihaesti" },
  { nume: "Rugetu", comuna: "Slatioara" },
  { nume: "Runcu" },
  { nume: "Rusănești", simplu: "Rusanesti", comuna: "Fartatesti" },
  { nume: "Saioci", comuna: "Roesti" },
  { nume: "Sălătrucel", simplu: "Salatrucel" },
  { nume: "Săliștea", simplu: "Salistea", comuna: "Malaia" },
  { nume: "Săliștea", simplu: "Salistea", comuna: "Ramnicu Valcea" },
  { nume: "Sânbotin", simplu: "Sanbotin", comuna: "Daesti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Susani" },
  { nume: "Sărsănești", simplu: "Sarsanesti", comuna: "Cernisoara" },
  { nume: "Sărulești", simplu: "Sarulesti", comuna: "Lapusata" },
  { nume: "Sășcioara", simplu: "Sascioara", comuna: "Zatreni" },
  { nume: "Satu Poieni", comuna: "Balcesti" },
  { nume: "Scaioși", simplu: "Scaiosi", comuna: "Orlesti" },
  { nume: "Scărișoara", simplu: "Scarisoara", comuna: "Mihaesti" },
  { nume: "Scăueni", simplu: "Scaueni", comuna: "Berislavesti" },
  { nume: "Schitu", comuna: "Nicolae Balcescu" },
  { nume: "Scorușu", simplu: "Scorusu", comuna: "Lapusata" },
  { nume: "Scundu" },
  { nume: "Seaca", comuna: "Calimanesti" },
  { nume: "Seaca", comuna: "Salatrucel" },
  { nume: "Seciu", comuna: "Fartatesti" },
  { nume: "Șerbăneasa", simplu: "Serbaneasa", comuna: "Nicolae Balcescu" },
  { nume: "Șerbănești", simplu: "Serbanesti", comuna: "Lapusata" },
  { nume: "Șerbănești", simplu: "Serbanesti", comuna: "Pausesti" },
  { nume: "Șerbănești", simplu: "Serbanesti", comuna: "Salatrucel" },
  { nume: "Șerbănești", simplu: "Serbanesti", comuna: "Stefanesti" },
  { nume: "Silea", comuna: "Orlesti" },
  { nume: "Sinești", simplu: "Sinesti" },
  { nume: "Șirineasa", simplu: "Sirineasa" },
  { nume: "Slătioara", simplu: "Slatioara" },
  { nume: "Slătioarele", simplu: "Slatioarele", comuna: "Ocnele Mari" },
  { nume: "Slăvitești", simplu: "Slavitesti", comuna: "Sirineasa" },
  { nume: "Snamăna", simplu: "Snamana", comuna: "Runcu" },
  { nume: "Șolicești", simplu: "Solicesti", comuna: "Pausesti" },
  { nume: "Șotani", simplu: "Sotani", comuna: "Fartatesti" },
  { nume: "Spârleni", simplu: "Sparleni", comuna: "Gusoeni" },
  { nume: "Spinu", comuna: "Perisani" },
  { nume: "Stănculești", simplu: "Stanculesti", comuna: "Fartatesti" },
  { nume: "Stănești-Lunca", simplu: "Stanesti-Lunca", comuna: "Lungesti" },
  { nume: "Stănești", simplu: "Stanesti" },
  { nume: "Stănești", simplu: "Stanesti", comuna: "Stoilesti" },
  { nume: "Stanomiru", comuna: "Zatreni" },
  { nume: "Ștefănești", simplu: "Stefanesti" },
  { nume: "Ștefănești", simplu: "Stefanesti", comuna: "Maciuca" },
  { nume: "Știrbești", simplu: "Stirbesti", comuna: "Ghioroiu" },
  { nume: "Stoenești", simplu: "Stoenesti" },
  { nume: "Stoenești", simplu: "Stoenesti", comuna: "Berislavesti" },
  { nume: "Stoicănești", simplu: "Stoicanesti", comuna: "Olanu" },
  { nume: "Stoiculești", simplu: "Stoiculesti", comuna: "Susani" },
  { nume: "Stoilești", simplu: "Stoilesti" },
  { nume: "Stolniceni", comuna: "Ramnicu Valcea" },
  { nume: "Străchinești", simplu: "Strachinesti", comuna: "Gradistea" },
  { nume: "Streminoasa", comuna: "Creteni" },
  { nume: "Stroești", simplu: "Stroesti" },
  { nume: "Stupărei", simplu: "Stuparei", comuna: "Mihaesti" },
  { nume: "Sub Deal", comuna: "Otesani" },
  { nume: "Suiești", simplu: "Suiesti", comuna: "Stanesti" },
  { nume: "Surdoiu", comuna: "Perisani" },
  { nume: "Șuricaru", simplu: "Suricaru", comuna: "Milcoiu" },
  { nume: "Surpatele", comuna: "Francesti" },
  { nume: "Surpați", simplu: "Surpati", comuna: "Runcu" },
  { nume: "Șușani", simplu: "Susani" },
  { nume: "Suseni", comuna: "Stoenesti" },
  { nume: "Șuta", simplu: "Suta", comuna: "Muereasca" },
  { nume: "Sutești", simplu: "Sutesti" },
  { nume: "Tănăsești", simplu: "Tanasesti", comuna: "Horezu" },
  { nume: "Tanislavi", comuna: "Fartatesti" },
  { nume: "Târgu Gângulești", simplu: "Targu Gangulesti", comuna: "Berbesti" },
  { nume: "Tătărani", simplu: "Tatarani", comuna: "Babeni" },
  { nume: "Țeica", simplu: "Teica", comuna: "Ocnele Mari" },
  { nume: "Teiu", comuna: "Galicea" },
  { nume: "Teiul", comuna: "Amarasti" },
  { nume: "Teiușu", simplu: "Teiusu", comuna: "Bunesti" },
  { nume: "Telechești", simplu: "Telechesti", comuna: "Maldaresti" },
  { nume: "Țepești", simplu: "Tepesti", comuna: "Tetoiu" },
  { nume: "Tepșenari", simplu: "Tepsenari", comuna: "Milcoiu" },
  { nume: "Tetoiu" },
  { nume: "Tighina", comuna: "Voicesti" },
  { nume: "Tina", comuna: "Livezi" },
  { nume: "Tisa", comuna: "Baile Olanesti" },
  { nume: "Titești", simplu: "Titesti" },
  { nume: "Titireci", comuna: "Bunesti" },
  { nume: "Tomșani", simplu: "Tomsani" },
  { nume: "Troian", comuna: "Ramnicu Valcea" },
  { nume: "Trundin", comuna: "Vladesti" },
  { nume: "Tufanii", comuna: "Nicolae Balcescu" },
  { nume: "Tulei-Câmpeni", simplu: "Tulei-Campeni", comuna: "Golesti" },
  { nume: "Turburea", comuna: "Gradistea" },
  { nume: "Turcești", simplu: "Turcesti", comuna: "Mateesti" },
  { nume: "Tuțulești", simplu: "Tutulesti", comuna: "Racovita" },
  { nume: "Țuțuru", simplu: "Tuturu", comuna: "Gradistea" },
  { nume: "Udrești", simplu: "Udresti", comuna: "Danicei" },
  { nume: "Ulmețel", simplu: "Ulmetel", comuna: "Pausesti-Maglasi" },
  { nume: "Ulmetu", comuna: "Copaceni" },
  { nume: "Urșani", simplu: "Ursani", comuna: "Horezu" },
  { nume: "Urși", simplu: "Ursi", comuna: "Popesti" },
  { nume: "Urși", simplu: "Ursi", comuna: "Stoilesti" },
  { nume: "Ursoaia", comuna: "Pesceana" },
  { nume: "Urzica", comuna: "Sinesti" },
  { nume: "Ușurei", simplu: "Usurei", comuna: "Susani" },
  { nume: "Vaideeni" },
  { nume: "Valea Alunișului", simplu: "Valea Alunisului", comuna: "Sirineasa" },
  { nume: "Valea Babei", comuna: "Runcu" },
  {
    nume: "Valea Bălcească",
    simplu: "Valea Balceasca",
    comuna: "Nicolae Balcescu",
  },
  { nume: "Valea Caselor", comuna: "Dragasani" },
  { nume: "Valea Caselor", comuna: "Popesti" },
  { nume: "Valea Cheii", comuna: "Pausesti-Maglasi" },
  { nume: "Valea Grădiștei", simplu: "Valea Gradistei", comuna: "Gradistea" },
  { nume: "Valea lui Stan", comuna: "Brezoi" },
  { nume: "Valea Lungă", simplu: "Valea Lunga", comuna: "Stanesti" },
  { nume: "Valea Măceșului", simplu: "Valea Macesului", comuna: "Voineasa" },
  { nume: "Valea Mare" },
  { nume: "Valea Mare", comuna: "Babeni" },
  { nume: "Valea Mare", comuna: "Berbesti" },
  { nume: "Valea Râului", simplu: "Valea Raului", comuna: "Galicea" },
  { nume: "Valea Scheiului", comuna: "Danicei" },
  { nume: "Valea Ursului", comuna: "Fartatesti" },
  { nume: "Valea Văleni", simplu: "Valea Valeni", comuna: "Zatreni" },
  { nume: "Valea Viei", comuna: "Nicolae Balcescu" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Pausesti" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Zatreni" },
  { nume: "Vărateci", simplu: "Varateci", comuna: "Runcu" },
  { nume: "Văratica", simplu: "Varatica", comuna: "Brezoi" },
  { nume: "Văratici", simplu: "Varatici", comuna: "Costesti" },
  { nume: "Vârleni", simplu: "Varleni", comuna: "Stanesti" },
  { nume: "Vătășești", simplu: "Vatasesti", comuna: "Golesti" },
  { nume: "Verdea", comuna: "Sutesti" },
  { nume: "Vețelu", simplu: "Vetelu", comuna: "Copaceni" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Francesti" },
  { nume: "Vlădești", simplu: "Vladesti" },
  { nume: "Vlăduceni", simplu: "Vladuceni", comuna: "Pausesti-Maglasi" },
  { nume: "Vlădulești", simplu: "Vladulesti", comuna: "Stoilesti" },
  { nume: "Voicești", simplu: "Voicesti" },
  {
    nume: "Voiceștii din Vale",
    simplu: "Voicestii din Vale",
    comuna: "Voicesti",
  },
  { nume: "Voiculeasa", comuna: "Glavile" },
  { nume: "Voineasa" },
  { nume: "Voineșița", simplu: "Voinesita", comuna: "Voineasa" },
  { nume: "Vulpuești", simplu: "Vulpuesti", comuna: "Mihaesti" },
  { nume: "Zărneni", simplu: "Zarneni", comuna: "Dragasani" },
  { nume: "Zărnești", simplu: "Zarnesti", comuna: "Lapusata" },
  { nume: "Zătreni", simplu: "Zatreni" },
  { nume: "Zătrenii de Sus", simplu: "Zatrenii de Sus", comuna: "Zatreni" },
  { nume: "Zăvideni", simplu: "Zavideni", comuna: "Prundeni" },
  { nume: "Zăvoieni", simplu: "Zavoieni", comuna: "Maciuca" },
  { nume: "Zgubea", comuna: "Rosiile" },
  { nume: "Zlătărei", simplu: "Zlatarei", comuna: "Dragasani" },
  { nume: "Zmeurătu", simplu: "Zmeuratu", comuna: "Stoenesti" },
];
