export const vn = [
  { nume: "Adjud" },
  { nume: "Adjudu Vechi", comuna: "Adjud" },
  {
    nume: "Alexandru Vlahuță",
    simplu: "Alexandru Vlahuta",
    comuna: "Dumbraveni",
  },
  { nume: "Andreiașu de Jos", simplu: "Andreiasu de Jos" },
  {
    nume: "Andreiașu de Sus",
    simplu: "Andreiasu de Sus",
    comuna: "Andreiasu De Jos",
  },
  { nume: "Anghelești", simplu: "Anghelesti", comuna: "Ruginesti" },
  { nume: "Argea", comuna: "Ploscuteni" },
  { nume: "Armeni", comuna: "Slobozia Ciorasti" },
  { nume: "Arșița", simplu: "Arsita", comuna: "Andreiasu De Jos" },
  { nume: "Arva", comuna: "Brosteni" },
  { nume: "Bahnele", comuna: "Vintileasca" },
  { nume: "Bălănești", simplu: "Balanesti", comuna: "Gura Calitei" },
  { nume: "Bălești", simplu: "Balesti" },
  { nume: "Balta Raței", simplu: "Balta Ratei", comuna: "Vanatori" },
  { nume: "Bârsești", simplu: "Barsesti" },
  { nume: "Bâtcari", simplu: "Batcari", comuna: "Nistoresti" },
  { nume: "Bătinești", simplu: "Batinesti", comuna: "Tifesti" },
  { nume: "Beciu", comuna: "Vartescoiu" },
  { nume: "Belciugele", comuna: "Maicanesti" },
  { nume: "Biceștii de Jos", simplu: "Bicestii de Jos", comuna: "Dumitresti" },
  { nume: "Biceștii de Sus", simplu: "Bicestii de Sus", comuna: "Dumitresti" },
  { nume: "Bichești", simplu: "Bichesti", comuna: "Boghesti" },
  { nume: "Biliești", simplu: "Biliesti", comuna: "Suraia" },
  { nume: "Bizighești", simplu: "Bizighesti", comuna: "Garoafa" },
  { nume: "Blidari", comuna: "Carligele" },
  { nume: "Blidari", comuna: "Dumitresti" },
  { nume: "Bodești", simplu: "Bodesti", comuna: "Vrancioaia" },
  { nume: "Boghești", simplu: "Boghesti" },
  { nume: "Bogheștii de Sus", simplu: "Boghestii de Sus", comuna: "Boghesti" },
  { nume: "Bogza", comuna: "Sihlea" },
  { nume: "Bolotești", simplu: "Bolotesti" },
  { nume: "Bonțești", simplu: "Bontesti", comuna: "Carligele" },
  { nume: "Bordeasca Nouă", simplu: "Bordeasca Noua", comuna: "Tataranu" },
  { nume: "Bordeasca Veche", comuna: "Tataranu" },
  { nume: "Bordești", simplu: "Bordesti" },
  { nume: "Bordeștii de Jos", simplu: "Bordestii de Jos", comuna: "Bordesti" },
  { nume: "Boțârlău", simplu: "Botarlau", comuna: "Vulturu" },
  { nume: "Brădăcești", simplu: "Bradacesti", comuna: "Nereju" },
  { nume: "Brădetu", simplu: "Bradetu", comuna: "Nistoresti" },
  { nume: "Broșteni", simplu: "Brosteni" },
  { nume: "Buda", comuna: "Corbita" },
  { nume: "Budești", simplu: "Budesti", comuna: "Cotesti" },
  { nume: "Burca", comuna: "Vidra" },
  { nume: "Burcioaia", comuna: "Adjud" },
  { nume: "Căiata", simplu: "Caiata", comuna: "Sihlea" },
  { nume: "Călienii Noi", simplu: "Calienii Noi", comuna: "Nanesti" },
  { nume: "Călienii Vechi", simplu: "Calienii Vechi", comuna: "Nanesti" },
  { nume: "Călimăneasa", simplu: "Calimaneasa", comuna: "Tanasoaia" },
  { nume: "Călimănești", simplu: "Calimanesti", comuna: "Marasesti" },
  { nume: "Câmpineanca", simplu: "Campineanca" },
  { nume: "Câmpuri", simplu: "Campuri" },
  { nume: "Cândești", simplu: "Candesti", comuna: "Dumbraveni" },
  { nume: "Cârligele", simplu: "Carligele" },
  {
    nume: "Carșochești-Corăbița",
    simplu: "Carsochesti-Corabita",
    comuna: "Paltin",
  },
  { nume: "Cătăuți", simplu: "Catauti", comuna: "Chiojdeni" },
  { nume: "Ceardac", comuna: "Golesti" },
  { nume: "Cerbu", comuna: "Jitia" },
  { nume: "Chiojdeni" },
  { nume: "Chiricani", comuna: "Nereju" },
  { nume: "Chițcani", simplu: "Chitcani", comuna: "Boghesti" },
  { nume: "Ciolănești", simplu: "Ciolanesti", comuna: "Fitionesti" },
  { nume: "Ciorani", comuna: "Pufesti" },
  { nume: "Ciorăști", simplu: "Ciorasti" },
  { nume: "Ciușlea", simplu: "Ciuslea", comuna: "Garoafa" },
  { nume: "Clipicești", simplu: "Clipicesti", comuna: "Tifesti" },
  { nume: "Cocoșari", simplu: "Cocosari", comuna: "Gura Calitei" },
  { nume: "Codrești", simplu: "Codresti", comuna: "Ciorasti" },
  { nume: "Colacu", comuna: "Valea Sarii" },
  { nume: "Copăcești", simplu: "Copacesti", comuna: "Ruginesti" },
  { nume: "Corbița", simplu: "Corbita" },
  { nume: "Cornetu", comuna: "Slobozia Bradului" },
  { nume: "Coroteni", comuna: "Slobozia Bradului" },
  { nume: "Costișa de Sus", simplu: "Costisa de Sus", comuna: "Tanasoaia" },
  { nume: "Costișa", simplu: "Costisa", comuna: "Homocea" },
  { nume: "Costișa", simplu: "Costisa", comuna: "Tanasoaia" },
  { nume: "Cotești", simplu: "Cotesti" },
  { nume: "Covrag", comuna: "Tanasoaia" },
  { nume: "Coza", comuna: "Tulnici" },
  { nume: "Crucea de Jos", comuna: "Panciu" },
  { nume: "Crucea de Sus", comuna: "Panciu" },
  { nume: "Dălhăuți", simplu: "Dalhauti", comuna: "Carligele" },
  { nume: "Dealu Cucului", comuna: "Poiana Cristei" },
  { nume: "Dealu Sării", simplu: "Dealu Sarii", comuna: "Jitia" },
  { nume: "Dealul Lung", comuna: "Gura Calitei" },
  { nume: "Diochețirediu", simplu: "Diochetirediu", comuna: "Movilita" },
  { nume: "Doaga", comuna: "Garoafa" },
  { nume: "Domnești-Sat", simplu: "Domnesti-Sat", comuna: "Pufesti" },
  { nume: "Domnești-Târg", simplu: "Domnesti-Targ", comuna: "Pufesti" },
  { nume: "Dragosloveni", comuna: "Dumbraveni" },
  { nume: "Dragosloveni", comuna: "Soveja" },
  { nume: "Dumbrava", comuna: "Panciu" },
  { nume: "Dumbrava", comuna: "Poiana Cristei" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni" },
  { nume: "Dumitrești", simplu: "Dumitresti" },
  {
    nume: "Dumitreștii de Sus",
    simplu: "Dumitrestii de Sus",
    comuna: "Dumitresti",
  },
  {
    nume: "Dumitreștii-Față",
    simplu: "Dumitrestii-Fata",
    comuna: "Dumitresti",
  },
  { nume: "După Măgura", simplu: "Dupa Magura", comuna: "Vintileasca" },
  { nume: "Făgetu", simplu: "Fagetu", comuna: "Nistoresti" },
  { nume: "Faraoanele", comuna: "Vartescoiu" },
  { nume: "Farcaș", simplu: "Farcas", comuna: "Reghiu" },
  { nume: "Făurei", simplu: "Faurei", comuna: "Garoafa" },
  { nume: "Feldioara", comuna: "Tanasoaia" },
  { nume: "Fetești", simplu: "Fetesti", comuna: "Campuri" },
  { nume: "Fetig", comuna: "Andreiasu De Jos" },
  { nume: "Fitionești", simplu: "Fitionesti" },
  { nume: "Focșani", simplu: "Focsani" },
  { nume: "Frecăței", simplu: "Frecatei", comuna: "Movilita" },
  { nume: "Găgești", simplu: "Gagesti", comuna: "Bolotesti" },
  { nume: "Galbeni", comuna: "Tanasoaia" },
  { nume: "Găloiești", simplu: "Galoiesti", comuna: "Dumitresti" },
  { nume: "Garoafa" },
  { nume: "Ghebari", comuna: "Paltin" },
  { nume: "Ghimicești", simplu: "Ghimicesti", comuna: "Fitionesti" },
  { nume: "Gogoiu", comuna: "Racoasa" },
  { nume: "Golești", simplu: "Golesti" },
  { nume: "Goleștii de Sus", simplu: "Golestii de Sus", comuna: "Cotesti" },
  { nume: "Gologanu", comuna: "Milcovul" },
  { nume: "Gresu", comuna: "Tulnici" },
  { nume: "Groapa Tufei", comuna: "Gura Calitei" },
  { nume: "Gugești", simplu: "Gugesti" },
  { nume: "Gura Caliței", simplu: "Gura Calitei" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Campuri" },
  { nume: "Hângulești", simplu: "Hangulesti", comuna: "Vulturu" },
  { nume: "Haret", comuna: "Marasesti" },
  { nume: "Hăulișca", simplu: "Haulisca", comuna: "Paulesti" },
  { nume: "Holbănești", simplu: "Holbanesti", comuna: "Fitionesti" },
  { nume: "Homocea" },
  { nume: "Hotaru", comuna: "Andreiasu De Jos" },
  { nume: "Igești", simplu: "Igesti", comuna: "Tifesti" },
  { nume: "Irești", simplu: "Iresti", comuna: "Vidra" },
  { nume: "Iugani", comuna: "Boghesti" },
  { nume: "Ivăncești", simplu: "Ivancesti", comuna: "Bolotesti" },
  { nume: "Izvoarele", comuna: "Corbita" },
  { nume: "Jariștea", simplu: "Jaristea" },
  { nume: "Jgheaburi", comuna: "Reghiu" },
  { nume: "Jiliște", simplu: "Jiliste", comuna: "Slobozia Ciorasti" },
  { nume: "Jitia de Jos", comuna: "Jitia" },
  { nume: "Jitia" },
  { nume: "Jorăști", simplu: "Jorasti", comuna: "Vanatori" },
  { nume: "Lacu lui Baban", comuna: "Gura Calitei" },
  { nume: "Lămotești", simplu: "Lamotesti", comuna: "Milcovul" },
  { nume: "Lărgășeni", simplu: "Largaseni", comuna: "Corbita" },
  { nume: "Lăstuni", simplu: "Lastuni", comuna: "Dumitresti" },
  { nume: "Lepșa", simplu: "Lepsa", comuna: "Tulnici" },
  { nume: "Lespezi", comuna: "Homocea" },
  { nume: "Liești", simplu: "Liesti", comuna: "Slobozia Bradului" },
  { nume: "Livada", comuna: "Mera" },
  { nume: "Livezile", comuna: "Vizantea-Livezi" },
  { nume: "Lojnița", simplu: "Lojnita", comuna: "Chiojdeni" },
  { nume: "Luncile", comuna: "Chiojdeni" },
  { nume: "Lupoaia", comuna: "Dumitresti" },
  { nume: "Măgura", simplu: "Magura", comuna: "Jitia" },
  { nume: "Mahriu", comuna: "Poiana Cristei" },
  { nume: "Măicănești", simplu: "Maicanesti" },
  { nume: "Maluri", comuna: "Vulturu" },
  { nume: "Mănăstioara", simplu: "Manastioara", comuna: "Fitionesti" },
  { nume: "Mândrești-Moldova", simplu: "Mandresti-Moldova", comuna: "Focsani" },
  { nume: "Mândrești-Munteni", simplu: "Mandresti-Munteni", comuna: "Focsani" },
  { nume: "Mărăcini", simplu: "Maracini", comuna: "Chiojdeni" },
  { nume: "Mărășești", simplu: "Marasesti" },
  { nume: "Mărăști", simplu: "Marasti", comuna: "Racoasa" },
  { nume: "Mărtinești", simplu: "Martinesti", comuna: "Tataranu" },
  { nume: "Mătăcina", simplu: "Matacina", comuna: "Valea Sarii" },
  { nume: "Mera" },
  { nume: "Mesteacănu", simplu: "Mesteacanu", comuna: "Vizantea-Livezi" },
  { nume: "Mihălceni", simplu: "Mihalceni", comuna: "Ciorasti" },
  { nume: "Milcovel", comuna: "Mera" },
  { nume: "Milcovul" },
  { nume: "Mirceștii Noi", simplu: "Mircestii Noi", comuna: "Vanatori" },
  { nume: "Mirceștii Vechi", simplu: "Mircestii Vechi", comuna: "Vanatori" },
  { nume: "Modruzeni", comuna: "Marasesti" },
  { nume: "Morărești", simplu: "Moraresti", comuna: "Paltin" },
  { nume: "Motnău", simplu: "Motnau", comuna: "Dumitresti" },
  { nume: "Movilița", simplu: "Movilita" },
  { nume: "Muncei", comuna: "Vrancioaia" },
  { nume: "Muncelu", comuna: "Straoane" },
  { nume: "Nănești", simplu: "Nanesti" },
  { nume: "Nănești", simplu: "Nanesti", comuna: "Tanasoaia" },
  { nume: "Năruja", simplu: "Naruja" },
  { nume: "Neculele", comuna: "Vintileasca" },
  { nume: "Negrilești", simplu: "Negrilesti" },
  { nume: "Neicu", comuna: "Panciu" },
  { nume: "Nereju Mic", comuna: "Nereju" },
  { nume: "Nereju" },
  { nume: "Nistorești", simplu: "Nistoresti" },
  { nume: "Obrejița", simplu: "Obrejita", comuna: "Tamboesti" },
  { nume: "Ocheșești", simplu: "Ochesesti", comuna: "Corbita" },
  { nume: "Odobasca", comuna: "Poiana Cristei" },
  { nume: "Odobești", simplu: "Odobesti" },
  { nume: "Olăreni", simplu: "Olareni", comuna: "Slobozia Bradului" },
  { nume: "Oleșești", simplu: "Olesesti", comuna: "Tifesti" },
  { nume: "Olteni", comuna: "Vartescoiu" },
  { nume: "Oreavu", comuna: "Gugesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Jaristea" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Marasesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Tamboesti" },
  { nume: "Paltin" },
  { nume: "Panciu" },
  { nume: "Pătrășcani", simplu: "Patrascani", comuna: "Tifesti" },
  { nume: "Păulești", simplu: "Paulesti" },
  { nume: "Păunești", simplu: "Paunesti" },
  { nume: "Păvălari", simplu: "Pavalari", comuna: "Paltin" },
  { nume: "Petreanu", comuna: "Poiana Cristei" },
  { nume: "Petrești", simplu: "Petresti", comuna: "Vanatori" },
  { nume: "Pietroasa", comuna: "Bolotesti" },
  { nume: "Pietroasa", comuna: "Campineanca" },
  { nume: "Pietroasa", comuna: "Tamboesti" },
  { nume: "Pietroasa", comuna: "Vartescoiu" },
  { nume: "Piscu Radului", comuna: "Vizantea-Livezi" },
  { nume: "Piscu Reghiului", comuna: "Reghiu" },
  { nume: "Pitulușa", simplu: "Pitulusa", comuna: "Brosteni" },
  { nume: "Plăcințeni", simplu: "Placinteni", comuna: "Boghesti" },
  { nume: "Pleșești", simplu: "Plesesti", comuna: "Boghesti" },
  { nume: "Plopu", comuna: "Gura Calitei" },
  { nume: "Ploscuțeni", simplu: "Ploscuteni" },
  { nume: "Ploștina", simplu: "Plostina", comuna: "Vrancioaia" },
  { nume: "Podu Lacului", comuna: "Poiana Cristei" },
  { nume: "Podu Nărujei", simplu: "Podu Narujei", comuna: "Naruja" },
  { nume: "Podu Șchiopului", simplu: "Podu Schiopului", comuna: "Nistoresti" },
  { nume: "Podu Stoica", comuna: "Naruja" },
  { nume: "Poduri", comuna: "Valea Sarii" },
  { nume: "Podurile", comuna: "Chiojdeni" },
  { nume: "Poenile", comuna: "Gura Calitei" },
  { nume: "Poiana Cristei" },
  { nume: "Poiana Stoichii", comuna: "Vintileasca" },
  { nume: "Poiana", comuna: "Vrancioaia" },
  { nume: "Poienița", simplu: "Poienita", comuna: "Dumitresti" },
  { nume: "Popești", simplu: "Popesti" },
  { nume: "Prahuda", comuna: "Paltin" },
  { nume: "Precistanu", comuna: "Garoafa" },
  { nume: "Prisaca", comuna: "Valea Sarii" },
  { nume: "Prisecani", comuna: "Boghesti" },
  { nume: "Pufești", simplu: "Pufesti" },
  { nume: "Putna", comuna: "Bolotesti" },
  { nume: "Răchitașu", simplu: "Rachitasu", comuna: "Andreiasu De Jos" },
  { nume: "Răchitosu", simplu: "Rachitosu", comuna: "Garoafa" },
  { nume: "Răcoasa", simplu: "Racoasa" },
  { nume: "Rădăcinești", simplu: "Radacinesti", comuna: "Corbita" },
  { nume: "Rădulești", simplu: "Radulesti", comuna: "Vanatori" },
  { nume: "Răiuți", simplu: "Raiuti", comuna: "Reghiu" },
  { nume: "Râmniceanca", simplu: "Ramniceanca", comuna: "Vartescoiu" },
  { nume: "Râmniceni", simplu: "Ramniceni", comuna: "Maicanesti" },
  { nume: "Rașca", simplu: "Rasca", comuna: "Gura Calitei" },
  { nume: "Răstoaca", simplu: "Rastoaca", comuna: "Milcovul" },
  { nume: "Rebegari", comuna: "Naruja" },
  { nume: "Reghiu" },
  { nume: "Repedea", comuna: "Straoane" },
  { nume: "Romănești", simplu: "Romanesti", comuna: "Nistoresti" },
  { nume: "Roșcari", simplu: "Roscari", comuna: "Dumitresti" },
  { nume: "Roșioara", simplu: "Rosioara", comuna: "Mera" },
  { nume: "Rotileștii Mari", simplu: "Rotilestii Mari", comuna: "Campuri" },
  { nume: "Rotileștii Mici", simplu: "Rotilestii Mici", comuna: "Campuri" },
  { nume: "Rucăreni", simplu: "Rucareni", comuna: "Soveja" },
  { nume: "Ruget", comuna: "Vidra" },
  { nume: "Ruginești", simplu: "Ruginesti" },
  { nume: "Sahastru", comuna: "Nereju" },
  { nume: "Salcia Nouă", simplu: "Salcia Noua", comuna: "Ciorasti" },
  { nume: "Salcia Veche", comuna: "Ciorasti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Tifesti" },
  { nume: "Satu Nou", comuna: "Ciorasti" },
  { nume: "Satu Nou", comuna: "Panciu" },
  { nume: "Scafari", comuna: "Vidra" },
  { nume: "Scânteia", simplu: "Scanteia", comuna: "Jaristea" },
  { nume: "Seciu", comuna: "Chiojdeni" },
  { nume: "Șerbănești", simplu: "Serbanesti", comuna: "Corbita" },
  { nume: "Șerbești", simplu: "Serbesti", comuna: "Vidra" },
  { nume: "Sihlea" },
  { nume: "Siminoc", comuna: "Dumitresti" },
  { nume: "Șindrilari", simplu: "Sindrilari", comuna: "Reghiu" },
  { nume: "Siretu", comuna: "Marasesti" },
  { nume: "Șișcani", simplu: "Siscani", comuna: "Adjud" },
  { nume: "Slimnic", comuna: "Tamboesti" },
  {
    nume: "Slobozia Botești",
    simplu: "Slobozia Botesti",
    comuna: "Maicanesti",
  },
  { nume: "Slobozia Bradului" },
  { nume: "Slobozia Ciorăști", simplu: "Slobozia Ciorasti" },
  { nume: "Șotârcari", simplu: "Sotarcari", comuna: "Gura Calitei" },
  { nume: "Spătăreasa", simplu: "Spatareasa", comuna: "Ciorasti" },
  { nume: "Spinești", simplu: "Spinesti", comuna: "Vrancioaia" },
  { nume: "Spulber", comuna: "Paltin" },
  { nume: "Străjescu", simplu: "Strajescu", comuna: "Garoafa" },
  { nume: "Străoane", simplu: "Straoane" },
  { nume: "Stupina", comuna: "Maicanesti" },
  { nume: "Suraia" },
  { nume: "Tăbucești", simplu: "Tabucesti", comuna: "Boghesti" },
  { nume: "Tâmboești", simplu: "Tamboesti" },
  { nume: "Tănăsari", simplu: "Tanasari", comuna: "Vintileasca" },
  { nume: "Tănăsoaia", simplu: "Tanasoaia" },
  { nume: "Târâtu", simplu: "Taratu", comuna: "Poiana Cristei" },
  { nume: "Tătăranu", simplu: "Tataranu" },
  { nume: "Tătaru", simplu: "Tataru", comuna: "Maicanesti" },
  { nume: "Țepa", simplu: "Tepa", comuna: "Paltin" },
  { nume: "Terchești", simplu: "Terchesti", comuna: "Popesti" },
  { nume: "Tichiriș", simplu: "Tichiris", comuna: "Vidra" },
  { nume: "Țifești", simplu: "Tifesti" },
  { nume: "Tinoasa", comuna: "Dumitresti" },
  { nume: "Țipău", simplu: "Tipau", comuna: "Paltin" },
  { nume: "Tișița", simplu: "Tisita", comuna: "Marasesti" },
  { nume: "Titila", comuna: "Andreiasu De Jos" },
  { nume: "Tojanii de Jos", comuna: "Paltin" },
  { nume: "Tojanii de Sus", comuna: "Paltin" },
  { nume: "Topești", simplu: "Topesti", comuna: "Barsesti" },
  { nume: "Trestia", comuna: "Dumitresti" },
  { nume: "Trestieni", comuna: "Tamboesti" },
  { nume: "Trotușanu", simplu: "Trotusanu", comuna: "Movilita" },
  { nume: "Tulburea", comuna: "Chiojdeni" },
  { nume: "Tulnici" },
  { nume: "Tuțu", simplu: "Tutu", comuna: "Corbita" },
  { nume: "Ungureni", comuna: "Nistoresti" },
  { nume: "Unirea", comuna: "Odobesti" },
  { nume: "Urechești", simplu: "Urechesti" },
  { nume: "Ursoaia", comuna: "Reghiu" },
  { nume: "Vadu Roșca", simplu: "Vadu Rosca", comuna: "Vulturu" },
  { nume: "Vâjâitoarea", simplu: "Vajaitoarea", comuna: "Tataranu" },
  { nume: "Vâlcani", simplu: "Valcani", comuna: "Paltin" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Campineanca" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Corbita" },
  { nume: "Valea Beciului", comuna: "Slobozia Bradului" },
  { nume: "Valea Cotești", simplu: "Valea Cotesti", comuna: "Cotesti" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Dumitresti" },
  { nume: "Valea Milcovului", comuna: "Reghiu" },
  { nume: "Valea Neagră", simplu: "Valea Neagra", comuna: "Nistoresti" },
  { nume: "Valea Sării", simplu: "Valea Sarii" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Movilita" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Ruginesti" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Straoane" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Varnița", simplu: "Varnita", comuna: "Racoasa" },
  { nume: "Vărsătura", simplu: "Varsatura", comuna: "Jaristea" },
  { nume: "Vârteșcoiu", simplu: "Vartescoiu" },
  { nume: "Verdea", comuna: "Racoasa" },
  {
    nume: "Vetrești-Herăstrău",
    simplu: "Vetresti-Herastrau",
    comuna: "Nistoresti",
  },
  { nume: "Vidra" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Paunesti" },
  { nume: "Viișoara", simplu: "Viisoara", comuna: "Vidra" },
  { nume: "Vintileasca" },
  { nume: "Vitănești", simplu: "Vitanesti", comuna: "Tifesti" },
  {
    nume: "Vităneștii de Sub Măgură",
    simplu: "Vitanestii de Sub Magura",
    comuna: "Bolotesti",
  },
  {
    nume: "Vizantea Mănăstirească",
    simplu: "Vizantea Manastireasca",
    comuna: "Vizantea-Livezi",
  },
  {
    nume: "Vizantea Răzășească",
    simplu: "Vizantea Razaseasca",
    comuna: "Vizantea-Livezi",
  },
  { nume: "Vladnicu de Jos", comuna: "Tanasoaia" },
  { nume: "Vladnicu de Sus", comuna: "Tanasoaia" },
  { nume: "Voetin", comuna: "Sihlea" },
  { nume: "Voloșcani", simplu: "Voloscani", comuna: "Vidra" },
  { nume: "Vrâncioaia", simplu: "Vrancioaia" },
  { nume: "Vulcăneasa", simplu: "Vulcaneasa", comuna: "Mera" },
  { nume: "Vulturu" },
];
