export const vl = [
  { nume: "Alunu" },
  { nume: "Amarasti" },
  { nume: "Berbesti" },
  { nume: "Berislavesti" },
  { nume: "Boisoara" },
  { nume: "Brezoi" },
  { nume: "Budesti" },
  { nume: "Bujoreni" },
  { nume: "Bunesti" },
  { nume: "Babeni" },
  { nume: "Balcesti" },
  { nume: "Barbatesti" },
  { nume: "Cernisoara" },
  { nume: "Copaceni" },
  { nume: "Costesti" },
  { nume: "Creteni" },
  { nume: "Calimanesti" },
  { nume: "Dragoesti" },
  { nume: "Dragasani" },
  { nume: "Daesti" },
  { nume: "Francesti" },
  { nume: "Fartatesti" },
  { nume: "Fauresti" },
  { nume: "Galicea" },
  { nume: "Ghioroiu" },
  { nume: "Glavile" },
  { nume: "Gradistea" },
  { nume: "Gusoeni" },
  { nume: "Horezu" },
  { nume: "Ionesti" },
  { nume: "Lalosu" },
  { nume: "Livezi" },
  { nume: "Lungesti" },
  { nume: "Ladesti" },
  { nume: "Malaia" },
  { nume: "Mateesti" },
  { nume: "Mihaesti" },
  { nume: "Milcoiu" },
  { nume: "Muereasca" },
  { nume: "Madulari" },
  { nume: "Maldaresti" },
  { nume: "Olanu" },
  { nume: "Orlesti" },
  { nume: "Otesani" },
  { nume: "Perisani" },
  { nume: "Pesceana" },
  { nume: "Pietrari" },
  { nume: "Popesti" },
  { nume: "Prundeni" },
  { nume: "Pausesti" },
  { nume: "Pausesti-Maglasi" },
  { nume: "Racovita" },
  { nume: "Roesti" },
  { nume: "Rosiile" },
  { nume: "Runcu" },
  { nume: "Ramnicu Valcea" },
  { nume: "Scundu" },
  { nume: "Sinesti" },
  { nume: "Slatioara" },
  { nume: "Stoenesti" },
  { nume: "Stoilesti" },
  { nume: "Stroesti" },
  { nume: "Stanesti" },
  { nume: "Sutesti" },
  { nume: "Salatrucel" },
  { nume: "Tetoiu" },
  { nume: "Titesti" },
  { nume: "Tomsani" },
  { nume: "Vaideeni" },
  { nume: "Valea Mare" },
  { nume: "Vladesti" },
  { nume: "Voicesti" },
  { nume: "Voineasa" },
  { nume: "Zatreni" },
  { nume: "Sirineasa" },
  { nume: "Stefanesti" },
  { nume: "Susani" },
  { nume: "Bodesti", comuna: "Alunu" },
  { nume: "Coltesti", comuna: "Alunu" },
  { nume: "Igoiu", comuna: "Alunu" },
  { nume: "Ilaciu", comuna: "Alunu" },
  { nume: "Ocracu", comuna: "Alunu" },
  { nume: "Rosia", comuna: "Alunu" },
  { nume: "Meresesti", comuna: "Amarasti" },
  { nume: "Nemoiu", comuna: "Amarasti" },
  { nume: "Padina", comuna: "Amarasti" },
  { nume: "Palanga", comuna: "Amarasti" },
  { nume: "Teiul", comuna: "Amarasti" },
  { nume: "Bonciu", comuna: "Babeni" },
  { nume: "Capu Dealului", comuna: "Babeni" },
  { nume: "Paduretu", comuna: "Babeni" },
  { nume: "Romani", comuna: "Babeni" },
  { nume: "Tatarani", comuna: "Babeni" },
  { nume: "Valea Mare", comuna: "Babeni" },
  { nume: "Curaturile", comuna: "Baile Govora" },
  { nume: "Gatejesti", comuna: "Baile Govora" },
  { nume: "Prajila", comuna: "Baile Govora" },
  { nume: "Cheia", comuna: "Baile Olanesti" },
  { nume: "Comanca", comuna: "Baile Olanesti" },
  { nume: "Gurguiata", comuna: "Baile Olanesti" },
  { nume: "Livadia", comuna: "Baile Olanesti" },
  { nume: "Mosoroasa", comuna: "Baile Olanesti" },
  { nume: "Olanesti", comuna: "Baile Olanesti" },
  { nume: "Pietrisu", comuna: "Baile Olanesti" },
  { nume: "Tisa", comuna: "Baile Olanesti" },
  { nume: "Benesti", comuna: "Balcesti" },
  { nume: "Chirculesti", comuna: "Balcesti" },
  { nume: "Carlogani", comuna: "Balcesti" },
  { nume: "Gorunesti", comuna: "Balcesti" },
  { nume: "Irimesti", comuna: "Balcesti" },
  { nume: "Otetelisu", comuna: "Balcesti" },
  { nume: "Preotesti", comuna: "Balcesti" },
  { nume: "Satu Poieni", comuna: "Balcesti" },
  { nume: "Bodesti", comuna: "Barbatesti" },
  { nume: "Barzesti", comuna: "Barbatesti" },
  { nume: "Negrulesti", comuna: "Barbatesti" },
  { nume: "Dealu Alunis", comuna: "Berbesti" },
  { nume: "Damteni", comuna: "Berbesti" },
  { nume: "Rosioara", comuna: "Berbesti" },
  { nume: "Targu Gangulesti", comuna: "Berbesti" },
  { nume: "Valea Mare", comuna: "Berbesti" },
  { nume: "Bradisor", comuna: "Berislavesti" },
  { nume: "Dangesti", comuna: "Berislavesti" },
  { nume: "Robaia", comuna: "Berislavesti" },
  { nume: "Radacinesti", comuna: "Berislavesti" },
  { nume: "Scaueni", comuna: "Berislavesti" },
  { nume: "Stoenesti", comuna: "Berislavesti" },
  { nume: "Bumbuesti", comuna: "Boisoara" },
  { nume: "Gaujani", comuna: "Boisoara" },
  { nume: "Corbu", comuna: "Brezoi" },
  { nume: "Calinesti", comuna: "Brezoi" },
  { nume: "Draganesti", comuna: "Brezoi" },
  { nume: "Golotreni", comuna: "Brezoi" },
  { nume: "Proieni", comuna: "Brezoi" },
  { nume: "Pascoaia", comuna: "Brezoi" },
  { nume: "Valea lui Stan", comuna: "Brezoi" },
  { nume: "Varatica", comuna: "Brezoi" },
  { nume: "Barza", comuna: "Budesti" },
  { nume: "Bercioiu", comuna: "Budesti" },
  { nume: "Barsesti", comuna: "Budesti" },
  { nume: "Linia", comuna: "Budesti" },
  { nume: "Piscu Pietrei", comuna: "Budesti" },
  { nume: "Racovita", comuna: "Budesti" },
  { nume: "Ruda", comuna: "Budesti" },
  { nume: "Bogdanesti", comuna: "Bujoreni" },
  { nume: "Gura Vaii", comuna: "Bujoreni" },
  { nume: "Lunca", comuna: "Bujoreni" },
  { nume: "Malu Alb", comuna: "Bujoreni" },
  { nume: "Malu Vartop", comuna: "Bujoreni" },
  { nume: "Olteni", comuna: "Bujoreni" },
  { nume: "Coasta Mare", comuna: "Bunesti" },
  { nume: "Firesti", comuna: "Bunesti" },
  { nume: "Rapanesti", comuna: "Bunesti" },
  { nume: "Teiusu", comuna: "Bunesti" },
  { nume: "Titireci", comuna: "Bunesti" },
  { nume: "Cainenii Mari", comuna: "Caineni" },
  { nume: "Cainenii Mici", comuna: "Caineni" },
  { nume: "Greblesti", comuna: "Caineni" },
  { nume: "Priloage", comuna: "Caineni" },
  { nume: "Robesti", comuna: "Caineni" },
  { nume: "Rau Vadului", comuna: "Caineni" },
  { nume: "Caciulata", comuna: "Calimanesti" },
  { nume: "Jiblea Noua", comuna: "Calimanesti" },
  { nume: "Jiblea Veche", comuna: "Calimanesti" },
  { nume: "Pausa", comuna: "Calimanesti" },
  { nume: "Seaca", comuna: "Calimanesti" },
  { nume: "Armasesti", comuna: "Cernisoara" },
  { nume: "Grosi", comuna: "Cernisoara" },
  { nume: "Modoia", comuna: "Cernisoara" },
  { nume: "Madulari", comuna: "Cernisoara" },
  { nume: "Obarsia", comuna: "Cernisoara" },
  { nume: "Sarsanesti", comuna: "Cernisoara" },
  { nume: "Bondoci", comuna: "Copaceni" },
  { nume: "Balteni", comuna: "Copaceni" },
  { nume: "Hotarasa", comuna: "Copaceni" },
  { nume: "Ulmetu", comuna: "Copaceni" },
  { nume: "Vetelu", comuna: "Copaceni" },
  { nume: "Bistrita", comuna: "Costesti" },
  { nume: "Pietreni", comuna: "Costesti" },
  { nume: "Varatici", comuna: "Costesti" },
  { nume: "Izvoru", comuna: "Creteni" },
  { nume: "Mrenesti", comuna: "Creteni" },
  { nume: "Streminoasa", comuna: "Creteni" },
  { nume: "Babuesti", comuna: "Daesti" },
  { nume: "Fedelesoiu", comuna: "Daesti" },
  { nume: "Sanbotin", comuna: "Daesti" },
  { nume: "Badeni", comuna: "Danicei" },
  { nume: "Ceretu", comuna: "Danicei" },
  { nume: "Ciresul", comuna: "Danicei" },
  { nume: "Dealu Launele", comuna: "Danicei" },
  { nume: "Dealu Scheiului", comuna: "Danicei" },
  { nume: "Dobresti", comuna: "Danicei" },
  { nume: "Dragulesti", comuna: "Danicei" },
  { nume: "Glodu", comuna: "Danicei" },
  { nume: "Gura Crucilor", comuna: "Danicei" },
  { nume: "Linia pe Vale", comuna: "Danicei" },
  { nume: "Launele de Jos", comuna: "Danicei" },
  { nume: "Udresti", comuna: "Danicei" },
  { nume: "Valea Scheiului", comuna: "Danicei" },
  { nume: "Valea Caselor", comuna: "Dragasani" },
  { nume: "Zlatarei", comuna: "Dragasani" },
  { nume: "Zarneni", comuna: "Dragasani" },
  { nume: "Buciumeni", comuna: "Dragoesti" },
  { nume: "Geamana", comuna: "Dragoesti" },
  { nume: "Afanata", comuna: "Fartatesti" },
  { nume: "Becsani", comuna: "Fartatesti" },
  { nume: "Cuci", comuna: "Fartatesti" },
  { nume: "Catetu", comuna: "Fartatesti" },
  { nume: "Dejoi", comuna: "Fartatesti" },
  { nume: "Dozesti", comuna: "Fartatesti" },
  { nume: "Dancai", comuna: "Fartatesti" },
  { nume: "Giulesti", comuna: "Fartatesti" },
  { nume: "Giulestii de Sus", comuna: "Fartatesti" },
  { nume: "Garnicet", comuna: "Fartatesti" },
  { nume: "Maricesti", comuna: "Fartatesti" },
  { nume: "Nisipi", comuna: "Fartatesti" },
  { nume: "Popesti", comuna: "Fartatesti" },
  { nume: "Rusanesti", comuna: "Fartatesti" },
  { nume: "Seciu", comuna: "Fartatesti" },
  { nume: "Stanculesti", comuna: "Fartatesti" },
  { nume: "Tanislavi", comuna: "Fartatesti" },
  { nume: "Valea Ursului", comuna: "Fartatesti" },
  { nume: "Sotani", comuna: "Fartatesti" },
  { nume: "Budesti", comuna: "Fauresti" },
  { nume: "Bungetani", comuna: "Fauresti" },
  { nume: "Babeni-Oltetu", comuna: "Fauresti" },
  { nume: "Colelia", comuna: "Fauresti" },
  { nume: "Diculesti", comuna: "Fauresti" },
  { nume: "Gainesti", comuna: "Fauresti" },
  { nume: "Milesti", comuna: "Fauresti" },
  { nume: "Marcusu", comuna: "Fauresti" },
  { nume: "Balutoaia", comuna: "Francesti" },
  { nume: "Cosani", comuna: "Francesti" },
  { nume: "Dezrobiti", comuna: "Francesti" },
  { nume: "Genuneni", comuna: "Francesti" },
  { nume: "Mosteni", comuna: "Francesti" },
  { nume: "Manailesti", comuna: "Francesti" },
  { nume: "Surpatele", comuna: "Francesti" },
  { nume: "Viisoara", comuna: "Francesti" },
  { nume: "Bratia din Deal", comuna: "Galicea" },
  { nume: "Bratia din Vale", comuna: "Galicea" },
  { nume: "Cocoru", comuna: "Galicea" },
  { nume: "Cremenari", comuna: "Galicea" },
  { nume: "Dealu Mare", comuna: "Galicea" },
  { nume: "Ostroveni", comuna: "Galicea" },
  { nume: "Teiu", comuna: "Galicea" },
  { nume: "Valea Raului", comuna: "Galicea" },
  { nume: "Cazanesti", comuna: "Ghioroiu" },
  { nume: "Herasti", comuna: "Ghioroiu" },
  { nume: "Mierea", comuna: "Ghioroiu" },
  { nume: "Poienari", comuna: "Ghioroiu" },
  { nume: "Stirbesti", comuna: "Ghioroiu" },
  { nume: "Aninoasa", comuna: "Glavile" },
  { nume: "Jarostea", comuna: "Glavile" },
  { nume: "Olteanca", comuna: "Glavile" },
  { nume: "Voiculeasa", comuna: "Glavile" },
  { nume: "Aldesti", comuna: "Golesti" },
  { nume: "Blidari", comuna: "Golesti" },
  { nume: "Coasta", comuna: "Golesti" },
  { nume: "Draganesti", comuna: "Golesti" },
  { nume: "Gibesti", comuna: "Golesti" },
  { nume: "Giurgiuveni", comuna: "Golesti" },
  { nume: "Opatesti", comuna: "Golesti" },
  { nume: "Poenita", comuna: "Golesti" },
  { nume: "Popesti", comuna: "Golesti" },
  { nume: "Tulei-Campeni", comuna: "Golesti" },
  { nume: "Vatasesti", comuna: "Golesti" },
  { nume: "Diaconesti", comuna: "Gradistea" },
  { nume: "Dobricea", comuna: "Gradistea" },
  { nume: "Linia", comuna: "Gradistea" },
  { nume: "Obislavu", comuna: "Gradistea" },
  { nume: "Strachinesti", comuna: "Gradistea" },
  { nume: "Turburea", comuna: "Gradistea" },
  { nume: "Valea Gradistei", comuna: "Gradistea" },
  { nume: "Tuturu", comuna: "Gradistea" },
  { nume: "Burdalesti", comuna: "Gusoeni" },
  { nume: "Dealu Mare", comuna: "Gusoeni" },
  { nume: "Gusoianca", comuna: "Gusoeni" },
  { nume: "Magureni", comuna: "Gusoeni" },
  { nume: "Sparleni", comuna: "Gusoeni" },
  { nume: "Ifrimesti", comuna: "Horezu" },
  { nume: "Romanii de Jos", comuna: "Horezu" },
  { nume: "Romanii de Sus", comuna: "Horezu" },
  { nume: "Ramesti", comuna: "Horezu" },
  { nume: "Tanasesti", comuna: "Horezu" },
  { nume: "Ursani", comuna: "Horezu" },
  { nume: "Bucsani", comuna: "Ionesti" },
  { nume: "Dealu Mare", comuna: "Ionesti" },
  { nume: "Delureni", comuna: "Ionesti" },
  { nume: "Fiscalia", comuna: "Ionesti" },
  { nume: "Fotesti", comuna: "Ionesti" },
  { nume: "Guguianca", comuna: "Ionesti" },
  { nume: "Marcea", comuna: "Ionesti" },
  { nume: "Prodanesti", comuna: "Ionesti" },
  { nume: "Cermegesti", comuna: "Ladesti" },
  { nume: "Chiricesti", comuna: "Ladesti" },
  { nume: "Ciumagi", comuna: "Ladesti" },
  { nume: "Dealu Corni", comuna: "Ladesti" },
  { nume: "Gageni", comuna: "Ladesti" },
  { nume: "Maldaresti", comuna: "Ladesti" },
  { nume: "Olteanca", comuna: "Ladesti" },
  { nume: "Popesti", comuna: "Ladesti" },
  { nume: "Pasculesti", comuna: "Ladesti" },
  { nume: "Berbesti", comuna: "Lalosu" },
  { nume: "Ghindari", comuna: "Lalosu" },
  { nume: "Mologesti", comuna: "Lalosu" },
  { nume: "Oltetani", comuna: "Lalosu" },
  { nume: "Portaresti", comuna: "Lalosu" },
  { nume: "Beresti", comuna: "Lapusata" },
  { nume: "Brosteni", comuna: "Lapusata" },
  { nume: "Mijati", comuna: "Lapusata" },
  { nume: "Scorusu", comuna: "Lapusata" },
  { nume: "Sarulesti", comuna: "Lapusata" },
  { nume: "Zarnesti", comuna: "Lapusata" },
  { nume: "Serbanesti", comuna: "Lapusata" },
  { nume: "Plesoiu", comuna: "Livezi" },
  { nume: "Paraienii de Jos", comuna: "Livezi" },
  { nume: "Paraienii de Mijloc", comuna: "Livezi" },
  { nume: "Paraienii de Sus", comuna: "Livezi" },
  { nume: "Parausani", comuna: "Livezi" },
  { nume: "Tina", comuna: "Livezi" },
  { nume: "Carcadiesti", comuna: "Lungesti" },
  { nume: "Dumbrava", comuna: "Lungesti" },
  { nume: "Fumureni", comuna: "Lungesti" },
  { nume: "Gantulei", comuna: "Lungesti" },
  { nume: "Stanesti-Lunca", comuna: "Lungesti" },
  { nume: "Bocsa", comuna: "Maciuca" },
  { nume: "Botorani", comuna: "Maciuca" },
  { nume: "Ciocanari", comuna: "Maciuca" },
  { nume: "Maciuceni", comuna: "Maciuca" },
  { nume: "Maldaresti", comuna: "Maciuca" },
  { nume: "Oveselu", comuna: "Maciuca" },
  { nume: "Popesti", comuna: "Maciuca" },
  { nume: "Zavoieni", comuna: "Maciuca" },
  { nume: "Stefanesti", comuna: "Maciuca" },
  { nume: "Balsoara", comuna: "Madulari" },
  { nume: "Bantesti", comuna: "Madulari" },
  { nume: "Dimulesti", comuna: "Madulari" },
  { nume: "Iacovile", comuna: "Madulari" },
  { nume: "Mamu", comuna: "Madulari" },
  { nume: "Ciungetu", comuna: "Malaia" },
  { nume: "Salistea", comuna: "Malaia" },
  { nume: "Maldarestii de Jos", comuna: "Maldaresti" },
  { nume: "Rosoveni", comuna: "Maldaresti" },
  { nume: "Telechesti", comuna: "Maldaresti" },
  { nume: "Greci", comuna: "Mateesti" },
  { nume: "Turcesti", comuna: "Mateesti" },
  { nume: "Arsanca", comuna: "Mihaesti" },
  { nume: "Buleta", comuna: "Mihaesti" },
  { nume: "Barsesti", comuna: "Mihaesti" },
  { nume: "Govora", comuna: "Mihaesti" },
  { nume: "Gurisoara", comuna: "Mihaesti" },
  { nume: "Munteni", comuna: "Mihaesti" },
  { nume: "Magura", comuna: "Mihaesti" },
  { nume: "Negreni", comuna: "Mihaesti" },
  { nume: "Rugetu", comuna: "Mihaesti" },
  { nume: "Scarisoara", comuna: "Mihaesti" },
  { nume: "Stuparei", comuna: "Mihaesti" },
  { nume: "Vulpuesti", comuna: "Mihaesti" },
  { nume: "Ciutesti", comuna: "Milcoiu" },
  { nume: "Cazanesti", comuna: "Milcoiu" },
  { nume: "Izbasesti", comuna: "Milcoiu" },
  { nume: "Tepsenari", comuna: "Milcoiu" },
  { nume: "Suricaru", comuna: "Milcoiu" },
  { nume: "Andreiesti", comuna: "Muereasca" },
  { nume: "Francesti-Coasta", comuna: "Muereasca" },
  { nume: "Gavanesti", comuna: "Muereasca" },
  { nume: "Hotarele", comuna: "Muereasca" },
  { nume: "Muereasca de Sus", comuna: "Muereasca" },
  { nume: "Pripoara", comuna: "Muereasca" },
  { nume: "Suta", comuna: "Muereasca" },
  { nume: "Banesti", comuna: "Nicolae Balcescu" },
  { nume: "Corbii din Vale", comuna: "Nicolae Balcescu" },
  { nume: "Dosu Raului", comuna: "Nicolae Balcescu" },
  { nume: "Ginerica", comuna: "Nicolae Balcescu" },
  { nume: "Galtofani", comuna: "Nicolae Balcescu" },
  { nume: "Linia Hanului", comuna: "Nicolae Balcescu" },
  { nume: "Mangureni", comuna: "Nicolae Balcescu" },
  { nume: "Mazararu", comuna: "Nicolae Balcescu" },
  { nume: "Plesoiu", comuna: "Nicolae Balcescu" },
  { nume: "Popesti", comuna: "Nicolae Balcescu" },
  { nume: "Predesti", comuna: "Nicolae Balcescu" },
  { nume: "Rotarasti", comuna: "Nicolae Balcescu" },
  { nume: "Schitu", comuna: "Nicolae Balcescu" },
  { nume: "Tufanii", comuna: "Nicolae Balcescu" },
  { nume: "Valea Balceasca", comuna: "Nicolae Balcescu" },
  { nume: "Valea Viei", comuna: "Nicolae Balcescu" },
  { nume: "Serbaneasa", comuna: "Nicolae Balcescu" },
  { nume: "Buda", comuna: "Ocnele Mari" },
  { nume: "Cosota", comuna: "Ocnele Mari" },
  { nume: "Facai", comuna: "Ocnele Mari" },
  { nume: "Gura Suhasului", comuna: "Ocnele Mari" },
  { nume: "Lunca", comuna: "Ocnele Mari" },
  { nume: "Ocnita", comuna: "Ocnele Mari" },
  { nume: "Slatioarele", comuna: "Ocnele Mari" },
  { nume: "Teica", comuna: "Ocnele Mari" },
  { nume: "Casa Veche", comuna: "Olanu" },
  { nume: "Cioboti", comuna: "Olanu" },
  { nume: "Dragioiu", comuna: "Olanu" },
  { nume: "Nicolesti", comuna: "Olanu" },
  { nume: "Stoicanesti", comuna: "Olanu" },
  { nume: "Auresti", comuna: "Orlesti" },
  { nume: "Procopoaia", comuna: "Orlesti" },
  { nume: "Scaiosi", comuna: "Orlesti" },
  { nume: "Silea", comuna: "Orlesti" },
  { nume: "Bogdanesti", comuna: "Otesani" },
  { nume: "Cucesti", comuna: "Otesani" },
  { nume: "Carstanesti", comuna: "Otesani" },
  { nume: "Sub Deal", comuna: "Otesani" },
  { nume: "Barcanele", comuna: "Pausesti" },
  { nume: "Buzdugan", comuna: "Pausesti" },
  { nume: "Cernelele", comuna: "Pausesti" },
  { nume: "Pausesti-Otasau", comuna: "Pausesti" },
  { nume: "Valeni", comuna: "Pausesti" },
  { nume: "Serbanesti", comuna: "Pausesti" },
  { nume: "Solicesti", comuna: "Pausesti" },
  { nume: "Coasta", comuna: "Pausesti-Maglasi" },
  { nume: "Pietrari", comuna: "Pausesti-Maglasi" },
  { nume: "Ulmetel", comuna: "Pausesti-Maglasi" },
  { nume: "Valea Cheii", comuna: "Pausesti-Maglasi" },
  { nume: "Vladuceni", comuna: "Pausesti-Maglasi" },
  { nume: "Baiasu", comuna: "Perisani" },
  { nume: "Mlaceni", comuna: "Perisani" },
  { nume: "Podeni", comuna: "Perisani" },
  { nume: "Poiana", comuna: "Perisani" },
  { nume: "Pripoare", comuna: "Perisani" },
  { nume: "Spinu", comuna: "Perisani" },
  { nume: "Surdoiu", comuna: "Perisani" },
  { nume: "Cermegesti", comuna: "Pesceana" },
  { nume: "Lupoaia", comuna: "Pesceana" },
  { nume: "Negraia", comuna: "Pesceana" },
  { nume: "Roesti", comuna: "Pesceana" },
  { nume: "Ursoaia", comuna: "Pesceana" },
  { nume: "Pietrarii de Sus", comuna: "Pietrari" },
  { nume: "Curtea", comuna: "Popesti" },
  { nume: "Daesti", comuna: "Popesti" },
  { nume: "Firijba", comuna: "Popesti" },
  { nume: "Meieni", comuna: "Popesti" },
  { nume: "Ursi", comuna: "Popesti" },
  { nume: "Valea Caselor", comuna: "Popesti" },
  { nume: "Barbuceni", comuna: "Prundeni" },
  { nume: "Calina", comuna: "Prundeni" },
  { nume: "Zavideni", comuna: "Prundeni" },
  { nume: "Balota", comuna: "Racovita" },
  { nume: "Blanoiu", comuna: "Racovita" },
  { nume: "Bradu-Clocotici", comuna: "Racovita" },
  { nume: "Copaceni", comuna: "Racovita" },
  { nume: "Gruiu Lupului", comuna: "Racovita" },
  { nume: "Tutulesti", comuna: "Racovita" },
  { nume: "Aranghel", comuna: "Ramnicu Valcea" },
  { nume: "Copacelu", comuna: "Ramnicu Valcea" },
  { nume: "Cazanesti", comuna: "Ramnicu Valcea" },
  { nume: "Dealu Malului", comuna: "Ramnicu Valcea" },
  { nume: "Feteni", comuna: "Ramnicu Valcea" },
  { nume: "Goranu", comuna: "Ramnicu Valcea" },
  { nume: "Lespezi", comuna: "Ramnicu Valcea" },
  { nume: "Poenari", comuna: "Ramnicu Valcea" },
  { nume: "Priba", comuna: "Ramnicu Valcea" },
  { nume: "Raureni", comuna: "Ramnicu Valcea" },
  { nume: "Stolniceni", comuna: "Ramnicu Valcea" },
  { nume: "Salistea", comuna: "Ramnicu Valcea" },
  { nume: "Troian", comuna: "Ramnicu Valcea" },
  { nume: "Baiasa", comuna: "Roesti" },
  { nume: "Bajenari", comuna: "Roesti" },
  { nume: "Barbarigeni", comuna: "Roesti" },
  { nume: "Ciocaltei", comuna: "Roesti" },
  { nume: "Cueni", comuna: "Roesti" },
  { nume: "Frasina", comuna: "Roesti" },
  { nume: "Piscu Scoartei", comuna: "Roesti" },
  { nume: "Rapa Caramizii", comuna: "Roesti" },
  { nume: "Saioci", comuna: "Roesti" },
  { nume: "Balaciu", comuna: "Rosiile" },
  { nume: "Cherasti", comuna: "Rosiile" },
  { nume: "Hotaroaia", comuna: "Rosiile" },
  { nume: "Lupuiesti", comuna: "Rosiile" },
  { nume: "Pertesti", comuna: "Rosiile" },
  { nume: "Plesesti", comuna: "Rosiile" },
  { nume: "Pasarei", comuna: "Rosiile" },
  { nume: "Romanesti", comuna: "Rosiile" },
  { nume: "Ratalesti", comuna: "Rosiile" },
  { nume: "Zgubea", comuna: "Rosiile" },
  { nume: "Caligi", comuna: "Runcu" },
  { nume: "Gropeni", comuna: "Runcu" },
  { nume: "Snamana", comuna: "Runcu" },
  { nume: "Surpati", comuna: "Runcu" },
  { nume: "Valea Babei", comuna: "Runcu" },
  { nume: "Varateci", comuna: "Runcu" },
  { nume: "Patesti", comuna: "Salatrucel" },
  { nume: "Seaca", comuna: "Salatrucel" },
  { nume: "Serbanesti", comuna: "Salatrucel" },
  { nume: "Avramesti", comuna: "Scundu" },
  { nume: "Blejani", comuna: "Scundu" },
  { nume: "Crangu", comuna: "Scundu" },
  { nume: "Ciucheti", comuna: "Sinesti" },
  { nume: "Dealu Bisericii", comuna: "Sinesti" },
  { nume: "Mijlocu", comuna: "Sinesti" },
  { nume: "Popesti", comuna: "Sinesti" },
  { nume: "Urzica", comuna: "Sinesti" },
  { nume: "Aricioaia", comuna: "Sirineasa" },
  { nume: "Ciorasti", comuna: "Sirineasa" },
  { nume: "Slavitesti", comuna: "Sirineasa" },
  { nume: "Valea Alunisului", comuna: "Sirineasa" },
  { nume: "Coasta Cerbului", comuna: "Slatioara" },
  { nume: "Gorunesti", comuna: "Slatioara" },
  { nume: "Milostea", comuna: "Slatioara" },
  { nume: "Mogesti", comuna: "Slatioara" },
  { nume: "Rugetu", comuna: "Slatioara" },
  { nume: "Barcanesti", comuna: "Stanesti" },
  { nume: "Cioponesti", comuna: "Stanesti" },
  { nume: "Cuculesti", comuna: "Stanesti" },
  { nume: "Garnicetu", comuna: "Stanesti" },
  { nume: "Linia Dealului", comuna: "Stanesti" },
  { nume: "Suiesti", comuna: "Stanesti" },
  { nume: "Valea Lunga", comuna: "Stanesti" },
  { nume: "Varleni", comuna: "Stanesti" },
  { nume: "Condoiesti", comuna: "Stefanesti" },
  { nume: "Dobrusa", comuna: "Stefanesti" },
  { nume: "Serbanesti", comuna: "Stefanesti" },
  { nume: "Budurasti", comuna: "Stoenesti" },
  { nume: "Barlogu", comuna: "Stoenesti" },
  { nume: "Deleni", comuna: "Stoenesti" },
  { nume: "Dobriceni", comuna: "Stoenesti" },
  { nume: "Gruieri", comuna: "Stoenesti" },
  { nume: "Gruiu", comuna: "Stoenesti" },
  { nume: "Mogosesti", comuna: "Stoenesti" },
  { nume: "Neghinesti", comuna: "Stoenesti" },
  { nume: "Piscu Mare", comuna: "Stoenesti" },
  { nume: "Popesti", comuna: "Stoenesti" },
  { nume: "Suseni", comuna: "Stoenesti" },
  { nume: "Zmeuratu", comuna: "Stoenesti" },
  { nume: "Balomireasa", comuna: "Stoilesti" },
  { nume: "Bulagei", comuna: "Stoilesti" },
  { nume: "Barsoiu", comuna: "Stoilesti" },
  { nume: "Delureni", comuna: "Stoilesti" },
  { nume: "Geamana", comuna: "Stoilesti" },
  { nume: "Ghiobesti", comuna: "Stoilesti" },
  { nume: "Giuroiu", comuna: "Stoilesti" },
  { nume: "Izvoru Rece", comuna: "Stoilesti" },
  { nume: "Malu", comuna: "Stoilesti" },
  { nume: "Netesti", comuna: "Stoilesti" },
  { nume: "Obogeni", comuna: "Stoilesti" },
  { nume: "Stanesti", comuna: "Stoilesti" },
  { nume: "Ursi", comuna: "Stoilesti" },
  { nume: "Vladulesti", comuna: "Stoilesti" },
  { nume: "Ciresu", comuna: "Stroesti" },
  { nume: "Dianu", comuna: "Stroesti" },
  { nume: "Obrocesti", comuna: "Stroesti" },
  { nume: "Pojogi-Cerna", comuna: "Stroesti" },
  { nume: "Ramesti", comuna: "Susani" },
  { nume: "Stoiculesti", comuna: "Susani" },
  { nume: "Sarbi", comuna: "Susani" },
  { nume: "Usurei", comuna: "Susani" },
  { nume: "Borosesti", comuna: "Sutesti" },
  { nume: "Cetateaua", comuna: "Sutesti" },
  { nume: "Izvorasu", comuna: "Sutesti" },
  { nume: "Mitrofani", comuna: "Sutesti" },
  { nume: "Mazili", comuna: "Sutesti" },
  { nume: "Racu", comuna: "Sutesti" },
  { nume: "Verdea", comuna: "Sutesti" },
  { nume: "Budele", comuna: "Tetoiu" },
  { nume: "Baroiu", comuna: "Tetoiu" },
  { nume: "Maneasa", comuna: "Tetoiu" },
  { nume: "Nenciulesti", comuna: "Tetoiu" },
  { nume: "Popesti", comuna: "Tetoiu" },
  { nume: "Tepesti", comuna: "Tetoiu" },
  { nume: "Bratovesti", comuna: "Titesti" },
  { nume: "Cucoiu", comuna: "Titesti" },
  { nume: "Bogdanesti", comuna: "Tomsani" },
  { nume: "Baltateni", comuna: "Tomsani" },
  { nume: "Chiceni", comuna: "Tomsani" },
  { nume: "Dumbravesti", comuna: "Tomsani" },
  { nume: "Folestii de Jos", comuna: "Tomsani" },
  { nume: "Folestii de Sus", comuna: "Tomsani" },
  { nume: "Miresti", comuna: "Tomsani" },
  { nume: "Cerna", comuna: "Vaideeni" },
  { nume: "Cornet", comuna: "Vaideeni" },
  { nume: "Izvoru Rece", comuna: "Vaideeni" },
  { nume: "Marita", comuna: "Vaideeni" },
  { nume: "Batasani", comuna: "Valea Mare" },
  { nume: "Delureni", comuna: "Valea Mare" },
  { nume: "Draganu", comuna: "Valea Mare" },
  { nume: "Margineni", comuna: "Valea Mare" },
  { nume: "Pietroasa", comuna: "Valea Mare" },
  { nume: "Fundatura", comuna: "Vladesti" },
  { nume: "Pleasa", comuna: "Vladesti" },
  { nume: "Priporu", comuna: "Vladesti" },
  { nume: "Trundin", comuna: "Vladesti" },
  { nume: "Tighina", comuna: "Voicesti" },
  { nume: "Voicestii din Vale", comuna: "Voicesti" },
  { nume: "Valea Macesului", comuna: "Voineasa" },
  { nume: "Voinesita", comuna: "Voineasa" },
  { nume: "Butanu", comuna: "Zatreni" },
  { nume: "Ciortesti", comuna: "Zatreni" },
  { nume: "Contea", comuna: "Zatreni" },
  { nume: "Dealu Glameia", comuna: "Zatreni" },
  { nume: "Dealu Valeni", comuna: "Zatreni" },
  { nume: "Fauresti", comuna: "Zatreni" },
  { nume: "Ganesti", comuna: "Zatreni" },
  { nume: "Lacusteni", comuna: "Zatreni" },
  { nume: "Lacustenii de Jos", comuna: "Zatreni" },
  { nume: "Lacustenii de Sus", comuna: "Zatreni" },
  { nume: "Mecea", comuna: "Zatreni" },
  { nume: "Manicea", comuna: "Zatreni" },
  { nume: "Oltetu", comuna: "Zatreni" },
  { nume: "Stanomiru", comuna: "Zatreni" },
  { nume: "Sascioara", comuna: "Zatreni" },
  { nume: "Valea Valeni", comuna: "Zatreni" },
  { nume: "Valeni", comuna: "Zatreni" },
  { nume: "Zatrenii de Sus", comuna: "Zatreni" },
];
