export const vs = [
  { nume: "Albesti" },
  { nume: "Alexandru Vlahuta" },
  { nume: "Arsura" },
  { nume: "Banca" },
  { nume: "Berezeni" },
  { nume: "Blagesti" },
  { nume: "Bogdana" },
  { nume: "Bogdanesti" },
  { nume: "Bogdanita" },
  { nume: "Botesti" },
  { nume: "Bacani" },
  { nume: "Bacesti" },
  { nume: "Balteni" },
  { nume: "Codaesti" },
  { nume: "Coroiesti" },
  { nume: "Costesti" },
  { nume: "Cretesti" },
  { nume: "Deleni" },
  { nume: "Delesti" },
  { nume: "Dragomiresti" },
  { nume: "Dranceni" },
  { nume: "Dumesti" },
  { nume: "Danesti" },
  { nume: "Epureni" },
  { nume: "Falciu" },
  { nume: "Gherghesti" },
  { nume: "Grivita" },
  { nume: "Garceni" },
  { nume: "Gagesti" },
  { nume: "Hoceni" },
  { nume: "Husi" },
  { nume: "Iana" },
  { nume: "Ibanesti" },
  { nume: "Ivesti" },
  { nume: "Ivanesti" },
  { nume: "Laza" },
  { nume: "Lipovat" },
  { nume: "Lunca Banului" },
  { nume: "Miclesti" },
  { nume: "Muntenii de Jos" },
  { nume: "Murgeni" },
  { nume: "Malusteni" },
  { nume: "Negresti" },
  { nume: "Oltenesti" },
  { nume: "Osesti" },
  { nume: "Perieni" },
  { nume: "Pogana" },
  { nume: "Poienesti" },
  { nume: "Puiesti" },
  { nume: "Pungesti" },
  { nume: "Padureni" },
  { nume: "Rebricea" },
  { nume: "Rosiesti" },
  { nume: "Solesti" },
  { nume: "Stanilesti" },
  { nume: "Tanacu" },
  { nume: "Todiresti" },
  { nume: "Tutova" },
  { nume: "Tacuta" },
  { nume: "Tatarani" },
  { nume: "Vaslui" },
  { nume: "Vetrisoaia" },
  { nume: "Viisoara" },
  { nume: "Vinderei" },
  { nume: "Voinesti" },
  { nume: "Vulturesti" },
  { nume: "Vutcani" },
  { nume: "Valeni" },
  { nume: "Zorleni" },
  { nume: "Zapodeni" },
  { nume: "Stefan cel Mare" },
  { nume: "Suletea" },
  { nume: "Corni-Albesti", comuna: "Albesti" },
  { nume: "Crasna", comuna: "Albesti" },
  { nume: "Gura Albesti", comuna: "Albesti" },
  { nume: "Buda", comuna: "Alexandru Vlahuta" },
  { nume: "Ghicani", comuna: "Alexandru Vlahuta" },
  { nume: "Morareni", comuna: "Alexandru Vlahuta" },
  { nume: "Fundatura", comuna: "Arsura" },
  { nume: "Mihail Kogalniceanu", comuna: "Arsura" },
  { nume: "Pahnesti", comuna: "Arsura" },
  { nume: "Baltateni", comuna: "Bacani" },
  { nume: "Drujesti", comuna: "Bacani" },
  { nume: "Suseni", comuna: "Bacani" },
  { nume: "Vulpaseni", comuna: "Bacani" },
  { nume: "Armaseni", comuna: "Bacesti" },
  { nume: "Babusa", comuna: "Bacesti" },
  { nume: "Paltinis", comuna: "Bacesti" },
  { nume: "Vovriesti", comuna: "Bacesti" },
  { nume: "Tibanestii Buhlii", comuna: "Bacesti" },
  { nume: "Balteni-Deal", comuna: "Balteni" },
  { nume: "Chetresti", comuna: "Balteni" },
  { nume: "1 Decembrie", comuna: "Banca" },
  { nume: "Gara Banca", comuna: "Banca" },
  { nume: "Ghermanesti", comuna: "Banca" },
  { nume: "Miclesti", comuna: "Banca" },
  { nume: "Mitoc", comuna: "Banca" },
  { nume: "Satu Nou", comuna: "Banca" },
  { nume: "Stoisesti", comuna: "Banca" },
  { nume: "Stramtura-Mitoc", comuna: "Banca" },
  { nume: "Sarbi", comuna: "Banca" },
  { nume: "Salcioara", comuna: "Banca" },
  { nume: "Tifu", comuna: "Banca" },
  { nume: "Musata", comuna: "Berezeni" },
  { nume: "Ranceni", comuna: "Berezeni" },
  { nume: "Satu Nou", comuna: "Berezeni" },
  { nume: "Stuhulet", comuna: "Berezeni" },
  { nume: "Barlad", comuna: "Birlad" },
  { nume: "Igesti", comuna: "Blagesti" },
  { nume: "Sipeni", comuna: "Blagesti" },
  { nume: "Arsita", comuna: "Bogdana" },
  { nume: "Fantana Blanarului", comuna: "Bogdana" },
  { nume: "Gavanu", comuna: "Bogdana" },
  { nume: "Lacu Babei", comuna: "Bogdana" },
  { nume: "Plopeni", comuna: "Bogdana" },
  { nume: "Similisoara", comuna: "Bogdana" },
  { nume: "Suceveni", comuna: "Bogdana" },
  { nume: "Verdes", comuna: "Bogdana" },
  { nume: "Buda", comuna: "Bogdanesti" },
  { nume: "Horoiata", comuna: "Bogdanesti" },
  { nume: "Hupca", comuna: "Bogdanesti" },
  { nume: "Orgoiesti", comuna: "Bogdanesti" },
  { nume: "Ulea", comuna: "Bogdanesti" },
  { nume: "Untesti", comuna: "Bogdanesti" },
  { nume: "Visinari", comuna: "Bogdanesti" },
  { nume: "Vladesti", comuna: "Bogdanesti" },
  { nume: "Cepesti", comuna: "Bogdanita" },
  { nume: "Coroiesti", comuna: "Bogdanita" },
  { nume: "Cartibasi", comuna: "Bogdanita" },
  { nume: "Radaesti", comuna: "Bogdanita" },
  { nume: "Schitu", comuna: "Bogdanita" },
  { nume: "Tunsesti", comuna: "Bogdanita" },
  { nume: "Gugesti", comuna: "Botesti" },
  { nume: "Ganesti", comuna: "Botesti" },
  { nume: "Talpigeni", comuna: "Botesti" },
  { nume: "Armaseni", comuna: "Bunesti-Averesti" },
  { nume: "Averesti", comuna: "Bunesti-Averesti" },
  { nume: "Bunesti", comuna: "Bunesti-Averesti" },
  { nume: "Plopi", comuna: "Bunesti-Averesti" },
  { nume: "Podu Oprii", comuna: "Bunesti-Averesti" },
  { nume: "Rosiori", comuna: "Bunesti-Averesti" },
  { nume: "Tabalaesti", comuna: "Bunesti-Averesti" },
  { nume: "Ghergheleu", comuna: "Codaesti" },
  { nume: "Pribesti", comuna: "Codaesti" },
  { nume: "Rediu Galian", comuna: "Codaesti" },
  { nume: "Chilieni", comuna: "Coroiesti" },
  { nume: "Coroiestii de Sus", comuna: "Coroiesti" },
  { nume: "Hreasca", comuna: "Coroiesti" },
  { nume: "Mireni", comuna: "Coroiesti" },
  { nume: "Movileni", comuna: "Coroiesti" },
  { nume: "Pacuraresti", comuna: "Coroiesti" },
  { nume: "Chitcani", comuna: "Costesti" },
  { nume: "Dinga", comuna: "Costesti" },
  { nume: "Puntiseni", comuna: "Costesti" },
  { nume: "Parvesti", comuna: "Costesti" },
  { nume: "Radesti", comuna: "Costesti" },
  { nume: "Budesti", comuna: "Cretesti" },
  { nume: "Cretestii de Sus", comuna: "Cretesti" },
  { nume: "Satu Nou", comuna: "Cretesti" },
  { nume: "Bereasa", comuna: "Danesti" },
  { nume: "Botoaia", comuna: "Danesti" },
  { nume: "Emil Racovita", comuna: "Danesti" },
  { nume: "Rascani", comuna: "Danesti" },
  { nume: "Tatarani", comuna: "Danesti" },
  { nume: "Bulboaca", comuna: "Deleni" },
  { nume: "Moreni", comuna: "Deleni" },
  { nume: "Zizinca", comuna: "Deleni" },
  { nume: "Albesti", comuna: "Delesti" },
  { nume: "Balesti", comuna: "Delesti" },
  { nume: "Cozmesti", comuna: "Delesti" },
  { nume: "Fundatura", comuna: "Delesti" },
  { nume: "Fastaci", comuna: "Delesti" },
  { nume: "Hordilesti", comuna: "Delesti" },
  { nume: "Harsova", comuna: "Delesti" },
  { nume: "Manastirea", comuna: "Delesti" },
  { nume: "Raduiesti", comuna: "Delesti" },
  { nume: "Grumezoaia", comuna: "Dimitrie Cantemir" },
  { nume: "Gusitei", comuna: "Dimitrie Cantemir" },
  { nume: "Hurdugi", comuna: "Dimitrie Cantemir" },
  { nume: "Plotonesti", comuna: "Dimitrie Cantemir" },
  { nume: "Urlati", comuna: "Dimitrie Cantemir" },
  { nume: "Belzeni", comuna: "Dragomiresti" },
  { nume: "Botoi", comuna: "Dragomiresti" },
  { nume: "Babuta", comuna: "Dragomiresti" },
  { nume: "Ciuperca", comuna: "Dragomiresti" },
  { nume: "Doagele", comuna: "Dragomiresti" },
  { nume: "Poiana Pietrei", comuna: "Dragomiresti" },
  { nume: "Popesti", comuna: "Dragomiresti" },
  { nume: "Radeni", comuna: "Dragomiresti" },
  { nume: "Semenea", comuna: "Dragomiresti" },
  { nume: "Tulesti", comuna: "Dragomiresti" },
  { nume: "Vladia", comuna: "Dragomiresti" },
  { nume: "Albita", comuna: "Dranceni" },
  { nume: "Baile Dranceni", comuna: "Dranceni" },
  { nume: "Ghermanesti", comuna: "Dranceni" },
  { nume: "Rasesti", comuna: "Dranceni" },
  { nume: "Soparleni", comuna: "Dranceni" },
  { nume: "Bobesti", comuna: "Duda-Epureni" },
  { nume: "Duda", comuna: "Duda-Epureni" },
  { nume: "Epureni", comuna: "Duda-Epureni" },
  { nume: "Valea Grecului", comuna: "Duda-Epureni" },
  { nume: "Dumestii Vechi", comuna: "Dumesti" },
  { nume: "Schinetea", comuna: "Dumesti" },
  { nume: "Valea Mare", comuna: "Dumesti" },
  { nume: "Bursuci", comuna: "Epureni" },
  { nume: "Barlalesti", comuna: "Epureni" },
  { nume: "Horga", comuna: "Epureni" },
  { nume: "Bogdanesti", comuna: "Falciu" },
  { nume: "Bozia", comuna: "Falciu" },
  { nume: "Copaceana", comuna: "Falciu" },
  { nume: "Odaia Bogdana", comuna: "Falciu" },
  { nume: "Ranzesti", comuna: "Falciu" },
  { nume: "Giurcani", comuna: "Gagesti" },
  { nume: "Peicani", comuna: "Gagesti" },
  { nume: "Popeni", comuna: "Gagesti" },
  { nume: "Tupilati", comuna: "Gagesti" },
  { nume: "Dumbraveni", comuna: "Garceni" },
  { nume: "Racova", comuna: "Garceni" },
  { nume: "Racovita", comuna: "Garceni" },
  { nume: "Slobozia", comuna: "Garceni" },
  { nume: "Trohan", comuna: "Garceni" },
  { nume: "Chetrosu", comuna: "Gherghesti" },
  { nume: "Corodesti", comuna: "Gherghesti" },
  { nume: "Dragomanesti", comuna: "Gherghesti" },
  { nume: "Draxeni", comuna: "Gherghesti" },
  { nume: "Lazu", comuna: "Gherghesti" },
  { nume: "Lunca", comuna: "Gherghesti" },
  { nume: "Soci", comuna: "Gherghesti" },
  { nume: "Valea Lupului", comuna: "Gherghesti" },
  { nume: "Fruntiseni", comuna: "Grivita" },
  { nume: "Grajdeni", comuna: "Grivita" },
  { nume: "Odaia Bursucani", comuna: "Grivita" },
  { nume: "Trestiana", comuna: "Grivita" },
  { nume: "Barbosi", comuna: "Hoceni" },
  { nume: "Deleni", comuna: "Hoceni" },
  { nume: "Oteleni", comuna: "Hoceni" },
  { nume: "Rediu", comuna: "Hoceni" },
  { nume: "Tomsa", comuna: "Hoceni" },
  { nume: "Siscani", comuna: "Hoceni" },
  { nume: "Halaresti", comuna: "Iana" },
  { nume: "Recea", comuna: "Iana" },
  { nume: "Silistea", comuna: "Iana" },
  { nume: "Vadurile", comuna: "Iana" },
  { nume: "Manzati", comuna: "Ibanesti" },
  { nume: "Putu Olarului", comuna: "Ibanesti" },
  { nume: "Albina", comuna: "Ivanesti" },
  { nume: "Blesca", comuna: "Ivanesti" },
  { nume: "Brosteni", comuna: "Ivanesti" },
  { nume: "Buscata", comuna: "Ivanesti" },
  { nume: "Cosca", comuna: "Ivanesti" },
  { nume: "Cosesti", comuna: "Ivanesti" },
  { nume: "Fundatura Mare", comuna: "Ivanesti" },
  { nume: "Fundatura Mica", comuna: "Ivanesti" },
  { nume: "Harsoveni", comuna: "Ivanesti" },
  { nume: "Iezerel", comuna: "Ivanesti" },
  { nume: "Ursoaia", comuna: "Ivanesti" },
  { nume: "Valea Mare", comuna: "Ivanesti" },
  { nume: "Valea Oanei", comuna: "Ivanesti" },
  { nume: "Belcesti", comuna: "Ivesti" },
  { nume: "Pogonesti", comuna: "Ivesti" },
  { nume: "Polocin", comuna: "Ivesti" },
  { nume: "Bejenesti", comuna: "Laza" },
  { nume: "Poiana lui Alexa", comuna: "Laza" },
  { nume: "Puscasi", comuna: "Laza" },
  { nume: "Rasnita", comuna: "Laza" },
  { nume: "Sauca", comuna: "Laza" },
  { nume: "Teisoru", comuna: "Laza" },
  { nume: "Valea Targului", comuna: "Laza" },
  { nume: "Chitoc", comuna: "Lipovat" },
  { nume: "Corbu", comuna: "Lipovat" },
  { nume: "Capusneni", comuna: "Lipovat" },
  { nume: "Fundu Vaii", comuna: "Lipovat" },
  { nume: "Broscosesti", comuna: "Lunca Banului" },
  { nume: "Condrea", comuna: "Lunca Banului" },
  { nume: "Focsa", comuna: "Lunca Banului" },
  { nume: "Lunca Veche", comuna: "Lunca Banului" },
  { nume: "Otetoaia", comuna: "Lunca Banului" },
  { nume: "Raducani", comuna: "Lunca Banului" },
  { nume: "Ghireasca", comuna: "Malusteni" },
  { nume: "Lupesti", comuna: "Malusteni" },
  { nume: "Manzatesti", comuna: "Malusteni" },
  { nume: "Manastirea", comuna: "Malusteni" },
  { nume: "Tutcani", comuna: "Malusteni" },
  { nume: "Chircesti", comuna: "Miclesti" },
  { nume: "Popesti", comuna: "Miclesti" },
  { nume: "Bacaoani", comuna: "Muntenii De Jos" },
  { nume: "Manjesti", comuna: "Muntenii De Jos" },
  { nume: "Secuia", comuna: "Muntenii De Jos" },
  { nume: "Carja", comuna: "Murgeni" },
  { nume: "Floreni", comuna: "Murgeni" },
  { nume: "Latesti", comuna: "Murgeni" },
  { nume: "Raiu", comuna: "Murgeni" },
  { nume: "Schineni", comuna: "Murgeni" },
  { nume: "Sarateni", comuna: "Murgeni" },
  { nume: "Cioatele", comuna: "Negresti" },
  { nume: "Cazanesti", comuna: "Negresti" },
  { nume: "Glodeni", comuna: "Negresti" },
  { nume: "Parpanita", comuna: "Negresti" },
  { nume: "Poiana", comuna: "Negresti" },
  { nume: "Valea Mare", comuna: "Negresti" },
  { nume: "Curteni", comuna: "Oltenesti" },
  { nume: "Pahna", comuna: "Oltenesti" },
  { nume: "Tarzii", comuna: "Oltenesti" },
  { nume: "Vinetesti", comuna: "Oltenesti" },
  { nume: "Zgura", comuna: "Oltenesti" },
  { nume: "Buda", comuna: "Osesti" },
  { nume: "Padureni", comuna: "Osesti" },
  { nume: "Valcele", comuna: "Osesti" },
  { nume: "Capotesti", comuna: "Padureni" },
  { nume: "Davidesti", comuna: "Padureni" },
  { nume: "Ivanesti", comuna: "Padureni" },
  { nume: "Leosti", comuna: "Padureni" },
  { nume: "Rusca", comuna: "Padureni" },
  { nume: "Todireni", comuna: "Padureni" },
  { nume: "Valeni", comuna: "Padureni" },
  { nume: "Ciocani", comuna: "Perieni" },
  { nume: "Crang", comuna: "Perieni" },
  { nume: "Crangu Nou", comuna: "Perieni" },
  { nume: "Podu Petris", comuna: "Perieni" },
  { nume: "Bogesti", comuna: "Pogana" },
  { nume: "Carjoani", comuna: "Pogana" },
  { nume: "Mascurei", comuna: "Pogana" },
  { nume: "Tomesti", comuna: "Pogana" },
  { nume: "Dealu Secarii", comuna: "Poienesti" },
  { nume: "Floresti", comuna: "Poienesti" },
  { nume: "Frasinu", comuna: "Poienesti" },
  { nume: "Fundu Vaii", comuna: "Poienesti" },
  { nume: "Oprisita", comuna: "Poienesti" },
  { nume: "Poienesti-Deal", comuna: "Poienesti" },
  { nume: "Bartalus-Mocani", comuna: "Puiesti" },
  { nume: "Bartalus-Razesi", comuna: "Puiesti" },
  { nume: "Cetatuia", comuna: "Puiesti" },
  { nume: "Cristesti", comuna: "Puiesti" },
  { nume: "Calimanesti", comuna: "Puiesti" },
  { nume: "Fulgu", comuna: "Puiesti" },
  { nume: "Fantanele", comuna: "Puiesti" },
  { nume: "Galtesti", comuna: "Puiesti" },
  { nume: "Iezer", comuna: "Puiesti" },
  { nume: "Lalesti", comuna: "Puiesti" },
  { nume: "Rotari", comuna: "Puiesti" },
  { nume: "Rusi", comuna: "Puiesti" },
  { nume: "Armasoaia", comuna: "Pungesti" },
  { nume: "Cursesti-Deal", comuna: "Pungesti" },
  { nume: "Cursesti-Vale", comuna: "Pungesti" },
  { nume: "Hordila", comuna: "Pungesti" },
  { nume: "Rapsa", comuna: "Pungesti" },
  { nume: "Silistea", comuna: "Pungesti" },
  { nume: "Stejaru", comuna: "Pungesti" },
  { nume: "Toporasti", comuna: "Pungesti" },
  { nume: "Bolati", comuna: "Rebricea" },
  { nume: "Craciunesti", comuna: "Rebricea" },
  { nume: "Draxeni", comuna: "Rebricea" },
  { nume: "Macresti", comuna: "Rebricea" },
  { nume: "Ratesu Cuzei", comuna: "Rebricea" },
  { nume: "Sasova", comuna: "Rebricea" },
  { nume: "Tatomiresti", comuna: "Rebricea" },
  { nume: "Tufestii de Jos", comuna: "Rebricea" },
  { nume: "Codreni", comuna: "Rosiesti" },
  { nume: "Gara Rosiesti", comuna: "Rosiesti" },
  { nume: "Gura Idrici", comuna: "Rosiesti" },
  { nume: "Idrici", comuna: "Rosiesti" },
  { nume: "Rediu", comuna: "Rosiesti" },
  { nume: "Valea lui Darie", comuna: "Rosiesti" },
  { nume: "Bousori", comuna: "Solesti" },
  { nume: "Iaz", comuna: "Solesti" },
  { nume: "Satu Nou", comuna: "Solesti" },
  { nume: "Valea Silistei", comuna: "Solesti" },
  { nume: "Serbotesti", comuna: "Solesti" },
  { nume: "Stioborani", comuna: "Solesti" },
  { nume: "Bogdana-Voloseni", comuna: "Stanilesti" },
  { nume: "Budu Cantemir", comuna: "Stanilesti" },
  { nume: "Chersacosu", comuna: "Stanilesti" },
  { nume: "Gura Vaii", comuna: "Stanilesti" },
  { nume: "Poganesti", comuna: "Stanilesti" },
  { nume: "Saratu", comuna: "Stanilesti" },
  { nume: "Brahasoaia", comuna: "Stefan Cel Mare" },
  { nume: "Barzesti", comuna: "Stefan Cel Mare" },
  { nume: "Calugareni", comuna: "Stefan Cel Mare" },
  { nume: "Cantalaresti", comuna: "Stefan Cel Mare" },
  { nume: "Muntenesti", comuna: "Stefan Cel Mare" },
  { nume: "Maraseni", comuna: "Stefan Cel Mare" },
  { nume: "Fedesti", comuna: "Suletea" },
  { nume: "Jigalia", comuna: "Suletea" },
  { nume: "Rascani", comuna: "Suletea" },
  { nume: "Cujba", comuna: "Tacuta" },
  { nume: "Dumasca", comuna: "Tacuta" },
  { nume: "Focseasca", comuna: "Tacuta" },
  { nume: "Mircesti", comuna: "Tacuta" },
  { nume: "Protopopesti", comuna: "Tacuta" },
  { nume: "Sofieni", comuna: "Tacuta" },
  { nume: "Benesti", comuna: "Tanacu" },
  { nume: "Muntenii de Sus", comuna: "Tanacu" },
  { nume: "Satu Nou", comuna: "Tanacu" },
  { nume: "Baltati", comuna: "Tatarani" },
  { nume: "Crasnaseni", comuna: "Tatarani" },
  { nume: "Giurgesti", comuna: "Tatarani" },
  { nume: "Leosti", comuna: "Tatarani" },
  { nume: "Mantu", comuna: "Tatarani" },
  { nume: "Stroiesti", comuna: "Tatarani" },
  { nume: "Valea Seaca", comuna: "Tatarani" },
  { nume: "Valea lui Bosie", comuna: "Tatarani" },
  { nume: "Cotic", comuna: "Todiresti" },
  { nume: "Dragesti", comuna: "Todiresti" },
  { nume: "Huc", comuna: "Todiresti" },
  { nume: "Plopoasa", comuna: "Todiresti" },
  { nume: "Rafaila", comuna: "Todiresti" },
  { nume: "Silistea", comuna: "Todiresti" },
  { nume: "Sofronesti", comuna: "Todiresti" },
  { nume: "Valea Popii", comuna: "Todiresti" },
  { nume: "Viisoara", comuna: "Todiresti" },
  { nume: "Borodesti", comuna: "Tutova" },
  { nume: "Badeana", comuna: "Tutova" },
  { nume: "Ciortolom", comuna: "Tutova" },
  { nume: "Coroiu", comuna: "Tutova" },
  { nume: "Crivesti", comuna: "Tutova" },
  { nume: "Pochidia", comuna: "Tutova" },
  { nume: "Satu Nou", comuna: "Tutova" },
  { nume: "Salceni", comuna: "Tutova" },
  { nume: "Vizureni", comuna: "Tutova" },
  { nume: "Feresti", comuna: "Valeni" },
  { nume: "Moara Domneasca", comuna: "Valeni" },
  { nume: "Bahnari", comuna: "Vaslui" },
  { nume: "Brodoc", comuna: "Vaslui" },
  { nume: "Moara Grecilor", comuna: "Vaslui" },
  { nume: "Rediu", comuna: "Vaslui" },
  { nume: "Viisoara", comuna: "Vaslui" },
  { nume: "Bumbata", comuna: "Vetrisoaia" },
  { nume: "Dodesti", comuna: "Viisoara" },
  { nume: "Halta Dodesti", comuna: "Viisoara" },
  { nume: "Urdesti", comuna: "Viisoara" },
  { nume: "Viltotesti", comuna: "Viisoara" },
  { nume: "Valeni", comuna: "Viisoara" },
  { nume: "Bradesti", comuna: "Vinderei" },
  { nume: "Docani", comuna: "Vinderei" },
  { nume: "Docaneasa", comuna: "Vinderei" },
  { nume: "Gara Docaneasa", comuna: "Vinderei" },
  { nume: "Gara Talasman", comuna: "Vinderei" },
  { nume: "Obarseni", comuna: "Vinderei" },
  { nume: "Valea Lunga", comuna: "Vinderei" },
  { nume: "Avramesti", comuna: "Voinesti" },
  { nume: "Bancesti", comuna: "Voinesti" },
  { nume: "Corobanesti", comuna: "Voinesti" },
  { nume: "Gardesti", comuna: "Voinesti" },
  { nume: "Marasesti", comuna: "Voinesti" },
  { nume: "Obarseni", comuna: "Voinesti" },
  { nume: "Obarsenii Lingurari", comuna: "Voinesti" },
  { nume: "Rugaria", comuna: "Voinesti" },
  { nume: "Stancaseni", comuna: "Voinesti" },
  { nume: "Uricari", comuna: "Voinesti" },
  { nume: "Buhaiesti", comuna: "Vulturesti" },
  { nume: "Podeni", comuna: "Vulturesti" },
  { nume: "Voinesti", comuna: "Vulturesti" },
  { nume: "Malaiesti", comuna: "Vutcani" },
  { nume: "Posta Elan", comuna: "Vutcani" },
  { nume: "Butucaria", comuna: "Zapodeni" },
  { nume: "Ciofeni", comuna: "Zapodeni" },
  { nume: "Delea", comuna: "Zapodeni" },
  { nume: "Dobroslovesti", comuna: "Zapodeni" },
  { nume: "Macresti", comuna: "Zapodeni" },
  { nume: "Portari", comuna: "Zapodeni" },
  { nume: "Telejna", comuna: "Zapodeni" },
  { nume: "Uncesti", comuna: "Zapodeni" },
  { nume: "Dealu Mare", comuna: "Zorleni" },
  { nume: "Popeni", comuna: "Zorleni" },
  { nume: "Simila", comuna: "Zorleni" },
];
