export const vn = [
  { nume: "Adjud" },
  { nume: "Andreiasu de Jos" },
  { nume: "Boghesti" },
  { nume: "Bolotesti" },
  { nume: "Bordesti" },
  { nume: "Brosteni" },
  { nume: "Barsesti" },
  { nume: "Balesti" },
  { nume: "Chiojdeni" },
  { nume: "Ciorasti" },
  { nume: "Corbita" },
  { nume: "Cotesti" },
  { nume: "Campineanca" },
  { nume: "Campuri" },
  { nume: "Carligele" },
  { nume: "Dumbraveni" },
  { nume: "Dumitresti" },
  { nume: "Fitionesti" },
  { nume: "Focsani" },
  { nume: "Garoafa" },
  { nume: "Golesti" },
  { nume: "Gugesti" },
  { nume: "Gura Calitei" },
  { nume: "Homocea" },
  { nume: "Jaristea" },
  { nume: "Jitia" },
  { nume: "Mera" },
  { nume: "Milcovul" },
  { nume: "Movilita" },
  { nume: "Maicanesti" },
  { nume: "Marasesti" },
  { nume: "Negrilesti" },
  { nume: "Nereju" },
  { nume: "Nistoresti" },
  { nume: "Nanesti" },
  { nume: "Naruja" },
  { nume: "Odobesti" },
  { nume: "Paltin" },
  { nume: "Panciu" },
  { nume: "Ploscuteni" },
  { nume: "Poiana Cristei" },
  { nume: "Popesti" },
  { nume: "Pufesti" },
  { nume: "Paulesti" },
  { nume: "Paunesti" },
  { nume: "Reghiu" },
  { nume: "Ruginesti" },
  { nume: "Racoasa" },
  { nume: "Sihlea" },
  { nume: "Slobozia Bradului" },
  { nume: "Slobozia Ciorasti" },
  { nume: "Straoane" },
  { nume: "Suraia" },
  { nume: "Tulnici" },
  { nume: "Tamboesti" },
  { nume: "Tanasoaia" },
  { nume: "Tataranu" },
  { nume: "Urechesti" },
  { nume: "Valea Sarii" },
  { nume: "Vidra" },
  { nume: "Vintileasca" },
  { nume: "Vrancioaia" },
  { nume: "Vulturu" },
  { nume: "Vanatori" },
  { nume: "Vartescoiu" },
  { nume: "Tifesti" },
  { nume: "Adjudu Vechi", comuna: "Adjud" },
  { nume: "Burcioaia", comuna: "Adjud" },
  { nume: "Siscani", comuna: "Adjud" },
  { nume: "Andreiasu de Sus", comuna: "Andreiasu De Jos" },
  { nume: "Arsita", comuna: "Andreiasu De Jos" },
  { nume: "Fetig", comuna: "Andreiasu De Jos" },
  { nume: "Hotaru", comuna: "Andreiasu De Jos" },
  { nume: "Rachitasu", comuna: "Andreiasu De Jos" },
  { nume: "Titila", comuna: "Andreiasu De Jos" },
  { nume: "Topesti", comuna: "Barsesti" },
  { nume: "Bichesti", comuna: "Boghesti" },
  { nume: "Boghestii de Sus", comuna: "Boghesti" },
  { nume: "Chitcani", comuna: "Boghesti" },
  { nume: "Iugani", comuna: "Boghesti" },
  { nume: "Plesesti", comuna: "Boghesti" },
  { nume: "Placinteni", comuna: "Boghesti" },
  { nume: "Prisecani", comuna: "Boghesti" },
  { nume: "Tabucesti", comuna: "Boghesti" },
  { nume: "Gagesti", comuna: "Bolotesti" },
  { nume: "Ivancesti", comuna: "Bolotesti" },
  { nume: "Pietroasa", comuna: "Bolotesti" },
  { nume: "Putna", comuna: "Bolotesti" },
  { nume: "Vitanestii de Sub Magura", comuna: "Bolotesti" },
  { nume: "Bordestii de Jos", comuna: "Bordesti" },
  { nume: "Arva", comuna: "Brosteni" },
  { nume: "Pitulusa", comuna: "Brosteni" },
  { nume: "Pietroasa", comuna: "Campineanca" },
  { nume: "Valcele", comuna: "Campineanca" },
  { nume: "Fetesti", comuna: "Campuri" },
  { nume: "Gura Vaii", comuna: "Campuri" },
  { nume: "Rotilestii Mari", comuna: "Campuri" },
  { nume: "Rotilestii Mici", comuna: "Campuri" },
  { nume: "Blidari", comuna: "Carligele" },
  { nume: "Bontesti", comuna: "Carligele" },
  { nume: "Dalhauti", comuna: "Carligele" },
  { nume: "Catauti", comuna: "Chiojdeni" },
  { nume: "Lojnita", comuna: "Chiojdeni" },
  { nume: "Luncile", comuna: "Chiojdeni" },
  { nume: "Maracini", comuna: "Chiojdeni" },
  { nume: "Podurile", comuna: "Chiojdeni" },
  { nume: "Seciu", comuna: "Chiojdeni" },
  { nume: "Tulburea", comuna: "Chiojdeni" },
  { nume: "Codresti", comuna: "Ciorasti" },
  { nume: "Mihalceni", comuna: "Ciorasti" },
  { nume: "Salcia Noua", comuna: "Ciorasti" },
  { nume: "Salcia Veche", comuna: "Ciorasti" },
  { nume: "Satu Nou", comuna: "Ciorasti" },
  { nume: "Spatareasa", comuna: "Ciorasti" },
  { nume: "Buda", comuna: "Corbita" },
  { nume: "Izvoarele", comuna: "Corbita" },
  { nume: "Largaseni", comuna: "Corbita" },
  { nume: "Ochesesti", comuna: "Corbita" },
  { nume: "Radacinesti", comuna: "Corbita" },
  { nume: "Tutu", comuna: "Corbita" },
  { nume: "Valcelele", comuna: "Corbita" },
  { nume: "Serbanesti", comuna: "Corbita" },
  { nume: "Budesti", comuna: "Cotesti" },
  { nume: "Golestii de Sus", comuna: "Cotesti" },
  { nume: "Valea Cotesti", comuna: "Cotesti" },
  { nume: "Alexandru Vlahuta", comuna: "Dumbraveni" },
  { nume: "Candesti", comuna: "Dumbraveni" },
  { nume: "Dragosloveni", comuna: "Dumbraveni" },
  { nume: "Bicestii de Jos", comuna: "Dumitresti" },
  { nume: "Bicestii de Sus", comuna: "Dumitresti" },
  { nume: "Blidari", comuna: "Dumitresti" },
  { nume: "Dumitrestii de Sus", comuna: "Dumitresti" },
  { nume: "Dumitrestii-Fata", comuna: "Dumitresti" },
  { nume: "Galoiesti", comuna: "Dumitresti" },
  { nume: "Lupoaia", comuna: "Dumitresti" },
  { nume: "Lastuni", comuna: "Dumitresti" },
  { nume: "Motnau", comuna: "Dumitresti" },
  { nume: "Poienita", comuna: "Dumitresti" },
  { nume: "Roscari", comuna: "Dumitresti" },
  { nume: "Siminoc", comuna: "Dumitresti" },
  { nume: "Tinoasa", comuna: "Dumitresti" },
  { nume: "Trestia", comuna: "Dumitresti" },
  { nume: "Valea Mica", comuna: "Dumitresti" },
  { nume: "Ciolanesti", comuna: "Fitionesti" },
  { nume: "Ghimicesti", comuna: "Fitionesti" },
  { nume: "Holbanesti", comuna: "Fitionesti" },
  { nume: "Manastioara", comuna: "Fitionesti" },
  { nume: "Mandresti-Moldova", comuna: "Focsani" },
  { nume: "Mandresti-Munteni", comuna: "Focsani" },
  { nume: "Bizighesti", comuna: "Garoafa" },
  { nume: "Ciuslea", comuna: "Garoafa" },
  { nume: "Doaga", comuna: "Garoafa" },
  { nume: "Faurei", comuna: "Garoafa" },
  { nume: "Precistanu", comuna: "Garoafa" },
  { nume: "Rachitosu", comuna: "Garoafa" },
  { nume: "Strajescu", comuna: "Garoafa" },
  { nume: "Ceardac", comuna: "Golesti" },
  { nume: "Oreavu", comuna: "Gugesti" },
  { nume: "Balanesti", comuna: "Gura Calitei" },
  { nume: "Cocosari", comuna: "Gura Calitei" },
  { nume: "Dealul Lung", comuna: "Gura Calitei" },
  { nume: "Groapa Tufei", comuna: "Gura Calitei" },
  { nume: "Lacu lui Baban", comuna: "Gura Calitei" },
  { nume: "Plopu", comuna: "Gura Calitei" },
  { nume: "Poenile", comuna: "Gura Calitei" },
  { nume: "Rasca", comuna: "Gura Calitei" },
  { nume: "Sotarcari", comuna: "Gura Calitei" },
  { nume: "Costisa", comuna: "Homocea" },
  { nume: "Lespezi", comuna: "Homocea" },
  { nume: "Padureni", comuna: "Jaristea" },
  { nume: "Scanteia", comuna: "Jaristea" },
  { nume: "Varsatura", comuna: "Jaristea" },
  { nume: "Cerbu", comuna: "Jitia" },
  { nume: "Dealu Sarii", comuna: "Jitia" },
  { nume: "Jitia de Jos", comuna: "Jitia" },
  { nume: "Magura", comuna: "Jitia" },
  { nume: "Belciugele", comuna: "Maicanesti" },
  { nume: "Ramniceni", comuna: "Maicanesti" },
  { nume: "Slobozia Botesti", comuna: "Maicanesti" },
  { nume: "Stupina", comuna: "Maicanesti" },
  { nume: "Tataru", comuna: "Maicanesti" },
  { nume: "Calimanesti", comuna: "Marasesti" },
  { nume: "Haret", comuna: "Marasesti" },
  { nume: "Modruzeni", comuna: "Marasesti" },
  { nume: "Padureni", comuna: "Marasesti" },
  { nume: "Siretu", comuna: "Marasesti" },
  { nume: "Tisita", comuna: "Marasesti" },
  { nume: "Livada", comuna: "Mera" },
  { nume: "Milcovel", comuna: "Mera" },
  { nume: "Rosioara", comuna: "Mera" },
  { nume: "Vulcaneasa", comuna: "Mera" },
  { nume: "Gologanu", comuna: "Milcovul" },
  { nume: "Lamotesti", comuna: "Milcovul" },
  { nume: "Rastoaca", comuna: "Milcovul" },
  { nume: "Diochetirediu", comuna: "Movilita" },
  { nume: "Frecatei", comuna: "Movilita" },
  { nume: "Trotusanu", comuna: "Movilita" },
  { nume: "Valeni", comuna: "Movilita" },
  { nume: "Calienii Noi", comuna: "Nanesti" },
  { nume: "Calienii Vechi", comuna: "Nanesti" },
  { nume: "Podu Narujei", comuna: "Naruja" },
  { nume: "Podu Stoica", comuna: "Naruja" },
  { nume: "Rebegari", comuna: "Naruja" },
  { nume: "Bradacesti", comuna: "Nereju" },
  { nume: "Chiricani", comuna: "Nereju" },
  { nume: "Nereju Mic", comuna: "Nereju" },
  { nume: "Sahastru", comuna: "Nereju" },
  { nume: "Bradetu", comuna: "Nistoresti" },
  { nume: "Batcari", comuna: "Nistoresti" },
  { nume: "Fagetu", comuna: "Nistoresti" },
  { nume: "Podu Schiopului", comuna: "Nistoresti" },
  { nume: "Romanesti", comuna: "Nistoresti" },
  { nume: "Ungureni", comuna: "Nistoresti" },
  { nume: "Valea Neagra", comuna: "Nistoresti" },
  { nume: "Vetresti-Herastrau", comuna: "Nistoresti" },
  { nume: "Unirea", comuna: "Odobesti" },
  { nume: "Carsochesti-Corabita", comuna: "Paltin" },
  { nume: "Ghebari", comuna: "Paltin" },
  { nume: "Moraresti", comuna: "Paltin" },
  { nume: "Prahuda", comuna: "Paltin" },
  { nume: "Pavalari", comuna: "Paltin" },
  { nume: "Spulber", comuna: "Paltin" },
  { nume: "Tojanii de Jos", comuna: "Paltin" },
  { nume: "Tojanii de Sus", comuna: "Paltin" },
  { nume: "Valcani", comuna: "Paltin" },
  { nume: "Tepa", comuna: "Paltin" },
  { nume: "Tipau", comuna: "Paltin" },
  { nume: "Crucea de Jos", comuna: "Panciu" },
  { nume: "Crucea de Sus", comuna: "Panciu" },
  { nume: "Dumbrava", comuna: "Panciu" },
  { nume: "Neicu", comuna: "Panciu" },
  { nume: "Satu Nou", comuna: "Panciu" },
  { nume: "Haulisca", comuna: "Paulesti" },
  { nume: "Viisoara", comuna: "Paunesti" },
  { nume: "Argea", comuna: "Ploscuteni" },
  { nume: "Dealu Cucului", comuna: "Poiana Cristei" },
  { nume: "Dumbrava", comuna: "Poiana Cristei" },
  { nume: "Mahriu", comuna: "Poiana Cristei" },
  { nume: "Odobasca", comuna: "Poiana Cristei" },
  { nume: "Petreanu", comuna: "Poiana Cristei" },
  { nume: "Podu Lacului", comuna: "Poiana Cristei" },
  { nume: "Taratu", comuna: "Poiana Cristei" },
  { nume: "Terchesti", comuna: "Popesti" },
  { nume: "Ciorani", comuna: "Pufesti" },
  { nume: "Domnesti-Sat", comuna: "Pufesti" },
  { nume: "Domnesti-Targ", comuna: "Pufesti" },
  { nume: "Gogoiu", comuna: "Racoasa" },
  { nume: "Marasti", comuna: "Racoasa" },
  { nume: "Varnita", comuna: "Racoasa" },
  { nume: "Verdea", comuna: "Racoasa" },
  { nume: "Farcas", comuna: "Reghiu" },
  { nume: "Jgheaburi", comuna: "Reghiu" },
  { nume: "Piscu Reghiului", comuna: "Reghiu" },
  { nume: "Raiuti", comuna: "Reghiu" },
  { nume: "Ursoaia", comuna: "Reghiu" },
  { nume: "Valea Milcovului", comuna: "Reghiu" },
  { nume: "Sindrilari", comuna: "Reghiu" },
  { nume: "Anghelesti", comuna: "Ruginesti" },
  { nume: "Copacesti", comuna: "Ruginesti" },
  { nume: "Valeni", comuna: "Ruginesti" },
  { nume: "Bogza", comuna: "Sihlea" },
  { nume: "Caiata", comuna: "Sihlea" },
  { nume: "Voetin", comuna: "Sihlea" },
  { nume: "Cornetu", comuna: "Slobozia Bradului" },
  { nume: "Coroteni", comuna: "Slobozia Bradului" },
  { nume: "Liesti", comuna: "Slobozia Bradului" },
  { nume: "Olareni", comuna: "Slobozia Bradului" },
  { nume: "Valea Beciului", comuna: "Slobozia Bradului" },
  { nume: "Armeni", comuna: "Slobozia Ciorasti" },
  { nume: "Jiliste", comuna: "Slobozia Ciorasti" },
  { nume: "Dragosloveni", comuna: "Soveja" },
  { nume: "Rucareni", comuna: "Soveja" },
  { nume: "Muncelu", comuna: "Straoane" },
  { nume: "Repedea", comuna: "Straoane" },
  { nume: "Valeni", comuna: "Straoane" },
  { nume: "Biliesti", comuna: "Suraia" },
  { nume: "Obrejita", comuna: "Tamboesti" },
  { nume: "Pietroasa", comuna: "Tamboesti" },
  { nume: "Padureni", comuna: "Tamboesti" },
  { nume: "Slimnic", comuna: "Tamboesti" },
  { nume: "Trestieni", comuna: "Tamboesti" },
  { nume: "Costisa", comuna: "Tanasoaia" },
  { nume: "Costisa de Sus", comuna: "Tanasoaia" },
  { nume: "Covrag", comuna: "Tanasoaia" },
  { nume: "Calimaneasa", comuna: "Tanasoaia" },
  { nume: "Feldioara", comuna: "Tanasoaia" },
  { nume: "Galbeni", comuna: "Tanasoaia" },
  { nume: "Nanesti", comuna: "Tanasoaia" },
  { nume: "Vladnicu de Jos", comuna: "Tanasoaia" },
  { nume: "Vladnicu de Sus", comuna: "Tanasoaia" },
  { nume: "Bordeasca Noua", comuna: "Tataranu" },
  { nume: "Bordeasca Veche", comuna: "Tataranu" },
  { nume: "Martinesti", comuna: "Tataranu" },
  { nume: "Vajaitoarea", comuna: "Tataranu" },
  { nume: "Batinesti", comuna: "Tifesti" },
  { nume: "Clipicesti", comuna: "Tifesti" },
  { nume: "Igesti", comuna: "Tifesti" },
  { nume: "Olesesti", comuna: "Tifesti" },
  { nume: "Patrascani", comuna: "Tifesti" },
  { nume: "Sarbi", comuna: "Tifesti" },
  { nume: "Vitanesti", comuna: "Tifesti" },
  { nume: "Coza", comuna: "Tulnici" },
  { nume: "Gresu", comuna: "Tulnici" },
  { nume: "Lepsa", comuna: "Tulnici" },
  { nume: "Colacu", comuna: "Valea Sarii" },
  { nume: "Matacina", comuna: "Valea Sarii" },
  { nume: "Poduri", comuna: "Valea Sarii" },
  { nume: "Prisaca", comuna: "Valea Sarii" },
  { nume: "Balta Ratei", comuna: "Vanatori" },
  { nume: "Jorasti", comuna: "Vanatori" },
  { nume: "Mircestii Noi", comuna: "Vanatori" },
  { nume: "Mircestii Vechi", comuna: "Vanatori" },
  { nume: "Petresti", comuna: "Vanatori" },
  { nume: "Radulesti", comuna: "Vanatori" },
  { nume: "Beciu", comuna: "Vartescoiu" },
  { nume: "Faraoanele", comuna: "Vartescoiu" },
  { nume: "Olteni", comuna: "Vartescoiu" },
  { nume: "Pietroasa", comuna: "Vartescoiu" },
  { nume: "Ramniceanca", comuna: "Vartescoiu" },
  { nume: "Burca", comuna: "Vidra" },
  { nume: "Iresti", comuna: "Vidra" },
  { nume: "Ruget", comuna: "Vidra" },
  { nume: "Scafari", comuna: "Vidra" },
  { nume: "Tichiris", comuna: "Vidra" },
  { nume: "Viisoara", comuna: "Vidra" },
  { nume: "Voloscani", comuna: "Vidra" },
  { nume: "Serbesti", comuna: "Vidra" },
  { nume: "Bahnele", comuna: "Vintileasca" },
  { nume: "Dupa Magura", comuna: "Vintileasca" },
  { nume: "Neculele", comuna: "Vintileasca" },
  { nume: "Poiana Stoichii", comuna: "Vintileasca" },
  { nume: "Tanasari", comuna: "Vintileasca" },
  { nume: "Livezile", comuna: "Vizantea-Livezi" },
  { nume: "Mesteacanu", comuna: "Vizantea-Livezi" },
  { nume: "Piscu Radului", comuna: "Vizantea-Livezi" },
  { nume: "Vizantea Manastireasca", comuna: "Vizantea-Livezi" },
  { nume: "Vizantea Razaseasca", comuna: "Vizantea-Livezi" },
  { nume: "Bodesti", comuna: "Vrancioaia" },
  { nume: "Muncei", comuna: "Vrancioaia" },
  { nume: "Plostina", comuna: "Vrancioaia" },
  { nume: "Poiana", comuna: "Vrancioaia" },
  { nume: "Spinesti", comuna: "Vrancioaia" },
  { nume: "Botarlau", comuna: "Vulturu" },
  { nume: "Hangulesti", comuna: "Vulturu" },
  { nume: "Maluri", comuna: "Vulturu" },
  { nume: "Vadu Rosca", comuna: "Vulturu" },
];
