export const vn = [
  { nume: "Adjud" },
  { nume: "Adjudu Vechi", comuna: "Adjud" },
  {
    nume: "Alexandru Vlahuţă",
    simplu: "Alexandru Vlahuta",
    comuna: "Dumbraveni",
  },
  { nume: "Andreiaşu de Jos", simplu: "Andreiasu de Jos" },
  {
    nume: "Andreiaşu de Sus",
    simplu: "Andreiasu de Sus",
    comuna: "Andreiasu De Jos",
  },
  { nume: "Angheleşti", simplu: "Anghelesti", comuna: "Ruginesti" },
  { nume: "Argea", comuna: "Ploscuteni" },
  { nume: "Armeni", comuna: "Slobozia Ciorasti" },
  { nume: "Arşiţa", simplu: "Arsita", comuna: "Andreiasu De Jos" },
  { nume: "Arva", comuna: "Brosteni" },
  { nume: "Bahnele", comuna: "Vintileasca" },
  { nume: "Bălăneşti", simplu: "Balanesti", comuna: "Gura Calitei" },
  { nume: "Băleşti", simplu: "Balesti" },
  { nume: "Balta Raţei", simplu: "Balta Ratei", comuna: "Vanatori" },
  { nume: "Bârseşti", simplu: "Barsesti" },
  { nume: "Bâtcari", simplu: "Batcari", comuna: "Nistoresti" },
  { nume: "Bătineşti", simplu: "Batinesti", comuna: "Tifesti" },
  { nume: "Beciu", comuna: "Vartescoiu" },
  { nume: "Belciugele", comuna: "Maicanesti" },
  { nume: "Biceştii de Jos", simplu: "Bicestii de Jos", comuna: "Dumitresti" },
  { nume: "Biceştii de Sus", simplu: "Bicestii de Sus", comuna: "Dumitresti" },
  { nume: "Bicheşti", simplu: "Bichesti", comuna: "Boghesti" },
  { nume: "Bilieşti", simplu: "Biliesti", comuna: "Suraia" },
  { nume: "Bizigheşti", simplu: "Bizighesti", comuna: "Garoafa" },
  { nume: "Blidari", comuna: "Carligele" },
  { nume: "Blidari", comuna: "Dumitresti" },
  { nume: "Bodeşti", simplu: "Bodesti", comuna: "Vrancioaia" },
  { nume: "Bogheşti", simplu: "Boghesti" },
  { nume: "Bogheştii de Sus", simplu: "Boghestii de Sus", comuna: "Boghesti" },
  { nume: "Bogza", comuna: "Sihlea" },
  { nume: "Boloteşti", simplu: "Bolotesti" },
  { nume: "Bonţeşti", simplu: "Bontesti", comuna: "Carligele" },
  { nume: "Bordeasca Nouă", simplu: "Bordeasca Noua", comuna: "Tataranu" },
  { nume: "Bordeasca Veche", comuna: "Tataranu" },
  { nume: "Bordeşti", simplu: "Bordesti" },
  { nume: "Bordeştii de Jos", simplu: "Bordestii de Jos", comuna: "Bordesti" },
  { nume: "Boţârlău", simplu: "Botarlau", comuna: "Vulturu" },
  { nume: "Brădăceşti", simplu: "Bradacesti", comuna: "Nereju" },
  { nume: "Brădetu", simplu: "Bradetu", comuna: "Nistoresti" },
  { nume: "Broşteni", simplu: "Brosteni" },
  { nume: "Buda", comuna: "Corbita" },
  { nume: "Budeşti", simplu: "Budesti", comuna: "Cotesti" },
  { nume: "Burca", comuna: "Vidra" },
  { nume: "Burcioaia", comuna: "Adjud" },
  { nume: "Căiata", simplu: "Caiata", comuna: "Sihlea" },
  { nume: "Călienii Noi", simplu: "Calienii Noi", comuna: "Nanesti" },
  { nume: "Călienii Vechi", simplu: "Calienii Vechi", comuna: "Nanesti" },
  { nume: "Călimăneasa", simplu: "Calimaneasa", comuna: "Tanasoaia" },
  { nume: "Călimăneşti", simplu: "Calimanesti", comuna: "Marasesti" },
  { nume: "Câmpineanca", simplu: "Campineanca" },
  { nume: "Câmpuri", simplu: "Campuri" },
  { nume: "Cândeşti", simplu: "Candesti", comuna: "Dumbraveni" },
  { nume: "Cârligele", simplu: "Carligele" },
  {
    nume: "Carşocheşti-Corăbiţa",
    simplu: "Carsochesti-Corabita",
    comuna: "Paltin",
  },
  { nume: "Cătăuţi", simplu: "Catauti", comuna: "Chiojdeni" },
  { nume: "Ceardac", comuna: "Golesti" },
  { nume: "Cerbu", comuna: "Jitia" },
  { nume: "Chiojdeni" },
  { nume: "Chiricani", comuna: "Nereju" },
  { nume: "Chiţcani", simplu: "Chitcani", comuna: "Boghesti" },
  { nume: "Ciolăneşti", simplu: "Ciolanesti", comuna: "Fitionesti" },
  { nume: "Ciorani", comuna: "Pufesti" },
  { nume: "Ciorăşti", simplu: "Ciorasti" },
  { nume: "Ciuşlea", simplu: "Ciuslea", comuna: "Garoafa" },
  { nume: "Clipiceşti", simplu: "Clipicesti", comuna: "Tifesti" },
  { nume: "Cocoşari", simplu: "Cocosari", comuna: "Gura Calitei" },
  { nume: "Codreşti", simplu: "Codresti", comuna: "Ciorasti" },
  { nume: "Colacu", comuna: "Valea Sarii" },
  { nume: "Copăceşti", simplu: "Copacesti", comuna: "Ruginesti" },
  { nume: "Corbiţa", simplu: "Corbita" },
  { nume: "Cornetu", comuna: "Slobozia Bradului" },
  { nume: "Coroteni", comuna: "Slobozia Bradului" },
  { nume: "Costişa de Sus", simplu: "Costisa de Sus", comuna: "Tanasoaia" },
  { nume: "Costişa", simplu: "Costisa", comuna: "Homocea" },
  { nume: "Costişa", simplu: "Costisa", comuna: "Tanasoaia" },
  { nume: "Coteşti", simplu: "Cotesti" },
  { nume: "Covrag", comuna: "Tanasoaia" },
  { nume: "Coza", comuna: "Tulnici" },
  { nume: "Crucea de Jos", comuna: "Panciu" },
  { nume: "Crucea de Sus", comuna: "Panciu" },
  { nume: "Dălhăuţi", simplu: "Dalhauti", comuna: "Carligele" },
  { nume: "Dealu Cucului", comuna: "Poiana Cristei" },
  { nume: "Dealu Sării", simplu: "Dealu Sarii", comuna: "Jitia" },
  { nume: "Dealul Lung", comuna: "Gura Calitei" },
  { nume: "Diocheţirediu", simplu: "Diochetirediu", comuna: "Movilita" },
  { nume: "Doaga", comuna: "Garoafa" },
  { nume: "Domneşti-Sat", simplu: "Domnesti-Sat", comuna: "Pufesti" },
  { nume: "Domneşti-Târg", simplu: "Domnesti-Targ", comuna: "Pufesti" },
  { nume: "Dragosloveni", comuna: "Dumbraveni" },
  { nume: "Dragosloveni", comuna: "Soveja" },
  { nume: "Dumbrava", comuna: "Panciu" },
  { nume: "Dumbrava", comuna: "Poiana Cristei" },
  { nume: "Dumbrăveni", simplu: "Dumbraveni" },
  { nume: "Dumitreşti", simplu: "Dumitresti" },
  {
    nume: "Dumitreştii de Sus",
    simplu: "Dumitrestii de Sus",
    comuna: "Dumitresti",
  },
  {
    nume: "Dumitreştii-Faţă",
    simplu: "Dumitrestii-Fata",
    comuna: "Dumitresti",
  },
  { nume: "După Măgura", simplu: "Dupa Magura", comuna: "Vintileasca" },
  { nume: "Făgetu", simplu: "Fagetu", comuna: "Nistoresti" },
  { nume: "Faraoanele", comuna: "Vartescoiu" },
  { nume: "Farcaş", simplu: "Farcas", comuna: "Reghiu" },
  { nume: "Făurei", simplu: "Faurei", comuna: "Garoafa" },
  { nume: "Feldioara", comuna: "Tanasoaia" },
  { nume: "Feteşti", simplu: "Fetesti", comuna: "Campuri" },
  { nume: "Fetig", comuna: "Andreiasu De Jos" },
  { nume: "Fitioneşti", simplu: "Fitionesti" },
  { nume: "Focşani", simplu: "Focsani" },
  { nume: "Frecăţei", simplu: "Frecatei", comuna: "Movilita" },
  { nume: "Găgeşti", simplu: "Gagesti", comuna: "Bolotesti" },
  { nume: "Galbeni", comuna: "Tanasoaia" },
  { nume: "Găloieşti", simplu: "Galoiesti", comuna: "Dumitresti" },
  { nume: "Garoafa" },
  { nume: "Ghebari", comuna: "Paltin" },
  { nume: "Ghimiceşti", simplu: "Ghimicesti", comuna: "Fitionesti" },
  { nume: "Gogoiu", comuna: "Racoasa" },
  { nume: "Goleşti", simplu: "Golesti" },
  { nume: "Goleştii de Sus", simplu: "Golestii de Sus", comuna: "Cotesti" },
  { nume: "Gologanu", comuna: "Milcovul" },
  { nume: "Gresu", comuna: "Tulnici" },
  { nume: "Groapa Tufei", comuna: "Gura Calitei" },
  { nume: "Gugeşti", simplu: "Gugesti" },
  { nume: "Gura Caliţei", simplu: "Gura Calitei" },
  { nume: "Gura Văii", simplu: "Gura Vaii", comuna: "Campuri" },
  { nume: "Hânguleşti", simplu: "Hangulesti", comuna: "Vulturu" },
  { nume: "Haret", comuna: "Marasesti" },
  { nume: "Hăulişca", simplu: "Haulisca", comuna: "Paulesti" },
  { nume: "Holbăneşti", simplu: "Holbanesti", comuna: "Fitionesti" },
  { nume: "Homocea" },
  { nume: "Hotaru", comuna: "Andreiasu De Jos" },
  { nume: "Igeşti", simplu: "Igesti", comuna: "Tifesti" },
  { nume: "Ireşti", simplu: "Iresti", comuna: "Vidra" },
  { nume: "Iugani", comuna: "Boghesti" },
  { nume: "Ivănceşti", simplu: "Ivancesti", comuna: "Bolotesti" },
  { nume: "Izvoarele", comuna: "Corbita" },
  { nume: "Jariştea", simplu: "Jaristea" },
  { nume: "Jgheaburi", comuna: "Reghiu" },
  { nume: "Jilişte", simplu: "Jiliste", comuna: "Slobozia Ciorasti" },
  { nume: "Jitia de Jos", comuna: "Jitia" },
  { nume: "Jitia" },
  { nume: "Jorăşti", simplu: "Jorasti", comuna: "Vanatori" },
  { nume: "Lacu lui Baban", comuna: "Gura Calitei" },
  { nume: "Lămoteşti", simplu: "Lamotesti", comuna: "Milcovul" },
  { nume: "Lărgăşeni", simplu: "Largaseni", comuna: "Corbita" },
  { nume: "Lăstuni", simplu: "Lastuni", comuna: "Dumitresti" },
  { nume: "Lepşa", simplu: "Lepsa", comuna: "Tulnici" },
  { nume: "Lespezi", comuna: "Homocea" },
  { nume: "Lieşti", simplu: "Liesti", comuna: "Slobozia Bradului" },
  { nume: "Livada", comuna: "Mera" },
  { nume: "Livezile", comuna: "Vizantea-Livezi" },
  { nume: "Lojniţa", simplu: "Lojnita", comuna: "Chiojdeni" },
  { nume: "Luncile", comuna: "Chiojdeni" },
  { nume: "Lupoaia", comuna: "Dumitresti" },
  { nume: "Măgura", simplu: "Magura", comuna: "Jitia" },
  { nume: "Mahriu", comuna: "Poiana Cristei" },
  { nume: "Măicăneşti", simplu: "Maicanesti" },
  { nume: "Maluri", comuna: "Vulturu" },
  { nume: "Mănăstioara", simplu: "Manastioara", comuna: "Fitionesti" },
  { nume: "Mândreşti-Moldova", simplu: "Mandresti-Moldova", comuna: "Focsani" },
  { nume: "Mândreşti-Munteni", simplu: "Mandresti-Munteni", comuna: "Focsani" },
  { nume: "Mărăcini", simplu: "Maracini", comuna: "Chiojdeni" },
  { nume: "Mărăşeşti", simplu: "Marasesti" },
  { nume: "Mărăşti", simplu: "Marasti", comuna: "Racoasa" },
  { nume: "Mărtineşti", simplu: "Martinesti", comuna: "Tataranu" },
  { nume: "Mătăcina", simplu: "Matacina", comuna: "Valea Sarii" },
  { nume: "Mera" },
  { nume: "Mesteacănu", simplu: "Mesteacanu", comuna: "Vizantea-Livezi" },
  { nume: "Mihălceni", simplu: "Mihalceni", comuna: "Ciorasti" },
  { nume: "Milcovel", comuna: "Mera" },
  { nume: "Milcovul" },
  { nume: "Mirceştii Noi", simplu: "Mircestii Noi", comuna: "Vanatori" },
  { nume: "Mirceştii Vechi", simplu: "Mircestii Vechi", comuna: "Vanatori" },
  { nume: "Modruzeni", comuna: "Marasesti" },
  { nume: "Morăreşti", simplu: "Moraresti", comuna: "Paltin" },
  { nume: "Motnău", simplu: "Motnau", comuna: "Dumitresti" },
  { nume: "Moviliţa", simplu: "Movilita" },
  { nume: "Muncei", comuna: "Vrancioaia" },
  { nume: "Muncelu", comuna: "Straoane" },
  { nume: "Năneşti", simplu: "Nanesti" },
  { nume: "Năneşti", simplu: "Nanesti", comuna: "Tanasoaia" },
  { nume: "Năruja", simplu: "Naruja" },
  { nume: "Neculele", comuna: "Vintileasca" },
  { nume: "Negrileşti", simplu: "Negrilesti" },
  { nume: "Neicu", comuna: "Panciu" },
  { nume: "Nereju Mic", comuna: "Nereju" },
  { nume: "Nereju" },
  { nume: "Nistoreşti", simplu: "Nistoresti" },
  { nume: "Obrejiţa", simplu: "Obrejita", comuna: "Tamboesti" },
  { nume: "Ocheşeşti", simplu: "Ochesesti", comuna: "Corbita" },
  { nume: "Odobasca", comuna: "Poiana Cristei" },
  { nume: "Odobeşti", simplu: "Odobesti" },
  { nume: "Olăreni", simplu: "Olareni", comuna: "Slobozia Bradului" },
  { nume: "Oleşeşti", simplu: "Olesesti", comuna: "Tifesti" },
  { nume: "Olteni", comuna: "Vartescoiu" },
  { nume: "Oreavu", comuna: "Gugesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Jaristea" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Marasesti" },
  { nume: "Pădureni", simplu: "Padureni", comuna: "Tamboesti" },
  { nume: "Paltin" },
  { nume: "Panciu" },
  { nume: "Pătrăşcani", simplu: "Patrascani", comuna: "Tifesti" },
  { nume: "Păuleşti", simplu: "Paulesti" },
  { nume: "Păuneşti", simplu: "Paunesti" },
  { nume: "Păvălari", simplu: "Pavalari", comuna: "Paltin" },
  { nume: "Petreanu", comuna: "Poiana Cristei" },
  { nume: "Petreşti", simplu: "Petresti", comuna: "Vanatori" },
  { nume: "Pietroasa", comuna: "Bolotesti" },
  { nume: "Pietroasa", comuna: "Campineanca" },
  { nume: "Pietroasa", comuna: "Tamboesti" },
  { nume: "Pietroasa", comuna: "Vartescoiu" },
  { nume: "Piscu Radului", comuna: "Vizantea-Livezi" },
  { nume: "Piscu Reghiului", comuna: "Reghiu" },
  { nume: "Pituluşa", simplu: "Pitulusa", comuna: "Brosteni" },
  { nume: "Plăcinţeni", simplu: "Placinteni", comuna: "Boghesti" },
  { nume: "Pleşeşti", simplu: "Plesesti", comuna: "Boghesti" },
  { nume: "Plopu", comuna: "Gura Calitei" },
  { nume: "Ploscuţeni", simplu: "Ploscuteni" },
  { nume: "Ploştina", simplu: "Plostina", comuna: "Vrancioaia" },
  { nume: "Podu Lacului", comuna: "Poiana Cristei" },
  { nume: "Podu Nărujei", simplu: "Podu Narujei", comuna: "Naruja" },
  { nume: "Podu Şchiopului", simplu: "Podu Schiopului", comuna: "Nistoresti" },
  { nume: "Podu Stoica", comuna: "Naruja" },
  { nume: "Poduri", comuna: "Valea Sarii" },
  { nume: "Podurile", comuna: "Chiojdeni" },
  { nume: "Poenile", comuna: "Gura Calitei" },
  { nume: "Poiana Cristei" },
  { nume: "Poiana Stoichii", comuna: "Vintileasca" },
  { nume: "Poiana", comuna: "Vrancioaia" },
  { nume: "Poieniţa", simplu: "Poienita", comuna: "Dumitresti" },
  { nume: "Popeşti", simplu: "Popesti" },
  { nume: "Prahuda", comuna: "Paltin" },
  { nume: "Precistanu", comuna: "Garoafa" },
  { nume: "Prisaca", comuna: "Valea Sarii" },
  { nume: "Prisecani", comuna: "Boghesti" },
  { nume: "Pufeşti", simplu: "Pufesti" },
  { nume: "Putna", comuna: "Bolotesti" },
  { nume: "Răchitaşu", simplu: "Rachitasu", comuna: "Andreiasu De Jos" },
  { nume: "Răchitosu", simplu: "Rachitosu", comuna: "Garoafa" },
  { nume: "Răcoasa", simplu: "Racoasa" },
  { nume: "Rădăcineşti", simplu: "Radacinesti", comuna: "Corbita" },
  { nume: "Răduleşti", simplu: "Radulesti", comuna: "Vanatori" },
  { nume: "Răiuţi", simplu: "Raiuti", comuna: "Reghiu" },
  { nume: "Râmniceanca", simplu: "Ramniceanca", comuna: "Vartescoiu" },
  { nume: "Râmniceni", simplu: "Ramniceni", comuna: "Maicanesti" },
  { nume: "Raşca", simplu: "Rasca", comuna: "Gura Calitei" },
  { nume: "Răstoaca", simplu: "Rastoaca", comuna: "Milcovul" },
  { nume: "Rebegari", comuna: "Naruja" },
  { nume: "Reghiu" },
  { nume: "Repedea", comuna: "Straoane" },
  { nume: "Romăneşti", simplu: "Romanesti", comuna: "Nistoresti" },
  { nume: "Roşcari", simplu: "Roscari", comuna: "Dumitresti" },
  { nume: "Roşioara", simplu: "Rosioara", comuna: "Mera" },
  { nume: "Rotileştii Mari", simplu: "Rotilestii Mari", comuna: "Campuri" },
  { nume: "Rotileştii Mici", simplu: "Rotilestii Mici", comuna: "Campuri" },
  { nume: "Rucăreni", simplu: "Rucareni", comuna: "Soveja" },
  { nume: "Ruget", comuna: "Vidra" },
  { nume: "Rugineşti", simplu: "Ruginesti" },
  { nume: "Sahastru", comuna: "Nereju" },
  { nume: "Salcia Nouă", simplu: "Salcia Noua", comuna: "Ciorasti" },
  { nume: "Salcia Veche", comuna: "Ciorasti" },
  { nume: "Sârbi", simplu: "Sarbi", comuna: "Tifesti" },
  { nume: "Satu Nou", comuna: "Ciorasti" },
  { nume: "Satu Nou", comuna: "Panciu" },
  { nume: "Scafari", comuna: "Vidra" },
  { nume: "Scânteia", simplu: "Scanteia", comuna: "Jaristea" },
  { nume: "Seciu", comuna: "Chiojdeni" },
  { nume: "Şerbăneşti", simplu: "Serbanesti", comuna: "Corbita" },
  { nume: "Şerbeşti", simplu: "Serbesti", comuna: "Vidra" },
  { nume: "Sihlea" },
  { nume: "Siminoc", comuna: "Dumitresti" },
  { nume: "Şindrilari", simplu: "Sindrilari", comuna: "Reghiu" },
  { nume: "Siretu", comuna: "Marasesti" },
  { nume: "Şişcani", simplu: "Siscani", comuna: "Adjud" },
  { nume: "Slimnic", comuna: "Tamboesti" },
  {
    nume: "Slobozia Boteşti",
    simplu: "Slobozia Botesti",
    comuna: "Maicanesti",
  },
  { nume: "Slobozia Bradului" },
  { nume: "Slobozia Ciorăşti", simplu: "Slobozia Ciorasti" },
  { nume: "Şotârcari", simplu: "Sotarcari", comuna: "Gura Calitei" },
  { nume: "Spătăreasa", simplu: "Spatareasa", comuna: "Ciorasti" },
  { nume: "Spineşti", simplu: "Spinesti", comuna: "Vrancioaia" },
  { nume: "Spulber", comuna: "Paltin" },
  { nume: "Străjescu", simplu: "Strajescu", comuna: "Garoafa" },
  { nume: "Străoane", simplu: "Straoane" },
  { nume: "Stupina", comuna: "Maicanesti" },
  { nume: "Suraia" },
  { nume: "Tăbuceşti", simplu: "Tabucesti", comuna: "Boghesti" },
  { nume: "Tâmboeşti", simplu: "Tamboesti" },
  { nume: "Tănăsari", simplu: "Tanasari", comuna: "Vintileasca" },
  { nume: "Tănăsoaia", simplu: "Tanasoaia" },
  { nume: "Târâtu", simplu: "Taratu", comuna: "Poiana Cristei" },
  { nume: "Tătăranu", simplu: "Tataranu" },
  { nume: "Tătaru", simplu: "Tataru", comuna: "Maicanesti" },
  { nume: "Ţepa", simplu: "Tepa", comuna: "Paltin" },
  { nume: "Tercheşti", simplu: "Terchesti", comuna: "Popesti" },
  { nume: "Tichiriş", simplu: "Tichiris", comuna: "Vidra" },
  { nume: "Ţifeşti", simplu: "Tifesti" },
  { nume: "Tinoasa", comuna: "Dumitresti" },
  { nume: "Ţipău", simplu: "Tipau", comuna: "Paltin" },
  { nume: "Tişiţa", simplu: "Tisita", comuna: "Marasesti" },
  { nume: "Titila", comuna: "Andreiasu De Jos" },
  { nume: "Tojanii de Jos", comuna: "Paltin" },
  { nume: "Tojanii de Sus", comuna: "Paltin" },
  { nume: "Topeşti", simplu: "Topesti", comuna: "Barsesti" },
  { nume: "Trestia", comuna: "Dumitresti" },
  { nume: "Trestieni", comuna: "Tamboesti" },
  { nume: "Trotuşanu", simplu: "Trotusanu", comuna: "Movilita" },
  { nume: "Tulburea", comuna: "Chiojdeni" },
  { nume: "Tulnici" },
  { nume: "Tuţu", simplu: "Tutu", comuna: "Corbita" },
  { nume: "Ungureni", comuna: "Nistoresti" },
  { nume: "Unirea", comuna: "Odobesti" },
  { nume: "Urecheşti", simplu: "Urechesti" },
  { nume: "Ursoaia", comuna: "Reghiu" },
  { nume: "Vadu Roşca", simplu: "Vadu Rosca", comuna: "Vulturu" },
  { nume: "Vâjâitoarea", simplu: "Vajaitoarea", comuna: "Tataranu" },
  { nume: "Vâlcani", simplu: "Valcani", comuna: "Paltin" },
  { nume: "Vâlcele", simplu: "Valcele", comuna: "Campineanca" },
  { nume: "Vâlcelele", simplu: "Valcelele", comuna: "Corbita" },
  { nume: "Valea Beciului", comuna: "Slobozia Bradului" },
  { nume: "Valea Coteşti", simplu: "Valea Cotesti", comuna: "Cotesti" },
  { nume: "Valea Mică", simplu: "Valea Mica", comuna: "Dumitresti" },
  { nume: "Valea Milcovului", comuna: "Reghiu" },
  { nume: "Valea Neagră", simplu: "Valea Neagra", comuna: "Nistoresti" },
  { nume: "Valea Sării", simplu: "Valea Sarii" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Movilita" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Ruginesti" },
  { nume: "Văleni", simplu: "Valeni", comuna: "Straoane" },
  { nume: "Vânători", simplu: "Vanatori" },
  { nume: "Varniţa", simplu: "Varnita", comuna: "Racoasa" },
  { nume: "Vărsătura", simplu: "Varsatura", comuna: "Jaristea" },
  { nume: "Vârteşcoiu", simplu: "Vartescoiu" },
  { nume: "Verdea", comuna: "Racoasa" },
  {
    nume: "Vetreşti-Herăstrău",
    simplu: "Vetresti-Herastrau",
    comuna: "Nistoresti",
  },
  { nume: "Vidra" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Paunesti" },
  { nume: "Viişoara", simplu: "Viisoara", comuna: "Vidra" },
  { nume: "Vintileasca" },
  { nume: "Vităneşti", simplu: "Vitanesti", comuna: "Tifesti" },
  {
    nume: "Vităneştii de Sub Măgură",
    simplu: "Vitanestii de Sub Magura",
    comuna: "Bolotesti",
  },
  {
    nume: "Vizantea Mănăstirească",
    simplu: "Vizantea Manastireasca",
    comuna: "Vizantea-Livezi",
  },
  {
    nume: "Vizantea Răzăşească",
    simplu: "Vizantea Razaseasca",
    comuna: "Vizantea-Livezi",
  },
  { nume: "Vladnicu de Jos", comuna: "Tanasoaia" },
  { nume: "Vladnicu de Sus", comuna: "Tanasoaia" },
  { nume: "Voetin", comuna: "Sihlea" },
  { nume: "Voloşcani", simplu: "Voloscani", comuna: "Vidra" },
  { nume: "Vrâncioaia", simplu: "Vrancioaia" },
  { nume: "Vulcăneasa", simplu: "Vulcaneasa", comuna: "Mera" },
  { nume: "Vulturu" },
];
